<?php 

include_once "../../../config/settings.inc.php";
define("IEM_APPID", 92);
include_once "../../../include/myview.php";
include_once "../../../include/forms.php";
include_once "../../../include/vtec.php";
include_once "../../../include/imagemaps.php";
include_once "../../../include/database.inc.php";
$mesosite = iemdb("mesosite");
$formhtml = "";
$image = "";
$t = new MyView();
$t->thispage = "current-plotter";
$t->title = "Automated Data Plotter";
$t->headextra = <<<EOF
 <link rel="stylesheet" href="https://code.jquery.com/ui/1.10.3/themes/smoothness/jquery-ui.css" />
EOF;


$q = isset($_GET["q"]) ? intval($_GET["q"]) : 0;
$network = isset($_GET["network"]) ? $_GET["network"]: "IACLIMATE";
$state = isset($_GET["state"]) ? $_GET["state"]: "IA";
$lmw = isset($_GET['_l']) ? "$('#_l').click();\n": '';

// Available Plots
$data = file_get_contents("http://iem.local/plotting/auto/meta/0.json");
$jobj = json_decode($data);
$pselect = "<select name=\"q\">";
while (list($k,$v) = each($jobj->plots)){
	$pselect .= sprintf("<optgroup label=\"%s\">", $v->label);
	while (list($k2,$v2) = each($v->options)){
		$mwonly = (isset($v2->mw)) ? ' data-mw="true"': '';
		$pselect .= sprintf("<option value=\"%s\"%s%s>%s</option>", $v2->id,
			($v2->id == $q) ? ' selected="selected"': '', $mwonly, $v2->label);
	}
	$pselect .= "</optgroup>";
}
$pselect .= "</select>";

$states = Array(
	'IA' => 'Iowa',
    'IL' => 'Illinois',
    'KS' => 'Kansas',
	'KY' => 'Kentucky',
	'MI' => 'Michigan',
    'MN' => 'Minnesota',
    'MO' => 'Missouri',
    'NE' => 'Nebraska',
    'ND' => 'North Dakota',
    'OH' => 'Ohio',
    'SD' => 'South Dakota',
    'WI' => 'Wisconsin',
);

$jsextra = "";
$networks = Array();
$description = null;

if (isset($_GET["q"])){
	$q = intval($_GET["q"]);
	$data = file_get_contents("http://iem.local/plotting/auto/meta/$q.json");
	$jobj = json_decode($data);
	$description = isset($jobj->description) ? $jobj->description: null;
	$imguri = "/plotting/auto/plot/$q/";
	$pltvars = Array();
	$form = "";
	while (list($k,$v) = each($jobj->arguments)){
		$value = isset($_GET[$v->name]) ? $_GET[$v->name] : $v->default;
		$pltvars[] = sprintf("%s:%s", $v->name, $value);
		// BEGIN generation of interfaces based on types
		if ($v->type == "zstation"){
			// Build out listing of networks, if we have not already
			if (sizeof($networks) == 0){
				$rs = pg_query($mesosite, "SELECT id, name from networks 
						where id ~* 'ASOS' or id = 'AWOS' ORDER by name ASC");
				for ($i=0;$row=@pg_fetch_assoc($rs,$i);$i++){
					$networks[$row["id"]] = $row["name"];
				}
			}
			// Assume if we have zstation, then we don't have multiple stations
			if ($v->name == "zstation1"){
				$networkcgi = "network1";
			}else if ($v->name == "zstation2"){
				$networkcgi = "network2";
			}else {
				$networkcgi = "network";
			}
			$defaultnetwork = isset($v->network) ? $v->network : "IA_ASOS"; 
			$network = isset($_GET[$networkcgi]) ? $_GET[$networkcgi]: $defaultnetwork;
			$netselect = make_select($networkcgi, $network, $networks, "onNetworkChange");
			$form .= "<tr><td>". $v->label ."</td><td>". $netselect ." ". 
				networkSelect($network, $value, Array(), $v->name) ."</td></tr>";
			$pltvars[] = sprintf("%s:%s", $networkcgi, $network);
		}
		elseif ($v->type == "ugc"){
			$stateselect = stateSelect($state, "onNetworkChange");
			$form .= "<tr><td>". $v->label ."</td><td>". $stateselect ." ". ugcStateSelect($state, $value) ."</td></tr>";
			$pltvars[] = sprintf("%s:%s", "state", $state);
		}
		elseif ($v->type == "station"){
			if (sizeof($networks) == 0){
				$networks = Array("ILCLIMATE" => "Illinois",
						"INCLIMATE" => "Indiana",
						"IACLIMATE" => "Iowa",
						"KSCLIMATE" => "Kansas",
						"KYCLIMATE" => "Kentucky",
						"MICLIMATE" => "Michigan",
						"MNCLIMATE" => "Minnesota",
						"MOCLIMATE" => "Missouri",
						"NECLIMATE" => "Nebraska",
						"NDCLIMATE" => "North Dakota",
						"OHCLIMATE" => "Ohio",
						"SDCLIMATE" => "South Dakota",
						"WICLIMATE" => "Wisconsin"
				);
			}
			$netselect = make_select("network", $network, $networks, "onNetworkChange");
			$form .= "<tr><td>". $v->label ."</td><td>". $netselect ." ". networkSelect($network, $value) ."</td></tr>";
			$pltvars[] = sprintf("%s:%s", "network", $network);
		}
		elseif ($v->type == "networkselect"){
			$extra = Array();
			if (isset($v->all)){
				$extra["_ALL"] = Array('name'=>' -- All Sites --');
			}
			$netselect = networkSelect($v->network, $value, $extra, "station");
			$form .= "<tr><td>". $v->label ."</td><td>". $netselect  ."</td></tr>";
			$pltvars[] = sprintf("%s:%s", "network", $network);
		}
		elseif ($v->type == "phenomena"){
			$netselect = vtecPhenoSelect($value);
			$form .= "<tr><td>". $v->label ."</td><td>". $netselect ."</td></tr>";
		}
		elseif ($v->type == "significance"){
			$netselect = vtecSigSelect($value);
			$form .= "<tr><td>". $v->label ."</td><td>". $netselect ."</td></tr>";
		}
		elseif ($v->type == "state"){
			$netselect = stateSelect($value);
			$form .= "<tr><td>". $v->label ."</td><td>". $netselect ."</td></tr>";
		}
		elseif ($v->type == "clstate"){
			$netselect = make_select($v->name, $value, $states);
			$form .= "<tr><td>". $v->label ."</td><td>". $netselect ."</td></tr>";
		}
		elseif ($v->type == "text"){
			$form .= "<tr><td>". $v->label ."</td>
			<td><input value=\"$value\" type=\"text\" name=\"". $v->name ."\"></td></tr>" ;
		}
		elseif ($v->type == "month"){
			$form .= "<tr><td>". $v->label ."</td>
			<td>". monthSelect2( $value, $v->name) ."</td></tr>" ;
		}
		elseif ($v->type == "zhour"){
			$form .= "<tr><td>". $v->label ."</td>
			<td>". gmtHourSelect( $value, $v->name) ."</td></tr>" ;
		}
		elseif ($v->type == "hour"){
			$form .= "<tr><td>". $v->label ."</td>
			<td>". hourSelect( $value, $v->name) ."</td></tr>" ;
		}
		elseif ($v->type == "day"){
			$form .= "<tr><td>". $v->label ."</td>
			<td>". daySelect( $value, $v->name) ."</td></tr>" ;
		}
		elseif ($v->type == "year"){
			$form .= "<tr><td>". $v->label ."</td>
			<td>". yearSelect2(isset($v->min) ? $v->min: 1893, $value, $v->name) ."</td></tr>" ;
		}
		elseif ($v->type == "select"){
			$netselect = make_select($v->name, $value, $v->options);
			$form .= "<tr><td>". $v->label ."</td><td>". $netselect ."</td></tr>";
		}
		elseif ($v->type == "date"){
			$dpname = "datepicker_". $v->name;
			$jsextra .= <<<EOF
$( "#{$dpname}" ).datepicker({
	changeMonth: true,
	changeYear: true,
		dateFormat : "yy/mm/dd",
		minDate    : new Date("{$v->min}")});
$("#{$dpname}").datepicker('setDate', new Date("{$value}"));
	
EOF;
			$form .= "<tr><td>". $v->label ."</td>"
					."<td><input type=\"text\" name=\"". $v->name 
					."\" id=\"{$dpname}\" /> (YYYY/mm/dd)</td></tr>";
		}
	}
	$imguri .= str_replace('/', '-', implode($pltvars, "::"));
	if (isset($_GET["_wait"]) && $_GET["_wait"] == 'yes'){
		$image = "";
	} else{
		$image = <<<EOF
	<p><span class="glyphicon glyphicon-arrow-down"></span> A graph will appear below this text with your specifications from above:<br >
	<img src="{$imguri}.png" class="img img-responsive" />
EOF;
	}
	$lmwoption = (isset($_GET['_l'])) ? '<input type="hidden" name="_l" value="on">': '';
	$formhtml = <<<EOF
<script>
function onNetworkChange(newnetwork){
    $("#_wait").val("yes");
	$('form#myForm').submit();
}
</script>
	<h4><span class="glyphicon glyphicon-arrow-right"></span> Second, select specific chart options::</h4>
	<form method="GET" name="s" id="myForm">
	<input type="hidden" name="_wait" value="no" id="_wait">
	<input type="hidden" name="q" value="{$q}">
	{$lmwoption}
	<table class="table table-striped">
		<thead><tr><th>Description</th><th>Value</th></tr></thead>
	$form
	</table>		
	<input type="submit" value="Make Plot with Options" />
</form>
EOF;
}

$dhtml = "";
if ($description != null){
	$dhtml = sprintf("<div class=\"alert alert-info\"><h4>Plot Description:</h4>%s</div>", $description);
}
$dataextra= "";
if (isset($jobj->data)){
	$dataextra = "<p><a href=\"{$imguri}.csv\" class=\"btn btn-default\"><i class=\"glyphicon glyphicon-pencil\"></i> View Data (as csv)</a></p>";
}

$t->content = <<<EOF
<h3>Automated Data Plotter</h3>

<p>This application dynamically generates many types of graphs.  These graphs
are derived from raw observations collected by the IEM.</p>

<br /><form method="GET" name="t">
<div class="form-group">
<h4><span class="glyphicon glyphicon-arrow-right"></span> First, select a chart type::</h4>
 <input type="checkbox" name="_l" id="_l">Only show options that also work outside Midwest US<br />
{$pselect}
<input type="submit" value="Select Plot Type" />
</div>
</form>

<hr />


 $formhtml


<hr />

$dhtml

$image

$dataextra
		
<div class="alert alert-info"><span class="glyphicon glyphicon-info-sign"></span>
		If you notice plotting issues with the image above, please 
		do <a class="alert-link" href="/info/contacts.php">let us know</a> by providing the 
		URL address currently shown by your web browser.</div>

EOF;
$t->jsextra = <<<EOF
<script src="https://code.jquery.com/ui/1.10.3/jquery-ui.js"></script>
<script>
$(document).ready(function(){
{$jsextra}

	$('#_l').change(function(){
		if($(this).is(":checked")) {
			$('select option[data-mw="true"]').addClass('hidden');
		} else {
			$('select option[data-mw="true"]').removeClass('hidden');
		}
	});
		{$lmw}
});
</script>
EOF;
$t->render('single.phtml');


?>