<?php
/* AJAX AFOS Retreiver */
include("../../../config/settings.inc.php");

$HEADEXTRA = '<link rel="stylesheet" type="text/css" href="../../ext/resources/css/ext-all.css"/>
<script type="text/javascript" src="../../ext/adapter/ext/ext-base.js"></script>
<script type="text/javascript" src="../../ext/ext-all.js"></script>
<script type="text/javascript" src="wfos.js"></script>
<script type="text/javascript" src="static.js"></script>';
$TITLE = "IEM NWS Text Product Finder";
$NOCONTENT = 1;
include("$rootpath/include/header.php");
?>
<!--
<style type="text/css">
    html, body {
        margin:0;
        padding:0;
        border:0 none;
        overflow:hidden;
        height:100%;
    }
</style>
<div id="header">
 <a href="<?php echo $rooturl; ?>/"><img src="<?php echo $rooturl; ?>/images/logo_small.gif" alt="IEM" style="float:left;"/></a><div style="font:normal 16px tahoma, arial, helvetica, sans-serif; margin: 10px;">IEM 2.0 :: NWS Text Product Finder</div>
</div>
-->
<div id="help"><p>How can I help you?</p></div>

<?php include("$rootpath/include/footer.php"); ?>
