<?php
// AJAX AFOS Retreiver
require_once "../../../config/settings.inc.php";
define("IEM_APPID", 59);
require_once "../../../include/myview.php";
$t = new MyView();

$t->headextra = <<<EOF
<link rel="stylesheet" href="/vendor/jquery-ui/1.11.4/jquery-ui.min.css" />
<link rel="stylesheet" href="static.css" />
EOF;
$t->jsextra = <<<EOM
<script type="text/javascript" src="/vendor/js-cookie/2.1.4/js.cookie.min.js"></script>
<script src="/vendor/jquery-ui/1.11.4/jquery-ui.js"></script>
<script type="text/javascript" src="static.js?v=13"></script>
EOM;
$t->title = "NWS Text Product Finder";
$t->thispage ="current-afos";

$helpdiv = <<<EOM
<h3>IEM NWS Text Product Finder</h3>

<p>Update 15 May 2019: If you specify a three character PIL, you will get
any PIL matches that start with those three characters.  You can optionally
specify a WMO Header (TTAAII) to reduce PIL ambiguity.</p>

<p>Update 19 Jan 2012: Added the ability to limit a AFOS PIL by the issuing
center ID (4 character).  For example, the AFOS pil RWRTX is issued by a 
number of centers in Texas.  To only get RWRTX from Fort Worth, enter KFWD
for the center.

<br />&nbsp;
<p>If you don't like this app, <a href="old.phtml">here is the old one</a>.</p>
<br />&nbsp;
<p>This application provides a nice interface into viewing National Weather
Service issued text products.  Once you select a product, a cookie is 
set on your computer so that when you visit this page the next time, the
same products will appear!</p>
<br />&nbsp;
<p>Using our local <a href="http://www.unidata.ucar.edu/projects/idd/index.html">UNIDATA IDD</a>
 data feed, a simple script archives <b>recent</b> NWS text products into a database.  The above form allows
you to query this database for recent products.  You must know 
the AFOS PIL / AWIPS ID in order to 
get the products you want.</p>

<div style="float: left; margin: 5px; padding: 5px; border: 1px dashed; background: #eeeeee;">
<b>MOS PILS</b>
<pre>
PIL       Description             Product ID for Des Moines
ECMxxx    ECMWF Guidance M         ECMDSM
ECSxxx    ECMWF Guidance S         ECSDSM
ECXxxx    ECMWF Guidance X         ECXDSM
MAVxxx    GFS MOS Guidance         MAVDSM
METxxx    NAM MOS Guidance         METDSM
MEXxxx    GFSX MOS Guidance        MEXDSM
NBExxx    National Blend E         NBEDSM
NBHxxx    National Blend H         NBHDSM
NBPxxx    National Blend P         NBPDSM
NBSxxx    National Blend S         NBSDSM
NBXxxx    National Blend X         NBXDSM

And model output

FRHxx     Eta Output               FRH68
FRHTxx    NGM Output               FRHT68
</pre>

<b>Other Favorites:</b>
<pre>
REPNT2  NHC Vortex Message
PMDHMD  Model Diagnostic Discussion
PMDSPD  Short Range Prognostic Discussion
PMDEPD  Extended Forecast Discussion
SWOMCD  SPC Mesoscale Discussion
SWODY1  SPC Day 1
SWODY2  SPC Day 2
AFDDMX  Des Moines WFO Area Forecast Discussion
SELX    Convective Watch where "X" is a number between 0-9
</pre>
</div>

<br />&nbsp;
<p>The archive maintains products from at least the most recent 7 days.  A daily scrubber 
runs at 3:30 AM each day to reindex the products and delete old products, so the query 
interface is off-line at that time. This interruption should only last 10 minutes.</p>

<br />&nbsp;
<p>Please do not depend on this page for operational decision making, errors can and do occur
with data processing, data reception and any other error possible with Internet communications.
All products should be used for educational purposes only.</p>

<p>
<ul>
 <li><a href="http://www.nws.noaa.gov/datamgmt/x_ref/xr04_X_ref_by_NNN.xlsx">NNN Categories</a></li>
</ul>
</p>
EOM;
$theform = <<<EOM
<form name="control" id="myform">

<p><label for="pil">3-6 Character PIL</label>
<br /><i>Specify 4-6 characters for exact match</i> 
<br /><input placeholder="AFDDMX" type="text" name="pil" maxlength="6" size="10"></p>

<p><label for="center">4 Character Center</label>
<br /><i>Can be left blank</i>
<br /><input placeholder="KDMX" type="text" name="center" maxlength="4" size="6"></p>

<p><label for="ttaaii">6 Char WMO Header</label>
<br /><i>Can be left blank</i>
<br /><input placeholder="FXUS63" type="text" name="ttaaii" maxlength="6" size="6"></p>

<p><label for="limit">Date Descending Entries</label>
<br /><input type="text" name="limit" maxlength="4" size="6" value="1"></p>

<p><label for="sdate">Start Date</label>
<br /><input id="sdate" type="text" name="sdate" value="No Limit"></p>

<p><label for="edate">End Date</label>
<br /><input id="edate" type="text" name="edate" value="No Limit"></p>

<p><button type="button" id="myform-submit" class="btn btn-default"><i class="fa fa-search"></i> Load Product</button></p>

</form>
EOM;
$t->content = <<<EOF

<div class="clearfix">&nbsp;</div>

<div class="row">
  <div class="col-md-3 well">
    {$theform}
  </div><!-- ./col-md-3 -->
  <div class="col-md-9">

<div class="panel with-nav-tabs panel-default" id="thetabs">
    <div class="panel-heading">
      <ul class="nav nav-tabs">
         <li class="active"><a href="#help" data-toggle="tab">Help</a></li>
      </ul>
    </div><!-- ./panel-heading -->
    <div class="panel-body">
    <div id="thetabs-toolbar">
        <button type="button" id="toolbar-refresh" class="btn btn-default"><i class="fa fa-refresh"></i> Refresh</button>
        <button type="button" id="toolbar-download" class="btn btn-default"><i class="fa fa-download"></i> Download Text</button>
        <button type="button" id="toolbar-print" class="btn btn-default"><i class="fa fa-print"></i> Send Text to Printer</button>
        <button type="button" id="toolbar-close" class="btn btn-default"><i class="fa fa-close"></i> Close Tab</button>
    </div>
     <div class="tab-content clearfix">

       <div class="tab-pane active" id="help">
        {$helpdiv}
       </div><!-- ./help -->
    </div><!-- ./tab-content -->
    </div><!-- ./panel-body -->
  </div><!-- ./col-md-9 -->
</div><!-- ./row -->

EOF;
$t->render('full.phtml');
?>
