<?php
/*
 * Create lists of links to archived AFOS products based on what the user wants
 */
require_once "../../../config/settings.inc.php";
define("IEM_APPID", 48);
require_once "../../../include/forms.php";
require_once "../../../include/database.inc.php";
require_once "../../../include/imagemaps.php";
require_once "../../../include/myview.php";
require_once "../../../include/network.php";

$afos = iemdb("afos");
$t = new MyView();
$t->title = "NWS Text Product by Issuing Center by Date";
$t->thispage ="archive-afos";
$t->headextra = <<<EOF
 <link rel="stylesheet" type="text/css" href="/vendor/select2/4.0.3/select2.min.css"/ >
EOF;
$t->jsextra = <<<EOF
<script src="/vendor/select2/4.0.3/select2.min.js"></script>
<script>
$(document).ready(function(){
    //disabled for now due to accessible issues
    //https://github.com/select2/select2/issues/3744
    //$(".iemselect2").select2();
});

function showHide(v){
	var d2 = document.getElementById("d2");
	if (document.getElementById("drange").checked){
		d2.style.display = "block";
	} else{
		d2.style.display = "none";
	}
}
function j(name){
	$('html,body').animate({
		scrollTop: $("#sect"+name).offset().top
	 });
}
</script>
EOF;
 
$wfo = isset($_REQUEST["wfo"])? xssafe($_REQUEST["wfo"]): null;
$source = isset($_REQUEST["source"])? substr($_GET["source"],0,4) : 'DMX';
$dbsource = $source;
$sesource = $source;
if (strlen($source) == 3){ $dbsource = "K$source";}
if ((strlen($source) == 4) && (substr($source, 0, 1) == 'K')) { $sesource = substr($source, 1, 3); }
if ($wfo != null){ $source = $wfo; }

$view = isset($_GET["view"])? xssafe($_GET["view"]): 'grid';
$year = isset($_GET["year"])? intval($_GET["year"]) : date("Y");
$month = isset($_GET["month"])? intval($_GET["month"]) : date("m");
$day = isset($_GET["day"])? intval($_GET["day"]) : date("d");
$year2 = isset($_GET["year2"])? intval($_GET["year2"]) : date("Y");
$month2 = isset($_GET["month2"])? intval($_GET["month2"]) : date("m");
$day2 = isset($_GET["day2"])? intval($_GET["day2"]) : date("d");
$order = isset($_GET["order"]) ? xssafe($_GET["order"]): "asc";
$ts = mktime(0,0,0, $month, $day, $year);
$ts2 = $ts + 86400;
$d2display = "none";

if (isset($_REQUEST['drange'])){
	$ts2 = mktime(0,0,0, $month2, $day2, $year2) + 86400;
	$d2display = "block";
}

$ar = Array("asc" => "Time Ascending",
		"desc" => "Time Descending");
if (!array_key_exists($order,$ar)){ $order = 'asc'; }
$oselect = make_select("order", $order, $ar);

$table = "";
$atags = "";
pg_query($afos, "SET TIME ZONE 'UTC'");
$rs = pg_prepare($afos, "_SELECT",
	"SELECT pil, entered from products ".
	"WHERE source = $1 and entered BETWEEN $2 and $3 and ".
	"pil is not null ORDER by entered $order");

$rs = pg_execute($afos, "_SELECT", Array($dbsource, date("Y-m-d H:i", $ts)."+00",
		date("Y-m-d H:i", $ts2)."+00"));
if ($view == "prod"){
	$prods = Array();
	for($i=0;$row=pg_fetch_array($rs);$i++){
		$ts = strtotime($row["entered"]);
		$url = sprintf("p.php?pil=%s&e=%s", $row["pil"], gmdate("YmdHi", $ts));
		@$prods[$row["pil"]] .= sprintf("<tr><td><a href=\"%s\">%s</a></td>
    	<td>%s</td><td>%s</td></tr>",
				$url, $row["pil"], gmdate("Y-m-d", $ts), gmdate("H:i", $ts));
	}
	$keys = array_keys($prods);
	asort($keys);
	$table .= "<table class=\"table table-condensed table-striped\"><tr><th>Product Link</th><th>Date</th><th>UTC Time</th></tr>";
	foreach($keys as $i => $k){
		$table .= sprintf("%s", $prods[$k]);
	}
	$table .= "</table>";
} else if ($view == "grid"){
	$columns = Array();
	for($i=0;$row=pg_fetch_array($rs);$i++){
		$ts = strtotime($row["entered"]);
		$url = sprintf("p.php?pil=%s&e=%s", $row["pil"], gmdate("YmdHi", $ts));
		@$columns[$row["pil"]] .= sprintf("<a href=\"%s\">%s</a> (%s)<br />",
				$url, $row["pil"], gmdate("H:i", $ts));
	}
	$keys = array_keys($columns);
	asort($keys);
	$table = "";
	$atags .= '<div class="clearfix"></div><strong>Skip to PIL:</strong> ';
	foreach($keys as $i => $k){
		$atags .= sprintf("<a class=\"btn btn-default btn-sm\" href=\"javascript:void(0)\" onclick=\"j('%s');\">%s</a> ",
		                  $k, $k);
		if ($i % 6 == 0){
			if ($i > 0){
				$table .= "</div>";
			}
			$table .= "<div class=\"row\">\n";
		}
		$table .= sprintf("<div id=\"sect$k\" class=\"col-lg-1 col-md-2 col-sm-2 col-xs-4 well\">%s</div>\n",
		                  $columns[$k]);
	}
	$table .= "</div>\n";
	$atags .= '<div class="clearfix"></div>';
} else {
	//view=time
	$lasthour = "";
	$colnum = 0;
	$atags .= '<div class="clearfix"></div><strong>Skip to Hour:</strong> ';
	for($i=0;$row=pg_fetch_array($rs);$i++){
		$ts = strtotime($row["entered"]);
		$url = sprintf("p.php?pil=%s&e=%s", $row["pil"], gmdate("YmdHi", $ts));
		if (gmdate("H", $ts) != $lasthour){
			if ($lasthour != ""){
				// End previous col-
				$table .= "</div>\n";
			}
			$lasthour = gmdate("H", $ts);
			$atags .= sprintf("<a class=\"btn btn-default btn-sm\" href=\"javascript:void(0)\" onclick=\"j('%s');\">%s</a> ",
                                  $lasthour, $lasthour);
			if ($colnum % 6 == 0){
				if ($colnum > 0){
					// End previous row + container
					$table .= "</div></div>";
				}
				$table .= "<div class=\"container\"><div class=\"row\">\n";
			}
			$table .= "<div id=\"sect$lasthour\" class=\"col-lg-1 col-md-2 col-sm-2 col-xs-4 well\">";
			$table .= sprintf("<strong>%s UTC</strong><br />", gmdate('d M Y : H', $ts));
		    $colnum += 1;
		}
		$table .= sprintf("<a href=\"%s\">%s</a> (%s)<br />", $url, $row["pil"],
				gmdate("H:i", $ts));
	}
	$table .= "</div></div>\n";
    $atags .= '<div class="clearfix"></div>';
}

$drangecheck = (isset($_REQUEST["drange"]))? "checked='checked'" : "";
$groups = Array("WFO", "RFC", "NWS", "NCEP", "CWSU", "WSO");
$groupnames = Array("Weather Forecast Offices (WFO)",
		"River Forecast Centers (RFC)",
		"NWS Admin Organizations",
		"NCEP Centers",
		"Center Weather Service Units (CWSU)",
		"Weather Service Offices (WSO)");
$sources = Array();
foreach($groups as $key => $s){
	$sources[$groupnames[$key]] = Array();
	$nt = new NetworkTable($s);
	foreach ($nt->table as $sid => $tbl)
	{
		$sources[$groupnames[$key]][$sid] = sprintf("[%s] %s", $sid,
				$tbl['name']);
	}
}
$netselect = make_select("source", $sesource, $sources, $jscallback="", $cssclass="form-control");

$yselect = yearSelect(1993, $year);
$mselect = monthSelect($month);
$dselect = daySelect($day);
$y2select = yearSelect2(1993, $year2, "year2");
$m2select = monthSelect($month2, "month2");
$d2select = daySelect2($day2, "day2");

$ar = Array("time" => "Chronological",
	"grid" => "PIL Grid",
	"prod" => "Product List");
$vselect = make_select("view", $view, $ar);


$t->content = <<<EOF
<h3>NWS Text Products by Issuing Center by Date</h3>
<p>This application prints out a listing of IEM archived text products
by issuing NWS Issuing Center and by date.  After about
seven days, the IEM purges a lot of the frequently issued products like
SHEF and METAR data. Please be patient with this page if you select a 
range of dates.</p>

<p><strong>Archive Completeness:</strong>
<ul>
 <li><strong>1993 thru 1995</strong>: Extremely sparse and random pockets of
 data.  If you find data, please feel lucky!</li>
 <li><strong>1996 thru 2001</strong>: Sometimes sparse / missing data.
 Also note that product source IDs
 are likely different back then (prior to NWS Modernization), some work was
 done to assign present day WMO source IDs to the product metadata stored in
 the database. The original text as not modified.  Known holes
 exist at: 29 Oct-1 Nov 1998, 24-27 Dec 1998, 25-28 Jul 1999, 21-25 Jan 2000,
 26-27 Mar 2000, 12-13 Jun 2001, 28-29 Jul 2001.</li>
 <li><strong>2002 thru 2007</strong>: More consistent archives, but still likely
 missing things.  Much better coverage though.</li>
 <li><strong>2008 thru now</strong>: Very good data coverage and higher fidelity
 archiving.</li>
 </ul>
</p>

<form name="selector" method="GET">
<div class="row well">
<div class="col-md-5">
  <strong>Select Issuing Center:</strong>
  <br />{$netselect}
</div>
<div class="col-md-3">
  <strong>For UTC Date:</strong>
  <br />{$yselect} {$mselect} {$dselect}
  <br /><input id="drange" type="checkbox" name="drange" value="yes" 
  onClick="showHide(this.value)" {$drangecheck}/>Enable Search over date range
  <br /><div id="d2" style="display: {$d2display}">
  {$y2select} {$m2select} {$d2select}</div>
</div>

<div class="col-md-4">
  <strong>Options:</strong>
  <br />How to view: {$vselect}
  <br />Sort order: {$oselect}
  <br /><input type="submit" value="Giveme Giveme!">
</div>

</div>
</form>
{$atags}

{$table}

EOF;

$t->render('full.phtml');

?>
