<?php
/*
 * Create lists of links to archived AFOS products based on what the user wants
 */
require_once "../../../config/settings.inc.php";
define("IEM_APPID", 48);
require_once "../../../include/forms.php";
require_once "../../../include/imagemaps.php";
require_once "../../../include/myview.php";
require_once "../../../include/network.php";
require_once "../../../include/mlib.php";

$t = new MyView();
$t->title = "NWS Text Product by Issuing Center by Date";
$t->headextra = <<<EOF
 <link rel="stylesheet" type="text/css" href="/vendor/select2/4.0.3/select2.min.css"/ >
<style>
.col-md-2 {
    overflow-y: scroll;
    overflow-x: hidden;
    max-height: 350px;

}
</style>
EOF;
$t->jsextra = <<<EOF
<script src="/vendor/select2/4.0.3/select2.min.js"></script>
<script>
$(document).ready(function(){
    $(".iemselect2").select2();
});

function showHide(v){
	var d2 = document.getElementById("d2");
	if (document.getElementById("drange").checked){
		d2.style.display = "block";
	} else{
		d2.style.display = "none";
	}
}
function j(name){
	$('html,body').animate({
		scrollTop: $("#sect"+name).offset().top
	 });
}
</script>
EOF;

// A dance here to get a 4-char and 3-char identifier
$source = isset($_REQUEST["source"])? substr($_GET["source"],0,4) : 'DMX';
$cccc = $source;
$sesource = $source;
if (strlen($source) == 3){
    $cccc = "K$source";
}
if ((strlen($source) == 4) && (substr($source, 0, 1) == 'K')) {
    $sesource = substr($source, 1, 3);
}

$view = isset($_GET["view"])? xssafe($_GET["view"]): 'grid';
$order = isset($_GET["order"]) ? xssafe($_GET["order"]): "asc";

$year = get_int404("year", date("Y"));
$month = get_int404("month", date("m"));
$day = get_int404("day", date("d"));
$year2 = get_int404("year2", date("Y"));
$month2 = get_int404("month2", date("m"));
$day2 = get_int404("day2", date("d"));

// Belt-suspenders check here
$dt = new DateTime("$year-$month-$day");
$datequeue = Array($dt->format("Y-m-d"));

$d2display = "none";

$timeformat = "H:i";
if (isset($_REQUEST['drange'])){
    $dt2 = new Datetime("$year2-$month2-$day2");
    // Enforce the 10 day limit on range
    if ($dt2->diff($dt)->days > 10){
        $dt2 = $dt->add(new DateInterval("P10D"));
        $year2 = $dt2->format("Y");
        $month2 = $dt2->format("m");
        $day2 = $dt2->format("d");
    }

    // Loop through all the days in the range from $dt to $dt2
    while (($dt <= $dt2) && sizeof($datequeue) < 10){
        $datequeue[] = $dt->format("Y-m-d");
        $dt->modify("+1 day");
    }
	$d2display = "block";
    $timeformat = "d/H:i";
}

$ar = Array("asc" => "Time Ascending",
		"desc" => "Time Descending");
if (!array_key_exists($order,$ar)){ $order = 'asc'; }
$oselect = make_select("order", $order, $ar);

$table = "";
$atags = "";

// Loop over dates in the datequeue
$prods = Array();
$columns = Array();
foreach($datequeue as $dt){
    $res = iemws_json(
        "nws/afos/list.json",
        Array("cccc" => $cccc, "date" => $dt),
    );
    $rows = $res["data"];
    if ($order == "desc"){
        $rows = array_reverse($rows);
    }
    if (sizeof($rows) == 0){
        $table .= "<h3>No products found for $dt</h3>\n";
        continue;
    }

    if ($view == "prod"){
        foreach($rows as $row){
            $ts = strtotime($row["entered"]);
            $url = sprintf("p.php?pil=%s&e=%s", $row["pil"], gmdate("YmdHi", $ts));
            if (!array_key_exists($row["pil"], $prods)){
                $prods[$row["pil"]] = "";
            }
            $prods[$row["pil"]] .= sprintf(
                "<tr><td><a href=\"%s\">%s</a></td><td>%s</td><td>%s</td></tr>",
                $url, $row["pil"], gmdate("Y-m-d", $ts), gmdate("H:i", $ts)
            );        
        }
    } else if ($view == "grid") {
        foreach($rows as $row){
            $ts = strtotime($row["entered"]);
            $url = sprintf("p.php?pil=%s&e=%s", $row["pil"], gmdate("YmdHi", $ts));
            if (!array_key_exists($row["pil"], $columns)){
                $columns[$row["pil"]] = "";
            }
            $columns[$row["pil"]] .= sprintf("<a href=\"%s\">%s</a> (%s)<br />",
                    $url, $row["pil"], gmdate($timeformat, $ts));    
        }    

    } else {
        $lasthour = "";
        $colnum = 0;
        $atags .= '<div class="clearfix"></div><strong>Skip to Hour:</strong> ';
        foreach($rows as $row){
            $ts = strtotime($row["entered"]);
            $url = sprintf("p.php?pil=%s&e=%s", $row["pil"], gmdate("YmdHi", $ts));
            if (gmdate("H", $ts) != $lasthour){
                if ($lasthour != ""){
                    // End previous col-
                    $table .= "</div>\n";
                }
                $lasthour = gmdate("H", $ts);
                $atags .= sprintf("<a class=\"btn btn-default btn-sm\" href=\"javascript:void(0)\" onclick=\"j('%s');\">%s</a> ",
                                      $lasthour, $lasthour);
                if ($colnum % 6 == 0){
                    if ($colnum > 0){
                        // End previous row + container
                        $table .= "</div></div>";
                    }
                    $table .= "<div class=\"container\"><div class=\"row\">\n";
                }
                $table .= "<div id=\"sect$lasthour\" class=\"col-lg-2 col-md-2 col-sm-2 col-xs-4 well\">";
                $table .= sprintf("<strong>%s UTC</strong><br />", gmdate('d M Y : H', $ts));
                $colnum += 1;
            }
            $table .= sprintf("<a href=\"%s\">%s</a> (%s)<br />", $url, $row["pil"],
                    gmdate("H:i", $ts));    
        }
        $table .= "</div></div>\n";
        $atags .= '<div class="clearfix"></div>';
    }
}
if ($view == "prod"){
    $keys = array_keys($prods);
    asort($keys);
    $table .= "<table class=\"table table-condensed table-striped\"><tr><th>Product Link</th><th>Date</th><th>UTC Time</th></tr>";
    foreach($keys as $i => $k){
        $table .= sprintf("%s", $prods[$k]);
    }
    $table .= "</table>";
} else if ($view == "grid") {
    ksort($columns);
    $keys = array_keys($columns);
    $table = "";
    $atags .= '<div class="clearfix"></div><strong>Skip to PIL:</strong> ';
    foreach($keys as $i => $k){
        $atags .= sprintf("<a class=\"btn btn-default btn-sm\" href=\"javascript:void(0)\" onclick=\"j('%s');\">%s</a> ",
                          $k, $k);
        if ($i % 6 == 0){
            if ($i > 0){
                $table .= "</div>";
            }
            $table .= "<div class=\"row\">\n";
        }
        $table .= sprintf("<div id=\"sect$k\" class=\"col-lg-2 col-md-2 col-sm-2 col-xs-4 well\">%s</div>\n",
                          $columns[$k]);
    }
    $table .= "</div>\n";
    $atags .= '<div class="clearfix"></div>';
}

$drangecheck = (isset($_REQUEST["drange"]))? "checked='checked'" : "";
$groups = Array("WFO", "RFC", "NWS", "NCEP", "CWSU", "WSO");
$groupnames = Array(
    "Weather Forecast Offices (WFO)",
    "River Forecast Centers (RFC)",
    "NWS Admin Organizations",
    "NCEP Centers",
    "Center Weather Service Units (CWSU)",
    "Weather Service Offices (WSO)",
);
$sources = Array();
foreach($groups as $key => $s){
	$sources[$groupnames[$key]] = Array();
	$nt = new NetworkTable($s);
	foreach ($nt->table as $sid => $tbl)
	{
		$sources[$groupnames[$key]][$sid] = sprintf("[%s] %s", $sid,
				$tbl['name']);
	}
}
$netselect = make_select(
    "source",
    $sesource,
    $sources,
    $jscallback="",
    $cssclass="form-control iemselect2");

$yselect = yearSelect(1983, $year);
$mselect = monthSelect($month);
$dselect = daySelect($day);
$y2select = yearSelect2(1993, $year2, "year2");
$m2select = monthSelect($month2, "month2");
$d2select = daySelect2($day2, "day2");

$ar = Array("time" => "Chronological",
	"grid" => "PIL Grid",
	"prod" => "Product List");
$vselect = make_select("view", $view, $ar);


$t->content = <<<EOM
<h3>NWS Text Products by Issuing Center by Date</h3>
<p>This application prints out a listing of IEM archived text products
by issuing NWS Issuing Center and by date.  After about
seven days, the IEM purges a lot of the frequently issued products like
SHEF and METAR data. Please be patient with this page if you select a 
range of dates.</p>

<p>See this <a href="/onsite/news.phtml?id=1408">news item</a> for more details
on this archive and sources used.  You can also find a listing of 
<a href="https://forecast.weather.gov/product_types.php?site=NWS">three character PILs</a>
and a brief associated product name on the NWS website.</p>

<p><strong>Archive Completeness:</strong>
<ul>
 <li><strong>1983 thru 2001</strong>: Sometimes sparse / missing data.
 Also note that product source IDs
 are likely different back then (prior to NWS Modernization), some work was
 done to assign present day WMO source IDs to the product metadata stored in
 the database. The original text was not modified. To find text from a now
 closed WSO from the period, try using the present day WFO center that covers
 the location.</li>
 <li><strong>2002 thru 2007</strong>: More consistent archives, but still likely
 missing things.  Much better coverage though.</li>
 <li><strong>2008 thru now</strong>: Very good data coverage and higher fidelity
 archiving.</li>
 </ul>
</p>

<p>This data presentation is powered by a <a href="/api/1/docs#/nws/service_nws_afos_list__fmt__get">IEM API Web Service</a>.</p>

<form name="selector" method="GET">
<div class="row well">
<div class="col-md-5">
  <strong>Select Issuing Center:</strong>
  <br />{$netselect}
</div>
<div class="col-md-5">
  <strong>For UTC Date:</strong>
  <br />{$yselect} {$mselect} {$dselect}
  <br /><input id="drange" type="checkbox" name="drange" value="yes" id="drange" 
  onClick="showHide(this.value)" {$drangecheck}/>
  <label for="drange">List over UTC date range through (max 10 days)</label>
  <br /><div id="d2" style="display: {$d2display}">
  {$y2select} {$m2select} {$d2select}</div>
</div>

<div class="col-md-2">
  <strong>Options:</strong>
  <br />How to view: {$vselect}
  <br />Sort order: {$oselect}
  <br /><input type="submit" value="Giveme Giveme!">
</div>

</div>
</form>
{$atags}

{$table}

EOM;

$t->render('full.phtml');
