
Ext.namespace('iemdata');

iemdata.nws_products = [
 ['ADA','ADA Alert Administrative Msg'],
 ['ADR','ADR NWS Aministrative Msg'],
 ['ADM','ADM Alert Aministrative Msg'],
 ['AFD','AFD Area Forecast Discussion'],
 ['AFM','AFM Area Forecast Matrices'],
 ['AFP','AFP Area Forecast Product'],
 ['AQA','AQA Air Quality Advisory'],
 ['AVA','AVA Avalanche Watch'],
 ['AVW','AVA Avalanche Warning'],
 ['AWS','AWS Area Weather Summary'],
 ['AWU','AWU Area Weather Update'],
 ['CAE','CAE Child Abduction Emergency'],
 ['CCF','CCF Coded City Forecast'],
 ['CDW','CDW Civil Danger Warning'],
 ['CEM','CEM Civil Emergency Message'],
 ['CF6','CF6 Daily Climate Webpage'],
 ['CFW','CFW Coastal Flood Warning'],
 ['CWF','CWF Coastal Waters Forecast'],
 ['DGT','DGT Drought Information Statement'],
 ['EQW','EQW Earthquake Warning'],
 ['ESF','ESF Flood Potential Outlook'],
 ['EWW','EEW Extreme Wind Warning'],
 ['FFA','FFA Flash Flood Watch'],
 ['FFG','FFG Flash Flood Guidance'],
 ['FFS','FFS Flash Flood Statement'],
 ['FFW','FFW Flash Flood Warning'],
 ['FLS','FLS Flood Statement'],
 ['FLW','FLW Flood Warning'],
 ['FRW','FRW Fire Warning'],
 ['FTM','FTM Free Text Message'],
 ['FWW','FWW Fire Weather Watch'],
 ['HLS','HLS Hurricane Local Statement'],
 ['HMD','HMD Hydrometerological Discussion'],
 ['HMW','HMW Hazardous Materials Warning'],
 ['HWO','HWO Hazardous Weather Outlook'],
 ['LAE','LAE Local Area Emergency'],
 ['LSR','LSR Local Storm Report'],
 ['MWS','MWS Marine Weather Statement'],
 ['MWW','MWW Marine Weather Warning'],
 ['NOW','NOW Short Term Forecast'],
 ['NPW','NPW Non-Precip Watch Warning'],
 ['PFM','PFM Point Forecast Matrices'],
 ['PNS','PNS Public Information Statement'],
 ['RER','RER Record Event Report'],
 ['RFW','RFW Red Flag Warning'],
 ['RR1','RR1 Misc HydroMet SHEF'],
 ['RR2','RR2 Misc HydroMet SHEF'],
 ['RR3','RR3 Misc HydroMet SHEF'],
 ['RR4','RR4 Misc HydroMet SHEF'],
 ['RR5','RR5 Misc HydroMet SHEF'],
 ['RR6','RR6 Misc HydroMet SHEF'],
 ['RRM','RRM Misc HydroMet SHEF'],
 ['RRS','RRS Special HydroMet SHEF'],
 ['RVA','RVA River Summary'],
 ['RVD','RVD Daily River Forecast'],
 ['RVF','RVF River Forecast'],
 ['RVS','RVS River Statement'],
 ['RWR','RWR Regional Weather Roundup'],
 ['RWS','RWS Regional Weather Summary'],
 ['RZF','RZF Regional Zone Forecast'],
 ['SFT','SFT Tabular State Forecast'],
 ['SMW','SMW Special Marine Warning'],
 ['SPS','SPS Special Weather Statement'],
 ['SRF','SRF Surf Forecast'],
 ['STO','STO State Road Conditions'],
 ['STP','STP State Max/Min/Precip Table'],
 ['SVR','SVR Severe Thunderstorm Warning'],
 ['SVS','SVS Severe Weather Statement'],
 ['TAF','TAF Terminal Aerodome Forecast'],
 ['TOE','TOE Telephone Outage Emergency'],
 ['TOR','TOR Tornado Warning'],
 ['TWB','TWB Transcribed Weather Broadcast'],
 ['TWD','TWD Tropical Weather Discussion'],
 ['TWO','TWO Tropical Weather Outlook'],
 ['WCN','WCN Watch Clearance Notification'],
 ['WSW','WSW Winter Weather Warnings'],
 ['ZFP','ZFP Zone Forecast Product']
];

iemdata.wfos = [
 ['ABQ','ALBUQUERQUE'],
 ['ABR','ABERDEEN'],
 ['AFC','ANCHORAGE'],
 ['AFG','FAIRBANKS'],
 ['AJK','JUNEAU'],
 ['AKQ','WAKEFIELD'],
 ['ALY','ALBANY'],
 ['AMA','AMARILLO'],
 ['APX','GAYLORD'],
 ['ARX','LA_CROSSE'],
 ['BGM','BINGHAMTON'],
 ['BIS','BISMARCK'],
 ['BMX','BIRMINGHAM'],
 ['BOI','BOISE'],
 ['BOU','DENVER'],
 ['BOX','TAUNTON'],
 ['BRO','BROWNSVILLE'],
 ['BTV','BURLINGTON'],
 ['BUF','BUFFALO'],
 ['BYZ','BILLINGS'],
 ['CAE','COLUMBIA'],
 ['CAR','CARIBOU'],
 ['CHS','CHARLESTON'],
 ['CLE','CLEVELAND'],
 ['CRP','CORPUS_CHRISTI'],
 ['CTP','STATE_COLLEGE'],
 ['CYS','CHEYENNE'],
 ['DDC','DODGE_CITY'],
 ['DLH','DULUTH'],
 ['DMX','DES_MOINES'],
 ['DTX','DETROIT'],
 ['DVN','QUAD_CITIES_IA'],
 ['EAX','KANSAS_CITY/PLEASANT_HILL'],
 ['EKA','EUREKA'],
 ['EPZ','EL_PASO_TX/SANTA_TERESA'],
 ['EWX','AUSTIN/SAN_ANTONIO'],
 ['EYW','KEY_WEST'],
 ['FFC','PEACHTREE_CITY'],
 ['FGF','EASTERN_NORTH_DAKOTA'],
 ['FGZ','FLAGSTAFF'],
 ['FSD','SIOUX_FALLS'],
 ['FWD','DALLAS/FORT_WORTH'],
 ['GGW','GLASGOW'],
 ['GID','HASTINGS'],
 ['GJT','GRAND_JUNCTION'],
 ['GLD','GOODLAND'],
 ['GRB','GREEN_BAY'],
 ['GRR','GRAND_RAPIDS'],
 ['GSP','GREENVILLE/SPARTANBURG'],
 ['GYX','GRAY'],
 ['HFO','HONOLULU'],
 ['HGX','HOUSTON/GALVESTON'],
 ['HNX','SAN_JOAQUIN_VALLEY/HANFORD'],
 ['ICT','WICHITA'],
 ['ILM','WILMINGTON'],
 ['ILN','WILMINGTON'],
 ['ILX','LINCOLN'],
 ['IND','INDIANAPOLIS'],
 ['IWX','NORTHERN_INDIANA'],
 ['JAN','JACKSON'],
 ['JAX','JACKSONVILLE'],
 ['JKL','JACKSON'],
 ['LBF','NORTH_PLATTE'],
 ['LCH','LAKE_CHARLES'],
 ['LIX','NEW_ORLEANS'],
 ['LKN','ELKO'],
 ['LMK','LOUISVILLE'],
 ['LOT','CHICAGO'],
 ['LOX','LOS_ANGELES/OXNARD'],
 ['LSX','ST_LOUIS'],
 ['LUB','LUBBOCK'],
 ['LWX','BALTIMORE_MD/_WASHINGTON_DC'],
 ['LZK','LITTLE_ROCK'],
 ['MAF','MIDLAND/ODESSA'],
 ['MEG','MEMPHIS'],
 ['MFL','MIAMI'],
 ['MFR','MEDFORD'],
 ['MHX','NEWPORT/MOREHEAD_CITY'],
 ['MKX','MILWAUKEE/SULLIVAN'],
 ['MLB','MELBOURNE'],
 ['MOB','MOBILE'],
 ['MPX','TWIN_CITIES/CHANHASSEN'],
 ['MQT','MARQUETTE'],
 ['MRX','MORRISTOWN'],
 ['MSO','MISSOULA'],
 ['MTR','SAN_FRANCISCO'],
 ['OAX','OMAHA/VALLEY'],
 ['OHX','NASHVILLE'],
 ['OKX','NEW_YORK'],
 ['OTX','SPOKANE'],
 ['OUN','NORMAN'],
 ['PAH','PADUCAH'],
 ['PBZ','PITTSBURGH'],
 ['PDT','PENDLETON'],
 ['PHI','MOUNT_HOLLY'],
 ['PIH','POCATELLO/IDAHO_FALLS'],
 ['PQR','PORTLAND'],
 ['PSR','PHOENIX'],
 ['PUB','PUEBLO'],
 ['RAH','RALEIGH'],
 ['REV','RENO'],
 ['RIW','RIVERTON'],
 ['RLX','CHARLESTON'],
 ['RNK','BLACKSBURG'],
 ['SEW','SEATTLE'],
 ['SGF','SPRINGFIELD'],
 ['SGX','SAN_DIEGO'],
 ['SHV','SHREVEPORT'],
 ['SJT','SAN_ANGELO'],
 ['SJU','SAN_JUAN'],
 ['SLC','SALT_LAKE_CITY'],
 ['STO','SACRAMENTO'],
 ['TAE','TALLAHASSEE'],
 ['TBW','TAMPA_BAY_AREA/RUSKIN'],
 ['TFX','GREAT_FALLS'],
 ['TOP','TOPEKA'],
 ['TSA','TULSA'],
 ['TWC','TUCSON'],
 ['UNR','RAPID_CITY'],
 ['VEF','LAS_VEGAS']
];
