<?php
 require_once "../../../config/settings.inc.php";
 require_once "../../../include/myview.php";
 $t = new MyView();

 $t->content = <<<EOF

<h3>Accessing "for public" chat rooms</h3>

<p>In order to keep efficient communications and quality information, the
chatrooms hosted on the <a href="https://nwschat.weather.gov">NWSChat server</a>
 are closed to the general public.

<p>One of the neat features that makes this setup interesting, is that "iembot"
messages are placed in these chatrooms.  Anybody can use this setup to
monitor what the "bot" is saying.  iembot is a process that automatically 
routes NWS text products to WFO specific chatrooms.

<p>Jason Patton, a meteorology student at Iowa State, has written up a 
configuration page for accessing the chatrooms.
<br /><b><a href="http://meteor.geol.iastate.edu/~jpatton/jabber/">How to join a WFO chatroom</a></b>.

<h4>Please note:</h4>
<ul>
  <li>These chatrooms do not contain the information shared on the IEM Chat 
     chat servers.</li>
  <li>These chatrooms do not contain NWS users or media users.  Most of the
     users are probably weather enthusiasts or perhaps chasers.</li>
  <li>No claims of accuracy or warranties with this.  Use at your own risk!</li>
  <li>You can not access these chatrooms with your iemchat.com Jabber account.
    You will need to setup another jabber account to use with this service.</li>
</ul>

EOF;
$t->render('single.phtml');
?>