<?php 
require_once "../../../config/settings.inc.php";
define("IEM_APPID", 24);
require_once "../../../include/forms.php";
require_once "../../../include/myview.php";
$t = new MyView();
$t->title = "ISU AMS Station #2 on Agronomy";
if (! isset($_GET["year"])){
    $t->refresh = 60;
}

$year = isset($_GET["year"]) ? intval($_GET["year"]): date("Y");
$month = isset($_GET["month"]) ? intval($_GET["month"]): date("m");
$day = isset($_GET["day"]) ? intval($_GET["day"]): date("d");
$myTime = mktime(0,0,0,$month, $day, $year);

$dirRef = date("Y/m/d", $myTime);
$dataurl = "/archive/data/$dirRef/text/ot/ot0010.dat";

$station = "isumet";

$ys = yearSelect2(2011, $year, "year");
$ms = monthSelect2($month, "month");
$ds = daySelect2($day, "day");
$ymd = sprintf("year=%s&month=%s&day=%s", $year, $month, $day);

$t->content = <<< EOF
<ol class="breadcrumb">
 <li><a href="/other/">Miscellaneous Stations</a></li>
 <li class="active">ISU AMS Station</li>	
</ol>

<p>You can plot 1 minute data for this location.  Note that 
the archive <br> begins 8 Sep 2011.</p>


  <form method="GET" action="ams2.phtml">
{$ys} {$ms} {$ds}

  <input type="submit" value="Make Plot"></form>

<a href="{$dataurl}">View raw data file</a><br />
<BR>
<img src="1min.php?station=ot0010&{$ymd}" ALT="Time Series">
<BR>
<img src="1min_inside.php?station=ot0010&{$ymd}" ALT="Time Series">
<br />
<img src="rh.php?station=ot0010&{$ymd}" ALT="Time Series">
<br />
<img src="srad.php?station=ot0010&{$ymd}" ALT="Time Series">
<BR>
<img src="1min_V.php?station=ot0010&{$ymd}" ALT="Time Series">
<BR>
<img src="1min_P.php?station=ot0010&{$ymd}" ALT="Time Series">
<br />
<img src="1min.php?station=ot0010&{$ymd}&rh" ALT="Time Series">
</div>
EOF;

$t->render("single.phtml");
