<?php 
include("../../../config/settings.inc.php");
define("IEM_APPID", 24);

include("../../../include/myview.php");
$t = new MyView();
$t->title = "ISU AMS Station #2 on Agronomy";

$year = isset($_GET["year"]) ? $_GET["year"] : date("Y");
$month = isset($_GET["month"]) ? $_GET["month"] : date("m");
$day = isset($_GET["day"]) ? $_GET["day"] : date("d");
$myTime = mktime(0,0,0,$month, $day, $year);

$dirRef = strftime("%Y/%m/%d", $myTime);
$dataurl = "http://mesonet.agron.iastate.edu/archive/data/$dirRef/text/ot/ot0010.dat";

include("../../../include/forms.php");   $station = "isumet";

$content = <<< EOF

<p>You can plot 1 minute data for this location.  Note that 
the archive <br> begins 8 Sep 2011.</p>

<table>
<tr class="even"><td>


  <form method="GET" action="ams2.phtml">
EOF;
$content .= yearSelect2(2011, $year, "year"); 
$content .= monthSelect2($month, "month"); 
$content .= daySelect2($day, "day"); 

$ymd = sprintf("year=%s&month=%s&day=%s", $year, $month, $day);
$content .= <<<EOF
  <input type="submit" value="Make Plot"></form>

</td></tr><tr><td>
<a href="{$dataurl}">View raw data file</a><br />
<BR>
<img src="1min.php?station=ot0010&${ymd}" ALT="Time Series">
<BR>
<img src="1min_inside.php?station=ot0010&${ymd}" ALT="Time Series">
<br />
<img src="rh.php?station=ot0010&${ymd}" ALT="Time Series">
<br />
<img src="srad.php?station=ot0010&${ymd}" ALT="Time Series">
<BR>
<img src="1min_V.php?station=ot0010&${ymd}" ALT="Time Series">
<BR>
<img src="1min_P.php?station=ot0010&${ymd}" ALT="Time Series">
<br />
<img src="1min.php?station=ot0010&${ymd}&rh" ALT="Time Series">
</td></tr></table>
</div>
EOF;

$t->content = $content;
$t->render("single.phtml");
?>