<?php
include("../../config/settings.inc.php");
$network = isset($_GET['network']) ? $_GET['network'] : 'IA_RAWS';
$sortcol = isset($_GET["sortcol"]) ? $_GET["sortcol"] : 'station';
?>

<?php 
  $REFRESH = "<meta http-equiv=\"refresh\" content=\"300;
  URL=current.phtml?sortcol=<?php echo $sortcol; ?>&network=<?php echo $network;
  ?>\">";
  $HEADEXTRA = '<script language="JavaScript" type="text/javascript">
<!--//BEGIN Script
function new_window(url) {
 link = window.open(url,"_new","toolbar=0,location=0,directories=0,status=0,menubar=no,scrollbars=yes,resizable=yes,width=800,height=600");
} 
//END Script-->
</script>
<script type="text/javascript" src="/js/tableruler.js"></script>
<script type="text/javascript">
    window.onload=function(){tableruler();}
</script>';
  $TITLE = "IEM | RAWS | Current Conditions";
  include("$rootpath/include/header.php"); 
  include("$rootpath/include/mlib.php"); 
  include("$rootpath/include/iemaccess.php");
  include("$rootpath/include/iemaccessob.php");

  $iem = new IEMAccess();
  $awos = $iem->getNetwork($network);
?>
<div class="text">
<b>Nav:</b><a href="/RAWS/">RAWS</a> <b> > </b> Current Conditions

<?php $current_network = "RAWS"; include("../include/current_bar.inc.php"); ?>
<form method="GET" action="current.phtml" name="stctrl">
<select name="network">
  <option value="IA_RAWS" <?php if ($network == "IA_RAWS") echo "SELECTED"; ?>>Iowa
  <option value="IN_RAWS" <?php if ($network == "IN_RAWS") echo "SELECTED"; ?>>Indiana
  <option value="IL_RAWS" <?php if ($network == "IL_RAWS") echo "SELECTED"; ?>>Illinois
  <option value="KS_RAWS" <?php if ($network == "KS_RAWS") echo "SELECTED"; ?>>Kansas
  <option value="MI_RAWS" <?php if ($network == "MI_RAWS") echo "SELECTED"; ?>>Michigan
  <option value="MN_RAWS" <?php if ($network == "MN_RAWS") echo "SELECTED"; ?>>Minnesota
  <option value="MO_RAWS" <?php if ($network == "MO_RAWS") echo "SELECTED"; ?>>Missouri
  <option value="NE_RAWS" <?php if ($network == "NE_RAWS") echo "SELECTED"; ?>>Nebraska
  <option value="ND_RAWS" <?php if ($network == "ND_RAWS") echo "SELECTED"; ?>>North Dakota
  <option value="OH_RAWS" <?php if ($network == "OH_RAWS") echo "SELECTED"; ?>>Ohio
  <option value="SD_RAWS" <?php if ($network == "SD_RAWS") echo "SELECTED"; ?>>South Dakota
  <option value="WI_RAWS" <?php if ($network == "WI_RAWS") echo "SELECTED"; ?>>Wisconsin
</select>
<input type="submit" value="Show State">
</form><p>


<h3 class="subtitle"><center>Current RAWS Conditions</center></h3><p>

** This page will automatically refresh every five minutes.

<?php
$vals = Array("station" => "Station ID", "gmt_ts" => "Ob Time", 
"relh" => "Relative Humidity",
  "min_tmpf" => "Today's Low Temperature",
  "max_tmpf" => "Today's High Temperature",
"tmpf" => "Temperature", "dwpf" => "Dew Point", "vsby" => "Visibility",
"sknt" => "Speed", "max_sknt" => "Peak Gust [knots]","pres" => "Altimeter",
"gtim" => "Gust Time", "phour" => "1 hr Rainfall", "pday" => "Today Rainfall", "feel" => "Feels Like");

echo "<br>Sorted by: <b>(". $vals[$sortcol] .")</b>  &nbsp; &nbsp; Click on a column to sort it.<br>\n";


?>

<form method="POST" action="/my/current.php">

<table style="font-size: 10pt;" class="ruler">
<thead>
<tr>
  <th>ADD:</th>
  <th>Station:</th>
  <th><a href="current.phtml?network=<?php echo $network; ?>&sortcol=gmt_ts">Ob Time</a></th>
  <th>
   <a href="current.phtml?network=<?php echo $network; ?>&sortcol=tmpf">Temp</a>
   (<a href="current.phtml?network=<?php echo $network; ?>&sortcol=max_tmpf">Hi</a> /
   <a href="current.phtml?network=<?php echo $network; ?>&sortcol=min_tmpf">Lo</a>)
 </th>
  <th><a href="current.phtml?network=<?php echo $network; ?>&sortcol=dwpf">DewP</a></th>
  <th><a href="current.phtml?network=<?php echo $network; ?>&sortcol=feel">Feels</a></th>
  <th><a href="current.phtml?network=<?php echo $network; ?>&sortcol=relh">RH%</a></th>
  <th>Dir</th>
  <th><a href="current.phtml?network=<?php echo $network; ?>&sortcol=sknt">Speed</a></th>
  <th><a href="current.phtml?network=<?php echo $network; ?>&sortcol=max_sknt">Peak Gust</a>
   <br>@ <a href="current.phtml?network=<?php echo $network; ?>&sortcol=gtim">Time</a></th>
  <th><a href="current.phtml?network=<?php echo $network; ?>&sortcol=pday">Total Rainfall</a></th>
</tr></thead>
<tbody>
<?php
// http://www.php.net/manual/en/function.asort.php

function aSortBySecondIndex($multiArray, $secondIndex) {
	while (list($firstIndex, ) = each($multiArray))
		$indexMap[$firstIndex] = $multiArray[$firstIndex][$secondIndex];
	arsort($indexMap);
	while (list($firstIndex, ) = each($indexMap))
		if (is_numeric($firstIndex))
			$sortedArray[] = $multiArray[$firstIndex];
		else $sortedArray[$firstIndex] = $multiArray[$firstIndex];
	return $sortedArray;
}

  while (list($key, $iemob) = each($awos) ){
    $mydata[$key] = $iemob->db;
    $mydata[$key]["ts"] = $iemob->ts;
    $mydata[$key]["sped"] = $mydata[$key]["sknt"] * 1.15078;
    $mydata[$key]["relh"] = relh(f2c($mydata[$key]["tmpf"]),
       f2c($mydata[$key]["dwpf"]) );
    $mydata[$key]["feel"] = feels_like($mydata[$key]["tmpf"],
       $mydata[$key]["relh"], $mydata[$key]["sped"]);
    if ($mydata[$key]["max_gust"] > $mydata[$key]["max_sknt"]){
      $mydata[$key]["peak"] = $mydata[$key]["max_gust"];
      $mydata[$key]["peak_ts"] = strtotime(substr( $mydata[$key]["max_gust_ts"],0,16) );
    } else {
      $mydata[$key]["peak"] = $mydata[$key]["max_sknt"];
      $mydata[$key]["peak_ts"] = strtotime(substr( $mydata[$key]["max_sknt_ts"],0,16) );
    }
                                                                                
  }

 $finalA = Array();
 $finalA = aSortBySecondIndex($mydata, $sortcol);
 $now = time();
 while (list ($key, $val) = each ($finalA))  { 
	$parts = $finalA[$key];
        echo "<tr ";
        if ($shade) echo "bgcolor=\"#EEEEEE\"";
        echo ">\n 
         <td><input type=\"checkbox\" name=\"st[]\" 
            value=\"".$key."\"></td>";

         $tdiff = $now - $parts["ts"];
         echo "<td>". $parts["sname"] . "</td>";
         echo "<td ";
         if ($tdiff > 10000){
           echo 'bgcolor="red"';
           $format = "%d %b %I:%M %p";
         } else if ($tdiff > 7200){
           echo 'bgcolor="green"';
           $format = "%d %b %I:%M %p";
         } else {
           $format = "%I:%M %p";
         }
         echo ">" . strftime($format, $parts["ts"]) ."</td>
 <td align='center'>". round($parts["tmpf"],0) ."(<font color=\"#ff0000\">".
 round($parts["max_tmpf"],0) ."</font>/<font color=\"#0000ff\">".
 round($parts["min_tmpf"],0) ."</font>)</td>
          <td>". $parts["dwpf"] ."</td>
          <td>". $parts["feel"] ."</td>
          <td>". $parts["relh"] ."</td>
          <td>". $parts["drct"] ."</td>
          <td>". round($parts["sknt"],0) ;
          if (intval($parts["gust"]) > 0){
            echo "G". round($parts["gust"],0);
          } echo "</td>";
          echo "<td>". round($parts["peak"],0) ." @ ". strftime("%I:%M %p", $parts["peak_ts"]) ."</td>
          <td>". round($parts["pday"],2) ."</td></tr>\n";
      $shade = ! $shade;
}


?></tbody><tfoot>
<tr>
 <td colspan=3>&nbsp;</td>
<?php $c = "javascript:new_window('http://mesonet.agron.iastate.edu/GIS/apps/php/currents.phtml?layers[]=radar&layers[]=labels&network=$network&var="; ?>
 <td><a href="<?php echo $c; ?>tmpf');">Plot</a>
    (<a href="<?php echo $c; ?>max_tmpf');">Plot</a> /
     <a href="<?php echo $c; ?>min_tmpf');">Plot</a>)</td>
 <td><a href="<?php echo $c; ?>dwpf');">Plot</a></td>
 <td><a href="<?php echo $c; ?>feel');">Plot</a></td>
 <td><a href="<?php echo $c; ?>relh');">Plot</a></td>
 <td colspan=2><a href="<?php echo $c; ?>barb');">Plot</a></td>
 <td><a href="<?php echo $c; ?>max_sknt');">Plot</a></td>
 <td><a href="<?php echo $c; ?>pday');">Plot</a></td>
</tr></tfoot>
</table>

<input type="submit" value="Add to Favorites">
<input type="reset" value="Reset">

</form>


<br><br></div>

<?php include("$rootpath/include/footer.php"); ?>
