<?php
include("../../../../config/settings.inc.php");
include("$rootpath/include/database.inc.php");
$coopdb = iemdb("coop");
include("$rootpath/include/forms.php");
include("$rootpath/include/network.php");
$nt = new NetworkTable("IACLIMATE");
$cities = $nt->table;

$var = isset($_GET["var"]) ? $_GET["var"]: "gdd50";
$year = isset($_GET["year"]) ? $_GET["year"]: date("Y");
$smonth = isset($_GET["smonth"]) ? $_GET["smonth"]: 5;
$sday = isset($_GET["sday"]) ? $_GET["sday"]: 1;
$emonth = isset($_GET["emonth"]) ? $_GET["emonth"]: date("m");
$eday = isset($_GET["eday"]) ? $_GET["eday"]: date("d");

/** Need to use external date lib 
  * http://php.weblogs.com/adodb_date_time_library
  */
include("$rootpath/include/adodb-time.inc.php");

$sts = adodb_mktime(0,0,0,$smonth, $sday, $year);
$ets = adodb_mktime(0,0,0,$emonth, $eday, $year);

$imgurl = sprintf("gsplot.php?smonth=%s&sday=%s&var=%s&emonth=%s&eday=%s&year=%s",
  $smonth, $sday, $var, $emonth, $eday, $year);


$TITLE = "IEM | NWS COOP Growing Season Data";
$HEADEXTRA = '<script language="JavaScript" type="text/javascript">
<!--//BEGIN Script
function new_window(url) {
        link = 
        window.open(url,"_new","toolbar=0,location=0,directories=0,status=0,menubar=no,scrollbars=yes,resizable=yes,width=450,height=400");
} 
//END Script-->
</script>';
$THISPAGE="current-gs";
include("$rootpath/include/header.php"); ?>

<div class="text">

<p>With this application, you can total a parameter of your
choice over a duration of your choice.  The resulting data is presented 
graphically as well as textually for use in a GIS. 

<form method="GET" action="gsplot.phtml" name="theform">
<table>
 <tr>
  <th colspan=5><h3 class="subtitle">Growing Season Charts</h3></th></tr>
 <tr>
   <th>Select Parameter:</th>
   <th>Year</th>
   <th>Month</th>
   <th>Day</th>
   <td></td>
  </tr>
 <tr>
  <td rowspan=2><select name="var">
     <option value="gdd50" <?php if($var == "gdd50") echo "SELECTED"; ?>>Growing Degree Days (base=50)</option>
     <option value="prec" <?php if($var == "prec") echo "SELECTED"; ?>>Precipitation</option>
     <option value="sdd86" <?php if($var == "sdd86") echo "SELECTED"; ?>>Stress Degree Days (base=86)</option>
    </select></td>
  <td rowspan=2><?php echo yearselect(1893, $year); ?></td>
  <td><?php echo monthSelect2($smonth, 'smonth'); ?></td>
  <td><?php echo daySelect2($sday, 'sday'); ?></td>
  <td rowspan=2><input type="submit" value="Make Plot"></td>
  </tr>
 <tr>
  <td><?php echo monthSelect2($emonth, 'emonth'); ?></td>
  <td><?php echo daySelect2($eday, 'eday'); ?></td>
  </tr>
</table>
</form>

<?php

$tr = sprintf("# Iowa COOP Accumulations (%s - %s)\n", adodb_date("Y-m-d", $sts),
	adodb_date("Y-m-d", $ets) );
$tr .= "# Download From: http://mesonet.agron.iastate.edu/GIS/apps/coop/gsplot.phtml
# Download Date: ". strftime("%d %b %Y") ."
# CLIM_ values are based on climatology 1951-today
# Data Contact: Daryl Herzmann akrherz@iastate.edu 515.294.5978
#-----------------------snip------------------\n";



/* Query the obs */
$rs = pg_prepare($coopdb, "SELECT", "SELECT stationid, s_rainfall,
    s_gdd50, s_sdd86, c_rainfall, c_gdd50, c_sdd86 from (
      SELECT stationid, 
	  sum(precip) as s_rainfall, sum(gdd50(high,low)) as s_gdd50,
	  sum(sdd86(high,low)) as s_sdd86 from alldata 
	  WHERE day >= $1 and day < $2 GROUP by stationid) as foo,
	 (SELECT station, 
      sum(precip) as c_rainfall, sum(gdd50) as c_gdd50,
      sum(sdd86) as c_sdd86 from climate51 
      WHERE valid >= $3 and valid < $4 GROUP by station) as foo2
	WHERE foo2.station = foo.stationid ORDER by stationid ASC");
$rs = pg_execute($coopdb, "SELECT", Array(adodb_date("Y-m-d", $sts),
	adodb_date("Y-m-d", $ets), "2000-". adodb_date('m-d', $sts), 
	"2000-". adodb_date('m-d', $ets)));


$tr .= sprintf("%6s,%21s,%10s,%10s,%10s,%10s,%10s,%10s,%10s\n", 'ID', 
 'StationName', 'Latitude', 'Longitude', 'GDD50', 'SDD86', 'PRECIP',
 'CLIM_GDD50', 'CLIM_PRECIP');
for($i=0;$row=@pg_fetch_array($rs,$i);$i++){

  $ukey = strtoupper($row["stationid"]);
  if (! isset($cities[$ukey]) ) continue;
  $tr .= sprintf("%6s,%-21s,%10.4f,%10.4f,%10.0f,%10.0f,%10.2f,%10.0f,%10.2f\n", $ukey, 
  $cities[$ukey]['name'],
  $cities[$ukey]['lat'], $cities[$ukey]['lon'], 
  $row["s_gdd50"], $row["s_sdd86"], $row["s_rainfall"],
  $row["c_gdd50"], $row["c_rainfall"] );
}
?>

<p>*Note: Only a sub-sample of stations are plotted on the map due to 
space restrictions.
<br />
  <img src="<?php echo $imgurl; ?>" border=1 />
  </p>

<p>
<img src="<?php echo $rooturl; ?>/images/gisready.png"><h3 class="heading"> Data Listing</h3>
<pre><?php echo $tr; ?></pre>

<p>You should be able to 'copy &amp; paste' this raw data listing into a simple
text editor and save the data file on your machine.  Most GIS systems can 
then import this dataset as a layer.  You may have to omit the commented lines
(#) if your GIS has trouble importing the data.</div>

<?php 
  include("$rootpath/include/footer.php");
?>
