<?php
include("../../../../config/settings.inc.php");
include("$rootpath/include/database.inc.php");

$var = isset($_GET["var"]) ? $_GET["var"]: "high";
$year = isset($_GET["year"]) ? $_GET["year"]: 2006;
$month = isset($_GET["month"]) ? $_GET["month"]: 2;
$day = isset($_GET["day"]) ? $_GET["day"]: 1;
$source = isset($_GET["source"]) ? $_GET["source"]: "qc";
$size = isset($_GET["size"]) ? $_GET["size"] : "640x480";
$showlabels = isset($_GET["labels"]);
$tokens = explode("x", $size);
$width = $tokens[0]; $height = $tokens[1];

/** Need to use external date lib *
  * http://php.weblogs.com/adodb_date_time_library
  */
include("$rootpath/include/adodb-time.inc.php");

$ts = adodb_mktime(0,0,0,$month,$day,$year);
$ndate = adodb_date("Y-m-d", $ts);

include("$rootpath/include/forms.php");

?>

<?php $TITLE = "IEM | NWS COOP Daily Plotter";
$THISPAGE = "networks-coop";
$HEADEXTRA = '<script language="JavaScript" type="text/javascript">
<!--//BEGIN Script
function new_window(url) {
        link = 
        window.open(url,"_new","toolbar=0,location=0,directories=0,status=0,menubar=no,scrollbars=yes,resizable=yes,width=450,height=400");
} 
//END Script-->
</script>';
include("$rootpath/include/header.php"); ?>

<div class="text">

<p>With this application, you can plot COOP observations for a date of your
choice.

<form method="GET" name="myform">
<table cellpadding="2" border="1" cellspacing="0">
 <tr>
   <th>Select Datasource:</th>
   <th>Select Parameter:</th>
   <th>Year</th>
   <th>Month</th>
   <th>Day</th>
   <th>Image Size</th>
   <td></td>
  </tr>
 <tr>
  <td><select name="source">
  <option value="qc" <?php if($source == "qc") echo "SELECTED"; ?>>QC'd (1893-)
  <option value="prelim" <?php if($source == "prelim") echo "SELECTED"; ?>>Preliminary (2004-)
  </select></td>
  <td><select name="var">
     <option value="high" <?php if($var == "high") echo "SELECTED"; ?>>High Temperature</option>
     <option value="low" <?php if($var == "low") echo "SELECTED"; ?>>Low Temperature</option>
     <option value="precip" <?php if($var == "precip") echo "SELECTED"; ?>>Precipitation</option>
     <option value="snow" <?php if($var == "snow") echo "SELECTED"; ?>>Snow [1]</option>
     <option value="snowd" <?php if($var == "snowd") echo "SELECTED"; ?>>Snow Depth [2]</option>
    </select></td>
  <td><?php echo yearselect(1893, $year); ?></td>
  <td><?php echo monthSelect2($month, 'month'); ?></td>
  <td><?php echo daySelect2($day, 'day'); ?></td>
  <td>
<select name="size">
  <option value="640x480" <?php if($size == "640x480") echo "SELECTED"; ?>>640x480</option>
  <option value="1024x768" <?php if($size == "1024x768") echo "SELECTED"; ?>>1024x768</option>
  <option value="1280x1024" <?php if($size == "1280x1024") echo "SELECTED"; ?>>1280x1024</option>
</select>
  </td>
  <td><input type="submit" value="Make Plot"></td>
  </tr>
</table>
<input type="checkbox" name="labels" <?php if ($showlabels){ echo "CHECKED=\"CHECKED\""; }?>>Show point labels
</form>
<br />[1] Snowfall data is not complete.  Please be careful using the data.
<br />[2] Snowfall depth data only goes back to 1991 for Quality Controled source.
<?php
dl($mapscript);
include("$rootpath/include/network.php");
if ($source == "qc") $nt = new NetworkTable("IACLIMATE");
else $nt = new NetworkTable("IA_COOP");
$cities = $nt->table;

function mktitlelocal($map, $imgObj, $titlet, $height) { 
 
  $layer = $map->getLayerByName("credits");
 
     // point feature with text for location
  $point = ms_newpointobj();
  $point->setXY( 0, 10);
  $point->draw($map, $layer, $imgObj, 0,
    $titlet ."                                                                                ");
  $point->free();

     // point feature with text for location
  $point = ms_newpointobj();
  $point->setXY( 0, $height - 15);
  $point->draw($map, $layer, $imgObj, 1,
    "  Iowa Environmental Mesonet | NWS COOP ");
  $point->free();
}

function plotNoData($map, $img){
  $layer = $map->getLayerByName("credits");

  $point = ms_newpointobj();
  $point->setXY( 100, 200);
  $point->draw($map, $layer, $img, 1,
    "  No data found for this date! ");
  $point->free();

}

$varDef = Array("low" => "Low Temperature",
  "precip" => "Precipitation",
  "snow" => "Snowfall",
  "snowd" => "Snow Depth",
  "high" => "High Temperature"
);



$rnd = Array("gdd50" => 0,
  "et" => 2,
  "prec" => 2,
  "snow" => 0,
  "sgdd50" => 0,
  "sdd86" => 0);


$myStations = $cities;

$map = ms_newMapObj("$rootpath/data/gis/base26915.map");
$map->selectOutputFormat("PNG24");
$map->set("width", $width);
$map->set("height",$height);
$map->setProjection("init=epsg:26915");

$map->setextent(250000, 4450000, 690000, 4880000);

$states = $map->getlayerbyname("states");
$states->set("status", MS_ON);

$counties = $map->getlayerbyname("iacounties");
$counties->set("status", MS_ON);

$snet = $map->getlayerbyname("datapoint");
$snet->set("status", MS_ON);

$ponly = $map->getlayerbyname("pointonly");
$ponly->set("status", MS_ON);

$cityname = $map->getlayerbyname("cityname");
$cityname->set("status", MS_ON);

$img = $map->prepareImage();
$counties->draw($img);
$states->draw($img);

$c = iemdb("coop");

if ($source == "qc")
{
  $sql = sprintf("SELECT * from alldata WHERE day = '%s' and %s is not null", adodb_date("Y-m-d", $ts), $var );
  $cutstring1 = 2;
  $cutstring2 = 4;
} else {
  $c = iemdb("access");
  $cutstring1 = 0;
  $cutstring2 = 5;
  $sql = sprintf("SELECT station as stationid, day, snowd, max_tmpf as high, min_tmpf as low, pday as precip from summary_%s WHERE day = '%s' and network = 'IA_COOP' and min_tmpf < 90 and max_tmpf > -90", adodb_date("Y", $ts), adodb_date("Y-m-d", $ts) );
}

$rs =  pg_exec($c, $sql);
$vals = Array();
for ($i=0; $row = @pg_fetch_array($rs,$i); $i++) {
  $stid = $row['stationid'];
  $vals[$stid] = (float)$row[$var];
}
/* ------------------------------------------------------- */


$tr = "# ".$ndate." ". $varDef[$var] ."
# Download From: http://mesonet.agron.iastate.edu/GIS/apps/coop/plot.phtml
# Download Date: ". strftime("%d %b %Y") ."
# Data Contact: Daryl Herzmann akrherz@iastate.edu 515.294.5978
#-----------------------snip------------------\n";
$tr .= sprintf("%10s,%20s,%10s,%10s,%10s,%10s\n", 'ID', 'StationName', 'Date', 'Latitude', 'Longitude', $var);
foreach($vals as $key => $value){
  $ukey = strtoupper($key);
  if (! isset($cities[$ukey]) ) continue;
  if (intval($value) == -99) continue;

  $tr .= sprintf("%10s,%-20s,%10s,%10.4f,%10.4f,%10s\n", $key, $cities[$ukey]['name'], $ndate,
  $cities[$ukey]['lat'], $cities[$ukey]['lon'], $value );

  if ($ukey == "IA0807") $cities["IA0807"]["lon"] -= 0.1;

  if ($showlabels){
    $pt = ms_newPointObj();
    $pt->setXY($cities[$ukey]['lon'], $cities[$ukey]['lat'], 0);
    $pt->draw($map, $ponly, $img, 0, '' );
    $pt->free();

    $pt = ms_newPointObj();
    $pt->setXY($cities[$ukey]['lon'], $cities[$ukey]['lat'], 0);
    $pt->draw($map, $cityname, $img, 0, substr($key,$cutstring1,$cutstring2) );
    $pt->free();
  }

  // Value UL
  $pt = ms_newPointObj();
  $pt->setXY($cities[$ukey]['lon'], $cities[$ukey]['lat'], 0);
  if ($value == 0.0001) $value = "T";
  $pt->draw($map, $snet, $img, 2, $value);
  $pt->free();
}
$map->drawLabelCache($img);


if ($i == 0)
   plotNoData($map, $img);

mktitlelocal($map, $img, " $ndate ". $varDef[$var] ."  ", $height);
$map->drawLabelCache($img);

$url = $img->saveWebImage();

?>
<p><h3 class="heading">Plot</h3>
  <p>Open this plot in a <a href="javascript:new_window('image.phtml?f=<?php echo $url; ?>');">new window</a> for comparison with other plots. Once the
image is loaded up in another window, you can modify this plots 
parameters.

<br />  <img src="<?php echo $url; ?>" border=1>

<p>
<img src="<?php echo $rooturl; ?>/images/gisready.png"><h3 class="heading"> Data Listing</h3>
<pre><?php echo $tr; ?></pre>

<p>You should be able to 'copy & paste' this raw data listing into a simple
text editor and save the data file on your machine.  Most GIS systems can 
then import this dataset as a layer.  You may have to omit the commented lines
(#) if your GIS has trouble importing the data.</div>

<?php 
  include("$rootpath/include/footer.php");
?>
