<?php
 include("../../../config/settings.inc.php");
 include("$rootpath/include/database.inc.php");
 $dbconn = iemdb("access");
 $rs = pg_prepare($dbconn, "SELECTIOC", "SELECT * from current_qc_ioc WHERE 
       network = $1");
 $rs = pg_prepare($dbconn, "SELECT", "SELECT * from current_qc WHERE 
       network = $1");
 $sortcol = isset($_GET["sortcol"]) ? $_GET["sortcol"]: "station";
 $network = isset($_GET["network"])? substr($_GET["network"],0,10): "IA_ASOS";
 $baa = 'network.phtml?network='. $network;
 $TITLE = "IEM | Quality Control | MADIS Raw QC";
 include("$rootpath/include/header.php"); 
?>

<h3 class="heading">MADIS QC Values</h3>
<p>Here are the MADIS QC values for some of the networks
in the IEM.  <font color="#ff0000">Red numbers</font> indicate that the observed value is too high.  <font color="#0000ff">Blue numbers</font> indicate that the observed value is too low.  The 'QC' value is an average of all of the QC routines MADIS runs.  The 'Spatial' column is a result of the <i>Spatial Consistency Check</i>.</p>


<?php 
 include("$rootpath/include/iemaccess.php"); 
 include("$rootpath/include/network.php");
 $nt = new NetworkTable($network);
 $cities = $nt->table;

 $rs = pg_execute($dbconn, "SELECT", Array($network));

$data = Array();
for($i=0; $row = @pg_fetch_array($rs,$i); $i++)
{
  $data[ $row["station"] ] = $row;
  $data[ $row["station"] ]["sname"] = $cities[ $row["station"] ]["name"];
}

$rs = pg_execute($dbconn, "SELECTIOC", Array($network));
for($i=0; $row = @pg_fetch_array($rs,$i); $i++)
{
  $data[ $row["station"] ]["valid_ioc"] = $row["valid"];
  $data[ $row["station"] ]["tmpf_ioc"] = $row["tmpf"];
  $data[ $row["station"] ]["tmpf_qc_av_ioc"] = $row["tmpf_qc_av"];
  $data[ $row["station"] ]["tmpf_qc_sc_ioc"] = $row["tmpf_qc_sc"];

  $data[ $row["station"] ]["dwpf_ioc"] = $row["dwpf"];
  $data[ $row["station"] ]["dwpf_qc_av_ioc"] = $row["dwpf_qc_av"];
  $data[ $row["station"] ]["dwpf_qc_sc_ioc"] = $row["dwpf_qc_sc"];

  $data[ $row["station"] ]["alti_ioc"] = $row["alti"];
  $data[ $row["station"] ]["alti_qc_av_ioc"] = $row["alti_qc_av"];
  $data[ $row["station"] ]["alti_qc_sc_ioc"] = $row["alti_qc_sc"];
}

function aSortBySecondIndex($multiArray, $secondIndex) {
        while (list($firstIndex, ) = each($multiArray))
                $indexMap[$firstIndex] = $multiArray[$firstIndex][$secondIndex];        arsort($indexMap);
        while (list($firstIndex, ) = each($indexMap))
                if (is_numeric($firstIndex))
                        $sortedArray[] = $multiArray[$firstIndex];
                else $sortedArray[$firstIndex] = $multiArray[$firstIndex];
        return $sortedArray;
}

$finalA = Array();
$finalA = aSortBySecondIndex($data, $sortcol);
?>

<?php
 /** Handle Selection of network */


$ns_networks = Array(
  "IA_ASOS" => "ASOS [Iowa]",
  "AWOS"    => "AWOS [Iowa]",
  "KCCI"    => "KCCI-TV SchoolNet",
  "KELO"    => "KELO-TV WeatherNet",
  "KIMT"    => "KIMT-TV StormNet",
  "MN_ASOS"    => "ASOS/AWOS [Minnesota]",
  "WI_ASOS"    => "ASOS/AWOS [Wisconsin]",
  "IL_ASOS"    => "ASOS/AWOS [Illinios]",
  "IN_ASOS"    => "ASOS/AWOS [Indiana]",
  "OH_ASOS"    => "ASOS/AWOS [Ohio]",
  "MI_ASOS"    => "ASOS/AWOS [Michigan]",
  "KS_ASOS"    => "ASOS/AWOS [Kansas]",
  "NE_ASOS"    => "ASOS/AWOS [Nebraska]",
  "SD_ASOS"    => "ASOS/AWOS [South Dakota]",
  "ND_ASOS"    => "ASOS/AWOS [North Dakota]",
);
?>
 
<form method="GET" name="switchNetwork">
 
<b>Select Network:</b><select name="id"
 onChange="location=this.form.id.options[this.form.id.selectedIndex].value">
<?php
while( list($key, $val) = each($ns_networks) ){
 echo "<option value=\"network.phtml?network=$key\" ";
 if ($network == $key) echo "selected=\"selected\"";
 echo ">". $ns_networks[$key] ."\n";
}
?></select>
</form>

<style>
#w { color: #ff0000;}
#c { color: #0000ff;}
#divider{ 
  border-style: none;
  text-align: center;
  background-color: #CCCCCC;
}
</style>

<table cellpadding=2 cellspacing=0 border=1>
<tr>
 <th colspan="2"></th>
 <th colspan="10">GSD MADIS</th>
 <th colspan="10">NWS/NOAA MADIS IOC</th>
</tr>
<tr>
  <td rowspan=2><a href="<?php echo $baa; ?>&sortcol=station">Site ID:</a></td>
  <td rowspan=2><a href="<?php echo $baa; ?>&sortcol=sname">Station Name:</a></td>
  <td rowspan=2>Ob Valid: (UTC)</td>
  <td colspan=3 id="divider">Air Temperature [F]</td>
  <td colspan=3 id="divider">Dewpoint [F]</td>
  <td colspan=3 id="divider">Altimeter [inch]</td>
  <td rowspan=2>Ob Valid: (UTC)</td>
  <td colspan=3 id="divider">Air Temperature [F]</td>
  <td colspan=3 id="divider">Dewpoint [F]</td>
  <td colspan=3 id="divider">Altimeter [inch]</td>
</tr>
<tr>
  <td id="divider"><a href="<?php echo $baa; ?>&sortcol=tmpf">OB:</a></td>
  <td><a href="<?php echo $baa; ?>&sortcol=tmpf_qc_av">QC:</a></td>
  <td><a href="<?php echo $baa; ?>&sortcol=tmpf_qc_sc">Spatial:</a></td>
  <td id="divider"><a href="<?php echo $baa; ?>&sortcol=dwpf">OB:</a></td>
  <td><a href="<?php echo $baa; ?>&sortcol=dwpf_qc_av">QC:</a></td>
  <td><a href="<?php echo $baa; ?>&sortcol=dwpf_qc_sc">Spatial:</a></td>
  <td id="divider"><a href="<?php echo $baa; ?>&sortcol=alti">OB:</a></td>
  <td><a href="<?php echo $baa; ?>&sortcol=alti_qc_av">QC:</a></td>
  <td><a href="<?php echo $baa; ?>&sortcol=alti_qc_sc">Spatial:</a></td>

  <td id="divider"><a href="<?php echo $baa; ?>&sortcol=tmpf_ioc">OB:</a></td>
  <td><a href="<?php echo $baa; ?>&sortcol=tmpf_qc_av_ioc">QC:</a></td>
  <td><a href="<?php echo $baa; ?>&sortcol=tmpf_qc_sc_ioc">Spatial:</a></td>
  <td id="divider"><a href="<?php echo $baa; ?>&sortcol=dwpf_ioc">OB:</a></td>
  <td><a href="<?php echo $baa; ?>&sortcol=dwpf_qc_av_ioc">QC:</a></td>
  <td><a href="<?php echo $baa; ?>&sortcol=dwpf_qc_sc_ioc">Spatial:</a></td>
  <td id="divider"><a href="<?php echo $baa; ?>&sortcol=alti_ioc">OB:</a></td>
  <td><a href="<?php echo $baa; ?>&sortcol=alti_qc_av_ioc">QC:</a></td>
  <td><a href="<?php echo $baa; ?>&sortcol=alti_qc_sc_ioc">Spatial:</a></td>
</tr>


<?php
$i = false;

function vp($v, $r){
 if ($v > 0) return '<td><font id="c">'. round($v,$r) .'</font></td>';
 else if ($v < 0) return '<td><font id="w">'. round($v,$r) .'</font></td>';
 return '<td>'. round($v,$r) .'</td>';
}
function pp($v, $r){
 if (intval($v) == -17966) return 'M';
 return round($v,$r);
}

while (list ($key, $val) = each ($finalA))  {
  $ts = strtotime($val["valid"]);
  echo '<tr ';
  if ($i) echo 'class="even"';
  echo '><td>'. $val["station"] .'</td><td>'. $cities[$key]["name"] .'</td>
  <td>'. strftime("%d %b %H:%M", $ts) .'</td>
  <td id="divider">'. pp($val["tmpf"],0) .'</td>'. 
  vp($val["tmpf_qc_av"], 1) . 
  vp($val["tmpf_qc_sc"], 1) . 
  '<td id="divider">'. pp($val["dwpf"],0) .'</td>'.
  vp($val["dwpf_qc_av"], 1) . 
  vp($val["dwpf_qc_sc"], 1) . 
  '<td id="divider">'. pp($val["alti"],2) .'</td>'.
  vp($val["alti_qc_av"], 2) . 
  vp($val["alti_qc_sc"], 2) . 
  '<td>'. strftime("%d %b %H:%M", strtotime($val["valid_ioc"])) .'</td>
  <td id="divider">'. pp($val["tmpf_ioc"],0) .'</td>'. 
  vp($val["tmpf_qc_av_ioc"], 1) . 
  vp($val["tmpf_qc_sc_ioc"], 1) . 
  '<td id="divider">'. pp($val["dwpf_ioc"],0) .'</td>'.
  vp($val["dwpf_qc_av_ioc"], 1) . 
  vp($val["dwpf_qc_sc_ioc"], 1) . 
  '<td id="divider">'. pp($val["alti_ioc"],2) .'</td>'.
  vp($val["alti_qc_av_ioc"], 2) . 
  vp($val["alti_qc_sc_ioc"], 2) . 
  '</tr>';

 $i = ! $i;
}

?></table>


<?php include("$rootpath/include/footer.php"); ?>
