<?php
 require_once "../../../config/settings.inc.php";
 define("IEM_APPID", 97);
 require_once "../../../include/myview.php";
 $t = new MyView();
 $t->thispage = "iem-qc";
 $t->title = "Quality Control, MADIS Raw QC";
 require_once "../../../include/database.inc.php";
 require_once "../../../include/forms.php";
 require_once "../../../include/mlib.php";
 $dbconn = iemdb("access");
 $rs = pg_prepare($dbconn, "SELECT", "SELECT * from current_qc WHERE 
       network = $1");
 $sortcol = isset($_GET["sortcol"]) ? xssafe($_GET["sortcol"]): "station";
 $network = isset($_GET["network"])? substr($_GET["network"],0,10): "IA_ASOS";
 $baa = 'network.phtml?network='. $network;

 require_once "../../../include/network.php";
 $nt = new NetworkTable($network);
 $cities = $nt->table;
 
 $rs = pg_execute($dbconn, "SELECT", Array($network));
 
 $data = Array();
 for($i=0; $row = @pg_fetch_array($rs,$i); $i++)
 {
 	$data[ $row["station"] ] = $row;
 	$data[ $row["station"] ]["sname"] = $cities[ $row["station"] ]["name"];
 }
  
 $finalA = Array();
 $finalA = aSortBySecondIndex($data, $sortcol);
 $ns_networks = Array(
 		"IA_ASOS" => "ASOS [Iowa]",
 		"AWOS"    => "AWOS [Iowa]",
 		"MN_ASOS"    => "ASOS/AWOS [Minnesota]",
 		"WI_ASOS"    => "ASOS/AWOS [Wisconsin]",
 		"IL_ASOS"    => "ASOS/AWOS [Illinios]",
 		"IN_ASOS"    => "ASOS/AWOS [Indiana]",
 		"OH_ASOS"    => "ASOS/AWOS [Ohio]",
 		"MI_ASOS"    => "ASOS/AWOS [Michigan]",
 		"KS_ASOS"    => "ASOS/AWOS [Kansas]",
 		"NE_ASOS"    => "ASOS/AWOS [Nebraska]",
 		"SD_ASOS"    => "ASOS/AWOS [South Dakota]",
 		"ND_ASOS"    => "ASOS/AWOS [North Dakota]",
 );
 
 $sselect = "";
 while( list($key, $val) = each($ns_networks) ){
 	$sselect .= "<option value=\"network.phtml?network=$key\" ";
 	if ($network == $key) $sselect .= "selected=\"selected\"";
 	$sselect .= ">". $ns_networks[$key] ."\n";
 }


 $i = false;
 
 function vp($v, $r){
 	if ($v > 0) return '<td><font id="c">'. round($v,$r) .'</font></td>';
 	else if ($v < 0) return '<td><font id="w">'. round($v,$r) .'</font></td>';
 	return '<td>'. round($v,$r) .'</td>';
 }
 function pp($v, $r){
 	if (intval($v) == -17966) return 'M';
 	return round($v,$r);
 }
 $table = "";
 while (list ($key, $val) = each ($finalA))  {
 	$ts = strtotime($val["valid"]);
 	$table .= '<tr ';
 	if ($i) $table .= 'class="even"';
 	$table .= '><td>'. $val["station"] .'</td><td>'. $cities[$key]["name"] .'</td>
  <td>'. strftime("%d %b %H:%M", $ts) .'</td>
  <td id="divider">'. pp($val["tmpf"],0) .'</td>'.
   vp($val["tmpf_qc_av"], 1) .
   vp($val["tmpf_qc_sc"], 1) .
   '<td id="divider">'. pp($val["dwpf"],0) .'</td>'.
   vp($val["dwpf_qc_av"], 1) .
   vp($val["dwpf_qc_sc"], 1) .
   '<td id="divider">'. pp($val["alti"],2) .'</td>'.
   vp($val["alti_qc_av"], 2) .
   vp($val["alti_qc_sc"], 2) .
   '</tr>';
 
 	$i = ! $i;
 }
 
 $t->content = <<<EOF
<h3 class="heading">MADIS QC Values</h3>
<p>Here are the MADIS QC values for some of the networks
in the IEM.  <font color="#ff0000">Red numbers</font> indicate that the 
observed value is too high.  <font color="#0000ff">Blue numbers</font> 
indicate that the observed value is too low.  The 'QC' value is an 
average of all of the QC routines MADIS runs.  The 'Spatial' column is a 
result of the <i>Spatial Consistency Check</i>.</p>




<form method="GET" name="switchNetwork">
 
<b>Select Network:</b><select name="id"
 onChange="location=this.form.id.options[this.form.id.selectedIndex].value">
{$sselect}
 </select>
</form>

<style>
#w { color: #ff0000;}
#c { color: #0000ff;}
#divider{ 
  border-style: none;
  text-align: center;
  background-color: #CCCCCC;
}
</style>

<table class="table table-condensed table-striped table-bordered">
<tr>
  <td rowspan=2><a href="{$baa}&sortcol=station">Site ID:</a></td>
  <td rowspan=2><a href="{$baa}&sortcol=sname">Station Name:</a></td>
  <td rowspan=2>Ob Valid: (UTC)</td>
  <td colspan=3 id="divider">Air Temperature [F]</td>
  <td colspan=3 id="divider">Dewpoint [F]</td>
  <td colspan=3 id="divider">Altimeter [inch]</td>
</tr>
<tr>
  <td id="divider"><a href="{$baa}&sortcol=tmpf">OB:</a></td>
  <td><a href="{$baa}&sortcol=tmpf_qc_av">QC:</a></td>
  <td><a href="{$baa}&sortcol=tmpf_qc_sc">Spatial:</a></td>
  <td id="divider"><a href="{$baa}&sortcol=dwpf">OB:</a></td>
  <td><a href="{$baa}&sortcol=dwpf_qc_av">QC:</a></td>
  <td><a href="{$baa}&sortcol=dwpf_qc_sc">Spatial:</a></td>
  <td id="divider"><a href="{$baa}&sortcol=alti">OB:</a></td>
  <td><a href="{$baa}&sortcol=alti_qc_av">QC:</a></td>
  <td><a href="{$baa}&sortcol=alti_qc_sc">Spatial:</a></td>
</tr>

{$table}
</table>
EOF;
$t->render('single.phtml');
?>
