<?php
require_once "../../../config/settings.inc.php";
define("IEM_APPID", 97);
require_once "../../../include/myview.php";
require_once "../../../include/database.inc.php";
require_once "../../../include/forms.php";
require_once "../../../include/mlib.php";

$t = new MyView();
$t->title = "Quality Control, MADIS Raw QC";
$dbconn = iemdb("iem");
$rs = pg_prepare(
    $dbconn,
    "SELECT",
    "SELECT c.*, t.id as station, t.name, " .
        "c.valid at time zone 'UTC' as uv from current_qc c JOIN stations t on " .
        "(c.iemid = t.iemid) WHERE t.network = $1"
);
$sortcol = isset($_GET["sortcol"]) ? xssafe($_GET["sortcol"]) : "station";
$network = isset($_GET["network"]) ? substr(xssafe($_GET["network"]), 0, 10) : "IA_ASOS";
if ($network == "AWOS") {
    $network = "IA_ASOS";
}
$baa = "network.phtml?network={$network}";

$rs = pg_execute($dbconn, "SELECT", array($network));

$data = array();
for ($i = 0; $row = pg_fetch_assoc($rs); $i++) {
    $data[$row["station"]] = $row;
}

$finalA = array();
$finalA = aSortBySecondIndex($data, $sortcol);

$rs = pg_exec(
    iemdb("mesosite"),
    "SELECT id, name from networks"
);
$networks = array();
while ($row = pg_fetch_assoc($rs)) {
    $networks[$row["id"]] = $row["name"];
}

$rs = pg_exec(
    $dbconn,
    "select distinct network from current_qc q JOIN stations t " .
        "ON (q.iemid = t.iemid) ORDER by network ASC"
);
$ar = array();
while ($row = pg_fetch_assoc($rs)) {
    $ar[$row["network"]] = $networks[$row["network"]];
}
$sselect = make_select("network", $network, $ar);

$i = false;

function vp($v, $r)
{
    if (is_null($v)) return "<td>M</td>";
    $v = floatval($v);
    if ($v > 0) return '<td><font id="c">' . myround($v, $r) . '</font></td>';
    else if ($v < 0) return '<td><font id="w">' . myround($v, $r) . '</font></td>';
    return '<td>' . myround($v, $r) . '</td>';
}
function pp($v, $r)
{
    if (is_null($v)) return "M";
    $v = floatval($v);
    if (intval($v) == -17966) return 'M';
    return myround($v, $r);
}
$table = "";
$now = new DateTime("now");
$thisyear = $now->format("Y");
foreach ($finalA as $key => $val) {
    $ts = new DateTime($val["uv"]);
    $fmt = ($ts->format("Y") == $thisyear) ? "d G:i" : "Y M d G:i";
    $table .= '<tr ';
    if ($i) $table .= 'class="even"';
    $table .= '><td>' . $val["station"] . '</td><td>' . $val["name"] . '</td>
  <td>' . $ts->format($fmt) . 'Z</td>
  <td id="divider">' . pp($val["tmpf"], 0) . '</td>' .
        vp($val["tmpf_qc_av"], 1) .
        vp($val["tmpf_qc_sc"], 1) .
        '<td id="divider">' . pp($val["dwpf"], 0) . '</td>' .
        vp($val["dwpf_qc_av"], 1) .
        vp($val["dwpf_qc_sc"], 1) .
        '<td id="divider">' . pp($val["alti"], 2) . '</td>' .
        vp($val["alti_qc_av"], 2) .
        vp($val["alti_qc_sc"], 2) .
        '</tr>';

    $i = !$i;
}

$t->content = <<<EOF
<h3>MADIS QC Values</h3>
<p>Here are the MADIS QC values for some of the networks
in the IEM.  <font color="#ff0000">Red numbers</font> indicate that the 
observed value is too high.  <font color="#0000ff">Blue numbers</font> 
indicate that the observed value is too low.  The 'QC' value is an 
average of all of the QC routines MADIS runs.  The 'Spatial' column is a 
result of the <i>Spatial Consistency Check</i>.</p>

<form method="GET" name="switchNetwork">
 
{$sselect}

<input type="submit" value="Switch Network">
</form>

<style>
#w { color: #ff0000;}
#c { color: #0000ff;}
#divider{ 
  border-style: none;
  text-align: center;
  background-color: #CCCCCC;
}
</style>

<table class="table table-condensed table-striped table-bordered">
<tr>
  <td rowspan=2><a href="{$baa}&sortcol=station">Site ID:</a></td>
  <td rowspan=2><a href="{$baa}&sortcol=sname">Station Name:</a></td>
  <td rowspan=2>Ob Valid: (UTC)</td>
  <td colspan=3 id="divider">Air Temperature [F]</td>
  <td colspan=3 id="divider">Dewpoint [F]</td>
  <td colspan=3 id="divider">Altimeter [inch]</td>
</tr>
<tr>
  <td id="divider"><a href="{$baa}&sortcol=tmpf">OB:</a></td>
  <td><a href="{$baa}&sortcol=tmpf_qc_av">QC:</a></td>
  <td><a href="{$baa}&sortcol=tmpf_qc_sc">Spatial:</a></td>
  <td id="divider"><a href="{$baa}&sortcol=dwpf">OB:</a></td>
  <td><a href="{$baa}&sortcol=dwpf_qc_av">QC:</a></td>
  <td><a href="{$baa}&sortcol=dwpf_qc_sc">Spatial:</a></td>
  <td id="divider"><a href="{$baa}&sortcol=alti">OB:</a></td>
  <td><a href="{$baa}&sortcol=alti_qc_av">QC:</a></td>
  <td><a href="{$baa}&sortcol=alti_qc_sc">Spatial:</a></td>
</tr>

{$table}
</table>
EOF;
$t->render('single.phtml');
