<?php include 'header.phtml'; ?>
<style>
html,body{
height:100%;
}
</style>
<?php 
$jsextra = array_key_exists('jsextra', $this->vars)? $this->jsextra : '';
if (array_key_exists('iemss', $this->vars)){
	$jsextra .= <<<EOF
<script src="/vendor/openlayers/3.9.0/ol.js"></script>
<script src="/js/iemss.js"></script>
EOF;
}
 
if (array_key_exists('north', $this->vars)){
	echo "<div class=\"row\"><div class=\"col-xs-12\">\n";
	echo $this->vars['north'];
	echo "</div></div>\n";
}
if (array_key_exists('east', $this->vars) && 
    array_key_exists('west', $this->vars)){
	echo "<div class=\"row\"><div class=\"col-xs-6\">\n";
	echo $this->vars['west'];
	echo "</div><div class=\"col-xs-6\">\n";
	echo $this->vars['east'];
	echo "</div></div>\n";
}
if (array_key_exists('content', $this->vars)){
  echo $this->vars['content'];
}
if (array_key_exists('south', $this->vars)){
	echo "<div class=\"row\"><div class=\"col-xs-12\">\n";
	echo $this->vars['south'];
	echo "</div></div>\n";
}
?>
<?php 
$jsextra = array_key_exists('jsextra', $this->vars)? $this->jsextra : '';
if (array_key_exists('iemss', $this->vars)){
	$jsextra .= <<<EOF
<script src="/vendor/openlayers/3.9.0/ol.js"></script>
<script src="/js/iemss.js"></script>
EOF;
}

?>
 <!-- Placed at the end of the document so the pages load faster -->
    <script src="/vendor/jquery/1.11.3/jquery-1.11.3.min.js"></script>
    <script src="/vendor/bootstrap/3.3.5/js/bootstrap.min.js"></script>
    <?php echo $jsextra; ?>
  </body>
</html>