<?php 
$title = is_null($this->title)? 'Iowa Environmental Mesonet': "IEM :: {$this->title}";
$headextra = is_null($this->headextra) ? '': $this->headextra;
?>
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><?php echo $title; ?></title>
    <meta name="description" content="Iowa State University, Iowa Environmental Mesonet">
    <meta name="author" content="daryl herzmann akrherz@iastate.edu">
    <?php echo $headextra; ?>
<style>
html,body{
height:100%;
}
</style>
    </head>
<?php 
$jsextra = is_null($this->jsextra) ? '' : $this->jsextra;
 
if (array_key_exists('north', $this->vars)){
    echo "<div class=\"row\"><div class=\"col-12\">\n";
    echo $this->vars['north'];
    echo "</div></div>\n";
}
if (array_key_exists('east', $this->vars) && 
    array_key_exists('west', $this->vars)){
    echo "<div class=\"row\"><div class=\"col-6\">\n";
    echo $this->vars['west'];
    echo "</div><div class=\"col-6\">\n";
    echo $this->vars['east'];
    echo "</div></div>\n";
}
if (!is_null($this->content)){
  echo $this->content;
}
if (array_key_exists('south', $this->vars)){
    echo "<div class=\"row\"><div class=\"col-12\">\n";
    echo $this->vars['south'];
    echo "</div></div>\n";
}
?>
    <script src="/vendor/bootstrap/5.3.6/js/bootstrap.bundle.min.js"></script>
    <script src="/vendor/jquery/3.2.1/jquery-3.2.1.min.js"></script>
    <script src="/js/iastate-iem.js"></script>
    <?php echo $jsextra; ?>
  </body>
</html>