<?php 
$title = array_key_exists('title', $this->vars)? 'IEM :: '. $this->title : 'Iowa Environmental Mesonet';
$headextra = array_key_exists('headextra', $this->vars)? $this->headextra : '';
?>
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><?php echo $title; ?></title>
    <meta name="description" content="Iowa State University, Iowa Environmental Mesonet">
    <meta name="author" content="daryl herzmann akrherz@iastate.edu">
	<?php echo $headextra; ?>
<style>
html,body{
height:100%;
}
</style>
    </head>
<?php 
$jsextra = array_key_exists('jsextra', $this->vars)? $this->jsextra : '';
if (array_key_exists('iemss', $this->vars)){
	$jsextra .= <<<EOF
<script src="/vendor/openlayers/3.9.0/ol.js"></script>
<script src="/js/iemss.js"></script>
EOF;
}
 
if (array_key_exists('north', $this->vars)){
	echo "<div class=\"row\"><div class=\"col-xs-12\">\n";
	echo $this->vars['north'];
	echo "</div></div>\n";
}
if (array_key_exists('east', $this->vars) && 
    array_key_exists('west', $this->vars)){
	echo "<div class=\"row\"><div class=\"col-xs-6\">\n";
	echo $this->vars['west'];
	echo "</div><div class=\"col-xs-6\">\n";
	echo $this->vars['east'];
	echo "</div></div>\n";
}
if (array_key_exists('content', $this->vars)){
  echo $this->vars['content'];
}
if (array_key_exists('south', $this->vars)){
	echo "<div class=\"row\"><div class=\"col-xs-12\">\n";
	echo $this->vars['south'];
	echo "</div></div>\n";
}
?>
<?php 
$jsextra = array_key_exists('jsextra', $this->vars)? $this->jsextra : '';
if (array_key_exists('iemss', $this->vars)){
	$jsextra .= <<<EOF
<script src="/vendor/openlayers/3.9.0/ol.js"></script>
<script src="/js/iemss.js"></script>
EOF;
}

?>
 <!-- Placed at the end of the document so the pages load faster -->
    <script src="/vendor/jquery/1.11.3/jquery-1.11.3.min.js"></script>
    <script src="/vendor/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <?php echo $jsextra; ?>
  </body>
</html>