<?php 
$jsextra = array_key_exists('jsextra', $this->vars)? $this->jsextra : '';
if (array_key_exists('iemss', $this->vars)){
	$jsextra .= <<<EOF
<script src="/vendor/openlayers/3.9.0/ol.js"></script>
<script src="/js/iemss.js"></script>
EOF;
}

?>
<div class="container" id="iem-footer">
<hr />

 <div class="pull-right">
 <form method="get" action="https://www.google.com/search" name="gsearch" 
 class="inline-form">
 <input value="mesonet.agron.iastate.edu" name="sitesearch" type="hidden" />
 
 <div class="form-group">
    <label for="inputsearch">Search Site with Google</label>
    <input type="text" class="form-control" name="q" id="inputsearch" placeholder="Enter search term">
  </div>
 </form>
 </div>

Copyright &copy; 2001-<?php echo date("Y"); ?>, Iowa State University of Science and Technology.
<br />
 <i class="glyphicon glyphicon-book"></i> <a href="/help/abbreviations.php">abbreviations</a>
 <i class="glyphicon glyphicon-earphone"></i> <a href="/info/contacts.php">contact us</a>
 <i class="glyphicon glyphicon-wrench"></i> <a href="https://github.com/akrherz/iem">development</a>
 <i class="glyphicon glyphicon-warning-sign"></i> <a href="/disclaimer.php">disclaimer</a>
 <i class="glyphicon glyphicon-list"></i> <a href="/apps.php">list apps</a>
 
</div><!-- /.iem-footer -->

    <!-- Placed at the end of the document so the pages load faster -->
    <script src="/vendor/jquery/1.11.3/jquery-1.11.3.min.js"></script>
    <script src="/vendor/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <?php echo $jsextra; ?>
<script type="text/javascript">
var _gaq = _gaq || [];
_gaq.push(['_setAccount', 'UA-784549-2']);
_gaq.push(['_trackPageview']);
(function() {
var ga = document.createElement('script');
ga.src = ('https:' == document.location.protocol ?
    'https://ssl' : 'http://www') +
    '.google-analytics.com/ga.js';
ga.setAttribute('async', 'true');
document.documentElement.firstChild.appendChild(ga);
})();
</script>
  </body>
</html>
