<div class="container" id="iem-footer">
	<div class="row"><div class="col-md-12">
	<div style="float: right;">
 <form method="get" action="http://www.google.com/search" name="search">
 <b>Search Site with Google:</b><br />
 <input value="mesonet.agron.iastate.edu" name="sitesearch" type="hidden" />
<input type="text" size="15" name="q" /><input type="submit" value="Search" /></form>
</div>

Copyright &copy; 2001-<?php echo date("Y"); ?>, Iowa State University of Science and Technology.
<br />All rights reserved.
 <a href="/help/abbreviations.php">abbreviations</a>
 &middot; <a href="/info/contacts.php">contact us</a>
 &middot; <a href="https://github.com/akrherz/iem">development</a>
 &middot; <a href="/disclaimer.php">disclaimer</a>
 
	</div>
	</div>
</div>

    <!-- Placed at the end of the document so the pages load faster -->
    <script src="/js/jquery.js"></script>
    <script src="/js/bootstrap.min.js"></script>
<script type="text/javascript">
var _gaq = _gaq || [];
_gaq.push(['_setAccount', 'UA-784549-2']);
_gaq.push(['_trackPageview']);
(function() {
var ga = document.createElement('script');
ga.src = ('https:' == document.location.protocol ?
    'https://ssl' : 'http://www') +
    '.google-analytics.com/ga.js';
ga.setAttribute('async', 'true');
document.documentElement.firstChild.appendChild(ga);
})();
</script>
  </body>
</html>