<?php include 'header.phtml'; ?>
<?php include 'navbar.phtml'; ?>
<main role="main" id="main-content">
<div class="container-fluid">
<?php 
if (array_key_exists('north', $this->vars)){
	echo "<div class=\"row\"><div class=\"col-xs-12\">\n";
	echo $this->vars['north'];
	echo "</div></div>\n";
}
if (array_key_exists('east', $this->vars) && 
    array_key_exists('west', $this->vars)){
	echo "<div class=\"row\"><div class=\"col-xs-6\">\n";
	echo $this->vars['west'];
	echo "</div><div class=\"col-xs-6\">\n";
	echo $this->vars['east'];
	echo "</div></div>\n";
}
if (array_key_exists('content', $this->vars)){
  echo "<div class=\"row\"><div class=\"col-xs-12\">\n";
  echo $this->vars['content'];
  echo "</div></div>\n";
}
if (array_key_exists('south', $this->vars)){
	echo "<div class=\"row\"><div class=\"col-xs-12\">\n";
	echo $this->vars['south'];
	echo "</div></div>\n";
}
?>
</div><!--/.container-->
</main>
<?php include 'footer.phtml'; ?>