<?php 
$title = is_null($this->title)? 'Iowa Environmental Mesonet': "IEM :: {$this->title}";
// Page should refresh
$refresh = "";
if ($this->refresh > 0){
  $refresh = sprintf("<meta http-equiv=\"refresh\" content=\"%s;\">",
    $this->refresh);
}
$headextra = is_null($this->headextra) ? '': $this->headextra;
if ($this->iemss){
  $headextra .= <<<EOF
<link rel="stylesheet" href="/vendor/openlayers/3.9.0/ol.css" type="text/css">
EOF;
}
$bodyextra = is_null($this->bodyextra) ? '': " {$this->bodyextra}";
?>
<!DOCTYPE html>
<html lang="en">
  <head>
    <?php echo $refresh; ?>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><?php echo $title; ?></title>
    <meta name="description" content="Iowa State University, Iowa Environmental Mesonet">
    <meta name="author" content="daryl herzmann akrherz@iastate.edu">

    <!-- NB: we are stuck with FA 4.7.0 due to iastate theme -->
    <link href="/vendor/fa/4.7.0/css/font-awesome.min.css" rel="stylesheet">
    <link href="/vendor/iastate-v2.0.13/css/iastate.min.css" rel="stylesheet">
    <link href="/css/bootstrap-override.css" rel="stylesheet">
 
    <!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="/vendor/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="/vendor/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
    <!-- Any page specific headextra content here -->
    <?php echo $headextra; ?>

    <!-- Essential Social Tags -->
    <meta property="og:title" content="<?php echo $title; ?>">
    <meta property="og:description" content="<?php echo $this->twitter_description; ?>">
    <meta property="og:image" content="https://mesonet.agron.iastate.edu<?php echo $this->twitter_image; ?>">
    <meta property="og:url" content="https://mesonet.agron.iastate.edu<?php echo htmlentities($_SERVER["REQUEST_URI"]); ?>">
    <?php if (!is_null($this->twitter_video)){ 
        echo <<<EOM
    <meta property="og:type" content="video">
    <meta property="og:video" content="https://mesonet.agron.iastate.edu{$this->twitter_video}">
    <meta property="og:video:type" content="video/mp4">
    <meta property="og:video:width" content="{$this->twitter_video_width}">
    <meta property="og:video:height" content="{$this->twitter_video_height}">

EOM;
    } ?>
    <meta name="twitter:card" content="<?php echo $this->twitter_card; ?>">

    <!-- Non-essential -->
    <meta name="twitter:creator" content="@akrherz">
    <!-- Le fav and touch icons -->
    <link rel="shortcut icon" href="/favicon.ico">
    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="/apple-touch-icon-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="/apple-touch-icon-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="72x72" href="/apple-touch-icon-precomposed.png">
    <link rel="apple-touch-icon-precomposed" href="/apple-touch-icon-precomposed.png">
  </head>

  <body<?php echo $bodyextra; ?>>
