<?php 
$title = array_key_exists('title', $this->vars)? 'IEM :: '. $this->title : 'Iowa Environmental Mesonet';
$refresh = array_key_exists('refresh', $this->vars)? $this->refresh : '';
$headextra = array_key_exists('headextra', $this->vars)? $this->headextra : '';
if (array_key_exists('iemss', $this->vars)){
  $headextra .= <<<EOF
<link rel="stylesheet" href="/vendor/openlayers/3.9.0/ol.css" type="text/css">
EOF;
}
$bodyextra = array_key_exists('bodyextra', $this->vars)? ' '. $this->bodyextra : '';
$twimage = array_key_exists('twitter_image', $this->vars) ? 
				$this->twitter_image : 'images/logo_small.png';
$twdescription = array_key_exists('twitter_description', $this->vars) ? 
				$this->twitter_description : 'Iowa Environmental Mesonet of Iowa State University';
?>
<!DOCTYPE html>
<html lang="en">
  <head>
    <?php 
    echo $refresh; 
    echo $headextra; 
    ?>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><?php echo $title; ?></title>
    <meta name="description" content="Iowa State University, Iowa Environmental Mesonet">
    <meta name="author" content="daryl herzmann akrherz@iastate.edu">

    <!-- Le styles -->
    <link href="/vendor/bootstrap/3.3.5/css/bootstrap.min.css" rel="stylesheet">
    <link href="/css/bootstrap-override.css" rel="stylesheet">
 
    <!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="/js/html5shiv.js"></script>
      <script src="/js/respond.min.js"></script>
    <![endif]-->

	<!-- Essential Social Tags -->
	<meta property="og:title" content="<?php echo $title; ?>">
	<meta property="og:description" content="<?php echo $twdescription; ?>">
	<meta property="og:image" content="https://mesonet.agron.iastate.edu<?php echo $twimage; ?>">
	<meta property="og:url" content="https://mesonet.agron.iastate.edu">
	<meta name="twitter:card" content="summary">

	<!-- Non-essential -->
	<meta name="twitter:creator" content="@akrherz">
    <!-- Le fav and touch icons -->
    <link rel="shortcut icon" href="/favicon.ico">
    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="/apple-touch-icon-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="/apple-touch-icon-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="72x72" href="/apple-touch-icon-precomposed.png">
    <link rel="apple-touch-icon-precomposed" href="/apple-touch-icon-precomposed.png">
  </head>

  <body<?php echo $bodyextra; ?>>
