<?php 
/*
 * - highlight note <-- Eliminated
 */
include_once dirname(__FILE__) ."/../database.inc.php";
$connection = iemdb("mesosite", TRUE, TRUE);
?>
<?php include 'header.phtml'; ?>
<?php include 'navbar.phtml'; ?>

    <div class="container">
      <div class="row">

        <div class="col-sm-8">
       
 <p>The Iowa Environmental Mesonet (IEM) collects environmental data from 
 cooperating members with observing networks. The data are stored and made 
 available on this website.</p>

 <div class="row">
<div class="col-xs-12 col-sm-4">
<a href="/agweather/" class="btn btn-default btn-block agweather">Ag Weather</a>
</div>
<div class="col-xs-12 col-sm-4">
<a href="/nws/" class="btn btn-default btn-block nws">NWS Users</a>
</div>
<div class="col-xs-12 col-sm-4">
<a href="/archive/" class="btn btn-default btn-block book">Researchers</a>
</div>
</div>
	
		<?php echo $this->feature; ?>		
        </div><!--/col-sm-8-->
        <div class="col-sm-4">

<?php 

if ($this->lsr_snow == 'true'){
	$nunce = time();
  echo <<<EOF
<div class="panel panel-default">
<div class="panel-heading">NWS Snowfall Reports:</div>
  <div class="panel-body">
<a href="/data/lsr_snowfall.png">
<img src="/data/lsr_snowfall.png?{$nunce}" border="0" alt="LSR Snowfall" class="img img-responsive"/></a>
  <a href="/lsr/#DMX,DVN,ARX,FSD,OAX/-43200">View Snowfall Reports on Map</a>
  </div>
</div>
EOF;
}

include_once(dirname(__FILE__) ."/../cameras.inc.php");
$rancam = "";
$loop = 0;
while ($rancam == "" && $loop < 20)
{
  srand ((float) microtime() * 10000000);
  $t = array_rand($cameras);
  if (@filemtime("/home/ldm/data/camera/stills/${t}.jpg") > (time() - 1200))
  {
    $rancam = $t;
  }
  $loop += 1;
}
if ($rancam == ""){ $rancam = "KCCI-016";}
?>
<div class="panel panel-default">
  <div class="panel-heading"><?php echo $cameras[$rancam]["name"] .", ". $cameras[$rancam]["state"]; ?> Webcam:</div>
  <div class="panel-body">
<a href="/current/webcam.php#<?php echo  $cameras[$rancam]["network"]; ?>-0"><img src="/data/camera/stills/<?php echo $rancam; ?>.jpg?<?php echo time(); ?>" border="0" alt="Webcam" class="img-responsive"/></a>
<a href="/current/webcam.php#<?php echo  $cameras[$rancam]["network"]; ?>-0">View other webcams</a>
  
  </div>
</div>


<div class="panel panel-default">
  <div class="panel-heading">Most Popular</div>
  <div class="panel-body">
<a href="/timemachine/#1.0">Iowa Mesonet Plot</a>
  [<a href="/current/loop.phtml?prod=mesonet">Loop</a>]
<br /><a href="/current/mcview.phtml?prod=comprad&amp;java=none&amp;mode=realtime&amp;frames=1">Current NEXRAD</a> [<a href="/current/mcview.phtml">Loop</a>]
<br /><a href="/GIS/apps/iem/freeze.phtml">IEM Freeze</a>
<br /><a href="/rainfall/">IEM GIS Rainfall</a>
<br /><a href="/my/current.phtml">Sortable Currents</a>
<br /><a href="/lsr/#DMX,DVN,ARX,FSD,OAX/-43200">View Storm Reports on Map</a>
<br /><a href="/onsite/features/tags/winter1415.html">Winter Storms of 2014-2015</a>

    </div>
</div>


<div class="panel panel-default">
  <div class="panel-heading">News Items &nbsp; <a href="/rss.php"><img src="/images/rss.gif" /></a></div>
  <div class="panel-body">
<?php 
$rs = pg_query($connection, "SELECT * from news ORDER by entered DESC LIMIT 5");

$today = mktime(0,0,0, date("m"), date("d"), date("Y"));

for ($i=0; $row = @pg_fetch_array($rs, $i); $i++){
	$ts = strtotime(substr($row["entered"],0,16));
	if ($ts > $today) $sts = strftime("%I:%M %p", $ts);
	else $sts = strftime("%d %b %I:%M %p", $ts);
	echo "<p><a href=\"/onsite/news.phtml?id=".$row["id"]."\">". $row["title"] ."</a><br /><i>Posted:</i> $sts</li>\n";
}

?>

<p><b class='glyphicon-envelope'></b>
<a href="/mailman/listinfo/dailyb">Sign up</a> for the 
<a href="/data/iemdb.html">Daily Bulletin</a></p>

  </div>
</div>

<?php echo $this->iemperf; ?>


        </div><!--/span-->
      </div><!--/row-->

<!-- Three columns highlighting stuff -->
<div class="row">
    <div class="col-sm-4">
        <h3>RADAR Products</h3>
        <a href="/timemachine/#2.0"><img src="/data/mwcomp.png" class="img-responsive" /></a>
        <p>The IEM processes National Weather Service NEXRAD information
        in real-time to produce and archive many products. This includes a 
        generated <a href="/docs/nexrad_composites/">composite</a> produced
        every five minutes dating back to 1995!</p>
        <p><a class="btn" href="/current/radar.phtml">View more products &raquo;</a></p>
    </div>
    <div class="col-sm-4">
        <h3>Precipitation</h3>
        <a href="/timemachine/#45.0"><img src="/data/iowa_q2_1d.png" class="img-responsive" /></a>
        <p>Besides point observations of precipitation, the IEM also processes
        gridded rainfall products made available by NOAA.  This information
        is archived and made available in GIS ready formats.</p>
        <p><a class="btn" href="/rainfall/">Download Precipitation for GIS &raquo;</a></p>
    </div>
    <div class="col-sm-4">
        <h3>Current Data</h3>
        <a href="/timemachine/#1.0"><img src="/data/mesonet.gif" class="img-responsive" /></a>
        <p>The IEM combines data from participating networks into products
        like maps shown above and web applications to analyze the data.</p>
        <p><a class="btn" href="/current/">More current products &raquo;</a></p>
    </div>
</div><!--/row-->

<div class="row clearfix well">
<div class="col-sm-2"><h4>Partners:</h4></div>
<div class='col-sm-4'>
<a href="http://www.agron.iastate.edu/"><img
src="/images/agronomy.png" alt="ISU Agronomy" class="img img-responsive"></a>
</div>
<div class='col-sm-2'>
<a href="http://www.iihr.uiowa.edu"><img src="/images/iihrlogo.jpg"
  alt="IIHR - University of Iowa" class="img img-responsive" /></a>
</div>
<div class='col-sm-3'>
 <a href="http://www.dot.state.ia.us"><img src="/images/doticon.gif"
 alt="DOT" class="img img-responsive" /></a>
</div>
<div class='col-sm-1'>
  <a href="http://www.weather.gov/dmx/"><img src="/images/nws.gif"
  alt="NWS" class="img img-responsive" /></a>
</div>

</div>

</div><!--/.container-->

<?php include 'footer.phtml'; ?>