<?php 
/*
 * - highlight note <-- Eliminated
 */

?>
<?php include 'header.phtml'; ?>
<?php include 'navbar.phtml'; ?>

    <div class="container">
      <div class="row">

        <div class="col-md-9">
       
 <p>The Iowa Environmental Mesonet (IEM) collects environmental data from 
 cooperating members with observing networks. The data are stored and made 
 available on this website.</p>

<div class="btn-group btn-group-justified">
<a href="/agweather/" class="btn btn-default agweather">Ag Weather</a>
<a href="/nws/" class="btn btn-default nws">NWS Users</a>
<a href="/archive/" class="btn btn-default book">Researchers</a>
</div>
        	
        	
<?php 
/*
 * Template for IEM Daily Feature!
 */
$connection = iemdb("mesosite", TRUE, TRUE);
$query1 = "SELECT oid, *, to_char(valid, 'YYYY/MM/YYMMDD') as imageref,
                to_char(valid, 'DD Mon YYYY HH:MI AM') as webdate,
                to_char(valid, 'YYYY-MM-DD') as permalink from feature
                ORDER by valid DESC LIMIT 1";
$result = pg_exec($connection, $query1);
$row = pg_fetch_array($result,0);
$foid = $row["oid"];
$good = intval($row["good"]);
$bad = intval($row["bad"]);
$tags = explode(",", $row["tags"]);
$fbid = $row["fbid"];
$fburl = "http://www.facebook.com/pages/IEM/157789644737?v=wall&story_fbid=".$fbid;
/* Hehe, check for a IEM vote! */
$voted = 0;
if (array_key_exists('foid', $_COOKIE) && $_COOKIE["foid"] == $foid)
{
	$voted = 1;
} elseif (getenv("REMOTE_ADDR") == "129.186.142.22" || getenv("REMOTE_ADDR") == "129.186.142.37")
{

} elseif (isset($_GET["feature_good"]))
{
	setcookie("foid", $foid, time()+100600);
	$voted = 1;

	$isql = "UPDATE feature SET good = good + 1 WHERE oid = $foid";
	$good += 1;
	pg_exec($connection, $isql);
} elseif (isset($_GET["feature_bad"]))
{
	setcookie("foid", $foid, time()+100600);
	$voted = 1;

	$isql = "UPDATE feature SET bad = bad + 1 WHERE oid = $foid";
	$bad += 1;
	pg_exec($connection, $isql);
}


$fref = "/mesonet/share/features/". $row["imageref"] ."_s.png";
$width = 320;
$height = 240;
if (is_file($fref)){
	list($width, $height, $type, $attr) = @getimagesize($fref);
}
$imghref = sprintf("%s/onsite/features/%s_s.png", ROOTURL, $row["imageref"]);
?>

<div class="panel panel-default top-buffer">
  <div class="panel-heading">
  <b>IEM Daily Feature</b> &nbsp; <a href="/feature_rss.php"><img src="/images/rss.gif" /></a>
  <div class="btn-group pull-right">
<a class="btn btn-default" href="<?php echo $fburl; ?>">Facebook</a>
<a class="btn btn-default" href="/onsite/features/cat.php?day=<?php echo $row["permalink"]; ?>">Permalink</a>
<a class="btn btn-default" href="/onsite/features/past.php">Past Features</a>
<a class="btn btn-default" href="/onsite/features/tags/">Tags</a>
	</div>
	<div class="clearfix"></div>
  </div>
  <div class="panel-body">

  <h4 style="display: inline;"><?php echo $row["title"]; ?></h4>
 
<div class="pull-left">
<?php 
echo "<small>Posted: ". $row["webdate"] ."</small>";
echo "<img src=\"$imghref\" alt=\"Feature\" class=\"pull-right\" />";
echo "<br /><small>Tags: &nbsp; ";
while (list($k,$v) = each($tags))
{
	echo sprintf("<a href=\"/onsite/features/tags/%s.html\">%s</a> &nbsp; ", $v, $v);
}
echo "</small>";

echo "<br />". $row["story"] ;

/* Rate Feature and Past ones too! */
if ($row["voting"] == "f"){

} else {
	echo "<div style='clear:both;'>";
	if ($voted){
		$goodurl = "/";
		$badurl = "/";
		$msg = "Thanks for voting!";
	} else {
		$goodurl = "/?feature_good";
		$badurl = "/?feature_bad";
		$msg = "Rate Feature";
	}

	echo "<strong>$msg</strong> 
	<a class=\"btn btn-success\" href=\"$goodurl\">Good ($good votes)</a>
	<a class=\"btn btn-danger\" href=\"$badurl\">Bad ($bad votes)</a></div>";
	
	echo "<div class=\"container\"><div id=\"fb-root\"></div><script src=\"http://connect.facebook.net/en_US/all.js#appId=196492870363354&amp;xfbml=1\"></script>
	<fb:comments send_notification_uid=\"16922938\" callback=\"/fbcb.php\" title=\"". $row["title"] ."\" \" href=\"/onsite/features/cat.php?day=". $row["permalink"] ."\" xid=\"$fbid\" numposts=\"6\" width=\"520\"></fb:comments>";

	echo "</div></div>";
}
/* Now, lets look for older features! */
echo "<br /><strong>Previous Years' Features</strong>";
$sql = "select *, extract(year from valid) as yr from feature 
		WHERE extract(month from valid) = extract(month from now()) 
		and extract(day from valid) = extract(day from now()) and 
		extract(year from valid) != extract(year from now()) ORDER by yr DESC";
$result = pg_exec($connection, $sql);
for($i=0;$row=@pg_fetch_array($result,$i);$i++)
{
	// Start a new row
	if ($i % 2 == 0){ echo "\n<div class=\"row\">"; }
	echo "\n<div class=\"col-md-6\">". $row["yr"] .": <a href=\"onsite/features/cat.php?day=". substr($row["valid"], 0, 10) ."\">". $row["title"] ."</a></div>";
	// End the row
	if ($i % 2 != 0){ echo "\n</div>\n"; }
}

if ($i % 2 != 0){ echo "\n<div class=\"col-md-6\">&nbsp;</div>\n</div>"; }
?>


</div><!--  end of panel body -->
</div>
        </div><!--/span-->
        <div class="col-md-3">
          <div class="sidebar-nav">
<?php 
include_once(ROOTPATH ."/include/cameras.inc.php");
$rancam = "";
$loop = 0;
while ($rancam == "" && $loop < 20)
{
  srand ((float) microtime() * 10000000);
  $t = array_rand($cameras);
  if (@filemtime("/home/ldm/data/camera/stills/${t}.jpg") > (time() - 1200))
  {
    $rancam = $t;
  }
  $loop += 1;
}
if ($rancam == ""){ $rancam = "KCWI-001";}
?>
<div class="panel panel-default">
  <div class="panel-heading"><?php echo $cameras[$rancam]["name"] .", ". $cameras[$rancam]["state"]; ?> Webcam:</div>
  <div class="panel-body">
<a href="/current/webcam.php#<?php echo  $cameras[$rancam]["network"]; ?>-0"><img src="/data/camera/stills/<?php echo $rancam; ?>.jpg?<?php echo time(); ?>" border="0" alt="Webcam" class="img-responsive"/></a>
<a href="/current/webcam.php#<?php echo  $cameras[$rancam]["network"]; ?>-0">View other webcams</a>
  
  </div>
</div>


<div class="panel panel-default">
  <div class="panel-heading">Most Popular</div>
  <div class="panel-body">
<a href="/timemachine/#1.0">Iowa Mesonet Plot</a>
  [<a href="/current/loop.phtml?prod=mesonet">Loop</a>]
<br /><a href="/current/mcview.phtml?prod=comprad&amp;java=none&amp;mode=realtime&amp;frames=1">Current NEXRAD</a> [<a href="/current/mcview.phtml">Loop</a>]
<br /><a href="/GIS/apps/iem/freeze.phtml">IEM Freeze</a>
<br /><a href="/rainfall/">IEM GIS Rainfall</a>
<br /><a href="/my/current.phtml">Sortable Currents</a>
<br /><a href="/onsite/features/tags/winter1213.html">Winter Storms of 2012-2013</a>

    </div>
</div>



<div class="panel panel-default">
  <div class="panel-heading">News Items &nbsp; <a href="/rss.php"><img src="/images/rss.gif" /></a></div>
  <div class="panel-body">
<?php 
$rs = pg_query($connection, "SELECT * from news ORDER by entered DESC LIMIT 5");

$today = mktime(0,0,0, date("m"), date("d"), date("Y"));

for ($i=0; $row = @pg_fetch_array($rs, $i); $i++){
	$ts = strtotime(substr($row["entered"],0,16));
	if ($ts > $today) $sts = strftime("%I:%M %p", $ts);
	else $sts = strftime("%d %b %I:%M %p", $ts);
	echo "<p><a href=\"/onsite/news.phtml?id=".$row["id"]."\">". $row["title"] ."</a><br /><i>Posted:</i> $sts</li>\n";
}

?>

<p><b class='glyphicon-envelope'></b>
<a href="/mailman/listinfo/dailyb">Sign up</a> for the 
<a href="/data/iemdb.html">Daily Bulletin</a></p>

  </div>
</div>

          </div><!--/.well -->
        </div><!--/span-->
      </div><!--/row-->

<!-- Three columns highlighting stuff -->
<div class="row">
    <div class="col-md-4">
        <h3>RADAR Products</h3>
        <img src="/data/mwcomp.png" class="img-responsive" />
        <p>The IEM processes National Weather Service NEXRAD information
        in real-time to produce and archive many products. This includes a 
        generated <a href="/docs/nexrad_composites/">composite</a> produced
        every five minutes dating back to 1995!</p>
        <p><a class="btn" href="/current/radar.phtml">View more products &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h3>Precipitation</h3>
        <img src="/data/iowa_q2_1d.png" class="img-responsive" />
        <p>Besides point observations of precipitation, the IEM also processes
        gridded rainfall products made available by NOAA.  This information
        is archived and made available in GIS ready formats.</p>
        <p><a class="btn" href="/rainfall/">Download Precipitation for GIS &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h3>Current Data</h3>
        <img src="/data/iowa_tmpf.png" class="img-responsive" />
        <p>The IEM combines data from participating networks into products
        like maps shown above and web applications to analyze the data.</p>
        <p><a class="btn" href="/current/">More current products &raquo;</a></p>
    </div>
</div><!--/row-->

<div class="row clearfix well">
<div class="col-md-1"><h4>Partners:</h4></div>
<div class='col-md-2'>
<a href="http://www.agron.iastate.edu/initiatives/default.html"><img
src="/images/ptfmark.gif" alt="Agronomy Path to the Future" class="img-responsive"></a>
</div>
<div class='col-md-2'>
<a href="http://www.iihr.uiowa.edu"><img src="images/iihrlogo.jpg"
  alt="IIHR - University of Iowa" class="img-responsive" /></a>
</div>
<div class='col-md-3'>
 <a href="http://www.dot.state.ia.us"><img src="images/doticon.gif"
 alt="DOT" class="img-responsive" /></a>
</div>
<div class='col-md-2'>
  <a href="http://www.iastate.edu"><img src="images/isuicon.gif" alt="ISU"
  class="img-responsive" /></a>
</div>
<div class='col-md-2'>
  <a href="http://www.crh.noaa.gov/dmx/"><img src="images/nws.gif"
  alt="NWS" class="img-responsive" /></a>
</div>

</div>

</div><!--/.container-->

<?php include 'footer.phtml'; ?>