<?php 
if (isset($this)){
	$THISPAGE = array_key_exists('thispage', $this->vars)? $this->thispage : 'xxx-xxx';
} else{
	$THISPAGE = isset($THISPAGE) ? $THISPAGE: 'xxx-xxx';
}
$_pages = Array(
	"archive" => Array(
		"title" => "Archive", 
		"subs" => Array(
			"base" => Array("title" => "Archive Mainpage", "url" => "/archive/"),
			"api" => Array("title" => "API", "url" => "/api/"),
			"schema" => Array("title" => "Archive Schema", "url" => "/archive/schema.php"),
			"browse" => Array("title" => "Browse data/", "url" => "/archive/data/"),
			"hrain" => Array("title" => "Hourly Precip", "url" => "/rainfall/obhour.phtml"),
			"iemre" => Array("title" => "IEM Reanalysis", "url" => "/iemre/"),
			"cases" => Array("title" => "Interesting Cases", "url" => "/cases/"),
			"mos" => Array("title" => "Model Output Statistics", "url" => "/mos/"),
			"afos" => Array("title" => "NWS Text Products", "url" => "/wx/afos/list.phtml"),
			"pireps" => Array("title" => "PIREPs", "url" => "/request/gis/pireps.php"),
			"smos" => Array("title" => "Soil Moisture Satellite", "url" => "/smos/"),
			"raob" => Array("title" => "Sounding Archive", "url" => "/archive/raob/"),
			"tm" => Array("title" => "Time Machine", "url" => "/timemachine/"),
		),
	),
	"climatology" => Array(
		"title" => "Climate",
		"subs" => Array(
			"base" => Array("title" => "Climate Mainpage", "url" => "/climate/"),
			"extremes" => Array("title" => "Daily Climatology", "url" => "/COOP/extremes.php"),
			"main" => Array("title" => "Mainpage", "url" => "/climate/"),
			"climodat" => Array("title" => "Climodat", "url" => "/climodat/"),
			"climodatm" => Array("title" => "Climodat Monitor", "url" => "/climodat/monitor.php"),
			"drought" => Array("title" => "Drought", "url" => "/dm/"),
			"today" => Array("title" => "Today", "url" => "/climate/today.phtml"),
			"yesterday" => Array("title" => "Yesterday", "url" => "/climate/yesterday.phtml"),
			"week" => Array("title" => "Week", "url" => "/climate/week.phtml"),
			"month" => Array("title" => "Month", "url" => "/climate/month.phtml"),
			"gs" => Array("title" => "Growing Season", "url" => "/climate/gs.phtml"),
			"year" => Array("title" => "Year", "url" => "/climate/year.phtml"),
		),
	),
	"current" => Array(
		"title" => "Current",
		"subs" => Array(
			"base" => Array("title" => "Current Mainpage", "url" => "/current/"),
			"api" => Array("title" => "API", "url" => "/api/"),
			"plotter" => Array("title" => "Auto Data Plotter", "url" => "/plotting/auto/"),
			"placefiles" => Array("title" => "Gibson Ridge Placefiles", "url" => "/request/grx/"),
			"gs" => Array("title" => "Growing Season", "url" => "/current/gs.phtml"),
			"jsonp" => Array("title" => "JSON Webservices", "url" => "/json/"),
			"afos" => Array("title" => "NWS Text", "url" => "/wx/afos/"),
			"products" => Array("title" => "Products", "url" => "/current/"),
			"radar" => Array("title" => "RADAR & Satellite", "url" => "/current/radar.phtml"),
			"sort" => Array("title" => "Sortable Currents", "url" => "/my/current.phtml"),
		),
	),
	"iem" => Array(
		"title" => "Info",
		"subs" => Array(
			"base" => Array("title" => "Info Mainpage", "url" => "/info.php"),
			"agweater" => Array("title" => "Ag Weather/Climate Info", "url" => "/agweather/"),
			"apps" => Array("title" => "Application Index", "url" => "/apps.php"),
			"feature" => Array("title" => "Daily Features", "url" => "/onsite/features/past.php"),
			"links" => Array("title" => "Links", "url" => "/info/links.php"),
			"networks" => Array("title" => "Network Tables", "url" => "/sites/networks.php"),
			"news" => Array("title" => "News", "url" => "/onsite/news.phtml"),
			"present" => Array("title" => "Presentations", "url" => "/present/"),
			"sites" => Array("title" => "Station Data and Metadata", "url" => "/sites/locate.php"),
			"qc" => Array("title" => "Quality Control", "url" => "/QC/"),
			"variables" => Array("title" => "Variables", "url" => "/info/variables.phtml"),
		),
	),
	"gis" => Array(
		"title" => "GIS",
		"subs" => Array(
			"base" => Array("title" => "GIS Mainpage", "url" => "/GIS/"),
			"browse" => Array("title" => "Browse Data", "url" => "/data/gis/"),
			"nexrad" => Array("title" => "NEXRAD Mosaic", "url" => "/docs/nexrad_mosaic/"),
			"ogc" => Array("title" => "OGC Webservices", "url" => "/ogc/"),
			"rainfall" => Array("title" => "Rainfall Data", "url" => "/rainfall/"),
			"radmap" => Array("title" => "RadMap API", "url" => "/GIS/radmap_api.phtml"),
			"radview" => Array("title" => "RADAR Services", "url" => "/GIS/radview.phtml"),
			"satellite" => Array("title" => "Satellite Data", "url" => "/GIS/goes.phtml"),
		),
	),
	"networks" => Array(
		"title" => "Networks",
		"subs" => Array(
			"base" => Array("title" => "Networks Mainpage", "url" => "/"),
			"asos" => Array("title" => "ASOS", "url" => "/ASOS/"),
			"awos" => Array("title" => "AWOS", "url" => "/AWOS/"),
			"cocorahs" => Array("title"=> "CoCoRaHS", "url" => "/cocorahs/"),
			"coop" => Array("title" => "NWS COOP", "url" => "/COOP/"),
			"dcp" => Array("title" => "DCP", "url" => "/DCP/"),
			"agclimate" => Array("title" => "ISU Soil Moisture", "url" => "/agclimate/"),
			"flux" => Array("title" => "NLAE Flux", "url" => "/nstl_flux/"),
			"rwis" => Array("title" => "RWIS", "url" => "/RWIS/"),
			"scan" => Array("title" => "SCAN", "url" => "/scan/"),
			"schoolnet" => Array("title" => "SchoolNet", "url" => "/schoolnet/"),
			"other" => Array("title" => "Other", "url" => "/other/"),
		),
	),
	"roads" => Array(
		"title" => "Roads",
		"subs" => Array(
			"base" => Array("title" => "Roads Mainpage", "url" => "/roads/"),
			"gis" => Array("title" => "GIS Products", "url" => "/roads/gis.phtml"),
			"history" => Array("title" => "Historical", "url" => "/roads/history.phtml"),
			"maps" => Array("title" => "Interactive Map", "url" => "/roads/maps.phtml"),
			"sort" => Array("title" => "Sortable Text", "url" => "/roads/rc.phtml"),
		),
	), 
	"severe" => Array(
		"title" => "Svr Wx",
		"icon" => "flash",
		"subs" => Array(
			"base" => Array("title" => "Severe Weather Mainpage", "url" => "/current/severe.phtml"),
			"cow" => Array("title" => "IEM Cow (SBW Verification)", "url" => "/cow/"),
			"iembot" => Array("title" => "iembot", "url" => "/projects/iembot/"),
			"interact" => Array("title" => "Interact Radar", "url" => "/GIS/apps/rview/warnings.phtml"),
			"lsr" => Array("title" => "Local Storm Report App", "url" => "/lsr/"),
			"raccoon" => Array("title" => "IEM Raccoon (SBW Powerpoints)", "url" => "/raccoon/"),
			"river" => Array("title" => "River Summary", "url" => "/river/"),
			"search" => Array("title" => "Search for Warnings", "url" => "/vtec/search.php"),
			"spcoutlook" => Array("title" => "SPC Convective Outlook / MCD Search", "url" => "/nws/spc_outlook_search/"),
			"watch" => Array("title" => "SPC Watches", "url" => "/GIS/apps/rview/watch.phtml"),
			"vtec" => Array("title" => "VTEC Browser", "url" => "/vtec/"),
		),
	),
	"webcam" => Array(
		"title" => "Webcams",
		"icon" => "camera",
		"subs" => Array(
			"base" => Array("title" => "Webcam mainpage", "url" => "/projects/webcam.php"),
			"loop" => Array("title" => "Build your own lapses", "url" => "/current/bloop.phtml"),
			"cool" => Array("title" => "Cool lapses", "url" => "/cool/"),
			"viewer" => Array("title" => "IEM Webcam Viewer", "url" => "/current/viewer.phtml"),
		    "isu" => Array("title" => "ISU Campus Webcams", "url" => "/current/isucams.phtml"),
		    "lapse" => Array("title" => "Recent lapses", "url" => "/current/camlapse/"),
			"stills" => Array("title" => "Still images", "url" => "/current/webcam.php"),
			),
	),
);
?>
<header>
<nav class="navbar-iastate">
	<div class="container">
		<!-- navbar-iastate-left -->
		<ul class="nav navbar-nav navbar-iastate-left">
			<li><a href='https://www.iastate.edu'>iastate.edu</a></li>
			<li class="dropdown dropdown-hover isu-index">
				<a href="https://www.iastate.edu/index/A" class="dropdown-toggle" data-toggle="" role="button" aria-haspopup="true" aria-expanded="false">Index</a>
				<ul class="dropdown-menu isu-index-alpha">
					<li><a href="https://www.iastate.edu/index/A/">A</a></li>
					<li><a href="https://www.iastate.edu/index/B/">B</a></li>
					<li><a href="https://www.iastate.edu/index/C/">C</a></li>
					<li><a href="https://www.iastate.edu/index/D/">D</a></li>
					<li><a href="https://www.iastate.edu/index/E/">E</a></li>
					<li><a href="https://www.iastate.edu/index/F/">F</a></li>
					<li><a href="https://www.iastate.edu/index/G/">G</a></li>
					<li><a href="https://www.iastate.edu/index/H/">H</a></li>
					<li><a href="https://www.iastate.edu/index/I/">I</a></li>
					<li><a href="https://www.iastate.edu/index/J/">J</a></li>
					<li><a href="https://www.iastate.edu/index/K/">K</a></li>
					<li><a href="https://www.iastate.edu/index/L/">L</a></li>
					<li><a href="https://www.iastate.edu/index/M/">M</a></li>
					<li><a href="https://www.iastate.edu/index/N/">N</a></li>
					<li><a href="https://www.iastate.edu/index/O/">O</a></li>
					<li><a href="https://www.iastate.edu/index/P/">P</a></li>
					<li><a href="https://www.iastate.edu/index/Q/">Q</a></li>
					<li><a href="https://www.iastate.edu/index/R/">R</a></li>
					<li><a href="https://www.iastate.edu/index/S/">S</a></li>
					<li><a href="https://www.iastate.edu/index/T/">T</a></li>
					<li><a href="https://www.iastate.edu/index/U/">U</a></li>
					<li><a href="https://www.iastate.edu/index/V/">V</a></li>
					<li><a href="https://www.iastate.edu/index/W/">W</a></li>
					<li><a href="https://www.iastate.edu/index/X/">X</a></li>
					<li><a href="https://www.iastate.edu/index/Y/">Y</a></li>
					<li><a href="https://www.iastate.edu/index/Z/">Z</a></li>
				</ul>
			</li>
		</ul>
		<!-- /navbar-iastate-left -->

		<!-- navbar-iastate-right -->
		<ul class="nav navbar-nav navbar-right navbar-iastate-right">
			<li><a href="https://info.iastate.edu/">Directory</a></li>
			<li><a href="https://www.fpm.iastate.edu/maps/">Maps</a></li>
			<li><a href="https://web.iastate.edu/safety/">Safety</a></li>
			<li class="dropdown dropdown-hover">
				<a href="//web.iastate.edu/signons/" class="dropdown-toggle" data-toggle="" role="button" aria-haspopup="true" aria-expanded="false">Sign Ons</a>
				<ul class="dropdown-menu">
					<li><a href="https://accessplus.iastate.edu/">AccessPlus</a></li>
					<li><a href="https://bb.its.iastate.edu/">Blackboard</a></li>
					<li><a href="https://iastate.box.com/">CyBox</a></li>
					<li><a href="https://cymail.iastate.edu/">CyMail</a></li>
					<li><a href="https://outlook.iastate.edu/">Outlook</a></li>
					<li><a href="https://web.iastate.edu/signons/">More Sign Ons...</a></li>
				</ul>
			</li>
		</ul>
		<!-- /navbar-iastate-right -->

	</div>
</nav>
<!-- /navbar-iastate -->

<nav class="navbar-site">
	<div class="container">

		<div class="navbar-site-wordmark">
			<a href="/" title="Home" class="wordmark-unit">
				<span class="wordmark-isu">Iowa State University</span>
				<span class="wordmark-unit-title">Iowa Environmental Mesonet</span>
			</a>
		</div>
 
		<div class="navbar-header visible-xs visible-sm">
			<button id="navbar-menu-button" type="button" class="navbar-toggle navbar-toggle-left collapsed" data-toggle="collapse" data-target="#navbar-menu-collapse, #navbar-site-links-collapse" aria-expanded="false">
				<span class="navbar-toggle-icon menu-icon">
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</span>
				<span class="navbar-toggle-label">
					Menu <span class="sr-only">Toggle</span>
				</span>
			</button>
			<button id="navbar-search-button" type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-site-search-collapse" aria-expanded="false">
				<span class="navbar-toggle-icon search-icon"></span>
				<span class="navbar-toggle-label">
					Search <span class="sr-only">Toggle</span>
				</span>
			</button>
		</div>

		<div class="navbar-site-info collapse navbar-collapse" id="navbar-site-search-collapse">
			<form action="https://www.google.com/search" class="navbar-site-search" method="GET" role="search">
				<label for="search-input" class="sr-only">Search</label>
				<input value="mesonet.agron.iastate.edu" name="sitesearch" type="hidden" />
				<input name="q" id="search-input" aria-label="Text input for search" title="Search" placeholder="Search" tabindex="0" type="text" class="form-control">
				<input class="hidden" title="Submit" type="submit" value="Search">
				<span class="search-icon"></span>
			</form>
		</div>

		<div class="navbar-site-info collapse navbar-collapse navbar-caps" id="navbar-site-links-collapse">
			<ul class="nav navbar-nav navbar-right">
				<!-- Site-wide links. Customized for your site -->
				<li><a href="/info/contacts.php">contact us</a></li>
				<li><a href="/disclaimer.php">disclaimer</a></li>
				<li><a href="/apps.php">apps</a></li>
			</ul>
		</div>

	</div>
</nav>
</header>

<div class="container">
<div class="navbar navbar-default">
    <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
        </button>
	</div>
    <div class="navbar-collapse collapse">
    	<div class="hidden-xs hidden-sm">
        <a href="/"><img style="height: 50px;" alt="IEM" class="img-responsive pull-left" src="/images/logo_small.png" /></a>
		</div>
        <ul class="nav navbar-nav">
        
<li class="dropdown"><a class="dropdown-toggle" data-toggle="dropdown" 
	href="#"> <span class="fa fa-home"></span> </a>
	<ul class="dropdown-menu">
        <li><a href="https://mesonet.agron.iastate.edu/projects/iao/">Iowa Atmospheric Observatory</a></li>
		<li><a href="https://mesonet.agron.iastate.edu">Iowa Environmental Mesonet</a></li>
	    <li><a href="https://iowa.cocorahs.org">Iowa CoCoRaHS</a></li>
		<li><a href="https://dailyerosion.org">Daily Erosion Project</a></li>
		<li><a href="https://weather.im">Weather.IM Project</a></li>
	</ul></li>
        
<?php 
$ar = preg_split('/-/', $THISPAGE);
function get_title($page){
	/*if (array_key_exists("icon", $page)){
		return sprintf("<span class=\"fa fa-%s visible-sm\"></span>"
				."<div class=\"hidden-sm\">%s</div>",
				$page["icon"], $page["title"]);
	}*/
	return sprintf("%s", $page["title"]);
}

foreach($_pages as $idx => $page)
{
  	echo sprintf("<li class=\"dropdown%s\">\n<a class=\"dropdown-toggle\" 
		data-toggle=\"dropdown\" href=\"#\">%s</a>\n", 
      ($ar[0] == $idx) ? " active" : "", get_title($page));

    echo "<ul class=\"dropdown-menu\">\n";
    foreach($page["subs"] as $idx2 => $page2)
    {
       echo sprintf("<li><a%s href=\"%s\">%s</a></li>\n", 
         ($ar[1] == $idx2 && $ar[0] == $idx) ? " class=\"active\"" : "",
           $page2["url"],  $page2["title"] );
    }
    echo "</ul>\n</li>\n";
}
  ?>
</ul>
        </div>
      </div>
    </div>
</div>