<?php include 'header.phtml'; ?>
<?php include 'navbar.phtml'; ?>
<div class="container">
<?php 
if (array_key_exists('north', $this->vars)){
	echo "<div class=\"row\"><div class=\"col-md-12\">\n";
	echo $this->vars['north'];
	echo "</div></div>\n";
}
if (array_key_exists('east', $this->vars) && 
    array_key_exists('west', $this->vars)){
	echo "<div class=\"row\"><div class=\"col-md-6\">\n";
	echo $this->vars['west'];
	echo "</div><div class=\"col-md-6\">\n";
	echo $this->vars['east'];
	echo "</div></div>\n";
}
if (array_key_exists('content', $this->vars)){
  echo "<div class=\"row\"><div class=\"col-md-12\">\n";
  echo $this->vars['content'];
  echo "</div></div>\n";
}
if (array_key_exists('south', $this->vars)){
	echo "<div class=\"row\"><div class=\"col-md-12\">\n";
	echo $this->vars['south'];
	echo "</div></div>\n";
}
?>
</div><!--/.container-->
<?php include 'footer.phtml'; ?>