<?php 
global $metadata;
global $station;
global $network;
?>
<div class="hidden-print">
<strong><?php echo $metadata["name"]; ?> Links:</strong>
<p>
<?php
$o = Array(
  "base" => Array("name" => "Information", "uri" => "site.php?"),
  "current" => Array("name" => "Last Ob", "uri" => "current.php?"),
  "pics" => Array("name" => "Photographs", "uri" => "pics.php?"),
  "cal" => Array("name" => "Calibration", "uri" => "cal.phtml?"),
  "meteo" => Array("name" => "Meteogram", "uri" => "meteo.php?"),
	"tables" => Array("name" => "Network Table", "uri" => "networks.php?"),
  "neighbors" => Array("name" => "Neighbors", "uri" => "neighbors.php?"),
  "7dayhilo" => Array("name" => "7 Day High/Low Plot", "uri" => "plot.php?prod=0&amp;"),
  "monthhilo" => Array("name" => "Month High/Low Plot", "uri" => "plot.php?prod=1&amp;"),
  "monthrain" => Array("name" => "Month Rainfall Plot", "uri" => "plot.php?prod=2&amp;"),
  "obhistory" => Array("name" => "Observation History", "uri" => "obhistory.php?",
	"azos" => True, "rwis" => True),
  "windrose" => Array("name" => "Wind Roses", "uri" => "windrose.phtml?"),
  "custom_windrose" => Array("name" => "Custom Wind Roses", "uri" => "dyn_windrose.phtml?"),
  "calendar" => Array("name" => "Data Calendar", "uri" => "hist.phtml?"),
);

while (list($key,$val) = each($o))
{
	if ((array_key_exists("azos", $val) &&  preg_match('/ASOS|AWOS|ISUSM/', $network) <= 0) &&
		(array_key_exists("rwis", $val) &&  preg_match('/RWIS/', $network) <= 0)){
		continue;
	}
  	$uri = sprintf("%sstation=%s&amp;network=%s", $val["uri"], $station, $network);
  	echo "<div style=\"";
  	if ($this->sites_current == $key) echo "background: #eaf;";
  	echo "width: 150px; float: left; padding-left: 10px;\"><a href=\"$uri\">". $val["name"] ."</a></div>";
}

if (preg_match('/ASOS|AWOS/', $network) > 0){
	$uri = sprintf("/request/download.phtml?network=%s", $network);
	echo "<div style=\"width: 150px; float: left; padding-left: 10px; border-left: 4px solid #0F0;\"><a href=\"$uri\">Download</a></div>";
}elseif (preg_match('/DCP/', $network) > 0){
	$uri = sprintf("/request/dcp/fe.phtml?network=%s", $network);
	echo "<div style=\"width: 150px; float: left; padding-left: 10px; border-left: 4px solid #0F0;\"><a href=\"$uri\">Download</a></div>";
	
}
?>
<br />
<form method="GET" name="automatic">
<?php 
if (isset($savevars)){
	while (list($k,$v)=each($savevars)){
		echo sprintf("<input type=\"hidden\" value=\"%s\" name=\"%s\" />",
		$v, $k);
	}
}
if (isset($_REQUEST["prod"])){
	echo "<input type='hidden' name='prod' value='". $_REQUEST["prod"] ."'>\n";
}
if (isset($_REQUEST["month"])){
	echo "<input type='hidden' name='month' value='". $_REQUEST["month"] ."'>\n";
}
if (isset($_REQUEST["year"])){
	echo "<input type='hidden' name='year' value='". $_REQUEST["year"] ."'>\n";
}
if (isset($_REQUEST["day"])){
	echo "<input type='hidden' name='day' value='". $_REQUEST["day"] ."'>\n";
}
?>
<input type="hidden" name="network" value="<?php echo $network; ?>">
<p>Other Sites in network:
<?php 
include_once(dirname(__FILE__)."/../imagemaps.php");
echo networkSelectAuto($network, $station); 
?>
 or <a href="locate.php?network=<?php echo $network; ?>">select from map</a>
</form>
</div>
