<?php 
global $metadata;
global $station;
global $network;
require_once dirname(__FILE__)."/../imagemaps.php";
?>
<div class="hidden-print">
<form method="GET" name="automatic">
<?php 
if (isset($savevars)){
	foreach($savevars as $k => $v){
		echo sprintf("<input type=\"hidden\" value=\"%s\" name=\"%s\" />",
		$v, $k);
	}
}
if (isset($_REQUEST["prod"])){
	echo "<input type='hidden' name='prod' value='". xssafe($_REQUEST["prod"]) ."'>\n";
}
if (isset($_REQUEST["month"])){
	echo "<input type='hidden' name='month' value='". xssafe($_REQUEST["month"]) ."'>\n";
}
if (isset($_REQUEST["year"])){
	echo "<input type='hidden' name='year' value='". xssafe($_REQUEST["year"]) ."'>\n";
}
if (isset($_REQUEST["day"])){
	echo "<input type='hidden' name='day' value='". xssafe($_REQUEST["day"]) ."'>\n";
}
?>
<input type="hidden" name="network" value="<?php echo $network; ?>">
<ol class="breadcrumb">
<li><a href="/sites/locate.php">Station Data &amp; Metadata</a></li>
<li><a href="/sites/locate.php?network=<?php echo $network; ?>"><?php echo $network; ?></a></li>
<li class="active"><?php echo networkSelectAuto($network, $station); ?> or <a href="locate.php?network=<?php echo $network; ?>">select from map</a></li>
</ol>
</form>

<p>
<?php
$o = Array(
  "base" => Array("name" => "Information", "uri" => "site.php?",
  		"metaok" => TRUE, "icon" => "info-circle"),
  "current" => Array("name" => "Last Ob", "uri" => "current.php?",
  		"icon" => "clock"),
  "pics" => Array("name" => "Photographs", "uri" => "pics.php?",
  		"icon" => "camera"),
  "cal" => Array("name" => "Calibration", "uri" => "cal.phtml?",
		"icon" => "wrench",
		"networks" => Array("AWOS", "IA_RWIS", "ISUAG", "ISUSM")),
  "meteo" => Array("name" => "Meteogram", "uri" => "meteo.php?",
  		"icon" => "chart-area"),
  "tables" => Array("name" => "Network Table", "uri" => "networks.php?",
  		"metaok" => TRUE, "icon" => "table"),
  "neighbors" => Array("name" => "Neighbors", "uri" => "neighbors.php?",
  		"metaok" => TRUE, "icon" => "users"),
  "monthsum" => Array("name" => "Monthly Summaries",
  		"uri" => "monthlysum.php?", "icon" => "table"),
  "obhistory" => Array("name" => "Observation History",
  		"uri" => "obhistory.php?", "icon" => "time"),
  "windrose" => Array("name" => "Wind Roses",
  		"uri" => "windrose.phtml?", "icon" => "asterisk"),
  "custom_windrose" => Array("name" => "Custom Wind Roses",
  		"uri" => "dyn_windrose.phtml?", "icon" => "asterisk"),
  "calendar" => Array("name" => "Data Calendar", "uri" => "hist.phtml?",
  		"icon" => "calendar"),
);

foreach($o as $key => $val)
{
	if ((array_key_exists("azos", $val) &&  preg_match('/ASOS|AWOS|ISUSM/', $network) <= 0) &&
		(array_key_exists("rwis", $val) &&  preg_match('/RWIS/', $network) <= 0)){
		continue;
	}
	if (array_key_exists("networks", $val) && !in_array($network, $val["networks"])){
		continue;
	}
	// Do not display links to pages that only work for sites that produce
	// data that we consume!
	if ($network == 'RAOB' && $key == 'custom_windrose'){
		
	}
	else if ($metadata["metasite"] == 't' && ! array_key_exists("metaok", $val)){
		continue;
	}
  	$uri = sprintf("%sstation=%s&amp;network=%s", $val["uri"], $station, $network);
  	$active = ($this->sites_current == $key) ? " active": "";
  	echo sprintf("<a href=\"%s\" class=\"btn btn-default%s\">".
  			"<span class=\"fa fa-%s\"></span> %s</a>",
  			$uri, $active, $val["icon"], $val["name"]);
}

if (preg_match('/ASOS|AWOS/', $network) > 0){
	$uri = sprintf("/request/download.phtml?network=%s", $network);
	echo sprintf("<a href=\"%s\" class=\"btn btn-default\"><span class=\"fa fa-download\"></span> Download</a>", 
			$uri);
}elseif (preg_match('/DCP/', $network) > 0){
	$uri = sprintf("/request/dcp/fe.phtml?network=%s", $network);
	echo sprintf("<a href=\"%s\" class=\"btn btn-default\"><span class=\"fa fa-download\"></span> Download</a>", 
			$uri);
	
}
?>
</p>
</div>
