<?php 
include 'header.phtml'; 
include 'navbar.phtml';
echo "<main role=\"main\" id=\"main-content\">";
echo "<div class=\"container-fluid\">";

include 'sitebar.phtml';

if (array_key_exists('north', $this->vars)){
    echo "<div class=\"row\"><div class=\"col-md-12\">\n";
    echo $this->vars['north'];
    echo "</div></div>\n";
}
if (array_key_exists('east', $this->vars) && 
    array_key_exists('west', $this->vars)){
    echo "<div class=\"row\"><div class=\"col-md-6\">\n";
    echo $this->vars['west'];
    echo "</div><div class=\"col-md-6\">\n";
    echo $this->vars['east'];
    echo "</div></div>\n";
}
if (!is_null($this->content)){
  echo "<div class=\"row\"><div class=\"col-md-12\">\n";
  echo $this->content;
  echo "</div></div>\n";
}
if (array_key_exists('south', $this->vars)){
    echo "<div class=\"row\"><div class=\"col-md-12\">\n";
    echo $this->vars['south'];
    echo "</div></div>\n";
}
echo "</div><!--/.container-->";
echo "</main>";
include 'footer.phtml';
