<?php
include("../../config/settings.inc.php");
include("$rootpath/include/database.inc.php");
$pgconn = iemdb("hads");
include("$rootpath/include/forms.php");
include("$rootpath/include/network.php");
$nt = new NetworkTable( Array("IA_DCP") );
$cities = $nt->table;

$minute = isset($_GET['minute']) ? $_GET["minute"] : 0;
$hour = isset($_GET['hour']) ? $_GET["hour"] : date("H");
$day = isset($_GET['day']) ? $_GET["day"] : date("d");
$month = isset($_GET['month']) ? $_GET["month"] : date("m");
$year = isset($_GET['year']) ? $_GET["year"] : date("Y");
$now = time() - 3600;
$ts = mktime($hour, $minute, 0, $month, $day, $year);

$THISPAGE = "networks-dcp";
$TITLE = "IEM | GOES DCP";
include("$rootpath/include/header.php"); 
?>
<h3>DCP Data Report for time: <?php echo date("d M Y h:i a", $ts); ?></h3>

<p>This application will display a table of observations valid at a given
time.  The SHEF encoded variable identifier is used to show which sites
reported which variables.  All times displayed are in central 
standard/daylight time.  If you click on the site identifier, you will
get a listing of all observations for that site for the date of your 
choice.


<form method="GET" action="cat.phtml">
<table>
<tr>
  <th>Year</th>
  <th>Month</th>
  <th>Day</th>
  <th>Hour</th>
  <th>Minute</th>
  <td></td>
</tr>

<tr>
  <td><?php echo yearSelect(2002, $year, "year"); ?></td>
  <td><?php echo monthSelect($month); ?></td>
  <td><?php echo daySelect($day); ?></td>
  <td><?php echo hourSelect($hour, 'hour'); ?></td>
  <td><select name="minute">
    <option value="00" <?php if ($minute == "00") echo "SELECTED"; ?>>00
    <option value="15" <?php if ($minute == "15") echo "SELECTED"; ?>>15
    <option value="30" <?php if ($minute == "30") echo "SELECTED"; ?>>30
    <option value="45" <?php if ($minute == "45") echo "SELECTED"; ?>>45
   </select></td>
  <td><input type="Submit" value="View Data"></td>
</tr>

</table>
</form>

<b>Legend:</b>  TAI = Air Temp (F), PCI = Rainfall Counter, PPH = Hourly Precip, UDI = Wind Direction, USI = Wind Speed
<?php

$tbl = strftime("raw%Y_%m", $ts);
$dstr = strftime("%Y-%m-%d %H:%M", $ts);
$ldate = strftime("%d %b %Y %I:%M %p", $ts);

$rs = pg_prepare($pgconn, "SELECT", "SELECT * from $tbl WHERE valid = $1 and station ~* 'I4$'");

$rs = pg_execute($pgconn, "SELECT", Array($dstr) );
pg_close($pgconn);

/* Load up the data into a big fat array */
$data = Array();
$datakeys = Array();
for( $i=0; $row = @pg_fetch_array($rs,$i); $i++)
{
  $station = $row["station"];
  if (! array_key_exists($station, $cities)){ continue; }
  $data[ $row["station"] ][ substr($row["key"],0,3) ] = $row["value"];
  $datakeys[ substr($row["key"],0,3) ]= 1;
}
$stations = array_keys( $data );
$keys = array_keys( $datakeys );
asort($stations);
asort($keys);
?>

<table cellpadding="1" cellspacing="0" border="1">
<?php
$header = "<tr style=\"background: #eee;\">
 <th>NWS ID</th><th>Station</th>";
while ( list($k,$v) = each($keys)){
  $header .= sprintf("<th>%s</th>", $v);
}
$header .= "</tr>";

$row = 0;
while ( list($k,$v) = each($stations)){
  if ($row % 25 == 0){ echo $header; }
  $row += 1;

  echo sprintf("<tr><td><a href='site.phtml?station=%s&year=%s&month=%s&day=%s'>%s</a></td><td>%s</td>", $v, date("Y", $ts), date("m", $ts), date("d", $ts), $v, $cities[$v]['name']);
  reset($keys);
  while ( list($k,$key) = each($keys)){
    echo @sprintf("<td>%s</td>", $data[$v][$key]);
  }
  echo "</tr>";
}
?>
</table>

<?php include("$rootpath/include/footer.php"); ?>
