<?php
 include("../../config/settings.inc.php");
 define("IEM_APPID", 75);
 include_once "$rootpath/include/database.inc.php";
 $pgconn = iemdb('iem');
 $mesosite = iemdb('mesosite');
  
 $sortcol = isset($_GET['sortcol']) ? $_GET['sortcol'] : "valid";
 $network = isset($_GET['network']) ? $_GET["network"] : 'IA_DCP';
 $shef = isset($_REQUEST['shef']) && $_REQUEST['shef'] == 'yes';

 $TITLE = "IEM | DCP/GOES Current Conditions";
 $REFRESH = "<meta http-equiv=\"refresh\" content=\"600;\">";
 $THISPAGE = "current-sort";
 include("$rootpath/include/header.php");
?>
<a href="/DCP/">DCP Network</a> &nbsp; <b> > </b> &nbsp; Current Conditions
<?php

$cols = Array(
	"valid" => "Timestamp",		
		'station' => "Station ID",
		'name' => 'Station Name',
		'HGIZ' => 'Water Stage Height',
		'TAIZ' => 'Air Temperature',
		'PPHZ' => '1 Hour Precip',
		'PPDZ' => 'Today Precip',
		);

function aSortBySecondIndex($multiArray, $secondIndex) {
	while (list($firstIndex, ) = each($multiArray))
		$indexMap[$firstIndex] = @$multiArray[$firstIndex][$secondIndex];        arsort($indexMap);
	while (list($firstIndex, ) = each($indexMap))
		if (is_numeric($firstIndex))
		$sortedArray[] = $multiArray[$firstIndex];
	else $sortedArray[$firstIndex] = $multiArray[$firstIndex];
	return $sortedArray;
}


 $rs = pg_prepare($pgconn, "SELECT", "select station, valid, value, 
 		physical_code, duration, source, extremum , name from 
 		current_shef c JOIN stations s on (c.station = s.id) 
 		where s.network = $1");
 $rs = pg_execute($pgconn, "SELECT", Array($network));

 $obs = Array();
 for($i=0;$row=@pg_fetch_assoc($rs,$i);$i++){
 	$datakey = sprintf("%s%s%s", $row["physical_code"], $row["duration"],
 			$row["extremum"]);
 	$obs[ $row['station'] ][ $datakey ] = $row["value"]; 
 	$obs[ $row['station'] ][ 'valid' ] = strtotime($row["valid"]);
 	$obs[ $row['station'] ][ 'name' ] = $row["name"];
 }

 $final = aSortBySecondIndex($obs, $sortcol);
 
 $current_network = "DCP"; include("$rootpath/include/current_bar.inc.php"); 
?>
<form method="GET" action="current.phtml" name="myselector">
<input type="hidden" name="sortcol" value="<?php echo $sortcol; ?>">
<strong>Select Network:</strong> 
<select name="network">
<?php 
$rs = pg_query($mesosite, "SELECT id, name from networks where id ~* 'DCP' ORDER by name ASC");
for ($i=0;$row=@pg_fetch_assoc($rs,$i);$i++){
	$sel = '';
	if ($network == $row["id"]){
		$sel = " selected='SELECTED'";
	}
	echo sprintf("<option value='%s'%s>%s</option>\n",
	  $row["id"], $sel, $row["name"]);
}

?>
</select>

<strong>Show SHEF Codes:</strong>
<select name="shef">
	<option value="no" <?php echo ($shef) ? '': 'SELECTED'; ?>>No</option>
	<option value="yes" <?php echo ($shef) ? 'SELECTED': ''; ?>>Yes</option>
</select>

<input type="submit" value="Go!">
</form>



<?php
echo "<p>Sorted by: ". $cols[$sortcol] ;
 $baseurl2 = "current.phtml?network=$network&sortcol=";
?>
<table style="width: 100%; font-size: 10pt;" cellpadding="2" border="1" cellspacing="0">
<thead>
<tr>
  <th><a href="<?php echo $baseurl2; ?>station">SiteID:</a></th>
  <th><a href="<?php echo $baseurl2; ?>name">Station Name:</a></th>
  <th><a href="<?php echo $baseurl2; ?>valid">Valid:</a></th>
  <th><a href="<?php echo $baseurl2; ?>HGIZ">Stage</a> [ft]</th>
  <th><a href="<?php echo $baseurl2; ?>TAIZ">Temp</a> [F]</th>
  <th><a href="<?php echo $baseurl2; ?>PPHZ">1h Rain</a> [in]</th>
  <th><a href="<?php echo $baseurl2; ?>PPDZ">Today Rain</a> [in]</th></tr></thead>
<tbody>
<?php
 $oddrow = true;
 $now = time();
 while (list($site, $value) = each($final) ){
   echo "<tr ";
   if ($oddrow) echo "bgcolor=\"#EEEEEE\"";
   $url = sprintf("%s/sites/site.php?station=%s&network=%s", $rooturl,
         $site, $network);
   echo "><td><a href=\"$url\">$site</a></td>
    <td>". $value["name"] ."</font></td>";
   echo "<td ";
   $tdiff = $now - $value["valid"];
   if ($tdiff > (6*3600) ){
       echo 'bgcolor="red"';
   }
   echo ">". strftime("%d %b %I:%M %p", $value["valid"]) ."</td>";
   
   if (array_key_exists('HGIZ', $value)){
      echo sprintf("<td>%s</td>", $value["HGIZ"]);
   } else {
      echo "<td></td>";
   }

   if (array_key_exists('TAIZ', $value)){
   	echo sprintf("<td>%s</td>", $value["TAIZ"]);
   } else {
   	echo "<td></td>";
   }

   if (array_key_exists('PPHZ', $value)){
   	echo sprintf("<td>%s</td>", $value["PPHZ"]);
   } else {
   	echo "<td></td>";
   }

   if (array_key_exists('PPDZ', $value)){
   	echo sprintf("<td>%s</td>", $value["PPDZ"]);
   } else {
   	echo "<td></td>";
   }
	echo "</tr>";    
	if ($shef)
	{
		echo "<tr ";
		if ($oddrow) echo "bgcolor=\"#EEEEEE\"";
		echo "><td colspan=7>";
		reset($value);
		while (list($k,$v)=each($value)){
			if ($k == 'name' || $k == 'valid') continue;
           echo sprintf("/%s %s ", $k, $v);
        }
        echo "</td></tr>";
	}
   $oddrow = ! $oddrow;
 }
?>
</tbody><tfoot>
<tr><td colspan=7>&nbsp;</td></tr>
</tfoot></table>

<?php include("$rootpath/include/footer.php");
?>
