<?php
 include("../../config/settings.inc.php");
 include_once "$rootpath/include/database.inc.php";
 $mesosite = iemdb('mesosite');
  
 $shef = isset($_GET['shef']) ? $_GET['shef'] : 0;
 $sortcol = isset($_GET['sortcol']) ? $_GET['sortcol'] : "ts";
 $network = isset($_GET['network']) ? $_GET["network"] : 'IA_DCP';
  $TITLE = "IEM | DCP Network";
   $REFRESH = "<meta http-equiv=\"refresh\" content=\"600;\">";
  $HEADEXTRA = '<script type="text/javascript" src="/js/tableruler.js"></script>
<script type="text/javascript">
    window.onload=function(){tableruler();}
</script>';
 $THISPAGE = "current-sort";
  include("$rootpath/include/header.php");
?>
<div class="text">
<a href="/DCP/">DCP Network</a> &nbsp; <b> > </b> &nbsp; Current Conditions
<?php
 include("$rootpath/include/iemaccess.php");
 include("$rootpath/include/iemaccessob.php");

 $iem = new IEMAccess();
 $ntbl = $iem->getNetwork($network);



 $db = Array();
 while (list($site, $iemob) = each($ntbl) ){
  $db[$site] = Array();
  $db[$site]['tmpf'] = "";
  $db[$site]['max_tmpf'] = "";
  $db[$site]['min_tmpf'] = "";
  if ($iemob->db["tmpf"] != -99) {
    $db[$site]['tmpf'] = $iemob->db["tmpf"];
    $db[$site]['max_tmpf'] = $iemob->db["max_tmpf"];
    $db[$site]['min_tmpf'] = $iemob->db["min_tmpf"];
  }
  $db[$site]['sname'] = $iemob->db["sname"];
  $db[$site]['phour'] = "";
  if ($iemob->db["phour"] != -99)
    $db[$site]['phour'] = $iemob->db["phour"];
  $db[$site]['ts'] = $iemob->ts;
  $db[$site]['sid'] = $site;
  $db[$site]['pday'] = "";
  if ($iemob->db["pday"] != -99)
    $db[$site]['pday'] = $iemob->db["pday"];
  $db[$site]['raw'] = $iemob->db["raw"];
   $db[$site]['rstage'] = "";
  if ($iemob->db["rstage"] > 0)
    $db[$site]['rstage'] = $iemob->db["rstage"];
 }

function aSortBySecondIndex($multiArray, $secondIndex) {
        while (list($firstIndex, ) = each($multiArray))
                $indexMap[$firstIndex] = $multiArray[$firstIndex][$secondIndex];        arsort($indexMap);
        while (list($firstIndex, ) = each($indexMap))
                if (is_numeric($firstIndex))
                        $sortedArray[] = $multiArray[$firstIndex];
                else $sortedArray[$firstIndex] = $multiArray[$firstIndex];
        return $sortedArray;
}

$db = aSortBySecondIndex($db, $sortcol);

$cols = Array("ts" => "Valid", "sid" => "Site ID", "sname" => "Station Name",
  "tmpf" => "Air Temperature", "phour" => "Rainfall One Hour", 
  "rstage" => "Stage", "pday" => "Today's Precip");
?>

<?php $current_network = "DCP"; include("$rootpath/include/current_bar.inc.php"); ?>
<form method="GET" action="current.phtml" name="myselector">
<input type="hidden" name="sortcol" value="<?php echo $sortcol; ?>">
Select Network: 
<select name="network">
<?php 
$rs = pg_query($mesosite, "SELECT id, name from networks where id ~* 'DCP' ORDER by name ASC");
for ($i=0;$row=@pg_fetch_assoc($rs,$i);$i++){
	$sel = '';
	if ($network == $row["id"]){
		$sel = " selected='SELECTED'";
	}
	echo sprintf("<option value='%s'%s>%s</option>\n",
	  $row["id"], $sel, $row["name"]);
}

?>
</select>
<input type="submit" value="Go!">
</form>



<?php
echo "<p>Sorted by: ". $cols[$sortcol] ;
 $baseurl2 = "current.phtml?network=$network&sortcol=";
?>
<table style="width: 100%; font-size: 10pt;" cellpadding="2" border="1" cellspacing="0">
<thead>
<tr>
  <th><a href="<?php echo $baseurl2; ?>sid">SiteID:</a></th>
  <th><a href="<?php echo $baseurl2; ?>sname">Station Name:</a></th>
  <th><a href="<?php echo $baseurl2; ?>ts">Valid:</a></th>
  <th><a href="<?php echo $baseurl2; ?>rstage">Stage</a> [ft]</th>
  <th><a href="<?php echo $baseurl2; ?>tmpf">Temp</a> [F]</th>
  <th><a href="<?php echo $baseurl2; ?>phour">1h Rain</a> [in]</th>
  <th><a href="<?php echo $baseurl2; ?>pday">Today Rain</a> [in]</th></tr></thead>
<tbody>
<?php
 $oddrow = true;
 $now = time();
 while (list($site, $value) = each($db) ){
   echo "<tr ";
   if ($oddrow) echo "bgcolor=\"#EEEEEE\"";
   $url = sprintf("%s/sites/site.php?station=%s&network=%s", $rooturl,
         $site, $network);
   echo "><td><a href=\"$url\">$site</a></td>
    <td>". $value["sname"] ."</font></td>";
   echo "<td ";
   $tdiff = $now - $value["ts"];
   if ($tdiff > (6*3600) ){
       echo 'bgcolor="red"';
   }
   echo ">". strftime("%d %b %I:%M %p", $value["ts"]) ."</td>
    <td>". $value["rstage"] ."</td>";
   if ($value["tmpf"] != ""){
   echo "<td>". $value["tmpf"] ." (<font color=\"#ff0000\">". $value["max_tmpf"] ."</font> / <font color=\"#0000ff\">". $value["min_tmpf"] ."</font>)</td>";
   } else{
    echo "<td></td>";
   }
   echo "<td>". $value["phour"] ."</td>
    <td>". $value["pday"] ."</td>
    </tr>";
	if ($shef)
	{
		echo "<tr align=\"center\" ";
		if ($oddrow) echo "bgcolor=\"#EEEEEE\"";
		echo "><td colspan=7><font style=\"color: brown; font-size: smaller;\">". $value["raw"] ."</font></td></tr>";
	}
   $oddrow = ! $oddrow;
 }
?>
</tbody><tfoot>
<tr><td colspan=7>&nbsp;</td></tr>
</tfoot></table></div>

<?php include("$rootpath/include/footer.php");
?>
