<?php 
 require_once "../../config/settings.inc.php";
 require_once "../../include/myview.php";
 $t = new MyView();
 $t->title = "GOES/HADS/DCP";

 $t->content = <<<EOF
<h3>GOES DCP</h3>

<p>The Geostationary Operational Environmental Satellites 
(GOES) Data Collection Platforms (DCPs) are a set of hydrologic and meteorologic
data collection points.  The DCPs are a collection of networks owned and operated 
by a host of entities. [<b>1</b>]  The IEM receives this dataset from our 
<a href="http://www.unidata.ucar.edu">Unidata</a> 
feed, which contains the products produced by the Office of Dissemination
of the National Weather Service.<p>

<p>The NWS has a fantastic 
<a href="https://hads.ncep.noaa.gov">website</a> if you are curious 
about this dataset.</p>


<p>The IEM attempts to process all available data in this feed.  The applications
 below are divided up by states, so switch the state shown to find data outside of 
 Iowa. </p>

<h3>Available Tools:</h3>
<ul>
<li><a href="/sites/locate.php?network=IA_DCP">IEM Station Data + Metadata</a>
 <br />View maps of sites by state/country that the IEM processes SHEF data for.</li>
<li><a href='plot.phtml'>Create Current/Historical Timeseries Plots</a>
  <br />Generate a plot of a station, time period, and variable of your choice.</li>
<li><a href='map.php'>Interactive Map of Currents by SHEF Code</a>
  <br />View current data processed by the IEM for a SHEF code of your choice.</li>
<li><a href='current.phtml'>Sortable Current Conditions</a>
  <br />View the most recent observations from the network.</li>
<li><a href='tomb.phtml'>Stations with Unknown Metadata</a>
  <br />NWSLI site identiers used that are unknown in NWSLI database.</li>
<li><a href='cat.phtml'>View Observations By Time</a>
  <br />View a table of observations at a valid time of your choice.</li>
<li><a href='site.phtml'>View Observations By Site By Day</a>
  <br />View a table of observations for a site for a day.</li>
<li><a href='/request/dcp/fe.phtml'><i class="fa fa-download" aria-hidden="true"></i> Download from the archive</a>
  <br />Download the observations from the archive.</li>
</ul>
<p>


<b>References:</b><br>
<b>1</b> <a
href="https://hads.ncep.noaa.gov/dcp_operators.shtml">https://hads.ncep.noaa.gov/dcp_operators.shtml</a>
, viewed 12 Jul 2017
<br><a href="http://water.usgs.gov/pubs/circ/circ1123/">http://water.usgs.gov/pubs/circ/circ1123/</a>
 , viewed: 21 Jun 2003

EOF;
$t->render('single.phtml');
?>