<?php 
include("../../config/settings.inc.php");

$HEADEXTRA = '<link rel="stylesheet" type="text/css" href="http://extjs.cachefly.net/ext-3.4.0/resources/css/ext-all.css"/>
<script type="text/javascript" src="http://extjs.cachefly.net/ext-3.4.0/adapter/ext/ext-base.js"></script>
<script type="text/javascript" src="http://extjs.cachefly.net/ext-3.4.0/ext-all.js"></script>
<script type="text/javascript" src="plot.js?v=3" />
';
$THISPAGE ="networks-dcp";
include("../../include/header.php");
?>
<h3>Historical DCP Plotting</h3>

<blockquote>This application allows you to plot historical DCP data for 
a station, time period, and variable of your choice.  Select a station first
to reveal available variables for that station.  You may also wish to
<a href="request/dcp/fe.phtml">download</a> the raw observations.</blockquote>

<div id="myform" style="float: left;"></div>

<div style="float: right;"><img src="" id="imagedisplay" /></div>

<?php include("../../include/footer.php"); ?>