<?php
$OL = "6.2.1";
require_once "../../config/settings.inc.php";
define("IEM_APPID", 110);
require_once "../../include/mlib.php";
force_https();
require_once "../../include/myview.php";
$t = new MyView();
require_once "../../include/database.inc.php";
require_once "../../include/forms.php";
require_once "../../include/imagemaps.php";

$day = isset($_GET['day']) ? intval($_GET["day"]): date("d");
$month = isset($_GET['month']) ? intval($_GET["month"]): date("m");
$year = isset($_GET['year']) ? intval($_GET["year"]): date("Y");
$station = isset($_GET['station'])? xssafe($_GET['station']): null;
$network = isset($_GET['network']) ? xssafe($_GET["network"]) : 'IA_DCP';

$ts = mktime(1, 0, 0, $month, $day, $year);

$hads = iemdb("hads");
$mesosite = iemdb("mesosite");

if ($station != null){
	/* Make sure this site is not both a DCP and COOP site, this would cause
	 * the app to do a yearlong query, which is expensive.
	 */
	$rs = pg_prepare($mesosite, "DUPSTATIONS", "SELECT network from stations
			WHERE id = $1 and (network ~* '_DCP' or network ~* '_COOP')");
	$rs = pg_execute($mesosite, "DUPSTATIONS", Array($station));
	$alone = (pg_numrows($rs) == 1) ? TRUE: FALSE;
	
	if (preg_match('/_COOP/', $network) && $alone){
		$table = sprintf("raw%s", date("Y",$ts));
		$rs = pg_prepare($hads, "QUERY", "SELECT * from $table WHERE 
				station = $1 ORDER by valid ASC");
				$rs = pg_execute($hads, "QUERY", Array($station));
	} else {
		$table = sprintf("raw%s_%s", date("Y",$ts), date("m", $ts));
		$rs = pg_prepare($hads, "QUERY", "SELECT * from $table WHERE 
				station = $1 and valid BETWEEN $2 and $3 ORDER by valid ASC");
		$rs = pg_execute($hads, "QUERY", 
				Array($station, date("Y-m-d", $ts), date("Y-m-d", $ts+86400)));
	}

	$data = Array();
	$cols = Array();
	for($i=0;$row=pg_fetch_array($rs);$i++){
	  $cols[ $row["key"] ] = 1;
	  $data[ strtotime(substr($row["valid"],0,16)) ][ $row["key"] ] = $row["value"];  
	}
	$mycols = array_keys($cols);
	sort($mycols);
}
	
$t->title = "SHEF Data by Site by Day";
if (is_null($station)){
  $t->headextra = <<<EOF
<link rel="stylesheet" href="/vendor/openlayers/{$OL}/ol.css" type="text/css">
<link type="text/css" href="/vendor/openlayers/{$OL}/ol-layerswitcher.css" rel="stylesheet" />
<link rel="stylesheet" type="text/css" href="/vendor/select2/4.0.3/select2.min.css"/ >
EOF;
  $t->jsextra = <<<EOF
<script src="/vendor/openlayers/{$OL}/ol.js" type="text/javascript"></script>
<script src='/vendor/openlayers/{$OL}/ol-layerswitcher.js'></script>
<script src="/js/olselect.php?network=${network}"></script>
<script src="/vendor/select2/4.0.3/select2.min.js"></script>
<script type="text/javascript">
$(document).ready(function(){
	$(".iemselect2").select2();	
});
</script>
EOF;

}

$nselect = "<select name=\"network\">";
$rs = pg_query($mesosite, "SELECT id, name from networks ". 
	"where id ~* '_DCP' or id ~* '_COOP' ORDER by name ASC");
for ($i=0;$row=pg_fetch_assoc($rs);$i++){
	$sel = '';
	if ($network == $row["id"]){
		$sel = " selected='SELECTED'";
	}
	$nselect .= sprintf("<option value='%s'%s>%s</option>\n",
			$row["id"], $sel, $row["name"]);
}
$nselect .= "</select>";
$n2select = networkSelect($network, $station);

$ys = yearSelect(2002,$year);
$ms = monthSelect($month);
$ds = daySelect($day);

$extra = "";
if (is_null($station)){ 
	$extra = <<<EOF
<style type="text/css">
        #map {
            width: 100%;
            height: 400px;
            border: 2px solid black;
        }
</style>
<i>Click on the dot to select your site:</i><br />
<div id="map"></div>
EOF;
} else { 
	if (! $alone){
		$extra = <<<EOF
<div class="warning">This site is listed within the IEM database as both a 
	"COOP" and "DCP" site. This printout below will only include a days 
	worth of data.</div>
EOF;
	}
	$extra .= "<br /><br />
	<table class=\"table table-striped table-bordered\" style=\"width: auto;\">";
	$theader = "<thead><tr><th>Site:</th><th>Valid:</th>";
	foreach($mycols as $k => $v){ $theader .= "<th>$v</th>"; }
	$theader .= "</tr></thead>";
	
	$times = array_keys($data);
	if (sizeof($times) == 0){
		$extra .= $theader;
		$extra .= "<tr><td colspan=\"2\">No Data Found</td></tr>";
	}
	$colorme = True;
	$cnt = 0;
	foreach($times as $k => $ts){
		if ($cnt % 30 == 0){
			$extra .= $theader;
		}
	
		$extra .= sprintf("<tr%s><td>%s</td><td><a href='cat.phtml?year=%s&month=%s&day=%s&hour=%s&minute=%s'>%s</a></td>",
				($colorme)? " style='background: #eee;'": "", $station,
				date("Y", $ts), date("m", $ts), date("d", $ts), date("H", $ts),
				date("i", $ts), date("Y-m-d H:i", $ts) );
		$colorme = !$colorme;
		foreach($mycols as $k => $v){
			$extra .= sprintf("<td>%s</td>", $data[$ts][$v] ?? '');
		}
		$extra .= "</tr>";
	
		$cnt += 1;
	}
	
	$extra .= "</table>";
}
	
$t->content = <<<EOF
<ol class="breadcrumb">
 <li><a href="/DCP/">GOES DCP/HADS Mainpage</a></li>
 <li class="active">List Obs by Date</li>
</ol>
<h3>SHEF Site Observations by Date</h3>
<ul>
 <li>Timestamps are presented in central standard or daylight time</li>
 <li>The column headings are the 
 <a href="http://www.weather.gov/ohd/hrl/shef/indexshef.htm">SHEF</a> encoded 
 variable names.</li>
 <li>Archive begins on 1 Jan 2002 for Iowa, 9 Dec 2010 for other states.  
 The archive is not complete for all the sites listed.</li>
 <li>The IEM classifies SHEF provided data into two classes on a state by
 state basis.  The COOP network sites are mostly official once-daily cooperative
 observer sites.  The DCP network is everybody else!</li>
 <li>If you select a COOP network site, you are provided observations for the
 entire year.</li>
 </ul>

<form method="GET" name="chstate">
<p><strong>Select Network:</strong> {$nselect}

<input type="submit" value="Select Network" />
</form>

<form method="GET" name="olselect">
<input type="hidden" name="network" value="{$network}" />
<table class="table table-condensed">
<thead>
<tr><th>Station:</th><th>Year</th><th>Month</th><th>Day</th><th></th></tr>
</thead>
<tr>
<td>{$n2select}
<br /><a href="site.phtml?year={$year}&month={$month}&day={$day}">Select from map</a></td>
<td>{$ys}</td>
<td>{$ms}</td>
<td>{$ds}</td>
<td><input type="submit" value="View Data"></td>
</tr></table>
</form>

	
$extra
EOF;
$t->render('full.phtml');
?>
