<?php
include("../../config/settings.inc.php");
include("$rootpath/include/database.inc.php");
include("$rootpath/include/forms.php");
include("$rootpath/include/stations.php");

$day = isset($_GET['day']) ? $_GET["day"] : date("d");
$month = isset($_GET['month']) ? $_GET["month"] : date("m");
$year = isset($_GET['year']) ? $_GET["year"] : date("Y");
$station = isset($_GET['station'])? $_GET['station']: 'AESI4';

$ts = mktime(1, 0, 0, $month, $day, $year);
$table = sprintf("raw%s_%s", date("Y",$ts), date("m", $ts));

$hads = iemdb("hads");
$rs = pg_prepare($hads, "QUERY", "SELECT * from $table WHERE station = $1 and valid BETWEEN $2 and $3 ORDER by valid ASC");
$rs = pg_execute($hads, "QUERY", Array($station, date("Y-m-d", $ts), date("Y-m-d", $ts+86400)));

$data = Array();
$cols = Array();
for($i=0;$row=@pg_fetch_array($rs,$i);$i++){
  $cols[ $row["key"] ] = 1;
  $data[ strtotime(substr($row["valid"],0,16)) ][ $row["key"] ] = $row["value"];  
}
$mycols = array_keys($cols);

$TITLE = "IEM | DCP Data by Site by Day";
$THISPAGE="networks-dcp";
if (! isset($_GET["station"])){
  include("$rootpath/include/google_keys.php");
  $network = "DCP";
  $api = $GOOGLEKEYS[$rooturl]["any"];
  $HEADEXTRA = "<script src='http://maps.google.com/maps?file=api&amp;v=2&amp;key=$api'></script>
 <script src='http://www.openlayers.org/api/OpenLayers.js'></script>
 <script src='${rooturl}/js/olselect.php?network=${network}'></script>";
 $BODYEXTRA = "onload=\"init()\"";
}

include("$rootpath/include/header.php"); 
?>
<h3>DCP Site Observations by Date</h3>
<ul>
 <li>Timestamps are presented in central standard or daylight time</li>
 <li>The column headings are the <a href="http://www.weather.gov/ohd/hrl/shef/indexshef.htm">SHEF</a> encoded variable names.</li>
 <li>Archive begins on 1 Jan 2008 and is only for Iowa.</li>
</ul>


<form method="GET" name="olselect">
<table><tr><th>Station:</th><th>Year</th><th>Month</th><th>Day</th><th></th></tr>
<tr>
<td><?php echo networkSelect(iemdb("mesosite"),"DCP", $station); ?>
<br /><a href="site.phtml?year=<?php echo $year; ?>&month=<?php echo $month; ?>&day=<?php echo $day; ?>">Select from map</a></td>
<td><?php echo yearSelect(2008,$year); ?></td>
<td><?php echo monthSelect($month); ?></td>
<td><?php echo daySelect($day); ?></td>
<td><input type="submit" value="View Data"></td>
</tr></table>
</form>
<?php if (! isset($_GET["station"])){ ?>
<style type="text/css">
        #map {
            width: 640px;
            height: 400px;
            border: 2px solid black;
        }
</style>
<i>Click black dot to select your site:</i><br />
<div id="map"></div>
<div id="sname" unselectable="on">No site selected</div>
<?php } ?>
<br /><br />
<table border="1" cellpadding="2" cellspacing="0">
<tr>
<th>Site:</th><th>Valid:</th>
<?php
 while(list($k,$v) = each($mycols)){ echo "<th>$v</th>"; }
?>
</tr>
<?php
$times = array_keys($data);
while(list($k,$ts) = each($times)){
  echo sprintf("<tr><td>%s</td><td>%s</td>", $station, date("Y-m-d H:i", $ts) );
  reset($mycols);
  while(list($k,$v) = each($mycols)){
    echo sprintf("<td>%s</td>", @$data[$ts][$v]);
  }
  echo "</tr>";
}

?>
</table>
<?php include("$rootpath/include/footer.php"); ?>
