<?php 
require_once "../../config/settings.inc.php";
define("IEM_APPID", 99);
require_once "../../include/myview.php";
require_once "../../include/database.inc.php";

$pgconn = iemdb('hads');
$rs = pg_query($pgconn, "SELECT nwsli, max(product) from unknown"
		." WHERE length(nwsli) = 5 and "
		."nwsli ~* '[A-Z][A-Z][A-Z][A-Z][0-9]' "
		."GROUP by nwsli ORDER by nwsli ASC");
$table = <<<EOF
<table id="table1" class="table table-striped table-bordered">
<thead><tr><th>NWSLI</th><th>WMO Source</th><th>Recent Product</th></tr></thead>
<tbody>
EOF;
$floor = date("YmdHi", time() - 8*86400);
for($i=0; $row=pg_fetch_array($rs); $i++){
	$link = sprintf("<a href=\"/p.php?pid=%s\">%s</a>", $row[1], $row[1]);
	if (substr($row[1], 0, 12) < $floor){
		$link = $row[1];
	}
	$table .= sprintf("<tr><td>%s</td><td>%s</td><td>%s</td>\n",
			$row[0], substr($row[1], 13, 4), $link);
}
$table .= "</tbody></table>";

$t = new MyView();
$t->title = "Unknown NWSLIs used in SHEF Products";
$t->jsextra = <<<EOF
<script src="/vendor/jquery-filtertable/1.5.7/jquery.filtertable.min.js"></script>
<script>
   $("#table1").filterTable({label: "Filter Table By: "});
</script>
EOF;

$t->content = <<<EOF
<ol class="breadcrumb">
		<li><a href="/DCP/">HADS/DCP Mainpage</a></li>
		<li class="active">Unknown NWSLIs</li>
</ol>

<h3>Unknown NWSLIs used in SHEF Products</h3>

<p>The IEM attempts to process all SHEF encoded products that come via a
NOAAPort data stream.  The identifiers used by the stations reported in this
data feed are supposed to adhere the <a href="https://www.weather.gov/media/mdl/SHEF_CodeManual_5July2012.pdf">SHEF Manual</a>
specification for site identifiers.  The most common set of identifiers are
found within the <a href="http://www.nws.noaa.gov/directives/sym/pd03012004curr.pdf">National Weather Service Location Identifier (NWSLI)</a> database.
Unfortunately, not all site ids used by issuance centers are contained within
NWSLI.  This page lists out unknown NWSLI'ish identifiers.  The IEM attempts
to rectify this list quarterly, so there may be some false positive listed. The
IEM maintains a week of raw SHEF data, so links to indicated products
older than a week old will not work.</p>

<p>This page is similiar to
<a href="https://www.nohrsc.noaa.gov/shef_archive/tomb.html">NOHRSC's Unknown Stations</a>
page, but this page only contains <strong>NWSLI-like identifiers</strong>.</p>

{$table}

EOF;
$t->render('single.phtml');
?>
