-- Storage of national blend mos
ALTER TABLE alldata add sky smallint;
ALTER TABLE alldata add gst smallint;
ALTER TABLE alldata add t03 smallint;
ALTER TABLE alldata add pzr smallint;
ALTER TABLE alldata add psn smallint;
ALTER TABLE alldata add ppl smallint;
ALTER TABLE alldata add pra smallint;
ALTER TABLE alldata add s06 smallint;
ALTER TABLE alldata add slv smallint;
ALTER TABLE alldata add i06 smallint;
ALTER TABLE alldata add lcb smallint;
ALTER TABLE alldata add swh smallint;
