<?php include_once("../../../config/settings.inc.php");
include_once "../../../include/myview.php";
include("../../../include/database.inc.php");
$pg = iemdb("squaw");
$t = new MyView();
$t->title = "Squaw Creek Flood Modeling";
include("../../../include/squaw/forms.inc.php"); 

$ms = monthSelect( date("m") , "month");
$ds =  daySelect( date("d") );
$ys = yearSelect(1990, date("Y") );
$hs = localHourSelect( date("I"), "hour" );
$hs2 = localHourSelect(3, "rhour1");
$hs3 = localHourSelect(4, "rhour2");

$sql = "SELECT * from scenarios";
$rs = pg_query($pg, $sql);
$scenarios = "";
while($row = pg_fetch_array($rs))
{
	$name = $row["name"];
	$id = $row["id"];
	$scenarios .= "<br /><input type=\"checkbox\" name=\"scenarios[]\" value=\"$id\">$name";
}

$t->content = <<<EOF
<h3>Run the Model!</h3>

<div class="help">This form allows you to set up the model with the necessary
parameters to run.  Any relevant storms are pulled into the run based on your
specification for time. Please fill out the following items and then click
the <i>Run Model</i> button at the bottom of the page.</div>

<form method="GET" action="model.phtml">
<input type="hidden" value="" name="storms">

<p><b>1. Model Initialization Time:</b></p>

<p>The model will start running from this time out to 60 hours.</p>

<table>
<thead>
<tr>
	<th>Month:</th><th>Day:</th><th>Year:</th><th>Hour:</th></tr>
</thead>
<tbody>
<tr>
	<td>{$ms}</td>
	<td>{$ds}</td>
	<td>{$ys}</td>
	<td>{$hs}</td></tr>
</tbody>
</table>

<p><b>2.  Configure Recession Curve:</b></p>

<p>The model needs to have two points along the recession curve of the Squaw
Creek.  These two points must be after the <i>Model Initialization Time</i> chosen in #1 and the flow must be receeding.</p>

<table>
<thead>
<tr>
	<th>Time Index:</th><th>Hour:</th><th>Flow:</th></tr>
</thead>

<tbody>
<tr>
	<td>1.</td><td>{$hs2}</td>
		<td><input type="text" name="rflow1" size="6"></td></tr>
<tr>
	<td>2.</td><td>{$hs3}</td>
		<td><input type="text" name="rflow2" size="6"></td></tr>
</tbody>
</table>

<p><b>3.  Select optional scenarios to run with:</b></p>

<p>You can select from these scenarios to run with as well.</p>
{$scenarios}

<p><b>4. Run The Model:</b></p>

<input type="submit" value="Run Model"><input type="reset" value="Reset Form">
</form>

EOF;
$t->render('single.phtml');
?>
