<?php 
 /* model.phtml */
 include("../../../config/settings.inc.php");
 include_once "../../../include/myview.php";
 $t = new MyView();
include("../../../include/database.inc.php");
$pg = iemdb("squaw");
 include("../../../include/squaw/constants.inc.php");
 include("../../../include/squaw/model.inc.php");
 include("../../../include/squaw/forms.inc.php");
 $ts = mktime($_GET["hour"],0,0, $_GET["month"], $_GET["day"], $_GET["year"]);
 $ts1 = mktime($_GET["rhour1"],0,0, $_GET["month"], $_GET["day"], $_GET["year"]);
 $ts2 = mktime($_GET["rhour2"],0,0, $_GET["month"], $_GET["day"], $_GET["year"]);

 $mymodel = new flood_model($ts);
 $mymodel->loglevel = $mymodel->INFO;
 $mymodel->addRecessionInfo($ts1, $_GET["rflow1"], $ts2, $_GET["rflow2"]);
 $mymodel->setSelectStorms($_GET);
 $mymodel->setSelectScenarios($_GET);
 $mymodel->run();

 $fref24 = $mymodel->plot24HCurve();
 $fref = $mymodel->plotRecessionCurve();
 $rmap = $mymodel->rainfallMap();

$t->title = "Squaw Creek Flood Modeling";

$msg = "";
if ( isset($mymodel->message) )
{
	$msg = "<div style=\"background: #ff0; border: 1px #000 solid;\"><b>Message:</b>{$mymodel->message}</div>";
}

$pinfo = $mymodel->printInfo();

$table = "";
reset($mymodel->storms);
while (list($key,$value) = each($mymodel->storms) )
{
	$table .= "<tr><td><input type=\"checkbox\" name=\"storms[]\" value=\"$key\" ";
	if ($mymodel->selectedstorms == "" ||
			in_array($key, $mymodel->selectedstorms))
	{  $table .= "CHECKED=\"CHECKED\""; }
   $table .= "><a href=\"/squaw/storm/edit.phtml?id=$key\" target=\"_new\">$value</a></td></tr>";
	}

	if (sizeof($mymodel->storms) == 0) {
	$table .= "<tr><th>No real storms found in database.</th></tr>\n";
 }

 $table2 = "";
 reset($mymodel->scenarios);
 while (list($key,$value) = each($mymodel->scenarios) )
 {
 	$table2 .= "<tr><td><input type=\"checkbox\" name=\"scenarios[]\" value=\"$key\" ";
 	if ($mymodel->selectedscenarios != "" &&
 			in_array($key, $mymodel->selectedscenarios))
 	{  $table2 .= "CHECKED=\"CHECKED\""; }
   $table2 .= "><a href=\"/squaw/scenario/edit.phtml?id=$key\" target=\"_new\">$value</a></td></tr>";
 	}
 
 	if (sizeof($mymodel->scenarios) == 0) {
 	$table2 .= "<tr><th>No scenarios found in database.</th></tr>\n";
 }
 
 $r1 = localHourSelect($_GET["rhour1"], "rhour1");
 $r2 = localHourSelect($_GET["rhour2"], "rhour2");
 
$t->content = <<<EOF

<?php 
{$msg}

<h3>Squaw Model Results:</h3>

<h4>36 Hour Model Prediction</h4> 
<img src="{$fref24}">

<h4>60 Hour Model Prediction</h4>
<img src="{$fref}">

<div style="float: right;">
<h4>Rainfall Map</h4>
<img src="{$rmap}">
</div>

{$pinfo}

<h4>Download Model results:</h4>
<a href="{$mymodel->basinlogname}">Comma Delimited</a>

<h4>Model Settings:</h4>
<form method="GET" action="model.phtml" name="mod">
<input type="hidden" name="day" value="{$_GET["day"]}">
<input type="hidden" name="month" value="{$_GET["month"]}">
<input type="hidden" name="year" value="{$_GET["year"]}">
<input type="hidden" name="hour" value="{$_GET["hour"]}">

<table>
<caption>Select Rainfall Events:</caption>
<tbody>
{$table}
</tr></tbody></table>

<p><table>
<caption>Select Scenario Events:</caption>
<tbody>
{$table2}
</tr></tbody></table>


<p><table>
<caption>Set Baseflow Parameters:</caption>
<thead>
<tr>
        <th>Time Index:</th><th>Hour:</th><th>Flow:</th></tr>
</thead>
                                                                                
<tbody>
<tr>
        <td>1.</td><td>{$r1}</td>
        <td><input type="text" name="rflow1" size="6" value="{$_GET["rflow1"]}"></td></tr>
<tr>
        <td>2.</td><td>{$r2}</td>
        <td><input type="text" name="rflow2" size="6" value="{$_GET["rflow2"]}"></td></tr>
</tbody>
</table>

<input type="submit" value="Re-Run Model">
</form>

EOF;
$t->render('single.phtml');
?>
