<?php
 include("../../config/settings.inc.php");
 include("$rootpath/include/constants.php");
 include("$rootpath/include/google_keys.php");
 include("$rootpath/include/imagemaps.php");
 $report = isset($_GET["report"])? substr($_GET["report"],0,2): "01";
 $station = isset($_GET["station"])? strtolower( substr($_GET["station"],0,6) ): "";


 if (isset($_GET["id"])){
   $station = $_GET["id"];
 }

 if (isset($_GET["dl"]) ){
   if (is_file("reports/${station}_${report}.txt") ){
     header("Content-type: application/octet-stream");
     header("Content-Disposition: attachment; filename=${station}_${report}.txt");
     readfile("reports/${station}_${report}.txt");
     die();
   }
 }

$THISPAGE = "climatology-climodat";
$TITLE = "IEM Climodat";
if (strlen($station) == ""){
  $network = "IACLIMATE";
  $api = $GOOGLEKEYS[$rooturl]["any"];
  $HEADEXTRA = "<script src='http://maps.google.com/maps?file=api&amp;v=2&amp;key=$api'></script>
 <script src='http://www.openlayers.org/api/OpenLayers.js'></script>
 <script src='${rooturl}/js/olselect.php?network=${network}'></script>";
 $BODYEXTRA = "onload=\"init()\"";
}
include("$rootpath/include/header.php"); 
?>


<h3 class="heading">IEM "Climodat" Reports</h3>
<?php if (strlen($station) == ""){ ?>

<div class="text">
<?php } ?>

<p>These "Climodat" reports provide some answers to the most common climatological
questions we get routinely asked.  These reports are based on the daily climate observations from the <a href="/COOP/">NWS COOP</a> network.  We also provide <a href="index.phtml#ks">"kitchen sink"</a> data files which contain the much of the raw information used to generate the reports. 

<p><strong>Note on data sources:</strong>
<br />The <a href="http://www.iowaagriculture.gov/climatology.asp">Iowa State Climatologist</a> provides the IEM with a monthly update of
quality controlled observational data.  This procedure takes a good deal of 
time on his behalf. Quality controlled information exists from <b>1 Jan 1951 till <?php echo date('d M Y', $coop_archive_end); ?></b>.  Any months of data
afterwards are based on preliminary data from <a href="http://www.ncdc.noaa.gov">NCDC</a> and other sources. Some sites have data back to 1893, so their reports 
contain data dating back to then.

<h3 class="subtitle">Climodat Reports</h3>
<div id="iem-form2"><form method="GET" action="index.phtml" name="olselect">

<table cellpadding=2 cellspacing=1>
  <tr><th>Select Climate Station:</th><th>Select Report:</th><td></td></tr>

<tr><td><?php echo networkSelect("IACLIMATE", strtoupper($station) ); ?>
<br /><?php if (strlen($station) > 0){ echo "<a href=\"index.phtml?report=${report}\">Select from map</a>"; } ?></td>

<td valign="top"><select name="report" size="1">
<option value="01" <?php if ($report == "01") echo "SELECTED"; ?>>Precipitation Events per Climate Week
<option value="02" <?php if ($report == "02") echo "SELECTED"; ?>>Twelve Significant Rainfall Events
<option value="03" <?php if ($report == "03") echo "SELECTED"; ?>>Growing Degree Days
<option value="04" <?php if ($report == "04") echo "SELECTED"; ?>>Daily Record Highs and Lows
<option value="05" <?php if ($report == "05") echo "SELECTED"; ?>>Daily Maximum Precipitation
<option value="06" <?php if ($report == "06") echo "SELECTED"; ?>>Daily Record Hi and Low Ranges
<option value="07" <?php if ($report == "07") echo "SELECTED"; ?>>Daily Mean Highs and Lows
<option value="08" <?php if ($report == "08") echo "SELECTED"; ?>>Number of Days Each Year Min &gt;= 32
<option value="09" <?php if ($report == "09") echo "SELECTED"; ?>>Last Spring/First Fall/Length of Season Base=32
<option value="10" <?php if ($report == "10") echo "SELECTED"; ?>>Last Spring/First Fall/Length of Season Base=30
<option value="11" <?php if ($report == "11") echo "SELECTED"; ?>>Last Spring/First Fall/Length of Season Base=28
<option value="12" <?php if ($report == "12") echo "SELECTED"; ?>>Last Spring/First Fall/Length of Season Base=26
<option value="13" <?php if ($report == "13") echo "SELECTED"; ?>>Last Spring/First Fall/Length of Season Base=24
<option value="14" <?php if ($report == "14") echo "SELECTED"; ?>>Monthly Average Maximum Temperatures
<option value="15" <?php if ($report == "15") echo "SELECTED"; ?>>Monthly Average Minimum Temperatures
<option value="16" <?php if ($report == "16") echo "SELECTED"; ?>>Monthly Average Mean Temperatures
<option value="17" <?php if ($report == "17") echo "SELECTED"; ?>>Monthly Precipitation Totals + Averages
<option value="18" <?php if ($report == "18") echo "SELECTED"; ?>>Monthly Heating Degree Days
<option value="19" <?php if ($report == "19") echo "SELECTED"; ?>>Monthly Cooling Degree Days
<option value="20" <?php if ($report == "20") echo "SELECTED"; ?>>Heat Stress Variables
<option value="21" <?php if ($report == "21") echo "SELECTED"; ?>>Monthly Rainy Days
<option value="22" <?php if ($report == "22") echo "SELECTED"; ?>>First Fall Freeze Probabilities
<option value="23" <?php if ($report == "23") echo "SELECTED"; ?>>Last Spring Freeze Probabilities
<option value="24" <?php if ($report == "24") echo "SELECTED"; ?>>Freeze/Thaw Cycles
<option value="25" <?php if ($report == "25") echo "SELECTED"; ?>>Monthly Snowy Days
<option value="26" <?php if ($report == "26") echo "SELECTED"; ?>>Yearly Temperature Exceedance Histograms
<option value="27" <?php if ($report == "27") echo "SELECTED"; ?>>High/Low Consecuative Day Streaks
</select></td>
<td><input type="submit" value="View Report"></td></tr></table>
</form>

<p>
<?php 
if (is_file("reports/${station}_$report.txt")){
echo "<table cellpadding=\"2\"><tr><th>Download Options</th><td><form name=\"dl\" action=\"index.phtml\">
  <input type=\"hidden\" name=\"dl\" value=\"yes\">
  <input type=\"hidden\" name=\"station\" value=\"$station\"> 
  <input type=\"hidden\" name=\"report\" value=\"$report\">
  <input type=\"submit\" value=\"Download Text Version\">
</form></td>
<td><form name=\"excel\" action=\"as-excel.php\">
  <input type=\"hidden\" name=\"station\" value=\"$station\"> 
  <input type=\"hidden\" name=\"report\" value=\"$report\">
  <input type=\"submit\" value=\"Download Excel Version\"></form></td>
</tr></table>"; 

echo "<pre>\n";
  include("reports/${station}_$report.txt");
echo "</pre>\n";
} else {
?> 
<style type="text/css">
        #map {
            width: 640px;
            height: 400px;
            border: 2px solid black;
        }
</style>
<i>Click black dot to select your site:</i><br />
<div id="map"></div>
<div id="sname" unselectable="on">No site selected</div>


<a name="ks"><h3 class="subtitle">"Kitchen Sink" Datafiles</h3></a>
<div id="iem-form2">
While the climodat reports are useful, they only provide information for one variable and one site at a time.  These "kitchen sink" datafiles contain the raw information broken down by year and month for variables like high/low temperature and precipitation.

<p><strong>Download:</strong>
<br />You can download all of the datafiles in one <a href="everything.zip">Zipfile (0.8 MB)</a> or <a href="ks/">browse a directory</a> to pick the individual files you want.

<p><strong>Format:</strong>
<br /><img src="/images/gisready.png" style="float: left;"> These text files are in a simple comma delimited format.  Two of the data columns contain the latitude
and longitude information which allows easy import into most GIS systems.

<p><strong>Details: <i>yearly file</i></strong>
<br />There is one yearly file (named <a href="ks/yearly.csv">yearly.csv</a>) which contains yearly summaries dating back to 1951.  Please consult the help file (named <a href="ks/yearly_ks.txt">yearly_ks.txt</a>) for further details.

<p><strong>Details: <i>monthly files</i></strong>
<br />For every year dating back to 1951, there is one file per year which 
contains monthly summaries of high/low temperature and precipitation.  You
can browse <a href="ks/">this directory</a> to pick the files you want or just 
download <a href="everything.zip">everything</a> to save the hassle. Please
consult the help file (named <a href="ks/monthly_ks.txt">monthly_ks.txt</a>)
for further details.

<p>Did these reports help?  Please let <a href="/info/contacts.php">us know</a> 
if you would like to see other variables in these files or have any other comments about them.  Enjoy!
</div>

<p><b>Disclaimer:</b> While we use care to provide accurate weather/climatic information, errors may occur because of equipment or other failure. We therefore provide this information without any warranty of accuracy. Users of this weather/climate data do so at their own risk, and are advised to use independent judgement as to whether to verify the data presented.</p>
</div>

<?php } ?>
<?php include("$rootpath/include/footer.php"); ?>
