<?php
 include("../../config/settings.inc.php");
 define("IEM_APPID", 15);
 include("../../include/myview.php");
 include("../../include/iemprop.php");
 include("../../include/imagemaps.php");
 include("../../include/forms.php");
 $report = isset($_REQUEST["report"])? substr($_REQUEST["report"],0,2): "01";
 $station = isset($_REQUEST["station"])? substr($_REQUEST["station"],0,6) : "";
 $network = isset($_REQUEST['network']) ? $_REQUEST['network'] : 'IACLIMATE';

 if (isset($_GET["id"])){
   $station = substr($_REQUEST["id"],0,6);
 }

 if (isset($_GET["dl"]) ){
   if (is_file("/mesonet/share/climodat/reports/${station}_${report}.txt") ){
     header("Content-type: application/octet-stream");
     header("Content-Disposition: attachment; filename=${station}_${report}.txt");
     readfile("/mesonet/share/climodat/reports/${station}_${report}.txt");
     die();
   }
 }

$coop_archive_end = strtotime( get_iemprop("iaclimate.end") );
$t = new MyView();
$t->thispage = "climatology-climodat";
$t->title = "Climodat Reports";

if ($station == "" || ! is_file("/mesonet/share/climodat/reports/${station}_$report.txt")){
	$t->headextra = <<<EOF
<link rel="stylesheet" href="/vendor/openlayers/3.5.0/ol.css" type="text/css">
<link type="text/css" href="/vendor/openlayers/3.5.0/ol3-layerswitcher.css" rel="stylesheet" />
EOF;
	$t->jsextra = <<<EOF
<script src="/vendor/openlayers/3.5.0/ol.js" type="text/javascript"></script>
<script src='/vendor/openlayers/3.5.0/ol3-layerswitcher.js'></script>
<script src="/js/olselect.php?network=${network}"></script>
EOF;
 	
}
$enddate = date('d M Y', $coop_archive_end);
$nselect = networkSelect($network, $station );

$ar = Array(
	"Precipitation" => Array(
		"05" => "Daily Maximum Precipitation",
		"17" => "Monthly Precipitation Total",
		"21" => "Monthly Rainy Days",
		"28" => "Precipitation Events by Month &amp; Year",
		"01" => "Precipitation Events per Climate Week",
		"02" => "Top 30 Rainfall Events",
	),
	"Temperature" => Array(
		"04" => "Daily Record Highs and Lows",
		"06" => "Daily Record High and Low Ranges",
		"07" => "Daily Mean Highs and Lows",
		"27" => "High/Low Consecutive Day Streaks",
		"14" => "Monthly Average Maximum Temperatures",
		"15" => "Monthly Average Minimum Temperatures",
		"16" => "Monthly Average Mean Temperatures",
		"18" => "Monthly Heating Degree Days",
		"19" => "Monthly Cooling Degree Days",
		"08" => "Number of Days Each Year Min &gt;= 32",
		"20" => "Heat Stress Variables",
		"26" => "Yearly Temperature Exceedance Histograms",
	),
	"Growing Season" => Array(
		"03" => "Growing Degree Days",
		"09" => "Last Spring / First Fall / Length of Season Base=32",
		"10" => "Last Spring / First Fall / Length of Season Base=30",
		"11" => "Last Spring / First Fall / Length of Season Base=28",
		"12" => "Last Spring / First Fall / Length of Season Base=26",
		"13" => "Last Spring / First Fall / Length of Season Base=24",
		"22" => "First Fall Freeze Probabilities",
		"23" => "Last Spring Freeze Probabilities",
		"24" => "Freeze/Thaw Cycles",
	),
	"Snow" => Array(
		"25" => "Monthly Snowy Days",
	)
);

$vselect = make_select("report", $report, $ar);

$content = <<<EOF
<h3>IEM "Climodat" Reports</h3>

<p>These "Climodat" reports provide some answers to the most common climatological
questions we get routinely asked.  These reports are based on the daily 
climate observations from the <a href="/COOP/">NWS COOP</a> network.  
We also provide <a href="index.phtml#ks">"kitchen sink"</a> data files 
which contain the much of the raw information used to generate the reports. 
There is a <a href="monitor.php">station monitor app</a> that allows you to see
current summarized statistics for a station collection of your choice.</p>

<p><strong>Note on data sources:</strong>
<br />The <a href="http://www.iowaagriculture.gov/climatology.asp">Iowa State Climatologist</a> 
provides the IEM with a monthly update of
quality controlled observational data.  This procedure takes a good deal of 
time on his behalf. Quality controlled information exists from 
<b>1 Jan 1951 till {$enddate}</b>.  Any months of data
afterwards are based on preliminary data from 
<a href="http://www.ncdc.noaa.gov">NCDC</a> and other sources. Some sites have 
data back to 1893, so their reports contain data dating back to then.

<p>Data is available from the following states: 
<a href="index.phtml?network=ILCLIMATE">Illinois</a> ,
<a href="index.phtml?network=INCLIMATE">Indiana</a> ,
<a href="index.phtml?network=IACLIMATE">Iowa</a> ,
<a href="index.phtml?network=KSCLIMATE">Kansas</a>,
<a href="index.phtml?network=KYCLIMATE">Kentucky</a> ,
<a href="index.phtml?network=MICLIMATE">Michigan</a> ,
<a href="index.phtml?network=MNCLIMATE">Minnesota</a> ,
<a href="index.phtml?network=MOCLIMATE">Missouri</a> ,
<a href="index.phtml?network=NECLIMATE">Nebraska</a> ,
<a href="index.phtml?network=OHCLIMATE">Ohio</a> ,
<a href="index.phtml?network=NDCLIMATE">North Dakota</a> ,
<a href="index.phtml?network=SDCLIMATE">South Dakota</a> ,
<a href="index.phtml?network=WICLIMATE">Wisconsin</a>.

<div class="alert alert-info">The daily observations that are used in these 
summary reports can be downloaded from 
<a class="alert-link" href="/request/coop/fe.phtml">here</a>.</div>


<div id="iem-form2">
<form method="GET" action="index.phtml" name="olselect">
<input type="hidden" name="network" value="{$network}" />

<table cellpadding=2 cellspacing=1>
  <tr><th>Select Climate Station:</th><th>Select Report:</th><td></td></tr>

<tr><td>{$nselect}
<br />or <a href="index.phtml?report=${report}">Select from map</a></td>

<td valign="top">
{$vselect}</td>
<td><input type="submit" value="View Report"></td></tr></table>
</form>
<p>
EOF;

if (is_file("/mesonet/share/climodat/reports/${station}_$report.txt")){
$content .= <<<EOF
<table cellpadding="2"><tr><th>Download Options</th><td><form name="dl" action="index.phtml">
  <input type="hidden" name="dl" value="yes">
  <input type="hidden" name="station" value="$station"> 
  <input type="hidden" name="report" value="$report">
  <input type="submit" value="Download Text Version">
</form></td>
<td><form name="excel" action="as-excel.php">
  <input type="hidden" name="station" value="$station"> 
  <input type="hidden" name="report" value="$report">
  <input type="submit" value="Download Excel Version"></form></td>
</tr></table>
<pre>
EOF;
  $content .= file_get_contents("/mesonet/share/climodat/reports/${station}_$report.txt");
$content .= "</pre>\n";
} else {
$content .= <<<EOF
	<style type="text/css">
        #map {
            width: 640px;
            height: 400px;
            border: 2px solid black;
        }
</style>
<i>Click black dot to select your site:</i><br />
<div id="map"></div>


<a name="ks"><h3 class="subtitle">"Kitchen Sink" Datafiles</h3></a>
<div id="iem-form2">
While the climodat reports are useful, they only provide information for one variable and one site at a time.  These "kitchen sink" datafiles contain the raw information broken down by year and month for variables like high/low temperature and precipitation.

<p><strong>Download:</strong>
<br />You can download all of the datafiles in one <a href="everything.zip">Zipfile (0.8 MB)</a> or <a href="ks/">browse a directory</a> to pick the individual files you want.

<p><strong>Format:</strong>
<br /><img src="/images/gisready.png" style="float: left;"> These text files are in a simple comma delimited format.  Two of the data columns contain the latitude
and longitude information which allows easy import into most GIS systems.

<p><strong>Details: <i>yearly file</i></strong>
<br />There is one yearly file (named <a href="ks/yearly.csv">yearly.csv</a>) which contains yearly summaries dating back to 1951.  Please consult the help file (named <a href="ks/yearly_ks.txt">yearly_ks.txt</a>) for further details.

<p><strong>Details: <i>monthly files</i></strong>
<br />For every year dating back to 1951, there is one file per year which 
contains monthly summaries of high/low temperature and precipitation.  You
can browse <a href="ks/">this directory</a> to pick the files you want or just 
download <a href="everything.zip">everything</a> to save the hassle. Please
consult the help file (named <a href="ks/monthly_ks.txt">monthly_ks.txt</a>)
for further details.

<p>Did these reports help?  Please let <a href="/info/contacts.php">us know</a> 
if you would like to see other variables in these files or have any other comments about them.  Enjoy!
</div>

<p><b>Disclaimer:</b> While we use care to provide accurate weather/climatic information, errors may occur because of equipment or other failure. We therefore provide this information without any warranty of accuracy. Users of this weather/climate data do so at their own risk, and are advised to use independent judgement as to whether to verify the data presented.</p>
</div>
EOF;
}  
$t->content = $content;
$t->render("single.phtml");
?>