-- Add Decagon Data Storage
CREATE TABLE decagon_data(
	uniqueid varchar(24),
	plotid varchar(24),
	valid timestamptz,
	d1moisture real,
	d1moisture_flag char(1),
	d1moisture_qc real,
	d1temp real,
	d1temp_flag char(1),
	d1temp_qc real,
	d1ec real,
	d1ec_flag char(1),
	d1ec_qc real,
	d2moisture real,
	d2moisture_flag char(1),
	d2moisture_qc real,
	d2temp real,
	d2temp_flag char(1),
	d2temp_qc real,
	d3moisture real,
	d3moisture_flag char(1),
	d3moisture_qc real,
	d3temp real,
	d3temp_flag char(1),
	d3temp_qc real,
	d4moisture real,
	d4moisture_flag char(1),
	d4moisture_qc real,
	d4temp real,
	d4temp_flag char(1),
	d4temp_qc real,
	d5moisture real,
	d5moisture_flag char(1),
	d5moisture_qc real,
	d5temp real,
	d5temp_flag char(1),
	d5temp_qc real
);
CREATE INDEX decagon_valid_idx on decagon_data(valid);
GRANT SELECT on decagon_data to nobody,apache;
