<?php
 include("../../config/settings.inc.php");
 $station = isset($_GET["station"])? substr($_GET["station"],0,5) : "";
 $network = isset($_GET["network"])? substr($_GET["network"],0,7) : "IA_COOP";
 $date = isset($_GET["date"]) ? substr($_GET["date"],0, 10) : "";
 $sortvar = isset($_GET["sortvar"]) ? substr($_GET["sortvar"], 0, 10): "";
 $year = isset($_GET["year"]) ? substr($_GET["year"], 0, 4): date("Y");

 if ($date == "" && $station == "") $station = "AMSI4";
 include("$rootpath/include/forms.php");
?>

<?php 
$TITLE = "IEM | COOP Obs";
$THISPAGE = "networks-coop";
include("$rootpath/include/header.php"); ?>

<div class="text"
<b>Nav:</b> <a href="/COOP/">NWS COOP</a> <b> > </b> Print Obs

<?php 

if (strlen($station) > 0) {
  $link = "cat.phtml?station=".$station."&network=". $network ."&sortvar=";
  if ($sortvar == "") $sortvar = "day";
 ?>
<h3 class="subtitle">COOP obs listed by station</h3>(<i>Click on a date to get all obs for a particular date.</i>)
<form name="switchnwsli" action="cat.phtml" method="GET">
<p>Enter NWSLI:<input type="text" size="6" maxlength="5" name="station" value="<?php echo $station; ?>">
Select Year: <?php echo yearSelect(2004, $year, "year"); ?>
<input type="submit" value="View COOP Station"></form>
<?php } 
 
if (strlen($date) > 0) { 
  $year = substr($date,0,4);
  $link = "cat.phtml?date=".$date."&network=". $network ."&sortvar=";
  if ($sortvar == "") $sortvar = "station";
?>
<h3 class="subtitle">COOP obs listed by date</h3>(<i>Click on the NWSLI to view all obs from one station.</i>)
<form name="switchdate" action="cat.phtml" method="GET">
<p>Enter Date:<input type="text" size="11" maxlength="10" name="date" value="<?php echo $date; ?>">
Select State: <select name="network">
 <option value="AL_COOP" <?php if ($network == "AL_COOP") echo "SELECTED"; ?>>Alabama
 <option value="AK_COOP" <?php if ($network == "AK_COOP") echo "SELECTED"; ?>>Alaska
 <option value="AR_COOP" <?php if ($network == "AR_COOP") echo "SELECTED"; ?>>Arkansas
 <option value="AZ_COOP" <?php if ($network == "AZ_COOP") echo "SELECTED"; ?>>Arizona
 <option value="CA_COOP" <?php if ($network == "CA_COOP") echo "SELECTED"; ?>>California
 <option value="CO_COOP" <?php if ($network == "CO_COOP") echo "SELECTED"; ?>>Colorado
 <option value="CT_COOP" <?php if ($network == "CT_COOP") echo "SELECTED"; ?>>Connecticut
 <option value="DE_COOP" <?php if ($network == "DE_COOP") echo "SELECTED"; ?>>Delaware
 <option value="FL_COOP" <?php if ($network == "FL_COOP") echo "SELECTED"; ?>>Florida
 <option value="GA_COOP" <?php if ($network == "GA_COOP") echo "SELECTED"; ?>>Georgia
 <option value="HI_COOP" <?php if ($network == "HI_COOP") echo "SELECTED"; ?>>Hawaii
 <option value="ID_COOP" <?php if ($network == "ID_COOP") echo "SELECTED"; ?>>Idaho
 <option value="IL_COOP" <?php if ($network == "IL_COOP") echo "SELECTED"; ?>>Illinois
 <option value="IN_COOP" <?php if ($network == "IN_COOP") echo "SELECTED"; ?>>Indiana
 <option value="IA_COOP" <?php if ($network == "IA_COOP") echo "SELECTED"; ?>>Iowa
 <option value="KS_COOP" <?php if ($network == "KS_COOP") echo "SELECTED"; ?>>Kansas
 <option value="KY_COOP" <?php if ($network == "KY_COOP") echo "SELECTED"; ?>>Kentucky
 <option value="LA_COOP" <?php if ($network == "LA_COOP") echo "SELECTED"; ?>>Louisana
 <option value="ME_COOP" <?php if ($network == "ME_COOP") echo "SELECTED"; ?>>Maine
 <option value="MD_COOP" <?php if ($network == "MD_COOP") echo "SELECTED"; ?>>Maryland
 <option value="MA_COOP" <?php if ($network == "MA_COOP") echo "SELECTED"; ?>>Massachusetts
 <option value="MI_COOP" <?php if ($network == "MI_COOP") echo "SELECTED"; ?>>Michigan
 <option value="MN_COOP" <?php if ($network == "MN_COOP") echo "SELECTED"; ?>>Minnesota
 <option value="MS_COOP" <?php if ($network == "MS_COOP") echo "SELECTED"; ?>>Mississippi
 <option value="MO_COOP" <?php if ($network == "MO_COOP") echo "SELECTED"; ?>>Missouri
 <option value="MT_COOP" <?php if ($network == "MT_COOP") echo "SELECTED"; ?>>Montana
 <option value="NE_COOP" <?php if ($network == "NE_COOP") echo "SELECTED"; ?>>Nebraska
 <option value="NH_COOP" <?php if ($network == "NH_COOP") echo "SELECTED"; ?>>New Hampshire
 <option value="NC_COOP" <?php if ($network == "NC_COOP") echo "SELECTED"; ?>>North Carolina
 <option value="ND_COOP" <?php if ($network == "ND_COOP") echo "SELECTED"; ?>>North Dakota
 <option value="NV_COOP" <?php if ($network == "NV_COOP") echo "SELECTED"; ?>>Nevada
 <option value="NH_COOP" <?php if ($network == "NH_COOP") echo "SELECTED"; ?>>New Hampshire
 <option value="NJ_COOP" <?php if ($network == "NJ_COOP") echo "SELECTED"; ?>>New Jersey
 <option value="NM_COOP" <?php if ($network == "NM_COOP") echo "SELECTED"; ?>>New Mexico
 <option value="NY_COOP" <?php if ($network == "NY_COOP") echo "SELECTED"; ?>>New York
 <option value="OH_COOP" <?php if ($network == "OH_COOP") echo "SELECTED"; ?>>Ohio
 <option value="OK_COOP" <?php if ($network == "OK_COOP") echo "SELECTED"; ?>>Oklahoma
 <option value="OR_COOP" <?php if ($network == "OR_COOP") echo "SELECTED"; ?>>Oregon
 <option value="PA_COOP" <?php if ($network == "PA_COOP") echo "SELECTED"; ?>>Pennsylvania
 <option value="RI_COOP" <?php if ($network == "RI_COOP") echo "SELECTED"; ?>>Rhode Island
 <option value="SC_COOP" <?php if ($network == "SC_COOP") echo "SELECTED"; ?>>South Carolina
 <option value="SD_COOP" <?php if ($network == "SD_COOP") echo "SELECTED"; ?>>South Dakota
 <option value="TN_COOP" <?php if ($network == "TN_COOP") echo "SELECTED"; ?>>Tennessee
 <option value="TX_COOP" <?php if ($network == "TX_COOP") echo "SELECTED"; ?>>Texas
 <option value="UT_COOP" <?php if ($network == "UT_COOP") echo "SELECTED"; ?>>Utah
 <option value="VT_COOP" <?php if ($network == "VT_COOP") echo "SELECTED"; ?>>Vermont
 <option value="VA_COOP" <?php if ($network == "VA_COOP") echo "SELECTED"; ?>>Virginia
 <option value="WA_COOP" <?php if ($network == "WA_COOP") echo "SELECTED"; ?>>Washington
 <option value="WV_COOP" <?php if ($network == "WV_COOP") echo "SELECTED"; ?>>West Virginia
 <option value="WI_COOP" <?php if ($network == "WI_COOP") echo "SELECTED"; ?>>Wisconsin
 <option value="WY_COOP" <?php if ($network == "WY_COOP") echo "SELECTED"; ?>>Wyoming
</select>
<input type="submit" value="View Date"></form>
<?php } ?>

<p><table border="1" cellspacing=0 cellpadding=2>
<tr>
  <th><a href="<?php echo $link; ?>station">NWSLI:</a></th>
  <th>Site Name:</th>
  <th><a href="<?php echo $link; ?>day">Date:</a></th>
  <th><a href="<?php echo $link; ?>max_tmpf">Max Air Temp</a></th>
  <th><a href="<?php echo $link; ?>min_tmpf">Min Air Temp</a></th>
  <th><a href="<?php echo $link; ?>pday">Precip</a></th>
  <th><a href="<?php echo $link; ?>snow">Snowfall</a></th>
  <th><a href="<?php echo $link; ?>snowd">Snow Depth</a></th></tr>

<?php 
 include("$rootpath/include/iemaccess.php");
 include("$rootpath/include/network.php");
 $nt = new NetworkTable($network);
 $cities = $nt->table;
 $iem = new IEMAccess();

 $sortdir = "ASC";
 if ($sortvar == "pday" || $sortvar == "snow" || $sortvar == "snowd" ||
     $sortvar == "max_tmpf") 
   $sortdir = "DESC";
 if (strlen($station) > 0) {
   $rs = $iem->query("SELECT * from summary_$year WHERE station = '$station'
     and network ~* 'COOP' ORDER by $sortvar $sortdir");
 } else {
   $rs = $iem->query("SELECT * from summary_$year WHERE day = '$date' and
     network = '$network' ORDER by $sortvar $sortdir");
 }
 $hirow = 1;
 for( $i=0; $row = @pg_fetch_array($rs,$i); $i++) {
   $nwsli = $row["station"];

   $high = $row["max_tmpf"];
   if ($high == "-99" || $high == "") $high = "M";
   if ($high > 130 || $high < -50) $high = "M";

   $low = $row["min_tmpf"];
   if ($low == "99" || $low == "" || $low == -99) $low = "M";
   if ($low > 130 || $low < -50) $low = "M";

   $rain = $row["pday"];
   if ($rain == 0.0001 || $rain == 0.001) $rain = "T";
   if ($rain == -99 || $rain == "") $rain = "M";
   if ($rain > 10 || $rain < 0) $rain = "M";

   $snow = $row["snow"];
   if ($snow == 0.0001 || $snow == 0.001) $snow = "T";
   if ($snow == -99 || $snow == "") $snow = "M";
   if ($snow > 100 || $snow < 0) $snow = "M";

   $snowd = $row["snowd"];
   if ($snowd == 0.0001 || $snowd == 0.001) $snowd = "T";
   if ($snowd == -99 || $snowd == "") $snowd = "M";
   if ($snowd > 1000 || $snowd < 0) $snowd = "M";

   echo "<tr";
   if ($hirow) echo " class=\"even\"";
   $hirow = ! $hirow;
   echo "><td>";
   if (strlen($station) > 0){
     echo $nwsli;
   } else {
     echo "<a href=\"cat.phtml?station=". $nwsli ."&network=". $network ."\">". $nwsli ."</a>";
   }

   echo "</td><td>". $cities[$nwsli]["name"] ."</td><td>";

   if (strlen($date) > 0){
      echo $row["day"];
   } else {
      echo "<a href=\"cat.phtml?date=". $row["day"] ."&network=". $network ."\">". $row["day"] ."</a>";
   }

   echo "</td><td>". $high ."</td><td>". $low ."</td><td>". $rain ."</td><td>". $snow ."</td><td>". $snowd ."</td></tr>\n";
 }

 
?>
</table>

<p>Theoretically, you should be able to highlight the entire table with 
your cursor and then copy-paste it into a spreadsheet program if you 
like.

<p>Errors exist in this dataset and you should evaluate the observations
before using...</div>

<?php include("$rootpath/include/footer.php"); ?>
