<?php 
/*
 * NWS COOP currents lister
 */
include("../../config/settings.inc.php");
define("IEM_APPID", 41);
 include("$rootpath/include/network.php");
 include("$rootpath/include/wfoLocs.php");
 include("$rootpath/include/forms.php");
 include("$rootpath/include/iemaccess.php");
 include("$rootpath/include/iemaccessob.php");
 
  $network = isset($_GET['network']) ? $_GET['network'] : 'IA_COOP'; 
  $wfo = isset($_REQUEST["wfo"]) ? $_REQUEST['wfo'] : null;
  $sortcol = isset($_GET['sortcol']) ? $_GET['sortcol'] : 'ts';

   $iem = new IEMAccess();
 if ($wfo == null){
   $net = $iem->getNetwork($network);
   $baseurl = "current.phtml?network=$network&sortcol=";
 } else {
 	$net = $iem->getWFO_COOP($wfo);
 	$baseurl = "current.phtml?wfo=$wfo&sortcol=";
 }
  
  $TITLE = "IEM | NWS COOP | Current Sortables";
 $HEADEXTRA = '<script language="JavaScript" type="text/javascript">
	<!--//BEGIN Script
	function new_window(url) {
 	link = window.open(url,"_new","toolbar=0,location=0,directories=0,status=0,menubar=no,scrollbars=yes,resizable=yes,width=800,height=600");
	}
	//END Script-->
	</script>';
 $THISPAGE = "current-sort";
include("$rootpath/include/header.php"); ?>
<?php

 $db = Array();
 while (list($site, $iemob) = each($net) ){
  $db[$site] = Array('snow'=> "", 'snowd'=>"", 'ratio'=>"", 'pday'=>"",
                      'min_tmpf'=>"", 'max_tmpf'=>"", 'tmpf'=>"", 'snoww'=>"");
  $db[$site]['ts'] = $iemob->ts;
  $db[$site]['lts'] = $iemob->lts;
  $db[$site]['sid'] = $site;
  $db[$site]['sname'] = $iemob->db["sname"];
  $db[$site]['state'] = $iemob->db["state"];
  $db[$site]['network'] = $iemob->db["network"];
  $db[$site]['county'] = $iemob->db["county"];
  if ($iemob->db["tmpf"] > -100) {
    $db[$site]['tmpf'] = $iemob->db["tmpf"];
  }
  if ($iemob->db["max_tmpf"] > -100) {
    $db[$site]['max_tmpf'] = $iemob->db["max_tmpf"];
  }
  
  if ($iemob->db["min_tmpf"] < 99) {
    $db[$site]['min_tmpf'] = $iemob->db["min_tmpf"];
  } 
  
  $db[$site]['pday'] = $iemob->db["pday"];
  $db[$site]['snoww'] = $iemob->db["snoww"];
  $db[$site]['snow'] = ($iemob->db["snow"] >= 0) ? $iemob->db["snow"] : "";
  $db[$site]['snowd'] = ($iemob->db["snowd"] >= 0) ? $iemob->db["snowd"] : "";
  $db[$site]["ratio"] = -1;
  if ($db[$site]["snow"] > 0.001 && $db[$site]["pday"] > 0.001)
   {
     $db[$site]["ratio"] = intval( $db[$site]["snow"] / $db[$site]["pday"] );
   }
  }

function aSortBySecondIndex($multiArray, $secondIndex) {
        while (list($firstIndex, ) = each($multiArray))
                $indexMap[$firstIndex] = $multiArray[$firstIndex][$secondIndex];        arsort($indexMap);
        while (list($firstIndex, ) = each($indexMap))
                if (is_numeric($firstIndex))
                        $sortedArray[] = $multiArray[$firstIndex];
                else $sortedArray[$firstIndex] = $multiArray[$firstIndex];
        return $sortedArray;
}

$db = aSortBySecondIndex($db, $sortcol);

$cols = Array("ts" => "Valid", "county" => "County",
  "sid" => "Site ID", "sname" => "Station Name", 
  "ratio" => "Snow to Water Ratio",
  "tmpf" => "Ob Temperature", "max_tmpf" => "24 hour High",
  "min_tmpf" => "24 hour Low", "snow" => "24 hour Snowfall",
  "snowd" => "Snowfall Depth", "pday" => "24 hour rainfall",
  "phour" => "Rainfall One Hour", "snoww" => "Snow Water Equivalent");
?>

<?php $current_network = "COOP"; include("$rootpath/include/current_bar.inc.php"); ?>

<form method="GET" action="current.phtml" name="stctrl">
<input type="hidden" name="sortcol" value="<?php echo $sortcol; ?>">
Option 1: <strong>View by State:</strong> <select name="network">
 <option value="AL_COOP" <?php if ($network == "AL_COOP") echo "SELECTED"; ?>>Alabama
 <option value="AK_COOP" <?php if ($network == "AK_COOP") echo "SELECTED"; ?>>Alaska
 <option value="AR_COOP" <?php if ($network == "AR_COOP") echo "SELECTED"; ?>>Arkansas
 <option value="AZ_COOP" <?php if ($network == "AZ_COOP") echo "SELECTED"; ?>>Arizona
 <option value="CA_COOP" <?php if ($network == "CA_COOP") echo "SELECTED"; ?>>California
 <option value="CO_COOP" <?php if ($network == "CO_COOP") echo "SELECTED"; ?>>Colorado
 <option value="CT_COOP" <?php if ($network == "CT_COOP") echo "SELECTED"; ?>>Connecticut
 <option value="DE_COOP" <?php if ($network == "DE_COOP") echo "SELECTED"; ?>>Delaware
 <option value="FL_COOP" <?php if ($network == "FL_COOP") echo "SELECTED"; ?>>Florida
 <option value="GA_COOP" <?php if ($network == "GA_COOP") echo "SELECTED"; ?>>Georgia
 <option value="HI_COOP" <?php if ($network == "HI_COOP") echo "SELECTED"; ?>>Hawaii
 <option value="ID_COOP" <?php if ($network == "ID_COOP") echo "SELECTED"; ?>>Idaho
 <option value="IL_COOP" <?php if ($network == "IL_COOP") echo "SELECTED"; ?>>Illinois
 <option value="IN_COOP" <?php if ($network == "IN_COOP") echo "SELECTED"; ?>>Indiana
 <option value="IA_COOP" <?php if ($network == "IA_COOP") echo "SELECTED"; ?>>Iowa
 <option value="KS_COOP" <?php if ($network == "KS_COOP") echo "SELECTED"; ?>>Kansas
 <option value="KY_COOP" <?php if ($network == "KY_COOP") echo "SELECTED"; ?>>Kentucky
 <option value="LA_COOP" <?php if ($network == "LA_COOP") echo "SELECTED"; ?>>Louisana
 <option value="ME_COOP" <?php if ($network == "ME_COOP") echo "SELECTED"; ?>>Maine
 <option value="MD_COOP" <?php if ($network == "MD_COOP") echo "SELECTED"; ?>>Maryland
 <option value="MA_COOP" <?php if ($network == "MA_COOP") echo "SELECTED"; ?>>Massachusetts
 <option value="MI_COOP" <?php if ($network == "MI_COOP") echo "SELECTED"; ?>>Michigan
 <option value="MN_COOP" <?php if ($network == "MN_COOP") echo "SELECTED"; ?>>Minnesota
 <option value="MS_COOP" <?php if ($network == "MS_COOP") echo "SELECTED"; ?>>Mississippi
 <option value="MO_COOP" <?php if ($network == "MO_COOP") echo "SELECTED"; ?>>Missouri
 <option value="MT_COOP" <?php if ($network == "MT_COOP") echo "SELECTED"; ?>>Montana
 <option value="NE_COOP" <?php if ($network == "NE_COOP") echo "SELECTED"; ?>>Nebraska
 <option value="NH_COOP" <?php if ($network == "NH_COOP") echo "SELECTED"; ?>>New Hampshire
 <option value="NC_COOP" <?php if ($network == "NC_COOP") echo "SELECTED"; ?>>North Carolina
 <option value="ND_COOP" <?php if ($network == "ND_COOP") echo "SELECTED"; ?>>North Dakota
 <option value="NV_COOP" <?php if ($network == "NV_COOP") echo "SELECTED"; ?>>Nevada
 <option value="NH_COOP" <?php if ($network == "NH_COOP") echo "SELECTED"; ?>>New Hampshire
 <option value="NJ_COOP" <?php if ($network == "NJ_COOP") echo "SELECTED"; ?>>New Jersey
 <option value="NM_COOP" <?php if ($network == "NM_COOP") echo "SELECTED"; ?>>New Mexico
 <option value="NY_COOP" <?php if ($network == "NY_COOP") echo "SELECTED"; ?>>New York
 <option value="OH_COOP" <?php if ($network == "OH_COOP") echo "SELECTED"; ?>>Ohio
 <option value="OK_COOP" <?php if ($network == "OK_COOP") echo "SELECTED"; ?>>Oklahoma
 <option value="OR_COOP" <?php if ($network == "OR_COOP") echo "SELECTED"; ?>>Oregon
 <option value="PA_COOP" <?php if ($network == "PA_COOP") echo "SELECTED"; ?>>Pennsylvania
 <option value="RI_COOP" <?php if ($network == "RI_COOP") echo "SELECTED"; ?>>Rhode Island
 <option value="SC_COOP" <?php if ($network == "SC_COOP") echo "SELECTED"; ?>>South Carolina
 <option value="SD_COOP" <?php if ($network == "SD_COOP") echo "SELECTED"; ?>>South Dakota
 <option value="TN_COOP" <?php if ($network == "TN_COOP") echo "SELECTED"; ?>>Tennessee
 <option value="TX_COOP" <?php if ($network == "TX_COOP") echo "SELECTED"; ?>>Texas
 <option value="UT_COOP" <?php if ($network == "UT_COOP") echo "SELECTED"; ?>>Utah
 <option value="VT_COOP" <?php if ($network == "VT_COOP") echo "SELECTED"; ?>>Vermont
 <option value="VA_COOP" <?php if ($network == "VA_COOP") echo "SELECTED"; ?>>Virginia
 <option value="WA_COOP" <?php if ($network == "WA_COOP") echo "SELECTED"; ?>>Washington
 <option value="WV_COOP" <?php if ($network == "WV_COOP") echo "SELECTED"; ?>>West Virginia
 <option value="WI_COOP" <?php if ($network == "WI_COOP") echo "SELECTED"; ?>>Wisconsin
 <option value="WY_COOP" <?php if ($network == "WY_COOP") echo "SELECTED"; ?>>Wyoming
</select>
<input type="submit" value="Go!">
</form>

<form method="GET" action="current.phtml" name="wfoctrl">
<input type="hidden" name="sortcol" value="<?php echo $sortcol; ?>">
Option 2: <strong>View by WFO:</strong> <?php echo wfoSelect($wfo); ?>
<input type="submit" value="Go!">
</form>

<?php
echo "<p>Sorted by: <strong>". $cols[$sortcol] ."</strong>. 
Times are presented in the local time of the site. Click on the identifier to
get all daily observations for the site.  Click on the site name to get more
information on the site.";
 
?>
<form name="st" action="/my/current.phtml" method="GET">
<table cellspacing="0" cellpadding="2" border="1"
       style="width: 100%; font-size: 10pt;" class="ruler">
<thead>
<tr>
  <th rowspan=2>Add:</th>
  <th rowspan=2><a href="<?php echo $baseurl; ?>sid">SiteID:</a></th>
  <th rowspan=2><a href="<?php echo $baseurl; ?>sname">Station Name:</a></th>
  <th rowspan=2><a href="<?php echo $baseurl; ?>county">County:</a></th>
  <th rowspan=2><a href="<?php echo $baseurl; ?>ts">Valid:</a></th>
  <th colspan=3>Temperatures [F]</th>
  <th colspan="5">Hydro</th></tr>

<tr>
  <th><a href="<?php echo $baseurl; ?>tmpf">At Ob</a></th>
  <th><a href="<?php echo $baseurl; ?>max_tmpf">24h High</a></th>
  <th><a href="<?php echo $baseurl; ?>min_tmpf">24h Low</a></th>
  <th><a href="<?php echo $baseurl; ?>pday">24hour Rain</a></th>
  <th><a href="<?php echo $baseurl; ?>snow">Snowfall</a></th>
  <th><a href="<?php echo $baseurl; ?>ratio">Ratio</a></th>
  <th><a href="<?php echo $baseurl; ?>snowd">Snow Depth</a></th>
  <th><a href="<?php echo $baseurl; ?>snoww">SWE</a></th>
</tr></thead>
<tbody>
<?php

 function precip_formatter($val){
 	if ($val == '') return '';
 	if ($val == 0.001) return 'T';
 	if ($val < 0) return 'M';
 	return $val;
 }

 function make_row($dict, $oddrow){
 	$s = "<tr";
 	if ($oddrow) $s .= ' bgcolor="#EEEEEE"';
 	$s .= ">";

 	$sitesurl = sprintf("%s/sites/site.php?station=%s&network=%s",
 		BASEURL, $dict["sid"], $dict["network"]);
 	
 	$s .= "<th><input type=\"checkbox\" name=\"st[]\" value=\"". $dict["sid"] ."\" /></th>";
 	$s .= "<td><a href=\"cat.phtml?station=". $dict["sid"] ."&network=". $dict["network"] . "\">". $dict['sid'] ."</a></td>";
 	$s .= "<td><a href=\"$sitesurl\">". $dict["sname"] .", ". $dict["state"] ."</a></td>";
    $s .= "<td>". $dict["county"] ."</td>";
 	
    $bgcolor = (date("Ymd") != date("Ymd", $dict["ts"])) ? '#F00': 'inherit';
    $fmt = (date("Ymd") != date("Ymd", $dict["ts"])) ? '%d %b %Y %I:%M %p': '%I:%M %p';
    $s .= "<td style=\"background: $bgcolor;\">". strftime($fmt, $dict["lts"]) ."</td>";
    
    $s .= sprintf("<td>%s</td><td><span style=\"color: #F00;\">%s</span></td>
    <td><span style=\"color: #00F;\">%s</span></td>", 
     $dict["tmpf"] != "" ? $dict["tmpf"] : "M",
     $dict["max_tmpf"] != "" ? $dict["max_tmpf"] : "M",
     $dict["min_tmpf"] != "" ? $dict["min_tmpf"] : "M"
    );
    
    $s .= sprintf("<td>%s</td><td>%s</td><td>%s</td><td>%s</td><td>%s</td>", precip_formatter($dict["pday"]),
    precip_formatter($dict["snow"]), precip_formatter($dict["ratio"]), precip_formatter($dict["snowd"]),
    precip_formatter($dict["snoww"]));
    
 	$s .= "</tr>\n";
 	return $s;
 }

 $oddrow = true;
 $firstsection = "";
 $lastsection = "";
 while (list($site, $value) = each($db) ){
   $oddrow = ! $oddrow;
   if (date("Ymd", $value["ts"]) == date("Ymd")){
   		$firstsection .= make_row($value, $oddrow);
   } else {
   		$value["tmpf"] = "";
   		$lastsection .= make_row($value, $oddrow);
   }
 }
 echo $firstsection;
 echo $lastsection;
?>
</tbody><tfoot>
<tr>
 <td colspan=6>&nbsp;</td>
<?php $c = "javascript:new_window('$rooturl/GIS/apps/php/currents.phtml?layers[]=radar&layers[]=labels&network=$network&var="; ?>
 <td><a href="<?php echo $c; ?>max_tmpf');">Plot</a></td>
 <td><a href="<?php echo $c; ?>min_tmpf');">Plot</a></td>
 <td><a href="<?php echo $c; ?>pday');">Plot</a></td>
 <td><a href="<?php echo $c; ?>snow');">Plot</a></td>
 <td></td>
 <td><a href="<?php echo $c; ?>snowd');">Plot</a></td>
 <td><a href="<?php echo $c; ?>snoww');">Plot</a></td>
</tr></tfoot>
</table>
<input type="submit" value="Add to Favorites">
</form>


<?php include("$rootpath/include/footer.php");
?>
