<?php 
 require_once "../../config/settings.inc.php";
 require_once "../../include/myview.php";
 require_once "../../include/generators.php";
 $t = new MyView();

 $t->title = "NWS COOP Data";

 $yr = date("Y");
 
 $dict = Array( 
 		Array("img" => "chart_line_f_t.png",
 				"url" => "/plotting/coop/threshold_histogram_fe.phtml",
 				"title" => "Winter Min Low Temp Frequencies",
 				"desc" => "Histogram showing the number of years that a certain low temperature threshold is exceeded."),
 
 		Array("img" => "chart_line_h_t.png",
 				"url" => "/plotting/coop/spread_fe.phtml",
 				"title" => "Daily Temperature Spread",
 				"desc" => "Histogram showing daily high/low temperatures."),
 
 		Array("img" => "data_table.png",
 				"url" => "/COOP/periods.phtml",
 				"title" => "Yearly Average Temperatures",
 				"desc" => "For a date interval of your choice, get the yearly statewide average temperatures."),
 
 		Array("img" => "data_table.png",
 				"url" => "/sites/hist.phtml?station=AMSI4&network=IA_COOP",
 				"title" => "Observations by Month",
 				"desc" => "View observations per station and per month basis."),
 
 		Array("img" => "data_table.png",
 				"url" => "/COOP/freezing.php",
 				"title" => "Fall Freezing Dates",
 				"desc" => "Statistics of dates for significant first fall freezes."),
 
 		Array("img" => "data_table.png",
 				"url" => "/COOP/snowd_duration.phtml",
 				"title" => "Snow Depth Duration",
 				"desc" => "For a given date, how long will the snow stick around?"),
 
 		Array("img" => "data_table.png",
 				"url" => "/COOP/extremes.php",
 				"title" => "Daily Climate in Tables",
 				"desc" => "Tables of daily temperature and precipitation climatology."),
 
 		Array("img" => "thumb_map.png",
 				"url" => "/GIS/apps/coop/index.php",
 				"title" => "Daily Climate in Maps",
 				"desc" => "Plots of daily extremes and averages with a GIS Ready! download of the data presented."),
 
 		Array("img" => "chart_line_t_d.png",
 				"url" => "/plotting/coop/climate_fe.php",
 				"title" => "Daily Average Temperatures",
 				"desc" => "Dynamically produced chart of average daily temperatures."),
 
 		Array("img" => "chart_line_t_y.png",
 				"url" => "/plotting/auto/?q=100",
 				"title" => "Yearly Average Temperatures",
 				"desc" => "Plot average daily temperatures for a year of your choice."),
 
 		Array("img" => "chart_line_d_a.png",
 				"url" => "/plotting/auto/?q=107",
 				"title" => "Accumulated Precipitation Probabilities",
 				"desc" => "Chart of precip probabilities for a time period of your choice."),
 
 		Array("img" => "chart_line_t_d.png",
 				"url" => "/plotting/coop/extremes_fe.php",
 				"title" => "Daily Temperatures Extremes",
 				"desc" => "Plot average temperatures and extremes throughout a year."),
 
 		Array("img" => "chart_line_t_d.png",
 				"url" => "/plotting/auto/?q=99",
 				"title" => "Yearly Departures from Average",
 				"desc" => "Plot average temperatures versus what actually occured during one year."),
 
 		Array("img" => "chart_line_ac_d.png",
 				"url" => "/plotting/auto/?q=108",
 				"title" => "Accumulated Departures from Average",
 				"desc" => "Plot an accumulated departure from average for rainfall and growing degree days for a time period of your choice!"),
 
 		Array("img" => "thumb_map.png",
 				"url" => "/GIS/apps/coop/plot.phtml",
 				"title" => "Map Daily Observations",
 				"desc" => "Generate maps of daily observations."),
 
 );
 $content = "";
 foreach($dict as $k => $v)
 {
 	$content .= <<<EOF
<div class="tease">
 <a href="{$v["url"]}"><img src="/images/{$v["img"]}" border="0"></a>
 <a href="{$v["url"]}">{$v["title"]}</a><br />{$v["desc"]}<br />&nbsp;
</div>
EOF;
 }
 
$news = get_news_by_tag("coop");
 
$t->content = <<<EOF
<div class="row">
 <div class="col-md-2 col-sm-2">
 <span style="font-size: 1.3em;">NWS COOP<br />Quick Links</span>
 </div>
 <div class="col-md-1 col-sm-1">
 <a href="/climodat/"><img src="/images/fileprint.png" /><br />Climodat</a>
 </div>
 <div class="col-md-1 col-sm-1">
 <a href="current.phtml"><img src="/images/view_text.png" /><br />Currents</a>
 </div>
  <div class="col-md-1 col-sm-1">
  <a href="/request/coop/obs-fe.phtml"><img src="/images/down.png" /><br />Download Raw</a>
 </div>
  <div class="col-md-1 col-sm-1">
  <a href="/request/coop/fe.phtml"><img src="/images/down.png" /><br />Download QC</a>
 </div>
  <div class="col-md-2 col-sm-2">
  <a href="/sites/locate.php?network=IA_COOP"><img src="/images/find.png" /><br />Locate Site</a>
 </div>
  <div class="col-md-2 col-sm-2">
  <a href="cat.phtml"><img src="/images/misc.png" /><br />2004-{$yr}</a>
 </div>
  <div class="col-md-2 col-sm-2">
  <a href="/GIS/apps/coop/gsplot.phtml"><img src="/images/view_icon.png" /><br />Growing Season</a>
 </div>
 </div>


<p>The National Weather Service [NWS] Cooperative Observer Program [COOP]
is a nation-wide network of people making daily weather observations. These
volunteers are invaluable in times of severe weather and heavy snowfall.  Their
observations also provide a 'ground truth' to compare against remote sensing
techniques.

<div class="row">
<div class="col-md-4 col-sm-4">

{$news}

<h3>Data Plots</h3>
<ul>
	<li><a href="/timemachine/#37.0">Iowa Precipitation Contour</a></li>
	<li><a href="/timemachine/#38.0">Midwest Precipitation Contour</a></li>
	<li><a href="/data/coopMonthPlot.gif">Rainfall totals for this month</a></li>
	<li><a href="/data/coopSnowPlot.gif">Snowfall totals this morning</a></li>
	<li><a href="/data/coopMonthSPlot.gif">Snowfall totals this month</a></li>
	<li><a href="/data/coopSnowDepth.gif">Snow depth this morning</a></li>
    <li><a href="/data/coopHighLow.gif">High + Low Temperatures this morning</a></li>
</ul>

</div><div class="col-md-4 col-sm-4">

<h3>Data + Summaries</h3>


<ul>
 <li>A <a href="/data/gis/shape/4326/iem/coopobs.zip">GIS shapefile</a> is 
 generated daily with the most recent set of COOP observation in it.</li>
 <li>A <a href="/data/csv/coop.csv">Comma Delimited File</a> of today's
 COOP observations.</li>
 <li><a href="/data/text/IEMNWSDPR.txt">Today's Rainfall Reports</a>
	<br />Rainfall reports valid for today along with today's climatology.</li>
 <li><a href="/data/text/IEMNWSMPR.txt">This Month's Totals</a>
	<br />Rainfall totals for this month along with climatology.</li>
 <li><a href="/data/text/IEMNWSYPR.txt">This Year's Totals</a>
	<br />Rainfall totals this year along with climatology.</li>
 <li><a href="current.phtml">Sortable Observations</a>
	<br />For all COOP sites in the Upper Midwest.</li>
</ul>



</div><div class="col-md-4 col-sm-4">


<p><h3>Download Data</h3>
<ul>
  <li><a href="/request/coop/fe.phtml">Download Daily Oberservations</a>
    <br>Pick your site, pick a time period, and download the data.</li>
  <li><a href="/COOP/cat.phtml">2004-<?php echo date("Y"); ?> Observations</a>
	<br />View all obs from 2004 to <?php echo date("Y"); ?> for one site or pick a date and view all sites!</li>
  <li><a href="/climodat">ClimoDat Interface</a> 
    <br>Handy application to access summary COOP data.</li>
  <li><a href="/COOP/hpd.php">Fisher Porter Rain Gauge Download</a>
	<br />IEM processed data made available by NCEI for Iowa stations only.</li>
  <li><a href="/GIS/apps/coop/gsplot.phtml">Growing Season Plotter</a>
    <br>Plot growing season totals since 1893 for a date span of your choice.
    <br>The resulting data is also available in a GIS Ready! format.</li>
  <li><a href="dl/normals.phtml">Daily Climate Normals</a>
    <br>Download daily normal high and low temperatures and average rainfall.</li>
</ul>

</div></div>

<p><h3>COOP Data Applications:</h3><br>

<style>
div.tease {
 margin: 5px;
 padding: 5px;
 width: 400px;
 height: 100px;
 background: #e8cc84;
 float: left;
}
div.tease img {
 margin-right: 5px;
 float: left;
}
div.tease a {
 font-weight: bold;
 padding: 5px;
}
</style>

{$content}
<br clear="all" />
EOF;
$t->render('single.phtml');
?>
