<?php
 include("../../config/settings.inc.php");
 include("../../include/myview.php");
 $t = new MyView();
 define("IEM_APPID", 31);
 $smonth = isset($_GET["smonth"]) ? intval($_GET["smonth"]): 0;
 $emonth = isset($_GET["emonth"]) ? intval($_GET["emonth"]): 0;
 $sday = isset($_GET["sday"]) ? intval($_GET["sday"]): 0;
 $eday = isset($_GET["eday"]) ? intval($_GET["eday"]): 0;
 $sortcol = isset($_GET["sortcol"]) ? $_GET["sortcol"] : "avg_high";

 include("../../include/forms.php");
 include("../../include/database.inc.php");
 $t->title = "Time period comparisons";

 $table = "";
 if ($sday > 0){
 	$sts = mktime(0,0,0,$smonth, $sday, 2000);
 	$ets = mktime(0,0,0,$emonth, $eday, 2000);
 	$days = round(( ($ets - $sts) / 86400.0),0) + 1;
 	$drestrict = "days = $days";
 	if ($smonth < 3 && $emonth > 2) $drestrict = "(days = $days or days = $days -1)";
 	
 	$coop = iemdb("coop");
 	
 	$link = "periods.phtml?sday=$sday&eday=$eday&smonth=$smonth&emonth=$emonth&sortcol=";
 	$nicedate = sprintf("%s - %s", date("d M", $sts), date("d M", $ets) );
 	$table .= <<<EOF
 	<p><strong>Yearly average temperatures between ({$nicedate}) 
 	dates inclusive<strong><br />
 	<table cellpadding="2" border="1" cellspacing="0">
 	<tr>
 	  <th><a href="{$link}year">Year:</a></th>
 	  <th># stations</th>
 	  <th><a href="{$link}avg_temp">Avg Temp:</a></th>
 	  <th><a href="{$link}avg_high">Avg High Temp:</a></th>
 	  <th><a href="{$link}avg_low">Avg Low Temp:</a></th>
 	</tr>
EOF;
	 $sql = sprintf("select year, count(station) as stations,
	 		avg(avg_high) as avg_high, avg(avg_low) as avg_low,
	 		avg((avg_high+avg_low)/2.0) as avg_temp from
	 		(select year, station, count(high) as days,
	 		avg(high) as avg_high, avg(low) as avg_low from alldata_ia
	 		WHERE sday BETWEEN '%s' and '%s' and
	 		high > -70 and low > -70 GROUP By year, station) as foo
	 		WHERE $drestrict GROUP by year ORDER by %s DESC", date("md", $sts), date("md",$ets), $sortcol );

	 $rs = pg_exec($coop, $sql);
	 for( $i=0; $row = @pg_fetch_assoc($rs,$i); $i++) {
	 		$table .= sprintf("<tr><th>%s</th><td>%s</td><td>%.2f</td><td>%.2f</td><td>%.2f</td></tr>", $row["year"], $row["stations"], $row["avg_temp"], $row["avg_high"], $row["avg_low"]);
	 }
	 $table .= "</table>";
 }
 
 $smonthselect = monthSelect($smonth, "smonth");
 $sdayselect = daySelect2($sday, "sday");
 $emonthselect = monthSelect($emonth, "emonth");
 $edayselect = daySelect2($eday, "eday");
 
 $t->content = <<<EOF
<ol class="breadcrumb">
	<li><a href="/COOP/">NWS COOP</a></li>
	<li class="active">Yearly time period averages</li>
</ol>

<h3 class="subtitle">COOP obs time period comparison</h3>

This application will compute Iowa statewide temperature averages for a time period 
of your choice based on the observation record the IEM has. This is just 
a simple average done without geographical weighting.  Just select the
date period below and submit the form.

<p><form name="switcher" method="GET">
<table>
<tr><th>Start Date:</th><td>{$smonthselect} {$sdayselect}</td>
 <td rowspan="2"><input type="submit" value="Make yearly comparison"></td></tr>
<tr><th>End Date:</th><td>{$emonthselect} {$edayselect}</td></tr>
</table>
</form>

{$table}

<p>Theoretically, you should be able to highlight the entire table with 
your cursor and then copy-paste it into a spreadsheet program if you 
like.

<p>Errors exist in this dataset and you should evaluate the observations
before using...
EOF;
$t->render('single.phtml');
?>
