<?php
include("../../config/settings.inc.php");

$HEADEXTRA = '<link rel="stylesheet" type="text/css" href="../ext/resources/css/ext-all.css"/>
<script type="text/javascript" src="../ext/adapter/ext/ext-base.js"></script>
<script type="text/javascript" src="../ext/ext-all.js"></script>
<script type="text/javascript" src="rooms.js"></script>
<script type="text/javascript" src="static.js?v=1.0.1"></script>';
$TITLE = "iembot web based monitor";
$NOCONTENT = 1;
$THISPAGE ="severe-iembot";
include("$rootpath/include/header.php");
?>
<style type="text/css">
.new-tab{
  background-image:url(new_tab.gif) !important;
}
td.x-grid3-td-message {
    overflow: hidden;
}
td.x-grid3-td-message div.x-grid3-cell-inner {
    white-space: normal;
}
</style>
<div id="help">
<div style="padding: 10px;">
<h3 class="heading">IEMBot Web Monitor</h3>
<p>&nbsp;</p>
<p>This application is a web based monitor of the messages <a href="http://mesonet.agron.iastate.edu/projecs/iembot/">IEMBot</a> produces.  These messages are organized by the NWS Office that issued them.  You can monitor these messages
in real-time as each office will appear as a "tab" in this window.</p>
<p>&nbsp;</p>
<p>This application presents links to web applications specially designed to
display the various products.  These apps include:
<ul>
 <li><a href="../vtec/">VTEC Product Browser</a></li>
 <li><a href="../GIS/apps/rview/watch.phtml">SPC Watch Overviews</a></li>
 <li><a href="../river/wfo.phtml">River Summary App</a></li>
 <li><a href="../cow/maplsr.phtml">Local Storm Report Mapping</a></li>
</ul>
</p>
<p>&nbsp;</p>
<p>As always, this information is provided without warranty and the possibility of removal in the future.</p>

</div>
</div>
<?php include("$rootpath/include/footer.php"); ?>
