<?php
include("../../config/settings.inc.php");

$HEADEXTRA = '<link rel="stylesheet" type="text/css" href="http://extjs.cachefly.net/ext-3.0.0/resources/css/ext-all.css"/>
<script type="text/javascript" src="http://extjs.cachefly.net/ext-3.0.0/adapter/ext/ext-base.js"></script>
<script type="text/javascript" src="http://extjs.cachefly.net/ext-3.0.0/ext-all.js"></script>
<script type="text/javascript" src="../ext/ux/StatusBar.js"></script>
<script type="text/javascript" src="rooms.js"></script>
<script type="text/javascript" src="soundmanager2.js"></script>
<script>
Ext.namespace("soundManager");
soundManager = new SoundManager();
soundManager.url = "swf/";
soundManager.consoleOnly = true;
soundManager.onload = function() {
 soundManager.createSound("message_new","sounds/message_new.mp3");
}

Ext.namespace("cfg");
cfg.server = "iem";
cfg.banner = "iem-header";
</script>
<script type="text/javascript" src="static.js?v=1.0.2"></script>';
$TITLE = "iembot web based monitor";
$NOCONTENT = 1;
$THISPAGE ="severe-iembot";
include("$rootpath/include/header.php");
?>
<style type="text/css">
.new-tab{
  background-image:url(new_tab.gif) !important;
}
td.x-grid3-td-message {
    overflow: hidden;
}
td.x-grid3-td-message div.x-grid3-cell-inner {
    white-space: normal;
}
</style>
<div id="help">
<div style="padding: 10px;">
<h3 class="heading">IEMBot Web Monitor</h3>
<p>&nbsp;</p>
<p>This application is a web based monitor of the messages <a href="http://mesonet.agron.iastate.edu/projecs/iembot/">IEMBot</a> produces.  These messages are organized by the NWS Office that issued them.  You can monitor these messages
in real-time as each office will appear as a "tab" in this window.</p>
<p>&nbsp;</p>
<p>This application presents links to web applications specially designed to
display the various products.  These apps include:
<ul>
 <li><a href="../vtec/">VTEC Product Browser</a></li>
 <li><a href="../GIS/apps/rview/watch.phtml">SPC Watch Overviews</a></li>
 <li><a href="../river/wfo.phtml">River Summary App</a></li>
 <li><a href="../cow/maplsr.phtml">Local Storm Report Mapping</a></li>
</ul>
</p>
<p>&nbsp;</p>
<h3>JSON web service</h3>
<p>&nbsp;</p>
<p>Data is provided to this application in a web 2.0 fashion by a JSON service.
You can directly call this JSON service to get the same information. The URI 
template is like:
<pre>
http://mesonet.agron.iastate.edu/iembot-json/room/roomname?seqnum=#
</pre>
<br />The seqnum is simple a message counter.  You would want to start with 0
to get the most recent history.  Then use the largest value you get back each
call to only fetch the most recent content.  The JSON payload is an array of
messages with index values of:
<ul>
 <li><i>seqnum</i>: The sequence number of the message</li>
 <li><i>ts</i>: The timestamp of the message in GMT</li>
 <li><i>author</i>: The author of the message</li>
 <li><i>log</i>: The message usually in HTML format</li>
</ul>
<p>&nbsp;</p>
<p>If you plan on developing a large application against this service, please
let <a href="../info/contacts.php">us know</a>.
<p>&nbsp;</p>
<p>As always, this information is provided without warranty and the possibility of removal in the future.</p>

</div>
</div>
<?php include("$rootpath/include/footer.php"); ?>
