/*
select '["'|| lower(id) || 'chat","' || name || '"],' from stations WHERE network = 'WFO' ORDER by id
*/

Ext.namespace('chatdata');

chatdata.rooms = [
 ['botstalk','All Bots Talk'],
 ["abqchat","Albuquerque"],
 ["abrchat","Aberdeen"],
 ["afcchat","Anchorage"],
 ["afgchat","Fairbanks"],
 ["ajkchat","Juneau"],
 ["akqchat","Wakefield"],
 ["alychat","Albany"],
 ["amachat","Amarillo"],
 ["apxchat","Gaylord"],
 ["arxchat","La Crosse"],
 ["bgmchat","Binghamton"],
 ["bischat","Bismarck"],
 ["bmxchat","Birmingham"],
 ["boichat","Boise"],
 ["bouchat","Denver"],
 ["boxchat","Taunton"],
 ["brochat","Brownsville"],
 ["btvchat","Burlington"],
 ["bufchat","Buffalo"],
 ["byzchat","Billings"],
 ["caechat","Columbia"],
 ["carchat","Caribou"],
 ["chschat","Charleston"],
 ["clechat","Cleveland"],
 ["crpchat","Corpus Christi"],
 ["ctpchat","State College"],
 ["cyschat","Cheyenne"],
 ["ddcchat","Dodge City"],
 ["dlhchat","Duluth"],
 ["dmxchat","Des Moines"],
 ["dtxchat","Detroit"],
 ["dvnchat","Quad Cities Ia"],
 ["eaxchat","Kansas City/Pleasant Hill"],
 ["ekachat","Eureka"],
 ["epzchat","El Paso Tx/Santa Teresa"],
 ["ewxchat","Austin/San Antonio"],
 ["ffcchat","Peachtree City"],
 ["fgfchat","Eastern North Dakota"],
 ["fgzchat","Flagstaff"],
 ["fsdchat","Sioux Falls"],
 ["fwdchat","Dallas/Fort Worth"],
 ["ggwchat","Glasgow"],
 ["gidchat","Hastings"],
 ["gjtchat","Grand Junction"],
 ["gldchat","Goodland"],
 ["grbchat","Green Bay"],
 ["grrchat","Grand Rapids"],
 ["gspchat","Greenville/Spartanburg"],
 ["gumchat","Guam"],
 ["gyxchat","Gray"],
 ["hfochat","Honolulu"],
 ["hgxchat","Houston/Galveston"],
 ["hnxchat","San Joaquin Valley/Hanford"],
 ["hunchat","Huntsville"],
 ["ictchat","Wichita"],
 ["ilmchat","Wilmington"],
 ["ilnchat","Wilmington"],
 ["ilxchat","Lincoln"],
 ["indchat","Indianapolis"],
 ["iwxchat","Northern Indiana"],
 ["janchat","Jackson"],
 ["jaxchat","Jacksonville"],
 ["jklchat","Jackson"],
 ["jsjchat","San Juan"],
 ["keychat","Key West"],
 ["lbfchat","North Platte"],
 ["lchchat","Lake Charles"],
 ["lixchat","New Orleans"],
 ["lknchat","Elko"],
 ["lmkchat","Louisville"],
 ["lotchat","Chicago"],
 ["loxchat","Los Angeles/Oxnard"],
 ["lsxchat","St Louis"],
 ["lubchat","Lubbock"],
 ["lwxchat","Baltimore Md/ Washington Dc"],
 ["lzkchat","Little Rock"],
 ["mafchat","Midland/Odessa"],
 ["megchat","Memphis"],
 ["mflchat","Miami"],
 ["mfrchat","Medford"],
 ["mhxchat","Newport/Morehead City"],
 ["mkxchat","Milwaukee/Sullivan"],
 ["mlbchat","Melbourne"],
 ["mobchat","Mobile"],
 ["mpxchat","Twin Cities/Chanhassen"],
 ["mqtchat","Marquette"],
 ["mrxchat","Morristown"],
 ["msochat","Missoula"],
 ["mtrchat","San Francisco"],
 ["oaxchat","Omaha/Valley"],
 ["ohxchat","Nashville"],
 ["okxchat","New York"],
 ["otxchat","Spokane"],
 ["ounchat","Norman"],
 ["pahchat","Paducah"],
 ["pbzchat","Pittsburgh"],
 ["pdtchat","Pendleton"],
 ["phichat","Mount Holly"],
 ["pihchat","Pocatello/Idaho Falls"],
 ["pqrchat","Portland"],
 ["psrchat","Phoenix"],
 ["pubchat","Pueblo"],
 ["rahchat","Raleigh"],
 ["revchat","Reno"],
 ["riwchat","Riverton"],
 ["rlxchat","Charleston"],
 ["rnkchat","Blacksburg"],
 ["sewchat","Seattle"],
 ["sgfchat","Springfield"],
 ["sgxchat","San Diego"],
 ["shvchat","Shreveport"],
 ["sjtchat","San Angelo"],
 ["sjuchat","San Juan"],
 ["slcchat","Salt Lake City"],
 ["stochat","Sacramento"],
 ["taechat","Tallahassee"],
 ["tbwchat","Tampa Bay Area/Ruskin"],
 ["tfxchat","Great Falls"],
 ["topchat","Topeka"],
 ["tsachat","Tulsa"],
 ["twcchat","Tucson"],
 ["unrchat","Rapid City"],
 ["vefchat","Las Vegas"]
];
