/*
select '["'|| lower(id) || '","' || name || '"],' from stations WHERE network = 'WFO' ORDER by id
*/

Ext.namespace('chatdata');

chatdata.rooms = [
 ['botstalk','All Bots Talk'],
 ["abq","Albuquerque"],
 ["abr","Aberdeen"],
 ["afc","Anchorage"],
 ["afg","Fairbanks"],
 ["ajk","Juneau"],
 ["akq","Wakefield"],
 ["aly","Albany"],
 ["ama","Amarillo"],
 ["apx","Gaylord"],
 ["arx","La Crosse"],
 ["bgm","Binghamton"],
 ["bis","Bismarck"],
 ["bmx","Birmingham"],
 ["boi","Boise"],
 ["bou","Denver"],
 ["box","Taunton"],
 ["bro","Brownsville"],
 ["btv","Burlington"],
 ["buf","Buffalo"],
 ["byz","Billings"],
 ["cae","Columbia"],
 ["car","Caribou"],
 ["chs","Charleston"],
 ["cle","Cleveland"],
 ["crp","Corpus Christi"],
 ["ctp","State College"],
 ["cys","Cheyenne"],
 ["ddc","Dodge City"],
 ["dlh","Duluth"],
 ["dmx","Des Moines"],
 ["dtx","Detroit"],
 ["dvn","Quad Cities Ia"],
 ["eax","Kansas City/Pleasant Hill"],
 ["eka","Eureka"],
 ["epz","El Paso Tx/Santa Teresa"],
 ["ewx","Austin/San Antonio"],
 ["ffc","Peachtree City"],
 ["fgf","Eastern North Dakota"],
 ["fgz","Flagstaff"],
 ["fsd","Sioux Falls"],
 ["fwd","Dallas/Fort Worth"],
 ["ggw","Glasgow"],
 ["gid","Hastings"],
 ["gjt","Grand Junction"],
 ["gld","Goodland"],
 ["grb","Green Bay"],
 ["grr","Grand Rapids"],
 ["gsp","Greenville/Spartanburg"],
 ["gum","Guam"],
 ["gyx","Gray"],
 ["hfo","Honolulu"],
 ["hgx","Houston/Galveston"],
 ["hnx","San Joaquin Valley/Hanford"],
 ["hun","Huntsville"],
 ["ict","Wichita"],
 ["ilm","Wilmington"],
 ["iln","Wilmington"],
 ["ilx","Lincoln"],
 ["ind","Indianapolis"],
 ["iwx","Northern Indiana"],
 ["jan","Jackson"],
 ["jax","Jacksonville"],
 ["jkl","Jackson"],
 ["jsj","San Juan"],
 ["key","Key West"],
 ["lbf","North Platte"],
 ["lch","Lake Charles"],
 ["lix","New Orleans"],
 ["lkn","Elko"],
 ["lmk","Louisville"],
 ["lot","Chicago"],
 ["lox","Los Angeles/Oxnard"],
 ["lsx","St Louis"],
 ["lub","Lubbock"],
 ["lwx","Baltimore Md/ Washington Dc"],
 ["lzk","Little Rock"],
 ["maf","Midland/Odessa"],
 ["meg","Memphis"],
 ["mfl","Miami"],
 ["mfr","Medford"],
 ["mhx","Newport/Morehead City"],
 ["mkx","Milwaukee/Sullivan"],
 ["mlb","Melbourne"],
 ["mob","Mobile"],
 ["mpx","Twin Cities/Chanhassen"],
 ["mqt","Marquette"],
 ["mrx","Morristown"],
 ["mso","Missoula"],
 ["mtr","San Francisco"],
 ["oax","Omaha/Valley"],
 ["ohx","Nashville"],
 ["okx","New York"],
 ["otx","Spokane"],
 ["oun","Norman"],
 ["pah","Paducah"],
 ["pbz","Pittsburgh"],
 ["pdt","Pendleton"],
 ["phi","Mount Holly"],
 ["pih","Pocatello/Idaho Falls"],
 ["pqr","Portland"],
 ["psr","Phoenix"],
 ["pub","Pueblo"],
 ["rah","Raleigh"],
 ["rev","Reno"],
 ["riw","Riverton"],
 ["rlx","Charleston"],
 ["rnk","Blacksburg"],
 ["sew","Seattle"],
 ["sgf","Springfield"],
 ["sgx","San Diego"],
 ["shv","Shreveport"],
 ["sjt","San Angelo"],
 ["sju","San Juan"],
 ["slc","Salt Lake City"],
 ["sto","Sacramento"],
 ["tae","Tallahassee"],
 ["tbw","Tampa Bay Area/Ruskin"],
 ["tfx","Great Falls"],
 ["top","Topeka"],
 ["tsa","Tulsa"],
 ["twc","Tucson"],
 ["unr","Rapid City"],
 ["vef","Las Vegas"]
];
