/*
 * Ext JS Library 3.0 RC2
 * Copyright(c) 2006-2009, Ext JS, LLC.
 * licensing@extjs.com
 * 
 * http://extjs.com/license
 */


Ext.ux.ItemSelector=Ext.extend(Ext.form.Field,{hideNavIcons:false,imagePath:"",iconUp:"up2.gif",iconDown:"down2.gif",iconLeft:"left2.gif",iconRight:"right2.gif",iconTop:"top2.gif",iconBottom:"bottom2.gif",drawUpIcon:true,drawDownIcon:true,drawLeftIcon:true,drawRightIcon:true,drawTopIcon:true,drawBotIcon:true,delimiter:',',bodyStyle:null,border:false,defaultAutoCreate:{tag:"div"},multiselects:null,initComponent:function(){Ext.ux.ItemSelector.superclass.initComponent.call(this);this.addEvents({'rowdblclick':true,'change':true});},onRender:function(ct,position){Ext.ux.ItemSelector.superclass.onRender.call(this,ct,position);var msConfig=[{legend:'Available',draggable:true,droppable:true,width:100,height:100},{legend:'Selected',droppable:true,draggable:true,width:100,height:100}];this.fromMultiselect=new Ext.ux.Multiselect(Ext.applyIf(this.multiselects[0],msConfig[0]));this.fromMultiselect.on('dblclick',this.onRowDblClick,this);this.toMultiselect=new Ext.ux.Multiselect(Ext.applyIf(this.multiselects[1],msConfig[1]));this.toMultiselect.on('dblclick',this.onRowDblClick,this);var p=new Ext.Panel({bodyStyle:this.bodyStyle,border:this.border,layout:"table",layoutConfig:{columns:3}});p.add(this.fromMultiselect);var icons=new Ext.Panel({header:false});p.add(icons);p.add(this.toMultiselect);p.render(this.el);icons.el.down('.'+icons.bwrapCls).remove();if(this.imagePath!=""&&this.imagePath.charAt(this.imagePath.length-1)!="/")
this.imagePath+="/";this.iconUp=this.imagePath+(this.iconUp||'up2.gif');this.iconDown=this.imagePath+(this.iconDown||'down2.gif');this.iconLeft=this.imagePath+(this.iconLeft||'left2.gif');this.iconRight=this.imagePath+(this.iconRight||'right2.gif');this.iconTop=this.imagePath+(this.iconTop||'top2.gif');this.iconBottom=this.imagePath+(this.iconBottom||'bottom2.gif');var el=icons.getEl();this.toTopIcon=el.createChild({tag:'img',src:this.iconTop,style:{cursor:'pointer',margin:'2px'}});el.createChild({tag:'br'});this.upIcon=el.createChild({tag:'img',src:this.iconUp,style:{cursor:'pointer',margin:'2px'}});el.createChild({tag:'br'});this.addIcon=el.createChild({tag:'img',src:this.iconRight,style:{cursor:'pointer',margin:'2px'}});el.createChild({tag:'br'});this.removeIcon=el.createChild({tag:'img',src:this.iconLeft,style:{cursor:'pointer',margin:'2px'}});el.createChild({tag:'br'});this.downIcon=el.createChild({tag:'img',src:this.iconDown,style:{cursor:'pointer',margin:'2px'}});el.createChild({tag:'br'});this.toBottomIcon=el.createChild({tag:'img',src:this.iconBottom,style:{cursor:'pointer',margin:'2px'}});this.toTopIcon.on('click',this.toTop,this);this.upIcon.on('click',this.up,this);this.downIcon.on('click',this.down,this);this.toBottomIcon.on('click',this.toBottom,this);this.addIcon.on('click',this.fromTo,this);this.removeIcon.on('click',this.toFrom,this);if(!this.drawUpIcon||this.hideNavIcons){this.upIcon.dom.style.display='none';}
if(!this.drawDownIcon||this.hideNavIcons){this.downIcon.dom.style.display='none';}
if(!this.drawLeftIcon||this.hideNavIcons){this.addIcon.dom.style.display='none';}
if(!this.drawRightIcon||this.hideNavIcons){this.removeIcon.dom.style.display='none';}
if(!this.drawTopIcon||this.hideNavIcons){this.toTopIcon.dom.style.display='none';}
if(!this.drawBotIcon||this.hideNavIcons){this.toBottomIcon.dom.style.display='none';}
var tb=p.body.first();this.el.setWidth(p.body.first().getWidth());p.body.removeClass();this.hiddenName=this.name;var hiddenTag={tag:"input",type:"hidden",value:"",name:this.name};this.hiddenField=this.el.createChild(hiddenTag);},afterRender:function(){Ext.ux.ItemSelector.superclass.afterRender.call(this);this.toStore=this.toMultiselect.store;this.toStore.on('add',this.valueChanged,this);this.toStore.on('remove',this.valueChanged,this);this.toStore.on('load',this.valueChanged,this);this.valueChanged(this.toStore);},initValue:Ext.emptyFn,toTop:function(){var selectionsArray=this.toMultiselect.view.getSelectedIndexes();var records=[];if(selectionsArray.length>0){selectionsArray.sort();for(var i=0;i<selectionsArray.length;i++){record=this.toMultiselect.view.store.getAt(selectionsArray[i]);records.push(record);}
selectionsArray=[];for(var i=records.length-1;i>-1;i--){record=records[i];this.toMultiselect.view.store.remove(record);this.toMultiselect.view.store.insert(0,record);selectionsArray.push(((records.length-1)-i));}}
this.toMultiselect.view.refresh();this.toMultiselect.view.select(selectionsArray);},toBottom:function(){var selectionsArray=this.toMultiselect.view.getSelectedIndexes();var records=[];if(selectionsArray.length>0){selectionsArray.sort();for(var i=0;i<selectionsArray.length;i++){record=this.toMultiselect.view.store.getAt(selectionsArray[i]);records.push(record);}
selectionsArray=[];for(var i=0;i<records.length;i++){record=records[i];this.toMultiselect.view.store.remove(record);this.toMultiselect.view.store.add(record);selectionsArray.push((this.toMultiselect.view.store.getCount())-(records.length-i));}}
this.toMultiselect.view.refresh();this.toMultiselect.view.select(selectionsArray);},up:function(){var record=null;var selectionsArray=this.toMultiselect.view.getSelectedIndexes();selectionsArray.sort();var newSelectionsArray=[];if(selectionsArray.length>0){for(var i=0;i<selectionsArray.length;i++){record=this.toMultiselect.view.store.getAt(selectionsArray[i]);if((selectionsArray[i]-1)>=0){this.toMultiselect.view.store.remove(record);this.toMultiselect.view.store.insert(selectionsArray[i]-1,record);newSelectionsArray.push(selectionsArray[i]-1);}}
this.toMultiselect.view.refresh();this.toMultiselect.view.select(newSelectionsArray);}},down:function(){var record=null;var selectionsArray=this.toMultiselect.view.getSelectedIndexes();selectionsArray.sort();selectionsArray.reverse();var newSelectionsArray=[];if(selectionsArray.length>0){for(var i=0;i<selectionsArray.length;i++){record=this.toMultiselect.view.store.getAt(selectionsArray[i]);if((selectionsArray[i]+1)<this.toMultiselect.view.store.getCount()){this.toMultiselect.view.store.remove(record);this.toMultiselect.view.store.insert(selectionsArray[i]+1,record);newSelectionsArray.push(selectionsArray[i]+1);}}
this.toMultiselect.view.refresh();this.toMultiselect.view.select(newSelectionsArray);}},fromTo:function(){var selectionsArray=this.fromMultiselect.view.getSelectedIndexes();var records=[];if(selectionsArray.length>0){for(var i=0;i<selectionsArray.length;i++){record=this.fromMultiselect.view.store.getAt(selectionsArray[i]);records.push(record);}
if(!this.allowDup)selectionsArray=[];for(var i=0;i<records.length;i++){record=records[i];if(this.allowDup){var x=new Ext.data.Record();record.id=x.id;delete x;this.toMultiselect.view.store.add(record);}else{this.fromMultiselect.view.store.remove(record);this.toMultiselect.view.store.add(record);selectionsArray.push((this.toMultiselect.view.store.getCount()-1));}}}
this.toMultiselect.view.refresh();this.fromMultiselect.view.refresh();var si=this.toMultiselect.store.sortInfo;if(si){this.toMultiselect.store.sort(si.field,si.direction);}
this.toMultiselect.view.select(selectionsArray);},toFrom:function(){var selectionsArray=this.toMultiselect.view.getSelectedIndexes();var records=[];if(selectionsArray.length>0){for(var i=0;i<selectionsArray.length;i++){record=this.toMultiselect.view.store.getAt(selectionsArray[i]);records.push(record);}
selectionsArray=[];for(var i=0;i<records.length;i++){record=records[i];this.toMultiselect.view.store.remove(record);if(!this.allowDup){this.fromMultiselect.view.store.add(record);selectionsArray.push((this.fromMultiselect.view.store.getCount()-1));}}}
this.fromMultiselect.view.refresh();this.toMultiselect.view.refresh();var si=this.fromMultiselect.store.sortInfo;if(si){this.fromMultiselect.store.sort(si.field,si.direction);}
this.fromMultiselect.view.select(selectionsArray);},valueChanged:function(store){var record=null;var values=[];for(var i=0;i<store.getCount();i++){record=store.getAt(i);values.push(record.get(this.toMultiselect.valueField));}
this.hiddenField.dom.value=values.join(this.delimiter);this.fireEvent('change',this,this.getValue(),this.hiddenField.dom.value);},getValue:function(){return this.hiddenField.dom.value;},onRowDblClick:function(vw,index,node,e){if(vw==this.toMultiselect.view){this.toFrom();}else if(vw==this.fromMultiselect.view){this.fromTo();}
return this.fireEvent('rowdblclick',vw,index,node,e);},reset:function(){range=this.toMultiselect.store.getRange();this.toMultiselect.store.removeAll();this.fromMultiselect.store.add(range);var si=this.fromMultiselect.store.sortInfo;if(si){this.fromMultiselect.store.sort(si.field,si.direction);}
this.valueChanged(this.toMultiselect.store);}});Ext.reg("itemselector",Ext.ux.ItemSelector);

Ext.ux.Multiselect=Ext.extend(Ext.form.Field,{ddReorder:false,appendOnly:false,width:100,height:100,displayField:0,valueField:1,allowBlank:true,minSelections:0,maxSelections:Number.MAX_VALUE,blankText:Ext.form.TextField.prototype.blankText,minSelectionsText:'Minimum {0} item(s) required',maxSelectionsText:'Maximum {0} item(s) allowed',delimiter:',',defaultAutoCreate:{tag:"div"},initComponent:function(){Ext.ux.Multiselect.superclass.initComponent.call(this);if(Ext.isArray(this.store)){if(Ext.isArray(this.store[0])){this.store=new Ext.data.ArrayStore({fields:['value','text'],data:this.store});this.valueField='value';}else{this.store=new Ext.data.ArrayStore({fields:['text'],data:this.store,expandData:true});this.valueField='text';}
this.displayField='text';}else{this.store=Ext.StoreMgr.lookup(this.store);}
this.addEvents({'dblclick':true,'click':true,'change':true,'drop':true});},onRender:function(ct,position){Ext.ux.Multiselect.superclass.onRender.call(this,ct,position);var fs=this.fs=new Ext.form.FieldSet({renderTo:this.el,title:this.legend,height:this.height,width:this.width,style:"padding:0;",tbar:this.tbar,bodyStyle:'overflow: auto;'});this.view=new Ext.ListView({multiSelect:true,store:this.store,columns:[{header:'Value',width:1,dataIndex:this.displayField}],hideHeaders:true});fs.add(this.view);this.view.on('click',this.onViewClick,this);this.view.on('beforeclick',this.onViewBeforeClick,this);this.view.on('dblclick',this.onViewDblClick,this);this.hiddenName=this.name||Ext.id();var hiddenTag={tag:"input",type:"hidden",value:"",name:this.hiddenName};this.hiddenField=this.el.createChild(hiddenTag);this.hiddenField.dom.disabled=this.hiddenName!=this.name;fs.doLayout();},afterRender:function(){Ext.ux.Multiselect.superclass.afterRender.call(this);if(this.ddReorder&&!this.dragGroup&&!this.dropGroup){this.dragGroup=this.dropGroup='MultiselectDD-'+Ext.id();}
if(this.draggable||this.dragGroup){this.dragZone=new Ext.ux.Multiselect.DragZone(this,{ddGroup:this.dragGroup});}
if(this.droppable||this.dropGroup){this.dropZone=new Ext.ux.Multiselect.DropZone(this,{ddGroup:this.dropGroup});}},initValue:Ext.emptyFn,onViewClick:function(vw,index,node,e){this.fireEvent('change',this,this.getValue(),this.hiddenField.dom.value);this.hiddenField.dom.value=this.getValue();this.fireEvent('click',this,e);this.validate();},onViewBeforeClick:function(vw,index,node,e){if(this.disabled){return false;}},onViewDblClick:function(vw,index,node,e){return this.fireEvent('dblclick',vw,index,node,e);},getValue:function(valueField){var returnArray=[];var selectionsArray=this.view.getSelectedIndexes();if(selectionsArray.length==0){return'';}
for(var i=0;i<selectionsArray.length;i++){returnArray.push(this.store.getAt(selectionsArray[i]).get((valueField!=null)?valueField:this.valueField));}
return returnArray.join(this.delimiter);},setValue:function(values){var index;var selections=[];this.view.clearSelections();this.hiddenField.dom.value='';if(!values||(values=='')){return;}
if(!Ext.isArray(values)){values=values.split(this.delimiter);}
for(var i=0;i<values.length;i++){index=this.view.store.indexOf(this.view.store.query(this.valueField,new RegExp('^'+values[i]+'$',"i")).itemAt(0));selections.push(index);}
this.view.select(selections);this.hiddenField.dom.value=this.getValue();this.validate();},reset:function(){this.setValue('');},getRawValue:function(valueField){var tmp=this.getValue(valueField);if(tmp.length){tmp=tmp.split(this.delimiter);}
else{tmp=[];}
return tmp;},setRawValue:function(values){setValue(values);},validateValue:function(value){if(value.length<1){if(this.allowBlank){this.clearInvalid();return true;}else{this.markInvalid(this.blankText);return false;}}
if(value.length<this.minSelections){this.markInvalid(String.format(this.minSelectionsText,this.minSelections));return false;}
if(value.length>this.maxSelections){this.markInvalid(String.format(this.maxSelectionsText,this.maxSelections));return false;}
return true;},disable:function(){this.disabled=true;this.hiddenField.dom.disabled=true;this.fs.disable();},enable:function(){this.disabled=false;this.hiddenField.dom.disabled=false;this.fs.enable();},destroy:function(){this.fs.destroy();if(this.dragZone&&this.dragZone.destroy)this.dragZone.destroy();if(this.dropZone&&this.dropZone.destroy)this.dropZone.destroy();Ext.ux.Multiselect.superclass.destroy.call(this);}});Ext.reg("multiselect",Ext.ux.Multiselect);Ext.ux.Multiselect.DragZone=function(ms,config){this.ms=ms;this.view=ms.view;var ddGroup=config.ddGroup||'MultiselectDD';var dd;if(Ext.isArray(ddGroup)){dd=ddGroup.shift();}else{dd=ddGroup;ddGroup=null;}
Ext.ux.Multiselect.DragZone.superclass.constructor.call(this,this.ms.fs.body,{containerScroll:true,ddGroup:dd});this.setDraggable(ddGroup);};Ext.extend(Ext.ux.Multiselect.DragZone,Ext.dd.DragZone,{collectSelection:function(data){data.repairXY=Ext.fly(this.view.getSelectedNodes()[0]).getXY();var i=0;this.view.store.each(function(rec){if(this.view.isSelected(i)){var n=this.view.getNode(i);var dragNode=n.cloneNode(true);dragNode.id=Ext.id();data.ddel.appendChild(dragNode);data.records.push(this.view.store.getAt(i));data.viewNodes.push(n);}
i++;},this);},onEndDrag:function(data,e){var d=Ext.get(this.dragData.ddel);if(d&&d.hasClass("multi-proxy")){d.remove();}},getDragData:function(e){var target=this.view.findItemFromChild(e.getTarget());if(target){if(!this.view.isSelected(target)&&!e.ctrlKey&&!e.shiftKey){this.view.select(target);this.ms.setValue(this.ms.getValue());}
if(this.view.getSelectionCount()==0||e.ctrlKey||e.shiftKey)return false;var dragData={sourceView:this.view,viewNodes:[],records:[]};if(this.view.getSelectionCount()==1){var i=this.view.getSelectedIndexes()[0];var n=this.view.getNode(i);dragData.viewNodes.push(dragData.ddel=n);dragData.records.push(this.view.store.getAt(i));dragData.repairXY=Ext.fly(n).getXY();}else{dragData.ddel=document.createElement('div');dragData.ddel.className='multi-proxy';this.collectSelection(dragData);}
return dragData;}
return false;},getRepairXY:function(e){return this.dragData.repairXY;},setDraggable:function(ddGroup){if(!ddGroup)return;if(Ext.isArray(ddGroup)){Ext.each(ddGroup,this.setDraggable,this);return;}
this.addToGroup(ddGroup);}});Ext.ux.Multiselect.DropZone=function(ms,config){this.ms=ms;this.view=ms.view;var ddGroup=config.ddGroup||'MultiselectDD';var dd;if(Ext.isArray(ddGroup)){dd=ddGroup.shift();}else{dd=ddGroup;ddGroup=null;}
Ext.ux.Multiselect.DropZone.superclass.constructor.call(this,this.ms.fs.body,{containerScroll:true,ddGroup:dd});this.setDroppable(ddGroup);};Ext.extend(Ext.ux.Multiselect.DropZone,Ext.dd.DropZone,{getTargetFromEvent:function(e){var target=e.getTarget();return target;},getDropPoint:function(e,n,dd){if(n==this.ms.fs.body.dom){return"below";}
var t=Ext.lib.Dom.getY(n),b=t+n.offsetHeight;var c=t+(b-t)/2;var y=Ext.lib.Event.getPageY(e);if(y<=c){return"above";}else{return"below";}},isValidDropPoint:function(pt,n,data){if(!data.viewNodes||(data.viewNodes.length!=1)){return true;}
var d=data.viewNodes[0];if(d==n){return false;}
if((pt=="below")&&(n.nextSibling==d)){return false;}
if((pt=="above")&&(n.previousSibling==d)){return false;}
return true;},onNodeEnter:function(n,dd,e,data){return false;},onNodeOver:function(n,dd,e,data){var dragElClass=this.dropNotAllowed;var pt=this.getDropPoint(e,n,dd);if(this.isValidDropPoint(pt,n,data)){if(this.ms.appendOnly){return"x-tree-drop-ok-below";}
if(pt){var targetElClass;if(pt=="above"){dragElClass=n.previousSibling?"x-tree-drop-ok-between":"x-tree-drop-ok-above";targetElClass="x-view-drag-insert-above";}else{dragElClass=n.nextSibling?"x-tree-drop-ok-between":"x-tree-drop-ok-below";targetElClass="x-view-drag-insert-below";}
if(this.lastInsertClass!=targetElClass){Ext.fly(n).replaceClass(this.lastInsertClass,targetElClass);this.lastInsertClass=targetElClass;}}}
return dragElClass;},onNodeOut:function(n,dd,e,data){this.removeDropIndicators(n);},onNodeDrop:function(n,dd,e,data){if(this.ms.fireEvent("drop",this,n,dd,e,data)===false){return false;}
var pt=this.getDropPoint(e,n,dd);if(n!=this.ms.fs.body.dom)
n=this.view.findItemFromChild(n);var insertAt=(this.ms.appendOnly||(n==this.ms.fs.body.dom))?this.view.store.getCount():this.view.indexOf(n);if(pt=="below"){insertAt++;}
var dir=false;if(data.sourceView==this.view){if(pt=="below"){if(data.viewNodes[0]==n){data.viewNodes.shift();}}else{if(data.viewNodes[data.viewNodes.length-1]==n){data.viewNodes.pop();}}
if(!data.viewNodes.length){return false;}
if(insertAt>this.view.store.indexOf(data.records[0])){dir='down';insertAt--;}}
for(var i=0;i<data.records.length;i++){var r=data.records[i];if(data.sourceView){data.sourceView.store.remove(r);}
this.view.store.insert(dir=='down'?insertAt:insertAt++,r);var si=this.view.store.sortInfo;if(si){this.view.store.sort(si.field,si.direction);}}
return true;},removeDropIndicators:function(n){if(n){Ext.fly(n).removeClass(["x-view-drag-insert-above","x-view-drag-insert-left","x-view-drag-insert-right","x-view-drag-insert-below"]);this.lastInsertClass="_noclass";}},setDroppable:function(ddGroup){if(!ddGroup)return;if(Ext.isArray(ddGroup)){Ext.each(ddGroup,this.setDroppable,this);return;}
this.addToGroup(ddGroup);}});

Ext.ux.XmlTreeLoader=Ext.extend(Ext.tree.TreeLoader,{XML_NODE_ELEMENT:1,XML_NODE_TEXT:3,processResponse:function(response,node,callback){var xmlData=response.responseXML;var root=xmlData.documentElement||xmlData;try{node.beginUpdate();node.appendChild(this.parseXml(root));node.endUpdate();if(typeof callback=="function"){callback(this,node);}}catch(e){this.handleFailure(response);}},parseXml:function(node){var nodes=[];Ext.each(node.childNodes,function(n){if(n.nodeType==this.XML_NODE_ELEMENT){var treeNode=this.createNode(n);if(n.childNodes.length>0){var child=this.parseXml(n);if(typeof child=='string'){treeNode.attributes.innerText=child;}else{treeNode.appendChild(child);}}
nodes.push(treeNode);}
else if(n.nodeType==this.XML_NODE_TEXT){var text=n.nodeValue.trim();if(text.length>0){return nodes=text;}}},this);return nodes;},createNode:function(node){var attr={tagName:node.tagName};Ext.each(node.attributes,function(a){attr[a.nodeName]=a.nodeValue;});this.processAttributes(attr);return Ext.ux.XmlTreeLoader.superclass.createNode.call(this,attr);},processAttributes:Ext.emptyFn});

Ext.ux.TabScrollerMenu=Ext.extend(Object,{pageSize:10,maxText:15,menuPrefixText:'Items',constructor:function(config){config=config||{};Ext.apply(this,config);},init:function(tabPanel){Ext.apply(tabPanel,this.tabPanelMethods);tabPanel.tabScrollerMenu=this;var thisRef=this;tabPanel.on({render:{scope:tabPanel,single:true,fn:function(){var newFn=tabPanel.createScrollers.createSequence(thisRef.createPanelsMenu,this);tabPanel.createScrollers=newFn;}}});},createPanelsMenu:function(){var h=this.stripWrap.dom.offsetHeight;var rtScrBtn=this.header.dom.firstChild;Ext.fly(rtScrBtn).applyStyles({right:'18px'});var stripWrap=Ext.get(this.strip.dom.parentNode);stripWrap.applyStyles({'margin-right':'36px'});var scrollMenu=this.header.insertFirst({cls:'x-tab-tabmenu-right'});scrollMenu.setHeight(h);scrollMenu.addClassOnOver('x-tab-tabmenu-over');scrollMenu.on('click',this.showTabsMenu,this);this.scrollLeft.show=this.scrollLeft.show.createSequence(function(){scrollMenu.show();});this.scrollLeft.hide=this.scrollLeft.hide.createSequence(function(){scrollMenu.hide();});},getPageSize:function(){return this.pageSize;},setPageSize:function(pageSize){this.pageSize=pageSize;},getMaxText:function(){return this.maxText;},setMaxText:function(t){this.maxText=t;},getMenuPrefixText:function(){return this.menuPrefixText;},setMenuPrefixText:function(t){this.menuPrefixText=t;},tabPanelMethods:{showTabsMenu:function(e){if(!this.tabsMenu){this.tabsMenu=new Ext.menu.Menu();this.on('beforedestroy',this.tabsMenu.destroy,this.tabsMenu);}
this.tabsMenu.removeAll();this.generateTabMenuItems();var target=Ext.get(e.getTarget());var xy=target.getXY();xy[1]+=24;this.tabsMenu.showAt(xy);},generateTabMenuItems:function(){var curActive=this.getActiveTab();var totalItems=this.items.getCount();var pageSize=this.tabScrollerMenu.getPageSize();if(totalItems>pageSize){var numSubMenus=Math.floor(totalItems/pageSize);var remainder=totalItems%pageSize;for(var i=0;i<numSubMenus;i++){var curPage=(i+1)*pageSize;var menuItems=[];for(var x=0;x<pageSize;x++){index=x+curPage-pageSize;var item=this.items.get(index);menuItems.push(this.autoGenMenuItem(item));}
this.tabsMenu.add({text:this.tabScrollerMenu.getMenuPrefixText()+' '+(curPage-pageSize+1)+' - '+curPage,menu:menuItems});}
if(remainder>0){var start=numSubMenus*pageSize;menuItems=[];for(var i=start;i<totalItems;i++){var item=this.items.get(i);menuItems.push(this.autoGenMenuItem(item));}
this.tabsMenu.add({text:this.tabScrollerMenu.menuPrefixText+' '+(start+1)+' - '+(start+menuItems.length),menu:menuItems});}}
else{this.items.each(function(item){if(item.id!=curActive.id&&!item.hidden){menuItems.push(this.autoGenMenuItem(item));}},this);}},autoGenMenuItem:function(item){var maxText=this.tabScrollerMenu.getMaxText();var text=Ext.util.Format.ellipsis(item.title,maxText);return{text:text,handler:this.showTabFromMenu,scope:this,disabled:item.disabled,tabToShow:item,iconCls:item.iconCls}},showTabFromMenu:function(menuItem){this.setActiveTab(menuItem.tabToShow);}}});

Ext.ux.TableGrid=function(table,config){config=config||{};Ext.apply(this,config);var cf=config.fields||[],ch=config.columns||[];table=Ext.get(table);var ct=table.insertSibling();var fields=[],cols=[];var headers=table.query("thead th");for(var i=0,h;h=headers[i];i++){var text=h.innerHTML;var name='tcol-'+i;fields.push(Ext.applyIf(cf[i]||{},{name:name,mapping:'td:nth('+(i+1)+')/@innerHTML'}));cols.push(Ext.applyIf(ch[i]||{},{'header':text,'dataIndex':name,'width':h.offsetWidth,'tooltip':h.title,'sortable':true}));}
var ds=new Ext.data.Store({reader:new Ext.data.XmlReader({record:'tbody tr'},fields)});ds.loadData(table.dom);var cm=new Ext.grid.ColumnModel(cols);if(config.width||config.height){ct.setSize(config.width||'auto',config.height||'auto');}else{ct.setWidth(table.getWidth());}
if(config.remove!==false){table.remove();}
Ext.applyIf(this,{'ds':ds,'cm':cm,'sm':new Ext.grid.RowSelectionModel(),autoHeight:true,autoWidth:false});Ext.ux.TableGrid.superclass.constructor.call(this,ct,{});};Ext.extend(Ext.ux.TableGrid,Ext.grid.GridPanel);Ext.grid.TableGrid=Ext.ux.TableGrid;

Ext.ux.FileUploadField=Ext.extend(Ext.form.TextField,{buttonText:'Browse...',buttonOnly:false,buttonOffset:3,readOnly:true,autoSize:Ext.emptyFn,initComponent:function(){Ext.ux.FileUploadField.superclass.initComponent.call(this);this.addEvents('fileselected');},onRender:function(ct,position){Ext.ux.FileUploadField.superclass.onRender.call(this,ct,position);this.wrap=this.el.wrap({cls:'x-form-field-wrap x-form-file-wrap'});this.el.addClass('x-form-file-text');this.el.dom.removeAttribute('name');this.fileInput=this.wrap.createChild({id:this.getFileInputId(),name:this.name||this.getId(),cls:'x-form-file',tag:'input',type:'file',size:1});var btnCfg=Ext.applyIf(this.buttonCfg||{},{text:this.buttonText});this.button=new Ext.Button(Ext.apply(btnCfg,{renderTo:this.wrap,cls:'x-form-file-btn'+(btnCfg.iconCls?' x-btn-icon':'')}));if(this.buttonOnly){this.el.hide();this.wrap.setWidth(this.button.getEl().getWidth());}
this.fileInput.on('change',function(){var v=this.fileInput.dom.value;this.setValue(v);this.fireEvent('fileselected',this,v);},this);},getFileInputId:function(){return this.id+'-file';},onResize:function(w,h){Ext.ux.FileUploadField.superclass.onResize.call(this,w,h);this.wrap.setWidth(w);if(!this.buttonOnly){var w=this.wrap.getWidth()-this.button.getEl().getWidth()-this.buttonOffset;this.el.setWidth(w);}},preFocus:Ext.emptyFn,getResizeEl:function(){return this.wrap;},getPositionEl:function(){return this.wrap;},alignErrorIcon:function(){this.errorIcon.alignTo(this.wrap,'tl-tr',[2,0]);}});Ext.reg('fileuploadfield',Ext.ux.FileUploadField);Ext.form.FileUploadField=Ext.ux.FileUploadField;

Ext.tree.ColumnTree=Ext.extend(Ext.tree.TreePanel,{lines:false,borderWidth:Ext.isBorderBox?0:2,cls:'x-column-tree',onRender:function(){Ext.tree.ColumnTree.superclass.onRender.apply(this,arguments);this.headers=this.header.createChild({cls:'x-tree-headers'});var cols=this.columns,c;var totalWidth=0;var scrollOffset=19;for(var i=0,len=cols.length;i<len;i++){c=cols[i];totalWidth+=c.width;this.headers.createChild({cls:'x-tree-hd '+(c.cls?c.cls+'-hd':''),cn:{cls:'x-tree-hd-text',html:c.header},style:'width:'+(c.width-this.borderWidth)+'px;'});}
this.headers.createChild({cls:'x-clear'});this.headers.setWidth(totalWidth+scrollOffset);this.innerCt.setWidth(totalWidth);}});Ext.tree.ColumnNodeUI=Ext.extend(Ext.tree.TreeNodeUI,{focus:Ext.emptyFn,renderElements:function(n,a,targetNode,bulkRender){this.indentMarkup=n.parentNode?n.parentNode.ui.getChildIndent():'';var t=n.getOwnerTree();var cols=t.columns;var bw=t.borderWidth;var c=cols[0];var buf=['<li class="x-tree-node"><div ext:tree-node-id="',n.id,'" class="x-tree-node-el x-tree-node-leaf ',a.cls,'">','<div class="x-tree-col" style="width:',c.width-bw,'px;">','<span class="x-tree-node-indent">',this.indentMarkup,"</span>",'<img src="',this.emptyIcon,'" class="x-tree-ec-icon x-tree-elbow">','<img src="',a.icon||this.emptyIcon,'" class="x-tree-node-icon',(a.icon?" x-tree-node-inline-icon":""),(a.iconCls?" "+a.iconCls:""),'" unselectable="on">','<a hidefocus="on" class="x-tree-node-anchor" href="',a.href?a.href:"#",'" tabIndex="1" ',a.hrefTarget?' target="'+a.hrefTarget+'"':"",'>','<span unselectable="on">',n.text||(c.renderer?c.renderer(a[c.dataIndex],n,a):a[c.dataIndex]),"</span></a>","</div>"];for(var i=1,len=cols.length;i<len;i++){c=cols[i];buf.push('<div class="x-tree-col ',(c.cls?c.cls:''),'" style="width:',c.width-bw,'px;">','<div class="x-tree-col-text">',(c.renderer?c.renderer(a[c.dataIndex],n,a):a[c.dataIndex]),"</div>","</div>");}
buf.push('<div class="x-clear"></div></div>','<ul class="x-tree-node-ct" style="display:none;"></ul>',"</li>");if(bulkRender!==true&&n.nextSibling&&n.nextSibling.ui.getEl()){this.wrap=Ext.DomHelper.insertHtml("beforeBegin",n.nextSibling.ui.getEl(),buf.join(""));}else{this.wrap=Ext.DomHelper.insertHtml("beforeEnd",targetNode,buf.join(""));}
this.elNode=this.wrap.childNodes[0];this.ctNode=this.wrap.childNodes[1];var cs=this.elNode.firstChild.childNodes;this.indentNode=cs[0];this.ecNode=cs[1];this.iconNode=cs[2];this.anchor=cs[3];this.textNode=cs[3].firstChild;}});

Ext.DataView.LabelEditor=Ext.extend(Ext.Editor,{alignment:"tl-tl",hideEl:false,cls:"x-small-editor",shim:false,completeOnEnter:true,cancelOnEsc:true,labelSelector:'span.x-editable',constructor:function(cfg,field){Ext.DataView.LabelEditor.superclass.constructor.call(this,field||new Ext.form.TextField({allowBlank:false,growMin:90,growMax:240,grow:true,selectOnFocus:true}),cfg);},init:function(view){this.view=view;view.on('render',this.initEditor,this);this.on('complete',this.onSave,this);},initEditor:function(){this.view.on({scope:this,containerclick:this.doBlur,click:this.doBlur});this.view.getEl().on('mousedown',this.onMouseDown,this,{delegate:this.labelSelector});},doBlur:function(){if(this.editing){this.field.blur();}},onMouseDown:function(e,target){if(!e.ctrlKey&&!e.shiftKey){var item=this.view.findItemFromChild(target);e.stopEvent();var record=this.view.store.getAt(this.view.indexOf(item));this.startEdit(target,record.data[this.dataIndex]);this.activeRecord=record;}else{e.preventDefault();}},onSave:function(ed,value){this.activeRecord.set(this.dataIndex,value);}});Ext.DataView.DragSelector=function(cfg){cfg=cfg||{};var view,proxy,tracker;var rs,bodyRegion,dragRegion=new Ext.lib.Region(0,0,0,0);var dragSafe=cfg.dragSafe===true;this.init=function(dataView){view=dataView;view.on('render',onRender);};function fillRegions(){rs=[];view.all.each(function(el){rs[rs.length]=el.getRegion();});bodyRegion=view.el.getRegion();}
function cancelClick(){return false;}
function onBeforeStart(e){return!dragSafe||e.target==view.el.dom;}
function onStart(e){view.on('containerclick',cancelClick,view,{single:true});if(!proxy){proxy=view.el.createChild({cls:'x-view-selector'});}else{proxy.setDisplayed('block');}
fillRegions();view.clearSelections();}
function onDrag(e){var startXY=tracker.startXY;var xy=tracker.getXY();var x=Math.min(startXY[0],xy[0]);var y=Math.min(startXY[1],xy[1]);var w=Math.abs(startXY[0]-xy[0]);var h=Math.abs(startXY[1]-xy[1]);dragRegion.left=x;dragRegion.top=y;dragRegion.right=x+w;dragRegion.bottom=y+h;dragRegion.constrainTo(bodyRegion);proxy.setRegion(dragRegion);for(var i=0,len=rs.length;i<len;i++){var r=rs[i],sel=dragRegion.intersect(r);if(sel&&!r.selected){r.selected=true;view.select(i,true);}else if(!sel&&r.selected){r.selected=false;view.deselect(i);}}}
function onEnd(e){view.un('containerclick',cancelClick,view);if(proxy){proxy.setDisplayed(false);}}
function onRender(view){tracker=new Ext.dd.DragTracker({onBeforeStart:onBeforeStart,onStart:onStart,onDrag:onDrag,onEnd:onEnd});tracker.initEl(view.el);}};

Ext.namespace('Ext.ux');Ext.ux.GMapPanel=Ext.extend(Ext.Panel,{initComponent:function(){var defConfig={plain:true,zoomLevel:3,yaw:180,pitch:0,zoom:0,gmapType:'map',border:false};Ext.applyIf(this,defConfig);Ext.ux.GMapPanel.superclass.initComponent.call(this);},afterRender:function(){var wh=this.ownerCt.getSize();Ext.applyIf(this,wh);Ext.ux.GMapPanel.superclass.afterRender.call(this);if(this.gmapType==='map'){this.gmap=new GMap2(this.body.dom);}
if(this.gmapType==='panorama'){this.gmap=new GStreetviewPanorama(this.body.dom);}
if(typeof this.addControl=='object'&&this.gmapType==='map'){this.gmap.addControl(this.addControl);}
if(typeof this.setCenter==='object'){if(typeof this.setCenter.geoCodeAddr==='string'){this.geoCodeLookup(this.setCenter.geoCodeAddr);}else{if(this.gmapType==='map'){var point=new GLatLng(this.setCenter.lat,this.setCenter.lng);this.gmap.setCenter(point,this.zoomLevel);}
if(typeof this.setCenter.marker==='object'&&typeof point==='object'){this.addMarker(point,this.setCenter.marker,this.setCenter.marker.clear);}}
if(this.gmapType==='panorama'){this.gmap.setLocationAndPOV(new GLatLng(this.setCenter.lat,this.setCenter.lng),{yaw:this.yaw,pitch:this.pitch,zoom:this.zoom});}}
GEvent.bind(this.gmap,'load',this,function(){this.onMapReady();});},onMapReady:function(){this.addMarkers(this.markers);this.addMapControls();this.addOptions();},onResize:function(w,h){if(typeof this.getMap()=='object'){this.gmap.checkResize();}
Ext.ux.GMapPanel.superclass.onResize.call(this,w,h);},setSize:function(width,height,animate){if(typeof this.getMap()=='object'){this.gmap.checkResize();}
Ext.ux.GMapPanel.superclass.setSize.call(this,width,height,animate);},getMap:function(){return this.gmap;},getCenter:function(){return this.getMap().getCenter();},getCenterLatLng:function(){var ll=this.getCenter();return{lat:ll.lat(),lng:ll.lng()};},addMarkers:function(markers){if(Ext.isArray(markers)){for(var i=0;i<markers.length;i++){var mkr_point=new GLatLng(markers[i].lat,markers[i].lng);this.addMarker(mkr_point,markers[i].marker,false,markers[i].setCenter,markers[i].listeners);}}},addMarker:function(point,marker,clear,center,listeners){Ext.applyIf(marker,G_DEFAULT_ICON);if(clear===true){this.getMap().clearOverlays();}
if(center===true){this.getMap().setCenter(point,this.zoomLevel);}
var mark=new GMarker(point,marker);if(typeof listeners==='object'){for(evt in listeners){GEvent.bind(mark,evt,this,listeners[evt]);}}
this.getMap().addOverlay(mark);},addMapControls:function(){if(this.gmapType==='map'){if(Ext.isArray(this.mapControls)){for(i=0;i<this.mapControls.length;i++){this.addMapControl(this.mapControls[i]);}}else if(typeof this.mapControls==='string'){this.addMapControl(this.mapControls);}else if(typeof this.mapControls==='object'){this.getMap().addControl(this.mapControls);}}},addMapControl:function(mc){var mcf=window[mc];if(typeof mcf==='function'){this.getMap().addControl(new mcf());}},addOptions:function(){if(Ext.isArray(this.mapConfOpts)){var mc;for(i=0;i<this.mapConfOpts.length;i++){this.addOption(this.mapConfOpts[i]);}}else if(typeof this.mapConfOpts==='string'){this.addOption(this.mapConfOpts);}},addOption:function(mc){var mcf=this.getMap()[mc];if(typeof mcf==='function'){this.getMap()[mc]();}},geoCodeLookup:function(addr){this.geocoder=new GClientGeocoder();this.geocoder.getLocations(addr,this.addAddressToMap.createDelegate(this));},addAddressToMap:function(response){if(!response||response.Status.code!=200){Ext.MessageBox.alert('Error','Code '+response.Status.code+' Error Returned');}else{place=response.Placemark[0];addressinfo=place.AddressDetails;accuracy=addressinfo.Accuracy;if(accuracy===0){Ext.MessageBox.alert('Unable to Locate Address','Unable to Locate the Address you provided');}else{if(accuracy<7){Ext.MessageBox.alert('Address Accuracy','The address provided has a low accuracy.<br><br>Level '+accuracy+' Accuracy (8 = Exact Match, 1 = Vague Match)');}else{point=new GLatLng(place.Point.coordinates[1],place.Point.coordinates[0]);if(typeof this.setCenter.marker==='object'&&typeof point==='object'){this.addMarker(point,this.setCenter.marker,this.setCenter.marker.clear,true,this.setCenter.listeners);}}}}}});Ext.reg('gmappanel',Ext.ux.GMapPanel);

Ext.ux.GroupSummary=Ext.extend(Ext.util.Observable,{constructor:function(config){Ext.apply(this,config);Ext.ux.GroupSummary.superclass.constructor.call(this);},init:function(grid){this.grid=grid;this.cm=grid.getColumnModel();this.view=grid.getView();var v=this.view;v.doGroupEnd=this.doGroupEnd.createDelegate(this);v.afterMethod('onColumnWidthUpdated',this.doWidth,this);v.afterMethod('onAllColumnWidthsUpdated',this.doAllWidths,this);v.afterMethod('onColumnHiddenUpdated',this.doHidden,this);v.afterMethod('onUpdate',this.doUpdate,this);v.afterMethod('onRemove',this.doRemove,this);if(!this.rowTpl){this.rowTpl=new Ext.Template('<div class="x-grid3-summary-row" style="{tstyle}">','<table class="x-grid3-summary-table" border="0" cellspacing="0" cellpadding="0" style="{tstyle}">','<tbody><tr>{cells}</tr></tbody>','</table></div>');this.rowTpl.disableFormats=true;}
this.rowTpl.compile();if(!this.cellTpl){this.cellTpl=new Ext.Template('<td class="x-grid3-col x-grid3-cell x-grid3-td-{id} {css}" style="{style}">','<div class="x-grid3-cell-inner x-grid3-col-{id}" unselectable="on">{value}</div>',"</td>");this.cellTpl.disableFormats=true;}
this.cellTpl.compile();},toggleSummaries:function(visible){var el=this.grid.getGridEl();if(el){if(visible===undefined){visible=el.hasClass('x-grid-hide-summary');}
el[visible?'removeClass':'addClass']('x-grid-hide-summary');}},renderSummary:function(o,cs){cs=cs||this.view.getColumnData();var cfg=this.cm.config;var buf=[],c,p={},cf,last=cs.length-1;for(var i=0,len=cs.length;i<len;i++){c=cs[i];cf=cfg[i];p.id=c.id;p.style=c.style;p.css=i==0?'x-grid3-cell-first ':(i==last?'x-grid3-cell-last ':'');if(cf.summaryType||cf.summaryRenderer){p.value=(cf.summaryRenderer||c.renderer)(o.data[c.name],p,o);}else{p.value='';}
if(p.value==undefined||p.value==="")p.value="&#160;";buf[buf.length]=this.cellTpl.apply(p);}
return this.rowTpl.apply({tstyle:'width:'+this.view.getTotalWidth()+';',cells:buf.join('')});},calculate:function(rs,cs){var data={},r,c,cfg=this.cm.config,cf;for(var j=0,jlen=rs.length;j<jlen;j++){r=rs[j];for(var i=0,len=cs.length;i<len;i++){c=cs[i];cf=cfg[i];if(cf.summaryType){data[c.name]=Ext.ux.GroupSummary.Calculations[cf.summaryType](data[c.name]||0,r,c.name,data);}}}
return data;},doGroupEnd:function(buf,g,cs,ds,colCount){var data=this.calculate(g.rs,cs);buf.push('</div>',this.renderSummary({data:data},cs),'</div>');},doWidth:function(col,w,tw){var gs=this.view.getGroups(),s;for(var i=0,len=gs.length;i<len;i++){s=gs[i].childNodes[2];s.style.width=tw;s.firstChild.style.width=tw;s.firstChild.rows[0].childNodes[col].style.width=w;}},doAllWidths:function(ws,tw){var gs=this.view.getGroups(),s,cells,wlen=ws.length;for(var i=0,len=gs.length;i<len;i++){s=gs[i].childNodes[2];s.style.width=tw;s.firstChild.style.width=tw;cells=s.firstChild.rows[0].childNodes;for(var j=0;j<wlen;j++){cells[j].style.width=ws[j];}}},doHidden:function(col,hidden,tw){var gs=this.view.getGroups(),s,display=hidden?'none':'';for(var i=0,len=gs.length;i<len;i++){s=gs[i].childNodes[2];s.style.width=tw;s.firstChild.style.width=tw;s.firstChild.rows[0].childNodes[col].style.display=display;}},refreshSummary:function(groupValue){return this.refreshSummaryById(this.view.getGroupId(groupValue));},getSummaryNode:function(gid){var g=Ext.fly(gid,'_gsummary');if(g){return g.down('.x-grid3-summary-row',true);}
return null;},refreshSummaryById:function(gid){var g=document.getElementById(gid);if(!g){return false;}
var rs=[];this.grid.store.each(function(r){if(r._groupId==gid){rs[rs.length]=r;}});var cs=this.view.getColumnData();var data=this.calculate(rs,cs);var markup=this.renderSummary({data:data},cs);var existing=this.getSummaryNode(gid);if(existing){g.removeChild(existing);}
Ext.DomHelper.append(g,markup);return true;},doUpdate:function(ds,record){this.refreshSummaryById(record._groupId);},doRemove:function(ds,record,index,isUpdate){if(!isUpdate){this.refreshSummaryById(record._groupId);}},showSummaryMsg:function(groupValue,msg){var gid=this.view.getGroupId(groupValue);var node=this.getSummaryNode(gid);if(node){node.innerHTML='<div class="x-grid3-summary-msg">'+msg+'</div>';}}});Ext.grid.GroupSummary=Ext.ux.GroupSummary;Ext.ux.GroupSummary.Calculations={'sum':function(v,record,field){return v+(record.data[field]||0);},'count':function(v,record,field,data){return data[field+'count']?++data[field+'count']:(data[field+'count']=1);},'max':function(v,record,field,data){var v=record.data[field];var max=data[field+'max']===undefined?(data[field+'max']=v):data[field+'max'];return v>max?(data[field+'max']=v):max;},'min':function(v,record,field,data){var v=record.data[field];var min=data[field+'min']===undefined?(data[field+'min']=v):data[field+'min'];return v<min?(data[field+'min']=v):min;},'average':function(v,record,field,data){var c=data[field+'count']?++data[field+'count']:(data[field+'count']=1);var t=(data[field+'total']=((data[field+'total']||0)+(record.data[field]||0)));return t===0?0:t/c;}};Ext.grid.GroupSummary.Calculations=Ext.ux.GroupSummary.Calculations;Ext.ux.HybridSummary=Ext.extend(Ext.ux.GroupSummary,{calculate:function(rs,cs){var gcol=this.view.getGroupField();var gvalue=rs[0].data[gcol];var gdata=this.getSummaryData(gvalue);return gdata||Ext.ux.HybridSummary.superclass.calculate.call(this,rs,cs);},updateSummaryData:function(groupValue,data,skipRefresh){var json=this.grid.store.reader.jsonData;if(!json.summaryData){json.summaryData={};}
json.summaryData[groupValue]=data;if(!skipRefresh){this.refreshSummary(groupValue);}},getSummaryData:function(groupValue){var json=this.grid.store.reader.jsonData;if(json&&json.summaryData){return json.summaryData[groupValue];}
return null;}});Ext.grid.HybridSummary=Ext.ux.HybridSummary;

if(!Array.prototype.map){Array.prototype.map=function(fun){var len=this.length;if(typeof fun!="function"){throw new TypeError();}
var res=new Array(len);var thisp=arguments[1];for(var i=0;i<len;i++){if(i in this){res[i]=fun.call(thisp,this[i],i,this);}}
return res;};}
Ext.ux.PagingMemoryProxy=Ext.extend(Ext.data.MemoryProxy,{constructor:function(data){Ext.ux.PagingMemoryProxy.superclass.constructor.call(this);this.data=data;},doRequest:function(action,rs,params,reader,callback,scope,options){params=params||{};var result;try{result=reader.readRecords(this.data);}catch(e){this.fireEvent("loadexception",this,options,null,e);callback.call(scope,null,options,false);return;}
if(params.filter!==undefined){result.records=result.records.filter(function(el){if(typeof(el)=="object"){var att=params.filterCol||0;return String(el.data[att]).match(params.filter)?true:false;}else{return String(el).match(params.filter)?true:false;}});result.totalRecords=result.records.length;}
if(params.sort!==undefined){var dir=String(params.dir).toUpperCase()=="DESC"?-1:1;var fn=function(r1,r2){return r1<r2;};result.records.sort(function(a,b){var v=0;if(typeof(a)=="object"){v=fn(a.data[params.sort],b.data[params.sort])*dir;}else{v=fn(a,b)*dir;}
if(v==0){v=(a.index<b.index?-1:1);}
return v;});}
if(params.start!==undefined&&params.limit!==undefined){result.records=result.records.slice(params.start,params.start+params.limit);}
callback.call(scope,result,options,true);}});Ext.data.PagingMemoryProxy=Ext.ux.PagingMemoryProxy;

Ext.ux.ProgressBarPager=Ext.extend(Object,{progBarWidth:225,defaultText:'Loading...',defaultAnimCfg:{duration:1,easing:'bounceOut'},constructor:function(config){if(config){Ext.apply(this,config);}},init:function(parent){if(parent.displayInfo){this.parent=parent;var ind=parent.items.indexOf(parent.displayItem);parent.remove(parent.displayItem,true);this.progressBar=new Ext.ProgressBar({text:this.defaultText,width:this.progBarWidth,animate:this.defaultAnimCfg});parent.displayItem=this.progressBar;parent.add(parent.displayItem);parent.doLayout();Ext.apply(parent,this.parentOverrides);this.progressBar.on('render',function(pb){pb.el.applyStyles('cursor:pointer');pb.el.on('click',this.handleProgressBarClick,this);},this);this.progressBar.on({scope:this,beforeDestroy:function(){this.progressBar.el.un('click',this.handleProgressBarClick,this);}});}},handleProgressBarClick:function(e){var parent=this.parent;var displayItem=parent.displayItem;var box=this.progressBar.getBox();var xy=e.getXY();var position=xy[0]-box.x;var pages=Math.ceil(parent.store.getTotalCount()/parent.pageSize);var newpage=Math.ceil(position/(displayItem.width/pages));parent.changePage(newpage);},parentOverrides:{updateInfo:function(){if(this.displayItem){var count=this.store.getCount();var pgData=this.getPageData();var pageNum=this.readPage(pgData);var msg=count==0?this.emptyMsg:String.format(this.displayMsg,this.cursor+1,this.cursor+count,this.store.getTotalCount());pageNum=pgData.activePage;;var pct=pageNum/pgData.pages;this.displayItem.updateProgress(pct,msg,this.animate||this.defaultAnimConfig);}}}});

Ext.ux.TabCloseMenu=function(){var tabs,menu,ctxItem;this.init=function(tp){tabs=tp;tabs.on('contextmenu',onContextMenu);}
function onContextMenu(ts,item,e){if(!menu){menu=new Ext.menu.Menu({items:[{id:tabs.id+'-close',text:'Close Tab',handler:function(){tabs.remove(ctxItem);}},{id:tabs.id+'-close-others',text:'Close Other Tabs',handler:function(){tabs.items.each(function(item){if(item.closable&&item!=ctxItem){tabs.remove(item);}});}}]});}
ctxItem=item;var items=menu.items;items.get(tabs.id+'-close').setDisabled(!item.closable);var disableOthers=true;tabs.items.each(function(){if(this!=item&&this.closable){disableOthers=false;return false;}});items.get(tabs.id+'-close-others').setDisabled(disableOthers);menu.showAt(e.getPoint());}};

Ext.ux.SelectBox=Ext.extend(Ext.form.ComboBox,{constructor:function(config){this.searchResetDelay=1000;config=config||{};config=Ext.apply(config||{},{editable:false,forceSelection:true,rowHeight:false,lastSearchTerm:false,triggerAction:'all',mode:'local'});Ext.ux.SelectBox.superclass.constructor.apply(this,arguments);this.lastSelectedIndex=this.selectedIndex||0;},initEvents:function(){Ext.ux.SelectBox.superclass.initEvents.apply(this,arguments);this.el.on('keydown',this.keySearch,this,true);this.cshTask=new Ext.util.DelayedTask(this.clearSearchHistory,this);},keySearch:function(e,target,options){var raw=e.getKey();var key=String.fromCharCode(raw);var startIndex=0;if(!this.store.getCount()){return;}
switch(raw){case Ext.EventObject.HOME:e.stopEvent();this.selectFirst();return;case Ext.EventObject.END:e.stopEvent();this.selectLast();return;case Ext.EventObject.PAGEDOWN:this.selectNextPage();e.stopEvent();return;case Ext.EventObject.PAGEUP:this.selectPrevPage();e.stopEvent();return;}
if((e.hasModifier()&&!e.shiftKey)||e.isNavKeyPress()||e.isSpecialKey()){return;}
if(this.lastSearchTerm==key){startIndex=this.lastSelectedIndex;}
this.search(this.displayField,key,startIndex);this.cshTask.delay(this.searchResetDelay);},onRender:function(ct,position){this.store.on('load',this.calcRowsPerPage,this);Ext.ux.SelectBox.superclass.onRender.apply(this,arguments);if(this.mode=='local'){this.calcRowsPerPage();}},onSelect:function(record,index,skipCollapse){if(this.fireEvent('beforeselect',this,record,index)!==false){this.setValue(record.data[this.valueField||this.displayField]);if(!skipCollapse){this.collapse();}
this.lastSelectedIndex=index+1;this.fireEvent('select',this,record,index);}},render:function(ct){Ext.ux.SelectBox.superclass.render.apply(this,arguments);if(Ext.isSafari){this.el.swallowEvent('mousedown',true);}
this.el.unselectable();this.innerList.unselectable();this.trigger.unselectable();this.innerList.on('mouseup',function(e,target,options){if(target.id&&target.id==this.innerList.id){return;}
this.onViewClick();},this);this.innerList.on('mouseover',function(e,target,options){if(target.id&&target.id==this.innerList.id){return;}
this.lastSelectedIndex=this.view.getSelectedIndexes()[0]+1;this.cshTask.delay(this.searchResetDelay);},this);this.trigger.un('click',this.onTriggerClick,this);this.trigger.on('mousedown',function(e,target,options){e.preventDefault();this.onTriggerClick();},this);this.on('collapse',function(e,target,options){Ext.getDoc().un('mouseup',this.collapseIf,this);},this,true);this.on('expand',function(e,target,options){Ext.getDoc().on('mouseup',this.collapseIf,this);},this,true);},clearSearchHistory:function(){this.lastSelectedIndex=0;this.lastSearchTerm=false;},selectFirst:function(){this.focusAndSelect(this.store.data.first());},selectLast:function(){this.focusAndSelect(this.store.data.last());},selectPrevPage:function(){if(!this.rowHeight){return;}
var index=Math.max(this.selectedIndex-this.rowsPerPage,0);this.focusAndSelect(this.store.getAt(index));},selectNextPage:function(){if(!this.rowHeight){return;}
var index=Math.min(this.selectedIndex+this.rowsPerPage,this.store.getCount()-1);this.focusAndSelect(this.store.getAt(index));},search:function(field,value,startIndex){field=field||this.displayField;this.lastSearchTerm=value;var index=this.store.find.apply(this.store,arguments);if(index!==-1){this.focusAndSelect(index);}},focusAndSelect:function(record){var index=typeof record==='number'?record:this.store.indexOf(record);this.select(index,this.isExpanded());this.onSelect(this.store.getAt(record),index,this.isExpanded());},calcRowsPerPage:function(){if(this.store.getCount()){this.rowHeight=Ext.fly(this.view.getNode(0)).getHeight();this.rowsPerPage=this.maxHeight/this.rowHeight;}else{this.rowHeight=false;}}});

Ext.Spotlight=function(config){Ext.apply(this,config);}
Ext.Spotlight.prototype={active:false,animate:true,duration:.25,easing:'easeNone',animated:false,createElements:function(){var bd=Ext.getBody();this.right=bd.createChild({cls:'x-spotlight'});this.left=bd.createChild({cls:'x-spotlight'});this.top=bd.createChild({cls:'x-spotlight'});this.bottom=bd.createChild({cls:'x-spotlight'});this.all=new Ext.CompositeElement([this.right,this.left,this.top,this.bottom]);},show:function(el,callback,scope){if(this.animated){this.show.defer(50,this,[el,callback,scope]);return;}
this.el=Ext.get(el);if(!this.right){this.createElements();}
if(!this.active){this.all.setDisplayed('');this.applyBounds(true,false);this.active=true;Ext.EventManager.onWindowResize(this.syncSize,this);this.applyBounds(false,this.animate,false,callback,scope);}else{this.applyBounds(false,false,false,callback,scope);}},hide:function(callback,scope){if(this.animated){this.hide.defer(50,this,[callback,scope]);return;}
Ext.EventManager.removeResizeListener(this.syncSize,this);this.applyBounds(true,this.animate,true,callback,scope);},doHide:function(){this.active=false;this.all.setDisplayed(false);},syncSize:function(){this.applyBounds(false,false);},applyBounds:function(basePts,anim,doHide,callback,scope){var rg=this.el.getRegion();var dw=Ext.lib.Dom.getViewWidth(true);var dh=Ext.lib.Dom.getViewHeight(true);var c=0,cb=false;if(anim){cb={callback:function(){c++;if(c==4){this.animated=false;if(doHide){this.doHide();}
Ext.callback(callback,scope,[this]);}},scope:this,duration:this.duration,easing:this.easing};this.animated=true;}
this.right.setBounds(rg.right,basePts?dh:rg.top,dw-rg.right,basePts?0:(dh-rg.top),cb);this.left.setBounds(0,0,rg.left,basePts?0:rg.bottom,cb);this.top.setBounds(basePts?dw:rg.left,0,basePts?0:dw-rg.left,rg.top,cb);this.bottom.setBounds(0,rg.bottom,basePts?0:rg.right,dh-rg.bottom,cb);if(!anim){if(doHide){this.doHide();}
if(callback){Ext.callback(callback,scope,[this]);}}},destroy:function(){this.doHide();Ext.destroy(this.right,this.left,this.top,this.bottom);delete this.el;delete this.all;}};

Ext.ux.Spinner=Ext.extend(Ext.util.Observable,{incrementValue:1,alternateIncrementValue:5,triggerClass:'x-form-spinner-trigger',splitterClass:'x-form-spinner-splitter',alternateKey:Ext.EventObject.shiftKey,defaultValue:0,accelerate:false,constructor:function(config){Ext.ux.Spinner.superclass.constructor.call(this,config);Ext.apply(this,config);this.mimicing=false;},init:function(field){this.field=field;field.afterMethod('onRender',this.doRender,this);field.afterMethod('onEnable',this.doEnable,this);field.afterMethod('onDisable',this.doDisable,this);field.afterMethod('afterRender',this.doAfterRender,this);field.afterMethod('onResize',this.doResize,this);field.afterMethod('onFocus',this.doFocus,this);field.beforeMethod('onDestroy',this.doDestroy,this);},doRender:function(ct,position){var el=this.el=this.field.getEl();var f=this.field;if(!f.wrap){f.wrap=this.wrap=el.wrap({cls:"x-form-field-wrap"});}
else{this.wrap=f.wrap.addClass('x-form-field-wrap');}
this.trigger=this.wrap.createChild({tag:"img",src:Ext.BLANK_IMAGE_URL,cls:"x-form-trigger "+this.triggerClass});if(!f.width){this.wrap.setWidth(el.getWidth()+this.trigger.getWidth());}
this.splitter=this.wrap.createChild({tag:'div',cls:this.splitterClass,style:'width:13px; height:2px;'});this.splitter.setRight((Ext.isIE)?1:2).setTop(10).show();this.proxy=this.trigger.createProxy('',this.splitter,true);this.proxy.addClass("x-form-spinner-proxy");this.proxy.setStyle('left','0px');this.proxy.setSize(14,1);this.proxy.hide();this.dd=new Ext.dd.DDProxy(this.splitter.dom.id,"SpinnerDrag",{dragElId:this.proxy.id});this.initTrigger();this.initSpinner();},doAfterRender:function(){var y;if(Ext.isIE&&this.el.getY()!=(y=this.trigger.getY())){this.el.position();this.el.setY(y);}},doEnable:function(){if(this.wrap){this.wrap.removeClass(this.field.disabledClass);}},doDisable:function(){if(this.wrap){this.wrap.addClass(this.field.disabledClass);this.el.removeClass(this.field.disabledClass);}},doResize:function(w,h){if(typeof w=='number'){this.el.setWidth(this.field.adjustWidth('input',w-this.trigger.getWidth()));}
this.wrap.setWidth(this.el.getWidth()+this.trigger.getWidth());},doFocus:function(){if(!this.mimicing){this.wrap.addClass('x-trigger-wrap-focus');this.mimicing=true;Ext.get(Ext.isIE?document.body:document).on("mousedown",this.mimicBlur,this,{delay:10});this.el.on('keydown',this.checkTab,this);}},checkTab:function(e){if(e.getKey()==e.TAB){this.triggerBlur();}},mimicBlur:function(e){if(!this.wrap.contains(e.target)&&this.field.validateBlur(e)){this.triggerBlur();}},triggerBlur:function(){this.mimicing=false;Ext.get(Ext.isIE?document.body:document).un("mousedown",this.mimicBlur,this);this.el.un("keydown",this.checkTab,this);this.field.beforeBlur();this.wrap.removeClass('x-trigger-wrap-focus');this.field.onBlur.call(this.field);},initTrigger:function(){this.trigger.addClassOnOver('x-form-trigger-over');this.trigger.addClassOnClick('x-form-trigger-click');},initSpinner:function(){this.field.addEvents({'spin':true,'spinup':true,'spindown':true});this.keyNav=new Ext.KeyNav(this.el,{"up":function(e){e.preventDefault();this.onSpinUp();},"down":function(e){e.preventDefault();this.onSpinDown();},"pageUp":function(e){e.preventDefault();this.onSpinUpAlternate();},"pageDown":function(e){e.preventDefault();this.onSpinDownAlternate();},scope:this});this.repeater=new Ext.util.ClickRepeater(this.trigger,{accelerate:this.accelerate});this.field.mon(this.repeater,"click",this.onTriggerClick,this,{preventDefault:true});this.field.mon(this.trigger,{mouseover:this.onMouseOver,mouseout:this.onMouseOut,mousemove:this.onMouseMove,mousedown:this.onMouseDown,mouseup:this.onMouseUp,scope:this,preventDefault:true});this.field.mon(this.wrap,"mousewheel",this.handleMouseWheel,this);this.dd.setXConstraint(0,0,10)
this.dd.setYConstraint(1500,1500,10);this.dd.endDrag=this.endDrag.createDelegate(this);this.dd.startDrag=this.startDrag.createDelegate(this);this.dd.onDrag=this.onDrag.createDelegate(this);},onMouseOver:function(){if(this.disabled){return;}
var middle=this.getMiddle();this.tmpHoverClass=(Ext.EventObject.getPageY()<middle)?'x-form-spinner-overup':'x-form-spinner-overdown';this.trigger.addClass(this.tmpHoverClass);},onMouseOut:function(){this.trigger.removeClass(this.tmpHoverClass);},onMouseMove:function(){if(this.disabled){return;}
var middle=this.getMiddle();if(((Ext.EventObject.getPageY()>middle)&&this.tmpHoverClass=="x-form-spinner-overup")||((Ext.EventObject.getPageY()<middle)&&this.tmpHoverClass=="x-form-spinner-overdown")){}},onMouseDown:function(){if(this.disabled){return;}
var middle=this.getMiddle();this.tmpClickClass=(Ext.EventObject.getPageY()<middle)?'x-form-spinner-clickup':'x-form-spinner-clickdown';this.trigger.addClass(this.tmpClickClass);},onMouseUp:function(){this.trigger.removeClass(this.tmpClickClass);},onTriggerClick:function(){if(this.disabled||this.el.dom.readOnly){return;}
var middle=this.getMiddle();var ud=(Ext.EventObject.getPageY()<middle)?'Up':'Down';this['onSpin'+ud]();},getMiddle:function(){var t=this.trigger.getTop();var h=this.trigger.getHeight();var middle=t+(h/2);return middle;},isSpinnable:function(){if(this.disabled||this.el.dom.readOnly){Ext.EventObject.preventDefault();return false;}
return true;},handleMouseWheel:function(e){if(this.wrap.hasClass('x-trigger-wrap-focus')==false){return;}
var delta=e.getWheelDelta();if(delta>0){this.onSpinUp();e.stopEvent();}
else
if(delta<0){this.onSpinDown();e.stopEvent();}},startDrag:function(){this.proxy.show();this._previousY=Ext.fly(this.dd.getDragEl()).getTop();},endDrag:function(){this.proxy.hide();},onDrag:function(){if(this.disabled){return;}
var y=Ext.fly(this.dd.getDragEl()).getTop();var ud='';if(this._previousY>y){ud='Up';}
if(this._previousY<y){ud='Down';}
if(ud!=''){this['onSpin'+ud]();}
this._previousY=y;},onSpinUp:function(){if(this.isSpinnable()==false){return;}
if(Ext.EventObject.shiftKey==true){this.onSpinUpAlternate();return;}
else{this.spin(false,false);}
this.field.fireEvent("spin",this);this.field.fireEvent("spinup",this);},onSpinDown:function(){if(this.isSpinnable()==false){return;}
if(Ext.EventObject.shiftKey==true){this.onSpinDownAlternate();return;}
else{this.spin(true,false);}
this.field.fireEvent("spin",this);this.field.fireEvent("spindown",this);},onSpinUpAlternate:function(){if(this.isSpinnable()==false){return;}
this.spin(false,true);this.field.fireEvent("spin",this);this.field.fireEvent("spinup",this);},onSpinDownAlternate:function(){if(this.isSpinnable()==false){return;}
this.spin(true,true);this.field.fireEvent("spin",this);this.field.fireEvent("spindown",this);},spin:function(down,alternate){var v=parseFloat(this.field.getValue());var incr=(alternate==true)?this.alternateIncrementValue:this.incrementValue;(down==true)?v-=incr:v+=incr;v=(isNaN(v))?this.defaultValue:v;v=this.fixBoundries(v);this.field.setRawValue(v);},fixBoundries:function(value){var v=value;if(this.field.minValue!=undefined&&v<this.field.minValue){v=this.field.minValue;}
if(this.field.maxValue!=undefined&&v>this.field.maxValue){v=this.field.maxValue;}
return this.fixPrecision(v);},fixPrecision:function(value){var nan=isNaN(value);if(!this.field.allowDecimals||this.field.decimalPrecision==-1||nan||!value){return nan?'':value;}
return parseFloat(parseFloat(value).toFixed(this.field.decimalPrecision));},doDestroy:function(){if(this.trigger){this.trigger.remove();}
if(this.wrap){this.wrap.remove();delete this.field.wrap;}
if(this.splitter){this.splitter.remove();}
if(this.dd){this.dd.unreg();this.dd=null;}
if(this.proxy){this.proxy.remove();}
if(this.repeater){this.repeater.purgeListeners();}}});Ext.form.Spinner=Ext.ux.Spinner;

Ext.ux.SpinnerField=Ext.extend(Ext.form.NumberField,{deferHeight:true,autoSize:Ext.emptyFn,onBlur:Ext.emptyFn,adjustSize:Ext.BoxComponent.prototype.adjustSize,constructor:function(config){var spinnerConfig=Ext.copyTo({},config,'incrementValue,alternateIncrementValue,accelerate,defaultValue,triggerClass,splitterClass');var spl=this.spinner=new Ext.form.Spinner(spinnerConfig);var plugins=config.plugins?(Ext.isArray(config.plugins)?config.plugins.push(spl):[config.plugins,spl]):spl;Ext.ux.SpinnerField.superclass.constructor.call(this,Ext.apply(config,{plugins:plugins}));},onShow:function(){if(this.wrap){this.wrap.dom.style.display='';this.wrap.dom.style.visibility='visible';}},onHide:function(){this.wrap.dom.style.display='none';},getResizeEl:function(){return this.wrap;},getPositionEl:function(){return this.wrap;},alignErrorIcon:function(){if(this.wrap){this.errorIcon.alignTo(this.wrap,'tl-tr',[2,0]);}},validateBlur:function(){return true;}});Ext.reg('spinner',Ext.ux.SpinnerField);Ext.form.SpinnerField=Ext.ux.SpinnerField;

Ext.ux.SliderTip=Ext.extend(Ext.Tip,{minWidth:10,offsets:[0,-10],init:function(slider){slider.on('dragstart',this.onSlide,this);slider.on('drag',this.onSlide,this);slider.on('dragend',this.hide,this);slider.on('destroy',this.destroy,this);},onSlide:function(slider){this.show();this.body.update(this.getText(slider));this.doAutoWidth();this.el.alignTo(slider.thumb,'b-t?',this.offsets);},getText:function(slider){return String(slider.getValue());}});

Ext.ux.SlidingPager=Ext.extend(Object,{init:function(pbar){Ext.each(pbar.items.getRange(2,6),function(c){c.hide();});var slider=new Ext.Slider({width:114,minValue:1,maxValue:1,plugins:new Ext.ux.SliderTip({getText:function(s){return String.format('Page <b>{0}</b> of <b>{1}</b>',s.value,s.maxValue);}}),listeners:{changecomplete:function(s,v){pbar.changePage(v);}}});pbar.insert(5,slider);pbar.on({change:function(pb,data){slider.maxValue=data.pages;slider.setValue(data.activePage);},beforedestroy:function(){slider.destroy();}});}});
