<?php
 include("../../config/settings.inc.php");
 $wtype = isset($_GET["wtype"]) ? $_GET["wtype"] : Array();
 $ltype = isset($_GET["ltype"]) ? $_GET["ltype"] : Array();
 $syear = isset($_GET["syear"]) ? $_GET["syear"] : date("Y");
 $smonth = isset($_GET["smonth"]) ? $_GET["smonth"] : date("m");
 $sday = isset($_GET["sday"]) ? $_GET["sday"] : date("d");
 $shour = isset($_GET["shour"]) ? $_GET["shour"] : 12;
 $sts = mktime($shour, 0, 0, $smonth, $sday, $syear);
 $eyear = isset($_GET["eyear"]) ? $_GET["eyear"] : date("Y");
 $emonth = isset($_GET["emonth"]) ? $_GET["emonth"] : date("m");
 $eday = isset($_GET["eday"]) ? $_GET["eday"] : date("d");
 $ehour = isset($_GET["ehour"]) ? $_GET["ehour"] : 12;
 $ets = mktime($ehour, 0, 0, $emonth, $eday, $eyear);
 $hail = isset($_GET["hail"]) ? $_GET["hail"] : 0.75;
 $wfo = isset($_GET["wfo"]) ? substr($_GET["wfo"],0,3) : "MPX";

 $abegin = mktime(0,0,0,6,8,2005);
 if ($sts < $abegin){ $sts = $abegin; }
 if ($ets < $sts){ $n = $sts; $sts = $ets; $ets = $n; }

 if ( in_array("FF", $wtype) && $syear < 2008){ 
   $wtype = array_diff( $wtype, array("FF") );
 }
 if ( in_array("FF", $ltype) && $syear < 2008){ 
   $ltype = array_diff( $ltype, array("FF") );
 }

 $TITLE = "IEM Cow";
 $THISPAGE = "severe-cow";
 include("$rootpath/include/header.php");
 include("$rootpath/include/forms.php");
 include("$rootpath/include/wfoLocs.php");
 include("$rootpath/include/database.inc.php");
?>
<a href="<?php echo $rooturl; ?>/cow/">Reset Application</a> (All timestamps are displayed in UTC)
<form method="GET" name="cow">
<table>
<tr>
 <th>Start:</th><td><?php echo yearSelect2(2005,$syear,"syear"); ?><?php echo monthSelect($smonth, "smonth"); ?><?php echo daySelect2($sday, "sday"); ?><?php echo gmtHourSelect($shour, "shour"); ?></td>
 <th>End:</th><td><?php echo yearSelect2(2005,$eyear,"eyear"); ?><?php echo monthSelect($emonth, "emonth"); ?><?php echo daySelect2($eday, "eday"); ?><?php echo gmtHourSelect($ehour, "ehour"); ?></td>
</tr>
</table>
<table>
<tr><th>WFO:</th>
<td>
<select name="wfo">
<?php
while( list($key, $value) = each($wfos) ){
  echo "<option value=\"$key\" ";
  if ($wfo == $key) echo "SELECTED";
  echo ">[".$key."] ". $wfos[$key]["city"] ."\n";
}
?>
</select>
</td>
<th>Warning Type:</th>
<td>
<input name="wtype[]" type="checkbox" value="TO" <?php if (in_array("TO", $wtype)) echo "CHECKED"; ?>>Tornado
<input name="wtype[]" type="checkbox" value="SV" <?php if (in_array("SV", $wtype)) echo "CHECKED"; ?>>Svr T'storm
<input name="wtype[]" type="checkbox" value="MA" <?php if (in_array("MA", $wtype)) echo "CHECKED"; ?>>Marine
<input name="wtype[]" type="checkbox" value="FF" <?php if (in_array("FF", $wtype)) echo "CHECKED"; ?>>Flash Flood (2008+)
</td></tr>
<tr>
<th>Hail Size:</th>
<td><select name="hail">
  <option value="0.75" <?php if ($hail == 0.75) echo "SELECTED"; ?>>0.75
  <option value="1.00" <?php if ($hail == 1.00) echo "SELECTED"; ?>>1.00
</select></td>
<th>LSR Type:</th>
<td>
<input name="ltype[]" type="checkbox" value="TO" <?php if (in_array("TO", $ltype)) echo "CHECKED"; ?>>Tornado
<input name="ltype[]" type="checkbox" value="SV" <?php if (in_array("SV", $ltype)) echo "CHECKED"; ?>>Svr T'storm
<input name="ltype[]" type="checkbox" value="MA" <?php if (in_array("MA", $ltype)) echo "CHECKED"; ?>>Marine
<input name="ltype[]" type="checkbox" value="FF" <?php if (in_array("FF", $ltype)) echo "CHECKED"; ?>>Flash Flood (2008+)
</td></tr>
</table>
<input type="submit" value="Go Cow Go"></form>

<?php if (isset($_GET["hail"])){ include("worker.php"); }
      else {
?>

<h3 class="heading">IEM Cow (NWS Storm Based Warning Verification)</h3>

<p><img src="cow.jpg" align="right" style="margin: 5px;">Data presented here is <b>unofficial</b> and should be used for 
educational purposes only.  This application allows you to view warnings
and storm reports issued by a Weather Forecast Office (WFO) for a period
of time of your choice.  The application attempts to automatically provide
verification numbers for the warnings issued.

<p>This application works for dates after 8 June 2005.

<h3>Storm Based Warnings</h3>
<p><img src="http://www.weather.gov/sbwarnings/images/SBW-main.jpg" align="left" style="margin:5px;"><img src="http://www.weather.gov/sbwarnings/images/SBW-main2.jpg" align="left" style="margin: 5px;"> On the first of October 2007, the National Weather
Service began issuing warnings for tornados, severe weather, floods, and 
marine hazards on a storm by storm basis.  Previously, the warnings
were issued for an entire county. This application attempts to provide 
verification statistics for these storm based warnings.

<p>The images shown are taken from the <a href="http://www.weather.gov/sbwarnings/">NWS Storm Based Warnings</a> website.

<p>Related links:
<ul>
 <li><a href="sbwsum.phtml">Graphical Summaries of Daily SBW</a></li>
 <li><a href="sbwstats.phtml">SBW Size Statistics</a></li>
</ul>

<?php } include("$rootpath/include/footer.php"); ?>
