<?php
include("../../config/settings.inc.php");
include("$rootpath/include/database.inc.php");
$pgconn = iemdb("postgis");
pg_query($pgconn, "SET TIME ZONE 'GMT'");
include("$rootpath/include/lsrs.php");
include("$rootpath/include/google_keys.php");
include("$rootpath/include/wfoLocs.php");
include("$rootpath/include/forms.php");

/* Calling API */
$ts = isset($_GET["ts"]) ? strtotime($_GET["ts"]) : time();
$ts2 = isset($_GET["ts2"]) ? strtotime($_GET["ts2"]) : $ts;
$wfo = isset($_GET["wfo"]) ? $_GET["wfo"] : "DMX";
$lat0 = isset($_GET["lat0"]) ? $_GET["lat0"] : $wfos[$wfo]["lat"];
$lon0 = isset($_GET["lon0"]) ? $_GET["lon0"] : $wfos[$wfo]["lon"];
$year = isset($_GET["year"]) ? $_GET["year"] : date("Y", $ts);
if ($ts2 != $ts){
  $lat0 = $wfos[$wfo]["lat"];
  $lon0 = $wfos[$wfo]["lon"];
}

$smonth = isset($_GET["smonth"]) ? $_GET["smonth"] : date("m", $ts);
$sday = isset($_GET["sday"]) ? $_GET["sday"] : date("d", $ts);
$shour = isset($_GET["shour"]) ? $_GET["shour"] : date("H", $ts);
$sminute = isset($_GET["sminute"]) ? $_GET["sminute"] : date("i", $ts);

$emonth = isset($_GET["emonth"]) ? $_GET["emonth"] : date("m", $ts2);
$eday = isset($_GET["eday"]) ? $_GET["eday"] : date("d", $ts2);
$ehour = isset($_GET["ehour"]) ? $_GET["ehour"] : date("H", $ts2);
$eminute = isset($_GET["eminute"]) ? $_GET["eminute"] : date("i", $ts2);

if (! isset($_GET["ts"])){ $ts = mktime($shour, $sminute, 0, $smonth, $sday, $year);}
if (! isset($_GET["ts2"])){ $ts2 = mktime($ehour, $eminute, 0, $emonth, $eday, $year);}

$tsSQL = date("Y-m-d H:i:00+00", $ts);
$tsSQL2 = date("Y-m-d H:i:00+00", $ts2);
$year = date("Y", $ts);
$d1 = date("d M Y H:i" ,  $ts);
$d2 = date("d M Y H:i" ,  $ts2);

$basets = $ts - (($sminute % 5) * 60);

if ($ts >= $ts2){
$minx = $lon0 - 0.02;
$maxx = $lon0 + 0.02;
$miny = $lat0 - 0.02;
$maxy = $lat0 + 0.02;
$sql = "select distinct source, county, state, typetext,remark, x(geom) as lon, y(geom) as lat, 
        city, magnitude, valid, geom, type as ltype, wfo from lsrs_${year} 
        WHERE valid = '$tsSQL' and
        geom && GeomFromEWKT('SRID=4326;MULTIPOLYGON((($minx $miny,$minx $maxy,$maxx $maxy,$maxx $miny,$minx $miny)))') ORDER by valid ASC";
} else {
  $sql = "select distinct source, typetext, remark, county, state,
        x(geom) as lon, y(geom) as lat,
        city, magnitude, valid, geom, type as ltype, wfo from lsrs_${year}
        WHERE valid >= '$tsSQL' and valid <= '$tsSQL2' and
        wfo = '$wfo' ORDER by valid ASC";
}
$rs = pg_exec($pgconn, $sql);
$g = "";
$lats = Array();
$lons = Array();
$table = "<table cellspacing=\"0\" cellpadding=\"3\" border=\"1\">
<tr style=\"background: #fafa00;\"><th>GMT Time</th><th>County</th><th>Location</th><th>Type</th><th>Magnitude</th></tr>";

for ($i=0;$row = @pg_fetch_array($rs,$i); $i++)
{
   $timestamp = strtotime(substr($row["valid"],0,16));
   //$imgx = intval(($row["lon"] - $minx) / $dx);
   //$imgy = intval(($maxy - $row["lat"]) / $dy);
   $lats[] = $row["lat"];
   $lons[] = $row["lon"];
   $wfo = $row["wfo"];
   $table .= sprintf("<tr><td><a href=\"javascript: showMarker($i);\">%s</a></td><td>%s</td><td>%s,%s</td><td>%s</td><td>%s</td></tr><tr><td></td><td colspan=\"4\">%s</td></tr>",
    date("m/d/Y H:i", $timestamp), $row["county"], $row["city"], 
    $row["state"], $row["typetext"], $row["magnitude"], $row["remark"]);

   $desc = "<b>Event:</b> ". $row['typetext'] ."<br /><b>Time:</b> ". date('d M Y H:i', $timestamp) ." GMT<br /><b>Magnitude:</b> ". $row['magnitude'] ."<br /><b>Source:</b> ". $row['source'] ."<br /><b>Remark:</b> ". $row['remark'] ;

   $g .= "
 markers[$i] = new GMarker(new GLatLng(". $row["lat"] .", ". $row["lon"] ."));
    GEvent.addListener(markers[$i], \"click\", function() {
            markers[$i].openInfoWindowHtml(\"$desc\",
              {maxWidth: 300});
          });
    map.addOverlay(markers[$i]);
    markers[$i].openInfoWindowHtml(\"$desc\",
              {maxWidth: 300});
    ";
} /* End for() loop */

$table .= "</table>";

?>
<?php 
$TITLE = "Local Storm Reports";
$THISPAGE = "severe-lsr";
$BODYEXTRA = "onload=\"load()\" onunload=\"GUnload()\"";
$HEADEXTRA = "
<script src=\"http://maps.google.com/maps?file=api&amp;v=2&amp;key=". $GOOGLEKEYS[$rooturl]["maplsr"] ."\" type=\"text/javascript\"></script>";

include("$rootpath/include/header.php");?>
<script type="text/javascript">
//<![CDATA[
var icon = new GIcon();
icon.image = "http://labs.google.com/ridefinder/images/mm_20_blue.png";
icon.shadow = "http://labs.google.com/ridefinder/images/mm_20_shadow.png";
icon.iconSize = new GSize(12, 20);
icon.shadowSize = new GSize(22, 20);
icon.iconAnchor = new GPoint(6, 20);
icon.infoWindowAnchor = new GPoint(5, 1);

var map;
var sbwLayer;
var markers = new Array();


CustomGetTileUrl=function(a,b,c) {
  if (typeof(window['this.myMercZoomLevel'])=="undefined") this.myMercZoomLevel=0;
  if (typeof(window['this.myStyles'])=="undefined") this.myStyles="default";
  var lULP = new GPoint(a.x*256,(a.y+1)*256);
  var lLRP = new GPoint((a.x+1)*256,a.y*256);
  var lUL = G_NORMAL_MAP.getProjection().fromPixelToLatLng(lULP,b,c);
  var lLR = G_NORMAL_MAP.getProjection().fromPixelToLatLng(lLRP,b,c);
  // switch between Mercator and DD if merczoomlevel is set
  if (this.myMercZoomLevel!=0 && map.getZoom() < this.myMercZoomLevel) {
    var lBbox=dd2MercMetersLng(lUL.lngDegrees)+","+dd2MercMetersLat(lUL.latDegrees)+","+dd2MercMetersLng(lLR.lngDegrees)+","+dd2MercMetersLat(lLR.latDegrees);
    var lSRS="EPSG:54004";
  } else {
    var lBbox=lUL.x+","+lUL.y+","+lLR.x+","+lLR.y;
    var lSRS="EPSG:4326";
  }
  var ts = new Date();
  var lURL=this.myBaseURL;
  lURL+="&REQUEST=GetMap";
  lURL+="&SERVICE=WMS";
  lURL+="&reaspect=false&VERSION=1.1.1";
  lURL+="&LAYERS="+this.myLayers;
  lURL+="&STYLES="+this.myStyles; 
  lURL+="&FORMAT="+this.myFormat;
  lURL+="&BGCOLOR=0xFFFFFF";
  lURL+="&TRANSPARENT=TRUE";
  lURL+="&SRS="+lSRS;
  lURL+="&TIME=<?php echo date('Y-m-d\TH:i:00\Z', $basets); ?>";
  lURL+="&BBOX="+lBbox;
  lURL+="&WIDTH=256";
  lURL+="&HEIGHT=256";
  lURL+="&GroupName="+this.myLayers;
  lURL+="&bogus="+ts.getTime();
  return lURL;
}

var tileNEX= new GTileLayer(new GCopyrightCollection(''),1,17);
    tileNEX.myLayers='nexrad-n0r-wmst';
    tileNEX.myFormat='image/png';
    tileNEX.myBaseURL='http://mesonet.agron.iastate.edu/cgi-bin/wms/nexrad/n0r.cgi?';
    tileNEX.getTileUrl=CustomGetTileUrl;

var layer4=[G_NORMAL_MAP.getTileLayers()[0],tileNEX];
var custommap4 = new GMapType(layer4, G_SATELLITE_MAP.getProjection(), 'Nexrad', G_SATELLITE_MAP);

function showMarker(i){
  GEvent.trigger(markers[i], 'click');
}
var showSBW = 1;
function toggleSBW(){
  if (! showSBW){ sbwLayer.show(); }
  else{ sbwLayer.hide(); }
  showSBW = ! showSBW;
}

function load() {
  if (GBrowserIsCompatible()) {
    map = new GMap2(document.getElementById("gmap"));
    map.setCenter(new GLatLng(<?php echo $lat0; ?>, <?php echo $lon0; ?>), 8);
    map.addControl(new GLargeMapControl());
 
    var mapControl = new GMapTypeControl();
    map.addControl(mapControl);

    var myicon = new GIcon(icon);
    map.addMapType(custommap4);
    <?php echo $g; ?>

    kml = "http://mesonet.agron.iastate.edu/kml/sbw_interval.php?wfo=<?php echo $wfo; ?>&ts=<?php echo date('Y-m-d%20H:i', $ts); ?>&ts2=<?php echo date('Y-m-d%20H:i', $ts2); ?>";
    sbwLayer = new GGeoXml(kml);
    map.addOverlay(sbwLayer);

<?php if ($ts == $ts2) { echo "map.setMapType(custommap4);"; } ?>



  }
}

//]]>
</script>
<div style="padding-left: 15px;">

<form method="GET" action="maplsr.phtml" name="goo">
<h3>Local Storm Report (LSR) Viewer</h3>
<div style="border:1px solid #ccc; padding: 5px; margin-left: 20px; float:left;">
<strong>Weather Office:</strong> <?php echo wfoSelect($wfo); ?>
<table>
<tr>
  <th>Start Time</th>
  <td rowspan="2"><?php echo yearSelect(2003,$year); ?></td>
  <td><?php echo monthSelect($smonth, "smonth"); ?></td>
  <td><?php echo daySelect2($sday, "sday"); ?></td>
  <td><?php echo gmtHourSelect($shour, "shour"); ?></td>
  <td><?php echo minuteSelect($sminute, "sminute"); ?></td></tr>
<tr>
  <th>End Time</th>
  <td><?php echo monthSelect($emonth, "emonth"); ?></td>
  <td><?php echo daySelect2($eday, "eday"); ?></td>
  <td><?php echo gmtHourSelect($ehour, "ehour"); ?></td>
  <td><?php echo minuteSelect($eminute, "eminute"); ?></td></tr>
</table>


<input type="submit" value="Update Map">
</div>
<br clear="all" />
<strong><?php echo $wfos[$wfo]['city']; ?>'s Local Storm Reports between <?php echo "$d1 and $d2"; ?></strong<br />
<input type="checkbox" checked="checked" name="showsbw" onClick="javascript: toggleSBW();">Show Storm Based Warnings
<div id="gmap" style="width: 90%; height: 500px"></div>

<h4>Table Listing of Events:</h4>

<i>Click event timestamp to view on map</i>

<?php echo $table; ?>

</form>
</div>

<?php include("$rootpath/include/footer.php"); ?>
