<?php
include("../../config/settings.inc.php");
include("$rootpath/include/database.inc.php");
/* Map warnings and a LSR */
include("../GIS/apps/rview/lib.php");

$ts = isset($_GET["ts"]) ? strtotime($_GET["ts"]) : die("Booooo");
$lat0 = isset($_GET["lat0"]) ? $_GET["lat0"] : die("Boooo");
$lon0 = isset($_GET["lon0"]) ? $_GET["lon0"] : die("Boooo");

$tsSQL = date("Y-m-d H:i:00+00", $ts);
$year = date("Y", $ts);
$d = date("d F Y H:i" ,  $ts);

$month = date("m", $ts);
$day = date("d", $ts);
$hour = date("H", $ts);
$m = date("i", $ts);

if ($m >= 55) $ma = "55";
else if ($m >= 50) $ma = "50";
else if ($m >= 45) $ma = "45";
else if ($m >= 40) $ma = "40";
else if ($m >= 35) $ma = "35";
else if ($m >= 30) $ma = "30";
else if ($m >= 25) $ma = "25";
else if ($m >= 20) $ma = "20";
else if ($m >= 15) $ma = "15";
else if ($m >= 10) $ma = "10";
else if ($m >= 5) $ma = "05";
else $ma = "00";
$m = $ma;
$basets = mktime($hour, $m, 0, $month, $day, $year);



dl($mapscript);

$map = ms_newMapObj("$rootpath/data/gis/base4326.map");

$map->setProjection("proj=latlong");
$map->set("width", 450);
$map->set("height", 450);
$lpad = 0.50;
$map->setextent($lon0 - $lpad,
                $lat0 - $lpad,
                $lon0 + $lpad,
                $lat0 + $lpad);


$namer = $map->getlayerbyname("namerica");
$namer->set("status", 1);

$stlayer = $map->getlayerbyname("states");
$stlayer->set("status", 1);

$lakes = $map->getlayerbyname("lakes");
$lakes->set("status", 1);

$clayer = $map->getlayerbyname("uscounties");
$clayer->set("status", 1);

$c0 = $map->getlayerbyname("warnings0_c");
$c0->set("connection", $_DATABASES["postgis"]);
$c0->set("status", 1);
$c0->set("data", "geom from (select significance, phenomena, geom, oid from warnings_$year WHERE expire > '$tsSQL' and issue <= '$tsSQL' and gtype = 'C' ORDER by phenomena ASC) as foo using unique oid using SRID=4326");


$p0 = $map->getlayerbyname("warnings0_p");
$p0->set("connection", $_DATABASES["postgis"]);
$p0->set("status", 1);
$p0->set("data", "geom from (select phenomena, geom, oid from warnings_$year WHERE significance != 'A' and expire > '$tsSQL' and issue <= '$tsSQL' and gtype = 'P') as foo using unique oid using SRID=4326");


$lsrs = $map->getlayerbyname("lsrs");
$lsrs->set("connection", $_DATABASES["postgis"]);
$lsrs->set("status",1);
$lsrs->set("data", "geom from (select distinct city, magnitude, valid, geom, type as ltype, city || magnitude || x(geom) || y(geom) as k from lsrs_${year} WHERE valid = '$tsSQL') as foo USING unique k USING SRID=4326");

$fp = "/mesonet/ARCHIVE/data/". date('Y/m/d/', $basets) ."GIS/uscomp/n0r_". date('YmdHi', $basets) .".png";
if (! is_file($fp))
    echo "<br /><i><b>NEXRAD composite not available: $fp</b></i>";
$radfile = $fp;


$img = $map->prepareImage();

$namer->draw($img);
$stlayer->draw( $img);
$lakes->draw($img);

$radar = $map->getlayerbyname("nexrad_n0r");
$radar->set("data", $radfile);
$radar->set("status", 1);
$radar->draw($img);
$clayer->draw( $img );
$c0->draw($img);
$p0->draw($img);
$lsrs->draw($img);

mktitle($map, $img, "                  IEM NEXRAD Base Reflect: $d UTC");
$map->drawLabelCache($img);
mklogolocal($map, $img);

$url = $img->saveWebImage();


?>
<img src="<?php echo $url; ?>">
