<?php
include("../../config/settings.inc.php");
$TITLE = "IEM | Storm Based Warning Stats";
$THISPAGE = "severe-cow";
include("$rootpath/include/forms.php");
include("$rootpath/include/wfoLocs.php");
include("$rootpath/include/database.inc.php");
$postgis = iemdb("postgis");

$year = isset($_GET["year"]) ? $_GET["year"] : date("Y", time()-86400);
$smonth = isset($_GET["smonth"]) ? $_GET["smonth"] : date("m", time()-86400);
$sday = isset($_GET["sday"]) ? $_GET["sday"] : date("d", time()-86400);
$emonth = isset($_GET["emonth"]) ? $_GET["emonth"] : date("m");
$eday = isset($_GET["eday"]) ? $_GET["eday"] : date("d");
$sortby = isset($_GET["sortby"]) ? $_GET["sortby"] : "wfo";
$sts = mktime(0,0,0,$smonth, $sday, $year);
$ets = mktime(0,0,0,$emonth, $eday, $year);

$rs = pg_prepare($postgis, "SELECT", "SELECT wfo, phenomena, count(*),
  sum( st_area2d( transform(geom,2163) ) ) as sum_polysize,
  avg( st_area2d( transform(geom,2163) ) ) as avg_polysize,
  sum( st_perimeter( transform(geom,2163) ) ) as sum_perimsize,
  avg( st_perimeter( transform(geom,2163) ) ) as avg_perimsize
  from warnings_$year WHERE gtype = 'P' and 
  phenomena IN ('SV','TO','MA','FF','FA') and significance = 'W'
  and issue BETWEEN $1 and $2 GROUP by wfo, phenomena ORDER by $sortby ASC");

pg_query($postgis, "SET TIME ZONE 'GMT'");
$rs = pg_execute($postgis, "SELECT", 
    Array( date('Y-m-d', $sts), date('Y-m-d', $ets) ) );

$data = Array();
$sorted = Array();
for ($i=0;$row=@pg_fetch_array($rs,$i);$i++)
{
  if (! array_key_exists($row["wfo"], $data)){ $sorted[] = $row["wfo"]; }
  $data[ $row["wfo"] ][ $row["phenomena"] ."_sum_polysize"] = $row["sum_polysize"];
  $data[ $row["wfo"] ][ $row["phenomena"] ."_sum_perimsize"] = $row["sum_perimsize"];
  $data[ $row["wfo"] ][ $row["phenomena"] ."_avg_polysize"] = $row["avg_polysize"];
  $data[ $row["wfo"] ][ $row["phenomena"] ."_avg_perimsize"] = $row["avg_perimsize"];
  $data[ $row["wfo"] ][ $row["phenomena"] ."_cnt"] = $row["count"];
}

$table = "
<style>
.to  { background: #FFC1C1; }
.sv  { background: #FFFF7E;}
.ma  { background: #A2CD5A;}
.fa { background: #C8F526;}
.ff { background: #FFEC8B;}
</style>
<table border=\"1\" cellpadding=\"3\" cellspacing=\"0\">
<tr>
  <th colspan='2'>Weather Forecast Office</th>
  <th colspan='3'>Summary</th>
  <th colspan='3' class='to'>Tornado</th>
  <th colspan='3' class='sv'>Severe Thunderstorm</th>
  <th colspan='3' class='ma'>Marine</th>
  <th colspan='3' class='ff'>Flash Flood</th>
  <th colspan='3' class='fa'>Areal Flood</th></tr>
<tr>
 <th>ID</th><th>Name</th>
 <th>Cnt</th><th>Permin</th><th>Area</th>
 <th class='to'>Cnt</th><th class='to'>Permin</th><th class='to'>Area</th>
 <th class='sv'>Cnt</th><th class='sv'>Permin</th><th class='sv'>Area</th>
 <th class='ma'>Cnt</th><th class='ma'>Permin</th><th class='ma'>Area</th>
 <th class='ff'>Cnt</th><th class='ff'>Permin</th><th class='ff'>Area</th>
 <th class='fa'>Cnt</th><th class='fa'>Permin</th><th class='fa'>Area</th>
</tr>
";
reset($sorted);
while( list($v,$wfo) = each($sorted) )
{
  $cnt = @$data[$wfo]["TO_cnt"] + @$data[$wfo]["SV_cnt"] +@$data[$wfo]["FA_cnt"] +@$data[$wfo]["FF_cnt"] ;
  $perim = @$data[$wfo]["TO_sum_perimsize"] + 
           @$data[$wfo]["SV_sum_perimsize"] +
           @$data[$wfo]["FA_sum_perimsize"] +
           @$data[$wfo]["FF_sum_perimsize"] ;
  $poly = @$data[$wfo]["TO_sum_polysize"] + 
           @$data[$wfo]["SV_sum_polysize"] +
           @$data[$wfo]["FA_sum_polysize"] +
           @$data[$wfo]["FF_sum_polysize"] ;
  $table .= @sprintf("<tr><td>%s</td><td>%s</td>
         <td>%s</td><td>%.1f</td><td>%.1f</td>
         <td class='to'>%s</td><td class='to'>%.1f</td><td class='to'>%.1f</td>
         <td class='sv'>%s</td><td class='sv'>%.1f</td><td class='sv'>%.1f</td>
         <td class='ma'>%s</td><td class='ma'>%.1f</td><td class='ma'>%.1f</td>
         <td class='ff'>%s</td><td class='ff'>%.1f</td><td class='ff'>%.1f</td>
         <td class='fa'>%s</td><td class='fa'>%.1f</td><td class='fa'>%.1f</td>
          </tr>", $wfo, $wfos[$wfo]['city'], 
          $cnt, $perim/$cnt/1000.0, $poly/$cnt/1000000.0,
$data[$wfo]["TO_cnt"], 
$data[$wfo]["TO_sum_perimsize"]/$data[$wfo]["TO_cnt"]/1000.0,
$data[$wfo]["TO_sum_polysize"]/$data[$wfo]["TO_cnt"]/1000000.0,
$data[$wfo]["SV_cnt"], 
$data[$wfo]["SV_sum_perimsize"]/$data[$wfo]["SV_cnt"]/1000.0,
$data[$wfo]["SV_sum_polysize"]/$data[$wfo]["SV_cnt"]/1000000.0,
$data[$wfo]["MA_cnt"], 
$data[$wfo]["MA_sum_perimsize"]/$data[$wfo]["MA_cnt"]/1000.0,
$data[$wfo]["MA_sum_polysize"]/$data[$wfo]["MA_cnt"]/1000000.0,
$data[$wfo]["FF_cnt"], 
$data[$wfo]["FF_sum_perimsize"]/$data[$wfo]["FF_cnt"]/1000.0,
$data[$wfo]["FF_sum_polysize"]/$data[$wfo]["FF_cnt"]/1000000.0,
$data[$wfo]["FA_cnt"], 
$data[$wfo]["FA_sum_perimsize"]/$data[$wfo]["FA_cnt"]/1000.0,
$data[$wfo]["FA_sum_polysize"]/$data[$wfo]["FA_cnt"]/1000000.0
);
}
$table .= "</table>";

/* BEGIN OUTPUT! */
include("$rootpath/include/header.php"); 
?>
<h3 class="heading">Storm Based Warning Geometry Statistics</h3>

<p>Pick a time period of your choice and get back a summary table of
storm based warning polygon statistics. You should be able to highlight 
this table and paste it into Excel, if you wish.
<br /><strong>Perimeter values are in kilometers and area values in square kilometers.</strong></p>

<?php
echo "<form method=\"GET\">
<table border=\"1\" cellpadding=\"3\" cellspacing='0'>
 <tr><td></td><th>Year</th><th>Month</th><th>Day</th><td></td></tr>
 <tr><td>Start:</td>
  <td rowspan=\"2\">". yearSelect($year, 2005, "year") ."</td>
  <td>". monthSelect($smonth, "smonth") ."</td>
  <td>". daySelect2($sday, "sday") ."</td>
  <td rowspan='2'><input type='submit' value='Generate Stats'></td>
 <tr><td>End:</td>
  <td>". monthSelect($emonth, "emonth") ."</td>
  <td>". daySelect2($eday, "eday") ."</td></tr>
</table>
</form>";


echo $table;

include("$rootpath/include/footer.php"); ?>
