<?php
require_once "../../config/settings.inc.php";
require_once "../../include/myview.php";
$t = new MyView();

require_once "../../include/forms.php";
require_once "../../include/database.inc.php";
require_once "../../include/network.php";
require_once "../../include/imagemaps.php";

$nt = new NetworkTable("WFO");
$nt->table["ALL"] = array("name" => " --- All ---- ", "id" => "ALL", "archive_begin" => null);
require_once "../../include/vtec.php";
$postgis = iemdb('postgis');

$wfo = isset($_GET["wfo"]) ? xssafe($_GET["wfo"]) : 'ALL';
$limit = isset($_GET["limit"]) ? xssafe($_GET["limit"]) : 'TOSV';
$tlimit = isset($_GET["tlimit"]) ? xssafe($_GET["tlimit"]) : '2007';
$lstring = "'SV','TO'";
if ($limit == "TO") {
    $lstring = "'TO'";
} else if ($limit == 'SV') {
    $lstring = "'SV'";
} else if ($limit == 'FF') {
    $lstring = "'FF'";
} else if ($limit == 'MA') {
    $lstring = "'MA'";
}

$tstring = '1980-01-01';
if ($tlimit == '2007') {
    $tstring = '2007-10-01';
} else if ($tlimit == '2011') {
    $tstring = '2011-01-01';
}
$wlimit = "and wfo = $1";
if ($wfo == 'ALL') {
    $wlimit = "and 'ALL' = $1";
}

pg_query($postgis, "SET TIME ZONE 'UTC'");
$rs = pg_prepare($postgis, "SELECTASC", "select round((ST_AREA(ST_Transform(geom,2163)) / 1000000.0)::numeric,2) as area, 
eventid, date(issue), phenomena, significance, wfo from sbw
WHERE status = 'NEW' and phenomena in ($lstring) $wlimit and 
significance = 'W' and issue > '$tstring' and ST_Area(geom) > 0 ORDER by area ASC LIMIT 10");
$rs = pg_prepare($postgis, "SELECTDESC", "select round((ST_AREA(ST_Transform(geom,2163)) / 1000000.0)::numeric,2) as area, 
eventid, date(issue), phenomena, significance, wfo from sbw 
WHERE status = 'NEW' and phenomena in ($lstring) $wlimit and 
significance = 'W' and issue > '$tstring'  ORDER by area DESC LIMIT 10");

$t->title = "NWS SVR/TOR Storm Based Warnings by Size";

$extra = array("ALL" => array("name" => "--- ALL Forecast Offices ---", "id" => "ALL", "archive_begin" => null));
$sselect = networkSelect("WFO", $wfo, $extra, "wfo");

$ar = array(
    "TOSV" => "Tornado + Severe Thunderstorm",
    "TO" => "Tornado Only",
    "SV" => "Severe Thunderstorm Only",
    "FF" => "Flash Flood Only",
    "MA" => "Marine Only"
);

$lselect = make_select("limit", $limit, $ar);

$ar = array(
    "all" => "All Available",
    "2007" => "After 1 Oct 2007",
    "2011" => "After 1 Jan 2011"
);
$tselect = make_select("tlimit", $tlimit, $ar);

$ltable = "";
$rs = pg_execute($postgis, "SELECTDESC", array($wfo));
for ($i = 0; $row = pg_fetch_array($rs); $i++) {

    $url = sprintf(
        "/vtec/#%s-O-%s-K%s-%s-%s-%04d",
        substr($row['date'], 0, 4),
        'NEW',
        $row['wfo'],
        $row["phenomena"],
        $row['significance'],
        $row["eventid"]
    );
    $ltable .= sprintf(
        "<tr><td>%s</td><td>%.0f</td><td>%s</td><td><a href='%s'>%s %s %s</a></td></tr>\n",
        $row['date'],
        $row['area'],
        $row['wfo'],
        $url,
        $vtec_phenomena[$row['phenomena']],
        $vtec_significance[$row["significance"]],
        $row['eventid']
    );
}

$btable = "";
$rs = pg_execute($postgis, "SELECTASC", array($wfo));
for ($i = 0; $row = pg_fetch_array($rs); $i++) {

    $url = sprintf(
        "/vtec/#%s-O-%s-K%s-%s-%s-%04d",
        substr($row['date'], 0, 4),
        'NEW',
        $row['wfo'],
        $row["phenomena"],
        $row['significance'],
        $row["eventid"]
    );
    $btable .= sprintf(
        "<tr><td>%s</td><td>%.2f</td><td>%s</td><td><a href='%s'>%s %s %s</a></td></tr>\n",
        $row['date'],
        $row['area'],
        $row["wfo"],
        $url,
        $vtec_phenomena[$row['phenomena']],
        $vtec_significance[$row["significance"]],
        $row['eventid']
    );
}

$t->content = <<<EOF
<ol class="breadcrumb">
 <li><a href="/current/severe.phtml">Severe Weather Mainpage</a></li>
 <li class="active">Top 10 Warnings by size</li>
</ol>

<h3>Top 10 NWS WFO Storm Based Warnings by Size</h3>

<p>This application prints out a listing of the top 10 largest and smallest
storm based warnings by Weather Forecast Office (WFO). You can click the 
Event ID to get more information on that warning. This page defaults to show the
largest and smallest warnings from any WFO.  Storm Based Warnings did not become
operational until 1 Oct 2007, so warning polygons prior to that date were only
experimental at best.  The areas shown are computed using
<a href="https://epsg.io/2163">EPSG:2163</a> (US National Atlas Equal Area).</p>

<div class="alert alert-info">Please be patient for page to load...</div>

<form name="selector" method="GET">
<table class="table table-condensed table-striped">
<thead>
<tr>
 <th>Select WFO:</th>
 <th>Limit Option:</th>
 <th>Time Period:</th>
<td><td>
<td><td>
</tr>
</head>
<tbody>
<tr><td>
{$sselect}
</td>

 <td>{$lselect}</td>
   <td>{$tselect}</td>
  <td><input type="submit" value="Giveme Giveme!"></td>
  </tr>
</table>
</form>


<h3>Top 10 Largest for WFO: {$wfo}</h3>
<table class="table table-condensed table-striped">
<tr><th>Date Issued</th><th>Size (sq km)</th><th>WFO</th><th>Phenomena</th></tr>
{$ltable}
</table>

<h3>Top 10 Smallest for WFO: {$wfo}</h3>
<table class="table table-condensed table-striped">
<tr><th>Date Issued</th><th>Size (sq km)</th><th>WFO</th><th>Phenomena</th></tr>
{$btable}
</table>
EOF;
$t->render('single.phtml');
