<?php
 include("../../../config/settings.inc.php");


 $network = isset($_GET['network']) ? $_GET['network'] : "IA_ASOS";
 $station1 = isset($_GET['station']) ? strtoupper($_GET['station']) : "";
 $station2 = isset($_GET['station1']) ? strtoupper($_GET['station1']) : "";

 $var = isset($_GET['var']) ? $_GET['var'] : "tmpf";
 include("$rootpath/include/station.php");
 $st = new StationData(Array($station1, $station2));
 $cities = $st->table;


 $uri = "$rooturl/plotting/compare/index.phtml?";
 $ar = Array();
 if (strlen($station1) > 0)
 {
   $ar["station1"] = $station1;
 } if (strlen($station2) > 0)
 {
   $ar["station1"] = $station2;
 }
 if (strlen($station2) > 0)
 {
   $uri = "$rooturl/plotting/compare/index.phtml?station1=$station2";
 }

include("$rootpath/include/google_keys.php");
include("$rootpath/include/imagemaps.php");
include("$rootpath/include/forms.php");
$api = $GOOGLEKEYS[$rooturl]["any"];
$HEADEXTRA = "<script src='http://maps.google.com/maps?file=api&amp;v=2&amp;key=$api'></script>
<script src='http://www.openlayers.org/api/OpenLayers.js'></script>
<script src='${rooturl}/js/olselect.php?network=${network}'></script>";
$BODYEXTRA = "onload=\"init()\"";
$THISPAGE = "iem-qc";
$TITLE = "IEM | Site Comparisons";
include("$rootpath/include/header.php"); 
?>
<style type="text/css">
        #map {
            width: 450px;
            height: 450px;
            border: 2px solid black;
        }
</style>

<h3 class="heading">IEM Site Comparisons</h3>

<p>This application plots a timeseries comparison between two sites of your
choice for a variable of your choice.  If you know the official IDs, you 
can enter them below.  Otherwise use the site selector below to build your
choices. 

<form method="GET" name="re" action="index.phtml">
<table border="1">
<tr><td></td><th>Site Identifier</th><th>Site Name</th><th>Network:</th><td></td></tr>

<tr>
  <th>Station 1:</th>
  <td><input type="text" size="10" name="station" value="<?php echo $station1; ?>"></td>
  <td><?php echo @$cities[$station1]['name']; ?></td>
  <td><?php echo @$cities[$station1]['network']; ?></td>
  <td><a href="index.phtml?station1=<?php echo $station2; ?>&network=<?php echo @$cities[$station1]['network']; ?>">Select from Map</a></td>
</tr>
<tr>
  <th>Station 2:</th>
  <td><input type="text" size="10" name="station1" value="<?php echo $station2; ?>"></td>
  <td><?php echo @$cities[$station2]['name']; ?></td>
  <td><?php echo @$cities[$station2]['network']; ?></td>
  <td><a href="index.phtml?station1=<?php echo $station1; ?>&network=<?php echo @$cities[$station2]['network']; ?>">Select from Map</a></td>
</tr>

<tr><th>Variable:</th><td colspan="3"><SELECT name="var">
<option value="tmpf" <? if ($var == "tmpf") echo "SELECTED"; ?>>Temperature
<option value="dwpf" <? if ($var == "dwpf") echo "SELECTED"; ?>>Dewpoint
<option value="sknt" <? if ($var == "sknt") echo "SELECTED"; ?>>Wind Speed (knots)
<option value="drct" <? if ($var == "drct") echo "SELECTED"; ?>>Wind Direction
<option value="alti" <? if ($var == "alti") echo "SELECTED"; ?>>Altimeter
<option value="phour" <? if ($var == "phour") echo "SELECTED"; ?>>Precip
</SELECT>
</td></tr>

<tr><td colspan="4"><INPUT TYPE="SUBMIT" VALUE="Build Comparison"> <a href="index.phtml">Reset App</a></td></tr>
</table>
</form>

<?php 
if (strlen($station1) == 0 || strlen($station2) == 0)
{
?>
<form name="netselect">
<input type="hidden" name="station1" value="<?php echo $station1; ?>">
<table><tr><th>Select Network</th>
<td><?php echo selectNetwork($network); ?></td>
<td><input type="submit" value="Switch to Network"></td>
</tr></table>
</form>

<p>

<form name="olselect">
<input type="hidden" value="<?php echo $network; ?>" name="network">
<input type="hidden" name="station1" value="<?php echo $station1; ?>">
<table><tr><th>Select Station</th>
<td><?php echo networkSelect($network, ""); ?></td>
<td><input type="submit" value="Select Station"></tr></table>
<div id="map"></div>
<div id="sname" unselectable="on">No site selected</div>
</form>


<?php
} else
{
  echo "<img src='plot.php?var=$var&station1=$station1&station2=$station2'>\n";
  echo "<br /><b>Loading Comparison, please be patient...</b>";
}
?>

<?php include("$rootpath/include/footer.php"); ?>
