<?php
$OL = "6.6.0";
 require_once "../../../config/settings.inc.php";
 require_once "../../../include/mlib.php";
 force_https();
  require_once "../../../include/myview.php";
 require_once "../../../include/forms.php";
 require_once "../../../include/imagemaps.php";
 require_once "../../../include/station.php";
 $t = new MyView();

 $network = isset($_REQUEST['network']) ? xssafe($_REQUEST['network']) : "IA_ASOS";
 $station1 = isset($_GET['station']) ? strtoupper(xssafe($_GET['station'])) : "";
 $station2 = isset($_GET['station1']) ? strtoupper(xssafe($_GET['station1'])) : "";

 $var = isset($_GET['var']) ? xssafe($_GET['var']): "tmpf";
 $st = new StationData(Array($station1, $station2));
 $cities = $st->table;


 $uri = "/plotting/compare/index.phtml?";
 $ar = Array();
 if (strlen($station1) > 0)
 {
   $ar["station1"] = $station1;
 } else {
 	$cities[""]["name"] = "";
 	$cities[""]["network"] = "";
 }
 
 if (strlen($station2) > 0)
 {
   $ar["station1"] = $station2;
   $uri = "/plotting/compare/index.phtml?station1=$station2";
 }else{
 	$cities[""]["name"] = "";
 	$cities[""]["network"] = "";
 }

$t->headextra = <<<EOF
<link rel="stylesheet" href="/vendor/openlayers/{$OL}/ol.css" type="text/css">
<link type="text/css" href="/vendor/openlayers/{$OL}/ol-layerswitcher.css" rel="stylesheet" />
<link rel="stylesheet" type="text/css" href="/vendor/select2/4.0.3/select2.min.css"/ >
EOF;
$t->jsextra = <<<EOF
<script src="/vendor/openlayers/{$OL}/ol.js" type="text/javascript"></script>
<script src='/vendor/openlayers/{$OL}/ol-layerswitcher.js'></script>
<script src="/js/olselect.php?network=${network}"></script>
<script src="/vendor/select2/4.0.3/select2.min.js"></script>
<script type="text/javascript">
$(document).ready(function(){
	$(".iemselect2").select2();	
});
</script>
EOF;
$t->title = "Site Comparisons";

$ar = Array("tmpf" => "Temperature",
"dwpf" => "Dew Point",
"sknt" => "Wind Speed (knots)",
"drct" => "Wind Direction",
"alti" => "Pressure Altimeter",
"phour" => "Hourly Precipitation");
$vselect = make_select("var", $var, $ar);

$content = <<<EOF
<style type="text/css">
        #map {
            width: 450px;
            height: 450px;
            border: 2px solid black;
        }
</style>

<h3>IEM Site Comparisons</h3>

<p><strong>17 Feb 2022 Deprecation Notice</strong> This page is more clunky then a typical
IEM page and uses obsolete technology.  I'd like to remove it at some point, but
let me know akrherz@iastate.edu if you want it kept around.
<a href="/plotting/auto/?q=174">Autoplot 174</a> and
<a href="/plotting/auto/?q=54">Autoplot 54</a> are likely more useful
for a comparison purpose than this page!</p>

<p>This application plots a timeseries comparison between two sites of your
choice for a variable of your choice.  If you know the official IDs, you 
can enter them below.  Otherwise use the site selector below to build your
choices. 

<form method="GET" name="re" action="index.phtml">
<table border="1">
<tr><td></td><th>Site Identifier</th><th>Site Name</th><th>Network:</th><td></td></tr>

<tr>
  <th>Station 1:</th>
  <td><input type="text" size="10" name="station" value="{$station1}"></td>
  <td>{$cities[$station1]['name']}</td>
  <td>{$cities[$station1]['network']}</td>
  <td><a href="index.phtml?station1={$station2}&network={$cities[$station1]['network']}">Select from Map</a></td>
</tr>
<tr>
  <th>Station 2:</th>
  <td><input type="text" size="10" name="station1" value="{$station2}"></td>
  <td>{$cities[$station2]['name']}</td>
  <td>{$cities[$station2]['network']}</td>
  <td><a href="index.phtml?station1={$station1}&network={$cities[$station2]['network']}">Select from Map</a></td>
</tr>

<tr><th>Variable:</th><td colspan="3">
{$vselect}
</td></tr>

<tr><td colspan="4"><INPUT TYPE="SUBMIT" VALUE="Build Comparison"> <a href="index.phtml">Reset App</a></td></tr>
</table>
</form>
EOF;
$nselect = selectNetwork($network);
$sselect = networkSelect($network, $station1);
if (strlen($station1) == 0 || strlen($station2) == 0)
{
$content .= <<<EOF
	<form name="netselect">
<input type="hidden" name="station1" value="{$station1}">
<table><tr><th>Select Network</th>
<td>{$nselect}</td>
<td><input type="submit" value="Switch to Network"></td>
</tr></table>
</form>

<p>

<form name="olselect">
<input type="hidden" value="{$network}" name="network">
<input type="hidden" name="station1" value="{$station1}">
<table><tr><th>Select Station</th>
<td>{$sselect}</td>
<td><input type="submit" value="Select Station"></tr></table>
<div id="map"></div>
</form>

EOF;
} else
{
$content .= <<<EOF
<img src="plot.php?var={$var}&station1={$station1}&station2={$station2}" />
<br /><b>Loading Comparison, please be patient...</b>
EOF;
}

$t->content = $content;
$t->render('single.phtml');
