<?php
 $id = intval($_GET["id"]);
 $TITLE = "IEM | News & Notes";
 include("/mesonet/php/include/header.php");
?>
<b>Nav:</b> <a href="/index.php">Homepage</a> &nbsp; <b> > </b> &nbsp; News & Notes

<br><br>

<?php
  if ($id > 0) echo "<b>News ID#: $id </b><br><a href=\"news.phtml\">View Last Ten</a><br>";
  else echo "<h4>10 most recent posts:</h4>";
  // Here is where we start pulling station Information

  $connection = pg_connect("10.10.10.40","5432","mesosite");
  if ($id > 0) {
    $q = "SELECT *, to_char(entered, 'YYYY-MM-DD HH:MI AM') as webdate 
           from news WHERE id = $id ";
    pg_exec($connection, "UPDATE news SET views = views + 1 WHERE id = $id");
  } else {
    $q = "SELECT *, to_char(entered, 'YYYY-MM-DD HH:MI AM') as webdate 
           from news ORDER by entered DESC LIMIT 10";
  }
  $result = pg_exec($connection, $q);
  $count = pg_numrows($result);
?>
<p><br><table>
<?php
  if ($count > 0 ){
    for( $i=0; $row = @pg_fetch_array($result,$i); $i++) 
    { 
       echo "<tr><th class=\"even\">Title:</th><td><b>". $row["title"] ."</b></td></tr>\n";
       echo "<tr><th class=\"even\">Author:</th><td><b>". $row["author"] ."</b></td></tr>\n";
       echo "<tr><th class=\"even\">Posted On:</th><td><b>". $row["webdate"] ."</b></td></tr>\n";
       echo "<tr><th class=\"even\">Views:</th><td><b>". $row["views"] ."</b></td></tr>\n";
     if (strlen($row["url"]) > 0)
       echo "<tr><th class=\"even\">Link:</th><td><a href=\"". $row["url"] ."\">". $row["url"] ."</a></td></tr>\n";

       echo "<tr><td></td><td><blockquote><pre>". $row["body"] ."</pre></blockquote></td></tr>";
    } // End of for

  } else {
    echo "No news is good news.";
  }

?>
</table>


<BR><BR>


</TD></TR>

<?php include("/mesonet/php/include/footer.php"); ?>
