<?php
 include("../../config/settings.inc.php");
 include("$rootpath/include/database.inc.php");
 $dbconn = iemdb("mesosite");

 $id = isset($_GET["id"]) ? intval($_GET["id"]): 0;
 $q = isset($_GET["q"]) ? pg_escape_string($_GET["q"]) : "";
 $TITLE = "IEM | News & Notes";
 $THISPAGE = "iem-news";
 include("$rootpath/include/header.php");

$rs = pg_prepare($dbconn, "SELECTONE", "SELECT *, 
      to_char(entered, 'YYYY-MM-DD HH:MI AM') as webdate 
      from news WHERE id = $1");
$rs = pg_prepare($dbconn, "READS", "UPDATE news SET views = views + 1 
      WHERE id = $1");
$rs = pg_prepare($dbconn, "SEARCH", "SELECT *, 
      to_char(entered, 'YYYY-MM-DD HH:MI AM') as webdate 
      from news WHERE (title ~* $1 or body ~* $1) 
      ORDER by entered DESC");

?>

<p><form method="GET" action="news.phtml" name="searchnews">
<b>Search Archive:</b> <input type="text" name="q" value="<?php echo $q; ?>" size="20"><input type="submit" value="Go!">
</form>

<?php

  if ($id > 0) {
    pg_execute($dbconn, "READS", Array($id) );
    $result = pg_execute($dbconn, "SELECTONE", Array($id) );
  } else if ($q != "") {
    $result = pg_execute($dbconn, "SEARCH", Array($q) );
  } else if ($id == 0) {
    $q = "SELECT *, to_char(entered, 'YYYY-MM-DD HH:MI AM') as webdate 
           from news ORDER by entered DESC LIMIT 1";
    $result = pg_exec($dbconn, $q);
  }

if (pg_numrows($result) == 1 && $id > 0){
  $prev = $id -1;
  $next = $id +1;
  echo "<a rel=\"nofollow\" href=\"news.phtml?id=$prev\">&lt;&lt; Previous</a> &nbsp; &nbsp; &nbsp;";
  echo "<a rel=\"nofollow\" href=\"news.phtml?id=$next\">Next &gt;&gt;</a>\n";

}

for( $i=0; $row = @pg_fetch_array($result,$i); $i++) 
{ 
  $id = $row["id"];
  echo "<h3 style=\"border-top: 2px solid #00f;\">". $row["title"] ."</h3>\n";
  echo "<i>Posted On:</i> ". $row["webdate"] ." &nbsp; &nbsp; &nbsp;";
  echo "<i>Author:</i> ". $row["author"] ." &nbsp; &nbsp; &nbsp;";
  echo "<i>Views:</i> ". $row["views"] ;
  if (strlen($row["url"]) > 0) {
     echo "<br /><i>Link:</i> <a href=\"". $row["url"] ."\">". $row["url"] ."</a>\n";
  }
  if ($id < 830) {
    echo "<br /><blockquote><pre>". $row["body"] ."</pre></blockquote>";
  } else {
    echo "<br />". $row["body"] ."<br />";
  }

} // End of for

  if (pg_numrows($result) == 0) {
    echo "<p>Search parameters yielded no results, oopsy!</p>";
  }
include("$rootpath/include/footer.php"); 
?>
