<?php
 /* storm/edit.phtml */

include_once("../../../config/settings.inc.php");
include("$rootpath/include/database.inc.php");
$pg = iemdb("squaw");
include_once("$rootpath/include/squaw/scenario.inc.php");
include_once("$rootpath/include/squaw/constants.inc.php");
include_once("$rootpath/include/squaw/forms.inc.php");


$id = isset($_GET["id"]) ? $_GET["id"] : -1;
$id = intval($id) or die("Error: Type of ID is incorrect, must be an int");
$mode = isset($_GET["mode"]) ? $_GET["mode"] : '';

$mystorm = new scenario($id);
$mystorm->processCGI($_GET);
if ($id >= 0)
{
	$myform = $mystorm->htmlEditor();
}
else 
{
	$myform = $mystorm->initStormEditor();
}
?>
<?php $THISPAGE = "storm"; include("$rootpath/include/squaw/header.inc.php"); ?>

<div id="content">

<?php if ( isset($mystorm->message) )
{ ?>
<div style="background: #ff0; border: 1px #000 solid;"><b>Message:</b><?php echo $mystorm->message; ?></div>
<?php } ?>

<b>Commands:</b>  <a href="edit.phtml">Create New Storm</a>  | <a href="del.phtml?id=<?php echo $id; ?>">Delete This Storm</a>

<form method="GET" action="edit.phtml" name="estorm">

<?php echo $myform; ?>

<p><input type="submit" value="Save Changes">
<input type="reset" value="Reset Form">
</form>

</div>

<?php include("$rootpath/include/footer.php"); ?>
