<?php
require_once '../../config/settings.inc.php';
define("IEM_APPID", 58);
require_once '../../include/myview.php';

$t = new MyView();
$t->title = "Drought Monitoring Products";
$startyear = intval(date("Y"));
if (intval(date("m")) < 10) {
    $startyear -= 1;
}
$departureplot = sprintf(
    "/plotting/auto/plot/97/sector:IA::var:precip_depart" .
        "::date1:%s-10-01::usdm:no::date2:%s::dpi:100.png",
    $startyear,
    date("Y-m-d")
);


$t->content = <<<EOF
<h3>Drought Monitoring Products</h3>

<div class="row">
<div class="col-md-6">

<p><b>Current Drought Monitor:</b>

<img src="http://droughtmonitor.unl.edu/data/png/current/current_ia_trd.png" class="img img-responsive">

<br />The <a href="http://droughtmonitor.unl.edu/">US Drought Monitor</a> website is a wonderful
resource for drought information.</p>


<p><b>IEM Relevant Autoplots Apps</b>
<br />The "IEM Autoplot" applications are dynamically generated plots that also
offer the raw data behind the plot as well.
<ul>
 <li><a href="/plotting/auto/?q=84">Gridded Precip Estimates/Departures (#84)</a></li>
 <li><a href="/plotting/auto/?q=97">Station Precip Estimates/Departures (#97)</a></li>
 <li><a href="/plotting/auto/?q=142">Station Trailing Days Timeseries (#142)</a></li>
 <li><a href="/plotting/auto/?q=194">US Drought Monitor Time Duration Maps (#194)</a></li>
</ul>

<p><b>Statements:</b>
<ul>
  <li><a href="http://www.cpc.ncep.noaa.gov/products/predictions/experimental/edb/droughtblend-access-page.html">Drought Blends</a> [CPC]</li>
</ul>

<p><b>Soil Moisture Status:</b>
<ul>
 <li><a href="http://www.cpc.ncep.noaa.gov/soilmst/img/curr.w.anom.daily.gif">Calculated Soil Moisture Anomaloy</a> [CPC]</li>
</ul>

<p><b>Ground Water Status:</b>
<ul>
 <li><a href="http://groundwaterwatch.usgs.gov/">USGS Ground Water Watch</a></li>
</ul>

</div>
<div class="col-md-6">

<p><strong>Water Year (October 1 - Today)</strong>

<p>The "Water Year" is typically defined to start on October 1<sup>rst</sup> and represents the
time when new water received goes to help the next year's growing season.</p>

<p><b>Precipitation Departures:</b>

<img src="{$departureplot}" class="img img-responsive"/>

<br /><a href="/plotting/auto/?q=97" class="btn btn-default">Generate More Plots Like this</a></p>


<p><b>Rainfall Status:</b>
<ul>
 <li><a href="http://www.cpc.ncep.noaa.gov/soilmst/img/curr.p.full.daily.gif">This month's rainfall</a> [CPC] </li>
 <li><a href="http://www.cpc.ncep.noaa.gov/soilmst/img/curr.p.anom.daily.gif">This month's rainfall anomaly</a> [CPC] </li>
 <li><a href="https://legacy.climate.ncsu.edu/water/map/">Interactive Maps of Departures</a>
<br /><span class="badge">Recommended</span> Excellent website providing summaries of precip
and US Drought Monitor status.</li>
 <li><a href="http://www.wrcc.dri.edu/spi/spi.html">Standardized Precipitation Index</a> [WRCC]</li>
</ul>

<p><b>Misc:</b>
<ul>
 <li><a href="https://www.esrl.noaa.gov/psd/eddi/">Evaporative Demand Drought Index (EDDI)</a></li>
 <li><a href="http://drought.eng.uci.edu/">Global Integrated Drought Monitoring and Prediction System</a></li>
 <li><a href="http://www.cdc.noaa.gov/~gtb/tele/pna.gif">PNA trends</a> [CDC] </li>
</ul>

<p><b>Websites referenced:</b>
<ul>
 <li><a href="http://www.cpc.ncep.noaa.gov/">Climate Prediction Center, NOAA</a></li>
 <li><a href="http://ndmc.unl.edu/">National Drought Mitigation Center, UNL</a></li>
 <li><a href="http://www.wrcc.dri.edu/">Western Regional Climate Center</a></li>
</ul>

</div>
</div>

<p>Please <a href="/info/contacts.php">contact us</a> if you have links you would like added on this page.
EOF;
$t->render('single.phtml');
