<?php
include("../../config/settings.inc.php");
$TITLE = "IEM | Drought Monitoring Products";
$THISPAGE = "climatology-drought";
include("$rootpath/include/header.php");
?>

<h3 class="heading">Drought Monitoring Products</h3>

<p class="intro">Here is a listing of resources related to drought 
monitoring.</p>

<table><tr><td>

<p><b>Drought Monitors:</b>
<ul>
 <li><a href="http://www.drought.unl.edu/dm/drmon.gif">US Drought Monitor</a> [NDMC]</li>
 <li><a href="http://www.wrcc.dri.edu/spi/spi.html">Standardized Precipitation Index</a> [WRCC]</li>
</ul>

<p><b>Statements:</b>
<ul>
  <li><a href="http://www.cpc.ncep.noaa.gov/products/predictions/experimental/edb/droughtblend-access-page.html">Drought Blends</a> [CPC]</li>
</ul>

<p><b>Soil Moisture Status:</b>
<ul>
 <li><a href="http://www.cpc.ncep.noaa.gov/soilmst/img/curr.w.anom.daily.gif">Calculated Soil Moisture Anomaloy</a> [CPC]</li>
</ul>

<p><b>Ground Water Status:</b>
<ul>
 <li><a href="http://groundwaterwatch.usgs.gov/">USGS Ground Water Watch</a></li>
</ul>

<p><b>Rainfall Status:</b>
<ul>
 <li><a href="http://www.cpc.ncep.noaa.gov/soilmst/img/curr.p.full.daily.gif">This month's rainfall</a> [CPC] </li>
 <li><a href="http://www.cpc.ncep.noaa.gov/soilmst/img/curr.p.anom.daily.gif">This month's rainfall anomaly</a> [CPC] </li>
</ul>

<p><b>Misc:</b>
<ul>
 <li><a href="http://www.cdc.noaa.gov/~gtb/tele/pna.gif">PNA trends</a> [CDC] </li>
</ul>

<p><b>Websites referenced:</b>
<ul>
 <li><a href="http://www.cpc.ncep.noaa.gov/">Climate Prediction Center, NOAA</a></li>
 <li><a href="http://ndmc.unl.edu/">National Drought Mitigation Center, UNL</a></li>
 <li><a href="http://www.wrcc.dri.edu/">Western Regional Climate Center</a></li>
</ul>

</td><td valign="TOP"> 


</td></tr></table>

<p>Please <a href="/info/contacts.php">contact us</a> if you have links you would like added on this page.

<?php include("$rootpath/include/footer.php"); ?>
