<?php
include("../../config/settings.inc.php");
$TITLE = "IEM | Drought Monitoring Products";
$THISPAGE = "climatology-drought";
include("$rootpath/include/header.php");
?>

<h3>Drought Monitoring Products</h3>

<p class="intro">Here is a listing of resources produced on the IEM website
and other websites that provide updates on the current drought monitoring 
situation.</p>

<table><tr><td>

<p><b>Drought Monitors:</b>
<ul>
 <li><a href="http://www.drought.unl.edu/dm/2005/drmon.gif">US Drought Monitor</a> [NDMC]</li>
 <li><a href="http://www.wrcc.dri.edu/spi/spi.html">Standardized Precipitation Index</a> [WRCC]</li>
</ul>

<p><b>Statements:</b>
<ul>
  <li><a href="/reports/2003/October/031010_1_nws.txt">NWS Des Moines Hydrologic Outlook (10 Oct 2003)</a></li>
  <li><a href="/reports/2003/October/031009_1_nws.txt">NWS LaCrosse Hydrologic Outlook (09 Oct 2003)</a></li>
  <li><a href="http://www.cpc.ncep.noaa.gov/products/predictions/experimental/edb/droughtblend-access-page.html">Drought Blends</a> [CPC]</li>
</ul>

<p><b>Soil Moisture Status:</b>
<ul>
 <li><a href="http://www.cpc.ncep.noaa.gov/soilmst/img/curr.w.anom.daily.gif">Calculated Soil Moisture Anomaloy</a> [CPC]</li>
</ul>

<p><b>Ground Water Status:</b>
<ul>
 <li><a href="http://groundwaterwatch.usgs.gov/">USGS Ground Water Watch</a></li>
</ul>

<p><b>Rainfall Status:</b>
<ul>
 <li><a href="http://www.cpc.ncep.noaa.gov/soilmst/img/curr.p.full.daily.gif">This month's rainfall</a> [CPC] </li>
 <li><a href="http://www.cpc.ncep.noaa.gov/soilmst/img/curr.p.anom.daily.gif">This month's rainfall anomaly</a> [CPC] </li>
</ul>

<p><b>Misc:</b>
<ul>
 <li><a href="http://www.cdc.noaa.gov/~gtb/tele/pna.gif">PNA trends</a> [CDC] </li>
</ul>

<p><b>Websites referenced:</b>
<ul>
 <li><a href="http://www.cpc.ncep.noaa.gov/">Climate Prediction Center, NOAA</a></li>
 <li><a href="http://ndmc.unl.edu/">National Drought Mitigation Center, UNL</a></li>
 <li><a href="http://www.wrcc.dri.edu/">Western Regional Climate Center</a></li>
</ul>

</td><td valign="TOP"> 

<b>Status Reports:</b><br>

 <table>
  <tr bgcolor="#EEEEEE"><th>Pasture & Range Land Status</th></tr>
  <tr><td><i>Updated: 14 Aug 2005</i>
    <br><i>Author: Richard Tinker, NOAA</i>
    <br>
     <table border=1>
       <tr><td>Good or Excellent:</td><td>30%</td></tr>
       <tr><td>Poor or Very Poor:</td><td>40%</td></tr>
     </table>
  </td></tr>
 </table>

</td></tr></table>

<p>Please <a href="/info/contacts.php">contact us</a> if you have links you would like added on this page.

<?php include("$rootpath/include/footer.php"); ?>
