
-- Boilerplate IEM schema_manager_version, the version gets incremented each
-- time we make an upgrade script
CREATE TABLE iem_schema_manager_version(
	version int,
	updated timestamptz);
INSERT into iem_schema_manager_version values (10, now());

CREATE TABLE sm_daily (
  station char(5),
  valid date,
  TAir_C_Avg real,
  TAir_C_Max real,
  TAir_C_TMx timestamp with time zone,
  TAir_C_Min real,
  TAir_C_TMn timestamp with time zone,
  SlrMJ_Tot real,
  Rain_mm_Tot real,
  WS_mps_S_WVT real,
  WindDir_D1_WVT real,
  WindDir_SD1_WVT real,
  WS_mps_Max real,
  WS_mps_TMx timestamp with time zone,
  DailyET real,
  TSoil_C_Avg real,
  VWC_12_Avg real,
  VWC_24_Avg real,
  VWC_50_Avg real,
  EC12 real,
  EC24 real,
  EC50 real,
  T12_C_Avg real,
  T24_C_Avg real,
  T50_C_Avg real,
  PA real,
  PA_2 real,
  PA_3 real,
  T06_C_Avg real,
  VWC_06_Avg real,
  ec06 real,
  pa06 real,
  pa12 real,
  pa24 real,
  pa50 real,
  t107_1_avg real,
  t107_2_avg real,
  t107_3_avg real,
  encrh_avg real,
  nancounttot real,
    tair_c_avg_f character(1),
    tair_c_avg_qc real,
    tair_c_max_f character(1),
    tair_c_max_qc real,
    tair_c_tmx_f character(1),
    tair_c_tmx_qc timestamp with time zone,
    tair_c_min_f character(1),
    tair_c_min_qc real,
    tair_c_tmn_f character(1),
    tair_c_tmn_qc timestamp with time zone,
    slrmj_tot_f character(1),
    slrmj_tot_qc real,
    rain_mm_tot_f character(1),
    rain_mm_tot_qc real,
    ws_mps_s_wvt_f character(1),
    ws_mps_s_wvt_qc real,
    winddir_d1_wvt_f character(1),
    winddir_d1_wvt_qc real,
    winddir_sd1_wvt_f character(1),
    winddir_sd1_wvt_qc real,
    ws_mps_max_f character(1),
    ws_mps_max_qc real,
    ws_mps_tmx_f character(1),
    ws_mps_tmx_qc timestamp with time zone,
    WS_mph_TMx timestamp with time zone,
    ws_mph_tmx_f character(1),
    ws_mph_tmx_qc timestamp with time zone,
    dailyet_f character(1),
    dailyet_qc real,
    tsoil_c_avg_f character(1),
    tsoil_c_avg_qc real,
    vwc_12_avg_f character(1),
    vwc_12_avg_qc real,
    vwc_24_avg_f character(1),
    vwc_24_avg_qc real,
    vwc_50_avg_f character(1),
    vwc_50_avg_qc real,
    ec12_f character(1),
    ec12_qc real,
    ec24_f character(1),
    ec24_qc real,
    ec50_f character(1),
    ec50_qc real,
    t12_c_avg_f character(1),
    t12_c_avg_qc real,
    t24_c_avg_f character(1),
    t24_c_avg_qc real,
    t50_c_avg_f character(1),
    t50_c_avg_qc real,
    pa_f character(1),
    pa_qc real,
    pa_2_f character(1),
    pa_2_qc real,
    pa_3_f character(1),
    pa_3_qc real,
    t06_c_avg_f character(1),
    t06_c_avg_qc real,
    vwc_06_avg_f character(1),
    vwc_06_avg_qc real,
    ec06_f character(1),
    ec06_qc real,
    pa06_f character(1),
    pa06_qc real,
    pa12_f character(1),
    pa12_qc real,
    pa24_f character(1),
    pa24_qc real,
    pa50_f character(1),
    pa50_qc real,
    t107_1_avg_f character(1),
    t107_1_avg_qc real,
    t107_2_avg_f character(1),
    t107_2_avg_qc real,
    t107_3_avg_f character(1),
    t107_3_avg_qc real,
    encrh_avg_f character(1),
    encrh_avg_qc real,
    nancounttot_f character(1),
    nancounttot_qc real,
    calc_vwc_06_avg real,
    calc_vwc_06_avg_qc real,
    calc_vwc_06_avg_f char(1),
    calc_vwc_12_avg real,
    calc_vwc_12_avg_qc real,
    calc_vwc_12_avg_f char(1),
    calc_vwc_24_avg real,
    calc_vwc_24_avg_qc real,
    calc_vwc_24_avg_f char(1),
    calc_vwc_50_avg real,
    calc_vwc_50_avg_qc real,
    calc_vwc_50_avg_f char(1),
        lwmv_1 real,
    lwmv_1_qc real,
    lwmv_1_f character(1),
    lwmv_2 real,
    lwmv_2_qc real,
    lwmv_2_f character(1),
    lwmdry_1_tot real,
    lwmdry_1_tot_qc real,
    lwmdry_1_tot_f character(1),
    lwmcon_1_tot real,
    lwmcon_1_tot_qc real,
    lwmcon_1_tot_f character(1),
    lwmwet_1_tot real,
    lwmwet_1_tot_qc real,
    lwmwet_1_tot_f character(1),
    lwmdry_2_tot real,
    lwmdry_2_tot_qc real,
    lwmdry_2_tot_f character(1),
    lwmcon_2_tot real,
    lwmcon_2_tot_qc real,
    lwmcon_2_tot_f character(1),
    lwmwet_2_tot real,
    lwmwet_2_tot_qc real,
    lwmwet_2_tot_f character(1),
    bpres_avg real,
    bpres_avg_qc real,
    bpres_avg_f character(1),
    rh_avg real,
    rh_avg_qc real,
    rh_avg_f character(1),
    ws_mph real,
    ws_mph_qc real,
    ws_mph_f character(1),
    etapples real,
    etapples_qc real,
    etappls_f character(1),
    ws_mph_max real,
    ws_mph_max_qc real,
    ws_mph_max_f character(1),
    rain_mm_2_tot real,
    rain_mm_2_tot_qc real,
    rain_mm_2_tot_f character(1),
  VWC_AVG2in real,
VWC_AVG2in_qc real,
VWC_AVG2in_f char(1),
EC_2in real,
EC_2in_qc real,
EC_2in_f char(1),
Temp_AVG2in real,
Temp_AVG2in_qc real,
Temp_AVG2in_f char(1),
VWC_AVG4in real,
VWC_AVG4in_qc real,
VWC_AVG4in_f char(1),
EC_4in real,
EC_4in_qc real,
EC_4in_f char(1),
Temp_AVG4in real,
Temp_AVG4in_qc real,
Temp_AVG4in_f char(1),
VWC_AVG8in real,
VWC_AVG8in_qc real,
VWC_AVG8in_f char(1),
EC_8in real,
EC_8in_qc real,
EC_8in_f char(1),
Temp_AVG8in real,
Temp_AVG8in_qc real,
Temp_AVG8in_f char(1),
VWC_AVG12in real,
VWC_AVG12in_qc real,
VWC_AVG12in_f char(1),
EC_12in real,
EC_12in_qc real,
EC_12in_f char(1),
Temp_AVG12in real,
Temp_AVG12in_qc real,
Temp_AVG12in_f char(1), 
VWC_AVG16in real,
VWC_AVG16in_qc real,
VWC_AVG16in_f char(1),
EC_16in real,
EC_16in_qc real,
EC_16in_f char(1),
Temp_AVG16in real,
Temp_AVG16in_qc real,
Temp_AVG16in_f char(1),
VWC_AVG20in real,
VWC_AVG20in_qc real,
VWC_AVG20in_f char(1),
EC_20in real,
EC_20in_qc real,
EC_20in_f char(1),
Temp_AVG20in real,
Temp_AVG20in_qc real,
Temp_AVG20in_f char(1),
lwmdry_lowbare_tot real,
lwmdry_lowbare_tot_qc real,
lwmdry_lowbare_tot_f char(1),
lwmcon_lowbare_tot real,
lwmcon_lowbare_tot_qc real,
lwmcon_lowbare_tot_f char(1),
lwmwet_lowbare_tot real,
lwmwet_lowbare_tot_qc real,
lwmwet_lowbare_tot_f char(1),
lwmdry_highbare_tot real,
lwmdry_highbare_tot_qc real,
lwmdry_highbare_tot_f char(1),
lwmcon_highbare_tot real,
lwmcon_highbare_tot_qc real,
lwmcon_highbare_tot_f char(1),
lwmwet_highbare_tot real,
lwmwet_highbare_tot_qc real,
lwmwet_highbare_tot_f char(1),
obs_count int
);
CREATE UNIQUE index sm_daily_idx on sm_daily(station, valid);
GRANT SELECT on sm_daily to nobody;

--- Soil Moisture Stations
CREATE TABLE sm_hourly (
  station char(5),
  valid timestamp with time zone,
  -- max air temp
  tair_c_max real,
  tair_c_max_qc real,
  tair_c_max_f char(1),

  -- min air temp
  tair_c_min real,
  tair_c_min_qc real,
  tair_c_min_f char(1),

  TAir_C_Avg real,
  RH real,
  SlrkW_Avg real,
  SlrMJ_Tot real,
  Rain_mm_Tot real,
  WS_mps_S_WVT real,
  WindDir_D1_WVT real,
  WindDir_SD1_WVT real,
  ETAlfalfa real,
  ETApples real,
  ETApples_qc real,
  ETApples_f char(1),
  SolarRadCalc real,
  TSoil_C_Avg real,
  VWC_12_Avg real,
  VWC_24_Avg real,
  VWC_50_Avg real,
  EC12 real,
  EC24 real,
  EC50 real,
  T12_C_Avg real,
  T24_C_Avg real,
  T50_C_Avg real,
  PA real,
  PA_2 real,
  PA_3 real,
  VWC_06_Avg real,
  T06_C_Avg real,
  ec06 real,
  pa06 real,
  pa12 real,
  pa24 real,
  pa50 real,
  p06outofrange real,
  p12outofrange real,
  p24outofrange real,
  p50outofrange real,
  tairnans_tot real,
  rhnans_tot real,
  ws_mph_max real,
  ws_mph_tmx timestamptz,
  encrh_avg real,
  outofrange06 real,
  outofrange12 real,
  outofrange24 real,
  outofrange50 real,
  battv_min real,
    tair_c_avg_f character(1),
    tair_c_avg_qc real,
    rh_f character(1),
    rh_qc real,
    slrkw_avg_f character(1),
    slrkw_avg_qc real,
    slrmj_tot_f character(1),
    slrmj_tot_qc real,
    rain_mm_tot_f character(1),
    rain_mm_tot_qc real,
    ws_mps_s_wvt_f character(1),
    ws_mps_s_wvt_qc real,
    winddir_d1_wvt_f character(1),
    winddir_d1_wvt_qc real,
    winddir_sd1_wvt_f character(1),
    winddir_sd1_wvt_qc real,
    etalfalfa_f character(1),
    etalfalfa_qc real,
    solarradcalc_f character(1),
    solarradcalc_qc real,
    tsoil_c_avg_f character(1),
    tsoil_c_avg_qc real,
    vwc_12_avg_f character(1),
      vwc_12_avg_qc real,
    vwc_24_avg_f character(1),
    vwc_24_avg_qc real,
    vwc_50_avg_f character(1),
    vwc_50_avg_qc real,
    ec12_f character(1),
    ec12_qc real,
    ec24_f character(1),
    ec24_qc real,
    ec50_f character(1),
    ec50_qc real,
    t12_c_avg_f character(1),
    t12_c_avg_qc real,
    t24_c_avg_f character(1),
    t24_c_avg_qc real,
    t50_c_avg_f character(1),
    t50_c_avg_qc real,
    pa_f character(1),
    pa_qc real,
    pa_2_f character(1),
    pa_2_qc real,
    pa_3_f character(1),
    pa_3_qc real,
    t06_c_avg_f character(1),
    t06_c_avg_qc real,
    vwc_06_avg_f character(1),
    vwc_06_avg_qc real,
    ec06_f character(1),
    ec06_qc real,
    pa06_f character(1),
    pa06_qc real,
    pa12_f character(1),
    pa12_qc real,
    pa24_f character(1),
    pa24_qc real,
    pa50_f character(1),
    pa50_qc real,
    t107_1_f character(1),
    t107_1_qc real,
    t107_2_f character(1),
    t107_2_qc real,
      t107_3_f character(1),
    t107_3_qc real,
    battv_min_f character(1),
    battv_min_qc real,
    p06outofrange_f character(1),
    p06outofrange_qc real,
    p12outofrange_f character(1),
    p12outofrange_qc real,
    p24outofrange_f character(1),
    p24outofrange_qc real,
    p50outofrange_f character(1),
    p50outofrange_qc real,
    tairnans_tot_f character(1),
    tairnans_tot_qc real,
    rhnans_tot_f character(1),
    rhnans_tot_qc real,
    ws_mph_max_f character(1),
    ws_mph_max_qc real,
    ws_mph_tmx_f character(1),
    ws_mph_tmx_qc timestamp with time zone,
    encrh_avg_f character(1),
    encrh_avg_qc real,
    outofrange06_f character(1),
    outofrange06_qc real,
    outofrange12_f character(1),
    outofrange12_qc real,
    outofrange24_f character(1),
    outofrange24_qc real,
    outofrange50_f character(1),
    outofrange50_qc real,
    calc_vwc_06_avg real,
    calc_vwc_06_avg_qc real,
    calc_vwc_06_avg_f char(1),
    calc_vwc_12_avg real,
    calc_vwc_12_avg_qc real,
    calc_vwc_12_avg_f char(1),
    calc_vwc_24_avg real,
    calc_vwc_24_avg_qc real,
    calc_vwc_24_avg_f char(1),
    calc_vwc_50_avg real,
    calc_vwc_50_avg_qc real,
    calc_vwc_50_avg_f char(1),
        lwmv_1 real,
    lwmv_1_qc real,
    lwmv_1_f character(1),
    lwmv_2 real,
    lwmv_2_qc real,
    lwmv_2_f character(1),
    lwmdry_1_tot real,
    lwmdry_1_tot_qc real,
    lwmdry_1_tot_f character(1),
    lwmcon_1_tot real,
    lwmcon_1_tot_qc real,
    lwmcon_1_tot_f character(1),
    lwmwet_1_tot real,
    lwmwet_1_tot_qc real,
    lwmwet_1_tot_f character(1),
    lwmdry_2_tot real,
    lwmdry_2_tot_qc real,
    lwmdry_2_tot_f character(1),
    lwmcon_2_tot real,
    lwmcon_2_tot_qc real,
    lwmcon_2_tot_f character(1),
    lwmwet_2_tot real,
    lwmwet_2_tot_qc real,
    lwmwet_2_tot_f character(1),
    bpres_avg real,
    bpres_avg_qc real,
    bpres_avg_f character(1),
    rain_mm_2_tot real,
    rain_mm_2_tot_qc real,
    rain_mm_2_tot_f character(1),
VWC_AVG2in real,
VWC_AVG2in_qc real,
VWC_AVG2in_f char(1),
EC_2in real,
EC_2in_qc real,
EC_2in_f char(1),
Temp_AVG2in real,
Temp_AVG2in_qc real,
Temp_AVG2in_f char(1),
VWC_AVG4in real,
VWC_AVG4in_qc real,
VWC_AVG4in_f char(1),
EC_4in real,
EC_4in_qc real,
EC_4in_f char(1),
Temp_AVG4in real,
Temp_AVG4in_qc real,
Temp_AVG4in_f char(1),
VWC_AVG8in real,
VWC_AVG8in_qc real,
VWC_AVG8in_f char(1),
EC_8in real,
EC_8in_qc real,
EC_8in_f char(1),
Temp_AVG8in real,
Temp_AVG8in_qc real,
Temp_AVG8in_f char(1),
VWC_AVG12in real,
VWC_AVG12in_qc real,
VWC_AVG12in_f char(1),
EC_12in real,
EC_12in_qc real,
EC_12in_f char(1),
Temp_AVG12in real,
Temp_AVG12in_qc real,
Temp_AVG12in_f char(1), 
VWC_AVG16in real,
VWC_AVG16in_qc real,
VWC_AVG16in_f char(1),
EC_16in real,
EC_16in_qc real,
EC_16in_f char(1),
Temp_AVG16in real,
Temp_AVG16in_qc real,
Temp_AVG16in_f char(1),
VWC_AVG20in real,
VWC_AVG20in_qc real,
VWC_AVG20in_f char(1),
EC_20in real,
EC_20in_qc real,
EC_20in_f char(1),
Temp_AVG20in real,
Temp_AVG20in_qc real,
Temp_AVG20in_f char(1),
lwmdry_lowbare_tot real,
lwmdry_lowbare_tot_qc real,
lwmdry_lowbare_tot_f char(1),
lwmcon_lowbare_tot real,
lwmcon_lowbare_tot_qc real,
lwmcon_lowbare_tot_f char(1),
lwmwet_lowbare_tot real,
lwmwet_lowbare_tot_qc real,
lwmwet_lowbare_tot_f char(1),
lwmdry_highbare_tot real,
lwmdry_highbare_tot_qc real,
lwmdry_highbare_tot_f char(1),
lwmcon_highbare_tot real,
lwmcon_highbare_tot_qc real,
lwmcon_highbare_tot_f char(1),
lwmwet_highbare_tot real,
lwmwet_highbare_tot_qc real,
lwmwet_highbare_tot_f char(1),
obs_count int
);
CREATE UNIQUE index sm_hourly_idx on sm_hourly(station, valid);
GRANT SELECT on sm_hourly to nobody;

--- Soil Moisture Stations
CREATE TABLE sm_minute (
  station char(5),
  valid timestamp with time zone,

  -- Air Temperature
  TAir_C_Avg real,
  TAir_C_Avg_qc real,
  TAir_C_Avg_f char(1),

  -- Relative Humidity
  rh_avg real,
  rh_avg_qc real,
  rh_avg_f char(1),

  -- Solar Rad total kJ over 1 minute
  SlrkJ_Tot real,
  SlrkJ_Tot_qc real,
  SlrkJ_Tot_f char(1),

  -- Precip total
  Rain_in_Tot real,
  Rain_in_Tot_qc real,
  Rain_in_Tot_f char(1),

  -- 4 inch soil
  TSoil_C_Avg real,
  TSoil_C_Avg_qc real,
  TSoil_C_Avg_f char(1),

  -- wind speed mph
  WS_mph_S_WVT real,
  WS_mph_S_WVT_qc real,
  WS_mph_S_WVT_f char(1),

  -- wind speed max
  WS_mph_max real,
  WS_mph_max_qc real,
  WS_mph_max_f char(1),

  -- wind direction
  WindDir_D1_WVT real,
  WindDir_D1_WVT_qc real,
  WindDir_D1_WVT_f char(1),

  -- 12 inch VWC
  calcVWC12_Avg real,
  calcVWC12_Avg_qc real,
  calcVWC12_Avg_f char(1),

  -- 24 inch VWC
  calcVWC24_Avg real,
  calcVWC24_Avg_qc real,
  calcVWC24_Avg_f char(1),

  -- 50 inch VWC
  calcVWC50_Avg real,
  calcVWC50_Avg_qc real,
  calcVWC50_Avg_f char(1),

  -- 12 inch temp
  T12_C_Avg real,
  T12_C_Avg_qc real,
  T12_C_Avg_f char(1),

  -- 24 inch temp
  T24_C_Avg real,
  T24_C_Avg_qc real,
  T24_C_Avg_f char(1),

  -- 50 inch temp
  T50_C_Avg real,
  T50_C_Avg_qc real,
  T50_C_Avg_f char(1),

  bp_mb real,
  bp_mb_qc real,
  bp_mb_f char(1)
) PARTITION by range(valid);
ALTER TABLE sm_minute OWNER to mesonet;
GRANT SELECT on sm_minute to nobody;
GRANT ALL on sm_minute to ldm;
CREATE INDEX on sm_minute(station, valid);


do
$do$
declare
     year int;
begin
    for year in 2019..2030
    loop
        execute format($f$
            create table sm_minute_%s partition of sm_minute
            for values from ('%s-01-01 00:00+00') to ('%s-01-01 00:00+00')
        $f$, year, year, year + 1);
        execute format($f$
            GRANT ALL on sm_minute_%s to mesonet,ldm
        $f$, year);
        execute format($f$
            GRANT SELECT on sm_minute_%s to nobody,apache
        $f$, year);
    end loop;
end;
$do$;

CREATE TABLE daily (
    station character varying(7),
    valid date,
    c11 real,
    c11_f character(1),
    c12 real,
    c12_f character(1),
    c20 real,
    c20_f character(1),
    c30 real,
    c30_f character(1),
    c40 real,
    c40_f character(1),
    c80 real,
    c80_f character(1),
    c90 real,
    c90_f character(1),
    c70 real,
    c70_f character(1),
    c110 real,
    c110_f character(1),
    c111 real,
    c111_f character(1),
    c509 real,
    c509_f character(1),
    c510 real,
    c510_f character(1),
    c1300 real,
    c1300_f character(1),
    c1301 real,
    c1301_f character(1),
    c900 real,
    c900_f character(1),
    c529 real,
    c529_f character(1),
    c530 real,
    c530_f character(1),
    c30h real,
    c30h_f character(1),
    c30l real,
    c30l_f character(1),
    c930 real,
    c930_f character(1)
);
CREATE UNIQUE INDEX daily_idx ON daily USING btree (station, valid);
grant select on daily to nobody,apache;

CREATE TABLE hourly (
    station character varying(7),
    valid timestamp with time zone,
    c100 real,
    c100_f character(1),
    c200 real,
    c200_f character(1),
    c300 real,
    c300_f character(1),
    c400 real,
    c400_f character(1),
    c500 real,
    c500_f character(1),
    c600 real,
    c600_f character(1),
    c700 real,
    c700_f character(1),
    c800 real,
    c800_f character(1),
    c900 real,
    c900_f character(1)
);
CREATE UNIQUE INDEX hourly_idx ON hourly USING btree (station, valid);
grant select on hourly to nobody,apache;

--- Clever hack to map data around!
create or replace view alldata as 
	select station, valid, ws_mps_s_wvt * 1.94 as sknt, 
	winddir_d1_wvt as drct, rain_mm_tot / 24.5 as phour from sm_hourly;
grant select on alldata to nobody,apache;

-- Storage of 15 minute data
CREATE TABLE sm_15minute (
  station char(5),
  valid timestamp with time zone,
TAir_C_Avg real,
TAir_C_Avg_f char,
TAir_C_Avg_qc real,
RH real,
RH_f char,
RH_qc real,
SlrkW_Avg real,
SlrkW_Avg_f char,
SlrkW_Avg_qc real,
SlrMJ_Tot real,
SlrMJ_Tot_f char,
SlrMJ_Tot_qc real,
Rain_mm_Tot real,
Rain_mm_Tot_f char,
Rain_mm_Tot_qc real,
WS_mps_S_WVT real,
WS_mps_S_WVT_f char,
WS_mps_S_WVT_qc real,
WindDir_D1_WVT real,
WindDir_D1_WVT_f char,
WindDir_D1_WVT_qc real,
WindDir_SD1_WVT real,
WindDir_SD1_WVT_f char,
WindDir_SD1_WVT_qc real,
ws_mph_max real,
ws_mph_max_f char,
ws_mph_max_qc real,
ws_mph_tmx timestamptz,
ws_mph_tmx_f char,
ws_mph_tmx_qc timestamptz,
TSoil_C_Avg real,
TSoil_C_Avg_f char,
TSoil_C_Avg_qc real,
VWC_06_Avg real,
VWC_06_Avg_f char,
VWC_06_Avg_qc real,
VWC_12_Avg real,
VWC_12_Avg_f char,
VWC_12_Avg_qc real,
VWC_24_Avg real,
VWC_24_Avg_f char,
VWC_24_Avg_qc real,
VWC_50_Avg real,
VWC_50_Avg_f char,
VWC_50_Avg_qc real,
ec06 real,
ec06_f char,
ec06_qc real,
EC12 real,
EC12_f char,
EC12_qc real,
EC24 real,
EC24_f char,
EC24_qc real,
EC50 real,
EC50_f char,
EC50_qc real,
T06_C_Avg real,
T06_C_Avg_f char,
T06_C_Avg_qc real,
T12_C_Avg real,
T12_C_Avg_f char,
T12_C_Avg_qc real,
T24_C_Avg real,
T24_C_Avg_f char,
T24_C_Avg_qc real,
T50_C_Avg real,
T50_C_Avg_f char,
T50_C_Avg_qc real,
pa06 real,
pa06_f char,
pa06_qc real,
pa12 real,
pa12_f char,
pa12_qc real,
pa24 real,
pa24_f char,
pa24_qc real,
pa50 real,
pa50_f char,
pa50_qc real,
p06outofrange real,
p06outofrange_f char,
p06outofrange_qc real,
p12outofrange real,
p12outofrange_f char,
p12outofrange_qc real,
p24outofrange real,
p24outofrange_f char,
p24outofrange_qc real,
p50outofrange real,
p50outofrange_f char,
p50outofrange_qc real,
battv_min real,
battv_min_f char,
battv_min_qc real,
    calc_vwc_06_avg real,
    calc_vwc_06_avg_qc real,
    calc_vwc_06_avg_f char(1),
    calc_vwc_12_avg real,
    calc_vwc_12_avg_qc real,
    calc_vwc_12_avg_f char(1),
    calc_vwc_24_avg real,
    calc_vwc_24_avg_qc real,
    calc_vwc_24_avg_f char(1),
    calc_vwc_50_avg real,
    calc_vwc_50_avg_qc real,
    calc_vwc_50_avg_f char(1),
    lwmv_1 real,
    lwmv_1_qc real,
    lwmv_1_f character(1),
    lwmv_2 real,
    lwmv_2_qc real,
    lwmv_2_f character(1),
    lwmdry_1_tot real,
    lwmdry_1_tot_qc real,
    lwmdry_1_tot_f character(1),
    lwmcon_1_tot real,
    lwmcon_1_tot_qc real,
    lwmcon_1_tot_f character(1),
    lwmwet_1_tot real,
    lwmwet_1_tot_qc real,
    lwmwet_1_tot_f character(1),
    lwmdry_2_tot real,
    lwmdry_2_tot_qc real,
    lwmdry_2_tot_f character(1),
    lwmcon_2_tot real,
    lwmcon_2_tot_qc real,
    lwmcon_2_tot_f character(1),
    lwmwet_2_tot real,
    lwmwet_2_tot_qc real,
    lwmwet_2_tot_f character(1),
    bpres_avg real,
    bpres_avg_qc real,
    bpres_avg_f character(1),
    rain_mm_2_tot real,
    rain_mm_2_tot_qc real,
    rain_mm_2_tot_f character(1),
    bp_mb real,
    bp_mb_qc real,
    bp_mb_f character(1),
    VWC_AVG2in real,
VWC_AVG2in_qc real,
VWC_AVG2in_f char(1),
EC_2in real,
EC_2in_qc real,
EC_2in_f char(1),
Temp_AVG2in real,
Temp_AVG2in_qc real,
Temp_AVG2in_f char(1),
VWC_AVG4in real,
VWC_AVG4in_qc real,
VWC_AVG4in_f char(1),
EC_4in real,
EC_4in_qc real,
EC_4in_f char(1),
Temp_AVG4in real,
Temp_AVG4in_qc real,
Temp_AVG4in_f char(1),
VWC_AVG8in real,
VWC_AVG8in_qc real,
VWC_AVG8in_f char(1),
EC_8in real,
EC_8in_qc real,
EC_8in_f char(1),
Temp_AVG8in real,
Temp_AVG8in_qc real,
Temp_AVG8in_f char(1),
VWC_AVG12in real,
VWC_AVG12in_qc real,
VWC_AVG12in_f char(1),
EC_12in real,
EC_12in_qc real,
EC_12in_f char(1),
Temp_AVG12in real,
Temp_AVG12in_qc real,
Temp_AVG12in_f char(1), 
VWC_AVG16in real,
VWC_AVG16in_qc real,
VWC_AVG16in_f char(1),
EC_16in real,
EC_16in_qc real,
EC_16in_f char(1),
Temp_AVG16in real,
Temp_AVG16in_qc real,
Temp_AVG16in_f char(1),
VWC_AVG20in real,
VWC_AVG20in_qc real,
VWC_AVG20in_f char(1),
EC_20in real,
EC_20in_qc real,
EC_20in_f char(1),
Temp_AVG20in real,
Temp_AVG20in_qc real,
Temp_AVG20in_f char(1),
lwmdry_lowbare_tot real,
lwmdry_lowbare_tot_qc real,
lwmdry_lowbare_tot_f char(1),
lwmcon_lowbare_tot real,
lwmcon_lowbare_tot_qc real,
lwmcon_lowbare_tot_f char(1),
lwmwet_lowbare_tot real,
lwmwet_lowbare_tot_qc real,
lwmwet_lowbare_tot_f char(1),
lwmdry_highbare_tot real,
lwmdry_highbare_tot_qc real,
lwmdry_highbare_tot_f char(1),
lwmcon_highbare_tot real,
lwmcon_highbare_tot_qc real,
lwmcon_highbare_tot_f char(1),
lwmwet_highbare_tot real,
lwmwet_highbare_tot_qc real,
lwmwet_highbare_tot_f char(1)
);

CREATE UNIQUE index sm_15minute_idx on sm_15minute(station, valid);
GRANT SELECT on sm_15minute to nobody;
