dependencies:
  # NB: these are requirements of code in this repo
  # autoplot uses
  - affine
  # pytest
  - beautifulsoup4
  # don't download stuff
  - cartopy_offlinedata
  # command line
  - click
  # pytest
  - coverage
  # ?help support
  - docutils
  # one wxc script
  - ephem
  # various places
  - fiona
  # various places
  - gdal
  # important
  - geopandas
  # Get stuff
  - httpx
  # mrms script
  - imageio
  # soft requirement for pandas
  - lxml
  - mastodon.py
  - matplotlib-base
  # various places
  - metar
  # duh
  - metpy>=1.0.0
  # yup
  - netcdf4
  # yup
  - numpy
  # racoon
  - odfpy
  # excel output
  - openpyxl
  # due to config settings
  - pandas>=2.2
  # mod-wsgi
  - paste
  # PIL
  - pillow
  # for downstream installs
  - pip
  # for psql and friends
  - postgresql
  # database
  - psycopg
  # for pyiem
  - pyarrow
  # validation
  - pydantic
  # lots of places
  - pygrib
  # caching
  - pymemcache
  # various places
  - pyproj
  # various shapefile dumpers
  - pyshp>=2
  # for testing
  - pytest
  - pytest-cov
  - pytest-mpl
  - pytest-runner
  - pytest-xdist
  - qrcode
  # various places
  - rasterio
  # various places
  - rasterstats
  # yo
  - requests
  # important
  - scipy
  # autoplots
  - seaborn
  # needed for downstream pip install?
  - setuptools-markdown
  # cow et al
  - shapely
  # various dumpers
  - simplejson
  - sqlalchemy
  # scripts
  - tqdm
  # AHPS scripts
  - twisted
  # testing
  - werkzeug
  # need to use more
  - verde
  # Excel
  - xlsxwriter
  # Excel
  - xlwt
