<?php 
include("../../../config/settings.inc.php");
include_once "../../../include/myview.php";
$t = new MyView();
include("../../../include/iemprop.php");
$asos_archive_end = strtotime( get_iemprop("asos.1min.end") );
include("../../../include/imagemaps.php");
require_once "../../../include/forms.php"; 

$station = isset($_GET["station"]) ? xssafe($_GET["station"]): "";
$year = isset($_GET["year"]) ? intval($_GET["year"]): date("Y");
$month = isset($_GET["month"]) ? intval($_GET["month"]): date("m");
$day = isset($_GET["day"]) ? intval($_GET["day"]): date("d");

$t = new MyView();
$t->thispage = "networks-asos";
$t->title = "Iowa ASOS 1 Minute Time Series";

$endts =  date("d M Y", $asos_archive_end);

$nselect = networkSelect("IA_ASOS", $station, Array("FSD","MLI","OMA") ); 
$ys = yearSelect(2000, $year, "year"); 
$ms = monthSelect($month, "month"); 
$ds = daySelect($day, "day"); 

$extra = "";
if (strlen($station) > 0 ) {
	$extra = <<<EOF


	<BR><BR>

	<img src="1min.php?year={$year}&month={$month}&day={$day}&station={$station}" ALT="Time Series">

	<BR>
	<img src="1min_V.php?year={$year}&month={$month}&day={$day}&station={$station}" ALT="Time Series">

	<br>
	<img src="1min_P.php?year={$year}&month={$month}&day={$day}&station={$station}" ALT="Time Series">


	<p><b>Note:</b> The wind speeds are indicated every minute by the red line.
	The blue dots represent wind direction and are shown every 10 minutes.</p>
EOF;
}

$t->content = <<<EOF
<p><b>Note:</b>The archive currently contains data from 1 Jan 2000
till {$endts} for Waterloo, Sioux City, Dubuque,
and Des Moines.  Other ASOS sites have data from March 2003 to 
{$endts}.



  <form method="GET" action="1station_1min.phtml">

    Make plot selections: <br>
   {$nselect}
   {$ys} {$ms} {$ds}

  <input type="submit" value="Make Plot"></form>

{$extra}


EOF;
$t->render('single.phtml');
?>
