<?php 
require_once "../../../config/settings.inc.php";
require_once "../../../include/myview.php";
$t = new MyView();
require_once "../../../include/iemprop.php";
$asos_archive_end = strtotime( get_iemprop("asos.1min.end") );
require_once "../../../include/imagemaps.php";
require_once "../../../include/forms.php"; 

$station = isset($_GET["station"]) ? xssafe($_GET["station"]): "";
$year = get_int404("year", date("Y", time() - 86400));
$month = get_int404("month", date("m", time() - 86400));
$day = get_int404("day", date("d", time() - 86400));

$t = new MyView();
$t->title = "Iowa ASOS 1 Minute Time Series";

$endts =  date("d M Y", $asos_archive_end);

$ar = Array();
$pgconn = iemdb("mesosite");
$rs = pg_query(
    $pgconn,
    "SELECT id, name, state from stations t JOIN station_attributes a ".
    "ON (t.iemid = a.iemid) WHERE t.network ~* 'ASOS' and ".
    "a.attr = 'HAS1MIN' ORDER by id ASC");
for($i=0; $row=pg_fetch_array($rs); $i++)
{
    $ar[$row[0]] = sprintf("[%s] %s, %s", $row[0], $row[1], $row[2]);
}

$sselect = make_select("station", $station, $ar);

$ys = yearSelect(2000, $year, "year"); 
$ms = monthSelect($month, "month"); 
$ds = daySelect($day, "day"); 

$extra = "";
if (strlen($station) > 0 ) {
	$extra = <<<EOF
<br /><br />
<img src="1min.php?year={$year}&month={$month}&day={$day}&station={$station}" ALT="Time Series">
<br />
<img src="1min_V.php?year={$year}&month={$month}&day={$day}&station={$station}" ALT="Time Series">
<br />
<img src="1min_P.php?year={$year}&month={$month}&day={$day}&station={$station}" ALT="Time Series">

<p><b>Note:</b> The wind speeds are indicated every minute by the red line.
The blue dots represent wind direction and are shown every 10 minutes.</p>
EOF;
}

$t->content = <<<EOF

<h3>ASOS Daily 1 Minute Data Traces</h3>

<p>This page presents an one minute interval plot of available data for a given
central time date.  Data for some sites goes back to the year 2000 and is mostly
updated until {$endts}.</p>

<p><a href="/plotting/auto/?q=211">Autoplot 211</a> is a more modern interface
to generate charts like these and the raw data download for this data is
<a href="/request/asos/1min.phtml">here</a>.</p>


  <form method="GET" action="1station_1min.phtml">

    Make plot selections: <br>
   {$sselect}
   {$ys} {$ms} {$ds}

  <input type="submit" value="Make Plot"></form>

{$extra}


EOF;
$t->render('single.phtml');
