<?php
require_once "../../config/settings.inc.php";
require_once "../../include/myview.php";
$t = new MyView();
$t->title = "Reanalysis Data";

$s4link = sprintf("/archive/data/%s/stage4/", date("Y/m/d"));

$t->content = <<<EOF
<h3>IEM Reanalysis (IEMRE)</h3><p>

<div class="row">
         <div class="col-sm-2">
         
<img src="iemre_anim.gif" class="img img-responsive" />

         </div>
         <div class="col-sm-10">
         
<p>IEM Reanalysis is an effort to provide a regular 
dataset of Iowa Environmental Data without many of the problems associated
with single site observations.  The IEM will continue to provide single
site observational data, but for some purposes, this dataset will be easier
to work with.  <strong>No dataset is perfect and this dataset is provided
without warranty.</strong></p>

<ul>
 <li><strong>Why do this?</strong>
 <br />Previously, the IEM has only provided raw observations with limited
quality control checks in place.  Quality control is hard!  Many times, users
are simply looking for something "close" and perhaps not as perfect as high
quality sensor observations can be.  Producing a gridded analysis is one
way to produce a dataset from point observations which can be sampled as
a means of spatial interpolation.</li>

 <li><strong>Isn't this a duplication of effort?</strong>
 <br />While there are other "reanalysis" type projects out there with
data freely available, many times their data does not update in near real-time
and does not include many of the datasets the IEM uniquely collects. We may
also produce an analysis on sub-hourly timescales.
<br />Having said that, here are some alternatives:
<br /><a href="https://daymet.ornl.gov/">DayMet</a>
<br /><a href="http://www.climatologylab.org/gridmet.html">GridMet</a>
<br /><a href="https://prism.oregonstate.edu/">PRISM</a>
</li>
</ul>

         </div>
         </div>

<h3>Product Changes</h3>

<p><strong>1 May 2018:</strong> Grid domain expanded to cover CONUS.  It will
take a while to fully populate the grids.  At the moment, just the previous
midwestern US data is available.  Grid resolution increased to 0.125x0.125
degree.</p>

<h3>Data Flow</h3>
 
<div class="row">
     <div class="col-md-4">
    <h4>1. Input Datasets</h4>
     <ul>
         <li><strong>NCEP Stage IV Precipitation</strong>
         <br />This is an hourly gridded product with precipitation estimates
         derived by RADAR and then bias corrected by gauge data. The IEM
         caches the <a href="{$s4link}">grib data</a> and makes hourly
         plots available <a href="/timemachine/#40.0">here</a>.</li>
         
         <li><strong>MRMS Precipitation</strong>
         <br />Currently, this is only used to populate a daily total in a
         dedicated netcdf file.</li>

         <li>ASOS/AWOS Daily Summaries</li>
         <li>NWS Daily Climate Summaries</li>
         <li>HRRR/MERRA/NARR Daily Solar Radiation</li>
         <li>NWS COOPerative Observations</li>
         <li>Manually QC'd Iowa COOP data from Iowa's State Climatologist</li>
         <li>NCDC QC'd COOP Data</li>
     </ul>
     </div>
     <div class="col-md-4">
    <h4>2. IEM ReAnalysis Gridded Datasets</h4>
     <ul>
         <li><a href="/plotting/auto/?q=86">Daily Maps of Gridded Variables</a>
         <br />View a smoothed or gridded plot of IEMRE data</li>
         <li><a href="/plotting/auto/?q=84">Maps of Precipitation</a>
         <br />Generate maps for a single day or multiple days.</li>
         <li>Download the raw NetCDF Files <a href="/onsite/iemre/">here</a>.</li>
     </ul>
     </div>
     <div class="col-md-4">
    <h4>3. Climodat Station Data</h4>
    <p>The location of the IEM Longterm tracked climate stations are used to
         sample from the IEMRE grid to produce daily values of high / low
         temperature, precipitation, snowfall, snow depth, and radiation.  For
         some stations, a direct copy of the corresponding ASOS station data
         is used.</p>
     <ul>
         <li><a href="/climodat/">Climodat Reports</a>
         <br />These are pre-generated reports answering many of the commonly
         asked climatology questions.</li>
     </ul>
     </div>
</div>
         
<br clear="all" />
<h3>Data Availability</h3>

<table class="table">
         <thead>
<tr><th>Hourly Interval</th><th>Daily Interval</th></tr>
</thead>
         <tr>
<td>
<ul>
 <li>2 Meter Air Temperature</li>
 <li>10 Meter Wind Speed and Direction</li>
 <li>Precipitation</li>
</ul>
</td>
<td>
<ul>
 <li>High and Low 2 Meter Air Temperature</li>
 <li>Precipitation</li>
</ul>
</td>
</tr>
</table>

<h3>Data Access</h3>

<p>Here are some JSON web services you may try.</p>

<p>
<pre>
MultiDay Request
================
Form: https://mesonet.agron.iastate.edu/iemre/multiday/{YYYY-MM-DD::date1}/{YYYY-MM-DD::date2}/{LAT}/{LON}/json
Example: https://mesonet.agron.iastate.edu/iemre/multiday/2010-05-01/2010-09-30/42.54/-96.40/json
</pre>

<pre>
Single Day Request
=======++=========
Form: https://mesonet.agron.iastate.edu/iemre/daily/{YYYY-MM-DD}/{LAT}/{LON}/json
Example: https://mesonet.agron.iastate.edu/iemre/daily/2010-05-01/42.54/-96.40/json
</pre>

<pre>
Single Day's Hourly (CDT/CST) Request
=======++=========
Form: https://mesonet.agron.iastate.edu/iemre/hourly/{YYYY-MM-DD}/{LAT}/{LON}/json
Example: https://mesonet.agron.iastate.edu/iemre/hourly/2010-05-01/42.54/-96.40/json
</pre>


<h4>Raw Data Access</h4>
                 
<p>The IEM makes extensive use of the <a href="https://www.unidata.ucar.edu/software/netcdf/">NetCDF</a>
file format to store these gridded datasets.  You can find individual web directories for various
IEMRE related datasets: 
<ul>
  <li><a href="/onsite/iemre/">IEMRE Files</a></li>
  <li><a href="/onsite/mrms/">MRMS CST Daily Netcdf File</a></li>
  <li><a href="/onsite/stage4/">NCEP Stage IV Hourly Data</a></li>
  <li><a href="/onsite/prism/">Oregon State PRISM Daily Data</a></li>
</ul>

EOF;
$t->render('single.phtml');
