<?php 
require_once "../../../config/settings.inc.php";
require_once "../../../include/myview.php";
$t = new MyView();
$t->title = "RadMapserver Docs";

$t->content = <<<EOF
<h3>NEXRAD Composite + Mapserver Documentation</h3>

<div class="text">
<p>This page hopefully explains how to produce a geo-referenced NEXRAD composite
image within GEMPAK. We then use Mapserver, as an example of how to create a 
GIS web mapping application.</p>

<table width="100%"><tr><td>

<h3 class="subtitle">The HOWTO:</h3>
The HOWTO is available in various formats.
<ul>
  <li><a href="howto.html">On-Line, HTML</a></li>
  <li><a href="howto.sgml">Linux-Doc SGML</a></li>
  <li><a href="howto.txt">Plain Text</a></li>
</ul>

<h3>Links:</h3>
Links to resources you may find useful.
<ul>
  <li>Mapserver (<a href="http://mapserver.org">http://mapserver.org</a>)</li>
</ul>

<h3>Files:</h3>
Links to files referenced in this HOWTO:
<ul>
  <li><a href="radmapserver-files.tar.gz">radmapserver-files.tar.gz</a></li>
  <ul>
    <li><a href="/radmapserver/radmapserver.map">radmapserver.map file</a></li>
    <li><a href="/radmapserver/radmapserver.html">radmapserver.html template file</a></li>
    <li><a href="/radmapserver/gisdata/radar.tif">Sample TIFF RADAR file</a></li>
    <li><a href="/radmapserver/gisdata/radar.wld">Sample world file for RADAR TIFF</a></li>
    <li><a href="states.zip">Upper midwest states shapefile</a></li>
  </ul>
  <li><a href="nex2img.tar.gz">nex2img</a> program for GEMPAK</li>
</ul>

</td><td valign="TOP">

<h3>Real-time Data:</h3>
<li>US Composite <a href="/data/gis/images/unproj/USCOMP/">Base Reflectivity</a>
<br>(<i>Generated every 5 minutes</i>)<p>

<h3>IEM RADAR Applications:</h3>
<li><a href="/GIS/apps/rview/warnings.phtml">Nationwide Warnings & Loops</a></li>
<li><a href="/current/mcview.phtml">Current &
Archived Iowa Composite Loops</a></li><p>

<h3>HOWTO Online Demo:</h3>
<li>Here is the working demo: <a
href="/cgi-bin/mapserv/mapserv?map=/opt/iem/htdocs/radmapserver/radmapserver.map&layers=states">demo</a>.</li><p>

<h3>News:</h3>
<ul>
		<li><strong>11 Apr 2016:</strong> corrected some URIs</li>
<li><b>28 Jul 2004:</b> Updated for Mapserver 4.x support.  URL fixes.</li>
<li><b>28 Jul 2003:</b> Release the nationwide composite.</li>
<li><b>25 Jul 2003:</b> Initial release for review.</li>
</ul>
		
</td></tr></table></div>
EOF;
$t->render('single.phtml');
?>
