<?php
  /**  IEM Data Vision */
  $uri = $_SERVER['PATH_INFO'];
  $a = explode("/", $uri);
  $valid    = (strlen($a[1]) > 0) ? $a[1] : "now";
  $mode    = (strlen($a[2]) > 0) ? $a[2] : "network";
  $id = (strlen($a[3]) > 0) ? $a[3] : "IA_ASOS";
  $sortcol = (strlen($a[4]) > 0) ? $a[4] : "ts";
  $sortdir = (strlen($a[5]) > 0) ? $a[5] : "desc";

//  print_r($a);
  $ttype = "current";
  $urlbase =  "http://mesonet.agron.iastate.edu/dv";
  $url = "$urlbase/$ttype/$valid/$mode/$id/";
?>
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html>
<head>
  <title>IEM Data Vision</title>
  <meta name="author" content="Daryl Herzmann">
  <meta name="refresh" content="60; URL=<?php echo $url; ?>">
  <link rel="stylesheet" type="text/css" href="/css/mesonet.css">
</head>
<?php include("../include/header2.php"); ?>

<?php include("netselect.inc.php"); ?>

<!-- Begin Big Table -->
<table cellspacing=0 border=0 cellpadding=0>
<tr><td><?php include("hbar.inc.php"); ?></td></tr>
<tr>
  <td bgcolor="#FFA500">

<?php 
  include("../include/iemaccess.php");
  include("../include/iemaccessob.php");
  include("sortables.inc.php");

  $v_tmpf = Array("title" => "Air Temp [F]", "fmt" => "%4.0f");
  $v_dwpf = Array("title" => "Dew Point [F]", "fmt" => "%4.0f");
  $v_drct = Array("title" => "Wind Dir", "fmt" => "%3.0f");
  $v_sknt = Array("title" => "Speed [knots]", "fmt" => "%3.0f");
  $v_pday = Array("title" => "Rainfall Today [in]", "fmt" => "%4.2f");
  $v_pres = Array("title" => "Pressure [in]", "fmt" => "%4.2f");
  $v_max_gust = Array("title" => "Peak Gust [knts]", "fmt" => "%4.0f");
  $v_max_gust_ts = Array("title" => "Peak Gust Time", "fmt" => "%I:%M %p",
                   "time" => "true");

  $netvars = Array(
   "IA_ASOS" => Array("tmpf" => $v_tmpf, "dwpf" => $v_dwpf, 
     "drct" => $v_drct, "sknt" => $v_sknt, "pday" => $v_pday),
   "AWOS" => Array("tmpf" => $v_tmpf, "dwpf" => $v_dwpf, 
     "drct" => $v_drct, "sknt" => $v_sknt, "pday" => $v_pday),
   "KCCI" => Array("tmpf" => $v_tmpf, "dwpf" => $v_dwpf,
     "pres" => $v_pres, "drct" => $v_drct, "sknt" => $v_sknt,
     "max_gust" => $v_max_gust, "max_gust_ts" => $v_max_gust_ts,
     "pday" => $v_pday),
   "KELO" => Array("tmpf" => $v_tmpf, "dwpf" => $v_dwpf, 
     "pres" => $v_pres, 
     "drct" => $v_drct, "sknt" => $v_sknt, "pday" => $v_pday),
  );

  $iem = new IEMAccess();
  $sortables = new sortables();
  $sortables->data = $iem->getNetwork($id);
  $sortables->url = $url;
  $sortables->addDisplayVars($netvars[$id]);
  $sortables->sort($sortcol, $sortdir);
  echo $sortables->printHTML();
?>
  


</td></tr></table>
<!-- End Big Table -->

<?php include("../include/footer2.php"); ?>
