<?php
  /**  IEM Data Vision */
  $uri = $_SERVER['PATH_INFO'];
  $a = explode("/", $uri);
  $valid    = (strlen($a[1]) > 0) ? $a[1] : "today";
  $mode    = (strlen($a[2]) > 0) ? $a[2] : "network";
  $id = (strlen($a[3]) > 0) ? $a[3] : "IA_ASOS";
  $sortcol = (strlen($a[4]) > 0) ? $a[4] : "ts";
  $sortdir = (strlen($a[5]) > 0) ? $a[5] : "desc";

  if ($valid == "now") $valid = "today";

  $ttype = "daily";
  $urlbase =  "http://mesonet.agron.iastate.edu/dv";
  $url = "$urlbase/$ttype/$valid/$mode/$id/";
?>
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html>
<head>
  <title>IEM Data Vision</title>
  <meta name="author" content="Daryl Herzmann">
  <link rel="stylesheet" type="text/css" href="/css/mesonet.css">
</head>
<?php include("../include/header2.php"); ?>

<?php include("netselect.inc.php"); ?>

<!-- Begin Big Table -->
<table cellspacing=0 border=0 cellpadding=0>
<tr><td><?php include("hbar.inc.php"); ?></td></tr>
<tr>
  <td bgcolor="#1E90FF">

<form method="get" name="switchDate">
<b>Select Date:</b><select name="day" 
  onChange="location=this.form.day.options[this.form.day.selectedIndex].value">
<?php 
 /** Switch the Day Valid!!! */
 $now = time();
 $start = time() - 20*86400;
 $step = $start;
 while( $step < $now) {
  $tkey = date("Y-m-d", $step);
  echo "<option value=\"$urlbase/$ttype/$tkey/$mode/$id/$sortcol/$sortdir\" ";
  if ($valid == $tkey) echo "selected=\"selected\"";
  echo ">$tkey\n";
  $step += 86400;
 }

 echo "<option value=\"$urlbase/$ttype/today/$mode/$id/$sortcol/$sortdir\" ";
 if ($valid == "today") echo "selected=\"selected\"";
 echo ">Today\n";

?></select>
</form>

<?php 
  include("../include/iemaccess.php");
  include("../include/iemaccessob.php");
  include("sortables.inc.php");

  $v_max_tmpf = Array("title" => "High Temp [F]", "fmt" => "%4.0f");
  $v_min_tmpf = Array("title" => "Low Temp [F]", "fmt" => "%4.0f");
  $v_pday = Array("title" => "Rainfall Today [in]", "fmt" => "%4.2f");

  $netvars = Array(
   "IA_ASOS" => Array("max_tmpf" => $v_max_tmpf, "min_tmpf" => $v_min_tmpf, 
     "pday" => $v_pday),
   "AWOS" => Array("max_tmpf" => $v_max_tmpf, "min_tmpf" => $v_min_tmpf, 
     "pday" => $v_pday),
  );

  $iem = new IEMAccess();
  $sortables = new sortables($iem);
  $sortables->data = $iem->getNetworkSummary($id, $valid);
  $sortables->addFavorites = false;
  $sortables->url = $url;
  $sortables->addDisplayVars($netvars[$id]);
  $sortables->sort($sortcol, $sortdir);
  echo $sortables->printHTML();
?>
  


</td></tr></table>
<!-- End Big Table -->

<?php include("../include/footer2.php"); ?>
