<?php
  /**  IEM Data Vision */
?>
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html>
<head>
  <title>IEM Data Vision</title>
  <meta name="author" content="Daryl Herzmann">
  <link rel="stylesheet" type="text/css" href="/css/mesonet.css">
</head>
<?php include("../include/header2.php"); ?>

<p>Welcome to IEM DataVision.  This application has been built from
the ground up for you to quickly find data valid for various different
timespans.

<p>
<ul>
  <li><a href="current.phtml">Current</a></li>
</ul>

<?php include("../include/footer2.php"); ?>
