<?php 
/* Front End to generate plots for a given day */
require_once "../../../../config/settings.inc.php";
define("IEM_APPID", 50);
require_once "../../../../include/forms.php";
  $pvar = isset($_GET["pvar"]) ? $_GET["pvar"]: "c11,c12";
  $ar = explode(",", $pvar);
  $_GET["var"] = $pvar;
  if (sizeof($ar) > 1){
   $_GET["var"] = $ar[0];
   $_GET["var2"] = $ar[1];
  }
  $year = isset($_GET["year"]) ? intval($_GET["year"]): date("Y", time() - 86400 - (7 * 3600) );
  $month = isset($_GET["month"]) ? intval($_GET["month"]): date("m", time() - 86400 - (7 * 3600) );
  $day = isset($_GET["day"]) ? intval($_GET["day"]): date("d", time() - 86400 - (7 * 3600) );
  $date = $year ."-". $month ."-". $day;
  $ts = mktime(0,0,0, $month, $day, $year);
  $network = isset($_REQUEST["network"]) ? strtoupper(xssafe($_REQUEST["network"])): 'AUTO';
  
  $networkopts = Array("AUTO", "ISUAG", "ISUSM");
  if (! in_array($network, $networkopts)){
  	die("Invalid network!");
  }
  $networkform = '<select name="network">';
  while( list($key,$val)=each($networkopts)){
  	$networkform .= sprintf("<option value='%s'%s>%s</option>", $val,
  			($val == $network)? " SELECTED='SELECTED'": "", $val);
  }
  $networkform .= "</select>";
  
  
 $imgurl = sprintf("plot.php?pvar=%s&amp;year=%s&amp;month=%s&amp;day=%s&amp;network=%s", $pvar, $year,
	$month, $day, $network);
  
  $varDef = Array("c11" => "High Air Temperatures",
  		"c12" => "Low Air Temperatures [F]",
  		"c11,c12" => "High and Low Air Temperatures [F]",
  		"c30" => "Avg 4in Soil Temperatures [F]",
  		"c40" => "Avg Wind Velocity [MPH]",
  		"c509" => "Peak 1 Minute Gust [MPH]",
  		"c529,c530" => "Peak 5 Second Gust [MPH] and Time",
  		"c90" => "Total Precipitation [inch]",
  		"c20" => "Avg Relative Humidity",
  		"c80" => "Solar Radiation [Langleys]",
  		"c70" => "Evapotranspiration [inch]",
  		"c300h,c300l" => "High and Low 4in Soil Temps [F]"
  );
  
  $selectform = '<select name="pvar">';
  while( list($key,$val)=each($varDef)){
  	$selectform .= sprintf("<option value='%s'%s>%s</option>", $key, 
  			($key == $pvar)? " SELECTED='SELECTED'": "", $val);
  }
  $selectform .= "</select>";
  

include("../../../../include/myview.php");
$t = new MyView();
$t->thispage = "networks-agclimate";
$t->title = "ISUAG Daily Data Plots";
$ys = yearSelect(1986, $year);
$ms = monthSelect($month); 
$ds = daySelect($day);
$t->content = <<<EOF
<h3 class="page-heading">ISU AgClimate Daily Data Plots</h3>

<p>This page will generate a plot for a variable and date of your choice.  If you 
want to plot an accumulated value, check out the 
<a href="gsplot.phtml">Growing Season Plots</a>.

<p>
  <form method="GET" action="dayplot.phtml">
  <table>
    <tr><th>Network:</th><th>Plot Variable:</th><th>Year:</th><th>Month:</th><th>Day:</th><td></td></tr>
    <tr>
  <td>{$networkform}</td>
  <td>${selectform}</td>
      <td>{$ys}</td>
      <td>{$ms}</td>
      <td>{$ds}</td>
      <td><input type="submit" value="Make Plot"></td>
    </tr>
  </table>
   </form>
<p>
<img src="{$imgurl}" class="image-responsive" />
EOF;
$t->render('single.phtml');
?>