<?php
include("../../../../config/settings.inc.php");
include("$rootpath/include/forms.php");
include("$rootpath/include/database.inc.php");
include("$rootpath/include/network.php");
$nt = new NetworkTable("ISUAG");
$ISUAGcities = $nt->table;
$ISUAGcities["A130219"]["lon"] += 0.2;

$var = isset($_GET["var"]) ? $_GET["var"] : "gdd50";
$year = isset($_GET["year"]) ? $_GET["year"] : date("Y");
$smonth = isset($_GET["smonth"]) ? $_GET["smonth"]:  5;
$emonth = isset($_GET["emonth"]) ? $_GET["emonth"]: 10;
$sday = isset($_GET["sday"]) ? $_GET["sday"]: 1;
$eday = isset($_GET["eday"]) ? $_GET["eday"]: 1;
$imgsz = isset($_GET["imgsz"]) ? $_GET["imgsz"] : "640x480";
$ar = explode("x", $imgsz);
$width = $ar[0];
$height = $ar[1];

$imgurl = sprintf("gsplot.php?var=%s&year=%s&smonth=%s&emonth=%s&eday=%s&sday=%s&imgsz=%s", $var, $year, $smonth, $emonth, $eday, $sday, $imgsz);

$gs_start = mktime(0,0,0,$smonth,$sday,$year);
$gs_end = mktime(0,0,0,$emonth,$eday,$year);

$round = Array("prec" => 2, "gdd50" => 0, "gdd32" => 0, "et" => 2, "sgdd50" => 0, "sdd86" => 0, "srad" => 0);

$today = time();
if ($gs_end >= $today)  $gs_end = $today;

$emonth = strftime("%m", $gs_end);
$eday = strftime("%d", $gs_end);
$smonth = strftime("%m", $gs_start);
$sday = strftime("%d", $gs_start);


$sstr = strftime("%Y-%m-%d", $gs_start);
$estr = strftime("%Y-%m-%d", $gs_end);
$cStart = "2000". strftime("-%m-%d", $gs_start);
$cEnd = "2000". strftime("-%m-%d", $gs_end);
$sstr_txt = strftime("%b %d", $gs_start);
$estr_txt = strftime("%b %d", $gs_end);

$varDef = Array("gdd50" => "Growing Degree Days (base=50)",
  "gdd32" => "Growing Degree Days (base=32)",
  "et" => "Potential Evapotranspiration",
  "prec" => "Precipitation",
  "srad" => "Solar Radiation (langleys)",
  "sgdd50" => "Soil Growing Degree Days (base=50)",
  "sdd86" => "Stress Degree Days (base=86)"
);



$rnd = Array("gdd50" => 0,
  "gdd32" => 0,
  "et" => 2, "c11" => 2,
  "prec" => 2,
  "srad" => 0,
  "sgdd50" => 0,
  "sdd86" => 0);


function gdd($high, $low, $ceiling, $floor)
{
  if ($low < $floor)    $low = $floor;
  if ($high > $ceiling) $high = $ceiling;
  if ($high < $floor) return 0;

  return (($high+$low)/2.00) - $floor;
}

/* -------- Lets compute the climatology ------ */
$c = iemdb("isuag");
$climatedb = iemdb("coop");
$climate = Array();
reset($ISUAGcities);
while( list($key,$val) = each($ISUAGcities) ) {
  $csite = strtolower($ISUAGcities[$key]["climate_site"]);
  $climate[$key] = Array('gdd32'=> 0, 'gdd50' => 0,'sdd86'=>0,'prec'=>0);

  $sql = sprintf("SELECT * from climate51 WHERE station = '%s' and
    valid BETWEEN '%s' and '%s'", $csite, $cStart, $cEnd);
  $rs =  pg_exec($climatedb, $sql);
  for ($i=0; $row = @pg_fetch_array($rs,$i); $i++) {
    $climate[$key]['gdd32'] += gdd($row["high"],$row["low"],86,32);
    $climate[$key]['gdd50'] += gdd($row["high"],$row["low"],86,50);
    $climate[$key]['prec'] += $row["precip"];
 
  }
}

/* ------------------------------------------------------- */
if ($var == 'gdd32') {
  $q = "SELECT station, c11, c12
     from daily WHERE valid >= '". $sstr ."'
     and valid < '". $estr ."'";

  $gdds = Array();
  $rs =  pg_exec($c, $q);
  for ($i=0; $row = @pg_fetch_array($rs,$i); $i++) {
    $stid = $row['station'];
    $high = (float)$row['c11'];
    $low  = (float)$row['c12'];
    $tgdd = gdd($high, $low, 86, 32);

    if (! isset($gdds[$stid]) ) $gdds[$stid] = 0;
    $gdds[$stid] = $gdds[$stid] + $tgdd;
  }
  $vals = $gdds;
} 
/* ------------------------------------------------------- */
if ($var == 'gdd50') {
  $q = "SELECT station, c11, c12
     from daily WHERE valid >= '". $sstr ."'
     and valid < '". $estr ."'";

  $gdds = Array();
  $rs =  pg_exec($c, $q);
  for ($i=0; $row = @pg_fetch_array($rs,$i); $i++) {
    $stid = $row['station'];
    $high = (float)$row['c11'];
    $low  = (float)$row['c12'];
    $tgdd = gdd($high, $low, 86, 50);

    if (! isset($gdds[$stid]) ) $gdds[$stid] = 0;
    $gdds[$stid] = $gdds[$stid] + $tgdd;
  }
  $vals = $gdds;
}  
/* ------------------------------------------------------- */
if ($var == 'sdd86') {
  $q = "SELECT station, c11, c12
     from daily WHERE valid >= '". $sstr ."'
     and valid < '". $estr ."'";

  $gdds = Array();
  $rs =  pg_exec($c, $q);
  for ($i=0; $row = @pg_fetch_array($rs,$i); $i++) {
    $stid = $row['station'];
    $high = (float)$row['c11'];
    $low  = (float)$row['c12'];
    $tgdd = gdd($high, $low, 186, 86);

    if (! isset($gdds[$stid]) ) $gdds[$stid] = 0;
    $gdds[$stid] = $gdds[$stid] + $tgdd;
  }
  $vals = $gdds;
}  
/* ------------------------------------------------------- */
else if ($var == 'sgdd50') {
  $q = "SELECT station, date(valid) as dvalid, 
     max(c300) as high, min(c300) as low
     from hourly WHERE valid >= '". $sstr ."'
     and valid < '". $estr ."' GROUP by station, dvalid";

  $gdds = Array();
  $rs =  pg_exec($c, $q);
  for ($i=0; $row = @pg_fetch_array($rs,$i); $i++) {
    $stid = $row['station'];
    $high = (float)$row['high'];
    $low  = (float)$row['low'];
    $tgdd = gdd($high, $low, 86, 50);

    if (! isset($gdds[$stid]) ) $gdds[$stid] = 0;
    $gdds[$stid] = $gdds[$stid] + $tgdd;
  }
  $vals = $gdds;
}  
/* ------------------------------------------------------- */
else if ($var == 'et') {
  $q = "SELECT station, sum(c70) as et
     from daily WHERE valid >= '". $sstr ."'
     and valid < '". $estr ."' GROUP by station";

  $vals = Array();
  $rs =  pg_exec($c, $q);
  for ($i=0; $row = @pg_fetch_array($rs,$i); $i++) {
    $stid = $row['station'];
    $vals[$stid] = $row['et'];
  }
}
/* ------------------------------------------------------- */
else if ($var == 'srad') {
  $q = "SELECT station, sum(c80) as srad
     from daily WHERE valid >= '". $sstr ."'
     and valid < '". $estr ."' GROUP by station";

  $vals = Array();
  $rs =  pg_exec($c, $q);
  for ($i=0; $row = @pg_fetch_array($rs,$i); $i++) {
    $stid = $row['station'];
    $vals[$stid] = $row['srad'];
  }
}
/* ------------------------------------------------------- */
else if ($var == 'prec') {
  $q = "SELECT station, sum(c90) as prec
     from daily WHERE valid >= '". $sstr ."'
     and valid < '". $estr ."' GROUP by station";

  $vals = Array();
  $rs =  pg_exec($c, $q);
  for ($i=0; $row = @pg_fetch_array($rs,$i); $i++) {
    $stid = $row['station'];
    $vals[$stid] = $row['prec'];
  }
}  
/* ------------------------------------------------------- */


$tr = "# ".$year." ". $varDef[$var] ." (". $sstr_txt ." - ". $estr_txt .")\n";
$tr .= "#-----------------------snip------------------\n";
$tr .= sprintf("%20s,%10s,%10s,%10s\n", 'StationName', 'Latitude', 'Longitude', $var);
foreach($vals as $key => $value){
  if ($key == "A133259") continue;

  $tr .= sprintf("%20s,%.4f,%.4f,%10s\n", $ISUAGcities[$key]['name'],
  $ISUAGcities[$key]['lat'], $ISUAGcities[$key]['lon'], round($value, $round[$var]) );

}


?>

<?php 
$THISPAGE = "networks-agclimate";
	$TITLE = "IEM | ISUAG Growing Season Data";
	$HEADEXTRA = '<script language="JavaScript" type="text/javascript">
<!--//BEGIN Script
function new_window(url) {
        link = 
       
window.open(url,"_new","toolbar=0,location=0,directories=0,status=0,menubar=no,scrollbars=yes,resizable=yes,width=450,height=400");
} 
//END Script-->
</script>';
        include("$rootpath/include/header.php"); 
?>

<h3 class="heading">Growing Season Maps</h3><p>

<div style="width: 640px;">
This application will plot an accumulated variable for a time period of your 
selection.  Data is based on the automated sensors from the ISU AG Climate
network.  A <a href="<?php echo $rooturl; ?>/GIS/apps/coop/gsplot.phtml">similiar application</a> exists based on the COOP network data, which
is of higher quality for temperature and precipitation.
</div>

<form method="GET" action="gsplot.phtml">
<table cellspacing="0" cellpadding="2" border="1"> 
<thead>
<tr>
   <th>Plot Parameter</th>
   <th>Year</th>
   <th>Month</th>
   <th>Day</th>
   <th>Image Size</th>
   <td></td>
  </tr>
</thead>
 <tr>
  <td rowspan=2><select name="var">
     <option value="gdd50" <?php if($var == "gdd50") echo "SELECTED"; ?>>Growing Degree Days (base=50,cap=86)</option>
     <option value="gdd32" <?php if($var == "gdd32") echo "SELECTED"; ?>>Growing Degree Days (base=32,cap=86)</option>
     <option value="et" <?php if($var == "et") echo "SELECTED"; ?>>Potential Evapotranspiration</option>
     <option value="sgdd50" <?php if($var == "sgdd50") echo "SELECTED"; ?>>Soil Growing Degree Days (base=50)</option>
     <option value="srad" <?php if($var == "srad") echo "SELECTED"; ?>>Solar Radiation (langleys)</option>
     <option value="sdd86" <?php if($var == "sdd86") echo "SELECTED"; ?>>Stress Degree Days (base=86)</option>
    </select></td>
  <td rowspan=2><?php echo yearSelect(1986, $year, "year"); ?></td>
  <td><?php echo monthSelect2($smonth, 'smonth'); ?></td>
  <td><?php echo daySelect2($sday, 'sday'); ?></td>
<td rowspan=2>
<select name="imgsz">
     <option value="640x480" <?php if($imgsz == "640x480") echo "SELECTED"; ?>>640x480</option>
     <option value="720x496" <?php if($imgsz == "720x496") echo "SELECTED"; ?>>720x496</option>
     <option value="1024x768" <?php if($imgsz == "1024x768") echo "SELECTED"; ?>>1024x768</option>
</select> 
</td>
  <td rowspan=2><input type="submit" value="Make Plot"></td>
  </tr>
 <tr>
  <td><?php echo monthSelect2($emonth, 'emonth'); ?></td>
  <td><?php echo daySelect2($eday, 'eday'); ?></td>
  </tr>
</table>
 

<?php

$varDef = Array("gdd50" => "Growing Degree Days (base=50)",
  "gdd32" => "Growing Degree Days (base=32)",
  "et" => "Potential Evapotranspiration",
  "prec" => "Precipitation",
  "srad" => "Solar Radiation (langleys)",
  "sgdd50" => "Soil Growing Degree Days (base=50)",
  "sdd86" => "Stress Degree Days (base=86)"
);


$rnd = Array("gdd50" => 0,
  "gdd32" => 0,
  "et" => 2, "c11" => 2,
  "prec" => 2,
  "srad" => 0,
  "sgdd50" => 0,
  "sdd86" => 0);


?>
<table>
<tr><td valign="top">
<h3 class="heading">Dynamic Historical Data:</h3>
<a href="dayplot.phtml">Daily Data Plots</a>
<br /><b>Growing Season Plots</b>

<p>Open this plot in a <a href="javascript:new_window('<?php echo $imgurl; ?>');">new window</a> for comparison with other plots. Once the
image is loaded up in another window, you can modify this plots 
parameters.

<p><b>*Note:</b> Precipitation recorded from this network is not reliable.
 You should use precipitation obs from the <a href="<?php echo $rooturl; ?>/COOP/">COOP</a> network.
</td>
  <td>
<?php
  if ($var == "gdd32" || $var == "gdd50" || $var == "prec")
{
  echo "Departure from climatology is shown below the accumulated value.";
}
?>
  <img src="<?php echo $imgurl; ?>" border=1>
</td></tr>
</table>

<p>
<center><img src="<?php echo $rooturl; ?>/images/gisready.png"><h3 class="subtitle"> Data Listing</h3></center>
<pre><?php echo $tr; ?></pre>

<p>You should be able to 'copy & paste' this raw data listing into a simple
text editor and save the data file on your machine.  Most GIS systems can 
then import this dataset as a layer.  You may have to omit the commented lines
(#) if your GIS has trouble importing the data.

<?php 
  include("$rootpath/include/footer.php");
?>
