<?php
include("../../../../config/settings.inc.php");
define("IEM_APPID", 51);
require_once "../../../../include/forms.php";
include("../../../../include/database.inc.php");
include("../../../../include/network.php");

$var = isset($_GET["var"]) ? xssafe($_GET["var"]) : "gdd50";
$year = isset($_GET["year"]) ? intval($_GET["year"]) : date("Y");
$smonth = isset($_GET["smonth"]) ? intval($_GET["smonth"]):  5;
$emonth = isset($_GET["emonth"]) ? intval($_GET["emonth"]): 10;
$sday = isset($_GET["sday"]) ? intval($_GET["sday"]): 1;
$eday = isset($_GET["eday"]) ? intval($_GET["eday"]): 1;
$imgsz = isset($_GET["imgsz"]) ? xssafe($_GET["imgsz"]): "640x480";
$ar = explode("x", $imgsz);
$width = $ar[0];
$height = $ar[1];

if ($year > 2013) {
	$nt = new NetworkTable("ISUSM");
	$ISUAGcities = $nt->table;
} else {
	$nt = new NetworkTable("ISUAG");
	$ISUAGcities = $nt->table;
	$ISUAGcities["A130219"]["lon"] += 0.2;
}

$imgurl = sprintf("gsplot.php?var=%s&amp;year=%s&amp;smonth=%s&amp;".
		"emonth=%s&amp;eday=%s&amp;sday=%s&amp;imgsz=%s",
		$var, $year, $smonth, $emonth, $eday, $sday, $imgsz);

$gs_start = mktime(0,0,0,$smonth,$sday,$year);
$gs_end = mktime(0,0,0,$emonth,$eday,$year);

$round = Array("prec" => 2, "gdd50" => 0, "gdd32" => 0, "et" => 2, 
"sgdd50" => 0, "sgdd52" => 0, "sdd86" => 0, "srad" => 0);

$today = time();
if ($gs_end >= $today)  $gs_end = $today;

$emonth = strftime("%m", $gs_end);
$eday = strftime("%d", $gs_end);
$smonth = strftime("%m", $gs_start);
$sday = strftime("%d", $gs_start);


$sstr = strftime("%Y-%m-%d", $gs_start);
$estr = strftime("%Y-%m-%d", $gs_end);
$cStart = "2000". strftime("-%m-%d", $gs_start);
$cEnd = "2000". strftime("-%m-%d", $gs_end);
$sstr_txt = strftime("%b %d", $gs_start);
$estr_txt = strftime("%b %d", $gs_end);

$varDef = Array("gdd50" => "Growing Degree Days (base=50)",
  "gdd32" => "Growing Degree Days (base=32)",
  "et" => "Potential Evapotranspiration",
  "prec" => "Precipitation",
  "srad" => "Solar Radiation (langleys)",
  "sgdd50" => "Soil Growing Degree Days (base=50)",
  "sgdd52" => "Soil Growing Degree Days (base=52)",
  "sdd86" => "Stress Degree Days (base=86)"
);



$rnd = Array("gdd50" => 0,
  "gdd32" => 0,
  "et" => 2, "c11" => 2,
  "prec" => 2,
  "srad" => 0,
  "sgdd50" => 0,
  "sgdd52" => 0,
  "sdd86" => 0);


function gdd($high, $low, $ceiling, $floor)
{
  if ($low < $floor)    $low = $floor;
  if ($high > $ceiling) $high = $ceiling;
  if ($high < $floor) return 0;

  return (($high+$low)/2.00) - $floor;
}

/* -------- Lets compute the climatology ------ */
$c = iemdb("isuag");
$climatedb = iemdb("coop");
$climate = Array();
reset($ISUAGcities);
while( list($key,$val) = each($ISUAGcities) ) {
  $csite = strtolower($ISUAGcities[$key]["climate_site"]);
  $climate[$key] = Array('gdd32'=> 0, 'gdd50' => 0,'sdd86'=>0,'prec'=>0);

  $sql = sprintf("SELECT * from climate51 WHERE station = '%s' and
    valid BETWEEN '%s' and '%s'", $csite, $cStart, $cEnd);
  $rs =  pg_exec($climatedb, $sql);
  for ($i=0; $row = @pg_fetch_array($rs,$i); $i++) {
    $climate[$key]['gdd32'] += gdd($row["high"],$row["low"],86,32);
    $climate[$key]['gdd50'] += gdd($row["high"],$row["low"],86,50);
    $climate[$key]['prec'] += $row["precip"];
 
  }
}

/* ------------------------------------------------------- */
if ($var == 'gdd32') {
	if ($year > 2013){
		$q = <<<EOF
  SELECT station, c2f(tair_c_max) as c11, c2f(tair_c_min) as c12 from sm_daily
  WHERE valid >= '{$sstr}' and valid < '{$estr}'
EOF;
	} else {
  		$q = <<<EOF
  SELECT station, c11, c12 from daily
  WHERE valid >= '{$sstr}' and valid < '{$estr}'
EOF;
	}
  
  $gdds = Array();
  $rs =  pg_exec($c, $q);
  for ($i=0; $row = @pg_fetch_array($rs,$i); $i++) {
    $stid = $row['station'];
    $high = (float)$row['c11'];
    $low  = (float)$row['c12'];
    $tgdd = gdd($high, $low, 86, 32);

    if (! isset($gdds[$stid]) ) $gdds[$stid] = 0;
    $gdds[$stid] = $gdds[$stid] + $tgdd;
  }
  $vals = $gdds;
} 
/* ------------------------------------------------------- */
if ($var == 'gdd50') {
	if ($year > 2013){
		$q = <<<EOF
  SELECT station, c2f(tair_c_max) as c11, c2f(tair_c_min) as c12 from sm_daily
  WHERE valid >= '{$sstr}' and valid < '{$estr}'
EOF;
	} else {
  		$q = <<<EOF
  SELECT station, c11, c12 from daily
  WHERE valid >= '{$sstr}' and valid < '{$estr}'
EOF;
	}

  $gdds = Array();
  $rs =  pg_exec($c, $q);
  for ($i=0; $row = @pg_fetch_array($rs,$i); $i++) {
    $stid = $row['station'];
    $high = (float)$row['c11'];
    $low  = (float)$row['c12'];
    $tgdd = gdd($high, $low, 86, 50);

    if (! isset($gdds[$stid]) ) $gdds[$stid] = 0;
    $gdds[$stid] = $gdds[$stid] + $tgdd;
  }
  $vals = $gdds;
}  
/* ------------------------------------------------------- */
if ($var == 'sdd86') {
	if ($year > 2013){
		$q = <<<EOF
  SELECT station, c2f(tair_c_max) as c11, c2f(tair_c_min) as c12 from sm_daily
  WHERE valid >= '{$sstr}' and valid < '{$estr}'
EOF;
	} else {
  		$q = <<<EOF
  SELECT station, c11, c12 from daily
  WHERE valid >= '{$sstr}' and valid < '{$estr}'
EOF;
	}

  $gdds = Array();
  $rs =  pg_exec($c, $q);
  for ($i=0; $row = @pg_fetch_array($rs,$i); $i++) {
    $stid = $row['station'];
    $high = (float)$row['c11'];
    $low  = (float)$row['c12'];
    $tgdd = gdd($high, $low, 186, 86);

    if (! isset($gdds[$stid]) ) $gdds[$stid] = 0;
    $gdds[$stid] = $gdds[$stid] + $tgdd;
  }
  $vals = $gdds;
}  
/* ------------------------------------------------------- */
else if ($var == 'sgdd50' || $var == 'sgdd52') {
	if ($year > 2013){
		$q = "SELECT station, date(valid) as dvalid, 
				c2f(max(tsoil_c_avg)) as high,
				c2f(min(tsoil_c_avg)) as low from sm_hourly WHERE
				valid >= '". $sstr ."'
     			and valid < '". $estr ."' GROUP by station, dvalid";	
	} else {
  		$q = "SELECT station, date(valid) as dvalid, 
     		max(c300) as high, min(c300) as low
     		from hourly WHERE valid >= '". $sstr ."'
     		and valid < '". $estr ."' GROUP by station, dvalid";
	}
  $gdds = Array();
  $rs =  pg_exec($c, $q);
  for ($i=0; $row = @pg_fetch_array($rs,$i); $i++) {
    $stid = $row['station'];
    $high = (float)$row['high'];
    $low  = (float)$row['low'];
    if ($var == 'sgdd50'){
    	$tgdd = gdd($high, $low, 86, 50);
    } else {
    	$tgdd = gdd($high, $low, 86, 52);
    }
    if (! isset($gdds[$stid]) ) $gdds[$stid] = 0;
    $gdds[$stid] = $gdds[$stid] + $tgdd;
  }
  $vals = $gdds;
}  
/* ------------------------------------------------------- */
else if ($var == 'et') {
	if ($year > 2013){
	$q = <<<EOF
	SELECT station, sum(dailyet / 24.5) as et from sm_daily
	WHERE valid >= '{$sstr}' and valid < '{$estr}' GROUP by station
EOF;
	} else {
  $q = "SELECT station, sum(c70) as et
     from daily WHERE valid >= '". $sstr ."'
     and valid < '". $estr ."' GROUP by station";
	}
  $vals = Array();
  $rs =  pg_exec($c, $q);
  for ($i=0; $row = @pg_fetch_array($rs,$i); $i++) {
    $stid = $row['station'];
    $vals[$stid] = $row['et'];
  }
}
/* ------------------------------------------------------- */
else if ($var == 'srad') {
	if ($year > 2013){
  $q = "SELECT station, sum(slrmj_tot) as srad
     from sm_daily WHERE valid >= '". $sstr ."'
     and valid < '". $estr ."' GROUP by station";
	} else {
		$q = "SELECT station, sum(c80) as srad
     from daily WHERE valid >= '". $sstr ."'
     and valid < '". $estr ."' GROUP by station";
	}
  
  $vals = Array();
  $rs =  pg_exec($c, $q);
  for ($i=0; $row = @pg_fetch_array($rs,$i); $i++) {
    $stid = $row['station'];
    $vals[$stid] = $row['srad'];
  }
}
/* ------------------------------------------------------- */
else if ($var == 'prec') {
	if ($year > 2013){
		$q = "SELECT station, sum(rain_mm_tot / 24.5) as prec
     from sm_daily WHERE valid >= '". $sstr ."'
     and valid < '". $estr ."' GROUP by station";
	} else {
  $q = "SELECT station, sum(c90) as prec
     from daily WHERE valid >= '". $sstr ."'
     and valid < '". $estr ."' GROUP by station";
	}

  $vals = Array();
  $rs =  pg_exec($c, $q);
  for ($i=0; $row = @pg_fetch_array($rs,$i); $i++) {
    $stid = $row['station'];
    $vals[$stid] = $row['prec'];
  }
}  
/* ------------------------------------------------------- */


$tr = "# ".$year." ". $varDef[$var] ." (". $sstr_txt ." - ". $estr_txt .")\n";
$tr .= "#-----------------------snip------------------\n";
$tr .= sprintf("%20s,%10s,%10s,%10s\n", 'StationName', 'Latitude', 'Longitude', $var);
foreach($vals as $key => $value){
  if ($key == "A133259") continue;

  $tr .= sprintf("%20s,%.4f,%.4f,%10s\n", $ISUAGcities[$key]['name'],
  		$ISUAGcities[$key]['lat'], $ISUAGcities[$key]['lon'], 
  		round($value, $round[$var]) );
}

include "../../../../include/myview.php";
$t = new MyView();
$t->thispage = "networks-agclimate";
$t->title = "ISUAG Growing Season Data";
$t->headextra = <<<EOF
<script language="JavaScript" type="text/javascript">
<!--//BEGIN Script
function new_window(url) {
        link = 
       
window.open(url,"_new","toolbar=0,location=0,directories=0,status=0,menubar=no,scrollbars=yes,resizable=yes,width=450,height=400");
} 
//END Script-->
</script>
EOF;

$ar = Array("gdd50" => "Growing Degree Days (base=50,cap=86)",
    "gdd32" => "Growing Degree Days (base=32,cap=86)",
    "et" => "Potential Evapotranspiration",
    "sgdd50" => "Soil Growing Degree Days (base=50)",
    "sgdd52" => "Soil Growing Degree Days (base=52)",
    "srad" => "Solar Radiation (langleys)",
    "sdd86" => "Stress Degree Days (base=86)",
);

$vselect = make_select("var", $var, $ar);

$varDef = Array("gdd50" => "Growing Degree Days (base=50)",
		"gdd32" => "Growing Degree Days (base=32)",
		"et" => "Potential Evapotranspiration",
		"prec" => "Precipitation",
		"srad" => "Solar Radiation (langleys)",
		"sgdd50" => "Soil Growing Degree Days (base=50)",
		"sgdd52" => "Soil Growing Degree Days (base=52)",
		"sdd86" => "Stress Degree Days (base=86)"
);


$rnd = Array("gdd50" => 0,
		"gdd32" => 0,
		"et" => 2, "c11" => 2,
		"prec" => 2,
		"srad" => 0,
		"sgdd50" => 0,
		"sgdd52" => 0,
		"sdd86" => 0);

$h3 = "";
if ($var == "gdd32" || $var == "gdd50" || $var == "prec")
{
	$h3 = "Departure from climatology is shown below the accumulated value.";
}
$yselect = yearSelect(1986, $year, "year");
$smselect = monthSelect2($smonth, 'smonth');
$sdselect = daySelect2($sday, 'sday');
$emselect = monthSelect2($emonth, 'emonth');
$edselect = daySelect2($eday, 'eday');

$ar = Array("640x480" => "640x480",
		"720x496" => "720x496",
		"1024x768" => "1024x768");
$iselect = make_select("imgsz", $imgsz, $ar);

$t->content = <<<EOF
<h3>Growing Season Maps</h3>

<p>This application will plot an accumulated variable for a time period of your 
selection.  Data is based on the automated sensors from the ISU AG Climate
network.  A <a href="/GIS/apps/coop/gsplot.phtml">similiar application</a> 
exists based on the COOP network data, which
is of higher quality for temperature and precipitation.

<div class="alert alert-warning">We are currently working through some data
quality issues with the new ISU Soil Moisture network for 2014.  Please use 
care when using these values and graphics!</div>

<form method="GET" action="gsplot.phtml">
<table class="table"> 
<thead>
<tr>
   <th>Plot Parameter</th>
   <th>Year</th>
   <th>Month</th>
   <th>Day</th>
   <th>Image Size</th>
   <td></td>
  </tr>
</thead>
 <tr>
  <td rowspan=2>{$vselect}</td>
  <td rowspan=2>{$yselect}</td>
  <td>{$smselect}</td>
  <td>{$sdselect}</td>
<td rowspan=2>
{$iselect}
</td>
  <td rowspan=2><input type="submit" value="Make Plot"></td>
  </tr>
 <tr>
  <td>{$emselect}</td>
  <td>{$edselect}</td>
  </tr>
</table>
 

<div class="row">
<div class="col-sm-3">

<h3>Dynamic Historical Data:</h3>
<a href="dayplot.phtml">Daily Data Plots</a>
<br /><b>Growing Season Plots</b>

<p>Open this plot in a <a href="javascript:new_window('{$imgurl}');">new window</a> 
for comparison with other plots. Once the
image is loaded up in another window, you can modify this plots 
parameters.

<p><b>*Note:</b> Precipitation recorded from this network is not reliable.
 You should use precipitation obs from the <a href="/COOP/">COOP</a> network.

 </div><div class="col-sm-9">
 
{$h3}
  <img src="{$imgurl}" class="img img-responsive">

  </div></div>
  
<p>
<center><img src="/images/gisready.png"><h3 class="subtitle"> Data Listing</h3></center>
<pre>{$tr}</pre>

<p>You should be able to 'copy & paste' this raw data listing into a simple
text editor and save the data file on your machine.  Most GIS systems can 
then import this dataset as a layer.  You may have to omit the commented lines
(#) if your GIS has trouble importing the data.
EOF;
$t->render('single.phtml');
?>
