<?php
require_once "../../../../config/settings.inc.php";
define("IEM_APPID", 51);
require_once "../../../../include/forms.php";
require_once "../../../../include/myview.php";

$var = isset($_GET["var"]) ? xssafe($_GET["var"]) : "gdd50";
$year = get_int404("year", date("Y"));
$smonth = get_int404("smonth", 5);
$emonth = get_int404("emonth", 9);
$sday = get_int404("sday", 1);
$eday = get_int404("eday", 30);
$imgsz = isset($_GET["imgsz"]) ? xssafe($_GET["imgsz"]) : "640x480";
$ar = explode("x", $imgsz);
$width = $ar[0];
$height = $ar[1];

// Make sure our edate is not too late
$today = time() - 86400;
$edate = mktime(0, 0, 0, $emonth, $eday, $year);
if ($edate > $today) {
    $emonth = date("m", $today);
    $eday = date("d", $today);
}

$varDef = array(
    "gdd32" => "Growing Degree Days (base=32)",
    "gdd41" => "Growing Degree Days (base=41)",
    "gdd46" => "Growing Degree Days (base=46)",
    "gdd48" => "Growing Degree Days (base=48)",
    "gdd50" => "Growing Degree Days (base=50)",
    "gdd51" => "Growing Degree Days (base=51)",
    "gdd52" => "Growing Degree Days (base=52)",
    "et" => "Potential Evapotranspiration",
    "precip" => "Precipitation",
    "srad" => "Solar Radiation (langleys)",
    "sgdd50" => "Soil Growing Degree Days (base=50)",
    "sgdd52" => "Soil Growing Degree Days (base=52)"
);
if (!array_key_exists($var, $varDef)) {
    die("variable undefined.");
}
$gddbase = 50;
$datavar = $var;
if (substr($var, 0, 3) == "gdd") {
    $gddbase = intval(str_replace("gdd", "", $var));
    $datavar = "gdd";
}
if (substr($var, 0, 4) == "sgdd") {
    $gddbase = intval(str_replace("sgdd", "", $var));
    $datavar = "sgdd";
}

$wsuri = sprintf(
    "/api/1/isusm/daily.geojson?sdate=%s-%02.0f-%02.0f&edate=%s-%02.0f-%02.0f&" .
        "gddbase=%s&gddceil=%s",
    $year,
    $smonth,
    $sday,
    $year,
    $emonth,
    $eday,
    $gddbase,
    86
);

$imgurl = sprintf(
    "gsplot.php?var=%s&amp;year=%s&amp;smonth=%s&amp;" .
        "emonth=%s&amp;eday=%s&amp;sday=%s&amp;imgsz=%s",
    $var,
    $year,
    $smonth,
    $emonth,
    $eday,
    $sday,
    $imgsz
);

$round = array("precip" => 2, "gdd" => 0, "sgdd" => 0, "et" => 2, "srad" => 0);


$jdata = file_get_contents("http://iem.local" . $wsuri);
$jobj = json_decode($jdata, $assoc = TRUE);

$tr = "# " . $year . " " . $varDef[$var] . " ({$smonth}/{$sday} - {$emonth}/{$eday})\n";
$tr .= "#-----------------------snip------------------\n";
$tr .= sprintf(
    "%-5s,%-40s,%-15s,%-10s,%-10s,%-10s,climate_%s\n",
    'ID',
    'StationName',
    'City',
    'Latitude',
    'Longitude',
    $var,
    $var
);

$climovar = "climo_" . $datavar;
foreach ($jobj["features"] as $bogus => $value) {
    $props = $value["properties"];
    if ($props[$datavar] === null) {
        continue;
    }
    $climo = "M";
    if (array_key_exists($climovar, $props)) {
        $climo = round($props["climo_" . $datavar], $round[$datavar]);
    }

    $tr .= sprintf(
        "%s,%-40.40s,%-15.15s,%10.4f,%10.4f,%10s,%10s\n",
        $props["station"],
        $props['name'],
        $props["city"],
        $props['lat'],
        $props['lon'],
        round($props[$datavar], $round[$datavar]),
        $climo
    );
}

$t = new MyView();
$t->title = "ISUAG Growing Season Data";
$t->headextra = <<<EOF
<script language="JavaScript" type="text/javascript">
<!--//BEGIN Script
function new_window(url) {
    link = window.open(url,"_new","toolbar=0,location=0,directories=0,status=0,menubar=no,scrollbars=yes,resizable=yes,width=450,height=400");
}
//END Script-->
</script>
EOF;

$vselect = make_select("var", $var, $varDef);

$h3 = "";
if ($datavar == "gdd" ||  $var == "precip") {
    $h3 = "Departure from climatology is shown below the accumulated value.";
}
$yselect = yearSelect(1986, $year, "year");
$smselect = monthSelect2($smonth, 'smonth');
$sdselect = daySelect2($sday, 'sday');
$emselect = monthSelect2($emonth, 'emonth');
$edselect = daySelect2($eday, 'eday');

$ar = array(
    "640x480" => "640x480",
    "720x496" => "720x496",
    "1024x768" => "1024x768"
);
$iselect = make_select("imgsz", $imgsz, $ar);

$t->content = <<<EOF
<h3>Growing Season Maps</h3>

<p>This application will plot an accumulated variable for a time period of your 
selection.  Data is based on the automated sensors from the ISU AG Climate
network.  A <a href="/GIS/apps/coop/gsplot.phtml">similiar application</a> 
exists based on the COOP network data, which
is of higher quality for temperature and precipitation.

<form method="GET" action="gsplot.phtml">
<table class="table"> 
<thead>
<tr>
   <th>Plot Parameter</th>
   <th>Year</th>
   <th>Month</th>
   <th>Day</th>
   <th>Image Size</th>
   <td></td>
  </tr>
</thead>
 <tr>
  <td rowspan=2>{$vselect}</td>
  <td rowspan=2>{$yselect}</td>
  <td>{$smselect}</td>
  <td>{$sdselect}</td>
<td rowspan=2>
{$iselect}
</td>
  <td rowspan=2><input type="submit" value="Make Plot"></td>
  </tr>
 <tr>
  <td>{$emselect}</td>
  <td>{$edselect}</td>
  </tr>
</table>

<div class="row">
<div class="col-sm-3">

<h3>Dynamic Historical Data:</h3>
<a href="/plotting/auto/?q=199">Daily Data Plots</a>
<br /><b>Growing Season Plots</b>

<p>Open this plot in a <a href="javascript:new_window('{$imgurl}');">new window</a> 
for comparison with other plots. Once the
image is loaded up in another window, you can modify this plots 
parameters.

<p><b>*Note:</b> Precipitation recorded from this network is not reliable.
 You should use precipitation obs from the <a href="/COOP/">COOP</a> network.

 </div><div class="col-sm-9">
 
{$h3}
  <img src="{$imgurl}" class="img img-responsive">
<p><strong>Note:</strong> Some stations are slightly moved on the map to
improve readability.</p>
  </div></div>
  
<p>
<button type="button" role="button" id="save" class="btn btn-primary">Download CSV Text</button>
<br />
<pre id="datatable">{$tr}</pre>

<p>You should be able to 'copy & paste' this raw data listing into a simple
text editor and save the data file on your machine.  Most GIS systems can 
then import this dataset as a layer.  You may have to omit the commented lines
(#) if your GIS has trouble importing the data.
EOF;
$t->jsextra = <<<EOM
<script>
$(document).ready(function(){
    $("#save").click(function(){
        var content = $("#datatable").text().split(/\\n/).slice(2).join("\\n");

        var link = document.createElement('a');
        link.setAttribute('download', 'isusm.csv');    
        link.setAttribute('href', 'data:text/plain;charset=utf-8,' + encodeURIComponent(content));
        link.click(); 
    });
});

</script>
EOM;
$t->render('single.phtml');
