<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<HTML>
<HEAD>
	<TITLE>IEM Access</TITLE>
	<META NAME="AUTHOR" CONTENT="Daryl Herzmann">
	<link rel="stylesheet" type="text/css" href="/css/mesonet.css">
</HEAD>

<?php 
$page = "gis";
include("../../include/header2.php"); ?>

<center>
<div class="ptitle">IEM Access</div>
</center>

<p>IEM Access is the projectname for the underlying data storage 
layer that drives most IEM applications.  IEM Access consists of 
a Internet accessible spatial database which can be accessed via 
a variety of methods and protocols.  This page can be considered
as the homepage for this effort.  As software and services are 
released, they will be linked in here.  Check back here for
updates and new features!

<h2 class="heads">IEM Access Applications:</h2>
<ul>
 <li><a href="http://mesonet.agron.iastate.edu/my/current.php">Current Sortables</a>
 <dd>Current conditions from the spatial database are presented in a 
  sortable HTML table format.</dd></li>
</ul>

<h2 class="heads">IEM Currents Shapefile:</h2>
<ul>
 <li><a href="http://mesonet.agron.iastate.edu/GIS/access/dumpSHP.php">Click to download .zip (.shp .dbf .shx)</a></li>
<dd>Current conditions from all of the IEM networks can be dumped to a shapefile and downloaded in a compressed .zip file.</dd>



<table>

</table>


<?php include("../../include/footer2.php"); ?>
