<?php

dl("php_mapscript_401.so");

include('../../../include/kcciLoc.php');

$map = ms_newMapObj("view.map");
//$map->setProjection("proj=latlong");
//$map->setExtent(-100,40,-90,50);
 
$counties = $map->getlayerbyname("counties");
$counties->set("status", MS_ON);
$counties->setProjection("proj=latlong");

$kcci = $map->getlayerbyname("KCCI");
$kcci->set("status", MS_ON);

$sites = $map->getlayerbyname("sites");
$sites->set("status", MS_ON);

$pt = ms_newPointObj();
$pt->setXY(450000, 4700000);

$img = $map->prepareImage();
 
$counties->draw($img);
$kcci->draw($img);
$sites->draw($img);
 
$map->drawLabelCache($img);
 
$url = $img->saveWebImage(MS_PNG, 0,0,-1);
?>
<html>

<form method="POST" action="display.phtml" target="display">

<?php echo "<input type=\"image\" name=\"image\" src=\"$url\">"; ?>
