<?php 
include("../../../config/settings.inc.php");
include("../../../include/myview.php");
include("../../../include/imagemaps.php");
include("../../../include/forms.php");

$network = isset($_REQUEST["network"]) ? substr($_REQUEST["network"],0,7): "IA_RWIS";

define("IEM_APPID", 63);
$t = new MyView();
$t->iemss = True;
$t->title = "RWIS Data Download";
$t->thispage = "networks-rwis";

$rselect = networkMultiSelect($network, "", Array("_ALL" => "All Sites"),
	'station[]');
$startyr = ($network == 'IA_RWIS') ? 1995: 2009;
$ys1 = yearSelect2($startyr, date("Y"), "year1");
$ms1 = monthSelect("", "month1");
$ds1 = daySelect2("", "day1");
$hs1 = hourSelect("", "hour1");
$ys2 = yearSelect2($startyr, date("Y"), "year2");
$ms2 = monthSelect("", "month2");
$ds2 = daySelect2("", "day2");
$hs2 = hourSelect("", "hour2");

$ar = Array(
		"Etc/UTC" => "Coordinated Universal Time (UTC)",
		"America/New_York" => "America/New_York (EST/EDT)",
		"America/Chicago" => "America/Chicago (CST/CDT)",
		"America/Denver" => "America/Denver (MST/MDT)",
		"America/Los_Angeles" => "America/Los_Angeles (WST/WDT)",
		"America/Anchorage" => "America/Anchorage (AKST/AKDT)",
);
$tzselect = make_select("tz", "Etc/UTC", $ar);


$t->content = <<<EOF
<ol class="breadcrumb">
 <li><a href="/RWIS/">RWIS Homepage</a></li>
 <li class="active">Download</li>
</ol>
<h3>RWIS Atmospheric / Surface Data Download</h3>

<p>The IEM archives RWIS information for the network in Iowa based on a direct
feed from the DOT.  We also archive other states based on an archive provided
by the <a href="http://madis.noaa.gov/">MADIS project</a>. Data for Iowa dates
back to 1995, whereas we only have data for other states back to 2009. 
The archive has some holes in it around the year 2000 and 2001, 
but it mostly in tack outside of those dates.</p>

<p>Data is available from the following states: 
 <a href="fe.phtml?network=AK_RWIS">Alaska</a>,
 <a href="fe.phtml?network=CO_RWIS">Colorado</a>,
 <a href="fe.phtml?network=IN_RWIS">Indiana</a>,
 <a href="fe.phtml?network=IA_RWIS">Iowa</a>,
 <a href="fe.phtml?network=KS_RWIS">Kansas</a>,
 <a href="fe.phtml?network=KY_RWIS">Kentucky</a>,
 <a href="fe.phtml?network=MN_RWIS">Minnesota</a>,
 <a href="fe.phtml?network=NE_RWIS">Nebraska</a>,
 <a href="fe.phtml?network=ND_RWIS">North Dakota</a>,
 <a href="fe.phtml?network=NV_RWIS">Nevada</a>,
 <a href="fe.phtml?network=NH_RWIS">New Hampshire</a>, 
 <a href="fe.phtml?network=OH_RWIS">Ohio</a>,
 <a href="fe.phtml?network=VA_RWIS">Virginia</a>,
 <a href="fe.phtml?network=WV_RWIS">West Virginia</a>,
 <a href="fe.phtml?network=WI_RWIS">Wisconsin</a>,
 and <a href="fe.phtml?network=WY_RWIS">Wyoming</a>.
 

<form method="GET" action="/cgi-bin/request/rwis.py" name="iemss">
<input type="hidden" name="minute1" value="0">
<input type="hidden" name="minute2" value="0">
<input type="hidden" name="network" value="{$network}">

<div class="row">
<div class="col-sm-7">

<div id="iemss" data-network="{$network}"></div>

</div>
<div class="col-sm-5">

<p><h4>2. Select Start/End Time:</h4>
<i>Times are in timezone you select in step 5 below.</i>
<table>
  <tr>
    <td></td>
    <th>Year</th><th>Month</th><th>Day</th>
    <th>Hour</th>
  </tr>

  <tr>
    <th>Start:</th>
    <td>{$ys1}</td>
    <td>{$ms1}</td>
   	<td>{$ds1}</td>
    <td>{$hs1}</td>
  </tr>

  <tr>
    <th>End:</th>
    <td>{$ys2}</td>
    <td>{$ms2}</td>
   	<td>{$ds2}</td>
    <td>{$hs2}</td>
  </tr>
</table>

<p><h4>3. Select Variables:</h4>
<select size="5" name="vars" MULTIPLE>
  <option value="tmpf">Air Temperature [F]
  <option value="dwpf">Dew Point Temperature [F]
  <option value="sknt">Wind Speed [knots]
  <option value="drct">Wind Direction [degree N]
  <option value="gust">Wind Gust [knots]
  <option value="tfs0">Pavement Sensor0 Temperature [F]
  <option value="tfs0_text">Pavement Sensor0 Condition
  <option value="tfs1">Pavement Sensor1 Temperature [F]
  <option value="tfs1_text">Pavement Sensor1 Condition
  <option value="tfs2">Pavement Sensor2 Temperature [F]
  <option value="tfs2_text">Pavement Sensor2 Condition
  <option value="tfs3">Pavement Sensor3 Temperature [F]
  <option value="tfs3_text">Pavement Sensor3 Condition
  <option value="subf">Subsurface Temperature [F]
</select>


<p><h4>4. How to view?</h4>
<select name="what">
  <option value="txt">Download as Delimited Text File</option>
  <option value="excel">Download as Excel</option>
  <option value="html">View as HTML webpage</option>
</select>

<p><h4>5. Timezone of Timestamps</h4>
   <i>This controls the timezone used for presenting the timestamps in the
    downloaded file.</i>
   <br />{$tzselect}</p>
    		
<p><h4>6. Data Delimitation:</h4>
How shall the output values be seperated?
<br><select name="delim">
    <option value="comma">Comma
    <option value="space">Space
    <option value="tab">Tab
   </select>

<p>
<h4>7. Include Lat / Lons?</h4><img src="/images/gisready.png">
 <select name="gis">
   <option value="no">No
   <option value="yes">Yes
 </select>
   		
<p><h4>8. Submit Form:</h4>
<input type="submit" value="Process Data Request">
<input type="reset">

</div></div>


</form>
EOF;
$t->render('single.phtml');
?>