<?php
require_once "../../../config/settings.inc.php";
require_once "../../../include/myview.php";
require_once "../../../include/imagemaps.php";
require_once "../../../include/forms.php";
require_once "../../../include/database.inc.php";

$network = isset($_REQUEST["network"]) ? xssafe($_REQUEST["network"]) : "IA_RWIS";

define("IEM_APPID", 63);
$t = new MyView();
$t->iemss = True;
$t->title = "RWIS Data Download";

$startyr = ($network == 'IA_RWIS') ? 1995 : 2009;
$ys1 = yearSelect2($startyr, date("Y"), "year1");
$ms1 = monthSelect("", "month1");
$ds1 = daySelect2("", "day1");
$hs1 = hourSelect("", "hour1");
$ys2 = yearSelect2($startyr, date("Y"), "year2");
$ms2 = monthSelect("", "month2");
$ds2 = daySelect2("", "day2");
$hs2 = hourSelect("", "hour2");

$ar = array(
    "Etc/UTC" => "Coordinated Universal Time (UTC)",
    "America/New_York" => "America/New_York (EST/EDT)",
    "America/Chicago" => "America/Chicago (CST/CDT)",
    "America/Denver" => "America/Denver (MST/MDT)",
    "America/Los_Angeles" => "America/Los_Angeles (PST/PDT)",
    "America/Anchorage" => "America/Anchorage (AKST/AKDT)",
);
$tzselect = make_select("tz", "Etc/UTC", $ar);

$ar = array();
$rs = pg_exec(
    iemdb("mesosite"),
    "SELECT id, name from networks where id ~* 'RWIS' ORDER by name ASC"
);
while ($row = pg_fetch_assoc($rs)) {
    $ar[$row["id"]] = $row["name"];
}
$sselect = make_select("network", $network, $ar);

$t->content = <<<EOF
<ol class="breadcrumb">
 <li><a href="/RWIS/">RWIS Homepage</a></li>
 <li class="active">Download</li>
</ol>
<h3>RWIS Atmospheric / Surface Data Download</h3>

<p>The IEM archives RWIS information for the network in Iowa based on a direct
feed from the DOT.  We also archive other states based on an archive provided
by the <a href="http://madis.noaa.gov/">MADIS project</a>. Data for Iowa dates
back to 1995, whereas we only have data for other states back to 2009. 
The archive has some holes in it around the year 2000 and 2001, 
but it mostly in tack outside of those dates.</p>

<p>
<form method="GET" name="s">
<strong>Available States:</strong> ${sselect}
<input type="submit" value="Select Network">
</form>
</p>

<form target="_blank" method="GET" action="/cgi-bin/request/rwis.py" name="iemss">
<input type="hidden" name="minute1" value="0">
<input type="hidden" name="minute2" value="0">
<input type="hidden" name="network" value="{$network}">

<div class="row">
<div class="col-sm-7">

<div id="iemss" data-network="{$network}"></div>

</div>
<div class="col-sm-5">

<p><h4>2. Select Start/End Time:</h4>
<i>Times are in timezone you select in step 5 below.</i>
<table>
  <tr>
    <td></td>
    <th>Year</th><th>Month</th><th>Day</th>
    <th>Hour</th>
  </tr>

  <tr>
    <th>Start:</th>
    <td>{$ys1}</td>
    <td>{$ms1}</td>
   	<td>{$ds1}</td>
    <td>{$hs1}</td>
  </tr>

  <tr>
    <th>End:</th>
    <td>{$ys2}</td>
    <td>{$ms2}</td>
   	<td>{$ds2}</td>
    <td>{$hs2}</td>
  </tr>
</table>

<p><h4>3. Select Variables:</h4>
<select size="5" name="vars" MULTIPLE>
  <option value="tmpf">Air Temperature [F]
  <option value="dwpf">Dew Point Temperature [F]
  <option value="sknt">Wind Speed [knots]
  <option value="drct">Wind Direction [degree N]
  <option value="gust">Wind Gust [knots]
  <option value="tfs0">Pavement Sensor0 Temperature [F]
  <option value="tfs0_text">Pavement Sensor0 Condition
  <option value="tfs1">Pavement Sensor1 Temperature [F]
  <option value="tfs1_text">Pavement Sensor1 Condition
  <option value="tfs2">Pavement Sensor2 Temperature [F]
  <option value="tfs2_text">Pavement Sensor2 Condition
  <option value="tfs3">Pavement Sensor3 Temperature [F]
  <option value="tfs3_text">Pavement Sensor3 Condition
  <option value="subf">Subsurface Temperature [F]
</select>

<br /><strong>See below for discussion on "Pavement Sensor* Condition"</strong></p>

<p><h4>4. How to view?</h4>
<select name="what">
  <option value="txt">Download as Delimited Text File</option>
  <option value="excel">Download as Excel</option>
  <option value="html">View as HTML webpage</option>
</select>

<p><h4>5. Timezone of Timestamps</h4>
   <i>This controls the timezone used for presenting the timestamps in the
    downloaded file.</i>
   <br />{$tzselect}</p>
    		
<p><h4>6. Data Delimitation:</h4>
How shall the output values be seperated?
<br><select name="delim">
    <option value="comma">Comma
    <option value="space">Space
    <option value="tab">Tab
   </select>

<p>
<h4>7. Include Lat / Lons?</h4><img src="/images/gisready.png">
 <select name="gis">
   <option value="no">No
   <option value="yes">Yes
 </select>
   		
<p><h4>8. Submit Form:</h4>
<input type="submit" value="Process Data Request">
<input type="reset">

</div></div>

<hr />

<h3>Pavement Sensor Condition Explaination</h3>

<p>The following applies to most of the Iowa RWIS sensors and is passed along by
the Iowa RWIS Coordinator.</p>

<p>The data is taken from the <a href="https://my.vaisala.net/en/roads/products/roadweathersensors/Pages/FP2000.aspx">Vaisala FP2000</a>.
These readings can be lumped into four general categories:  wet, dry, snow/ice, error.
The sensor gives quite a few more, especially in the snow/ice realm but functionally
it is difficult to distinguish clear differences between them.</p>

<p>From the glossary:</p>

<table class="table table-bordered">
<thead><tr><th>Status</th><th>Description</th></tr></thead>
<tbody>

<tr><th>Snow/Ice Warning</th>

<td>Continuous film of ice and water mixture at or below freezing (32°F / 0°C) with insufficient chemical to keep the mixture from freezing.
This status can only be reported at Vaisala ESP and SP sites when precipitation occurs.
</td></tr>
<tr><th>Ice Warning</th>

<td>Continuous film of ice and water mixture at or below freezing (32°F / 0°C) with insufficient chemical to keep the mixture from freezing. 
This status can only be reported at NTCIP sites.
</td></tr>
<tr><th>Snow Warning</th>

<td>This status can be reported at NTCIP sites, but will not be reported by Vaisala NTCIP sites.
</td></tr>
<tr><th>Wet Below Freezing</th>

<td>Moisture on pavement sensor with a surface temperature below freezing (32°F / 0°C). 
This status will only be reported at Vaisala SCAN Detector sites.
</td></tr>
<tr><th>Ice Watch</th>

<td>Thin or spotty film of moisture at or below freezing (32°F / 0°C). 
This status can only be reported at NTCIP sites when precipitation is not occurring.
</td></tr>
<tr><th>Snow/IceWatch</th>

<td>Thin or spotty film of moisture at or below freezing (32°F / 0°C). 
This status can only be reported at Vaisala ESP and SP sites when precipitation is not occurring.
</td></tr>
<tr><th>Snow Watch</th>

<td>This status can be reported at NTCIP sites, but is not detected at Vaisala NTCIP sites.
</td></tr>
<tr><th>Frost</th>

<td>Moisture on pavement at or below freezing (32°F / 0°C) with a pavement temperature at or below the dew point temperature. 
This status can only be reported by Vaisala ESP, SP, and NTCIP sites when precipitation is not occurring.
</td></tr>
<tr><th>Chemical Wet</th>

<td>Continuous film of water and ice mixture at or below freezing (32°F or 0°C) with enough chemical to keep the mixture from freezing. 
This status can only be reported by Vaisala ESP, SP, and NTCIP sites when precipitation occurs.
</td></tr>
<tr><th>Wet</th>

<td>Continuous film of moisture on the pavement sensor with a surface temperature above freezing (32°F or 0°C). 
This status can be reported by Vaisala ESP, SP, SCAN Detector, and NTCIP sites when precipitation has occurred.
</td></tr>
<tr><th>Damp</th>

<td>Thin or spotty film of moisture above freezing (32°F or 0°C). 
This status can only be reported by Vaisala ESP, and SP sites when precipitation is not occurring.
</td></tr>
<tr><th>Trace Moisture</th>

<td>Thin or spotty film of moisture above freezing (32°F or 0°C). Surface moisture occurred without precipitation being detected.
This status will only be reported at NTCIP sites when precipitation is not occurring.
</td></tr>
<tr><th>Absorption at Dew Point, Absorption, & Dew</th>

<td>These statuses can be reported at NTCIP sites, but are not currently detected at Vaisala NTCIP sites.
</td></tr>
<tr><th>Dry</th>

<td>Absence of moisture on the surface sensor. 
This status can be reported by Vaisala ESP, SP, SCAN Dectector, and NTCIP sites.
</td></tr>
<tr><th>Other</th>

<td>Other is the standard NTCIP ESS surface condition code to handle conditions not explicitly included in this table. This status will only be reported NTCIP by sensors installed at NTCIP ESS sites.
</td></tr>
<tr><th>No Report</th>

<td>The surface sensor is not operating properly and requires maintenance. 
This status will only be reported by Vaisala ESP and SP sites.</td></tr>

<tr><th>Error</th>

<td>The surface sensor is not operating properly and requires maintenance. 
This status will only be reported by NTCIP sites.</td></tr>

</tbody>
</table>


</form>
EOF;
$t->render('single.phtml');
