<?php 
include("../../../config/settings.inc.php");
define("IEM_APPID", 81);
include_once "../../../include/myview.php";
$t = new MyView();
include("../../../include/imagemaps.php");
include("../../../include/forms.php");

$t->title = "RWIS Soil Probe Data Download";
$t->thispage = "networks-rwis";

$ys = yearSelect2(2008, date("Y"), "year1");
$ms = monthSelect("", "month1");
$ds = daySelect2("", "day1");
$hs = gmtHourSelect("", "hour1");

$ys2 = yearSelect2(2008, date("Y"), "year2");
$ms2 = monthSelect("", "month2");
$ds2 = daySelect2("", "day2");
$hs2 = gmtHourSelect("", "hour2");

$ar = Array(
		"Etc/UTC" => "Coordinated Universal Time (UTC)",
		"America/New_York" => "America/New_York (EST/EDT)",
		"America/Chicago" => "America/Chicago (CST/CDT)",
		"America/Denver" => "America/Denver (MST/MDT)",
		"America/Los_Angeles" => "America/Los_Angeles (WST/WDT)",
		"America/Anchorage" => "America/Anchorage (AKST/AKDT)",
		);
$tzselect = make_select("tz", "Etc/UTC", $ar);

$t->content = <<<EOF
<ol class="breadcrumb">
 <li><a href="/RWIS/">RWIS Homepage</a></li>
 <li class="active">Iowa Soil Data Download</li>
</ol>

<p>This page provides access to the Iowa RWIS Soil Probe sensor data. The
data columns are 15 temperature values at these depths (1,3,6,9,12,18,24,
30,36,42,48,54,60,66,72 inches).  They are labelled s0temp thru s14temp.
Values are in Fahrenheit.

<form method="GET" action="/cgi-bin/request/rwis.py">
<input type="hidden" name="src" value="soil">
<input type="hidden" name="vars" value="s0temp">
<input type="hidden" name="vars" value="s1temp">
<input type="hidden" name="vars" value="s2temp">
<input type="hidden" name="vars" value="s3temp">
<input type="hidden" name="vars" value="s4temp">
<input type="hidden" name="vars" value="s5temp">
<input type="hidden" name="vars" value="s6temp">
<input type="hidden" name="vars" value="s7temp">
<input type="hidden" name="vars" value="s8temp">
<input type="hidden" name="vars" value="s9temp">
<input type="hidden" name="vars" value="s10temp">
<input type="hidden" name="vars" value="s11temp">
<input type="hidden" name="vars" value="s12temp">
<input type="hidden" name="vars" value="s13temp">
<input type="hidden" name="vars" value="s14temp">

<table>
<tr><td width="50%">

<p><h3>1. Select Station:</h3><br>
<i>Select One or More or All stations in the network.</i><br />
<select name="stations" size="5" MULTIPLE>
  <option value="RCRI4">Anamosa
  <option value="RCLI4">Cantril
  <option value="RDNI4">Denison
  <option value="ROSI4">Osceola (I-35)
  <option value="RPFI4">Plainfield
  <option value="RSGI4">Sigourney
  <option value="RSCI4">Sioux City / Moville
  <option value="RTPI4">Tipton
</select>


<p><h3>2. Select Start/End Time:</h3><br>
<i>Times are in UTC.  Archive starts in June 2008.</i>
<table>
  <tr>
    <td></td>
    <th>Year</th><th>Month</th><th>Day</th>
    <th>Hour</th>
  </tr>

  <tr>
    <th>Start:</th>
    <td>{$ys}</td>
    <td>{$ms}</td>
    <td>{$ds}</td>
    <td>{$hs}
	<input type="hidden" name="minute1" value="0"></td>
  </tr>

  <tr>
    <th>End:</th>
    <td>{$ys2}</td>
    <td>{$ms2}</td>
    <td>{$ds2}</td>
    <td>{$hs2}
	<input type="hidden" name="minute2" value="0"></td>
    </tr>
</table>

</td><td valign="TOP">

<p><h4>3. Timezone of Timestamps</h4>
   <i>This controls the timezone used for presenting the timestamps in the
    downloaded file.</i>
   <br />{$tzselect}</p>
    		
<p><h3>4. How to view?</h3><br>
<select name="what">
  <option value="download">Download to Disk
  <option value="view">View on-line
</select>

<p><h3>5. Data Delimitation:</h3><br>
How shall the output values be seperated?
<br><select name="delim">
    <option value="comma">Comma
    <option value="space">Space
    <option value="tab">Tab
   </select>

<p>
<h3>6. Include Lat / Lons?</h3><img src="/images/gisready.png"><br>
 <select name="gis">
   <option value="no">No
   <option value="yes">Yes
 </select>

</td></tr></table>

<p><h3>Submit Form:</h3><br>
<input type="submit" value="Process Data Request">
<input type="reset">
</form>
EOF;
$t->render('single.phtml');

?>
