<?php

function mktitle($map, $imgObj, $titlet) {
  $layer = $map->getLayerByName("credits");

  // point feature with text for location
  $point = ms_newpointobj();
  $point->setXY(10, 15);

  $point->draw($map, $layer, $imgObj, "credits",
    $titlet);
}

function mklogolocal($map, $imgObj) {

 $layer = $map->getLayerByName("logo");

 // point feature with text for location
 $point = ms_newpointobj();
 $point->setXY(44, 24);

 $point->draw($map, $layer, $imgObj, "logo", "");
}



dl("php_mapscript_441.so");
print_r($_GET);
 $oextents = isset($_GET['extents']) ? $_GET['extents'] : "-105,40,-90,50";
 $zoom     = isset($_GET['zoom']) ? $_GET['zoom'] : 0;
 $imgwidth = 640;
 $imgheight = 480;
 if ( isset($_GET['img_x']) ){
   include("../include/click2geo.inc.php");
   $extents = click2geo($oextents, $_GET['img_x'], $_GET['img_y'],
     $imgwidth, $imgheight, $zoom);
 } else {
   $extents = $oextents;
 }



$map = ms_newMapObj("base4326-beta.map");
$map->set("width", $imgwidth);
$map->set("height", $imgheight);

$arExtents = explode(",", $extents);
$map->setextent($arExtents[0], $arExtents[1], $arExtents[2], $arExtents[3]);

$namerica = $map->getlayerbyname("namerica");
$namerica->set("status", MS_ON);

$counties = $map->getlayerbyname("counties");
$counties->set("status", MS_ON);

$lakes = $map->getlayerbyname("lakes");
$lakes->set("status", MS_ON);

$states = $map->getlayerbyname("states");
$states = $map->getlayerbyname("states");

$mwradar = $map->getlayerbyname("mwradar");
$mwradar->set("status", MS_ON);

$temps = $map->getlayerbyname("temps");
$temps->set("status", MS_ON);

$sites = $map->getlayerbyname("sites");
$sites->set("status", MS_ON);
$sites->setFilter("network != 'NEXRAD'");
if ($_GET["labelcache"] == "yes") 
$sites->set("labelcache", MS_ON);
else
$sites->set("labelcache", MS_OFF);

$img = $map->prepareImage();
$namerica->draw($img);
$counties->draw($img);
$lakes->draw($img);
$states->draw($img);
$mwradar->draw($img);
$sites->draw($img);
$temps->draw($img);
//$ts = @filemtime("/mesonet/data/gis/images/unproj/MWCOMP/n0r_0.png");
$d = date("d F Y h:i A" ,  time() );

mktitle($map, $img, "                  IEM Currents valid: $d");
$map->drawLabelCache($img);
mklogolocal($map, $img);


$url = $img->saveWebImage(MS_PNG);

?>
<html>
<head>
<script Language="JavaScript">
 function resetNavButtons(zoom){
   document.myform.zoom.value = zoom;
   document.myform.action = 'map.phtml'; 
   document.myform.target = 'map';
   document.panButton.src = "/GIS/apps/imagenav/button_pan_off.png";
   document.zoominButton.src = "/GIS/apps/imagenav/button_zoomin_off.png";
   document.zoomoutButton.src = "/GIS/apps/imagenav/button_zoomout_off.png";
   document.queryButton.src = "/GIS/apps/imagenav/button_query_off.png";
 }
 function resetButtons(){
   document.myform.action = 'ob.phtml'; 
   document.myform.target = 'ob';
   document.panButton.src = "/GIS/apps/imagenav/button_pan_off.png";
   document.zoominButton.src = "/GIS/apps/imagenav/button_zoomin_off.png";
   document.zoomoutButton.src = "/GIS/apps/imagenav/button_zoomout_off.png";
   document.queryButton.src = "/GIS/apps/imagenav/button_query_off.png";

 }
 function hideLayer( layerName) {
  if ( document.getElementById ) {
    var w = document.getElementById(layerName);
    w.style.display = 'none';
  }
 }
 function showLayer( layerName) {
  if ( document.getElementById ) {
    var w = document.getElementById(layerName);
    w.style.display = 'block';
  }
 }
 function setLayerDisplay( layerName) {
  hideLayer('layerSelect');
  hideLayer('networkSelect');
  showLayer(layerName);
}

</script>
  <meta http-equiv="refresh" content="120; <?php echo $uri; ?>">
  <link rel="stylesheet" type="text/css" href="/css/main.css" />
</head>
<body style="background: #eeeeee;">

<form name="myform" target="ob" action="ob.phtml" method="GET">

<b>Map Controls:</b>

<img src="/GIS/apps/imagenav/button_zoomin_off.png" name="zoominButton" alt="Zoom In"
  onClick="javascript: resetNavButtons(-2); document.zoominButton.src = '/GIS/apps/imagenav/button_zoomin_on.png';">

<img src="/GIS/apps/imagenav/button_pan_off.png" name="panButton" alt="Pan"
  onClick="javascript: resetNavButtons(1); document.panButton.src = '/GIS/apps/imagenav/button_pan_on.png';">

<img src="/GIS/apps/imagenav/button_zoomout_off.png" name="zoomoutButton" alt="Zoom Out"
  onClick="javascript: resetNavButtons(2); document.zoomoutButton.src = '/GIS/apps/imagenav/button_zoomout_on.png';">

<img src="/GIS/apps/imagenav/button_query_on.png" name="queryButton" alt="Query"
  onClick="javascript: resetButtons(); document.queryButton.src = '/GIS/apps/imagenav/button_query_on.png';">
<a href="map.phtml">Reset</a>

<input type="hidden" name="zoom" value="1">
<input type="hidden" name="extents" value="<?php echo $extents; ?>">


<input type="image" name="img" src="<?php echo $url; ?>">

</form>

<strong>Map Settings:</strong><br />
<table>
<tr>
<th><a href="javascript: setLayerDisplay('layerSelect', 'block');">Layers:</a></th>
<th><a href="javascript: setLayerDisplay('networkSelect', 'block');">Networks:</a></th>
</tr>
</table>

<div id="layerSelect" style="display: none;">
Layer Select Stuff
<hr>
<hr>
<hr>
<hr>
</div>

<div id="networkSelect" style="display: none;">
Network Select Stuff
<hr>
<hr>
<hr>
<hr>
</div>

</body>
</html>
