<?php
 $extents = $_GET['extents']; 
 $click_x = $_GET['img_x'];
 $click_y = $_GET['img_y'];
 $imgsz_x = 640;
 $imgsz_y = 480;

 $arExtents = explode(",", $extents);
 $ll_x = $arExtents[0];
 $ll_y = $arExtents[1];
 $ur_x = $arExtents[2];
 $ur_y = $arExtents[3];

 $dy = ($ur_y - $ll_y) / floatval($imgsz_y);
 $dx = ($ur_x - $ll_x) / floatval($imgsz_x);

 $centerX = ($click_x * $dx) + $ll_x ;
 $centerY = $ur_y - ($click_y * $dy) ;

 $sql = "SELECT s.*, c.* from summary s, current c WHERE c.station = (select station from current ORDER by distance(geom, setsrid(GeometryFromText('POINT($centerX $centerY)'), 4326)) ASC LIMIT 1) and c.station = s.station and s.day = 'TODAY'";

 $conn = pg_connect("dbname=iem port=9999 host=10.10.10.30");
 $rs = pg_exec($conn, $sql);
 $row = pg_fetch_array($rs,0);

function variablePrint($val, $name)
{
  if ($val < -50) return;
  $s = "<tr><th>$name</th><td>$val</td></tr>";
  return $s;
}

echo "<table>\n";
echo variablePrint($row["sname"], "Site");
echo variablePrint($row["valid"], "Ob Valid");
echo variablePrint($row["tmpf"], "Air Temp");

echo "</table>\n";
?>
