<?php
require_once "../../config/settings.inc.php";
define("IEM_APPID", 35);
require_once "../../include/myview.php";
$t = new MyView();
$t->title = "Open GIS Consortium Web Services";
$t->content = <<<EOF

<h3>OGC Web Services</h3>

<p>The <a href="http://www.opengeospatial.org">Open Geospatial Consortium, Inc</a> (OGC) 
        is a standards organization leading the development of geospatial and 
        location based services.  The OGC has adopted a number of specifications, 
        some of which are used by the IEM.  This page lists these services.</p>

<h4>Some items of note:</h4>
<ol>
 <li>All of these services are available via https:// connections.</li>
 <li>There are four DNS aliases for the website to allow web browers to make
    many simultaneous requests against these services.<br />
  <ol>
    <li>mesonet1.agron.iastate.edu</li> 
    <li>mesonet2.agron.iastate.edu</li> 
    <li>mesonet3.agron.iastate.edu</li>
    <li>www.mesonet.agron.iastate.edu</li>
   </ol>
   </li>
</ol>

<h3>Tile Map Service (TMS)</h3>

<p>Here are working examples using IEM TMS services within various Javascript
libraries.</p>

<div class="row">
<div class="col-md-3 well">
<h4>Bing Maps</h4>

<p>The Microsoft Bing Maps group kindly provided these two examples.</p>

<p><strong>Single Tile Layer:</strong>
<a href="https://www.bing.com/api/maps/sdk/mapcontrol/isdk#tileLayerPublicXYZoom+JS">example</a></p>

<p><strong>Animated Tile Layer:</strong>
<a href="https://www.bing.com/api/maps/sdk/mapcontrol/isdk#weatherRadarMap+JS">example</a></p>
</div>

<div class="col-md-3 well">
<h4>ESRI JS API</h4>
<p>Here is an <a href="arcgis_wtms.html">example</a> using the ESRI JS API. This
was contributed by Derek Swingley.
</div>

<div class="col-md-3 well">
<h4>Google Maps</h4>
<p>Here is <a href="googlemaps_v3.html">an example for Google Maps v3</a>. 
</div>

<div class="col-md-3 well">
<h4>OpenLayers</h4>
<p><a href="openlayers_example.html">Example</a> for OpenLayers v2.</p>

<p><a href="ol3_example.html">Example</a> for OpenLayers v3.</p>
</div>

</div><!-- ./row -->

<h4>Listing of Tile Map Services</h4>

<p>The following services are for Spherical Mercator (EPSG:3857) maps only.</p>

<table class="table table-striped table-condensed">
<thead>
<tr><th>Service Name</th><th>Description</th><th>Legend</th></tr>
</thead>

<tr><td>uscounties</td><td>US County Borders</td></tr>
<tr><td>usstates</td><td>US State Borders</td></tr>

<tr>
<td>Template: goes_<i>bird</i>_<i>sector</i>_ch<i>channel</i><br />
Example: goes_east_conus_ch02
</td>
<td>Current GOES R/S Imagery. Where: <br />
 <i>bird</i> is "east" or "west"<br />
 <i>sector</i> is "fulldisk", "alaska" (west only), "conus", "hawaii" (west only),
 "mesoscale-1", "mesoscale-2", "puertorico" (east only)<br />
 <i>channel</i> is two-digit, zero padded 01-16 <br />
 <a href="/GIS/goes.phtml">more info</a>.</td>
</tr>

<tr><td>Template: hrrr::REFD-FXXXX-0</td><td>Latest HRRR Reflectivity Forecasts, FXXXX is the forecast minute 
<a href="/GIS/model.phtml">more info</a></td></tr>
<tr><td>Template: hrrr::REFD-FXXXX-YYYYMMDDHHMI</td><td>Archived HRRR Reflectivity Forecasts, FXXXX is the forecast minute 
<a href="/GIS/model.phtml">more info</a></td></tr>

<tr><td>Template: ridge::XXX-XXX-0</td><td>Latest individual RADAR XXX data for product XXX 
<a href="../GIS/ridge.phtml">more info</a></td></tr>
<tr><td>Template: ridge::XXX-XXX-YYYYMMDDHHMI</td><td>Archived individual RADAR XXX data for product XXX 
<a href="../GIS/ridge.phtml">more info</a></td></tr>
<tr><td>nexrad-n0q-900913</td><td>NEXRAD Base Reflectivity current</td></tr>
<tr><td>nexrad-n0q-900913-m05m</td><td>... 5 minutes old ...</td></tr>
<tr><td>nexrad-n0q-900913-m10m</td><td>... 10 minutes old ...</td></tr>
<tr><td>nexrad-n0q-900913-m15m</td><td>... 15 minutes old ...</td></tr>
<tr><td>nexrad-n0q-900913-m20m</td><td>... 20 minutes old ...</td></tr>
<tr><td>nexrad-n0q-900913-m25m</td><td>... 25 minutes old ...</td></tr>
<tr><td>nexrad-n0q-900913-m30m</td><td>... 30 minutes old ...</td></tr>
<tr><td>nexrad-n0q-900913-m35m</td><td>... 35 minutes old ...</td></tr>
<tr><td>nexrad-n0q-900913-m40m</td><td>... 40 minutes old ...</td></tr>
<tr><td>nexrad-n0q-900913-m45m</td><td>... 45 minutes old ...</td></tr>
<tr><td>nexrad-n0q-900913-m50m</td><td>... 50 minutes old ...</td></tr>
<tr><td>nexrad-n0q-900913-m55m</td><td>... 55 minutes old ...</td></tr>
<tr><td>nexrad-eet-900913</td><td>NEXRAD Echo Tops EET current</td></tr>
<tr><td>nexrad-eet-900913-m05m</td><td>... 5 minutes old ...</td></tr>
<tr><td>nexrad-eet-900913-m10m</td><td>... 10 minutes old ...</td></tr>
<tr><td>nexrad-eet-900913-m15m</td><td>... 15 minutes old ...</td></tr>
<tr><td>nexrad-eet-900913-m20m</td><td>... 20 minutes old ...</td></tr>
<tr><td>nexrad-eet-900913-m25m</td><td>... 25 minutes old ...</td></tr>
<tr><td>nexrad-eet-900913-m30m</td><td>... 30 minutes old ...</td></tr>
<tr><td>nexrad-eet-900913-m35m</td><td>... 35 minutes old ...</td></tr>
<tr><td>nexrad-eet-900913-m40m</td><td>... 40 minutes old ...</td></tr>
<tr><td>nexrad-eet-900913-m45m</td><td>... 45 minutes old ...</td></tr>
<tr><td>nexrad-eet-900913-m50m</td><td>... 50 minutes old ...</td></tr>
<tr><td>nexrad-eet-900913-m55m</td><td>... 55 minutes old ...</td></tr>

<tr><td>q2-n1p-900913</td>
  <td>Q2 1 Hour Precipitation</td>
  <td><img src="/images/mrms_q3_p1h.png"></td>
  </tr> 
<tr><td>q2-p24h-900913</td>
  <td>Q2 24 Hour Precipitation</td>
  <td><img src="/images/mrms_q3_p24h.png"></td>
  </tr> 
<tr><td>q2-p48h-900913</td>
  <td>Q2 48 Hour Precipitation</td>
  <td><img src="/images/mrms_q3_p24h.png"></td>
  </tr> 
<tr><td>q2-p72h-900913</td>
  <td>Q2 72 Hour Precipitation</td>
  <td><img src="/images/mrms_q3_p24h.png"></td>
  </tr> 

  <tr><td>q2-hsr-900913</td><td>MRMS Hybrid-Scan Reflectivity Composite.</td></tr>
</table>

<h4>Web Map Service (WMS)</h4>

<p>A WMS defines a protocol for web based retrieval of geodata in raster map format. If you are interested in the capabilities XML file, simply add "VERSION=1.1.1&REQUEST=GetCapabilities&SERVICE=WMS&" to the URI string.</p>

<div class="iem-form">
<strong>Services</strong>
<ul>
<li>Iowa Precipitation
 <br /><code>https://mesonet.agron.iastate.edu/cgi-bin/wms/iowa/rainfall.cgi?</code></li>
<li>MRMS Q3 Precipitation (Missing data is grey)
 <br /><code>https://mesonet.agron.iastate.edu/cgi-bin/wms/us/mrms.cgi?</code>
 <br /><i>Layer:</i> <strong>mrms_p72h</strong> 72 Hour Precipitation
 <br /><i>Layer:</i> <strong>mrms_p48h</strong> 48 Hour Precipitation
 <br /><i>Layer:</i> <strong>mrms_p24h</strong> 24 Hour Precipitation
 <br /><i>Layer:</i> <strong>mrms_p1h</strong> One Hour Precipitation
 </li>
<li>MRMS Q3 Precipitation (Missing data is transparent)
 <br /><code>https://mesonet.agron.iastate.edu/cgi-bin/wms/us/mrms_nn.cgi?</code>
 <br /><i>Layer:</i> <strong>mrms_p72h</strong> 72 Hour Precipitation
 <br /><i>Layer:</i> <strong>mrms_p48h</strong> 48 Hour Precipitation
 <br /><i>Layer:</i> <strong>mrms_p24h</strong> 24 Hour Precipitation
 <br /><i>Layer:</i> <strong>mrms_p1h</strong> One Hour Precipitation
 </li>

 <hr />
 <li>GOES East Imagery (All Sectors, All 16 Channels)
<br /><code>https://mesonet.agron.iastate.edu/cgi-bin/wms/goes_east.cgi?</code>
<br /><i>Layer Template:</i> <strong>sector_chchannel</strong> ie conus_ch02</li>

<li>GOES West Imagery (All Sectors, All 16 Channels)
<br /><code>https://mesonet.agron.iastate.edu/cgi-bin/wms/goes_west.cgi?</code>
<br /><i>Layer Template:</i> <strong>sector_chchannel</strong> ie hawaii_ch02</li>

<hr />
<li>CONUS NEXRAD Base Reflectivity (n0q) 
 <br /><code>https://mesonet.agron.iastate.edu/cgi-bin/wms/nexrad/n0q.cgi?</code></li>
<li>Historical CONUS NEXRAD Base Reflectivity [WMS-T] (n0q) 
 <br /><code>https://mesonet.agron.iastate.edu/cgi-bin/wms/nexrad/n0q-t.cgi?</code></li>
 <li>Historical CONUS NEXRAD Base Reflectivity [WMS-T] (n0r) 
 <br /><code>https://mesonet.agron.iastate.edu/cgi-bin/wms/nexrad/n0r-t.cgi?</code></li>
<li>CONUS NEXRAD 8-bit Net Echo Tops (eet) 
 <br /><code>https://mesonet.agron.iastate.edu/cgi-bin/wms/nexrad/eet.cgi?</code></li>
<li>CONUS NEXRAD 1 Hour Precipitation (daa) 
 <br /><code>https://mesonet.agron.iastate.edu/cgi-bin/wms/nexrad/daa.cgi?</code></li>
<li>CONUS NEXRAD Net Echo Tops (net) 
 <br /><code>https://mesonet.agron.iastate.edu/cgi-bin/wms/nexrad/net.cgi?</code></li>
<li>CONUS NEXRAD Storm Total Precipitation (dta) 
 <br /><code>https://mesonet.agron.iastate.edu/cgi-bin/wms/nexrad/dta.cgi?</code></li>
<li>RIDGE Single NEXRAD Imagery 
 <br /><code>https://mesonet.agron.iastate.edu/cgi-bin/wms/nexrad/ridge.cgi?sector=XXX&amp;prod=XXX&amp;</code>
  <br />You also need to provide two CGI variables for the NEXRAD identifier
  and level III product you want. For example, sector=DMX&amp;prod=N0Q
  <br />
  <br /><i>Layer:</i> <strong>single</strong> Most recent image for the given 
        RADAR identifier and Level III product.  A simple JSON metadata file
        exists for each RADAR and Level III product combination, for example 
        <a href="/data/gis/images/4326/ridge/DMX/N0Q_0.json">DMX N0Q</a>.
  <br />
  <br /><i>Layer:</i> <strong>single-archive</strong> This allows request of
        a specific volume scan time from IEM's archive of imagery.  You need
        to specify the prod and sector like with the "single" layer, but also
        need to include a year, month, day and time.  All of these values are 
        in UTC.  Here's an <a href="https://mesonet.agron.iastate.edu/cgi-bin/wms/nexrad/ridge.cgi?service=wms&version=1.1.1&request=GetMap&format=png&TRANSPARENT=TRUE&bgcolor=0xCCCCFE&BBOX=-14215828.6745634,5401834.631799334,-13166501.150410566,6006604.399507464&SRS=EPSG:3857&width=1716&height=989&sector=RTX&prod=N0Q&layers=single-archive&year=2015&month=01&day=27&time=2303">example request</a>
        that gets NEXRAD RTX N0Q product for 27 Jan 2015 at 23:03 UTC.  You 
        must know the volume scan times prior to making the request.  There
        are <a href="/json/">JSON</a> services that can help you out. 
        Unfortunately, this service <strong>does not support WMS-T</strong> 
        due to complications with how I serve this information out, sorry.
 </li>
 
 <hr />
 <li>NWS Current Warnings
 <br /><code>https://mesonet.agron.iastate.edu/cgi-bin/wms/us/wwa.cgi?</code>
</li>
<li>Iowa Rainfall Estimates
 <br /><code>https://mesonet.agron.iastate.edu/cgi-bin/wms/iowa/rainfall.cgi?</code></li>
<li>Iowa Winter Road Conditions 
 <br /><code>https://mesonet.agron.iastate.edu/cgi-bin/wms/iowa/roadcond.cgi?</code>
 <br /><i>Layer:</i> <strong>roadcond-noninterstate</strong> Non Interstate Road Conditions
 <br /><i>Layer:</i> <strong>roadcond-interstate</strong> Interstate Road Conditions
</li>


</ul>
</div>

<h4>Web Feature Service (WFS)</h4>

<p>A WFS is a service that provides geodata as simple features in Geography Markup Language (GML).</p>

<div class="iem-form">
<strong>Services</strong>
<ul>

<!-- No worky at the moment
<li>Iowa Rainfall Estimates
 <br /><code>https://mesonet.agron.iastate.edu/wfs/rainfall.php?</code></li>
-->

<li>National Weather Service Warnings Current
 <br /><code>https://mesonet.agron.iastate.edu/wfs/ww.php?</code></li>

<li>National Weather Service Warnings Archive For UTC Date (since 11 Jul 2002)
 <br /><code>https://mesonet.agron.iastate.edu/wfs/ww.php?date=YYYY-MM-DD&amp;</code></li>

<li>National Weather Service Warnings Archive At Given UTC Time(since 11 Jul 2002)
 <br /><code>https://mesonet.agron.iastate.edu/wfs/ww.php?date=YYYY-MM-DD&amp;time=HH:MI&amp;</code></li>


</ul>
</div>
EOF;
$t->render('single.phtml');
