<?php
include("../../config/settings.inc.php");
$TITLE = "IEM | Open GIS Consortium Web Services";
$THISPAGE = "gis-ogc";
include("$rootpath/include/header.php"); ?>


<h3 class="heading">OGC Web Services</h3>

<p>The <a href="http://www.opengeospatial.org">Open Geospatial Consortium, Inc</a> (OGC) is a standards organization leading the development of geospatial and location based services.  The OGC has adopted a number of specifications, some of which are used by the IEM.  This page lists these services.</p>

<h4>Tile Map Service (TMS)</h4>

<p>This service makes for easy integration with web mapping applications like 
OpenLayers and Google Maps.  Here is an example for Google Maps:</p>

<pre style="border-top: 1px solid #ccc; background: #EEFFCC; border-bottom: 1px solid #ccc; padding-left: 5px;">
var tileNEX = new GTileLayer(null,null,null); 
tileNEX.getTileUrl = function(tile,zoom) {
   /* Include date at the end as a cachebuster */
   return "http://mesonet.agron.iastate.edu/cache/tile.py/1.0.0/nexrad-n0r-900913/"
   + zoom + "/" + tile.x + "/" + tile.y +".png?"+ (new Date()).getTime(); 
};
tileNEX.isPng = function() { return true;};
tileNEX.getOpacity = function() { return 0.5; }


var layer4=[G_NORMAL_MAP.getTileLayers()[0],tileNEX]; 
var custommap4 = new GMapType(layer4, G_SATELLITE_MAP.getProjection(), "Nexrad", G_SATELLITE_MAP);
map.addMapType(custommap4);
</pre>

<p>The <i>nexrad-n0r-900913</i> is the layer name and represents the "current" composite base reflectivity.  There are also these other layers available from the TMS:
<ul>
 <li><i>nexrad-n0r-900913-m05m</i>: Composite 5 minutes old</li>
 <li><i>nexrad-n0r-900913-m10m</i>: Composite 10 minutes old</li>
 <li><i>nexrad-n0r-900913-m15m</i>: Composite 15 minutes old</li>
 <li><i>nexrad-n0r-900913-m20m</i>: Composite 20 minutes old</li>
 <li><i>nexrad-n0r-900913-m25m</i>: Composite 25 minutes old</li>
 <li><i>nexrad-n0r-900913-m30m</i>: Composite 30 minutes old</li>
 <li><i>nexrad-n0r-900913-m35m</i>: Composite 35 minutes old</li>
 <li><i>nexrad-n0r-900913-m40m</i>: Composite 40 minutes old</li>
 <li><i>nexrad-n0r-900913-m45m</i>: Composite 45 minutes old</li>
 <li><i>nexrad-n0r-900913-m50m</i>: Composite 50 minutes old</li>
 <li><i>conus-goes-ir-4km-900913</i>: GOES CONUS Infrared ~4km</li>
 <li><i>conus-goes-wv-4km-900913</i>: GOES CONUS Water Vapor ~4km</li>
 <li><i>conus-goes-vis-1km-900913</i>: GOES CONUS Visible ~1km</li> 
</ul>

<h4>Web Map Service (WMS)</h4>

<p>A WMS defines a protocol for web based retrieval of geodata in raster map format. If you are interested in the capabilities XML file, simply add "VERSION=1.1.1&REQUEST=GetCapabilities&SERVICE=WMS&" to the URI string.</p>

<div class="iem-form">
<strong>Services</strong>
<ul>
<li>CONUS GOES Infrared Satellite
 <br /><code>http://mesonet.agron.iastate.edu/cgi-bin/wms/goes/conus_ir.cgi?</code></li>
<li>CONUS GOES Visible Satellite
 <br /><code>http://mesonet.agron.iastate.edu/cgi-bin/wms/goes/conus_vis.cgi?</code></li>
<li>GOES East infrared imagery
<br /><code>http://mesonet.agron.iastate.edu/cgi-bin/wms/goes/east_ir.cgi?</code></li>
<li>GOES West infrared imagery
<br /><code>http://mesonet.agron.iastate.edu/cgi-bin/wms/goes/west_ir.cgi?</code></li>
<li>GOES East visible imagery
<br /><code>http://mesonet.agron.iastate.edu/cgi-bin/wms/goes/east_vis.cgi?</code></li>
<li>GOES West visible imagery
<br /><code>http://mesonet.agron.iastate.edu/cgi-bin/wms/goes/west_vis.cgi?</code></li>
<li>CONUS NEXRAD Base Reflectivity (n0r) 
 <br /><code>http://mesonet.agron.iastate.edu/cgi-bin/wms/nexrad/n0r.cgi?</code></li>
<li>Historical CONUS NEXRAD Base Reflectivity [WMS-T] (n0r) 
 <br /><code>http://mesonet.agron.iastate.edu/cgi-bin/wms/nexrad/n0r-t.cgi?</code></li>
<li>CONUS NEXRAD 1 Hour Precipitation (n1p) 
 <br /><code>http://mesonet.agron.iastate.edu/cgi-bin/wms/nexrad/n1p.cgi?</code></li>
<li>CONUS NEXRAD Storm Total Precipitation (ntp) 
 <br /><code>http://mesonet.agron.iastate.edu/cgi-bin/wms/nexrad/ntp.cgi?</code></li>
<li>NWS Current Warnings
 <br /><code>http://mesonet.agron.iastate.edu/cgi-bin/wms/us/wwa.cgi?</code>
</li>

<li>Iowa Rainfall Estimates
 <br /><code>http://mesonet.agron.iastate.edu/cgi-bin/wms/iowa/rainfall.cgi?</code></li>

<li>Iowa Winter Road Conditions 
 <br /><code>http://mesonet.agron.iastate.edu/cgi-bin/wms/iowa/roadcond.cgi?</code>
 <br /><i>Layer:</i> <strong>roadcond-noninterstate</strong> Non Interstate Road Conditions
 <br /><i>Layer:</i> <strong>roadcond-interstate</strong> Interstate Road Conditions
</li>


</ul>
</div>

<h4>Web Feature Service (WFS)</h4>

<p>A WFS is a service that provides geodata as simple features in Geography Markup Language (GML).</p>

<div class="iem-form">
<strong>Services</strong>
<ul>

<!-- No worky at the moment
<li>Iowa Rainfall Estimates
 <br /><code>http://mesonet.agron.iastate.edu/wfs/rainfall.php?</code></li>
-->

<li>National Weather Service Warnings Current
 <br /><code>http://mesonet.agron.iastate.edu/wfs/ww.php?</code></li>

<li>National Weather Service Warnings Archive (since 11 Jul 2002)
 <br /><code>http://mesonet.agron.iastate.edu/wfs/ww.php?date=YYYY-MM-DD&amp;</code></li>


</ul>
</div>


<?php include("$rootpath/include/footer.php"); ?>
