<?php 
 include("../../config/settings.inc.php"); 
 include "../../include/myview.php";
 
 include "../../include/database.inc.php";
 include "../../include/network.php";
 include "../../include/mlib.php";
 $nt = new NetworkTable("ISUSM");

 $jdata = file_get_contents("http://iem.local/api/1/currents.json?network=ISUSM");
 $jobj = json_decode($jdata, $assoc=TRUE);

 $table = "<table class='table table-striped table-bordered table-condensed'>
 		<tr><th rowspan='2'>Location</th>
 		<th rowspan='2'>Valid</th>
 		<th colspan='3'>Air Temp &deg;F</th>
 		<th colspan='3'>Wind MPH</th>
 		<th colspan='2'>Rain inch</th>
 		<th>4 inches</th>
 		<th colspan='2'>12 inches</th>
 		<th colspan='2'>24 inches</th>
 		<th colspan='2'>50 inches</th>
 		</tr>
 		<tr>
 		<th>Ob</th><th>High</th><th>Low</th>
 		<th>Speed</th><th>Gust</th><th>Today's Peak</th>
 		<th>Hour</th><th>Day</th>
 		<th>Temp &deg;F</th><th>Temp &deg;F</th><th>Moist %</th>
 		<th>Temp &deg;F</th><th>Moist %</th>
 		<th>Temp &deg;F</th><th>Moist %</th>
 		</tr>";
 $offline = Array();
 $threshold = time() - 86400;
 while (list($bogus, $data)=each($jobj["data"])) {
     $sid = $data["station"];
 	$uri = sprintf("/sites/site.php?station=%s&network=ISUSM", $sid);
 	
 	$ts = strtotime($data["local_valid"]);
 	if ($ts < $threshold){
 		$offline[] = sprintf("<a href=\"%s\">%s</a>", $uri,
				 $nt->table[$sid]['name']);
 		continue;
 	}
 	
 	$pday = ($data['pday'] < 0) ? 0 : $data['pday'];
 	$table .= sprintf("<tr><td><a href=\"%s\">%s</a></td><td>%s</td>
 			<td>%.1f</td><td>%.1f</td><td>%.1f</td>
 			<td>%s @ %.0f</td><td>%.0f</td><td>%.0f @ %s</td>
 			<td>%.2f</td><td>%.2f</td><td>%.1f</td><td>%.1f</td><td>%s</td>
 			<td>%.1f</td><td>%s</td>
 			<td>%.1f</td><td>%s</td></tr>", $uri, $nt->table[$sid]['name'],
 			date("g A", $ts), $data["tmpf"],
 			$data["max_tmpf"], $data["min_tmpf"], 
 			drct2txt($data["drct"]), $data["sknt"] * 1.15,
 			$data['gust'] * 1.15, $data['max_gust'] * 1.15,
 			date("g:i A", strtotime($data['local_max_gust_ts'])),
 			$data['phour'], $pday, $data["c1tmpf"],
 			$data["c2tmpf"], 
			($data["c2smv"] < 0) ? "Frozen": round($data["c2smv"],1),
 			 $data["c3tmpf"], 
 			($data["c3smv"] < 0) ? "Frozen": round($data["c3smv"],1),
 			$data["c4tmpf"], 
 			($data["c4smv"] < 0) ? "Frozen": round($data["c4smv"],1) 
 	);
 }
 
 $table .= "</table>";
 if (sizeof($offline) > 0){
 	$table .= sprintf("<br />Sites Offline: %s", implode($offline, ","));
 }
 $v = isset($_REQUEST["v"]) ? htmlentities($_REQUEST["v"]): 'tmpf';
 $t = new MyView();
 $t->current_network = "ISUSM";
 $t->title = "ISU Ag Climate Sortable Currents"; 
 $t->thispage = "networks-agclimate";

 $t->breadcrumbs = <<<EOF
 <ol class="breadcrumb">
 <li><a href="/agclimate">ISU Soil Moisture Network</a></li>
 <li class="active">Sortable Currents</li>
 </ol>
EOF;
 $t->content = <<<EOF
 
<p>We are in the process of deploying a network of automated sensors that will
measure soil temperature and moisture.  Here is the most recent observation 
collected:
<br />
{$table}


EOF;

$t->render('sortables.phtml');
?>