<?php 
 include("../../config/settings.inc.php");
 define("IEM_APPID", 10); 
 include "../../include/myview.php"; 
 include "../../include/mlib.php";
 $t = new MyView();
 $t->title = "ISU Ag Climate"; 
 $t->thispage = "networks-agclimate";
 
$t->jsextra = <<<EOF
<script src='/vendor/openlayers/3.9.0/ol.js'></script>
<script src='/vendor/openlayers/3.9.0/ol3-layerswitcher.js'></script>
<script src="/vendor/jquery-ui/1.11.4/jquery-ui.js"></script>
<script src='dataexplorer.js?v=4'></script>
<script src="/assets/jquery-timepicker/1.5.3/jquery-ui-timepicker-addon.min.js"></script>
<script src="/assets/jquery-timepicker/1.5.3/jquery-ui-sliderAccess.js"></script>
EOF;

$dt = date("Y/m/d H:00", time() - (20*60));
$t->headextra = <<<EOF
<link rel="stylesheet" type="text/css" href="/vendor/openlayers/3.9.0/ol.css"/ >
<link rel="stylesheet" type="text/css" href="/vendor/openlayers/3.9.0/ol3-layerswitcher.css"/ >
<link rel="stylesheet" type="text/css" href="/assets/jquery-timepicker/1.5.3/jquery-ui-timepicker-addon.min.css"/ >
<link rel="stylesheet" type="text/css" href="/vendor/jquery-ui/1.11.4/jquery-ui.min.css"/ >
<script>
	var defaultdt = "{$dt}";
</script>
<style>
  #map {
    width: 100%;
    height: 400px;
  }
.popover-content {
  min-width: 180px;
}
</style>
EOF;
 
 $t->content = <<<EOF

<h3><span class="badge">New!</span> ISU Soil Moisture Network</h3>
 <div class="alert alert-info">
 Iowa State University is in the process of deploying a new network of 
 automated weather equipment with the standard suite of weather instruments 
 along with soil temperature and moisture sensors.  The soil moisture data is
 a work-in-progress as a calibration step is yet necessary at many of the sites.
 </div>
 
<form name="mapper">
<div class="row">
	<div class="col-md-3 col-sm-5 well">

<h4>Available Tools:</h4>
<div class="list-group">
<a href="/agclimate/soilt.php" class="list-group-item"><i class="glyphicon glyphicon-picture"></i> County Soil Temp Map</a>
<a href="hist/daily.php" class="list-group-item"><i class="glyphicon glyphicon-cloud-download"></i>  Daily Data Download</a>
<a href="hist/hourly.php" class="list-group-item"><i class="glyphicon glyphicon-cloud-download"></i> Hourly Data Download</a>
<a href="/sites/networks.php?network=ISUSM" class="list-group-item"><i class="glyphicon glyphicon-info-sign"></i> Listing of Stations</a>
<a href="smts.php" class="list-group-item"><i class="glyphicon glyphicon-signal"></i> Plot Time Series</a>
<a href="info.phtml" class="list-group-item"><i class="glyphicon glyphicon-wrench"></i> Sensor Package</a>
<a href="current.phtml" class="list-group-item"><i class="glyphicon glyphicon-refresh"></i> Sortable Currents</a>
<a href="/sites/locate.php?network=ISUSM" class="list-group-item"><i class="glyphicon glyphicon-info-sign"></i> Station Metadata</a>
<a href="/agclimate/usage/" class="list-group-item"><i class="glyphicon glyphicon-signal"></i> Website Usage Stats</a>
</div>

	</div>
	<div class="col-md-9 col-sm-7">
	
<div class="row">
<div class="col-md-6">
	<h4>Select Time:</h4> 
<input type="text" id="datetimepicker" name="dosomething" />
<br />
 <button type="button" class="btn btn-default btn-xs" id="minusoneday">-1 Day</button>
 <button type="button" class="btn btn-default btn-xs" id="minusonehour">-1 HR</button>
 <button type="button" class="btn btn-default btn-xs" id="plusonehour">+1 HR</button>
 <button type="button" class="btn btn-default btn-xs" id="plusoneday">+1 Day</button>
</div>
<div class="col-md-6">
<h4>Select Variable:</h4>
<select name="varname" id="varpicker">
	<option value="tmpf">Air Temperature [F]</option>
	<option value="bat">Battery Voltage [V]</option>
	<option value="encrh_avg">Logger Enclosure Rel Humid [%]</option>
	<option value="et">Evapotranspiration [inch]</option>
	<option value="high">Daily High Temperature [F]</option>
	<option value="low">Daily Low Temperature [F]</option>
	<option value="pday">Daily Precipitation [inch]</option>
	<option value="hrprecip">Hourly Precipitation [inch]</option>
	<option value="radmj">Hourly Radiation [MJ]</option>
	<option value="rh">Relative Humidity [%]</option>
	<option value="soil12m">Soil Moisture (12 inch) [Vol %]</option>
	<option value="soil24m">Soil Moisture (24 inch) [Vol %]</option>
	<option value="soil50m">Soil Moisture (50 inch) [Vol %]</option>
	<option value="soil04t">Soil Temperature (4 inch) [F]</option>
	<option value="soil12t">Soil Temperature (12 inch) [F]</option>
	<option value="soil24t">Soil Temperature (24 inch) [F]</option>
	<option value="soil50t">Soil Temperature (50 inch) [F]</option>
	<option value="wind">Wind Direction + Speed [mph]</option>
	<option value="gust">Wind Gust [mph]</option>
</select>
</div></div>
	
 		<span id="maptitle">The map is displaying Air Temperature [F] valid at {$dt}</span>
		<div id="map"></div>
 		<div id="popup" title="Station Information"></div>
	</div>
</div>
</form>

<div class="alert alert-info">
 <h4>Rainfall Disclaimer:</h4>
<p>The Soil Moisture Network uses a non-heated tipping bucket rain gage and is
unable to measure snowfall. If you are interested in higher quality 
precipitation data, check out the <a href="/COOP/">NWS COOP</a> network
of human observations.</div>
 				
 				
<h3>Legacy ISU AgClimate Network</h3>

<div class="alert alert-danger"><span class="badge">23 April 2014:</span> Data
 is no longer being collected from these stations.  You will want to 
 use the "Soil Moisture Network" above as your source for this type of data.
 </div> 
 				
<p>The Iowa State University "Ag Climate" network is one of the nation's 
oldest automated weather observation networks with data dating back to 1986.
These stations are scheduled to be removed during the spring of 2014.</p>

<div class="row">
 	<div class="col-md-4 col-sm-4">
 		<h4>Available Tools:</h4>
<ul>
 <li><a href="hist/hourlyRequest.php">Hourly Data Download</a></li>
<li><a href="hist/dailyRequest.php">Daily Data Download</a></li>
<li><a href="/GIS/apps/agclimate/gsplot.phtml">Growing Season</a></li>
<li><a href="soilt.php">4 inch Soil Temperatures</a></li>
<li><a href="/GIS/apps/agclimate/gsplot.phtml">Growing Season Maps</a></li>
<li><a href="/plotting/agc/">Time Series Charts</a></li>
<li><a href="soilt-prob.php">4 inch Soil Temperature Probabilities</a></li>
<li><a href="/GIS/apps/agclimate/dayplot.phtml">Daily Data Plotter</a></li>
</ul>			
 	</div>
 	<div class="col-md-4 col-sm-4">
 	<h4>Information:</h4>
<ul>
<li><a href="/agclimate/info.phtml">Information</a> about network stations.</li>
<li><a href="http://www.hprcc.unl.edu/awdn/et/">Information on PET</a> calculations done by the High Plains Climate Center.</li>
</ul>		
 	<h4>Accumulated values:</h4>
<ul>
 	<li><a href="display.php?prod=10">Monthly evapotranspiration</a></li>
    <li><a href="display.php?prod=11">Monthly rainfall</a></li>
    <li><a href="display.php?prod=12">Standard Chill Units since 1 Sept</a></li>
</ul>	
 	</div>
 	<div class="col-md-4 col-sm-4">
 <h4>Plots:</h4>
<ul>
  <li><a href="display.php?prod=1">Max/Min Air Temps</a></li>
  <li><a href="display.php?prod=2">Avg 4in Soil Temps</a></li>
  <li><a href="display.php?prod=3">Max/Min 4in Soil Temps</a></li>
  <li><a href="/agclimate/soilt.php">County-based Soil Temps</a></li>
  <li><a href="display.php?prod=4">Solar Radiation Values</a></li>
  <li><a href="/GIS/apps/agclimate/dayplot.phtml?pvar=c90">Precipitation</a></li>
  <li><a href="display.php?prod=6">Potential E-T</a></li>
  <li><a href="display.php?prod=7">Peak Wind Gust (5 sec)</a></li>
  <li><a href="display.php?prod=8">Average Wind Speed</a></li>
  <li><a href="display.php?prod=9">Max/Min Dew Points</a></li>				
</ul>
 	</div>
</div>

EOF;

$t->render('single.phtml');
?>