<?php
 include("../../config/settings.inc.php");
 $TITLE = "IEM | ISU Ag Climate";
 $THISPAGE = "networks-agclimate";
 include("$rootpath/include/header.php");
?>

<h3>ISU Agclimate Data information</h3>

<table>
<caption>Station Id conversion table</caption>
<tr><th>StationId:</th><th>Station Name:</th><th>Data Starts At:</th><th>Data Ends At:</th></tr>
<tr><td>a130209</td><td>Ames</td><td>Jul 01, 1986</td><td>Current</td></tr>
<tr><td>a131069</td><td>Calmar</td><td>Sep 21, 2001 </td><td>Current</td></tr>  
<tr><td>a131299</td><td>Castana</td><td>May 19, 1988</td><td>Current</td></tr>
<tr><td>a131329</td><td>Cedar Rapids </td><td>Jun 22, 1998</td><td>Current</td></tr>
<tr><td>a131559</td><td>Chariton</td><td>Aug 17, 1988</td><td>Current</td></tr>
<tr><td>a131909</td><td>Crawfordsville</td><td>Jan 01, 1990</td><td>Current</td></tr>
<tr><td>a130219</td><td>Gilbert</td><td>Aug 28, 1986</td><td>Current</td></tr>
<tr><td>a135879</td><td>Nashua</td><td>Sep 01, 1988</td><td>Current</td></tr>
<tr><td>a138019</td><td>Sutherlan</td><td>Jul 23, 1988</td><td>Current</td></tr>
<tr><td>a134759</td><td>Lewis</td><td>Jun 19, 1997</td><td>Current</td></tr>
<tr><td>a136949</td><td>Rhodes</td><td>May 17, 1999</td><td>Oct 11,2006</td></tr>
<tr><td>a134309</td><td>Kanawha</td><td>Jun 19, 1997</td><td>Current</td></tr>
<tr><td>a135849</td><td>Muscatine</td><td>Mar 27, 2000</td><td>Current</td></tr>
</table>
<!--
<tr><td>a133259</td><td>          </td><td>Jan 01, 1990</td><td>Current</td></tr>
-->

<p>You can get lat/lon information from <a href="<?php echo $rooturl; ?>/sites/networks.php?network=ISUAG&format=html">this page</a>.

<h4>Units for Data</h4>

<table>
<tr><td>Precipation</td><td>inches</td></tr>
<tr><td>Hourly Solar Radiation</td><td>Kilo calories per hour per meter squared</td></tr>
<tr><td>Daily Solar Radiation</td><td>Langleys</td></tr>
<tr><td>Temperatures</td><td>Fahrenhit</td></tr>
<tr><td>Wind speeds</td><td>MPH</td></tr>
<tr><td>Time</td><td>local time, either CST or CDT</td></tr>
</table>

<h4>Hardware Specs</h4>

<p><strong>Temperature:</strong> All of our stations have either the Campbell HMP35 or HMP45.  The 35 was discontinued and replaced with the 45.

<br /><br /><strong>Solar Radiation:</strong> LI-COR pyranometer, model <a href="http://www.campbellsci.com/li200x-l">LI200X</a>.

<?php include("$rootpath/include/footer.php"); ?>
