<?php
include("../../config/settings.inc.php");
 $TITLE = "IEM | QC | Active Trouble Tickets";
include("$rootpath/include/header.php");
include("$rootpath/include/database.inc.php");
?>

<div class="text">
<a href="/QC/">Quality Control</a> > <b>Active Trouble Tickets</b>

<?php
 $conn = iemdb("portfolio");
 $rs = pg_exec($conn, "SELECT *, getSiteName(s_mid) as s_name from tt_base 
    WHERE status != 'CLOSED' ORDER by id ASC");
 pg_close($conn);

 $ars = Array("iaawos" => "", "iarwis" => "", "kcci" => "", "kelo" => "",
 "kimt" => "");
 
 for( $i=0; $row = @pg_fetch_array($rs,$i); $i++)
 {
   $entered = strtotime(substr($row["entered"],0,16));
   $last = strtotime(substr($row["last"],0,16));
   $s = "<tr>
     <th>". $row["id"] ."</th>
     <td>". $row["status"] ."</td>
     <td>". strftime("%Y-%m-%d", $entered) ."</td>
     <td>". strftime("%Y-%m-%d", $last) ."</td>
     <td>[". $row["s_mid"] ."] ". $row["s_name"] ."</td>
     <td>". $row["subject"] ."</td>
     </tr>";
   $ars[$row["portfolio"]] .= $s;
 }
?>

<p>

The IEM developed a system called "IEM Tracker" to track meta-data 
of sites in our component networks.  This page presents a listing of 
'Trouble Tickets' that are currently active.  Currently, only the ticket
header is presented, but in the future more info will be made publicly 
available.  If you have any questions or comments about a ticket listed,
please feel free to <a href="/info/contacts.php">Contact Us</a>.
</div>

<h3 class="subtitle">Iowa AWOS network</h3>
<table border=1 cellpadding=2 cellspacing=0>
<tr>
 <th>ID</th><td>Status:</td><td>Opened:</td><td>Updated:</td><td>Site:</td><td>Ticket Topic:</td></tr>
<?php echo $ars["iaawos"]; ?>
</table><br><br>

<h3 class="subtitle">Iowa RWIS network</h3>
<table border=1 cellpadding=2 cellspacing=0>
<tr>
 <th>ID</th><td>Status:</td><td>Opened:</td><td>Updated:</td><td>Site:</td><td>Ticket Topic:</td></tr>
<?php echo $ars["iarwis"]; ?>
</table><br><br>

<h3 class="subtitle">KCCI SchoolNet</h3>
<table border=1 cellpadding=2 cellspacing=0>
<tr>
 <th>ID</th><td>Status:</td><td>Opened:</td><td>Updated:</td><td>Site:</td><td>Ticket Topic:</td></tr>
<?php echo $ars["kccisnet"]; ?>
</table><br><br>

<h3 class="subtitle">KELO WeatherNet</h3>
<table border=1 cellpadding=2 cellspacing=0>
<tr>
 <th>ID</th><td>Status:</td><td>Opened:</td><td>Updated:</td><td>Site:</td><td>Ticket Topic:</td></tr>
<?php echo $ars["kelosnet"]; ?>
</table><br><br></div>

<h3 class="subtitle">KIMT WeatherNet</h3>
<table border=1 cellpadding=2 cellspacing=0>
<tr>
 <th>ID</th><td>Status:</td><td>Opened:</td><td>Updated:</td><td>Site:</td><td>Ticket Topic:</td></tr>
<?php echo $ars["kimtsnet"]; ?>
</table><br><br></div>


<?php include("$rootpath/include/footer.php"); ?>
