<?php 
require_once "../../../config/settings.inc.php";
require_once "../../../include/myview.php";
$t = new MyView();
$t->title = "Gibson Ridge Placefiles";
$t->thispage = "current-placefiles";
$t->content = <<<EOF

<h3>IEM Data in Gibson Ridge Placefile format</h3>

<p><a href="http://www.grlevelx.com">Gibson Ridge Software</a> develops 
a very popular set of RADAR data visualization programs.  These placefiles
can be freely used for educational use.  Use of the non government data 
"on-air" by media is strictly not allowed without permission of the 
provider.</p>

<div class="row well">
<div class="col-sm-12">

<h3>Placefile Range Ring Generator</h3>
<form method="GET" action="/cgi-bin/request/grx_rings.py" name="rings">

<p>Contributed by Zach Hiris, this generates a static placefile with range
rings specified at the given distance for a point.</p>

<div class="row">
<div class="col-sm-4">
<strong>Location Label:</strong><br />
<input type="text" name="loc" value="My Location">
</div>
<div class="col-sm-4">
<strong>Latitude (degrees N)</strong>
<input type="text" name="lat" value="42.00">
</div>
<div class="col-sm-4">
<strong>Longitude (degrees E)</strong>
<input type="text" name="lon" value="-94.33">
</div>
</div>


<table class="table">
<thead><tr><th>Ring</th><th>Miles</th><th>Red (0-255)</th><th>Green (0-255)</th>
<th>Blue (0-255)</th><th>Alpha (0-255)</th></tr></thead>

<tbody>
<tr>
  <td>1</td>
  <td><input type="text" size="5" maxlength="5" name="m0" value="100"></td>
  <td><input type="text" size="5" maxlength="3" name="r0" value="255"></td>
  <td><input type="text" size="5" maxlength="3" name="g0" value="255"></td>
  <td><input type="text" size="5" maxlength="3" name="b0" value="0"></td>
  <td><input type="text" size="5" maxlength="3" name="a0" value="255"></td>
  </tr>
<tr>
  <td>2</td>
  <td><input type="text" size="5" maxlength="5" name="m1" value="0"> (0 disables)</td>
  <td><input type="text" size="5" maxlength="3" name="r1" value="255"></td>
  <td><input type="text" size="5" maxlength="3" name="g1" value="255"></td>
  <td><input type="text" size="5" maxlength="3" name="b1" value="0"></td>
  <td><input type="text" size="5" maxlength="3" name="a1" value="255"></td>
  </tr>
<tr>
  <td>3</td>
  <td><input type="text" size="5" maxlength="5" name="m2" value="0"> (0 disables)</td>
  <td><input type="text" size="5" maxlength="3" name="r2" value="255"></td>
  <td><input type="text" size="5" maxlength="3" name="g2" value="255"></td>
  <td><input type="text" size="5" maxlength="3" name="b2" value="0"></td>
  <td><input type="text" size="5" maxlength="3" name="a2" value="255"></td>
  </tr>

</table>
</table>
<input type="submit" value="Generate Placefile">
</form>
</div>
</div>

<p>
<table class="table table-striped">
		<thead><tr><th>Title</th><th>Description</th></tr></thead>
<tr>
  <th><a href="iadot_trucks.txt">Iowa DOT Truck Locations</a></th>
  <td>https://mesonet.agron.iastate.edu/request/grx/iadot_trucks.txt<br />
  <i>Notes:</i>  Locations of Iowa DOT Snow Plows.</td>
</tr>
<tr>
  <th><a href="roadcond.php">Iowa Winter Road Conditions</a></th>
  <td>https://mesonet.agron.iastate.edu/request/grx/roadcond.php<br />
  <i>Notes:</i>  Observations provided by the Iowa State Patrol.</td>
</tr>
<tr>
  <th><a href="asos.php">Iowa AWOS Data</a></th>
  <td>https://mesonet.agron.iastate.edu/request/grx/asos.php<br />
  <i>Notes:</i>  none at this time</td>
</tr>
<tr>
  <th><a href="rwis.php">Iowa RWIS Data</a></th>
  <td>https://mesonet.agron.iastate.edu/request/grx/rwis.php<br />
  <i>Notes:</i>  Could use some data presentation improvements (TODO)</td>
</tr>
<tr>
  <th><a href="webcams.php?overview">IEM Webcam Overview</a></th>
  <td>https://mesonet.agron.iastate.edu/request/grx/webcams.php?overview<br />
  <i>Notes:</i>  This layer provides the locations and direction
that the webcam is looking.  <b>This layer should be used along with the
individual network layers...</b> There aren't bandwidth concerns with this 
layer.</td>
</tr>
<tr>
  <th><a href="webcams.php?network=KCCI">KCCI-TV Webcams</a></th>
  <td>https://mesonet.agron.iastate.edu/request/grx/webcams.php?network=KCCI<br />
  <i>Notes:</i>  You will not want to use this on a low bandwidth 
connection as all of the webcam images are loaded every 1-5 minutes.  Please
only use this layer when you are using the data!  Thanks...</td>
</tr>
<tr>
  <th><a href="webcams.php?network=KELO">KELO-TV Webcams</a></th>
  <td>https://mesonet.agron.iastate.edu/request/grx/webcams.php?network=KELO<br />
  <i>Notes:</i>  You will not want to use this on a low bandwidth
connection as all of the webcam images are loaded every 1-5 minutes.  Please
only use this layer when you are using the data!  Thanks...</td>
</tr>
<tr>
  <th><a href="webcams.php?network=KCRG">KCRG-TV Webcams</a></th>
  <td>https://mesonet.agron.iastate.edu/request/grx/webcams.php?network=KCRG<br />
  <i>Notes:</i>  You will not want to use this on a low bandwidth
connection as all of the webcam images are loaded every 1-5 minutes.  Please
only use this layer when you are using the data!  Thanks...</td>
</tr>

<tr>
  <th><a href="l3attr.txt">NEXRAD Level3 Attributes</a></th>
  <td>https://mesonet.agron.iastate.edu/request/grx/l3attr.txt<br />
  <i>Notes:</i> This is a placefile of the level3 NEXRAD storm attributes. This
may be useful when looking at level2 data.  You can optionally pass a nexrad
		3 character ID to limit the display to a certain NEXRAD. ie)
		l3attr.txt?nexrad=DMX .  Otherwise, the service will utilize the
		longitude and latitude passed to the server by the Gibson Ridge Client
		to limit the displayed attributes.</td>
</tr>

<tr>
  <th><a href="watch_by_county.php">SPC Watch by County</a></th>
  <td>https://mesonet.agron.iastate.edu/request/grx/watch_by_county.php?<br />
  <i>Notes:</i> This is a placefile of the union of counties within a
  Storm Prediction Center watch.  You can optionally pass an option
  <code>alpha=255</code> to set the alpha value for the used color.  This value
  is a number between 0 and 255. The
  service uses the official NWS colors for Severe Thunderstorm Watch (#DB7093)
  and Tornado Watch (yellow).</td>
</tr>

<tr>
  <th><a href="time_mot_loc.php">NWS Warning TIME...MOT...LOC</a> (TOR)</th>
  <td>https://mesonet.agron.iastate.edu/request/grx/time_mot_loc.php?<br />
  <i>Notes:</i> This provides lines indicating the path of travel for
  tornado warnings based on the coding within the warning.</td>
</tr>

<tr>
  <th><a href="time_mot_loc.php?all">NWS Warning TIME...MOT...LOC</a> (TOR+SVR)</th>
  <td>https://mesonet.agron.iastate.edu/request/grx/time_mot_loc.php?all<br />
  <i>Notes:</i> This provides lines indicating the path of travel for
  tornado and severe thunderstorm warnings based on the coding within the warning.</td>
</tr>


</table>
EOF;
$t->render('single.phtml');
?>
