<?php 
include("../../../config/settings.inc.php");
include_once "../../../include/myview.php";
$t = new MyView();
$t->title = "NWS COOP Daily Normals";
$t->thispage = "climatology-today";
include("../../../include/imagemaps.php"); 
require_once "../../../include/forms.php";

$year = date("Y");
$nselect = networkSelect("IACLIMATE", "");
$mselect = monthSelect("month");
$dselect = daySelect("day");

$t->content = <<<EOF

<p>With this interface, you can download daily climate normals for NWS COOP
sites.  Please fill out the form below:</p>

<form method="GET" action="normals_wkr.php" name="dl">

<h3>1. Climatology Source:</h3>
<blockquote>
(<i>Based on daily observations, the IEM has computed standard climatological values. The
official data is the 30 year record from NCDC.</i>)
</blockquote>

<strong>Select Data Source</strong><br />
 <select name="source">
    <option value="climate">IEM Climatology 1893-{$year}</option>
    <option value="climate51">IEM Climatology 1951-{$year}</option>
 	<option value="climate71" SELECTED>IEM Climatology 1971-2000</option>
 	<option value="ncdc_climate71">NCDC Climatology 1971-2000 *Official*</option>
 	<option value="ncdc_climate81">NCDC Climatology 1981-2010 *Official*</option>
 	<option value="climate81">IEM Climatology 1981-2010</option>
 </select>

<h3>2. Download Type:</h3>

<input type="radio" name="mode" value="station" checked="CHECKED">Single Station, All Days</input>
<input type="radio" name="mode" value="day">All Stations, One Day</input>

<p><b>2a. Select Station:</b><br>{$nselect}

<p><b>2b. Select Month & Date:</b><br>

Select Month: {$mselect}
<br>Select Day: {$dselect}


<h3>3. Download Options:</h3>
<select name="dloption">
  <option value="online">View Online</option>
  <option value="cdf">Download to Disk [CDF]</option>
</select><p>

<h3>4. Submit Form:</h3><br>
<input type="submit" value="Get Data"><input type="reset">

</form><p>

<p><img src="/images/gisready.png"> Data includes Lat/Lon information.
EOF;
$t->render('single.phtml');
?>
