<?php 
include("../../../config/settings.inc.php");
 $TITLE = "IEM | NWS COOP | Daily Normals";
$THISPAGE = "climatology-today";
include("$rootpath/include/header.php"); 
include("$rootpath/include/imagemaps.php"); 
include("$rootpath/include/forms.php"); 
?><div class="text">

<p>With this interface, you can download daily climate normals for NWS COOP
sites.  Please fill out the form below:</p>

<form method="GET" action="normals_wkr.php" name="dl">

<h3 class="subtitle">1. Climatology Source:</h3>
<blockquote>
(<i>Based on daily observations, the IEM has computed standard climatological values. The
official data is the 30 year record from NCDC.</i>)
</blockquote>

<strong>Select Data Source</strong><br />
 <select name="source">
    <option value="climate">IEM Climatology 1893-<?php echo date("Y"); ?></option>
    <option value="climate51">IEM Climatology 1951-<?php echo date("Y"); ?></option>
 	<option value="climate71" SELECTED>IEM Climatology 1971-2000</option>
 	<option value="ncdc_climate71">NCDC Climatology 1971-2000 *Official*</option>
 	<option value="ncdc_climate81">NCDC Climatology 1981-2010 *Official*</option>
 	<option value="climate81">IEM Climatology 1981-2010</option>
 </select>

<h3 class="subtitle">2. Download Type:</h3>

<input type="radio" name="mode" value="station" checked="CHECKED">Single Station, All Days</input>
<input type="radio" name="mode" value="day">All Stations, One Day</input>

<p><b>2a. Select Station:</b><br>
<?php echo networkSelect("IACLIMATE", ""); ?>

<p><b>2b. Select Month & Date:</b><br>

Select Month:<?php echo monthSelect("month"); ?>
<br>Select Day:<?php echo daySelect("day"); ?>


<h3 class="subtitle">3. Download Options:</h3>
<select name="dloption">
  <option value="online">View Online</option>
  <option value="cdf">Download to Disk [CDF]</option>
</select><p>

<h3 class="subtitle">4. Submit Form:</h3><br>
<input type="submit" value="Get Data"><input type="reset">

</form><p>

<p><img src="<?php echo $rooturl; ?>/images/gisready.png"> Data includes Lat/Lon information.
</div>
<?php include("$rootpath/include/footer.php"); ?>
