<?php
 include("../../config/settings.inc.php");
 $network = isset($_GET["network"]) ? $_GET["network"] : "IA_ASOS";
 
$TITLE = "IEM Networks";
include("$rootpath/include/database.inc.php");
include("$rootpath/include/google_keys.php");
include("$rootpath/include/imagemaps.php");
$api = $GOOGLEKEYS[$rooturl]["any"];
$HEADEXTRA = "<script src='http://maps.google.com/maps?file=api&amp;v=2&amp;key=$api'></script>
<script src='http://www.openlayers.org/api/OpenLayers.js'></script>
<script src='${rooturl}/js/olselect.php?network=${network}'></script>";
$BODYEXTRA = "onload=\"init()\"";
include("$rootpath/include/header.php"); 

?>


<h3 class="heading">IEM Network [<?php echo $network; ?>] Sites</h3>

<style type="text/css">
        #map {
            width: 450px;
            height: 450px;
            border: 2px solid black;
        }
</style>

<form name="olselect">
<div id="map"></div>
<div id="sname" unselectable="on">No site selected</div>
<?php echo networkSelect($network, ""); ?>
</form>


<?php include("$rootpath/include/footer.php"); ?>
