<?php
 include("../../config/settings.inc.php");

 $TITLE = "IEM Representivity";
 include("$rootpath/include/header.php");
?>

<h2>IEM Representivity Analysis</h2>

<h3>Motivation:</h3>

<p>This document provides information and statistics regarding
representativity of the IEM.  This work follows Dubois 2000.

<h3>Introduction:</h3>

<p>The IEM is a collection of environmental monitoring networks.  To various
extents, each network has differenting sensors, reporting times, siting, 
maintainance schedules, and quality control. Because of these differences, we
have split up the IEM into its component networks in order to evaluate each
on its own merits.  Similiar networks in data quality are then aggregated
to explore the spatial statistical benefits of the IEM partnership.

<p>The following abbreviations are used to represent networks and collections
of networks.
<br />
<table>
<tr><th>Abbreviation</th><th>Description</th></tr>
<tr><th>ASOS</th><td><a href="<?php echo $webroot; ?>/ASOS/">Iowa Automated Surface Observing System</a> sites. </td></tr>
</table>

<h3>Nearest Neighbors Index (NNI)</h3>

<table>
<thead>
<tr><th>Network</th><th>NNI</th><th>Z</th><th>Avg Distance</th><th>Exp Distance</th><th>Area</th></tr>
</thead>
<tr><th>ASOS</th>
    <td>1.58</td>
    <td>3.85</td>
    <td>71.9</td>
    <td>45.5</td>
    <td>97,920</td>
</tr>
<tr><th>AWOS</th>
 <td>1.28</td>
 <td>3.05</td>
 <td>38.1</td>
 <td>29.8</td>
 <td>120,650</td>
</tr>
<tr><th>RWIS</th>
 <td>1.45</td>
 <td>5.80</td>
 <td>36.6</td>
 <td>25.2</td>
 <td>120,103</td>
</tr>
<tr><td>SchoolNet</td>
 <td>1.45</td>
 <td>6.61</td>
 <td>20.0</td>
 <td>13.7</td>
 <td>45,841</td>
</tr>
<tr><td>ISUAG</td>
 <td>1.69</td>
 <td>4.08</td>
 <td>74.7</td>
 <td>44.2</td>
 <td>71,362</td>
</tr>
<tr><td>Tier 1</td>
 <td>1.32</td>
 <td>4.27</td>
 <td>34.2</td>
 <td>25.7</td>
 <td>127,572</td>
</tr>
<tr><td>Tier 2</td>
 <td>0.95</td>
 <td>0.90</td>
 <td>17.4</td>
 <td>18.3</td>
 <td>132,272</td>
</tr>
<tr><td>Tier 3</td>
 <td>0.94</td>
 <td>1.51</td>
 <td>12.9</td>
 <td>13.7</td>
 <td>132,272</td>
</tr>
</table>

<?php include("$rootpath/include/footer.php"); ?>
