<?php
 include("../../config/settings.inc.php");

 $TITLE = "IEM Representivity";
 include("$rootpath/include/header.php");
?>
<style>
.figure {
  background: #eee;
  border: 2px dashed #000;
  text-align: center;
}
.ptext h3 {
  border-bottom: 1px solid #00f;
  padding-top: 30px;
}
.ptext h4 {
  padding-left: 45px;
  color: #f00;

}
</style>

<div class="ptext" style="width: 800px;">

<h2>IEM Representivity Analysis (<i>Draft</i>)</h2>

<p>This document provides information and statistics regarding
representativity of the Iowa Environmental Mesonet (IEM).
  This work follows Dubois (2000).

<ol>
 <li><a href="#introduction">Introduction</a></li>
 <li><a href="#nearest">Nearest Neighbor Index</a></li>
 <li><a href="#fractal">Fractal Dimension</a></li>
 <li><a href="#morisita">Morisita Index</a></li>
 <li><a href="#thiessen">Thiessen Polygons</a></li>
 <li><a href="#represent">Coefficient of Representativity</a></li>
 <li><a href="#conclusions">Conclusions</a></li>
</ol>

<h3><a name="introduction">1. Introduction:</a></h3>

<p>The IEM is a collection of environmental monitoring networks. The purpose
of this collection is to produce more a precise analysis of weather and 
climatic variables in the state.  To produce higher resolution products for
the entire state, point observations are often grided onto a regular grid
using well known algorithms like nearest neighbor or the barnes scheme.  This 
process is not arbitrary due to the numerous tunable parameters to most any
analysis algorithm.  It is important to investigate the characteristics of
our mesonet to determine the appropriate scales at which we can analyze
phenomena.

<p>Each observing network in the IEM has differenting sensors, reporting times, siting, 
maintainance schedules, and quality control. Because of these differences, we
have split up the IEM into its component networks in order to evaluate each
on its own merits.  Similiar networks in data quality are then aggregated
to explore the spatial statistical benefits of the IEM partnership.

<p>
<table cellpadding="3" cellspacing="0" border="1">
<caption>Table 1 provides an overview of the IEM networks used in this study.</caption>
<thead>
<tr><th>Abbreviation</th><th>Description</th><th>Map</th></tr>
</thead>
<tr><th>ASOS</th><td>The <a href="<?php echo $webroot; ?>/ASOS/">Iowa Automated Surface Observing System</a> sites are located at primary airports and are maintained by the National Weather Service.  This network is rigorously checked and maintained.  For Iowa, the main issue is the lack of ASOS sites in Westcentral and Southwest Iowa.</td><td><img src="nni_images/asos_locs.png"></tr>

<tr><th>AWOS</th><td>The <a href="<?php echo $webroot; ?>/AWOS/">Iowa Automated Weather Observing System</a> sites are located at secondary airports and are maintained by the Iowa State Department of Transportation via 3rd party contractor.  Data quality should be comparable with the ASOS network, but a number of factors produce biases when compared with the ASOS network.  The main issues include siting, maintainance schedules, network communication, and instrumentation.  Most of the big differences between the ASOS and AWOS network show up in the temperature and dew point variables. </td><td><img src="nni_images/awos_locs.png"></tr>

<tr><th>RWIS</th><td>The <a href="<?php echo $webroot; ?>/RWIS/">Iowa Roadway Weather Information System</a> sites are located along side interstates and highways.  They are maintained by the Iowa Department of Transportation via a 3rd party contractor.  Atmospheric data from this network is of lesser quality than the ASOS or AWOS networks.  Their primary purpose is for automated observation of winter weather. </td><td><img src="nni_images/rwis_locs.png"></td></tr>

<tr><th>SchoolNet</th><td>The IEM collects data from a number of <a href="<?php echo $webroot; ?>/schoolnet/">SchoolNets</a>.  For the purposes of this document, we only consider the KCCI-TV SchoolNet.  Data quality is close to that of the RWIS network, but siting issues make variables like wind and precipitation problematic. </td><td><img src="nni_images/snet_locs.png"></td></tr>

<tr><th>ISUAG</th><td>The <a href="<?php echo $webroot; ?>/agclimate/">ISU Ag Climate</a> sites primarily provide soil temperature and solar radiation readings.They are maintained by the Iowa State University Extension.  The main issue with this network is the timing of observations received.  Each station is called daily to download its observation record from the previous day. </td><td><img src="nni_images/isuag_locs.png"></td></tr>
</table>

<p>

<table cellpadding="3" cellspacing="0" border="1">
<caption>Table 2 lists our proposed combination of networks based on data quality 
and reliability.</caption>
<thead>
<tr><th>Abbreviation</th><th>Description</th><th>Map</th></tr>
</thead>
<tr><th>Tier 1</th><td>ASOS + AWOS:  The combination of these two networks is commonly used in the meteorological community to produce various analysis products.  Both networks are located at airports and are for the most part, well sited.</td><td><img src="nni_images/tier1_locs.png"></tr>

<tr><th>Tier 2</th><td>ASOS + AWOS + RWIS:  The RWIS network is included in this grouping, since it has the closest data quality reputation to the ASOS+AWOS networks.  </td><td><img src="nni_images/tier2_locs.png"></tr>

<tr><th>Tier 3</th><td>ASOS + AWOS + RWIS + SchoolNet + ISUAG:  All networks included.</td><td><img src="nni_images/tier3_locs.png"></tr>

</table>

<h3><a name="nearest">2. Nearest Neighbors Index (NNI)</a></h3>

<p>The NNI is a statistic comparing the mean minimum distances between sampling points to that which is expected by chance over some sampling area.

<h4>Procedure:</h4>

<p>Point shapefile coverages for each of the network groups was created.  These files were loaded into ESRI's ArcGIS 9.1.  An ArcGIS extension called <a href="http://arcscripts.esri.com/details.asp?dbid=12227"><i>Nearest Neighbor Analysis / Event-Event Distances</i></a> written by Dr M. Sawada was used to compute the NNI.

<h4>Data:</h4>
<table cellpadding=2 cellspacing=0 border=1>
<caption>Table 3 shows NNI values along with other relevant statistics used in the NNI calculation. (DARYL: Figure out what Z is...)</caption>
<thead>
<tr><th>Network</th><th>Sites</th><th>NNI</th><th>Z</th><th>Avg Min Distance<br />[km]</th><th>Expected Min Distance<br />[km]</th><th>Area [km^2]</th></tr>
</thead>
<tr><th>ASOS</th><td>15</td>
    <td style="background: #ff0;">1.58</td>
    <td>3.85</td>
    <td>71.9</td>
    <td>45.5</td>
    <td>97,920</td>
</tr>
<tr><th>AWOS</th><td>39</td>
 <td>1.28</td>
 <td>3.05</td>
 <td>38.1</td>
 <td>29.8</td>
 <td>120,650</td>
</tr>
<tr><th>RWIS</th><td>53</td>
 <td>1.45</td>
 <td>5.80</td>
 <td>36.6</td>
 <td>25.2</td>
 <td>120,103</td>
</tr>
<tr><th>SchoolNet</th><td>68</td>
 <td>1.45</td>
 <td>6.61</td>
 <td>20.0</td>
 <td>13.7</td>
 <td>45,841</td>
</tr>
<tr><th>ISUAG</th><td>12</td>
 <td>1.69</td>
 <td>4.08</td>
 <td>74.7</td>
 <td>44.2</td>
 <td>71,362</td>
</tr>
<tr><th>Tier 1</th><td>54</td>
 <td>1.32</td>
 <td>4.27</td>
 <td>34.2</td>
 <td>25.7</td>
 <td>127,572</td>
</tr>
<tr><th>Tier 2</th><td>107</td>
 <td style="background: #ff0;">0.95</td>
 <td>0.90</td>
 <td>17.4</td>
 <td>18.3</td>
 <td>132,272</td>
</tr>
<tr><th>Tier 3</th><td>187</td>
 <td>0.94</td>
 <td>1.51</td>
 <td>12.9</td>
 <td>13.7</td>
 <td>132,272</td>
</tr>
</table>

<h4>Analysis:</h4>

<table cellpadding=2 cellspacing=0 border=1>
<caption>Table 4 details NNI interpretation</caption>
<thead>
<tr><th>NNI Value</th><th>Details</th></tr>
</thead>
<tr><td>&gt; 1</td><td>indicates dispersion of samples</td></tr>
<tr><td> ~~ 1</td><td>indicates sampling points have a uniform distribution</td></tr>
<tr><td> &lt; 1</td><td>indicates samples are clustered</td></tr>
</table>

<p>Table 3 shows the results of the NNI computation.  The ASOS network has
 a relatively high value of 1.58 which indicates dispersion of the sampling
points.  This spread was one of the main reasons the IEM was created, since
the baseline ASOS network doesn't have good representivity at even a 50 km scale over the state.  The NNI value of 0.95 for the combination of the AWOS and RWIS networks to the ASOS network in Tier 2 shows the benefit of the IEM collaboration.  Tier 2's value of 0.95 is very close to unity and indicates that the network has a nearly uniform distribution.

<h3><a name="fractal">3.  Fractal Dimension</a></h3>

<p>The fractal dimension is a measure of the variation of the average number
of observing points found within circles of certain radius of each point 
centered at that point.  The motivation of this statistic is to obtain the 
fractal dimension of the observing network such that any phenomena with 
fractal dimension less than the space dimension minus the fractal dimension of 
the network can not be resolved. (DARYL doesn't fully understand what he is saying yet)

<h4>Procedure</h4>

<p>A python script was written to compute the needed variables for the fractal
dimension statistic.  The spatial computations were done in the PostGIS 
database using the NAD83 UTM Zone15 North projection.

<h4>Data</h4>
<div class="figure">
<img src="nni_images/fractal.png">
<br />Figure 1: Fractal Dimension
</div>

<p>

<table cellpadding=2 cellspacing=0 border=1>
<caption>Table 5: Fractal dimension results</caption>
<thead><th>Distance</th><th>ASOS</th><th>AWOS</th><th>RWIS</th><th>SchoolNet</th><th>ISUAG</th><th>Tier 1</th><th>Tier 2</th><th>Tier 3</th></tr></thead>

<tr><td>30-100km</td><td>1.05</td><td>0.72</td><td>0.85</td><td>0.73</td><td>0.69</td><td>0.82</td><td>0.77</td><td>0.74</td></tr>

<tr><td>30-300km</td><td>2.23</td><td>1.65</td><td>1.75</td><td>1.25</td><td>1.99</td><td>1.78</td><td>1.67</td><td>1.56</td></tr>


</table>

<h4>Analysis</h4>

<p>(<i>I am having a tough time understanding fractals...  Still researching...</i>)  For data varying in 2 dimensions, a network is able to resolve phenomena
that is 2 minus the factal dimension.

<h3><a name="morisita">4. Morisita Index</a></h3>

<p>The Morisita index investigates the amount of contagion in a sampling
network.  It basically looks at how much clustering occurs when a sampling
network is broken up into regular cells. If each cell has the same number of
observation points inside of it, then the index should indicate uniformity in
space at that scale.

<h4>Procedure:</h4>

<p>A python script was written to compute this value.  The spatial computations were
done in NAD83 UTM Zone 15N, which is a common projection for Iowa.  Figures 2 illustrates the morisita index.  You have some area of interest with a 
number of observations points (leftside graphic).  You then divide this 
area up into equal sized cells and then count the number of cells 
with sites in them (rightside graphic). 

<div class="figure">
<table cellpadding="3" cellspacing="0" border="1">
<thead>
<tr><th>Observation Points</th><th>Divided up by 25 cells</th></tr>
</thead>
<tr><td><img src="nni_images/morisita_1.png" border="2"></td>
    <td><img src="nni_images/morisita_2.png" border="2"></td>
</tr></table>
<br />Figure 2:  Illustration of Morisita Index
</div>

<p>In this example, the Morisita index is around 13.  This is a very high
number and indicates clustering.  You then itterate over
a number of different grid cell sizes to get trends and a better understanding 
of how the clustering varies at different scales.

<h4>Data:</h4>
<div class="figure">
<img src="nni_images/morisita.gif">
<br />Figure 3: Morisita Index 
</div>

<h4>Analysis:</h4>

<p>For the Morisita Index, values above 1 indicate clustering at that scale.
  This chart clearly shows clustering of the Tier2 and Tier3 networks at small scales.  RWIS sites tend to be located in the same urban areas as airport sensors from the ASOS and AWOS network.  This materializes in the clustering noted at 10-30 km cell sizes.

<p>It is interesting to note the clustering at 200-250 km within the SchoolNet.  This is a result of the KCCI SchoolNet being confined to Central Iowa.  When the index is computed, a large clustering occurs at that scale.

<h3><a name="thiessen">5. Thiessen/Voronoi polygons</a></h3>

<p>Thiessen polygons have been a traditional staple of the spatial statistian.  Think of them as polygon areas where any point inside that polygon is the closest to 1 sampling point within that polygon as well.  So there is one polygon per sampling point.

<h4>Procedure:</h4>

<p>The point coverage shapefiles were loaded into ArcGIS 9.1.  The Thiessen polygon tool was then used to generate the polygons.  These polygons were then clipped by the border of Iowa within ArcGIS as well.  The resulting coverage was exported to Shapefile and then loaded into the IEM's spatial database for analysis.

<h4>Data:</h4>
<div class="figure">
<table cellspacing="0" cellpadding="3" border="1">
<thead><tr><th colspan="2">Figure 4: Tier 1</th></tr></thead>
<tr><td><img src="nni_images/tier1_areas.png"></td><td><img src="nni_images/tier1_th.png"></td></tr>
<thead><tr><th colspan="2">Figure 5: Tier 2</th></tr></thead>
<tr><td><img src="nni_images/tier2_areas.png"></td><td><img src="nni_images/tier2_th.png"></td></tr>
<thead><tr><th colspan="2">Figure 6: Tier 3</th></tr></thead>
<tr><td><img src="nni_images/tier3_areas.png"></td><td><img src="nni_images/tier3_th.png"></td></tr>
</table>
</div>

<h4>Analysis:</h4>

<p>Thiessen polygon's provide a quick synopsis of how large of an area is 
represented by a single point.  Areas in a network that are undersampled can
quickly be seen.  Figure 4 shows the interesting contrast between the more
densely sampled areas of Central Iowa and along the I-380 corridor in Eastern
Iowa.  The largest polygons can be seen in Northeast and Southern Iowa.  The 
histogram for Tier 1 also nicely details the collection of smaller polygons
around 2,000 km**2 
along with a second mode of larger polygons around 5,000 km**2.  Unfortunately,
this bi-modal distribution is not greatly helped by the addition of the RWIS sensors in Tier 2.  The clustering of the RWIS sensors simply splits some of the
larger polygons, but a couple of rather large polygons in Northeastern Iowa still exist.

<p>For Tier 3, the clustering of sites in Central Iowa with the SchoolNet 
network creates a large number of smaller polygons and doesn't help to eliminate
the larger polygons in Eastern Iowa.  The average polygon size on the maps are
only interesting in the fact that they indicate what the ideal size would be
if all of the sites were spread out equally. 

<h3><a name="represent">6. Coefficient of Representativity</a></h3>

<h4>Procedure:</h4>

<p>The thiessen polygons and network coverages were loaded into the IEM spatial
database.  Python scripts were then written to analyze distances and compute
other parameters needed for the coefficient of representativity (CR).  
All spatial math was done in NAD83 UTM Zone15N.

<h4>Data:</h4>
<div class="figure">
<table>
<tr><td>Figure 7:<br/><img src="nni_images/tier1_cr.png"></td>
    <td>Figure 8:<br/><img src="nni_images/tier2_cr.png"></td></tr>
<tr><td>Figure 9:<br/><img src="nni_images/tier3_cr.png"></td>
    <td></td></tr>
</table>
</div>

<h4>Analysis:</h4>

<table cellspacing="0" cellpadding="3" border="1">
<thead><tr><th>CR Value</th><th>Conclusion</th></tr></thead>
<tr><td>CR &gt; 1</td><td>The measure is isolated.</td></tr>
<tr><td>CR ~~ 1</td><td>Ideal case, measure is spatially uniform.</td></tr>
<tr><td>CR &lt; 1</td><td>The measure is clustered</td></tr>
</table>

<p>Tier 1 clearly shows the undersampled portions of the state, which are 
NE Iowa and parts of SW Iowa.  By adding the RWIS network in tier 2, we appear 
to only gain more clustering in limited areas and other areas suffer even more from sparse observation.  Tier 3 clearly shows the affect of adding 60+ SchoolNet sites in Central Iowa, since the clustering goes up and the sparse areas get even worse due to the increased number of stations.

<h3><a name="conclusions">7. Conclusions</a></h3>

<p>A representativity analysis was performed following work done by Dubois.
The statistical benefits of the IEM collaboration show up in almost every 
variable, but there are certain caveats that appear as well.  
The main caveat is that the addition of networks to the baseline ASOS and
AWOS network often only add clustering to the network as a whole.

<p>(DARYL: adds more conclusions here...)

<h3>References</h3>

<p>Dubois G (2000) How representative are samples in a sampling network? <i>J Geographic Info Decision Anal<i> 4:1-10

<p>

</div>

<?php include("$rootpath/include/footer.php"); ?>
