<?php 
require_once "../../config/settings.inc.php";
require_once "../../include/myview.php";
$t = new MyView();
$t->title = "Data Variables";

$t->content = <<<EOF

<p>This table shows the variables reported from the various IEM networks.  As
you can see, no network reports everything, but the combination of all
of these networks collects everything.  This is the motivation behind the 
IEM.

<p><table class="table table-bordered table-striped">
<thead>
		<tr>
  <td class="climo-header-left" rowspan="2" align="center">Variable:</td>
  <td class="climo-header-left" colspan="10" align="center">IEM Network:</td>
  </tr>
<tr>
  <td><a href="/ASOS/">ASOS</a></td>
  <td><a href="/AWOS/">AWOS</a></td>
  <td><a href="/cocorahs/">CoCoRaHS</a></td>
  <td><a href="/COOP/">COOP</a></td>
  <td><a href="/DCP/">DCP</a></td>
  <td><a href="/agclimate/">ISU Soil Moisture</a></td>
  <td><a href="/nstl_flux/">NLAE Flux</a></td>
  <td><a href="/RWIS/">RWIS</a></td>
  <td><a href="/scan/">SCAN</a></td>
  <td><a href="/schoolnet/">SchoolNet</a></td>
  </tr>
</thead>
		
<tr class="odd"><th>Air Temperature</th>
  <td>X</td><td>X</td><td>&nbsp;</td><td>X</td><td>Some</td>
  <td>X</td><td>X</td><td>X</td><td>X</td><td>X</td></tr>
<tr class="even"><th>Humidity</th>
  <td>X</td><td>X</td><td>&nbsp;</td><td>&nbsp;</td><td>Some</td>
  <td>X</td><td>X</td><td>X</td><td>X</td><td>X</td></tr>
<tr class="odd"><th>Wind Speed/Direction</th>
  <td>X</td><td>X</td><td>&nbsp;</td><td>&nbsp;</td><td>Some</td>
  <td>X</td><td>X</td><td>X</td><td>X</td><td>X</td></tr>
<tr class="even"><th>Air Pressure</th>
  <td>X</td><td>X</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td>
  <td>&nbsp;</td><td>X</td><td>&nbsp;</td><td>X</td><td>X</td></tr>
<tr class="odd"><th>Precipitation</th>
  <td>X</td><td>X</td><td>X</td><td>X</td><td>Some</td>
  <td>X</td><td>X</td><td>Some</td><td>X</td><td>X</td></tr>
<tr class="even"><th>Solar Radiation</th>
  <td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td>
  <td>X</td><td>X</td><td>&nbsp;</td><td>X</td><td>X</td></tr>
<tr class="odd"><th>Visibility</th>
  <td>X</td><td>X</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td>
  <td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td></tr>
<tr class="even"><th>Clouds Heights/Coverage</th>
  <td>X</td><td>X</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td>
  <td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td></tr>
<tr class="odd"><th>Soil Temperature</th>
  <td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td>
  <td>X</td><td>&nbsp;</td><td>&nbsp;</td><td>X</td><td>&nbsp;</td></tr>
<tr class="even"><th>Soil Moisture</th>
  <td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td>
  <td>X</td><td></td><td>&nbsp;</td><td>X</td><td>&nbsp;</td></tr>

<tr class="odd"><th>Snowfall/Snow Depth</th>
  <td>&nbsp;</td><td>&nbsp;</td><td>X</td><td>X</td><td>&nbsp;</td>
  <td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td></tr>
		
<tr class="even"><th>River Stage</th>
  <td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td>
  <td>Some</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td>
  <td>&nbsp;</td></tr>

</table>

<p><b>Legend:</b>  
  <dd>X == Network reports this variable
   <br>Some == Some sites report this variable, not all
   <br>(blank) == No sites report this variable</dd></div>
EOF;
$t->render('single.phtml');
