<?php 
include("../../config/settings.inc.php");
$TITLE = "IEM | Data Variables";
$THISPAGE = "iem-variables";
include("$rootpath/include/header.php"); ?>

<div class="text">

<p>This table shows the variables reported from the various IEM networks.  As
you can see, no network reports everything, but the combination of all
of these networks collects everything.  This is the motivation behind the 
IEM.

<p><table border=1 cellpadding=2 cellspacing=0>
<tr>
  <td class="climo-header-left" rowspan="2" align="center">Variable:</td>
  <td class="climo-header-left" colspan="8" align="center">IEM Network:</td>
  </tr>
<tr>
  <td bgcolor="#CCCCCC"><a href="/ASOS/">ASOS</a></td>
  <td bgcolor="#CCCCCC"><a href="/AWOS/">AWOS</a></td>
  <td bgcolor="#CCCCCC"><a href="/COOP/">COOP</a></td>
  <td bgcolor="#CCCCCC"><a href="/DCP/">DCP</a></td>
  <td bgcolor="#CCCCCC"><a href="/agclimate/">ISU AG</a></td>
  <td bgcolor="#CCCCCC"><a href="/RWIS/">RWIS</a></td>
  <td bgcolor="#CCCCCC"><a href="/scan/">SCAN</a></td>
  <td bgcolor="#CCCCCC"><a href="/schoolnet/">SchoolNet</a></td>
  </tr>

<tr class="odd"><th>Air Temperature</th>
  <td>X</td><td>X</td><td>X</td><td>Some</td>
  <td>X</td><td>X</td><td>X</td><td>X</td></tr>
<tr class="even"><th>Humidity</th>
  <td>X</td><td>X</td><td>&nbsp;</td><td>Some</td>
  <td>X</td><td>X</td><td>X</td><td>X</td></tr>
<tr class="odd"><th>Wind Speed/Direction</th>
  <td>X</td><td>X</td><td>&nbsp;</td><td>Some</td>
  <td>X</td><td>X</td><td>X</td><td>X</td></tr>
<tr class="even"><th>Air Pressure</th>
  <td>X</td><td>X</td><td>&nbsp;</td><td>&nbsp;</td>
  <td>&nbsp;</td><td>&nbsp;</td><td>X</td><td>X</td></tr>
<tr class="odd"><th>Precipitation</th>
  <td>X</td><td>X</td><td>X</td><td>Some</td>
  <td>X</td><td>Some</td><td>X</td><td>X</td></tr>
<tr class="even"><th>Solar Radiation</th>
  <td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td>
  <td>X</td><td>&nbsp;</td><td>X</td><td>X</td></tr>
<tr class="odd"><th>Visibility</th>
  <td>X</td><td>X</td><td>&nbsp;</td><td>&nbsp;</td>
  <td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td></tr>
<tr class="even"><th>Clouds Heights/Coverage</th>
  <td>X</td><td>X</td><td>&nbsp;</td><td>&nbsp;</td>
  <td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td></tr>
<tr class="odd"><th>Soil Temperature</th>
  <td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td>
  <td>X</td><td>&nbsp;</td><td>X</td><td>&nbsp;</td></tr>
<tr class="even"><th>Soil Moisture</th>
  <td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td>
  <td>&nbsp;</td><td>&nbsp;</td><td>X</td><td>&nbsp;</td></tr>
<tr class="odd"><th>Snowfall/Snow Depth</th>
  <td>&nbsp;</td><td>&nbsp;</td><td>X</td><td>&nbsp;</td>
  <td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td></tr>
<tr class="even"><th>River Stage</th>
  <td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>X</td>
  <td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td></tr>

</table>

<p><b>Legend:</b>  
  <dd>X == Network reports this variable
   <br>Some == Some sites report this variable, not all
   <br>(blank) == No sites report this variable</dd></div>

<?php include("$rootpath/include/footer.php"); ?>
