<?php 
include("../../../config/settings.inc.php");
include("../../../include/myview.php");
require_once "../../../include/forms.php";
include ("../../../include/iemaccess.php");
include ("../../../include/iemaccessob.php");
$t = new MyView();
$t->title = "Beloit Weather Station";
$t->thispage = "networks-other";

$year = isset( $_GET["year"] ) ? intval($_GET["year"]): date("Y");
$month = isset( $_GET["month"] ) ? intval($_GET["month"]): date("m");
$day = isset( $_GET["day"] ) ? intval($_GET["day"]): date("d");

$iem = new IEMAccess();
$iemob = $iem->getSingleSite("OT0009");
$rs = $iemob->db;


 $vardict = Array("valid" => "Observation Time", "tmpf" => "Air Temperature [F]",
   "dwpf" => "Dew Point [F]", "relh" => "Relative Humidity [%]",
   "drct" => "Wind Direction", "sknt" => "Wind Speed [knots]",
   "srad" => "Solar Radiation [W m{-2}]",
   "mslp" => "Pressure [mb]", "phour" => "Hourly Precipitation [inches]",
   "c1tmpf" => "Soil Temperature [F]", "pday" => "Daily Precipitation [inches]");

 $vselect = "";
 foreach ( $vardict as $key => $value ) {
 	if ($rs[$key] != "") {
 		if ($key == "valid") {
 			$t2 = date("d M Y, g A", strtotime($rs[$key]));
 			$vselect .= '<tr><td><b>'. $value .'</b></td><td>'. $t2 .'</td></tr>';
 		} else {
 			$vselect .= '<tr><td><b>'. $value .'</b></td><td>'. $rs[$key] .'</td></tr>';
 		} // End if
 	} // End if
 }
 $ys = yearSelect2(2010, $year, "year");
 $ms = monthSelect($month, "month");
 $ds = daySelect($day, "day");
 
 $table = "";
 $rs2 = pg_query($iem->dbconn, "SELECT day, max_tmpf, min_tmpf, pday from summary s JOIN stations t
  ON (t.iemid = s.iemid)
  WHERE t.id = 'OT0009' ORDER by day DESC");
 for($i=0;$row=@pg_fetch_array($rs2,$i);$i++){
 	$table .= sprintf("<tr><th>%s</th><td>%.1f</td><td>%.1f</td><td>%.2f</td></tr>",
 			$row["day"], $row["max_tmpf"], $row["min_tmpf"], $row["pday"]);
 }
 
 $t->content = <<<EOF

<h3>Beloit Weather Station</h3>

<div class="alert alert-warning">This station was removed in 2012</div>

<div style="float: right; margin: 5px;"><img src="photo.jpg" /></div>
<p>The <a href="http://www.lsiowa.org/residential_beloit.html">Beloit Residential Treatment Center</a> is situated in a neighborhood
area at 1323 Northwestern Avenue in Ames. Children ages 5 to 15 live in
two facilities on campus, including the new Anna J. Hull Treatment
Center. This weather station is used by the students to help their 
gardening activities.</p>

<strong>Current Observation</strong><br />
<table cellpadding="3" cellspacing="0" border="1">
{$vselect}
</table>

<p><strong>Time Series Graph</strong><br />
Select Date after 14 May 2010:
<form method="GET" name="formerr">
{$ys}
{$ms}
{$ds}
<input type="submit" value="Create Chart">
</form>
<br />


<img src="t_rad.php?year={$year}&month={$month}&day={$day}" />

<p><strong>Daily Totals</strong><br />
<table cellpadding="2" cellspacing="0" border="1">
<tr><th>Day</th><th>High Temperature</th><th>Low Temperature</th><th>Rainfall [inch]</th></tr>
{$table}
</table>
EOF;
$t->render('single.phtml');
?>
