<?php 
        $TITLE = "IEM | AWOS | Questionable Calibrations";
include("/mesonet/php/include/header.php"); 
?>
<div class="text">
<b>Nav:</b> <a href="/AWOS/">AWOS</a> &nbsp; > &nbsp; Questionable Calibrations

<p>Based on the 1 minute AWOS data archive provided by the DOT, here is a 
listing of sites that appear to have been incorrectly calibrated since last 
fall. The
window of time missing in the one minute data record is assumed to be the
time when the station was offline for calibration. All temperature values are in
Fahrenhit. For the humidity values, we are not certain if the dew point is actually being adjusted or
the relative humidity is being adjusted on the sites.  Based on some conversations, the dew point is being adjusted.

<p>

<table cellpadding=2 cellspacing=0 border=1>

<tr>
 <th colspan="5" class="climo-header-left">8 September 2003</th></tr>
<tr>
 <td></td><th>Time:</th><th>Temperature</th><th>Dew Point</th><th>Rel Humidity %</th></tr>
<tr>
 <td rowspan="6">Mount Pleasant (MPZ)</td>
     <td>18:46Z</td><td>82</td><td>59</td><td>46</td></tr>
 <tr><td>18:47Z</td><td>82</td><td>58</td><td>44</td></tr>
 <tr><td>18:48Z</td><td>82</td><td>58</td><td>44</td></tr>
 <tr class="even"><td>19:12Z</td><td>86</td><td>62</td><td>45</td></tr>
 <tr><td>19:13Z</td><td>86</td><td>62</td><td>45</td></tr>
 <tr><td>19:14Z</td><td>86</td><td>62</td><td>45</td></tr>



<tr>
 <th colspan="5" class="climo-header-left">2 October 2003</th></tr>
<tr>
 <td></td><th>Time:</th><th>Temperature</th><th>Dew Point</th><th>Rel Humidity %</th></tr>
<tr>
 <td rowspan="6">Harlan (HNR)</td>
     <td>17:42Z</td><td>57</td><td>24</td><td>28</td></tr>
 <tr><td>17:43Z</td><td>57</td><td>25</td><td>29</td></tr>
 <tr><td>17:44Z</td><td>57</td><td>25</td><td>29</td></tr>
 <tr class="even"><td>18:08Z</td><td>63</td><td>36</td><td>37</td></tr>
 <tr><td>18:09Z</td><td>63</td><td>36</td><td>37</td></tr>
 <tr><td>18:10Z</td><td>63</td><td>36</td><td>37</td></tr>


<tr>
 <td></td><th>Time:</th><th>Temperature</th><th>Dew Point</th><th>Rel Humidity %</th></tr>
<tr>
 <td rowspan="6">Denison (DNS)</td>
     <td>19:33Z</td><td>64</td><td>32</td><td>30</td></tr>
 <tr><td>19:34Z</td><td>64</td><td>32</td><td>30</td></tr>
 <tr><td>19:35Z</td><td>65</td><td>33</td><td>30</td></tr>
 <tr class="even"><td>19:48Z</td><td>67</td><td>37</td><td>33</td></tr>
 <tr><td>19:49Z</td><td>66</td><td>37</td><td>34</td></tr>
 <tr><td>19:50Z</td><td>66</td><td>37</td><td>34</td></tr>


<tr>
 <th colspan="5" class="climo-header-left">6 November 2003</th></tr>
<tr>
 <td></td><th>Time:</th><th>Temperature</th><th>Dew Point</th><th>Rel Humidity %</th></tr>
<tr>
 <td rowspan="6">Orange City (ORC)<br><i>(Fixed 29 Mar 2004)</i></td>
     <td>17:59Z</td><td>37</td><td>19</td><td>48</td></tr>
 <tr><td>18:00Z</td><td>37</td><td>19</td><td>48</td></tr>
 <tr><td>18:01Z</td><td>37</td><td>19</td><td>48</td></tr>
 <tr class="even"><td>18:14Z</td><td>39</td><td>29</td><td>67</td></tr>
 <tr><td>18:15Z</td><td>39</td><td>30</td><td>69</td></tr>
 <tr><td>18:16Z</td><td>39</td><td>30</td><td>69</td></tr>


<tr>
 <td></td><th>Time:</th><th>Temperature</th><th>Dew Point</th><th>Rel Humidity %</th></tr>
<tr>
 <td rowspan="6">Sheldon (SHL)</td>
     <td>18:53Z</td><td>36</td><td>22</td><td>56</td></tr>
 <tr><td>18:54Z</td><td>36</td><td>22</td><td>56</td></tr>
 <tr><td>18:55Z</td><td>36</td><td>22</td><td>56</td></tr>
 <tr class="even"><td>19:20Z</td><td>39</td><td>29</td><td>67</td></tr>
 <tr><td>19:21Z</td><td>39</td><td>29</td><td>67</td></tr>
 <tr><td>19:22Z</td><td>39</td><td>29</td><td>67</td></tr>


<tr>
 <td></td><th>Time:</th><th>Temperature</th><th>Dew Point</th><th>Rel Humidity %</th></tr>
<tr>
 <td rowspan="6">Algona (SHL)</td>
     <td>20:58Z</td><td>36</td><td>22</td><td>56</td></tr>
 <tr><td>20:59Z</td><td>36</td><td>22</td><td>56</td></tr>
 <tr><td>21:00Z</td><td>36</td><td>22</td><td>56</td></tr>
 <tr class="even"><td>21:20Z</td><td>40</td><td>26</td><td>57</td></tr>
 <tr><td>21:21Z</td><td>41</td><td>26</td><td>55</td></tr>
 <tr><td>21:22Z</td><td>41</td><td>25</td><td>53</td></tr>


<tr>
 <th colspan="5" class="climo-header-left">14 November 2003</th></tr>
<tr>
 <td></td><th>Time:</th><th>Temperature</th><th>Dew Point</th><th>Rel Humidity %</th></tr>
<tr>
 <td rowspan="6">Charles City (CCY)</td>
     <td>17:53Z</td><td>42</td><td>34</td><td>73</td></tr>
 <tr><td>17:54Z</td><td>42</td><td>34</td><td>73</td></tr>
 <tr><td>17:55Z</td><td>42</td><td>34</td><td>73</td></tr>
 <tr class="even"><td>18:10Z</td><td>43</td><td>36</td><td>76</td></tr>
 <tr><td>18:11Z</td><td>43</td><td>36</td><td>76</td></tr>
 <tr><td>18:12Z</td><td>43</td><td>36</td><td>76</td></tr>

<tr>
 <td rowspan="6">Decorah (DEH)</td>
     <td>19:17Z</td><td>40</td><td>33</td><td>76</td></tr>
 <tr><td>19:18Z</td><td>40</td><td>33</td><td>76</td></tr>
 <tr><td>19:19Z</td><td>40</td><td>33</td><td>76</td></tr>
 <tr class="even"><td>19:34Z</td><td>42</td><td>37</td><td>82</td></tr>
 <tr><td>19:35Z</td><td>42</td><td>37</td><td>82</td></tr>
 <tr><td>19:36Z</td><td>42</td><td>38</td><td>86</td></tr>


<tr>
 <td rowspan="6">Monticello (MXO)</td>
     <td>21:34Z</td><td>46</td><td>31</td><td>56</td></tr>
 <tr><td>21:35Z</td><td>46</td><td>31</td><td>56</td></tr>
 <tr><td>21:36Z</td><td>46</td><td>31</td><td>56</td></tr>
 <tr class="even"><td>22:00Z</td><td>44</td><td>33</td><td>65</td></tr>
 <tr><td>22:01Z</td><td>44</td><td>33</td><td>65</td></tr>
 <tr><td>22:02Z</td><td>44</td><td>33</td><td>65</td></tr>



<tr>
 <th colspan="5" class="climo-header-left">21 November 2003</th></tr>
<tr>
 <td></td><th>Time:</th><th>Temperature</th><th>Dew Point</th><th>Rel Humidity %</th></tr>
<tr>
 <td rowspan="6">Creston (CSQ)</td>
     <td>20:21Z</td><td>45</td><td>25</td><td>45</td></tr>
 <tr><td>20:22Z</td><td>44</td><td>24</td><td>45</td></tr>
 <tr><td>20:23Z</td><td>44</td><td>24</td><td>45</td></tr>
 <tr class="even"><td>20:39Z</td><td>43</td><td>27</td><td>53</td></tr>
 <tr><td>20:40Z</td><td>43</td><td>27</td><td>53</td></tr>
 <tr><td>20:41Z</td><td>43</td><td>27</td><td>53</td></tr>

<tr>
 <th colspan="5" class="climo-header-left">2 December 2003</th></tr>
<tr>
 <td></td><th>Time:</th><th>Temperature</th><th>Dew Point</th><th>Rel Humidity %</th></tr>
<tr>
 <td rowspan="6">Newton (TNU)<br><i>(Fixed 6 Apr 2004)</i></td>
     <td>20:25Z</td><td>39</td><td>15</td><td>37</td></tr>
 <tr><td>20:26Z</td><td>39</td><td>15</td><td>37</td></tr>
 <tr><td>20:27Z</td><td>39</td><td>15</td><td>37</td></tr>
 <tr class="even"><td>20:41Z</td><td>39</td><td>28</td><td>64</td></tr>
 <tr><td>20:42Z</td><td>39</td><td>28</td><td>64</td></tr>
 <tr><td>20:43Z</td><td>39</td><td>28</td><td>64</td></tr>

<tr>
 <td></td><th>Time:</th><th>Temperature</th><th>Dew Point</th><th>Rel Humidity %</th></tr>
<tr>
 <td rowspan="6">Ankeny (IKV)<br><i>(Fixed 6 Apr 2004)</i></td>
     <td>21:37Z</td><td>38</td><td>21</td><td>50</td></tr>
 <tr><td>21:38Z</td><td>38</td><td>21</td><td>50</td></tr>
 <tr><td>21:39Z</td><td>38</td><td>21</td><td>50</td></tr>
 <tr class="even"><td>21:55Z</td><td>38</td><td>30</td><td>73</td></tr>
 <tr><td>21:56Z</td><td>38</td><td>30</td><td>73</td></tr>
 <tr><td>21:57Z</td><td>38</td><td>30</td><td>73</td></tr>

<tr>
 <th colspan="5" class="climo-header-left">4 December 2003</th></tr>
<tr>
 <td></td><th>Time:</th><th>Temperature</th><th>Dew Point</th><th>Rel Humidity %</th></tr>
<tr>
 <td rowspan="6">Webster City (EBS)</td>
     <td>17:24Z</td><td>31</td><td>23</td><td>72</td></tr>
 <tr><td>17:25Z</td><td>31</td><td>23</td><td>72</td></tr>
 <tr><td>17:26Z</td><td>31</td><td>23</td><td>72</td></tr>
 <tr class="even"><td>17:43Z</td><td>31</td><td>23</td><td>72</td></tr>
 <tr><td>17:44Z</td><td>31</td><td>23</td><td>72</td></tr>
 <tr><td>17:45Z</td><td>31</td><td>23</td><td>72</td></tr>


<tr>
 <td></td><th>Time:</th><th>Temperature</th><th>Dew Point</th><th>Rel Humidity %</th></tr>
<tr>
 <td rowspan="6">Clarion (CAV)</td>
     <td>18:57Z</td><td>33</td><td>24</td><td>69</td></tr>
 <tr><td>18:58Z</td><td>33</td><td>24</td><td>69</td></tr>
 <tr><td>18:59Z</td><td>33</td><td>24</td><td>69</td></tr>
 <tr class="even"><td>19:19Z</td><td>33</td><td>26</td><td>75</td></tr>
 <tr><td>19:20Z</td><td>33</td><td>26</td><td>75</td></tr>
 <tr><td>19:21Z</td><td>33</td><td>26</td><td>75</td></tr>


<tr>
 <th colspan="5" class="climo-header-left">8 December 2003</th></tr>
<tr>
 <td></td><th>Time:</th><th>Temperature</th><th>Dew Point</th><th>Rel Humidity %</th></tr>
<tr>
 <td rowspan="6">Knoxville (OKV)</td>
     <td>19:13Z</td><td>49</td><td>38</td><td>66</td></tr>
 <tr><td>19:14Z</td><td>49</td><td>39</td><td>68</td></tr>
 <tr><td>19:15Z</td><td>50</td><td>39</td><td>66</td></tr>
 <tr class="even"><td>19:26Z</td><td>49</td><td>39</td><td>68</td></tr>
 <tr><td>19:27Z</td><td>49</td><td>39</td><td>68</td></tr>
 <tr><td>19:28Z</td><td>49</td><td>39</td><td>68</td></tr>
<tr>
 <td></td><th>Time:</th><th>Temperature</th><th>Dew Point</th><th>Rel Humidity %</th></tr>
<tr>
 <td rowspan="6">Chariton (CNC)</td>
     <td>20:15Z</td><td>53</td><td>40</td><td>61</td></tr>
 <tr><td>20:16Z</td><td>53</td><td>40</td><td>61</td></tr>
 <tr><td>20:17Z</td><td>53</td><td>40</td><td>61</td></tr>
 <tr class="even"><td>20:29Z</td><td>51</td><td>39</td><td>63</td></tr>
 <tr><td>20:30Z</td><td>51</td><td>39</td><td>63</td></tr>
 <tr><td>20:31Z</td><td>51</td><td>39</td><td>63</td></tr>



<tr>
 <th colspan="5" class="climo-header-left">15 December 2003</th></tr>
<tr>
 <td></td><th>Time:</th><th>Temperature</th><th>Dew Point</th><th>Rel Humidity %</th></tr>
<tr>
 <td rowspan="6">Lemars (LRJ)</td>
     <td>19:36Z</td><td>35</td><td>28</td><td>75</td></tr>
 <tr><td>19:37Z</td><td>35</td><td>28</td><td>75</td></tr>
 <tr><td>19:38Z</td><td>35</td><td>28</td><td>75</td></tr>
 <tr class="even"><td>19:54Z</td><td>35</td><td>34</td><td>96</td></tr>
 <tr><td>19:55Z</td><td>35</td><td>34</td><td>96</td></tr>
 <tr><td>19:56Z</td><td>35</td><td>34</td><td>96</td></tr>

<tr>
 <th colspan="5" class="climo-header-left">17 December 2003</th></tr>
<tr>
 <td></td><th>Time:</th><th>Temperature</th><th>Dew Point</th><th>Rel Humidity %</th></tr>
<tr>
 <td rowspan="6">Fairfield (FFL)</td>
     <td>19:17Z</td><td>34</td><td>23</td><td>64</td></tr>
 <tr><td>19:18Z</td><td>34</td><td>23</td><td>64</td></tr>
 <tr><td>19:19Z</td><td>34</td><td>23</td><td>64</td></tr>
 <tr class="even"><td>19:34Z</td><td>37</td><td>30</td><td>76</td></tr>
 <tr><td>19:35Z</td><td>37</td><td>30</td><td>76</td></tr>
 <tr><td>19:36Z</td><td>37</td><td>30</td><td>76</td></tr>

<tr>
 <td></td><th>Time:</th><th>Temperature</th><th>Dew Point</th><th>Rel Humidity %</th></tr>
<tr>
 <td rowspan="6">Fort Madison (FSW)</td>
     <td>21:43Z</td><td>37</td><td>24</td><td>59</td></tr>
 <tr><td>21:44Z</td><td>37</td><td>24</td><td>59</td></tr>
 <tr><td>21:45Z</td><td>38</td><td>24</td><td>57</td></tr>
 <tr class="even"><td>22:17Z</td><td>34</td><td>28</td><td>78</td></tr>
 <tr><td>22:18Z</td><td>34</td><td>28</td><td>78</td></tr>
 <tr><td>22:19Z</td><td>34</td><td>28</td><td>78</td></tr>

<tr>
 <td></td><th>Time:</th><th>Temperature</th><th>Dew Point</th><th>Rel Humidity %</th></tr>
<tr>
 <td rowspan="6">Keokuk (EOK)</td>
     <td>22:56Z</td><td>35</td><td>24</td><td>64</td></tr>
 <tr><td>22:57Z</td><td>35</td><td>24</td><td>64</td></tr>
 <tr><td>22:58Z</td><td>35</td><td>24</td><td>64</td></tr>
 <tr class="even"><td>23:14Z</td><td>34</td><td>27</td><td>75</td></tr>
 <tr><td>23:15Z</td><td>34</td><td>27</td><td>75</td></tr>
 <tr><td>23:16Z</td><td>34</td><td>27</td><td>75</td></tr>

<tr>
 <th colspan="5" class="climo-header-left">5 April 2004</th></tr>
<tr>
 <td></td><th>Time:</th><th>Temperature</th><th>Dew Point</th><th>Rel Humidity %</th></tr>
<tr>
 <td rowspan="6">Washington (AWG)</td>
     <td>18:11Z</td><td>57</td><td>27</td><td>31</td></tr>
 <tr><td>18:12Z</td><td>57</td><td>27</td><td>31</td></tr>
 <tr><td>18:13Z</td><td>57</td><td>27</td><td>31</td></tr>
 <tr class="even"><td>18:36Z</td><td>66</td><td>37</td><td>34</td></tr>
 <tr><td>18:37Z</td><td>66</td><td>37</td><td>34</td></tr>
 <tr><td>18:38Z</td><td>67</td><td>37</td><td>34</td></tr>


<tr>
 <th colspan="5" class="climo-header-left">19 May 2004</th></tr>
<tr>
 <td></td><th>Time:</th><th>Temperature</th><th>Dew Point</th><th>Rel Humidity %</th></tr>


<tr>
 <td rowspan="6">Adubon (ADU)</td>
     <td>13:40Z</td><td>60</td><td>54</td><td>80</td></tr>
 <tr><td>13:41Z</td><td>60</td><td>54</td><td>80</td></tr>
 <tr><td>13:42Z</td><td>60</td><td>54</td><td>80</td></tr>
 <tr class="even"><td>14:03Z</td><td>60</td><td>58</td><td>93</td></tr>
 <tr><td>14:04Z</td><td>60</td><td>58</td><td>93</td></tr>
 <tr><td>14:05Z</td><td>60</td><td>58</td><td>93</td></tr>

<tr>
 <td rowspan="6">Atlantic (AIO)</td>
     <td>15:21Z</td><td>65</td><td>57</td><td>75</td></tr>
 <tr><td>15:22Z</td><td>65</td><td>57</td><td>75</td></tr>
 <tr><td>15:23Z</td><td>65</td><td>57</td><td>75</td></tr>
 <tr class="even"><td>15:58Z</td><td>63</td><td>61</td><td>93</td></tr>
 <tr><td>15:59Z</td><td>63</td><td>61</td><td>93</td></tr>
 <tr><td>16:00Z</td><td>63</td><td>61</td><td>93</td></tr>

<tr>
 <td rowspan="6">Creston (CSQ)</td>
     <td>18:45Z</td><td>67</td><td>67</td><td>100</td></tr>
 <tr><td>18:46Z</td><td>68</td><td>68</td><td>100</td></tr>
 <tr><td>18:47Z</td><td>68</td><td>68</td><td>100</td></tr>
 <tr class="even"><td>19:29Z</td><td>71</td><td>69</td><td>93</td></tr>
 <tr><td>19:30Z</td><td>71</td><td>69</td><td>93</td></tr>
 <tr><td>19:31Z</td><td>71</td><td>69</td><td>93</td></tr>


</table>
</div>

<?php include("/mesonet/php/include/footer.php"); ?>
