<?php
include("../../../../config/settings.inc.php");
include("$rootpath/include/database.inc.php");

$state = isset($_GET['state']) ? $_GET['state'] : '' ;
$radar = isset($_GET['radar']) ? $_GET['radar'] : 1;
$refresh = isset($_GET['refresh']) ? $_GET['refresh'] : 0;
  // freeze.php
$uri = "freeze.phtml";

if ($state == "MN_N")
  $sextent = "-96, 44, -91, 49";
else if ($state == "MN_S")
  $sextent = "-96, 42, -91, 47";
else if ($state == "ND")
  $sextent = "-105, 45, -96, 47";
else if ($state == "SD")
  $sextent = "-105, 42, -96, 47";
else if ($state == "KS")
  $sextent = "-102.5, 37, -94.5, 40";
else if ($state == "NE")
  $sextent = "-104, 40, -95.3, 43";
else if ($state == "WI")
  $sextent = "-95, 43, -87, 47";
else if ($state == "IL")
  $sextent = "-93, 37, -87, 43";
else if ($state == "MO")
  $sextent = "-95, 36, -90, 41";
else if ($state == "IA_NE")
  $sextent = "-93.6, 41.9, -90, 43.8";
else if ($state == "IA_SE")
  $sextent = "-93.6, 40.3, -90, 41.9";
else if ($state == "IA_SW")
  $sextent = "-96.6, 40.3, -93.6, 41.9";
else if ($state == "IA_NW")
  $sextent = "-96.6, 41.9, -93.6, 43.8";
else if ($state == "IA")
  $sextent = "-96, 40, -91, 45";



 if (isset($sextent))
   $oextents = $sextent;
 else 
   $oextents = isset($_GET['extents']) ? $_GET['extents'] : "-105,36,-86,50";
 $zoom     = isset($_GET['zoom']) ? $_GET['zoom'] : 0;
 $imgwidth = 640;
 $imgheight = 480;
 if ( isset($_GET['img_x']) ){
   include("$rootpath/include/click2geo.inc.php");
   $extents = click2geo($oextents, $_GET['img_x'], $_GET['img_y'],
     $imgwidth, $imgheight, $zoom);
 } else {
   $extents = $oextents;
 }


function mktitle($map, $imgObj, $titlet) {
  $layer = $map->getLayerByName("credits");
                                                                                 
  // point feature with text for location
  $point = ms_newpointobj();
  $point->setXY(10, 15);
                                                                                 
  $point->draw($map, $layer, $imgObj, "credits",
    $titlet);
}
                                                                                 
function mklogolocal($map, $imgObj) {
                                                                                 
 $layer = $map->getLayerByName("logo");
                                                                                 
 // point feature with text for location
 $point = ms_newpointobj();
 $point->setXY(44, 24);
                                                                                 
 $point->draw($map, $layer, $imgObj, 0, "");
}


$map = ms_newMapObj("$rootpath/data/gis/base4326.map");

$arExtents = explode(",", $extents);
$map->setextent($arExtents[0], $arExtents[1], $arExtents[2], $arExtents[3]);

$namer = $map->getlayerbyname("namerica");
$namer->set("status", MS_ON);

$lakes = $map->getlayerbyname("lakes");
$lakes->set("status", MS_ON);

$states = $map->getlayerbyname("states");
$states->set("status", MS_ON);

$sites = $map->getlayerbyname("airtemps");
$sites->set("status", MS_ON);
$sites->set("connection", $_DATABASES["access"] );

$counties = $map->getlayerbyname("uscounties");
$counties->set("status", MS_ON);

$surface = $map->getlayerbyname("surface");
$surface->set("status", MS_ON);
$surface->set("connection", $_DATABASES["access"] );

$n0r = $map->getlayerbyname("nexrad_n0r");
$n0r->set("status", MS_ON);

$img = $map->prepareImage();
$namer->draw($img);
$lakes->draw($img);
if ($radar)
  $n0r->draw($img);
$counties->draw($img);
$states->draw($img);
$surface->draw($img);
$sites->draw($img);

$d = date("d F Y h:i a");

mktitle($map, $img, "                        IEM Freeze valid: ". $d);
$map->drawLabelCache($img);
mklogolocal($map, $img);

$ltmp = $map->drawLegend();
$legendsrc = $ltmp->saveWebImage();


$url = $img->saveWebImage();
?>

<?php
 if ($refresh > 0){
  echo "<meta http-equiv=\"refresh\" content=\"". $refresh ."; URL=". $uri ."?refresh=". $refresh ."&extents=". $extents ."&state=". $state ."\">\n";
 }
?>

<?php 
 $TITLE = "IEM Freeze";
 $HEADEXTRA = '<script Language="JavaScript">
 function resetButtons(){
   document.panButton.src = "../imagenav/button_pan_off.png";
   document.zoominButton.src = "../imagenav/button_zoomin_off.png";
   document.zoomoutButton.src = "../imagenav/button_zoomout_off.png";
 }
</script>';
 include("$rootpath/include/header.php"); ?>

<h3 class="heading">IEM Freeze (version 1.0)</h3><p><div class="text">

<form method="GET" action="<?php echo $uri; ?>" name="myform">

<input type="hidden" name="extents" value="<?php echo $extents; ?>">
<input type="hidden" name="state" value="<?php echo $state; ?>">
<input type="hidden" name="zoom" value="1">

<table style="width: 790px;" cellspacing="0" cellpadding="0" border=0>
<tr class="even"><td colspan=2>
<b>Map Controls:</b>
<img src="../imagenav/button_zoomin_off.png" name="zoominButton" alt="Zoom In"
  onClick="javascript: resetButtons(); document.zoominButton.src = '../imagenav/button_zoomin_on.png'; document.myform.zoom.value = -2;">
<img src="../imagenav/button_pan_on.png" name="panButton" alt="Pan"
  onClick="javascript: resetButtons(); document.panButton.src = '../imagenav/button_pan_on.png'; document.myform.zoom.value = 1;">
<img src="../imagenav/button_zoomout_off.png" name="zoomoutButton" alt="Zoom Out"
  onClick="javascript: resetButtons(); document.zoomoutButton.src = '../imagenav/button_zoomout_on.png'; document.myform.zoom.value = 2;">
<a href="<?php echo $uri; ?>">Reset</a>

&nbsp; &nbsp; <b>Radar Layer? </b>
<select name="radar">
  <option value="1" <?php if ($radar) echo "SELECTED"; ?>>Show
  <option value="0" <?php if (! $radar) echo "SELECTED"; ?>>Hide
</select>

&nbsp; &nbsp; <b>Map Refresh? </b>
<select name="refresh">
  <option value=0 <?php if ($refresh == 0) echo "SELECTED"; ?>>Never
  <option value=300 <?php if ($refresh == 300) echo "SELECTED"; ?>>5 minutes
  <option value=600 <?php if ($refresh == 600) echo "SELECTED"; ?>>10 minutes
</select>

<input type="submit" value="View">

</td></tr>
<tr><td>
<?php echo "<input type=\"image\" name=\"img\" src=\"$url\">"; ?></form>
</td><td bgcolor="#000" align="center">

<b><font color="white"><u>Preset Views:</u></font></b>
<form name="ba">
<select name="ba" onChange="location=this.form.ba.options[this.form.ba.selectedIndex].value">
 <option value="#"> -- User Defined --
 <option value="<?php echo $uri; ?>?state=A" <?php if ($state == "A") echo "SELECTED"; ?>>View All
 <option value="<?php echo $uri; ?>?state=IL" <?php if ($state == "IL") echo "SELECTED"; ?>>Illinois
 <option value="<?php echo $uri; ?>?state=IA" <?php if ($state == "IA") echo "SELECTED"; ?>>Iowa
 <option value="<?php echo $uri; ?>?state=IA_NE" <?php if ($state == "IA_NE") echo "SELECTED"; ?>>Iowa (NE)
 <option value="<?php echo $uri; ?>?state=IA_SE" <?php if ($state == "IA_SE") echo "SELECTED"; ?>>Iowa (SE)
 <option value="<?php echo $uri; ?>?state=IA_SW" <?php if ($state == "IA_SW") echo "SELECTED"; ?>>Iowa (SW)
 <option value="<?php echo $uri; ?>?state=IA_NW" <?php if ($state == "IA_NW") echo "SELECTED"; ?>>Iowa (NW)
 <option value="<?php echo $uri; ?>?state=KS" <?php if ($state == "KS") echo "SELECTED"; ?>>Kansas
 <option value="<?php echo $uri; ?>?state=NE" <?php if ($state == "NE") echo "SELECTED"; ?>>Nebraska
 <option value="<?php echo $uri; ?>?state=MN_N" <?php if ($state == "MN_N") echo "SELECTED"; ?>>Minnesota (North)
 <option value="<?php echo $uri; ?>?state=MN_S" <?php if ($state == "MN_S") echo "SELECTED"; ?>>Minnesota (South)
 <option value="<?php echo $uri; ?>?state=MO" <?php if ($state == "MO") echo "SELECTED"; ?>>Missouri
 <option value="<?php echo $uri; ?>?state=ND" <?php if ($state == "ND") echo "SELECTED"; ?>>North Dakota
 <option value="<?php echo $uri; ?>?state=SD" <?php if ($state == "SD") echo "SELECTED"; ?>>South Dakota
 <option value="<?php echo $uri; ?>?state=WI" <?php if ($state == "WI") echo "SELECTED"; ?>>Wisconsin
</select></form>
<b><font color="white"><u>Temperature Key:</u></font></b>

<img src="<?php echo $legendsrc; ?>">
<!--
<br><b><font color="#1e8914"> >= 35 </font></b>
<br><b><font color="#2ac11d"> >= 34 </font></b>
<br><b><font color="#35e025"> >= 33 </font></b>
<br><b><font color="#e840e2"> >= 32 </font></b>
<br><b><font color="#e872e2"> >= 31 </font></b>
<br><b><font color="#e8a4e2"> >= 30 </font></b>
<br><b><font color="#e8d6e2"> < 30 </font></b>
-->

</td></tr>
</table>

<br>
<table width="50%">
<tr><td></td></tr>
<tr><td>
<p><b>IEM Freeze</b> lets you quickly evaluate air
and pavement temperatures, along with concurrent radar observations
of precipitation:<br>
<ul>
<li><b>Pavement temperatures</b> are indicated by color-coded dots.</li>
<li><b>Air temperatures</b> are given by numerical values (also color-coded).</li>
<li><b>Current Composite RADAR</b> also is overlain on each plot.</li>
</ul>

<p>This <a href="http://mesonet.agron.iastate.edu/cool/images/freeze_031215.png">historical plot</a> shows how IEM Freeze looks when the winter weather gets interesting.</p>

</td></tr>
</table>
<p>Your feedback is needed!  Please let me know how you would like this 
application to behave.</div>


<?php include("$rootpath/include/footer.php"); ?>
