<?php 
require_once "../../../../config/settings.inc.php";

$OL = '3.11.0';

require_once "../../../../include/myview.php";

$t = new MyView();
$t->title = "IEM Local Storm Report Analysis";
$t->headextra = <<<EOF
<link rel="stylesheet" href="/vendor/openlayers/{$OL}/ol.css" type="text/css">
<link rel="stylesheet" href="/vendor/jquery-ui/1.11.4/jquery-ui.min.css" />
<link type="text/css" href="/vendor/openlayers/{$OL}/ol3-layerswitcher.css" rel="stylesheet" />
<link type="text/css" href="/vendor/datatables/1.10.10/datatables.min.css" rel="stylesheet" />
<style>
.map {
        height: 400px;
        width: 100%;
        background-color: #D2B48C;
}
.popover {
                width: 300px;
                }
</style>
EOF;

$t->jsextra = <<<EOF
<script src="/vendor/openlayers/{$OL}/ol.js" type="text/javascript"></script>
<script src="/vendor/jquery-ui/1.11.4/jquery-ui.js"></script>
<script src='/vendor/openlayers/{$OL}/ol3-layerswitcher.js'></script>
<script src='/vendor/datatables/1.10.10/datatables.min.js'></script>
<script src="lsr.js"></script>
EOF;
$content = <<<EOF

<div class="row">
		<div class="col-md-6">Map Goes Here
		<div id="map"></div>
		</div>
		<div class="col-md-6">Analysis Map Goes Here
		<div id='icontain'></div>
		</div>
</div>

<div class="row">
		<div class="col-md-6">Table goes Here</div>
	<table id="datatable">
		<thead><tr><th>Station</th><th>Snowfall [inch]</th></tr></thead>
	</table>
</div>
		

EOF;

$t->content = $content;

$t->render('full.phtml');
?>