<?php
include("../../config/settings.inc.php");
$TITLE = "IEM | Cocorahs Location Tester";
// $HEADEXTRA = "<script src=\"http://maps.google.com/maps?file=api&v=2&key=ABQIAAAArXt77YptylBNPFEy0AgJxBSIAqwrigl8jXGOsOEC-fLr61xmiRQCcUwpfUFnMcQA3EUy4XMAJpU3rQ\" type=\"text/javascript\"></script>";
$HEADEXTRA = "<script src=\"http://maps.google.com/maps?file=api&v=2&key=ABQIAAAArXt77YptylBNPFEy0AgJxBS839jvGSb8GoH9442gM8Cxu9GSaxTIrO8uKa5AWWGtCmI40oFahlLjiQ\" type=\"text/javascript\"></script>";
include("$rootpath/include/header.php"); 
?>

<h3>CoCoRaHs Naming Points Tester</h3>

This app overlays the naming points provided by CoCoRaHs HQ with google maps 
to see how they line up.  Click on the marker to get the name and lat/lon of
the point in the dataset.  The labels on the map are Google's.

<p><div id="map" style="border: 1px solid #000; margin-left: 5px; width: 670px; height: 530px"></div>

<script type="text/javascript">
    //<![CDATA[

    var map = new GMap2(document.getElementById("map"));
    map.addControl(new GLargeMapControl());
    map.addControl(new GMapTypeControl());
    map.addControl(new GOverviewMapControl());
    map.setCenter(new GLatLng(42.0234, -93.6256), 10);


var icon = new GIcon();
icon.image = "http://labs.google.com/ridefinder/images/mm_20_blue.png";
icon.shadow = "http://labs.google.com/ridefinder/images/mm_20_shadow.png";
icon.iconSize = new GSize(12, 20);
icon.shadowSize = new GSize(22, 20);
icon.iconAnchor = new GPoint(6, 20);
icon.infoWindowAnchor = new GPoint(5, 1);

function addPoint(lon, lat, city)
{
    var point = new GPoint(lon, lat);
    var marker = new GMarker(point, icon);
    GEvent.addListener(marker, "click", function() {
       marker.openInfoWindowHtml(city+"<br />"+lat+"<br />"+lon);
    });
    map.addOverlay(marker);

}

<?php
 $fc = file('cities_2006_IA.txt');
 while (list ($line_num, $line) = each ($fc)) {
   $tokens = explode(" ", trim($line),5);
   if (count($tokens) < 4) continue;
?>
    addPoint(<?php echo $tokens[1]; ?>, <?php echo $tokens[0]; ?>,"<?php echo $tokens[4]; ?>");

<?php  } ?>


    //]]>
    </script>
<?php
include("$rootpath/include/footer.php"); 
?>
