<?php 
include("../../config/settings.inc.php");
define("IEM_APPID", 56);
$network = isset($_GET['network']) ? $_GET['network'] : 'IACOCORAHS'; 
$sortcol = isset($_GET['sortcol']) ? $_GET['sortcol'] : 'ts';

$TITLE = "IEM | CoCoRaHS | Last Observation";
$HEADEXTRA = '<script language="JavaScript" type="text/javascript">
	<!--//BEGIN Script
	function new_window(url) {
 	link = window.open(url,"_new","toolbar=0,location=0,directories=0,status=0,menubar=no,scrollbars=yes,resizable=yes,width=800,height=600");
	}
	//END Script-->
	</script>
<script type="text/javascript" src="/js/tableruler.js"></script>
<script type="text/javascript">
    window.onload=function(){tableruler();}
</script>';
 $THISPAGE = "current-sort";
include("$rootpath/include/header.php"); ?>
<div class="text">
<?php
 include("$rootpath/include/network.php");
 $nt = new NetworkTable($network);

 include("$rootpath/include/iemaccess.php");
 include("$rootpath/include/iemaccessob.php");
 include_once("$rootpath/include/database.inc.php");

 /* Compute monthly rainfall totals! */
 $dbconn = iemdb("access");
 $year = date("Y");
 $first_of_month = date("Y-m");
 $sql = "SELECT id, 
   sum(case WHEN pday < 0 THEN 0 ELSE pday END) as pmonth, 
   sum(case WHEN pday < 0 THEN 1 ELSE 0 END) as missing from 
   summary_$year s, stations t WHERE t.network = '$network' and t.iemid = s.iemid
   and day >= '${first_of_month}-01' GROUP by id";
 $rs = pg_exec($dbconn, $sql);
 $monthDict = Array();
 for( $i=0; $row = @pg_fetch_array($rs,$i); $i++){ 
   $monthDict[ $row["id"] ] = Array("accum" => round($row["pmonth"],2), "missing" => $row["missing"] );
 }

 $iem = new IEMAccess();
 $net = $iem->getNetwork($network);

 $db = Array();
 while (list($site, $iemob) = each($net) ){
  $db[$site] = Array('snow'=> "", 'snowd'=>"", 'ratio'=>"", 'pday'=>"", 'pmonth'=>"", 'pmiss' => "");
  $db[$site]['ts'] = $iemob->ts;
  $db[$site]['sid'] = $site;
  $db[$site]['sname'] = $iemob->db["sname"];
  $db[$site]['county'] = $nt->table[$site]["county"];
  if ( date("Ym") == date("Ym", $iemob->ts) ){
    $db[$site]['pmonth'] = @$monthDict[$site]["accum"];
    $db[$site]['pmiss'] = @$monthDict[$site]["missing"];
  }
  if ( date("Ymd") != date("Ymd", $iemob->ts) ){
    continue;
  }


  $db[$site]['pday'] = $iemob->db["ob_pday"];
  $db[$site]['snow'] = ($iemob->db["snow"] >= 0) ? $iemob->db["snow"] : " ";
  $db[$site]['snowd'] = ($iemob->db["snowd"] >= 0) ? $iemob->db["snowd"] : " ";
  $db[$site]["ratio"] = -1;
  if ($db[$site]["snow"] > 0.001 && $db[$site]["pday"] > 0.001)
   {
     $db[$site]["ratio"] = intval( $db[$site]["snow"] / $db[$site]["pday"] );
   }
 }

function aSortBySecondIndex($multiArray, $secondIndex) {
        while (list($firstIndex, ) = each($multiArray))
                $indexMap[$firstIndex] = $multiArray[$firstIndex][$secondIndex];        arsort($indexMap);
        while (list($firstIndex, ) = each($indexMap))
                if (is_numeric($firstIndex))
                        $sortedArray[] = $multiArray[$firstIndex];
                else $sortedArray[$firstIndex] = $multiArray[$firstIndex];
        return $sortedArray;
}

$db = aSortBySecondIndex($db, $sortcol);

$cols = Array("ts" => "Valid", "county" => "County",
  "sid" => "Site ID", "sname" => "Station Name",
  "tmpf" => "Ob Temperature", "max_tmpf" => "24 hour High",
  "min_tmpf" => "24 hour Low", "snow" => "24 hour Snowfall",
  "snowd" => "Snowfall Depth", "pday" => "24 hour rainfall",
  "phour" => "Rainfall One Hour", "pmonth" => "Rainfall for Month");
?>

<?php $current_network = "CoCoRaHS"; include("$rootpath/include/current_bar.inc.php"); ?>

<form method="GET" action="current.phtml" name="stctrl">
<input type="hidden" name="sortcol" value="<?php echo $sortcol; ?>">
<b>Show State:</b><select name="network">
  <option value="IACOCORAHS" <?php if ($network == "IACOCORAHS") echo "SELECTED"; ?>>Iowa
  <option value="ILCOCORAHS" <?php if ($network == "ILCOCORAHS") echo "SELECTED"; ?>>Illinois
</select>
<input type="submit" value="Go!">
</form>


<?php
echo "<p>Sorted by: ". $cols[$sortcol] ;


 $baseurl2 = "current.phtml?network=$network&sortcol=";
?> . The number of observations missing for this month is shown in parenthesis.
<form name="st" action="/my/current.phtml" method="GET">
<table style="width: 100%; font-size: 10pt;" class="ruler" border="1">
<thead>
<tr>
  <th rowspan=2>Add:</th>
  <th rowspan=2><a href="<?php echo $baseurl2; ?>sid">SiteID:</a></th>
  <th rowspan=2><a href="<?php echo $baseurl2; ?>sname">Station Name:</a></th>
  <th rowspan=2><a href="<?php echo $baseurl2; ?>county">County:</a></th>
  <th rowspan=2><a href="<?php echo $baseurl2; ?>ts">Valid:</a></th>
  <th colspan=5>Hydro</th></tr>

<tr>
  <th><a href="<?php echo $baseurl2; ?>pday">24hour Rain</a></th>
  <th><a href="<?php echo $baseurl2; ?>pmonth">Month Rain</a></th>
  <th><a href="<?php echo $baseurl2; ?>snow">Snowfall</a></th>
  <th><a href="<?php echo $baseurl2; ?>ratio">Ratio</a></th>
  <th><a href="<?php echo $baseurl2; ?>snowd">Snow Depth</a></th>
</tr></thead>
<tbody>
<?php
 $oddrow = true;
 $now = time();
 while (list($site, $value) = each($db) ){
   $tdiff = $now - $value["ts"];
   if ( intval( date("Y", $value["ts"]) ) < 2003 ) continue;
   $oddrow = ! $oddrow;

   echo "<tr ";
   if ($oddrow) echo "bgcolor=\"#EEEEEE\"";
   echo "><th><input type=\"checkbox\" name=\"st[]\"
   value=\"".$site."\"></th><td> $site </td>
    <td>". $value["sname"] ."</td>
    <td>". $value["county"] ."</td>";
   echo "<td ";
   if ($tdiff > (24*3600) || date("Ymd") != date("Ymd", $value["ts"]) ){
     echo 'bgcolor="red">'. strftime("%d %b %I:%M %p", $value["ts"]) .'</td>';
   } else {
     echo ">". strftime("%I:%M %p", $value["ts"]) ."</td>";
   }

   if ($value["pday"] == 0.0001) $value["pday"] = "T";
   if ($value["pmonth"] == 0.0001) $value["pmonth"] = "T";
   if ($value["pday"] < 0) $value["pday"] = "M";
   if ($value["snow"] == 0.0001) $value["snow"] = "T";
   if ($value["snowd"] == 0.0001) $value["snowd"] = "T";
   if ($value["snow"] < 0) $value["snow"] = "M";

   echo "<td>". $value["pday"] ."</td>";
   echo "<td>". $value["pmonth"];
   if ($value["pmiss"] > 0) echo " (". $value["pmiss"] .")";
    echo "</td>";
    echo "<td>". $value["snow"] ."</td>";
    if ($value["ratio"] > 0) echo "<td>". $value["ratio"] ."</td>";
    else echo "<td></td>";
    echo "<td>". $value["snowd"] ."</td>";
   echo "</tr>";
 }
?>
</tbody><tfoot>
<tr>
 <td colspan=5>&nbsp;</td>
<?php $c = "javascript:new_window('$rooturl/GIS/apps/php/currents.phtml?layers[]=radar&layers[]=labels&network=$network&var="; ?>
 <td><a href="<?php echo $c; ?>pday');">Plot</a></td>
 <td></td>
 <td><a href="<?php echo $c; ?>snow');">Plot</a></td>
 <td></td>
 <td><a href="<?php echo $c; ?>snowd');">Plot</a></td>
</tr></tfoot>

<?php
 echo "</table>";
 echo "<input type=\"submit\" value=\"Add to Favorites\">\n</form>";
?>
</div>

<?php include("$rootpath/include/footer.php");
?>
