<?php 
require_once "../../config/settings.inc.php";
require_once "../../include/myview.php";
require_once "../../include/network.php";
require_once "../../include/forms.php";
require_once "../../include/database.inc.php";
require_once "../../include/mlib.php";
$t = new MyView();

define("IEM_APPID", 56);
$network = isset($_GET['network']) ? xssafe($_GET['network']): 'IA_COCORAHS'; 
$sortcol = isset($_GET['sortcol']) ? xssafe($_GET['sortcol']): 'ts';

$nselect = '<select name="network">';
$mesosite = iemdb("mesosite");
$rs = pg_query(
    $mesosite,
    "SELECT id, name from networks where id ~* '_COCORAHS' ORDER by name ASC");
for ($i = 0; $row = pg_fetch_assoc($rs); $i++) {
    $sel = '';
    if ($network == $row["id"]) {
        $sel = " selected='SELECTED'";
    }
    $nselect .= sprintf(
        "<option value='%s'%s>%s</option>\n",
        $row["id"],
        $sel,
        $row["name"]
    );
}
$nselect .= "</select>";

$t->title = "CoCoRaHS Last Observation";
$t->headextra = <<<EOF
<script language="JavaScript" type="text/javascript">
    <!--//BEGIN Script
    function new_window(url) {
     link = window.open(url,"_new","toolbar=0,location=0,directories=0,status=0,menubar=no,scrollbars=yes,resizable=yes,width=800,height=600");
    }
    //END Script-->
    </script>
EOF;
$t->current_network = "CoCoRaHS";

$nt = new NetworkTable($network);

$dbconn = iemdb("coop");
$year = date("Y");
$sql = <<<EOM
with today as (
    select t.id, c.*, t.tzname
    from cocorahs_$year c JOIN stations t on (c.iemid = t.iemid)
    WHERE day = 'TODAY' and t.network = $1),
month as (
    SELECT iemid,
    sum(precip) as pmonth, count(*) as count from 
    cocorahs_$year s WHERE day >= $2 GROUP by iemid)

select t.*, m.pmonth, m.count,
obvalid at time zone t.tzname as local_valid
from today t JOIN month m on (t.iemid = m.iemid)
ORDER by t.id asc
EOM;
$day1 = new DateTime();
;
$rs = pg_prepare($dbconn, "CS", $sql);
 $rs = pg_execute($dbconn, "CS", array($network, $day1->format("Y-m") .'-01'));
 $monthDict = Array();
 $db = Array();
 for( $i=0; $row = pg_fetch_array($rs); $i++){
  $site = $row["id"];
  $db[$site] = Array(
    'pmonth' => $row["pmonth"],
    'count' => $row["count"],
    'snow'=> "", 'snowd'=>"", 'ratio'=>"", 'pday'=>"", 'pmonth'=>"", 'pmiss' => "");
  $db[$site]['ts'] = strtotime($row["local_valid"]);
  $db[$site]['sid'] = $site;
  $db[$site]['name'] = $nt->table[$site]["name"];
  $db[$site]['county'] = $nt->table[$site]["county"];
  $db[$site]['pday'] = $row["precip"];
  $db[$site]['snow'] = ($row["snow"] >= 0) ? $row["snow"] : " ";
  $db[$site]['snowd'] = ($row["snowd"] >= 0) ? $row["snowd"] : " ";
  $db[$site]["ratio"] = -1;
  if ($db[$site]["snow"] > 0.0001 && $db[$site]["pday"] > 0.0001)
   {
     $db[$site]["ratio"] = intval( $db[$site]["snow"] / $db[$site]["pday"] );
   }
}
$db = aSortBySecondIndex($db, $sortcol, "desc");

$cols = Array("ts" => "Valid", "county" => "County",
  "sid" => "Site ID", "name" => "Station Name",
  "tmpf" => "Ob Temperature", "max_tmpf" => "24 hour High",
  "min_tmpf" => "24 hour Low", "snow" => "24 hour Snowfall",
  "snowd" => "Snowfall Depth", "pday" => "24 hour rainfall",
  "pmonth" => "Precipitation for Month");

$baseurl2 = "current.phtml?sortcol=";
$content = <<<EOM
<p>Sorted by: {$cols[$sortcol]}. 
The number of observations missing for this month is shown in parenthesis.

<form method="GET" action="current.phtml" name="stctrl">
<input type="hidden" name="sortcol" value="{$sortcol}">
Option 1: <strong>View by State:</strong> {$nselect}
<input type="submit" value="Go!">
</form>


<form name="st" action="/my/current.phtml" method="GET">
<table class="table table-striped table-condensed table-bordered">
<thead>
<tr>
  <th rowspan="2">Add:</th>
  <th rowspan="2"><a href="{$baseurl2}sid">SiteID:</a></th>
  <th rowspan="2"><a href="{$baseurl2}name">Station Name:</a></th>
  <th rowspan="2"><a href="{$baseurl2}county">County:</a></th>
  <th rowspan="2"><a href="{$baseurl2}ts">Valid:</a></th>
  <th colspan="5">Hydro</th></tr>

<tr>
  <th><a href="{$baseurl2}pday">24hour Precip</a></th>
  <th><a href="{$baseurl2}pmonth">Month Precip</a></th>
  <th><a href="{$baseurl2}snow">Snowfall</a></th>
  <th><a href="{$baseurl2}ratio">Ratio</a></th>
  <th><a href="{$baseurl2}snowd">Snow Depth</a></th>
</tr></thead>
<tbody>
EOM;
 $oddrow = true;
 $now = time();
 foreach($db as $site => $value){
   $tdiff = $now - $value["ts"];
   if ( intval( date("Y", $value["ts"]) ) < 2003 ) continue;
   $oddrow = ! $oddrow;

   $content .= "<tr ";
   if ($oddrow) $content .= "bgcolor=\"#EEEEEE\"";
   $content .= <<<EOM
><th><input type="checkbox" name="st[]"
   value="{$site}"></th><td><a href="/sites/site.php?station={$site}&network={$network}">$site</a></td>
    <td>{$value["name"]}</td>
    <td>{$value["county"]}</td>
EOM;
   $content .= "<td ";
   if ($tdiff > (24*3600) || date("Ymd") != date("Ymd", $value["ts"]) ){
     $content .= 'bgcolor="red">'. date("d M Y h:i A", $value["ts"]) .'</td>';
   } else {
     $content .= ">". date("h:i A", $value["ts"]) ."</td>";
   }

   if ($value["pday"] == 0.0001) $value["pday"] = "T";
   if ($value["pmonth"] == 0.0001) $value["pmonth"] = "T";
   if ($value["pday"] < 0) $value["pday"] = "M";
   if ($value["snow"] == 0.0001) $value["snow"] = "T";
   if ($value["snowd"] == 0.0001) $value["snowd"] = "T";
   if ($value["snow"] < 0) $value["snow"] = "M";

   $content .= "<td>". $value["pday"] ."</td>";
   $content .= "<td>". $value["pmonth"];
   if ($value["pmiss"] > 0) $content .= " (". $value["pmiss"] .")";
    $content .= "</td>";
    $content .= "<td>". $value["snow"] ."</td>";
    if ($value["ratio"] > 0) $content .= "<td>". $value["ratio"] ."</td>";
    else $content .= "<td></td>";
    $content .= "<td>". $value["snowd"] ."</td>";
   $content .= "</tr>";
 }
$content .= <<<EOM
</tbody>
</table>
<input type="submit" value="Add to Favorites">
         </form>
EOM;
$t->content = $content;
$t->render('sortables.phtml');
