<?php 
require_once "../../config/settings.inc.php";
require_once "../../include/myview.php";
require_once "../../include/network.php";
require_once "../../include/forms.php";
require_once "../../include/database.inc.php";
require_once "../../include/mlib.php";
$t = new MyView();

define("IEM_APPID", 56);
$network = isset($_GET['network']) ? xssafe($_GET['network']): 'IACOCORAHS'; 
$sortcol = isset($_GET['sortcol']) ? xssafe($_GET['sortcol']): 'ts';

$t->title = "CoCoRaHS Last Observation";
$t->headextra = <<<EOF
<script language="JavaScript" type="text/javascript">
    <!--//BEGIN Script
    function new_window(url) {
     link = window.open(url,"_new","toolbar=0,location=0,directories=0,status=0,menubar=no,scrollbars=yes,resizable=yes,width=800,height=600");
    }
    //END Script-->
    </script>
EOF;
$t->current_network = "CoCoRaHS";

 $nt = new NetworkTable($network);

 /* Compute monthly rainfall totals! */
 $dbconn = iemdb("iem");
 $year = date("Y");
 $first_of_month = date("Y-m");
 $sql = "SELECT id, 
   sum(case WHEN pday < 0 THEN 0 ELSE pday END) as pmonth, 
   sum(case WHEN pday < 0 THEN 1 ELSE 0 END) as missing from 
   summary_$year s, stations t WHERE t.network = '$network' and t.iemid = s.iemid
   and day >= '${first_of_month}-01' GROUP by id";
 $rs = pg_exec($dbconn, $sql);
 $monthDict = Array();
 for( $i=0; $row = pg_fetch_array($rs); $i++){ 
   $monthDict[ $row["id"] ] = Array("accum" => round($row["pmonth"],2), "missing" => $row["missing"] );
 }

$arr = Array("network" => $network);
$jobj = iemws_json("currents.json", $arr);

 $db = Array();
 foreach($jobj["data"] as $bogus => $iemob){
     $site = $iemob["station"];
  $db[$site] = Array('snow'=> "", 'snowd'=>"", 'ratio'=>"", 'pday'=>"", 'pmonth'=>"", 'pmiss' => "");
  $db[$site]['ts'] = strtotime($iemob["local_valid"]);
  $db[$site]['sid'] = $site;
  $db[$site]['name'] = $iemob["name"];
  $db[$site]['county'] = $nt->table[$site]["county"];
  if ( date("Ym") == date("Ym", strtotime($iemob["local_valid"])) ){
    $db[$site]['pmonth'] = @$monthDict[$site]["accum"];
    $db[$site]['pmiss'] = @$monthDict[$site]["missing"];
  }
  if ( date("Ymd") != date("Ymd", strtotime($iemob["local_valid"])) ){
    continue;
  }


  $db[$site]['pday'] = $iemob["ob_pday"];
  $db[$site]['snow'] = ($iemob["snow"] >= 0) ? $iemob["snow"] : " ";
  $db[$site]['snowd'] = ($iemob["snowd"] >= 0) ? $iemob["snowd"] : " ";
  $db[$site]["ratio"] = -1;
  if ($db[$site]["snow"] > 0.0001 && $db[$site]["pday"] > 0.0001)
   {
     $db[$site]["ratio"] = intval( $db[$site]["snow"] / $db[$site]["pday"] );
   }
 }

$db = aSortBySecondIndex($db, $sortcol, "desc");

$cols = Array("ts" => "Valid", "county" => "County",
  "sid" => "Site ID", "name" => "Station Name",
  "tmpf" => "Ob Temperature", "max_tmpf" => "24 hour High",
  "min_tmpf" => "24 hour Low", "snow" => "24 hour Snowfall",
  "snowd" => "Snowfall Depth", "pday" => "24 hour rainfall",
  "phour" => "Rainfall One Hour", "pmonth" => "Rainfall for Month");

$baseurl2 = "current.phtml?sortcol=";
$content = <<<EOF
<p>Sorted by: {$cols[$sortcol]}. 
The number of observations missing for this month is shown in parenthesis.
<form name="st" action="/my/current.phtml" method="GET">
<table class="table table-striped table-condensed table-bordered">
<thead>
<tr>
  <th rowspan="2">Add:</th>
  <th rowspan="2"><a href="{$baseurl2}sid">SiteID:</a></th>
  <th rowspan="2"><a href="{$baseurl2}name">Station Name:</a></th>
  <th rowspan="2"><a href="{$baseurl2}county">County:</a></th>
  <th rowspan="2"><a href="{$baseurl2}ts">Valid:</a></th>
  <th colspan="5">Hydro</th></tr>

<tr>
  <th><a href="{$baseurl2}pday">24hour Rain</a></th>
  <th><a href="{$baseurl2}pmonth">Month Rain</a></th>
  <th><a href="{$baseurl2}snow">Snowfall</a></th>
  <th><a href="{$baseurl2}ratio">Ratio</a></th>
  <th><a href="{$baseurl2}snowd">Snow Depth</a></th>
</tr></thead>
<tbody>
EOF;
 $oddrow = true;
 $now = time();
 foreach($db as $site => $value){
   $tdiff = $now - $value["ts"];
   if ( intval( date("Y", $value["ts"]) ) < 2003 ) continue;
   $oddrow = ! $oddrow;

   $content .= "<tr ";
   if ($oddrow) $content .= "bgcolor=\"#EEEEEE\"";
   $content .= <<<EOF
><th><input type="checkbox" name="st[]"
   value="{$site}"></th><td><a href="/sites/site.php?station={$site}&network={$network}">$site</a></td>
    <td>{$value["name"]}</td>
    <td>{$value["county"]}</td>
EOF;
   $content .= "<td ";
   if ($tdiff > (24*3600) || date("Ymd") != date("Ymd", $value["ts"]) ){
     $content .= 'bgcolor="red">'. strftime("%d %b %Y %I:%M %p", $value["ts"]) .'</td>';
   } else {
     $content .= ">". strftime("%I:%M %p", $value["ts"]) ."</td>";
   }

   if ($value["pday"] == 0.0001) $value["pday"] = "T";
   if ($value["pmonth"] == 0.0001) $value["pmonth"] = "T";
   if ($value["pday"] < 0) $value["pday"] = "M";
   if ($value["snow"] == 0.0001) $value["snow"] = "T";
   if ($value["snowd"] == 0.0001) $value["snowd"] = "T";
   if ($value["snow"] < 0) $value["snow"] = "M";

   $content .= "<td>". $value["pday"] ."</td>";
   $content .= "<td>". $value["pmonth"];
   if ($value["pmiss"] > 0) $content .= " (". $value["pmiss"] .")";
    $content .= "</td>";
    $content .= "<td>". $value["snow"] ."</td>";
    if ($value["ratio"] > 0) $content .= "<td>". $value["ratio"] ."</td>";
    else $content .= "<td></td>";
    $content .= "<td>". $value["snowd"] ."</td>";
   $content .= "</tr>";
 }
$content .= <<<EOF
</tbody>
</table>
<input type="submit" value="Add to Favorites">
         </form>
EOF;
$t->content = $content;
$t->render('sortables.phtml');
