<?php 
require_once "../../config/settings.inc.php";
require_once "../../include/myview.php";
$t = new MyView();

$t->title = "CoCoRaHS";

$t->content = <<<EOF

<h3>Community Collaborative Rain, Hail, and Snow Network</h3>
		
<p><a href="https://cocorahs.org">CoCoRaHS</a> is a nationwide effort to collect
	observations of rain, hail, and snowfall.  This network is a lot like the
	<a href="/COOP/">NWS Cooperative Observer (COOP)</a> network, but is not
	official.  The IEM collects the daily reports from this network and
	offers a few tools for the dataset.</p>

<ul>
	<li><a href="current.phtml">Sortable Currents</a></li>
	<li><a href="obs.phtml">View Observations by date or site</a></li>
</ul>
	
EOF;
$t->render('single.phtml');
