<?php
require_once "../../config/settings.inc.php";
define("IEM_APPID", 57);
require_once "../../include/database.inc.php";
require_once "../../include/myview.php";
require_once "../../include/forms.php";
require_once "../../include/imagemaps.php";

$access = iemdb("coop");

$t = new MyView();
$t->title = "CoCoRaHS Observations";

$station = isset($_GET["station"]) ? xssafe($_GET["station"]) : null;
$network = isset($_GET["network"]) ? xssafe($_GET["network"]) : "IA_COCORAHS";
$datestr = isset($_GET["date"]) ? substr(xssafe($_GET["date"]), 0, 10) : date("Y-m-d");
$sortvar = isset($_GET["sortvar"]) ? substr(xssafe($_GET["sortvar"]), 0, 10) : "precip";
$year = get_int404("year", date("Y"));

$single_station_mode = !is_null($station);

try {
    $dt = new DateTime($datestr);
} catch (Exception $e) {
    xssafe("<tag>");
}
if ($sortvar == "pday") {
    $sortvar = "precip";
}
$opts = array("precip", "snow", "snowd", "station");
if (!in_array($sortvar, $opts)) {
    $sortvar = "precip";
}
$sortdir = "ASC";
if (
    $sortvar == "precip" || $sortvar == "snow" ||
    $sortvar == "snowd" || $sortvar == "max_tmpf"
) {
    $sortdir = "DESC";
}
$stname = uniqid();
if ($single_station_mode) {
    $link = "obs.phtml?station=$station&network=$network&year={$year}&sortvar=";
    pg_prepare(
        $access,
        $stname,
        <<<EOM
    SELECT s.*, t.id as station, t.name, t.county
    from cocorahs_$year s JOIN stations t
    ON (t.iemid = s.iemid) WHERE t.id = $1
    ORDER by $sortvar $sortdir
EOM
    );
    $rs = pg_execute($access, $stname, array($station));
} else {
    $year = $dt->format("Y");
    $link = "obs.phtml?network=$network&date={$datestr}&sortvar=";
    $table = sprintf("cocorahs_%s", $dt->format("Y"));
    pg_prepare(
        $access,
        $stname,
        <<<EOM
        SELECT s.*, t.id as station, t.name, t.county
        from $table s JOIN stations t
        ON (t.iemid = s.iemid) WHERE day = $1 and
        network = $2 ORDER by $sortvar $sortdir
EOM
    );
    $rs = pg_execute($access, $stname, array($dt->format("Y-m-d"), $network));
}
$hirow = 1;
$table = "";

function fmt($val){
    if (is_null($val)){
        return "M";
    }
    if ($val > 0 && $val < 0.005){
        return "T";
    }
    return $val;
}

while ($row = pg_fetch_assoc($rs)) {
    $nwsli = $row["station"];

    $rain = fmt($row["precip"]);
    $snow = fmt($row["snow"]);
    $snowd = fmt($row["snowd"]);

    $table .= sprintf(
        '<tr><td><a href="obs.phtml?station=%s&network=%s&year=%s">%s</a></td>'.
        '<td>%s</td><td>%s</td>'.
        '<td><a href="obs.phtml?date=%s&network=%s">%s</a></td>'.
        '<td>%s</td><td>%s</td><td>%s</td></tr>',
        $nwsli,
        $network,
        $year,
        $nwsli,
        $row["name"],
        $row["county"],
        $row["day"],
        $network,
        $row["day"],
        $rain,
        $snow,
        $snowd,
    );

}

$ss = networkSelect($network, $station);
$nselect = selectNetworkType("COCORAHS", $network);
$ys =  yearSelect(2000, $year, "year");

$t->content = <<<EOM
<ol class="breadcrumb">
 <li><a href="/cocorahs/">CoCoRaHS Mainpage</a></li>
 <li class="active">CoCoRaHS Obs by Date or Station</li>
</ol>

<p>This page allows you to explore CoCoRaHS observations for a given
state by date or by single station for a given year.
You can then click on stations and dates to update
the data presentation.</p>

<form method="GET" name="switchnet">
<p><strong>Option 1: Select State and Date:</strong><br />
State: {$nselect} Date:
<input type="date" name="date" value="{$datestr}">
<input type="submit"></p>
</form>

<form method="GET" name="switchnet2">
<p><strong>Option 2: Select Station and Year:</strong><br />
Station: {$ss} Year: {$ys}
<input type="submit"></p>
</form>

<p><table class="table table-striped table-bordered">
<thead class="sticky">
<tr>
  <th><a href="{$link}station">ID #:</a></th>
  <th>Site Name:</th>
  <th>County:</th>
  <th><a href="{$link}day">Date:</a></th>
  <th><a href="{$link}precip">Precip</a></th>
  <th><a href="{$link}snow">Snowfall</a></th>
  <th><a href="{$link}snowd">Snow Depth</a></th></tr>
</thead>
<tbody>
{$table}
</tbody>
</table>

<p>Theoretically, you should be able to highlight the entire table with 
your cursor and then copy-paste it into a spreadsheet program if you 
like.

<p>Errors exist in this dataset and you should evaluate the observations
before using...</div>
EOM;
$t->render('full.phtml');
