<?php
include("../../../../config/settings.inc.php");
include("$rootpath/include/database.inc.php");

/* $_GET vars */
$wfo = isset($_GET["wfo"]) ? substr($_GET["wfo"],0,3) : die("variable wfo not set. Exit.");
$event_id = isset($_GET["event_id"]) ? intval($_GET["event_id"]) : die("variable event_id not set. Exit.");
$phenomena = isset($_GET["phenomena"]) ? substr($_GET["phenomena"],0,2) : die("variable phenomena not set. Exit.");
$year = isset($_GET["year"]) ? intval($_GET["year"]) : date("Y");


$connect = iemdb("postgis");
$query = "SELECT report, svs from warnings_$year WHERE wfo = '$wfo' and eventid = $event_id and phenomena = '$phenomena'";

$result = pg_exec($connect, $query);

$row = pg_fetch_array($result, 0);
?>
<?php include("$rootpath/include/header.php"); ?>
<pre><?php echo $row["report"]; ?></pre>
<?php
if (strlen($row["svs"]) > 0 )
{
 $parts = explode('__', $row["svs"]);
 for ($i=1;$i<(sizeof($parts) - 1);$i++)
 {
   echo "<h4><a name=\"svs\">SVS Update</a>:</h4><pre>". $parts[$i] ."</pre>\n"; }
}
?>
<?php include("$rootpath/include/footer.php"); ?>
