<?php
include("../../../../config/settings.inc.php");
include("$rootpath/include/database.inc.php");
 /* Draw Details of Warning */
 $wfo = isset($_GET["wfo"]) ? substr($_GET["wfo"], 0,3) : 'DMX';
 $type = isset($_GET["type"]) ? substr($_GET["type"], 0,3) : 'SVR';
 $eventid = isset($_GET["eventid"]) ? intval($_GET["eventid"]) : 3;

$pgconn = iemdb("postgis");

/* First we query to see if this is a valid polygon */
$sql = "SELECT *, xmax(geom) as xmax, xmin(geom) as xmin, ymax(geom) as ymax, ymin(geom) as ymin from warnings_2005 WHERE wfo = '$wfo' and eventid = '$eventid' and type = '$type' and gtype = 'P'";
$rs = pg_query($pgconn, $sql);
$row = pg_fetch_array($rs, 0);
$geom = $row["geom"];
$report = $row["report"];
echo $row["issue"];
$issuets = strtotime($row["issue"]);
$expirets = strtotime($row["expire"]);
$basets = $issuets + (($expirets - $issuets) / 2.0);
echo "--". $issuets ."--";
$now = time();
if ($now - $basets > 3600)  $isarchive = 1;
echo $isarchive;
$ar = localtime($basets);
$m = $ar[1];

if ($m > 55) $ma = "55";
else if ($m > 50) $ma = "50";
else if ($m > 45) $ma = "45";
else if ($m > 40) $ma = "40";
else if ($m > 35) $ma = "35";
else if ($m > 30) $ma = "30";
else if ($m > 25) $ma = "25";
else if ($m > 20) $ma = "20";
else if ($m > 15) $ma = "15";
else if ($m > 10) $ma = "10";
else if ($m > 5) $ma = "05";
else $ma = "00";
$diff = $m - intval($ma);
$basets = $basets - ($diff * 60);
$basets = strtotime( gmdate("Y/m/d H:i", $basets) );
$year = gmdate("Y", $basets);
$width = 640;
$height = 480;
$y0 = $row["ymin"] - 1;
$y1 = $row["ymax"] + 1;
$x0 = $row["xmin"] - 1;
$x1 = $row["xmax"] + 1;
include('lib.php');

dl("php_mapscript_442.so");
$imgi = 0;
include("warnings_plot.php");
echo $q;
$imgurl = $url;

/* Query out demographics */
$sql = "SELECT * from cities WHERE the_geom && '$geom' ORDER by pop_1990 DESC";
$rs = pg_query($pgconn, $sql);
$cities = Array();
for( $i=0; $row = @pg_fetch_array($rs,$i); $i++) {
  $cities[] = $row;
}
?>



<?php include("/mesonet/php/include/header.php"); ?>


<table border="0" cellpadding="0" cellspacing="0" >

 


  <tr>
    <td bgcolor="#EEEECC"><b><font face="verdana,arial,helvetica" color="#cc6600" size="4">&nbsp;Tornado Warning&nbsp;</font></b></td>
  </tr>

  

</table>




<!-- **************** Get Warning Data *********************************** -->
<!-- ************************************************************************************* -->




<!-- *********************** Calculate SF3 Section   ********************************** -->




<!-- *********************** Calculate SF1 Section   ********************************** -->



<!-- ************************************************************************************* -->






<!-- ********************************************************************************************** -->



<table class="ReportTable" ID="Table4">

	<tr>
      <td class="ReportTitle2" colspan="4"><font Face="Verdana,Arial,Helvetica" Size="2"><font color="#cc6600">Counties:</font>&nbsp;<b>Parker Tarrant </b></td>
    </tr>

	
    <tr>
      <td class="Reportdata2">Issued: </td>
      <td class="Reportdata2">
      Saturday 4/5/2003 6:53:00 PM&nbsp;

      </td>
     
      
      <td class="Reportdata2">Expires: </td>
      <td class="ReportData2">
      Saturday 4/5/2003 7:45:00 PM&nbsp;
       </td>
      

    </tr>
 </table>

<table class=ReportTable>
<tr>
<td bgcolor=#aaaaaa valign=center align=center >
<img border=0 src="<?php echo $imgurl; ?>">
<td bgcolor=#EEEECC valign=top align=center>



<table class=WarningTable ID="Table1">
<tr>
<td align="center" width=25% bgcolor="#EEccaa"><font Face="Verdana,Arial,Helvetica" Size="-2"><font color="#cc6600">Status</font></td>
<td nowrap Align="left" bgcolor="#dddddd"><font Face="trebuchet ms, arial, helvetica, sans-serif" Size="2">WARNING&nbsp;</td>
</tr>
<td align="center" bgcolor="#EEEECC"><font Face="Verdana,Arial,Helvetica" Size="-2"><font color="#cc6600">Event</font></td>

<td Align="left" bgcolor="eeeeee"><font Face="trebuchet ms, arial, helvetica, sans-serif" Size="2"><font color="ff0000">Warning</font></td>
</tr>



<tr>
<td align="center" bgcolor="#EEEECC"><font Face="Verdana,Arial,Helvetica" Size="-2"><font color="#cc6600">Area</font></td>
<td nowrap Align="left" bgcolor="#dddddd"><font Face="trebuchet ms, arial, helvetica, sans-serif" Size="2">657 Sq. Miles&nbsp;</td>
</tr>

<tr>
<td align="center" bgcolor="#EEEECC"><font Face="Verdana,Arial,Helvetica" Size="-2"><font color="#cc6600">Storm Motion</font></td>
<td Align="left"  bgcolor="eeeeee"><font Face="trebuchet ms, arial, helvetica, sans-serif" Size="2"><font color="0000ff"> East At 35 Mph.&nbsp;</font></td>

</tr>




</table>



<!-- ******************* Warning Table ************************************************* -->




<table class="WarningTable" >
<tr>
<td nowrap align="left" bgcolor="#EEccaa"><font Face="Verdana,Arial,Helvetica" Size="-2"><font color="#000000">Impacted Population:</font></td>

<td Align="right"  bgcolor="eeeeee"><font face="Arial" style="font-family: Arial,Helvetica; font-size: 9pt"><font color="000000">349,306&nbsp;</font></td>
</tr>
<tr>
<td align="left" bgcolor="#EEEECC"><font Face="Verdana,Arial,Helvetica" Size="-2"><font color="#000000">In Homes:</font></td>
<td Align="right"  bgcolor="eeeeee"><font face="Arial" style="font-family: Arial,Helvetica; font-size: 8pt"><font color="000000">84.04%&nbsp;</font></td>
</tr>
<tr>
<td align="left" bgcolor="#EEEECC"><font Face="Verdana,Arial,Helvetica" Size="-2"><font color="#000000">In Multi-Family Units:</font></td>
<td Align="right"  bgcolor="eeeeee"><font face="Arial" style="font-family: Arial,Helvetica; font-size: 8pt"><font color="000000">8.25%&nbsp;</font></td>
</tr>
<tr>
<td align="left" bgcolor="#EEEECC"><font Face="Verdana,Arial,Helvetica" Size="-2"><font color="#000000">In Mobile Homes:</font></td>

<td Align="right"  bgcolor="eeeeee"><font face="Arial" style="font-family: Arial,Helvetica; font-size: 8pt"><font color="000000">7.71%&nbsp;</font></td>
</tr>
<tr>
<td align="left" bgcolor="#EEccaa"><font Face="Verdana,Arial,Helvetica" Size="-2"><font color="#000000">English Spoken Well:</font></td>
<td Align="right"  bgcolor="eeeeee"><font face="Arial" style="font-family: Arial,Helvetica; font-size: 8pt"><font color="000000">96.27%&nbsp;</font></td>
</tr>
<tr>
<td align="left" bgcolor="#EEccaa"><font Face="Verdana,Arial,Helvetica" Size="-2"><font color="#000000">English Not Spoken:</font></td>
<td Align="right"  bgcolor="eeeeee"><font face="Arial" style="font-family: Arial,Helvetica; font-size: 8pt"><font color="000000">3.73%&nbsp;</font></td>
</tr>
<tr>
<td align="left" bgcolor="#EEEECC"><font Face="Verdana,Arial,Helvetica" Size="-2"><font color="#000000">Urban:</font></td>

<td Align="right"  bgcolor="eeeeee"><font face="Arial" style="font-family: Arial,Helvetica; font-size: 8pt"><font color="000000">87.39%&nbsp;</font></td>
</tr>
<tr>
<td align="left" bgcolor="#EEEECC"><font Face="Verdana,Arial,Helvetica" Size="-2"><font color="#000000">Rural:</font></td>
<td Align="right"  bgcolor="eeeeee"><font face="Arial" style="font-family: Arial,Helvetica; font-size: 8pt"><font color="000000">12.61%&nbsp;</font></td>
</tr>
<tr>
<td align="left" bgcolor="#EEEECC"><font Face="Verdana,Arial,Helvetica" Size="-2"><font color="#000000">Not Living in Texas in 1995:</font></td>
<td Align="right"  bgcolor="eeeeee"><font face="Arial" style="font-family: Arial,Helvetica; font-size: 9pt"><font color="000000">7.89%&nbsp;</font></td>
</tr>
<tr>
<td align="left" bgcolor="#EEEECC"><font Face="Verdana,Arial,Helvetica" Size="-2"><font color="#000000">Housing Units</font></td>

<td Align="right"  bgcolor="eeeeee"><font face="Arial" style="font-family: Arial,Helvetica; font-size: 9pt"><font color="000000">118,390&nbsp;</font></td>
</tr>
<tr>
<td colspan=2 align="center" bgcolor="#EEEECC"><font face="Arial" style="font-family: Arial,Helvetica; font-size: 9pt"><font color="#0000aa">Source: 2000 Census</font></td>
</tr>
</table>







</td></tr>
</table>

    






<!-- ********************************************************************************************** -->
    
    
    
    
<table class="ReportTable" ID="Table3">
	
	
<!-- ************************************************************************ -->
	
	
	<tr>
      <td class="ReportTitle" colspan="1"><b>DESCRIPTION</b></td>
    </tr>

    <tr>
      <td class="Reportdata2">

      <b>* TORNADO WARNING FOR...<br>&nbsp;&nbsp; EASTERN PARKER COUNTY IN NORTH CENTRAL TEXAS<br>&nbsp;&nbsp; TARRANT COUNTY IN NORTH CENTRAL TEXAS<br>&nbsp;&nbsp;</b><br>
      * At 649 PM CST... A Severe Thunderstorm With A History Of Producing Tornadoes Was 17 Miles West Of Springtown... Moving East At 35 Mph. The Storm Will Enter Western Sections Of Tarrant County After 715 PM CST.<br>
      &nbsp;<br></td>
    </tr>
 
 

 <!-- ************************************************************************ -->

    
    
    <tr>
      <td class="ReportTitle" colspan="1"><b>TIMING </b></td>
    </tr>	
    <tr>
      <td class="Reportdata2">
      * THE TORNADO IS EXPECTED TO BE NEAR... AZLE...PELICAN BAY AROUND 725 PM CST  EAGLE MOUNTAIN AROUND 735 PM CST  SAGINAW AROUND 740 PM CST  BLUE MOUND AROUND 745 PM CST 
      </td>
    </tr>
    
    
   
    
 </table>


<!-- ********************************************************************************************** -->

<!-- *************************** Population in Warning Area Section **************************** -->


&nbsp;<br>
<table class=reporttable ID="Table2">
<tr>
      <td class="ReportTitle" colspan="15"><b>POPULATION IN WARNING AREA (Up to 15 Top Populations Listed)</b></td>
    </tr>

<tr VALIGN="bottom">

    <td ALIGN="center" class=reportdata colspan=1><font face="Arial" style="font-family: Arial,Helvetica; font-size: 8pt"><b>City/Location</b></font></td>
    <td ALIGN="center" class=reportdata colspan=1><font face="Arial" style="font-family: Arial,Helvetica; font-size: 8pt"><b>County</b></font></td>
   
    <td ALIGN="center" class=reporthigh colspan=1 ><font face="Arial" style="font-family: Arial,Helvetica; font-size: 8pt"><b>Persons</b></font></td>
    <td ALIGN="center" class=reporthigh colspan=2 ><font face="Arial" style="font-family: Arial,Helvetica; font-size: 8pt"><b>Gender</b></font></td>
    <td ALIGN="center" class=reportunits colspan=1 ><font face="Arial" style="font-family: Arial,Helvetica; font-size: 8pt"><b>Housing</b></font></td>
    <td ALIGN="center" class=reportunits colspan=1 ><font face="Arial" style="font-family: Arial,Helvetica; font-size: 8pt"><b>Families</b></font></td>    

    <td ALIGN="center"  class=reportdata colspan=4 ><font face="Arial" style="font-family: Arial,Helvetica; font-size: 8pt"><b>Persons by Age (Years)</b></font></td>

 </tr>
 
  <tr VALIGN="bottom">
  
    <td ALIGN="center" VALIGN="bottom"><font face="Arial" style="font-family: Arial,Helvetica; font-size: 8pt"><b>&nbsp;</b></font></td>
    <td ALIGN="center" VALIGN="bottom"><font face="Arial" style="font-family: Arial,Helvetica; font-size: 8pt"><b>&nbsp;</b></font></td>
    <td ALIGN="center" VALIGN="bottom"><font face="Arial" style="font-family: Arial,Helvetica; font-size: 8pt"><b>&nbsp;</b></font></td>
 
    <td ALIGN="center" VALIGN="bottom"><font face="Arial" style="font-family: Arial,Helvetica; font-size: 8pt">Male</font></td>
   
    <td ALIGN="center" VALIGN="bottom"><font face="Arial" style="font-family: Arial,Helvetica; font-size: 8pt">Female</font></td>

    <td ALIGN="center" VALIGN="bottom"><font face="Arial" style="font-family: Arial,Helvetica; font-size: 8pt">Units&nbsp;</font></td>
    <td ALIGN="center" VALIGN="bottom"><font face="Arial" style="font-family: Arial,Helvetica; font-size: 8pt"><b>&nbsp;</b></font></td>
  
    <td ALIGN="center" VALIGN="bottom"><font face="Arial" style="font-family: Arial,Helvetica; font-size: 8pt"><10</font></td>
    
    
    <td ALIGN="center" VALIGN="bottom"><font face="Arial" style="font-family: Arial,Helvetica; font-size: 8pt">10-17</font></td>
   
  
    <td ALIGN="center" VALIGN="bottom"><font face="Arial" style="font-family: Arial,Helvetica; font-size: 8pt">18-65</font></td>
    
    
    <td ALIGN="center" VALIGN="bottom"><font face="Arial" style="font-family: Arial,Helvetica; font-size: 8pt">65+</font></td>

    
     
  </tr>
  
<?php
reset($cities);
while (list($key, $row) = each($cities))
{
  echo sprintf("<tr><td>%s %s</td><td>%s</td><td>%s</td><td>%s</td><td>%s</td><td>%s</td><td>%s</td><td>%s</td><td>%s</td><td>%s</td><td>%s</td></tr>", "#", $row["name"], "Cnty", intval($row["pop_1990"]), "M", "F", "h", "F", "10", "17", "18", "65");

}
?>
 
 

<!-- Outer Table -->
<tr valign=top>
<td colspan=20 bgcolor=#CC6600>&nbsp;
</td>
</tr>

<tr valign=top>
   
    <td ALIGN="left" class=reportdata ><font face="Arial" style="font-family: Arial,Helvetica; font-size: 8pt">Total of<br>30 Locations&nbsp;</font></td>
    <td ALIGN="left" class=reportdata ><font face="Arial" style="font-family: Arial,Helvetica; font-size: 8pt">&nbsp;</font></td>
  
    <td ALIGN="right" class=reporthigh valign="bottom" ><font face="Arial" style="font-family: Arial,Helvetica; font-size: 9pt"><b>349,306</b></font></td>
    <td ALIGN="left" class=reportdata ><font face="Arial" style="font-family: Arial,Helvetica; font-size: 8pt">&nbsp;</font></td>

    <td ALIGN="left" class=reportdata ><font face="Arial" style="font-family: Arial,Helvetica; font-size: 8pt">&nbsp;</font></td>
    <td ALIGN="right" class=reportunits valign="bottom" ><font face="Arial" style="font-family: Arial,Helvetica; font-size: 9pt"><b>118,390</b></font></td>
    <td ALIGN="right" class=reportunits valign="bottom" ><font face="Arial" style="font-family: Arial,Helvetica; font-size: 9pt"><b>90,356</b></font></td>
 
    <td ALIGN="right" colspan=10 class=reportdata valign="bottom" ><font face="Arial" style="font-family: Arial,Helvetica; font-size: 8pt">&nbsp;</font></td>
    
      </tr>

  
<tr valign=top>
   
    <td ALIGN="left" class=reportdata colspan=20 ><font face="Arial" color="0000ff" style="font-family: Arial,Helvetica; font-size: 8pt">Above Warning Information is presented through a cooperative project between the<br> <a href="http://www.nctcog.org">North Central Texas Council of Governments</a> and the <a href="http://www.srh.noaa.gov/fwd/">National Weather Service Fort Worth Office</a></font></td>

     
      </tr>

  
  

 
 
 
</table>
<!-- SQLPoly 35109.58 -->










<!-- ********************************************************************************************** -->

&nbsp;<br>
    
    
 <table class=reporttable ID="Table5">   
    <tr>
      <td class="ReportTitle" colspan="1"><b>WARNING TEXT</b></td>
    </tr>	
    <tr>
      <td class="Reportdata2">
      <pre class="Reportdata2">
<?php echo $report; ?>
</pre>
     </td>

    </tr>
 </table>
       

<table class=reporttable ID="Table7">   
    
    <tr>
      <td class="Reportdata">
      
      <a href="http://www.dfwinfo.com/weather/graphicalwarnings/nwspublic.asp">Back to Warning List</a>     
      
     </td>
    </tr>
 </table>

<?php include("/mesonet/php/include/footer.php"); ?>
