<?php
include("../../../../config/settings.inc.php");
include("$rootpath/include/database.inc.php");
include("$rootpath/include/vtec.php");
include("$rootpath/include/wfoLocs.php");
include('lib.php');

$postgis = iemdb("postgis");
pg_exec($postgis, "SET TIME ZONE 'GMT'");

/* Get variables */
$year = isset($_GET["year"]) ? intval($_GET["year"]) : 2006;
$significance = isset($_GET["significance"]) ? $_GET["significance"] : "W";
$wfo = isset($_GET["wfo"]) ? substr($_GET["wfo"],0,3) : "DMX";
$event_id = isset($_GET["event_id"]) ? intval($_GET["event_id"]) : 1;
$phenomena = isset($_GET["phenomena"]) ? substr($_GET["phenomena"],0,2) : "SV";


putenv("TZ=GMT");

function determine_time_base($t)
{
  $year = date("Y", $t);
  $month = date("m", $t);
  $day = date("d", $t);
  $hour = date("H", $t);
  $m = date("i", $t);

  if ($m >= 55) $ma = "55";
  else if ($m >= 50) $ma = "50";
  else if ($m >= 45) $ma = "45";
  else if ($m >= 40) $ma = "40";
  else if ($m >= 35) $ma = "35";
  else if ($m >= 30) $ma = "30";
  else if ($m >= 25) $ma = "25";
  else if ($m >= 20) $ma = "20";
  else if ($m >= 15) $ma = "15";
  else if ($m >= 10) $ma = "10";
  else if ($m >= 5) $ma = "05";
  else $ma = "00";

  return mktime($hour, $ma, 0, $month, $day, $year);
}



/* Fetch Event from the database */
$query = "SELECT *, astext(geom) as g, x(centroid(geom)) as lon0, y(centroid(geom)) as lat0 from warnings_$year WHERE wfo = '$wfo' and eventid = $event_id and phenomena = '$phenomena' and significance = '$significance'";
$result = pg_exec($postgis, $query);
$polygon = pg_fetch_array($result, 0);

$geom = $polygon["g"];

/* Draw Image! */
$issue = strtotime(substr($polygon["issue"],0,16)) + 240;
$ts = determine_time_base($issue);
$basets = $ts;
$isarchive = 1;
if (time() < ($ts + 450)) $isarchive = 0;
$imgi = 0;
$tzoff = 0;
$interval = 5;
$width = 400;
$height = 300;
$zoom = 100;
$lat0 = $polygon["lat0"];
$lon0 = $polygon["lon0"];
$layers = array("uscounties", "watches", "warnings", "nexrad");
$lsrwindow = 0;
$lsrlook = 0;
$maptitle = "IEM NEXRAD valid:";
dl($mapscript);
include("warnings_plot.php");


$query = "select sum(pop2004) as pop, sum(males) as males, sum(females) as females from blockgroup WHERE the_geom && 'SRID=4326;${geom}' and overlaps('SRID=4326;${geom}', the_geom)";
$blockgroup = pg_exec($postgis, $query);
$blocktotal = pg_fetch_array($blockgroup,0);

$query = "select * from placepoly WHERE the_geom && 'SRID=4326;${geom}' and contains('SRID=4326;${geom}', the_geom) ORDER by pop2000 DESC";
$placepoly = pg_exec($postgis, $query);

?>

<?php include("$rootpath/include/header.php"); ?>

<div style="border: 2px #000 dashed; background: #3e3; width: 800px;">
<div style="width: 100%; background: #ccc;">
<?php echo $vtec_phenomena[ $polygon["phenomena"] ] ."  ". $vtec_significance[ $polygon["significance"] ]; ?> 
</div>
<?php echo "<img src=\"$url\">"; ?>
<table>
 <tr><th>Population:</th><td><?php echo $blocktotal["pop"]; ?></td></tr>
 <tr><th>Males:</th><td><?php echo $blocktotal["males"]; ?></td></tr>
 <tr><th>Females:</th><td><?php echo $blocktotal["females"]; ?></td></tr>
</table>

</div>

<p>
<hr />
<?php
for ($i=0;$place = @pg_fetch_array($placepoly,$i);$i++)
{
  echo "<br />". $place["name"] . " --- ". $place["pop2000"] ;
}

?>
<hr />

<?php include("$rootpath/include/footer.php"); ?>

