<?php
include("../../../../config/settings.inc.php");
include("$rootpath/include/database.inc.php");
include("$rootpath/include/vtec.php");
include("$rootpath/include/wfoLocs.php");
include("$rootpath/include/forms.php");
include("$rootpath/include/lsrs.php");
include('lib.php');
putenv("TZ=GMT");

function determine_time_base($t)
{
  $year = date("Y", $t);
  $month = date("m", $t);
  $day = date("d", $t);
  $hour = date("H", $t);
  $m = date("i", $t);

  if ($m >= 55) $ma = "55";
  else if ($m >= 50) $ma = "50";
  else if ($m >= 45) $ma = "45";
  else if ($m >= 40) $ma = "40";
  else if ($m >= 35) $ma = "35";
  else if ($m >= 30) $ma = "30";
  else if ($m >= 25) $ma = "25";
  else if ($m >= 20) $ma = "20";
  else if ($m >= 15) $ma = "15";
  else if ($m >= 10) $ma = "10";
  else if ($m >= 5) $ma = "05";
  else $ma = "00";

  return mktime($hour, $ma, 0, $month, $day, $year);
}

$year = isset($_GET["year"]) ? intval($_GET["year"]) : 2006;

$wfo = isset($_GET["wfo"]) ? $_GET["wfo"] : "MPX";
$eventid = isset($_GET["eventid"]) ? intval($_GET["eventid"]) : 103;
$phenomena = isset($_GET["phenomena"]) ? $_GET["phenomena"] : "SV";
$significance = isset($_GET["significance"]) ? $_GET["significance"] : "W";

include("$rootpath/include/header.php");

$connect = iemdb("postgis");
pg_exec($connect, "SET TIME ZONE 'GMT'");

/* We need to fetch the extent */
$query1 = "SELECT xmax(extent(geom)) as x1, xmin(extent(geom)) as x0, ymin(extent(geom)) as y0, ymax(extent(geom)) as y1 from warnings_$year WHERE wfo = '$wfo' and phenomena = '$phenomena' and eventid = $eventid and significance = '$significance'";
$result = pg_exec($connect, $query1);
if (pg_num_rows($result) == 0) die("Could not find this product in the database!");
$row = pg_fetch_array($result, 0);
$lpad = 0.5;
$y1 = $row["y1"] +$lpad; $y0 = $row["y0"]-$lpad; 
$x1 = $row["x1"] +$lpad; $x0 = $row["x0"]-$lpad;


$query2 = "SELECT *, astext(geom) as t from warnings_$year WHERE wfo = '$wfo' and phenomena = '$phenomena' and eventid = $eventid and significance = '$significance'";
if ($significance == "W" && ($phenomena == "SV" or $phenomena == "TO"))
{
  $query2 .= " and gtype = 'P'";
}
$result = pg_exec($connect, $query2);
if (pg_num_rows($result) == 0) die("Could not find this product in the database!");
$row = pg_fetch_array($result, 0);

/* Determine time base, 4 minutes from product issuance */
$issue = strtotime(substr($row["issue"],0,16)) + 240;
$cow_issue = strtotime(substr($row["issue"],0,16)) - 21600;
$cow_expire = strtotime(substr($row["issue"],0,16)) + 21600;

$cow_url = sprintf("%s/cow/?syear=%s&smonth=%s&sday=%s&shour=%s&eyear=%s&emonth=%s&eday=%s&ehour=%s&wfo=%s&wtype[]=TO&wtype[]=SV&hail=0.75&ltype[]=TO&ltype[]=SV", $rooturl, date("Y", $cow_issue), date("m", $cow_issue),date("d", $cow_issue),date("H", $cow_issue), date("Y", $cow_expire), date("m", $cow_expire), date("d", $cow_expire), date("H", $cow_expire), $row["wfo"]);

$cow = "";
if ($row["significance"] == "W") $cow = "<li><a href=\"$cow_url\">Polygon Verification</a></li>";

$gis_url = sprintf("http://mesonet.agron.iastate.edu/cgi-bin/request/gis/watchwarn.py?year=%s&month1=%s&day1=%s&hour1=%s&minute1=0&month2=%s&day2=%s&hour2=%s&minute2=0",  date("Y", $cow_issue), date("m", $cow_issue),date("d", $cow_issue),date("H", $cow_issue), date("m", $cow_expire), date("d", $cow_expire), date("H", $cow_expire) );

$radar_url = sprintf("%s/GIS/apps/rview/warnings.phtml?archive=yes&tz=UTC&cu=0&year=%s&month=%s&day=%s&hour=%s&minute=%s&tzoff=0&sortdir=DESC&loop=0&sortcol=issue&c=yes&lon0=%s&lat0=%s", $rooturl, date("Y", $issue), date("m", $issue), date("d", $issue), date("H", $issue), date("i", $issue), ($x1+$x0)/2.0, ($y1 + $y0) / 2.0);

$next_eventid = $eventid + 1;
$last_eventid = $eventid - 1;
$next_link = sprintf("<a href=\"%s/GIS/apps/rview/warnings_cat.phtml?year=%s&wfo=%s&phenomena=%s&eventid=%s&significance=%s\">Next</a> ", $rooturl, $year, $row["wfo"], $phenomena, $next_eventid, $significance);

$last_link = "";
if ($last_eventid > 0)
  $last_link = sprintf(" <a href=\"%s/GIS/apps/rview/warnings_cat.phtml?year=%s&wfo=%s&phenomena=%s&eventid=%s&significance=%s\">Previous</a> ", $rooturl, $year, $row["wfo"], $phenomena, $last_eventid, $significance);


$ts = determine_time_base($issue);
$basets = $ts;
$isarchive = 1;
if (time() < ($ts + 450)) $isarchive = 0;
$imgi = 0;
$tzoff = 0;
$interval = 5;
$width = 400;
$height = 300;
/* $zoom = ($y1 - $y0) > ($x1 - $x0) ? ($y1 - $y0) * 140 : ($x1 - $x0) * 140; 
$lat0 = $y1 - $y0;
$lon0 = $x1 - $x0;
*/
$layers = array("uscounties", "warnings", "nexrad");
$lsrwindow = 0;
$lsrlook = 0;
$warngeo = "both";
$maptitle = "IEM NEXRAD valid:";
dl($mapscript);
include("warnings_plot.php");

echo "
<h3>Valid Time Extent Code (VTEC) Product Browser</h3>
<form method=\"GET\" name=\"changero\">
<table border=\"2\" cellpadding=\"5\" cellspacing=\"0\">
<tr><td valign=\"top\">
<b>Summary:</b>
<table>
<tr><td>NWS WFO:</td><td>"; ?>
<select name="wfo" style="width: 195px;">
<?php
while( list($key, $value) = each($wfos) ){
  echo "<option value=\"$key\" ";
  if ($wfo == $key) echo "SELECTED";
  echo ">[".$key."] ". $wfos[$key]["city"] ."</option>";
}
?>
</select>
<?php echo "</td></tr>
<tr><td>Year:</td><td>". yearSelect(2005,$year) ."</td></tr>
<tr><td>Event ID:</td><td>$last_link <input name=\"eventid\" type=\"text\" size=\"5\" value=\"". $row["eventid"] ."\"> $next_link</td></tr>
<tr><td>Phenomena:</td><td>";
?>
<select name="phenomena" style="width: 195px;">
<?php
while( list($key, $value) = each($vtec_phenomena) ){
  echo "<option value=\"$key\" ";
  if ($row["phenomena"] == $key) echo "SELECTED";
  echo ">[".$key."] ". $vtec_phenomena[$key] ."</option>";
}
?>
</select>
<?php echo "</td></tr>
<tr><td>Significance:</td><td>"; ?>
<select name="significance" style="width: 195px;">
<?php
while( list($key, $value) = each($vtec_significance) ){
  echo "<option value=\"$key\" ";
  if ($row["significance"] == $key) echo "SELECTED";
  echo ">[".$key."] ". $vtec_significance[$key] ."</option>";
}
?>
</select>
<?php echo "</td></tr>
<tr><td>Status:</td><td>". $vtec_status[ $row["status"] ] ."</td></tr>
<tr><td>Issued:</td><td>". substr($row["issue"],0,16) ." GMT</td></tr>
<tr><td>Expires:</td><td>". substr($row["expire"],0,16) ." GMT</td></tr>
</table>
<input type=\"submit\" value=\"Load Product\">
</form>
<h4>Links:</h4>
<ul>
 $cow
 <li><a href=\"$gis_url\">Download Shapefile of Warnings</a></li>
 <li><a href=\"$radar_url\">Interactive RADAR Display</a></li>
</ul>
</td><td><img src=\"$url\">";
if ($significance == "W" && ($phenomena == "SV" or $phenomena == "TO" or $phenomena == "MA"))
{
  /* Lets go dig for LSR reports */
  $sql = sprintf("SELECT distinct * from lsrs_%s WHERE
         geom && SetSrid(GeometryFromText('%s'),4326) and
         contains(SetSrid(GeometryFromText('%s'),4326), geom)
         and wfo = '%s' and
         valid >= '%s' and valid <= '%s' ORDER by valid ASC", $year,
          $row["t"], $row["t"], $wfo, $row["issue"], $row["expire"]);
  $result = pg_exec($connect, $sql);
  echo "<p><b>Storm Reports within this polygon valid during warning</b><br /><table border=\"1\" cellspacing=\"0\" cellpadding=\"2\"><tr><th>Time (GMT):</th><th>Type:</th><th>Magnitude:</th><th>City</th><th>County</th></tr>";
  if (pg_numrows($result) == 0) echo "<tr><th colspan=\"5\">No storm reports found</th></tr>\n";
  for( $i=0; $lsr = @pg_fetch_array($result,$i); $i++)
  { 
     echo sprintf("<tr><td>%s</td><td>%s</td><td>%s</td><td>%s</td><td>%s</td></tr><tr><td colspan=\"5\">%s</td></tr>", substr($lsr["valid"], 11,5), $lsr_types[$lsr["type"]]['name'], $lsr["magnitude"], $lsr["city"], $lsr["county"], $lsr["remark"]);
  }
  echo "</table>";
}


echo "</td></tr></table>";

/* Print out the raw report */
echo "<h4>Text Product:</h4><pre>". str_replace("\001", "", $row["report"]) ."</pre>";

if (strlen($row["svs"]) > 0 ) 
{
 $parts = explode('__', $row["svs"]);
 for ($i=1;$i<(sizeof($parts) - 1);$i++)
 {
   echo "<h4><a name=\"svs\">Updates</a>:</h4><pre>". str_replace("\001", "", $parts[$i]) ."</pre>\n";
 }
}

include("$rootpath/include/footer.php");
?>
