<?php
include("../../../../config/settings.inc.php");
include("$rootpath/include/database.inc.php");
include("$rootpath/include/vtec.php");
include("$rootpath/include/wfoLocs.php");
include("$rootpath/include/forms.php");
include("$rootpath/include/lsrs.php");
include('lib.php');
putenv("TZ=GMT");

function vtecPhenoSelect($selected)
{
 global $vtec_phenomena;
 $s = "<select name=\"phenomena\" style=\"width: 195px;\">\n";
 while( list($key, $value) = each($vtec_phenomena) ){
  $s .= "<option value=\"$key\" ";
  if ($selected == $key) $s .= "SELECTED";
  $s .= ">[".$key."] ". $vtec_phenomena[$key] ."</option>";
 }
 $s .= "</select>\n";
 return $s;
}

function vtecSigSelect($selected)
{
 global $vtec_significance;
 $s = "<select name=\"significance\" style=\"width: 195px;\">\n";
 while( list($key, $value) = each($vtec_significance) ){
  $s .= "<option value=\"$key\" ";
  if ($selected == $key) $s .= "SELECTED";
  $s .= ">[".$key."] ". $vtec_significance[$key] ."</option>";
 }
 $s .= "</select>\n";
 return $s;
}

function wfoSelect($selected)
{
 global $wfos;
 $s = "<select name=\"wfo\" style=\"width: 195px;\">\n";
 while( list($key, $value) = each($wfos) ){
   $s .= "<option value=\"$key\" ";
   if ($selected == $key) $s .= "SELECTED";
   $s .= ">[".$key."] ". $wfos[$key]["city"] ."</option>";
 }
 $s .= "</select>";
 return $s;
}

function determine_time_base($t)
{
  $year = date("Y", $t);
  $month = date("m", $t);
  $day = date("d", $t);
  $hour = date("H", $t);
  $m = date("i", $t);

  if ($m >= 55) $ma = "55";
  else if ($m >= 50) $ma = "50";
  else if ($m >= 45) $ma = "45";
  else if ($m >= 40) $ma = "40";
  else if ($m >= 35) $ma = "35";
  else if ($m >= 30) $ma = "30";
  else if ($m >= 25) $ma = "25";
  else if ($m >= 20) $ma = "20";
  else if ($m >= 15) $ma = "15";
  else if ($m >= 10) $ma = "10";
  else if ($m >= 5) $ma = "05";
  else $ma = "00";

  return mktime($hour, $ma, 0, $month, $day, $year);
}

$year = isset($_GET["year"]) ? intval($_GET["year"]) : 2006;
$wfo = isset($_GET["wfo"]) ? $_GET["wfo"] : "MPX";
$eventid = isset($_GET["eventid"]) ? intval($_GET["eventid"]) : 103;
$phenomena = isset($_GET["phenomena"]) ? $_GET["phenomena"] : "SV";
$significance = isset($_GET["significance"]) ? $_GET["significance"] : "W";
$warngeo = isset($_GET["warngeo"]) ? $_GET["warngeo"] : "both";
if ($phenomena != "SV" && $phenomena != "TO" && $phenomena != "MA") $warngeo = "county";
if (($phenomena == "SV" || $phenomena == "TO" || $phenomena == "MA") && !isset($_GET["warngeo"])) {
 $warngeo = "sbw";
}
if (($phenomena == "MA" || $significance != "W")) { $warngeo = "both"; }

$HEADEXTRA = "<script type=\"text/javascript\" src=\"${rooturl}/ext/adapter/ext/ext-base.js\"></script>
<script type=\"text/javascript\" src=\"${rooturl}/ext/ext-all.js\"></script>
<link rel=\"stylesheet\" type=\"text/css\" href=\"${rooturl}/ext/resources/css/ext-all.css\" />
";

include("$rootpath/include/header.php");
echo "<form method=\"GET\" name=\"changero\">";

$connect = iemdb("postgis");
pg_exec($connect, "SET TIME ZONE 'GMT'");

/* We need to fetch the extent */
$query1 = "SELECT xmax(extent(geom)) as x1, xmin(extent(geom)) as x0, ymin(extent(geom)) as y0, ymax(extent(geom)) as y1 from warnings_$year WHERE wfo = '$wfo' and phenomena = '$phenomena' and eventid = $eventid and significance = '$significance'";
$result = pg_exec($connect, $query1);
$row = pg_fetch_array($result, 0);
$lpad = 0.5;
$y1 = $row["y1"] +$lpad; $y0 = $row["y0"]-$lpad; 
$x1 = $row["x1"] +$lpad; $x0 = $row["x0"]-$lpad;


$query2 = "SELECT *, astext(geom) as t from warnings_$year WHERE wfo = '$wfo' and phenomena = '$phenomena' and eventid = $eventid and significance = '$significance'";
if ($significance == "W" && ($phenomena == "SV" or $phenomena == "TO" or $phenomena == "MA"))
{
  $query2 .= " and gtype = 'P'";
}
$result = pg_exec($connect, $query2);



/* Lets be nice and list out all warnings instead */
if (pg_num_rows($result) == 0) 
{
 $sql = "select sumtxt( n.name || ' ['||n.state||'], ') as s, eventid, min(issue) as i, 
         max(expire) as e from 
         (select distinct ugc, eventid, issue, expire from warnings_$year 
          WHERE wfo = '$wfo' and gtype = 'C' and 
          significance = '$significance' and phenomena = '$phenomena') as foo, 
         nws_ugc n WHERE n.ugc = foo.ugc GROUP by eventid ORDER by eventid ASC";
 $result = pg_exec($connect, $sql);

 echo "<h3>$year ". $vtec_phenomena[$phenomena]  ." ". $vtec_significance[$significance] ."(s) issued by ". $wfos[$wfo]["city"] ." Weather Office</h3>";

 echo "<table><tr><td>NWS WFO:</td><td>". wfoSelect($wfo) ."</td><td>Year:</td><td>". yearSelect(2005,$year) ."</td><td rowspan=\"2\"><input type=\"hidden\" value=\"0\" name=\"eventid\"><input type=\"submit\" value=\"View\"></td></tr><tr><td>Phenomena:</td><td>". vtecPhenoSelect($phenomena) ."</td><td>Significance:</td><td>". vtecSigSelect($significance) ."</td></tr></table>";

 echo "<br />Here is a listing of products archived by the IEM. Click on the
  event id to get more details";

 echo "<p><table class=\"ruler\" border=\"1\"><thead><tr><th>Event ID</th><th>Issued</th><th>Expired</th><th>Counties Effected:</th></tr></thead>\n";
 for ($i=0; $row = @pg_fetch_array($result,$i); $i++)
 {
   $url = sprintf("warnings_cat.phtml?wfo=%s&year=%s&eventid=%s&phenomena=%s&significance=%s", $wfo, $year, $row["eventid"], $phenomena, $significance);
   $iss = date("d M Y H:i", strtotime(substr($row["i"],0,16)));
   $exp = date("d M Y H:i", strtotime(substr($row["e"],0,16)));
   echo "<tr><th><a href=\"$url\">". $row["eventid"] ."</a></th><td>". $iss ." Z</td><td>". $exp ." Z</td><td>". substr($row["s"],0,-2)  ."</td></tr>\n";
 }
 if (pg_num_rows($result) == 0)
 {
  echo "<tr><td colspan=\"4\">No products found, sorry!</td></tr>";
 }
 echo "</table>\n";
 include("$rootpath/include/footer.php");
 die();
}




$row = pg_fetch_array($result, 0);

/* Determine time base, 4 minutes from product issuance */
$issue = strtotime(substr($row["issue"],0,16)) + 240;
$cow_issue = strtotime(substr($row["issue"],0,16)) - 21600;
$cow_expire = strtotime(substr($row["issue"],0,16)) + 21600;

$lsrwindow = 0;
if ($significance == "W" && ($phenomena == "SV" or $phenomena == "TO" or $phenomena == "MA")) 
{
  $hard_code_lsr_time = 1;
  $lsr_sts = strtotime(substr($row["issue"],0,16));
  $lsr_ets = strtotime(substr($row["expire"],0,16));
  $lsrwindow = 1;
}

$cow_url = sprintf("%s/cow/?syear=%s&smonth=%s&sday=%s&shour=%s&eyear=%s&emonth=%s&eday=%s&ehour=%s&wfo=%s&wtype[]=TO&wtype[]=SV&hail=0.75&ltype[]=TO&ltype[]=SV", $rooturl, date("Y", $cow_issue), date("m", $cow_issue),date("d", $cow_issue),date("H", $cow_issue), date("Y", $cow_expire), date("m", $cow_expire), date("d", $cow_expire), date("H", $cow_expire), $row["wfo"]);

$cow = "";
if ($row["significance"] == "W") $cow = "<li><a href=\"$cow_url\">Polygon Verification</a></li>";

$gis_url = sprintf("http://mesonet.agron.iastate.edu/cgi-bin/request/gis/watchwarn.py?year=%s&month1=%s&day1=%s&hour1=%s&minute1=0&month2=%s&day2=%s&hour2=%s&minute2=0",  date("Y", $cow_issue), date("m", $cow_issue),date("d", $cow_issue),date("H", $cow_issue), date("m", $cow_expire), date("d", $cow_expire), date("H", $cow_expire) );

$radar_url = sprintf("%s/GIS/apps/rview/warnings.phtml?archive=yes&tz=UTC&cu=0&year=%s&month=%s&day=%s&hour=%s&minute=%s&tzoff=0&sortdir=DESC&loop=0&sortcol=issue&c=yes&lon0=%s&lat0=%s", $rooturl, date("Y", $issue), date("m", $issue), date("d", $issue), date("H", $issue), date("i", $issue), ($x1+$x0)/2.0, ($y1 + $y0) / 2.0);

$next_eventid = $eventid + 1;
$last_eventid = $eventid - 1;
$next_link = sprintf("<a href=\"%s/GIS/apps/rview/warnings_cat.phtml?year=%s&wfo=%s&phenomena=%s&eventid=%s&significance=%s&warngeo=%s\">Next</a> ", $rooturl, $year, $row["wfo"], $phenomena, $next_eventid, $significance, $warngeo);

$last_link = "";
if ($last_eventid > 0)
  $last_link = sprintf(" <a href=\"%s/GIS/apps/rview/warnings_cat.phtml?year=%s&wfo=%s&phenomena=%s&eventid=%s&significance=%s&warngeo=%s\">Previous</a> ", $rooturl, $year, $row["wfo"], $phenomena, $last_eventid, $significance, $warngeo);
  

$all_link = sprintf(" <a href=\"%s/GIS/apps/rview/warnings_cat.phtml?year=%s&wfo=%s&phenomena=%s&eventid=0&significance=%s&warngeo=%s\">View all events of this type</a> ", $rooturl, $year, $row["wfo"], $phenomena, $significance, $warngeo);


$ts = determine_time_base($issue);
$basets = $ts;
$isarchive = 1;
if (time() < ($ts + 450)) $isarchive = 0;
$imgi = 0;
$tzoff = 0;
$interval = 5;
$width = 500;
$height = 400;
$lsrlook = 0;
$layers = array("uscounties_and_name", "warnings", "nexrad");
$maptitle = "IEM NEXRAD valid:";
$singleWarning = 1;
dl($mapscript);
include("warnings_plot.php");

echo "
<h3>Valid Time Extent Code (VTEC) Product Browser</h3>
<table border=\"2\" cellpadding=\"5\" cellspacing=\"0\">
<tr><td valign=\"top\">
<b>Summary:</b>
<table>
<tr><td>NWS WFO:</td><td>". wfoSelect($wfo) ."</td></tr>
<tr><td>Year:</td><td>". yearSelect(2005,$year) ."</td></tr>
<tr><td>Event ID:</td><td>$last_link <input name=\"eventid\" type=\"text\" size=\"5\" value=\"". $row["eventid"] ."\"> $next_link</td></tr>
<tr><td>Phenomena:</td><td>". vtecPhenoSelect($phenomena) ."</td></tr>
<tr><td>Significance:</td><td>". vtecSigSelect($significance) ."</td></tr>
<tr><td>Status:</td><td>". $vtec_status[ $row["status"] ] ."</td></tr>
<tr><td>Issued:</td><td>". substr($row["issue"],0,16) ." GMT</td></tr>
<tr><td>Expires:</td><td>". substr($row["expire"],0,16) ." GMT</td></tr>"; ?>

<tr><td>Warning<br />geography:</td>
<td><select name="warngeo">
 <option value="both" <?php if ($warngeo == "both") echo "SELECTED"; ?>>County + Polygon</option>
 <option value="county" <?php if ($warngeo == "county") echo "SELECTED"; ?>>County Only</option>
 <option value="sbw" <?php if ($warngeo == "sbw") echo "SELECTED"; ?>>Storm based warning</option>
</select></td></tr>

</table>
<input type="submit" value="Load Product">
</form>
<h4>Links:</h4>
<ul>
 <li><?php echo $all_link; ?></li>
 <?php echo $cow; ?>
 <li><a href="<?php echo $gis_url; ?>">Download Shapefile of Warnings</a></li>
 <li><a href="<?php echo $radar_url; ?>">Interactive RADAR Display</a></li>
</ul>
</td><td><img src="<?php echo $url; ?>">

<?php
if ($significance == "W" && ($phenomena == "SV" or $phenomena == "TO" or $phenomena == "MA"))
{
  /* Lets go dig for LSR reports */
  $sql = sprintf("SELECT distinct * from lsrs_%s WHERE
         geom && SetSrid(GeometryFromText('%s'),4326) and
         contains(SetSrid(GeometryFromText('%s'),4326), geom)
         and wfo = '%s' and
         valid >= '%s' and valid <= '%s' ORDER by valid ASC", $year,
          $row["t"], $row["t"], $wfo, $row["issue"], $row["expire"]);
  $result = pg_exec($connect, $sql);
  echo "<p><b>Storm Reports within this polygon valid during warning</b><br /><table border=\"1\" cellspacing=\"0\" cellpadding=\"2\"><tr><th>Time (GMT):</th><th>Type:</th><th>Magnitude:</th><th>City</th><th>County</th></tr>";
  if (pg_numrows($result) == 0) echo "<tr><th colspan=\"5\">No storm reports found</th></tr>\n";
  for( $i=0; $lsr = @pg_fetch_array($result,$i); $i++)
  { 
     echo sprintf("<tr><td>%s</td><td>%s</td><td>%s</td><td>%s</td><td>%s</td></tr><tr><td colspan=\"5\">%s</td></tr>", substr($lsr["valid"], 11,5), $lsr_types[$lsr["type"]]['name'], $lsr["magnitude"], $lsr["city"], $lsr["county"], $lsr["remark"]);
  }
  echo "</table>";
}


echo "</td></tr></table>";
?>
<style>
.list {list-style:square;width:700px;padding-left:16px;}
.list li{padding:2px;font-size:8pt;}

pre {
   font-size:11px; 
}

.x-tab-panel-body .x-panel-body {
    padding:10px;
}
</style>

<p>&nbsp;<br />
<?php


/* Generate text tabs :) */
$js = "Ext.onReady(function(){
    // basic tabs 1, built from existing content
    var tabs = new Ext.TabPanel({
        renderTo: 'tabs1',
        width:900,
        frame:true,
        plain:true,
        enableTabScroll:true,
        defaults:{autoHeight: true},
        items:[
            {contentEl:'svs0', title: 'Issuance'},
";


echo "<div id=\"tabs1\">
<div id=\"svs0\" class=\"x-hide-display\">
<p><pre>". str_replace("\001", "", $row["report"]) ."</pre></p>
</div>";

$lsvs = str_replace("\001", "", $row["report"]);
if (strlen($row["svs"]) > 0 ) 
{
  $parts = explode('__', $row["svs"]);
  $q = 1;
  for ($i=1;$i<(sizeof($parts) - 1);$i++)
  {
     $svs = str_replace("\001", "", $parts[$i]);
     if ($svs == $lsvs) continue;
     $lsvs = $svs;
     echo "<div id=\"svs${q}\" class=\"x-hide-display\"><p><pre>${svs}</pre></p></div>\n";
     $js .= "{contentEl:'svs${q}', title: 'Update ${q}'},\n";
     $q += 1;
  }
}
$v = $q - 1;
$js .= "        ],
        activeTab: ${v},
    });
});";
echo "<script> $js </script>";
echo "</div>";

include("$rootpath/include/footer.php");
?>
