<?php
include("../../../../config/settings.inc.php");
include("$rootpath/include/database.inc.php");
$baseuri = "warnings.phtml";
putenv("TZ=GMT");

if (isset($_GET["img_x"]) && isset($_GET["img_y"]) )
{
  $arExtents = explode(",", $_GET["extents"]);
  $ll_x = $arExtents[0];  
  $ll_y = $arExtents[1];
  $ur_x = $arExtents[2];
  $ur_y = $arExtents[3];

  $dy = ($ur_y - $ll_y) / floatval(480);
  $dx = ($ur_x - $ll_x) / floatval(640);

  $_GET["lon0"] = ($_GET["img_x"] * $dx) + $ll_x ;
  $_GET["lat0"] = $ur_y - ($_GET["img_y"] * $dy) ;
  /* $_GET["site"] = "user"; */
}

$layers = isset($_GET["layers"]) ? $_GET["layers"]: Array("cwas", "warnings", "uscounties", "nexrad");
$cu = isset($_GET["cu"]) ? $_GET["cu"]: 0;
$loop = isset($_GET["loop"]) ? $_GET["loop"] : 0;
$tz = isset($_GET["tz"]) ? $_GET["tz"] : "CST";
$tzdict = Array("UTC" => 0, "EDT" => 14400, "EST" => 18000, "CDT" => 18000, "CST" => 21600, "MDT" => 21600, "MST" => 25200, "PDT" => 25200, "PST" => 28800);

$tzoff = $tzdict[$tz];
$autopilot = isset($_GET["autopilot"]) ? $_GET["autopilot"] : 0;
$filter = isset($_GET["filter"]) ? $_GET["filter"]: 0;
$lsrwindow = isset($_GET["lsrwindow"]) ? $_GET["lsrwindow"] : "0";
$lsrlook = isset($_GET["lsrlook"]) ? $_GET["lsrlook"] : "+";
$site = isset($_GET["site"]) ? $_GET["site"]: "DMX";
$osite = isset($_GET["osite"]) ? $_GET["osite"]: "DMX";
$sortcol = isset($_GET["sortcol"]) ? $_GET["sortcol"]: "issued";
$sortdir = isset($_GET["sortdir"]) ? $_GET["sortdir"]: 0;
$lon0 = isset($_GET["lon0"]) ? $_GET["lon0"]: 0;
$lat0 = isset($_GET["lat0"]) ? $_GET["lat0"]: 0;
$zoom = isset($_GET["zoom"]) ? $_GET["zoom"]: 250;
$imgsize = isset($_GET["imgsize"]) ? $_GET["imgsize"] : "640x480";
$ar = explode("x", $imgsize);
$width = $ar[0];
$height = $ar[1];

$isarchive = (isset($_GET["archive"]) && $_GET["archive"] == "yes") ? 1 : 0;
$archive = isset($_GET["archive"]) ? $_GET["archive"] : "";
//if ($isarchive) { $loop = 0; }
$a = time();
if ($isarchive)
{
  $year = isset($_GET["year"]) ? intval($_GET["year"]) : date("Y", $a - $tzoff);
  $month = isset($_GET["month"]) ? intval($_GET["month"]) : date("m", $a - $tzoff);
  $day = isset($_GET["day"]) ? intval($_GET["day"]) : date("d", $a - $tzoff);
  $hour = isset($_GET["hour"]) ? intval($_GET["hour"]) : date("H", $a - $tzoff);
  $m = isset($_GET["minute"]) ? intval($_GET["minute"]) : date("i", $a - $tzoff);
} else {
  $year = date("Y", $a - $tzoff);
  $month = date("m", $a - $tzoff);
  $day = date("d", $a - $tzoff);
  $hour = date("H", $a - $tzoff);
  $m = date("i", $a - $tzoff);
}

if ($m >= 55) $ma = "55";
else if ($m >= 50) $ma = "50";
else if ($m >= 45) $ma = "45";
else if ($m >= 40) $ma = "40";
else if ($m >= 35) $ma = "35";
else if ($m >= 30) $ma = "30";
else if ($m >= 25) $ma = "25";
else if ($m >= 20) $ma = "20";
else if ($m >= 15) $ma = "15";
else if ($m >= 10) $ma = "10";
else if ($m >= 5) $ma = "05";
else $ma = "00";
//if (! $isarchive ) {$m = $ma;}
$m = $ma;
$basets = mktime($hour, $m, 0, $month, $day, $year);
$wfo_filter_ts = mktime(0,0,0,8,29,2004);
if ($isarchive && $basets < $wfo_filter_ts)
{
  $filter = 0;
}

include("$rootpath/include/wfoLocs.php");
include("$rootpath/include/forms.php");
include('lib.php');
$uri = "$baseuri?site=$site&cu=$cu&archive=$archive&year=$year&month=$month&day=$day&hour=$hour&minute=$m&loop=$loop&filter=$filter&sortdir=$sortdir&zoom=$zoom";
$uri_nowfo = "$baseuri?archive=$archive&cu=$cu&year=$year&month=$month&day=$day&hour=$hour&minute=$m&loop=$loop&filter=$filter&sortdir=$sortdir&zoom=$zoom";

/*
 Okay, complicated location stuff here...
  + case1: Default DMX (first page load)
  + case2: User clicks on map
  + case3: User selects different WFO  ($osite != $site)
  + case4: Nothing happens. lat0 lon0 are defined
*/

if (isset($_GET["lat0"]) && isset($_GET["lon0"]) && $osite == $site)
{
  $uri .= "&lat0=$lat0&lon0=$lon0";
}
else if (isset($_GET["site"]) || $lat0 == 0 || $lon0 == 0 || $osite != $site)
{
  $osite = $site;
  $lat0 = $wfos[$site]["lat"];
  $lon0 = $wfos[$site]["lon"];
  $uri .= "&lat0=$lat0&lon0=$lon0";
}

if (! $isarchive)
{
  // $REFRESH = "<meta http-equiv=\"refresh\" content=\"180; $uri\">";
}
$TITLE = "IEM | RADAR & NWS Warnings";
$HEADEXTRA = "<script language=\"JavaScript\">
function addTime() {
var d = new Date();
document.form.tzoff.value=(d.getTimezoneOffset()*60);
}

function reverseLayer(lyr) {
  if ( document.getElementById ) {
    var w = document.getElementById(lyr);
    if (w.style.display == \"none\") { w.style.display = \"block\"; }
    else { w.style.display = \"none\"; }
  }
}

function handsOff2( ) {
  reverseLayer(\"iem-header\");
  reverseLayer(\"form-control\");
  reverseLayer(\"iem-footer\");
}
function handsOff( ) {
  reverseLayer(\"iem-header\");
  reverseLayer(\"form-control\");
  reverseLayer(\"iem-footer\");
  if (document.myform.autopilot.value == 1){
    document.myform.autopilot.value = 0;
  } else {
    document.myform.autopilot.value = 1;
  }
}

setTimeout(\"document.myform.submit()\", 300000);
</script>";

if ($autopilot) $BODYEXTRA = "onLoad=\"handsOff2();\"";
?>

<?php include("$rootpath/include/header.php");?>

<form method="GET" name="myform" action="<?php echo $baseuri; ?>">
<input type="hidden" value="<?php echo $autopilot; ?>" name="autopilot">
<input type="hidden" value="<?php echo $site; ?>" name="osite">

<b>Nav:</b> <a href="<?php echo $rooturl; ?>/current/">Current Data</a> <b> > </b>
  <a href="<?php echo $rooturl; ?>/current/radar.phtml">Radar Products</a> <b> > </b>
  NEXRAD & Warnings <a href="<?php echo $baseuri; ?>">RESET APP!</a> &nbsp; 
 <input type="submit" onClick="javascript: handsOff(); return false;" value="Auto Pilot">
<br>

<?php

dl($mapscript);

?>

<table>
<tr><td>
<?php
if (intval($loop) ==  1){

  $urls = Array();

  for ($i=0;$i<9;$i++){
   $imgi = 8 - $i;
   include("warnings_plot.php");
   $urls[$i] = $url;
  }

  include ("loop.php");
  $radTimes = Array();
  printHTML($urls, $radTimes);
} else if (intval($loop) == 2){
  $urls = Array();
  $fts = time();
  $f = fopen("/var/www/htdocs/tmp/". $fts .".dat", 'w');

  for ($i=0;$i<9;$i++){
   $imgi = 8 - $i;
   include("warnings_plot.php");
   $urls[$i] = $url;
   fwrite($f, "$rooturl/$url\n");
  }
  fclose($f);
?>
  <applet codebase="<?php echo $rooturl; ?>/current/class/" code="AniS.class" width="<?php echo $width; ?>" height="<?php echo $height + 100; ?>" alt="You must enable Java in your browser to view the radar loop">
        <param name="controls" value="startstop, looprock, step, speed, toggle, zoom">
        <param name="rate" value="80">
	<PARAM name="no_enh" value="true">
        <param name="pause_percent" value="800">
        <param name="file_of_filenames" value="/tmp/<?php echo $fts; ?>.dat">
</applet>

<?php
} else {
  $imgi = 0;
  include("warnings_plot.php");

  echo "<input type=\"image\" name=\"img\" src=\"". $url ."\" border=\"1\">\n";

}

?>
</td><td valign="top">
<b>Warnings Legend:</b>
<br />
<!-- <img src="<?php // echo $legendsrc; ?>"> -->
<img src="static/warnings_legend.png">
<br /><b>Layers:</b>
<input type="hidden" name="layers[]" value="blank">
<br /><input name="layers[]" type="checkbox" value="cwas" <?php if (in_array("cwas", $layers)) echo "checked='CHECKED'"; ?>>WFO Boundaries
<br /><input name="layers[]" type="checkbox" value="warnings" <?php if (in_array("warnings", $layers)) echo "checked='CHECKED'"; ?>>Warnings
<!-- <br /><input name="layers[]" type="checkbox" value="warnings_summary" <?php if (in_array("warnings_summary", $layers)) echo "checked='CHECKED'"; ?>>Warning Summary -->
<br /><input name="layers[]" type="checkbox" value="uscounties" <?php if (in_array("uscounties", $layers)) echo "checked='CHECKED'"; ?>>US Counties
<br /><input name="layers[]" type="checkbox" value="usdm" <?php if (in_array("usdm", $layers)) echo "checked='CHECKED'"; ?>>US Drought Monitor
<br /><input name="layers[]" type="checkbox" value="nexrad" <?php if (in_array("nexrad", $layers)) echo "checked='CHECKED'"; ?>>US NEXRAD
<br /><input name="layers[]" type="checkbox" value="goes_east1V" <?php if (in_array("goes_east1V", $layers)) echo "checked='CHECKED'"; ?>>GOES East Visible
<br /><input name="layers[]" type="checkbox" value="goes_west1V" <?php if (in_array("goes_west1V", $layers)) echo "checked='CHECKED'"; ?>>GOES West Visible
<br /><input name="layers[]" type="checkbox" value="goes_east04I4" <?php if (in_array("goes_east04I4", $layers)) echo "checked='CHECKED'"; ?>>GOES East IR
<br /><input name="layers[]" type="checkbox" value="goes_west04I4" <?php if (in_array("goes_west04I4", $layers)) echo "checked='CHECKED'"; ?>>GOES West IR

<p><input type="submit" value="Show Map">
</td></tr></table>

<table bgcolor="black" width="100%" cellpadding=2 border=0 cellspacing=0>
  <tr><td>
<table width="100%" bgcolor="white" cellpadding=2 border=0 cellspacing=0>
  <tr><td valign="TOP" bgcolor="#dddddd">
<div id="form-control">
<input type="hidden" name="tzoff" value="0">
<?php if (isset($_GET["lat0"])) { ?>
<input type="hidden" value="<?php echo $lat0; ?>" name="lat0">
<input type="hidden" value="<?php echo $lon0; ?>" name="lon0">
<?php } ?>

<table style="padding: 2px;" border="1">
<tr>
<th>Select WFO</th>
<td><select name="site">
<?php
while( list($key, $value) = each($wfos) ){
  echo "<option value=\"$key\" ";
  if ($site == $key) echo "SELECTED";
  echo ">[".$key."] ". $wfos[$key]["city"] ."\n";
}
/*
if ( isset($_GET["site"]) && $_GET["site"] == "user" ) { 
echo "<option value=\"user\" SELECTED>User Selected\n";
}
*/
?>
</select></td>

<th>Timezone:</th>
<td><select name="tz">
  <option value="UTC" <?php if ($tz == "UTC") echo "SELECTED"; ?>>UTC
  <option value="EDT" <?php if ($tz == "EDT") echo "SELECTED"; ?>>EDT
  <option value="EST" <?php if ($tz == "EST") echo "SELECTED"; ?>>EST
  <option value="CDT" <?php if ($tz == "CDT") echo "SELECTED"; ?>>CDT
  <option value="CST" <?php if ($tz == "CST") echo "SELECTED"; ?>>CST
  <option value="MDT" <?php if ($tz == "MDT") echo "SELECTED"; ?>>MDT
  <option value="MST" <?php if ($tz == "MST") echo "SELECTED"; ?>>MST
  <option value="PDT" <?php if ($tz == "PDT") echo "SELECTED"; ?>>PDT
  <option value="PST" <?php if ($tz == "PST") echo "SELECTED"; ?>>PST
</select></td>

<th>Zoom</th>
<td><select name="zoom">
 <option value="25" <?php if ($zoom == 25) echo "SELECTED"; ?>>25km
 <option value="50" <?php if ($zoom == 50) echo "SELECTED"; ?>>50km
 <option value="100" <?php if ($zoom == 100) echo "SELECTED"; ?>>100km
 <option value="250" <?php if ($zoom == 250) echo "SELECTED"; ?>>250km
 <option value="500" <?php if ($zoom == 500) echo "SELECTED"; ?>>500km
 <option value="1000" <?php if ($zoom == 1000) echo "SELECTED"; ?>>1000km
 <option value="3000" <?php if ($zoom == 3000) echo "SELECTED"; ?>>3000km
</select></td>

<th>Loop?</th>
<td><select name="loop">
  <option value="0" <?php if ($loop == 0) echo "SELECTED"; ?>>No
  <option value="1" <?php if ($loop == 1) echo "SELECTED"; ?>>Java Script
  <option value="2" <?php if ($loop == 2) echo "SELECTED"; ?>>Applet
</select></td>


</tr>
</table>


<table style="padding: 2px;" border="1">
<tr>
<th>WFO Filter:</th>
<td><select name="filter">
  <option value="0" <?php if ($filter == 0) echo "SELECTED"; ?>>No
  <option value="1" <?php if ($filter == 1) echo "SELECTED"; ?>>Yes
</select></td>

<th>Sort</th>
<td><select name="sortdir">
  <option value="0" <?php if ($sortdir == 0) echo "SELECTED"; ?>>DESC
  <option value="1" <?php if ($sortdir == 1) echo "SELECTED"; ?>>ASC
</select></td>


<th>LSR Window</th>
<td>
<select name="lsrlook">
 <option value="+" <?php if ($lsrlook == "+") echo "SELECTED" ?>>+
 <option value="-" <?php if ($lsrlook == "-") echo "SELECTED" ?>>-
 <option value="+/-" <?php if ($lsrlook == "+/-") echo "SELECTED" ?>>+/-
</select>
<select name="lsrwindow">
 <option value="0" <?php if ($lsrwindow == 0) echo "SELECTED"; ?>>Hide
 <option value="5" <?php if ($lsrwindow == 5) echo "SELECTED"; ?>>5 minutes
 <option value="10" <?php if ($lsrwindow == 10) echo "SELECTED"; ?>>10 minutes
 <option value="15" <?php if ($lsrwindow == 15) echo "SELECTED"; ?>>15 minutes
 <option value="30" <?php if ($lsrwindow == 30) echo "SELECTED"; ?>>30 minutes
 <option value="60" <?php if ($lsrwindow == 60) echo "SELECTED"; ?>>60 minutes
</select></td>

<th>Size</th>
<td><select name="imgsize">
 <option value="640x480" <?php if ($imgsize == "640x480") echo "SELECTED"; ?>>640x480
 <option value="800x600" <?php if ($imgsize == "800x600") echo "SELECTED"; ?>>800x600
 <option value="1024x768" <?php if ($imgsize == "1024x768") echo "SELECTED"; ?>>1024x768
 <option value="1280x1024" <?php if ($imgsize == "1280x1024") echo "SELECTED"; ?>>1280x1024
</select></td>

</tr></table>

<table style="padding: 3px;" border="1">
<thead><tr><th>&nbsp;</th><th>Year:</th><th>Month:</th><th>Day:</th><th>Hour:</th><th>Minute</th><td></td></tr></thead>
<tbody>
<tr>
<td><input type="checkbox" value="yes" name="archive" <?php if($isarchive) echo
"CHECKED=CHECKED"; ?>>Archived Mode?</td>
<td><?php echo yearSelect(2003, $year, "year"); ?></td>
<td><?php echo monthSelect($month, "month"); ?></td>
<td><?php echo daySelect($day, "day"); ?></td>
<td><?php echo hourSelect($hour, "hour"); ?></td>
<td><?php echo local5MinuteSelect($m, "minute"); ?></td>
<td><input type="submit" value="Show Map"></td>
</tr>
</tbody></table>
</div>


</td></tr>

<tr><td>

<?php

/* if ($site == "user") 
{
  echo sprintf("User selected Latitude: %.3f Longitude: %.3f", $lat0, $lon0);
} else {
  echo "Selected WFO:</b> ". $wfos[$site]["city"] ." (".$site.")\n";
} */
  echo "Selected WFO:</b> ". $wfos[$site]["city"] ." (".$site.")\n";



echo "
  </td></tr>\n</table>
</td></tr>\n</table>\n";

echo "<input type=\"hidden\" name=\"extents\" value=\"". $map->extent->minx .",". $map->extent->miny .",". $map->extent->maxx .",". $map->extent->maxy ."\">\n";

$connection = iemdb("postgis");

$scols = Array("wfo", "phenomena", "cname", "expire", "sname", "issue", "updated", "status", "fcster", "eventid");
if (! in_array($sortcol, $scols) ){
 $sortcol = "issue";
}
if ($sortdir == 1) $sortdir = "ASC";
else $sortdir = "DESC";

$wtable = "warnings";
$tsextra = "CURRENT_TIMESTAMP and issue < CURRENT_TIMESTAMP ";
if ($isarchive)
{
  $wtable = "warnings_$year";
  $tsextra = "'". strftime("%Y-%m-%d %H:%M:00+00", $basets + $tzoff ) ."' and w.issue < '". strftime("%Y-%m-%d %H:%M:00+00", $basets + $tzoff ) ."'";
}
$cuextra = "";
if ($cu == 1) $cuextra = " and w.phenomena IN ('SV','TO') ";
$query = "SELECT w.phenomena, w.oid, u.name as cname, w.expire as expire, 
  w.updated as updated, w.status as status, w.fcster as fcster, 
  w.eventid as eventid, w.significance as significance, 
  w.issue as issue, u.state as sname, xmax(w.geom) as lon0, 
  ymax(w.geom) as lat0, w.wfo as wfo
  from $wtable w, nws_ugc u
  WHERE w.expire > $tsextra and w.significance != 'A'
   and w.gtype = 'C' and w.ugc = u.ugc $cuextra ORDER by $sortcol $sortdir";

pg_exec($connection, "set time zone 'GMT'");
$result = pg_exec($connection, $query);

pg_close($connection);

$afos = Array("SV" => "Svr Tstorm",
  "TO" => "Tornado",
  "FF" => "Flash Flood");
?>
Warnings Valid at: <b><?php 
if ($tzoff == 0)
{
  if ($isarchive)
  echo strftime("%d %b %Y %H:%M %Z", $basets); 
  else
  echo strftime("%d %b %Y %H:%M %Z"); 
}
else 
{
  if ($isarchive)
  echo strftime("%d %b %Y %I:%M %p ", $basets) . $tz; 
  else
  echo strftime("%d %b %Y %I:%M %p ", time() - $tzoff) . $tz; 
}
?></b>
 &nbsp; Warnings Filter: <input type="radio" value="0" name="cu" <?php if ($cu == 0) { echo "checked"; } ?>>Show All
<input type="radio" value="1" name="cu" <?php if ($cu == 1) { echo "checked"; } ?>>Convective Only
<table width="100%" style="padding: 3px;" border="1">
<thead>
<tr>
 <th <?php if ($sortcol == "wfo") echo "style='background: #f00;'"; ?>><a href="<?php echo "$uri&sortcol=wfo";?>">WFO</a></th>

 <th <?php if ($sortcol == "phenomena") echo "style='background: #f00;'"; ?> ><a href="<?php echo "$uri&sortcol=phenomena";?>">Warn</a></th>

 <th <?php if ($sortcol == "eventid") echo "style='background: #f00;'"; ?>><a href="<?php echo "$uri&sortcol=eventid";?>">VTEC#</a></th>

 <th <?php if ($sortcol == "cname") echo "style='background: #f00;'"; ?>><a href="<?php echo "$uri&sortcol=cname";?>">County</a></th>

 <th <?php if ($sortcol == "expire") echo "style='background: #f00;'"; ?>><a href="<?php echo "$uri&sortcol=expire";?>">Expires</a></th>

 <th <?php if ($sortcol == "sname") echo "style='background: #f00;'"; ?>><a href="<?php echo "$uri&sortcol=sname";?>">State</a></th>

 <th <?php if ($sortcol == "issue") echo "style='background: #f00;'"; ?>><a href="<?php echo "$uri&sortcol=issue";?>">Issued</a></th>

 <th <?php if ($sortcol == "updated") echo "style='background: #f00;'"; ?>><a href="<?php echo "$uri&sortcol=updated";?>">Updated</a></th>

 <th <?php if ($sortcol == "status") echo "style='background: #f00;'"; ?>><a href="<?php echo "$uri&sortcol=status";?>">Status</a></th>

 <th <?php if ($sortcol == "fcster") echo "style='background: #f00;'"; ?>><a href="<?php echo "$uri&sortcol=fcster";?>">Forecaster</a></th>
</tr>
</thead>
<tbody>
<?php
$k = 0;
if ($tzoff == 0)
{
  $dformat = "%H:%M GMT";
}
else
{
  $dformat = "%I:%M %p";
}

/* Loop thru results from database! */
$wA = Array();
$oA = Array();
$iA = Array();
$uA = Array();
$fA = Array();
for( $i=0; $row = @pg_fetch_array($result,$i); $i++) 
{
  /* Save the drama! */
  if ($filter && $row["wfo"] != $site) continue; 

  /* key is wfo_state_vtecP_vtecE_vtecSig_expire_status */
  $key = sprintf("%s|%s|%s|%s|%s|%s|%s", $row["wfo"], $row["sname"], 
     $row["phenomena"], $row["eventid"], $row["significance"], $row["expire"],
     $row["status"]);

  $oA[$key] = $row["oid"];
  $iA[$key] = $row["issue"];
  $uA[$key] = $row["updated"];
  $fA[$key] = $row["fcster"];
  @$wA[$key] .= "<a href=\"$baseuri?tz=$tz&cu=$cu&year=$year&month=$month&day=$day&hour=$hour&minute=$m&archive=$archive&tzoff=$tzoff&sortdir=$sortdir&loop=$loop&sortcol=$sortcol&c=yes&lon0=". $row["lon0"] ."&lat0=". $row["lat0"] ."\">". $row["cname"] ."</a>, ";
}

/* Now we loop thru aggregated warnings */
while ( list($key, $val) = each($wA) )
{
  $tokens = explode("|", $key);
  $wfo = $tokens[0];
  $sname = $tokens[1];
  $phenomena = $tokens[2];
  $eventid = $tokens[3];
  $significance = $tokens[4];
  $expire = $tokens[5];
  $status = $tokens[6];
  $oid = $oA[$key];

  if ($eventid > 0) {
    $warningscat = "warnings_cat.phtml?year=$year&wfo=$wfo&phenomena=$phenomena&eventid=$eventid";
  } else { /* Old warnings have no VTEC! */
    $warningscat = "warnings_cat.phtml?year=$year&oid=$oid";
  }

  $k += 1;
  $issue = strtotime($iA[$key]) - $tzoff;
  $expire = strtotime($expire) - $tzoff;
  $updated = strtotime($uA[$key]) - $tzoff;

 echo "<tr ";
 if ($k % 2 == 0) echo "bgcolor=\"#EEEEEE\"";
 echo "><td><a href=\"$uri_nowfo&tz=$tz&cu=$cu&year=$year&month=$month&day=$day&hour=$hour&minute=$m&archive=$archive&tzoff=$tzoff&site=$wfo\">$wfo</a></td><td><a href=\"$warningscat\">$phenomena</a></td><td>$eventid</td>";

 echo "<td>". $wA[$key] ."</td>";

 echo "<td>". strftime($dformat, $expire) ."</td>
    <td>". $sname ."</td>
    <td>". strftime($dformat, $issue) ."</td>
    <td>". strftime($dformat, $updated) ."</td>
    <td><a href=\"". $warningscat ."#svs\">$status</a></td>
    <td>". $fA[$key] ."</td>
    </tr>\n";

}
if ($k == 0 && $filter){
 $msg = "No warnings currently valid for ". $wfos[$site]["city"] ;
} else if ($k == 0) {
 $msg = "No warnings valid in the United States";
}
if ($k == 0){
  echo "<tr><td colspan=\"10\">$msg</td></tr>";
}
?>
</tbody>
</table>

</form>
<?php if (! $isarchive) { ?>
<img src="<?php echo $rooturl; ?>/images/gisready.png">Download <a href="<?php echo $rooturl; ?>/data/gis/shape/unproj/us/current_ww.zip">GIS shapefile of current warnings</a> and/or <a href="<?php echo $rooturl; ?>/GIS/data/gis/images/unproj/USCOMP/n0r_0.gtif.Z">GeoTiff of NEXRAD base reflectivity</a>.
<?php } ?>

<font size="-1">
<p><b>Notes:</b>
<ul>
 <li>This application is research grade and should not be used operationally.</li>
 <li>Flash Flood Warnings (FFW) do not have VTEC IDs, so those columns are blank for FFWs.</li>
 <li>The status column is simply the status of the warning.  The warning is in 'NEW' state until a SVS is issued, then it goes to 'CON' for continued.</li>
 <li>Warnings identified by WFO are available after 29 Aug 2004.</li>
 <li>NEXRAD composite is available since 1 Aug 2003.</li>
 <li>Prior to the NWS adoption of VTEC, warnings were not expired nor canceled.</li>
 <li>SVS updates were added in 2005.</li>
 <li>LSR archive begins 8 June 2005.</li>
 <li>Archive of watches begins 13 August 2004.</li>
</ul>
</font>

<?php  include ("$rootpath/include/footer.php");?>
