<?php
if (substr($_SERVER["REMOTE_ADDR"], 0, 5) == "65.55"){ die("Go Away"); }

include("../../../../config/settings.inc.php");
include("$rootpath/include/database.inc.php");
include("$rootpath/include/vtec.php");
include("lib.inc");
$baseuri = "warnings.phtml";
putenv("TZ=GMT");

if (isset($_GET["img_x"]) && isset($_GET["img_y"]) )
{
  $arExtents = explode(",", $_GET["extents"]);
  $ll_x = $arExtents[0];  
  $ll_y = $arExtents[1];
  $ur_x = $arExtents[2];
  $ur_y = $arExtents[3];

  $dy = ($ur_y - $ll_y) / floatval(480);
  $dx = ($ur_x - $ll_x) / floatval(640);

  $_GET["lon0"] = ($_GET["img_x"] * $dx) + $ll_x ;
  $_GET["lat0"] = $ur_y - ($_GET["img_y"] * $dy) ;
  /* $_GET["site"] = "user"; */
}

$layers = isset($_GET["layers"]) ? $_GET["layers"]: Array("cwas", "warnings", "uscounties", "nexrad", "watches");
$cu = isset($_GET["cu"]) ? $_GET["cu"]: 0;
$loop = isset($_GET["loop"]) ? $_GET["loop"] : 0;
$tz = isset($_GET["tz"]) ? $_GET["tz"] : "CDT";
$tzdict = Array("UTC" => 0, "EDT" => 14400, "EST" => 18000, "CDT" => 18000, "CST" => 21600, "MDT" => 21600, "MST" => 25200, "PDT" => 25200, "PST" => 28800);

$tzoff = $tzdict[$tz];
$autopilot = isset($_GET["autopilot"]) ? $_GET["autopilot"] : 0;
$filter = isset($_GET["filter"]) ? $_GET["filter"]: 0;
$lsrwindow = isset($_GET["lsrwindow"]) ? $_GET["lsrwindow"] : "0";
$lsrlook = isset($_GET["lsrlook"]) ? $_GET["lsrlook"] : "+";
$site = isset($_GET["site"]) ? substr($_GET["site"],0,3): "DMX";
$osite = isset($_GET["osite"]) ? substr($_GET["osite"],0,3): "DMX";
$sortcol = isset($_GET["sortcol"]) ? $_GET["sortcol"]: "issued";
$sortdir = isset($_GET["sortdir"]) ? $_GET["sortdir"]: 0;
$lon0 = isset($_GET["lon0"]) ? $_GET["lon0"]: 0;
$lat0 = isset($_GET["lat0"]) ? $_GET["lat0"]: 0;
$zoom = isset($_GET["zoom"]) ? $_GET["zoom"]: 250;
$imgsize = isset($_GET["imgsize"]) ? $_GET["imgsize"] : "640x480";
$interval = isset($_GET["interval"]) ? $_GET["interval"] : 5;
$frames = isset($_GET["frames"]) ? $_GET["frames"] : 10;
$warngeo = isset($_GET["warngeo"]) ? $_GET["warngeo"] : "both";
$ar = explode("x", $imgsize);
$width = $ar[0];
$height = $ar[1];

$isarchive = (isset($_GET["archive"]) && $_GET["archive"] == "yes") ? 1 : 0;
$archive = isset($_GET["archive"]) ? $_GET["archive"] : "";
//if ($isarchive) { $loop = 0; }
$a = time();
if ($isarchive)
{
  $year = isset($_GET["year"]) ? intval($_GET["year"]) : date("Y", $a - $tzoff);
  $month = isset($_GET["month"]) ? intval($_GET["month"]) : date("m", $a - $tzoff);
  $day = isset($_GET["day"]) ? intval($_GET["day"]) : date("d", $a - $tzoff);
  $hour = isset($_GET["hour"]) ? intval($_GET["hour"]) : date("H", $a - $tzoff);
  $m = isset($_GET["minute"]) ? intval($_GET["minute"]) : date("i", $a - $tzoff);
} else {
  $year = date("Y", $a - $tzoff);
  $month = date("m", $a - $tzoff);
  $day = date("d", $a - $tzoff);
  $hour = date("H", $a - $tzoff);
  $m = date("i", $a - $tzoff);
}

if ($m >= 55) $ma = "55";
else if ($m >= 50) $ma = "50";
else if ($m >= 45) $ma = "45";
else if ($m >= 40) $ma = "40";
else if ($m >= 35) $ma = "35";
else if ($m >= 30) $ma = "30";
else if ($m >= 25) $ma = "25";
else if ($m >= 20) $ma = "20";
else if ($m >= 15) $ma = "15";
else if ($m >= 10) $ma = "10";
else if ($m >= 5) $ma = "05";
else $ma = "00";
//if (! $isarchive ) {$m = $ma;}
$m = $ma;
$basets = mktime($hour, $m, 0, $month, $day, $year);
$wfo_filter_ts = mktime(0,0,0,8,29,2004);
if ($isarchive && $basets < $wfo_filter_ts)
{
  $filter = 0;
}

include("$rootpath/include/wfoLocs.php");
$wfos["NHC"] = Array("lat" => 25.75 , "lon" => -80.38 , "city" => "National Hurricane Center");
include("$rootpath/include/forms.php");
include('lib.php');
$uri = "$baseuri?frames=$frames&interval=$interval&site=$site&cu=$cu&archive=$archive&year=$year&month=$month&day=$day&hour=$hour&minute=$m&loop=$loop&filter=$filter&sortdir=$sortdir&zoom=$zoom&warngeo=$warngeo";
$uri_nowfo = "$baseuri?frames=$frames&interval=$interval&archive=$archive&cu=$cu&year=$year&month=$month&day=$day&hour=$hour&minute=$m&loop=$loop&filter=$filter&sortdir=$sortdir&zoom=$zoom&warngeo=$warngeo";

/*
 Okay, complicated location stuff here...
  + case1: Default DMX (first page load)
  + case2: User clicks on map
  + case3: User selects different WFO  ($osite != $site)
  + case4: Nothing happens. lat0 lon0 are defined
*/

if (isset($_GET["lat0"]) && isset($_GET["lon0"]) && $osite == $site)
{
  $uri .= "&lat0=$lat0&lon0=$lon0";
}
else if (isset($_GET["site"]) || $lat0 == 0 || $lon0 == 0 || $osite != $site)
{
  $osite = $site;
  $lat0 = $wfos[$site]["lat"];
  $lon0 = $wfos[$site]["lon"];
  $uri .= "&lat0=$lat0&lon0=$lon0";
}

$TITLE = "IEM | RADAR & NWS Warnings";
$HEADEXTRA = "<script type=\"text/javascript\" src=\"warnings.js\"></script>
<link rel=\"stylesheet\" type=\"text/css\" href=\"warnings.css\" />
<script language=\"JavaScript1.2\" type=\"text/javascript\">
";
if (! $isarchive)
  $HEADEXTRA .= "setTimeout(\"document.myform.submit()\", 300000);\n";
$HEADEXTRA .= "</script>";

if ($autopilot) $BODYEXTRA = "onLoad=\"handsOff2();\"";
?>
<?php $THISPAGE = "severe-interact"; include("$rootpath/include/header.php");?>
<form style="display: inline;" method="GET" name="myform" action="<?php echo $baseuri; ?>">
<input type="hidden" value="<?php echo $autopilot; ?>" name="autopilot">
<input type="hidden" value="<?php echo $site; ?>" name="osite">
<input type="hidden" name="tzoff" value="0">
<?php if (isset($_GET["lat0"])) { ?>
<input type="hidden" value="<?php echo $lat0; ?>" name="lat0">
<input type="hidden" value="<?php echo $lon0; ?>" name="lon0">
<?php } ?>


<div id="blankspace" style="width: 640px; height: 480px; position: absolute; z-index: 1;">&nbsp;</div>
<div id="datawindow" style="background: #eee; position: absolute; left: 5px; top: 130px; width: <?php echo ($width + 250); ?>px; z-index: 2;">
<input type="submit" value="Layers" style="background: #73FA4D;" onClick="javascript: showControl('layers-control'); return false;">
<input type="submit" value="Locations" style="background: #F2FE5A;" onClick="javascript: showControl('locations-control'); return false;">
<input type="submit" value="Time" style="background: #FF5EC4;" onClick="javascript: showControl('time-control'); return false;">
<input type="submit" value="Options" style="background: #2EA7F2;" onClick="javascript: showControl('options-control'); return false;">
<input type="submit" value="Update Map">
<input type="submit" onClick="javascript: handsOff(); return false;" value="Auto Pilot">
<br />
<?php 
  include("inc_layers_control.php");
  include("inc_locations_control.php"); 
  include("inc_time_control.php");
  include("inc_options_control.php"); 

dl($mapscript);
$heightadd = 0;
$maptitle = "IEM NEXRAD composite base reflect valid:";
if (intval($loop) ==  1){

  $urls = Array();
  $fts = time();
  $f = fopen("/var/www/htdocs/tmp/". $fts .".dat", 'w');

  for ($i=0;$i<$frames;$i++){
   $imgi = $frames - 1 - $i;
   include("warnings_plot.php");
   $urls[$i] = $url;
   fwrite($f, "$rooturl/$url\n");
  }
  fclose($f);
  echo "<div id=\"applet-hack\"></div><a href=\"anim_gif.php?fts=$fts\">Download as Animated Gif</a><br />";
  include ("loop.php");
  printHTML($urls);
} else if (intval($loop) == 2){
  $heightadd = 100;
  $urls = Array();
  $fts = time();
  $f = fopen("/var/www/htdocs/tmp/". $fts .".dat", 'w');

  for ($i=0;$i<$frames;$i++){
   $imgi = $frames - 1 - $i;
   include("warnings_plot.php");
   $urls[$i] = $url;
   fwrite($f, "$rooturl/$url\n");
  }
  fclose($f);
  echo "<a href=\"anim_gif.php?fts=$fts\">Download as Animated Gif</a><br />";
?>
  <div id="applet-hack"><applet codebase="<?php echo $rooturl; ?>/current/class/" code="AniS.class" width="<?php echo $width; ?>" height="<?php echo $height + 100; ?>" alt="You must enable Java in your browser to view the radar loop" style="float: left;">
        <param name="bottom_controls" value="startstop, looprock, step, speed, toggle, zoom">
        <param name="rate" value="80">
	<PARAM name="no_enh" value="true">
    <param name="pause_percent" value="800">
        <param name="file_of_filenames" value="/tmp/<?php echo $fts; ?>.dat">
</applet></div>

<?php
} else {
  $imgi = 0;
  include("warnings_plot.php");

  echo "<div id=\"applet-hack\"></div><input type=\"image\" name=\"img\" src=\"". $url ."\" border=\"1\">\n";

}

?>
<!-- Warnings Key! -->
<img src="static/warnings_legend.png">
</div>

<?php
echo "<input type=\"hidden\" name=\"extents\" value=\"". $map->extent->minx .",". $map->extent->miny .",". $map->extent->maxx .",". $map->extent->maxy ."\">\n";

$connection = iemdb("postgis");

$scols = Array("wfo", "phenomena", "cname", "expire", "sname", "issue", "updated", "status", "fcster", "eventid");
if (! in_array($sortcol, $scols) ){
 $sortcol = "issue";
}
if ($sortdir == 1) $sortdir = "ASC";
else $sortdir = "DESC";

$wtable = "warnings_$year";
$tsextra = "CURRENT_TIMESTAMP and issue < CURRENT_TIMESTAMP ";
if ($isarchive)
{
  $wtable = "warnings_$year";
  $tsextra = "'". strftime("%Y-%m-%d %H:%M:00+00", $basets + $tzoff ) ."' and w.issue < '". strftime("%Y-%m-%d %H:%M:00+00", $basets + $tzoff ) ."'";
}
$cuextra = "";
if ($cu == 1) $cuextra = " and w.phenomena IN ('SV','TO','MA') ";
$query = "SELECT w.phenomena, w.oid, u.name as cname, w.expire as expire, 
  w.updated as updated, w.status as status, w.fcster as fcster, 
  w.eventid as eventid, w.significance as significance, 
  w.issue as issue, u.state as sname, xmax(w.geom) as lon0, 
  ymax(w.geom) as lat0, w.wfo as wfo
  from $wtable w, nws_ugc u
  WHERE w.expire > $tsextra and w.significance != 'A'
   and w.gtype = 'C' and w.ugc = u.ugc $cuextra ORDER by $sortcol $sortdir";
pg_exec($connection, "set time zone 'GMT'");
$result = pg_exec($connection, $query);

pg_close($connection);

$afos = Array("SV" => "Svr Tstorm",
  "TO" => "Tornado",
  "FF" => "Flash Flood");
?>
<div style="clear: both; margin-top: <?php echo $height +70 +$heightadd; ?>px;">
Warnings Valid at: <b><?php 
if ($tzoff == 0)
{
  if ($isarchive)
  echo strftime("%d %b %Y %H:%M %Z", $basets); 
  else
  echo strftime("%d %b %Y %H:%M %Z"); 
}
else 
{
  if ($isarchive)
  echo strftime("%d %b %Y %I:%M %p ", $basets) . $tz; 
  else
  echo strftime("%d %b %Y %I:%M %p ", time() - $tzoff) . $tz; 
}
?></b>
<br clear=\"all\" />
<?php
$k = 0;
if ($tzoff == 0)
{
  $dformat = "%H:%M GMT";
}
else
{
  $dformat = "%I:%M %p";
}

/* Loop thru results from database! */
$wA = Array();
$oA = Array();
$iA = Array();
$uA = Array();
$fA = Array();
for( $i=0; $row = @pg_fetch_array($result,$i); $i++) 
{
  /* Save the drama! */
  if ($filter && $row["wfo"] != $site) continue; 

  /* key is wfo_state_vtecP_vtecE_vtecSig_expire_status */
  $key = sprintf("%s|%s|%s|%s|%s|%s|%s", $row["wfo"], $row["sname"], 
     $row["phenomena"], $row["eventid"], $row["significance"], $row["expire"],
     $row["status"]);

  $oA[$key] = $row["oid"];
  $iA[$key] = $row["issue"];
  $uA[$key] = $row["updated"];
  $fA[$key] = $row["fcster"];
  @$wA[$key] .= "<a href=\"warnings.phtml?archive=$archive&$baseuri?tz=$tz&cu=$cu&year=$year&month=$month&day=$day&hour=$hour&minute=$m&tzoff=$tzoff&sortdir=$sortdir&loop=$loop&sortcol=$sortcol&c=yes&lon0=". $row["lon0"] ."&lat0=". $row["lat0"] ."&warngeo=$warngeo\">". $row["cname"] ."</a>, ";
}

/* Now we loop thru aggregated warnings */
while ( list($key, $val) = each($wA) )
{
  $tokens = explode("|", $key);
  $wfo = $tokens[0];
  $sname = $tokens[1];
  $phenomena = $tokens[2];
  $eventid = $tokens[3];
  $significance = $tokens[4];
  $expire = $tokens[5];
  $status = $tokens[6];
  $oid = $oA[$key];

  if ($eventid > 0) {
    $warningscat = "warnings_cat.phtml?year=$year&wfo=$wfo&phenomena=$phenomena&eventid=$eventid&significance=$significance";
  } else { /* Old warnings have no VTEC! */
    $warningscat = "warnings_old.phtml?year=$year&oid=$oid";
  }

  $k += 1;
  $issue = strtotime($iA[$key]) - $tzoff;
  $expire = strtotime($expire) - $tzoff;
  $updated = strtotime($uA[$key]) - $tzoff;
  $resetApp = "$uri_nowfo&tz=$tz&cu=$cu&year=$year&month=$month&day=$day&hour=$hour&minute=$m&archive=$archive&tzoff=$tzoff&site=$wfo";

  echo "<div class=\"wwa-state\">$sname</div><div class=\"wwa$significance\"><span style=\"font-size: 14pt;\">". $vtec_phenomena[$phenomena] ." ". $vtec_significance[$significance] ."</span> (<a href=\"$warningscat\">View Text</a>) expires ". strftime($dformat, $expire) ." by <a href=\"$resetApp\">$wfo</a> (". $fA[$key] .")<br />". $wA[$key] ."in $sname  <br /><div class=\"vtec\">VTEC# $eventid ($status)</div><div class=\"issued\">Issued: ".strftime($dformat, $issue) ."</div><div class=\"updated\">Updated: ".  strftime($dformat, $updated) ."</div>&nbsp;</div>\n";


}
if ($k == 0 && $filter){
 $msg = "<p>No warnings currently valid for ". $wfos[$site]["city"] ;
} else if ($k == 0) {
 $msg = "<p>No warnings valid in the United States";
}
if ($k == 0){
  echo "$msg";
}
?>

</form>
<div style="clear: both;">
<?php if (! $isarchive) { ?>
<img src="<?php echo $rooturl; ?>/images/gisready.png">Download <a href="<?php echo $rooturl; ?>/data/gis/shape/unproj/us/current_ww.zip">GIS shapefile of current warnings</a> and/or <a href="<?php echo $rooturl; ?>/data/gis/images/4326/USCOMP/n0r_0.gtif.Z">GeoTiff of NEXRAD base reflectivity</a>.
<?php } ?>

<font size="-1">
<p><b>Notes:</b>
<ul>
 <li>This application is educational grade and should not be used operationally.</li>
 <li>Flash Flood Warnings (FFW) do not have VTEC IDs, so those columns are blank for FFWs.</li>
 <li>The status column is simply the status of the warning.  The warning is in 'NEW' state until a SVS is issued, then it goes to 'CON' for continued.</li>
 <li>Warnings identified by WFO are available after 29 Aug 2004.</li>
 <li>NEXRAD composite is available since 1 Aug 2003.</li>
 <li>Prior to the NWS adoption of VTEC, warnings were not expired nor canceled.</li>
 <li>SVS updates were added in 2005.</li>
 <li>LSR archive begins 1 Jan 2004.</li>
 <li>Archive of watches begins 1 Jan 1997.</li>
</ul>
</font>
</div>


<?php  include ("$rootpath/include/footer.php");?>
