<?php
include("../../../../config/settings.inc.php");
include("$rootpath/include/database.inc.php");

$year = isset($_GET["year"]) ? intval($_GET["year"]) : 0;

if (isset($_GET["oid"]) ) {
  $oid = isset($_GET["oid"]) ? $_GET["oid"] : 0;
  $query = "SELECT * from warnings_$year WHERE oid = $oid";
} else {
  $wfo = isset($_GET["wfo"]) ? $_GET["wfo"] : die("WFO Not Defined!");
  $eventid = isset($_GET["eventid"]) ? $_GET["eventid"] : die("eventid not defined");
  $phenomena = isset($_GET["phenomena"]) ? $_GET["phenomena"] : die("phenomena not defined");
  $query = "SELECT * from warnings_$year WHERE wfo = '$wfo' and phenomena = '$phenomena' and eventid = $eventid ";
}

include("$rootpath/include/header.php");

$connect = iemdb("postgis");


$result = pg_exec($connect, $query);

$row = pg_fetch_array($result, 0);

echo "<pre>". $row["report"] ."</pre>";

if (strlen($row["svs"]) > 0 ) 
{
 $parts = explode('__', $row["svs"]);
 for ($i=1;$i<(sizeof($parts) - 1);$i++)
 {
   echo "<h4><a name=\"svs\">SVS Update</a>:</h4><pre>". $parts[$i] ."</pre>\n";
 }
}

include("$rootpath/include/footer.php");
?>
