<?php
include_once "../../include/forms.php";

$site = isset($_GET["site"]) ? $_GET["site"]: 'ISUAG::302E';
$date = isset($_GET["date"]) ? $_GET["date"]: '2014-06-10';
$errmsg = "";
if (strlen($date) != 10){
	$errmsg = "<div class='alert alert-warning'>Invalid Date Specified!</div>";
	$date = '2014-06-10';
}
$days = isset($_GET["days"]) ? intval($_GET["days"]): 1;
$ptype = isset($_GET['ptype']) ? $_GET['ptype']: '1';

//with data as (select uniqueid, plotid, min(date(valid)), max(date(valid)) from decagon_data GROUP by uniqueid, plotid) SELECT '"'||uniqueid || '::'|| plotid || '"=>"' || uniqueid || ' '||plotid||' ('|| min ||' to '|| max ||') ['|| (max - min) ||' days]",' as d from data ORDER by d;
$ar = Array(
 "DPAC::NE"=>"DPAC NE (2011-07-01 to 2014-12-04) [1252 days]",
 "DPAC::NW"=>"DPAC NW (2011-07-01 to 2014-12-04) [1252 days]",
 "DPAC::SE"=>"DPAC SE (2011-07-01 to 2014-12-04) [1252 days]",
 "DPAC::SW"=>"DPAC SW (2011-07-01 to 2014-12-04) [1252 days]",
 "GILMORE::11-1"=>"GILMORE 11-1 (2011-06-01 to 2013-12-16) [929 days]",
 "GILMORE::11-2"=>"GILMORE 11-2 (2011-06-01 to 2013-12-31) [944 days]",
 "GILMORE::12-2"=>"GILMORE 12-2 (2011-06-01 to 2013-12-31) [944 days]",
 "GILMORE::14-1"=>"GILMORE 14-1 (2011-06-01 to 2013-12-31) [944 days]",
 "GILMORE::14-2"=>"GILMORE 14-2 (2011-06-01 to 2013-12-31) [944 days]",
 "GILMORE::16-2"=>"GILMORE 16-2 (2011-06-01 to 2013-12-31) [944 days]",
 "GILMORE::17-3"=>"GILMORE 17-3 (2011-06-01 to 2013-12-31) [944 days]",
 "GILMORE::19-1"=>"GILMORE 19-1 (2011-06-01 to 2013-12-31) [944 days]",
 "GILMORE::19-3"=>"GILMORE 19-3 (2011-06-01 to 2013-12-31) [944 days]",
 "GILMORE::21-3"=>"GILMORE 21-3 (2011-06-01 to 2013-12-31) [944 days]",
 "GILMORE::22-3"=>"GILMORE 22-3 (2011-06-01 to 2013-10-18) [870 days]",
 "GILMORE::24-3"=>"GILMORE 24-3 (2011-06-01 to 2013-12-31) [944 days]",
 "GILMORE::3-1"=>"GILMORE 3-1 (2011-06-01 to 2013-10-28) [880 days]",
 "GILMORE::4-1"=>"GILMORE 4-1 (2011-06-01 to 2013-12-31) [944 days]",
 "ISUAG::302E"=>"ISUAG 302E (2011-05-24 to 2014-12-31) [1317 days]",
 "ISUAG::302W"=>"ISUAG 302W (2011-05-24 to 2014-12-31) [1317 days]",
 "ISUAG::308E"=>"ISUAG 308E (2000-01-02 to 2014-12-31) [5477 days]",
 "ISUAG::311W"=>"ISUAG 311W (2011-05-24 to 2014-12-31) [1317 days]",
 "ISUAG::402W"=>"ISUAG 402W (2011-05-27 to 2014-12-31) [1314 days]",
 "ISUAG::408E"=>"ISUAG 408E (2011-05-24 to 2014-12-31) [1317 days]",
 "ISUAG::408W"=>"ISUAG 408W (2011-05-24 to 2014-12-31) [1317 days]",
 "ISUAG::410E"=>"ISUAG 410E (2011-05-24 to 2014-12-31) [1317 days]",
		"NAEW::WS109"=>"NAEW WS109 (2013-04-09 to 2014-12-31) [631 days]",
		"NAEW::WS111"=>"NAEW WS111 (2013-04-10 to 2014-12-31) [630 days]",
		"NAEW::WS113"=>"NAEW WS113 (2013-04-10 to 2014-12-31) [630 days]",
		"NAEW::WS115"=>"NAEW WS115 (2014-01-09 to 2014-12-31) [356 days]",
		"NAEW::WS118"=>"NAEW WS118 (2013-04-09 to 2014-12-31) [631 days]",
		"NAEW::WS123"=>"NAEW WS123 (2013-04-15 to 2014-12-31) [625 days]",
		"NAEW::WS127"=>"NAEW WS127 (2013-04-15 to 2014-12-31) [625 days]",
 "SEPAC::10"=>"SEPAC 10 (2011-07-13 to 2014-09-30) [1175 days]",
 "SEPAC::11"=>"SEPAC 11 (2011-07-13 to 2014-09-30) [1175 days]",
 "SEPAC::12"=>"SEPAC 12 (2011-07-13 to 2014-09-30) [1175 days]",
 "SEPAC::5"=>"SEPAC 5 (2011-07-13 to 2014-09-30) [1175 days]",
 "SEPAC::6"=>"SEPAC 6 (2011-06-30 to 2014-09-30) [1188 days]",
 "SEPAC::7"=>"SEPAC 7 (2011-06-30 to 2014-09-30) [1188 days]",
 "SEPAC::8"=>"SEPAC 8 (2011-07-13 to 2014-09-30) [1175 days]",
 "SEPAC::9"=>"SEPAC 9 (2011-07-13 to 2014-09-30) [1175 days]",
 "SERF::1"=>"SERF 1 (2011-06-03 to 2014-12-31) [1307 days]",
 "SERF::2"=>"SERF 2 (2011-06-07 to 2014-05-22) [1080 days]",
 "SERF::3"=>"SERF 3 (2011-06-03 to 2014-12-31) [1307 days]",
 "SERF::4"=>"SERF 4 (2011-06-03 to 2014-12-31) [1307 days]",
 "SERF::5"=>"SERF 5 (2011-06-03 to 2014-12-31) [1307 days]",
 "SERF::6"=>"SERF 6 (2011-06-03 to 2014-12-31) [1307 days]",
 "SERF::7"=>"SERF 7 (2011-06-03 to 2014-12-31) [1307 days]",
 "SERF::8"=>"SERF 8 (2011-06-03 to 2014-12-31) [1307 days]",
 "WATERMAN::1"=>"WATERMAN 1 (2013-09-18 to 2014-12-22) [460 days]",
 "WATERMAN::4"=>"WATERMAN 4 (2013-09-18 to 2014-12-22) [460 days]",
 "WATERMAN::5"=>"WATERMAN 5 (2013-09-18 to 2014-12-22) [460 days]",		
		);
$siteselect = make_select("site", $site, $ar);

$ar = Array(
		'1' => 'Timeseries',
		'2' => 'Daily Averages',
		'3' => 'Hourly Averages');
$ptypeselect = make_select("ptype", $ptype, $ar);

$imageurl = sprintf("plot_decagon.py?site=%s&date=%s&days=%s&ptype=%s", 
		$site, $date, $days, $ptype);

echo <<<EOF
<html lang='en'>
<head>
<link href="/vendor/bootstrap/3.3.5/css/bootstrap.min.css" rel="stylesheet">
<link href="/css/bootstrap-override.css" rel="stylesheet">
<link rel="stylesheet" href="http://code.jquery.com/ui/1.10.3/themes/smoothness/jquery-ui.css" />  
</head>
<body>

<h3>CSCAP Decagon Data Plotting</h3>

{$errmsg}

<form method="GET" name="plot1">
<table class="table table-bordered">
<thead><tr><th>Select Site and Plot:</th><th>Select Start Date</th>
<th>Number of Days to Plot</th><th>Plot Type</th></tr></thead>
<tbody><tr><td>
{$siteselect}
</td>
<td><input type="text" id="datepicker" name="date" value="{$date}" /></td>
<td><input type="text" name="days" value="{$days}" /></td>
<td>{$ptypeselect}</td>
</tr></tbody>
</table>

<input type="submit" value="Make Plot">
</form>

<p><img src="{$imageurl}"></p>

<h3>Observation Site Collection Interval</h3>

<p>This table lists the observation time interval at each site:
<pre>
DPAC     5 minute
GILMORE  5 minute
ISUAG    5 minute
NAEW    30 minute
SEPAC    5 minute
SERF     5 minute
WATERMAN 2 minute
</pre></p>

<script src="/vendor/jquery/1.11.3/jquery-1.11.3.min.js"></script>
<script src="/vendor/bootstrap/3.3.5/js/bootstrap.min.js"></script>
 <script src="http://code.jquery.com/ui/1.10.3/jquery-ui.js"></script>
<script>
$(document).ready(function(){
	$( "#datepicker" ).datepicker({dateFormat:"yy-mm-dd",
		defaultDate: "{$date}",
		changeMonth: true,
		changeYear: true,
		minDate: new Date(2011, 1, 1),
		maxDate: new Date(2016, 1, 1)});		
});
		
</script>
</body>
</html>
EOF;
?>