<?php
include_once "../../include/forms.php";

$site = isset($_GET["site"]) ? $_GET["site"]: 'ISUAG::302E';
$date = isset($_GET["date"]) ? $_GET["date"]: '2014-06-10';
$view = isset($_GET['view']) ? $_GET['view']: 'plot';
$depth = isset($_GET['depth']) ? $_GET['depth']: 'all';
$errmsg = "";
if (strlen($date) != 10){
	$errmsg = "<div class='alert alert-warning'>Invalid Date Specified!</div>";
	$date = '2014-06-10';
}
$days = isset($_GET["days"]) ? intval($_GET["days"]): 1;
$ptype = isset($_GET['ptype']) ? $_GET['ptype']: '1';

/* with data as (select uniqueid, plotid, min(date(valid)),
 max(date(valid)) from decagon_data GROUP by uniqueid, plotid)
 
 SELECT '"'||uniqueid || '::'|| plotid || '"=>"' || uniqueid || ' '||
 plotid||' ('|| min ||' to '|| max ||') ['|| (max - min) ||' days]",' as d
 from data ORDER by d;
*/
$ar = Array(
 "DPAC::NE"=>"DPAC NE (2011-07-01 to 2015-12-06) [1619 days]",
 "DPAC::NW"=>"DPAC NW (2011-07-01 to 2015-12-06) [1619 days]",
 "DPAC::SE"=>"DPAC SE (2011-07-01 to 2015-12-06) [1619 days]",
 "DPAC::SW"=>"DPAC SW (2011-07-01 to 2015-12-06) [1619 days]",
 "GILMORE::3-1"=>"GILMORE 3-1 (2011-06-01 to 2015-12-10) [1653 days]",
 "GILMORE::4-1"=>"GILMORE 4-1 (2011-06-01 to 2015-12-10) [1653 days]",
 "GILMORE::11-1"=>"GILMORE 11-1 (2011-06-01 to 2015-09-04) [1556 days]",
 "GILMORE::11-2"=>"GILMORE 11-2 (2011-06-01 to 2015-09-04) [1556 days]",
 "GILMORE::12-2"=>"GILMORE 12-2 (2011-06-01 to 2015-09-04) [1556 days]",
 "GILMORE::14-1"=>"GILMORE 14-1 (2011-06-01 to 2015-09-04) [1556 days]",
 "GILMORE::14-2"=>"GILMORE 14-2 (2011-06-01 to 2015-09-04) [1556 days]",
 "GILMORE::16-2"=>"GILMORE 16-2 (2011-06-01 to 2015-12-10) [1653 days]",
 "GILMORE::17-3"=>"GILMORE 17-3 (2000-01-02 to 2015-12-10) [5821 days]",
 "GILMORE::19-1"=>"GILMORE 19-1 (2011-06-01 to 2015-12-10) [1653 days]",
 "GILMORE::19-3"=>"GILMORE 19-3 (2011-06-01 to 2015-12-10) [1653 days]",
 "GILMORE::21-3"=>"GILMORE 21-3 (2011-06-01 to 2015-12-10) [1653 days]",
 "GILMORE::22-3"=>"GILMORE 22-3 (2011-06-01 to 2015-12-10) [1653 days]",
 "GILMORE::24-3"=>"GILMORE 24-3 (2011-06-01 to 2015-12-10) [1653 days]",
		"ISUAG::302E"=>"ISUAG 302E (2011-05-24 to 2015-09-10) [1570 days]",
		"ISUAG::302W"=>"ISUAG 302W (2011-05-24 to 2015-10-12) [1602 days]",
		"ISUAG::308E"=>"ISUAG 308E (2011-05-24 to 2015-10-02) [1592 days]",
		"ISUAG::311W"=>"ISUAG 311W (2011-05-24 to 2015-09-10) [1570 days]",
		"ISUAG::402W"=>"ISUAG 402W (2011-05-27 to 2015-10-01) [1588 days]",
		"ISUAG::408E"=>"ISUAG 408E (2011-05-24 to 2015-10-12) [1602 days]",
		"ISUAG::408W"=>"ISUAG 408W (2011-05-24 to 2015-10-12) [1602 days]",
		"ISUAG::410E"=>"ISUAG 410E (2011-05-24 to 2015-10-12) [1602 days]",
		"ISUAG.USB::1-1.1"=>"ISUAG.USB 1-1.1 (2014-07-17 to 2015-12-31) [532 days]",
		"ISUAG.USB::1-2.1"=>"ISUAG.USB 1-2.1 (2014-07-17 to 2015-12-31) [532 days]",
		"ISUAG.USB::1-3.2"=>"ISUAG.USB 1-3.2 (2014-07-17 to 2015-12-31) [532 days]",
		"ISUAG.USB::1-5.1"=>"ISUAG.USB 1-5.1 (2014-07-18 to 2015-12-31) [531 days]",
		"ISUAG.USB::1-6.2"=>"ISUAG.USB 1-6.2 (2014-07-18 to 2015-12-31) [531 days]",
		"ISUAG.USB::1-7.2"=>"ISUAG.USB 1-7.2 (2014-07-18 to 2015-12-31) [531 days]",
		"ISUAG.USB::2-1.1"=>"ISUAG.USB 2-1.1 (2014-07-21 to 2015-12-31) [528 days]",
		"ISUAG.USB::2-2.1"=>"ISUAG.USB 2-2.1 (2014-07-21 to 2015-12-31) [528 days]",
		"ISUAG.USB::2-5.2"=>"ISUAG.USB 2-5.2 (2014-07-21 to 2015-12-31) [528 days]",
		"ISUAG.USB::2-6.1"=>"ISUAG.USB 2-6.1 (2014-07-21 to 2015-12-31) [528 days]",
		"ISUAG.USB::2-7.2"=>"ISUAG.USB 2-7.2 (2014-07-21 to 2015-12-31) [528 days]",
		"ISUAG.USB::2-8.2"=>"ISUAG.USB 2-8.2 (2014-07-21 to 2015-12-31) [528 days]",
		"ISUAG.USB::3-2.1"=>"ISUAG.USB 3-2.1 (2014-07-18 to 2015-12-31) [531 days]",
		"ISUAG.USB::3-3.2"=>"ISUAG.USB 3-3.2 (2014-07-22 to 2015-12-31) [527 days]",
		"ISUAG.USB::3-5.1"=>"ISUAG.USB 3-5.1 (2014-07-22 to 2015-12-31) [527 days]",
		"ISUAG.USB::3-6.2"=>"ISUAG.USB 3-6.2 (2014-07-22 to 2015-12-31) [527 days]",
		"ISUAG.USB::3-7.1"=>"ISUAG.USB 3-7.1 (2014-07-22 to 2015-12-31) [527 days]",
		"ISUAG.USB::3-8.2"=>"ISUAG.USB 3-8.2 (2014-07-22 to 2015-12-31) [527 days]",
		"MASON::205"=>"MASON 205 (2014-06-06 to 2014-10-24) [140 days]",
		"MASON::206"=>"MASON 206 (2014-06-06 to 2014-10-24) [140 days]",
		"MASON::207"=>"MASON 207 (2014-06-06 to 2014-10-24) [140 days]",
		"MASON::208-1"=>"MASON 208-1 (2014-06-06 to 2014-10-24) [140 days]",
		"MASON::208-2"=>"MASON 208-2 (2014-06-06 to 2014-10-24) [140 days]",
		"MASON::305"=>"MASON 305 (2014-06-06 to 2014-10-24) [140 days]",
		"MASON::306"=>"MASON 306 (2014-06-06 to 2014-10-24) [140 days]",
		"MASON::307-1"=>"MASON 307-1 (2014-06-06 to 2014-10-24) [140 days]",
		"MASON::307-2"=>"MASON 307-2 (2014-06-06 to 2014-10-24) [140 days]",
		"MASON::308"=>"MASON 308 (2014-06-06 to 2014-10-24) [140 days]",
		"MASON::505"=>"MASON 505 (2014-06-06 to 2014-10-24) [140 days]",
		"MASON::506"=>"MASON 506 (2014-06-06 to 2014-10-24) [140 days]",
		"MASON::507-1"=>"MASON 507-1 (2014-06-06 to 2014-10-24) [140 days]",
		"MASON::507-2"=>"MASON 507-2 (2014-06-06 to 2014-10-24) [140 days]",
		"MASON::508"=>"MASON 508 (2014-06-06 to 2014-10-24) [140 days]",
		"MASON::601-1"=>"MASON 601-1 (2014-06-06 to 2014-10-24) [140 days]",
		"MASON::601-2"=>"MASON 601-2 (2014-06-06 to 2014-10-24) [140 days]",
		"MASON::602"=>"MASON 602 (2014-06-06 to 2014-10-24) [140 days]",
		"MASON::603"=>"MASON 603 (2014-06-06 to 2014-10-24) [140 days]",
		"MASON::604"=>"MASON 604 (2014-06-06 to 2014-10-24) [140 days]",
 "NAEW::WS109"=>"NAEW WS109 (2013-04-09 to 2015-11-02) [937 days]",
 "NAEW::WS111"=>"NAEW WS111 (2013-04-10 to 2015-11-02) [936 days]",
 "NAEW::WS113"=>"NAEW WS113 (2013-04-10 to 2015-11-02) [936 days]",
 "NAEW::WS115"=>"NAEW WS115 (2013-04-15 to 2015-11-02) [931 days]",
 "NAEW::WS118"=>"NAEW WS118 (2013-04-09 to 2015-11-02) [937 days]",
 "NAEW::WS123"=>"NAEW WS123 (2013-04-15 to 2015-11-02) [931 days]",
 "NAEW::WS127"=>"NAEW WS127 (2013-04-15 to 2015-10-17) [915 days]",
 "SEPAC::5"=>"SEPAC 5 (2011-07-13 to 2015-11-24) [1595 days]",
 "SEPAC::6"=>"SEPAC 6 (2011-06-30 to 2015-11-24) [1608 days]",
 "SEPAC::7"=>"SEPAC 7 (2011-06-30 to 2015-11-24) [1608 days]",
 "SEPAC::8"=>"SEPAC 8 (2011-07-13 to 2015-11-24) [1595 days]",
 "SEPAC::9"=>"SEPAC 9 (2011-07-13 to 2015-11-24) [1595 days]",
 "SEPAC::10"=>"SEPAC 10 (2011-07-13 to 2015-11-24) [1595 days]",
 "SEPAC::11"=>"SEPAC 11 (2011-07-13 to 2015-11-24) [1595 days]",
 "SEPAC::12"=>"SEPAC 12 (2011-07-13 to 2015-11-24) [1595 days]",
 "SERF::1"=>"SERF 1 (2011-06-03 to 2014-12-31) [1307 days]",
 "SERF::2"=>"SERF 2 (2011-06-07 to 2014-05-22) [1080 days]",
 "SERF::3"=>"SERF 3 (2011-06-03 to 2014-12-31) [1307 days]",
 "SERF::4"=>"SERF 4 (2011-06-03 to 2014-12-31) [1307 days]",
 "SERF::5"=>"SERF 5 (2011-06-03 to 2014-12-31) [1307 days]",
 "SERF::6"=>"SERF 6 (2011-06-03 to 2014-12-31) [1307 days]",
 "SERF::7"=>"SERF 7 (2011-06-03 to 2014-12-31) [1307 days]",
 "SERF::8"=>"SERF 8 (2011-06-03 to 2014-12-31) [1307 days]",
		"STJOHNS::WN1"=>"STJOHNS WN1 (2011-12-14 to 2015-11-20) [1437 days]",
		"STJOHNS::WN2"=>"STJOHNS WN2 (2011-12-14 to 2015-11-20) [1437 days]",
		"STJOHNS::WN3"=>"STJOHNS WN3 (2011-12-15 to 2015-11-03) [1419 days]",
		"STJOHNS::WS1"=>"STJOHNS WS1 (2011-12-15 to 2015-11-20) [1436 days]",
		"STJOHNS::WS2"=>"STJOHNS WS2 (2011-09-20 to 2015-11-20) [1522 days]",
		"STJOHNS::WS3"=>"STJOHNS WS3 (2011-12-15 to 2015-11-20) [1436 days]",
 "WATERMAN::1"=>"WATERMAN 1 (2013-09-18 to 2015-12-16) [819 days]",
 "WATERMAN::4"=>"WATERMAN 4 (2013-09-18 to 2015-12-16) [819 days]",
 "WATERMAN::5"=>"WATERMAN 5 (2013-09-18 to 2015-12-16) [819 days]",
		);
$siteselect = make_select("site", $site, $ar);

$ar = Array(
		'1' => 'Observations (no aggregation)',
		'3' => 'Hourly Averages',
		'2' => 'Daily Averages',
		'4' => 'Weekly Averages',
		);
$ptypeselect = make_select("ptype", $ptype, $ar);

$ar = Array(
		'plot'=> 'View Plot',
		'html' => 'View Raw Data in HTML Table',
		'csv' => 'Download as CSV File',
		'excel' => 'Download as Excel File'
		);
$viewselect = make_select('view', $view, $ar);

$ar = Array(
		'all' => 'All Depths, one plot',
		'1' => '10cm, all plots for site',
		'2' => '20cm, all plots for site',
		'3' => '40cm, all plots for site',
		'4' => '60cm, all plots for site',
		'5' => '100cm, all plots for site',
		);
$depthselect = make_select('depth', $depth, $ar);

if ($view != 'plot'){
	$imageurl = sprintf("plot_decagon.py?site=%s&date=%s&days=%s&ptype=%s&view=%s&depth=%s", 
		$site, $date, $days, $ptype, $view, $depth);
	$uri = sprintf("http://iem.local/cscap/%s", $imageurl);
	if ($view == 'html'){
		$data = file_get_contents($uri);
		$interface = $data;
	} else{
		Header(sprintf("Location: /cscap/%s", $imageurl));
		die();
	}
} else {
	$imageurl = sprintf("decagon_%s_%s_%s_%s_%s.png", 
		$site, $date, $days, $ptype, $depth);
	$interface = "<img src=\"{$imageurl}\">";
	
}

echo <<<EOF
<html lang='en'>
<head>
<link href="/vendor/bootstrap/3.3.5/css/bootstrap.min.css" rel="stylesheet">
<link href="/css/bootstrap-override.css" rel="stylesheet">
<link rel="stylesheet" href="/vendor/jquery-ui/1.11.4/jquery-ui.css" /> 
<link rel="stylesheet" href="/vendor/jquery-ui/1.11.4/jquery-ui.theme.css" />  
<title>CSCAP Decagon Data Plotting/Download</title>
<style>
select {
  color: #000;
}
</style>
</head>
<body>

<h3>CSCAP Decagon Data Plotting/Download</h3>

{$errmsg}

<form method="GET" name="plot1">
<table class="table table-bordered">
<thead><tr><th>Select Site and Plot:</th><th>Depth Option:</th><th>Select Start Date</th>
</tr></thead>
<tbody><tr><td>
{$siteselect}
</td><td>{$depthselect}</td>
<td><input type="text" id="datepicker" name="date" value="{$date}" size="11" /></td>
</tr></tbody></table>

<table class="table table-bordered">
<thead><tr><th>Number of Days to Plot</th>
<th>Timeseries Aggregation:</th><th>View Option</th></tr></thead>
<tbody><tr>
<td><input type="text" name="days" value="{$days}" size="4" /></td>
<td>{$ptypeselect}</td>
<td>{$viewselect}</td>
</tr></tbody>
</table>

<input type="submit" value="Run">
</form>

<p>{$interface}</p>

<h3>Frequently Asked Questions</h3>

<ol>
<li><strong>How are timezones handled?</strong><br />
The timestamps presented should be valid for the local time zone of the sensor
and are daylight saving time aware.  The daily aggregates should compute the
daily summaries in the time zone of the station.
</li>
<li><strong>What quality control procedures have been implemented?</strong><br />
Please see this <a href="https://docs.google.com/document/d/1K_FtA-nkhCVlkBULgwOpYb4FmMptaZDuEcaqaj7fS-U/edit">Google Drive Doc</a> for more details on this and the flags used
to denote quality control.
</li>
</ol>

<h3>Observation Site Collection Interval</h3>

<p>This table lists the observation time interval at each site:
<pre>
 ST  SITE       INTERVAL  SAMPLING DEPTHS     PERIOD
[IN] DPAC       5 minute  10 20 40 60 100 cm  n=5 years; 2011 to 2015
[IA] GILMORE    5 minute  10 20 40 60 100 cm  n=5 years; 2011 to 2015
[IA] ISUAG      5 minute  10 20 40 60 100 cm  n=5 years; 2011 to 2015
[IA] ISUAG.USB  5 minute  10 20 40 60 100 cm  n=2 years; 2014 to 2015
[MI] KELLOGG                                  TBD
[MI] MASON     60 minute     20 40 60  80 cm  n=2 years; 2014 to 2015
[MN] HICKS.B                                  n=4 years; 2012 to 2015
[MN] HICKS.G                                  n=4 years; 2012 to 2015
[MN] HICKS.P                                  n=4 years; 2012 to 2015
[MN] VICMS                                    n=3 years; 2013 to 2015
[OH] NAEW      30 minute   5 10 20 30  50 cm  n=3 years; 2013 to 2015
[IN] SEPAC      5 minute  10 20 40 60 100 cm  n=5 years; 2011 to 2015
[IA] SERF       5 minute  10 20 40 60 100 cm  n=5 years; 2011 to 2015
[OH] STJOHNS    5 minute  10 20 40 60 100 cm  n=5 years; 2011 to 2015
[OH] WATERMAN   2 minute  10 20 40 60 100 cm  n=3 years; 2013 to 2015
</pre></p>

<h3>Notes</h3>

<p>Decagon data included in this visualization and aggregation tool is associated with the 
USDA-NIFA funded project: "Cropping Systems Coordinated Agricultural Project: Climate Change,
Mitigation, and Adaptation in Corn-based Cropping Systems." (Award No. 2011-68002-30190).</p>

<ul>
 <li>NAEW soil moisture sensor depths were   
 aligned when possible with VICMS in MN for data compilation. However, a
 rock layer prohibits sensor installation deeper than 50 cm.</li>
</ul>

<script src="/vendor/bootstrap/3.3.5/js/bootstrap.min.js"></script>
<script src="/vendor/jquery/1.11.3/jquery-1.11.3.min.js"></script>
<script src="/vendor/jquery-ui/1.11.4/jquery-ui.js"></script>
<script>
$(document).ready(function(){
	$( "#datepicker" ).datepicker({dateFormat:"yy-mm-dd",
		defaultDate: "{$date}",
		changeMonth: true,
		changeYear: true,
		minDate: new Date(2011, 1, 1),
		maxDate: new Date(2016, 1, 1)});		
});
		
</script>
</body>
</html>
EOF;
?>