<?php
include_once "../../include/forms.php";

$site = isset($_GET["site"]) ? $_GET["site"]: 'DPAC::NE';
$date = isset($_GET["date"]) ? $_GET["date"]: '2014-06-10';
$view = isset($_GET['view']) ? $_GET['view']: 'plot';
$depth = isset($_GET['depth']) ? $_GET['depth']: 'all';
$errmsg = "";
if (strlen($date) != 10){
	$errmsg = "<div class='alert alert-warning'>Invalid Date Specified!</div>";
	$date = '2014-06-10';
}
$days = isset($_GET["days"]) ? intval($_GET["days"]): 1;
$ptype = isset($_GET['ptype']) ? $_GET['ptype']: '1';

/* with data as (select uniqueid, plotid, min(date(valid)),
 max(date(valid)) from watertable_data GROUP by uniqueid, plotid)
 
 SELECT '"'||uniqueid || '::'|| plotid || '"=>"' || uniqueid || ' '||
 plotid||' ('|| min ||' to '|| max ||') ['|| (max - min) ||' days]",' as d
 from data ORDER by d;
*/
$ar = Array(
		"DPAC::NE"=>"DPAC NE (2006-07-01 to 2015-12-03) [3442 days]",
		"DPAC::NW"=>"DPAC NW (2006-07-01 to 2015-12-03) [3442 days]",
		"DPAC::SE"=>"DPAC SE (2006-09-20 to 2015-12-03) [3361 days]",
		"DPAC::SW"=>"DPAC SW (2006-07-01 to 2015-12-03) [3442 days]",
		);
$siteselect = make_select("site", $site, $ar);

$ar = Array(
		'1' => 'Observations (no aggregation)',
		'3' => 'Hourly Averages',
		'2' => 'Daily Averages',
		'4' => 'Weekly Averages',
		);
$ptypeselect = make_select("ptype", $ptype, $ar);

$ar = Array(
		'plot'=> 'View Plot',
		'html' => 'View Raw Data in HTML Table',
		'csv' => 'Download as CSV File',
		'excel' => 'Download as Excel File'
		);
$viewselect = make_select('view', $view, $ar);

$jsextra = "";
if ($view != 'plot'){
	$imageurl = sprintf("plot_watertable.py?site=%s&date=%s&days=%s&ptype=%s&view=%s", 
		$site, $date, $days, $ptype, $view);
	$uri = sprintf("http://iem.local/cscap/%s", $imageurl);
	if ($view == 'html'){
		$data = file_get_contents($uri);
		$interface = $data;
	} else{
		Header(sprintf("Location: /cscap/%s", $imageurl));
		die();
	}
} else {
	$jsurl = sprintf("watertable_%s_%s_%s_%s.js", 
		$site, $date, $days, $ptype);
	$jsextra = "<script src=\"{$jsurl}\"></script>";
	$interface = <<<EOF
<div id="hc" style="width: 100%; height: 400px;"></div>
EOF;
}

echo <<<EOF
<html lang='en'>
<head>
<link href="/vendor/bootstrap/3.3.5/css/bootstrap.min.css" rel="stylesheet">
<link href="/css/bootstrap-override.css" rel="stylesheet">
<link rel="stylesheet" href="/vendor/jquery-ui/1.11.4/jquery-ui.css" /> 
<link rel="stylesheet" href="/vendor/jquery-ui/1.11.4/jquery-ui.theme.css" />  
<title>CSCAP Water Table Data Plotting/Download</title>
<style>
select {
  color: #000;
}
</style>
</head>
<body>

<h3>CSCAP Water Table Data Plotting/Download</h3>

{$errmsg}

<form method="GET" name="plot1">
<table class="table table-bordered">
<thead><tr><th>Select Site: (<i>currently, all plots at site are shown on the graph)</i></th><th>Select Start Date</th>
</tr></thead>
<tbody><tr><td>
{$siteselect}
</td>
<td><input type="text" id="datepicker" name="date" value="{$date}" size="11" /></td>
</tr></tbody></table>

<table class="table table-bordered">
<thead><tr><th>Number of Days to Plot</th>
<th>Timeseries Aggregation:</th><th>View Option</th></tr></thead>
<tbody><tr>
<td><input type="text" name="days" value="{$days}" size="4" /></td>
<td>{$ptypeselect}</td>
<td>{$viewselect}</td>
</tr></tbody>
</table>

<input type="submit" value="Run">
</form>

<p>{$interface}</p>

<p><i>Pro Tip:</i> You can click the legend name to toggle showing and hiding
the data series.  You can also mouse click and drag on the plot to zoom it in.
</p>

<h3>Frequently Asked Questions</h3>

<ol>
<li><strong>How are timezones handled?</strong><br />
The timestamps presented should be valid for the local time zone of the sensor
and are daylight saving time aware.  The daily aggregates should compute the
daily summaries in the time zone of the station.
</li>
<li><strong>What quality control procedures have been implemented?</strong><br />
Please see this <a href="https://docs.google.com/document/d/1K_FtA-nkhCVlkBULgwOpYb4FmMptaZDuEcaqaj7fS-U/edit">Google Drive Doc</a> for more details on this and the flags used
to denote quality control.
</li>
</ol>

<h3>Observation Site Collection Interval</h3>

<p>This table lists the observation time interval at each site:
<pre>
 ST  SITE       INTERVAL  
[IN] DPAC      60 minute  n=10 years; 2006 to 2015
</pre></p>

<h3>Notes</h3>

<ul>
 <li></li>
</ul>

<script src="/vendor/jquery/1.11.3/jquery-1.11.3.min.js"></script>
<script src="/vendor/jquery-ui/1.11.4/jquery-ui.js"></script>
<script src="/vendor/bootstrap/3.3.5/js/bootstrap.min.js"></script>
<script src="/vendor/highcharts/4.2.0/highcharts.js"></script>
<script src="/vendor/highcharts/4.2.0/highcharts-more.js"></script>
<script src="/vendor/highcharts/4.2.0/modules/exporting.js"></script>
{$jsextra}
<script>
$(document).ready(function(){
	$( "#datepicker" ).datepicker({dateFormat:"yy-mm-dd",
		defaultDate: "{$date}",
		changeMonth: true,
		changeYear: true,
		minDate: new Date(2006, 1, 1),
		maxDate: new Date(2016, 1, 1)});		
});
		
</script>
</body>
</html>
EOF;
?>