<?php
require_once "../../config/settings.inc.php";
require_once "../../include/myview.php";
require_once "../../include/database.inc.php";

$t = new MyView();
define("IEM_APPID", 145);

$t->title = "RWIS Archived Webcam Imagery";
$t->headextra = <<<EOF
 <link rel="stylesheet" href="/vendor/jquery-ui/1.11.4/jquery-ui.css" />
EOF;
$t->jsextra = <<<EOF
 <script src="/vendor/jquery-ui/1.11.4/jquery-ui.js"></script>
 <script src="camera.js"></script>
EOF;
$t->thispage = "networks-rwis";

$conn = iemdb("mesosite");
$rs = pg_query($conn, "SELECT id, name, date(sts) as s from webcams WHERE network = 'IDOT'
		ORDER by name ASC");
$sform = "<select name='cid'>";
for ($i=0;$row=pg_fetch_assoc($rs);$i++){
	$sform .= sprintf("<option value='%s'>%s -- (%s)</option>\n", $row["id"], $row["name"],
			$row["s"]);
}
$sform .= "</select>";


$t->content = <<<EOF
<h3>Archived Iowa RWIS Webcam Imagery</h3>

<p>The IEM archives imagery provided by the Iowa DOT RWIS network.  Each site
with a webcam has a number of preset views that are each queried about once
per 10 minutes.  Please select the webcam view you wish to see and then 
select a date of interest.  The left hand menu will automatically populate with
a listing of images available for that date. <strong>Hint:</strong> Once you
select a time, use the up/down keyboard arrow to create a quasi-timelapse.</p>

<p>Archiving started back on 19 Dec 2009.  The start date of invidual webcams
is shown in the select menu.

<input type="hidden" id="realdate" />

<div class="row">
  <div class="col-md-8 col-sm-12">
  <span style="font-weight: bold;">1. Select Webcam View:</span>{$sform}
  </div>
  <div class="col-md-4 col-sm-12">
  <span style="font-weight: bold;">2. Date:</span> <input type="text" id="datepicker" />

  </div>
</div>

<div class="row">
  <div class="col-md-2 col-sm-12">
  <strong>3. Select Time:</sstrong>
  <br />
  <select size="30" name="times">
  </select> 
  </div>
  <div class="col-md-8 col-sm-12">
  <img id="theimage" src="camera_instructions.png" class="img img-responsive">
  </div>
</div>

<br clear="all" />
EOF;
$t->render("full.phtml");
?>
