<?php
 include("../../config/settings.inc.php");
 $sortcol = isset($_GET["sortcol"]) ? $_GET["sortcol"] : "ts";
$network = isset($_GET['network']) ? $_GET['network'] : 'IA_RWIS';
 $TITLE = "IEM | RWIS | Currents";
 $REFRESH = "<meta http-equiv=\"refresh\" content=\"600; URL=current.phtml?sortcol=$sortcol&network=$network\">";
 $HEADEXTRA = '<script language="JavaScript" type="text/javascript">
<!--//BEGIN Script
function new_window(url) {
 link = window.open(url,"_new","toolbar=0,location=0,directories=0,status=0,menubar=no,scrollbars=yes,resizable=yes,width=800,height=600");
} 
//END Script-->
</script>';
 $THISPAGE = "current-sort";
 include("$rootpath/include/header.php"); ?>
<?php include("$rootpath/include/mlib.php"); ?>
<?php 
  include("$rootpath/include/iemaccess.php");
  include("$rootpath/include/iemaccessob.php");

$iem = new IEMAccess();
$rwis = $iem->getNetwork($network);


?>

<?php

$vals = Array("tmpf" => "Air Temperature [F]", "dwpf" => "Dew Point Temp [F]",
  "sknt" => "Wind Speed [knots]", "drct" => "Wind Direction [deg]",
  "pday" => "Precip Accum [inches]", "max_sknt" => "Wind Gust [knots]",
  "ts" => "Observation Time [local]", "feel" => "Feels Like", "peak" =>"Wind Gust",
  "min_tmpf" => "Today's Low Temperature", "peak_ts" => "Time of Wind Gust",
  "max_tmpf" => "Today's High Temperature", "sname" => "Station Name",
  "sid" => "Station ID", "relh" => "Relative Humidity", "vsby" => "Visibility");

?>

<?php $current_network = "RWIS"; include("$rootpath/include/current_bar.inc.php"); ?>
<form method="GET" action="current.phtml">
<select name="network">
  <option value="IN_RWIS" <?php if ($network == "IN_RWIS") echo "SELECTED"; ?>>Indiana 
  <option value="IA_RWIS" <?php if ($network == "IA_RWIS") echo "SELECTED"; ?>>Iowa
  <option value="IL_RWIS" <?php if ($network == "IL_RWIS") echo "SELECTED"; ?>>Illinois
  <option value="KS_RWIS" <?php if ($network == "KS_RWIS") echo "SELECTED"; ?>>Kansas
  <option value="MD_RWIS" <?php if ($network == "MD_RWIS") echo "SELECTED"; ?>>Maryland
  <option value="MN_RWIS" <?php if ($network == "MN_RWIS") echo "SELECTED"; ?>>Minnesota
  <option value="NE_RWIS" <?php if ($network == "NE_RWIS") echo "SELECTED"; ?>>Nebraska
  <option value="NH_RWIS" <?php if ($network == "NH_RWIS") echo "SELECTED"; ?>>New Hampshire
  <option value="ND_RWIS" <?php if ($network == "ND_RWIS") echo "SELECTED"; ?>>North Dakota
  <option value="OH_RWIS" <?php if ($network == "OH_RWIS") echo "SELECTED"; ?>>Ohio
  <option value="WI_RWIS" <?php if ($network == "WI_RWIS") echo "SELECTED"; ?>>Wisconsin
  <option value="WY_RWIS" <?php if ($network == "WY_RWIS") echo "SELECTED"; ?>>Wyoming
</select>
<input type="submit" value="Show State">
</form>

<?php
echo "Sorted by: <b>(". $vals[$sortcol] .")</b>  &nbsp; &nbsp; Click on a column to sort it.<br>\n";
$uri = "current.phtml?network=${network}&sortcol=";
?>

<form method="GET" action="/my/current.phtml">
<table style="width: 100%; font-size: 10pt;" border="0" cellpadding="1" cellspacing="0">
<thead>
<tr>
  <th rowspan="2">ADD:</th>
  <th rowspan="2"><a href="<?php echo $uri; ?>sname">Station:</a></th>
  <th rowspan="2"><a href="<?php echo $uri; ?>ts">Ob Time</a></th>
  <th colspan="3" bgcolor="#acdcda">Temps &deg;F</th>
  <th>&nbsp;</th>
  <th>&nbsp;</th>
  <th colspan="3" bgcolor="#EEEEEE">Wind [knots]</th>
  <th><a href="<?php echo $uri; ?>pday">Precip</a></th>
</tr>
<tr>
  
  <th>
   <a href="<?php echo $uri; ?>tmpf">Air</a>
   (<a href="<?php echo $uri; ?>max_tmpf">Hi</a> /
   <a href="<?php echo $uri; ?>min_tmpf">Lo</a>)
</th>
  <th><a href="<?php echo $uri; ?>dwpf">DewP</a></th>
  <th><a href="<?php echo $uri; ?>feel">Feels</a></th>
  <th><a href="<?php echo $uri; ?>relh">RH%</a></th>
  <th><a href="<?php echo $uri; ?>vsby">Vis</a></th>
  <th><a href="<?php echo $uri; ?>sknt">Speed</a></th>
  <th><a href="<?php echo $uri; ?>drct">Direction</a></th>
  <th><a href="<?php echo $uri; ?>peak">Gust</a>
    @<a href="<?php echo $uri; ?>peak_ts">Time</a></th>
  <th><a href="<?php echo $uri; ?>pday">Accum</a> [1]</th>
</tr></thead>
<tbody>
<?php
function aSortBySecondIndex($multiArray, $secondIndex) {
        while (list($firstIndex, ) = each($multiArray))
                $indexMap[$firstIndex] = $multiArray[$firstIndex][$secondIndex];
        arsort($indexMap);
        while (list($firstIndex, ) = each($indexMap))
                if (is_numeric($firstIndex))
                        $sortedArray[] = $multiArray[$firstIndex];
                else $sortedArray[$firstIndex] = $multiArray[$firstIndex];
        return $sortedArray;
}

  $mydata = Array();

  while (list($key, $iemob) = each($rwis) ){
    $mydata[$key] = $iemob->db;
    $mydata[$key]["ts"] = $iemob->ts;
    $mydata[$key]["relh"] = relh(f2c($mydata[$key]["tmpf"]), 
       f2c($mydata[$key]["dwpf"]) );
    $mydata[$key]["feel"] = feels_like($mydata[$key]["tmpf"], 
       $mydata[$key]["relh"], $mydata[$key]["sknt"] * 1.15078);
    if ($mydata[$key]["dwpf"] > $mydata[$key]["tmpf"]){
       $mydata[$key]["feel"] = "";
       $mydata[$key]["dwpf"] = "";
    }
    if ($mydata[$key]["relh"] > 100){ 
       $mydata[$key]["feel"] = "";
       $mydata[$key]["dwpf"] = "";
       $mydata[$key]["relh"] = "";
    }
    if ($mydata[$key]["tmpf"] > 120){ 
       $mydata[$key]["feel"] = "";
       $mydata[$key]["dwpf"] = "";
       $mydata[$key]["relh"] = "";
       $mydata[$key]["tmpf"] = "";
    }
    if ($mydata[$key]["vsby"] < 0){ $mydata[$key]["vsby"] = -1; }
     $mydata[$key]["peak_ts"] = 0;
    if ($mydata[$key]["max_gust"] > $mydata[$key]["max_sknt"]){
      $mydata[$key]["peak"] = $mydata[$key]["max_gust"];
      $mydata[$key]["peak_ts"] = strtotime(substr( $mydata[$key]["max_gust_ts"],0,16) );
    } else {
      $mydata[$key]["peak"] = $mydata[$key]["max_sknt"];
     if ($mydata[$key]["max_sknt_ts"] > 0) {
      $mydata[$key]["peak_ts"] = strtotime(substr( $mydata[$key]["max_sknt_ts"],0,16) );
    }
  }

  }


$finalA = Array();
$finalA = aSortBySecondIndex($mydata, $sortcol);
$i = 0;
$now = time();
$skippedStations = Array();

  // Loop though all data 
  while (list ($key, $val) = each ($finalA))  {
    $parts = $finalA[$key];
    $tdiff = $now - $parts["ts"];

     // Dont show IAC
    if ($key == "RIOW"){
      continue;
    }
    if ($tdiff > 6900){
      $skippedStations[$key] = $parts;
      continue;
    }

    $i++;

	  echo "<tr";
	  if ($i % 2 == 0)  echo " bgcolor='#eeeeee'";  
            
          echo ">";
   echo "<td><input type=\"checkbox\" name=\"st[]\" 
               value=\"".$key."\"></td>";
  echo "<td>". $parts["sname"] . "</td><td ";
  if ($tdiff > 11900){
    echo 'bgcolor="red"';
    $format = "%b-%d-%y %I:%M %p";
  } else if ($tdiff > 6900){
    echo 'bgcolor="orange"';
    $format = "%I:%M %p";
  } else if ($tdiff > 1800){
    echo 'bgcolor="green"';
    $format = "%I:%M %p";
  } else {
    $format = "%I:%M %p";
  }
  echo ">". strftime($format, $parts["ts"]) ."</td>
  <td align='center'>". round($parts["tmpf"],0) ."(<font color=\"#ff0000\">".
  round($parts["max_tmpf"],0) ."</font>/<font color=\"#0000ff\">".
  round($parts["min_tmpf"],0) ."</font>)</td>
 <td>". round($parts["dwpf"],0) ."</td>
 <td>". round($parts["feel"],0) ."</td>
 <td>". $parts["relh"] ."</td>
 <td>". round($parts["vsby"],1) ."</td>
 <td>". round($parts["sknt"],0) ;
  if (strlen($parts["gust"]) > 0 && $parts["gust"] > 0){
              echo "G". round($parts["gust"],0);
  } 
  echo "</td>
            <td>". $parts["drct"] ."</td>
	    <td>". round($parts["peak"],0) ."@ ". strftime("%I:%M %p", $parts["peak_ts"] ) ."</td>
            <td>". round($parts["pday"],2) ."</td>
	    </tr>\n";
   }




while (list ($key, $val) = each ($skippedStations) ) {
  $parts = $finalA[$key];
  $i++;

	  echo "<tr";
	  if ($i % 2 == 0)  echo " bgcolor='#eeeeee'";  
            
          echo ">";
   echo "<td><input type=\"checkbox\" name=\"st[]\" 
               value=\"".$key."\"></td>";
  echo "<td>". $parts["sname"] . "</td><td ";
  echo 'bgcolor="red"';
  $format = "%b-%d-%y";
  echo ">". strftime($format, $parts["ts"]) ."</td><th align='center' colspan='9'>Site Offline</th></tr>\n";
}

?>
</tbody>
<tfoot>
<tr>
 <td colspan=3>&nbsp;</td>
<?php $c = "javascript:new_window('http://mesonet.agron.iastate.edu/GIS/apps/php/currents.phtml?layers[]=radar&layers[]=labels&network=".$network."&var="; ?>
 <td><a href="<?php echo $c; ?>tmpf');">Plot</a>
    (<a href="<?php echo $c; ?>max_tmpf');">Plot</a> /
     <a href="<?php echo $c; ?>min_tmpf');">Plot</a>)</td>
 <td><a href="<?php echo $c; ?>dwpf');">Plot</a></td>
 <td><a href="<?php echo $c; ?>feel');">Plot</a></td>
 <td><a href="<?php echo $c; ?>vsby');">Plot</a></td>
 <td><a href="<?php echo $c; ?>relh');">Plot</a></td>
 <td colspan=2><a href="<?php echo $c; ?>barb');">Plot</a></td>
 <td><a href="<?php echo $c; ?>max_sknt');">Plot</a></td>
 <td><a href="<?php echo $c; ?>pday');">Plot</a></td>

</tr></tfoot>
</table>
<input type="submit" value="Add to Favorites">
<input type="reset" value="Reset">

</form>

<br><br>

<b>Notes:</b><br>
<b>1</b> Not all sites have the ability to measure precip nor visibility.<br>
<b>2</b> The Iowa City (I-80) RWIS site does not have atmospheric sensors on it
, so it is not included on this page.<br>



<?php include("$rootpath/include/footer.php"); ?>
