<?php 
require_once "../../config/settings.inc.php";
require_once "../../include/myview.php";
require_once "../../include/cameras.inc.php";
require_once "../../include/forms.php";
$camid = isset($_GET["camid"]) ? xssafe($_GET["camid"]) : "IDOT-000";

$cdict = Array();
$selectform = "<select name=\"camid\">\n";
foreach($cameras as $id => $cam){
  if ($cam["network"] != "IDOT"){ continue; }
  $base = substr($id,0,8);
  if (! array_key_exists($base, $cdict)){ $cdict[$base] = 0; }
  $cdict[$base] += 1;

  if (substr($id,9,2) == "00"){
    $selectform .= "<option value=\"$base\"";
    if ($base == $camid){  $selectform .= " selected=\"selected\" "; }
    $selectform .= ">". $cam["name"] ."</option>";
  }
}
$selectform .= "</select>\n";

$t = new MyView();
$t->title = "Iowa DOT RWIS Data";

$camimgs = "";
for($i=0;$i<$cdict[$camid];$i++){
	$camimgs .= sprintf("<div class=\"col-md-3\"><img src=\"/data/camera/stills/%s-%02d.jpg?%s\" class=\"img img-responsive\"></div>", 
			$camid, $i, time() );
}

$t->content = <<<EOF
<h3>Roadway Weather Information System</h3><p>

<div class="row">
<div class="col-md-8">

The Iowa Department of Transportation maintains a set 
of observing stations located along major roads in the state.  These stations
measure pavement temperatures as well as atmospherics.  The DOT has a good
website called <a href="http://weatherview.iowadot.gov">WeatherView</a>, which contains recent obs and a 
wealth of other information.  The products on this page are intended to 
supplement their site.
</div>

<div class="col-md-4">
<b>RWIS Network</b>
<br>About 6 obs per hour
<br>Stations: 62
<br><a href="/sites/locate.php?network=IA_RWIS">Locations</a>
</div>

</div><!-- ./row -->

<h4>Roadside Webcams <a href="camera.phtml" class="btn btn-default">Webcam Archive Viewer</a></h4>

<form method="" action="" name="widget">
Available sites: {$selectform}
<input type="submit" value="View Webcam">
</form>

<div class="row">
{$camimgs}
</div>


<div class="row">
<div class="col-md-4">
		

  <h3>Current Conditions</h3>
<ul>
    <li><a href="current.phtml">Atmospherics</a></li>
    <li><a href="currentSF.phtml">Pavement</a></li>
    <li><a href="soil.phtml">Soil Probes</a></li>
    <li><a href="traffic.phtml">Traffic Data</a></li>
    <li><a href="/GIS/apps/iem/freeze.phtml">IEM Freeze</a>
	<br /><dd>Combine air and pavement temperatures with current
  	RADAR.</dd></li>
</ul>

  <h3>Time Series Plots:</h3>
<ul>
   <li><a href="/plotting/rwis/sf_fe.php">Recent Air/Pavement Temps</a></li>
</ul>

  <h3 class="subtitle">Plots with RWIS data</h3>
<ul>
   <li><a href="/data/mesonet.gif">Combined Mesonet</a></li>
   <li><a href="/data/iowa_rwis.png">RWIS Mesonet</a></li>
   <li><a href="/data/rwis_sf.png">Pavement Temperatures</a></li>
   <li><a href="/data/heat.gif">Heat Index</a></li>
   <li><a href="/data/wcht.gif">Wind Chill Index</a></li>
   <li><a href="/data/rwis.txt">Current RWIS Raw Text File</a></li>
</ul>


</div>
<div class="col-md-4">

<h3>Station Plot with NEXRAD</h3>
<ul>
   <li><a href="/data/DMX_radar.gif">Des Moines</a></li>
   <li><a href="/data/OAX_radar.gif">Omaha</a></li>
   <li><a href="/data/DVN_radar.gif">Davenport</a></li>
   <li><a href="/data/FSD_radar.gif">Sioux Falls</a></li>
   <li><a href="/data/ARX_radar.gif">LaCrosse</a></li>
</ul>
</div>

<div class="col-md-4">

  <h3>Data Download</h3>
<ul>
 <li><a href="/request/rwis/fe.phtml">Atmosphere &amp; Pavement Data</a></li>
 <li><a href="/request/rwis/soil.phtml">Soil Probe Data</a></li>
 <li><a href="/request/rwis/traffic.phtml">Traffic Data</a></li>
</ul>



  <h3>Comparisons:</h3>
<ul>
   <li><a href="/data/temps.gif">Temperatures vs ASOS/AWOS</a></li>
   <li><a href="/data/dewps.gif">Dew Points vs ASOS/AWOS</a></li>
   <li><a href="/data/winds.gif">Winds vs ASOS/AWOS</a></li>
   <li><a href="/plotting/compare/">Plot Recent Comparisions</a></li>
</ul>

  <h3>QC Info:</h3>
<ul>
  <li>Sites <a href="/QC/offline.php">offline</a></li>
</ul>
</p>

</div>
</div><!-- ./row -->

EOF;

$t->render("single.phtml");
