<?php
include("../../config/settings.inc.php");
include("$rootpath/include/database.inc.php");
$dbconn = iemdb("iem");
$sortcol = isset($_GET['sortcol']) ? $_GET['sortcol'] : 'valid';

/* Query out the data */
$rs = pg_prepare($dbconn, "SELECT", "select t.valid, s.name as sname,
     max(case when sensor_id = 0 then temp else null end) as s0,
     max(case when sensor_id = 1 then temp else null end) as s1,
     max(case when sensor_id = 2 then temp else null end) as s2,
     max(case when sensor_id = 3 then temp else null end) as s3,
     max(case when sensor_id = 4 then temp else null end) as s4,
     max(case when sensor_id = 5 then temp else null end) as s5,
     max(case when sensor_id = 6 then temp else null end) as s6,
     max(case when sensor_id = 7 then temp else null end) as s7,
     max(case when sensor_id = 8 then temp else null end) as s8,
     max(case when sensor_id = 9 then temp else null end) as s9,
     max(case when sensor_id = 10 then temp else null end) as s10,
     max(case when sensor_id = 11 then temp else null end) as s11,
     max(case when sensor_id = 12 then temp else null end) as s12,
     max(case when sensor_id = 13 then temp else null end) as s13,
     max(case when sensor_id = 14 then temp else null end) as s14
      from rwis_soil_data t, stations s
      where s.remote_id = t.location_id GROUP by sname, valid ORDER by $sortcol DESC");
$rs = pg_execute($dbconn, "SELECT", Array());

 $TITLE = "IEM | RWIS | Current Soil Probe Data";
 $REFRESH = "<meta http-equiv=\"refresh\" content=\"600;
 URL=soil.phtml?sortcol=$sortcol\">";
 $THISPAGE = "current-sort";
 include("$rootpath/include/header.php"); 

 $current_network = "RWIS Soil"; 
 include("$rootpath/include/current_bar.inc.php"); 
?>
<h3 class="subtitle">Iowa RWIS Soil Probe Data</h3>

<p>** This page will automatically refresh every 10 minutes.
<br>Click on a column to sort it.</p>

<?php
function fancytime($strtime){
  $now = time();
  $ts = strtotime($strtime);
  if (($now - $ts) < 600){ return date("h:i A", $ts); }
  else { return date("M d h:i A", $ts); }
}
$vals = Array(
 "sname" => "Station Name",
 "valid" => "Observation Time",
 "s0" => "1 inch Depth Temperature",
 "s1" => "3 inch Depth Temperature",
 "s2" => "6 inch Depth Temperature",
 "s3" => "9 inch Depth Temperature",
 "s4" => "12 inch Depth Temperature",
 "s5" => "18 inch Depth Temperature",
 "s6" => "24 inch Depth Temperature",
 "s7" => "30 inch Depth Temperature",
 "s8" => "36 inch Depth Temperature",
 "s9" => "42 inch Depth Temperature",
 "s10" => "48 inch Depth Temperature",
 "s11" => "54 inch Depth Temperature",
 "s12" => "60 inch Depth Temperature",
 "s13" => "66 inch Depth Temperature",
 "s14" => "72 inch Depth Temperature",
);

echo "<p>Sorted by: <b>". $vals[$sortcol] ."</b><br>\n";
?>
<table style="width: 100%; font-size: 10pt;" cellpadding="1" cellspacing="0"
  border="1">
<thead>
<tr>
  <th rowspan="2"><a href="soil.phtml?sortcol=sname">Station:</a></th>
  <th rowspan="2"><a href="soil.phtml?sortcol=valid">Ob Time</a></th>
  <th colspan="15">Soil Problems Located at Specified Depth</th>
</tr>
<tr>
  <th><a href="soil.phtml?sortcol=s0">1</a></th>
  <th><a href="soil.phtml?sortcol=s1">3</a></th>
  <th><a href="soil.phtml?sortcol=s2">6</a></th>
  <th><a href="soil.phtml?sortcol=s3">9</a></th>
  <th><a href="soil.phtml?sortcol=s4">12</a></th>
  <th><a href="soil.phtml?sortcol=s5">18</a></th>
  <th><a href="soil.phtml?sortcol=s6">24</a></th>
  <th><a href="soil.phtml?sortcol=s7">30</a></th>
  <th><a href="soil.phtml?sortcol=s8">36</a></th>
  <th><a href="soil.phtml?sortcol=s9">42</a></th>
  <th><a href="soil.phtml?sortcol=s10">48</a></th>
  <th><a href="soil.phtml?sortcol=s11">54</a></th>
  <th><a href="soil.phtml?sortcol=s12">60</a></th>
  <th><a href="soil.phtml?sortcol=s13">66</a></th>
  <th><a href="soil.phtml?sortcol=s14">72</a></th>
</tr>
</thead>
<tbody>
<?php
$data = Array();

for($i=0;$row=@pg_fetch_array($rs,$i);$i++){
   echo sprintf("<tr><th>%s</th><th>%s</th>
   <td>%.1f</td><td>%.1f</td><td>%.1f</td><td>%.1f</td>
   <td>%.1f</td><td>%.1f</td><td>%.1f</td><td>%.1f</td><td>%.1f</td>
   <td>%.1f</td><td>%.1f</td><td>%.1f</td><td>%.1f</td><td>%.1f</td>
   <td>%.1f</td></tr>\n", 
   $row["sname"], fancytime($row["valid"]),
   $row["s0"], $row["s1"],$row["s2"],$row["s3"],$row["s4"],$row["s5"],
   $row["s6"],$row["s7"],$row["s8"],$row["s9"],$row["s10"],$row["s11"],
   $row["s12"],$row["s13"], $row["s14"]);
}
?>
</tbody>
</table>

</form>

<br><br>


<?php include("$rootpath/include/footer.php"); ?>
