<?php
 include("../../config/settings.inc.php");
 define("IEM_APPID", 7);
 $network = isset($_GET['network']) ? substr($_GET["network"],0,7) : 'IA_ASOS';
 $metar = isset($_GET['metar']) ? $_GET["metar"] : "no";
 $sortcol = isset($_GET['sortcol'])  ? $_GET['sortcol']: "ts";
 $sorder = isset($_GET['sorder']) ? $_GET['sorder']: "desc";
 $format = isset($_REQUEST["format"]) ? $_REQUEST['format'] : 'html';
 if ($format == 'jsonp'){
 	header("Location: ../geojson/network_obs.php?network=$network&callback=mycallback");
 	die();
 }
 
  $TITLE = "IEM | ASOS | Current Conditions";
  $REFRESH = "<meta http-equiv=\"refresh\" content=\"1200;\">";
  $HEADEXTRA = '<script language="JavaScript" type="text/javascript">
<!--//BEGIN Script
function new_window(url) {
 link = window.open(url,"_new","toolbar=0,location=0,directories=0,status=0,menubar=no,scrollbars=yes,resizable=yes,width=800,height=600");
} 
//END Script-->
</script>
';
 $THISPAGE = "current-sort";

  include("$rootpath/include/mlib.php"); 
  include("$rootpath/include/network.php");
  $nt = new NetworkTable($network);
  $cities = $nt->table;
  include("$rootpath/include/iemaccess.php");
  include("$rootpath/include/iemaccessob.php");
  include_once "$rootpath/include/database.inc.php";
  $mesosite = iemdb('mesosite');
  pg_prepare($mesosite, "FINDTZ", "SELECT tzname from networks where id = $1");
  $rs = pg_execute($mesosite, "FINDTZ", Array($network));
  $row = pg_fetch_assoc($rs,0);
  $tzname = $row["tzname"];

$vals = Array("tmpf" => "Air Temperature [F]", "dwpf" => "Dew Point Temp [F]",
  "sknt" => "Wind Speed [knots]", "drct" => "Wind Direction [deg]",
  "alti" => "Altimeter [mb]", "peak" => "Today's Wind Gust [knots]",
  "peak_ts" => "Time of Peak Gust", "relh" => "Relative Humidity",
  "feel" => "Feels Like [F]", "vsby" => "Visibility [miles]",
  "ts" => "Observation Time", "phour" => "Last Hour Rainfall [inch]",
  "min_tmpf" => "Today's Low Temperature", "sname" => "Station Name",
  "max_tmpf" => "Today's High Temperature",
  "skyl1" => "Cloud Level 1",
  "skyl2" => "Cloud Level 2",
  "skyl3" => "Cloud Level 3",
  "skyl4" => "Cloud Level 4",
  "pday" => "Today Rainfall [inch]", );

function aSortBySecondIndex($multiArray, $secondIndex, $sorder) {
  while (list($firstIndex, ) = each($multiArray))
       $indexMap[$firstIndex] = $multiArray[$firstIndex][$secondIndex];
  if ($sorder == "asc")
        asort($indexMap);
  else 
        arsort($indexMap);
  while (list($firstIndex, ) = each($indexMap))
      if (is_numeric($firstIndex))
                 $sortedArray[] = $multiArray[$firstIndex];
      else $sortedArray[$firstIndex] = $multiArray[$firstIndex];
  return $sortedArray;
}

$iem = new IEMAccess($tzname);
$asos = $iem->getNetwork($network);

/* Final data array */
$mydata = Array();

while ( list($key, $iemob) = each($asos) ){
    $mydata[$key] = $iemob->db;
    $mydata[$key]["ts"] = $iemob->lts;
    $mydata[$key]["sname"] = $cities[$key]["name"];
    $mydata[$key]["sped"] = $mydata[$key]["sknt"] * 1.15078;
    $mydata[$key]["relh"] = relh(f2c($mydata[$key]["tmpf"]), 
       f2c($mydata[$key]["dwpf"]) );
    if ($mydata[$key]["tmpf"] > -99 && $mydata[$key]["dwpf"] > -99){
       $mydata[$key]["feel"] = feels_like($mydata[$key]["tmpf"], 
         $mydata[$key]["relh"], $mydata[$key]["sped"]);
    } else {
    	$mydata[$key]["feel"] = null;
    }
    if ($mydata[$key]["max_gust"] > $mydata[$key]["max_sknt"]){
      $mydata[$key]["peak"] = $mydata[$key]["max_gust"];
      $mydata[$key]["peak_ts"] = strtotime(substr( $mydata[$key]["lmax_gust_ts"],0,16) );
    } else {
      $mydata[$key]["peak"] = $mydata[$key]["max_sknt"];
      if ($mydata[$key]["max_sknt_ts"] > 0) {
         $mydata[$key]["peak_ts"] = strtotime(substr( $mydata[$key]["lmax_sknt_ts"],0,16) );
      }
    }

} // End of while

if($format == 'csv'){
	$csv = "station,valid_gmt,tmpf,dwpf,sknt,drct,relh,vsby,phour_in,pday_in,metar\n";
	while (list ($key, $val) = each ($mydata))  {
		$data = $mydata[$key];
		$csv .= sprintf("%s,%s,%.0f,%.0f,%.0f,%.0f,%.1f,%s,%.2f,%.2f,%s\n", $key, gmstrftime("%Y-%m-%d %H:%M", $data['ts']),
			$data['tmpf'], $data['dwpf'], $data['sknt'], $data['drct'], $data['relh'], 
			$data['vsby'], $data['phour'],
			$data['pday'], $data['raw']);
	}
	header("Content-type: text/plain");
	echo $csv;
	die();
}



/* Begin HTML output! */
  include("$rootpath/include/header.php"); 
  $current_network = "ASOS"; include("$rootpath/include/current_bar.inc.php"); ?>

<table border=1 cellspacing=0 cellpadding=1>
<tr>
  <td>
<form method="GET" action="current.phtml">
<input type="hidden" name="sortcol" value="<?php echo $sortcol; ?>">
Select Network: 
<select name="network">
<?php 
$rs = pg_query($mesosite, "SELECT id, name from networks where id ~* 'ASOS' ORDER by name ASC");
for ($i=0;$row=@pg_fetch_assoc($rs,$i);$i++){
	$sel = '';
	if ($network == $row["id"]){
		$sel = " selected='SELECTED'";
	}
	echo sprintf("<option value='%s'%s>%s</option>\n",
	  $row["id"], $sel, $row["name"]);
}

?>
</select></td>
  <td>Include METARS:<br />
  <input value="no" type="radio" name="metar" <?php if ($metar == "no") echo  "CHECKED"; ?>> No
  <input value="yes" type="radio" name="metar" <?php if ($metar == "yes") echo  "CHECKED"; ?>> Yes
</td>
<td>Sort Order:
<select name="sorder">
  <option value="asc" <?php if ($sorder == "asc") echo "SELECTED"; ?>>Ascending
  <option value="desc" <?php if ($sorder == "desc") echo "SELECTED"; ?>>Decending
</select></td>
<td>Format:
<select name="format">
  <option value="html" <?php if ($format == "html") echo "SELECTED"; ?>>Web Page
  <option value="csv" <?php if ($format == "csv") echo "SELECTED"; ?>>Comma Delimited
  <option value="jsonp" <?php if ($format == "jsonp") echo "SELECTED"; ?>>Geo-JSON-P
</select></td>
<td><input type="submit" value="Go!"></form></td>
</tr></table>




<?php
echo "<br /><strong>Times shown are for timezone: ${tzname}.</strong> The local day summary
is based on that timezone. <br />Table sorted by: <b>(". $vals[$sortcol] .")</b>  &nbsp; &nbsp; Click on
a column to sort it. Click on site ID for more information. You can download data from 
this network <a href='../request/download.phtml?network=${network}'>here</a>.<br />\n";
?>

<form method="GET" action="<?php echo $rooturl; ?>/my/current.phtml">


<?php $uri = "current.phtml?sorder=$sorder&metar=$metar&network=$network&sortcol="; ?>

<table style="width: 100%; font-size: 10pt;" cellspacing=0 cellpadding=1 border=1>
<thead>
<tr>
  <th rowspan="2">ADD:</th>
  <th rowspan="2"><a href="<?php echo $uri; ?>sname">Station</a></th>
  <th rowspan="2"><a href="<?php echo $uri; ?>ts">Ob Time</a></th>
  <th colspan="5">Temps &deg;F</th>
  <th colspan="3">&nbsp;</th>
  <th colspan="3">Wind [knots]</th>
  <th colspan="2">Precip</font></th>
  <th colspan="4">Clouds</font></th>
<tr>
  <th><a href="<?php echo $uri; ?>tmpf">Air</a></th>
  <th><a href="<?php echo $uri; ?>max_tmpf">Hi</a></th>
  <th><a href="<?php echo $uri; ?>min_tmpf">Lo</a></th>
  <th><a href="<?php echo $uri; ?>dwpf">Dewp</a></th>
  <th><a href="<?php echo $uri; ?>feel">Feels</a></th>
  <th><a href="<?php echo $uri; ?>relh">RH %</a></th>
  <th><a href="<?php echo $uri; ?>alti">Alti</a></th>
  <th><a href="<?php echo $uri; ?>vsby">Vsby</a></th>
  <th><a href="<?php echo $uri; ?>sknt">Speed</a></th>
  <th><a href="<?php echo $uri; ?>drct">Drct</a></th>
  <th><a href="<?php echo $uri; ?>peak">Gust</a>
    @ <a href="<?php echo $uri; ?>peak_ts">Time</a></th>
  <th><a href="<?php echo $uri; ?>phour">1 Hour</a></th>
  <th><a href="<?php echo $uri; ?>pday">Today</a></th>
  <th><a href="<?php echo $uri; ?>skyl1">Level 1</a></th>
  <th><a href="<?php echo $uri; ?>skyl2">Level 2</a></th>
  <th><a href="<?php echo $uri; ?>skyl3">Level 3</a></th>
  <th><a href="<?php echo $uri; ?>skyl4">Level 4</a></th>
</tr></thead>
<tbody>
<?php

$finalA = aSortBySecondIndex($mydata, $sortcol, $sorder);
$now = time();
$i = 0;
$old = "";
while (list ($key, $val) = each ($finalA))  {
  $i++;
  $parts = $finalA[$key];

  $row = "<tr";
  if ($i % 2 == 0)  $row .= " bgcolor='#eeeeee'";  
  $row .= "><td><input type=\"checkbox\" name=\"st[]\" value=\"".$key."\"></td>";

  $tdiff = $now - $asos[$key]->ts;
  $url = sprintf("%s/sites/site.php?station=%s&network=%s", $rooturl,
         $key, $network);
  $row .= "<td>". $cities[$key]["name"] . " (<a href=\"$url\">${key}</a>)</td>";
  $row .= "<td ";
  if ($tdiff > 10000){
    $fmt = "%d %b %I:%M %p";
    $row .= "bgcolor=\"red\">". strftime($fmt, $asos[$key]->lts) ."</td><td colspan=\"16\">Site Offline</td></tr>";
    $old .= $row;
    continue;
  } else if ($tdiff > 7200){
    $fmt = "%I:%M %p";
    $row .= 'bgcolor="orange"';
  } else if ($tdiff > 3600){
    $fmt = "%I:%M %p";
    $row .= 'bgcolor="green"';
  } else {
    $fmt = "%I:%M %p";
  }
  $row .= ">". strftime($fmt, $asos[$key]->lts) ."</td>
   <td align='center'>". round($parts["tmpf"],0) ."</td><td><font color=\"#ff0000\">". round($parts["max_tmpf"],0) ."</font></td><td><font color=\"#0000ff\">". round($parts["min_tmpf"],0) ."</font></td>
     <td>". round($parts["dwpf"],0) ."</td>
     <td>". round($parts["feel"],0) ."</td>
	    <td>". $parts["relh"] ."</td>
	    <td>". $parts["alti"] ."</td>
	    <td>". $parts["vsby"] ."</td>
             <td>". round($parts["sknt"],0) ;

   if (floatval($parts["gust"] > 0)){
      $row .= "G". round($parts["gust"],0);
   } $row .= "</td>";
   $row .= "<td>". drct2txt( $parts["drct"] ) ."</td><td>";
  if (isset($parts["peak_ts"])) $row .=  $parts["peak"] ." @ ". strftime("%I:%M %p", $parts["peak_ts"]) ;
  $row .= "</td><td>". $parts["phour"] ."</td>
            <td>". $parts["pday"] ."</td>
<td>". $parts["skyc1"] ." ". $parts["skyl1"] ."</td>
<td>". $parts["skyc2"] ." ". $parts["skyl2"] ."</td>
<td>". $parts["skyc3"] ." ". $parts["skyl3"] ."</td>
<td>". $parts["skyc4"] ." ". $parts["skyl4"] ."</td>
	    </tr>\n";
  if ($metar == "yes") {
    $row .= "<tr";
    if ($i % 2 == 0)  $row .= " bgcolor='#eeeeee'";
    $row .= ">";
    $row .= "<td colspan=\"20\">
             <font color=\"brown\">". $parts["raw"] ."</font></td>
             </tr>\n";
   }
  echo $row;
 }
echo $old;


 $uri = "javascript:new_window('$rooturl/GIS/apps/php/currents.phtml?layers[]=radar&layers[]=labels&network=$network";
?>
</tbody>
<tfoot>
<tr>
 <td colspan="3">&nbsp;</td>
 <td><a href="<?php echo $uri; ?>&var=tmpf');">Plot</a></td>
 <td><a href="<?php echo $uri; ?>&var=max_tmpf');">Plot</a></td>
 <td><a href="<?php echo $uri; ?>&var=min_tmpf');">Plot</a></td>
 <td><a href="<?php echo $uri; ?>&var=dwpf');">Plot</a></td>
 <td><a href="<?php echo $uri; ?>&var=feel');">Plot</a></td>
 <td><a href="<?php echo $uri; ?>&var=relh');">Plot</a></td>
 <td><a href="<?php echo $uri; ?>&var=alti');">Plot</a></td>
 <td><a href="<?php echo $uri; ?>&var=vsby');">Plot</a></td>
 <td><a href="<?php echo $uri; ?>&var=sknt');">Plot</a></td>
 <td>&nbsp;</td>
 <td><a href="<?php echo $uri; ?>&var=max_gust');">Plot</a></td>
 <td><a href="<?php echo $uri; ?>&var=phour');">Plot</a></td>
 <td><a href="<?php echo $uri; ?>&var=pday');">Plot</a></td>
 <td></td>
 <td></td>
 <td></td>
 <td></td>
</tr></tfoot>
</table>

<input type="submit" value="Add to Favorites">
<input type="reset" value="Reset">

</form>


<?php include("$rootpath/include/footer.php"); ?>
