<?php 
 include("../../config/settings.inc.php");
  $THISPAGE = 'networks-asos'; 
  $TITLE = "IEM | ASOS Data";
include("$rootpath/include/header.php"); 
?>

<h3 class="heading">ASOS Network</h3><p>

<div class="text">
<table><tr><td style="width: 650px;" valign="top">
The Automated Surface Observing System (ASOS) is considered
to be the flagship automated observing network.  Located at airports, the ASOS
stations provide essential observations for the National Weather Service (NWS), the Federal Aviation Administration (FAA), and the Department of Defense (DOD).
The primary function of the ASOS stations are to take minute-by-minute 
observations and generate basic weather reports.<font class="ref">[1]</font></td><td>

<div class="ninfo">
<b><u>ASOS</u></b>
<br>Reports: Hourly
<br>Stations: 15
<br><a href="/info/network.phtml?network=IA_ASOS">Locations</a>
</div></td></tr></table>

<p class="intro">Observations from the ASOS network are nationally monitored 
for quality 24 hours per day.  Depending on the trouble, maintenance can
be performed on the same day.</p>

<table width="100%">
<tr><td width="50%" valign="top">

<P><h3 class="subtitle">Current ASOS Data:</h3>
<UL>
 <li><a href="current.phtml">Sortable Current Conditions</a></li>
 <li><a href="/data/mesonet.gif">Combined Mesonet</a></li>
 <li><a href="/data/asos.gif">ASOS Mesonet</a><a href="/help/imageHelp.php?iod=5"> <img alt="info" src="/images/ihelp.png" border="0"></a></li>
 <li><a href="/data/wcht.gif">Wind Chill Index</a></li>
 <li><a href="/data/relh.gif">Relative Humidity</a></li>
 <li><a href="../plotting/hr/1station.php">Plot Recent Timeseries</a></li>
</UL>


<P><h3 class="subtitle">1 Minute Archive:</h3>
The National Climatic Data Center collects a 1 minute interval archive
from the ASOS network.  This archive is available <a href="http://www.ncdc.noaa.gov/oa/climate/climatedata.html#asosminutedata">here</a>, but in a terrible
format!  The IEM has done its best to process this data and will make it 
available here for Iowa sites.
<ul>
 <li><a href="<?php echo $rooturl; ?>/request/asos/1min.phtml">Download</a> these observations</li>
 <li><a href="<?php echo $rooturl; ?>/plotting/asos/1station_1min.phtml">Daily graphs</a> of temperature, wind, and pressure</li>
</ul>
<br />Data is available for Des Moines, Waterloo, Dubuque, and Sioux City back to 2000.  The rest of the sites since March 2005.

<p><h3 class="subtitle">Quality Control:</h3>
<ul>
 <li><a href="/QC/madis/network.phtml?network=IA_ASOS">MADIS Raw QC Values</a></li>
</ul>

</td><td valign="top" width="50%">

<p><h3 class="subtitle">Historical Data:</h3>
<ul>
 <li><a href="/request/download.phtml">Download</a> data from the archive</li>
<li><a href="/cgi-bin/precip/catAZOS.py">Hourly Precipitation</a> tables</li>
<li><a href="/data/text/IEMAZOMPR.txt">This Month's Rainfall Totals</a></li>
<li><a href="reports/2003precip.phtml">2003 Rainfall Totals</a></li>
<li><a href="reports/2004precip.phtml">2004 Rainfall Totals</a></li>
<li><a href="reports/2005precip.phtml">2005 Rainfall Totals</a></li>
<li><a href="reports/2006precip.phtml">2006 Rainfall Totals</a></li>
<li><a href="reports/2007precip.phtml">2007 Rainfall Totals</a></li>
<li><a href="reports/2008precip.phtml">2008 Rainfall Totals</a></li>
<li><a href="reports/2009precip.phtml">2009 Rainfall Totals</a></li>
</ul>


<p><h3 class="subtitle">Comparisons:</h3>
(<i>The RUC2 is an operational forecast model run by the Weather Service.</i>)<br>
<ul>
 <li><a href="/plotting/compare/">Generate Interactive Comparisons</a> between two sites of your choice.</li>
  <li><a href="/wx/data/models/ruc2_iem_T.gif">Temperatures vs RUC2 Model</a></li>
  <li><a href="/data/temps.gif">Temperatures vs RWIS Network</a></li>
  <li><a href="/data/snet/Tcompare.gif">Temperatures vs SchoolNet Network</a></li>
  <li><a href="/wx/data/models/ruc2_iem_Td.gif">Dew Points vs RUC2 Model</a></li>
  <li><a href="/data/dewps.gif">Dew Points vs RWIS Network</a></li>
  <li><a href="/data/snet/Dcompare.gif">Dew Points vs SchoolNet Network</a></li>
  <li><a href="/wx/data/models/ruc2_iem_V.gif">Winds vs RUC2 Model</a></li>
  <li><a href="/data/winds.gif">Winds vs RWIS Network</a></li>
  <li><a href="/wx/data/models/ruc2_iem_Rh.gif">Relative Humidity vs RUC2 Model</a></li>
  <li><a href="/data/snet/Pcompare.gif">Pressure vs SchoolNet Network (mb)</a></li>
  <li><a href="/data/snet/P2compare.gif">Pressure vs SchoolNet Network (in)</a></li>
</ul>

</td></tr></table>

<p><b>References:</b><br>
<b>1</b> Adapted from the ASOS User's Guide, March 1998

<br><br></div>

<?php include("$rootpath/include/footer.php"); ?>
