<?php 
 require_once "../../config/settings.inc.php";
 define("IEM_APPID", 21);
 require_once '../../include/myview.php';

$t = new MyView();
$t->title = "ASOS/AWOS Network";

$t->content = <<< EOM
<h3>ASOS Network</h3><p>

<div class="well pull-right">
<b><u>ASOS</u></b>
<br>Reports: Hourly
<br>Stations: 15
<br><a href="/sites/locate.php?network=IA_ASOS">Locations</a>
</div>
		
The Automated Surface Observing System (ASOS) is considered
to be the flagship automated observing network.  Located at airports, the ASOS
stations provide essential observations for the National Weather Service (NWS), the Federal Aviation Administration (FAA), and the Department of Defense (DOD).
The primary function of the ASOS stations are to take minute-by-minute 
observations and generate basic weather reports.<font class="ref">[1]</font>

		
<p class="intro">Observations from the ASOS network are nationally monitored 
for quality 24 hours per day.  Depending on the trouble, maintenance can
be performed on the same day.</p>

<div class="row">
<div class="col-md-6">

<P><h3>Current ASOS Data:</h3>
<ul>
 <li><a href="current.phtml">Sortable Current Conditions</a></li>
 <li><a href="/data/mesonet.gif">Combined Mesonet</a></li>
 <li><a href="/data/asos.gif">ASOS Mesonet</a></li>
 <li><a href="/data/wcht.gif">Wind Chill Index</a></li>
	<li><a href="recent.phtml">Recent Interesting METAR Reports</a></li>
	<li><a href="/data/relh.gif">Relative Humidity</a></li>
</ul>


<h3>1 Minute Archive:</h3>

<p>The National Center for Environmental Information (NCEI) provides an archive
of one minute interval observations from many US ASOS sites back to the year 2000.
This archive is available 
<a href="https://www1.ncdc.noaa.gov/pub/data/asos-onemin/">here</a>, but in a terrible
format!  The IEM makes a best-guess effort at processing the mostly undocumented
data format and updates the archive daily.  This dataset is <strong>not realtime</strong>
and is delayed by 18-36 hours or more due to NCEI availability.</p> 

<ul>
 <li><a href="/request/asos/1min.phtml">Download</a> these observations</li>
 <li><a href="/plotting/asos/1station_1min.phtml">Daily graphs</a> of temperature, wind, and pressure</li>
</ul>
<br />Data is available for some sites back to 2000.  The rest of the sites since March 2005.

<p><h3>Quality Control:</h3>
<ul>
 <li><a href="/QC/madis/network.phtml?network=IA_ASOS">MADIS Raw QC Values</a></li>
 <li><a href="precipnote.phtml">Note about ASOS Precipitation Timing</a></li>
 </ul>

</div>
<div class="col-md-6">

<p><h3>Historical Data:</h3>
<ul>
 <li><a href="/request/download.phtml">Download</a> raw observations from the archive</li>
 <li><a href="/cgi-bin/precip/catAZOS.py">Hourly Precipitation</a> tables</li>
 <li><a href="/ASOS/reports/mon_prec.php">Monthly Precipitation</a> tables</li>
 <li><a href="/request/asos/hourlyprecip.phtml">Download</a> computed hourly precipitation totals</li>
 <li><a href="/request/daily.phtml">Download</a> computed daily summaries</li>
 <li><a href="/climodat/">IEM Climodat</a> has monthly/yearly summaries of 
		precipitation and temperature.</li>
</ul>


<p><h3 class="subtitle">Comparisons:</h3>
(<i>The RUC2 is an operational forecast model run by the Weather Service.</i>)<br>
<ul>
 <li><a href="/plotting/compare/">Generate Interactive Comparisons</a> between two sites of your choice.</li>
  <li><a href="/wx/data/models/ruc2_iem_T.gif">Temperatures vs RUC2 Model</a></li>
  <li><a href="/data/temps.gif">Temperatures vs RWIS Network</a></li>
  <li><a href="/data/snet/Tcompare.gif">Temperatures vs SchoolNet Network</a></li>
  <li><a href="/wx/data/models/ruc2_iem_Td.gif">Dew Points vs RUC2 Model</a></li>
  <li><a href="/data/dewps.gif">Dew Points vs RWIS Network</a></li>
  <li><a href="/data/snet/Dcompare.gif">Dew Points vs SchoolNet Network</a></li>
  <li><a href="/wx/data/models/ruc2_iem_V.gif">Winds vs RUC2 Model</a></li>
  <li><a href="/data/winds.gif">Winds vs RWIS Network</a></li>
  <li><a href="/wx/data/models/ruc2_iem_Rh.gif">Relative Humidity vs RUC2 Model</a></li>
  <li><a href="/data/snet/Pcompare.gif">Pressure vs SchoolNet Network (mb)</a></li>
  <li><a href="/data/snet/P2compare.gif">Pressure vs SchoolNet Network (in)</a></li>
</ul>

</div></div>

<p><b>References:</b><br>
<b>1</b> Adapted from the <a href="https://www.weather.gov/media/asos/aum-toc.pdf">ASOS User's Guide</a>

<ul>
<li><a href="http://www.nws.noaa.gov/asos/pdfs/AWPAG_stat.pdf">All Weather Precipitation Gauge</a> install dates.</li>
</ul>

<br><br>
EOM;
$t->render('single.phtml');
