<?php
require_once "../../config/settings.inc.php";
define("IEM_APPID", 104);
require_once "../../include/myview.php";
$t = new MyView();
$t->title = "Recent Interesting METAR Reports";

$t->content = <<<EOF
 <ol class="breadcrumb">
     <li><a href="/ASOS/">ASOS Mainpage</a></li>
    <li class="active">Recent Interesting METAR Reports</li>
 </ol>
<p>The IEM processes and archives a feed of METAR formatted weather observations.
     These observations sometimes contain interesting things reported.  This page
     lists out such recent occurences of a given phenomena. This page lists
     out reports for the past 2 to 3 days.</p>

 <form name="local">
 <p><strong>Select Report:</strong>
     <select id="report" name="report">
        <option value="snowdepth">Snow Depth Reports (4/xxx)</option>
        <option value="fc">Funnel Cloud / Tornado / Waterspouts Reports (FC/+FC)</option>
        <option value="gr">Hail Reports (GR)</option>
        <option value="i1">Ice Accretion 1 Hour (I1nnn)</option>
        <option value="i3">Ice Accretion 3 Hours (I3nnn)</option>
        <option value="i6">Ice Accretion 6 Hours (I6nnn)</option>
        <option value="pno">No Precipitation Reported (PNO)</option>
        <option value="50">Wind Sustained/Gusts AOA 50 kts (US Only)</option>
        <option value="50A">Wind Sustained/Gusts AOA 50 kts (Worldwide)</option>
     </select>
 </form></o>

 <p><table class="table table-bordered table-striped" id="datatable">
<thead class="sticky">
<tr><th>ID</th><th>Network</th><th>UTC Valid</th><th>Value</th><th>METAR</th></tr>
</thead>
 <tbody>
 </tbody>
 </table></p>

EOF;
$t->jsextra = <<<EOF
<script src="recent.js"></script>
EOF;

$t->render('single.phtml');
