<?php
 include("../../../config/settings.inc.php");

 $station = isset($_GET['station']) ? $_GET["station"]: "";
 $network = isset($_GET["network"]) ? $_GET['network'] : "IA_ASOS";
 $year = isset($_GET['year']) ? $_GET['year'] : date("Y");

$THISPAGE = "climatology-year";
include("$rootpath/include/database.inc.php");
include("$rootpath/include/google_keys.php");
include("$rootpath/include/imagemaps.php");
include("$rootpath/include/forms.php");
$api = $GOOGLEKEYS[$rooturl]["any"];
$HEADEXTRA = "<script src='http://maps.google.com/maps?file=api&amp;v=2&amp;key=$api'></script>
<script src='http://www.openlayers.org/api/OpenLayers.js'></script>
<script src='${rooturl}/js/olselect.php?network=${network}'></script>";
$BODYEXTRA = "onload=\"init()\"";

$TITLE = "IEM | Yearly Rainfall Traces";
include("$rootpath/include/header.php"); ?>
<style type="text/css">
        #map {
            width: 450px;
            height: 450px;
            border: 2px solid black;
        }
</style>

<h3 class="heading">Yearly Rainfall Traces</h3>

<div class="text">
<p>This application creates a plot of observed precipitation versus 
climatology for a site of your choice in Iowa. 

<?php if (strlen($station) > 0 ) { ?>
<form name="ds" action="rainfall.phtml" method="GET">
<input type="hidden" value="<?php echo $network; ?>" name="network">
<table cellspacing=2 border=1 cellpadding=2>
<tr><th>Site ID:</th><th>Select Year:</th></tr>
<tr><td><?php echo networkSelect($network,$station); ?>
<a href="rainfall.phtml?network=<?php echo $network; ?>">Select from map</a></td>
  <td><?php echo yearSelect(2004,$year,"year"); ?></td>
</table>
<input type="submit" value="Make Plot">
</form>

<CENTER>
<img src="rainfall_plot.php?<?php echo "station=$station&year=$year"; ?>" ALT="Time Series">
</CENTER>

<?php } else { ?>

<br /><a href="rainfall.phtml?network=IA_ASOS">Iowa ASOS</a> &nbsp; 
<a href="rainfall.phtml?network=AWOS">Iowa AWOS</a> &nbsp; 
<a href="rainfall.phtml?network=IA_COOP">Iowa NWS COOP</a> &nbsp; 
<a href="rainfall.phtml?network=KCCI">KCCI-TV SchoolNet</a> &nbsp; 

<form name="olselect">
<input type="hidden" value="<?php echo $network; ?>" name="network">
<table><tr><th>Select Station</th>
<td><?php echo networkSelect($network, ""); ?></td>
<td><input type="submit" value="Make Plot"></tr></table>
<div id="map"></div>
<div id="sname" unselectable="on">No site selected</div>
</form>

<?php } ?>
</div>

<?php include("$rootpath/include/footer.php"); ?>
