<?
include( "/mesonet/www/apps/chameleon/htdocs/chameleon.php" );
 
$szTemplate = "template.phtml";
$szMapFile = "base.map";
 
class SampleApp extends Chameleon
{
  function SampleApp()
  {
    parent::Chameleon();
    $this->moMapSession = new MapSession_RW;
    $this->moMapSession->setTempDir( getSessionSavePath());
  }
}
 
$oApp =  new SampleApp();
$oApp->registerSkin( 'skins/sample' );
$oApp->CWCInitialize( $szTemplate, $szMapFile  );
$oApp->CWCExecute();
?>

