<cwc2 type="SharedResource" name="WaitImage">
    <waitimage language="en-CA" waitimage="images/spinner.gif" waitimagewidth="216" waitimageheight="50"/>
</cwc2>


<!-- Button Resource for Pan Arrows -->
<cwc2 type="SharedResource" name="PanArrows">
    <imagewidth value="50"/>
    <imageheight value="50"/>
    <labelfont value="fonts/Vera.ttf"/>
    <usetextbuttoncache value="false"/>
    <state value="normal">
        <textbuttoncolor value="f0f0f0"/>
    </state>
    <state value="hover">
        <textbuttoncolor value="cccccc"/>
    </state>
    <state value="selected">
        <textbuttoncolor value="cccccc"/>
    </state>
</cwc2>


<!-- defaults for NavButton -->
<cwc2 type="SharedResource" name="NavButtons">
    <textbuttonbackgroundimage value=""/>
    <imagewidth value="24"/>
    <imageheight value="24"/>
    <textbuttonpadding value="0"/>
    <textbuttonnudge value="0"/>
    <labelcolor value="111111"/>
    <labelfont value="fonts/Vera.ttf"/>
    <labelalign value="left"/>
    <labelfontsize value="8"/>
    <labelantialias value="true"/>
    <usetextbuttoncache value="false"/>
    <state value="normal">
        <textbuttoncolor value="f0f0f0"/>
        <textbuttonborder_topleft_image value="borders/border_tl_1.png"/>
        <textbuttonborder_top_image value="borders/border_t_1.png"/>
        <textbuttonborder_topright_image value="borders/border_tr_1.png"/>
        <textbuttonborder_right_image value="borders/border_r_1.png"/>
        <textbuttonborder_left_image value="borders/border_l_1.png"/>
        <textbuttonborder_bottomright_image value="borders/border_br_1.png"/>
        <textbuttonborder_bottom_image value="borders/border_b_1.png"/>
        <textbuttonborder_bottomleft_image value="borders/border_bl_1.png"/>
    </state>
    <state value="hover">
        <textbuttoncolor value="cccccc"/>
        <textbuttonborder_topleft_image value="borders/border_tl_2.png"/>
        <textbuttonborder_top_image value="borders/border_t_2.png"/>
        <textbuttonborder_topright_image value="borders/border_tr_2.png"/>
        <textbuttonborder_right_image value="borders/border_r_2.png"/>
        <textbuttonborder_left_image value="borders/border_l_2.png"/>
        <textbuttonborder_bottomright_image value="borders/border_br_2.png"/>
        <textbuttonborder_bottom_image value="borders/border_b_2.png"/>
        <textbuttonborder_bottomleft_image value="borders/border_bl_2.png"/>
    </state>
    <state value="selected">
        <textbuttoncolor value="cccccc"/>
        <textbuttonborder_topleft_image value="borders/border_tl_3.png"/>
        <textbuttonborder_top_image value="borders/border_t_3.png"/>
        <textbuttonborder_topright_image value="borders/border_tr_3.png"/>
        <textbuttonborder_right_image value="borders/border_r_3.png"/>
        <textbuttonborder_left_image value="borders/border_l_3.png"/>
        <textbuttonborder_bottomright_image value="borders/border_br_3.png"/>
        <textbuttonborder_bottom_image value="borders/border_b_3.png"/>
        <textbuttonborder_bottomleft_image value="borders/border_bl_3.png"/>
    </state>
</cwc2>

<!-- defaults for textbuttons-->
<cwc2 type="SharedResource" name="TextButtons">
    <textbuttonbackgroundimage value=""/>
    <imagewidth value="120"/>
    <imageheight value="24"/>
    <textbuttonpadding value="0"/>
    <textbuttonnudge value="0"/>
    <labelcolor value="111111"/>
    <labelfont value="fonts/Vera.ttf"/>
    <labelalign value="left"/>
    <labelfontsize value="8"/>
    <labelantialias value="true"/>
    <usetextbuttoncache value="false"/>
    <state value="normal">
        <textbuttoncolor value="f0f0f0"/>
        <textbuttonborder_topleft_image value="borders/border_tl_1.png"/>
        <textbuttonborder_top_image value="borders/border_t_1.png"/>
        <textbuttonborder_topright_image value="borders/border_tr_1.png"/>
        <textbuttonborder_right_image value="borders/border_r_1.png"/>
        <textbuttonborder_left_image value="borders/border_l_1.png"/>
        <textbuttonborder_bottomright_image value="borders/border_br_1.png"/>
        <textbuttonborder_bottom_image value="borders/border_b_1.png"/>
        <textbuttonborder_bottomleft_image value="borders/border_bl_1.png"/>
    </state>
    <state value="hover">
        <textbuttoncolor value="cccccc"/>
        <textbuttonborder_topleft_image value="borders/border_tl_2.png"/>
        <textbuttonborder_top_image value="borders/border_t_2.png"/>
        <textbuttonborder_topright_image value="borders/border_tr_2.png"/>
        <textbuttonborder_right_image value="borders/border_r_2.png"/>
        <textbuttonborder_left_image value="borders/border_l_2.png"/>
        <textbuttonborder_bottomright_image value="borders/border_br_2.png"/>
        <textbuttonborder_bottom_image value="borders/border_b_2.png"/>
        <textbuttonborder_bottomleft_image value="borders/border_bl_2.png"/>
    </state>
    <state value="selected">
        <textbuttoncolor value="cccccc"/>
        <textbuttonborder_topleft_image value="borders/border_tl_3.png"/>
        <textbuttonborder_top_image value="borders/border_t_3.png"/>
        <textbuttonborder_topright_image value="borders/border_tr_3.png"/>
        <textbuttonborder_right_image value="borders/border_r_3.png"/>
        <textbuttonborder_left_image value="borders/border_l_3.png"/>
        <textbuttonborder_bottomright_image value="borders/border_br_3.png"/>
        <textbuttonborder_bottom_image value="borders/border_b_3.png"/>
        <textbuttonborder_bottomleft_image value="borders/border_bl_3.png"/>
    </state>
</cwc2>


<html>
<head>
	<title>Sample 5</title>
<script language="JavaScript">
function myOnLoad()
{
  CWC2OnLoadFunction()
}
</script>
<link href="sample.css" rel="stylesheet" type="text/css">
</head>
<body onLoad="myOnLoad()">

<form>

<div id="TitleLayer" name="TitleLayer">
<!-- TITLE -->
<cwc2 type="Title" label="IEM Mongoose (v0.1)" labelclass="title">
</cwc2>
<!-- SESSIONEXPIRED -->
<cwc2 type="SessionExpired" text="Your session has expired.">
</cwc2>
</div>


<div id="NavToolsLayer" name="NavToolsLayer">
  <table border="0" cellspacing="4" cellpadding="0">
    <tr>
      [#nav_basic.html#]
      [#nav_enhanced.html#]
    </tr>
  </table>
</div>


<div id="PanArrowsLayer" name="PanArrowsLayer">
  <table width="100%" height="100%" border="0" cellpadding="0" cellspacing="0" bgcolor="f0f0f0" class="grey_border">
    <tr valign="top">
      <!-- COMPASSPOINT - NORTHWEST -->
      <td align="left"><cwc2 type="CompassPoint" Visible="true" styleresource="PanArrows" Direction="northwest" image="icons/icon_pan_nw.png" PanPercent="80" imagetip="Pan NorthWest">
              <image state="normal"/>
              <image state="hover"/>
              <image state="selected"/>
          </cwc2></td>
      <!-- COMPASSPOINT - NORTH -->
      <td align="center"><cwc2 type="CompassPoint" Visible="true" styleresource="PanArrows" Direction="north" image="icons/icon_pan_n.png" PanPercent="80" imagetip="Pan North">
              <image state="normal"/>
              <image state="hover"/>
              <image state="selected"/>
          </cwc2></td>
      <!-- COMPASSPOINT - NORTHEAST -->
      <td align="right"><cwc2 type="CompassPoint" Visible="true" styleresource="PanArrows" Direction="northeast" image="icons/icon_pan_ne.png" PanPercent="80" imagetip="Pan NorthEast">
              <image state="normal"/>
              <image state="hover"/>
              <image state="selected"/>
        </cwc2></td>
    </tr>

    <tr valign="middle">
      <!-- COMPASSPOINT - WEST -->
      <td align="left"><cwc2 type="CompassPoint" Visible="true" styleresource="PanArrows" Direction="west" image="icons/icon_pan_w.png" PanPercent="80" imagetip="Pan West">
              <image state="normal"/>
              <image state="hover"/>
              <image state="selected"/>
          </cwc2></td>
      <td align="center">&nbsp;</td>
      <!-- COMPASSPOINT - EAST -->
      <td align="right"><cwc2 type="CompassPoint" Visible="true" styleresource="PanArrows" Direction="east" image="icons/icon_pan_e.png" PanPercent="80" imagetip="Pan East">
              <image state="normal"/>
              <image state="hover"/>
              <image state="selected"/>
          </cwc2></td>
    </tr>
    <tr valign="bottom">
      <!-- COMPASSPOINT - SOUTHWEST -->
      <td align="left"><cwc2 type="CompassPoint" Visible="true" styleresource="PanArrows" Direction="southwest" image="icons/icon_pan_sw.png" PanPercent="80" imagetip="Pan SouthWest">
              <image state="normal"/>
              <image state="hover"/>
              <image state="selected"/>
          </cwc2></td>
      <!-- COMPASSPOINT - SOUTH -->
      <td align="center"><cwc2 type="CompassPoint" Visible="true" styleresource="PanArrows" Direction="south" image="icons/icon_pan_s.png" PanPercent="80" imagetip="Pan South">
              <image state="normal"/>
              <image state="hover"/>
              <image state="selected"/>
          </cwc2></td>
      <!-- COMPASSPOINT - SOUTHEAST -->
      <td align="right"><cwc2 type="CompassPoint" Visible="true" styleresource="PanArrows" Direction="southeast" image="icons/icon_pan_se.png" PanPercent="80" imagetip="Pan SouthEast">
              <image state="normal"/>
              <image state="hover"/>
              <image state="selected"/>
          </cwc2></td>
    </tr>
  </table>
</div>
                                                                                
<div id="MainMapLayer" name="MainMapLayer">
<!-- MAPDHTMLWIDGET -->
<cwc2 type="MapDHTMLWidget" visible="true" width="400" height="400" allowresize="true" marqueecolor="FF3333" marqueewidth="2" minscale="1"/>
</div>



<cwc2 type="ErrorReport" popupwidth="500" popupheight="400" toolbar="false" status="false" menubar="false"  visible="false" image="images/icon_error.png" imagewidth="18" imageheight="18" imagetip="Display Error Report" label="Error Report"/>

</form>


</body>
</html>
