<?php
include("../../config/settings.inc.php");
$TITLE = "IEM | Cool Stuff";
include("$rootpath/include/header.php"); ?>

<h3 class="heading">IEM Cool Stuff</h3>
<p>Every now and then, the IEM produces something cool. This page contains
a listing of cool stuff as rated by IEM users.</p>

<h3 class="subtitle">Applications and GIS Products:</h3>

<br clear="left" />
<p><div class="iem-form">
<table width="100%"><thead>
<tr><th colspan="2" align="left"><b>IEM Freeze</b></th></tr></thead>
<tbody><tr><td><br /><img src="<?php echo $rooturl; ?>/cool/images/freeze_031215.png" width="300" height="230"></td>
<td valign="top"><br />IEM Freeze is an application that lets you quickly evaluate air and pavement
temperatures, along with concurrent radar observations of precipitation.<br
/><br /><a
href="<?php echo $rooturl; ?>/GIS/apps/iem/freeze.phtml">IEM Freeze Application</a></td></tr></tbody></table></div>

<br clear="left" />
<p><div class="iem-form">
<table width="100%"><thead>
<tr><th colspan="2" align="left"><b>RWIS Pavement Temperatures</b></th></tr></thead>
<tbody><tr><td><br /><img src="<?php echo $rooturl; ?>/cool/images/rwispaveplot.png" width="300"
height="270"></td>
<td valign="top"><br />The RWIS Pavement Temperature Time Series application
allows you to plot current or historical time series data of pavement
temperature, bridge temperature, air temperature, etc. all in one meteogram for
any RWIS site in Iowa.<br
/><br /><a
href="<?php echo $rooturl; ?>/plotting/rwis/sf_fe.php">Pavement Temperature Time Series
Application</a></td></tr></tbody></table></div>

<br clear="left" />
<p><div class="iem-form">
<table width="100%"><thead>
<tr><th colspan="2" align="left"><b>1-Minute Time Series Plots</b></th></tr></thead>
<tbody><tr><td><br /><img src="<?php echo $rooturl; ?>/cool/images/snettimeseries.png" width="250"
height="120"></td>
<td valign="top"><br />Here you can get current and historical temperature, wind
speed/direction, and pressure time series plots for any Schoolnet or AWOS site
in Iowa.<br
/><br /><a
href="<?php echo $rooturl; ?>/plotting/snet/1station_1min.php">Plotting for Schoolnet</a><br
/><br />

<a
href="<?php echo $rooturl; ?>/plotting/awos/1station_1min.php">Plotting for AWOS</a></td></tr></tbody></table></div>

<br /><br /><h3 class="subtitle">Web Camera Videos:</h3>

<p><div class="iem-form">
<table width="100%"><thead> <tr><th colspan="2" align="left"><b>22 Mar 2006: Radiation 101</b></th></tr></thead> <tbody><tr><td><br /><img src="<?php echo $rooturl; ?>/cool/images/ames_060322_tree.jpg" width="320"></td><td valign="top"><br />After an early spring snow storm, the skies cleared nicely the next day allowing full sunshine to hit these two evergreen trees.  What happened during the day and shown in this lapse can be found in the radiation 101 book.  The green tree absorbs incoming short wave radiation from the sun and then emitts it back to the snow surface as long wave radiation.  The snow reflects the short wave and absorbs the long wave thus melting the snow around the tree near the long wave radiation source (the trees).
<br /><br /><a href="../onsite/lapses/ames_060322_tree.mpg">View MPG (2 MB)</a>
<br /><br /><a href="../onsite/lapses/ames_060322_tree.qt">View QT (2 MB)</a>
</td></tr></tbody></table></div>


<p><div class="iem-form">
<table width="100%"><thead> <tr><th colspan="2" align="left"><b>12 Nov 2005: Ames tornado</b></th></tr></thead> <tbody><tr><td><br /><img src="<?php echo $rooturl; ?>/cool/images/ames_051112.jpg" width="320"></td><td valign="top"><br />The second tornado caught by a web camera on this day.  This tornado briefly touched down in NW Ames and badly damaged a few houses.  It was the second tornado to hit the city of Ames in 2005.
<br /><br /><a href="../cases/051112/ames_webcam_tornado_kcci/ames_TORNADO.mpg">View MPG (2 MB)</a>
<br /><br /><a href="../cases/051112/ames_webcam_tornado_kcci/ames_TORNADO.qt">View QT (2 MB)</a>
</td></tr></tbody></table></div>

<p><div class="iem-form">
<table width="100%"><thead> <tr><th colspan="2" align="left"><b>12 Nov 2005: Woodward tornado</b></th></tr></thead> <tbody><tr><td><br /><img src="<?php echo $rooturl; ?>/cool/images/madrid_051112.jpg" width="320"></td><td valign="top"><br />Just a great time lapse from the Madrid webcamera looking SW toward the city of Woodward.  This storm produced extensive damage there, but the dissipation of the tornado shown in this lapse happened just as the tornado approached the city.  It could have been much worse.
<br /><br /><a href="../cases/051112/madrid_webcam_tornado_kcci/madrid_TORNADO_1.mpg">View MPG (2 MB)</a>
<br /><br /><a href="../cases/051112/madrid_webcam_tornado_kcci/madrid_TORNADO_1.qt">View QT (2 MB)</a>
</td></tr></tbody></table></div>

<p><div class="iem-form">
<table width="100%"><thead> <tr><th colspan="2" align="left"><b>24 Jul 2005: Tama Cloud Burp</b></th></tr></thead> <tbody><tr><td><br /><img src="<?php echo $rooturl; ?>/cool/images/tama_050724_burp.jpg" width="320"></td><td valign="top"><br />Nice little lapse of a quick updraft looking northeast from Tama around 7 PM.  If you watch the lapse, you will see a little bit of ice get thrown out of the top of the cloud!  It is kind of neat to see.  14 minutes of time elapse during this lapse.
<br /><br /><a href="../onsite/lapses/tama_050724.mpg">View MPG (3 MB)</a>
<br /><br /><a href="../onsite/lapses/tama_050724.qt">View QT (3 MB)</a>
</td></tr></tbody></table></div>


<p><div class="iem-form">
<table width="100%"><thead>
<tr><th colspan="2" align="left"><b>12 Jun 2005: Creston Convection</b></th></tr></thead>
<tbody><tr><td><br /><img src="<?php echo $rooturl; ?>/cool/images/creston_050612.jpg" width="320"></td><td valign="top"><br />Caught a neat lapse of growing convection looking east from Creston during the late afternoon.  These storms were in an environment of about 2000 J/kg of CAPE and not much shear.  They did not produce any significant hail or wind.
<br /><br /><a href="../onsite/lapses/creston_050612_1.mpg">View MPG (3 MB)</a>
<br /><br /><a href="../onsite/lapses/creston_050612_1.qt">View QT (3 MB)</a>
</td></tr></tbody></table></div>


<p><div class="iem-form">
<table width="100%"><thead>
<tr><th colspan="2" align="left"><b>6 Jun 2005: Newton Convection</b></th></tr></thead>
<tbody><tr><td><br /><img src="<?php echo $rooturl; ?>/cool/images/newton_050606.jpg" width="320"></td>
<td valign="top"><br />Caught this thunderstorm looking north from Newton.  No severe weather was reported with this cell, but it made for a pretty lapse.  You can see how this cell was not able to sustain an updraft.  This lapse contains
900 frames between 3:45 and 5:45 PM.
<br /><br /><a href="../onsite/lapses/newton_050606.mpg">View MPG (8 MB)</a>
<br /><br /><a href="../onsite/lapses/newton_050606.qt">View QT (8 MB)</a>
</td></tr></tbody></table></div>

<p><div class="iem-form">
<table width="100%"><thead>
<tr><th colspan="2" align="left"><b>8 May 2005: Tornado or Not Tornado...</b></th></tr></thead>
<tbody><tr><td><br /><img src="<?php echo $rooturl; ?>/cool/images/carr_dust.jpg" width="320"></td>
<td valign="top"><br />Was this storm a tornado or not?  It is hard to tell. It certainly did not last long.  The movie shows a rotating(?) dust column to the west of Carroll between 5:06 and 5:09 PM.  The cloud base is at about 4,000 feet and RADAR returns at the time were not indicating much rotation.  You can decide for yourself!
<br /><br /><a href="../onsite/lapses/carr_050508_1.mpg">View MPG (1.2 MB)</a>
<br /><br /><a href="../onsite/lapses/carr_050508_1.qt">View QT (1.2 MB)</a>
</td></tr></tbody></table></div>

<br clear="left" />
<p><div class="iem-form">
<table width="100%"><thead>
<tr><th colspan="2" align="left"><b>29 Oct 2004: Super Cell!</b></th></tr></thead>
<tbody><tr><td><br /><img src="<?php echo $rooturl; ?>/cool/images/winterset_041029.jpg" width="320"></td>
<td valign="top"><br />This is a fancy video at the anvil and overshooting top of a supercell east of the Winterset Camera.  The day was characterized by very strong speed shear and 'good-enough' convective available potential energy (CAPE).  Storms away from the cold front were able to have decent organized structure.  
.<br /><br /><a href="../onsite/lapses/winterset_041029.mpg">View MPG (3.2 MB)</a></td></tr></tbody></table></div>

<br clear="left" />
<p><div class="iem-form">
<table width="100%"><thead>
<tr><th colspan="2" align="left"><b>27 Aug 2004: Humboldt Convection</b></th></tr></thead>
<tbody><tr><td><br /><img src="<?php echo $rooturl; ?>/cool/images/humboldt_cu.jpg"></td>
<td valign="top"><br />This is a video of a supercell east of Humboldt. The
convection in this storm is very vigorous and supported very large hail.  This was one of the first cells to fire on a very active weather day in Iowa
.<br /><br /><a href="../onsite/lapses/humboldt_040826_cu.mpg">View MPG (3.3 MB)</a></td></tr></tbody></table></div>

<br clear="left" />
<p><div class="iem-form">
<table width="100%"><thead>
<tr><th colspan="2" align="left"><b>27 Aug 2004: Rockwell City Beaver Tail</b></th></tr></thead>
<tbody><tr><td><br /><img src="<?php echo $rooturl; ?>/cool/images/rock_beaver.jpg"></td>
<td valign="top"><br />This is a fantastic lapse of a beaver tail flowing
into a vigorous thunderstorms.  Storms on this day produced baseball sized 
in numerous locations.  This view is looking west.<br /><br /><a href="../onsite/lapses/rockcity_040826_1.mpg">View MPG (1.7
MB)</a></td></tr></tbody></table></div>

<br clear="left" />
<p><div class="iem-form">
<table width="100%"><thead>
<tr><th colspan="2" align="left"><b>11 July 2004: Carroll Convection Video
#2</b></th></tr></thead>
<tbody><tr><td><br /><img src="<?php echo $rooturl; ?>/cool/images/carr_conv2.jpg"></td>
<td valign="top"><br />Another movie of bubbling convection from Carroll.  This shot is looking 
northwest.  This is not as nice as the #1 video, but it is still worth the 
download for you weather junkies.<br /><br /><a
href="../onsite/lapses/carroll_040711_1.mpg">View MPG (6.4
MB)</a></td></tr></tbody></table></div>

<br clear="left" />
<p><div class="iem-form">
<table width="100%"><thead>
<tr><th colspan="2" align="left"><b>4 July 2004: Carroll Convection Video #1</b></th></tr></thead>
<tbody><tr><td><br /><img src="<?php echo $rooturl; ?>/cool/images/carr_conv1.jpg"></td>
<td valign="top"><br />This is a fantastic movie of bubbling convection as captured by the 
webcamera in Carroll.  This image is looking due east and near sunset.<br /><br /><a href="../onsite/lapses/carroll_040704_1.mpg">View MPG (4.6 MB)</a>
</td></tr></tbody></table></div>

<br clear="left" />
<p><div class="iem-form">
<table width="100%"><thead><tr><th colspan="2" align="left"><b>11 June 2004: Tornado on Webster City
Webcamera</b></th></tr></thead>
<tbody><tr><td>
<br /><img src="<?php echo $rooturl; ?>/cool/images/web_thumb.jpg"></td>
<td valign="top"><br />This tornado was caught by the Webster City webcamera that is a part of <a href="/schoolnet/">KCCI's SchoolNet project</a>.  The movie is taken looking
far south and a bit west.<br /><br /><a href="../onsite/lapses/webstercity_040611_full.mpg">View MPG (3
MB)</a></td></tr><tbody></table></div>



<!-- Begin the bottom of the page -->

<?php include("$rootpath/include/footer.php"); ?>
