<?php 
 require_once "../../config/settings.inc.php";
 include("../../include/myview.php");
 require_once "../../include/mlib.php"; 
 include_once "../../include/database.inc.php";
 require_once "../../include/forms.php";
 
 $t = new MyView();
 $t->current_network = "Other";
 $sortcol = isset($_GET["sortcol"]) ? xssafe($_GET["sortcol"]): "station";
 $network = isset($_GET["network"]) ? xssafe($_GET["network"]): 'OT';
 
 $mesosite = iemdb('mesosite');
 pg_prepare($mesosite, "FINDTZ", "SELECT tzname from networks where id = $1");
 $rs = pg_execute($mesosite, "FINDTZ", Array($network));
 if (pg_num_rows($rs) < 1){
 	$tzname = "America/Chicago";
 } else {
 	$row = pg_fetch_assoc($rs,0);
 	$tzname = $row["tzname"];
 }
  
 $t->title = "Other Currents";
 $t->refresh = 600;
 $t->thispage = "current-sort";

 $jdata = file_get_contents("http://iem.local/api/1/currents.json?network=$network");
 $jobj = json_decode($jdata, $assoc=TRUE);

$vals = Array("tmpf" => "Air Temperature [F]", "dwpf" => "Dew Point Temp [F]",
  "sknt" => "Wind Speed [knots]", "wdir" => "Wind Direction [deg]",
  "pday" => "Precip Accum [inches]", "max_sknt" => "Wind Gust [knots]",
  "ts" => "Observation Time [local]", "feel" => "Feels Like",
  "min_tmpf" => "Today's Low Temperature", "drct" => "Wind Direction",
  "max_tmpf" => "Today's High Temperature", "gtim" => "Wind Gust Time",
  "station" => "Station ID", "relh" => "Relative Humidity");

$t->breadcrumbs = <<<EOF
<ol class="breadcrumb">
	<li><a href="/other/">Other Networks</a></li>
	<li class="active">Current Conditions</li>
</ol>
EOF;

$mydata = Array();

while (list($bogus, $iemob) = each($jobj["data"]) ){
    $key = $iemob["station"];
	$mydata[$key] = $iemob;
	$mydata[$key]["ts"] = strtotime($iemob["local_valid"]);
	$mydata[$key]["sped"] = $mydata[$key]["sknt"] * 1.15078;
    $mydata[$key]["relh"] = relh(f2c($mydata[$key]["tmpf"]),
       f2c($mydata[$key]["dwpf"]) );
    if ($mydata[$key]["tmpf"] > -99 && $mydata[$key]["dwpf"] > -99){
       $mydata[$key]["feel"] = feels_like($mydata[$key]["tmpf"],
         $mydata[$key]["relh"], $mydata[$key]["sped"]);
    } else {
        $mydata[$key]["feel"] = null;
    }
	
	if ($mydata[$key]["max_gust"] > $mydata[$key]["max_sknt"]){
		$mydata[$key]["peak"] = $mydata[$key]["max_gust"];
		$mydata[$key]["peak_ts"] = strtotime($mydata[$key]["local_max_gust_ts"]);
	} else {
		$mydata[$key]["peak"] = $mydata[$key]["max_sknt"];
		$mydata[$key]["peak_ts"] = @strtotime($mydata[$key]["local_max_sknt_ts"]);
	}

}

$finalA = aSortBySecondIndex($mydata, $sortcol);
$i = 0;
$now = time();

$table = "";
// Loop though all data
while (list ($key, $val) = each ($finalA))  {
	$parts = $finalA[$key];
	$i++;
	$tdiff = $now - $parts["ts"];
	// Don't show stations over 5 days old
	if ($tdiff > 86400*5){
		continue;
	}
	$table .= "<tr";
	if ($i % 2 == 0)  $table .= " bgcolor='#eeeeee'";

	$table .= ">";
	$table .= "<td><input type=\"checkbox\" name=\"st[]\"
               value=\"".$key."\"></td>";
	$table .= sprintf("<td><a href=\"/sites/site.php?station=%s&amp;network=%s\">%s</a></td>",
	    $key, $network, $parts["name"]); 
	$table .= "<td ";
	if ($tdiff > 11900){
		$table .= 'bgcolor="red"';
		$format = "%b-%d-%y %I:%M %p";
	} else if ($tdiff > 7200){
		$table .= 'bgcolor="orange"';
		$format = "%I:%M %p";
	} else if ($tdiff > 3600){
		$table .= 'bgcolor="green"';
		$format = "%I:%M %p";
	} else {
		$format = "%I:%M %p";
	}
	$table .= ">". strftime($format, $parts["ts"]) ."</td>
  <td align='center'>". round($parts["tmpf"],0) ."(<font color=\"#ff0000\">".
  round($parts["max_tmpf"],0) ."</font>/<font color=\"#0000ff\">".
  round($parts["min_tmpf"],0) ."</font>)</td>
 <td>". round($parts["dwpf"],0) ."</td>
 <td>". $parts["feel"] ."</td>
 <td>". $parts["relh"] ."</td>
 <td>". round($parts["sknt"],0) ;
	if (strlen($parts["gust"]) > 0 && $parts["gust"] > 0){
		$table .= "G". round($parts["gust"],1);
	}
	$table .= "</td>
            <td>". round($parts["drct"],0) ."</td>
	    <td>". round($parts["peak"],0) ."@ ". strftime("%I:%M %p", $parts["peak_ts"] ) ."</td>
	    </tr>\n";
}

$networks = Array(
		"KYMN" => "Kentucky Mesonet",
		"OT" => "IEM Misc Stations",
		"VTWAC" => "Vermont Weather Analytics Center");
$buttons = "";
while (list($key,$val)=each($networks)){
	$buttons .= sprintf("<a class=\"btn btn-sm%s\" href=\"current.phtml?network=%s\">%s</a>",
			($key == $network) ? ' active': '', $key, $val);
}

$content = <<<EOF

<p><b>Other Networks:</b> {$buttons}
 
<br /><strong>Times shown are for timezone: ${tzname}.</strong> The local day summary
is based on that timezone.
<br />Sorted by: <b>({$vals[$sortcol]})</b>  &nbsp; &nbsp; Click on
a column to sort it.<br>

<form method="GET" action="/my/current.phtml">
<table class="table table-striped table-condensed table-bordered">
<thead>
<tr>
  <th rowspan="2">ADD:</th>
  <th rowspan="2">Station:</th>
  <th rowspan="2"><a href="current.phtml?sortcol=ts">Ob Time</a></th>
  <th colspan="3">Temps &deg;F</th>
  <th>&nbsp;</th>
  <th colspan="3">Wind [knots]</th>
</tr>

<tr>
  <th>
   <a href="current.phtml?network={$network}&amp;sortcol=tmpf">Air</a>
   (<a href="current.phtml?network={$network}&amp;sortcol=max_tmpf">Hi</a> /
   <a href="current.phtml?network={$network}&amp;sortcol=min_tmpf">Lo</a>)
</th>
  <th><a href="current.phtml?network={$network}&amp;sortcol=dwpf">DewP</a></th>
  <th><a href="current.phtml?network={$network}&amp;sortcol=feel">Feels</a></th>
  <th><a href="current.phtml?network={$network}&amp;sortcol=relh">RH%</a></th>
  <th><a href="current.phtml?network={$network}&amp;sortcol=sknt">Speed</a></th>
  <th><a href="current.phtml?network={$network}&amp;sortcol=drct">Direction</a></th>
  <th><a href="current.phtml?network={$network}&amp;sortcol=max_sknt">Gust</a>
    @<a href="current.phtml?network={$network}&amp;sortcol=gtim">Time</a></th>
</tr>
</thead>
<tbody>
{$table}
</tbody>
</table>
<input type="submit" value="Add to Favorites">
<input type="reset" value="Reset">

</form>

<br><br>
EOF;
$t->content = $content;
$t->render("sortables.phtml");
?>
