<?php 
include("../../config/settings.inc.php");
include("../../include/myview.php");
$t = new MyView();
$t->title = "Other Network";
include("../../include/forms.php"); 
include("../../include/imagemaps.php"); 

$year = isset($_GET["year"]) ? $_GET["year"] : date("Y");
$month = isset($_GET["month"]) ? $_GET["month"] : date("m");
$day = isset($_GET["day"]) ? $_GET["day"] : date("d");
$myTime = mktime(0,0,0,$month,$day,$year);
$station = isset($_GET["station"]) ? $_GET["station"]: "OT0002";

$nselect = networkSelect("OT", $station);
$yselect = yearSelect(2007, $year);
$mselect = monthSelect($month);
$dselect = daySelect($day);

$t->content = <<<EOF
<ol class="breadcrumb">
 <li><a href="/other/">Other Networks</a></li>
 <li class="active">Mesonet Northeast Ames</li>
</ol>

  <form method="GET" name="control">
  {$nselect}
  {$yselect}
  {$mselect}
  {$dselect}

  <input type="submit" value="Make Plot"></form>

<BR>
<img src="plot_temps.php?station={$station}&year={$year}&month={$month}&day={$day}" ALT="Time Series">
<img src="plot_winds.php?station={$station}&year={$year}&month={$month}&day={$day}" ALT="Time Series">

</div>
EOF;
$t->render('single.phtml');
?>
