<?php
require_once "../../config/settings.inc.php";
require_once "../../include/myview.php";
$t = new MyView();
$t->title = "Other Network";
require_once "../../include/forms.php";
require_once "../../include/imagemaps.php";

$year = get_int404("year", date("Y"));
$month = get_int404("month", date("m"));
$day = get_int404("day", date("d"));
$myTime = mktime(0, 0, 0, $month, $day, $year);
$station = isset($_GET["station"]) ? xssafe($_GET["station"]) : "OT0002";

$nselect = networkSelect("OT", $station);
$yselect = yearSelect(2007, $year);
$mselect = monthSelect($month);
$dselect = daySelect($day);

$t->content = <<<EOF
<ol class="breadcrumb">
 <li><a href="/other/">Other Networks</a></li>
 <li class="active">Mesonet Northeast Ames</li>
</ol>

  <form method="GET" name="control">
  {$nselect}
  {$yselect}
  {$mselect}
  {$dselect}

  <input type="submit" value="Make Plot"></form>

<BR>
<img src="plot_temps.php?station={$station}&year={$year}&month={$month}&day={$day}" ALT="Time Series">
<img src="plot_winds.php?station={$station}&year={$year}&month={$month}&day={$day}" ALT="Time Series">

</div>
EOF;
$t->render('single.phtml');
