<?php 
include("../../config/settings.inc.php");
$TITLE = "IEM | 1 Minute Time Series";
include("$rootpath/include/header.php"); 
include("$rootpath/include/forms.php"); 
include("$rootpath/include/imagemaps.php"); 

$year = isset($_GET["year"]) ? $_GET["year"] : date("Y");
$month = isset($_GET["month"]) ? $_GET["month"] : date("m");
$day = isset($_GET["day"]) ? $_GET["day"] : date("d");
$myTime = mktime(0,0,0,$month,$day,$year);
$station = isset($_GET["station"]) ? $_GET["station"]: "OT0002";

?>

<div class="text">
<a href="/other/">Other Networks</a> &nbsp;<b> > </b> &nbsp; Mesonet Northeast Ames

  <form method="GET" name="control">
  <?php echo networkSelect("OT", $station); ?>
  <?php echo yearSelect(2007, $year); ?>
  <?php echo monthSelect($month); ?>
  <?php echo daySelect($day); ?>

  <input type="submit" value="Make Plot"></form>

<BR>
<img src="plot_temps.php?station=<?php echo $station; ?>&year=<?php echo $year; ?>&month=<?php echo $month; ?>&day=<?php echo $day; ?>" ALT="Time Series">
<img src="plot_winds.php?station=<?php echo $station; ?>&year=<?php echo $year; ?>&month=<?php echo $month; ?>&day=<?php echo $day; ?>" ALT="Time Series">

</div>
<?php include("$rootpath/include/footer.php"); ?>
