<?php 
require_once "../../config/settings.inc.php";
define("IEM_APPID", 25);
require_once "../../include/myview.php";
$t = new MyView();
require_once "../../include/forms.php";
require_once "../../include/imagemaps.php";
require_once "../../include/mlib.php";

$t->title = "Other Data Networks";

$y1select = yearSelect2(2012, 2012, "year1");
$m1select = monthSelect(1, "month1");
$d1select = daySelect2(1, "day1");
$y2select = yearSelect2(2012, date("Y"), "year2");
$m2select = monthSelect(date("m"), "month2");
$d2select = daySelect2(date("d"), "day2");
$y12select = yearSelect2(2003, date("Y"), "year1");
$y22select = yearSelect2(2003, date("Y"), "year2");
$y13select = yearSelect2(2014, date("Y"), "year1");
$y23select = yearSelect2(2014, date("Y"), "year2");
$nselect = networkSelect("OT", "");

$t->content = <<<EOF
<h3>Other Data Networks</h3>

<p>This page contains links to miscellaneous IEM networks and standalone
stations.  The <a href="/schoolnet/">School-based Network</a> is no longer
collected and the <a href="/projects/iao/">Iowa Atmospheric Observatory</a>
equipment has been removed.</p>

<h3>Agronomy Hall, ISU:</h3>

<ul>
<li><a href="/other/current.phtml">Sortable Currents</a></li>
<li><a href="/plotting/mesoeast/">Ames (Northern, Dave Flory)</a></li>
<li><a href="/plotting/mesonorth/ot_10min.phtml">Indoor Temperature for Met Cluster Room</a>, B548 Agronomy Hall.  Outfitted with 4 One-Wire sensors reporting every minute.</li>
<li><a href="/plotting/isumet/ams2.phtml">ISU AMS Station</a>, On the roof.  Davis Vantage Pro 2, installed 8 Sep 2011.
<a href="/request/daily.phtml?network=OT">Download daily summaries</a> for station.</li>
</ul>

<h3>City of Ames</h3>
<ul>
<li><a href="daily_plot.phtml?station=OT0008&year=2007&month=2&day=13">Reiman Gardens station</a>, only some limited data from 2007 for the site.</li>
</ul>


<h3>Stuart Smith Park Hydrology Learning Lab, Ames</h3>

<p>These are four ground water monitoring wells and a stream gauge located at
the Stuart Smith Park in Ames.  These data are used by the Geology 100 class, but
are freely available to others.

<div class="row">
<div class="col-md-6 well">

<h4>Download Stream Gage Data ("Bubbler")</h4>
<form method="GET" action="/cgi-bin/request/ss.py" name="bubbler">
<input type="hidden" name="opt" value="bubbler" />
<table class="table table-bordered">
 <th>Start Date:</th> 
  <td>{$y1select}</td>
  <td>{$m1select}</td>
  <td>{$d1select}</td></tr>

<tr>
 <th>End Date:</th>
  <td>{$y2select}</td>
  <td>{$m2select}</td>
  <td>{$d2select}</td></tr>

</table>
<input type="checkbox" name="excel" value="yes" />Download as Excel File
<br /><input type="submit" value="Request Data" />
</form>

</div><div class="col-md-6 well">

<h4><i class="fa fa-download"></i> Download Ground Monitoring Well Data</h4>
<form method="GET" action="/cgi-bin/request/ss.py" name="gage">
<input type="hidden" name="opt" value="gage" />
<table class="table table-bordered">
  <td rowspan="2"><strong>Select Station(s):</strong><br />
  <select multiple size="4" name="station">
   <option value="9100131">SSP #1</option>
   <option value="9100104">SSP #6</option>
   <option value="9100156">SSP #7</option>
   <option value="9100135">SSP #8</option>
  </select>
  </td>
  <th>Start Date:</th> 
  <td>{$y1select}</td>
  <td>{$m1select}</td>
  <td>{$d1select}</td></tr>

<tr>
 <th>End Date:</th>
  <td>{$y2select}</td>
  <td>{$m2select}</td>
  <td>{$d2select}</td></tr>

</table>
<input type="checkbox" name="excel" value="yes" />Download as Excel File
<br /><input type="submit" value="Request Data" />
</form>

</div></div>


<h3>ISU FEEL Data</h3>

<p>This data is provided by The National Laboratory for Agriculture and the Environment.</p>

<form name="feel" action="/cgi-bin/request/feel.py">
<table>
<tr>
 <th>Start Date:</th> 
  <td>{$y13select}</td>
  <td>{$m1select}</td>
  <td>{$d1select}</td></tr>

<tr>
 <th>End Date:</th>
  <td>{$y23select}</td>
  <td>{$m2select}</td>
  <td>{$d2select}</td></tr>

</table>
<input type="submit" value="Request Data" />
</form>


<h3>Raw Data Download!</h3>
<form name="dl" action="/cgi-bin/request/other.py">
<table class="table table-condensed table-bordered">
<tr><th rowspan="2">Select Location: {$nselect}</th>
 <th>Start Date:</th> 
  <td>{$y12select}</td>
  <td>{$m1select}</td>
  <td>{$d1select}</td></tr>

<tr>
 <th>End Date:</th>
  <td>{$y22select}</td>
  <td>{$m2select}</td>
  <td>{$d2select}</td></tr>

</table>
<input type="submit" value="Request Data" />
</form>
EOF;
$t->render('single.phtml');
