<?php 
 include("../../config/settings.inc.php");
 include("../../include/myview.php");
 $t = new MyView();
 $sortcol = isset($_GET["sortcol"]) ? $_GET["sortcol"] : "station";

 $t->title = "Kentucky Mesonet";
 $t->refresh = "<meta http-equiv=\"refresh\" content=\"600; URL=kymn.phtml?sortcol=$sortcol\">";
 $t->headextra = <<<EOF
 <script language="JavaScript" type="text/javascript">
<!--//BEGIN Script
function new_window(url) {
 link = window.open(url,"_new","toolbar=0,location=0,directories=0,status=0,menubar=no,scrollbars=yes,resizable=yes,width=800,height=600");
} 
//END Script-->
</script>
EOF;
 include("../../include/mlib.php"); 
  include("../../include/iemaccess.php");
  include("../../include/iemaccessob.php");

$iem = new IEMAccess();
$rwis = $iem->getNetwork("KYMN");

$vals = Array("tmpf" => "Air Temperature [F]", "dwpf" => "Dew Point Temp [F]",
  "sknt" => "Wind Speed [knots]", "wdir" => "Wind Direction [deg]",
  "pday" => "Precip Accum [inches]", "max_gust" => "Wind Gust [knots]",
  "ts" => "Observation Time [local]", "feel" => "Feels Like",
  "min_tmpf" => "Today's Low Temperature", "drct" => "Wind Direction",
  "max_tmpf" => "Today's High Temperature", "dwpf" => "Dew Point",
  "gtim" => "Wind Gust Time",
  "station" => "Station ID", "relh" => "Relative Humidity");

$t->breadcrumbs = <<<EOF
<ol class="breadcrumb">
 <li><a href="/other/">Other Networks</a></li>
 <li class="active">Kentucky Mesonet</li>
 </ol>
EOF;
$t->current_network = "Other";

function aSortBySecondIndex($multiArray, $secondIndex) {
        while (list($firstIndex, ) = each($multiArray))
                $indexMap[$firstIndex] = $multiArray[$firstIndex][$secondIndex];
        arsort($indexMap);
        while (list($firstIndex, ) = each($indexMap))
                if (is_numeric($firstIndex))
                        $sortedArray[] = $multiArray[$firstIndex];
                else $sortedArray[$firstIndex] = $multiArray[$firstIndex];
        return $sortedArray;
}

  $mydata = Array();

  while (list($key, $iemob) = each($rwis) ){
    $mydata[$key] = $iemob->db;
    $mydata[$key]["ts"] = $iemob->ts;
    $mydata[$key]["sped"] = $mydata[$key]["sknt"] * 1.15078;
	if ($mydata[$key]["ozone"] < 0) $mydata[$key]["ozone"] = "NA";
	if ($mydata[$key]["co2"] < 0) $mydata[$key]["co2"] = "NA";
    if ($mydata[$key]["relh"] < 0)
      $mydata[$key]["relh"] = relh(f2c($mydata[$key]["tmpf"]), 
         f2c($mydata[$key]["dwpf"]) );
    $mydata[$key]["feel"] = feels_like($mydata[$key]["tmpf"], 
       $mydata[$key]["relh"], $mydata[$key]["sped"]);
    if ($mydata[$key]["max_gust"] > $mydata[$key]["max_sknt"]){
      $mydata[$key]["peak"] = $mydata[$key]["max_gust"];
      $mydata[$key]["peak_ts"] = strtotime(substr( $mydata[$key]["max_gust_ts"],0,16) );
    } else {
      $mydata[$key]["peak"] = $mydata[$key]["max_sknt"];
      $mydata[$key]["peak_ts"] = @strtotime(substr( $mydata[$key]["max_sknt_ts"],0,16) );
    }

  }


  $finalA = Array();
  $finalA = aSortBySecondIndex($mydata, $sortcol);
  $i = 0;
  $now = time();
$table = "";
  // Loop though all data 
  while (list ($key, $val) = each ($finalA))  {
    $parts = $finalA[$key];
    $i++;
    $tdiff = $now - $parts["ts"];
      // Don't show stations over 5 days old
    if ($tdiff > 86400*5){
      continue;
    }
	  $table .= "<tr";
	  if ($i % 2 == 0)  $table .= " bgcolor='#eeeeee'";  
            
          $table .= ">";
   $table .= "<td><input type=\"checkbox\" name=\"st[]\" 
               value=\"".$key."\"></td>";
  $table .= "<td>". $parts["sname"] . "</td><td ";
  if ($tdiff > 11900){
    $table .= 'bgcolor="red"';
    $format = "%b-%d-%y %I:%M %p";
  } else if ($tdiff > 6900){
    $table .= 'bgcolor="orange"';
    $format = "%I:%M %p";
  } else if ($tdiff > 1800){
    $table .= 'bgcolor="green"';
    $format = "%I:%M %p";
  } else {
    $format = "%I:%M %p";
  }
  $table .= ">". strftime($format, $parts["ts"]) ."</td>
  <td align='center'>". round($parts["tmpf"],0) ."(<font color=\"#ff0000\">".
  round($parts["max_tmpf"],0) ."</font>/<font color=\"#0000ff\">".
  round($parts["min_tmpf"],0) ."</font>)</td>
 <td>". round($parts["dwpf"],0) ."</td>
 <td>". $parts["feel"] ."</td>
 <td>". $parts["relh"] ."</td>
 <td>". round($parts["sknt"],0) ;
  if (strlen($parts["gust"]) > 0 && $parts["gust"] > 0){
              $table .= "G". $parts["gust"];
  } 
  $table .= "</td>
            <td>". round($parts["drct"],0) ."</td>
	    <td>". round($parts["peak"],0) ."@ ". strftime("%I:%M %p", $parts["peak_ts"] ) ."</td></tr>\n";
   }

   $c = "javascript:new_window('/GIS/apps/php/currents.phtml?layers[]=radar&layers[]=labels&network=KYMN&var=";
    
$t->content = <<<EOF
<p><b>Other Networks:</b>  
<a href="current.phtml">Misc Stations</a> &nbsp; -- &nbsp; 
<a href="wtm.phtml">West Texas Mesonet</a> &nbsp; -- &nbsp; 

<br />
Sorted by: <b>({$vals[$sortcol]})</b>  &nbsp; &nbsp; Click on
a column to sort it.<br>

<form method="GET" action="/my/current.phtml">
<table style="font-size: 10pt;" class="ruler">
<thead>
<tr>
  <th rowspan="2">ADD:</th>
  <th rowspan="2">Station:</th>
  <th rowspan="2"><a href="wtm.phtml?sortcol=ts">Ob Time</a></th>
  <th colspan="3">Temps &deg;F</th>
  <th>&nbsp;</th>
  <th colspan="3">Wind [knots]</th>
<tr>
  
  <th>
   <a href="kymn.phtml?sortcol=tmpf">Air</a>
   (<a href="kymn.phtml?sortcol=max_tmpf">Hi</a> /
   <a href="kymn.phtml?sortcol=min_tmpf">Lo</a>)
</th>
  <th><a href="kymn.phtml?sortcol=dwpf">DewP</a></th>
  <th><a href="kymn.phtml?sortcol=feel">Feels</a></th>
  <th><a href="kymn.phtml?sortcol=relh">RH%</a></th>
  <th><a href="kymn.phtml?sortcol=sknt">Speed</a></th>
  <th><a href="kymn.phtml?sortcol=drct">Direction</a></th>
  <th><a href="kymn.phtml?sortcol=max_gust">Gust</a>
    @<a href="kymn.phtml?sortcol=gtim">Time</a></th>
</tr></thead><tbody>
  {$table}
</tbody>
<tfoot>
<tr>
 <td colspan=3>&nbsp;</td>
 <td><a href="{$c}tmpf');">Plot</a>
    (<a href="{$c}max_tmpf');">Plot</a> /
     <a href="{$c}min_tmpf');">Plot</a>)</td>
 <td><a href="{$c}dwpf');">Plot</a></td>
 <td><a href="{$c}feel');">Plot</a></td>
 <td><a href="{$c}relh');">Plot</a></td>
 <td colspan=2><a href="{$c}barb');">Plot</a></td>
 <td><a href="{$c}max_gust');">Plot</a></td>
</tr></tfoot>
</table>
<input type="submit" value="Add to Favorites">
<input type="reset" value="Reset">

</form>

<br><br>
EOF;
$t->render('sortables.phtml');
?>