<?php 
require_once "../../../config/settings.inc.php";
define("IEM_APPID", 132);
require_once "../../../include/myview.php";
require_once "../../../include/forms.php";
require_once "../../../include/imagemaps.php";

$t = new MyView();
$t->title = "Download Aviation Weather Center G-AIRMETs Shapefile/KML";
$content = <<<EOF
<p>
<ul class="breadcrumb">
<li><a href="/nws/">NWS Mainpage</a></li>
<li class="active">AWC G-AIRMETs Download</li>
</ul>
</p>

<p>The IEM has a database archive of
<a href="https://www.aviationweather.gov/gairmet/">AWC G-AIRMETs</a>
since their inception on about 3 March 2021.  The IEM also maintains an
archive of the raw XML text, which you can find listed on the main
<a href="/wx/afos/list.phtml?source=KKCI">AFOS List Page for KKCI</a>. These
products are assigned a product identifier of <code>GMT</code> on that page.
</p>

<p><strong>Related:</strong>
<a class="btn btn-primary" href="cwas.phtml">CWSU Center Weather Advisories</a>
<a class="btn btn-primary" href="pireps.php">PIREPs</a>
<a class="btn btn-primary" href="awc_sigmets.phtml">SIGMETs</a>
<a class="btn btn-primary" href="/request/taf.php">TAFs</a>
</p>

<form method="GET" action="/cgi-bin/request/gis/awc_gairmets.py">
<table class="table">
<thead><tr><th colspan="6">Time Interval for G-AIRMET
*Issue Time (G-AIRMETISSUETIME)* (UTC)</th></tr></thead>
<tr>
    <td></td><th>Year</th><th>Month</th><th>Day</th>
    <th>Hour</th><th>Minute</th>
</tr>

<tr>
EOF;
$content .= "<th>Start:</th>
    <td>
     ". yearSelect2(2021, date("Y"), "year1") ."
    </td>
    <td>
     ". monthSelect2(0,"month1") ."
    </td>
    <td>
     ". daySelect2(0, "day1") ."
    </td>
    <td>
     ". gmtHourSelect(0, "hour1") ."
    </td>
    <td>
     ". minuteSelect(0, "minute1") ."
    </td>
  </tr>

  <tr>
    <th>End:</th>
    <td>
     ". yearSelect2(2021, date("Y"), "year2") ."
    </td>
    <td>
     ". monthSelect2(date("m"), "month2") ."
    </td>
    <td>
     ". daySelect2(date("d"), "day2") ."
    </td>
    <td>
     ". gmtHourSelect(0, "hour2") ."
    </td>
    <td>
     ". minuteSelect(0, "minute2") ."
    </td>
  </tr>
</table>";

$content .= <<<EOM

<p><strong>Format:</strong><br />
<input type="radio" name="format" value="shp" checked="checked" id="shp" />
<label for="shp">Shapefile</label>
<input type="radio" name="format" value="kml" id="kml" />
<label for="kml">KML</label>

<p><input type="submit" value="Giveme data right now!"></p>
</form>

<h4>Shapefile DBF schema:</h4>
<pre>
Field 0: Type=C/String, Title=`NAME', GML_ID + VALID_AT timestamp
Field 1: Type=C/String, Title=`LABEL', Event label from GML_ID
Field 2: Type=C/String, Title=`GML_ID', Verbatim GML_ID from product
Field 3: Type=C/String, Title=`VALID_AT', UTC Valid At time (gml:timePosition)
Field 4: Type=C/String, Title=`VALID_FM', UTC From Time (G-AIRMETVALIDFROM)
Field 5: Type=C/String, Title=`VALID_TO', UTC To Time (G-AIRMETVALIDTO)
Field 6: Type=C/String, Title=`ISSUTIME', UTC Issue Time (G-AIRMETISSUETIME)
Field 7: Type=C/String, Title=`PROD_ID', IEM Text Product ID
Field 8: Type=C/String, Title=`STATUS', Status of AIRMET
Field 9: Type=C/String, Title=`HZTYPE', Hazard Type
Field 10: Type=C/String, Title=`WXCOND', Comma list of weather conditions
</pre>

<h4>Archive / Usage Notes:</h4>
<ol>
</ol>
</form>
EOM;

$t->content = $content;
$t->render('single.phtml');
