<?php 
require_once "../../../config/settings.inc.php";
define("IEM_APPID", 133);
require_once "../../../include/myview.php";
require_once "../../../include/forms.php";
require_once "../../../include/imagemaps.php";

$t = new MyView();
$t->title = "Download CWSU Center Weather Advisory (CWA) Shapefile/KML";
$content = <<<EOF
<p>
<ul class="breadcrumb">
<li><a href="/nws/">NWS Mainpage</a></li>
<li class="active">CWSU CWA Download</li>
</ul>
</p>

<p>The IEM has a database archive of
<a href="https://www.aviationweather.gov/cwamis">CWSU Center Weather Advisories</a>.
The archive presently dates back to 1 January 2014 and is updated in real-time as
new products are received and processed.  Robust processing of the CWA has been
problematic as the raw products are more free-form text than adhering to a format
specification.  Presently, attempts are not made at processing cancellation statements. 
</p>

<p><strong>Related:</strong>
<a class="btn btn-primary" href="awc_gairmets.phtml">AWC Graphical-AIRMETs</a>
<a class="btn btn-primary" href="pireps.php">PIREPs</a>
<a class="btn btn-primary" href="awc_sigmets.phtml">SIGMETs</a>
<a class="btn btn-primary" href="/request/taf.php">TAFs</a>
<a class="btn btn-primary" href="/request/tempwind_aloft.php">Temp/Winds Aloft</a>
</p>

<div class="alert alert-warning">
<p>The data presented here is beta quality and refinements are being made yet
to improve text parsing robustness.  This message will be removed once more
quality control checks are done to ensure fidelity.</p>
</div>

<form method="GET" action="/cgi-bin/request/gis/cwas.py">
<table class="table">
<thead><tr><th colspan="6">Time Interval for CWA Issuance (UTC)</th></tr></thead>
<tr>
    <td></td><th>Year</th><th>Month</th><th>Day</th>
    <th>Hour</th><th>Minute</th>
</tr>

<tr>
EOF;
$content .= "<th>Start:</th>
    <td>
     ". yearSelect2(2014, date("Y"), "year1") ."
    </td>
    <td>
     ". monthSelect2(0,"month1") ."
    </td>
    <td>
     ". daySelect2(0, "day1") ."
    </td>
    <td>
     ". gmtHourSelect(0, "hour1") ."
    </td>
    <td>
     ". minuteSelect(0, "minute1") ."
    </td>
  </tr>

  <tr>
    <th>End:</th>
    <td>
     ". yearSelect2(2014, date("Y"), "year2") ."
    </td>
    <td>
     ". monthSelect2(date("m"), "month2") ."
    </td>
    <td>
     ". daySelect2(date("d"), "day2") ."
    </td>
    <td>
     ". gmtHourSelect(0, "hour2") ."
    </td>
    <td>
     ". minuteSelect(0, "minute2") ."
    </td>
  </tr>
</table>";

$content .= <<<EOM

<p><strong>Format:</strong><br />
<input type="radio" name="format" value="shp" checked="checked" id="shp" />
<label for="shp">Shapefile</label>
<input type="radio" name="format" value="kml" id="kml" />
<label for="kml">KML</label>

<p><input type="submit" value="Giveme data right now!"></p>
</form>

<h4>Shapefile DBF schema:</h4>
<pre>
Field 0: Type=C/String, Title='CENTER', CWSU Center ID
Field 1: Type=C/String, Title='ISSUE', UTC CWA Issuance Time
Field 2: Type=C/String, Title='EXPIRE', UTC CWA Expiration Time
Field 3: Type=C/String, Title='PROD_ID', IEM Text Product Identifier
Field 4: Type=C/String, Title='NARRATIV', Text Narrative found in raw text
Field 5: Type=N/Double, Title='NUMBER', CWA Number
</pre>

<h4>Archive / Usage Notes:</h4>
<ol>
</ol>
</form>
EOM;

$t->content = $content;
$t->render('single.phtml');
