<?php 
require_once "../../../config/settings.inc.php";
define("IEM_APPID", 17);
require_once "../../../include/forms.php";
require_once "../../../include/myview.php";
require_once "../../../include/network.php";
$nt = new NetworkTable("WFO");

$t = new MyView();
$t->thispage = "gis-";
$t->title = "Archived Local Storm Reports";

$ys = yearSelect2(2003, date("Y"), "year1");
$ms = monthSelect2(0,"month1");
$ds = daySelect2(0, "day1");
$hs = gmtHourSelect(0, "hour1");
$ns = minuteSelect(0, "minute1");
$ys2 = yearSelect2(2003, date("Y"), "year2");
$ms2 = monthSelect2(0,"month2");
$ds2 = daySelect2(0, "day2");
$hs2 = gmtHourSelect(0, "hour2");
$ns2 = minuteSelect(0, "minute2");

$ss = "";
foreach($nt->table as $key => $value){
	$ss .= "<option value='$key'>[$key] ". $value["name"] ."</option>\n";
}

$t->content = <<<EOF
<ol class="breadcrumb">
<li><a href="/GIS/">GIS Mainpage</a></li>
<li class="active">Archived Local Storm Reports Shapefiles</li>
</ol>

<p>This page allows you to generate a GIS shapefile of NWS issued Local Storm
Reports for a time period of your choice.  Please be sure to read the
archive status and dbf schema below. The IEM's archive is certainly not complete or official.  

<p>If you are looking for a real-time source of lsrs, you can find with the following 
files generated every 5 minutes:  <a href="/data/gis/shape/4326/us/lsr_24hour.zip">ESRI Shapefile</a>, 
<a href="/data/gis/shape/4326/us/lsr_24hour.csv">Comma Delimited</a>,
<a href="/data/gis/shape/4326/us/lsr_24hour.geojson">GeoJSON</a>.</p>


<p><strong>Looking to automate the downloading of LSRs?</strong>
<br />You can use the following URI form to get the most recent number of seconds
worth of LSRs.  Note that these times are based on the valid time of the LSR and
not the issuance of the text product itself that contained the LSR.
<br /><code>https://mesonet.agron.iastate.edu/cgi-bin/request/gis/lsr.py?wfo[]=ALL&amp;recent=86400&amp;justcsv=1</code>
<br /><code>https://mesonet.agron.iastate.edu/cgi-bin/request/gis/lsr.py?wfo[]=DMX&amp;wfo[]=DVN&amp;recent=86400&amp;justcsv=1</code>
<br />Omit the justcsv portion to return the zipped shapefile.</p>
		
<form method="GET" action="/cgi-bin/request/gis/lsr.py">
<h4>Limit Weather Forecast Office (WFO)</h4>
<select name="wfo[]" MULTIPLE size="5">
 <option value="ALL" SELECTED>All Available</option>
 {$ss}
</select>
<h4>Select time interval</h4>
<i>(Times are in UTC.  Local Storm Reports with an event time <b>valid</b>
between these times selected below will be included in the output GIS file...)</i>
<table class="table table-condensed table-bordered table-striped">
  <thead><tr>
    <td></td>
    <th>Year</th><th>Month</th><th>Day</th>
    <th>Hour</th><th>Minute</th>
  </tr></thead>
  <tbody>
  <tr>
    <th>Start:</th>
    <td>{$ys}</td>
    <td>{$ms}</td>
    <td>{$ds}</td>
    <td>{$hs}</td>
    <td>{$ns}</td>
  </tr>

  <tr>
    <th>End:</th>
    <td>{$ys2}</td>
    <td>{$ms2}</td>
    <td>{$ds2}</td>
    <td>{$hs2}</td>
    <td>{$ns2}</td>
   </tr>
    </tbody>
</table>

<p><input type='checkbox' name='justcsv' value='true' /> 
    		Giveme only a comma delimited file
     		
<p><input type="submit" value="Giveme shapefile now!">
</form>

<h4>Shapefile DBF schema:</h4>
<pre>
VALID    Timestamp of LSR in GMT/UTC time
MAG      Magnitude value of the LSR
WFO      Weather Forecast Office originating the LSR
TYPECODE 1 character identifier of the report type, IEM specific
TYPETEXT Textual value of LSR type used in report
CITY     Location used for the LSR 
COUNTY   County/Parish of the LSR city
STATE    Two character state abbreviation
SOURCE   Who reported the LSR
REMARK   Text summary with the LSR
LAT      Latitude
LON      Longitude
</pre>

<h4>Archive notes:</h4>
<ul>
 <li>Before 1 Dec 2006, there was no differentiation between Snow and Sleet reports.</li>
</ul>
EOF;
$t->render('single.phtml');
?>
