<?php 
require_once "../../../config/settings.inc.php";
define("IEM_APPID", 128);
require_once "../../../include/myview.php";
require_once "../../../include/forms.php";
require_once "../../../include/imagemaps.php";

$t = new MyView();
$t->title = "Download SPC Watches Shapefile";
$content = <<<EOF
<p>
<ul class="breadcrumb">
<li><a href="/nws/">NWS Mainpage</a></li>
<li class="active">Storm Prediction Center Watches</li>
</ul>
</p>

<p>The IEM maintains an archive of the watch polygons issued by the
Storm Prediction Center since 1997.  Please note that these watches are not the official
spatial bounds anymore as the WCN/ watch by county product is the official
coverage.</p>

<p><strong>Related:</strong>
<a class="btn btn-primary" href="watchwarn.phtml">NWS VTEC Watch Warning Advisory</a>
&nbsp;
<a class="btn btn-primary" href="spc_mcd.phtml">SPC Convective Discussions</a>
&nbsp;
<a class="btn btn-primary" href="spc_outlooks.phtml">SPC Outlooks</a>
&nbsp;
<a class="btn btn-primary" href="wpc_mpd.phtml">WPC Precip Discussions</a>
</p>

<form method="GET" action="/cgi-bin/request/gis/spc_watch.py">
<table class="table">
<thead><tr><th colspan="6">Time Interval for Outlook *Issuance* (UTC)</th></tr></thead>
<tr>
    <td></td><th>Year</th><th>Month</th><th>Day</th>
    <th>Hour</th><th>Minute</th>
</tr>

<tr>
EOF;
$content .= "<th>Start:</th>
    <td>
     ". yearSelect2(1997, date("Y"), "year1") ."
    </td>
    <td>
     ". monthSelect2(0,"month1") ."
    </td>
    <td>
     ". daySelect2(0, "day1") ."
    </td>
    <td>
     ". gmtHourSelect(0, "hour1") ."
    </td>
    <td>
     ". minuteSelect(0, "minute1") ."
    </td>
  </tr>

  <tr>
    <th>End:</th>
    <td>
     ". yearSelect2(1997, date("Y"), "year2") ."
    </td>
    <td>
     ". monthSelect2(date("m"), "month2") ."
    </td>
    <td>
     ". daySelect2(date("d"), "day2") ."
    </td>
    <td>
     ". gmtHourSelect(0, "hour2") ."
    </td>
    <td>
     ". minuteSelect(0, "minute2") ."
    </td>
  </tr>
</table>";

$content .= <<<EOM
<p><input type="submit" value="Giveme data right now!">
</form>

<h4>Shapefile DBF schema:</h4>
<pre>
Field 0: Type=C/String, Title=`ISSUE', UTC Issuance Timestamp YYYYmmddHHMM
Field 1: Type=C/String, Title=`EXPIRE', UTC MCD Expiration Timestamp
Field 2: Type=C/String, Title=`SEL', The 0-9 watch sequence number
Field 3: Type=C/String, Title=`TYPE', TOR or SVR watch
Field 4: Type=N/Double, Title=`NUM', SPC Watch Number
</pre>

<h4>Archive / Usage Notes:</h4>
<ol>
<li>To re-emphasize, these polygons are <strong>not the official</strong>
watch anymore.  The official watch is issued on a county/zone basis.</li>
</ol>
</form>
EOM;

$t->content = $content;
$t->render('single.phtml');

?>