<?php 
require_once "../../../config/settings.inc.php";
define("IEM_APPID", 128);
require_once "../../../include/myview.php";
require_once "../../../include/forms.php";
require_once "../../../include/imagemaps.php";

$t = new MyView();
$t->title = "Download SPC Watches Shapefile";
$content = <<<EOF
<p>
<ul class="breadcrumb">
<li><a href="/nws/">NWS Mainpage</a></li>
<li class="active">Storm Prediction Center Watches</li>
</ul>
</p>

<p>The IEM maintains an archive of the watch polygons issued by the
Storm Prediction Center since 1997.  Please note that these watches are not the official
spatial bounds anymore as the WCN/ watch by county product is the official
coverage.</p>

<p><strong>Related:</strong>
<a class="btn btn-primary" href="watchwarn.phtml">NWS VTEC Watch Warning Advisory</a>
&nbsp;
<a class="btn btn-primary" href="spc_mcd.phtml">SPC Convective Discussions</a>
&nbsp;
<a class="btn btn-primary" href="spc_outlooks.phtml">SPC Outlooks</a>
&nbsp;
<a class="btn btn-primary" href="wpc_mpd.phtml">WPC Precip Discussions</a>
</p>

<form method="GET" action="/cgi-bin/request/gis/spc_watch.py">
<table class="table">
<thead><tr><th colspan="6">Time Interval for Outlook *Issuance* (UTC)</th></tr></thead>
<tr>
    <td></td><th>Year</th><th>Month</th><th>Day</th>
    <th>Hour</th><th>Minute</th>
</tr>

<tr>
EOF;
$content .= "<th>Start:</th>
    <td>
     ". yearSelect2(1997, date("Y"), "year1") ."
    </td>
    <td>
     ". monthSelect2(0,"month1") ."
    </td>
    <td>
     ". daySelect2(0, "day1") ."
    </td>
    <td>
     ". gmtHourSelect(0, "hour1") ."
    </td>
    <td>
     ". minuteSelect(0, "minute1") ."
    </td>
  </tr>

  <tr>
    <th>End:</th>
    <td>
     ". yearSelect2(1997, date("Y"), "year2") ."
    </td>
    <td>
     ". monthSelect2(date("m"), "month2") ."
    </td>
    <td>
     ". daySelect2(date("d"), "day2") ."
    </td>
    <td>
     ". gmtHourSelect(0, "hour2") ."
    </td>
    <td>
     ". minuteSelect(0, "minute2") ."
    </td>
  </tr>
</table>";

$content .= <<<EOM
<p><input type="submit" value="Giveme data right now!">
</form>

<h4>Shapefile DBF schema:</h4>
<pre>
Field 0: Type=C/String, Title=`ISSUE', UTC Issuance Timestamp YYYYmmddHHMM
Field 1: Type=C/String, Title=`EXPIRE', UTC MCD Expiration Timestamp
Field 2: Type=C/String, Title=`SEL', The 0-9 watch sequence number
Field 3: Type=C/String, Title=`TYPE', TOR or SVR watch
Field 4: Type=N/Double, Title=`NUM', SPC Watch Number
Field 5: Type=N/Double, Title=`P_TORTWO', PROB OF 2 OR MORE TORNADOES
Field 6: Type=N/Double, Title=`P_TOREF2', PROB OF 1 OR MORE STRONG /EF2-EF5/ TORNADOES
Field 7: Type=N/Double, Title=`P_WIND10', PROB OF 10 OR MORE SEVERE WIND EVENTS
Field 8: Type=N/Double, Title=`P_WIND65', PROB OF 1 OR MORE WIND EVENTS >= 65 KNOTS 
Field 9: Type=N/Double, Title=`P_HAIL10', PROB OF 10 OR MORE SEVERE HAIL EVENTS
Field 10: Type=N/Double, Title=`P_HAIL2I', PROB OF 1 OR MORE HAIL EVENTS >= 2 INCHES
Field 11: Type=N/Double, Title=`P_HAILWND' PROB OF 6 OR MORE COMBINED SEVERE HAIL/WIND EVENTS
Field 12: Type=N/Double, Title=`MAX_HAIL', MAX HAIL /INCHES/ 
Field 13: Type=N/Double, Title=`MAX_GUST', MAX WIND GUSTS SURFACE /KNOTS/
Field 14: Type=N/Double, Title=`MAX_TOPS', MAX TOPS /X 100 FEET/
Field 15: Type=N/Double, Title=`MV_DRCT', MEAN STORM MOTION VECTOR /DEGREES/
Field 16: Type=N/Double, Title=`MV_SKNT', MEAN STORM MOTION VECTOR /KNOTS/
Field 17: Type=N/Integer, Title=`IS_PDS', PARTICULARLY DANGEROUS SITUATION
</pre>

<h4>Archive / Usage Notes:</h4>
<ol>
<li><strong>30 April 2022:</strong> Associated probabilities found in the <code>WWP</code>
 product are now included as attributes.  This archive goes back to about May 2006.</li>
<li>To re-emphasize, these polygons are <strong>not the official</strong>
watch anymore.  The official watch is issued on a county/zone basis.</li>
</ol>
</form>
EOM;

$t->content = $content;
$t->render('single.phtml');
