<?php 
require_once "../../../config/settings.inc.php";
define("IEM_APPID", 125);
require_once "../../../include/myview.php";
require_once "../../../include/forms.php";
require_once "../../../include/imagemaps.php";

$t = new MyView();
$t->thispage = "gis-";
$t->title = "Download SPC Convective/Fire Weather Outlooks Shapefile";
$content = <<<EOF
<h3>Storm Prediction Center Convective and Fire Weather Outlooks</h3>

<p>The IEM attempts to process and archive the convective and fire weather
outlooks issued by the Storm Prediction Center. This processing is done by
parsing the PTS product via <a href="https://github.com/akrherz/pyIEM/blob/main/src/pyiem/nws/products/spcpts.py">pyIEM decoder</a>. 
Recently, the SPC website has added direct single outlook downloads in various
GIS formats. 
<strong>Your best data quality will come from scraping their website</strong>, but
maybe that approach is not for all users of this data! So here it is, a means
to bulk download the IEM's SPC Outlook database.</p>
 
<form method="GET" action="/cgi-bin/request/gis/spc_outlooks.py">
<table class="table">
<thead><tr><th colspan="6">Time Interval for Outlook *Issuance* (UTC)</th></tr></thead>
<tr>
    <td></td><th>Year</th><th>Month</th><th>Day</th>
    <th>Hour</th><th>Minute</th><th>Outlook Type:</th><th>Outlook Day:</th>
</tr>

<tr>
EOF;
$content .= "<th>Start:</th>
    <td>
     ". yearSelect2(2002, date("Y"), "year1") ."
    </td>
    <td>
     ". monthSelect2(0,"month1") ."
    </td>
    <td>
     ". daySelect2(0, "day1") ."
    </td>
    <td>
     ". gmtHourSelect(0, "hour1") ."
    </td>
    <td>
     ". minuteSelect(0, "minute1") ."
    </td>
    <td rowspan=\"2\">
    <input id=\"tc\" type=\"checkbox\" name=\"type\" value=\"C\" checked>
    <label for=\"tc\">Convective</label>
    <br /><input id=\"tf\" type=\"checkbox\" name=\"type\" value=\"F\" checked>
    <label for=\"tf\">Fire Weather</label>
    </td>
    <td rowspan=\"2\">
    <input id=\"d1\" type=\"checkbox\" name=\"d\" value=\"1\" checked>
    <label for=\"d1\">1</label>
    <input id=\"d2\" type=\"checkbox\" name=\"d\" value=\"2\" checked>
    <label for=\"d2\">2</label>
    <input id=\"d3\" type=\"checkbox\" name=\"d\" value=\"3\" checked>
    <label for=\"d3\">3</label>
    <input id=\"d4\" type=\"checkbox\" name=\"d\" value=\"4\" checked>
    <label for=\"d4\">4</label><br />
    <input id=\"d5\" type=\"checkbox\" name=\"d\" value=\"5\" checked>
    <label for=\"d5\">5</label>
    <input id=\"d6\" type=\"checkbox\" name=\"d\" value=\"6\" checked>
    <label for=\"d6\">6</label>
    <input id=\"d7\" type=\"checkbox\" name=\"d\" value=\"7\" checked>
    <label for=\"d7\">7</label>
    <input id=\"d8\" type=\"checkbox\" name=\"d\" value=\"8\" checked>
    <label for=\"d8\">8</label>
    </td>
  </tr>

  <tr>
    <th>End:</th>
    <td>
     ". yearSelect2(2002, date("Y"), "year2") ."
    </td>
    <td>
     ". monthSelect2(0,"month2") ."
    </td>
    <td>
     ". daySelect2(0, "day2") ."
    </td>
    <td>
     ". gmtHourSelect(0, "hour2") ."
    </td>
    <td>
     ". minuteSelect(0, "minute2") ."
    </td>
  </tr>
</table>";

$content .= <<<EOM
<p><input type="submit" value="Giveme data right now!">
</form>

<h4>Shapefile DBF schema:</h4>
<pre>
Field 0: Type=C/String, Title='ISSUE', Outlook Beginning Valid Time UTC
Field 1: Type=C/String, Title='EXPIRE', Outlook Ending Valid Time UTC
Field 2: Type=C/String, Title='PRODISS', Timestamp of Product Issuance UTC
Field 3: Type=C/String, Title='TYPE', Either C=Convective, F=Fire Weather
Field 4: Type=N/Double, Title='DAY', Day 1 through 8 for the outlook
Field 5: Type=C/String, Title='THRESHOLD', Threshold Label
Field 6: Type=C/String, Title='CATEGORY', Category of Threshold Label
Field 7: Type=N/Double, Title='CYCLE', The generalized forecast issuance hour
</pre>

<h4>Archive / Usage Notes:</h4>
<ol>
 <li><strong>1 Apr 2021:</strong> An assessment was made of the archive
 completeness and found 99.9% coverage.  Some of the holes are due to
 lost PTS text products yet to be found and others are due to errors within
 the PTS product causing it to be generally unusable.</li>
 <li>The polygons returned by this download represent the full extent of the
 threshold bounds and not some bisected area only valid for the given threshold.
 Rewording, if you download an outlook that had a moderate risk polygon.  That area
 would also be covered by an enhanced, slight, and general thunderstorm polygon.</li>
 <li>A complication with using this dataset is that all outlooks are returned, the
 <code>CYCLE</code> attribute attempts to define a canonical outlook for a given
 issuance cycle.  For example, the Day 1 20Z convective outlook may get issued three
 times for various reasons.  The download contains all three, but two of them will
 have a cycle of `-1` and the other will have a `20`.</li>
 <li>Presently, the service only returns outlooks that had actual geographies
 associated with the outlook.  For example, if there was no Day 5 area in the
 outlook, no entries are included in the download result.</li>
 </ol>
</form>
EOM;

$t->content = $content;
$t->render('single.phtml');

?>