<?php 
include("../../../config/settings.inc.php");

function get_file_size($filename, $size_in = 'MB')
{
$size_in_bytes = filesize($filename);
 
// Precision: decimals at the end for each type of size
 
if($size_in == 'B')
{
$size = $size_in_bytes;
$precision = 0;
}
elseif($size_in == 'KB')
{
$size = (($size_in_bytes / 1024));
$precision = 2;
}
elseif($size_in == 'MB')
{
$size = (($size_in_bytes / 1024) / 1024);
$precision = 2;
}
elseif($size_in == 'GB')
{
$size = (($size_in_bytes / 1024) / 1024) / 1024;
$precision = 2;
}
 
$size = round($size, $precision);
 
    return $size.' '.$size_in;
}

$TITLE = "IEM | Watch/Warn shapefiles";
include("$rootpath/include/forms.php");
include("$rootpath/include/header.php"); ?>

<h3 class="heading">Archived NWS Watch/Warning GIS Shapefiles</h3>

<p>This page allows you to generate a GIS shapefile of NWS issued watches
and warnings for a time period of your choice.  Please be sure to read the
archive status and dbf schema below. The IEM's archive is certainly not complete or official.  If you are looking for a real-time source of warning shapefiles, you can find that <a href="http://mesonet.agron.iastate.edu/data/gis/shape/4326/us/current_ww.zip">here.</a></p>

<div class="warning"> Due to transient server load or other issues, this application sometimes fails to generate output.  You may wish to try shorting the duration of your request or email <a href="../../info/contacts.php">us</a> for help.
</div>

<table><tr><td width="50%" valign="top">

<form method="GET" action="/cgi-bin/request/gis/watchwarn.py">
<h4>Select time interval</h4>
<i>(Times are in UTC.  Watches/Warnings <b>issued</b> between these times
will be included in the output GIS file...)</i>
<table>
  <tr>
    <td></td>
    <th>Year</th><th>Month</th><th>Day</th>
    <th>Hour</th><th>Minute</th>
  </tr>

  <tr>
    <th>Start:</th>
    <td>
     <?php echo yearSelect2(1986, date("Y"), "year1"); ?>
    </td>
    <td>
     <?php echo monthSelect2(0,"month1"); ?>
    </td>
    <td>
     <?php echo daySelect2(0, "day1"); ?>
    </td>
    <td>
     <?php echo gmtHourSelect(0, "hour1"); ?>
    </td>
    <td>
     <?php echo minuteSelect(0, "minute1"); ?>
    </td>
  </tr>

  <tr>
    <th>End:</th>
    <td>
     <?php echo yearSelect2(1986, date("Y"), "year2"); ?>
    </td>
    <td>
     <?php echo monthSelect2(0,"month2"); ?>
    </td>
    <td>
     <?php echo daySelect2(0, "day2"); ?>
    </td>
    <td>
     <?php echo gmtHourSelect(0, "hour2"); ?>
    </td>
    <td>
     <?php echo minuteSelect(0, "minute2"); ?>
    </td>
  </tr>
</table>

<br /><input type="checkbox" name="limit0" value="yes">Limit Output to Tornado, Severe Thunderstorm, Marine, and Flash Flood Warnings
<br /><input type="checkbox" name="limit1" value="yes">Limit Output to only Storm Based Warnings

<p><input type="submit" value="Giveme shapefile now!">
</form>

<h4>Shapefile DBF schema:</h4>
<table>
<tr><th>WFO</th><td>Three letter ID for issuing Weather Forecast Office</td></tr>
<tr><th>ISSUED   </th><td>String representing product initial valid GMT timestamp YYYYMMDDHHMM</td></tr>
<tr><th>EXPIRED  </th><td>String representing product expiration, this is not the original 
         product expiration, but the actual time the product was no longer
         valid.  For example, the product could have been extended in time
         or cancelled.</td></tr>
<tr><th>PHENOM   </th><td>VTEC phenomena code.  Ex)  SV == Severe Thunderstorm , TO == Tornado</td></tr>
<tr><th>GTYPE    </th><td>Geographical type of polygon.  C == County, P == Polygon</td></tr>
<tr><th>SIG      </th><td>VTEC significance. Ex) A == Watch, W == Warning</td></tr>
<tr><th>ETN      </th><td>VTEC Event Tracking Number</td></tr>
<tr><th>STATUS   </th><td>VTEC last value of status for the product.  Often EXP == Expire</td></tr>
<tr><th>NWS_UGC  </th><td>NWS code used for a zone of a county</td></tr>
<tr><th>AREA_KM2 </th><td>Area of the geometry in sq kilometers (Projection: EPSG 2163)</td></tr>
</table>

</td><td width="50%" valign="top">
<h4>Pre-generated zip files</h4>

<p>These files are same as you could download from the form on the left, just
you don't have to wait so long!</p>

<table cellpadding="2" cellspacing="0" border="1">
<tr><th>Year</th><th>All</th><th>Limit Tor,Svr,Mar,FF</th><th>Limit Storm Based</th></tr>
<?php 
for($year=1986;$year<date("Y");$year++){
  $allurl = sprintf("<a href=\"%s/pickup/wwa/%s_all.zip\">Zip</a>", $rooturl, $year);
  $allfp = "/mesonet/share/pickup/wwa/${year}_all.zip";
  $tsmfurl = sprintf("<a href=\"%s/pickup/wwa/%s_tsmf.zip\">Zip</a>", $rooturl, $year);
  $tsmffp = "/mesonet/share/pickup/wwa/${year}_tsmf.zip";
  $sbwurl = "N/A";
  $sbwfp = "/dev/zero";
  if ($year > 2001){
    $sbwurl = sprintf("<a href=\"%s/pickup/wwa/%s_tsmf_sbw.zip\">Zip</a>", $rooturl, $year);
    $sbwfp = "/mesonet/share/pickup/wwa/${year}_tsmf_sbw.zip";
  }
  echo sprintf("<tr><th>%s</th><td>%s (%s)</td><td>%s (%s)</td><td>%s (%s)</td></tr>", $year,
   $allurl, get_file_size($allfp), $tsmfurl, get_file_size($tsmffp),
   $sbwurl, get_file_size($sbwfp) );
}
?>
</table>

</td></tr></table>

<h4>Archive status:</h4>
<table border="1" cellpadding="3">
<tr><th>Dataset component</th><th>Start Time</th><th>Notes</th></tr>
<tr>
 <td>Tornado<br />Severe T'storm<br /> Flash Flood<br />Special Marine</td>
 <td>1 Jan 2002 (Polygons)
     <br />1 Jan 1986 (Counties)</td>
 <td>Only the initial polygon is used.  Polygon updates in the SVS
  statements are ignored.  The VTEC attributes didn't appear until
  they became operational.</td>
</tr>
<tr>
 <td>All VTEC watch/warn</td>
 <td>12 Nov 2005</td>
 <td>Products other than TOR, SVR</td>
</tr>
<tr>
 <td>SVR,TOR Watch by County</td>
 <td>12 Nov 2005</td>
 <td></td>
</tr>
</table>

<?php include("$rootpath/include/footer.php"); ?>
