<?php 
include("../../../config/settings.inc.php");

$TITLE = "IEM | Watch/Warn shapefiles";
include("$rootpath/include/forms.php");
include("$rootpath/include/header.php"); ?>

<h3 class="heading">Archived NWS Watch/Warning GIS Shapefiles</h3>

<p>This page allows you to generate a GIS shapefile of NWS issues watches
and warnings for a time period of your choice.  Please be sure to read the
archive status and dbf schema below. The IEM's archive is certainly not complete or official.  If you are looking for a real-time source of warning shapefiles, you can find that <a href="http://mesonet.agron.iastate.edu/data/gis/shape/4326/us/current_ww.zip">here.</a></p>

<div class="warning"> Due to transient server load or other issues, this application sometimes fails to generate output.  You may wish to try shorting the duration of your request or email <a href="../../info/contacts.php">us</a> for help.
</div>

<form method="GET" action="/cgi-bin/request/gis/watchwarn.py">
<h4>Select time interval</h4>
<i>(Times are in UTC.  Watches/Warnings <b>issued</b> between these times
will be included in the output GIS file...)</i>
<table>
  <tr>
    <td></td>
    <th>Year</th><th>Month</th><th>Day</th>
    <th>Hour</th><th>Minute</th>
  </tr>

  <tr>
    <th>Start:</th>
    <td rowspan="2">
     <?php echo yearSelect(2002, date("Y"), "year"); ?>
    </td>
    <td>
     <?php echo monthSelect2(0,"month1"); ?>
    </td>
    <td>
     <?php echo daySelect2(0, "day1"); ?>
    </td>
    <td>
     <?php echo gmtHourSelect(0, "hour1"); ?>
    </td>
    <td>
     <?php echo minuteSelect(0, "minute1"); ?>
    </td>
  </tr>

  <tr>
    <th>End:</th>
    <td>
     <?php echo monthSelect2(0,"month2"); ?>
    </td>
    <td>
     <?php echo daySelect2(0, "day2"); ?>
    </td>
    <td>
     <?php echo gmtHourSelect(0, "hour2"); ?>
    </td>
    <td>
     <?php echo minuteSelect(0, "minute2"); ?>
    </td>
  </tr>
</table>

<br /><input type="checkbox" name="limit0" value="yes">Limit Output to Tornado, Severe Thunderstorm, Marine, and Flash Flood Warnings
<br /><input type="checkbox" name="limit1" value="yes">Limit Output to only Storm Based Warnings

<p><input type="submit" value="Giveme shapefile now!">
</form>

<h4>Shapefile DBF schema:</h4>
<pre>
WFO     Three letter ID for issuing Weather Forecast Office
ISSUED  String representing product initial valid GMT timestamp YYYYMMDDHHMM
EXPIRED String representing product expiration, this is not the original 
        product expiration, but the actual time the product was no longer
        valid.  For example, the product could have been extended in time
        or cancelled.
PHENOM  VTEC phenomena code.  Ex)  SV == Severe Thunderstorm , TO == Tornado
GTYPE   Geographical type of polygon.  C == County, P == Polygon
SIG     VTEC significance. Ex) A == Watch, W == Warning
ETN     VTEC Event Tracking Number
STATUS  VTEC last value of status for the product.  Often EXP == Expire
NWS_UGC NWS code used for a zone of a county
</pre>

<h4>Archive status:</h4>
<table border="1" cellpadding="3">
<tr><th>Dataset component</th><th>Start Time</th><th>Notes</th></tr>
<tr>
 <td>TOR / SVR Warnings</td>
 <td>1 Jan 2002 (Polygons)
     <br />1 Jan 2002 (Counties)</td>
 <td>Only the initial polygon is used.  Polygon updates in the SVS
  statements are ignored.  The VTEC attributes didn't appear until
  they became operational.</td>
</tr>
<tr>
 <td>All VTEC watch/warn</td>
 <td>12 Nov 2005</td>
 <td>Products other than TOR, SVR</td>
</tr>
<tr>
 <td>SVR,TOR Watch by County</td>
 <td>12 Nov 2005</td>
 <td></td>
</tr>
</table>

<?php include("$rootpath/include/footer.php"); ?>
