<?php 
require_once "../../../config/settings.inc.php";
define("IEM_APPID", 129);
require_once "../../../include/myview.php";
require_once "../../../include/forms.php";
require_once "../../../include/imagemaps.php";

$t = new MyView();
$t->title = "Download WPC Mesoscale Precipitation Discussion Shapefile";
$content = <<<EOF
<p>
<ul class="breadcrumb">
<li><a href="/nws/">NWS Mainpage</a></li>
<li class="active">Weather Prediction Center Mesoscale Precipitation Discussions</li>
</ul>
</p>

<p>The IEM has a database archive of WPC Mesocale Precipitation Discussions since fall 2017. This
page offers a shapefile download of these.
<a href="/cgi-bin/request/gis/wpc_mpd.py?help" class="btn btn-default">Backend Documentation</a> exists
for those wishing to script against this service.
</p>

<p><strong>Related:</strong>
<a class="btn btn-primary" href="watchwarn.phtml">NWS VTEC Watch Warning Advisory</a>
&nbsp;
<a class="btn btn-primary" href="spc_mcd.phtml">SPC Convective Discussions</a>
&nbsp;
<a class="btn btn-primary" href="outlooks.phtml">SPC/WPC Outlooks</a>
&nbsp;
<a class="btn btn-primary" href="spc_watch.phtml">SPC Watch Polygons</a>
</p>

<form method="GET" action="/cgi-bin/request/gis/wpc_mpd.py">
<table class="table">
<thead><tr><th colspan="6">Time Interval for MPD *Issuance* (UTC)</th></tr></thead>
<tr>
    <td></td><th>Year</th><th>Month</th><th>Day</th>
    <th>Hour</th><th>Minute</th>
</tr>

<tr>
EOF;
$content .= "<th>Start:</th>
    <td>
     ". yearSelect2(2017, date("Y"), "year1") ."
    </td>
    <td>
     ". monthSelect2(0,"month1") ."
    </td>
    <td>
     ". daySelect2(0, "day1") ."
    </td>
    <td>
     ". gmtHourSelect(0, "hour1") ."
    </td>
    <td>
     ". minuteSelect(0, "minute1") ."
    </td>
  </tr>

  <tr>
    <th>End:</th>
    <td>
     ". yearSelect2(2017, date("Y"), "year2") ."
    </td>
    <td>
     ". monthSelect2(date("m"), "month2") ."
    </td>
    <td>
     ". daySelect2(date("d"), "day2") ."
    </td>
    <td>
     ". gmtHourSelect(0, "hour2") ."
    </td>
    <td>
     ". minuteSelect(0, "minute2") ."
    </td>
  </tr>
</table>";

$content .= <<<EOM
<p><input type="submit" value="Giveme data right now!">
</form>

<h4>Shapefile DBF schema:</h4>
<pre>
Field 0: Type=C/String, Title=`ISSUE', UTC Issuance Timestamp YYYYmmddHHMM
Field 1: Type=C/String, Title=`EXPIRE', UTC MCD Expiration Timestamp
Field 2: Type=C/String, Title=`PROD_ID', IEM Product ID (see below)
Field 3: Type=N/Double, Title=`YEAR', YEAR of MCD
Field 4: Type=N/Double, Title=`NUM', SPC MCD Number
Field 6: Type=C/String, Title=`CONCERN', WPC MPD concerning heading

</pre>

<h4>Archive / Usage Notes:</h4>
<ol>
<li>The <code>PROD_ID</code> DBF field is a string the IEM uses to identify
NWS Text products and can be used to call an IEM API to fetch the text of
this product. https://mesonet.agron.iastate.edu/api/1/nwstext/{PROD_ID}</li>

<li>The <code>YEAR</code> and <code>NUM</code> fields can be used to construct
a stable URL into SPC's website like so: https://www.spc.noaa.gov/products/md/{year}/md{NUM:04i}.html</li>
</ol>
</form>
EOM;

$t->content = $content;
$t->render('single.phtml');

?>