<?php 
require_once "../../../config/settings.inc.php";
define("IEM_APPID", 157);
require_once "../../../include/myview.php";
require_once "../../../include/iemprop.php";
$gmapskey = get_iemprop("google.maps.key");
$t = new MyView();

$t->jsextra = <<<EOF
<script type="text/javascript" src="https://extjs.cachefly.net/ext/gpl/5.1.0/build/ext-all.js"></script>
<script type="text/javascript" src="/ext/ux/ExcelGridPanel.js"></script>
<script type="text/javascript" src="search.js?v=4"></script>
EOF;
$t->headextra = <<<EOF
<script src="https://maps.googleapis.com/maps/api/js?key={$gmapskey}" type="text/javascript"></script>
<link rel="stylesheet" type="text/css" href="https://extjs.cachefly.net/ext/gpl/5.1.0/build/packages/ext-theme-neptune/build/resources/ext-theme-neptune-all.css"/>
		  <style>
  .map {
    width: 100%;
    height: 400px;
    float: left;
  }
		#warntable { float: right; }
		</style>
EOF;
$t->thispage ="severe-spcoutlook";
$t->title = "SPC Convective Outlook Search by Point";

$t->content = <<<EOF
<ol class="breadcrumb">
  <li><a href="/nws/">NWS Mainpage</a></li>
  <li class="active">SPC Outlook Search by Point</li>
</ol>
<p>This application allows you to search of Storm Prediction Center outlooks by
point.  The data presented is based on unofficial processing and archving done
by the IEM.</p>

<div class="alert alert-info"><strong>Troubles downloading Excel File?</strong>
<br />It turns out that making an export to Excel option that works for all
	variants of Microsoft Office and web browsers is very difficult.  Here are
	some tips.
<ul>
	<li>When you "Export to Excel", you should get a file saved in your downloads
		folder with a .xml ending.</li>
	<li>When you double click this .xml file, Microsoft Windows may not know
		what to do with the file.  Try opening Excel first and then go to 
		File -&gt; Open to attempt to open the file.</li>
	<li>If that fails, attempt to right click the file and go to 'Open With'
		and then select Excel from the available options.</li>
</ul>
		</div>

<div class="alert alert-warning"><strong>Beta Testing!!!</strong>
<br />This application is in beta phase to get some friendly testing and feedback.
There are likely some bugs and rough spots here, so please let <a href="/info/contacts.php">daryl know</a>
 your feedback. 
		</div>
	
<h3><a name="bypoint">1.</a> Search for Outlooks by Point</h3>

<br />
This section allows you to specify a point on the map below by dragging the 
marker to where you are interested in.  Once you stop dragging the marker, the
grid will update and provide a listing of the outlooks found.  
<br clear="all" />
<div class="row">
	<div class="col-md-4">
		<p><strong>Either enter coordinates manually:</strong><br />
		<i>Latitude (deg N):</i> <input size="8" id="lat"><br />
		<i>Longitude (deg E):</i> <input size="8" id="lon">
		<br /><input type="checkbox" id="last" name="last" value="1">
	List Most Recent <input id="events" type="text" name="events" size="3" value="1"> Event(s)	
		<br />Select Outlook: <input type="radio" name="day" value="1" checked>Day 1 &nbsp;
		<input type="radio" name="day" value="2">Day 2 &nbsp;
		<input type="radio" name="day" value="3">Day 3

		<br />Select Category:
		<input type="radio" name="cat" value="categorical" checked>Categorical &nbsp;
		<input type="radio" name="cat" value="hail">Hail &nbsp;
		<input type="radio" name="cat" value="tornado">Tornado &nbsp;
		<input type="radio" name="cat" value="wind">Wind

		<br /><button class="btn btn-default" id="manualpt">Update</button>
		</p>
		<p><strong>Or drag marker to select coordinate:</strong><br />
		<div id="map" class="map"></div>
	</div>
		<div class="col-md-8"><div id="warntable" style="width: 100%"></div></div>
</div>

		
EOF;
$t->render('single.phtml');
?>
