<?php
require_once "../../../config/settings.inc.php";
define("IEM_APPID", 157);
require_once "../../../include/mlib.php";
force_https();
require_once "../../../include/myview.php";
require_once "../../../include/iemprop.php";
$t = new MyView();
$OL = "9.2.4";

$t->jsextra = <<<EOF
<script src='/vendor/openlayers/{$OL}/ol.js'></script>
<script type="text/javascript" src="/js/olselect-lonlat.js"></script>
<script type="text/javascript" src="search.js?v=2"></script>
EOF;
$t->headextra = <<<EOF
<link rel="stylesheet" type="text/css" href="/vendor/openlayers/{$OL}/ol.css" />
<style>
.map {
    width: 100%;
    height: 400px;
    float: left;
}
</style>
EOF;
$t->title = "SPC Convective Outlook + Discussion + Watch Search by Point";

$t->content = <<<EOF
<ol class="breadcrumb">
  <li><a href="/nws/">NWS Mainpage</a></li>
  <li class="active">SPC Convective Outlook + Discussion + Watch Search by Point</li>
</ol>
<p>This application allows you to search an archive of Storm Prediction Center (SPC)
Convective Outlooks, Mesoscale Convective Discussions (MCD)s, and Convective Watches.
This archive is <strong>unofficial</strong> and based on IEM's processing of text products issued by
the SPC. Each tab presents buttons that allow for a download of the data in
Excel or CSV format and a direct link to the JSON service backending the
table.</p>

<div class="clearfix"></div>

<div class="row">
    <div class="col-md-4 well">
    <h3>Search by Point</h3>
        <p><strong>Either enter coordinates manually:</strong><br />
        <i>Latitude (deg N):</i> <input size="8" id="lat"><br />
        <i>Longitude (deg E):</i> <input size="8" id="lon">
        <br /><strong>Outlook Search Options:</strong>
        <br />
        <input type="checkbox" id="last" name="last" value="1">
    List Most Recent <input id="events" type="text" name="events" size="3" value="1"> Event(s)	
        <br />Select Outlook: <input type="radio" name="day" value="1" checked id="d1">
        <label for="d1">Day 1</label> &nbsp;
        <input type="radio" name="day" value="2" id="d2">
        <label for="d2">Day 2</label> &nbsp;
        <input type="radio" name="day" value="3" id="d3">
        <label for="d3">Day 3</label>

        <br />Select Category:<br/>
        <input type="radio" name="cat" value="categorical" checked id="categorical">
        <label for="categorical">Categorical</label> &nbsp;
        <input type="radio" name="cat" value="hail" id="hail">
        <label for="hail">Hail</label> &nbsp;
        <input type="radio" name="cat" value="tornado" id="tornado">
        <label for="tornado">Tornado</label> &nbsp;
        <input type="radio" name="cat" value="wind" id="wind">
        <label for="wind">Wind</label>

        <br /><button class="btn btn-default" id="manualpt">Update</button>
        </p>
        <p><strong>Or drag marker to select coordinate:</strong><br />
        <div id="map" class="map"></div>
    </div>
    <div class="col-md-8">
    <h3>Results of Point Search</h3>
<div id="thetabs">	
    <ul class="nav nav-pills">
        <li class="active"><a href="#1a" data-toggle="tab">Convective Outlooks</a></li>
        <li><a href="#2a" data-toggle="tab">Mesoscale Convective Discussions</a></li>
        <li><a href="#3a" data-toggle="tab">Watch Polygons</a></li>
    </ul>

    <div class="tab-content clearfix">
        <div class="tab-pane active" id="1a">

<p>This archive dates back until <strong>1987</strong>.</p>

<div class="pull-right">
    <a class="btn btn-default" href="/" target="_blank" id="outlooks_excel">
    <i class="fa fa-table"></i> Download as Excel</a>
    <a class="btn btn-default" href="/" target="_blank" id="outlooks_csv">
    <i class="fa fa-table"></i> Download as CSV</a>
    <a class="btn btn-default" href="/" target="_blank" id="outlooks_link">
    <i class="fa fa-link"></i> JSON-P Webservice</a>
</div>

<table id="outlooks" class="table table-condensed table-bordered table-striped">
<caption></caption>
<thead>
<tr><th>Day</th><th>Threshold</th><th>Outlook Issued At (UTC)</th><th>Outlook Begins (UTC)</th>
<th>Outlook Expires (UTC)</th></tr>
</thead>
<tbody>

</tbody>
</table>
        <div id="outlook_spinner" style="display: none;"><img src="/images/wait24trans.gif"> Loading</div>

        </div>
        <div class="tab-pane" id="2a">

<p>This archive dates back until <strong>20 October 2008</strong> and is based
on the MCD polygon included within the text.</p>

<div class="pull-right">
    <a class="btn btn-default" href="/" target="_blank" id="mcds_excel">
    <i class="fa fa-table"></i> Download as Excel</a>
    <a class="btn btn-default" href="/" target="_blank" id="mcds_csv">
    <i class="fa fa-table"></i> Download as CSV</a>
    <a class="btn btn-default" href="/" target="_blank" id="mcds_link">
    <i class="fa fa-link"></i> JSON-P Webservice</a>
</div>


<table id="mcds" class="table table-condensed table-bordered table-striped">
<caption></caption>
<thead>
<tr><th>Discussion Number</th>
<th>UTC Valid</th>
<th>UTC Expire</th>
<th>Watch Confidence</th>
<th>Concerning</th>
</tr>
</thead>
<tbody>

</tbody>
</table>
        <div id="mcd_spinner" style="display: none;"><img src="/images/wait24trans.gif"> Loading</div>
        </div><!-- ./2a -->
        <div class="tab-pane" id="3a">

<p>This archive dates back until <strong>1997</strong> and uses the initial watch
polygon included in the SAW product.  <strong>These polygons are not the official
watches!</strong>  You should use the <a href="/vtec/search.php">VTEC Search</a>
tool to get more accurate results for the watch-by-county era.</p>

<div class="pull-right">
    <a class="btn btn-default" href="/" target="_blank" id="watches_excel">
    <i class="fa fa-table"></i> Download as Excel</a>
    <a class="btn btn-default" href="/" target="_blank" id="watches_csv">
    <i class="fa fa-table"></i> Download as CSV</a>
    <a class="btn btn-default" href="/" target="_blank" id="watches_link">
    <i class="fa fa-link"></i> GeoJSON-P Webservice</a>
</div>

<table id="watches" class="table table-condensed table-bordered table-striped">
<caption></caption>
<thead>
<tr><th>Watch Number</th><th>Type</th><th>UTC Valid</th><th>UTC Expire</th>
<th>Max Hail Size</th><th>Max Wind Speed</th><th>Is PDS?</th>
</tr>
</thead>
<tbody>

</tbody>
</table>
        <div id="watch_spinner" style="display: none;"><img src="/images/wait24trans.gif"> Loading</div>
        </div>   
    </div>
</div><!-- ./thetabs -->

    </div><!-- ./col-md-8 -->
</div><!-- ./row -->

EOF;
$t->render('full.phtml');
