<?php 

include_once "../../../config/settings.inc.php";
include_once "../../../include/myview.php";
include_once "../../../include/forms.php";
include_once "../../../include/imagemaps.php";
include_once "../../../include/forms.php";
$formhtml = "";
$image = "";
$t = new MyView();
$t->thispage = "networks-coop";
$t->title = "NWS COOP Data Plotter";

$q = isset($_GET["q"]) ? intval($_GET["q"]) : 0;
$network = isset($_GET["network"]) ? $_GET["network"]: "IACLIMATE";

// Available Plots
$data = file_get_contents("http://iem.local/COOP/auto/meta/0.json");
$jobj = json_decode($data);
$ar = Array();
while (list($k,$v) = each($jobj->plots)){
	if (intval($k) == $q){
		$t->title = $v;
	}
	$ar[$k] = $v;
}
$pselect = make_select("q", $q, $ar);

$states = Array(
		'IA' => 'Iowa',
          'IL'=> 'Illinois',
          'KS'=> 'Kansas',
		  'KY'=> 'Kentucky',
		  'MI'=> 'Michigan',
          'MN'=> 'Minnesota',
        'MO'=> 'Missouri',
          'NE'=> 'Nebraska',
          'ND'=> 'North Dakota',
          'OH'=> 'Ohio',
          'SD'=> 'South Dakota',
          'WI'=> 'Wisconsin',
        
);

$networks = Array("ILCLIMATE" => "Illinois",
		"INCLIMATE" => "Indiana",
		"IACLIMATE" => "Iowa",
		"KSCLIMATE" => "Kansas",
		"KYCLIMATE" => "Kentucky",
		"MICLIMATE" => "Michigan",
		"MNCLIMATE" => "Minnesota",
		"MOCLIMATE" => "Missouri",
		"NECLIMATE" => "Nebraska",
		"NDCLIMATE" => "North Dakota",
		"OHCLIMATE" => "Ohio",
		"SDCLIMATE" => "South Dakota",
		"WICLIMATE" => "Wisconsin"
);


if (isset($_GET["q"])){
	$q = intval($_GET["q"]);
	$data = file_get_contents("http://iem.local/COOP/auto/meta/$q.json");
	$jobj = json_decode($data);
	$imguri = "/COOP/auto/plot/$q/";
	$pltvars = Array();
	$form = "";
	while (list($k,$v) = each($jobj->arguments)){
		$value = isset($_GET[$v->name]) ? $_GET[$v->name] : $v->default;
		$pltvars[] = sprintf("%s:%s", $v->name, $value);
		if ($v->type == "station"){
			$netselect = make_select("network", $network, $networks, "onNetworkChange");
			$form .= "<tr><td>". $v->label ."</td><td>". $netselect ." ". networkSelect($network, $value) ."</td></tr>";
		}
		if ($v->type == "clstate"){
			$netselect = make_select($v->name, $value, $states);
			$form .= "<tr><td>". $v->label ."</td><td>". $netselect ."</td></tr>";
		}
		if ($v->type == "text"){
			$form .= "<tr><td>". $v->label ."</td>
			<td><input value=\"$value\" type=\"text\" name=\"". $v->name ."\"></td></tr>" ;
		}
		if ($v->type == "month"){
			$form .= "<tr><td>". $v->label ."</td>
			<td>". monthSelect2( $value, $v->name) ."</td></tr>" ;
		}
		if ($v->type == "year"){
			$form .= "<tr><td>". $v->label ."</td>
			<td>". yearSelect2(1893, $value, $v->name) ."</td></tr>" ;
		}
		if ($v->type == "select"){
			$netselect = make_select($v->name, $value, $v->options);
			$form .= "<tr><td>". $v->label ."</td><td>". $netselect ."</td></tr>";
		}
	}
	$imguri .= implode($pltvars, "_");
	$imguri .= ".png";
	$image = <<<EOF
	<p><span class="glyphicon glyphicon-arrow-down"></span> A graph will appear below this text with your specifications from above:<br >
	<img src="$imguri" class="img img-responsive" />
EOF;
	$formhtml = <<<EOF
<script>
function onNetworkChange(newnetwork){
	$('form#myForm').submit();
}
</script>
	<h4><span class="glyphicon glyphicon-arrow-right"></span> Second, select specific chart options::</h4>
	<form method="GET" name="s" id="myForm">
	<input type="hidden" name="q" value="{$q}">
	<table class="table table-striped">
		<thead><tr><th>Description</th><th>Value</th></tr></thead>
	$form
	</table>		
	<input type="submit" value="Make Plot with Options" />
</form>
EOF;
}


$t->content = <<<EOF
<h3>COOP Data Plotter</h3>

<p>This application dynamically generates many types of graphs.  These graphs
are derived from NWS Cooperative Observer data that is processed and sometimes
estimated by the IEM.  The raw data can be downloaded <a href="/request/coop/fe.phtml">here</a>.</p>

<br /><form method="GET" name="t">
<div class="form-group">
<h4><span class="glyphicon glyphicon-arrow-right"></span> First, select a chart type::</h4>
{$pselect}
<input type="submit" value="Select Plot Type" />
</div>
</form>

<hr />


 $formhtml


<hr />

$image

<div class="alert alert-info"><span class="glyphicon glyphicon-info-sign"></span>
		If you notice plotting issues with the image above, please 
		do <a class="alert-link" href="/info/contacts.php">let us know</a> by providing the 
		URL address currently shown by your web browser.</div>

EOF;

$t->render('single.phtml');


?>