<body bgcolor="#F5E658">

<h3>SchoolNet Rainfall Rates:</h3>

<p>The networks in the IEM SchoolNet report rainfall accumulations every 
minute.  Given this high temporal frequency, it would only seem natural to
look at the rainfall intensities.

<br><br>Please note the following caveats:</p>
<ol>
 <li>Data is presented for educational purposes.</li>
 <li>Unfortunately, some of the sites will report rainfall when the 
     wind shakes the instrument tower (provokes tips).</li>
 <li>Rainfall is not measured during the cold season.</li>
</ol>

<p>Missing data is denoted with a 'M' character.  When possible, the data
is interpolated.  Interpolation is done when there was no accumulation
during the missing period. We can determine this, since an accumulation
is reported.  Say, for instance, an ob at 1:10 PM was 2.00 inches and 
then the ob at 1:20 PM was still 2.00 inches, we can then say that all
the obs between those two times were also 2.00 inches.</p>

<p>The heaviest rainfall event recorded from this network occured at the
Glidden site on 10 July 2003 around 7 AM.  You can view this period by 
selecting the appropriate options in the above frame.

<p>If you have any questions, please let us know.</p>
