<?php
include("../../../config/settings.inc.php");
$TITLE = "IEM | High Temperature Forecasting";
include("$rootpath/include/header.php"); ?>

<h3>High Temperature Forecasting Methods</h3>

<p><img src="figs/year.png">
<p><img src="figs/jan.png">
<img src="figs/feb.png">
<img src="figs/mar.png">
<img src="figs/apr.png">
<img src="figs/may.png">
<img src="figs/jun.png">
<img src="figs/jul.png">
<img src="figs/aug.png">
<img src="figs/sep.png">
<img src="figs/oct.png">
<img src="figs/nov.png">
<img src="figs/dec.png">

<p>


<?php include("$rootpath/include/footer.php"); ?>
