<?php
require_once "../../../config/settings.inc.php";
include_once "../../../include/myview.php";
$t = new MyView();
$t->title = "High Temperature Forecasting";

$t->content = <<<EOF
<h3>High Temperature Forecasting Methods</h3>

<p><img src="figs/year.png">
<p><img src="figs/jan.png">
<img src="figs/feb.png">
<img src="figs/mar.png">
<img src="figs/apr.png">
<img src="figs/may.png">
<img src="figs/jun.png">
<img src="figs/jul.png">
<img src="figs/aug.png">
<img src="figs/sep.png">
<img src="figs/oct.png">
<img src="figs/nov.png">
<img src="figs/dec.png">

<p>
EOF;
$t->render('single.phtml');
