<?php
require_once "../../config/settings.inc.php";
require_once "../../include/database.inc.php";

require_once "../../include/myview.php";
$t = new MyView();

$title = isset($_POST["title"]) ? $_POST["title"] : "";
$body = isset($_POST["body"]) ? $_POST["body"] : "";
$author = isset($_POST["author"]) ? $_POST["author"] : "";
$url = isset($_POST["url"]) ? $_POST["url"] : "";
$tags = isset($_REQUEST["tags"]) ? explode(",", $_REQUEST["tags"]) : array();

$msg = "";
if (strlen($title) > 0) {
    $conn = iemdb("mesosite", TRUE, TRUE);
    $rs = pg_prepare($conn, "INJECTOR", "INSERT into 
       news(body, author, title, url, tags) VALUES ($1,$2,$3,$4, $5)");
    pg_execute($conn, "INJECTOR", array(
        str_replace("\r", "", $body),
        $author, $title, $url, "{" . join(",", $tags) . "}"
    ));
    $msg = "Story entered!";
}

$t->title = "Add News Item";

$t->jsextra = "
<script>
$('#testhtml').click(function(){
    $('#testhtml_target').html($('#story').val());
});
</script>
";


$t->content = <<<EOF
<form method="POST" action="add_news.phtml" name='news'>

<p>Enter Title:<input type="text" name="title" size="30">

<p>Reference URL?:
<input type="text" name="url" size="50">

<p>Enter Story (HTML please :) ):<br />
<textarea id="story" name='body' rows="20" cols="70" style="font-family:monospace;"></textarea>

<p>Enter Author:
 <input type="text" name="author" value="Daryl Herzmann">

<p>Tags (comma seperated)
<input type="text" name="tags" />

<p>Post Story:
 <input type="submit">
 <input type="reset">
 <a class="btn btn-default" role="button" id="testhtml">Preview</a>

</form>

<div id="testhtml_target"></div>

EOF;
$t->render('single.phtml');
