<?php
include("../../config/settings.inc.php");
include("../../include/database.inc.php");
$dbconn = iemdb("mesosite", TRUE, TRUE);
 /* Edit IEM Properties */
$rs = pg_prepare($dbconn, "DELETE", "DELETE from properties WHERE
      propname = $1");
$rs = pg_prepare($dbconn, "INSERT", "INSERT into properties
      (propname, propvalue) VALUES ($1, $2)");

if (isset($_REQUEST["del"])){
	$rs = pg_execute($dbconn, "DELETE", Array($_REQUEST["del"]));
}

if ( isset($_GET["propname"]) && isset($_GET["propvalue"])){
  $propname = $_GET["propname"];
  $propvalue = $_GET["propvalue"];

  $rs = pg_execute($dbconn, "DELETE", Array($propname));
  $rs = pg_execute($dbconn, "INSERT", Array($propname, $propvalue));
}

$rs = pg_query($dbconn, "SELECT * from properties ORDER by propname ASC");

include("../../include/myview.php");
$t = new MyView();
$t->title = "Properties Editor";


$table = "<table class='table table-striped'>
<thead><tr><th>Delete</th><th>Name</th><th>Value</th></tr></thead>";

for($i=0;$row=pg_fetch_assoc($rs);$i++){
	$uri = sprintf("props.phtml?del=%s", $row["propname"]);
 $table .= sprintf("<tr><td><a href='%s'>X</a></td><td>%s</td><td>%s</td></tr>\n", 
 		$uri, $row["propname"], $row["propvalue"]);
}
$table .= "</table>";

$t->content = <<<EOF

<ol class="breadcrumb">
 <li><a href="/admin/">Administration</a></li>
 <li class="active">IEM Props Editor</li>
</ol>

$table
		
<form method="GET" name="editor">
<p>Name:<input type="text" name="propname">
Value:<input type="text" name="propvalue">
<input type="submit" value="Add/Update Property">
</form>
EOF;
$t->render('single.phtml');
?>