<?php 
include("../../config/settings.inc.php");
$TITLE = "IEM | Mailing Lists";
include("$rootpath/include/header.php"); ?>

<div class="text">
<p>The IEM maintains a set of mailing lists to distribute information 
to users.  Listed here are the public addresses that you can sign up for.  If you 
have a specific data product that you would like to receive routinely, please let 
us know.</p>

<H3 class="subtitle">Public Lists:</H3>
<UL>
	<LI><a href="/mailman/listinfo/story_warn">Story County Weather Warnings</a><BR>
	NWS weather alert bulletins for Story County are forwarded onto this listserv.</li>

	<li><a href="/mailman/listinfo/boone_warn">Boone County Weather Warnings</a><BR>
        NWS weather alert bulletins for Boone County are forwarded onto this listserv.</li>
	<li><a href="/mailman/listinfo/dailyb">IEM Daily Bulletin</a><br>
	Daily email for IEM information and observational network stats.</li>
	<li><a href="/mailman/listinfo/iarwis-alert">RWIS Network Wind Alerts</a><br>
	Severe wind gusts from the RWIS network are automatically emailed
        to this list.</li>

</UL>


</TD></TR></div>

<?php include("$rootpath/include/footer.php"); ?>
