<?php
/* Download NSTL Data */
require_once "../../config/settings.inc.php";
require_once "../../include/database.inc.php";
require_once "../../include/forms.php";

$eyear = get_int404("eyear", date("Y", time() - 86400));
$emonth = get_int404("emonth", date("m", time() - 86400));
$eday = get_int404("eday", date("d", time() - 86400));
$smonth = get_int404("smonth", date("m", time()));
$sday = get_int404("sday", date("d", time()));
$syear = get_int404("syear", date("Y", time() - 86400));

$stations = $_GET["station"];
$stationString = "(";
foreach ($stations as $key => $value) {
    $stationString .= " '" . $value . "',";
}
$stationString = substr($stationString, 0, -1);
$stationString .= ")";


$sts = mktime(0, 0, 0, $smonth, $sday, $syear);
$ets = mktime(0, 0, 0, $emonth, $eday, $eyear);

$pg_conn = iemdb("other");
pg_exec($pg_conn, "SET TIME ZONE 'UTC'");

$sql = sprintf(
    "SELECT * from flux_data WHERE valid >= '%s 00:00' and 
        valid < '%s 23:59' and station IN $stationString 
        ORDER by valid ASC",
    date("Y-m-d", $sts),
    date("Y-m-d", $ets)
);

$rs = pg_exec($pg_conn, $sql);

header("Content-type: application/octet-stream");
header("Content-Disposition: attachment; filename=fluxdata.txt");


for ($i = 0; $row = pg_fetch_assoc($rs); $i++) {
    if ($i == 0) /* Print el-header */ {
        echo "station,valid";
        $cols = array_keys($row);
        $printCols = array();
        foreach ($cols as $k => $v) {
            if ($v == "station" || $v == "valid") {
                continue;
            }
            $printCols[] = $v;
            echo ",$v";
        }
        echo "\n";
    }
    echo sprintf("%s,%s,", $row["station"], $row["valid"]);
    reset($printCols);
    foreach ($printCols as $k => $v) {
        echo $row[$v] . ",";
    }
    echo "\n";
}
