<?php
 /* Download NSTL Data */
include("../../config/settings.inc.php");
include("$rootpath/include/database.inc.php");

$year = isset($_GET["year"]) ? $_GET["year"] : date("Y", time() - 86400);
$emonth = isset($_GET["emonth"]) ? $_GET["emonth"] : date("m", time() - 86400);
$eday = isset($_GET["eday"]) ? $_GET["eday"] : date("d", time() - 86400);
$smonth = isset($_GET["smonth"]) ? $_GET["smonth"] : date("m", time() );
$sday = isset($_GET["sday"]) ? $_GET["sday"] : date("d", time() );
$all = isset($_GET["all"]);

$sts = mktime(0,0,0,$smonth, $sday, $year);
$ets = mktime(0,0,0,$emonth, $eday, $year);

$pg_conn = iemdb("other");
pg_exec($pg_conn, "SET TIME ZONE 'GMT'");

if ($all) { $sql = sprintf("SELECT * from flux%s ORDER by valid ASC", $year); }
else { $sql = sprintf("SELECT * from flux%s WHERE date(valid) >= '%s' and date(valid) <= '%s' ORDER by valid ASC", $year, date("Y-m-d", $sts), date("Y-m-d", $ets) ); }

$rs = pg_exec($pg_conn, $sql);

header("Content-type: application/octet-stream");
header("Content-Disposition: attachment; filename=fluxdata.txt");


for( $i=0; $row = @pg_fetch_array($rs,$i, PGSQL_ASSOC); $i++)
{
  if ($i == 0) /* Print el-header */
  {
    echo "station,valid";
    $cols = array_keys($row);
    $printCols = Array();
    foreach ($cols as $k => $v)
    {
       if ($v == "station" || $v == "valid") { continue; }
       $printCols[] = $v;
       echo ",$v";
    }
    echo "\n";
  }
  echo sprintf("%s,%s,", $row["station"], $row["valid"]);
  reset($printCols);
  foreach( $printCols as $k => $v)
  {
    echo $row[$v] .",";
  }
  echo "\n";
}

?>
