<?php
 /* Download NSTL Data */
include("../../config/settings.inc.php");
include("$rootpath/include/database.inc.php");

$year = isset($_GET["year"]) ? $_GET["year"] : date("Y", time() - 86400);
$month = isset($_GET["month"]) ? $_GET["month"] : date("m", time() - 86400);
$day = isset($_GET["day"]) ? $_GET["day"] : date("d", time() - 86400);
$all = isset($_GET["all"]);


$pg_conn = iemdb("other");

if ($all) { $sql = sprintf("SELECT * from flux%s ORDER by valid ASC", $year); }
else { $sql = sprintf("SELECT * from flux%s WHERE date(valid) = '%s-%s-%s' ORDER by valid ASC", $year, $year, $month, $day); }

$rs = pg_exec($pg_conn, $sql);

header("Content-type: application/octet-stream");
header("Content-Disposition: attachment; filename=fluxdata.txt");


for( $i=0; $row = @pg_fetch_array($rs,$i, PGSQL_ASSOC); $i++)
{
  if ($i == 0) /* Print el-header */
  {
    echo "station,valid";
    $cols = array_keys($row);
    $printCols = Array();
    foreach ($cols as $k => $v)
    {
       if ($v == "station" || $v == "valid") { continue; }
       $printCols[] = $v;
       echo ",$v";
    }
    echo "\n";
  }
  echo sprintf("%s,%s,", $row["station"], $row["valid"]);
  reset($printCols);
  foreach( $printCols as $k => $v)
  {
    echo $row[$v] .",";
  }
  echo "\n";
}

?>
