<?php
include("../../config/settings.inc.php");
include("$rootpath/include/forms.php");

$THISPAGE = "networks-flux";
$TITLE = "IEM | NLAE Flux Sites";
include("$rootpath/include/database.inc.php");
include("$rootpath/include/header.php"); ?>

<TR><TD>

<h3 class="heading">USDA-ARS-National Laboratory for Agriculture and the Environment Flux Sites</h3>

<p>The IEM is pleased to host the data from a set of observing platforms operated by the USDA-ARS-National Laboratory for Agriculture and the Environment (NLAE).  These sites directly measure and derive numerous air and soil flux values. 

<p>These raw data have not been subjected to the National Laboratory for Agriculture and the Environment's quality control or quality assurance procedures. The correction factor's are calculated within a Campbell Scientific, Inc (Logan, UT) provided flux program for the CR5000 dataloggers. The WPL corrections are based on the equations found in Webb, E.K., G.I. Pearman, and R. Leuning, 1980. Correction of flux measurements for density effects due to heat and water vapor transfer.

<p>They are released for limited public use as preliminary data to be used only with appropriate caution. <a href="vars.phtml">View variables</a> collected from this network.

<br><br>
<a href="plots.phtml"><img src="pthumb.png" style="border: 2px solid #000; margin:5px;"></a>
<a href="plots.phtml">Generate daily time series plots</a>


<br clear="left" />
<p>
<?php

$lats = Array("nstl11" => 41.97482, "nstl10" => 41.9749, 
   "nspr" => 41.55865, "nstl30ft" => 41.97485, 
   "nstl110" => 42.1654);
$lons = Array("nstl11" => -94.69367, "nstl10" => -93.6914, 
   "nspr" =>-93.29286, "nstl30ft" => -94.6924, "nstl110" => -93.7940);

?>

<table width="100%">
<thead><tr><th colspan="6" align="left">Site Information:</th></tr></thead>
<tr><th align="left">ID</th><th align="left">Status</th><th align="left">Lat</th><th align="left">Lon</th><th
align="left">First Observation</th><th align="left">Last Observation</th></tr></thead>
<tbody>
<?php
$pg_conn = iemdb("other");
$sql = "SELECT * from flux_meta ORDER by sts ASC";
$rs = pg_exec($pg_conn, $sql);

for( $i=0; $row = @pg_fetch_array($rs,$i); $i++)
{
  echo sprintf("<tr><th>%s</th><td>%s</td><td>%s</td><td>%s</td><td>%s</td><td>%s</td></tr>", $row["station"], $row["surface"], $lats[$row["station"]], $lons[$row["station"]], substr($row["sts"],0,10), substr($row["ets"],0,10) );
}
?>
</tbody>
</table><p>

<form method="GET" action="dl.phtml" name="single">
<h3>Download Data:</h3><br />

<p>This form will give you all variables for the day interval of your choice.
<br />Timestamps and date periods are in UTC.

<table>
<tr><th>Year:</th>
  <th>Month:</th>
  <th>Day:</th></tr>

<tr>  
  <td rowspan="2"><?php echo yearSelect(2002, date("Y"), "year"); ?></td>
  <td><?php echo monthSelect(date("m"), "smonth"); ?></td>
  <td><?php echo daySelect2(date("d"), "sday"); ?></td></tr>

<tr>
  <td><?php echo monthSelect(date("m"), "emonth"); ?></td>
  <td><?php echo daySelect2(date("d"), "eday"); ?></td></tr>

</table>
<input type="submit" value="Download Date">
</form>

<br>


<?php include("$rootpath/include/footer.php"); ?>
