<?php
require_once "../../config/settings.inc.php";
define("IEM_APPID", 26);
require_once "../../include/myview.php";
$t = new MyView();
require_once "../../include/forms.php";
require_once "../../include/database.inc.php";

$dt = dt_from_cgi_ymd();
$pvar1 = isset($_GET["pvar1"]) ? xssafe($_GET["pvar1"]) : "fc_wpl";
$pvar2 = isset($_GET["pvar2"]) ? xssafe($_GET["pvar2"]) : "le_wpl";
$pvar3 = isset($_GET["pvar3"]) ? xssafe($_GET["pvar3"]) : "hs";
$pvar4 = isset($_GET["pvar4"]) ? xssafe($_GET["pvar4"]) : "rn_total_avg";

$other = iemdb("other");
$sql = "SELECT * from flux_vars ORDER by details ASC";
$rows = pg_query($other, $sql);
$var_names = array();
$var_details = array();
while ($row = pg_fetch_assoc($rows)) {
    $var_names[] = $row["name"];
    $var_details[] = $row["details"];
}

/**
 * Generate an HTML select element with the given options.
 *
 * @param string $name The name attribute of the select element.
 * @param string $selected The value that should be selected by default.
 * @param array $ids The array of option values.
 * @param array $values The array of option display texts.
 * @return string The HTML string for the select element.
 */
function genselect($name, $selected, $ids, $values)
{
    $s = "<select name=\"$name\">\n";
    foreach ($ids as $k => $v) {
        $s .= "<option value=\"$v\" ";
        if ($selected == $v) $s .= "selected=\"selected\"";
        $s .= ">" . $values[$k] . "</option>";
    }
    $s .= "</select>\n";
    return $s;
}
$t->title = "NLAE Flux Sites";

$ys = yearSelect(2002, $dt->format("Y"), "year");
$ms = monthSelect($dt->format("m"), "month");
$ds = daySelect($dt->format("d"), "day");
$spvar1 = genselect("pvar1", $pvar1, $var_names, $var_details);
$spvar2 = genselect("pvar2", $pvar2, $var_names, $var_details);
$spvar3 = genselect("pvar3", $pvar3, $var_names, $var_details);
$spvar4 = genselect("pvar4", $pvar4, $var_names, $var_details);

$u1 = sprintf("plot.php?pvar=%s&year=%s&month=%s&day=%s", $pvar1, $dt->format("Y"), $dt->format("m"), $dt->format("d"));
$u2 = sprintf("plot.php?pvar=%s&year=%s&month=%s&day=%s", $pvar2, $dt->format("Y"), $dt->format("m"), $dt->format("d"));
$u3 = sprintf("plot.php?pvar=%s&year=%s&month=%s&day=%s", $pvar3, $dt->format("Y"), $dt->format("m"), $dt->format("d"));
$u4 = sprintf("plot.php?pvar=%s&year=%s&month=%s&day=%s", $pvar4, $dt->format("Y"), $dt->format("m"), $dt->format("d"));

$t->content = <<<EOM
<nav aria-label="breadcrumb">
 <ol class="breadcrumb">
 <li class="breadcrumb-item"><a href="/nstl_flux/">NLAE Flux Stations</a></li>
 <li class="breadcrumb-item active" aria-current="page">Time Series Plots</li>
 </ol>
</nav>

<p>This page generates 4 plots of your choice.  Select the date and variables
you wish to plot and then click on the 'Generate Plots' button.


<form method="GET" name="selector">

<table class="table table-bordered">
<thead>
<tr>
 <th colspan="3">Select Date:</th>
 <th>Select Plot Variable:</th></tr></thead>
<tbody>
<tr><th>Year:</th><th>Month:</th><th>Day:</th>
<td rowspan="2"><b>1.</b> {$spvar1}
 <br /><b>2.</b> {$spvar2}
 <br /><b>3.</b> {$spvar3}
 <br /><b>4.</b> {$spvar4}
</td></tr>
<tr>
 <td>{$ys}</td>
 <td>{$ms}</td>
 <td>{$ds}</td>

</tr>
</table>
<input type="submit" value="Generate Plots">
<p>
<br /><img src="{$u1}" class="img-fluid">
<br /><img src="{$u2}" class="img-fluid">
<br /><img src="{$u3}" class="img-fluid">
<br /><img src="{$u4}" class="img-fluid">
EOM;
$t->render('single.phtml');
