<?php 
include("../../config/settings.inc.php");
include("../../include/myview.php");
require_once "../../include/iemprop.php";
$gmapskey = get_iemprop("google.maps.key");

$t = new MyView();
$t->title = "Frost Forecasting";
$t->headextra = <<<EOF
<script src="https://maps.googleapis.com/maps/api/js?key={$gmapskey}" type="text/javascript"></script>
<style>
  #map {
    width: 100%;
    height: 400px;
    float: left;
  }
</style>
<script type="text/javascript">
var myv = "bdeckt";
var myt = '00';
var mymodel = 'bridget';
var myi = '001';
var marker;
function updatePlot(){
	$('#frost_ts').attr('src', "frost_ts_"+ mymodel +"_"+
		marker.getPosition().lng() +"_"+ marker.getPosition().lat() +".png")
}
function switchmodel(){
	mymodel = $("#whichmodel").val();
	updatePlot();		
}
function updateMarkerPosition(latLng) {
	updatePlot();		
}
function initialize() {
        var latLng = new google.maps.LatLng(41.53, -93.653);
        var map = new google.maps.Map(document.getElementById('map'), {
            zoom: 5,
            center: latLng,
            mapTypeId: google.maps.MapTypeId.ROADMAP
        });
	marker = new google.maps.Marker({
            position: latLng,
            title: 'Point A',
            map: map,
            draggable: true
	});

          google.maps.event.addListener(marker, 'dragend', function() {
            updateMarkerPosition(marker.getPosition());
          });
}

function showimg(){
	$('#modimg').attr('src', '/data/model/frost/'+mymodel+'/'+myt+'/'+myv+'_'+myt+'_f'+myi+'.png');
}
function show(i){
	myi = i;
	showimg();
}
function setv(v){
	myv = v;		
	showimg();
}
function sett(t){
	myt = t;		
	showimg();
}
// Onload handler to fire off the app.
google.maps.event.addDomListener(window, 'load', initialize);

</script>

EOF;

$table = "<form name='d'><table class=\"table table-striped table-bordered table-condensed\">";

$table .= "<tr><td>Day 1</td>";
for ($i=1;$i<25;$i++){
	$table .= sprintf("<td><a href=\"#\" onmouseover=\"show('%03d');\">%s</a></td>", $i, $i);
}
$table .= "</tr>";

$table .= "<tr><td>Day 2</td>";
for ($i=25;$i<49;$i++){
	$table .= sprintf("<td><a href=\"#\" onmouseover=\"show('%03d');\">%s</a></td>", $i, $i);
}
$table .= "</tr>";

$table .= "<tr><td>Day 3</td>";
for ($i=49;$i<73;$i++){
	$table .= sprintf("<td><a href=\"#\" onmouseover=\"show('%03d');\">%s</a></td>", $i, $i);
}
$table .= "</tr>";


$table .= <<<EOF
</table>

<p>
<input checked="checked" type="radio" name="v" value="bdeckt" onclick="setv('bdeckt')">Bridge Deck Temperature</input>
<input type="radio" name="v" value="frostd" onclick="setv('frostd')">Frost Depth</input>
<input type="radio" name="v" value="ifrost" onclick="setv('ifrost')">Frost Presence</input>

<p>
<input checked="checked" type="radio" name="t" value="00" onclick="sett('00')">00 UTC</input>
<input type="radio" name="t" value="12" onclick="sett('12')">12 UTC</input>
		
		
<p><img src="/data/model/frost/00/bdeckt_00_f001.png" id="modimg" />
</form>
EOF;

$t->content = <<<EOF

<h2>ISU + Iowa DOT Road Pavement Forecasting</h2>

<div class="alert alert-warning">This page contains unofficial and experimental
forecasts intended for research purposes.</div>

<div class="row">
 <div class="col-md-6">
 	<form name="s">
 	<strong>Select Pavement Model:</strong>
 	<select name="model" id="whichmodel" onChange="switchmodel();">
 	  <option value="bridget">BridgeT</option>
 	  <option value="metro">METRo</option>
 	 </select>
 	</form>
 	<div id="map"></div>
 </div>
 <div class="col-md-6">
 <img id="frost_ts" src="frost_ts_bridget_-93.5_42.1.png" class="img img-responsive">
 
 <br /><h4>Color Codes used in chart:</h4>
 <div style="background: #eee;">
 <span style="color: white; background: #000;">Normal/Dry</span>
 <br /><span style="color: #0f0;">Wet</span>
 <br /><span style="color: orange;">Ice/Mix</span>
 <br /><span style="color: brown;">Dew (Metro Only)</span>
 <br /><span style="color: #00f;">Melting Snow</span>
 <br /><span style="color: purple;">Freezing Rain</span>
 </div>
 
 </div>
</div>


<h4>IEM Useful Links:</h4>
<ul>
<li><a href="/GIS/apps/iem/freeze.phtml">IEM Freeze</a></li>
<li><a href="/data/mesonet.gif">Mesonet plot</a></li>
<li><a href="/data/rwis_sf.png">RWIS pavement temps plot</a></li>
<li><a href="/RWIS/current.phtml">RWIS sortable currents</a></li></ul>
</td></tr></table>

<br clear="all">
<h2 class="subtitle">Frost Model Schedule</h2>
<table border=1>
<tr>
 <th>Model Run:</th><td>MM5 Init:</td><td>Frost Model Init:</td><td>Products Delivered:</td></tr>
<tr>
 <th>00Z (6PM):</th>
 <td>04Z (10PM)</td>
 <td>05Z (11PM)</td>
 <td>06Z (Midnight)</td></tr>
<tr>
 <th>12Z (6AM):</th>
 <td>16Z (10AM)</td>
 <td>17Z (11AM)</td>
 <td>18Z (Noon)</td></tr>
</table>

<h2>Output graphics:</h2>

{$table}

EOF;
$t->render('single.phtml');
?>
