<?php 
include("../../config/settings.inc.php");
include("../../include/myview.php");

$t = new MyView();
$t->title = "Frost Forecasting";
$t->headextra = <<<EOF
<script src="https://maps.googleapis.com/maps/api/js?sensor=false" type="text/javascript"></script>
<style>
  #map {
    width: 500px;
    height: 400px;
    float: left;
  }
</style>
<script type="text/javascript">
var myv = "bdeckt";
var myt = '00';
var myi = '001';
function updateMarkerPosition(latLng) {
        //console.log(latLng.lat() +'-'+ latLng.lng());
		$('#frost_ts').attr('src', "frost_ts_"+ latLng.lng() +"_"+ latLng.lat() +".png")
}
function initialize() {
        var latLng = new google.maps.LatLng(41.53, -93.653);
        var map = new google.maps.Map(document.getElementById('map'), {
            zoom: 5,
            center: latLng,
            mapTypeId: google.maps.MapTypeId.ROADMAP
        });
          var marker = new google.maps.Marker({
            position: latLng,
            title: 'Point A',
            map: map,
            draggable: true
        });

          google.maps.event.addListener(marker, 'dragend', function() {
            updateMarkerPosition(marker.getPosition());
          });
}

function showimg(){
	$('#modimg').attr('src', '/data/model/frost/'+myt+'/'+myv+'_'+myt+'_f'+myi+'.png');
}
function show(i){
	myi = i;
	showimg();
}
function setv(v){
	myv = v;		
	showimg();
}
function sett(t){
	myt = t;		
	showimg();
}
// Onload handler to fire off the app.
google.maps.event.addDomListener(window, 'load', initialize);

</script>

EOF;

$table = "<form name='d'><table class=\"table table-striped table-bordered table-condensed\">";

$table .= "<tr><td>Day 1</td>";
for ($i=1;$i<25;$i++){
	$table .= sprintf("<td><a href=\"#\" onmouseover=\"show('%03d');\">%s</a></td>", $i, $i);
}
$table .= "</tr>";

$table .= "<tr><td>Day 2</td>";
for ($i=25;$i<49;$i++){
	$table .= sprintf("<td><a href=\"#\" onmouseover=\"show('%03d');\">%s</a></td>", $i, $i);
}
$table .= "</tr>";

$table .= "<tr><td>Day 3</td>";
for ($i=49;$i<73;$i++){
	$table .= sprintf("<td><a href=\"#\" onmouseover=\"show('%03d');\">%s</a></td>", $i, $i);
}
$table .= "</tr>";


$table .= <<<EOF
</table>

<p>
<input checked="checked" type="radio" name="v" value="bdeckt" onclick="setv('bdeckt')">Bridge Deck Temperature</input>
<input type="radio" name="v" value="frostd" onclick="setv('frostd')">Frost Depth</input>
<input type="radio" name="v" value="ifrost" onclick="setv('ifrost')">Frost Presence</input>

<p>
<input checked="checked" type="radio" name="t" value="00" onclick="sett('00')">00 UTC</input>
<input type="radio" name="t" value="12" onclick="sett('12')">12 UTC</input>
		
		
<p><img src="/data/model/frost/00/bdeckt_00_f001.png" id="modimg" />
</form>
EOF;

$t->content = <<<EOF

<div class="row">
 <div class="col-md-6"><div id="map"></div></div>
 <div class="col-md-6"><img id="frost_ts" src="frost_ts_-93.5_42.1.png" class="img img-responsive"></div>
</div>

<table><tr><td valign="top">
<img align="left" src="images/Station_bridge.jpg"></td><td>

<h3 class="heading">Frost Forecasting</h3>

<p>This page is the homepage of our frost modeling and prediction effort. 
Products presented here are for educational use only.

<h2 class="subtitle">IEM Useful Links:</h2><ul>
<li><a href="/GIS/apps/iem/freeze.phtml">IEM Freeze</a></li>
<li><a href="/data/mesonet.gif">Mesonet plot</a></li>
<li><a href="/data/rwis_sf.gif">RWIS pavement temps plot</a></li>
<li><a href="/RWIS/current.phtml">RWIS sortable
currents</a></li></ul>
</td></tr></table>

<br clear="all">
<h2 class="subtitle">Frost Model Schedule</h2>
<table border=1>
<tr>
 <th>Model Run:</th><td>MM5 Init:</td><td>Frost Model Init:</td><td>Products Delivered:</td></tr>
<tr>
 <th>00Z (6PM):</th>
 <td>04Z (10PM)</td>
 <td>05Z (11PM)</td>
 <td>06Z (Midnight)</td></tr>
<tr>
 <th>12Z (6AM):</th>
 <td>16Z (10AM)</td>
 <td>17Z (11AM)</td>
 <td>18Z (Noon)</td></tr>
</table>

<h2>Output graphics:</h2>

{$table}


<!--
<h3>Time series:</h3>
<li><a href="/plotting/24h/1station.php?station=AMW">Recent Ames ASOS</a></li>
<li><a href="/plotting/scan/radn5temps.php">SCAN site recent soil temps w/ rad</a></li>

<h3>Frost Forecasts:</h3>
&nbsp; &nbsp; <b>ISU Frost Model</b>
<BR><a href="/plotting/frost/accum.php?model=MM5">with ISU MM5 input data</a>
<BR><a href="/plotting/frost/accum.php?model=SSI">with SSI input data</a>

<h3>Forecast Comparison:</h3>
<a href="/plotting/frost/f201.php?varnum=4">MM5 Skin Temp vs SSI Pavement</a>
<br><a href="/plotting/frost/f201.php?varnum=5">MM5 2m Air Temp vs SSI Air Temp</a>
<br><a href="/plotting/frost/f201.php?varnum=6">MM5 2m Dew Point vs SSI Dew Point</a>
<br><a href="/plotting/frost/f201.php?varnum=7">MM5 2m Wind Speed vs SSI Wind Speed</a>

<BR><BR>
-->
EOF;
$t->render('single.phtml');
?>
