<?php
require_once "../../config/settings.inc.php";
define("IEM_APPID", 90);
require_once "../../include/myview.php";
require_once "../../include/database.inc.php";
require_once "../../include/imagemaps.php";
require_once "../../include/forms.php";

$mesosite = iemdb('mesosite');

$t = new MyView();
$t->iemss = True;
$t->title = "Download Daily Summary Data";

$network = isset($_REQUEST["network"]) ? xssafe($_REQUEST["network"]) : "IA_ASOS";

$ar = Array();
$rs = pg_query($mesosite, "SELECT id, name from networks ORDER by name ASC");
for ($i = 0; $row = pg_fetch_assoc($rs); $i++) {
    $ar[$row["id"]] = $row["name"];
}
$nselect = make_select("network", $network, $ar);

$y1 = yearSelect2(1928, date("Y"), "year1");
$m1 = monthSelect("", "month1");
$d1 = daySelect2("", "day1");
$y2 = yearSelect2(1928, date("Y"), "year2");
$m2 = monthSelect(date("m"), "month2");
$d2 = daySelect2(date("d"), "day2");

$ar = Array(
    "None" => "Text string 'None'",
    "M" => "M",
    "blank" => "Empty string (blank)",
);
$naselect = make_select("na", "blank", $ar);

$ar = Array(
    "csv" => "Comma Seperated (csv)",
    "excel" => "Excel (xlsx)",
    "json" => "JSON",
);
$fmtselect = make_select("format", "csv", $ar);


$vars = array(
    "max_temp_f" => "Maximum Air Temperature [F].",
    "min_temp_f" => "Minimum Air Temperature [F].",
    "max_dewpoint_f" => "Maximum Dew Point [F].",
    "min_dewpoint_f" => "Minimum Dew Point [F].",
    "precip_in" => "Daily Precipitation [inch].",
    "avg_wind_speed_kts" => "Average Wind Speed [knots]",
    "avg_wind_drct" => "Average Wind Direction [deg]",
    "min_rh" => "Minimum Relative Humidity [%]",
    "avg_rh" => "Average Relative Humidity [%]: computed by time averaging the available reports, it is not average of the daily max/min.",
    "max_rh" => "Maximum Relative Humidity [%]",
    "climo_high_f" => "NCEI 1991-2020 Daily High Temperature Climatology [F]",
    "climo_low_f" => "NCEI 1991-2020 Daily Low Temperature Climatology [F]",
    "climo_precip_in" => "NCEI 1991-2020 Daily Precipitation Climatology [inch]",
    "snow_in" => "Reported Snowfall [inch]",
    "snowd_in" => "Reported Snow Depth [inch]",
    "min_feel" => "Minimum 'Feels Like' (either wind chill or heat index) temperature.  The value is always at least the air temperature.",
    "avg_feel" => "Average 'Feels Like' (either wind chill or heat index) temperature.  The value is always at least the air temperature. Value is a time weighted average.",
    "max_feel" => "Maximum 'Feels Like' (either wind chill or heat index) temperature.  The value is always at least the air temperature.",
    "max_wind_speed_kts" => "Maximum sustained wind speed in knots.",
    "max_wind_gust_kts" => "Maximum wind gust in knots.",
    "srad_mj" => "Daily Solar Radiation MJ/m2 (when available).",
);
$varform = "";
foreach($vars as $key => $val){
    $varform .= sprintf(
        '<br /><label for="%s" class="checkbox-inline"><input type="checkbox" name="var" value="%s" id="%s" class="sq-form-field" > '.
        '[%s] %s</label>'. "\n",
        $key, $key, $key, $key, $val,
    );
}


$t->content = <<<EOF
<style>
label {
    font-weight: normal !important;
    margin-bottom: 5px;
    display:inline-block;
}
input {
    display:inline-block;
}
</style>

<h3>IEM Computed Daily Summary of Observations</h3>

<p>This page allows you to download the IEM computed daily summary of whatever
    observations the IEM collected for a given observation site. You can also
    download data from COOP networks with this interface, in which case the
    "daily" data are effectively the once-daily observations.</p.

<p>Select network to download from:<br />
<form name="network" action="daily.phtml">
{$nselect}
<input type="submit" value="Switch Network">
</form>

<form target="_blank" name="iemss" action="/cgi-bin/request/daily.py">
<input type="hidden" value="{$network}" name="network" />

<p>&nbsp;</p>

<div class="row">
<div class="col-md-6 col-sm-6">

<div id="iemss" data-network="{$network}"></div>

</div><div class="col-md-6 col-sm-6">

<h4>Select inclusive date period:</h4>
<table class="table table-striped">
  <tr>
    <td></td>
    <th>Year</th><th>Month</th><th>Day</th>
  </tr>

  <tr>
    <th>Start:</th>
    <td>{$y1}</td><td>{$m1}</td><td>{$d1}</td>
  </tr>

  <tr>
    <th>End:</th>
    <td>{$y2}</td><td>{$m2}</td><td>{$d2}</td>
  </tr>
</table>

<h4>Select from available daily variables</h4>

<p><strong>Note</strong>: Values of 0.0001 inches are Trace Reports</p>

{$varform}

<h4>How to represent missing values:</h4>

{$naselect}

<h4>Download Data Format:</h4>

{$fmtselect}

<p><input type="submit" value="Request Data"></p>

</div></div>
</form>

EOF;
$t->render('full.phtml');
