<?php
require_once "../../config/settings.inc.php";
define("IEM_APPID", 90);
require_once "../../include/myview.php";
require_once "../../include/database.inc.php";
require_once "../../include/imagemaps.php";
require_once "../../include/forms.php";

$mesosite = iemdb('mesosite');

$t = new MyView();
$t->iemss = True;
$t->title = "Download Daily Summary Data";

$network = isset($_REQUEST["network"]) ? xssafe($_REQUEST["network"]) : "IA_ASOS";

$nselect = "<select name=\"network\">";
$rs = pg_query($mesosite, "SELECT id, name from networks ORDER by name ASC");
for ($i = 0; $row = pg_fetch_assoc($rs); $i++) {
    $sel = '';
    if ($network == $row["id"]) {
        $sel = " selected='SELECTED'";
    }
    $nselect .= sprintf(
        "<option value='%s'%s>%s</option>\n",
        $row["id"],
        $sel,
        $row["name"]
    );
}
$nselect .= "</select>";

$y1 = yearSelect2(1928, date("Y"), "year1");
$m1 = monthSelect("", "month1");
$d1 = daySelect2("", "day1");
$y2 = yearSelect2(1928, date("Y"), "year2");
$m2 = monthSelect(date("m"), "month2");
$d2 = daySelect2(date("d"), "day2");

$t->content = <<<EOF
<h3>IEM Computed Daily Summary of Observations</h3>
        
<p>This page allows you to download the IEM computed daily summary of whatever
    observations the IEM collected for a given observation site. You can also
    download data from COOP networks with this interface, in which case the
    "daily" data are effectively the once-daily observations.</p.

<p>Select network to download from:<br />
<form target="_blank" name="network" action="daily.phtml">
{$nselect}		
<input type="submit" value="Switch Network">
        </form>

<form name="iemss" action="/cgi-bin/request/daily.py">
<input type="hidden" value="{$network}" name="network" />

<p>&nbsp;</p>

<div class="row">
<div class="col-md-6 col-sm-6">

<div id="iemss" data-network="{$network}"></div>

<h4>Select inclusive date period:</h4>
<table class="table table-striped">
  <tr>
    <td></td>
    <th>Year</th><th>Month</th><th>Day</th>
  </tr>

  <tr>
    <th>Start:</th>
    <td>{$y1}</td><td>{$m1}</td><td>{$d1}</td>
        </tr>

  <tr>
    <th>End:</th>
    <td>{$y2}</td><td>{$m2}</td><td>{$d2}</td>
  </tr>
</table>

            </div>
            <div class="col-md-6 col-sm-6">

    <p><strong>Note</strong>: Values of 0.0001 inches are Trace Reports</p>

<dl class="dl-horizontal">
 <dt>station</dt><dd>Common identifier for the station.</dd>
 <dt>day</dt><dd>Calendar date of the summary.</dd>
 <dt>max_temp_f</dt><dd>Maximum Air Temperature [F].</dd>
 <dt>min_temp_f</dt><dd>Minimum Air Temperature [F].</dd>
 <dt>max_dewpoint_f</dt><dd>Maximum Dew Point [F].</dd>
 <dt>min_dewpoint_f</dt><dd>Minimum Dew Point [F].</dd>
 <dt>precip_in</dt><dd>Daily Precipitation [inch].</dd>
 <dt>avg_wind_speed_kts</dt><dd>Average Wind Speed [knots]</dd>
 <dt>avg_wind_drct</dt><dd>Average Wind Direction [deg]</dd>
 <dt>min_rh</dt><dd>Minimum Relative Humidity [%]</dd>
 <dt>avg_rh</dt><dd>Average Relative Humidity [%]: computed by time averaging
            the available reports, it is not average of the daily max/min.</dd>
 <dt>max_rh</dt><dd>Maximum Relative Humidity [%]</dd>
 <dt>climo_high_f</dt><dd>NCEI 1991-2020 Daily High Temperature Climatology [F]</dd>
 <dt>climo_low_f</dt><dd>NCEI 1991-2020 Daily Low Temperature Climatology [F]</dd>
 <dt>climo_precip_in</dt><dd>NCEI 1991-2020 Daily Precipitation Climatology [inch]</dd>
 <dt>snow_in</dt><dd>Reported Snowfall [inch]</dd>
 <dt>snowd_in</dt><dd>Reported Snow Depth [inch]</dd>
 <dt>min_feel</dt><dd>Minimum "Feels Like" (either wind chill or heat index)
 temperature.  The value is always at least the air temperature.</dd>
 <dt>avg_feel</dt><dd>Average "Feels Like" (either wind chill or heat index)
 temperature.  The value is always at least the air temperature. Value is
 a time weighted average.</dd>
 <dt>max_feel</dt><dd>Maximum "Feels Like" (either wind chill or heat index)
 temperature.  The value is always at least the air temperature.</dd>
 <dt>max_wind_speed_kts</dt><dd>Maximum sustained wind speed in knots.</dd>
 <dt>max_wind_gust_kts</dt><dd>Maximum wind gust in knots.</dd>
            </dl>

</div></div>
            <input type="submit" value="Request Data">
</form>

EOF;
$t->render('single.phtml');
