<?php 
include("../../config/settings.inc.php");
define("IEM_APPID", 8);
$year = date("Y");
$network = isset($_GET['network']) ? $_GET['network'] : "IA_ASOS";
$station = "";

include("$rootpath/include/database.inc.php");
include("$rootpath/include/google_keys.php");
include("$rootpath/include/imagemaps.php");
include("$rootpath/include/forms.php");
$api = $GOOGLEKEYS[$rooturl]["any"];
$HEADEXTRA = "<script src='http://maps.google.com/maps?file=api&amp;v=2&amp;key=$api'></script>
<script src='http://openlayers.org/api/2.11/OpenLayers.js'></script>
<script src='${rooturl}/js/olselect.php?network=${network}'></script>";
$TITLE = "IEM | Download Data";
$THISPAGE = "networks-asos";
$BODYEXTRA = "onload=\"init()\"";
include("$rootpath/include/header.php");
?>
<style type="text/css">
        #map {
            width: 450px;
            height: 450px;
            border: 2px solid black;
        }
</style>

<h3>ASOS/AWOS data download</h3>

<p>The IEM maintains an ever growing archive of automated airport weather
observations from around the world!  These observations are typically called 
'ASOS' or sometimes 'AWOS' sensors.  A more generic term may be METAR data, 
which is a term that describes the format the data is transmitted as. If you 
don't get data for a request, please feel free to 
<a href="../info/contacts.php">contact us</a> for help. The IEM also has a one
minute interval dataset for Iowa <a href="asos/1min.phtml">ASOS</a> (2000-) 
and <a href="awos/1min.php">AWOS</a> (1995-2011) sites.  This archive
simply provides the as-is collection of historical observations, very little 
quality control is done.

<div class="warning">Please be patient with this page as it will take a number
of seconds to process your request and provide the result.</div>

<form name="netselect">
<table><tr><th>Select Network</th>
<td><?php echo selectAzosNetwork($network); ?></td>
<td><input type="submit" value="Switch to Network"></td>
</tr></table>
</form>


<TABLE>
<TR>
<TD valign="top">
<h3 class="subtitle">1) Select Station/Network by clicking on location: </h3>

<form method="GET" action="<?php echo $rootcgi; ?>/request/getData.py" name="olselect">
<div id="map"></div>
<div id="sname">No site selected</div>

</TD>

<TD>
<P>Selected Station: <?php echo networkSelect($network, $station); ?>

<br><br>
<h3 class="subtitle">2) Select From Available Data:</h3>
<SELECT name="data" size="5" MULTIPLE>
	<option value="all" SELECTED>All Available
	<option value="tmpf">Air Temperature [F]
	<option value="tmpc">Air Temperature [C]
	<option value="dwpf">Dew Point [F]
	<option value="dwpc">Dew Point [C]
	<option value="relh">Relative Humidity [%]
	<option value="drct">Wind Direction 
	<option value="sknt">Wind Speed [knots]
	<option value="alti">Altimeter [inches]
	<option value="mslp">Sea Level Pressure [mb]
	<option value="p01m">1 hour Precipitation [mm]
	<option value="p01i">1 hour Precipitation [inch]
	<option value="vsby">Visibility [miles]
	<option value="gust">Wind Gust [knots]
	<option value="skyc1">Cloud Coverage Level 1
	<option value="skyc2">Cloud Coverage Level 2
	<option value="skyc3">Cloud Coverage Level 3
	<option value="skyl1">Cloud Height Level 1 [ft]
	<option value="skyl2">Cloud Height Level 2 [ft]
	<option value="skyl3">Cloud Height Level 3 [ft]
	<option value="metar">Raw METAR</option>
</SELECT>
<br />
<strong>Note:</strong> Cloud information and raw METAR data is not available 
for all observations, the IEM continues to backfill this information.


<br><br>
<h3 class="subtitle">3) Specific Date Range (If needed):</h3>
<TABLE>
<TR><TH>Start:</TH><TH>Stop:</TH></TR>

<tr>
 <td><?php echo yearSelect2(1941, date("Y"), "year1"); ?></td>
 <td><?php echo yearSelect2(1941, date("Y"), "year2"); ?></td>
</tr>

<tr>
 <td><?php echo monthSelect2(date("m"), "month1"); ?></td>
 <td><?php echo monthSelect2(date("m"), "month2"); ?></td>
</TR>

<tr>
 <td><?php echo daySelect2(date("d"), "day1"); ?></td>
 <td><?php echo daySelect2(date("d"), "day2"); ?></td>
</tr>

</TABLE>

<br><br>
<h3 class="subtitle">4) Format of time output:</h3>
<SELECT name="tz">
	<option value="GMT">GMT (UTC) timestamps
	<option value="local">Central Standard/Daylight Time
</SELECT>

<br><br>
<h3 class="subtitle">5) Data Format:</h3>
<SELECT name="format">
	<option value="tdf">Tab Delimited
	<option value="comma">Comma Delimited
</SELECT>

<p><h3>6) Include Lat/Lons?:</h3>
<select name="latlon">
  <option value="no">No
  <option value="yes">Yes
</select>

<br><br>
<h3 class="subtitle">7) Finally, get Data:</h3>

  <input type="submit" value="Get Data">
  <input type="reset">
</TD></TR></TABLE>
</form>



<?php include("$rootpath/include/footer.php"); ?>

