<?php 
include("../../config/settings.inc.php");

$year = date("Y");
$network = isset($_GET['network']) ? $_GET['network'] : "IA_ASOS";
$station = "";

include("$rootpath/include/database.inc.php");
include("$rootpath/include/google_keys.php");
include("$rootpath/include/imagemaps.php");
include("$rootpath/include/forms.php");
$api = $GOOGLEKEYS[$rooturl]["any"];
$HEADEXTRA = "<script src='http://maps.google.com/maps?file=api&amp;v=2&amp;key=$api'></script>
<script src='http://www.openlayers.org/api/OpenLayers.js'></script>
<script src='${rooturl}/js/olselect.php?network=${network}'></script>";
$TITLE = "IEM | Download Data";
$THISPAGE = "networks-asos";
$BODYEXTRA = "onload=\"init()\"";
include("$rootpath/include/header.php");
?>
<style type="text/css">
        #map {
            width: 450px;
            height: 450px;
            border: 2px solid black;
        }
</style>

<h3>ASOS data download</h3>
<p>The IEM archives observations from many of the sites in the United States.
This observation archive contains many sites from the MidWest back to 2001 and
the rest of the country since roughly 2007.  The Iowa data for the Iowa ASOS
network goes back to the 1970s for some sites.

<form name="netselect">
<table><tr><th>Select Network</th>
<td><?php echo selectAzosNetwork($network); ?></td>
<td><input type="submit" value="Switch to Network"></td>
</tr></table>
</form>


<TABLE>
<TR>
<TD valign="top">
<h3 class="subtitle">1) Select Station/Network by clicking on location: </h3>

<form method="GET" action="/cgi-bin/request/getData.py" name="olselect">
<div id="map"></div>
<div id="sname" unselectable="on">No site selected</div>


<p>In general, data from the Iowa ASOS network is almost always available.
Data from other states is more sporatic.  If you have any questions, please
don't hesitate to contact us.

<p><b>Other download pages:</b>
<ul>
  <li><a href="/request/awos/1min.php">1 minute interval Iowa AWOS data</a></li>
  <li><a href="<?php echo $rooturl; ?>/request/asos/1min.phtml">1 minute interval Iowa ASOS data</a></li>
  <li><a href="/request/rwis/fe.phtml">Iowa RWIS data</a></li>
</ul>

</TD>

<TD>
<P>Selected Station: <?php echo networkSelect($network, $station); ?>

<br><br>
<h3 class="subtitle">2) Select From Available Data:</h3>
<SELECT name="data" size="5" MULTIPLE>
	<option value="all" SELECTED>All Available
	<option value="tmpf">Air Temperature [F]
	<option value="dwpf">Dew Point [F]
	<option value="drct">Wind Direction 
	<option value="sknt">Wind Speed [knots]
	<option value="alti">Altimeter [inches]
	<option value="skyc">Cloud Coverage
	<option value="p01m">1 hour Precipitation [mm]
	<option value="vsby">Visibility [miles]
</SELECT>

<br><br>
<h3 class="subtitle">3) Select Date Range:</h3>
<SELECT name="timeRange"> 
	<Option value="allYear">Entire Year
	<option value="allMonth">Entire Month
	<option value="rangeMonth">Range of Months
	<option value="allDay">Entire Day
	<option value="rangeDays">Range of Days
</SELECT>

<br><br>
<h3 class="subtitle">4) Specific Date Range (If needed):</h3>
<TABLE>
<TR><TH>Start:</TH><TH>Stop:</TH></TR>

<TR>
 <TD colspan="2" align="center">
  <?php 
$y = 2001;
if ($network == "IA_ASOS") $y = 1970;
if ($network == "AWOS") $y = 1970;
echo yearSelect($y, $year, "year"); 

 ?>
 </TD>
</TR>

<TR>
 <TD>
   <SELECT name="month1">
   	<option value="1">January
	<option value="2">Febuary
	<option value="3">March
	<option value="4">April
	<option value="5">May
	<option value="6">June
	<option value="7">July
	<option value="8">August
	<option value="9">September
	<option value="10">October
	<option value="11">November
	<option value="12">December
   </SELECT>
 </TD>
 <TD>
    <SELECT name="month2">
   	<option value="1">January
	<option value="2">Febuary
	<option value="3">March
	<option value="4">April
	<option value="5">May
	<option value="6">June
	<option value="7">July
	<option value="8">August
	<option value="9">September
	<option value="10">October
	<option value="11">November
	<option value="12">December
   </SELECT>
 </TD>
</TR>

<tr>
 <td>
  <SELECT name="day1">
   <option value="1">1	 <option value="2">2	 <option value="3">3	 <option value="4">4
   <option value="5">5	 <option value="6">6	 <option value="7">7	 <option value="8">8
   <option value="9">9	 <option value="10">10   <option value="11">11   <option value="12">12
   <option value="13">13   <option value="14">14   <option value="15">15   <option value="16">16
   <option value="17">17   <option value="18">18   <option value="19">19   <option value="20">20
   <option value="21">21   <option value="22">22   <option value="23">23   <option value="24">24
   <option value="25">25   <option value="26">26   <option value="27">27   <option value="28">28
   <option value="29">29   <option value="30">30   <option value="31">31
  </SELECT>
 </td>
 <td>
  <SELECT name="day2">
   <option value="1">1	 <option value="2">2	 <option value="3">3	 <option value="4">4
   <option value="5">5	 <option value="6">6	 <option value="7">7	 <option value="8">8
   <option value="9">9	 <option value="10">10   <option value="11">11   <option value="12">12
   <option value="13">13   <option value="14">14   <option value="15">15   <option value="16">16
   <option value="17">17   <option value="18">18   <option value="19">19   <option value="20">20
   <option value="21">21   <option value="22">22   <option value="23">23   <option value="24">24
   <option value="25">25   <option value="26">26   <option value="27">27   <option value="28">28
   <option value="29">29   <option value="30">30   <option value="31">31
  </SELECT>
 </td>

</tr>

</TABLE>

<br><br>
<h3 class="subtitle">5) Include possible 20min observations?</h3>
<i> &nbsp; &nbsp; (Leave yes if unsure)</i>
<SELECT name="include20s">
	<option value="yes">Yes
	<option value="no">No
</SELECT>

<br><br>
<h3 class="subtitle">6) Format of time output:</h3>
<SELECT name="tz">
	<option value="GMT">GMT (UTC) timestamps
	<option value="local">Central Standard/Daylight Time
</SELECT>

<br><br>
<h3 class="subtitle">7) Data Format:</h3>
<SELECT name="format">
	<option value="tdf">Tab Delimited
	<option value="space">Space Delimited
	<option value="comma">Comma Delimited
</SELECT>

<br><br>
<h3 class="subtitle">8) Finally, get Data:</h3>

  <input type="submit" value="Get Data">
  <input type="reset">
</TD></TR></TABLE>
</form>

</TD></TR></div>

<?php include("$rootpath/include/footer.php"); ?>

