<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
	"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1"></meta>
<link rel="stylesheet" href="../include/phplayersmenu/layersmenu-demo.css" type="text/css"></link>
<link rel="stylesheet" href="../include/phplayersmenu/layerstreemenu.css" type="text/css"></link>
<style type="text/css">
<!--
@import url("../include/phplayersmenu/layerstreemenu-hidden.css");
//-->
</style>
<?php include ("../include/phplayersmenu/libjs/layersmenu-browser_detection.js"); ?>
<script language="JavaScript" type="text/javascript" src="../include/phplayersmenu/libjs/layerstreemenu-cookies.js"></script>
<base target="bodyframe"></base>
</head>
<body style="background-color: #ffffff; margin: 3px;">

<div class="normal">
Site Index , <a href="/" target="_top">Quit</a>
</div>
<?php
include ("../include/phplayersmenu/lib/PHPLIB.php");
include ("../include/phplayersmenu/lib/layersmenu-common.inc.php");
include ("../include/phplayersmenu/lib/treemenu.inc.php");
$myDirPath = "../include/phplayersmenu/";
$myWwwPath = "/include/phplayersmenu/";
$mid = new TreeMenu();
$mid->setDirroot($myDirPath);
$mid->setLibdir($myDirPath . "lib/");
$mid->setLibjsdir($myDirPath . "libjs/");
$mid->setLibjswww($myWwwPath . "libjs/");
$mid->setImgdir($myDirPath . "images/");
$mid->setImgwww($myWwwPath . "images/");
$mid->setMenuStructureFile("si.txt");
$mid->parseStructureForMenu("treemenu1");
$mid->newTreeMenu("treemenu1");
$mid->printTreeMenu("treemenu1");
?>

</body>
</html>
