<?php 
include("../../config/settings.inc.php");
include("../../include/myview.php");
include("../../include/mlib.php");
include("../../include/network.php");
include("../../include/iemaccess.php");
include("../../include/iemaccessob.php");
require_once "../../include/forms.php";
$nt = new NetworkTable("SCAN");
$cities = $nt->table;

$sortcol = isset($_GET["sortcol"]) ? xssafe($_GET["sortcol"]): 'station';
$t = new MyView();
$t->title = "SCAN Sortable Currents";
$t->refresh = "<meta http-equiv=\"refresh\" content=\"3600;\">";
$t->headextra = <<<EOF
<script language="JavaScript" type="text/javascript">
<!--//BEGIN Script
function new_window(url) {
 link = window.open(url,"_new","toolbar=0,location=0,directories=0,status=0,menubar=no,scrollbars=yes,resizable=yes,width=650,height=500");
} 
//END Script-->
</script>
EOF;
$t->thispage = "current-sort";

$iem = new IEMAccess();
$scan = $iem->getNetwork("SCAN");

function make_link($sid){
	return sprintf("/sites/site.php?network=SCAN&station=%s", $sid);
}

function aSortBySecondIndex($multiArray, $secondIndex) {
	while (list($firstIndex, ) = each($multiArray))
		$indexMap[$firstIndex] = $multiArray[$firstIndex][$secondIndex];
	arsort($indexMap);
	while (list($firstIndex, ) = each($indexMap))
	if (is_numeric($firstIndex))
		$sortedArray[] = $multiArray[$firstIndex];
	else $sortedArray[$firstIndex] = $multiArray[$firstIndex];
	return $sortedArray;
}

$mydata = Array();

while (list($key, $iemob) = each($scan) ){
	$mydata[$key] = $iemob->db;
	$mydata[$key]["ts"] = $iemob->ts;
	$mydata[$key]["sped"] = $mydata[$key]["sknt"] * 1.15078;
	$mydata[$key]["relh"] = relh(f2c($mydata[$key]["tmpf"]),
			f2c($mydata[$key]["dwpf"]) );
	$mydata[$key]["feel"] = feels_like($mydata[$key]["tmpf"],
			$mydata[$key]["relh"], $mydata[$key]["sped"]);
	if ($mydata[$key]["max_gust"] > $mydata[$key]["max_sknt"]){
		$mydata[$key]["peak"] = $mydata[$key]["max_gust"];
		$mydata[$key]["peak_ts"] = strtotime(substr( $mydata[$key]["max_gust_ts"],0,16) );
	} else {
		$mydata[$key]["peak"] = $mydata[$key]["max_sknt"];
		if ($mydata[$key]["max_sknt_ts"] > 0){
			$mydata[$key]["peak_ts"] = strtotime(substr( $mydata[$key]["max_sknt_ts"],0,16) );
		}
	}

}


$finalA = Array();
$finalA = aSortBySecondIndex($mydata, $sortcol);
$i = 0;
$now = time();

$t1 = "";
// Loop though all data
while (list ($key, $val) = each ($finalA))  {
	$parts = $finalA[$key];
	$i++;
	$tdiff = $now - $parts["ts"];
	// Don't show stations over 5 days old
	if ($tdiff > 86400*5){
		continue;
	}
	$t1 .= "<tr";
	if ($i % 2 == 0)  $t1 .= " bgcolor='#eeeeee'";

	$t1 .= ">";
	$t1 .= "<td><input type=\"checkbox\" name=\"st[]\"
               value=\"".$key."\"></td>";
	$t1 .= "<td><a href=\"". make_link($key) ."\">". $cities[$key]["name"] . "</a></td><td ";
	if ($tdiff > 11900){
		$t1 .= 'bgcolor="red"';
		$format = "%b-%d-%y %I:%M %p";
	} else if ($tdiff > 9600){
		$t1 .= 'bgcolor="orange"';
		$format = "%I:%M %p";
	} else if ($tdiff > 7200){
		$t1 .= 'bgcolor="green"';
		$format = "%I:%M %p";
	} else {
		$format = "%I:%M %p";
	}
	$t1 .= ">". strftime($format, $parts["ts"]) ."</td>
  <td align='center'>". round($parts["tmpf"],0) ."(<font color=\"#ff0000\">".
  round($parts["max_tmpf"],0) ."</font>/<font color=\"#0000ff\">".
  round($parts["min_tmpf"],0) ."</font>)</td>
 <td>". round($parts["dwpf"],0) ."</td>
 <td>". $parts["feel"] ."</td>
 <td>". $parts["relh"] ."</td>
 <td>". round($parts["sknt"],0) ;
	if (strlen($parts["gust"]) > 0 && $parts["gust"] > 0){
		$t1 .= "G". $parts["gust"];
	}
	$t1 .= "</td><td>". round($parts["drct"],0) ."</td>";
	$t1 .= "<td>";
	if (array_key_exists("peak_ts", $parts)){
		$t1 .= round($parts["peak"],0) ."@ ". strftime("%I:%M %p", $parts["peak_ts"]) ;
	}	
	$t1 .= "</td><td>". round($parts["srad"],0) ."</td></tr>";
}

$t2 = "";
$n = $finalA;
while (list ($key, $val) = each ($n))  {
	$parts = $finalA[$key];
	$tdiff = $now - $parts["ts"];
	// Don't show stations over 5 days old
	if ($tdiff > 86400*5){
		continue;
	}
	$i++;
	$t2 .= "<tr";
	if ($i % 2 == 0)  $t2 .= " bgcolor='#eeeeee'";

	$t2 .= ">";
	$t2 .= "<td><a href=\"". make_link($key) ."\">". $cities[$key]["name"] . "</a></td></td><td ";
	if ($tdiff > 11900){
		$t2 .= 'bgcolor="red"';
		$format = "%b-%d-%y %I:%M %p";
	} else if ($tdiff > 9600){
		$t2 .= 'bgcolor="orange"';
		$format = "%I:%M %p";
	} else if ($tdiff > 7200){
		$t2 .= 'bgcolor="green"';
		$format = "%I:%M %p";
	} else {
		$format = "%I:%M %p";
	}
	$t2 .= ">". strftime($format, $parts["ts"]) ."</td>
    <td>". round($parts["c1smv"],0) ."</td><td>". round($parts["c1tmpf"],0) ."</td>
    <td>". round($parts["c2smv"],0) ."</td><td>". round($parts["c2tmpf"],0) ."</td>
    <td>". round($parts["c3smv"],0) ."</td><td>". round($parts["c3tmpf"],0) ."</td>
    <td>". round($parts["c4smv"],0) ."</td><td>". round($parts["c4tmpf"],0) ."</td>
    <td>". round($parts["c5smv"],0) ."</td><td>". round($parts["c5tmpf"],0) ."</td>";

	$t2 .= "</tr>";
}

$vals = Array("tmpf" => "Air Temperature [F]", "dwpf" => "Dew Point Temp [F]",
  "sknt" => "Wind Speed [knots]", "wdir" => "Wind Direction [deg]",
  "pday" => "Precip Accum [inches]", "max_sknt" => "Wind Gust [knots]",
  "ts" => "Observation Time [local]", "feel" => "Feels Like",
  "min_tmpf" => "Today's Low Temperature", "srad" => "Solar Radiation",
  "max_tmpf" => "Today's High Temperature",
  "station" => "Station ID", "relh" => "Relative Humidity");

$c = "javascript:new_window('/GIS/apps/php/currents.phtml?layers[]=radar&layers[]=labels&network=SCAN&var=";

$t->current_network = 'SCAN';
$t->content = <<<EOF
<h3>Current SCAN Conditions</h3>

Sorted by: <b>({$vals[$sortcol]})</b>  &nbsp; &nbsp; Click on
a column to sort it.<br>

<form method="GET" action="/my/current.phtml">
<table class="table table-striped">
<thead>
<tr>
  <th rowspan="2">ADD:</th>
  <th rowspan="2">Station:</th>
  <th rowspan="2"><a href="current.phtml?sortcol=ts">Ob Time</a></th>
  <th colspan="3">Temps &deg;F</th>
  <th>&nbsp;</th>
  <th colspan="3">Wind [knots]</th>
  <th>&nbsp;</th>
<tr>
  
  <th>
   <a href="current.phtml?sortcol=tmpf">Air</a>
   (<a href="current.phtml?sortcol=max_tmpf">Hi</a> /
   <a href="current.phtml?sortcol=min_tmpf">Lo</a>)
</th>
  <th><a href="current.phtml?sortcol=dwpf">DewP</a></th>
  <th><a href="current.phtml?sortcol=feel">Feels</a></th>
  <th><a href="current.phtml?sortcol=relh">RH%</a></th>
  <th><a href="current.phtml?sortcol=sknt">Speed</a></th>
  <th><a href="current.phtml?sortcol=drct">Direction</a></th>
  <th><a href="current.phtml?sortcol=max_sknt">Gust</a>
    @<a href="current.phtml?sortcol=gtim">Time</a></th>
  <th><a href="current.phtml?sortcol=srad">Solar Rad</a></th>
</tr></thead>
<tbody>
{$t1}
</tbody>
<tfoot>
<tr>
 <td colspan=3>&nbsp;</td>
<?php  ?>
 <td><a href="{$c}tmpf');">Plot</a>
    (<a href="{$c}max_tmpf');">Plot</a> /
     <a href="{$c}min_tmpf');">Plot</a>)</td>
 <td><a href="{$c}dwpf');">Plot</a></td>
 <td><a href="{$c}feel');">Plot</a></td>
 <td><a href="{$c}relh');">Plot</a></td>
 <td colspan=2><a href="{$c}barb');">Plot</a></td>
 <td><a href="{$c}max_sknt');">Plot</a></td>
 <td>&nbsp;</td>
</tr></tfoot>
</table>
<input type="submit" value="Add to Favorites">
<input type="reset" value="Reset">

</form>

<br><br>

<h3>SCAN Soil Conditions</h3>

<table class="table table-striped">
<thead>
 <tr>
  <th colspan=2>&nbsp;</th>
  <th colspan=2>2 inch</th>
  <th colspan=2>4 inch</th>
  <th colspan=2>8 inch</th>
  <th colspan=2>20 inch</th>
  <th colspan=2>40 inch</th>
 </tr>
 <tr>
  <th>Station:</th>
  <th>Ob Time:</th>
  <th>Moist:</th><th>Temp:</th>
  <th>Moist:</th><th>Temp:</th>
  <th>Moist:</th><th>Temp:</th>
  <th>Moist:</th><th>Temp:</th>
  <th>Moist:</th><th>Temp:</th>
 </tr></thead>
<tbody>{$t2}</tbody>
<tfoot>
<tr>
<td colspan="12">&nbsp;</td>
</tr>
</tfoot>
</table>
EOF;
$t->render("sortables.phtml");
?>
