<?php 
require_once "../../config/settings.inc.php";
require_once "../../include/myview.php";
$t = new MyView();
$t->title = "Soil Climate Analysis Network";
$t->thispage = "networks-scan";

$baseuri = "https://wcc.sc.egov.usda.gov/nwcc/site";
$t->content = <<<EOF
<h3>SCAN Network</h3>

<p>This page contains data for the Ames SCAN site
provided by the National Water & Climate Center (NWCC).  SCAN is
an acronym for <i>Soil Climate Analysis Network</i>. Although this station
does provide atmospheric data, its main purpose is to provide soil
information from five depths.</p>

<div class="well pull-right">
<b>SCAN</b>
<br>Reports: 1x per Hour
<br>IA Stations: 2
<br><a href="/sites/locate.php?network=SCAN">Locations</a>
</div>

<h3>Data Products:</h3>

<ul>
 <li><a href="/scan/current.phtml">Sortable Current Conditions</a></li>
 <li><a href="/plotting/scan/">Current/Historical Timeseries Plots</a></li>
 <li><a href="/request/scan/fe.phtml">Download Hourly data</a></li>
</ul>



<p><h3>Station Locations</h3><br>
<table class="table table-striped">
		<thead>
<tr>
  <th>Station</th>
  <th>Site #</th>
  <th>Latitude</th>
  <th>Longitude</th>
  <th>Elevation</th>
</tr>
		</thead>

<tr>
  <th><a href="${baseuri}?sitenum=2031&state=ia">Ames, IA</a></th>
  <td>2031</td>
  <td>42&deg;00' N</td>
  <td>93&deg;43' W</td>
  <td>1073 Feet</td>
</tr>

<tr>
  <th><a href="${baseuri}?sitenum=2068&state=ia">Shagbark Hills, IA</a></th>
  <td>2068</td>
  <td>42&deg;26' N</td>
  <td>95&deg;46' W</td>
  <td>1400 Feet</td>
</tr>


<tr>
  <th><a href="${baseuri}?sitenum=2001&state=ne">Rodger's Farm, NE</a></th>
  <td>2001</td>
  <td>40&deg;51' N</td>
  <td>96&deg;28' W</td>
  <td>1215 Feet</td>
</tr>

<tr>
  <th><a href="${baseuri}?sitenum=2047&state=mo">Spickard, MO</a></th>
  <td>2047</td>
  <td>40&deg;14' N</td>
  <td>93&deg;42' W</td>
  <td>911 Feet</td>
</tr>

<tr>
  <th><a href="${baseuri}?sitenum=2004&state=il">Mason, IL</a></th>
  <td>2004</td>
  <td>40&deg;19' N</td>
  <td>89&deg;54' W</td>
  <td>495 Feet</td>
</tr>


</table></div>
EOF;
$t->render('single.phtml');
?>
