<?php
// akrherz-laptop
//$GMAPS = "ABQIAAAArXt77YptylBNPFEy0AgJxBTEPTchOOxox1p8iAIUd6vZPwtmshSf1SjZDs8mgJqi8O6Q9LzLekF7WA";
// mesonet
$GMAPS = "ABQIAAAArXt77YptylBNPFEy0AgJxBRsfiNEA0kVU4cf1gE-kIxF-2kj4BT9CFWPUXEdhqnHcAtP5mmsd-IFkg";

?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
  <head>
   <style type="text/css" media="screen">@import "../css/main.css";</style>
    <script src="http://maps.google.com/maps?file=api&v=1&key=<?php echo $GMAPS; ?>" type="text/javascript"></script>
  </head>
  <body>
<div id="justone">
<h2>Google Maps Interface</h2>
    
<div id="map" style="margin-left: 20px; width: 640px; height: 480px"></div>

<script type="text/javascript">
    //<![CDATA[
    var map = new GMap(document.getElementById("map"));
    map.addControl(new GLargeMapControl());
    map.addControl(new GMapTypeControl());


    map.centerAndZoom(new GPoint(-93.922, 41.850), 7);

    function createMarker(point, html) {
      var marker = new GMarker(point);
      GEvent.addListener(marker, "click", function() {
         marker.openInfoWindowHtml(html);
      });
      return marker;
    }

  var point = new GPoint(-93.923, 41.849);
  var marker = createMarker(point, "<div style=\"width: 200px\">Damage details for Point 1<br /><img src=\"madrid_051112.jpg\"></div>");
  map.addOverlay(marker);
  var point = new GPoint(-93.922, 41.850);
  var marker = createMarker(point, "<div style=\"width: 200px\">Damage details for Point 2</div>");
  map.addOverlay(marker);
  var point = new GPoint(-93.698, 42.036);
  var marker = createMarker(point, "<div style=\"width: 200px\">Damage details for Point 3</div>");
  map.addOverlay(marker);

    //]]>
    </script>
  </body>
</html>
