<?php
 /* storm/del.phtml */
include_once("../../../config/settings.inc.php");
include("$rootpath/include/database.inc.php");
$pg = iemdb("squaw");
include_once("$rootpath/include/squaw/storm.inc.php");
include_once("$rootpath/include/squaw/constants.inc.php");
include_once("$rootpath/include/squaw/forms.inc.php");

$id = isset($_GET["id"]) ? $_GET["id"] : -1;
$id = intval($id) or die("Error: Type of ID is incorrect, must be an int");

$mystorm = new storm($id);
if (isset($_GET["confirm"]) )
{
	$mystorm->delete();
	header("Location: index.phtml");
	die();
}
?>
<?php $THISPAGE = "storm"; include("$rootpath/include/squaw/header.inc.php"); ?>

<div id="content">

<form method="GET" action="del.phtml">

<p><b>Are you sure you want to delete this storm?</b>

<input type="hidden" name="confirm" value="yes">
<input type="hidden" name="id" value="<?php echo $id; ?>">

<p><input type="submit" value="Delete!">
</form>

</div>
 
<?php include("$rootpath/include/footer.php"); ?>
