<?php 
include("../../../config/settings.inc.php");
include("../../../include/myview.php");
include_once "../../../include/database.inc.php";
include("../../../include/imagemaps.php");
include("../../../include/forms.php"); 

$mesosite = iemdb('mesosite');
$network = isset($_REQUEST['network']) ? $_REQUEST["network"] : 'IA_COOP';

define("IEM_APPID", 45);
$t = new MyView();
$t->title = "NWS COOP Raw Observations Download"; 
$t->thispage = "networks-coop";

$t->north = <<<EOF
<ol class="breadcrumb">
<li><a href="/COOP/">NWS COOP Network</a></li>
<li class="active">Raw Data Download</li>
</ol>

<p>This form provides access to the raw observations from the NWS COOP network. The
high and low temperature values are for the 24 hour period prior to the observation
on the date! Typically, this is a period ending at 8 AM localtime.</p>
EOF;

$west = <<<EOF
<form method="GET" name="chstate">
<p>Select from State: <select name="network">
EOF;

$rs = pg_query($mesosite, "SELECT id, name from networks where id ~* 'COOP' 
		ORDER by name ASC");
for ($i=0;$row=@pg_fetch_assoc($rs,$i);$i++){
	$sel = '';
	if ($network == $row["id"]){
		$sel = " selected='SELECTED'";
	}
	$west .= sprintf("<option value='%s'%s>%s</option>\n",
	  $row["id"], $sel, $row["name"]);
}

$west .= <<<EOF
</select>
<input type="submit" value="Change Network" />
</form>


<form method="GET" action="obs-dl.php" name='dl'>
<input type='hidden' name='network' value="{$network}" />

<p><h3 class="subtitle">1. Select Station(s):</h3><br>
EOF;
$west .= networkMultiSelect($network, ""); 

$y1 = yearSelect2(2010, date("Y"), "year1");
$m1 = monthSelect("", "month1");
$d1 = daySelect2("", "day1");
$y2 = yearSelect2(2010, date("Y"), "year2");
$m2 = monthSelect("", "month2");
$d2 = daySelect2("", "day2");

$west .= <<<EOF
<p><h3 class="subtitle">2. Select Start/End Time:</h3><br>
<table class="table table-striped">
  <tr>
    <td></td>
    <th>Year</th><th>Month</th><th>Day</th>
  </tr>

  <tr>
    <th>Start:</th>
    <td>{$y1}</td><td>{$m1}</td><td>{$d1}</td>
		</tr>

  <tr>
    <th>End:</th>
    <td>{$y2}</td><td>{$m2}</td><td>{$d2}</td>
  </tr>
</table>

EOF;
$t->west = $west;
$t->east = <<<EOF
<p><h3 class="subtitle">3. How to view?</h3><br>
<select name="what">
  <option value="download">Download to Disk
  <option value="view">View on-line
</select>

<p><h3 class="subtitle">4. Data Delimitation:</h3><br>
How shall the output values be seperated?
<br><select name="delim">
    <option value="comma">Comma
    <option value="space">Space
    <option value="tab">Tab
   </select>

<p><h3 class="subtitle">Submit Form:</h3><br>
<input type="submit" value="Process Data Request">
<input type="reset">
</form>
EOF;

$t->render('single.phtml');
?>