<?php
require_once "../../../config/settings.inc.php";
require_once "../../../include/myview.php";
require_once "../../../include/database.inc.php";
require_once "../../../include/imagemaps.php";
require_once "../../../include/forms.php";

$mesosite = iemdb('mesosite');
$network = isset($_REQUEST['network']) ? xssafe($_REQUEST["network"]) : 'IA_COOP';

define("IEM_APPID", 45);
$t = new MyView();
$t->title = "NWS COOP Raw Observations Download";

$content = <<<EOF
<ol class="breadcrumb">
<li><a href="/COOP/">NWS COOP Network</a></li>
<li class="active">Raw Data Download</li>
</ol>

<p>This form provides access to the raw observations from the NWS COOP network.
<strong>The date presented in the download is the date on which the observation
        was made!</strong> The observations represent a 24 hour period prior
        to the timestamp on the observation.  These observations are typically
        made around 7 AM localtime.</p>
EOF;

$west = <<<EOF
<form method="GET" name="chstate">
<p>Select from State: <select name="network">
EOF;

$rs = pg_query($mesosite, "SELECT id, name from networks where id ~* 'COOP' 
        ORDER by name ASC");
for ($i = 0; $row = pg_fetch_assoc($rs); $i++) {
    $sel = '';
    if ($network == $row["id"]) {
        $sel = " selected='SELECTED'";
    }
    $west .= sprintf(
        "<option value='%s'%s>%s</option>\n",
        $row["id"],
        $sel,
        $row["name"]
    );
}

$west .= <<<EOF
</select>
<input type="submit" value="Change Network" />
</form>


<form method="GET" action="obs-dl.php" name='dl'>
<input type='hidden' name='network' value="{$network}" />

<p><h3>1. Select Station(s):</h3><br>
EOF;
$west .= networkMultiSelect($network, "", array(), "station[]");

$y1 = yearSelect2(2010, date("Y"), "year1");
$m1 = monthSelect("", "month1");
$d1 = daySelect2("", "day1");
$y2 = yearSelect2(2010, date("Y"), "year2");
$m2 = monthSelect("", "month2");
$d2 = daySelect2("", "day2");

$west .= <<<EOF
<p><h3>2. Select Start/End Date:</h3>
<p>These dates are the date of the observation and do not always represent
a local calendar day!.</p>
<table class="table table-striped">
  <tr>
    <td></td>
    <th>Year</th><th>Month</th><th>Day</th>
  </tr>

  <tr>
    <th>Start:</th>
    <td>{$y1}</td><td>{$m1}</td><td>{$d1}</td>
        </tr>

  <tr>
    <th>End:</th>
    <td>{$y2}</td><td>{$m2}</td><td>{$d2}</td>
  </tr>
</table>

EOF;
$east = <<<EOF
<p><h3>3. How to view?</h3><br>
<select name="what">
  <option value="download">Download to Disk
  <option value="view">View on-line
</select>

<p><h3 class="subtitle">4. Data Delimitation:</h3><br>
How shall the output values be seperated?
<br><select name="delim">
    <option value="comma">Comma
    <option value="space">Space
    <option value="tab">Tab
   </select>

<p><h3 class="subtitle">Submit Form:</h3><br>
<input type="submit" value="Process Data Request">
<input type="reset">
</form>

<p><h3>Download variable description</h3>
<pre>
nwsli National Weather Service Location Identifier
date  Date the observation was taken
time  Time (local timezone) the observation was taken
high_F      24 Hour High Temperature [F]
low_F       24 Hour Low Temperature [F]
precip      24 Hour Precipitation [inch]
snow_inch   24 Hour Snowfall [inch]
snowd_inch  Snow Depth [inch] at observation
</pre>

EOF;
$t->content = <<<EOM
$content
<div class="row">
<div class="col-md-6">
$west
</div>
<div class="col-md-6">
$east
</div>
</div>

EOM;

$t->render('single.phtml');
