<?php
date_default_timezone_set('America/Chicago');
$rootpath='/mesonet/www/apps/iemwebsite/';
$rooturl='http://mesonet.agron.iastate.edu';
$rootcgi='http://mesonet.agron.iastate.edu/cgi-bin';
$mapscript='php_mapscript_564.so';
$fb_feature_key='';
$fb_feature_secret='';
$fb_feature_id='';
?>
