<?php
include("../../config/settings.inc.php");
$TITLE = "IEM | Presentations";
include("$rootpath/include/header.php"); ?>


<h3 class="heading">Presentation Archive</h3><p>

<img src="/~akrherz/images/sandiego066.jpg" width="180" style="float: left; margin: 5px;">

<p>We have been honored to present our work on a number of occasions across the United States.  Here is a listing of presentations and the electronic materials used during the talks.  If there is an IEM talk you attended and not found on this list, please let us know. 

<p>Click the date in the table to view materials used during the presentation.

<br clear="all" />

<table>
<thead>
<tr>
 <th>Date</th><th>Event</th><th>Location</th>
</tr>
</thead>

<tbody>
<tr><td><a href="/present/011004_isu">2001 Oct 04</a></td><td>Iowa State Meteorology Department Seminar</td><td>Ames, IA</td></tr> 
<tr><td><a href="/present/020322_CInwa">2002 Mar 22</a></td><td>Central Iowa NWA Severe Storms Conference</td><td>Des Moines, IA</td></tr>
<tr><td><a href="/present/020405_oax">2002 Apr 05</a></td><td>NWS Omaha presentation</td><td>Omaha, NE</td></tr>
<tr><td><a href="/present/020626_suth">2002 Jun 26</a></td><td>ISU Experiment Farm Day</td><td>Sutherland, IA</td></tr>
<tr><td><a href="/present/020812_ncar">2002 Aug 12</a></td><td>NCAR GIS Conference</td><td>Boulder, CO</td></tr>
<tr><td><a href="/present/020825_barons">2002 Aug 25</a></td><td>Baron Services Training Conference</td><td>Huntsville, AL</td></tr>
<tr><td><a href="/present/020924_isu">2002 Sep 24</a></td><td>Iowa State Meteorology Department Seminar</td><td>Ames, IA</td></tr>
<tr><td><a href="/present/021021_nwa">2002 Oct 21</a></td><td>National Weather Association Annual Meeting</td><td>Fort Worth, TX</td></tr>
<tr><td><a href="/present/021120_isugis">2002 Nov 20</a></td><td>Iowa State GIS Day</td><td>Ames, IA</td></tr>
<tr><td><a href="/present/021120_marshall">2002 Nov 20</a></td><td>Marshall County GIS Day</td><td>Ames, IA</td></tr>
<tr><td><a href="/present/030211_ams">2003 Feb 11</a></td><td>American Meteorological Society Annual Meeting</td><td>Long Beach, CA</td></tr>
<tr><td><a href="/present/030218_cipco">2003 Feb 18</a></td><td>KCCI SchoolNet Training Inservice</td><td>Des Moines, IA</td></tr>
<tr><td><a href="/present/030514_epa">2003 May 14</a></td><td>EPA Environmental Monitoring Conference</td><td>Kansas City, MO</td></tr>
<tr><td><a href="/present/030625_unidata">2003 Jun 25</a></td><td>UNIDATA Expanding Horizons Conference</td><td>Boulder, CO</td></tr>
<tr><td><a href="/present/030701_igic">2003 Jul 01</a></td><td>Iowa Geographic Information Council Annual Meeting</td><td>Ames, IA</td></tr>
<tr><td><a href="/present/030917_nevada">2003 Sep 17</a></td><td>SchoolNet training workshop</td><td>Nevada, IA</td></tr>
<tr><td><a href="/present/031014_isu">2003 Oct 14</a></td><td>Iowa State Meteorology Department Seminar</td><td>Ames, IA</td></tr>
<tr><td><a href="/present/031022_igic">2003 Oct 22</a></td><td>Iowa Geographic Information Council Quarterly meeting (video conference)</td><td>Ames, IA</td></tr>
<tr><td><a href="/present/031105_asa">2003 Nov 05</a></td><td>American Society of Agronomy Annual Meeting</td><td>Denver, IA</td></tr>
<tr><td><a href="/present/031121_fsd">2003 Nov 21</a></td><td>NWS Sioux Falls Presentation</td><td>Sioux Falls, IA</td></tr>
<tr><td><a href="/present/040115_ams">2004 Jan 15</a></td><td>American Meteorological Society Annual Meeting</td><td>Seattle, WA</td></tr>
<tr><td><a href="/present/040224_cipco">2004 Feb 24</a></td><td>KCCI SchoolNet Training Inservice</td><td>Des Moines, IA</td></tr>
<tr><td><a href="/present/040227_dvn">2004 Feb 27</a></td><td>NWS Davenport Presentation</td><td>Davenport, IA</td></tr>
<tr><td><a href="/present/040318_lse">2004 Mar 18</a></td><td>NWS LaCrosse Presentation</td><td>LaCrosse, WI</td></tr>
<tr><td><a href="/present/040918_baron">2004 Sep 18</a></td><td>Baron Services Training Conference</td><td>Huntsville, AL</td></tr>
<tr><td><a href="/present/050512_ams/">2005 Jan 12</a></td><td>American Meteorological Society Annual Meeting</td><td>San Diego, CA</td></tr>
<tr><td><a href="/present/050405_cipco">2005 Apr 05</a></td><td>KCCI SchoolNet Training Inservice</td><td>Des Moines, IA</td></tr>
<tr><td><a href="/present/050420_nasa">2005 Apr 20</a></td><td>Iowa-NASA Data Integration Workshop</td><td>Ames, IA</td></tr>

</tbody>
</table>


<?php include("$rootpath/include/footer.php"); ?>
