<?php
include("../../../../config/settings.inc.php");
include("$rootpath/include/forms.php");
$uri = "fe.phtml";

$year = isset($_GET["year"]) ? $_GET["year"] : 1971;
$month = isset($_GET["month"]) ? $_GET["month"] : 1;
$day = isset($_GET["day"]) ? $_GET["day"] : 1;
$metric = isset($_GET["metric"]) ? $_GET["metric"]: "";
$ts = mktime(0, 0, 0, $month, $day, $year);
$dstr = date("Y-m-d", $ts);

$oextents = isset($_GET['extents']) ? $_GET['extents'] : "-104.5, 35, -80.3, 49";
$zoom     = isset($_GET['zoom']) ? $_GET['zoom'] : 0;
$pvar = isset($_GET['pvar']) ? $_GET['pvar'] : "rainfall_in";

if ($zoom == 99) {
 $oextents = "-104.5, 35, -80.3, 49";
}

 $imgwidth = 640;
 $imgheight = 480;
 if ( isset($_GET['img_x']) ){
   include("$rootpath/include/click2geo.inc.php");
   $extents = click2geo($oextents, $_GET['img_x'], $_GET['img_y'],
     $_GET['map_width'], $_GET['map_height'], $zoom);
 } else {
   $extents = $oextents;
 }

$keep_vars = Array("pvar" => $pvar, "metric" => $metric, "extents" => $extents,
  "dstr" => date("Y-m-d", $ts) );


$nicedate = strftime("%d %b %Y", $ts);



$imgurl = "plot.php?var=$pvar&extents=$extents&dstr=$dstr";

?>
<?php 
 include("$rootpath/include/header.php"); 
 include("side.phtml");
?>

<form method="GET" action="fe.phtml" name="myform">

<div class="table">
<table>
<thead>
<tr>
<th>Plot Variable</th>
<th>Date</th>
</tr>
</thead>
<tbody>
<tr>
<td>
 <select name="pvar">
	<option value="rainfall_in" <?php if ($pvar == "rainfall_in") echo "SELECTED"; ?>>Rainfall Total [in]
	<option value="dailyhigh" <?php if ($pvar == "dailyhigh") echo "SELECTED"; ?>>Daily High Temperature [F]
	<option value="dailylow" <?php if ($pvar == "dailylow") echo "SELECTED"; ?>>Daily Low Temperature [F]
	<option value="rh" <?php if ($pvar == "rh") echo "SELECTED"; ?>>Relative Humidity [%]
	<option value="evap" <?php if ($pvar == "evap") echo "SELECTED"; ?>>Daily Evaporation [in]
	<option value="solar" <?php if ($pvar == "solar") echo "SELECTED"; ?>>Solar Radiation [MJ]
 </select>
</td>
<td>
 <?php echo yearSelect(1971,$year); ?>
 <?php echo monthSelect($month); ?>
 <?php echo daySelect($day); ?>
</td>

</tr>
</tbody>
</table>
</div>

<br /><input type="submit" value="Generate Map">


<p>
<input type="hidden" name="map_height" value="<?php echo $map->height; ?>">
<input type="hidden" name="map_width" value="<?php echo $map->width; ?>">
<input type="hidden" name="ul_x" value="<?php echo $map->extent->minx; ?>">
<input type="hidden" name="ul_y" value="<?php echo $map->extent->maxy ; ?>">
<input type="hidden" name="lr_x" value="<?php echo $map->extent->maxx; ?>">
<input type="hidden" name="lr_y" value="<?php echo $map->extent->miny ; ?>">
<input type="hidden" name="extents" value="<?php echo $map->extent->minx .",".$map->extent->miny .",".$map->extent->maxx .",".$map->extent->maxy ; ?>">
<input type="hidden" name="zoom" value="1">
<script Language="JavaScript">
 function resetButtons(){
   document.myform.action = 'fe.phtml';
   document.panButton.src = '../imagenav/button_pan_off.png';
   document.zoominButton.src = '../imagenav/button_zoomin_off.png';
   document.zoomoutButton.src = '../imagenav/button_zoomout_off.png';
   document.queryButton.src = '../imagenav/button_query_off.png';
 }
</script>
<b>Map Controls:</b>
<img src="../imagenav/button_zoomfull_off.png" name="zoomfullButton" alt="Full Extents"
  onClick="javascript: resetButtons(); document.zoomfullButton.src = '../imagenav/button_zoomfull_on.png'; document.myform.zoom.value = 99; document.myform.submit();">
<img src="../imagenav/button_zoomin_off.png" name="zoominButton" alt="Zoom In"
  onClick="javascript: resetButtons(); document.zoominButton.src = '../imagenav/button_zoomin_on.png'; document.myform.zoom.value = -2;">
<img src="../imagenav/button_pan_on.png" name="panButton" alt="Pan"
  onClick="javascript: resetButtons(); document.panButton.src = '../imagenav/button_pan_on.png'; document.myform.zoom.value = 1;">
<img src="../imagenav/button_zoomout_off.png" name="zoomoutButton" alt="Zoom Out"
  onClick="javascript: resetButtons(); document.zoomoutButton.src = '../imagenav/button_zoomout_on.png'; document.myform.zoom.value = 2;">
<img src="../imagenav/button_query_off.png" name="queryButton" alt="Query"
  onClick="javascript: resetButtons(); document.queryButton.src = '../imagenav/button_query_on.png'; document.myform.action = 'click.php';">

<p><div style="width: 650px;"><input type="image" name="img" src="<?php echo $imgurl; ?>" border="1" height="480" width="640"></div>
</form>
<script language="JavaScript">
<!-- // as
var cal = new calendar2(document.forms['myform'].elements['dstr']);
cal.year_scroll = true;
cal.time_comp = false;
//-->
</script>

</td></tr></table>

<?php include("$rootpath/include/footer.php"); ?>
