<?php
/* Webcam Scheduler!!!! */
require_once "../../../config/settings.inc.php";
require_once "../../../include/cameras.inc.php";
require_once "../../../include/database.inc.php";
require_once "../../../include/forms.php";
$conn = iemdb("mesosite", TRUE, TRUE);

$id = isset($_GET["id"]) ? $_GET["id"] : "";
$day = isset($_GET["day"]) ? $_GET["day"] : date("d");
$month = isset($_GET["month"]) ? $_GET["month"]: date("m");
$year = isset($_GET["year"]) ? $_GET["year"] : date("Y");
$hour = isset($_GET["hour"]) ? $_GET["hour"]: date("H");
$minute = isset($_GET["minute"]) ? $_GET["minute"]: 0;
$dur = isset($_GET["dur"]) ? intval($_GET["dur"]): 60;
$movie_seconds = isset($_GET["movie_seconds"]) ? intval($_GET["movie_seconds"]): 8;

$is_daily = isset($_GET["is_daily"]);
$filename = isset($_GET["filename"]) ? strtolower($_GET["filename"]): "mymoviefile";
$sts = mktime($hour, $minute, 0, $month, $day, $year);
$ets = $sts + ($dur * 60);


if (isset($_GET["oid"])){
  $sql = sprintf("DELETE from webcam_scheduler WHERE oid = %s", $_GET["oid"]);
  pg_exec($conn, $sql);
}

if (strlen($id) > 0)
{
  $d = 1;
  if (! $is_daily) $d = 0;
  $sql = sprintf("INSERT into webcam_scheduler values ('%s','%s','%s','%s','%s', %s)", $id, date("Y-m-d H:i", $sts), date("Y-m-d H:i", $ets), $d, $filename, $movie_seconds);
  pg_exec($conn, $sql);

}

?>
<html>
<head>
 <title>IEM Admin: Camera Scheduler</title>
</head>
<body>
<style>
h4 {
 color: #00c;
 margin: 3px;
 padding: 3px;
}
</style>

<h3>Fancy Pants Webcamera lapse scheduler!!!</h3>

<form method="GET">

<h4>Step 1: Select webcamera:</h4>
<select name="id">
<?php
while (list($cid, $v) = each($cameras) )
{
  if ($v["active"]){
    echo "<option value=\"$cid\" ";
    if ($cid == $id) echo "SELECTED";
    echo ">". $v["name"];
  }
}
?></select>

<h4>Step 2: When should timelapse begin?</h4>
<b>Note:</b> Only processes scheduled after the top of the next hour
from now will be processed.
<br /><?php echo hourSelect($hour, "hour");  
      echo minuteSelect($minute, "minute"); ?>

<h4>Step 3: Approximate Lapse Duration</h4>
<input type="text" value="<?php echo $dur; ?>" name="dur" size="5">(in minutes)

<h4>Step 4: Set a specific date</h4>
<?php echo yearSelect2(date("Y"), $year, "year"); 
      echo monthSelect($month);
      echo daySelect($day); ?>

<h4>Step 5: Daily Scheduler</h4>
This lapse will run every day for the time and duration.
<br /><input type="checkbox" value="yes" name="is_daily" <?php if ($is_daily) echo "CHECKED=\"CHECKED\""; ?>>Schedule Daily!

<h4>Step 6: Output filename:</h4>
Filename (no spaces, funny characters please!) This is the filename,
<br />that will appear on the Live box in E:\live\content\movies\webcam_scheduler
<br /><input type="text" name="filename" value="<?php echo $filename; ?>">

<h4>Step 7: Movie duration:</h4>
How long of a movie will this be? (in seconds)
<br /><input type="text" size="4" name="movie_seconds" value="<?php echo $movie_seconds; ?>">

<h4>Step 8: Buy daryl steak and submit form!</h4>
<input type="submit" value="Make it so number 1">
</form>

<h3>Current Schedule:</h3>
<table border="1" cellpadding="2">
<tr><th>Camera:</th><th>Begin:</th><th>End:</th><th>Is Daily</th><th>Filename</th><td>Movie Duration</td><td></td></tr>
<?php
$sql = "SELECT *, oid from webcam_scheduler ORDER by cid ASC";
$rs = pg_exec($conn, $sql);

for( $i=0; $row = @pg_fetch_array($rs,$i); $i++) {
  echo sprintf("<tr><th>%s</th><td>%s</td><td>%s</td><td>%s</td><td>%s</td><td>%s</td><td><a href=\"scheduler.phtml?oid=%s\">Delete</a></tr>", $cameras[$row["cid"]]["name"], $row["begints"], $row["endts"], $row["is_daily"], $row["filename"], $row["movie_seconds"], $row["oid"]);
}
?>
</table>

</body>
</html>
