<?php
 include("../../config/settings.inc.php");
 include("$rootpath/include/database.inc.php");
 /* bypoint.phtml  Query IEM rainfall by a point */

$method = isset($_GET["method"]) ? $_GET["method"] : die('$method not specified');
$year = isset($_GET["year"]) ? intval($_GET["year"]) : die('$year not specified');
$view = isset($_GET["view"]) ? $_GET["view"] : "online";

$d = Array();
$sts = mktime(0,0,0,1,1,$year);
$ets = mktime(0,0,0,1,1,$year + 1);
$today = time();
if ($today < $ets) $ets = $today;
$now = $sts;
while ($now < $ets)
{
	$d[ date("Y-m-d", $now) ] = Array("rain"=> 0, "ob"=> "M");
	$now += 86400;
}

$pg = iemdb("wepp");

$data = "# IEM Rainfall http://mesonet.agron.iastate.edu/rainfall 
# Date Generated: ". date("r") ."\n";
if ($method == "geocode")
{
	$s = isset($_GET["street"]) ? $_GET["street"] : "100 Main Street";
	$c = $_GET["city"] .", IA";
	$data .= "# Request Method: Geocoded $s , $c IA \n";
	$u = sprintf("http://localhost/cgi-bin/geocoder.py?street=%s&city=%s", $s, $c);
	$res = trim( file_get_contents(str_replace(" ", "%20", $u)) );
	//echo "GEOCODER RESPONSE:::$res::: $u :::";
	if (substr($res,0,5) != "ERROR")
	{
		$tokens = explode(",", $res);
		$latitude = $tokens[0];
		$longitude = $tokens[1];
	} else 
	{
		die("Geocoder failed for: $s, $c");
	}
}
else if ($method == "id")
{
	include("$rootpath/include/station.php");
	$id = strtoupper($_GET["nwsli"]);
    $st = new StationData($id);
    $cities = $st->table;
	$latitude = round($cities[$id]["lat"],4);
	$longitude = round($cities[$id]["lon"],4);
	$data .= "# Request Method: Specified NWSLI $id \n";

	if (intval($year) >= 2004)
	{
		include("$rootpath/include/iemaccess.php");
		$iem = new IEMAccess();
		$rs = $iem->query("SELECT day, pday from summary_$year WHERE station = '$id'");
		while ($row = pg_fetch_array($rs))
		{
			if ($row["pday"] >= 0)
			{
				$d[ $row["day"] ]["ob"] = $row["pday"];
			} else {
				$d[ $row["day"] ]["ob"] = 0;

			}
		}
	}
}
else if ($method == "latlon")
{
	if (isset($_GET["lat"])){ 
		$latitude = $_GET["lat"]; };
	if (isset($_GET["lon"])){ 
		$longitude = $_GET["lon"]; };
	$data .= "# Request Method: Specified Lat $latitude Lon $longitude \n";
}

/* Cleanup Lat Lon values */
if ($longitude > 0)
{
	$longitude = 0 - $longitude;
}

$sql = "select hrap_i, distance( the_geom, 
	transform(geometryfromtext('POINT($longitude $latitude)',4326), 26915) ) 
	from hrap_utm ORDER by distance ASC LIMIT 1";
$rs = pg_exec($pg, $sql);
$row = pg_fetch_array($rs);

$hrap_i = $row["hrap_i"];
$data .= "# Latitude: $latitude Longitude: $longitude HRAP_I: $hrap_i
Day Valid  Estimate   Observation\n";

$sql = "select rainfall / 25.4 as inch, valid from daily_rainfall_$year
	WHERE hrap_i = $hrap_i ORDER by valid ASC";
$rs = pg_exec($pg, $sql);

$tot = 0;
$otot = 0;
while ($row = pg_fetch_array($rs))
{
	$tot += $row["inch"];
	$otot += $d[ $row["valid"] ]["ob"];
	$d[ $row["valid"] ]["rain"] = $row["inch"];
}

while (list($k,$v) = each($d))
{
	$data .=  sprintf("%s%5.2f%9s\n", $k, $d[$k]["rain"],
			$d[$k]["ob"]);
}
$data .= sprintf("%s %s%4.2f%9s\n", $year, "Total:", $tot, $otot);

if ($view == "download")
{
	header("Content-type: application/octet-stream");
	header("Content-Disposition: attachment; filename=iemrainfall.dat");
	echo $data;
	die();
}

$THISPAGE = "gis-rainfall";
include("$rootpath/include/header.php"); ?>
<pre>
<?php echo $data; ?>
</pre>
<?php include("$rootpath/include/footer.php"); ?>
