<?php
include("../../config/settings.inc.php");
include("../../include/myview.php");
$t = new MyView();

$t->headextra = '<link rel="stylesheet" type="text/css" href="https://extjs.cachefly.net/ext/gpl/3.4.1.1/resources/css/ext-all.css"/>
<script type="text/javascript" src="https://extjs.cachefly.net/ext/gpl/3.4.1.1/adapter/ext/ext-base.js"></script>
<script type="text/javascript" src="https://extjs.cachefly.net/ext/gpl/3.4.1.1/ext-all.js"></script>
<script type="text/javascript" src="/ext/ux/StatusBar.js"></script>
<script type="text/javascript" src="obhour-static.js"></script>
';

$t->title = "Hourly Precip Accumulator";
$t->thispage ="archive-hrain";

$t->content = <<<EOF
<style type="text/css">
 .x-grid3-cell-inner, .x-grid3-hd-inner { white-space:normal !important; }
</style>
<div id="iem-header">
<a href="/">IEM Homepage</a> &gt; <a href="/ASOS/">ASOS Mainpage</a>
</div>
<div id="iem-footer"></div>

<div id="sidebarinfo" style="padding: 5px;">
<p>This application attempts to compute accumulated precip values over
different time intervals.  The valid time reported is the ending time, so
the 1 Hour value at 11 AM would be for a period between 10-11 AM.</p>

<p>This application does not have data for the current hour.  The database
is updated at the top of the hour for the previous hour.</p>
</div>

EOF;
$t->render('app.phtml');
