<?php
/* Pure IEM 2.0 App to do vtec stuff.  Shorter url please as well */
include("../../config/settings.inc.php");

$HEADEXTRA = '<link rel="stylesheet" type="text/css" href="http://extjs.cachefly.net/ext-3.2.0/resources/css/ext-all.css"/>
<script type="text/javascript" src="http://extjs.cachefly.net/ext-3.2.0/adapter/ext/ext-base.js"></script>
<script type="text/javascript" src="http://extjs.cachefly.net/ext-3.2.0/ext-all.js"></script>
<script type="text/javascript" src="../ext/ux/StatusBar.js"></script>
<script type="text/javascript" src="obhour-static.js"></script>
';

$TITLE = "IEM Hourly Precip Accumulator";
$NOCONTENT = 1;
$THISPAGE ="archive-hrain";
include("$rootpath/include/header.php");

?>

<style type="text/css">
 .x-grid3-cell-inner, .x-grid3-hd-inner { white-space:normal !important; }
</style>

<div id="sidebarinfo" style="padding: 5px;">
<p>This application attempts to compute accumulated precip values over
different time intervals.  The valid time reported is the ending time, so
the 1 Hour value at 11 AM would be for a period between 10-11 AM.</p>

<p>This application does not have data for the current hour.  The database
is updated at the top of the hour for the previous hour.</p>
</div>

<div id="footer"></div>
</body></html>
