<?php 
include("../../config/settings.inc.php");
include("../../include/database.inc.php");
include("../../include/forms.php");  
include("setup.php");
$day1 = isset($_GET["day1"]) ? $_GET["day1"] : 1;
$day2 = isset($_GET["day2"]) ? $_GET["day2"] : 1;
$month1 = isset($_GET["month1"]) ? $_GET["month1"]: date("m");
$month2 = isset($_GET["month2"]) ? $_GET["month2"]: date("m");
$year1 = isset($_GET["year1"]) ? $_GET["year1"] : date("Y");
$year2 = isset($_GET["year2"]) ? $_GET["year2"] : date("Y");
$hour1 = isset($_GET["hour1"]) ? $_GET["hour1"]: 12;
$hour2 = isset($_GET["hour2"]) ? $_GET["hour2"]: 12;
$minute1 = isset($_GET["minute1"]) ? $_GET["minute1"]: 0;
$minute2 = isset($_GET["minute2"]) ? $_GET["minute2"]: 0;
$units = isset($_GET["units"]) ? $_GET["units"]: "mph";
$nsector = isset($_GET['nsector']) ? $_GET['nsector']: 36;
$level = isset($_GET["level"]) ? $_GET['level']: 1000;
$fmt = isset($_GET["fmt"]) ? $_GET["fmt"]: 'png';


if (isset($_GET["hour1"])){
	$rose_uri = "/cgi-bin/mywindrose.py?nsector=$nsector&station=$station".
		"&network=$network&day1=$day1&day2=$day2&month1=$month1&".
		"month2=$month2&year1=$year1&year2=$year2&hour1=$hour1&".
		"hour2=$hour2&minute1=$minute1&minute2=$minute2&".
		"units=$units&amp;fmt=$fmt";
	if (isset($_GET["hourlimit"])){
	  $rose_uri .= "&hourlimit=1";
	}
	if (isset($_GET["monthlimit"])){
	  $rose_uri .= "&monthlimit=1";
	}
	if (isset($_GET["hourrangelimit"])){
		$rose_uri .= "&hourrangelimit=1";
	}
	if (isset($_GET["staticrange"])){
		$rose_uri .= "&staticrange=1";
	}
	if ($network == 'RAOB') $rose_uri .= "&level=". $level;
	$rosedata_uri = "{$rose_uri}&justdata=true";
}

include_once "../../include/myview.php";
$t = new MyView();
$firstyear = 1995;
if ($metadata["archive_begin"]){
	$firstyear = date("Y", strtotime($metadata["archive_begin"]));
}

$t->thispage ="iem-sites";
$t->title = "Custom Wind Roses";
$t->sites_current="custom_windrose";
$tznote = "(Times are in US Central Standard/Daylight Time, sorry)";
if ($network == 'RAOB'){
	$tznote = "(Times presented are in UTC)";
}

$ar = Array("png" => "PNG Image (.PNG)",
		"pdf" => "Portable Document Format (.PDF)",
		"svg" => "Scalable Vector Graphic (.SVG)");
$fselect = make_select("fmt", $fmt, $ar);

$content = <<<EOF
<h3>Custom Wind Rose Plots</h3>

This application attempts to generate a wind rose for a time period of 
your choice.  Please be patient when submitting this form, as it may take 
up to a few minutes to generate the plot due to the large amount of data
that this application processes. You can limit the dataset from which the
windrose is derived in three ways:
<ol>
 <li>By only including observations from a specific hour</li>
 <li>By only including observations from a specific month</li>
 <li>By only including observations between a start and end hour</li>
</ol>

<form method="GET" name="windrose">
<input type="hidden" name="station" value="{$station}">
<input type="hidden" name="network" value="{$network}">
<h4>Select Start/End Time:</h4><br>
<i>{$tznote}</i>

<table class="table table-bordered table-condensed">
  <tr>
    <td></td>
    <th>Year</th><th>Month</th><th>Day</th>
    <th>Hour</th><th>Minute</th>
<td rowspan="3">
EOF;
$hs1 = hourSelect($hour1, "hour1");
$hs2 = hourSelect($hour2, "hour2");
$mi1 = minuteSelect($minute1, "minute1");
$mi2 = minuteSelect($minute2, "minute2");
if ($network == 'RAOB'){
	$levels = Array(1000 => 1000,
			925 => 925,
			850 => 850,
			700 => 700,
			500 => 500,
			400 => 400,
			300 => 300,
			250 => 250,
			150 => 150,
			100 => 100);
	$content .= 'Select Pressure Level: ' . make_select("level", $level, $levels) .' hPa<br />';
	$hours = Array(0 => 0, 12 => 12);
	$hs1 = make_select("hour1", $hour1, $hours);
	$hs2 = make_select("hour2", $hour2, $hours);
	$mi1 = "";
	$mi2 = "";
}
$content .= '<input type="checkbox" name="hourlimit" value="1" ';
if (isset($_GET["hourlimit"])) $content .= "checked=\"checked\" "; 
$content .= '>1. Limit to Hour of Start Time
<br /><input type="checkbox" name="monthlimit" value="1" ';
if (isset($_GET["monthlimit"])) $content .= "checked=\"checked\" "; 
$content .= '>2. Limit to Month of Start Time
<br /><input type="checkbox" name="hourrangelimit" value="1" ';
if (isset($_GET["hourrangelimit"])) $content .= "checked=\"checked\" "; 
$content .= '>3. Limit to Range of hours given by start and end time
<br /><input type="checkbox" name="staticrange" value="1" ';
if (isset($_GET["staticrange"])) $content .= "checked=\"checked\" "; 
$content .= '>Optional: Hard code the frequency axis limit to 100%
<br />Display Units: <select name="units">
 <option value="kts" ';
if ($units == "kts"){ $content .= "SELECTED='SELECTED'"; } 
$content .= '>Knots
 <option value="mph" ';
if ($units == "mph"){ $content .= "SELECTED='SELECTED'"; }
$content .= '>Miles Per Hour
 <option value="mps" ';
if ($units == "mps"){ $content .= "SELECTED='SELECTED'"; }
$content .= '>Meters Per Second
</select>
<br />Direction Bins: <select name="nsector">';
$opts = Array(8,12,16,20,24,28,32,36);
while(list($k,$v)=each($opts)){
	$content .= sprintf("<option value=\"%s\" %s>%s</option>\n", $v, 
			($nsector == $v) ? 'selected="selected"': '',$v);
}


$content .= '
</select>

<br />Image Format: '. $fselect .'
<br /><input type="submit"></td>
  </tr>

  <tr>
    <th>Start:</th>
    <td>
     '. yearSelect2($firstyear, $year1, "year1") .'
    </td>
    <td>
     '. monthSelect($month1, "month1") .'
    </td>
    <td>
     '. daySelect2($day1, "day1") .'
    </td>
    <td>
     '. $hs1 .'
    </td>
    <td>
     '. $mi1 .'
    </td>
  </tr>

  <tr>
    <th>End:</th>
    <td>'. yearSelect2($firstyear, $year2, "year2") .'</td>
    <td>
     '. monthSelect($month2, "month2") .'
    </td>
    <td>
     '. daySelect2($day2, "day2").'
    </td>
    <td>
     '. $hs2 .'
    </td>
    <td>
     '. $mi2 .'
    </td>
  </tr>
</table>
</form>';

if (isset($rose_uri)){
  $content .= "<div class=\"alert alert-info\" id=\"img-loading\">Image will appear below once generated, please be patient...</div>";
  $content .= "<a href='{$rosedata_uri}' class='btn btn-primary' role='button' rel='nofollow'><i class='glyphicon glyphicon-list'></i> View raw data for chart</a><br />";
  if ($fmt == 'pdf'){
  	$content .= <<<EOF
<object id="windrose-plot" src="{$rose_uri}" width="700px" height="700px">
    <embed src="{$rose_uri}" width="700px" height="700px">
    </embed>
</object>
EOF;
  } else {
	  $content .= "<img src=\"$rose_uri\" class=\"img-responsive\" id=\"windrose-plot\">";
  }
} else {
  $content .= "<div class=\"alert alert-info\">Please make your custom plot
  		selections above</a>";
}
$t->jsextra = <<<EOF
<script>
  $('#windrose-plot').load(function(){
	$('#img-loading').css('display', 'none');	
	});
		
</script>
EOF;

$t->content = $content;
$t->render('sites.phtml');
 
 ?>