<?php
require_once "../../../config/settings.inc.php";
require_once "../../../include/myview.php";
require_once "../../../include/forms.php";
$t = new MyView();
$t->title = "IEM NE Ames Time Series";

$year = get_int404("year", date("Y"));
$month = get_int404("month", date("m"));
$day = get_int404("day", date("d"));
$myTime = mktime(0, 0, 0, $month, $day, $year);

$dirRef = date("Y/m/d", $myTime);
$dataurl = "/archive/data/$dirRef/text/ot/ot0006.dat";

$ys = yearSelect(2003, $year);
$ms = monthSelect($month);
$ds = daySelect($day);

$titleDate = date("M d, Y", $myTime);

$dirRef = date("Y/m/d", $myTime);
$thisMax = -99;
$thisMin = 99;
$maxGust = 0;
$gustTime = "N/A";
$fn = "/mesonet/ARCHIVE/data/$dirRef/text/ot/ot0006.dat";
if (file_exists($fn)) {
    $fcontents = file($fn);
    foreach ($fcontents as $line_num => $line) {
        if ($line_num < 5) continue;
        $parts = explode(" ", $line);
        $tm = $parts[5];
        if ($tm > $thisMax) {
            $thisMax = $tm;
        }
        if ($tm < $thisMin) {
            $thisMin = $tm;
        }
        $gust = floatval($parts[11]);
        $gust_time = $parts[12];
        if ($gust > $maxGust) {
            $maxGust = $gust;
            $gustTime = $gust_time;
        }
    } // End of while
}

$t->content = <<<EOM
<ul class="breadcrumb">
 <li><a href="/other/">Other Stations</a></li>
 <li class="active">Mesonet NE Ames</li>
</ul>

<p>You can plot 1 minute data for this location.  Note that 
the archive <br> begins 24 Oct 2004.</p>

<table>
<tr class="even"><td>


  <form method="GET">
  {$ys} {$ms} {$ds}

  <input type="submit" value="Make Plot"></form>

</td></tr><tr><td>

<BR>
<a href="{$dataurl}">View raw data file</a><br />
<div><font>Today's Maximum Temperature: {$thisMax} F<br>
Today's Minimum Temperature: {$thisMin} F<br></font></div> 

<div><font>Today's Maximum Wind Gust: {$maxGust} mph<br>
Time of Maximum Wind Gust: {$gustTime}<br><br></font></div>

<img src="1min.php?year={$year}&amp;month={$month}&amp;day={$day}" ALT="Time Series">
<br />
<img src="1min_inside.php?year={$year}&amp;month={$month}&amp;day={$day}" ALT="Time Series">
<br />
<img src="rh.php?year={$year}&amp;month={$month}&amp;day={$day}" ALT="Time Series">
<br />
<img src="baro.php?year={$year}&amp;month={$month}&amp;day={$day}" ALT="Time Series">
<br />
<img src="1min_V.php?year={$year}&amp;month={$month}&amp;day={$day}" ALT="Time Series">
<br />
<img src="dailyrain.php?year={$year}&amp;month={$month}&amp;day={$day}" ALT="Time Series">
<br />
<img src="temp_rh.php?year={$year}&amp;month={$month}&amp;day={$day}" ALT="Time Series">
<br />
</td></tr></table>
</div>
EOM;
$t->render('single.phtml');
