<?php 
include("../../../config/settings.inc.php");
$TITLE = "IEM NE Ames Time Series";
$THISPAGE = "networks-other";
include("$rootpath/include/header.php"); 
include("$rootpath/include/forms.php"); 
$year = isset($_GET["year"]) ? $_GET["year"] : date("Y");
$month = isset($_GET["month"]) ? $_GET["month"] : date("m");
$day = isset($_GET["day"]) ? $_GET["day"] : date("d");
$myTime = mktime(0,0,0,$month,$day,$year);

$dirRef = strftime("%Y/%m/%d", $myTime);
$dataurl = "http://mesonet.agron.iastate.edu/archive/data/$dirRef/text/ot/ot0006.dat";

?>

<div class="text">
<a href="/other/">Other Networks</a> &nbsp;<b> > </b> &nbsp; Mesonet Northeast Ames

<p>You can plot 1 minute data for this location.  Note that 
the archive <br> begins 24 Oct 2004.</p>

<table>
<tr class="even"><td>


  <form method="GET" action="main.phtml">
  <?php echo yearSelect(2003, $year); ?>
  <?php echo monthSelect($month); ?>
  <?php echo daySelect($day); ?>

  <input type="submit" value="Make Plot"></form>

</td></tr><tr><td>

<BR>
<a href="<?php echo $dataurl; ?>">View raw data file</a><br />
<?php include("maxmintemp.php"); ?>
<?php include("windtext.php"); ?>
<img src="./1min.php?year=<?php echo $year; ?>&month=<?php echo $month; ?>&day=<?php echo $day; ?>" ALT="Time Series">
<BR>
<img src="./1min_inside.php?year=<?php echo $year; ?>&month=<?php echo $month; ?>&day=<?php echo $day; ?>" ALT="Time Series">
<BR>
<img src="./rh.php?year=<?php echo $year; ?>&month=<?php echo $month; ?>&day=<?php echo $day; ?>" ALT="Time Series">
<BR>
<img src="./baro.php?year=<?php echo $year; ?>&month=<?php echo $month; ?>&day=<?php echo $day; ?>" ALT="Time Series">
<BR>
<img src="./1min_V.php?year=<?php echo $year; ?>&month=<?php echo $month; ?>&day=<?php echo $day; ?>" ALT="Time Series">
<BR>
<img src="./dailyrain.php?year=<?php echo $year; ?>&month=<?php echo $month; ?>&day=<?php echo $day; ?>" ALT="Time Series">
<BR>
</td></tr></table>
</div>
<?php include("$rootpath/include/footer.php"); ?>
