<?php
 include("../../../config/settings.inc.php");
 define("IEM_APPID", 34);
 include("../../../include/myview.php");
include("../../../include/database.inc.php");
include("../../../include/imagemaps.php");
include_once("../../../include/forms.php");

 $station = isset($_GET["station"]) ? $_GET["station"]: "";
 $network = isset($_REQUEST["network"]) ? $_REQUEST["network"]: "IACLIMATE";


 $syear = isset($_GET['syear']) ? $_GET['syear'] : date("Y");
 $smonth = isset($_GET['smonth']) ? $_GET['smonth'] : 1;
 $sday = isset($_GET['sday']) ? $_GET['sday'] : 1;

 $eyear = isset($_GET['eyear']) ? $_GET['eyear'] : date("Y");
 $emonth = isset($_GET['emonth']) ? $_GET['emonth'] : date("m");
 $eday = isset($_GET['eday']) ? $_GET['eday'] : date("d");
  
$dcgi = "network=$network&syear=$syear&smonth=$smonth&sday=$sday";
$dcgi .= "&eyear=$eyear&emonth=$emonth&eday=$eday&";

$year2 = null;
if (isset($_REQUEST['year2']) && isset($_REQUEST['year2on'])){
	$year2 = intval( $_REQUEST['year2']);
	$dcgi .= "year2=${year2}&";
}

$year3 = null;
if (isset($_REQUEST['year3']) && isset($_REQUEST['year3on'])){
	$year3 = intval( $_REQUEST['year3']);
	$dcgi .= "year3=${year3}&";
}

$year4 = null;
if (isset($_REQUEST['year4']) && isset($_REQUEST['year4on'])){
	$year4 = intval( $_REQUEST['year4']);
	$dcgi .= "year4=${year4}&";
}
$t = new MyView();
$t->thispage = "networks-coop";
$t->title = "NWS COOP Accumulated Departures";
$t->headextra = <<<EOF
<link rel="stylesheet" href="/vendor/openlayers/3.8.2/ol.css" type="text/css">
<link type="text/css" href="/vendor/openlayers/3.8.2/ol3-layerswitcher.css" rel="stylesheet" />
EOF;
$t->jsextra = <<<EOF
<script src="/vendor/openlayers/3.8.2/ol.js" type="text/javascript"></script>
<script src='/vendor/openlayers/3.8.2/ol3-layerswitcher.js'></script>
<script src="/js/olselect.php?network=${network}"></script>
EOF;

$nselect = networkSelect($network, $station);
$ysselect = yearSelect2(1893,$syear,"syear");
$msselect = monthSelect2($smonth,"smonth");
$dsselect = daySelect2($sday,"sday");
$yeselect = yearSelect2(1893,$eyear,"eyear");
$meselect = monthSelect2($emonth,"emonth");
$deselect = daySelect2($eday,"eday");
$content = <<<EOF
<style type="text/css">
        #map {
            width: 450px;
            height: 450px;
            border: 2px solid black;
        }
</style>

<h3 class="heading">Accumulated Data Traces</h3>

<p>This application plots three graphs of accumulated growing degree days,
 rainfall, and stress degree days.  You can optionally compare the selected
 period against two other years of your choice.  If you are looking for the raw 
 data, you can download on the <a href="/request/coop/fe.phtml">COOP data download</a> page.  Your plot time duration can not exceed 5 years.  This page may take a few seconds to load, so please be patient.</p>

<p>Data is available from the following states: 
<a href="acc.phtml?network=ILCLIMATE">Illinois</a> ,
<a href="acc.phtml?network=INCLIMATE">Indiana</a> ,
<a href="acc.phtml?network=IACLIMATE">Iowa</a> ,
<a href="acc.phtml?network=KSCLIMATE">Kansas</a>,
<a href="acc.phtml?network=KYCLIMATE">Kentucky</a> ,
<a href="acc.phtml?network=MICLIMATE">Michigan</a> ,
<a href="acc.phtml?network=MNCLIMATE">Minnesota</a> ,
<a href="acc.phtml?network=NECLIMATE">Nebraska</a> ,
<a href="acc.phtml?network=OHCLIMATE">Ohio</a> ,
<a href="acc.phtml?network=NDCLIMATE">North Dakota</a> ,
<a href="acc.phtml?network=SDCLIMATE">South Dakota</a> ,
<a href="acc.phtml?network=WICLIMATE">Wisconsin</a>.

<form name="olselect" action="acc.phtml" method="GET">
<input type="hidden" name="network" value="{$network}" />
<table style="padding: 3px; border: 0px; margin: 0px;">
<thead>
<tr><th>Climate Site:</th><td></td><th>Year:</th><th>Month:</th><th>Day:</th></tr>
</thead>
<tbody>
<tr>
  <td rowspan="2"> {$nselect}
	<br /><a href="acc.phtml?{$dcgi}">Select via map.</a></td>
  <td>Start Date:</td>
  <td>{$ysselect}</td>
  <td>{$msselect}</td>
  <td>{$dsselect}</td>
</tr>
<tr>
  <td>End Date:</td>
  <td>{$yeselect}</td>
  <td>{$meselect}</td>
  <td>{$deselect}</td>
  </tr>
</tbody>
</table>
<br />

<br /><input type="checkbox" name="year2on" value="yes" 
EOF;
if ($year2 != null) $content .= "CHECKED=CHECKED"; 
$content .= "/> Compare with year ". yearSelect2(1893, $year2, "year2"); 

$content .= "<br /><input type=\"checkbox\" name=\"year3on\" value=\"yes\" "; 
if ($year3 != null) $content .= "CHECKED=CHECKED"; 
$content .= "/> Compare with year ". yearSelect2(1893, $year3, "year3"); 

$content .= "<br /><input type=\"checkbox\" name=\"year4on\" value=\"yes\" ";
if ($year4 != null) $content .= "CHECKED=CHECKED";
$content .= "/> Compare with year ". yearSelect2(1893, $year4, "year4");

$content .= " <p><input type=\"submit\" value=\"Make Plot\"></form>";

 if (strlen($station) > 0 ) { 

$content .= "<p><img src=\"/cgi-bin/climate/acc.py?$dcgi&station=$station\" ALT=\"Time Series\">";
 } else {  
 	$content .= <<<EOF
<div id="map"></div>
EOF;
} 
$t->content = $content;
$t->render('single.phtml');
?>