<?php
 include("../../../config/settings.inc.php");
include("$rootpath/include/database.inc.php");
include("$rootpath/include/google_keys.php");
include("$rootpath/include/imagemaps.php");


 $station = isset($_GET["station"]) ? $_GET["station"]: "";
 $network = "IACLIMATE";
 $api = $GOOGLEKEYS[$rooturl]["any"];

 $syear = isset($_GET['syear']) ? $_GET['syear'] : date("Y");
 $smonth = isset($_GET['smonth']) ? $_GET['smonth'] : 1;
 $sday = isset($_GET['sday']) ? $_GET['sday'] : 1;

 $eyear = isset($_GET['eyear']) ? $_GET['eyear'] : date("Y");
 $emonth = isset($_GET['emonth']) ? $_GET['emonth'] : 6;
 $eday = isset($_GET['eday']) ? $_GET['eday'] : 1;
$dcgi = "syear=$syear&smonth=$smonth&sday=$sday&eyear=$eyear&emonth=$emonth&eday=$eday&";
?>

<?php 	
$THISPAGE = "networks-coop";
$TITLE = "IEM | Accumulated Traces";
$HEADEXTRA = "<script src='http://maps.google.com/maps?file=api&amp;v=2&amp;key=$api'></script>
<script src='http://www.openlayers.org/api/OpenLayers.js'></script>
<script src='${rooturl}/js/olselect.php?network=${network}&c=". time() ."'></script>";
$BODYEXTRA = "onload=\"init()\"";
include("$rootpath/include/header.php"); ?>

<style type="text/css">
        #map {
            width: 450px;
            height: 450px;
            border: 2px solid black;
        }
</style>


<h3 class="heading">Accumulated Data Traces</h3>

<p>This application plots a graph of accumulated rainfall and growing degree 
days for a time period of your choice!  If you are looking for the raw 
data, you can download on the <a href="/request/coop/fe.phtml">COOP data download</a> page.  Your plot time duration can not exceed 5 years.  This page may take a few seconds to load, so please be patient.</p>

<div class="text">

<?php include_once("$rootpath/include/forms.php"); ?>
<form name="olselect" action="acc.phtml" method="GET">

<table style="padding: 3px; border: 0px; margin: 0px;">
<thead>
<tr><th>Climate Site:</th><td></td><th>Year:</th><th>Month:</th><th>Day:</th></tr>
</thead>
<tbody>
<tr>
  <td rowspan="2"><?php echo networkSelect($network, $station); ?>
	<br /><a href="acc.phtml?<?php echo $dcgi; ?>">Select via map.</a></td>
  <td>Start Date:</td>
  <td><?php echo yearSelect2(1893,$syear,"syear"); ?></td>
  <td><?php echo monthSelect2($smonth,"smonth"); ?></td>
  <td><?php echo daySelect2($sday,"sday"); ?></td>
</tr>
<tr>
  <td>End Date:</td>
  <td><?php echo yearSelect2(1893,$eyear,"eyear"); ?></td>
  <td><?php echo monthSelect2($emonth,"emonth"); ?></td>
  <td><?php echo daySelect2($eday,"eday"); ?></td>
</tr>
</tbody>
</table>
<input type="submit" value="Make Plot">
</form>

<?php if (strlen($station) > 0 ) { ?>

<p><img src="acc_gdd_plot.php?<?php echo "$dcgi&station=$station"; ?>" ALT="Time Series">
<p><img src="acc_rain_plot.php?<?php echo "$dcgi&station=$station"; ?>" ALT="Time Series">
<p><img src="acc_sdd_plot.php?<?php echo "$dcgi&station=$station"; ?>" ALT="Time Series">

<?php } else {  ?>
<div id="map"></div>
<div id="sname" unselectable="on">No site selected</div>
<?php } ?>
</div>

<?php include("$rootpath/include/footer.php"); ?>
