<?php
include("../../../config/settings.inc.php");
include_once "../../../include/myview.php";
$t = new MyView();

$t->title = "Growing Season Temperature Spreads";

$t->content = <<<EOF
<p><h3 class="heading">Seasonal Temperature Spreads</h3><p>

<p>Related: <a href="spread_fe.phtml">View by Date</a>
<b>|</b> <a href="mspread.phtml">View by Month</a>

<p><img src="images/spread_djf.png">
<p><img src="images/spread_mam.png">
<p><img src="images/spread_jja.png">
<p><img src="images/spread_son.png">
EOF;
$t->render('single.phtml');
