<?php
require_once "../../../config/settings.inc.php";
require_once "../../../include/myview.php";
$t = new MyView();

$t->title = "Monthly Temperature Spreads";
$t->content = <<<EOF

<p><h3>Monthly Temperature Spreads</h3><p>

<p>Related: <a href="spread_fe.phtml">View by Date</a>
<b>|</b> <a href="gspread.phtml">View by Season</a>

<p><img src="images/spread_jan.png">
<p><img src="images/spread_feb.png">
<p><img src="images/spread_mar.png">
<p><img src="images/spread_apr.png">
<p><img src="images/spread_may.png">
<p><img src="images/spread_jun.png">
<p><img src="images/spread_jul.png">
<p><img src="images/spread_aug.png">
<p><img src="images/spread_sep.png">
<p><img src="images/spread_oct.png">
<p><img src="images/spread_nov.png">
<p><img src="images/spread_dec.png">
EOF;
$t->render('single.phtml');
