<?php
include("../../../config/settings.inc.php");
include_once "../../../include/myview.php";
 include("../../../include/forms.php"); 
$t = new MyView();

$month = isset($_GET['month']) ? $_GET['month'] : date("m");
$day = isset($_GET['day']) ? $_GET['day'] : date("d");
$ts = strtotime("2003-$month-$day");
$pts = strftime("2003-%m-%d", $ts);
$t->title = "Daily Temperature Spreads";

$ms = monthSelect($month);
$ds = daySelect($day);

$t->content = <<<EOF
<p><h3>Daily Temperature Spread</h3><p>

<p>Related: <a href="gspread.phtml">View by Season</a>
 <b>|</b> <a href="mspread.phtml">View by Month</a>

<h3>Information</h3><p>
Select a date from the following menu and a chart is generated with the
frequency of high and low temperature occurances for sites in the Iowa NWS
COOP network. The dashed lines represent the number of occurances for a particular temperature for a certain day.  The solid curve line is the cumulative distribution.  The light red and blue curves are the statistical normal distribution.

<form name="ddd" action="spread_fe.phtml">
<table border=1 cellspacing=0 cellpadding=3>
<tr>
<th>Select Month:</th>
<th>{$ms}</th>
<th>Select Day:</th>
<th>{$ds}</th>
<td><input type="submit" value="Gen Chart"></form></tr>

<tr><td colspan=5>
<img src="spread.php?ts={$pts}">
</td></tr>
</table>

EOF;

$t->render('single.phtml');
?>
