<?php 
include("../../../config/settings.inc.php");
$TITLE = "IEM | Low Temperature Threshold Histograms";
$station1 = isset($_GET["station1"]) ? $_GET["station1"] : "";
$station2 = isset($_GET["station2"]) ? $_GET["station2"] : "";
$mode = isset($_GET["mode"]) ? $_GET["mode"]: "";
include("$rootpath/include/header.php"); 
include("$rootpath/include/network.php");     
$nt = new NetworkTable("IACLIMATE");
$cities = $nt->table;
?>

<B>Navigation:</B>
<a href="http://mesonet.agron.iastate.edu/">IEM</a> &nbsp;>&nbsp;
<a href="/COOP/">NWS COOP</a> &nbsp;>&nbsp;
<B>COOP Low Temperature Thresholds</B>

<BR>


<form method="GET">

<table>
<tr>
  <th class="subtitle">Station 1</th>
  <th class="subtitle">Station 2</th>
  <td></td>
  <td></td>
</tr>

<tr>
<td>
<SELECT name="station1">
<?php
	for(reset($cities); $key = key($cities); next($cities))
	{
		print("<option value=\"" . $cities[$key]["id"] ."\"");
                if ($cities[$key]["id"] == $station1) print(" SELECTED ");

		print(">" . $cities[$key]["name"] . "\n");
	}
?>
</SELECT>
</td>
<td>
<SELECT name="station2">
<?php
        for(reset($cities); $key = key($cities); next($cities))
        {
                print("<option value=\"" . $cities[$key]["id"] ."\"");
                if ($cities[$key]["id"] == $station2) print(" SELECTED ");

                print(">" . $cities[$key]["name"] . "\n");
        }
?>
</SELECT>
</td>
<td>
  <select name="mode">
<?php
   echo "<option value=\"o\" ";
   if ($mode == "o") echo " SELECTED ";
   echo ">One Station\n";
   echo "<option value=\"c\" ";
   if ($mode == "c") echo " SELECTED ";
   echo ">Compare Two\n";

?>
  </select>
</td>

<td>
<input type="SUBMIT" value="Make Plot">

</form>
</td>

</tr></table>

<div style="width:640px;">
<p>This application plots the frequency of years during which a threshold 
temperature was exceeded for a particular site for 1 day that winter.  You can select multiple
sites to compare them.  This page may take 30 seconds to load once you select
your sites.
</div>
<br />

<?php
if ($station1 != "" && $station2 != "")
{
  if ($mode == "c"){
    echo "<img src=\"threshold_histogram.php?station1=".$station1."&station2=".$station2."\">\n";

  }else {
    echo "<img src=\"threshold_histogram.php?station1=". $station1 ."\">\n";
  }
} else {
  echo "<p>Select your site above...</p>";
}
?>

<?php include("$rootpath/include/footer.php"); ?>
