<?php
require_once "../../config/settings.inc.php";
require_once "../../include/database.inc.php";
require_once "../../include/forms.php";
require_once "../../include/myview.php";
$t = new MyView();
require_once "lib.php";

$year1 = isset($_GET["year1"]) ? intval($_GET["year1"]): date("Y");
$year2 = isset($_GET["year2"]) ? intval($_GET["year2"]): date("Y");
$month1 = isset($_GET["month1"]) ? intval($_GET["month1"]): date("m");
$month2 = isset($_GET["month2"]) ? intval($_GET["month2"]): date("m");
$day1 = isset($_GET["day1"]) ? intval($_GET["day1"]): date("d");
$day2 = isset($_GET["day2"]) ? intval($_GET["day2"]): date("d");
$hour1 = isset($_GET["hour1"]) ? intval($_GET["hour1"]): 0;
$hour2 = isset($_GET["hour2"]) ? intval($_GET["hour2"]): 12;
$model = isset($_GET["model"]) ? xssafe($_GET["model"]): "GFS";
$station = isset($_GET["station"]) ? strtoupper(xssafe($_GET["station"])): "KAMW";

$t->thispage = "archive-mos";
$t->title = "NWS MOS Download Interface";

$ys1 = yearSelect2(2000,$year1, "year1");
$ms1 = monthSelect($month1, "month1");
$ds1 = daySelect2($day1, "day1");
$ys2 = yearSelect2(2000,$year1, "year2");
$ms2 = monthSelect($month1, "month2");
$ds2 = daySelect2($day1, "day2");

$table = "";
while (list($k,$v) = each($mosvars)){
	$table .= sprintf("<tr><th>%s</th><td>%s</td></tr>\n", $k, $v);
}

$modselect = "<select name=\"model\">";
$modselect .= "<option value=\"GFS\" ";
if ($model == "GFS") $modselect .= " SELECTED";
$modselect .= ">AVN/GFS</option>\n";
$modselect .= "<option value=\"NAM\" ";
if ($model == "NAM" || $model == "ETA") $modselect .= " SELECTED";
$modselect .= ">Eta/NAM</option>\n";
$modselect .= "<option value=\"NBS\" ";
if ($model == "NBS") $modselect .= " SELECTED";
$modselect .= ">NBS</option>\n";
$modselect .= "</select>";

$t->content = <<<EOF
<h3>NWS MOS Download Interface</h3>

<p>This page allows you to download from the IEM's archive of NWS MOS
data. The archive goes back to June 2000.  You can set the start and end times
to the same time to get that particular run.

<form name="selector" action="dl.php" method="GET">
<table class="table table-striped">
<tr><th>Enter 4-Char Station ID:</th>
  <th><input type="text" name="station" value="{$station}" size="10"></th>

<th>Select Model</th>
 <th>{$modselect}
</th></tr>

<tr><th>Start Date</th>
  <td>{$ys1}</td>
  <td>{$ms1}</td>
  <td>{$ds1}</td>
  <td><select name="hour1">
 <option value="0">00 UTC</option>
 <option value="6">6 UTC</option>
 <option value="12">12 UTC</option>
 <option value="18">18 UTC</option>
  </select></td></tr>

<tr><th>End Date (inclusive)</th>
  <td>{$ys2}</td>
  <td>{$ms2}</td>
  <td>{$ds2}</td>
  <td><select name="hour2">
 <option value="0">00 UTC</option>
 <option value="6">6 UTC</option>
 <option value="12">12 UTC</option>
 <option value="18">18 UTC</option>
  </select></td></tr>
</table>

<input type="submit" value="Generate Data">
</form>

<h4>Description of MOS variables</h4>
<table>
  		{$table}
</table>
EOF;
$t->render('single.phtml');
?>
