<?php
include("../../config/settings.inc.php");
include("$rootpath/include/database.inc.php");
include("$rootpath/include/forms.php");
include("lib.php");

$year1 = isset($_GET["year1"]) ? $_GET["year1"]: date("Y");
$year2 = isset($_GET["year2"]) ? $_GET["year2"]: date("Y");
$month1 = isset($_GET["month1"]) ? $_GET["month1"]: date("m");
$month2 = isset($_GET["month2"]) ? $_GET["month2"]: date("m");
$day1 = isset($_GET["day1"]) ? $_GET["day1"]: date("d");
$day2 = isset($_GET["day2"]) ? $_GET["day2"]: date("d");
$hour1 = isset($_GET["hour1"]) ? $_GET["hour1"]: 0;
$hour2 = isset($_GET["hour2"]) ? $_GET["hour2"]: 12;
$model = isset($_GET["model"]) ? $_GET["model"]: "GFS";
$station = isset($_GET["station"]) ? strtoupper($_GET["station"]): "KAMW";

$THISPAGE = "archive-mos";
$TITLE = "IEM | NWS MOS Download Interface";
include("$rootpath/include/header.php");
?>

<h3>NWS MOS Download Interface</h3>

<p>This page allows you to download from the IEM's archive of NWS MOS
data. The archive goes back to 3 May 2007.

<form name="selector" action="dl.php" method="GET">
<table>
<tr><th>Enter 4-Char Station ID:</th>
  <th><input type="text" name="station" value="<?php echo $station; ?>" size="10"></th>

<th>Select Model</th>
 <th><?php
echo "<select name=\"model\">";
echo "<option value=\"GFS\" ";
if ($model == "GFS") echo " SELECTED";
  echo ">GFS</option>\n";
echo "<option value=\"NAM\" ";
if ($model == "NAM" || $model == "ETA") echo " SELECTED";
  echo ">Eta/NAM</option>\n";
echo "</select>";
?>
</th></tr>

<tr><th>Start Date</th>
  <td><?php echo yearSelect2(2007,$year1, "year1"); ?></td>
  <td><?php echo monthSelect($month1, "month1"); ?></td>
  <td><?php echo daySelect2($day1, "day1"); ?></td>
  <td><select name="hour1">
 <option value="0">00 UTC</option>
 <option value="12">12 UTC</option>
  </select></td></tr>

<tr><th>End Date (inclusive)</th>
  <td><?php echo yearSelect2(2007,$year2, "year2"); ?></td>
  <td><?php echo monthSelect($month2, "month2"); ?></td>
  <td><?php echo daySelect2($day2, "day2"); ?></td>
  <td><select name="hour2">
 <option value="0">00 UTC</option>
 <option value="12">12 UTC</option>
  </select></td></tr>
</table>

<input type="submit" value="Generate Data">
</form>

<h4>Description of MOS variables</h4>
<table>
<?php
while (list($k,$v) = each($mosvars)){
  echo sprintf("<tr><th>%s</th><td>%s</td></tr>\n", $k, $v);
}
echo "</table>";

include("$rootpath/include/footer.php");
?>
