<?php
// Used in fe.phtml and table.phtml

$mosvars = Array(
 "n_x" => "Max/Min Temp [F]",
 "tmp" => "2m Air Temperature [F]",
 "dpt" => "2m Dew Point [F]",
 "cld" => "Cloud Coverage",
 "wdr" => "10m Wind Direction [deg]",
 "wsp" => "10m Wind Speed [kts]",
 "p06" => "6 Hr Probability of Precipitation [%]",
 "p12" => "12 Hr Probability of Precipitation [%]",
 "q06" => "6 Hr Quantitative Precipitation Forecast",
 "q12" => "12 Hr Quantitative Precipitation Forecast",
 "t06" => "6 Hr Thunderstorm Probability [%]",
 "t12" => "12 Hr Thunderstorm Probability [%]",
 "snw" => "Categorical Snow",
 "cig" => "Categorical Ceiling Height",
 "vis" => "Categorical Visibility",
 "obv" => "Obstruction to Vision",
 "poz" => "Freezing Rain Probability [%]",
 "pos" => "Snowfall Probability [%]",
 "typ" => "Precipitation Type",
 "sky" => "Sky Coverage [%]",
 "gst" => "Wind Gust [kts]",
 "t03" => "T03",
 "pzr" => "Probability of Freezing Rain [%]",
 "psn" => "Probability of Snow [%]",
 "ppl" => "Probability of PL [%]",
 "pra" => "Probability of Rain [%]",
 "s06" => "S06",
 "slv" => "SLV",
 "i06" => "I06",
 "lcb" => "LCB",
 "swh" => "SWH",
);
