<?php
putenv("TZ=GMT");

include("../../config/settings.inc.php");
include("$rootpath/include/database.inc.php");
include("$rootpath/include/forms.php");
$mosdb = iemdb("mos");
pg_exec($mosdb, "SET TIME ZONE 'GMT'");

$year = isset($_GET["year"]) ? $_GET["year"]: date("Y", time() - 2*86400);
$month = isset($_GET["month"]) ? $_GET["month"]: date("m", time() - 2*86400);
$day = isset($_GET["day"]) ? $_GET["day"]: date("d", time() - 2*86400);
$hour =  0;
$model = isset($_GET["model"]) ? $_GET["model"]: "GFS";
$station = isset($_GET["station"]) ? strtoupper($_GET["station"]): "KAMW";
$vname = isset($_GET["vname"]) ? strtolower($_GET["vname"]): "tmp";

$now = strtotime("${year}-${month}-${day} ${hour}:00");
if ($model == "NAM" && $now < mktime(12,0,0,12,9,2008)){ $model = "ETA"; }
$sts = $now - (86400*3) - (3600*12);
$ets = $now - 3600;

$runsper = Array("GFS"=>6, "NAM"=>12, "ETA"=>12);
$sqlSelector = "(";
$runtimes = Array();
$data = Array();
$table = sprintf("<hr><h3>[$station] $model MOS $vname Table Centered On: %sZ</h3>", date('Y M d, H', $now));
for($now=$sts;$now <= $ets; $now += (3600*$runsper[$model])){
  $s = date("Y-m-d H:i", $now);
  $runtimes[] = $s;
}
$table .= sprintf("<table cellpadding=\"2\" cellspacing=\"0\" border=\"1\"><tr><td></td><td colspan=\"%s\">Model Run Initialized at:</td></tr><tr><th width=\"75\">Valid:</th>", sizeof($runtimes) );
for($now=$sts;$now <= $ets; $now += (3600*$runsper[$model])){
  $s = date("Y-m-d H:i", $now);
  $sqlSelector .= sprintf("'%s',", $s);
  $table .= sprintf("<td>%sZ</td>", date('d/H', $now));
  $data[$s] = Array();
}
$table .= "</tr>\n";
$sqlSelector = substr($sqlSelector,0,-1) . ")";

$rs = pg_prepare($mosdb, "SELECT", "SELECT *, t06_1 ||'/'||t06_2 as t06, 
      t12_1 ||'/'|| t12_2 as t12 from t${year} WHERE 
      runtime IN $sqlSelector
      and station = $1 and model = $2");
$rs = pg_execute($mosdb, "SELECT", Array($station, $model));
for ($i=0;$row=@pg_fetch_array($rs,$i);$i++)
{
  $data[ substr($row["runtime"],0,16) ][ substr($row["ftime"],0,16) ] = $row[$vname];
}


for($now=$sts+(3600*12);$now <= $ets+(2*86400); $now += (3600*3)){
 $table .= sprintf("<tr><td>%sZ</td>", date('d/H', $now) );
 reset($runtimes);
 while (list($k,$s) = each($runtimes)){
   $table .= @sprintf("<td>%s</td>", $data[$s][date('Y-m-d H:i', $now)]);
 }
 $table .= "</tr>\n";
}
$table .= "</table>";

// Begin Output
$THISPAGE = "archive-mos";
$TITLE = "IEM MOS Tables";
include("$rootpath/include/header.php");

$vars = Array(
 "n_x" => "Max/Min Temp [F]",
 "tmp" => "2m Air Temperature [F]",
 "dpt" => "2m Dew Point [F]",
 "cld" => "",
 "wdr" => "10m Wind Direction [deg]",
 "wsp" => "10m Wind Speed [kts]",
 "p06" => "",
 "p12" => "",
 "q06" => "",
 "q12" => "",
 "t06" => "",
 "t12" => "",
 "snw" => "Snow",
 "cig" => "",
 "vis" => "",
 "obv" => "",
 "poz" => "",
 "pos" => "",
 "typ" => "");

echo "<form>";
echo "<input type=\"text\" name=\"station\" value=\"$station\">";
echo "<select name=\"vname\">";
while (list($v,$n) = each($vars))
{
  echo "<option value=\"$v\"";
  if ($vname == $v) echo " SELECTED";
  echo ">$n [". strtoupper($v) ."]</option>\n";
}
echo "</select>";

echo "<select name=\"model\">";
echo "<option value=\"GFS\" ";
if ($model == "GFS") echo " SELECTED";
  echo ">GFS</option>\n";
echo "<option value=\"NAM\" ";
if ($model == "NAM" || $model == "ETA") echo " SELECTED";
  echo ">Eta/NAM</option>\n";
echo "</select>";

echo yearSelect(2007,$year);
echo monthSelect($month);
echo daySelect($day);

echo "<input type=\"submit\" value=\"Generate\">";
echo "</form>";


echo $table;
include("$rootpath/include/footer.php");
?>
