<?php
putenv("TZ=UTC");
define("IEM_APPID", 153);
require_once "../../config/settings.inc.php";
date_default_timezone_set('UTC');
require_once "../../include/database.inc.php";
require_once "../../include/forms.php";
require_once "../../include/myview.php";
$t = new MyView();
require_once "lib.php";
$mosdb = iemdb("mos");
pg_exec($mosdb, "SET TIME ZONE 'UTC'");

$year = get_int404("year", date("Y", time() + 86400));
$month = get_int404("month", date("m", time() + 86400));
$day = get_int404("day", date("d", time() + 86400));
$hour =  0;
$model = isset($_GET["model"]) ? strtoupper(xssafe($_GET["model"])) : "GFS";
$station = isset($_GET["station"]) ? strtoupper(xssafe($_GET["station"])) : "KAMW";
$vname = isset($_GET["vname"]) ? strtolower(xssafe($_GET["vname"])) : "tmp";
$models = array(
    "GFS" => "AVN/GIS",
    "MEX" => "GFS Extended (MEX)",
    "NAM" => "NAM",
    "ETA" => "ETA",
    "NBS" => "NBS",
    "NBE" => "NBE",
    "LAV" => "LAV",
);
if (!array_key_exists($model, $models)) {
    $model = "NBE";
}

$now = strtotime("{$year}-{$month}-{$day} {$hour}:00");
if ($model == "NAM" && $now < mktime(12, 0, 0, 12, 9, 2008)) {
    $model = "ETA";
}
if ($model == "GFS" && $now < mktime(12, 0, 0, 12, 16, 2003)) {
    $model = "AVN";
}
$sts = $now - (86400 * 3) - (3600 * 12);
$ets = $now - 3600;
if ($model == "MEX" || $model == "NBE") {
    $ets = $ets + (86400 * 7);
}

$runsper = array(
    "GFS" => 6,
    "AVN" => 6, "NAM" => 12, "ETA" => 12, "NBS" => 6, "MEX" => 12, "NBE" => 6, "LAV" => 6
);
$sqlSelector = "(";
$runtimes = array();
$data = array();
$table = sprintf("<hr><h3>[$station] $model MOS $vname Table Centered On: %sZ</h3>", date('Y M d, H', $now));
for ($now = $sts; $now <= $ets; $now += (3600 * $runsper[$model])) {
    $s = date("Y-m-d H:i", $now);
    $runtimes[] = $s;
}
$table .= sprintf("<table class=\"table table-condensed table-bordered table-striped\"><thead><tr><td></td><th colspan=\"%s\">Model Run Initialized at:</th></tr><tr><th width=\"75\">Valid:</th>", sizeof($runtimes));
for ($now = $sts; $now <= $ets; $now += (3600 * $runsper[$model])) {
    $s = date("Y-m-d H:i", $now);
    $sqlSelector .= sprintf("'%s',", $s);
    $table .= sprintf("<th>%sZ</th>", date('d/H', $now));
    $data[$s] = array();
}
$table .= "</tr></thead><tbody>\n";
$sqlSelector = substr($sqlSelector, 0, -1) . ")";

$rs = pg_prepare($mosdb, "SELECT", "SELECT *, t06_1 ||'/'||t06_2 as t06, " .
    "t12_1 ||'/'|| t12_2 as t12 from alldata WHERE " .
    "runtime IN $sqlSelector " .
    "and station = $1 and model = $2");
$rs = pg_execute($mosdb, "SELECT", array($station, $model));
for ($i = 0; $row = pg_fetch_array($rs); $i++) {
    $data[substr($row["runtime"], 0, 16)][substr($row["ftime"], 0, 16)] = $row[$vname];
}

for ($now = $sts + (3600 * 12); $now <= $ets + (2 * 86400); $now += (3600 * 3)) {
    $thisrow = sprintf("<tr><td>%sZ</td>", date('d/H', $now));
    $allnulls = TRUE;
    $lookup = date('Y-m-d H:i', $now);
    foreach ($runtimes as $k => $s) {
        $val = null;
        if (array_key_exists($lookup, $data[$s])) {
            $val = $data[$s][$lookup];
        }
        if (!is_null($val)) {
            $allnulls = FALSE;
        }
        $thisrow .= sprintf("<td>%s</td>", $val);
    }
    $thisrow .= "</tr>\n";
    if (!$allnulls) {
        $table .= $thisrow;
    }
}
$table .= "</tbody></table>";

// Begin Output
$t->title = "Model Output Statistics Table for $station";

$content = <<<EOF
<ol class="breadcrumb">
 <li><a href="/mos/">Model Output Statistics</a></li>
 <li class="active">Single Variable Data Table</li>
</ol>

<p>This page produces a simple table for the combination of a MOS forecast 
point, MOS variable, and range of dates.  The purpose is to examine how a
forecast has changed with time.  The first entry box requires that you know
the four character identifier of the MOS site being forecasted for.  You 
should use the "K" for United States sites.</p>

<p><form name="updator">
<input type="text" name="station" value="$station">

<select name="vname">
EOF;
foreach ($mosvars as $v => $n) {
    $content .= "<option value=\"$v\"";
    if ($vname == $v) $content .= " SELECTED";
    $content .= ">$n [" . strtoupper($v) . "]</option>\n";
}
$content .= "</select>";

$content .= make_select("model", $model, $models);

$content .= yearSelect(2000, $year);
$content .= monthSelect($month);
$content .= daySelect($day);

$content .= "<input type=\"submit\" value=\"Generate\">";
$content .= "</form>";

$content .= $table;
$t->content = $content;
$t->render('single.phtml');
