<?php
include("../../config/settings.inc.php");
session_start();
$metar = isset($_GET['metar']) ? $_GET["metar"] : "no";
$sortcol = isset($_GET["sortcol"]) ? $_GET["sortcol"] : "ts";
$expiry = 60*60*24*100; // 100 days
//setcookie(session_name(), session_id(), time()+$expiry, "/");

if (!isset($_SESSION['stations'])){
  $_SESSION['stations'] = Array();
  if (isset($_COOKIE['stations'])){
    $_SESSION['stations'] = explode(",", $_COOKIE['stations']);
  }
} 

$st = isset($_GET["st"]) ? $_GET["st"] : "";
$str = isset($_GET["str"]) ? $_GET["str"] : "";

if ($st != ""){
    foreach ($st as $key => $value) {
      if (strlen($value) > 0 && $value != "ahack") {
        array_push( $_SESSION['stations'], $value);
      }
    }
  }
  if ($str != ""){
   foreach ($str as $key => $value) {
      if (strlen($value) > 0 && $value != "ahack") {
        foreach ($_SESSION['stations'] as $key2 => $value2){
          if ($value2 == $value){
            unset($_SESSION['stations'][$key2]);
          }
        }
      }
    } 
}
setcookie("stations", implode(",", $_SESSION['stations']),time()+$expiry, "/");

?>

<?php 
 $TITLE = "MY IEM | Current Conditions";
 $REFRESH = "<meta http-equiv=\"refresh\" content=\"60;
 URL=current.phtml?sortcol=$sortcol&metar=$metar\">";
 $HEADEXTRA = '<script language="JavaScript" type="text/javascript">
<!--//BEGIN Script
function new_window(url) {
	link = 
	window.open(url,"Link","toolbar=0,location=0,directories=0,status=0,menubar=no,scrollbars=yes,resizable=yes,width=800,height=600");
} 
//END Script-->
</script>
<script type="text/javascript" src="/js/tableruler.js"></script>
<script type="text/javascript">
    window.onload=function(){tableruler();}
</script>';
 $THISPAGE = "current-sort";
 include("$rootpath/include/header.php"); ?>
<?php include("$rootpath/include/mlib.php"); ?>
<?php include("$rootpath/include/iemaccess.php"); ?>
<?php include("$rootpath/include/iemaccessob.php"); ?>

<?php $current_network = "My Favorites"; include("$rootpath/include/current_bar.inc.php"); ?>
<form method="GET" action="current.phtml">
<input type="hidden" name="sortcol" value="<?php echo $sortcol; ?>">

<div class="text"><p>
<table class="back" border=1 cellspacing=0 cellpadding=1>
<tr>
  <th>View Options:</th>
  <td>Include METARS (ASOS):
  <input value="no" type="radio" name="metar" <?php if ($metar == "no") echo  "CHECKED"; ?>> No
  <input value="yes" type="radio" name="metar" <?php if ($metar == "yes") echo  "CHECKED"; ?>> Yes
</td>
<td><input type="submit" value="Go!"></form></td>
</tr></table><p>


<h3 class="subtitle"><center>Current Conditions</center></h3><p>

<?php
if (strlen($sortcol) == 0) {
  $sortcol = "valid";
}
$vals = Array("valid" => "Observation Time", "tmpf" => "Temperature", 
 "dwpf" => "Dew Point", "pres" => "Altimeter", "relh" => "Relative Humidity",
 "sknt" => "Wind Speed", 12 => "20 min Gust",
"gust" => "Peak Gust Today", "gtim" => "Time of Peak Gust", 
"pday" => "Today's Precipitation", "feel" => "Feels Like", 
"pmonth" => "Month's Precipitation", "phour" => "Hourly Precip",
"tmpf0" => "Sensor 1 - Temp [F]",  "sname" => "Station Name",
  "tmpf1" => "Sensor 2 - Temp [F]",
  "tmpf2" => "Sensor 3 - Temp [F]",
  "tmpf3" => "Sensor 4 - Temp [F]",
  "dry0" => "Sensor 1 - Cond [F]",
  "dry1" => "Sensor 2 - Cond [F]",
  "dry2" => "Sensor 3 - Cond [F]",
  "dry3" => "Sensor 4 - Cond [F]",
  "ts" => "Observation Time", "min_tmpf" => "Low Air Temperature Today",
  "vsby" => "Visibility", "max_tmpf" => "High Air Temperature Today",
  "max_sknt_ts" => "Time of Peak Gust",
  "max_sknt" => "Wind Gust [knots]", "peak" => "Peak Wind Gust [kts]",
  "peak_ts" => "Time of Peak Wind Gust",
  "city" => "Site Name");

echo "<br>Sorted by: <b>(". $vals[$sortcol] .")</b>  &nbsp; &nbsp; Click on a column to sort it.<br>\n";

?>

<?php
// http://www.php.net/manual/en/function.asort.php

function aSortBySecondIndex($multiArray, $secondIndex) {
	while (list($firstIndex, ) = each($multiArray))
		$indexMap[$firstIndex] = @$multiArray[$firstIndex][$secondIndex];
	arsort($indexMap);
	while (list($firstIndex, ) = each($indexMap))
		if (is_numeric($firstIndex))
			$sortedArray[] = $multiArray[$firstIndex];
		else $sortedArray[$firstIndex] = $multiArray[$firstIndex];
	return $sortedArray;
}
function sortBySecondIndex($multiArray, $secondIndex) {
    while (list($firstIndex, ) = each($multiArray))
        $indexMap[$firstIndex] = @$multiArray[$firstIndex][$secondIndex];
    asort($indexMap);
    while (list($firstIndex, ) = each($indexMap))
        if (is_numeric($firstIndex))
            $sortedArray[] = $multiArray[$firstIndex];
        else $sortedArray[$firstIndex] = $multiArray[$firstIndex];
    return $sortedArray;
}

 $iem = new IEMAccess();
 $mydata = Array();
 $doSF = 0;
 foreach ($_SESSION['stations'] as $key => $value){
   if (strlen($value) == 7){
     $doSF = 1;
   } else {
     $iemob = $iem->getSingleSite($value);
     if (isset($iemob->invalid)){continue; }
     $mydata[$value] = $iemob->db;
    $mydata[$value]["sped"] = $mydata[$value]["sknt"] * 1.15078;
    $mydata[$value]["relh"] = relh(f2c($mydata[$value]["tmpf"]), 
       f2c($mydata[$value]["dwpf"]) );
    $mydata[$value]["feel"] = feels_like($mydata[$value]["tmpf"], 
       $mydata[$value]["relh"], $mydata[$value]["sped"]);

    $mydata[$value]["peak_ts"] = 0;
    $mydata[$value]["peak"] = 0;
    if ($mydata[$value]["max_gust"] > $mydata[$value]["max_sknt"]){
      $mydata[$value]["peak"] = $mydata[$value]["max_gust"];
      $mydata[$value]["peak_ts"] = strtotime(substr( $mydata[$value]["max_gust_ts"],0,16) );
    } else {
      $mydata[$value]["peak"] = $mydata[$value]["max_sknt"];
      if ($mydata[$value]["max_sknt_ts"] > 0) {
          $mydata[$value]["peak_ts"] = strtotime(substr( $mydata[$value]["max_sknt_ts"],0,16) );
      }
    }
    if ($mydata[$value]["pday"] < 0) $mydata[$value]["pday"] = "";
    if ($mydata[$value]["phour"] < 0) $mydata[$value]["phour"] = "";
    if ($mydata[$value]["vsby"] < 0) $mydata[$value]["vsby"] = "";

   }
 }

 // Handle when there are no stations here
 if (sizeof($mydata) == 0){
   echo "<p>There are currently 0 sites in your selected list.  Please visit
    one of the data network pages listed above and add sites to your favorites
    list.</p>";
 } else {
?>

<form method="GET" action="current.phtml">

<table style="width: 100%; font-size: 10pt;" class="ruler">
<thead>
<tr>
  <?php $uri = "current.phtml?metar=$metar&sortcol="; ?>
  <th rowspan="2">DEL</th>
  <th rowspan="2"><a href="<?php echo $uri; ?>sname">Station:</a></th>
  <th rowspan="2"><a href="<?php echo $uri; ?>ts">Valid</a></th>
  <th colspan=6></td>
  <th colspan="3" bgcolor="#EEEEEE">Wind Knots</th>
  <th colspan="2" bgcolor="#e6e6fa">Precipitation</th>
</tr>
<tr>
  <th><a href="<?php echo $uri; ?>tmpf">Temp</a> (<a href="<?php echo $uri; ?>max_tmpf">Hi</a>/<a href="<?php echo $uri; ?>min_tmpf">Lo</a>)</th>
  <th><a href="<?php echo $uri; ?>dwpf">DewP</a></th>
  <th><a href="<?php echo $uri; ?>feel">Feels</a></th>
  <th><a href="<?php echo $uri; ?>relh">RH%</a></th>
  <th><a href="<?php echo $uri; ?>pres">Pres</a></th>
  <th><a href="<?php echo $uri; ?>vsby">Vsby</a></th>
  <th>Dir</th>
  <th><a href="<?php echo $uri; ?>sknt">Speed</a></th>
  <th><a href="<?php echo $uri; ?>peak">Today Gust</a> 
    <a href="<?php echo $uri; ?>peak_ts">@time</a></th>
  <th><a href="<?php echo $uri; ?>phour">Hour</a></th>
  <th><a href="<?php echo $uri; ?>pday">Today</a></th>
</tr>
 </thead>
<tbody>
<?php
 $finalA = Array();
if ($sortcol == "sname"){
 $finalA = sortBySecondIndex($mydata, $sortcol);
}else{
 $finalA = aSortBySecondIndex($mydata, $sortcol);
}
 $now = time();
 $cgiStr = "";
 $i = 0;
while (list ($key, $val) = each ($finalA))  { 
  $i++;
  $parts = $finalA[$key];
  $cgiStr .= "st[]=". $key ."&";
  $tdiff = $now - $parts["ts"];
  echo "<tr";
  if ($i % 2 == 0)  echo " bgcolor='#eeeeee'";
  echo ">\n 
    <td><input type=\"checkbox\" name=\"str[]\" value=\"".$key."\"></td>
    <th>". $parts["sname"] . " [". $parts["network"] ."]</th>";
  echo "<td ";
  if ($tdiff > 10000){
    echo 'bgcolor="red"';
    $format = "%b-%d %I:%M %p";
  } else if ($tdiff > 3600){
    echo 'bgcolor="green"';
    $format = "%I:%M %p";
  } else {
    $format = "%I:%M %p";
  }
   echo ">". strftime($format, $parts["ts"]) ."</td>";

  echo "<td align='center'>". round($parts["tmpf"],0) ."(<font color=\"#ff0000\">". round($parts["max_tmpf"],0) ."</font>/<font color=\"#0000ff\">". round($parts["min_tmpf"],0) .")</td>
          <td align='center'>". round($parts["dwpf"],0) ."</td>
          <td>". round($parts["feel"],0) ."</td>
          <td>". round($parts["relh"],0) ."</td>
          <td>". $parts["pres"] ."</td>
          <td>". $parts["vsby"] ."</td>
            <td>". round($parts["drct"],0) ."</td>
            <td>". round($parts["sknt"],0) ."</td><td>". round($parts["peak"],0) ." @ ";
  echo strftime($format, $parts["peak_ts"]) ;
  echo "</td>
          <td>". $parts["phour"] ."</td>
          <td>". $parts["pday"] ."</td></tr>\n";
         if ($metar == "yes") {
            echo "<tr";
            if ($i % 2 == 0)  echo " bgcolor='#eeeeee'";
            echo ">";
            echo "<td colspan=15 align=\"CENTER\">
             <font color=\"brown\">". $parts["raw"] ."</font></td>
             </tr>\n";
         }
}

?>
</tbody>
<tfoot>
<tr>
 <td></td>
 <td></td>
 <td></td>
 <td><a href="javascript:new_window('http://mesonet.agron.iastate.edu/GIS/apps/php/currents.phtml?var=tmpf&<?php echo $cgiStr ; ?>');">Plot</a> (<a href="javascript:new_window('http://mesonet.agron.iastate.edu/GIS/apps/php/currents.phtml?var=max_tmpf&<?php echo $cgiStr ; ?>');">Plot</a> / <a href="javascript:new_window('http://mesonet.agron.iastate.edu/GIS/apps/php/currents.phtml?var=min_tmpf&<?php echo $cgiStr ; ?>');">Plot</a> )</td>
 <td><a href="javascript:new_window('http://mesonet.agron.iastate.edu/GIS/apps/php/currents.phtml?var=dwpf&<?php echo $cgiStr ; ?>');">Plot</a></td>
 <td><a href="javascript:new_window('http://mesonet.agron.iastate.edu/GIS/apps/php/currents.phtml?var=feel&<?php echo $cgiStr ; ?>');">Plot</a></td>
 <td><a href="javascript:new_window('http://mesonet.agron.iastate.edu/GIS/apps/php/currents.phtml?var=relh&<?php echo $cgiStr ; ?>');">Plot</a></td>
 <td></td>
 <td><a href="javascript:new_window('http://mesonet.agron.iastate.edu/GIS/apps/php/currents.phtml?var=vsby&<?php echo $cgiStr ; ?>');">Plot</a></td>
 <td></td>
 <td><a href="javascript:new_window('http://mesonet.agron.iastate.edu/GIS/apps/php/currents.phtml?var=sknt&<?php echo $cgiStr ; ?>');">Plot</a></td>
 <td><a href="javascript:new_window('http://mesonet.agron.iastate.edu/GIS/apps/php/currents.phtml?var=max_sknt&<?php echo $cgiStr ; ?>');">Plot</a></td>
 <td colspan="3"></td>

</tr>
</tfoot>
</table>

<input type="submit" value="Remove Stations">
</form>
<?php

} // end of else

//==========================================================================
if ($doSF == 1){
?>
<h3 align="center">RWIS Pavement Conditions</h3>
<form method="GET" action="/my/current.phtml">
<table border=1 style="font-size: 10pt;" cellspacing=0 cellpadding=2 width="100%">
<tr>
  <td rowspan="2">DEL:</td>
  <th rowspan="2"><a href="current.phtml?sortcol=sname">Station:</a></th>
  <th rowspan="2"><a href="current.phtml?sortcol=ts">Ob Time</a></th>
  <th colspan="2" bgcolor="#acdcda">Air:</th>
  <th bgcolor="#acdcda">Sensor 1</th>
  <th bgcolor="#acdcda">Sensor 2</th>
  <th bgcolor="#acdcda">Sensor 3</th>
  <th bgcolor="#acdcda">Sensor 4</th>
  <td></td>
  <td></td>
<tr>
  
  <th><a href="current.phtml?sortcol=tmpf">Temp</a></th>
  <th><a href="current.phtml?sortcol=dwpf">Dew P</a></th>
  <th><a href="current.phtml?sortcol=tsf0">Temp</a></th>
  <th><a href="current.phtml?sortcol=tsf1">Temp</a></th>
  <th><a href="current.phtml?sortcol=tsf2">Temp</a></th>
  <th><a href="current.phtml?sortcol=tsf3">Temp</a></th>
  <th><a href="current.phtml?sortcol=rwis_subf">Sub T</a></th>
  <th><a href="current.phtml?sortcol=pave_avg">Ave Surface Temp</a> [<b>2</b>]
</th>
<?php

 $mydata = Array();
 foreach ($_SESSION['stations'] as $key => $value){
   if (strlen($value) == 7){
     $value = substr($value, 0, 4);
     $iemob = $iem->getSingleSite($value);
     $mydata[$value] = $iemob->db;
     $mydata[$value]["ts"] = $iemob->ts;

     $t = Array($mydata[$value]['tsf0'], $mydata[$value]['tsf1'], 
      $mydata[$value]['tsf2'], $mydata[$value]['tsf3']);
     arsort($t);
     while (min($t) == -99.99){  
      $ba = array_pop($t); 
      if (sizeof($t) == 0) break;
      }
     if (sizeof($t) > 0){
      while ((max($t) - min($t)) > 20){ $ba = array_pop($t); }
      $mydata[$value]['pave_avg'] = array_sum($t) / sizeof($t);
     } else {
      $mydata[$value]['pave_avg'] = -99.99;
     }
   }
 }

 $finalA = Array();
  $finalA = aSortBySecondIndex($mydata, $sortcol);
  $i = 0;
  $now = time();
  while (list ($key, $val) = each ($finalA))  {
    $parts = $finalA[$key];
          $i++;
          $tdiff = $now - $parts["ts"];
    if ($tdiff > 86400*5){
      continue;
    }
          echo "<tr";
          if ($i % 2 == 0)  echo " bgcolor='#eeeeee'";  
            
          echo ">";
          echo "<td><input type=\"checkbox\" name=\"str[]\" 
            value=\"".$key."_SF\"></td>";
          echo "<th>". $parts["sname"] . "</th>";
  echo "<td";
  if ($tdiff > 11900){
    echo ' bgcolor="red">'. strftime("%b-%d-%y %I:%M %p", $parts["ts"]) .'</td>'
;
  } else if ($tdiff > 7200){
    echo ' bgcolor="orange">'. strftime("%b-%d %I:%M %p", $parts["ts"]) .'</td>'
;
  } else if ($tdiff > 3600){
    echo ' bgcolor="green">'. strftime("%I:%M %p", $parts["ts"]) .'</td>';
  } else {
  echo '>'. strftime("%I:%M %p", $parts["ts"]) .'</td>';
  }
     if ($parts["tsf0"] < -90) $tmpf0 = "M";
     else $tmpf0 = round($parts["tsf0"], 1);
     if ($parts["tsf1"] < -90) $tmpf1 = "M";
     else $tmpf1 = round($parts["tsf1"], 1);
     if ($parts["tsf2"] < -90) $tmpf2 = "M";
     else $tmpf2 = round($parts["tsf2"], 1);
     if ($parts["tsf3"] < -90) $tmpf3 = "M";
     else $tmpf3 = round($parts["tsf3"], 1);
     if ($parts["rwis_subf"] < -90) $subt = "M";
     else $subt = round($parts["rwis_subf"], 1);
     if ($parts["pave_avg"] < -90) $pave_avg = "M";
     else $pave_avg = round($parts["pave_avg"], 1);

            echo "<td align='center'>". $parts["tmpf"] ."</td>
            <td align='center'>". $parts["dwpf"] ."</td>
            <td align='center'>". $tmpf0 ."</td>
            <td align='center'>". $tmpf1 ."</td>
            <td align='center'>". $tmpf2 ."</td>
            <td align='center'>". $tmpf3 ."</td>
            <td align='center'>". $subt ."</td>
            <td align='center'>". $pave_avg ."</td>
            </tr>\n";


   }


?>
</table>
<input type="submit" value="Remove Stations">
</form>


<?php
}
//===========================================================================
?>

<br><br>

<b>Notes:</b><br>
<b>1.</b> The plotting functionality does not work in all situations.  It 
does work sometimes!
<br><b>2. </b> The average surface temperature is calculated by the IEM using some
logic to account for sites without 4 sensors or broken sensors.

<br><br></div>

<?php include("$rootpath/include/footer.php"); ?>
