<?php 
include("../../../config/settings.inc.php");
	$TITLE = "IEM | Webcam Lapse Player";
$HEADEXTRA = '
    <script src="AC_RunActiveContent.js" type="text/javascript"></script>
    <script src="FAVideo.js" type="text/javascript"></script>
';
    $THISPAGE = "webcam-lapse";
	include("$rootpath/include/header.php"); 
$c = Array(
  "algona" => "Algona",
  "ames" => "Ames",
  "zoo" => "Blank Park Zoo",
  "bigcreek" => "Big Creek Marina",
  "brookings" => "Brookings, SD",
  "rathbun" => "Lake Rathbun",
  "cedarrapids-mm" => "Cedar Rapids - Mount Mercy",
  "chariton" => "Chariton",
  "clarion" => "Clarion",
  "creston" => "Creston",
  "dubuque" => "Dubuque",
  "glidden" => "Glidden",
  "greenfield" => "Greenfield",
  "humboldt" => "Humboldt",
  "huron" => "Huron, SD",
  "indy" => "Indianola",
  "iemwest" => "ISU Ag Farm",
  "jeff" => "Jefferson",
  "knoxville" => "Knoxville",
  "lamoni" => "Lamoni",
  "madrid" => "Madrid",
  "mitchell" => "Mitchell, SD",
  "monticello" => "Monticello",
  "newton" => "Newton",
  "nevada" => "Nevada",
  "osceola" => "Osceola",
  "panora" => "Panora",
  "pella" => "Pella",
  "saylor" => "Saylorville Lake",
  "stratford" => "Stratford",
  "rock" => "Rockwell City",
  "tama" => "Tama",
  "twincedars" => "Twin Cedars",
  "vinton" => "Vinton",
  "washington" => "Washington",
  "watertown" => "Watertown, SD",
  "web" => "Webster City",
  "winterset" => "Winterset");
?>



<div style="background: #eee; border: 1px solid #000; margin: 5px; padding: 5px; width: 650px;">
The <strong>Web Camera Movie Player</strong> is a Flash application that plays
recent movies taken from the webcam network.  Please note the timestamps to 
see when this movie was generated.
<div id="myPlayer"></div>
<form name="theform">
<br /><strong>Select Camera:</strong>
<select name="mycam" onchange="myloader();">
<?php
while( list($key, $value) = each($c) )
{
  echo "<option value=\"$key\">$value \n";
}
?>
</select>
<strong>Select Lapse:</strong>
<select name="mylapse" onchange="myloader()">
 <option value="sunrise">Sunrise 
 <option value="morning">Morning (8 AM - 11 AM) 
 <option value="afternoon">Afternoon (1 PM - 4 PM)
 <option value="eve">Sunset 
 <option value="day">Full day
</select>
</div>
</form>

<p>Application powered by <a href="http://labs.adobe.com/wiki/index.php/Flash-Ajax_Video_Component">FAVideo</a>

<script>
player = new FAVideo("myPlayer","http://mesonet.agron.iastate.edu/onsite/lapses/auto/algona_sunrise.flv",0,0,{ autoLoad:true, autoPlay:true });
player.setSize(640,480);
myloader();
player.setAutoPlay(true);

function myloader()
{
  ts = new Date();
  var url = "http://mesonet.agron.iastate.edu/onsite/lapses/auto/"+ document.theform.mycam.value +"_"+ document.theform.mylapse.value +".flv?"+ ts.getTime();
  player.load(url);
  player.play();
}

</script>

<?php include("$rootpath/include/footer.php"); ?>
