<?php
 /* 
  * Add/Edit a site to the IEM Database 
  * $Id: $:
  */
include("../../../config/settings.inc.php");
include("$rootpath/include/database.inc.php");

$station = isset($_REQUEST["station"]) ? substr($_REQUEST["station"],0,10) : "";
$sname = isset($_REQUEST["sname"]) ? $_REQUEST["sname"] : "";
$state = isset($_REQUEST["state"]) ? $_REQUEST["state"] : "";
$country = isset($_REQUEST["country"]) ? $_REQUEST["country"] : "";
$elevation = isset($_REQUEST["elevation"]) ? $_REQUEST["elevation"] : "";
$network = isset($_REQUEST["network"]) ? substr($_REQUEST["network"],0,10) : "";
$online = isset($_REQUEST["online"]) ? $_REQUEST["online"] : "";
$latitude = isset($_REQUEST["latitude"]) ? $_REQUEST["latitude"] : "";
$longitude = isset($_REQUEST["longitude"]) ? $_REQUEST["longitude"] : "";

$pg_conn = iemdb("mesosite");

/* Input station Details */
if (isset($_REQUEST["longitude"]) && isset($_REQUEST["latitude"]))
{
   $sql = sprintf("INSERT into stations (id, network) values ('%s','%s')", $station, $network);
   @pg_exec($pg_conn, $sql);

   $sql = sprintf("UPDATE stations SET synop = 9999, country = '%s', plot_name = '%s', 
   name = '%s', state = '%s', elevation = '%s', online = '%s', 
   geom = 'SRID=4326;POINT(%s %s)' WHERE id = '%s' and network = '%s'", $country, $sname, $sname, 
   $state, $elevation, $online, $longitude, $latitude,  $station, $network);
   pg_exec($pg_conn, $sql);
   
   echo "<h2>Updated Station Table!</h2>";
}

/* Search for station */
$sql = sprintf("SELECT *, y(geom), x(geom) from stations WHERE id = '%s' and network = '%s'", 
		$station, $network);
$rs = pg_exec($pg_conn, $sql);
if (pg_numrows($rs) == 1){
  	$row = pg_fetch_assoc($rs,0);
  	$elevation = $row['elevation'];
  	$sname = $row["name"];
  	$latitude = $row["y"];
  	$online = $row["online"];
  	$longitude = $row["x"];
  	$country = $row["country"];
  	$state = $row["state"];
}

?>

<h3>Add/Edit a Site to the mesosite database</h3>

<p><a href="<?php echo $rooturl; ?>/admin/">Back to admin</a>

<form method="POST" name="finder">
<p>Find SiteID:<input type="text" name="station">
and network:<input type="text" name="network"><input type="submit" value="go">
</form>

<form method="POST" name="editor">

<table>
<tr><th>Site ID:</th><td><input type="text" name="station" value="<?php echo $station; ?>"></td></tr>
<tr><th>Name:</th><td><input type="text" name="sname" value="<?php echo $sname; ?>"></td></tr>
<tr><th>State Abbrev:</th><td><input type="text" name="state" size="2" value="<?php echo $state; ?>"></td></tr>
<tr><th>Country:</th><td><input type="text" name="country" size="2" value="<?php echo $country; ?>"></td></tr>
<tr><th>Elevation (m):</th><td><input type="text" name="elevation" value="<?php echo $elevation; ?>"></td></tr>
<tr><th>Network:</th><td><input type="text" name="network" value="<?php echo $network; ?>"></td></tr>
<tr><th>Online (t or f):</th><td><input type="text" name="online" value="<?php echo $online; ?>"></td></tr>
<tr><th>Latitude:</th><td><input type="text" name="latitude" value="<?php echo $latitude; ?>"></td></tr>
<tr><th>Longitude:</th><td><input type="text" name="longitude" value="<?php echo $longitude; ?>"></td></tr>

</table>
<input type="reset" />
<input type="submit" />

</form>
