<?php
include("../../../config/settings.inc.php");
include("$rootpath/include/database.inc.php");
 /* Add/Edit a site to the IEM Database */

$station = isset($_GET["station"]) ? $_GET["station"] : "";
$sname = isset($_GET["sname"]) ? $_GET["sname"] : "";
$state = isset($_GET["state"]) ? $_GET["state"] : "";
$elevation = isset($_GET["elevation"]) ? $_GET["elevation"] : "";
$network = isset($_GET["network"]) ? $_GET["network"] : "";
$online = isset($_GET["online"]) ? $_GET["online"] : "";
$latitude = isset($_GET["latitude"]) ? $_GET["latitude"] : "";
$longitude = isset($_GET["longitude"]) ? $_GET["longitude"] : "";

$pg_conn = iemdb("mesosite");

/* Input station Details */
if (strlen($station) > 0 && strlen($sname) > 0)
{
   $sql = sprintf("INSERT into stations (id, network) values ('%s','%s')", $station, $network);
   echo $sql;
  pg_exec($pg_conn, $sql);
   $sql = sprintf("UPDATE stations SET synop = 9999, country = 'US', plot_name = '%s', name = '%s', state = '%s', elevation = '%s', online = '%s', geom = 'SRID=4326;POINT(%s %s)' WHERE id = '%s' and network = '%s'", $sname, $sname, $state, $elevation, $online, $longitude, $latitude,  $station, $network);
  echo $sql;
  pg_exec($pg_conn, $sql);
}

/* Search for station */
if (strlen($station) > 0 && strlen($sname) == 0) 
{
  $sql = sprintf("SELECT * from stations WHERE id = '%s' and network = '%s'", $station, $network);
  echo $sql;
}

?>

<h3>Add/Edit a Site to the mesosite database</h3>

<form method="GET" name="finder">
<p>Find SiteID:<input type="text" name="station">
and network:<input type="text" name="network"><input type="submit" value="go">
</form>

<form method="GET" name="editor">

<table>
<tr><th>Site ID:</th><td><input type="text" name="station" value="<?php echo $station; ?>"></td></tr>
<tr><th>Name:</th><td><input type="text" name="sname" value="<?php echo $sname; ?>"></td></tr>
<tr><th>State Abbrev:</th><td><input type="text" name="state" size="2" value="<?php echo $state; ?>"></td></tr>
<tr><th>Elevation (m):</th><td><input type="text" name="elevation" value="<?php echo $elevation; ?>"></td></tr>
<tr><th>Network:</th><td><input type="text" name="network" value="<?php echo $network; ?>"></td></tr>
<tr><th>Online (t or f):</th><td><input type="text" name="online" value="<?php echo $online; ?>"></td></tr>
<tr><th>Latitude:</th><td><input type="text" name="latitude" value="<?php echo $latitude; ?>"></td></tr>
<tr><th>Longitude:</th><td><input type="text" name="longitude" value="<?php echo $longitude; ?>"></td></tr>

</table>

<input type="submit">

</form>
