<?php
        $Acities = array(
"DSM" => array("city" => "Des Moines","id" => "dsm"),
"ALO" => array("city" => "Waterloo", "id" => "alo"),
"DBQ" => array("city" => "Dubuque", "id" => "dbq"),
"DVN" => array("city" => "Davenport", "id" => "dvn"),
"CID" => array("city" => "Cedar Rapids", "id" => "cid"),
"BRL" => array("city" => "Burlington", "id" => "brl"),
"OTM" => array("city" => "Ottumwa", "id" => "otm"),
"LWD" => array("city" => "Lamoni", "id" => "lwd"),
"AMW" => array("city" => "Ames", "id" => "amw"),
"MIW" => array("city" => "Marshalltown", "id" => "miw"),
"MCW" => array("city" => "Mason City", "id" => "mcw"),
"EST" => array("city" => "Estherville", "id" => "est"),
"SPW" => array("city" => "Spencer", "id" => "spw"),
"CBF" => array("city" => "Council Bluffs", "id" => "cbf"),
"IOW" => array("city" => "Iowa City", "id" => "iow"),
"SUX" => array("city" => "Sioux City", "id" => "sux")
 );
        $A2cities = array(
"DSM" => array("city" => "Des Moines","id" => "dsm"),
"ALO" => array("city" => "Waterloo", "id" => "alo"),
"DBQ" => array("city" => "Dubuque", "id" => "dbq"),
"DVN" => array("city" => "Davenport", "id" => "dvn"),
"FOD" => array("city" => "Fort Dodge", "id" => "fod"),
"CWI" => array("city" => "Clinton", "id" => "cwi"),
"CID" => array("city" => "Cedar Rapids", "id" => "cid"),
"BRL" => array("city" => "Burlington", "id" => "brl"),
"OTM" => array("city" => "Ottumwa", "id" => "otm"),
"LWD" => array("city" => "Lamoni", "id" => "lwd"),
"AMW" => array("city" => "Ames", "id" => "amw"),
"MIW" => array("city" => "Marshalltown", "id" => "miw"),
"MCW" => array("city" => "Mason City", "id" => "mcw"),
"EST" => array("city" => "Estherville", "id" => "est"),
"SPW" => array("city" => "Spencer", "id" => "spw"),
"CBF" => array("city" => "Council Bluffs", "id" => "cbf"),
"IOW" => array("city" => "Iowa City", "id" => "iow"),
"SUX" => array("city" => "Sioux City", "id" => "sux")
 );
      $Ocities = array(
"AFK" => array("city" => "Nebraska City, NE", "id" => "AFK", "lat" => "40.6", "lon" => "-95.87"),
"OTG"=> array("city" => "Worthington, MN","id" => "otg"),
"MJQ"=> array("city" => "Jackson, MN","id" => "mjq"),
"FRM"=> array("city" => "Fairmont, MN","id" => "frm"),
"AEL"=> array("city" => "Albert Lea, MN","id" => "ael"),
"AUM" => array("city" => "Austin, MN","id" => "aum"),
"RST"=> array("city" => "Rochester, MN","id" => "rst"),
"ONA"=> array("city" => "Winona, MN","id" => "ona"),
"TOB"=> array("city" => "Dodge Center, MN","id" => "tob"),
"OWA"=> array("city" => "Owatonna, MN","id" => "owa"),
"FBL" => array("city" => "Faribault, MN","id" => "fbl"),
"MKT"=> array("city" => "Mankato, MN","id" => "mkt"),
"JYG"=> array("city" => "St. James, MN","id" => "jyg"),
"ULM"=> array("city" => "New Ulm, MN","id" => "ulm"),
"MWM"=> array("city" => "Windom, MN","id" => "mwm"),
"PQN"=> array("city" => "Pipestone, MN","id" => "pqn"),
"FKA"=> array("city" => "Preston, MN","id" => "fka"),
"MML"=> array("city" => "Marshall/Ryan, MN","id" => "mml"),
"YKN"=> array("city" => "Yankton, SD","id" => "ykn"),
"FSD"=> array("city" => "Souix Falls, SD","id" => "fsd"),
"BKX"=> array("city" => "Brookings, SD","id" => "bkx"),
"MHE"=> array("city" => "Mitchell, SD","id" => "mhe"),
"OMA"=> array("city" => "Omaha, NE","id" => "oma"),
"TQE"=> array("city" => "Tekamah, NE","id" => "tqe"),
"OFK"=> array("city" => "Norfolk, NE","id" => "ofk"),
"OLU"=> array("city" => "Columbus, NE","id" => "olu"),
"FET"=> array("city" => "Fremont, NE","id" => "fet"),
"LNK"=> array("city" => "Lincoln, NE","id" => "lnk"),
"BIE"=> array("city" => "Beatrice, NE","id" => "bie"),
"FNB"=> array("city" => "Falls City, NE","id" => "fnb"),
"MLE"=> array("city" => "Millard, NE", "id" => "mle"),
"ONL"=> array("city" => "O'Neill, NE", "id" => "ONL"),
"STJ"=> array("city" => "St Joseph, MO","id" => "stj"),
"IRK"=> array("city" => "Kirksville, MO","id" => "irk"),
"UIN"=> array("city" => "Quincy, IL","id" => "uin"),
"MQB"=> array("city" => "Macomb, IL","id" => "mqb"),
"GBG"=> array("city" => "Galesburg, IL","id" => "gbg"),
"MLI"=> array("city" => "Moline, IL","id" => "mli"),
"SQI"=> array("city" => "Sterling Rock Falls, IL","id" => "sqi"),
"FEP"=> array("city" => "Freeport, IL","id" => "fep"),
"PRG"=> array("city" => "Paris, IL","id" => "prg"),
"VYS"=> array("city" => "Peru, IL","id" => "vys"),
"PDC"=> array("city" => "Praire Du Chien, WI","id" => "pdc"),
"OVS"=> array("city" => "Boscobel, WI","id" => "ovs"),
"MRJ"=> array("city" => "Mineral Point, WI","id" => "mrj"),
"EFT"=> array("city" => "Monroe, WI","id" => "eft"),
"LNR"=> array("city" => "Lone Rock, WI","id" => "lnr")
);
?>
