<?php

        $Zcities = array(
"ADU" => array("city" => "Audubon","id" => "ADU"),
"AIO" => array("city" => "Atlantic", "id" => "AIO"),
"AWG" => array("city" => "Washington", "id" => "AWG"),
"AXA" => array("city" => "Algona", "id" => "AXA"),
"BNW" => array("city" => "Boone", "id" => "BNW"),
"CAV" => array("city" => "Clarion", "id" => "CAV"),
"CCY" => array("city" => "Charles City", "id" => "CCY"),
"CIN" => array("city" => "Carroll", "id" => "CIN"),
"CNC" => array("city" => "Chariton", "id" => "CNC"),
"CSQ" => array("city" => "Creston", "id" => "CSQ"),
"CWI" => array("city" => "Clinton", "id" => "CWI"),
"DEH" => array("city" => "Decorah", "id" => "DEH"),
"DNS" => array("city" => "Denison", "id" => "DNS"),
"EBS" => array("city" => "Webster City", "id" => "EBS"),
"EOK" => array("city" => "Keokuk", "id" => "EOK"),
"FFL" => array("city" => "Fairfeild", "id" => "FFL"),
"FOD" => array("city" => "Fort Dodge", "id" => "FOD"),
"FSW" => array("city" => "Fort Madison", "id" => "FSW"),
"HNR" => array("city" => "Harlan", "id" => "HNR"),
"ICL" => array("city" => "Clarinda", "id" => "ICL"),
"IKV" => array("city" => "Ankeny", "id" => "IKV"),
"LRJ" => array("city" => "Le Mars", "id" => "LRJ"),
"MUT" => array("city" => "Muscatine", "id" => "MUT"),
"MXO" => array("city" => "Monticello", "id" => "MXO"),
"OLZ" => array("city" => "Oelwein", "id" => "OLZ"),
"ORC" => array("city" => "Orange City", "id" => "ORC"),
"OXV" => array("city" => "Knoxville", "id" => "OXV"),
"RDK" => array("city" => "Red Oak", "id" => "RDK"),
"SDA" => array("city" => "Shenandoah", "id" => "SDA"),
"SHL" => array("city" => "Sheldon", "id" => "SHL"),
"SLB" => array("city" => "Storm Lake", "id" => "SLB"),
"TNU" => array("city" => "Newton", "id" => "TNU"),
"DSM" => array("city" => "Des Moines","id" => "DSM"),
"ALO" => array("city" => "Waterloo", "id" => "ALO"),
"DBQ" => array("city" => "Dubuque", "id" => "DBQ"),
"DVN" => array("city" => "Davenport", "id" => "DVN"),
"CID" => array("city" => "Cedar Rapids", "id" => "CID"),
"BRL" => array("city" => "Burlington", "id" => "BRL"),
"OTM" => array("city" => "Ottumwa", "id" => "OTM"),
"LWD" => array("city" => "Lamoni", "id" => "LWD"),
"AMW" => array("city" => "Ames", "id" => "AMW"),
"MIW" => array("city" => "Marshalltown", "id" => "MIW"),
"MCW" => array("city" => "Mason City", "id" => "MCW"),
"EST" => array("city" => "Estherville", "id" => "EST"),
"SPW" => array("city" => "Spencer", "id" => "SPW"),
"CBF" => array("city" => "Council Bluffs", "id" => "CBF"),
"IOW" => array("city" => "Iowa City", "id" => "IOW"),
"SUX" => array("city" => "Sioux City", "id" => "SUX")

 );

?>      
