<?php
        $Rcities = array(
"RADA" => array("city" => "Adair (I-80)","id" => "RADA"),
"RALG" => array("city" => "Algona (US 18)", "id" => "RALG"),
"RATN" => array("city" => "Alton (IA10)", "id" => "RATN"),
"RALT" => array("city" => "Altoona (I-80/US 65)", "id" => "RALT"),
"RAME" => array("city" => "Ames (I-35)", "id" => "RAME"),
"RANK" => array("city" => "Ankeny (I-35)", "id" => "RANK"),
"RAVO" => array("city" => "Avoca (I-80)", "id" => "RAVO"),
"RBUR" => array("city" => "Burlington (US 34)", "id" => "RBUR"),
"RCAR" => array("city" => "Carroll (US 30)", "id" => "RCAR"),
"RCDR" => array("city" => "Cedar Rapids (I-380)", "id" => "RCDR"),
"RCID" => array("city" => "Cedar Rapids (US 30)", "id" => "RCID"),
"RCRI4" => array("city" => "Cedar Rapids (US-30)", "id" => "RCRI4"),
"RCEN" => array("city" => "Centerville (IA 2)", "id" => "RCEN"),
"RCOU" => array("city" => "Council Bluffs (I-80)", "id" => "RCOU"),
"RCRE" => array("city" => "Creston (US 34)", "id" => "RCRE"),
"RDAV" => array("city" => "Davenport (I-80/I-280)", "id" => "RDAV"),
"RDEC" => array("city" => "Decorah (IA 9)", "id" => "RDEC"),
"RDSM" => array("city" => "Des Moines (I-35)", "id" => "RDSM"),
"RDES" => array("city" => "Des Moines (I-235)", "id" => "RDES"),
"RDST" => array("city" => "De Soto (I-80/US 169)", "id" => "RDST"),
"RDEW" => array("city" => "De Witt (US 30/US 61)", "id" => "RDEW"),
"RDUB" => array("city" => "Dubuque (US 20)", "id" => "RDUB"),
"RFOD" => array("city" => "Fort Dodge (US 20)", "id" => "RFOD"),
"RGRI" => array("city" => "Grinnell (I-80)", "id" => "RGRI"),
"RHAN" => array("city" => "Hanlontown (I-35)", "id" => "RHAN"),
"RIAC" => array("city" => "Iowa City (US 218)", "id" => "RIAC"),
"RIOW" => array("city" => "Iowa City (I-80)", "id" => "RIOW"),
"RJEF" => array("city" => "Jefferson (IA 4)", "id" => "RJEF"),
"RLEO" => array("city" => "Leon (I-35)/IA 2)", "id" => "RLEO"),
"RMAN" => array("city" => "Manchester (US 20)", "id" => "RMAN"),
"RMAQ" => array("city" => "Maquoketa (US 61/IA 64)", "id" => "RMAQ"),
"RMAR" => array("city" => "Marshalltown (US 30)", "id" => "RMAR"),
"RMCW" => array("city" => "Mason City (I-35)", "id" => "RMCW"),
"RMIS" => array("city" => "Missouri Valley (I-29)", "id" => "RMIS"),
"RMOU" => array("city" => "Mount Pleasant (US 218)", "id" => "RMOU"),
"RNEW" => array("city" => "New Hampton (US 18)", "id" => "RNEW"),
"RONA" => array("city" => "Onawa (I-29)", "id" => "RONA"),
"ROSC" => array("city" => "Osceola (I-35)", "id" => "ROSC"),
"ROTT" => array("city" => "Ottumwa (US 63)", "id" => "ROTT"),
"RPEL" => array("city" => "Pella (IA 163)", "id" => "RPEL"),
"RRED" => array("city" => "Red Oak (US 34/US 71)", "id" => "RRED"),
"RSID" => array("city" => "Sidney (I-29/IA 2)", "id" => "RSID"),
"RSIG" => array("city" => "Sigourney (IA 92)", "id" => "RSIG"),
"RSIO" => array("city" => "Sioux City (I-29)", "id" => "RSIO"),
"RSPE" => array("city" => "Spencer (US 18)", "id" => "RSPE"),
"RSBI4" => array("city" => "Steamboat Rock (US-20)", "id" => "RSBI4"),
"RSTO" => array("city" => "Storm Lake (US 71/IA 3)", "id" => "RSTO"),
"RTIP" => array("city" => "Tipton (I-80)", "id" => "RTIP"),
"RURB" => array("city" => "Urbana (I-380)", "id" => "RURB"),
"RWAT" => array("city" => "Waterloo (US 20)", "id" => "RWAT"),
"RWIL" => array("city" => "Williams (I-35)", "id" => "RWIL"),
"RWBG" => array("city" => "Williamsburg (I-80)", "id" => "RWBG")
 );
?>
