<?php
/*
 * The IEM homepage!
 */
require_once '../config/settings.inc.php';
define("IEM_APPID", 1);
require_once '../include/mlib.php';
force_https();
require_once '../include/myview.php';
require_once '../include/generators.php';
require_once '../include/iemprop.php';
require_once '../include/cameras.inc.php';

$t = new MyView();
$t->headextra = <<<EOF
<link rel="alternate" type="application/rss+xml" 
  title="IEM News + Notes Feed" 
  href="/rss.php" />
EOF;
if (date("md") == "0911" || isset($_GET["911"])){
    $feature = <<<EOM
<h1 class="text-center">Remembering 9/11</h1>

<div class="row">
<div class="col-md-6">
<p class="lead">The fateful day of September 11th, 2001 is a distant memory for some, a
constant nightmare for others and an unexperienced event for most college age
students and younger.  May we all not forget the ultimate sacrifice many made
that day and the years that followed.</p> 
</div>
<div class="col-md-6">
<img src="/images/911.jpg" class="img img-responsive">
<br />&copy; Gordon Donovan/Yahoo News
</div>
</div>

EOM;
} else {
    $feature = gen_feature($t);
}
$iemperf = get_website_stats();
$lsr_snow = get_iemprop("homepage.lsrmap.on");

$rancam = "";
$loop = 0;
while ($rancam == "" && $loop < 20)
{
    $cam = array_rand($cameras);
    $camfn = "/mesonet/ldmdata/camera/stills/{$cam}.jpg";
    if (is_file($camfn) && filemtime($camfn) > (time() - 1200))
    {
        $rancam = $cam;
    }
    $loop += 1;
}
if ($rancam == ""){ $rancam = "ISUC-006";}

$lsrsnow = "";
$nunce = time();
if ($lsr_snow == 'true'){
    $lsrsnow =  <<<EOM
<div class="panel panel-default">
<div class="panel-heading">NWS Snowfall Reports:</div>
  <div class="panel-body">
<a href="/data/lsr_snowfall.png">
<img src="/data/lsr_snowfall.png?{$nunce}" border="0" alt="LSR Snowfall" class="img img-responsive"/></a>
  <a href="/lsr/#DMX,DVN,ARX,FSD,OAX/-43200">View Snowfall Reports on Map</a>
  </div>
</div>
EOM;
}

$pgconn = iemdb("mesosite");
$rs = pg_query($pgconn, "SELECT * from news ORDER by entered DESC LIMIT 5");

$today = new DateTime();

$news = "";
for ($i=0; $row = pg_fetch_array($rs); $i++){
    $ts = new DateTime(substr($row["entered"],0,16));
    if ($ts > $today) $sts = $ts->format("g:i A");
    $sts = $ts->format("j M g:i A");
    $news .= sprintf("<p><a href=\"/onsite/news.phtml?id=%s\">%s</a>".
        "<br /><i>Posted:</i> %s</li>\n", $row["id"], $row["title"], $sts);
}
$nounce = time();
$t->content = <<<EOM
      <div class="row">

        <div class="col-sm-9">
       
 <p>The Iowa Environmental Mesonet (IEM) collects environmental data from 
 cooperating members with observing networks. The data are stored and made 
 available on this website.</p>


 <div class="row">
<div class="col-xs-12 col-sm-4">
<a href="/agweather/" class="btn btn-default btn-block agweather">Ag Weather</a>
</div>
<div class="col-xs-12 col-sm-4">
<a href="/nws/" class="btn btn-default btn-block nws">NWS Users</a>
</div>
<div class="col-xs-12 col-sm-4">
<a href="/archive/" class="btn btn-default btn-block book">Researchers</a>
</div>
</div>

{$feature}
        </div><!--/col-sm-9-->
        <div class="col-sm-3">

{$lsrsnow}

<div class="panel panel-default">
  <div class="panel-heading">{$cameras[$rancam]["name"]}, {$cameras[$rancam]["state"]} Webcam:</div>
  <div class="panel-body">
<a href="/current/webcam.php#{$cameras[$rancam]["network"]}-0"><img src="/data/camera/stills/{$rancam}.jpg?{$nunce}" border="0" alt="Webcam" class="img-responsive"/></a>
<a href="/current/webcam.php#{$cameras[$rancam]["network"]}-0">View other webcams</a>
  
  </div>
</div>

<div class="panel panel-default">
  <div class="panel-heading">Most Popular (<a href="/apps.php">List Apps</a>)</div>
  <div class="panel-body">
<a href="/plotting/auto/">Automated Data Plotting</a>
<br /><a href="/climodat/">Climodat Reports</a>
<br /><a href="/explorer/">IEM Explorer</a>
<br /><a href="/timemachine/#1.0">Iowa Mesonet Plot</a>
  [<a href="/current/loop.phtml?prod=mesonet">Loop</a>]
<br /><a href="/current/mcview.phtml?prod=comprad&amp;java=none&amp;mode=realtime&amp;frames=1">Current NEXRAD</a> [<a href="/current/mcview.phtml">Loop</a>]
<br /><a href="/rainfall/">IEM GIS Rainfall</a>
<br /><a href="/my/current.phtml">Sortable Currents</a>
<br /><a href="/onsite/features/tags/winter2223.html">Winter Storms of 2022-2023</a>

    </div>
</div>

<div class="panel panel-default">
  <div class="panel-heading">News Items &nbsp; <a href="/rss.php"><img src="/images/rss.gif" /></a></div>
  <div class="panel-body">

{$news}

<p><b class='fa fa-envelope'></b>
<a href="https://groups.google.com/g/iem-dailyb">Sign up</a> for the 
<a href="/data/iemdb.html">Daily Bulletin</a></p>

  </div>
</div>

{$iemperf}

        </div><!--/span-->
      </div><!--/row-->

<!-- Three columns highlighting stuff -->
<div class="row">
    <div class="col-sm-4">
        <h3>Soil Temperatures</h3>
        <a href="/agclimate/soilt.php"><img src="/data/soilt_day1.png?{$nounce}" class="img-responsive" /></a>
        <p>Data from the <a href="/agclimate">Iowa State Soil Moisture Network</a>
        is found on this website
        and daily soil temperature averages are used to produce the highlighted
        analysis.</p>
    </div>
    <div class="col-sm-4">
        <h3>Precipitation</h3>
        <a href="/timemachine/#82.0"><img src="/data/iowa_ifc_1d.png" class="img-responsive" /></a>
        <p><a href="/current/index.phtml/precipitation">More Precipitation Maps</a></p>
    </div>
    <div class="col-sm-4">
        <h3>Current Data</h3>
        <a href="/timemachine/#1.0"><img src="/data/mesonet.gif" class="img-responsive" /></a>
        <p>The IEM combines data from participating networks into products
        like maps shown above and web applications to analyze the data.</p>
        <p><a href="/current/">More current products &raquo;</a></p>
    </div>
</div><!--/row-->

<div class="row clearfix well">
<div class="col-sm-2"><h4>Partners:</h4></div>
<div class='col-sm-4'>
<a href="http://www.agron.iastate.edu/"><img
src="/images/agronomy.png" alt="ISU Agronomy" class="img img-responsive"></a>
</div>
<div class='col-sm-2'>
<a href="http://www.iihr.uiowa.edu"><img src="/images/iihrlogo.jpg"
  alt="IIHR - University of Iowa" class="img img-responsive" /></a>
</div>
<div class='col-sm-3'>
 <a href="http://www.iowadot.gov"><img src="/images/iowadot.png"
 alt="DOT" class="img img-responsive" style="max-height: 50px;"/></a>
</div>
<div class='col-sm-1'>
  <a href="http://www.weather.gov/dmx/"><img src="/images/nws.gif"
  alt="NWS" class="img img-responsive" /></a>
</div>

</div>

EOM;

$t->render('full.phtml');
