<?php
/*
 * The IEM homepage!
 */
require_once '../config/settings.inc.php';
define("IEM_APPID", 1);
include_once '../include/myview.php';
include_once '../include/generators.php';
include_once '../include/iemprop.php';

$t = new MyView();
$t->headextra = <<<EOF
<link rel="alternate" type="application/rss+xml" 
  title="IEM News + Notes Feed" 
  href="/rss.php" />
EOF;
$t->feature = gen_feature($t);
$t->iemperf = get_website_stats();
$t->lsr_snow = get_iemprop("homepage.lsrmap.on");
$t->render('homepage.phtml');
?>