<?php
require_once '../../config/settings.inc.php';
include_once '../../include/myview.php';
include_once "../../include/cameras.inc.php";
require_once "../../include/forms.php"; 
define("IEM_APPID", 117);
$t = new MyView();

$java = isset($_GET["java"]) ? xssafe($_GET["java"]): 'script';
$cid = isset($_GET['cid']) ? xssafe($_GET['cid']): 'KCCI-016';

$t->thispage = "webcam-loop";

$frames  = isset($_GET['frames']) ? intval($_GET['frames']): 12;
$interval = isset($_GET['interval']) ? intval($_GET['interval']): 300;
$day = isset($_GET['day']) ? intval($_GET["day"]): date("d", time() - 3600);
$month = isset($_GET['month']) ? intval($_GET["month"]): date("m", time() - 3600);
$hour = isset($_GET['hour']) ? intval($_GET["hour"]): date("H", time() - 3600);
$minute = isset($_GET['minute']) ? intval($_GET["minute"]): date("i", time() - 3600);
$minute = $minute - ($minute % 5);
$year = isset($_GET['year']) ? intval($_GET["year"]): date("Y", time() - 3600);
$nts = mktime($hour, $minute, 0, $month, $day, $year);

$width = 320; $height = 240;
$szSwitch = mktime(14,0,0,5,12,2011);
if ($nts > $szSwitch){
	$width = 640;
	$height = 480;
}

$now = time();
$wmessage = "";
if ($nts < $cameras[$cid]["sts"] || $nts > $cameras[$cid]["ets"]){
  $wmessage = "<p><div class=\"warning\"><b>Error:</b> Your choice of time and station is outside of the archive available for this site!</div>\n";
  $day = date("d", $cameras[$cid]["ets"] - 3600);
  $month = date("m", $cameras[$cid]["ets"] - 3600);
  $hour = date("H", $cameras[$cid]["ets"] - 3600);
  $minute = date("i", $cameras[$cid]["ets"] - 3600);
  $year = date("Y", $cameras[$cid]["ets"] - 3600);
  $minute = $minute - ($minute % 5);
}

$nts = mktime($hour, $minute, 0, $month, $day, $year);

$images = Array();
$labels = Array();
$files = "";
for ($i=0; $i < (intval($frames));$i++){
  $ts = $nts + ($i * (intval($interval) ));
  if ($ts > $now) { /* We are in the future! */
    $frames = $i;
    break;
  }
  $uri = "/archive/data/". gmdate('Y/m/d/', $ts) ."camera/$cid/". $cid ."_". gmdate('YmdHi', $ts) .".jpg";
  $labels[] = date("d M Y H:i a", $ts);
  $images[] = $uri;
  $files .= $uri .",";
}

$cselect = "<select name=\"cid\">";
while (list($k,$v) = each($cameras)) {
	if ($v["network"] == "IDOT"){ continue; }
	$lbl = sprintf("%s (%s)", $v["name"], date("d M Y", $v["sts"]) );
	$cselect .= "<option value=\"$k\"";
	if ($cid == $k) $cselect .= "selected=\"selected\"";
	$cselect .= ">". $lbl ."\n";
}
$cselect .= "</select>";
$ys = yearSelect(2003, $year, "year");
$ms = monthSelect($month);
$ds = daySelect($day);
$hs = hourSelect($hour, "hour");
$mi = minuteSelect($minute, "minute",5);

$ar = Array(
		"script" => "Java Script",
		"none" => "List Images",
);
$loopselect = make_select("java", $java, $ar);

$ar = Array(
		"60" => "1 minute",
		"300" => "5 minutes",
		"900" => "15 minutes",
		"3600" => "1 hour",
		"86400" => "1 day",
		"604800" => "1 week",
);
$intselect = make_select("interval", $interval, $ar);

if ($java == "script") {
	$sz = sizeof($images); 
	$mis = "";
	$i = 0;
	while ( list($key,$val) = each($images) ){
		$mis .= "modImages[$i] = \"". $images[$i] ."\";\n";
		$i++;
	}
	$control = <<<EOF
<script LANGUAGE="JavaScript1.2" type="text/javascript">
//<!--
modImages = new Array();
{$mis}
first_image = 1;
last_image = {$sz};
current_image = first_image;
-->
</script>
<script language="JavaScript" src="/js/animation.js"></script>


<img NAME="animation" WIDTH="{$width}" HEIGHT="{$height}" 
		SRC="/images/pixel.gif" ALT="Image" border="2" />

  <form METHOD="POST" NAME="control_form">
<a HREF="JavaScript: func()" onClick="change_mode(1);reverse()"><img BORDER=0 SRC="../images/rev_button.gif" ALT="REV"></a>
<a HREF="JavaScript: func()" onClick="stop()"><img BORDER=0 SRC="../images/stp_button.gif" ALT="STOP"></a>
<a HREF="JavaScript: func()" onClick="change_mode(1);fwd()"><img BORDER=0 SRC="../images/fwd_button.gif" ALT="FWD"></a>
  <font SIZE=-1 COLOR="#3300CC">Frame No:</font>
  <input TYPE="text" NAME="frame_nr" VALUE=9 SIZE="2" onFocus="this.select()" onChange="go2image(this.value)"></input>
  </form>
<script LANGUAGE="JavaScript1.2" type="text/javascript">
//<!--
launch();
-->
</script>
EOF;
} else {
	$control = "";
		while ( list($key,$val) = each($images) ){
			$control .= sprintf("<img src=\"%s\" style=\"margin: 2px;\">", $val);
		}
}

$imglinks = "";
reset($images);
while ( list($key, $value) = each($images) ){
	$imglinks .= "<li><a href=\"". $images[$key] ."\">". $labels[$key] ."</a></li>";
}

$t->content = <<<EOF
{$wmessage}

<p>Still images are saved from the SchoolNet8 web cameras every 5 minutes.  
This page gives you a tool to build animations from this archive of images.</p>


<form method="GET" action="bloop.phtml" name="imageform">

<table>
<tr><th>Camera (Archive Starts / Ends):</th>
<th>Year:</th><th>Month:</th><th>Day:</th><th>Hour:</th><th>Minute:</th></tr>
 <tr>
  <td>{$cselect}
</td>

<td>{$ys}</td>
<td>{$ms}</td>
<td>{$ds}</td>
<td>{$hs}</td>
<td>{$mi}</td>
</tr>
</table>

<table>
<tr>
<th>Frames:</th><td><input type="text" maxsize="2" size="3" name="frames" value="{$frames}"></td>
<th>Loop Tool:</th>
<td>{$loopselect}</td>
<th>Frame Interval:</th><td>
{$intselect}
</td></tr></table>
<input type="submit" value="Gen Loop"></form>

<div style="text-align: center;">
{$control}
</div>

<p>Images used in this loop.<br>
<ul>
{$imglinks}
</ul>

EOF;
$t->render('single.phtml');
?>