<?php
include('../../config/settings.inc.php');
include("$rootpath/include/cameras.inc.php");
$java = isset($_GET["java"]) ? $_GET["java"] : 'applet';
$cid = isset($_GET['cid']) ? $_GET['cid'] : 'KCCI-001';

$THISPAGE = "webcam-loop";
include("$rootpath/include/header.php"); 
include("$rootpath/include/forms.php"); 

?>

<div id="justone">

<?php
 /**
  * bloop.phtml
  */


$frames  = isset($_GET['frames']) ? $_GET['frames'] : 12;
$interval = isset($_GET['interval']) ? $_GET['interval']: 300;
$day = isset($_GET['day']) ? $_GET["day"] : date("d", time() - 3600);
$month = isset($_GET['month']) ? $_GET["month"]: date("m", time() - 3600);
$hour = isset($_GET['hour']) ? $_GET["hour"]: date("H", time() - 3600);
$minute = isset($_GET['minute']) ? $_GET["minute"]: date("i", time() - 3600);
$minute = $minute - ($minute % 5);
$year = isset($_GET['year']) ? $_GET["year"]: date("Y", time() - 3600);
$nts = mktime($hour, $minute, 0, $month, $day, $year);

$now = time();
if ($nts < $cameras[$cid]["sts"] || $nts > $cameras[$cid]["ets"]){
  echo "<p><div style=\"background: #ccc;\"><b>Error:</b> Your choice of time and station is outside of the archive available for this site!</div>\n";
  $day = date("d", $cameras[$cid]["ets"] - 3600);
  $month = date("m", $cameras[$cid]["ets"] - 3600);
  $hour = date("H", $cameras[$cid]["ets"] - 3600);
  $minute = date("i", $cameras[$cid]["ets"] - 3600);
  $year = date("Y", $cameras[$cid]["ets"] - 3600);
  $minute = $minute - ($minute % 5);
}

$nts = mktime($hour, $minute, 0, $month, $day, $year);

$images = Array();
$labels = Array();
$files = "";
for ($i=0; $i < (intval($frames));$i++){
  $ts = $nts + ($i * (intval($interval) ));
  if ($ts > $now) { /* We are in the future! */
    $frames = $i;
    break;
  }
  $uri = "http://mesonet.agron.iastate.edu/archive/data/". gmdate('Y/m/d/', $ts) ."camera/$cid/". $cid ."_". gmdate('YmdHi', $ts) .".jpg";
  $labels[] = date("d M Y H:i a", $ts);
  $images[] = $uri;
  $files .= $uri .",";
}
?>

<p>Still images are saved from the SchoolNet8 web cameras every 5 minutes.  
This page gives you a tool to build animations from this archive of images.
If your browser does not support java, please try the 'Java Script' loop tool.

<form method="GET" action="bloop.phtml" name="imageform">

<table>
<tr><th>Camera (Archive Starts / Ends):</th><th>Year:</th><th>Month:</th><th>Day:</th><th>Hour:</th><th>Minute:</th></tr>
 <tr>
  <td><select name="cid">
<?php
 while (list($k,$v) = each($cameras)) {
  if ($v["network"] == "IDOT"){ continue; }
  $lbl = sprintf("%s (%s)", $v["name"], date("d M Y", $v["sts"]) );
  echo "<option value=\"$k\"";
  if ($cid == $k) echo "selected=\"selected\""; 
  echo ">". $lbl ."\n";
}
?>
</select>
</td>

<td><?php echo yearSelect(2003, $year, "year"); ?></td>
<td><?php echo monthSelect($month); ?></td>
<td><?php echo daySelect($day); ?></td>
<td><?php echo hourSelect($hour, "hour"); ?></td>
<td><?php echo minuteSelect($minute, "minute",5); ?></td>
</tr>
</table>

<table>
<tr>
<th>Frames:</th><td><input type="text" maxsize="2" size="3" name="frames" value="<?php echo $frames; ?>"></td>
<th>Loop Tool:</th>
<td>
<select name="java">
  <option value="applet" <?php if ($java == "applet") echo "selected=\"selected\""; ?>>Java Applet</option>
  <option value="script" <?php if ($java == "script") echo "selected=\"selected\""; ?>>Java Script</option>
  <option value="none" <?php if ($java == "none") echo "selected=\"selected\""; ?>>List Images (None)</option>
</select>
<th>Frame Interval:</th><td>
<select name="interval">
  <option value="60" <?php if ($interval == 60) echo "selected=\"selected\""; ?>>1 minute</option>
  <option value="300" <?php if ($interval == 300) echo "selected=\"selected\""; ?>>5 minutes</option>
  <option value="900" <?php if ($interval == 900) echo "selected=\"selected\""; ?>>15 minutes</option>
  <option value="3600" <?php if ($interval == 3600) echo "selected=\"selected\""; ?>>1 hour</option>
  <option value="86400" <?php if ($interval == 86400) echo "selected=\"selected\""; ?>>1 day</option>
  <option value="604800" <?php if ($interval == 604800) echo "selected=\"selected\""; ?>>1 week</option>
</select>
</td></tr></table>
<input type="submit" value="Gen Loop"></form>

<div style="text-align: center;">
<?php if ($java == "applet") { ?>
<applet codebase="http://mesonet.agron.iastate.edu/current/class/" code="AniS.class" width="450" height="400" alt="You must enable Java in your browser to view the radar loop">
        <param name="controls" value="startstop, looprock, step, speed, toggle,
zoom">
        <param name="rate" value="80">
 <param name="no_enh" value="true">
        <param name="pause_percent" value="800">
        <param name="filenames" value="<?php echo $files; ?>">
</applet>
<?php } else if ($java == "script") { ?>
<script LANGUAGE="JavaScript1.2" type="text/javascript">
//<!--
modImages = new Array();
<?php
 $i = 0;
 while ( list($key,$val) = each($images) ){ 
   echo "modImages[$i] = \"". $images[$i] ."\";\n";
   $i++;
 } ?>
first_image = 1;
last_image = <?php echo sizeof($images); ?>;
current_image = first_image;
-->
</script>
<script language="JavaScript" src="../js/animation.js"></script>


<img NAME="animation" WIDTH=320 HEIGHT=240 SRC="../images/pixel.gif" ALT="Image" border="2" />

  <form METHOD="POST" NAME="control_form">
<a HREF="JavaScript: func()" onClick="change_mode(1);reverse()"><img BORDER=0 SRC="../images/rev_button.gif" ALT="REV"></a>
<a HREF="JavaScript: func()" onClick="stop()"><img BORDER=0 SRC="../images/stp_button.gif" ALT="STOP"></a>
<a HREF="JavaScript: func()" onClick="change_mode(1);fwd()"><img BORDER=0 SRC="../images/fwd_button.gif" ALT="FWD"></a>
  <font SIZE=-1 COLOR="#3300CC">Frame No:</font>
  <input TYPE="text" NAME="frame_nr" VALUE=9 SIZE="2" onFocus="this.select()" onChange="go2image(this.value)"></input>
  </form>
<script LANGUAGE="JavaScript1.2" type="text/javascript">
//<!--
launch();
-->
</script>

<?php 
}  else {
while ( list($key,$val) = each($images) ){ 
  echo sprintf("<img src=\"%s\" style=\"margin: 2px;\">", $val);
}
}
?>
</div>

<p>Images used in this loop.<br>
<ul>
<?php 
reset($images);
while ( list($key, $value) = each($images) ){
  echo "<li><a href=\"". $images[$key] ."\">". $labels[$key] ."</a></li>";
}
?>
</ul>
</div>

<?php
include("$rootpath/include/footer.php"); ?>
