<?php 
 include("../../config/settings.inc.php");
include("$rootpath/include/iemprop.php");
$camera_refresh = get_iemprop("webcam.interval");
/* CGI GET Requests */
 $year = isset($_GET["year"]) ? $_GET["year"] : date("Y");
 $month = isset($_GET["month"]) ? $_GET["month"] : date("m");
 $day = isset($_GET["day"]) ? $_GET["day"] : date("d");
 $hour = isset($_GET["hour"]) ? $_GET["hour"] : date("H");
 $minute = isset($_GET["minute"]) ? $_GET["minute"] : date("i");
 $isarchive = isset($_GET["archive"]);
 $network = isset($_GET["network"]) ? $_GET["network"] : "KCCI";

 $ts = time();
 if ($isarchive){
 $radts = mktime($hour, $minute, 0, $month, $day, $year) - (($minute % 5) * 60);
 } else {
 $radts = time();
 }
 $num = 1;
 include("$rootpath/include/cameras.inc.php");
if ($network == "KCRG"){ $cameras["KCCI-017"]["network"] = "KCRG"; }
 while (list($id, $val) = each($cameras))
 {
    if ($cameras[$id]["network"] != $network) continue;

	$cameras[$id]["url"] = sprintf("$rooturl/data/camera/stills/%s.jpg?%s", $id, time() );
    if ( @filemtime("/home/ldm/data/camera/stills/${id}.jpg") < (time() - 1200))
    {      
      $cameras[$id]["active"] = false;
    }

 if ($isarchive)
 {
    $cameras[$id]["active"] = true;
    $ts = mktime($hour, $minute, 0, $month, $day, $year);
    $ts5 = mktime($hour, $minute - ($minute % 5), 0, $month, $day, $year);

    $fp = "/mesonet/ARCHIVE/data/". gmdate("Y/m/d/", $ts) ."camera/$id/${id}_". gmdate("YmdHi", $ts) .".jpg";
    $url = "$rooturl/archive/data/". gmdate("Y/m/d/", $ts) ."camera/$id/${id}_". gmdate("YmdHi", $ts) .".jpg";
    $fp5 = "/mesonet/ARCHIVE/data/". gmdate("Y/m/d/", $ts5) ."camera/$id/${id}_". gmdate("YmdHi", $ts5) .".jpg";
    $url5 = "http://mesonet.agron.iastate.edu/archive/data/". gmdate("Y/m/d/", $ts5) ."camera/$id/${id}_". gmdate("YmdHi", $ts5) .".jpg";

    if (is_file($fp)) $cameras[$id]["url"] = $url;
    else if (is_file($fp5)) $cameras[$id]["url"] = $url5;
    else $cameras[$id]["active"] = false;
 }
 
 if ($cameras[$id]["active"]){ 
  $cameras[$id]["num"] = intval(substr($id,5,3)); }
}/* End of while */

reset($cameras);

	$TITLE = "IEM | Web Cameras";
if (! $isarchive)
	$REFRESH = "<meta http-equiv=\"refresh\" content=\"${camera_refresh};\">";
    $THISPAGE = "webcam-still";
	include("$rootpath/include/header.php"); 
	include("$rootpath/include/forms.php"); 

$selback = Array("KELO" => "#fff", "KCCI" => "#fff", "KCRG" => "#fff");
$selback[$network] = "#ffcc99";
?>


<strong>Webcam Networks</strong>
<div style="width:775px; border: 1px dashed #ccc;">
<div style="float: left; width: 250px; text-align: center; border: 3px #eee solid; background: <?php echo $selback["KCCI"]; ?>;">
  <a href="camera.phtml?network=KCCI">KCCI-TV<br />Des Moines, IA</a>
</div>
<div style="float: left; width: 250px; text-align: center; border: 3px #eee solid; background: <?php echo $selback["KCRG"]; ?>;">
  <a href="camera.phtml?network=KCRG">KCRG-TV<br />Cedar Rapids, IA</a>
</div>
<div style="float: left; width: 250px; text-align: center; border: 3px #eee solid; background: <?php echo $selback["KELO"]; ?>;">
  <a href="camera.phtml?network=KELO">KELO-TV<br />Sioux Falls, SD</a>
</div>
<br clear="all" />
</div>


<?php 
  if ($network == "KCCI") { include("kccicam.php"); }
  elseif ($network == "KELO") { include("kelocam.php"); }
  elseif ($network == "KCRG") { include("kcrgcam.php"); }
?>

<?php include("$rootpath/include/footer.php"); ?>
