<?php 
require_once "../../config/settings.inc.php";
require_once "../../include/myview.php";
require_once "../../include/database.inc.php";

$t = new MyView();
$coopdb = iemdb("coop");

$t->thispage = "current-gs";
$t->title = "Current Growing Season Data";

$table = "";
$lkp = Array(
    "IA0200" => "Ames", "IA2203" => "Des Moines",
	"IA8706" => "Waterloo", "IA1319" => "Cedar Rapids",
	"IA2364" => "Dubuque", "IA2110" => "Decorah",
	"IA5230" => "Mason City", "IA7708" => "Sioux City",
    "IA7613" => "Shenandoah", "IA4585" => "Lamoni",
    "IA4705" => "Davenport");
$rs = pg_query($coopdb, "select o.station,
   sum(gdd50(o.high, o.low)) as ogdd50, sum(o.precip) as oprecip,
   sum(gdd50) as cgdd50, sum(c.precip) as cprecip,
   max(o.high) as maxtmpf, min(o.low) as mintmpf,
   avg( (o.high + o.low) / 2.0 ) as avgtmpf
  from alldata_ia o, climate51 c WHERE
   c.station in ('IA0200', 'IA1319', 'IA2203','IA8706', 'IA2364', 'IA2110',
    'IA5230', 'IA7708', 'IA7613', 'IA4585', 'IA4705')
   and o.station = c.station
   and day >= '".date("Y")."-05-01' and day < '".date("Y")."-10-01'
   and extract(doy from day) = extract(doy from valid)  GROUP by o.station
   ORDER by o.station ASC");
for($i=0;$row=@pg_fetch_array($rs,$i);$i++){
	$table .= sprintf("<tr style=\"background: %s;\"><th>%s</th><td>%.0f</td><td>%.0f</td><td>%.2f</td><td>%.2f</td><td>%.0f</td><td>%.0f</td><td>%.0f</td></tr>",
			($i % 2 == 0) ? "#eee": "#fff;", $lkp[$row["station"]], $row["ogdd50"], $row["cgdd50"], $row["oprecip"], $row["cprecip"],
			$row["maxtmpf"], $row["mintmpf"], $row["avgtmpf"]);
}

$d = date("d M Y", time() - 86400);
$y = date("Y");
$murl = "/climodat/monitor.php?sdate=05/01/${y}&amp;".
    "edate=12/31/${y}&amp;s[]=IA0200&amp;s[]=IA1319&amp;s[]=IA2203&amp;".
    "s[]=IA8706&amp;s[]=IA2364&amp;s[]=IA2110&amp;s[]=IA5230&amp;".
    "s[]=IA7708&amp;s[]=IA7613&amp;s[]=IA4585&amp;s[]=IA4705";
$t->content = <<<EOF

<h3>Selected Location Summary: 01 May thru {$d}</h3>

<p>These values are estimates based on the IEM's collection of various datasets.
Climatology is based on observations back to 1951.</p>

<p>There is an <a href="{$murl}"><span class="fa fa-refresh"></span> interactive version</a>
of this table available as well.</p>

<table cellpadding="2" cellspacing="0" border="1">
 <tr><th rowspan="2">Location</th><th colspan="2">Growing Degree Days</th>
  <th colspan="2">Precipitation</th>
  <th colspan="3">Temperature</th>
 </tr>
 <tr>
 <th>Observed</th><th>Climate</th>
 <th>Observed</th><th>Climate</th>
 <th>Highest</th><th>Lowest</th><th>Average</th>
 </tr>
{$table}
</table>

<h3>Data Applications</h3>
<ul>
	<li><a href="/GIS/apps/coop/gsplot.phtml">Maps and Data Download</a>
	<br />Accumulate Growing Degree Days, Stress Degree Days,
	and precipitation for any growing season of your choice.</li>
</ul>


<h3>Growing Degree Days</h3>
<ul>
 <li>(base=50) May 1 - Today Observations: <a href="/data/summary/gdd_may1.png">contour plot</a></li>
 <li>(base=60) May 1 - Today Observations: <a href="/data/summary/gdd_may1_6086.png">contour plot</a></li>
 <li>(base=65) May 1 - Today Observations: <a href="/data/summary/gdd_may1_6586.png">contour plot</a></li>
 <li>May 1 - Today Climatology: <a href="/data/summary/gdd_norm_may1.png">contour plot</a> or <a href="/data/summary/gdd_norm_may1_pt.png">value plot</a></li>
</ul>
EOF;
$t->render('full.phtml');
?>
