<?php
function listItem($url, $ltext, $name, $selected)
{
  if ($name != $selected)
    return "<li><a href=\"$url\">$ltext</a></li>\n";

  return "<li><a href=\"$url\"><strong style=\"color: #f00;\">$ltext</strong></a></li>\n";
}

?>
<div class="horiz-list" style="border: #bdf solid 2px;">
<ul style="background: #fff; margin: 2px; padding-left: 5px;">
 <li><strong style="color: #bdf;">Current Data:</strong></li>
<?php
  echo listItem($rooturl."/current/index.phtml", "Surface Data", "surface", $THISPAGE);
  echo listItem($rooturl."/current/radar.phtml", "RADAR & Satellite", "radar", $THISPAGE);
  echo listItem($rooturl."/current/severe.phtml", "Severe Weather", "severe", $THISPAGE);
  echo listItem($rooturl."/current/misc.phtml", "Advanced Products", "advanced", $THISPAGE);
  echo listItem($rooturl."/current/camera.phtml", "Web Cameras", "camera", $THISPAGE);
?>
</ul>
</div>

