<?php 
/*
 * Mainpage of currents for the website, kind of ugly, but it is OK
 */
require '../../config/settings.inc.php';
include_once('../../include/myview.php');

$t = new MyView();
$t->thispage = "current-products";
$t->title = "Current Products";

$daylink = sprintf("%s0000", date("Ymd"));
$mhourlink = gmdate("YmdH", time() -3600) ."00";
$t->content = <<<EOF

<div class="row">
<div class="col-md-4">

<h4>IEM Station Plot</h4>
<a href="/timemachine/#1.0"><img class="img-responsive" src="/data/mesonet.gif" /></a>

<h3 class="subtitle">Mesonet Plots</h3>
<ul>
 <li><a href="/timemachine/#1.0">Iowa Mesonet Plot</a> [<a href="loop.phtml?prod=mesonet">Loop</a>]</li>
 <li><a href="/timemachine/#4.0">Upper Mid-West</a> [<a href="loop.phtml?prod=mwmesonet">Loop</a>]</li>
</ul>


<h3 class="subtitle">Temperature</h3>
<ul>
 <li><a href="/timemachine/#63.0">12Z Low Temperature</a></li>
 <li><a href="/data/summary/iowa_asos_high.png">Today High Temperature</a></li>
</ul>

<h3 class="subtitle">NMQ Q2 Precipitation Plots</h3>
<p>These plots are from the <a href="http://nmq.ou.edu">National Mosaic QPE</a>
project providing precipitation estimates at a 5 minute and 1 km interval.
<ul>
  <li><a href="/timemachine/#44.{$mhourlink}">Current Precip Intensity</a></li>
  <li><a href="/timemachine/#45.{$mhourlink}">Today's Precip</a></li>
  <li>1 Hour Total (<a href="/data/iowa_q2_1h.png">Current</a> or <a href="../timemachine/#46.0">Archive</a> )</li>
  <li>3 Hour Total (<a href="/data/iowa_q2_3h.png">Current</a> or <a href="../timemachine/#47.0">Archive</a> )</li>
  <li>6 Hour Total (<a href="/data/iowa_q2_6h.png">Current</a> or <a href="../timemachine/#48.0">Archive</a> )</li>
</ul>



<h3 class="subtitle">External Website Resources:</h3>
<a href="http://www.rap.ucar.edu/weather/surface/">RAP Surface Page</a>

</div><div class="col-md-4">

		<h4>Current Temperatures</h4>
<a href="/data/iowa_tmpf.png"><img src="/data/iowa_tmpf.png" class="img-responsive"/></a>
<br />
		

<h3 class="subtitle">Single Variable Plots</h3>
<ul>  <li><a href="/data/mesonet_altm.gif">Altimeter</a></li>
  <li><a href="/data/ceil.gif">Ceiling</a></li>
  <li><a href="/data/heat.gif">Heat Index</a></li>
  <li><a href="/data/relh.gif">Relative Humidity</a></li>
  <li><a href="/timemachine/#24.0">Visibility</a></li>

</ul>

<h3 class="subtitle">Precipitation</h3>
<ul>
  <li><a href="/timemachine/#82.0">Iowa Flood Center RADAR Estimates</a></li>
  <li><a href="/timemachine/#37.0">Iowa Precipitation Contour [COOP]</a></li>
  <li><a href="/timemachine/#38.0">Midwest Precipitation Contour [COOP]</a></li>
  <li><a href="/timemachine/#39.{$mhourlink}">Iowa StageIV Hourly Estimate</a></li>
  <li><a href="/timemachine/#40.{$mhourlink}">Midwest StageIV Hourly Estimate</a></li>
  <li><a href="/timemachine/#41.{$daylink}">Iowa StageIV Daily Estimate</a></li>
  <li><a href="/timemachine/#42.{$daylink}">Midwest Daily Estimate</a></li>
  <li><a href="/timemachine/#43.{$daylink}">US StageIV Daily Estimate</a></li>

  <li><a href="/data/1hprecip.gif">ASOS + AWOS (Last Hour)</a></li>
  <li><a href="/data/summary/today_prec.png">ASOS + AWOS (Today)</a></li>
</ul>

</div><div class="col-md-4">

		<h4>Rainfall Today</h4>
<a href="/timemachine/#45.{$daylink}"><img src="/data/iowa_q2_1d.png" class="img-responsive"/></a>
<br />
		
<h3>Wind Plots</h3>
<ul>
  <li><a href="/timemachine/#60.{$mhourlink}">Wind Power Potential</a></li>
  <li><a href="/data/wcht.gif">Wind Chill Index</a></li>
  <li><a href="/timemachine/#16.{$daylink}">Wind Gust Today</a></li>
</ul>


<h3 class="subtitle">Gridded Surface Plots:</h3>
<table>
<tr><td>
  <br><a href="/data/surfaceTW0.gif">Temps & Winds</a></td><td>
         <br><a href="SFloop.php?product=TW">Loop</a></td></tr>
<tr><td>
  <a href="/data/surfaceDW0.gif">Dew Points & Winds</a></td><td>
         <a href="SFloop.php?product=DW">Loop</a></td></tr>
<tr><td>
  <a href="/data/surfaceTE0.gif">Theta E & Winds</a></td><td>
         <a href="SFloop.php?product=TE">Loop</a></td></tr>
<tr><td>
  <a href="/data/surfaceMD0.gif">Moisture Divergence</a></td><td>
         <a href="SFloop.php?product=MD">Loop</a></td></tr>
<tr><td>
  <a href="/data/surfaceFRNT0.gif">Frontogensis</a></td><td>
         <a href="SFloop.php?product=FRNT">Loop</a></td></tr>
<tr><td>
  <a href="/data/surfaceDIV0.gif">Divergence</a></td><td>
         <a href="SFloop.php?product=DIV">Loop</a></td></tr>
</table>



<p><h3 class="subtitle">Soundings:</h3>
<a href="http://www.rap.ucar.edu/weather/upper/sla_wp.gif">Slater Profiler</a>
<br /><a href="http://www.rap.ucar.edu/weather/upper/dvn.gif">Davenport</a>
<br><a href="http://www.rap.ucar.edu/weather/upper/oax.gif">Omaha</a>
<br><a href="http://www.rap.ucar.edu/weather/upper/mpx.gif">Minneapolis</a>
<br><a href="http://www.rap.ucar.edu/weather/upper/top.gif">Topeka</a>
<br /><a href="http://www.uni.edu/storm/">Profiling Radiometer @UNI</a>

		</div>
</div>
EOF;
$t->render('single.phtml');
 ?>
