<?php 
include("../../config/settings.inc.php");
	$THISPAGE = "current-products";
	$TITLE = "IEM | Current Data";
	include("$rootpath/include/header.php"); 
?>

<table width="800px">
<tr><th>IEM Station Plot</th><th>Current Temperatures</th><th>Rainfall Today</th></tr>
<tr>
<td><a href="<?php echo $rooturl; ?>/timemachine/#1.0"><img src="../data/mesonet.gif" border="0" width="275"/></a></td>
<td><a href="<?php echo $rooturl; ?>/data/iowa_tmpf.png"><img src="../data/iowa_tmpf.png" border="0" width="275"/></a></td>
<td><a href="<?php echo $rooturl; ?>/data/summary/today_prec.png"><img src="../data/summary/today_prec.png" border="0" width="275"/></a></td>
</tr>
</table>



<table border=0 width=780px>
<tr><td valign="top">

<h3 class="subtitle">Mesonet Plots</h3>
<ul>
 <li><a href="<?php echo $rooturl; ?>/timemachine/#1.0">Iowa Mesonet Plot</a> [<a href="loop.phtml?prod=mesonet">Loop</a>]</li>
 <li><a href="<?php echo $rooturl; ?>/timemachine/#4.0">Upper Mid-West</a> [<a href="loop.phtml?prod=mwmesonet">Loop</a>]</li>
</ul>


<h3 class="subtitle">Temperature</h3>
<ul>
 <li><a href="<?php echo $rooturl; ?>/data/summary/iowa_asos_12z_low.png">12Z Low Temperature</a></li>
 <li><a href="<?php echo $rooturl; ?>/data/summary/iowa_asos_high.png">Today High Temperature</a></li>
</ul>
<h3 class="subtitle">Precipitation</h3>
<ul>
    <li><a href="<?php echo $rooturl; ?>/timemachine/#37.0">Iowa Precipitation Contour [COOP]</a></li>
    <li><a href="<?php echo $rooturl; ?>/timemachine/#38.0">Midwest Precipitation Contour [COOP]</a></li>
    <li><a href="<?php echo $rooturl; ?>/timemachine/#39.0">Iowa StageIV Hourly Estimate</a></li>
    <li><a href="<?php echo $rooturl; ?>/timemachine/#40.0">Midwest StageIV Hourly Estimate</a></li>
  <li><a href="<?php echo $rooturl; ?>/data/1hprecip.gif">ASOS + AWOS (Last Hour)</a></li>
  <li><a href="<?php echo $rooturl; ?>/data/summary/today_prec.png">ASOS + AWOS (Today)</a></li>
</ul>

<h3 class="subtitle">External Website Resources:</h3>
<a href="http://www.rap.ucar.edu/weather/surface/">RAP Surface Page</a>

</td><td valign="top">

<h3 class="subtitle">Single Variable Plots</h3>
<ul>  <li><a href="<?php echo $rooturl; ?>/data/mesonet_altm.gif">Altimeter</a></li>
  <li><a href="<?php echo $rooturl; ?>/data/ceil.gif">Ceiling</a></li>
  <li><a href="<?php echo $rooturl; ?>/data/heat.gif">Heat Index</a></li>
  <li><a href="<?php echo $rooturl; ?>/data/relh.gif">Relative Humidity</a></li>
  <li>Visibility: <a href="<?php echo $rooturl; ?>/data/vsby.gif">plot</a> , <a href="<?php echo $rooturl; ?>/data/vsby_contour.png">contour</a></li>
  <li><a href="<?php echo $rooturl; ?>/data/wcht.gif">Wind Chill Index</a></li>
  <li><a href="<?php echo $rooturl; ?>/timemachine/#16.<?php echo date('Ymd');?>0000">Wind Gust Today</a></li>
</ul>


<h3 class="subtitle">Temporal Change Plots</h3>
<ul>
  <li><a href="<?php echo $rooturl; ?>/GIS/apps/delta/plot.php?i=15m">15min Pressure Change</a></li>
  <li><a href="<?php echo $rooturl; ?>/GIS/apps/delta/plot.php">1 hour Pressure Change</a></li>
</ul>

</td><td valign="top">


<h3 class="subtitle">Gridded Surface Plots:</h3>
<table>
<tr><td>
  <br><a href="/data/surfaceTW0.gif">Temps & Winds</a></td><td>
         <br><a href="SFloop.php?product=TW">Loop</a></td></tr>
<tr><td>
  <a href="/data/surfaceDW0.gif">Dew Points & Winds</a></td><td>
         <a href="SFloop.php?product=DW">Loop</a></td></tr>
<tr><td>
  <a href="/data/surfaceTE0.gif">Theta E & Winds</a></td><td>
         <a href="SFloop.php?product=TE">Loop</a></td></tr>
<tr><td>
  <a href="/data/surfaceMD0.gif">Moisture Divergence</a></td><td>
         <a href="SFloop.php?product=MD">Loop</a></td></tr>
<tr><td>
  <a href="/data/surfaceFRNT0.gif">Frontogensis</a></td><td>
         <a href="SFloop.php?product=FRNT">Loop</a></td></tr>
<tr><td>
  <a href="/data/surfaceDIV0.gif">Divergence</a></td><td>
         <a href="SFloop.php?product=DIV">Loop</a></td></tr>
</table>



<p><h3 class="subtitle">Soundings:</h3>
<a href="http://www.rap.ucar.edu/weather/upper/sla_wp.gif">Slater Profiler</a>
<br /><a href="http://www.rap.ucar.edu/weather/upper/dvn.gif">Davenport</a>
<br><a href="http://www.rap.ucar.edu/weather/upper/oax.gif">Omaha</a>
<br><a href="http://www.rap.ucar.edu/weather/upper/mpx.gif">Minneapolis</a>
<br><a href="http://www.rap.ucar.edu/weather/upper/top.gif">Topeka</a>

</td></tr>
</table>

</div>


<?php include("$rootpath/include/footer.php"); ?>
