<?php
require_once "../../config/settings.inc.php";
define("IEM_APPID", 116);
require_once "../../include/myview.php";

$t = new MyView();
$t->refresh = 60;
$t->title = "Iowa State Webcams";

$cb = rand(0, 100000);

$t->content = <<<EOM
<style>
.nopadding {
   padding: 0 !important;
   margin: 0 !important;
}
</style>

<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="/projects/webcam.php">IEM Webcam Project</a></li>
    <li class="breadcrumb-item active" aria-current="page">ISU Webcams</li>
  </ol>
</nav>

<p>This page provides the most recently cached webcam image by the IEM.</p>

<div class="row">
  <div class="col-md-6">
<h4>AEA Farm</h4>
<img src="/data/camera/stills/KCCI-027.jpg?{$cb}" class="img-fluid"></div>
<div class="col-md-6">
<h4>Memorial Union</h4>
<img src="/data/camera/stills/ISUC-003.jpg?{$cb}" class="img-fluid"></div>
</div>

<h4>Curtis Hall</h4>

<div class="row">
  <div class="col-md-4 nopadding"><img src="/data/camera/stills/ISUC-004.jpg?{$cb}" class="img-fluid"></div>
  <div class="col-md-4 nopadding"><img src="/data/camera/stills/ISUC-005.jpg?{$cb}" class="img-fluid"></div>
  <div class="col-md-4 nopadding"><img src="/data/camera/stills/ISUC-006.jpg?{$cb}" class="img-fluid"></div>
</div>

EOM;
$t->render('full.phtml');
