<?php
include("../../config/settings.inc.php");
include("../../include/myview.php");
include("../../include/forms.php");
$t = new MyView();
 /* Script to generate a loop of whatever */
 $prod = isset($_GET['prod']) ? $_GET['prod'] : 'mesonet';
 $java = isset($_GET['java']) ? $_GET['java'] : 'applet';
 $frames = isset($_GET['frames']) ? $_GET['frames'] : 10;

$products = Array(
 "mesonet" => Array("aformat" => 'mesonet_%H00.gif',
		"tint" => 3600, "width" => 900, "height" => 700, "minute" => 8,
		"name" => "Iowa Mesonet Plot"),
 "mwmesonet" => Array("aformat" => 'MWmesonet_%H00.gif',
		"tint" => 3600, "width" => 900, "height" => 700, "minute" => 8,
		"name" => "Midwest Mesonet Plot"),
);

$baseurl2 = '/archive/data/';
$files = "";
$hrefs = "";
$loopendts = time();
$m = date("i");
if ($m < $products[$prod]["minute"])  $loopendts = time() - 3600;

$q = $frames - 1;
for($i=$q; $i >= 0; $i--)
{
	$ts = $loopendts - ($products[$prod]["tint"] * $i);
	$gts = strtotime( gmdate("Y-m-d H:i", $ts) );
	$u = $baseurl2 . strftime("%Y/%m/%d/". $products[$prod]["aformat"], $gts);
	$hrefs .= "<br><img src=\"$u\">";
	$files .= $u .","; 
}

/* ========================================================= */

 $t->title = "Product Looper"; 
 $ar = Array(
 		"applet" => "Java Applet",
 		"none" => "List Images"
 );
 $loopselect = make_select("java", $java, $ar);
 
 $prodselect = "<select name=\"prod\">";
 reset($products);
  while( list($k, $v) = each($products) )
 {
 	$prodselect .= "<option value=\"$k\" ";
 	if ($prod == $k) $prodselect .= " SELECTED ";
 	$prodselect .= ">". $products[$k]["name"] ."\n";
 }
 $prodselect .= "</select>";
 
if ($java == "applet") { 
	$height = $products[$prod]["height"] + 100;
 $control = <<<EOF
 <applet codebase="/current/class/"
 	code="AniS.class" width="{$products[$prod]["width"]}" height="{$height}" 
 	alt="You must enable Java in your browser to view the loop">
 	<param name="controls" value="startstop, looprock, step, speed, toggle,zoom">
 	<param name="rate" value="80">
 	<param name="no_enh" value="true">
 	<param name="pause_percent" value="800">
 	<param name="filenames" value="{$files}">
 </applet>
EOF;
} else { 
 	$control =  $hrefs;
 } 
 
$t->content = <<<EOF
<h3>IEM Product Looper</h3>

<div style="padding: 10px; border: 2px solid #000;">

<form method="GET" action="loop.phtml">
<table style="padding: 2px; border:0px; margin: 2px;">
<tr>
 <th>Loop Mode:</th>
 <th>Select Product:</th>
 <th>Frames:</th>
 <td rowspan="2"><input type="submit" value="Generate Loop"></td></tr>

<tr>
 <td>{$loopselect}</td>
 <td>{$prodselect}</td>
<td><input type="text" name="frames" value="{$frames}" size="3"></tr></table>


</form>

{$control}

</div>
EOF;
$t->render('single.phtml');
?>
