<?php
 include("../../config/settings.inc.php");
 $uri = 'mcview.phtml';
 include("$rootpath/include/forms.php");

 /** Import our variables */
 $prod = isset($_GET["prod"]) ? $_GET["prod"] : "comprad";
 $java = isset($_GET["java"]) ? $_GET["java"] : "applet";
 $mode = isset($_GET["mode"]) ? $_GET["mode"] : "realtime";
 $frames = isset($_GET["frames"]) ? $_GET["frames"] : 13;
 $interval = isset($_GET["interval"]) ? $_GET["interval"]: 5;

/* Lets see what the form is set to */
 $year = isset($_GET["year"]) ? $_GET["year"] : date("Y");
 $month = isset($_GET["month"]) ? $_GET["month"] : date("m");
 $day = isset($_GET["day"]) ? $_GET["day"] : date("d");
 $hour = isset($_GET["hour"]) ? $_GET["hour"] : date("h");
 $minute = isset($_GET["minute"]) ? $_GET["minute"] : date("i");

 /** Acceptable number of frames are between 1 and 100 */
 if (intval($frames) > 100 || intval($frames) < 1) $frames = 13;
 /** Acceptable interval is between 5 and 60 */
 if (intval($interval) > 60 || intval($interval) < 5) $interval = 5;

 $astart = Array("comprad" => mktime(0,0,0,1,1,2000),
         "usrad" => mktime(0,0,0,1,1,2000),
         "ictrad" => mktime(0,0,0,1,1,2000),
         "hunrad" => mktime(0,0,0,1,1,2000),
         "sdrad" => mktime(0,0,0,1,1,2000),
         "sel0rad" => mktime(13,35,0,11,2,2004),
         "sel1rad" => mktime(13,35,0,11,2,2004),
         "sel2rad" => mktime(13,35,0,11,2,2004),
         "sel3rad" => mktime(13,35,0,11,2,2004),
         "sel4rad" => mktime(13,35,0,11,2,2004),
         "sel5rad" => mktime(13,35,0,11,2,2004),
         "sel6rad" => mktime(13,35,0,11,2,2004),
         "sel7rad" => mktime(13,35,0,11,2,2004),
         "sel8rad" => mktime(13,35,0,11,2,2004),
         "sel9rad" => mktime(13,35,0,11,2,2004),
         "lotrad" => mktime(0,0,0,1,1,2000) );

 $now = mktime() - 120;
 $aend = mktime();

/* Figure when the lapse starts! $ts */
if ($mode == "realtime"){
  $ts = $now - ($frames -1) * (intval($interval) * 60);
} else { /* Historical */
  $ots = mktime($hour, $minute, 0, $month, $day, $year);
  /* Make sure archive request is not sooner than archive start */
  if ($ots < $astart[$prod])  
    $ts = $astart[$prod];
  /* Make sure archive request is not in the future */
  else if ($ots > $now)    
    $ts = $now - (($frames) * (intval($interval) * 60) ) ;
  /* Set the timestamp */
  else 
    $ts = $ots;
}

// This is what we set the form time to
$formts = $ts;

$ar = localtime($ts);
$m = $ar[1];

if ($m >= 55) $ma = "55";
else if ($m >= 50) $ma = "50";
else if ($m >= 45) $ma = "45";
else if ($m >= 40) $ma = "40";
else if ($m >= 35) $ma = "35";
else if ($m >= 30) $ma = "30";
else if ($m >= 25) $ma = "25";
else if ($m >= 20) $ma = "20";
else if ($m >= 15) $ma = "15";
else if ($m >= 10) $ma = "10";
else if ($m >= 5) $ma = "05";
else if ($m >= 0) $ma = "00";

$diff = $m - intval($ma);

$hour  = date("H", $formts);
$day   = date("d", $formts);
$month = date("m", $formts);
$year  = date("Y", $formts);
$minute = $ma;

/* Our actual loop start time! */
$loopts = $ts - ($diff * 60);
$switchts = mktime(0,0,0, 8,22,2004);
$lwidth = 900;
$lheight = 700;
if ($loopts > $switchts){
  $lwidth = 650;
  $lheight =550;
}

$files = "";

$images = Array();
$radtimes = Array();
for ($i=0; $i < intval($frames); $i++){
  $myuri = "$rooturl/archive/data/". gmdate('Y/m/d/', $loopts + ($i * (intval($interval) * 60)) ) ."$prod/n0r_". gmdate('Ymd_Hi', $loopts + ($i * (intval($interval) * 60)) ) .".png";
  $myhref = "$rooturl/archive/data/". gmdate('Y/m/d/', $loopts + ($i * (intval($interval) * 60)) ) ."GIS/uscomp/n0r_". gmdate('YmdHi', $loopts + ($i * (intval($interval) * 60)) ) .".png";
  $gisbase = "$rooturl/archive/data/". gmdate('Y/m/d/', $loopts + ($i * (intval($interval) * 60)) ) ."GIS/uscomp/";
  $files .= $myuri .",";
  $images[] = $myuri;
  $radtimes[] = $loopts + ($i * (intval($interval) * 60));
}

/* We finally start output */

$HEADEXTRA = "<script LANGUAGE=\"JavaScript1.2\" type=\"text/javascript\">
//<!--

function switchToArchiveMode()
{
  document.controls.mode.selectedIndex = 1;
}

-->
</script>";
  if ($mode == "realtime") $REFRESH = "<meta http-equiv=\"refresh\" content=\"300; URL=$uri?java=$java&frames=$frames&interval=$interval&prod=$prod\">";
  $TITLE = "Current & Historical IEM NEXRAD Composite Loop";
  $THISPAGE = "current-radar";
  include("$rootpath/include/header.php");
?>
<a href="<?php echo $rooturl; ?>/current/">Current Data</a> &nbsp; <b>></b> &nbsp; <b>IEM NEXRAD Composite</b>
&nbsp; &nbsp; <a href="<?php echo $uri; ?>">Reset Application for a Current Loop</a>

<br><form method="GET" action="<?php echo $uri; ?>" name="controls">

<table cellpadding=2 cellspacing=0>
 <tr><td valign="top" style="width: 170px;">


<div class="iembox" style="width: 200px;">
<h4>Composite Product:</h4>
<select name="prod">
  <option value="comprad" <?php if ($prod == "comprad") echo "SELECTED"; ?>>A1. Iowa (Default)</option>
  <option value="usrad" <?php if ($prod == "usrad") echo "SELECTED"; ?>>A1. United States</option>
  <option value="hunrad" <?php if ($prod == "hunrad") echo "SELECTED"; ?>>A1. Huntsville, AL</option>
  <option value="lotrad" <?php if ($prod == "lotrad") echo "SELECTED"; ?>>A1. North Illinois</option>
  <option value="sdrad" <?php if ($prod == "sdrad") echo "SELECTED"; ?>>A1. South Dakota</option>
  <option value="ictrad" <?php if ($prod == "ictrad") echo "SELECTED"; ?>>A1. Wichita, KS</option>
<?php for ($i=0; $i<10; $i++){
  echo "<option value=\"sel${i}rad\"";
  if ($prod == "sel${i}rad") echo " SELECTED ";
  echo ">A3. Watch (SEL${i})</option>"; 
} ?>
</select>

<br />(<i>Archive Begins @</i>)
<br /><b>Al.</b> 1 Jan 2000
<br /><b>A2.</b> 21 Sep 2005

<h4>Display Tool:</h4>
<select name="java">
  <option value="applet" <?php if ($java == "applet") echo "SELECTED"; ?>>Java Applet</option>
  <option value="script" <?php if ($java == "script") echo "SELECTED"; ?>>Java Script</option>
  <option value="none" <?php if ($java == "none") echo "SELECTED"; ?>>List Images</option>
</select>

<h4>Mode:</h4>
<select name="mode">
  <option value="realtime" <?php if ($mode == "realtime") echo "SELECTED"; ?>>RealTime
  <option value="archive" <?php if ($mode == "archive") echo "SELECTED"; ?>>Archived
</select>

<h4>Frames:</h4>
<input type="text" size="3" name="frames" value="<?php echo $frames; ?>">

<h4>Frame Interval:</h4>
<select name="interval">
  <option value="5" <?php if ($interval == 5) echo "SELECTED"; ?>>5 min (DEFAULT)
  <option value="10" <?php if ($interval == 10) echo "SELECTED"; ?>>10 min
  <option value="15" <?php if ($interval == 15) echo "SELECTED"; ?>>15 min
  <option value="20" <?php if ($interval == 20) echo "SELECTED"; ?>>20 min
  <option value="30" <?php if ($interval == 30) echo "SELECTED"; ?>>30 min
  <option value="60" <?php if ($interval == 60) echo "SELECTED"; ?>>60 min
</select>

<h4>Date:</h4>
<?php 
  $start = intval(2000);
  $now = time();
  $tyear = strftime("%Y", $now);
  echo "<select name='year' onChange=\"javascript: switchToArchiveMode(); \">\n";
  for ($i=$start; $i<=$tyear;$i++) {
    echo "<option value='".$i ."' ";
    if ($i == intval($year)) echo "SELECTED";
    echo ">". $i ."\n";
  }
  echo "</select>\n";

  echo "<select name='month' onChange=\"javascript: switchToArchiveMode(); \">\n";
  for ($i=1; $i<=12;$i++) {
    $ts = mktime(0,0,0,$i,1,0);
    echo "<option value='".$i ."' ";
    if ($i == intval($month)) echo "SELECTED";
    echo ">". strftime("%b" ,$ts) ."\n";
  }
  echo "</select>\n";

  echo "<select name='day' onChange=\"javascript: switchToArchiveMode(); \">\n";
  for ($k=1;$k<32;$k++){
    echo "<option value=\"".$k."\" ";
    if ($k == (int)$day){
      echo "SELECTED";
    }
    echo ">".$k."\n";
  }
  echo "</select>\n";

?>
<h4>Time:</h4>
<?php

  echo "<select name='hour'  onChange=\"javascript: switchToArchiveMode(); \">\n";
  for ($i=0; $i<24;$i++) {
    $ts = mktime($i,0,0,1,1,0);
    echo "<option value='".$i."' ";
    if ($i == intval($hour)) echo "SELECTED";
    echo ">". strftime("%I %p" ,$ts) ."\n";
  }
  echo "</select>\n";

  echo "<select name='minute' onChange=\"javascript: switchToArchiveMode(); \">\n";
  for ($i=0; $i<60;$i=$i+5) {
    echo "<option value='".$i."' ";
    if ($i == intval($minute)) echo "SELECTED";
    echo sprintf(">%02d\n", $i );
  }
  echo "</select>\n";

?>

<p><input type="submit" value="Generate Loop"> 

<h4>Related Links:</h4> 
<a href="<?php $rooturl; ?>/GIS/apps/rview/warnings.phtml">Interactive RADAR</a>
<br /><a href="<?php $rooturl; ?>/cow/">Warning Verification</a>
</div>
</form>
</td><td>

<?php if ($mode == "realtime") echo " &nbsp; <b>REAL-TIME mode:</b> Will refresh in 5 minutes"; ?> 

<?php if ($java == "applet") { ?>
<applet codebase="class/" code="AniS.class" width="<? echo $lwidth; ?>" height="<?php echo $lheight; ?>" alt="You must enable Java in your browser to view the radar loop">
 <param name="controls" value="startstop, looprock, step, speed, toggle, zoom">
 <param name="rate" value="80">
 <PARAM name="no_enh" value="true">
 <param name="pause_percent" value="800">
 <param name="filenames" value="<?php echo $files; ?>">
</applet>
<?php } if ($java == "script") { ?>
<script LANGUAGE="JavaScript1.2" type="text/javascript">
//<!--
modImages = new Array();
<?php
 $i = 0;
 reset($images);
 while ( list($key,$val) = each($images) ){
   echo "modImages[$i] = \"". $images[$i] ."\";\n";
   $i++;
 } ?>
first_image = 1;
last_image = <?php echo sizeof($images); ?>;
current_image = first_image;
-->
</script>
<script language="JavaScript" src="/js/animation.js"></script>
<img NAME="animation" SRC="<?php echo $images[0]; ?>" ALT="Image" border="2" />
                                                                                
  <form METHOD="POST" NAME="control_form">
<a HREF="JavaScript: func()" onClick="change_mode(1);reverse()"><img BORDER=0 SRC="/images/rev_button.gif" ALT="REV"></a>
<a HREF="JavaScript: func()" onClick="stop()"><img BORDER=0 SRC="/images/stp_button.gif" ALT="STOP"></a>
<a HREF="JavaScript: func()" onClick="change_mode(1);fwd()"><img BORDER=0 SRC="/images/fwd_button.gif" ALT="FWD"></a>
  <font SIZE=-1 COLOR="#3300CC">Frame No:</font>
  <input TYPE="text" NAME="frame_nr" VALUE=9 SIZE="2" onFocus="this.select()" onChange="go2image(this.value)"></input>
  </form>
<script LANGUAGE="JavaScript1.2" type="text/javascript">
//<!--
launch();
-->
</script>
<?php } if ($java == "none") { 
 reset($images);
 while ( list($key,$val) = each($images) ){
   echo "<p><img src=\"". $val ."\">\n";
 }
}
?>

</td></tr></table>

<p><b>GIS NEXRAD layers</b>
<br />The NEXRAD layer used in these images are available in a georeferenced 
RASTER format. You will need this <a href="/data/gis/images/4326/USCOMP/n0r_0.tfw">this world file</a> to correctly georeference them.  The projection of 
these images is geographic NAD83 (<i>unprojected</i>).  You will need to 
rename the world file to match the filename of the RADAR layer before loading
into your GIS.
<br>
<ul>
<?php
foreach ($radtimes as $value ){
  $myhref = "$rooturl/archive/data/". gmdate('Y/m/d/',$value ) ."GIS/uscomp/n0r_". gmdate('YmdHi', $value ) .".png";
  echo "<li><a href='$myhref'>$myhref</a> (<a href='$rooturl/request/gis/n0r2gtiff.php?dstr=". gmdate('YmdHi', $value) ."'>GeoTiff</a>)</li>\n";
}
?>
</ul>

<?php include("$rootpath/include/footer.php"); ?>
