<?php 
 include("../../config/settings.inc.php");
	$page = "current";
	$TITLE = "IEM | Current Data";
	include("$rootpath/include/header.php"); 
?>

<div id="iem-section">
<center><table>
<tr><th><a href="index.phtml">Surface Data</a></th>
<th><a href="radar.phtml">RADAR/Sat Data</a></th>
<th>Advanced Met Plots</th>
<th><a href="camera.phtml">Web Cameras</a></th>
<th>&nbsp;</th>
</tr></table></center></div>

<div class="text">
<!-- Begin two column for gridded data and UA -->
<table class="page" cellpadding="10">
<tr><td class="top" valign="top">

<h3 class="subtitle">Gridded Surface Plots:</h3>
<table>
<tr><td>
  <br><a href="/data/0surfaceTW.gif">Temps & Winds</a></td><td> 
         <br><a href="SFloop.php?product=TW">Loop</a></td></tr>
<tr><td>
  <a href="/data/0surfaceDW.gif">Dew Points & Winds</a></td><td> 
         <a href="SFloop.php?product=DW">Loop</a></td></tr>
<tr><td>
  <a href="/data/0surfaceTE.gif">Theta E & Winds</a></td><td>
         <a href="SFloop.php?product=TE">Loop</a></td></tr>
<tr><td>
  <a href="/data/0surfaceMD.gif">Moisture Divergence</a></td><td>
         <a href="SFloop.php?product=MD">Loop</a></td></tr>
<tr><td>
  <a href="/data/0surfaceFRNT.gif">Frontogensis</a></td><td>
         <a href="SFloop.php?product=FRNT">Loop</a></td></tr>
<tr><td>
  <a href="/data/0surfaceDIV.gif">Divergence</a></td><td>
         <a href="SFloop.php?product=DIV">Loop</a></td></tr>
</table>


</td><td valign="top">
<h3 class="subtitle">Other Data Links:</h3><br />
<a href="http://www.rap.ucar.edu/weather/upper/sla_wp.gif">Slater Profiler</a>
<br><a href="http://www.rap.ucar.edu/weather/surface/">RAP Surface Page</a>

<p><h3 class="subtitle">Soundings:</h3><br>
<a href="http://www.rap.ucar.edu/weather/upper/dvn.gif">Davenport</a>
<br><a href="http://www.rap.ucar.edu/weather/upper/oax.gif">Omaha</a>
<br><a href="http://www.rap.ucar.edu/weather/upper/mpx.gif">Minneapolis</a>
<br><a href="http://www.rap.ucar.edu/weather/upper/top.gif">Topeka</a>

</td></tr>
</table></div>


<?php include("$rootpath/include/footer.php"); ?>
