<?php 
include("../../config/settings.inc.php");
include("../../include/myview.php");
$t = new MyView();
define("IEM_APPID", 72);
$t->title = "Current Monthly Plots";
$t->thispage = "current-month";

$d = date("F");
$t->content = <<<EOF
<h4>Temperature</h4>
<ul>
<li><a href="/data/summary/mon_mean_T.png">Average Temperature</a>[ASOS/AWOS]</li>
</ul>

<h4>Precipitation</h4>
<ul>
<li><a href="/data/summary/month_prec.png">Precip Accum</a>[ASOS/AWOS]</li>
<li><a href="/data/coopMonthPlot.png">Precip Accum</a>[COOP]</li>
<li><a href="/plotting/month/rainfall.phtml">Plots of Monthly Rainfall</a></li>
<li><a href="/AWOS/reports/mon_prec.php">AWOS Monthly Totals</a></li>
<li><a href="/ASOS/reports/mon_prec.php">ASOS Monthly Totals</a></li>
<li><a href="/timemachine/#62.0">Iowa MRMS Q3 Total Precipitation</a></li>
  <li><a href="/timemachine/#58.0">Iowa Precipitation Analysis</a>
	<br />Contour 
	plot of analyzed precipitation for this month and previous months back
	to 1893.</li>
</ul>

<h4>Snowfall</h4>
<ul>
<li><a href="/data/coopMonthSPlot.gif">Snowfall this month</a>[COOP]</li>
</ul>

<h4>Winds</h4>
<ul>
<li><a href="/sites/windrose.phtml?station=DSM&network=IA_ASOS">Wind Roses</a></li>
</ul>

<h4>GDD</h4>
<ul>
<li><a href="/data/summary/gdd_mon.png">{$d} Accumulated Growing Degree Days (base=50)</a></li>
</ul>

<h4>SDD</h4>
<ul>
<li><a href="/data/summary/sdd_mon.png">{$d} Accumulated Stress Degree Days (base=86)</a></li>
</ul>
EOF;
$t->render('single.phtml');
?>
