<?php
include("../../config/settings.inc.php");

$REFRESH = "<meta http-equiv=\"refresh\" content=\"300; URL=http://mesonet.agron.iastate.edu/current/mwcomp.phtml\">";
$TITLE = "IEM | Iowa NEXRAD + Warnings";
  include("$rootpath/include/header.php");?>

<a href="radar.phtml">Current RADAR Products</a>
&nbsp; <b>|</b> &nbsp; <a href="mcview.phtml">Loop RADAR</a>
&nbsp; <b>|</b> &nbsp; <a href="uscomp.phtml">Switch to US View</a>
&nbsp; <b>|</b> &nbsp; <a href="<?php echo $rooturl; ?>/GIS/apps/rview/warnings.phtml">Current Warnings</a>

<br /><img src="<?php echo $rooturl; ?>/data/mwcomp.png?<?php echo time(); ?>">

<br /><i>(Image refreshes every 5 minutes)</i>
 
<?php include("$rootpath/include/footer.php"); ?>


