<?php 
    include("../../config/settings.inc.php");
	$THISPAGE = "current-radar";
	$TITLE = "IEM | Current RADAR Page";
	$HEADEXTRA = '<script language="JavaScript">

function changeSite(newSite, newSname) {

	document.myForm.sname.value = newSname ;
	document.myForm.site.value = newSite ;

} // End of changeSite

</script>';
include("$rootpath/include/header.php");
?>


<div id="iem-radar"><div class="text">
<p><table><tr><td class="heading" colspan="2">RADAR Data Selector</td></tr>

<tr><td valign="top">
<br><img src="<?php echo $rooturl; ?>/GIS/apps/radar/mwmosaic.php" USEMAP="#mymap">

<MAP NAME="mymap">
<AREA SHAPE="POLY" COORDS="109,216,187,214,184,331,74,290" 
  HREF="javascript:changeSite('EAX', 'Pleasant Hill, MO');">
<AREA SHAPE="POLY" COORDS="40,145,115,165,115,215,104,215,98,233,61,232" 
  HREF="javascript:changeSite('OAX', 'Omaha, NE');">
<AREA SHAPE="POLY" COORDS="35,90,101,93,117,112,116,160,13,140" 
  HREF="javascript:changeSite('FSD', 'Sioux Falls, SD');">
<AREA SHAPE="POLY" COORDS="117,128,116,213,178,212,178,125" 
  HREF="javascript:changeSite('DMX', 'Des Moines, IA');">
<AREA SHAPE="POLY" COORDS="88,39,214,48,150,127,121,127,101,92,81,90" 
  HREF="javascript:changeSite('MPX', 'Minneapolis, MN');">
<AREA SHAPE="POLY" COORDS="215,54,155,121,178,122,182,150,248,149" 
 HREF="javascript:changeSite('ARX', 'LaCrosse, WI');">
<AREA SHAPE="POLY" COORDS="180,152,180,213,190,212,191,223,249,222,249,150" 
 HREF="javascript:changeSite('DVN', 'Davenport, IA');">
</MAP>

<p><a href="javascript:changeSite('UDX', 'Rapid City, SD');">Rapid City</a> and
<a href="javascript:changeSite('ABR', 'Aberdeen, SD');">Aberdeen</a> are also available.

<p><b>Time composites:</b>
<ul>
 <li><a href="<?php echo $rooturl; ?>/timemachine/#27.<?php echo gmdate("Ymd", time() - 86400); ?>0000">Yesterday (GMT) CONUS</a></li>
 <li><a href="<?php echo $rooturl; ?>/timemachine/#26.<?php echo gmdate("Ymd", time() - 86400); ?>0000">Yesterday (GMT) Iowa</a></li>
</ul>

</td><td valign="top">

<form name="myForm" action="raddisplay.phtml">

<br><i>Enter or select NEXRAD<br>
 by clicking on the map:</i><br>
<input type="text" name="site" size=3 maxsize=3>
<input type="text" name="sname">

<p>Select Product:<br>
<select name="prod">
  <option value="N0R">Base Reflectivity</option>
  <option value="N0R_loop">Base Reflectivity Loop (Java Applet)</option>
  <option value="N0R_loop_nj">Base Reflectivity Loop (JavaScript)</option>
  <option value="N0V">Base Velocity</option>
  <option value="N0V_loop">Base Velocity Loop (Java Applet)</option>
  <option value="N0V_loop_nj">Base Velocity Loop (JavaScript)</option>
  <option value="wiem">Hourly Mesonet Overlay</option>
</select>

<p><input type="submit" value="Show"><input type="reset">

<hr>
<b>Raw Data:</b>
<ul
<li><a href="/data/nexrd2/raw/">Level2 NEXRAD data</a></li>
<ul>
 <li><a href="http://weather.noaa.gov/monitor/radar2/">NWS Feed Monitor</a></li>
 <li><a href="http://mesonet.tamu.edu/products/RADAR/nexrad/CRAFT/">Texas Mesonet level2 data cache</a></li>
 <li><a href="http://lead.unidata.ucar.edu:8080/thredds/idd/radars.html">Unidata 6 month data cache</a></li>
</ul>
</ul>

<b>Static Composite Maps:</b>
<ul>
<li><a href="mwcomp.phtml">MidWest Composite w/ warnings</a></li>
<li><a href="uscomp.phtml">US Composite w/ warnings</a></li>
<li><a href="sel.phtml">Convective Watches Overview</a></li>
</ul>

<b>GIS Web-Mapping Apps:</b>
<ul>
<li><a href="<?php echo $rooturl; ?>/GIS/apps/rview/compare.phtml">Iowa RADAR comparisons</a></li>
<li><a href="<?php echo $rooturl; ?>/current/mcview.phtml">Current/Archived Composite Loop</a></li>
<li><a href="<?php echo $rooturl; ?>/GIS/apps/rview/warnings.phtml">Nationwide Weather Warnings.</a> (NWS WFO Friendly)</li>
<li><a href="<?php echo $rooturl; ?>/GIS/apps/iawarn/iawarn.php">Iowa single site NEXRADS w/ warnings.</a></li>
<li><a href="<?php echo $rooturl; ?>/cgi-bin/mapserv/mapserv.radar?map=<?php echo $rootpath; ?>htdocs/GIS/apps/warning0/warning0.map&layers=smooth_radar&layers=watches">Nationwide NEXRAD with current/past day warnings</a></li>
<li><a href="<?php echo $rooturl; ?>/GIS/apps/rview/watch.phtml">Storm Prediction Center (SPC) Watches since 1997.</a></li>
<li><a href="<?php echo $rooturl; ?>/GIS/apps/rview/warnings_cat.phtml">VTEC product browser</a></li>
</ul>
</td></tr>
</table><p>

<TABLE>
<tr>
 <td class="heading" colspan=2>Misc Plots</td>
</tr>
<TR class="odd">
	<TD>Precipitation [NEXRAD]</TD>
	<td> <a href="/data/nexradPrecip1h.gif">1 hour Estimate</a> [<a href="loop.phtml?prod=nexradprecip">Loop</a>] </td>
	</TD>
</TR>

<TR class="even">
        <TD>20min Mesonet + DMX NEXRAD</TD>
        <TD> <a href="../data/20radarOverlay_0.gif">Image</a> &nbsp; | &nbsp;
        <a href="20radarLoop.html">Loop</a> &nbsp; | &nbsp;
        <a href="20radarLoop_s.html">Small Loop</a>
        </TD>
</TR>

<TR class="odd">
        <TD>20min Mesonet + Composite NEXRAD</TD>
        <TD> <a href="../data/MWoverlay_0.gif">Image</a> &nbsp; | &nbsp;
        <a href="MWoverlayLoop.html">Loop</a> 
        </TD>
</TR>

<TR class="even">
	<TD>Satellite</TD>
	<TD><a href="http://www.meteor.iastate.edu/wx/data/current/IAsatvis.gif">Visible</a> &nbsp; | &nbsp;
	<a href="http://www.meteor.iastate.edu/wx/data/current/IAsatir.gif">Infrared</a> &nbsp; | &nbsp;
  <a href="http://weather.cod.edu/data/satellite/1km/Iowa.gif">Iowa 1km</a> (<a href="http://weather.cod.edu/analysis/loops/satmaster.pl?Iowa">Loop</a>)
	</TD>
</TR>

</table></div></div>

<?php include("$rootpath/include/footer.php"); ?>
