<?php 
include("../../config/settings.inc.php");
$prod = isset($_GET['prod']) ? $_GET["prod"]: "";
$product = substr($prod,0,3);
$site = isset($_GET['site']) ? substr($_GET['site'],0,3): "DMX";

$TITLE = "IEM | Current RADAR Data";
$THISPAGE = "current-radar";
$HEADEXTRA = "<BASE HREF=\"http://mesonet.agron.iastate.edu/data/nexrad/\">";
if ($prod == 'N0R_loop_nj' || $prod == 'N0V_loop_nj'){
  $BODYEXTRA = "onload=\"launch()\"";
}
include("$rootpath/include/header.php"); 


if ($prod == 'N0R' || $prod == 'N0V'){
  echo "<img src=\"/data/nexrad/${site}_${prod}_0.gif\">";
}
else if ($prod == 'N0R_loop_nj' || $prod == 'N0V_loop_nj'){
  include ('NIDSloop.php');
}else if ($prod == 'N0R_loop' || $prod == 'N0V_loop'){
    $rprod = substr($prod,0, 3);
?>
<applet codebase="<?php echo $rooturl; ?>/current/class/" code="AniS.class" width=650 height=600 alt="You must enable Java in your browser to view the radar loop">
        <param name="controls" value="startstop, looprock, step, speed, toggle, 
zoom">
        <param name="rate" value="80">
		<param name="no_enh" value="true">
        <param name="pause_percent" value="800">
        <param name="file_of_filenames" value="<?php echo $rooturl; ?>/current/text/K<?php echo $site ."_". $rprod; ?>.txt">
        </applet>
<?php
}

?></div>
<?php include("$rootpath/include/footer.php"); ?>
