<?php
require_once "../../config/settings.inc.php";
define("IEM_APPID", 70);
require_once "../../include/myview.php";
require_once "../../include/database.inc.php";
require_once "../../include/forms.php";

$t = new MyView();
$conn = iemdb("postgis");
$sel = get_int404("sel", -1);
$t->refresh = 300;
$t->title = "SPC Watches Overview";

$metdata = array();
$rs = pg_query($conn, "SELECT * from watches_current");
for ($i = 0; $row = pg_fetch_assoc($rs); $i++) {
    $metadata[$row["sel"]] = $row;
    $metadata[$row["sel"]]["sts"] = strtotime(substr($row["issued"], 0, 16));
    $metadata[$row["sel"]]["ets"] = strtotime(substr($row["expired"], 0, 16));
}

if ($sel > -1) {
    $row = $metadata["SEL" . $sel];

    $t->content = <<<EOF
<a href="sel.phtml">View All Watches</a>

<p><img src="/data/sel{$sel}comp.png" />

<br /><pre>{$row["report"]}</pre>
EOF;
} else {
    $content = "";
    for ($i = 0; $i < 10; $i++) {
        $row = $metadata["SEL" . $i];
        $content .= "<div class=\"col-md-4 well\">
        <strong>SEL{$i}:</strong> Issued: " . date("j M Y g:i A", $row["sts"])
            . "<br />Expired: " . date("j M Y g:i A", $row["ets"]) . ",
                        <a href=\"/GIS/apps/rview/watch.phtml?year=" . date("Y", $row["sts"]) . "&num=" . $row["num"] . "\">more info</a>
                        <br /><a href=\"sel.phtml?sel={$i}\">
        <img src=\"/data/sel{$i}comp.png\" class=\"img img-responsive\"></a>
        </div>";
    }
    $t->content = <<<EOF

<p>Click on an image to get an enlarged view as well as the text for the watch. 
These images are for the last 10 areas in which watches have been valid for.  
If the watch is currently valid, it will appear on the plot.  The timestamps
presented are in US Central time.

$content

EOF;
}
$t->render('single.phtml');
