<?php
 include("../../config/settings.inc.php");
 include("$rootpath/include/database.inc.php");
 $conn = iemdb("postgis");
 $width = isset($_GET["width"])? $_GET["width"] : "320";
 $sel = isset($_GET["sel"]) ? intval($_GET["sel"]) : -1;
$rs = pg_prepare($conn, "SELECT", "SELECT * from watches_current 
      WHERE sel = $1");

 $REFRESH = "<meta http-equiv=\"refresh\" content=\"300;\">";
 $TITLE = "IEM | SPC Watches Overview";
 $THISPAGE = "current-radar";
 include("$rootpath/include/header.php");
?>

<?php if ($sel != -1) { 
 $rs = pg_execute($conn, "SELECT", Array("SEL". $sel));
?>

<a href="sel.phtml">View All Watches</a>

<p><img src="/data/sel<?php echo $sel; ?>comp.png" />
<?php

 $row = @pg_fetch_array($rs);

 echo "<br /><pre>". $row["report"] ."</pre>";

?>
<?php } else { ?>

<p>Click on an image to get an enlarged view as well as the text for the watch. These images are for the last 10 areas in which watches have been valid for.  If the watch is currently valid, it will appear on the plot.

<table>
<tr>
 <td><b>SEL0:</b><br /><a href="sel.phtml?sel=0"><img src="/data/sel0comp.png" width="<?php echo $width; ?>"></a></td>
 <td><b>SEL1:</b><br /><a href="sel.phtml?sel=1"><img src="/data/sel1comp.png" width="<?php echo $width; ?>"></a></td><tr>
<tr>
 <td><b>SEL2:</b><br /><a href="sel.phtml?sel=2"><img src="/data/sel2comp.png" width="<?php echo $width; ?>"></a></td>
 <td><b>SEL3:</b><br /><a href="sel.phtml?sel=3"><img src="/data/sel3comp.png" width="<?php echo $width; ?>"></a></td><tr>
<tr>
 <td><b>SEL4:</b><br /><a href="sel.phtml?sel=4"><img src="/data/sel4comp.png" width="<?php echo $width; ?>"></a></td>
 <td><b>SEL5:</b><br /><a href="sel.phtml?sel=5"><img src="/data/sel5comp.png" width="<?php echo $width; ?>"></a></td><tr>
<tr>
 <td><b>SEL6:</b><br /><a href="sel.phtml?sel=6"><img src="/data/sel6comp.png" width="<?php echo $width; ?>"></a></td>
 <td><b>SEL7:</b><br /><a href="sel.phtml?sel=7"><img src="/data/sel7comp.png" width="<?php echo $width; ?>"></a></td><tr>
<tr>
 <td><b>SEL8:</b><br /><a href="sel.phtml?sel=8"><img src="/data/sel8comp.png" width="<?php echo $width; ?>"></a></td>
 <td><b>SEL9:</b><br /><a href="sel.phtml?sel=9"><img src="/data/sel9comp.png" width="<?php echo $width; ?>"></a></td><tr>
</table>
<?php
 } 
include("$rootpath/include/footer.php"); 
?>
