<?php 
require_once "../../config/settings.inc.php";
require_once "../../include/myview.php";
$t = new MyView();
$t->thispage = "severe-main";
$t->title = "Severe Weather Products";
$t->content = <<<EOF
<div class="row">
<div class="col-md-4"> 
 <h3>Current Severe Weather</h3>
  <ul>
<li><a href="/wx/afos/">NWS Text Product Finder</a>
  <br />A quick and easy way to find NWS text products if you know the 
  product identifiers.</li>

<li><a href="/iembot/">Web iembot monitor</a>
  <br />This fancy application allows you to monitor text products coming
  from your local NWS office or the entire nation in realtime!</li>

<li><a href="/data/gis/shape/4326/us/current_nexattr.zip">Current NEXRAD Storm Attributes</a>
  <br />Point shapefile generated every minute containing a summary of
   NEXRAD storm attributes.</li>

<li><a href="sel.phtml">Convective Watches Overview</a>
  <br />10 maps of the last locations of convective watches issued by SPC.</li>

</ul>

 <h3>GIS Local Storm Reports</h3>
<ul>

<li><a href="/data/gis/shape/4326/us/lsr_24hour.zip">Current Shapefile</a>
 <br />A shapefile of Local Storm Reports (LSRs) valid for the past 24 hours.
  The file is updated every 5 minutes.</li>

<li><a href="/request/gis/lsrs.phtml">Download Archived LSRs</a>
 <br />Generate a shapefile of LSRs for a period of your choice dating back 
  to 2003!</li>

</ul>

 <h3>GIS Watch/Warnings</h3>
<ul>

<li><a href="/data/gis/shape/4326/us/current_ww.zip">Current Shapefile</a>
 <br />A shapefile of active county based and storm based based weather warnings. This file is updated every 5 minutes.</li>

<li><a href="/request/gis/watchwarn.phtml">Download Archived NWS Warnings</a>
 <br />Generate a GIS shapefile of weather warnings for a time period of your
 choice!</li>

  </ul>
</div>
<div class="col-md-4">
 <h3>Apps with Statistics</h3>
 <ul>
 <li><a href="/cow/sbwstats.phtml">Summary of Polygon Sizes</a>
  <br />View storm based warning size summary statistics by WFO for a period of your
  choice.</li>
<li><a href="/cow/top10.phtml">Top 10 Polygon Sizes</a>
  <br />List top 10 largest and smallest storm based warnings by WFO.</li>

  <li><a href="/plotting/auto/?q=92">Days since VTEC WWA Product</a>
  <br />Generates a map of the number of days since a VTEC WWA Product.</li>

  <li><a href="/vtec/events.php">VTEC Events by WFO or State by Year</a>
  <br />Simple table listing any VTEC events by a given WFO or state for
  a given year.</li>

   <li><a href="/vtec/maxetn.php">Maximum VTEC EventID (ETN) by year</a>
  <br />This diagnostic prints out the maximum issued VTEC eventid (ETN) by
year.  A useful diagnostic for a NWS Office wishing to check their local VTEC
eventd database.</li>

<li><a href="/vtec/emergencies.php">Tornado + Flash Flood Emergencies listing</a>
<br />Simple table showing IEM indicated Tornado and Flash Flood Emergency 
events.</li>

<li><a href="/vtec/yearly_counts.php">Yearly counts of VTEC Products</a>
  <br />Generates a table of the number of VTEC products issued by year.</li>
  </ul>
 
 <h3>Apps with Archives</h3>
<ul>
<li><a href="/cow/">IEM Cow</a>
  <br />Unofficial NWS storm-based warning verification.</li>

<li><a href="/raccoon/">IEM Raccoon</a>
  <br />Generate Microsoft Powerpoint overviews of storm based warnings.</li>


<li><a href="/vtec/search.php">Search by County/Zone or Point</a>
  <br />Find archived warnings by searching for a county or zone.  You can
  also search for storm based warnings by a point.</li>


<li><a href="/GIS/apps/rview/watch.phtml">Storm Prediction Center (SPC) Watches since 1997.</a>
 <br />Maps of SPC issued watches and initial RADAR (since 1997) at watch issuance.</li>

<li><a href="/GIS/apps/rview/warnings.phtml">Nationwide Weather Warnings.</a> 
 <br />Popular web mapping application showing all sorts of information
  relating to severe weather.  Works great for situational awareness
  displays.</li>

<li><a href="/GIS/apps/rview/warnings_cat.phtml">VTEC product browser</a>
 <br />Popular application that allows you to navigate thru an archive of
  weather warnings.  Full text is displayed along with the maps.</li>

  <li><a href="mcview.phtml?prod=comprad&java=none&mode=realtime&frames=1">MidWest Composite w/ warnings</a></li>
  <li><a href="mcview.phtml?prod=usrad&java=none&mode=realtime&frames=1">US Composite w/ warnings</a></li>

 <li>Storm Based Warnings: <a href="/cow/sbwsum.phtml">daily summary images</a>, images displaying sbw for a given date.</li>
</ul>
</div>
<div class="col-md-4">
 <h3>Severe Weather Outlooks</h3>

<p><a href="http://www.spc.noaa.gov">Storm Prediction Center</a> convective outlooks:

<p><b>Current Day 1 Outlook</b><br />
 <a href="http://www.spc.noaa.gov/products/outlook/day1otlk.html">
		<img src="http://www.spc.noaa.gov/products/outlook/day1otlk.gif" class="img img-responsive" alt="Day 1 Outlook"></a>

<p><b>Current Day 2 Outlook</b><br />
 <a href="http://www.spc.noaa.gov/products/outlook/day2otlk.html">
		<img src="http://www.spc.noaa.gov/products/outlook/day2otlk.gif" class="img img-responsive" alt="Day 2 Outlook"></a>

<p><b>Current Day 3 Outlook</b><br />
 <a href="http://www.spc.noaa.gov/products/outlook/day3otlk.html">
		<img src="http://www.spc.noaa.gov/products/outlook/day3otlk.gif" class="img img-responsive" alt="Day 3 Outlook"></a>

<p><b>Current Day 4-8 Outlook</b><br />
 <a href="http://www.spc.noaa.gov/products/exper/day4-8/">
		<img src="http://www.spc.noaa.gov/products/exper/day4-8/day48prob.gif" class="img img-responsive" alt="Day 4-8 Outlook"></a>

</div>
</div><!-- ./row -->
EOF;
$t->render('single.phtml');
?>