<applet codebase="class/" code="AniS.class" width=650 height=600 alt="You must enable Java in your browser to view the radar loop">
	<param name="controls" value="startstop, looprock, step, speed, toggle, zoom">
	<param name="rate" value="80">

	<param name="pause_percent" value="800">
	<param name="file_of_filenames" value="text/kdmx.txt">
	<br><br><br><br><span class="red"><b>Java must be enabled for radar loops to display.
	<br><br>In Netscape:<br>Select: Edit -> Preferences -> Advanced<br>Check "Enable Java" and "Enable Javascript"
	<br><br>In Internet Explorer<br>Select: Tools -> Internet Options -> Security tab<br>Select the Internet zone and set the Security level for the zone to "Medium"
	<br><br><br>You may need to restart your browser after making these changes.</b></span>
	</applet>
