<?php
$OL = "3.16.0";
include("../../config/settings.inc.php");
define("IEM_APPID", 95);
include("../../include/myview.php");
$t = new MyView();
 include("../../include/cameras.inc.php"); 
 $id = isset($_GET["id"]) ? $_GET["id"] : "KCCI-001";

 $camselect = "";
 $cnt = 0;
 while (list($cid, $v) = each($cameras) ) {
 	if ($v["active"] && $v["network"] != "IDOT"){
 		$camselect .= "<div class=\"col-md-2\"><label class=\"radio-inline\"><input type=\"radio\" name=\"id\" value=\"$cid\" id=\"c$cid\" ";
 		if ($cid == $id) { $camselect .= "checked=\"checked\""; }
 		$camselect .= " onClick=\"setCameraFromForm('{$cid}');\">". $v["name"] ."</label></div>\n";
 		$cnt += 1;
 	}
 }
 
 $t->title =  "Current + Live Web Camera Shots";
 $t->thispage = "webcam-viewer";
 $t->jsextra = <<<EOF
 <script src='/vendor/openlayers/{$OL}/ol.js'></script>
 <script src='/vendor/openlayers/{$OL}/ol3-layerswitcher.js'></script>
 <script src="/vendor/moment/2.13.0/moment.min.js"></script>
 <script src="/vendor/moment/2.13.0/moment.min.js"></script>
 <script src="/vendor/bootstrap-datetimepicker/4.17.37/bootstrap-datetimepicker.min.js"></script>
 <script>
 	var cameraID = "{$id}";
 </script>
 <script src='viewer.js'></script>
EOF;
 $t->headextra = <<<EOF
<link rel="stylesheet" href="/vendor/openlayers/{$OL}/ol.css" type="text/css">
<link rel="stylesheet" href="/vendor/openlayers/{$OL}/ol3-layerswitcher.css" type="text/css">
<link rel="stylesheet" href="/vendor/bootstrap-datetimepicker/4.17.37/bootstrap-datetimepicker.min.css" type="text/css">
EOF;
 

 
 $t->content = <<<EOF
<style>
 h2 {
   margin-top: 0px;
}
</style>
 
     <div class="row">
     	<div class="col-sm-6">
     	<h3>Webcam Viewer App</h3>
     	</div>
        <div class='col-sm-3'>
    <strong>Application Mode:</strong>
<div class="btn-group" id="toggle_event_mode">
	<button type="button" class="btn btn-info locked_active">Realtime</button>
	<button type="button" class="btn btn-default unlocked_inactive">Archive</button>
</div>
		</div>
        <div class='col-sm-3'>
        <div id="dtdiv" style="display: none;">
    <strong>Date &amp; Time:</strong> (click calendar icon)
        <div class="form-group">
                <div class='input-group date' id='dtpicker'>
                    <input type='text' class="form-control" />
                    <span class="input-group-addon">
                        <span class="glyphicon glyphicon-calendar"></span>
                    </span>
                </div>
            </div>
        </div>
        </div>
     </div>
 
<div class="row">
<div class="col-md-6">
<h2 id="webcam_title">Application is Loading...</h2>
<img id="webcam_image" name="camera" src="/data/camera/640x480/{$id}.jpg" class="img img-responsive" />
</div>
<div class="col-md-6">
<h2 id="radar_title">Application is Loading...</h2>
<div style="width: 100%; height: 400px;" id="map"></div>
</div>

<br clear="all" />

<form name="main" target="JavaScript: func()">
<b>Select Camera:</b>
<div class="row">
{$camselect}
</div>
<p><input type="submit" onclick="liveShot(); return false;" value="Live Shot!"></p>

</form>


<div style="padding: 5px;">


<h3>JavaScript Web Camera Viewer Help</h3>

<p>This page should never reload.  The refreshing of the web camera images is controlled by Javascript.  The images will automatically reload:
<ul>
	<li>every minute</li>
	<li>when you select a camera site</li>
	<li>when you click the 'Live Shot' button.</li>
</ul></p>

<p>The Live Shot images are being acquired directly from the camera!  Please
be patient after clicking the 'Live Shot' button for it may take a few 
seconds to contact the camera.  When the display refreshes 
by itself, the image is coming from a cache which may be up to 5 minutes old.
This is done since bandwidth to the cameras is limited.</p>
</div>
EOF;
$t->render('full.phtml');
?>