<?php
include("../../config/settings.inc.php");
define("IEM_APPID", 95);
include("../../include/myview.php");
$t = new MyView();
 include("../../include/cameras.inc.php"); 
 $id = isset($_GET["id"]) ? $_GET["id"] : "KCCI-001";

 $camselect = "";
 $cnt = 0;
 while (list($cid, $v) = each($cameras) ) {
 	if ($v["active"] && $v["network"] != "IDOT"){
 		$camselect .= "<div class=\"col-md-2\"><label class=\"radio-inline\"><input type=\"radio\" name=\"id\" value=\"$cid\" id=\"c$cid\" ";
 		if ($cid == $id) { $camselect .= "checked=\"checked\""; }
 		$camselect .= " onClick=\"setCameraFromForm('{$cid}');\">". $v["name"] ."</label></div>\n";
 		$cnt += 1;
 	}
 }
 
 $t->title =  "Current + Live Web Camera Shots";
 $t->thispage = "webcam-viewer";
 $t->jsextra = <<<EOF
 <script src='/vendor/openlayers/3.8.2/ol.js'></script>
 <script src='/vendor/openlayers/3.8.2/ol3-layerswitcher.js'></script>
 <script>
 	var cameraID = "{$id}";
 </script>
 <script src='viewer.js'></script>
EOF;
 $t->headextra = <<<EOF
<link rel="stylesheet" href="/vendor/openlayers/3.8.2/ol.css" type="text/css">
<link rel="stylesheet" href="/vendor/openlayers/3.8.2/ol3-layerswitcher.css" type="text/css">
EOF;
 

 
 $t->content = <<<EOF

<div class="row">
<div class="col-md-6">

<img name="camera" src="/data/camera/640x480/{$id}.jpg" class="img img-responsive" />

</div>
<div class="col-md-6">


<div style="width: 100%; height: 400px;" id="map"></div>
<br />
<form name="radar">
<div class="row">
<div class="col-md-6">
<input type="radio" name="nexrad" value="nexrad-n0q-900913"
             onclick="switchRADAR()" checked="checked">US Composite</input>
</div>
<div class="col-md-6">
<input type="radio" name="nexrad" value="ridge::DVN-N0Q-0"
             onclick="switchRADAR()">Davenport Reflectivity</input>
</div>
             <div class="col-md-6">
<input type="radio" name="nexrad" value="ridge::DVN-N0U-0"
             onclick="switchRADAR()">Davenport Velocity</input>
</div>
             <div class="col-md-6">
<input type="radio" name="nexrad" value="ridge::DMX-N0Q-0"
             onclick="switchRADAR()">Des Moines Reflectivity</input>
</div>
             <div class="col-md-6">
<input type="radio" name="nexrad" value="ridge::DMX-N0U-0"
             onclick="switchRADAR()">Des Moines Velocity</input>
</div>
             <div class="col-md-6">
<input type="radio" name="nexrad" value="ridge::ARX-N0Q-0"
             onclick="switchRADAR()">LaCrosse Reflectivity</input>
</div>
             <div class="col-md-6">
<input type="radio" name="nexrad" value="ridge::ARX-N0U-0"
             onclick="switchRADAR()">LaCrosse Velocity</input>
</div>
             <div class="col-md-6">
<input type="radio" name="nexrad" value="ridge::FSD-N0Q-0"
             onclick="switchRADAR()">Sioux Falls Reflectivity</input>
</div>
             <div class="col-md-6">
<input type="radio" name="nexrad" value="ridge::FSD-N0U-0"
             onclick="switchRADAR()">Sioux Falls Velocity</input>
</div>
</form>

</div>
</div>

<br clear="all" />

<form name="main" target="JavaScript: func()">
<b>Select Camera:</b>
<div class="row">
{$camselect}
</div>
<p><input type="submit" onclick="liveShot(); return false;" value="Live Shot!"></p>

</form>


<div style="padding: 5px;">


<h3>JavaScript Web Camera Viewer Help</h3>

<p>This page should never reload.  The refreshing of the web camera images is controlled by Javascript.  The images will automatically reload:
<ul>
	<li>every minute</li>
	<li>when you select a camera site</li>
	<li>when you click the 'Live Shot' button.</li>
</ul></p>

<p>The Live Shot images are being acquired directly from the camera!  Please
be patient after clicking the 'Live Shot' button for it may take a few 
seconds to contact the camera.  When the display refreshes 
by itself, the image is coming from a cache which may be up to 5 minutes old.
This is done since bandwidth to the cameras is limited.</p>
</div>
EOF;
$t->render('single.phtml');
?>