<?php 
include("../../config/settings.inc.php");
include("$rootpath/include/database.inc.php");
$coopdb = iemdb("coop");

$TITLE = "IEM | Current | Yearly Plots";
$THISPAGE = "current-year";
include("$rootpath/include/header.php"); 
?>
<h3>Selected Location Summary: 01 Jan thru <?php echo date("d M Y", time() - 86400); ?></h3>

<p>These values are estimates based on the IEM's collection of various datasets.
Climatology is based on observations back to 1951.

<table cellpadding="2" cellspacing="0" border="1">
 <tr><th rowspan="2">Location</th><th colspan="2">Growing Degree Days</th>
  <th colspan="2">Precipitation</th>
  <th colspan="3">Temperature</th>
 </tr>
 <tr>
 <th>Observed</th><th>Climate</th>
 <th>Observed</th><th>Climate</th>
 <th>Highest</th><th>Lowest</th><th>Average</th>
 </tr>
<?php
$lkp = Array("ia0200" => "Ames", "ia2203" => "Des Moines",
      "ia8706" => "Waterloo", "ia1319" => "Cedar Rapids",
      "ia2364" => "Dubuque", "ia2110" => "Decorah",
      "ia5230" => "Mason City", "ia7708" => "Sioux City",
      "ia7613" => "Shenandoah", "ia4585" => "Lamoni", "ia4705" => "Davenport");
$rs = pg_query($coopdb, "select stationid, 
   sum(gdd50(o.high, o.low)) as ogdd50, sum(o.precip) as oprecip, 
   sum(gdd50) as cgdd50, sum(c.precip) as cprecip,
   max(o.high) as maxtmpf, min(o.low) as mintmpf,
   avg( (o.high + o.low) / 2.0 ) as avgtmpf
  from alldata o, climate51 c WHERE 
   stationid in ('ia0200', 'ia1319', 'ia2203','ia8706', 'ia2364', 'ia2110',
    'ia5230', 'ia7708', 'ia7613', 'ia4585', 'ia4705') 
   and stationid = station 
   and day >= '2010-01-01' and day <= '2010-12-31' 
   and extract(doy from day) = extract(doy from valid)  GROUP by stationid
   ORDER by stationid ASC");
for($i=0;$row=@pg_fetch_array($rs,$i);$i++){
  echo sprintf("<tr style=\"background: %s;\"><th>%s</th><td>%.0f</td><td>%.0f</td><td>%.2f</td><td>%.2f</td><td>%.0f</td><td>%.0f</td><td>%.0f</td></tr>", 
  ($i % 2 == 0) ? "#eee": "#fff;", $lkp[$row["stationid"]], $row["ogdd50"], $row["cgdd50"], $row["oprecip"], $row["cprecip"], 
  $row["maxtmpf"], $row["mintmpf"], $row["avgtmpf"]);
}
?>
</table>


<h4>Precipitation</h4>

<ul class="iem-list">
 <li><a href="../data/summary/year/diff.png">Departure from normal</a></li>
 <li><a href="../data/summary/year/stage4obs.png">Stage4 estimates</a></li>
 <li><a href="../data/summary/year/normals.png">Normal accumulation</a></li>
</ul>


<h4>Temperature</h4>
<ul class="iem-list">
<li><a href="/plotting/coop/climate_fe.php">Annual Average Temperatures</a></li>
<li><a href="/plotting/coop/vyear_fe.php">Yearly Departures from Average</a></li>
<li><a href="/COOP/freezing.php">Freezing Statistics</a></li>
<li><a href="/data/summary/gdd_jan1.png">Accumulated Growing Degree Days-(base=50)</a></li>
</ul>

<h4>Past 4 Months</h4>
<ul class="iem-list">
 <li><a href="/data/summary/4mon_stage4obs.png">Estimated accumulation</a></li>
 <li><a href="/data/summary/4mon_normals.png">Climatology</a></li>
 <li><a href="/data/summary/4mon_diff.png">Departure from normal</a></li>
</ul>


<h4>Winds</h4>
<ul class="iem-list">
<li><a href="http://mesonet.agron.iastate.edu/sites/windrose.phtml?station=DSM&network=IA_ASOS">Wind Roses</a></li>
</ul>



<?php include("$rootpath/include/footer.php"); ?>
