<?php 
// A simple box inclusion on the download pages
$uri = $_SERVER["SCRIPT_URL"];
$lh = '';
$ld = '';
$ch = '';
$cd = '';
$ci = '';
$highlight = "<i class=\"fa fa-check\"></i> &nbsp; ";
if ($uri == '/agclimate/hist/dailyRequest.php'){
    $ld = $highlight;
}
elseif ($uri == '/agclimate/hist/hourlyRequest.php'){
    $lh = $highlight;
}
elseif ($uri == '/agclimate/hist/hourly.php'){
    $ch = $highlight;
}
elseif ($uri == '/agclimate/hist/daily.php'){
    $cd = $highlight;
}
elseif ($uri == '/agclimate/hist/inversion.php'){
    $ci = $highlight;
}

$box = <<<EOM
<div class="row">
    <div class="col-sm-6">
<div class="panel panel-default">
  <div class="panel-heading">Legacy "ISU AgClimate" 1986-~2013</div>
  <div class="panel-body">
        <div class="row">
            <div class="col-sm-6">{$lh}<a href="hourlyRequest.php">Hourly Data</a></div>
            <div class="col-sm-6">{$ld}<a href="dailyRequest.php">Daily Data</a></div>
        </div>
    </div>
</div>
    </div>
    <div class="col-sm-6">
<div class="panel panel-default">
  <div class="panel-heading">"ISU Soil Moisture Network" ~2013-present</div>
  <div class="panel-body">
        <div class="row">
            <div class="col-sm-4">{$ch}<a href="hourly.php">Hourly Data</a></div>
            <div class="col-sm-4">{$ci}<a href="inversion.php">Inversion Data</a></div>
            <div class="col-sm-4">{$cd}<a href="daily.php">Daily Data</a></div>
        </div>
    </div>
</div>

    </div>
</div>
EOM;

$qcbox = <<<EOM
<!--
<p><strong>Include Quality Control Flags?</strong>
<br /><input type="checkbox" name="qcflags" value="1">
<label for="qcflags">Yes, please include</label>
<br />
<table>
<thead><tr><th>Flag</th><th>Meaning</th></tr></thead>
<tbody>
<tr><td>E</td><td>Value estimated by IEM.</td></tr>
</tbody>
</table>
-->
EOM;
