<?php 
  include("../../config/settings.inc.php");
  include('switchtv.php'); 
include("../../include/myview.php");
$t = new MyView();
  $network = isset($_GET['ntv']) ? $_GET['ntv'] : 'KCCI';
  $sortcol = isset($_GET['sortcol']) ? $_GET['sortcol'] : "";

  $t->title = "School Network";
  $t->refresh = "<meta http-equiv=\"refresh\" content=\"60; URL=current.phtml?tv=$tv&sortcol=$sortcol\">";
  $t->headextra = <<<EOF
<script language="JavaScript" type="text/javascript">
<!--//BEGIN Script
function new_window(url) {
 link = window.open(url,"Link","toolbar=0,location=0,directories=0,status=0,menubar=no,scrollbars=yes,resizable=yes,width=360,height=400");
} 
function new_window_big(url) {
 link = window.open(url,"Link","toolbar=0,location=0,directories=0,status=0,menubar=no,scrollbars=yes,resizable=yes,width=800,height=600");
} 
//END Script-->
</script>
EOF;
  
 $t->thispage = "current-sort";
  include("../../include/mlib.php"); 
  include("../../include/iemaccess.php");
  include("../../include/iemaccessob.php");

  $iem = new IEMAccess();
  $snet = $iem->getNetwork( strtoupper($tv) );

$today = mktime(0,0,0, date("m"), date("d"), date("Y"));

$t->breadcrumbs = <<<EOF
<ol class="breadcrumb">
<li><a href="/schoolnet">School Net</a></li>
<li class="current">Current Conditions</li>
</ol>
EOF;
$t->current_network = "SchoolNet"; 

$link = "current.phtml";
$content = <<<EOF
<p>** This page will automatically refresh every minute.
Click on a column to sort it. Perhaps you would like to know 
<a href="/GIS/apps/snet/raining.php">Where's it raining?</a></p>

<table cellpadding="0" cellspacing="0" border="0">
<tr>
   <td class="kcci" align="center"><a href="{$link}?ntv=KCCI" style="text-decoration: none;"><img src="/schoolnet/images/kcci8.jpg" border="0"><br /><b>SchoolNet8</b></a></td>

    <td class="kelo" align="center"><a href="{$link}?ntv=KELO" style="text-decoration: none;"><img src="/schoolnet/images/kelo.png" border="0"><br /><b>WeatherNet</b></a></td>

    <td class="kimt" align="center"><a href="{$link}?ntv=KIMT" style="text-decoration: none;"><img src="/schoolnet/images/kimt_logo.png" border="0"><br /><b>StormNet</b></a></td>

</tr>

<tr>
  <td colspan="9">

<table width="100%" cellpadding=2><tr><td>
<table width="100%" cellpadding=2 bgcolor="white"><tr><td>
EOF;

if (strlen($sortcol) == 0) {
  $sortcol = "sname";
}
$vals = Array("ts" => "Observation Time", "sname" => "Station Name",
 "tmpf" => "Temperature", "drct" => "Wind Direction", "dwpf" => "Dew Point",
 "relh" => "Relative Humidity", "alti" => "Pressure",
 "sknt" => "Wind Speed", "20gu" => "20 min Gust",
 "peak" => "Peak Gust Today", "peak_ts" => "Time of Peak Gust", 
 "pday" => "Today's Precipitation", "feel" => "Feels Like", 
 "max_tmpf" => "High Temperature", "min_tmpf" => "Low Temperature",
 "pmonth" => "Month's Precipitation", "prate" => "Hourly Precip Rate");

if (! isset($vals[$sortcol])){
$sortcol = "tmpf";
}

// http://www.php.net/manual/en/function.asort.php

function aSortBySecondIndex($multiArray, $secondIndex) {
	while (list($firstIndex, ) = each($multiArray))
		$indexMap[$firstIndex] = $multiArray[$firstIndex][$secondIndex];
	asort($indexMap);
	while (list($firstIndex, ) = each($indexMap))
	if (is_numeric($firstIndex))
		$sortedArray[] = $multiArray[$firstIndex];
	else $sortedArray[$firstIndex] = $multiArray[$firstIndex];
	return $sortedArray;
}
function arSortBySecondIndex($multiArray, $secondIndex) {
	while (list($firstIndex, ) = each($multiArray))
		$indexMap[$firstIndex] = $multiArray[$firstIndex][$secondIndex];        arsort($indexMap);
	while (list($firstIndex, ) = each($indexMap))
	if (is_numeric($firstIndex))
		$sortedArray[] = $multiArray[$firstIndex];
	else $sortedArray[$firstIndex] = $multiArray[$firstIndex];
	return $sortedArray;
}




$mydata = Array();
while (list($key, $iemob) = each($snet) ){
	$mydata[$key] = $iemob->db;
	$mydata[$key]["sped"] = $mydata[$key]["sknt"] * 1.15078;
	if ($mydata[$key]["max_tmpf"] > 150) {
		$mydata[$key]["max_tmpf"] = "";
	}
	if ($mydata[$key]["tmpf"] < 150 && $mydata[$key]["tmpf"] > -50) {
		$mydata[$key]["feel"] = feels_like($mydata[$key]["tmpf"],
				$mydata[$key]["relh"], $mydata[$key]["sped"]);
	} else {
		$mydata[$key]["tmpf"] = "";
		$mydata[$key]["relh"] = "";
		$mydata[$key]["feel"] = "";
		$mydata[$key]["max_tmpf"] = "";
		$mydata[$key]["min_tmpf"] = "";
	}
	if ($mydata[$key]["relh"] < 5){
		$mydata[$key]["relh"] = "";
		$mydata[$key]["feel"] = "";
		$mydata[$key]["dwpf"] = "";
	}

	if ($mydata[$key]["max_gust"] > $mydata[$key]["max_sknt"]){
		$mydata[$key]["peak"] = $mydata[$key]["max_gust"];
		$mydata[$key]["peak_ts"] = strtotime(substr( $mydata[$key]["max_gust_ts"],0,16) );
	} else {
		$mydata[$key]["peak"] = $mydata[$key]["max_sknt"];
		if ($mydata[$key]["max_sknt_ts"] > 0){
			$mydata[$key]["peak_ts"] = strtotime(substr( $mydata[$key]["max_sknt_ts"],0,16) );
		} else {
			$mydata[$key]["peak_ts"] = 0;
		}
	}

}



$finalA = Array();
if ($sortcol == "sname"){
	$finalA = aSortBySecondIndex($mydata, $sortcol);
} else {
	$finalA = arSortBySecondIndex($mydata, $sortcol);
}
$now = time();

$skippedStations = Array();
$table = "";
while (list ($key, $val) = each ($finalA))  {
	$parts = $finalA[$key];
	$tdiff = $now - $parts["ts"];
	if ($tdiff > 3600 && $sortcol != "ts") {
		$skippedStations[$key] = $parts;
		continue;
	}
	$table .= "<tr>\n ";
	$table .= "<td><input type=\"checkbox\" name=\"st[]\"
    value=\"".$key."\"></td>";
	$table .= "<th><a href=\"javascript:new_window('/content/".strtolower($tv)."_fe.php?station=".$key."');\">". $parts["sname"] . "</a></th>";


	$table .= "<td ";
	if ($tdiff < 200){
		$table .= ">". strftime("%I:%M %p", $parts['ts']);
	} else if ($tdiff < 600){
		$table .= "bgcolor=\"green\">". strftime("%I:%M %p", $parts['ts']);
	} else {
		$table .= "bgcolor=\"red\">". strftime("%d %b %I:%M %p", $parts['ts']);
	}
	$table .= "</td>";
	$table .= "<td align='center'>". $parts["tmpf"] ."(<font color=\"#ff0000\">".
			round($parts["max_tmpf"],0) ."</font>/<font color=\"#0000ff\">".
			round($parts["min_tmpf"],0) ."</font>)</td>
          <td>". $parts["dwpf"] ."</td>
          <td align='center'>". $parts["relh"] ."%</td>
          <td>". $parts["feel"] ."</td>
          <td>". $parts["pres"] ."</td>
          <td>". drct2txt($parts["drct"]) ."</td>
            <td>". round($parts["sknt"],0) ."</td>
            <td>". round($parts["peak"],0) ." @"
            		. strftime("%I:%M %p", $parts["peak_ts"]) ."</td>
          <td>". $parts["pday"] ."</td>
          <td>". $parts["pmonth"] ."</td>
          </tr>\n";
}

/* Loop through sites that are old */
while (list ($key, $val) = each ($skippedStations) ) {
	$parts = $finalA[$key];
	$tdiff = $now - $parts["ts"];
	$table .= "<tr>\n ";
	$table .= "<td><input type=\"checkbox\" name=\"st[]\"
    value=\"".$key."\"></td>";
	$table .= "<th><a href=\"javascript:new_window
('/content/". strtolower($tv) ."_fe.php?station=".$key."');\">". $parts["sname"] . "</a></th>";

	$table .= "<td bgcolor=\"red\">". strftime("%d %b %I:%M %p", $parts['ts']) ."</td>";

	if ($parts["ts"] < $today) {
		$table .= "<th colspan=10>Site Offline!</th></tr>";
	} else {
		$table .= "<td align='center'>". $parts["tmpf"] ."(<font color=\"#ff0000\">".
				round($parts["max_tmpf"],0) ."</font>/<font color=\"#0000ff\">".
				round($parts["min_tmpf"],0) ."</font>)</td>
          <td>". $parts["dwpf"] ."</td>
          <td align='center'>". $parts["relh"] ."%</td>
          <td>". $parts["feel"] ."</td>
          <td>". $parts["pres"] ."</td>
          <td>". $parts["drct"] ."</td>
            <td>". round($parts["sknt"],0) ."</td>
            <td>". round($parts["peak"],0) ." @"
            		. strftime("%I:%M %p", $parts["peak_ts"] )."</td>
          <td>". $parts["pday"] ."</td>
          <td>". $parts["pmonth"] ."</td>
          </tr>\n";
	}
} 
$c = "javascript:new_window_big('/GIS/apps/php/currents.phtml?layers[]=radar&layers[]=labels&network=". strtoupper($tv)."&var=";

$content .= <<<EOF
<p>Sorted by: <b>{$vals[$sortcol]}</b><br>

<form method="GET" action="/my/current.phtml">

<table class="ruler" style="width: 100%; font-size: 10pt;">
<thead>
<tr>
  <th rowspan="2">ADD:</th>
  <th rowspan="2"><a href="current.phtml?sortcol=sname">Station:</a></th>
  <th rowspan="2"><a href="current.phtml?sortcol=ts">Ob Time</a> [1]</th>
  <th></th>
  <th></th>
  <th></th>
  <th></th>
  <th></th>
  <th colspan="3" bgcolor="#EEEEEE">Wind [2] knots</th>
  <th bgcolor="#e6e6fa" colspan=2>Precipitation</th>
</tr>
<tr>
  
  <th><a href="current.phtml?tv={$tv}&sortcol=tmpf">Temp</a>(<a href="current.phtml?tv={$tv}&sortcol=max_tmpf">Hi</a> /
   <a href="current.phtml?tv={$tv}&sortcol=min_tmpf">Lo</a>)</th>
  <th><a href="current.phtml?tv={$tv}&sortcol=dwpf">DewP</a></th>
  <th><a href="current.phtml?tv={$tv}&sortcol=relh">RH%</a></th>
  <th><a href="current.phtml?tv={$tv}&sortcol=feel">Feels<br>Like</a></th>
  <th><a href="current.phtml?tv={$tv}&sortcol=alti">Pres</a></th>
  <th><a href="current.phtml?tv={$tv}&sortcol=drct">Drct</a></th>
  <th><a href="current.phtml?tv={$tv}&sortcol=sknt">Speed</a></th>
  <th><a href="current.phtml?tv={$tv}&sortcol=peak">Today Gust</a> 
    <a href="current.phtml?tv={$tv}&sortcol=peak_ts">@time</a> [4]</th>
  <th><a href="current.phtml?tv={$tv}&sortcol=pday">Today</a></th>
  <th><a href="current.phtml?tv={$tv}&sortcol=pmonth">Month</a></th>
</tr>
</thead><tbody>

{$table}

</tbody>
<tfoot>
<tr>
<td colspan=3></td>
 <td><a href="{$c}tmpf');">Plot</a>
    (<a href="{$c}max_tmpf');">Plot</a> /
     <a href="{$c}min_tmpf');">Plot</a>)</td>
 <td><a href="{$c}dwpf');">Plot</a></td>
 <td><a href="{$c}relh');">Plot</a></td>
 <td><a href="{$c}feel');">Plot</a></td>
 <td><a href="{$c}pres');">Plot</a></td>
 <td colspan=2><a href="{$c}barb');">Plot</a></td>
 <td><a href="{$c}max_sknt');">Plot</a></td>
 <td><a href="{$c}pday');">Plot</a></td>
 <td><a href="{$c}pmonth');">Plot</a></td>
 
</tr>
</tfoot>
</table>

<input type="submit" value="Add to Favorites">
<input type="reset" value="Reset">

</form>

</td></tr></table>
</td></tr></table>
</td></tr></table>

<br><br>

<b>Notes:</b><br>
<b>1</b>Observation times listed are assigned to the observation based on the 
Mesonet system clock and not the observation clock which tends to drift.
<br><b>2</b> Wind values are 1 minute averages calculated by the IEM.

<br><br>
EOF;
$t->content = $content;
$t->render('sortables.phtml');
?>