<html>

<h3>Iowa Environmental Mesonet Archived Data Browser</h3>

<p>As much as I loathe FRAMED HTML pages, this is probably a good instance
to use them.  The top frame controls the time and mode of this application.
The side frame will display available information for your time and mode.  Well,
what do I mean by modes?

<p>Currently, this application has two data modes.  <i>Hourly</i> mode shows 
plots and data that is valid for a particular hour.  <i>Daily</i> mode shows
plots and data valid for the duration of a particular day.

<p>Do you have something you would like added?  Let me know!  Daryl 

</html>
