<?php 
include_once "../../config/settings.inc.php";
require_once "../../include/myview.php";
require_once "../../include/iemprop.php";
$gmapskey = get_iemprop("google.maps.key");
$OL = "6.2.1";

$t = new MyView();
$t->title = "SCADA Stuff";
$t->headextra = <<<EOF
<link rel="stylesheet" href="/vendor/openlayers/{$OL}/ol.css" type="text/css">
<link rel="stylesheet" href="/vendor/jquery-ui/1.11.4/jquery-ui.min.css" />
<link type="text/css" href="/vendor/openlayers/{$OL}/ol-layerswitcher.css" rel="stylesheet" />
EOF;
$t->jsextra = <<<EOF
<script src="/vendor/openlayers/{$OL}/ol.js" type="text/javascript"></script>
<script src="/vendor/jquery-ui/1.11.4/jquery-ui.js"></script>
<script src='/vendor/openlayers/{$OL}/ol-layerswitcher.js'></script>
<script src="map.js"></script>
EOF;
$t->content = <<<EOF

<br />
<a href="map_power.phtml">Map / Power Diagnostics by Minute</a>
		<hr>

<div class="row">
<div class="col-md-10">
<div id="map" style="width:100%; height:500px;"></div>
</div>
<div class="col-md-2">
<h4>Turbines in Wakes:</h4>
<br />0: <span id="t0">0</span>
<br />1: <span id="t1">0</span>
<br />2: <span id="t2">0</span>
<br />3: <span id="t3">0</span>
<br />4: <span id="t4">0</span>
<br />5+: <span id="t5">0</span>
<h4>Wakes over Turbines:</h4>
<br />0: <span id="w0">0</span>
<br />1: <span id="w1">0</span>
<br />2: <span id="w2">0</span>
<br />3: <span id="w3">0</span>
<br />4: <span id="w4">0</span>
<br />5+: <span id="w5">0</span>
</div>
</div>

<form>
<div class="row">
  <div class="col-md-3">
	<h4>Wind Direction</h4>
  	<div id="dirslider">
  		<div id="dirslider-handle" class="ui-slider-handle"></div>
  	</div>
  </div>

  <div class="col-md-3">
	<h4>Turbine Blade Length</h4>
	<input type="text" size="5" value="39" id="bladeLength"> (m)
  </div>

  <div class="col-md-3">
	<h4>Wake Angle</h4>
  	<div id="angleslider">
  		<div id="angleslider-handle" class="ui-slider-handle"></div>
  	</div>
  </div>

  <div class="col-md-3">
	<h4>Downstream Wake Length</h4>
	<input type="text" size="7" value="1000" id="downstreamLength"> (m)
  </div>

</div>
</form>

EOF;

$t->render('single.phtml');
?>
