<?php 
include_once "../../config/settings.inc.php";
require_once "../../include/myview.php";
require_once "../../include/forms.php";

$day = isset($_GET["day"]) ? $_GET["day"] : 30;
$month = isset($_GET["month"]) ? $_GET["month"] : 7;
$year = isset($_GET["year"]) ? $_GET["year"] : 2013;
$hour = isset($_GET["hour"]) ? $_GET["hour"] : 20;
$minute = isset($_GET["minute"]) ? $_GET["minute"] : 0;

$yselect = yearSelect2(2013, $year, "year");
$mselect = monthSelect($month, "month");
$dselect = daySelect2($day, "day");
$hrselect = hourSelect($hour, "hour");
$miselect = minuteSelect($minute, "minute");

$ts = mktime($hour, $minute, 0, $month, $day, $year);
$img = sprintf("map_power_%s.png", date('YmdHi', $ts));

$ar = Array("yaw" => "Original", "yaw2" => "daryl corrected 12 Sep");

$t = new MyView();
$t->title = "Confidential MEC Stuff";
$t->content = <<<EOF
<ol class="breadcrumb">
 <li><a href="/scada/">SCADA Mainpage</a></li>
 <li class="active">Plot Turbine Farm Power at Given Time</li> 
</ol>

<form method="GET" name='a'>

<table class="table table-condensed" style="width: auto">
<thead><tr>
<th>Date:</th><th>Time:</th></tr>
</thead>
<tbody>
<tr><td>$yselect $mselect $dselect</td>
<td>$hrselect $miselect</td>
</tr>
</tbody>
</table>

		
		<input type="submit" value="Make Plot" />
		</form>

<p><img src="$img" />

EOF;

$t->render('single.phtml');
?>
