<?php 
require_once "../../config/settings.inc.php";
require_once "../../include/myview.php";
$t = new MyView();
$t->title = "GOES GIS Products";

$adir = date("Y/m/d");

$t->content = <<<EOF
<h3>GOES Satellite Imagery for GIS</h3>

<p>The IEM has a long history processing the GOES Satellite information into
formats and services appropriate for GIS.  This processing was based on the
GINI format of products provided by NOAA.  The IEM implemented a number of
services and archives based on this format.</p>

<p>With the advent of GOES-R and GOES-S, this GINI format was discontinued and
the IEM <a href="/onsite/news.phtml?id=1369">pulled the plug</a> on the various
GOES East services back in 2018 and now in late 2019 GOES West.</p>

<p>A renewed effort is now being made to process the new GOES-R and GOES-S data
into similar formats and services as before.  There is not a one-to-one match
here due to many reasons.</p>

<p>The source of our GOES data comes via <a href="https://www.unidata.ucar.edu/data/nimage.html">Unidata NIMAGE</a>
products, which nicely merge the netCDF tiles into consistent products. These
products use a geostationary satellite projection that the IEM attempts to 
natively store and use within the various services.</p>

<div class="row">
 <div class="col-md-6">

 <h3>Satellite native projections</h3>
<img src="goes_c13.png" class="img img-responsive" />
 <br /><a href="/data/gis/images/GOES/">current imagery folder</a>
 </div>
 
<div class="col-md-6">
 
 <h3>Ready for Google-Maps</h3>
 <img src="goes-gm.png" class="img img-responsive" />
 <br /><a href="/ogc/">Tile Map Service</a>
 <br /><a href="/ogc/openlayers_example.html">OpenLayers Example</a>
 
 </div>
</div>

<h4>Changes</h4>

<ul>
<li><strong>1 December 2019:</strong> GOES West products have stopped and everything
has been migrated to new workflows based on GOES-R (GOES-16) and GOES-S (GOES-17).</li>

<li><strong>30 January 2018:</strong> GOES East products and services have been removed</li>

<li><b>18 December 2017:</b> The GOES "East" satellite has been assigned now to
the recently launched GOES R/16 satelitte. Sadly, due to format changes and the
amount of CPU processing and disk storage needed, the IEM can likely no longer process
these datasets.  The old GOES "East" continues to transmit until the first week or 
so of January.</li>

<li><b>24 November 2014:</b> The Infrared Imagery is now color enhanced by
default.  The previous default grayscale was not very useful.  You can find
a color ramp <a href="legends/ir_ramp.png">here</a>.</li>
</ul>

<h3>OGC Web Map Service</h3>


<p><strong>GOES West infrared imagery</strong>
<br /><code>https://mesonet.agron.iastate.edu/cgi-bin/wms/goes/west_ir.cgi?</code>

<p><strong>GOES West Alaska infrared imagery</strong>
<br /><code>https://mesonet.agron.iastate.edu/cgi-bin/wms/goes/alaska_ir.cgi?</code>

<p><strong>GOES West Hawaii infrared imagery</strong>
<br /><code>https://mesonet.agron.iastate.edu/cgi-bin/wms/goes/hawaii_ir.cgi?</code>

<hr />


<p><strong>GOES West visible imagery</strong>
<br /><code>https://mesonet.agron.iastate.edu/cgi-bin/wms/goes/west_vis.cgi?</code>

<p><strong>GOES West Alaska visible imagery</strong>
<br /><code>https://mesonet.agron.iastate.edu/cgi-bin/wms/goes/alaska_vis.cgi?</code>

<p><strong>GOES West Hawaii visible imagery</strong>
<br /><code>https://mesonet.agron.iastate.edu/cgi-bin/wms/goes/hawaii_vis.cgi?</code>

<hr>


<p><strong>GOES West water vapor imagery</strong>
<br /><code>https://mesonet.agron.iastate.edu/cgi-bin/wms/goes/west_wv.cgi?</code>

<p><strong>GOES West Alaska water vapor imagery</strong>
<br /><code>https://mesonet.agron.iastate.edu/cgi-bin/wms/goes/alaska_wv.cgi?</code>

<p><strong>GOES West Hawaii water vapor imagery</strong>
<br /><code>https://mesonet.agron.iastate.edu/cgi-bin/wms/goes/hawaii_wv.cgi?</code>

<p><b>Note:</b>  To get the WMS capabilities, you need to add
<br /><code>VER=1.1.1&amp;SERVICE=WMS&amp;REQUEST=GetCapabilities</code>
<br />to the URIs above.  Your WMS application may require it.


<h3>Archive</h3>

<p>Since 20 Dec 2005, the IEM has archived 4km composites of East/West imagery.
<p>Since 8 March 2009, water vapor channel was added to the archive as well.
<p>Since 21 June 2011, the IEM started archiving GOES East and West vis,ir, and water vapor
imagery in PNG format on the AWIPS 211 projection.
<p>Since 14 March 2012, the IEM started archiving all of the GINI processed imagery.
<p>22 March 2012, removed the confusing filenames of including the GOES satellite
identifier in the filename.  This causes problems when the satellites change from
east to west.

<div class="iem-form">
<strong>Today's archive of imagery</strong>
<br /><code><a href="https://mesonet.agron.iastate.edu/archive/data/{$adir}/GIS/sat/">https://mesonet.agron.iastate.edu/archive/data/{$adir}/GIS/sat/</a></code>
<br/>The URL pattern contains the year, month, and day.  The datafiles have
timestamps in UTC.
</div>

<h3>Online Applications</h3>
<ul>

<li>The <a href="/GIS/apps/rview/warnings.phtml">RADAR &amp; NWS Warnings</a> app provides a neat web mapping interface combining
radar and satellite data along with NWS warning products.</li>

</ul>
EOF;
$t->render('single.phtml');
