<?php 
include("../../config/settings.inc.php");
$THISPAGE = "gis-satellite";
$TITLE = "IEM | GOES GIS Products";
include("$rootpath/include/header.php"); ?>

<h4>GOES Satellite Imagery for GIS</h4>

<p>The IEM receives a "real-time" feed of GOES East and West satellite imagery
in GINI format.  We process this into GIS-ready RASTERs for download and web
services.  This page details this dataset.

<table cellpadding="3" cellspacing="0" border="1">
<tr>
 <th>AWIPS native projections</th>
 <th>Reprojected into EPSG:4326 "lat/long"</th>
 <th>Ready for Google-Maps</th>
 </tr>
 
<tr>
 <td><img src="goes-gini-example.png" />
 <br /><a href="<?php echo $rooturl; ?>/data/gis/images/">current imagery folder</a></td>
 <td valign="top"><img src="goes4326_example.png" />
 <br /><a href="<?php echo $rooturl; ?>/data/gis/images/4326/goes">current imagery folder</a></td>
 <td valign="top"><img src="goes-gm.png" />
 <br /><a href="<?php echo $rooturl; ?>/ogc/">Tile Map Service</a>
 <br /><a href="<?php echo $rooturl; ?>/ogc/openlayers_example.html">OpenLayers Example</a></td>
 </tr>
 
</table>

<h4>IEM GOES Ingest Status</h4>

<?php 
 $fpbase = "/home/ldm/data/gis/images/awips211";
 $east = json_decode(file_get_contents("$fpbase/GOES_EAST_IR.json")); 
 $west = json_decode(file_get_contents("$fpbase/GOES_WEST_IR.json")); 
 
 ?>
<table border="1" cellspacing="0" cellpadding="3">
 <tr><th></th><th>Bird</th><th>Latest Imagery</th><th>JSON Metadata</th></tr>
 <tr><th>East</th>
 	<td><?php echo $east->{"meta"}->{"bird"}; ?></td>
 	<td><?php echo $east->{"meta"}->{"valid"}; ?></td>
 	<td><a href="../data/gis/images/awips211/GOES_EAST_IR.json">IR</a> - 
 	<a href="../data/gis/images/awips211/GOES_EAST_VIS.json">VIS</a> -
 	<a href="../data/gis/images/awips211/GOES_EAST_WV.json">WV</a></td> 
 	</tr>
 <tr><th>West</th>
 	<td><?php echo $west->{"meta"}->{"bird"}; ?></td>
 	<td><?php echo $west->{"meta"}->{"valid"}; ?></td>
 	 <td><a href="../data/gis/images/awips211/GOES_WEST_IR.json">IR</a> - 
 	<a href="../data/gis/images/awips211/GOES_WEST_VIS.json">VIS</a> -
 	<a href="../data/gis/images/awips211/GOES_WEST_WV.json">WV</a></td> 
 	</tr>
</table>


<p>The <a href="http://www.goes.noaa.gov/">GOES (Geostationary Satellite)</a> 
provide the commonly seen views of clouds from space.  The IEM receives a near
real-time feed of this data in GINI format and processes it into geo-referenced
PNG raster files.  A directory of these files can be found 
<a href="<?php echo $rooturl; ?>/data/gis/images/">here</a>, but the native grid
projections may be difficult for you to use.  The IEM projects this data onto a
simple lat/long grid (EPSG:4326) and you can find those files 
<a href="<?php echo $rooturl; ?>/data/gis/images/4326/goes/">here</a>. 
Besides the raw files, the IEM also provides <a href="../ogc/">OGC web-services</a>
of this imagery.

<h3>AWIPS Projection Data</h3>

<p>The raw GINI data files are provided on predefined grids used by the National
Weather Service AWIPS system.  Here is an attempt to cross reference these grid
numbers into Proj4 strings.

<table cellpadding="2" cellspacing="0" border="1">
<tr><th>AWIPS Grid</th><th>Proj4 String</th><th>ESRI Projection files</th></tr>
<tr><th>208</th><td>proj=merc lat_ts=20 x_0=0 y_0=0 a=6371200.0 b=6371200.0</td><td></td></tr>
<tr><th>211</th><td>proj=lcc lat_0=25 lat_1=25 lat_2=25 lon_0=-95 a=6371200.0 b=6371200.0</td>
<td><a href='awips211.aux.xml'>awips211.aux.xml</a> <a href='awips211.prj'>awips211.prj</a> </td></tr>
</table>

<p>These AWIPS projection imagery files can be found <a href="<?php echo $rooturl; ?>/data/gis/images/">here</a>.
 You will find three files for each image: the raw PNG imagery, the world file, and a 
 JSON formatted metadata file.

<h3>OGC Web Map Service</h3>

<strong>Conus GOES visible imagery</strong>
<br /><code>http://mesonet.agron.iastate.edu/cgi-bin/wms/goes/conus_vis.cgi?</code>

<p><strong>Conus GOES infrared imagery</strong>
<br /><code>http://mesonet.agron.iastate.edu/cgi-bin/wms/goes/conus_ir.cgi?</code>

<p><strong>Conus GOES water vapor  imagery</strong>
<br /><code>http://mesonet.agron.iastate.edu/cgi-bin/wms/goes/conus_wv.cgi?</code>

<hr />

<p><strong>GOES East infrared imagery</strong>
<br /><code>http://mesonet.agron.iastate.edu/cgi-bin/wms/goes/east_ir.cgi?</code>

<p><strong>GOES West infrared imagery</strong>
<br /><code>http://mesonet.agron.iastate.edu/cgi-bin/wms/goes/west_ir.cgi?</code>

<p><strong>GOES West Alaska infrared imagery</strong>
<br /><code>http://mesonet.agron.iastate.edu/cgi-bin/wms/goes/alaska_ir.cgi?</code>

<p><strong>GOES West Hawaii infrared imagery</strong>
<br /><code>http://mesonet.agron.iastate.edu/cgi-bin/wms/goes/hawaii_ir.cgi?</code>

<hr />

<p><strong>GOES East visible imagery</strong>
<br /><code>http://mesonet.agron.iastate.edu/cgi-bin/wms/goes/east_vis.cgi?</code>

<p><strong>GOES West visible imagery</strong>
<br /><code>http://mesonet.agron.iastate.edu/cgi-bin/wms/goes/west_vis.cgi?</code>

<p><strong>GOES West Alaska visible imagery</strong>
<br /><code>http://mesonet.agron.iastate.edu/cgi-bin/wms/goes/alaska_vis.cgi?</code>

<p><strong>GOES West Hawaii visible imagery</strong>
<br /><code>http://mesonet.agron.iastate.edu/cgi-bin/wms/goes/hawaii_vis.cgi?</code>

<hr>

<p><strong>GOES East water vapor imagery</strong>
<br /><code>http://mesonet.agron.iastate.edu/cgi-bin/wms/goes/east_wv.cgi?</code>

<p><strong>GOES West water vapor imagery</strong>
<br /><code>http://mesonet.agron.iastate.edu/cgi-bin/wms/goes/west_wv.cgi?</code>

<p><strong>GOES West Alaska water vapor imagery</strong>
<br /><code>http://mesonet.agron.iastate.edu/cgi-bin/wms/goes/alaska_wv.cgi?</code>

<p><strong>GOES West Hawaii water vapor imagery</strong>
<br /><code>http://mesonet.agron.iastate.edu/cgi-bin/wms/goes/hawaii_wv.cgi?</code>

<p><b>Note:</b>  To get the WMS capabilities, you need to add
<br /><code>VER=1.1.1&amp;SERVICE=WMS&amp;REQUEST=GetCapabilities</code>
<br />to the URIs above.  Your WMS application may require it.


<h3>Archive</h3>

<p>Since 20 Dec 2005, the IEM has archived 4km composites of East/West imagery.
<p>Since 8 March 2009, water vapor channel was added to the archive as well.
<p>Since 21 June 2011, the IEM started archiving GOES East and West vis,ir, and water vapor
imagery in PNG format on the AWIPS 211 projection.
<p>Since 14 March 2012, the IEM started archiving all of the GINI processed imagery.
<p>22 March 2012, removed the confusing filenames of including the GOES satellite
identifier in the filename.  This causes problems when the satellites change from
east to west.

<div class="iem-form">
<strong>Today's archive of imagery</strong>
<br /><code><a href="http://mesonet.agron.iastate.edu/archive/data/<?php echo date("Y/m/d"); ?>/GIS/sat/">http://mesonet.agron.iastate.edu/archive/data/<?php echo date("Y/m/d"); ?>/GIS/sat/</a></code>
<br/>The URL pattern contains the year, month, and day.  The datafiles have
timestamps in UTC.
</div>

<h3>Online Applications</h3>
<ul>

<li>The <a href="http://mesonet.agron.iastate.edu/GIS/apps/rview/warnings.phtml">RADAR &amp; NWS Warnings</a> app provides a neat web mapping interface combining
radar and satellite data along with NWS warning products.</li>

</ul>
<?php include("$rootpath/include/footer.php"); ?>
