<?php 
include("../../config/settings.inc.php");
$THISPAGE = "gis-satellite";
$TITLE = "IEM | GOES GIS Products";
include("$rootpath/include/header.php"); ?>

<h4>GOES Satellite Imagery for GIS</h4>

<img src="vis_example.jpg" />

<p>The <a href="http://www.goes.noaa.gov/">GOES (Geostationary Satellite)</a> 
provide the commonly seen views of clouds from space.  The IEM receives a near
real-time feed of this data in GINI format and processes it into geo-referenced
PNG raster files.  A directory of these files can be found 
<a href="<?php echo $rooturl; ?>/data/gis/images/">here</a>, but the native grid
projections may be difficult for you to use.  The IEM projects this data onto a
simple lat/long grid (EPSG:4326) and you can find those files 
<a href="<?php echo $rooturl; ?>/data/gis/images/4326/goes/">here</a>. 
Besides the raw files, the IEM also provides <a href="../ogc/">OGC web-services</a>
of this imagery.

<h3>AWIPS Projection Data</h3>

<p>The raw GINI data files are provided on predefined grids used by the National
Weather Service AWIPS system.  Here is an attempt to cross reference these grid
numbers into Proj4 strings.

<table cellpadding="2" cellspacing="0" border="1">
<tr><th>AWIPS Grid</th><th>Proj4 String</th></tr>
<tr><th>208</th><td>proj=merc lat_ts=20 x_0=0 y_0=0 a=6371200.0 b=6371200.0</td></tr>
<tr><th>211</th><td>proj=lcc lat_0=25 lat_1=25 lat_2=25 lon_0=-95 a=6371200.0 b=6371200.0</td></tr>
</table>

<p>These AWIPS projection imagery files can be found <a href="<?php echo $rooturl; ?>/data/gis/images/">here</a>.
 You will find three files for each image: the raw PNG imagery, the world file, and a 
 JSON formatted metadata file.

<h3>OGC Web Map Service</h3>

<strong>Conus GOES visible imagery</strong>
<br /><code>http://mesonet.agron.iastate.edu/cgi-bin/wms/goes/conus_vis.cgi?</code>

<p><strong>Conus GOES infrared imagery</strong>
<br /><code>http://mesonet.agron.iastate.edu/cgi-bin/wms/goes/conus_ir.cgi?</code>

<p><strong>Conus GOES water vapor  imagery</strong>
<br /><code>http://mesonet.agron.iastate.edu/cgi-bin/wms/goes/conus_wv.cgi?</code>

<hr />

<p><strong>GOES East infrared imagery</strong>
<br /><code>http://mesonet.agron.iastate.edu/cgi-bin/wms/goes/east_ir.cgi?</code>

<p><strong>GOES West infrared imagery</strong>
<br /><code>http://mesonet.agron.iastate.edu/cgi-bin/wms/goes/west_ir.cgi?</code>

<p><strong>GOES West Alaska infrared imagery</strong>
<br /><code>http://mesonet.agron.iastate.edu/cgi-bin/wms/goes/alaska_ir.cgi?</code>

<p><strong>GOES West Hawaii infrared imagery</strong>
<br /><code>http://mesonet.agron.iastate.edu/cgi-bin/wms/goes/hawaii_ir.cgi?</code>

<hr />

<p><strong>GOES East visible imagery</strong>
<br /><code>http://mesonet.agron.iastate.edu/cgi-bin/wms/goes/east_vis.cgi?</code>

<p><strong>GOES West visible imagery</strong>
<br /><code>http://mesonet.agron.iastate.edu/cgi-bin/wms/goes/west_vis.cgi?</code>

<p><strong>GOES West Alaska visible imagery</strong>
<br /><code>http://mesonet.agron.iastate.edu/cgi-bin/wms/goes/alaska_vis.cgi?</code>

<p><strong>GOES West Hawaii visible imagery</strong>
<br /><code>http://mesonet.agron.iastate.edu/cgi-bin/wms/goes/hawaii_vis.cgi?</code>

<hr>

<p><strong>GOES East water vapor imagery</strong>
<br /><code>http://mesonet.agron.iastate.edu/cgi-bin/wms/goes/east_wv.cgi?</code>

<p><strong>GOES West water vapor imagery</strong>
<br /><code>http://mesonet.agron.iastate.edu/cgi-bin/wms/goes/west_wv.cgi?</code>

<p><strong>GOES West Alaska water vapor imagery</strong>
<br /><code>http://mesonet.agron.iastate.edu/cgi-bin/wms/goes/alaska_wv.cgi?</code>

<p><strong>GOES West Hawaii water vapor imagery</strong>
<br /><code>http://mesonet.agron.iastate.edu/cgi-bin/wms/goes/hawaii_wv.cgi?</code>

<p><b>Note:</b>  To get the WMS capabilities, you need to add
<br /><code>VER=1.1.1&amp;SERVICE=WMS&amp;REQUEST=GetCapabilities</code>
<br />to the URIs above.  Your WMS application may require it.


<h3>Archive</h3>

<p>Since 20 Dec 2005, the IEM has archived 4km composites of East/West imagery.
<p>Since 8 March 2009, water vapor channel was added to the archive as well.
<p>Since 21 June 2011, the IEM started archiving GOES East and West vis,ir, and water vapor
imagery in PNG format on the AWIPS 211 projection.
<p>Since 14 March 2012, the IEM started archiving all of the GINI formatted
satellite imagery.

<div class="iem-form">
<strong>Today's archive of imagery</strong>
<br /><code><a href="http://mesonet.agron.iastate.edu/archive/data/<?php echo date("Y/m/d"); ?>/GIS/sat/">http://mesonet.agron.iastate.edu/archive/data/<?php echo date("Y/m/d"); ?>/GIS/sat/</a></code>
<br/>The URL pattern contains the year, month, and day.  The datafiles have
timestamps in UTC.
</div>

<h3>Online Applications</h3>
<ul>

<li>The <a href="http://mesonet.agron.iastate.edu/GIS/apps/rview/warnings.phtml">RADAR &amp; NWS Warnings</a> app provides a neat web mapping interface combining
radar and satellite data along with NWS warning products.</li>

</ul>
<?php include("$rootpath/include/footer.php"); ?>
