<?php
include("../../config/settings.inc.php");
include("$rootpath/include/forms.php");

$day = isset($_GET["day"]) ? intval($_GET["day"]) : date("d", time());
$month = isset($_GET["month"]) ? intval($_GET["month"]) : date("m", time());
$hour = isset($_GET["hour"]) ? intval($_GET["hour"]) : date("H", time());
$minute = isset($_GET["minute"]) ? intval($_GET["minute"]) : date("i", 0);
$sz = isset($_GET["sz"]) ? floatval($_GET["sz"]) : 2.5;

/* Do areal extents */
$map_x = isset($_GET["map_x"]) ? $_GET["map_x"]: 0;
$map_y = isset($_GET["map_y"]) ? $_GET["map_y"]: 0;
$ul_x = -126.0;
$ul_y = 50.0;
$lr_y = 24.0;
$lr_x = -66.0;
if ($map_x != 0 && $map_y != 0)
{
  $dx = ($ul_x - $lr_x) / 300.0;
  $dy = ($ul_y - $lr_y) / 130.0;
  $clickx = ($map_x * (0 - $dx) ) + $ul_x;
  $clicky = ($map_y * (0 - $dy) ) + $ul_y;
  $sz_x = floatval($sz);
  $sz_y = floatval($sz) * 7.0 / 8.0 ;

  $extents = Array($clickx - $sz_x, $clicky - $sz_y, $clickx + $sz_x, $clicky + $sz_y);

} else if (isset($_GET["osz"]) && $sz != $_GET["osz"]){
  $oextents = explode(",", $_GET["oextents"]);
  $clickx = $oextents[0] + (($oextents[2] - $oextents[0]) / 2.0);
  $clicky = $oextents[1] + (($oextents[3] - $oextents[1]) / 2.0);
  $sz_x = floatval($sz) ;
  $sz_y = floatval($sz) * 7.0 / 8.0 ;
  $extents = Array($clickx - $sz_x, $clicky - $sz_y, $clickx + $sz_x, $clicky + $sz_y);

} else if (isset($_GET["oextents"])){
  $extents = explode(",", $_GET["oextents"]);
} else {
  $extents = Array(-105,40,-97,47);
}


$ourl = sprintf("rby-overview.php?BBOX=%s,%s,%s,%s",  $extents[0], $extents[1], $extents[2], $extents[3]);
$url = sprintf("rad-by-year.php?month=%s&day=%s&hour=%s&minute=%s&BBOX=%s,%s,%s,%s", $month, $day, $hour, $minute, $extents[0], $extents[1], $extents[2], $extents[3]);

$THISPAGE = "gis-nexrad";
$TITLE = "IEM NEXRAD by Year";
include("$rootpath/include/header.php");
?>

<h3 class="heading">IEM NEXRAD Composite by Year</h3>

<p>This application generates a summary image of IEM generated NEXRAD composites for a given time over the archives duration.  You can click on the map to move the desired location.</p>

<form method="GET" action="rad-by-year-fe.phtml" name="Selector">
<input type="hidden" name="oextents" value="<?php echo implode(",", $extents); ?>">
<input type="hidden" name="osz" value="<?php echo $sz; ?>">
<table cellpadding="2" border="0" cellspacing="0">
<tr><th>Select Area</th><th colspan="2">Select Date</th></tr>
<tr>
<td rowspan="5">
  <input type="image" src="<?php echo $ourl; ?>" name="map">
<br /><strong>Select Rough Box Size</strong>
<select name="sz">
 <option value="0.5" <?php if ($sz == 0.5){ echo "SELECTED"; } ?>>100 km 
 <option value="1" <?php if ($sz == 1){ echo "SELECTED"; } ?>>200 km 
 <option value="2.5" <?php if ($sz == 2.5){ echo "SELECTED"; } ?>>500 km 
 <option value="5" <?php if ($sz == 5){ echo "SELECTED"; } ?>>1000 km 
 <option value="20" <?php if ($sz == 20){ echo "SELECTED"; } ?>>4000 km 
</select>
</td>
<td>Month:</td><td><?php echo monthSelect($month, "month"); ?></td></tr>
<tr><td>Day:</td><td><?php echo daySelect($day, "day"); ?></td></tr>
<tr><td>Hour:</td><td><?php echo hourSelect($hour, "hour"); ?></td></tr>
<tr><td>Minute:</td><td><?php echo local5MinuteSelect($minute, "minute"); ?></td></tr>
<tr><td colspan="2"><input type="submit" value="Generate Image"></td></tr>
</table>
</form>
<p><i>The image below may take a few moments to appear...</i><br />
<img src="<?php echo $url; ?>">

<?php
include("$rootpath/include/footer.php");
?>
