<?php
$OL = "6.2.1";
 require_once "../../../config/settings.inc.php";
 require_once "../../../include/myview.php";
 require_once "../../../include/database.inc.php";
 require_once "../../../include/imagemaps.php";
 require_once "../../../include/forms.php";
 $t = new MyView();

 $station = isset($_GET['station']) ? xssafe($_GET["station"]): "";
 $network = isset($_GET["network"]) ? xssafe($_GET['network']): "IA_ASOS";
 $year = isset($_GET['year']) ? intval($_GET['year']): date("Y");
 $month = isset($_GET['month']) ? intval($_GET['month']): date("m");

$t->thispage = "climatology-month";
$t->headextra = <<<EOF
<link rel="stylesheet" href="/vendor/openlayers/{$OL}/ol.css" type="text/css">
<link type="text/css" href="/vendor/openlayers/{$OL}/ol-layerswitcher.css" rel="stylesheet" />
<link rel="stylesheet" type="text/css" href="/vendor/select2/4.0.3/select2.min.css"/ >
EOF;
$t->jsextra = <<<EOF
<script src="/vendor/openlayers/{$OL}/ol.js" type="text/javascript"></script>
<script src='/vendor/openlayers/{$OL}/ol-layerswitcher.js'></script>
<script src="/js/olselect.php?network=${network}"></script>
<script src="/vendor/select2/4.0.3/select2.min.js"></script>
<script type="text/javascript">
$(document).ready(function(){
	$(".iemselect2").select2();	
});
</script>
EOF;

$t->title = "Monthly Rainfall Traces";

$content = <<<EOF
<style type="text/css">
        #map {
            width: 450px;
            height: 450px;
            border: 2px solid black;
        }
</style>

<h3 class="heading">Monthly Rainfall Traces</h3>

<p>This application creates a plot of observed precipitation versus 
climatology for a site of your choice in Iowa. 
EOF;
if (strlen($station) > 0 ) { 
	$nselect = networkSelect($network,$station);
	$yselect = yearSelect(2004,$year,"year");
	$mselect = monthSelect($month);
	$content .= <<<EOF
<form name="ds" action="rainfall.phtml" method="GET">
<input type="hidden" value="{$network}" name="network">
<table cellspacing=2 border=1 cellpadding=2>
<tr><th>Site ID:</th><th>Select Year:</th><th>Select Month:</th></tr>
<tr><td>{$nselect}
<a href="rainfall.phtml?network={$network}">Select from map</a></td>
  <td>{$yselect}</td>
    <td>{$mselect}</td></tr>
</table>
<input type="submit" value="Make Plot">
</form>

<p><img src="/plotting/auto/plot/17/month:{$month}::year:{$year}::station:{$station}::network:{$network}::p:precip.png" alt="Time Series" />
EOF;
} else { 
	$nselect = networkSelect($network, "");
	$content .= <<<EOF

<br /><a href="rainfall.phtml?network=IA_ASOS">Iowa ASOS</a> &nbsp; 
<a href="rainfall.phtml?network=AWOS">Iowa AWOS</a> &nbsp; 
<a href="rainfall.phtml?network=IA_COOP">Iowa NWS COOP</a> &nbsp; 
<a href="rainfall.phtml?network=KCCI">KCCI-TV SchoolNet</a> &nbsp; 

<form name="olselect">
<input type="hidden" value="{$network}" name="network">
<table><tr><th>Select Station</th>
<td>{$nselect}</td>
<td><input type="submit" value="Make Plot"></tr></table>
<div id="map"></div>
</form>
EOF;
} 
$t->content = $content;
$t->render('single.phtml');
?>
