<?php 
include("../../../config/settings.inc.php");
$network = isset($_GET['network']) ? $_GET["network"] : 'IA_DCP';
$TITLE = "IEM | DCP Data Download";
$THISPAGE = "networks-dcp";
include("$rootpath/include/header.php"); 
 include("$rootpath/include/imagemaps.php");
 include("$rootpath/include/forms.php"); 
?>

<p>Filling out this form will provide you with whatever archive data the
IEM has from the DCP network.  The archive has some holes in it....

<form method="GET" name="chstate">
<p><strong>Select State:</strong> <select name="network">
 <option value="AL_DCP" <?php if ($network == "AL_DCP") echo "SELECTED"; ?>>Alabama
 <option value="AK_DCP" <?php if ($network == "AK_DCP") echo "SELECTED"; ?>>Alaska
 <option value="AR_DCP" <?php if ($network == "AR_DCP") echo "SELECTED"; ?>>Arkansas
 <option value="AZ_DCP" <?php if ($network == "AZ_DCP") echo "SELECTED"; ?>>Arizona
 <option value="CA_DCP" <?php if ($network == "CA_DCP") echo "SELECTED"; ?>>California
 <option value="CO_DCP" <?php if ($network == "CO_DCP") echo "SELECTED"; ?>>Colorado
 <option value="CT_DCP" <?php if ($network == "CT_DCP") echo "SELECTED"; ?>>Connecticut
 <option value="DE_DCP" <?php if ($network == "DE_DCP") echo "SELECTED"; ?>>Delaware
 <option value="FL_DCP" <?php if ($network == "FL_DCP") echo "SELECTED"; ?>>Florida
 <option value="GA_DCP" <?php if ($network == "GA_DCP") echo "SELECTED"; ?>>Georgia
 <option value="HI_DCP" <?php if ($network == "HI_DCP") echo "SELECTED"; ?>>Hawaii
 <option value="ID_DCP" <?php if ($network == "ID_DCP") echo "SELECTED"; ?>>Idaho
 <option value="IL_DCP" <?php if ($network == "IL_DCP") echo "SELECTED"; ?>>Illinois
 <option value="IN_DCP" <?php if ($network == "IN_DCP") echo "SELECTED"; ?>>Indiana
 <option value="IA_DCP" <?php if ($network == "IA_DCP") echo "SELECTED"; ?>>Iowa
 <option value="KS_DCP" <?php if ($network == "KS_DCP") echo "SELECTED"; ?>>Kansas
 <option value="KY_DCP" <?php if ($network == "KY_DCP") echo "SELECTED"; ?>>Kentucky
 <option value="LA_DCP" <?php if ($network == "LA_DCP") echo "SELECTED"; ?>>Louisana
 <option value="ME_DCP" <?php if ($network == "ME_DCP") echo "SELECTED"; ?>>Maine
 <option value="MD_DCP" <?php if ($network == "MD_DCP") echo "SELECTED"; ?>>Maryland
 <option value="MA_DCP" <?php if ($network == "MA_DCP") echo "SELECTED"; ?>>Massachusetts
 <option value="MI_DCP" <?php if ($network == "MI_DCP") echo "SELECTED"; ?>>Michigan
 <option value="MN_DCP" <?php if ($network == "MN_DCP") echo "SELECTED"; ?>>Minnesota
 <option value="MS_DCP" <?php if ($network == "MS_DCP") echo "SELECTED"; ?>>Mississippi
 <option value="MO_DCP" <?php if ($network == "MO_DCP") echo "SELECTED"; ?>>Missouri
 <option value="MT_DCP" <?php if ($network == "MT_DCP") echo "SELECTED"; ?>>Montana
 <option value="NE_DCP" <?php if ($network == "NE_DCP") echo "SELECTED"; ?>>Nebraska
 <option value="NH_DCP" <?php if ($network == "NH_DCP") echo "SELECTED"; ?>>New Hampshire
 <option value="NC_DCP" <?php if ($network == "NC_DCP") echo "SELECTED"; ?>>North Carolina
 <option value="ND_DCP" <?php if ($network == "ND_DCP") echo "SELECTED"; ?>>North Dakota
 <option value="NV_DCP" <?php if ($network == "NV_DCP") echo "SELECTED"; ?>>Nevada
 <option value="NH_DCP" <?php if ($network == "NH_DCP") echo "SELECTED"; ?>>New Hampshire
 <option value="NJ_DCP" <?php if ($network == "NJ_DCP") echo "SELECTED"; ?>>New Jersey
 <option value="NM_DCP" <?php if ($network == "NM_DCP") echo "SELECTED"; ?>>New Mexico
 <option value="NY_DCP" <?php if ($network == "NY_DCP") echo "SELECTED"; ?>>New York
 <option value="OH_DCP" <?php if ($network == "OH_DCP") echo "SELECTED"; ?>>Ohio
 <option value="OK_DCP" <?php if ($network == "OK_DCP") echo "SELECTED"; ?>>Oklahoma
 <option value="OR_DCP" <?php if ($network == "OR_DCP") echo "SELECTED"; ?>>Oregon
 <option value="PA_DCP" <?php if ($network == "PA_DCP") echo "SELECTED"; ?>>Pennsylvania
 <option value="RI_DCP" <?php if ($network == "RI_DCP") echo "SELECTED"; ?>>Rhode Island
 <option value="SC_DCP" <?php if ($network == "SC_DCP") echo "SELECTED"; ?>>South Carolina
 <option value="SD_DCP" <?php if ($network == "SD_DCP") echo "SELECTED"; ?>>South Dakota
 <option value="TN_DCP" <?php if ($network == "TN_DCP") echo "SELECTED"; ?>>Tennessee
 <option value="TX_DCP" <?php if ($network == "TX_DCP") echo "SELECTED"; ?>>Texas
 <option value="UT_DCP" <?php if ($network == "UT_DCP") echo "SELECTED"; ?>>Utah
 <option value="VT_DCP" <?php if ($network == "VT_DCP") echo "SELECTED"; ?>>Vermont
 <option value="VA_DCP" <?php if ($network == "VA_DCP") echo "SELECTED"; ?>>Virginia
 <option value="WA_DCP" <?php if ($network == "WA_DCP") echo "SELECTED"; ?>>Washington
 <option value="WV_DCP" <?php if ($network == "WV_DCP") echo "SELECTED"; ?>>West Virginia
 <option value="WI_DCP" <?php if ($network == "WI_DCP") echo "SELECTED"; ?>>Wisconsin
 <option value="WY_DCP" <?php if ($network == "WY_DCP") echo "SELECTED"; ?>>Wyoming
</select>
<input type="submit" value="Select State" />
</form>


<form method="GET" action="dl.php" name='dl'>
<input type='hidden' name='network' value="<?php echo $network; ?>" />

<table>
<tr><td width="50%">

<p><h3 class="subtitle">1. Select Station:</h3><br>
<?php echo networkMultiSelect($network, ""); ?>

<p><h3 class="subtitle">2. Select Start/End Time:</h3><br>
<i>Times are in UTC. Archive starts in 2002 for Iowa, 9 Dec 2010 for all others.</i>
<table>
  <tr>
    <td></td>
    <th>Year</th><th>Month</th><th>Day</th>
    <th>Hour</th>
  </tr>

  <tr>
    <th>Start:</th>
    <td rowspan="2">
     <?php echo yearSelect(2002, date("Y"), "year"); ?>
    </td>
    <td>
     <?php echo monthSelect("", "month1"); ?>
    </td>
    <td>
     <?php echo daySelect2("", "day1"); ?>
    </td>
    <td>
     <?php echo gmtHourSelect("", "hour1"); ?>
	<input type="hidden" name="minute1" value="0">
    </td>
  </tr>

  <tr>
    <th>End:</th>
    <td>
     <?php echo monthSelect("", "month2"); ?>
    </td>
    <td>
     <?php echo daySelect2("", "day2"); ?>
    </td>
    <td>
     <?php echo gmtHourSelect("", "hour2"); ?>
	<input type="hidden" name="minute2" value="0">
    </td>
  </tr>
</table>

</td><td valign="TOP">

<p><h3 class="subtitle">3. How to view?</h3><br>
<select name="what">
  <option value="download">Download to Disk
  <option value="view">View on-line
</select>

<p><h3 class="subtitle">4. Data Delimitation:</h3><br>
How shall the output values be seperated?
<br><select name="delim">
    <option value="comma">Comma
    <option value="space">Space
    <option value="tab">Tab
   </select>

</td></tr></table>

<p><h3 class="subtitle">Submit Form:</h3><br>
<input type="submit" value="Process Data Request">
<input type="reset">
</form>

<?php include("$rootpath/include/footer.php"); ?>
