<?php
/* Map a warning and LSRs */

$poid = isset($_GET["poid"]) ? intval($_GET["poid"]) : die("Booooo");
$sts = isset($_GET["sts"]) ? strtotime($_GET["sts"]) : die("Booooo");
$ets = isset($_GET["ets"]) ? strtotime($_GET["ets"]) : die("Booooo");
$lat0 = isset($_GET["lat0"]) ? $_GET["lat0"] : die("Boooo");
$lon0 = isset($_GET["lon0"]) ? $_GET["lon0"] : die("Boooo");

$stsSQL = date("Y-m-d H:i", $sts);
$etsSQL = date("Y-m-d H:i", $ets);

dl($mapscript);

$map = ms_newMapObj("$rootpath/GIS/apps/rview/mosaic2.map");

$map->setProjection("proj=latlong");
$lpad = 1.0;
$map->setextent($lon0 - $lpad,
                $lat0 - $lpad,
                $lon0 + $lpad,
                $lat0 + $lpad);


$namer = $map->getlayerbyname("namerica");
$namer->set("status", 1);

$stlayer = $map->getlayerbyname("states");
$stlayer->set("status", 1);

$lakes = $map->getlayerbyname("lakes");
$lakes->set("status", 1);

$clayer = $map->getlayerbyname("counties_unproj");
$clayer->set("status", 1);

$c0 = $map->getlayerbyname("warnings0_c");
$c0->set("status", 1);
$c0->set("data", "geom from warnings_$year");
$c0->setFilter("oid = $coid");

$p0 = $map->getlayerbyname("warnings0_p");
$p0->set("status", 1);
$p0->set("data", "geom from warnings_$year");
$p0->setFilter("oid = $poid");

$lsrs = $map->getlayerbyname("lsrs");
$lsrs->set("status",1);
$lsrs->setFilter("valid >= '$stsSQL' and valid < '$etsSQL'");

$img = $map->prepareImage();

$namer->draw($img);
$clayer->draw( $img );
$stlayer->draw( $img);
$lakes->draw($img);
$c0->draw($img);
$p0->draw($img);
$lsrs->draw($img);

//mktitle($map, $img, "                  IEM NEXRAD composite base reflect valid:
$d");
$map->drawLabelCache($img);
//mklogolocal($map, $img);

$url = $img->saveWebImage(MS_PNG);


?>
<img src="<?php echo $url; ?>">
