<?php 
include("../../../config/settings.inc.php");
$TITLE = "IEM | Iowa Caucus Weather";
include("$rootpath/include/header.php"); 
?>

<div style="width: 600px;">

<div class="ptitle"><img src="logo.gif">2004 Iowa Caucus Day</div>

<p>The Iowa Caucus is just a few days away.  The weather on Monday could play 
a major role in voter demographic turnout.  This page contains reasources for
Iowa's weather on Caucus Day (19 Jan 2004).  Information provided is for
educational use only.</p>

<div style="padding: 10px; border-style: solid; border-color: #000000; border-width: 1px;">

<div style="text-align: center; font-size: large; font-color: #0000f0;">Forecast Discussion</div>

<?php include("fx.txt"); ?>

<div style="text-align: center; font-size: large; font-color: #0000f0;">Average Temperatures for 19 Jan</div>

<p><table border=1 cellpadding=3 cellspacing=0>
<tr>
<th>City:</th><th>High: (&deg;F)</th><th>Low: (&deg;F)</th></tr>

<tr><th>Cedar Rapids</th><th>33</th><th>12</th></tr>
<tr><th>Des Moines</th><th>33</th><th>12</th></tr>
<tr><th>Dubuque</th><th>28</th><th>9</th></tr>
<tr><th>Iowa City</th><th>33</th><th>13</th></tr>
<tr><th>Sioux City</th><th>29</th><th>9</th></tr>
<tr><th>Waterloo</th><th>27</th><th>7</th></tr>

</table>

</div>
</div>

<?php include("$rootpath/include/footer.php"); ?>
