<?php
 $station = isset($_GET['station']) ? $_GET['station']: "";
 $network = isset($network) ? $_GET['network'] : "IA_ASOS";
 $year = isset($_GET['year']) ? $_GET['year'] : date("Y");
 $smonth = isset($_GET['smonth']) ? $_GET['smonth'] : 5;
 $emonth = isset($_GET['emonth']) ? $_GET['emonth'] : 10;
 $sday = isset($_GET['sday']) ? $_GET['sday'] : 1;
 $eday = isset($_GET['eday']) ? $_GET['eday'] : 1;
 include("../../../config/settings.inc.php");
include("$rootpath/include/database.inc.php");
include("$rootpath/include/google_keys.php");
include("$rootpath/include/imagemaps.php");
$api = $GOOGLEKEYS[$rooturl]["any"];
$HEADEXTRA = "<script src='http://maps.google.com/maps?file=api&amp;v=2&amp;key=$api'></script>
<script src='http://www.openlayers.org/api/OpenLayers.js'></script>
<script src='${rooturl}/js/olselect.php?network=${network}'></script>";
$BODYEXTRA = "onload=\"init()\"";
$THISPAGE = "climatology-season";
$TITLE = "IEM | Accumulated Values versus Climatology";
include("$rootpath/include/header.php"); ?>
<style type="text/css">
        #map {
            width: 450px;
            height: 450px;
            border: 2px solid black;
        }
</style>

<h3 class="heading">Growing Season Traces</h3>

<p>This application generates a plot of observed rainfall + temperatures 
versus climatology.  This application should be used with extreme caution
since it uses non quality controlled observations.  There is also missing data which
can cause errors in the accumulated values.</p>

<div class="text">
<P>Pick network to select station from:
<br><a href="fe.phtml?network=IA_ASOS">ASOS</a>
 -or- <a href="fe.phtml?network=AWOS">AWOS</a>
 -or- <a href="fe.phtml?network=IA_COOP">NWS COOP</a>
 -or- <a href="fe.phtml?network=KCCI">KCCI SchoolNet</a>

<?php if (strlen($station) > 0 ) { ?>
<?php include_once("$rootpath/include/forms.php"); ?>
<form name="ds" action="fe.phtml" method="GET">
<table cellspacing=2 border=1 cellpadding=2>
<thead>
<tr><th>Site ID:</th><th>Year:</th><th>Start Date:</th><th>End Date:</th></tr>
</thead>
<tbody>
<tr><td><?php echo networkSelect($network, $station); ?></td>
  <td><?php echo yearSelect(2004,$year,"year"); ?></td>
  <td><?php echo monthSelect($smonth,"smonth"); ?><?php echo daySelect($sday,"sday"); ?></td>
  <td><?php echo monthSelect($emonth,"emonth"); ?><?php echo daySelect($eday,"eday"); ?></td>
</tr>
</tbody>
</table>
<input type="submit" value="Make Plot">
</form>

<p><img src="gdd_plot.php?<?php echo "station=$station&year=$year&smonth=$smonth&sday=$sday&emonth=$emonth&eday=$eday"; ?>" ALT="Time Series">
<p><img src="rainfall_plot.php?<?php echo "station=$station&year=$year&smonth=$smonth&sday=$sday&emonth=$emonth&eday=$eday"; ?>" ALT="Time Series">

<?php } else { ?>

<form name="olselect">
<input type="hidden" value="<?php echo $network; ?>" name="network">
<table><tr><th>Select Station</th>
<td><?php echo networkSelect($network, $station); ?></td>
<td><input type="submit" value="Make Plot"></tr></table>
<div id="map"></div>
<div id="sname" unselectable="on">No site selected</div>
</form>


<?php } ?>
</div>

<?php include("$rootpath/include/footer.php"); ?>
