<?php
 $station = isset($_GET['station']) ? $_GET['station']: "";
 $network = isset($network) ? $_GET['network'] : "IA_ASOS";
 $year = isset($_GET['year']) ? $_GET['year'] : date("Y");
 $month = isset($_GET['month']) ? $_GET['month'] : date("m");
 include("../../../config/settings.inc.php");
 include("$rootpath/include/selectWidget.php");
 $sw = new selectWidget("fe.phtml", "fe.phtml?", $network);
 $sw->logic($_GET);
?>

<?php 	$TITLE = "IEM | Growing Season Traces";
include("$rootpath/include/header.php"); ?>

<h3 class="heading">Growing Season Traces</h3>

<p>This application generates a plot of observed rainfall + temperatures 
versus climatology.  This application should be used with extreme caution
since it uses non quality controlled observations.  There is also missing data which
can cause errors in the accumulated values.</p>

<div class="text">
<P>Pick network to select station from:
<br><a href="fe.phtml?network=IA_ASOS">ASOS</a>
 -or- <a href="fe.phtml?network=AWOS">AWOS</a>
 -or- <a href="fe.phtml?network=IA_COOP">NWS COOP</a>
 -or- <a href="fe.phtml?network=KCCI">KCCI SchoolNet</a>

<?php if (strlen($station) > 0 ) { ?>
<?php include_once("$rootpath/include/forms.php"); ?>
<form name="ds" action="fe.phtml" method="GET">
<input type="hidden" value="<?php echo $station; ?>" name="station">
<table cellspacing=2 border=1 cellpadding=2>
<thead>
<tr><th>Site ID:</th><th>Select Year:</th></tr>
</thead>
<tbody>
<tr><td><input type="text" name="station" value="<?php echo $station; ?>" size="6"></td>
  <td><?php echo yearSelect(2004,$year,"year"); ?></td></tr>
</tbody>
</table>
<input type="submit" value="Make Plot">
</form>

<p><img src="gdd_plot.php?<?php echo "station=$station&year=$year"; ?>" ALT="Time Series">
<p><img src="rainfall_plot.php?<?php echo "station=$station&year=$year"; ?>" ALT="Time Series">

<?php } else { ?>


<?php
echo $sw->printInterface();
	}
?>
</div>

<?php include("$rootpath/include/footer.php"); ?>
