<?php
$OL = "7.2.2";
require_once "../../../config/settings.inc.php";
require_once "../../../include/database.inc.php";
require_once "../../../include/imagemaps.php";
require_once "../../../include/myview.php";
require_once "../../../include/forms.php";
define("IEM_APPID", 14);
$station = isset($_GET['station']) ? xssafe($_GET['station']) : "";
$network = isset($_REQUEST["network"]) ? xssafe($_REQUEST['network']) : "IA_ASOS";
$year = isset($_GET['year']) ? intval($_GET['year']) : date("Y");
$smonth = isset($_GET['smonth']) ? intval($_GET['smonth']) : 5;
$emonth = isset($_GET['emonth']) ? intval($_GET['emonth']) : 10;
$sday = isset($_GET['sday']) ? intval($_GET['sday']) : 1;
$eday = isset($_GET['eday']) ? intval($_GET['eday']) : 1;

$t = new MyView();
$t->headextra = <<<EOF
<link rel="stylesheet" href="/vendor/openlayers/{$OL}/ol.css" type="text/css">
<link type="text/css" href="/vendor/openlayers/{$OL}/ol-layerswitcher.css" rel="stylesheet" />
<link rel="stylesheet" type="text/css" href="/vendor/select2/4.0.3/select2.min.css"/ >
EOF;
$t->jsextra = <<<EOF
<script src="/vendor/openlayers/{$OL}/ol.js" type="text/javascript"></script>
<script src='/vendor/openlayers/{$OL}/ol-layerswitcher.js'></script>
<script src="/js/olselect.js"></script>
<script src="/vendor/select2/4.0.3/select2.min.js"></script>
<script type="text/javascript">
$(document).ready(function(){
    $(".iemselect2").select2();	
});
</script>
EOF;
$t->title = "Accumulated Values versus Climatology";

$mesosite = iemdb("mesosite");
$rs = pg_query($mesosite, "SELECT id, name from networks where
    id ~* '^IA' or id ~* '^MN' or id ~* '^WI' or id ~* '^ND' or id ~* '^SD' or id ~* '^NE'
     or id ~* '^KS' or id ~* '^MO' or id ~* '^IL' or id ~* '^IN' or id ~* '^OH' or id ~* '^KY'
    or id in ('KCCI','KELO','KIMT')");
$nselect = "<select name=\"network\">";
for ($i = 0; $row = pg_fetch_assoc($rs); $i++) {
    $nselect .= sprintf(
        "<option value=\"%s\"%s>%s</option>",
        $row["id"],
        ($row["id"] == $network) ? ' selected="selected"' : '',
        $row["name"]
    );
}
$nselect .= "</select>";

$content = <<<EOF
<style type="text/css">
        #map {
            width: 450px;
            height: 450px;
            border: 2px solid black;
        }
</style>

<h3 class="heading">Growing Season Traces</h3>

<p>This application generates a plot of observed rainfall + temperatures 
versus climatology.  This application should be used with extreme caution
since it uses non quality controlled observations.  There is also missing data which
can cause errors in the accumulated values.</p>


<P>Pick network to select station from:
<form name='netselect' method='GET'>
{$nselect}
<input type="submit" value="Select Network" />
</form>
EOF;
$sselect = networkSelect($network, $station);
if (strlen($station) > 0) {

    $yselect = yearSelect(2004, $year, "year");
    $smselect =  monthSelect($smonth, "smonth");
    $sdselect = daySelect2($sday, "sday");
    $emselect =  monthSelect($emonth, "emonth");
    $edselect = daySelect2($eday, "eday");
    $content .= <<<EOF
<form name="ds" action="fe.phtml" method="GET">
<table cellspacing=2 border=1 cellpadding=2>
<thead>
<tr><th>Site ID:</th><th>Year:</th><th>Start Date:</th><th>End Date:</th></tr>
</thead>
<tbody>
<tr><td>{$sselect}</td>
  <td>{$yselect}</td>
  <td>{$smselect} {$sdselect}</td>
  <td>{$emselect} {$edselect}</td>
</tr>
</tbody>
</table>
<input type="submit" value="Make Plot">
</form>

<p><img src="gdd_plot.php?network={$network}&station={$station}&year={$year}&smonth={$smonth}&sday={$sday}&emonth={$emonth}&eday={$eday}" ALT="Time Series">
<p><img src="rainfall_plot.php?network={$network}&station={$station}&year={$year}&smonth={$smonth}&sday={$sday}&emonth={$emonth}&eday={$eday}" ALT="Time Series">
EOF;
} else {
    $content .= <<<EOF
<form name="olselect">
<input type="hidden" value="{$network}" name="network">
<table><tr><th>Select Station</th>
<td>{$sselect}</td>
<td><input type="submit" value="Make Plot"></tr></table>
<div id="map" data-network="{$network}"></div>
</form>
EOF;
}
$t->content = $content;
$t->render('single.phtml');
