<html>
<head>
 <title>IEM | SchoolNet Currents</title>
</head>

<FRAMESET COLS="480,*" BORDER="0">
  <FRAME SRC="http://mesonet.agron.iastate.edu/cgi-bin/mapserv/mapserv401?map=/mesonet/www/html/GIS/apps/snet/view.map" name="top" RESIZE="no" FRAMEBORDER="0" FRAMESPACING="0" 
     scrolling="no" MARGINWIDTH="0" MARGINHEIGHT="0">
  <FRAME SRC="display.phtml" name="display"  RESIZE="no" FRAMEBORDER="0" 
     FRAMESPACING="0" MARGINWIDTH="0" MARGINHEIGHT="0">
</FRAMESET>

</HTML>
