<?php
// These stubs were generated by the phan stub generator.
// @phan-stub-for-extension mapscript@

namespace {
class CompositingFilter  {

    // methods
    public function filter_set(string $arg1) : void {}
    public function filter_get() : ?string {}
    public function next_set(?\CompositingFilter $arg1) : void {}
    public function next_get() : ?\CompositingFilter {}
    public function __construct() {}
    public function __set(string $arg1, $arg2 = null) : void {}
    public function __get(string $arg1) {}
    public function __isset(string $arg1) : bool {}
}

class DBFInfo  {

    // methods
    public function nRecords_get() : int {}
    public function nFields_get() : int {}
    public function getFieldName(int $arg1) : ?string {}
    public function getFieldWidth(int $arg1) : int {}
    public function getFieldDecimals(int $arg1) : int {}
    public function getFieldType(int $arg1) : int {}
    public function __construct() {}
    public function __set(string $arg1, $arg2 = null) : void {}
    public function __get(string $arg1) {}
    public function __isset(string $arg1) : bool {}
}

class LayerCompositer  {

    // methods
    public function comp_op_set(int $arg1) : void {}
    public function comp_op_get() : int {}
    public function opacity_set(int $arg1) : void {}
    public function opacity_get() : int {}
    public function filter_set(?\CompositingFilter $arg1) : void {}
    public function filter_get() : ?\CompositingFilter {}
    public function next_set(?\LayerCompositer $arg1) : void {}
    public function next_get() : ?\LayerCompositer {}
    public function __construct() {}
    public function __set(string $arg1, $arg2 = null) : void {}
    public function __get(string $arg1) {}
    public function __isset(string $arg1) : bool {}
}

class OWSRequest  {

    // methods
    public function NumParams_get() : int {}
    public function type_set(int $arg1) : void {}
    public function type_get() : int {}
    public function contenttype_set(string $arg1) : void {}
    public function contenttype_get() : ?string {}
    public function postrequest_set(string $arg1) : void {}
    public function postrequest_get() : ?string {}
    public function httpcookiedata_set(string $arg1) : void {}
    public function httpcookiedata_get() : ?string {}
    public function __construct() {}
    public function loadParams() : int {}
    public function loadParamsFromURL(string $arg1) : int {}
    public function loadParamsFromPost(string $arg1, string $arg2) : int {}
    public function setParameter(string $arg1, string $arg2) : void {}
    public function addParameter(string $arg1, string $arg2) : void {}
    public function getName(int $arg1) : ?string {}
    public function getValue(int $arg1) : ?string {}
    public function getValueByName(string $arg1) : ?string {}
    public function __set(string $arg1, $arg2 = null) : void {}
    public function __get(string $arg1) {}
    public function __isset(string $arg1) : bool {}
}

class classObj  {

    // methods
    public function metadata_get() : ?\hashTableObj {}
    public function validation_get() : ?\hashTableObj {}
    public function numstyles_get() : int {}
    public function numlabels_get() : int {}
    public function refcount_get() : int {}
    public function layer_get() : ?\layerObj {}
    public function leader_get() : ?\labelLeaderObj {}
    public function status_set(int $arg1) : void {}
    public function status_get() : int {}
    public function isfallback_set(int $arg1) : void {}
    public function isfallback_get() : int {}
    public function name_set(string $arg1) : void {}
    public function name_get() : ?string {}
    public function title_set(string $arg1) : void {}
    public function title_get() : ?string {}
    public function minscaledenom_set(float $arg1) : void {}
    public function minscaledenom_get() : float {}
    public function maxscaledenom_set(float $arg1) : void {}
    public function maxscaledenom_get() : float {}
    public function minfeaturesize_set(int $arg1) : void {}
    public function minfeaturesize_get() : int {}
    public function debug_set(int $arg1) : void {}
    public function debug_get() : int {}
    public function keyimage_set(string $arg1) : void {}
    public function keyimage_get() : ?string {}
    public function group_set(string $arg1) : void {}
    public function group_get() : ?string {}
    public function sizeunits_set(int $arg1) : void {}
    public function sizeunits_get() : int {}
    public function template_set(string $arg1) : void {}
    public function template_get() : ?string {}
    public function __construct(?\layerObj $arg1 = null) {}
    public function updateFromString(string $arg1) : int {}
    public function convertToString() : ?string {}
    public function cloneClass() : ?\classObj {}
    public function setExpression(string $arg1) : int {}
    public function getExpressionString() : ?string {}
    public function setText(string $arg1) : int {}
    public function getTextString() : ?string {}
    public function drawLegendIcon(?\mapObj $arg1, ?\layerObj $arg2, int $arg3, int $arg4, ?\imageObj $arg5, int $arg6, int $arg7) : int {}
    public function createLegendIcon(?\mapObj $arg1, ?\layerObj $arg2, int $arg3, int $arg4) : ?\imageObj {}
    public function getLabel(int $arg1) : ?\labelObj {}
    public function addLabel(?\labelObj $arg1) : int {}
    public function removeLabel(int $arg1) : ?\labelObj {}
    public function getStyle(int $arg1) : ?\styleObj {}
    public function insertStyle(?\styleObj $arg1, int $arg2 = unknown) : int {}
    public function removeStyle(int $arg1) : ?\styleObj {}
    public function moveStyleUp(int $arg1) : int {}
    public function moveStyleDown(int $arg1) : int {}
    public function __set(string $arg1, $arg2 = null) : void {}
    public function __get(string $arg1) {}
    public function __isset(string $arg1) : bool {}
}

class clusterObj  {

    // methods
    public function maxdistance_set(float $arg1) : void {}
    public function maxdistance_get() : float {}
    public function buffer_set(float $arg1) : void {}
    public function buffer_get() : float {}
    public function region_set(string $arg1) : void {}
    public function region_get() : ?string {}
    public function updateFromString(string $arg1) : int {}
    public function convertToString() : ?string {}
    public function setGroup(string $arg1) : int {}
    public function getGroupString() : ?string {}
    public function setFilter(string $arg1) : int {}
    public function getFilterString() : ?string {}
    public function __construct() {}
    public function __set(string $arg1, $arg2 = null) : void {}
    public function __get(string $arg1) {}
    public function __isset(string $arg1) : bool {}
}

class colorObj  {

    // methods
    public function red_set(int $arg1) : void {}
    public function red_get() : int {}
    public function green_set(int $arg1) : void {}
    public function green_get() : int {}
    public function blue_set(int $arg1) : void {}
    public function blue_get() : int {}
    public function alpha_set(int $arg1) : void {}
    public function alpha_get() : int {}
    public function __construct(int $arg1 = unknown, int $arg2 = unknown, int $arg3 = unknown, int $arg4 = unknown) {}
    public function setRGB(int $arg1, int $arg2, int $arg3, int $arg4 = unknown) : int {}
    public function setHex(string $arg1) : int {}
    public function toHex() : ?string {}
    public function __set(string $arg1, $arg2 = null) : void {}
    public function __get(string $arg1) {}
    public function __isset(string $arg1) : bool {}
}

class configObj  {

    // methods
    public function env_set(?\hashTableObj $arg1) : void {}
    public function env_get() : ?\hashTableObj {}
    public function maps_set(?\hashTableObj $arg1) : void {}
    public function maps_get() : ?\hashTableObj {}
    public function plugins_set(?\hashTableObj $arg1) : void {}
    public function plugins_get() : ?\hashTableObj {}
    public function __construct(string $arg1 = unknown) {}
    public function __set(string $arg1, $arg2 = null) : void {}
    public function __get(string $arg1) {}
    public function __isset(string $arg1) : bool {}
}

class errorObj  {

    // methods
    public function code_set(int $arg1) : void {}
    public function code_get() : int {}
    public function routine_set(string $arg1) : void {}
    public function routine_get() : string {}
    public function message_set(string $arg1) : void {}
    public function message_get() : string {}
    public function http_status_set(string $arg1) : void {}
    public function http_status_get() : string {}
    public function isreported_set(int $arg1) : void {}
    public function isreported_get() : int {}
    public function errorcount_set(int $arg1) : void {}
    public function errorcount_get() : int {}
    public function __construct() {}
    public function next() : ?\errorObj {}
    public function __set(string $arg1, $arg2 = null) : void {}
    public function __get(string $arg1) {}
    public function __isset(string $arg1) : bool {}
}

class fontSetObj  {

    // methods
    public function filename_get() : ?string {}
    public function numfonts_get() : int {}
    public function fonts_get() : ?\hashTableObj {}
    public function __construct() {}
    public function __set(string $arg1, $arg2 = null) : void {}
    public function __get(string $arg1) {}
    public function __isset(string $arg1) : bool {}
}

class hashTableObj  {

    // methods
    public function numitems_get() : int {}
    public function __construct() {}
    public function set(string $arg1, string $arg2) : int {}
    public function get(string $arg1, string $arg2 = unknown) : ?string {}
    public function remove(string $arg1) : int {}
    public function clear() : void {}
    public function nextKey(string $arg1 = unknown) : ?string {}
    public function __set(string $arg1, $arg2 = null) : void {}
    public function __get(string $arg1) {}
    public function __isset(string $arg1) : bool {}
}

class imageObj  {

    // methods
    public function width_get() : int {}
    public function height_get() : int {}
    public function resolution_get() : float {}
    public function resolutionfactor_get() : float {}
    public function imagepath_get() : ?string {}
    public function imageurl_get() : ?string {}
    public function format_get() : ?\outputFormatObj {}
    public function __construct(int $arg1, int $arg2, ?\outputFormatObj $arg3 = null, string $arg4 = unknown, float $arg5 = unknown, float $arg6 = unknown) {}
    public function save(string $arg1, ?\mapObj $arg2 = null) : void {}
    public function write(?\SWIG\_p_FILE $arg1 = null) : int {}
    public function getBytes() : Stringable {}
    public function getSize() : int {}
    public function pasteImage(?\imageObj $arg1, float $arg2 = unknown, int $arg3 = unknown, int $arg4 = unknown) : int {}
    public function saveWebImage() : ?string {}
    public function __set(string $arg1, $arg2 = null) : void {}
    public function __get(string $arg1) {}
    public function __isset(string $arg1) : bool {}
}

class intarray  {

    // methods
    public function __construct(int $arg1) {}
    public function getitem(int $arg1) : int {}
    public function setitem(int $arg1, int $arg2) : void {}
    public function cast() : ?\SWIG\_p_int {}
    public static function frompointer(?\SWIG\_p_int $arg1) : ?\intarray {}
    public function __set(string $arg1, $arg2 = null) : void {}
    public function __get(string $arg1) {}
    public function __isset(string $arg1) : bool {}
}

class labelCacheMemberObj  {

    // methods
    public function numtextsymbols_get() : int {}
    public function layerindex_get() : int {}
    public function classindex_get() : int {}
    public function status_get() : int {}
    public function markerid_get() : int {}
    public function point_get() : ?\pointObj {}
    public function bbox_get() : ?\rectObj {}
    public function leaderline_get() : ?\lineObj {}
    public function leaderbbox_get() : ?\rectObj {}
    public function __construct() {}
    public function __set(string $arg1, $arg2 = null) : void {}
    public function __get(string $arg1) {}
    public function __isset(string $arg1) : bool {}
}

class labelCacheObj  {

    // methods
    public function num_rendered_members_get() : int {}
    public function freeCache() : void {}
    public function __construct() {}
    public function __set(string $arg1, $arg2 = null) : void {}
    public function __get(string $arg1) {}
    public function __isset(string $arg1) : bool {}
}

class labelCacheSlotObj  {

    // methods
    public function numlabels_get() : int {}
    public function cachesize_get() : int {}
    public function nummarkers_get() : int {}
    public function markercachesize_get() : int {}
    public function labels_get() : ?\labelCacheMemberObj {}
    public function markers_get() : ?\markerCacheMemberObj {}
    public function __construct() {}
    public function __set(string $arg1, $arg2 = null) : void {}
    public function __get(string $arg1) {}
    public function __isset(string $arg1) : bool {}
}

class labelLeaderObj  {

    // methods
    public function numstyles_get() : int {}
    public function maxdistance_set(int $arg1) : void {}
    public function maxdistance_get() : int {}
    public function gridstep_set(int $arg1) : void {}
    public function gridstep_get() : int {}
    public function __construct() {}
    public function __set(string $arg1, $arg2 = null) : void {}
    public function __get(string $arg1) {}
    public function __isset(string $arg1) : bool {}
}

class labelObj  {

    // methods
    public function refcount_get() : int {}
    public function font_set(string $arg1) : void {}
    public function font_get() : ?string {}
    public function color_set(?\colorObj $arg1) : void {}
    public function color_get() : ?\colorObj {}
    public function outlinecolor_set(?\colorObj $arg1) : void {}
    public function outlinecolor_get() : ?\colorObj {}
    public function outlinewidth_set(int $arg1) : void {}
    public function outlinewidth_get() : int {}
    public function shadowcolor_set(?\colorObj $arg1) : void {}
    public function shadowcolor_get() : ?\colorObj {}
    public function shadowsizex_set(int $arg1) : void {}
    public function shadowsizex_get() : int {}
    public function shadowsizey_set(int $arg1) : void {}
    public function shadowsizey_get() : int {}
    public function size_set(int $arg1) : void {}
    public function size_get() : int {}
    public function minsize_set(int $arg1) : void {}
    public function minsize_get() : int {}
    public function maxsize_set(int $arg1) : void {}
    public function maxsize_get() : int {}
    public function position_set(int $arg1) : void {}
    public function position_get() : int {}
    public function offsetx_set(int $arg1) : void {}
    public function offsetx_get() : int {}
    public function offsety_set(int $arg1) : void {}
    public function offsety_get() : int {}
    public function angle_set(float $arg1) : void {}
    public function angle_get() : float {}
    public function anglemode_set(int $arg1) : void {}
    public function anglemode_get() : int {}
    public function buffer_set(int $arg1) : void {}
    public function buffer_get() : int {}
    public function align_set(int $arg1) : void {}
    public function align_get() : int {}
    public function wrap_set(string $arg1) : void {}
    public function wrap_get() : string {}
    public function maxlength_set(int $arg1) : void {}
    public function maxlength_get() : int {}
    public function space_size_10_set(float $arg1) : void {}
    public function space_size_10_get() : float {}
    public function minfeaturesize_set(int $arg1) : void {}
    public function minfeaturesize_get() : int {}
    public function autominfeaturesize_set(int $arg1) : void {}
    public function autominfeaturesize_get() : int {}
    public function minscaledenom_set(float $arg1) : void {}
    public function minscaledenom_get() : float {}
    public function maxscaledenom_set(float $arg1) : void {}
    public function maxscaledenom_get() : float {}
    public function mindistance_set(int $arg1) : void {}
    public function mindistance_get() : int {}
    public function repeatdistance_set(int $arg1) : void {}
    public function repeatdistance_get() : int {}
    public function maxoverlapangle_set(float $arg1) : void {}
    public function maxoverlapangle_get() : float {}
    public function partials_set(int $arg1) : void {}
    public function partials_get() : int {}
    public function force_set(int $arg1) : void {}
    public function force_get() : int {}
    public function encoding_set(string $arg1) : void {}
    public function encoding_get() : ?string {}
    public function priority_set(int $arg1) : void {}
    public function priority_get() : int {}
    public function numstyles_set(int $arg1) : void {}
    public function numstyles_get() : int {}
    public function sizeunits_set(int $arg1) : void {}
    public function sizeunits_get() : int {}
    public function __construct() {}
    public function updateFromString(string $arg1) : int {}
    public function convertToString() : ?string {}
    public function removeBinding(int $arg1) : int {}
    public function getBinding(int $arg1) : ?string {}
    public function setBinding(int $arg1, string $arg2) : int {}
    public function removeExpressionBinding(int $arg1) : int {}
    public function getExpressionBinding(int $arg1) : ?string {}
    public function setExpressionBinding(int $arg1, string $arg2) : int {}
    public function setExpression(string $arg1) : int {}
    public function getExpressionString() : ?string {}
    public function setText(string $arg1) : int {}
    public function getTextString() : ?string {}
    public function getStyle(int $arg1) : ?\styleObj {}
    public function insertStyle(?\styleObj $arg1, int $arg2 = unknown) : int {}
    public function removeStyle(int $arg1) : ?\styleObj {}
    public function moveStyleUp(int $arg1) : int {}
    public function moveStyleDown(int $arg1) : int {}
    public function __set(string $arg1, $arg2 = null) : void {}
    public function __get(string $arg1) {}
    public function __isset(string $arg1) : bool {}
}

class layerObj  {

    // methods
    public function refcount_get() : int {}
    public function numclasses_get() : int {}
    public function maxclasses_get() : int {}
    public function index_get() : int {}
    public function map_get() : ?\mapObj {}
    public function numitems_get() : int {}
    public function metadata_get() : ?\hashTableObj {}
    public function validation_get() : ?\hashTableObj {}
    public function bindvals_get() : ?\hashTableObj {}
    public function connectionoptions_get() : ?\hashTableObj {}
    public function cluster_get() : ?\clusterObj {}
    public function extent_get() : ?\rectObj {}
    public function numjoins_get() : int {}
    public function utfdata_get() : \SWIG\_expressionObj {}
    public function compositer_get() : ?\LayerCompositer {}
    public function classitem_set(string $arg1) : void {}
    public function classitem_get() : ?string {}
    public function header_set(string $arg1) : void {}
    public function header_get() : ?string {}
    public function footer_set(string $arg1) : void {}
    public function footer_get() : ?string {}
    public function template_set(string $arg1) : void {}
    public function template_get() : ?string {}
    public function name_set(string $arg1) : void {}
    public function name_get() : ?string {}
    public function group_set(string $arg1) : void {}
    public function group_get() : ?string {}
    public function status_set(int $arg1) : void {}
    public function status_get() : int {}
    public function rendermode_set(int $arg1) : void {}
    public function rendermode_get() : int {}
    public function data_set(string $arg1) : void {}
    public function data_get() : ?string {}
    public function type_set(int $arg1) : void {}
    public function type_get() : int {}
    public function connectiontype_set(int $arg1) : void {}
    public function connectiontype_get() : int {}
    public function tolerance_set(float $arg1) : void {}
    public function tolerance_get() : float {}
    public function toleranceunits_set(int $arg1) : void {}
    public function toleranceunits_get() : int {}
    public function identificationclassauto_set(int $arg1) : void {}
    public function identificationclassauto_get() : int {}
    public function identificationclassgroup_set(string $arg1) : void {}
    public function identificationclassgroup_get() : ?string {}
    public function symbolscaledenom_set(float $arg1) : void {}
    public function symbolscaledenom_get() : float {}
    public function minscaledenom_set(float $arg1) : void {}
    public function minscaledenom_get() : float {}
    public function maxscaledenom_set(float $arg1) : void {}
    public function maxscaledenom_get() : float {}
    public function minfeaturesize_set(int $arg1) : void {}
    public function minfeaturesize_get() : int {}
    public function labelminscaledenom_set(float $arg1) : void {}
    public function labelminscaledenom_get() : float {}
    public function labelmaxscaledenom_set(float $arg1) : void {}
    public function labelmaxscaledenom_get() : float {}
    public function mingeowidth_set(float $arg1) : void {}
    public function mingeowidth_get() : float {}
    public function maxgeowidth_set(float $arg1) : void {}
    public function maxgeowidth_get() : float {}
    public function sizeunits_set(int $arg1) : void {}
    public function sizeunits_get() : int {}
    public function maxfeatures_set(int $arg1) : void {}
    public function maxfeatures_get() : int {}
    public function startindex_set(int $arg1) : void {}
    public function startindex_get() : int {}
    public function offsite_set(?\colorObj $arg1) : void {}
    public function offsite_get() : ?\colorObj {}
    public function transform_set(int $arg1) : void {}
    public function transform_get() : int {}
    public function labelcache_set(int $arg1) : void {}
    public function labelcache_get() : int {}
    public function postlabelcache_set(int $arg1) : void {}
    public function postlabelcache_get() : int {}
    public function labelitem_set(string $arg1) : void {}
    public function labelitem_get() : ?string {}
    public function tileitem_set(string $arg1) : void {}
    public function tileitem_get() : ?string {}
    public function tileindex_set(string $arg1) : void {}
    public function tileindex_get() : ?string {}
    public function tilesrs_set(string $arg1) : void {}
    public function tilesrs_get() : ?string {}
    public function units_set(int $arg1) : void {}
    public function units_get() : int {}
    public function connection_set(string $arg1) : void {}
    public function connection_get() : ?string {}
    public function plugin_library_set(string $arg1) : void {}
    public function plugin_library_get() : ?string {}
    public function plugin_library_original_set(string $arg1) : void {}
    public function plugin_library_original_get() : ?string {}
    public function bandsitem_set(string $arg1) : void {}
    public function bandsitem_get() : ?string {}
    public function filteritem_set(string $arg1) : void {}
    public function filteritem_get() : ?string {}
    public function styleitem_set(string $arg1) : void {}
    public function styleitem_get() : ?string {}
    public function requires_set(string $arg1) : void {}
    public function requires_get() : ?string {}
    public function labelrequires_set(string $arg1) : void {}
    public function labelrequires_get() : ?string {}
    public function debug_set(int $arg1) : void {}
    public function debug_get() : int {}
    public function classgroup_set(string $arg1) : void {}
    public function classgroup_get() : ?string {}
    public function mask_set(string $arg1) : void {}
    public function mask_get() : ?string {}
    public function encoding_set(string $arg1) : void {}
    public function encoding_get() : ?string {}
    public function utfitem_set(string $arg1) : void {}
    public function utfitem_get() : ?string {}
    public function utfitemindex_set(int $arg1) : void {}
    public function utfitemindex_get() : int {}
    public function numprocessing_get() : int {}
    public function __construct(?\mapObj $arg1 = null) {}
    public function setOpacity(int $arg1) : void {}
    public function getOpacity() : int {}
    public function cloneLayer() : ?\layerObj {}
    public function updateFromString(string $arg1) : int {}
    public function convertToString() : ?string {}
    public function insertClass(?\classObj $arg1, int $arg2 = unknown) : int {}
    public function removeClass(int $arg1) : ?\classObj {}
    public function open() : int {}
    public function whichShapes(\rectObj $arg1) : int {}
    public function nextShape() : ?\shapeObj {}
    public function close() : void {}
    public function getShape(?\resultObj $arg1) : ?\shapeObj {}
    public function getNumResults() : int {}
    public function getResultsBounds() : ?\rectObj {}
    public function getResult(int $arg1) : ?\resultObj {}
    public function getClass(int $arg1) : ?\classObj {}
    public function getItem(int $arg1) : ?string {}
    public function setItems(?\SWIG\_p_p_char $arg1, int $arg2) : int {}
    public function draw(?\mapObj $arg1, ?\imageObj $arg2) : int {}
    public function drawQuery(?\mapObj $arg1, ?\imageObj $arg2) : int {}
    public function queryByFilter(?\mapObj $arg1, string $arg2) : int {}
    public function queryByAttributes(?\mapObj $arg1, string $arg2, string $arg3, int $arg4) : int {}
    public function queryByPoint(?\mapObj $arg1, ?\pointObj $arg2, int $arg3, float $arg4) : int {}
    public function queryByRect(?\mapObj $arg1, \rectObj $arg2) : int {}
    public function queryByFeatures(?\mapObj $arg1, int $arg2) : int {}
    public function queryByShape(?\mapObj $arg1, ?\shapeObj $arg2) : int {}
    public function queryByIndex(?\mapObj $arg1, int $arg2, int $arg3, int $arg4 = unknown) : int {}
    public function getResults() : ?\resultCacheObj {}
    public function setFilter(string $arg1) : int {}
    public function getFilterString() : ?string {}
    public function setWKTProjection(string $arg1) : int {}
    public function getProjection() : ?string {}
    public function setProjection(string $arg1) : int {}
    public function addFeature(?\shapeObj $arg1) : int {}
    public function getNumFeatures() : int {}
    public function getExtent() : ?\rectObj {}
    public function setExtent(float $arg1 = unknown, float $arg2 = unknown, float $arg3 = unknown, float $arg4 = unknown) : int {}
    public function getWMSFeatureInfoURL(?\mapObj $arg1, int $arg2, int $arg3, int $arg4, string $arg5) : ?string {}
    public function executeWFSGetFeature() : ?string {}
    public function applySLD(string $arg1, string $arg2) : int {}
    public function applySLDURL(string $arg1, string $arg2) : int {}
    public function generateSLD() : ?string {}
    public function isVisible() : int {}
    public function moveClassUp(int $arg1) : int {}
    public function moveClassDown(int $arg1) : int {}
    public function setProcessingKey(string $arg1, string $arg2) : void {}
    public function addProcessing(string $arg1) : void {}
    public function getNumProcessing() : int {}
    public function getProcessing(int $arg1) : ?string {}
    public function getProcessingKey(string $arg1) : ?string {}
    public function clearProcessing() : int {}
    public function setConnectionType(int $arg1, string $arg2) : int {}
    public function getClassIndex(?\mapObj $arg1, ?\shapeObj $arg2, ?\SWIG\_p_int $arg3 = null, int $arg4 = unknown) : int {}
    public function getGeomTransform() : ?string {}
    public function setGeomTransform(string $arg1) : void {}
    public function getItemType(int $arg1) : ?string {}
    public function __set(string $arg1, $arg2 = null) : void {}
    public function __get(string $arg1) {}
    public function __isset(string $arg1) : bool {}
}

class legendObj  {

    // methods
    public function label_get() : ?\labelObj {}
    public function map_get() : ?\mapObj {}
    public function transparent_set(int $arg1) : void {}
    public function transparent_get() : int {}
    public function imagecolor_set(?\colorObj $arg1) : void {}
    public function imagecolor_get() : ?\colorObj {}
    public function keysizex_set(int $arg1) : void {}
    public function keysizex_get() : int {}
    public function keysizey_set(int $arg1) : void {}
    public function keysizey_get() : int {}
    public function keyspacingx_set(int $arg1) : void {}
    public function keyspacingx_get() : int {}
    public function keyspacingy_set(int $arg1) : void {}
    public function keyspacingy_get() : int {}
    public function outlinecolor_set(?\colorObj $arg1) : void {}
    public function outlinecolor_get() : ?\colorObj {}
    public function status_set(int $arg1) : void {}
    public function status_get() : int {}
    public function height_set(int $arg1) : void {}
    public function height_get() : int {}
    public function width_set(int $arg1) : void {}
    public function width_get() : int {}
    public function position_set(int $arg1) : void {}
    public function position_get() : int {}
    public function postlabelcache_set(int $arg1) : void {}
    public function postlabelcache_get() : int {}
    public function template_set(string $arg1) : void {}
    public function template_get() : ?string {}
    public function updateFromString(string $arg1) : int {}
    public function convertToString() : ?string {}
    public function __construct() {}
    public function __set(string $arg1, $arg2 = null) : void {}
    public function __get(string $arg1) {}
    public function __isset(string $arg1) : bool {}
}

class lineObj  {

    // methods
    public function numpoints_get() : int {}
    public function __construct() {}
    public function project(\projectionObj|\reprojectionObj|null $arg1, ?\projectionObj $arg2 = null) : int {}
    public function get(int $arg1) : ?\pointObj {}
    public function add(?\pointObj $arg1) : int {}
    public function set(int $arg1, ?\pointObj $arg2) : int {}
    public function __set(string $arg1, $arg2 = null) : void {}
    public function __get(string $arg1) {}
    public function __isset(string $arg1) : bool {}
}

class mapObj  {

    // methods
    public function refcount_get() : int {}
    public function numlayers_get() : int {}
    public function maxlayers_get() : int {}
    public function configoptions_get() : ?\hashTableObj {}
    public function symbolset_get() : ?\symbolSetObj {}
    public function fontset_get() : ?\fontSetObj {}
    public function labelcache_get() : ?\labelCacheObj {}
    public function numoutputformats_get() : int {}
    public function outputformat_get() : ?\outputFormatObj {}
    public function imagetype_get() : ?string {}
    public function reference_get() : ?\referenceMapObj {}
    public function scalebar_get() : ?\scalebarObj {}
    public function legend_get() : ?\legendObj {}
    public function querymap_get() : ?\queryMapObj {}
    public function web_get() : ?\webObj {}
    public function config_get() : ?\configObj {}
    public function datapattern_set(string $arg1) : void {}
    public function datapattern_get() : ?string {}
    public function templatepattern_set(string $arg1) : void {}
    public function templatepattern_get() : ?string {}
    public function name_set(string $arg1) : void {}
    public function name_get() : ?string {}
    public function status_set(int $arg1) : void {}
    public function status_get() : int {}
    public function height_set(int $arg1) : void {}
    public function height_get() : int {}
    public function width_set(int $arg1) : void {}
    public function width_get() : int {}
    public function maxsize_set(int $arg1) : void {}
    public function maxsize_get() : int {}
    public function extent_set(?\rectObj $arg1) : void {}
    public function extent_get() : ?\rectObj {}
    public function cellsize_set(float $arg1) : void {}
    public function cellsize_get() : float {}
    public function units_set(int $arg1) : void {}
    public function units_get() : int {}
    public function scaledenom_set(float $arg1) : void {}
    public function scaledenom_get() : float {}
    public function resolution_set(float $arg1) : void {}
    public function resolution_get() : float {}
    public function defresolution_set(float $arg1) : void {}
    public function defresolution_get() : float {}
    public function shapepath_set(string $arg1) : void {}
    public function shapepath_get() : ?string {}
    public function mappath_set(string $arg1) : void {}
    public function mappath_get() : ?string {}
    public function sldurl_set(string $arg1) : void {}
    public function sldurl_get() : ?string {}
    public function imagecolor_set(?\colorObj $arg1) : void {}
    public function imagecolor_get() : ?\colorObj {}
    public function layerorder_set(?\SWIG\_p_int $arg1) : void {}
    public function layerorder_get() : ?\SWIG\_p_int {}
    public function debug_set(int $arg1) : void {}
    public function debug_get() : int {}
    public function __construct(string $arg1 = unknown, ?\configObj $arg2 = null) {}
    public function cloneMap() : ?\mapObj {}
    public function insertLayer(?\layerObj $arg1, int $arg2 = unknown) : int {}
    public function removeLayer(int $arg1) : ?\layerObj {}
    public function setExtent(float $arg1, float $arg2, float $arg3, float $arg4) : int {}
    public function offsetExtent(float $arg1, float $arg2) : int {}
    public function scaleExtent(float $arg1, float $arg2, float $arg3) : int {}
    public function setCenter(?\pointObj $arg1) : int {}
    public function setSize(int $arg1, int $arg2) : int {}
    public function pixelToGeoref(float $arg1, float $arg2, ?\pointObj $arg3) : void {}
    public function getRotation() : float {}
    public function setRotation(float $arg1) : int {}
    public function getLayer(int $arg1) : ?\layerObj {}
    public function getLayerByName(string $arg1) : ?\layerObj {}
    public function getSymbolByName(string $arg1) : int {}
    public function prepareQuery() : void {}
    public function prepareImage() : ?\imageObj {}
    public function setImageType(string $arg1) : void {}
    public function selectOutputFormat(string $arg1) : void {}
    public function getOutputFormat(int $arg1) : ?\outputFormatObj {}
    public function setOutputFormat(?\outputFormatObj $arg1) : void {}
    public function draw() : ?\imageObj {}
    public function drawQuery() : ?\imageObj {}
    public function drawLegend(int $arg1 = unknown) : ?\imageObj {}
    public function drawScalebar() : ?\imageObj {}
    public function drawReferenceMap() : ?\imageObj {}
    public function embedScalebar(?\imageObj $arg1) : int {}
    public function embedLegend(?\imageObj $arg1) : int {}
    public function drawLabelCache(?\imageObj $arg1) : int {}
    public function queryByFilter(string $arg1) : int {}
    public function queryByPoint(?\pointObj $arg1, int $arg2, float $arg3) : int {}
    public function queryByRect(\rectObj $arg1) : int {}
    public function queryByFeatures(int $arg1) : int {}
    public function queryByShape(?\shapeObj $arg1) : int {}
    public function setWKTProjection(string $arg1) : int {}
    public function getProjection() : ?string {}
    public function setProjection(string $arg1) : int {}
    public function save(string $arg1) : int {}
    public function saveQuery(string $arg1, int $arg2 = unknown) : int {}
    public function loadQuery(string $arg1) : int {}
    public function freeQuery(int $arg1 = unknown) : void {}
    public function saveQueryAsGML(string $arg1, string $arg2 = unknown) : int {}
    public function setSymbolSet(string $arg1) : int {}
    public function getNumSymbols() : int {}
    public function setFontSet(string $arg1) : int {}
    public function saveMapContext(string $arg1) : int {}
    public function loadMapContext(string $arg1, int $arg2 = unknown) : int {}
    public function moveLayerUp(int $arg1) : int {}
    public function moveLayerDown(int $arg1) : int {}
    public function getLayersDrawingOrder() : ?\intarray {}
    public function setLayersDrawingOrder(?\SWIG\_p_int $arg1) : int {}
    public function setConfigOption(string $arg1, string $arg2) : void {}
    public function getConfigOption(string $arg1) : ?string {}
    public function applyConfigOptions() : void {}
    public function applySLD(string $arg1) : int {}
    public function applySLDURL(string $arg1) : int {}
    public function generateSLD(string $arg1 = unknown) : ?string {}
    public function processTemplate(int $arg1, ?\SWIG\_p_p_char $arg2, ?\SWIG\_p_p_char $arg3, int $arg4) : ?string {}
    public function processLegendTemplate(?\SWIG\_p_p_char $arg1, ?\SWIG\_p_p_char $arg2, int $arg3) : ?string {}
    public function processQueryTemplate(?\SWIG\_p_p_char $arg1, ?\SWIG\_p_p_char $arg2, int $arg3) : ?string {}
    public function getOutputFormatByName(string $arg1) : ?\outputFormatObj {}
    public function appendOutputFormat(?\outputFormatObj $arg1) : int {}
    public function removeOutputFormat(string $arg1) : int {}
    public function loadOWSParameters(?\OWSRequest $arg1, string $arg2 = unknown) : int {}
    public function OWSDispatch(?\OWSRequest $arg1) : int {}
    public function convertToString() : ?string {}
    public function applyDefaultSubstitutions() : void {}
    public function applySubstitutions(?\SWIG\_p_p_char $arg1, ?\SWIG\_p_p_char $arg2, int $arg3) : void {}
    public function zoomPoint(int $arg1, ?\pointObj $arg2, int $arg3, int $arg4, ?\rectObj $arg5, ?\rectObj $arg6) : int {}
    public function zoomRectangle(?\rectObj $arg1, int $arg2, int $arg3, ?\rectObj $arg4, ?\rectObj $arg5) : int {}
    public function zoomScale(float $arg1, ?\pointObj $arg2, int $arg3, int $arg4, ?\rectObj $arg5, ?\rectObj $arg6) : int {}
    public function __set(string $arg1, $arg2 = null) : void {}
    public function __get(string $arg1) {}
    public function __isset(string $arg1) : bool {}
}

class mapscript {

    // constants
    const MAX_ERROR_LEN = 8192;
    const MS_TRUE = 1;
    const MS_FALSE = 0;
    const MS_UNKNOWN = -1;
    const MS_ON = 1;
    const MS_OFF = 0;
    const MS_DEFAULT = 2;
    const MS_EMBED = 3;
    const MS_DELETE = 4;
    const MS_YES = 1;
    const MS_NO = 0;
    const MS_LAYER_ALLOCSIZE = 64;
    const MS_CLASS_ALLOCSIZE = 8;
    const MS_STYLE_ALLOCSIZE = 4;
    const MS_LABEL_ALLOCSIZE = 2;
    const MS_MAX_LABEL_PRIORITY = 10;
    const MS_MAX_LABEL_FONTS = 5;
    const MS_DEFAULT_LABEL_PRIORITY = 1;
    const MS_LABEL_FORCE_GROUP = 2;
    const MS_RENDER_WITH_SWF = 2;
    const MS_RENDER_WITH_RAWDATA = 3;
    const MS_RENDER_WITH_IMAGEMAP = 5;
    const MS_RENDER_WITH_TEMPLATE = 8;
    const MS_RENDER_WITH_OGR = 16;
    const MS_RENDER_WITH_PLUGIN = 100;
    const MS_RENDER_WITH_CAIRO_RASTER = 101;
    const MS_RENDER_WITH_CAIRO_PDF = 102;
    const MS_RENDER_WITH_CAIRO_SVG = 103;
    const MS_RENDER_WITH_OGL = 104;
    const MS_RENDER_WITH_AGG = 105;
    const MS_RENDER_WITH_KML = 106;
    const MS_RENDER_WITH_UTFGRID = 107;
    const MS_RENDER_WITH_MVT = 108;
    const MS_NUM_CHECK_NONE = 0;
    const MS_NUM_CHECK_RANGE = 1;
    const MS_NUM_CHECK_GT = 2;
    const MS_NUM_CHECK_GTE = 3;
    const MS_FILE_MAP = 0;
    const MS_FILE_SYMBOL = 1;
    const MS_INCHES = 0;
    const MS_FEET = 1;
    const MS_MILES = 2;
    const MS_METERS = 3;
    const MS_KILOMETERS = 4;
    const MS_DD = 5;
    const MS_PIXELS = 6;
    const MS_PERCENTAGES = 7;
    const MS_NAUTICALMILES = 8;
    const MS_INHERIT = -1;
    const MS_SHAPE_POINT = 0;
    const MS_SHAPE_LINE = 1;
    const MS_SHAPE_POLYGON = 2;
    const MS_SHAPE_NULL = 3;
    const MS_LAYER_POINT = 0;
    const MS_LAYER_LINE = 1;
    const MS_LAYER_POLYGON = 2;
    const MS_LAYER_RASTER = 3;
    const MS_LAYER_ANNOTATION = 4;
    const MS_LAYER_QUERY = 5;
    const MS_LAYER_CIRCLE = 6;
    const MS_LAYER_TILEINDEX = 7;
    const MS_LAYER_CHART = 8;
    const MS_TRUETYPE = 0;
    const MS_BITMAP = 1;
    const MS_FIRST_MATCHING_CLASS = 0;
    const MS_ALL_MATCHING_CLASSES = 1;
    const MS_POSITIONS_LENGTH = 14;
    const MS_UL = 101;
    const MS_LR = 102;
    const MS_UR = 103;
    const MS_LL = 104;
    const MS_CR = 105;
    const MS_CL = 106;
    const MS_UC = 107;
    const MS_LC = 108;
    const MS_CC = 109;
    const MS_AUTO = 110;
    const MS_XY = 111;
    const MS_NONE = 112;
    const MS_AUTO2 = 113;
    const MS_FOLLOW = 114;
    const MS_TINY = 5;
    const MS_SMALL = 7;
    const MS_MEDIUM = 10;
    const MS_LARGE = 13;
    const MS_GIANT = 16;
    const MS_NORMAL = 0;
    const MS_HILITE = 1;
    const MS_SELECTED = 2;
    const MS_INLINE = 0;
    const MS_SHAPEFILE = 1;
    const MS_TILED_SHAPEFILE = 2;
    const MS_UNUSED_2 = 3;
    const MS_OGR = 4;
    const MS_UNUSED_1 = 5;
    const MS_POSTGIS = 6;
    const MS_WMS = 7;
    const MS_ORACLESPATIAL = 8;
    const MS_WFS = 9;
    const MS_GRATICULE = 10;
    const MS_MYSQL = 11;
    const MS_RASTER = 12;
    const MS_PLUGIN = 13;
    const MS_UNION = 14;
    const MS_UVRASTER = 15;
    const MS_CONTOUR = 16;
    const MS_KERNELDENSITY = 17;
    const MS_IDW = 18;
    const MS_FLATGEOBUF = 19;
    const MS_RASTER_LABEL = 20;
    const MS_DB_XBASE = 0;
    const MS_DB_CSV = 1;
    const MS_DB_MYSQL = 2;
    const MS_DB_ORACLE = 3;
    const MS_DB_POSTGRES = 4;
    const MS_JOIN_ONE_TO_ONE = 0;
    const MS_JOIN_ONE_TO_MANY = 1;
    const MS_SINGLE = 0;
    const MS_MULTIPLE = 1;
    const MS_QUERY_SINGLE = 0;
    const MS_QUERY_MULTIPLE = 1;
    const MS_QUERY_IS_NULL = 0;
    const MS_QUERY_BY_POINT = 1;
    const MS_QUERY_BY_RECT = 2;
    const MS_QUERY_BY_SHAPE = 3;
    const MS_QUERY_BY_ATTRIBUTE = 4;
    const MS_QUERY_BY_INDEX = 5;
    const MS_QUERY_BY_FILTER = 6;
    const MS_ALIGN_DEFAULT = 0;
    const MS_ALIGN_LEFT = 1;
    const MS_ALIGN_CENTER = 2;
    const MS_ALIGN_RIGHT = 3;
    const MS_CJC_NONE = 0;
    const MS_CJC_BEVEL = 1;
    const MS_CJC_BUTT = 2;
    const MS_CJC_MITER = 3;
    const MS_CJC_ROUND = 4;
    const MS_CJC_SQUARE = 5;
    const MS_CJC_TRIANGLE = 6;
    const MS_CJC_DEFAULT_JOIN_MAXSIZE = 3;
    const MS_SUCCESS = 0;
    const MS_FAILURE = 1;
    const MS_DONE = 2;
    const MS_IMAGEMODE_PC256 = 0;
    const MS_IMAGEMODE_RGB = 1;
    const MS_IMAGEMODE_RGBA = 2;
    const MS_IMAGEMODE_INT16 = 3;
    const MS_IMAGEMODE_FLOAT32 = 4;
    const MS_IMAGEMODE_BYTE = 5;
    const MS_IMAGEMODE_FEATURE = 6;
    const MS_IMAGEMODE_NULL = 7;
    const MS_IMAGEMODE_FLOAT64 = 8;
    const MS_GEOS_EQUALS = 0;
    const MS_GEOS_DISJOINT = 1;
    const MS_GEOS_TOUCHES = 2;
    const MS_GEOS_OVERLAPS = 3;
    const MS_GEOS_CROSSES = 4;
    const MS_GEOS_INTERSECTS = 5;
    const MS_GEOS_WITHIN = 6;
    const MS_GEOS_CONTAINS = 7;
    const MS_GEOS_BEYOND = 8;
    const MS_GEOS_DWITHIN = 9;
    const MS_TRANSFORM_NONE = 0;
    const MS_TRANSFORM_ROUND = 1;
    const MS_TRANSFORM_SNAPTOGRID = 2;
    const MS_TRANSFORM_FULLRESOLUTION = 3;
    const MS_TRANSFORM_SIMPLIFY = 4;
    const MS_COMPOP_CLEAR = 0;
    const MS_COMPOP_SRC = 1;
    const MS_COMPOP_DST = 2;
    const MS_COMPOP_SRC_OVER = 3;
    const MS_COMPOP_DST_OVER = 4;
    const MS_COMPOP_SRC_IN = 5;
    const MS_COMPOP_DST_IN = 6;
    const MS_COMPOP_SRC_OUT = 7;
    const MS_COMPOP_DST_OUT = 8;
    const MS_COMPOP_SRC_ATOP = 9;
    const MS_COMPOP_DST_ATOP = 10;
    const MS_COMPOP_XOR = 11;
    const MS_COMPOP_PLUS = 12;
    const MS_COMPOP_MINUS = 13;
    const MS_COMPOP_MULTIPLY = 14;
    const MS_COMPOP_SCREEN = 15;
    const MS_COMPOP_OVERLAY = 16;
    const MS_COMPOP_DARKEN = 17;
    const MS_COMPOP_LIGHTEN = 18;
    const MS_COMPOP_COLOR_DODGE = 19;
    const MS_COMPOP_COLOR_BURN = 20;
    const MS_COMPOP_HARD_LIGHT = 21;
    const MS_COMPOP_SOFT_LIGHT = 22;
    const MS_COMPOP_DIFFERENCE = 23;
    const MS_COMPOP_EXCLUSION = 24;
    const MS_COMPOP_CONTRAST = 25;
    const MS_COMPOP_INVERT = 26;
    const MS_COMPOP_INVERT_RGB = 27;
    const MS_COMPOP_HSL_HUE = 28;
    const MS_COMPOP_HSL_LUMINOSITY = 29;
    const MS_COMPOP_HSL_SATURATION = 30;
    const MS_COMPOP_HSL_COLOR = 31;
    const MS_STYLE_BINDING_LENGTH = 12;
    const MS_STYLE_BINDING_SIZE = 0;
    const MS_STYLE_BINDING_WIDTH = 1;
    const MS_STYLE_BINDING_ANGLE = 2;
    const MS_STYLE_BINDING_COLOR = 3;
    const MS_STYLE_BINDING_OUTLINECOLOR = 4;
    const MS_STYLE_BINDING_SYMBOL = 5;
    const MS_STYLE_BINDING_OUTLINEWIDTH = 6;
    const MS_STYLE_BINDING_OPACITY = 7;
    const MS_STYLE_BINDING_OFFSET_X = 8;
    const MS_STYLE_BINDING_OFFSET_Y = 9;
    const MS_STYLE_BINDING_POLAROFFSET_PIXEL = 10;
    const MS_STYLE_BINDING_POLAROFFSET_ANGLE = 11;
    const MS_LABEL_BINDING_LENGTH = 12;
    const MS_LABEL_BINDING_SIZE = 0;
    const MS_LABEL_BINDING_ANGLE = 1;
    const MS_LABEL_BINDING_COLOR = 2;
    const MS_LABEL_BINDING_OUTLINECOLOR = 3;
    const MS_LABEL_BINDING_FONT = 4;
    const MS_LABEL_BINDING_PRIORITY = 5;
    const MS_LABEL_BINDING_POSITION = 6;
    const MS_LABEL_BINDING_SHADOWSIZEX = 7;
    const MS_LABEL_BINDING_SHADOWSIZEY = 8;
    const MS_LABEL_BINDING_OFFSET_X = 9;
    const MS_LABEL_BINDING_OFFSET_Y = 10;
    const MS_LABEL_BINDING_ALIGN = 11;
    const MS_TOKEN_LOGICAL_AND = 300;
    const MS_TOKEN_LOGICAL_OR = 301;
    const MS_TOKEN_LOGICAL_NOT = 302;
    const MS_TOKEN_LITERAL_NUMBER = 310;
    const MS_TOKEN_LITERAL_STRING = 311;
    const MS_TOKEN_LITERAL_TIME = 312;
    const MS_TOKEN_LITERAL_SHAPE = 313;
    const MS_TOKEN_LITERAL_BOOLEAN = 314;
    const MS_TOKEN_COMPARISON_EQ = 320;
    const MS_TOKEN_COMPARISON_NE = 321;
    const MS_TOKEN_COMPARISON_GT = 322;
    const MS_TOKEN_COMPARISON_LT = 323;
    const MS_TOKEN_COMPARISON_LE = 324;
    const MS_TOKEN_COMPARISON_GE = 325;
    const MS_TOKEN_COMPARISON_IEQ = 326;
    const MS_TOKEN_COMPARISON_RE = 327;
    const MS_TOKEN_COMPARISON_IRE = 328;
    const MS_TOKEN_COMPARISON_IN = 329;
    const MS_TOKEN_COMPARISON_LIKE = 330;
    const MS_TOKEN_COMPARISON_INTERSECTS = 331;
    const MS_TOKEN_COMPARISON_DISJOINT = 332;
    const MS_TOKEN_COMPARISON_TOUCHES = 333;
    const MS_TOKEN_COMPARISON_OVERLAPS = 334;
    const MS_TOKEN_COMPARISON_CROSSES = 335;
    const MS_TOKEN_COMPARISON_WITHIN = 336;
    const MS_TOKEN_COMPARISON_CONTAINS = 337;
    const MS_TOKEN_COMPARISON_EQUALS = 338;
    const MS_TOKEN_COMPARISON_BEYOND = 339;
    const MS_TOKEN_COMPARISON_DWITHIN = 340;
    const MS_TOKEN_FUNCTION_LENGTH = 350;
    const MS_TOKEN_FUNCTION_TOSTRING = 351;
    const MS_TOKEN_FUNCTION_COMMIFY = 352;
    const MS_TOKEN_FUNCTION_AREA = 353;
    const MS_TOKEN_FUNCTION_ROUND = 354;
    const MS_TOKEN_FUNCTION_FROMTEXT = 355;
    const MS_TOKEN_FUNCTION_BUFFER = 356;
    const MS_TOKEN_FUNCTION_DIFFERENCE = 357;
    const MS_TOKEN_FUNCTION_SIMPLIFY = 358;
    const MS_TOKEN_FUNCTION_SIMPLIFYPT = 359;
    const MS_TOKEN_FUNCTION_GENERALIZE = 360;
    const MS_TOKEN_FUNCTION_SMOOTHSIA = 361;
    const MS_TOKEN_FUNCTION_CENTERLINE = 362;
    const MS_TOKEN_FUNCTION_DENSIFY = 363;
    const MS_TOKEN_FUNCTION_OUTER = 364;
    const MS_TOKEN_FUNCTION_INNER = 365;
    const MS_TOKEN_FUNCTION_JAVASCRIPT = 366;
    const MS_TOKEN_FUNCTION_UPPER = 367;
    const MS_TOKEN_FUNCTION_LOWER = 368;
    const MS_TOKEN_FUNCTION_INITCAP = 369;
    const MS_TOKEN_FUNCTION_FIRSTCAP = 370;
    const MS_TOKEN_BINDING_DOUBLE = 380;
    const MS_TOKEN_BINDING_INTEGER = 381;
    const MS_TOKEN_BINDING_STRING = 382;
    const MS_TOKEN_BINDING_TIME = 383;
    const MS_TOKEN_BINDING_SHAPE = 384;
    const MS_TOKEN_BINDING_MAP_CELLSIZE = 385;
    const MS_TOKEN_BINDING_DATA_CELLSIZE = 386;
    const MS_PARSE_TYPE_BOOLEAN = 0;
    const MS_PARSE_TYPE_STRING = 1;
    const MS_PARSE_TYPE_SHAPE = 2;
    const MS_PARSE_TYPE_SLD = 3;
    const MS_NOOVERRIDE = -1111;
    const MS_STYLE_SINGLE_SIDED_OFFSET = -99;
    const MS_STYLE_DOUBLE_SIDED_OFFSET = -999;
    const MS_LABEL_PERPENDICULAR_OFFSET = -99;
    const MS_LABEL_PERPENDICULAR_TOP_OFFSET = 99;
    const MS_SCALEBAR_INTERVALS_MIN = 1;
    const MS_SCALEBAR_INTERVALS_MAX = 100;
    const MS_SCALEBAR_WIDTH_MIN = 5;
    const MS_SCALEBAR_WIDTH_MAX = 1000;
    const MS_SCALEBAR_HEIGHT_MIN = 2;
    const MS_SCALEBAR_HEIGHT_MAX = 100;
    const MS_SCALEBAR_OFFSET_MIN = -50;
    const MS_SCALEBAR_OFFSET_MAX = 50;
    const MS_LEGEND_KEYSIZE_MIN = 5;
    const MS_LEGEND_KEYSIZE_MAX = 1000;
    const MS_LEGEND_KEYSPACING_MIN = 0;
    const MS_LEGEND_KEYSPACING_MAX = 50;
    const MS_RESOLUTION_MAX = 1000;
    const MS_RESOLUTION_MIN = 10;
    const MS_VERSION_MAJOR = 8;
    const MS_VERSION_MINOR = 6;
    const MS_VERSION_REV = 1;
    const MS_VERSION = '8.6.1';
    const MS_VERSION_NUM = 80601;
    const MS_NOERR = 0;
    const MS_IOERR = 1;
    const MS_MEMERR = 2;
    const MS_TYPEERR = 3;
    const MS_SYMERR = 4;
    const MS_REGEXERR = 5;
    const MS_TTFERR = 6;
    const MS_DBFERR = 7;
    const MS_IDENTERR = 9;
    const MS_EOFERR = 10;
    const MS_PROJERR = 11;
    const MS_MISCERR = 12;
    const MS_CGIERR = 13;
    const MS_WEBERR = 14;
    const MS_IMGERR = 15;
    const MS_HASHERR = 16;
    const MS_JOINERR = 17;
    const MS_NOTFOUND = 18;
    const MS_SHPERR = 19;
    const MS_PARSEERR = 20;
    const MS_UNUSEDERR = 21;
    const MS_OGRERR = 22;
    const MS_QUERYERR = 23;
    const MS_WMSERR = 24;
    const MS_WMSCONNERR = 25;
    const MS_ORACLESPATIALERR = 26;
    const MS_WFSERR = 27;
    const MS_WFSCONNERR = 28;
    const MS_MAPCONTEXTERR = 29;
    const MS_HTTPERR = 30;
    const MS_CHILDERR = 31;
    const MS_WCSERR = 32;
    const MS_GEOSERR = 33;
    const MS_RECTERR = 34;
    const MS_TIMEERR = 35;
    const MS_GMLERR = 36;
    const MS_SOSERR = 37;
    const MS_NULLPARENTERR = 38;
    const MS_AGGERR = 39;
    const MS_OWSERR = 40;
    const MS_OGLERR = 41;
    const MS_RENDERERERR = 42;
    const MS_V8ERR = 43;
    const MS_OGCAPIERR = 44;
    const MS_FGBERR = 45;
    const MS_NUMERRORCODES = 46;
    const MESSAGELENGTH = 2048;
    const ROUTINELENGTH = 64;
    const HTTPSTATUSLENGTH = 128;
    const MS_ERROR_LANGUAGE = 'en-US';
    const MS_HTTP_400_BAD_REQUEST = '400 Bad Request';
    const MS_HTTP_500_INTERNAL_SERVER_ERROR = '500 Internal Server Error';
    const MS_DEBUGLEVEL_ERRORSONLY = 0;
    const MS_DEBUGLEVEL_DEBUG = 1;
    const MS_DEBUGLEVEL_TUNING = 2;
    const MS_DEBUGLEVEL_V = 3;
    const MS_DEBUGLEVEL_VV = 4;
    const MS_DEBUGLEVEL_VVV = 5;
    const MS_DEBUGLEVEL_DEVDEBUG = 20;
    const SHX_BUFFER_PAGE = 1024;
    const MS_SHAPEFILE_POINT = 1;
    const MS_SHAPEFILE_ARC = 3;
    const MS_SHAPEFILE_POLYGON = 5;
    const MS_SHAPEFILE_MULTIPOINT = 8;
    const MS_SHP_POINTZ = 11;
    const MS_SHP_ARCZ = 13;
    const MS_SHP_POLYGONZ = 15;
    const MS_SHP_MULTIPOINTZ = 18;
    const MS_SHP_POINTM = 21;
    const MS_SHP_ARCM = 23;
    const MS_SHP_POLYGONM = 25;
    const MS_SHP_MULTIPOINTM = 28;
    const FTString = 0;
    const FTInteger = 1;
    const FTDouble = 2;
    const FTInvalid = 3;
    const wkp_none = 0;
    const wkp_lonlat = 1;
    const wkp_gmerc = 2;
    const MS_SYMBOL_SIMPLE = 1000;
    const MS_SYMBOL_VECTOR = 1001;
    const MS_SYMBOL_ELLIPSE = 1002;
    const MS_SYMBOL_PIXMAP = 1003;
    const MS_SYMBOL_TRUETYPE = 1004;
    const MS_SYMBOL_HATCH = 1005;
    const MS_SYMBOL_SVG = 1006;
    const MS_SYMBOL_ALLOCSIZE = 64;
    const MS_MAXVECTORPOINTS = 100;
    const MS_MAXPATTERNLENGTH = 10;
    const MS_IMAGECACHESIZE = 6;
    const MS_HASHSIZE = 41;
    const MS_CONFIG_SECTION = 3000;
    const MS_CONFIG_SECTION_ENV = 3001;
    const MS_CONFIG_SECTION_MAPS = 3002;
    const MS_CONFIG_SECTION_PLUGINS = 3003;
    const MS_DEFAULT_CGI_PARAMS = 100;
    const MS_GET_REQUEST = 0;
    const MS_POST_REQUEST = 1;

    // methods
    public static function msSaveImage(?\mapObj $arg1, ?\imageObj $arg2, string $arg3) : int {}
    public static function msFreeImage(?\imageObj $arg1) : void {}
    public static function msSetup() : int {}
    public static function msCleanup() : void {}
    public static function msLoadMapFromString(string $arg1, string $arg2, ?\configObj $arg3) : ?\mapObj {}
    public static function msGetErrorObj() : ?\errorObj {}
    public static function msResetErrorList() : void {}
    public static function msGetVersion() : ?string {}
    public static function msGetVersionInt() : int {}
    public static function msGetErrorString(string $arg1) : ?string {}
    public static function msLoadConfig(string $arg1) : ?\configObj {}
    public static function msFreeConfig(?\configObj $arg1) : void {}
    public static function msConfigGetEnv(?\configObj $arg1, string $arg2) : ?string {}
    public static function msConfigGetMap(?\configObj $arg1, string $arg2, string $arg3) : ?string {}
    public static function msConfigGetPlugin(?\configObj $arg1, string $arg2) : ?string {}
    public static function msConnPoolCloseUnreferenced() : void {}
    public static function msIO_resetHandlers() : void {}
    public static function msIO_installStdoutToBuffer() : void {}
    public static function msIO_installStdinFromBuffer() : void {}
    public static function msIO_stripStdoutBufferContentType() : ?string {}
    public static function msIO_stripStdoutBufferContentHeaders() : void {}
    public static function msIO_getStdoutBufferString() : ?string {}
    public static function msIO_getStdoutBufferBytes() {}
    public static function msIO_getAndStripStdoutBufferMimeHeaders() : ?\hashTableObj {}
}

class markerCacheMemberObj  {

    // methods
    public function id_get() : int {}
    public function bounds_get() : ?\rectObj {}
    public function __construct() {}
    public function __set(string $arg1, $arg2 = null) : void {}
    public function __get(string $arg1) {}
    public function __isset(string $arg1) : bool {}
}

class outputFormatObj  {

    // methods
    public function numformatoptions_get() : int {}
    public function name_set(string $arg1) : void {}
    public function name_get() : ?string {}
    public function mimetype_set(string $arg1) : void {}
    public function mimetype_get() : ?string {}
    public function driver_set(string $arg1) : void {}
    public function driver_get() : ?string {}
    public function extension_set(string $arg1) : void {}
    public function extension_get() : ?string {}
    public function renderer_set(int $arg1) : void {}
    public function renderer_get() : int {}
    public function imagemode_set(int $arg1) : void {}
    public function imagemode_get() : int {}
    public function transparent_set(int $arg1) : void {}
    public function transparent_get() : int {}
    public function bands_set(int $arg1) : void {}
    public function bands_get() : int {}
    public function inmapfile_set(int $arg1) : void {}
    public function inmapfile_get() : int {}
    public function __construct(string $arg1, string $arg2 = unknown) {}
    public function setExtension(string $arg1) : void {}
    public function setMimetype(string $arg1) : void {}
    public function setOption(string $arg1, string $arg2) : void {}
    public function validate() : int {}
    public function getOption(string $arg1, string $arg2 = unknown) : ?string {}
    public function getOptionAt(int $arg1) : ?string {}
    public function attachDevice(?\SWIG\_p_void $arg1) : void {}
    public function __set(string $arg1, $arg2 = null) : void {}
    public function __get(string $arg1) {}
    public function __isset(string $arg1) : bool {}
}

class pointObj  {

    // methods
    public function x_set(float $arg1) : void {}
    public function x_get() : float {}
    public function y_set(float $arg1) : void {}
    public function y_get() : float {}
    public function z_set(float $arg1) : void {}
    public function z_get() : float {}
    public function m_set(float $arg1) : void {}
    public function m_get() : float {}
    public function __construct(float $arg1 = unknown, float $arg2 = unknown, float $arg3 = unknown, float $arg4 = unknown) {}
    public function project(\projectionObj|\reprojectionObj|null $arg1, ?\projectionObj $arg2 = null) : int {}
    public function draw(?\mapObj $arg1, ?\layerObj $arg2, ?\imageObj $arg3, int $arg4, string $arg5) : int {}
    public function distanceToPoint(?\pointObj $arg1) : float {}
    public function distanceToSegment(?\pointObj $arg1, ?\pointObj $arg2) : float {}
    public function distanceToShape(?\shapeObj $arg1) : float {}
    public function setXY(float $arg1, float $arg2, float $arg3 = unknown) : int {}
    public function setXYZ(float $arg1, float $arg2, float $arg3, float $arg4 = unknown) : int {}
    public function setXYZM(float $arg1, float $arg2, float $arg3, float $arg4) : int {}
    public function toString() : ?string {}
    public function toShape() : ?\shapeObj {}
    public function __set(string $arg1, $arg2 = null) : void {}
    public function __get(string $arg1) {}
    public function __isset(string $arg1) : bool {}
}

class projectionObj  {

    // methods
    public function numargs_get() : int {}
    public function generation_number_get() : int {}
    public function wellknownprojection_set(int $arg1) : void {}
    public function wellknownprojection_get() : int {}
    public function __construct(string $arg1) {}
    public function setWKTProjection(string $arg1) : int {}
    public function getUnits() : int {}
    public function __set(string $arg1, $arg2 = null) : void {}
    public function __get(string $arg1) {}
    public function __isset(string $arg1) : bool {}
}

class queryMapObj  {

    // methods
    public function map_get() : ?\mapObj {}
    public function height_set(int $arg1) : void {}
    public function height_get() : int {}
    public function width_set(int $arg1) : void {}
    public function width_get() : int {}
    public function status_set(int $arg1) : void {}
    public function status_get() : int {}
    public function style_set(int $arg1) : void {}
    public function style_get() : int {}
    public function color_set(?\colorObj $arg1) : void {}
    public function color_get() : ?\colorObj {}
    public function updateFromString(string $arg1) : int {}
    public function convertToString() : ?string {}
    public function __construct() {}
    public function __set(string $arg1, $arg2 = null) : void {}
    public function __get(string $arg1) {}
    public function __isset(string $arg1) : bool {}
}

class rectObj  {

    // methods
    public function minx_set(float $arg1) : void {}
    public function minx_get() : float {}
    public function miny_set(float $arg1) : void {}
    public function miny_get() : float {}
    public function maxx_set(float $arg1) : void {}
    public function maxx_get() : float {}
    public function maxy_set(float $arg1) : void {}
    public function maxy_get() : float {}
    public function __construct(float $arg1 = unknown, float $arg2 = unknown, float $arg3 = unknown, float $arg4 = unknown, int $arg5 = unknown) {}
    public function project(\projectionObj|\reprojectionObj|null $arg1, ?\projectionObj $arg2 = null) : int {}
    public function fit(int $arg1, int $arg2) : float {}
    public function draw(?\mapObj $arg1, ?\layerObj $arg2, ?\imageObj $arg3, int $arg4, string $arg5) : int {}
    public function getCenter() : ?\pointObj {}
    public function toPolygon() : ?\shapeObj {}
    public function toString() : ?string {}
    public function __set(string $arg1, $arg2 = null) : void {}
    public function __get(string $arg1) {}
    public function __isset(string $arg1) : bool {}
}

class referenceMapObj  {

    // methods
    public function map_get() : ?\mapObj {}
    public function extent_set(?\rectObj $arg1) : void {}
    public function extent_get() : ?\rectObj {}
    public function height_set(int $arg1) : void {}
    public function height_get() : int {}
    public function width_set(int $arg1) : void {}
    public function width_get() : int {}
    public function color_set(?\colorObj $arg1) : void {}
    public function color_get() : ?\colorObj {}
    public function outlinecolor_set(?\colorObj $arg1) : void {}
    public function outlinecolor_get() : ?\colorObj {}
    public function image_set(string $arg1) : void {}
    public function image_get() : ?string {}
    public function status_set(int $arg1) : void {}
    public function status_get() : int {}
    public function marker_set(int $arg1) : void {}
    public function marker_get() : int {}
    public function markername_set(string $arg1) : void {}
    public function markername_get() : ?string {}
    public function markersize_set(int $arg1) : void {}
    public function markersize_get() : int {}
    public function minboxsize_set(int $arg1) : void {}
    public function minboxsize_get() : int {}
    public function maxboxsize_set(int $arg1) : void {}
    public function maxboxsize_get() : int {}
    public function updateFromString(string $arg1) : int {}
    public function convertToString() : ?string {}
    public function __construct() {}
    public function __set(string $arg1, $arg2 = null) : void {}
    public function __get(string $arg1) {}
    public function __isset(string $arg1) : bool {}
}

class reprojectionObj  {

    // methods
    public function generation_number_in_set(int $arg1) : void {}
    public function generation_number_in_get() : int {}
    public function generation_number_out_set(int $arg1) : void {}
    public function generation_number_out_get() : int {}
    public function __construct(?\projectionObj $arg1, ?\projectionObj $arg2) {}
    public function __set(string $arg1, $arg2 = null) : void {}
    public function __get(string $arg1) {}
    public function __isset(string $arg1) : bool {}
}

class resultCacheObj  {

    // methods
    public function numresults_get() : int {}
    public function hasnext_get() : int {}
    public function bounds_get() : ?\rectObj {}
    public function getResult(int $arg1) : ?\resultObj {}
    public function __construct() {}
    public function __set(string $arg1, $arg2 = null) : void {}
    public function __get(string $arg1) {}
    public function __isset(string $arg1) : bool {}
}

class resultObj  {

    // methods
    public function shapeindex_get() : int {}
    public function tileindex_get() : int {}
    public function resultindex_get() : int {}
    public function classindex_get() : int {}
    public function __construct(int $arg1) {}
    public function __set(string $arg1, $arg2 = null) : void {}
    public function __get(string $arg1) {}
    public function __isset(string $arg1) : bool {}
}

class scaleTokenEntryObj  {

    // methods
    public function minscale_set(float $arg1) : void {}
    public function minscale_get() : float {}
    public function maxscale_set(float $arg1) : void {}
    public function maxscale_get() : float {}
    public function value_set(string $arg1) : void {}
    public function value_get() : ?string {}
    public function __construct() {}
    public function __set(string $arg1, $arg2 = null) : void {}
    public function __get(string $arg1) {}
    public function __isset(string $arg1) : bool {}
}

class scaleTokenObj  {

    // methods
    public function name_set(string $arg1) : void {}
    public function name_get() : ?string {}
    public function n_entries_set(int $arg1) : void {}
    public function n_entries_get() : int {}
    public function tokens_set(?\scaleTokenEntryObj $arg1) : void {}
    public function tokens_get() : ?\scaleTokenEntryObj {}
    public function __construct() {}
    public function __set(string $arg1, $arg2 = null) : void {}
    public function __get(string $arg1) {}
    public function __isset(string $arg1) : bool {}
}

class scalebarObj  {

    // methods
    public function transparent_set(int $arg1) : void {}
    public function transparent_get() : int {}
    public function imagecolor_set(?\colorObj $arg1) : void {}
    public function imagecolor_get() : ?\colorObj {}
    public function height_set(int $arg1) : void {}
    public function height_get() : int {}
    public function width_set(int $arg1) : void {}
    public function width_get() : int {}
    public function style_set(int $arg1) : void {}
    public function style_get() : int {}
    public function intervals_set(int $arg1) : void {}
    public function intervals_get() : int {}
    public function label_set(?\labelObj $arg1) : void {}
    public function label_get() : ?\labelObj {}
    public function color_set(?\colorObj $arg1) : void {}
    public function color_get() : ?\colorObj {}
    public function backgroundcolor_set(?\colorObj $arg1) : void {}
    public function backgroundcolor_get() : ?\colorObj {}
    public function outlinecolor_set(?\colorObj $arg1) : void {}
    public function outlinecolor_get() : ?\colorObj {}
    public function units_set(int $arg1) : void {}
    public function units_get() : int {}
    public function status_set(int $arg1) : void {}
    public function status_get() : int {}
    public function position_set(int $arg1) : void {}
    public function position_get() : int {}
    public function postlabelcache_set(int $arg1) : void {}
    public function postlabelcache_get() : int {}
    public function align_set(int $arg1) : void {}
    public function align_get() : int {}
    public function offsetx_set(int $arg1) : void {}
    public function offsetx_get() : int {}
    public function offsety_set(int $arg1) : void {}
    public function offsety_get() : int {}
    public function updateFromString(string $arg1) : int {}
    public function convertToString() : ?string {}
    public function __construct() {}
    public function __set(string $arg1, $arg2 = null) : void {}
    public function __get(string $arg1) {}
    public function __isset(string $arg1) : bool {}
}

class shapeObj  {

    // methods
    public function numlines_get() : int {}
    public function numvalues_get() : int {}
    public function bounds_set(?\rectObj $arg1) : void {}
    public function bounds_get() : ?\rectObj {}
    public function type_set(int $arg1) : void {}
    public function type_get() : int {}
    public function index_set(int $arg1) : void {}
    public function index_get() : int {}
    public function tileindex_set(int $arg1) : void {}
    public function tileindex_get() : int {}
    public function classindex_set(int $arg1) : void {}
    public function classindex_get() : int {}
    public function text_set(string $arg1) : void {}
    public function text_get() : ?string {}
    public function scratch_set(int $arg1) : void {}
    public function scratch_get() : int {}
    public function resultindex_set(int $arg1) : void {}
    public function resultindex_get() : int {}
    public function __construct(int $arg1 = unknown) {}
    public static function fromWKT(string $arg1) : ?\shapeObj {}
    public function project(\projectionObj|\reprojectionObj|null $arg1, ?\projectionObj $arg2 = null) : int {}
    public function get(int $arg1) : ?\lineObj {}
    public function add(?\lineObj $arg1) : int {}
    public function draw(?\mapObj $arg1, ?\layerObj $arg2, ?\imageObj $arg3) : int {}
    public function setBounds() : void {}
    public function cloneShape() : ?\shapeObj {}
    public function copy(?\shapeObj $arg1) : int {}
    public function toWKT() : ?string {}
    public function buffer(float $arg1) : ?\shapeObj {}
    public function simplify(float $arg1) : ?\shapeObj {}
    public function topologyPreservingSimplify(float $arg1) : ?\shapeObj {}
    public function convexHull() : ?\shapeObj {}
    public function boundary() : ?\shapeObj {}
    public function getCentroid() : ?\pointObj {}
    public function Union(?\shapeObj $arg1) : ?\shapeObj {}
    public function intersection(?\shapeObj $arg1) : ?\shapeObj {}
    public function difference(?\shapeObj $arg1) : ?\shapeObj {}
    public function symDifference(?\shapeObj $arg1) : ?\shapeObj {}
    public function overlaps(?\shapeObj $arg1) : int {}
    public function within(?\shapeObj $arg1) : int {}
    public function crosses(?\shapeObj $arg1) : int {}
    public function intersects(?\shapeObj $arg1) : int {}
    public function touches(?\shapeObj $arg1) : int {}
    public function equals(?\shapeObj $arg1) : int {}
    public function disjoint(?\shapeObj $arg1) : int {}
    public function getArea() : float {}
    public function getLength() : float {}
    public function getValue(int $arg1) : ?string {}
    public function contains(\pointObj|\shapeObj|null $arg1) : int {}
    public function distanceToPoint(?\pointObj $arg1) : float {}
    public function distanceToShape(?\shapeObj $arg1) : float {}
    public function getLabelPoint() : ?\pointObj {}
    public function setValue(int $arg1, string $arg2) : int {}
    public function initValues(int $arg1) : void {}
    public function __set(string $arg1, $arg2 = null) : void {}
    public function __get(string $arg1) {}
    public function __isset(string $arg1) : bool {}
}

class shapefileObj  {

    // methods
    public function type_get() : int {}
    public function numshapes_get() : int {}
    public function bounds_get() : ?\rectObj {}
    public function __construct(string $arg1, int $arg2 = unknown) {}
    public function get(int $arg1, ?\shapeObj $arg2) : int {}
    public function getShape(int $arg1) : ?\shapeObj {}
    public function getPoint(int $arg1, ?\pointObj $arg2) : int {}
    public function getTransformed(?\mapObj $arg1, int $arg2, ?\shapeObj $arg3) : int {}
    public function getExtent(int $arg1, ?\rectObj $arg2) : void {}
    public function add(?\shapeObj $arg1) : int {}
    public function addPoint(?\pointObj $arg1) : int {}
    public function getDBF() : ?\DBFInfo {}
    public function __set(string $arg1, $arg2 = null) : void {}
    public function __get(string $arg1) {}
    public function __isset(string $arg1) : bool {}
}

class styleObj  {

    // methods
    public function refcount_get() : int {}
    public function symbolname_get() : ?string {}
    public function patternlength_set(int $arg1) : void {}
    public function patternlength_get() : int {}
    public function pattern_set(?\SWIG\_p_double $arg1) : void {}
    public function pattern_get() : \SWIG\_p_double {}
    public function angle_set(float $arg1) : void {}
    public function angle_get() : float {}
    public function autoangle_set(int $arg1) : void {}
    public function autoangle_get() : int {}
    public function antialiased_set(int $arg1) : void {}
    public function antialiased_get() : int {}
    public function color_set(?\colorObj $arg1) : void {}
    public function color_get() : ?\colorObj {}
    public function outlinecolor_set(?\colorObj $arg1) : void {}
    public function outlinecolor_get() : ?\colorObj {}
    public function opacity_set(int $arg1) : void {}
    public function opacity_get() : int {}
    public function mincolor_set(?\colorObj $arg1) : void {}
    public function mincolor_get() : ?\colorObj {}
    public function maxcolor_set(?\colorObj $arg1) : void {}
    public function maxcolor_get() : ?\colorObj {}
    public function minvalue_set(float $arg1) : void {}
    public function minvalue_get() : float {}
    public function maxvalue_set(float $arg1) : void {}
    public function maxvalue_get() : float {}
    public function rangeitem_set(string $arg1) : void {}
    public function rangeitem_get() : ?string {}
    public function rangeitemindex_set(int $arg1) : void {}
    public function rangeitemindex_get() : int {}
    public function symbol_set(int $arg1) : void {}
    public function symbol_get() : int {}
    public function size_set(float $arg1) : void {}
    public function size_get() : float {}
    public function minsize_set(float $arg1) : void {}
    public function minsize_get() : float {}
    public function maxsize_set(float $arg1) : void {}
    public function maxsize_get() : float {}
    public function gap_set(float $arg1) : void {}
    public function gap_get() : float {}
    public function initialgap_set(float $arg1) : void {}
    public function initialgap_get() : float {}
    public function linecap_set(int $arg1) : void {}
    public function linecap_get() : int {}
    public function linejoin_set(int $arg1) : void {}
    public function linejoin_get() : int {}
    public function linejoinmaxsize_set(float $arg1) : void {}
    public function linejoinmaxsize_get() : float {}
    public function width_set(float $arg1) : void {}
    public function width_get() : float {}
    public function outlinewidth_set(float $arg1) : void {}
    public function outlinewidth_get() : float {}
    public function minwidth_set(float $arg1) : void {}
    public function minwidth_get() : float {}
    public function maxwidth_set(float $arg1) : void {}
    public function maxwidth_get() : float {}
    public function offsetx_set(float $arg1) : void {}
    public function offsetx_get() : float {}
    public function offsety_set(float $arg1) : void {}
    public function offsety_get() : float {}
    public function polaroffsetpixel_set(float $arg1) : void {}
    public function polaroffsetpixel_get() : float {}
    public function polaroffsetangle_set(float $arg1) : void {}
    public function polaroffsetangle_get() : float {}
    public function minscaledenom_set(float $arg1) : void {}
    public function minscaledenom_get() : float {}
    public function maxscaledenom_set(float $arg1) : void {}
    public function maxscaledenom_get() : float {}
    public function sizeunits_set(int $arg1) : void {}
    public function sizeunits_get() : int {}
    public function __construct(?\classObj $arg1 = null) {}
    public function updateFromString(string $arg1) : int {}
    public function convertToString() : ?string {}
    public function cloneStyle() : ?\styleObj {}
    public function setSymbolByName(?\mapObj $arg1, string $arg2) : int {}
    public function removeBinding(int $arg1) : int {}
    public function setBinding(int $arg1, string $arg2) : int {}
    public function getBinding(int $arg1) : ?string {}
    public function getGeomTransform() : ?string {}
    public function setGeomTransform(string $arg1) : void {}
    public function __set(string $arg1, $arg2 = null) : void {}
    public function __get(string $arg1) {}
    public function __isset(string $arg1) : bool {}
}

class symbolObj  {

    // methods
    public function refcount_get() : int {}
    public function numpoints_get() : int {}
    public function imagepath_get() : ?string {}
    public function name_set(string $arg1) : void {}
    public function name_get() : ?string {}
    public function type_set(int $arg1) : void {}
    public function type_get() : int {}
    public function inmapfile_set(int $arg1) : void {}
    public function inmapfile_get() : int {}
    public function sizex_set(float $arg1) : void {}
    public function sizex_get() : float {}
    public function sizey_set(float $arg1) : void {}
    public function sizey_get() : float {}
    public function minx_set(float $arg1) : void {}
    public function minx_get() : float {}
    public function miny_set(float $arg1) : void {}
    public function miny_get() : float {}
    public function maxx_set(float $arg1) : void {}
    public function maxx_get() : float {}
    public function maxy_set(float $arg1) : void {}
    public function maxy_get() : float {}
    public function filled_set(int $arg1) : void {}
    public function filled_get() : int {}
    public function anchorpoint_x_set(float $arg1) : void {}
    public function anchorpoint_x_get() : float {}
    public function anchorpoint_y_set(float $arg1) : void {}
    public function anchorpoint_y_get() : float {}
    public function transparent_set(int $arg1) : void {}
    public function transparent_get() : int {}
    public function transparentcolor_set(int $arg1) : void {}
    public function transparentcolor_get() : int {}
    public function character_set(string $arg1) : void {}
    public function character_get() : ?string {}
    public function font_set(string $arg1) : void {}
    public function font_get() : ?string {}
    public function __construct(string $arg1, string $arg2 = unknown) {}
    public function setImagepath(string $arg1) : int {}
    public function setPoints(?\lineObj $arg1) : int {}
    public function getPoints() : ?\lineObj {}
    public function getImage(?\outputFormatObj $arg1) : ?\imageObj {}
    public function setImage(?\imageObj $arg1) : int {}
    public function __set(string $arg1, $arg2 = null) : void {}
    public function __get(string $arg1) {}
    public function __isset(string $arg1) : bool {}
}

class symbolSetObj  {

    // methods
    public function numsymbols_get() : int {}
    public function maxsymbols_get() : int {}
    public function filename_set(string $arg1) : void {}
    public function filename_get() : ?string {}
    public function imagecachesize_set(int $arg1) : void {}
    public function imagecachesize_get() : int {}
    public function __construct(string $arg1 = unknown) {}
    public function getSymbol(int $arg1) : ?\symbolObj {}
    public function getSymbolByName(string $arg1) : ?\symbolObj {}
    public function index(string $arg1) : int {}
    public function appendSymbol(?\symbolObj $arg1) : int {}
    public function removeSymbol(int $arg1) : ?\symbolObj {}
    public function save(string $arg1) : int {}
    public function __set(string $arg1, $arg2 = null) : void {}
    public function __get(string $arg1) {}
    public function __isset(string $arg1) : bool {}
}

class webObj  {

    // methods
    public function metadata_get() : ?\hashTableObj {}
    public function validation_get() : ?\hashTableObj {}
    public function map_get() : ?\mapObj {}
    public function imagepath_set(string $arg1) : void {}
    public function imagepath_get() : ?string {}
    public function imageurl_set(string $arg1) : void {}
    public function imageurl_get() : ?string {}
    public function temppath_set(string $arg1) : void {}
    public function temppath_get() : ?string {}
    public function header_set(string $arg1) : void {}
    public function header_get() : ?string {}
    public function footer_set(string $arg1) : void {}
    public function footer_get() : ?string {}
    public function empty_set(string $arg1) : void {}
    public function empty_get() : ?string {}
    public function error_set(string $arg1) : void {}
    public function error_get() : ?string {}
    public function minscaledenom_set(float $arg1) : void {}
    public function minscaledenom_get() : float {}
    public function maxscaledenom_set(float $arg1) : void {}
    public function maxscaledenom_get() : float {}
    public function mintemplate_set(string $arg1) : void {}
    public function mintemplate_get() : ?string {}
    public function maxtemplate_set(string $arg1) : void {}
    public function maxtemplate_get() : ?string {}
    public function queryformat_set(string $arg1) : void {}
    public function queryformat_get() : ?string {}
    public function legendformat_set(string $arg1) : void {}
    public function legendformat_get() : ?string {}
    public function browseformat_set(string $arg1) : void {}
    public function browseformat_get() : ?string {}
    public function template_set(string $arg1) : void {}
    public function template_get() : ?string {}
    public function __construct() {}
    public function updateFromString(string $arg1) : int {}
    public function convertToString() : ?string {}
    public function __set(string $arg1, $arg2 = null) : void {}
    public function __get(string $arg1) {}
    public function __isset(string $arg1) : bool {}
}

function mscleanup() : void {}
function msconfiggetenv(?\configObj $arg1, string $arg2) : ?string {}
function msconfiggetmap(?\configObj $arg1, string $arg2, string $arg3) : ?string {}
function msconfiggetplugin(?\configObj $arg1, string $arg2) : ?string {}
function msconnpoolcloseunreferenced() : void {}
function msfreeconfig(?\configObj $arg1) : void {}
function msfreeimage(?\imageObj $arg1) : void {}
function msgeterrorobj() : ?\errorObj {}
function msgeterrorstring(string $arg1) : ?string {}
function msgetversion() : ?string {}
function msgetversionint() : int {}
function msio_getandstripstdoutbuffermimeheaders() : ?\hashTableObj {}
function msio_getstdoutbufferbytes() {}
function msio_getstdoutbufferstring() : ?string {}
function msio_installstdinfrombuffer() : void {}
function msio_installstdouttobuffer() : void {}
function msio_resethandlers() : void {}
function msio_stripstdoutbuffercontentheaders() : void {}
function msio_stripstdoutbuffercontenttype() : ?string {}
function msloadconfig(string $arg1) : ?\configObj {}
function msloadmapfromstring(string $arg1, string $arg2, ?\configObj $arg3) : ?\mapObj {}
function msreseterrorlist() : void {}
function mssaveimage(?\mapObj $arg1, ?\imageObj $arg2, string $arg3) : int {}
function mssetup() : int {}
const FTDouble = 2;
const FTInteger = 1;
const FTInvalid = 3;
const FTString = 0;
const HTTPSTATUSLENGTH = 128;
const MAX_ERROR_LEN = 8192;
const MESSAGELENGTH = 2048;
const MS_AGGERR = 39;
const MS_ALIGN_CENTER = 2;
const MS_ALIGN_DEFAULT = 0;
const MS_ALIGN_LEFT = 1;
const MS_ALIGN_RIGHT = 3;
const MS_ALL_MATCHING_CLASSES = 1;
const MS_AUTO = 110;
const MS_AUTO2 = 113;
const MS_BITMAP = 1;
const MS_CC = 109;
const MS_CGIERR = 13;
const MS_CHILDERR = 31;
const MS_CJC_BEVEL = 1;
const MS_CJC_BUTT = 2;
const MS_CJC_DEFAULT_JOIN_MAXSIZE = 3;
const MS_CJC_MITER = 3;
const MS_CJC_NONE = 0;
const MS_CJC_ROUND = 4;
const MS_CJC_SQUARE = 5;
const MS_CJC_TRIANGLE = 6;
const MS_CL = 106;
const MS_CLASS_ALLOCSIZE = 8;
const MS_COMPOP_CLEAR = 0;
const MS_COMPOP_COLOR_BURN = 20;
const MS_COMPOP_COLOR_DODGE = 19;
const MS_COMPOP_CONTRAST = 25;
const MS_COMPOP_DARKEN = 17;
const MS_COMPOP_DIFFERENCE = 23;
const MS_COMPOP_DST = 2;
const MS_COMPOP_DST_ATOP = 10;
const MS_COMPOP_DST_IN = 6;
const MS_COMPOP_DST_OUT = 8;
const MS_COMPOP_DST_OVER = 4;
const MS_COMPOP_EXCLUSION = 24;
const MS_COMPOP_HARD_LIGHT = 21;
const MS_COMPOP_HSL_COLOR = 31;
const MS_COMPOP_HSL_HUE = 28;
const MS_COMPOP_HSL_LUMINOSITY = 29;
const MS_COMPOP_HSL_SATURATION = 30;
const MS_COMPOP_INVERT = 26;
const MS_COMPOP_INVERT_RGB = 27;
const MS_COMPOP_LIGHTEN = 18;
const MS_COMPOP_MINUS = 13;
const MS_COMPOP_MULTIPLY = 14;
const MS_COMPOP_OVERLAY = 16;
const MS_COMPOP_PLUS = 12;
const MS_COMPOP_SCREEN = 15;
const MS_COMPOP_SOFT_LIGHT = 22;
const MS_COMPOP_SRC = 1;
const MS_COMPOP_SRC_ATOP = 9;
const MS_COMPOP_SRC_IN = 5;
const MS_COMPOP_SRC_OUT = 7;
const MS_COMPOP_SRC_OVER = 3;
const MS_COMPOP_XOR = 11;
const MS_CONFIG_SECTION = 3000;
const MS_CONFIG_SECTION_ENV = 3001;
const MS_CONFIG_SECTION_MAPS = 3002;
const MS_CONFIG_SECTION_PLUGINS = 3003;
const MS_CONTOUR = 16;
const MS_CR = 105;
const MS_DBFERR = 7;
const MS_DB_CSV = 1;
const MS_DB_MYSQL = 2;
const MS_DB_ORACLE = 3;
const MS_DB_POSTGRES = 4;
const MS_DB_XBASE = 0;
const MS_DD = 5;
const MS_DEBUGLEVEL_DEBUG = 1;
const MS_DEBUGLEVEL_DEVDEBUG = 20;
const MS_DEBUGLEVEL_ERRORSONLY = 0;
const MS_DEBUGLEVEL_TUNING = 2;
const MS_DEBUGLEVEL_V = 3;
const MS_DEBUGLEVEL_VV = 4;
const MS_DEBUGLEVEL_VVV = 5;
const MS_DEFAULT = 2;
const MS_DEFAULT_CGI_PARAMS = 100;
const MS_DEFAULT_LABEL_PRIORITY = 1;
const MS_DELETE = 4;
const MS_DONE = 2;
const MS_EMBED = 3;
const MS_EOFERR = 10;
const MS_ERROR_LANGUAGE = 'en-US';
const MS_FAILURE = 1;
const MS_FALSE = 0;
const MS_FEET = 1;
const MS_FGBERR = 45;
const MS_FILE_MAP = 0;
const MS_FILE_SYMBOL = 1;
const MS_FIRST_MATCHING_CLASS = 0;
const MS_FLATGEOBUF = 19;
const MS_FOLLOW = 114;
const MS_GEOSERR = 33;
const MS_GEOS_BEYOND = 8;
const MS_GEOS_CONTAINS = 7;
const MS_GEOS_CROSSES = 4;
const MS_GEOS_DISJOINT = 1;
const MS_GEOS_DWITHIN = 9;
const MS_GEOS_EQUALS = 0;
const MS_GEOS_INTERSECTS = 5;
const MS_GEOS_OVERLAPS = 3;
const MS_GEOS_TOUCHES = 2;
const MS_GEOS_WITHIN = 6;
const MS_GET_REQUEST = 0;
const MS_GIANT = 16;
const MS_GMLERR = 36;
const MS_GRATICULE = 10;
const MS_HASHERR = 16;
const MS_HASHSIZE = 41;
const MS_HILITE = 1;
const MS_HTTPERR = 30;
const MS_HTTP_400_BAD_REQUEST = '400 Bad Request';
const MS_HTTP_500_INTERNAL_SERVER_ERROR = '500 Internal Server Error';
const MS_IDENTERR = 9;
const MS_IDW = 18;
const MS_IMAGECACHESIZE = 6;
const MS_IMAGEMODE_BYTE = 5;
const MS_IMAGEMODE_FEATURE = 6;
const MS_IMAGEMODE_FLOAT32 = 4;
const MS_IMAGEMODE_FLOAT64 = 8;
const MS_IMAGEMODE_INT16 = 3;
const MS_IMAGEMODE_NULL = 7;
const MS_IMAGEMODE_PC256 = 0;
const MS_IMAGEMODE_RGB = 1;
const MS_IMAGEMODE_RGBA = 2;
const MS_IMGERR = 15;
const MS_INCHES = 0;
const MS_INHERIT = -1;
const MS_INLINE = 0;
const MS_IOERR = 1;
const MS_JOINERR = 17;
const MS_JOIN_ONE_TO_MANY = 1;
const MS_JOIN_ONE_TO_ONE = 0;
const MS_KERNELDENSITY = 17;
const MS_KILOMETERS = 4;
const MS_LABEL_ALLOCSIZE = 2;
const MS_LABEL_BINDING_ALIGN = 11;
const MS_LABEL_BINDING_ANGLE = 1;
const MS_LABEL_BINDING_COLOR = 2;
const MS_LABEL_BINDING_FONT = 4;
const MS_LABEL_BINDING_LENGTH = 12;
const MS_LABEL_BINDING_OFFSET_X = 9;
const MS_LABEL_BINDING_OFFSET_Y = 10;
const MS_LABEL_BINDING_OUTLINECOLOR = 3;
const MS_LABEL_BINDING_POSITION = 6;
const MS_LABEL_BINDING_PRIORITY = 5;
const MS_LABEL_BINDING_SHADOWSIZEX = 7;
const MS_LABEL_BINDING_SHADOWSIZEY = 8;
const MS_LABEL_BINDING_SIZE = 0;
const MS_LABEL_FORCE_GROUP = 2;
const MS_LABEL_PERPENDICULAR_OFFSET = -99;
const MS_LABEL_PERPENDICULAR_TOP_OFFSET = 99;
const MS_LARGE = 13;
const MS_LAYER_ALLOCSIZE = 64;
const MS_LAYER_ANNOTATION = 4;
const MS_LAYER_CHART = 8;
const MS_LAYER_CIRCLE = 6;
const MS_LAYER_LINE = 1;
const MS_LAYER_POINT = 0;
const MS_LAYER_POLYGON = 2;
const MS_LAYER_QUERY = 5;
const MS_LAYER_RASTER = 3;
const MS_LAYER_TILEINDEX = 7;
const MS_LC = 108;
const MS_LEGEND_KEYSIZE_MAX = 1000;
const MS_LEGEND_KEYSIZE_MIN = 5;
const MS_LEGEND_KEYSPACING_MAX = 50;
const MS_LEGEND_KEYSPACING_MIN = 0;
const MS_LL = 104;
const MS_LR = 102;
const MS_MAPCONTEXTERR = 29;
const MS_MAXPATTERNLENGTH = 10;
const MS_MAXVECTORPOINTS = 100;
const MS_MAX_LABEL_FONTS = 5;
const MS_MAX_LABEL_PRIORITY = 10;
const MS_MEDIUM = 10;
const MS_MEMERR = 2;
const MS_METERS = 3;
const MS_MILES = 2;
const MS_MISCERR = 12;
const MS_MULTIPLE = 1;
const MS_MYSQL = 11;
const MS_NAUTICALMILES = 8;
const MS_NO = 0;
const MS_NOERR = 0;
const MS_NONE = 112;
const MS_NOOVERRIDE = -1111;
const MS_NORMAL = 0;
const MS_NOTFOUND = 18;
const MS_NULLPARENTERR = 38;
const MS_NUMERRORCODES = 46;
const MS_NUM_CHECK_GT = 2;
const MS_NUM_CHECK_GTE = 3;
const MS_NUM_CHECK_NONE = 0;
const MS_NUM_CHECK_RANGE = 1;
const MS_OFF = 0;
const MS_OGCAPIERR = 44;
const MS_OGLERR = 41;
const MS_OGR = 4;
const MS_OGRERR = 22;
const MS_ON = 1;
const MS_ORACLESPATIAL = 8;
const MS_ORACLESPATIALERR = 26;
const MS_OWSERR = 40;
const MS_PARSEERR = 20;
const MS_PARSE_TYPE_BOOLEAN = 0;
const MS_PARSE_TYPE_SHAPE = 2;
const MS_PARSE_TYPE_SLD = 3;
const MS_PARSE_TYPE_STRING = 1;
const MS_PERCENTAGES = 7;
const MS_PIXELS = 6;
const MS_PLUGIN = 13;
const MS_POSITIONS_LENGTH = 14;
const MS_POSTGIS = 6;
const MS_POST_REQUEST = 1;
const MS_PROJERR = 11;
const MS_QUERYERR = 23;
const MS_QUERY_BY_ATTRIBUTE = 4;
const MS_QUERY_BY_FILTER = 6;
const MS_QUERY_BY_INDEX = 5;
const MS_QUERY_BY_POINT = 1;
const MS_QUERY_BY_RECT = 2;
const MS_QUERY_BY_SHAPE = 3;
const MS_QUERY_IS_NULL = 0;
const MS_QUERY_MULTIPLE = 1;
const MS_QUERY_SINGLE = 0;
const MS_RASTER = 12;
const MS_RASTER_LABEL = 20;
const MS_RECTERR = 34;
const MS_REGEXERR = 5;
const MS_RENDERERERR = 42;
const MS_RENDER_WITH_AGG = 105;
const MS_RENDER_WITH_CAIRO_PDF = 102;
const MS_RENDER_WITH_CAIRO_RASTER = 101;
const MS_RENDER_WITH_CAIRO_SVG = 103;
const MS_RENDER_WITH_IMAGEMAP = 5;
const MS_RENDER_WITH_KML = 106;
const MS_RENDER_WITH_MVT = 108;
const MS_RENDER_WITH_OGL = 104;
const MS_RENDER_WITH_OGR = 16;
const MS_RENDER_WITH_PLUGIN = 100;
const MS_RENDER_WITH_RAWDATA = 3;
const MS_RENDER_WITH_SWF = 2;
const MS_RENDER_WITH_TEMPLATE = 8;
const MS_RENDER_WITH_UTFGRID = 107;
const MS_RESOLUTION_MAX = 1000;
const MS_RESOLUTION_MIN = 10;
const MS_SCALEBAR_HEIGHT_MAX = 100;
const MS_SCALEBAR_HEIGHT_MIN = 2;
const MS_SCALEBAR_INTERVALS_MAX = 100;
const MS_SCALEBAR_INTERVALS_MIN = 1;
const MS_SCALEBAR_OFFSET_MAX = 50;
const MS_SCALEBAR_OFFSET_MIN = -50;
const MS_SCALEBAR_WIDTH_MAX = 1000;
const MS_SCALEBAR_WIDTH_MIN = 5;
const MS_SELECTED = 2;
const MS_SHAPEFILE = 1;
const MS_SHAPEFILE_ARC = 3;
const MS_SHAPEFILE_MULTIPOINT = 8;
const MS_SHAPEFILE_POINT = 1;
const MS_SHAPEFILE_POLYGON = 5;
const MS_SHAPE_LINE = 1;
const MS_SHAPE_NULL = 3;
const MS_SHAPE_POINT = 0;
const MS_SHAPE_POLYGON = 2;
const MS_SHPERR = 19;
const MS_SHP_ARCM = 23;
const MS_SHP_ARCZ = 13;
const MS_SHP_MULTIPOINTM = 28;
const MS_SHP_MULTIPOINTZ = 18;
const MS_SHP_POINTM = 21;
const MS_SHP_POINTZ = 11;
const MS_SHP_POLYGONM = 25;
const MS_SHP_POLYGONZ = 15;
const MS_SINGLE = 0;
const MS_SMALL = 7;
const MS_SOSERR = 37;
const MS_STYLE_ALLOCSIZE = 4;
const MS_STYLE_BINDING_ANGLE = 2;
const MS_STYLE_BINDING_COLOR = 3;
const MS_STYLE_BINDING_LENGTH = 12;
const MS_STYLE_BINDING_OFFSET_X = 8;
const MS_STYLE_BINDING_OFFSET_Y = 9;
const MS_STYLE_BINDING_OPACITY = 7;
const MS_STYLE_BINDING_OUTLINECOLOR = 4;
const MS_STYLE_BINDING_OUTLINEWIDTH = 6;
const MS_STYLE_BINDING_POLAROFFSET_ANGLE = 11;
const MS_STYLE_BINDING_POLAROFFSET_PIXEL = 10;
const MS_STYLE_BINDING_SIZE = 0;
const MS_STYLE_BINDING_SYMBOL = 5;
const MS_STYLE_BINDING_WIDTH = 1;
const MS_STYLE_DOUBLE_SIDED_OFFSET = -999;
const MS_STYLE_SINGLE_SIDED_OFFSET = -99;
const MS_SUCCESS = 0;
const MS_SYMBOL_ALLOCSIZE = 64;
const MS_SYMBOL_ELLIPSE = 1002;
const MS_SYMBOL_HATCH = 1005;
const MS_SYMBOL_PIXMAP = 1003;
const MS_SYMBOL_SIMPLE = 1000;
const MS_SYMBOL_SVG = 1006;
const MS_SYMBOL_TRUETYPE = 1004;
const MS_SYMBOL_VECTOR = 1001;
const MS_SYMERR = 4;
const MS_TILED_SHAPEFILE = 2;
const MS_TIMEERR = 35;
const MS_TINY = 5;
const MS_TOKEN_BINDING_DATA_CELLSIZE = 386;
const MS_TOKEN_BINDING_DOUBLE = 380;
const MS_TOKEN_BINDING_INTEGER = 381;
const MS_TOKEN_BINDING_MAP_CELLSIZE = 385;
const MS_TOKEN_BINDING_SHAPE = 384;
const MS_TOKEN_BINDING_STRING = 382;
const MS_TOKEN_BINDING_TIME = 383;
const MS_TOKEN_COMPARISON_BEYOND = 339;
const MS_TOKEN_COMPARISON_CONTAINS = 337;
const MS_TOKEN_COMPARISON_CROSSES = 335;
const MS_TOKEN_COMPARISON_DISJOINT = 332;
const MS_TOKEN_COMPARISON_DWITHIN = 340;
const MS_TOKEN_COMPARISON_EQ = 320;
const MS_TOKEN_COMPARISON_EQUALS = 338;
const MS_TOKEN_COMPARISON_GE = 325;
const MS_TOKEN_COMPARISON_GT = 322;
const MS_TOKEN_COMPARISON_IEQ = 326;
const MS_TOKEN_COMPARISON_IN = 329;
const MS_TOKEN_COMPARISON_INTERSECTS = 331;
const MS_TOKEN_COMPARISON_IRE = 328;
const MS_TOKEN_COMPARISON_LE = 324;
const MS_TOKEN_COMPARISON_LIKE = 330;
const MS_TOKEN_COMPARISON_LT = 323;
const MS_TOKEN_COMPARISON_NE = 321;
const MS_TOKEN_COMPARISON_OVERLAPS = 334;
const MS_TOKEN_COMPARISON_RE = 327;
const MS_TOKEN_COMPARISON_TOUCHES = 333;
const MS_TOKEN_COMPARISON_WITHIN = 336;
const MS_TOKEN_FUNCTION_AREA = 353;
const MS_TOKEN_FUNCTION_BUFFER = 356;
const MS_TOKEN_FUNCTION_CENTERLINE = 362;
const MS_TOKEN_FUNCTION_COMMIFY = 352;
const MS_TOKEN_FUNCTION_DENSIFY = 363;
const MS_TOKEN_FUNCTION_DIFFERENCE = 357;
const MS_TOKEN_FUNCTION_FIRSTCAP = 370;
const MS_TOKEN_FUNCTION_FROMTEXT = 355;
const MS_TOKEN_FUNCTION_GENERALIZE = 360;
const MS_TOKEN_FUNCTION_INITCAP = 369;
const MS_TOKEN_FUNCTION_INNER = 365;
const MS_TOKEN_FUNCTION_JAVASCRIPT = 366;
const MS_TOKEN_FUNCTION_LENGTH = 350;
const MS_TOKEN_FUNCTION_LOWER = 368;
const MS_TOKEN_FUNCTION_OUTER = 364;
const MS_TOKEN_FUNCTION_ROUND = 354;
const MS_TOKEN_FUNCTION_SIMPLIFY = 358;
const MS_TOKEN_FUNCTION_SIMPLIFYPT = 359;
const MS_TOKEN_FUNCTION_SMOOTHSIA = 361;
const MS_TOKEN_FUNCTION_TOSTRING = 351;
const MS_TOKEN_FUNCTION_UPPER = 367;
const MS_TOKEN_LITERAL_BOOLEAN = 314;
const MS_TOKEN_LITERAL_NUMBER = 310;
const MS_TOKEN_LITERAL_SHAPE = 313;
const MS_TOKEN_LITERAL_STRING = 311;
const MS_TOKEN_LITERAL_TIME = 312;
const MS_TOKEN_LOGICAL_AND = 300;
const MS_TOKEN_LOGICAL_NOT = 302;
const MS_TOKEN_LOGICAL_OR = 301;
const MS_TRANSFORM_FULLRESOLUTION = 3;
const MS_TRANSFORM_NONE = 0;
const MS_TRANSFORM_ROUND = 1;
const MS_TRANSFORM_SIMPLIFY = 4;
const MS_TRANSFORM_SNAPTOGRID = 2;
const MS_TRUE = 1;
const MS_TRUETYPE = 0;
const MS_TTFERR = 6;
const MS_TYPEERR = 3;
const MS_UC = 107;
const MS_UL = 101;
const MS_UNION = 14;
const MS_UNKNOWN = -1;
const MS_UNUSEDERR = 21;
const MS_UNUSED_1 = 5;
const MS_UNUSED_2 = 3;
const MS_UR = 103;
const MS_UVRASTER = 15;
const MS_V8ERR = 43;
const MS_VERSION = '8.6.1';
const MS_VERSION_MAJOR = 8;
const MS_VERSION_MINOR = 6;
const MS_VERSION_NUM = 80601;
const MS_VERSION_REV = 1;
const MS_WCSERR = 32;
const MS_WEBERR = 14;
const MS_WFS = 9;
const MS_WFSCONNERR = 28;
const MS_WFSERR = 27;
const MS_WMS = 7;
const MS_WMSCONNERR = 25;
const MS_WMSERR = 24;
const MS_XY = 111;
const MS_YES = 1;
const ROUTINELENGTH = 64;
const SHX_BUFFER_PAGE = 1024;
const swig_runtime_data_type_pointer = 139893437669536;
const wkp_gmerc = 2;
const wkp_lonlat = 1;
const wkp_none = 0;
}

namespace SWIG {
class _int  {
}

class _p_CompositingOperation  {
}

class _p_DBFFieldType  {
}

class _p_FILE  {
}

class _p_char  {
}

class _p_debugLevel  {
}

class _p_double  {
}

class _p_expressionObj  {
}

class _p_int  {
}

class _p_int32_t  {
}

class _p_p_char  {
}

class _p_projectionContext  {
}

class _p_uint32_t  {
}

class _p_void  {
}

}
