<?php
require_once "../../../config/settings.inc.php";
require_once "../../../include/myview.php";
$t = new MyView();
$t->title = "Debug + Create Simple Graphic from LAT...LON text";

$imgurl = "/images/wait24trans.gif";
$t->content = <<<EOM

<nav aria-label="breadcrumb">
 <ol class="breadcrumb">
 <li class="breadcrumb-item"><a href="/nws/">IEM NWS Homepage</a></li>
 <li class="breadcrumb-item active" aria-current="page">Debug / Create Simple Graphic from LAT...LON</li>
 </ol>
</nav>

<p>This page generates a simple diagnostic plot of a parsed polygon from a
NWS Text Product.</p>

<textarea id="thetext" cols="80" rows="5">
LAT...LON 3310 11199 3329 11199 3328 11156 3304 11157
</textarea>
<br />
Title: <input id="thetitle" type="text" maxlength="220" size="100" value="My Title">
<br />
<input id="thebutton" type="button" role="button" value="Create Graphic Now, Please!">

<h4>Image will appear here:</h4>
<p><img id="theimage" src="{$imgurl}" class="img-fluid"></p>

<h4>GeoJSON representation here:</h4>
<pre id="thegeojson">

</pre>

EOM;
$t->jsextra = <<<EOM
<script type="text/javascript" src="index.js"></script>
EOM;
$t->render('single.phtml');
