<?php include("../../config/settings.inc.php"); ?>
<?php $THISPAGE = "roads-gis"; 
include("$rootpath/include/header.php"); ?>

<h3>GIS Products:</h3>

<p>
The Iowa Road Conditions data is available in the following GIS formats and 
Open-GIS based web services.  Please let us know if you would like to see a different format or have any questions about these data sources.
</p>

<h4>Shapefile:</h4>
<p>
Line coverage shapefile in the <i>NAD83 UTM Zone15 North</i> projection.
</p>
<ul>
 <li>Current road conditions: <a href="http://mesonet.agron.iastate.edu/data/gis/shape/26915/ia/iaroad_cond.zip">Zip File</a> (~200 KB)</li>
</ul>

<h4>Google Earth / KML</h4>

<p>This file is in KML format, which works in many applications, such as 
Google Earth.<br />

<a href="http://mesonet.agron.iastate.edu/kml/roadcond.php">http://mesonet.agron.iastate.edu/kml/roadcond.php</a>

<p>Also, here is a test layer you can use to see the various colors used.<br />

<a href="http://mesonet.agron.iastate.edu/kml/roadcond.php?test">http://mesonet.agron.iastate.edu/kml/roadcond.php?test</a>

<h4>Open GIS Consortium Web Services:</h4>
<p>
Some intelligent GIS platforms are able to consume data from remove
servers that implement <a href="http://www.opengis.org">Open GIS Consortium</a>
web services.  If your client supports this feature, try pointing your
application to one of these services.
</p>

<p><strong>Web Map Service:</strong>
<br /> <code>http://mesonet.agron.iastate.edu/cgi-bin/wms/iowa/roadcond.cgi?</code></p>



<?php include("$rootpath/include/footer.php"); ?>
</body>
</html>
