<?php 
require_once "../../config/settings.inc.php";
define("IEM_APPID", 43);
require_once "../../include/myview.php";
require_once "../../include/database.inc.php";
require_once "../../include/forms.php"; 
$t = new MyView();
$dbconn = iemdb('postgis');

$month = isset($_GET["month"]) ? intval($_GET["month"]) : intval(date("m"));
$year = isset($_GET["year"]) ? intval($_GET["year"]) : intval(date("Y"));
$segid = isset($_GET["segid"]) ? intval($_GET["segid"]) : "";
$valid = isset($_GET["valid"]) ? DateTime::createFromFormat("Y-m-d H:i", $_GET['valid']) : null;

$t->thispage = "roads-history";
$t->title = "Historical Iowa Winter Road Conditions";
$t->headextra = <<<EOM
<link rel="stylesheet" type="text/css" href="/vendor/select2/4.0.3/select2.min.css"/ >
EOM;
$t->jsextra = <<<EOF
<script src="/vendor/select2/4.0.3/select2.min.js"></script>
<script src="/vendor/jquery-filtertable/1.5.7/jquery.filtertable.min.js"></script>
		<script>
        $("#table1").filterTable({label: "Filter Table By: "});
        $(".iemselect2").select2()
		</script>
EOF;

$segselect = segmentSelect($dbconn, $year, $month, $segid);
$ys = yearSelect2(2006, $year, "year");
$ms = monthSelect($month);

$content = <<<EOF
<h3>Historical Road Conditions</h3>

<form method="GET" action="history.phtml">
<table class="table table-striped">
<tr>
 <td>Select Road Segment:</td>
 <td>Select Year</td>
 <td>Select Month</td>
 <td></td>
</tr>

<tr>
 <td>{$segselect}</td>
 <td>{$ys}</td>
 <td>{$ms}</td>
 <td><input type="submit" value="View History"></td>
</tr>
</table>
</form>
EOF;

$year1 = ($month < 7) ? ($year - 1) : $year;
$year2 = ($month < 7) ? $year : ($year + 1);

if (isset($_GET["month"]) && isset($_GET["segid"]) )
{
  $content .= "<div class=\"alert-info\">Here is a listing of historical 
  		road conditions for the segment you selected.  Updates during active
  		weather can be as frequent as every five minutes, but the following
  		display only shows when the given segment changed condition.
  		Click on the time of the report to get a listing of all road 
  		conditions for that time.</div>";
  $content .= "<br /><table id='table1' class=\"table table-condensed table-striped\">
  		<thead><tr><th>Date:</th><th>Report Time:</th><th>Road Segment</th>
  		<th>Condition</th></tr></thead><tbody>";

   $rs = pg_prepare($dbconn, "SELECT", "SELECT c.label, l.valid, "
   		."b.major, b.minor from roads_base b, "
	    ."roads_log l, roads_conditions c WHERE l.segid = $1 and "
   		."extract(month from l.valid) = $2 and l.cond_code = c.code "
   		."and b.segid = l.segid ORDER by valid ASC");
  $rs = pg_execute($dbconn, "SELECT", Array($segid, $month));

  	$lastcond = "";
  	for ($i=0; $row = pg_fetch_array($rs); $i++)
  	{
  		if ($lastcond == $row["label"]) continue;
  		$lastcond = $row["label"];
    	$ts = strtotime(substr($row["valid"],0,16));
		$content .= sprintf("<tr><td>%s</td>
    		<td><a href=\"history.phtml?valid=%s\">%s</a></td>
    		<td>%s -- %s</td><td>%s</td></tr>",
    		strftime('%d %b %Y', $ts), strftime('%Y-%m-%d%%20%H:%M', $ts),
  			strftime('%I:%M %p', $ts), $row["major"], $row["minor"],
			$row["label"]);
  	}
  	$content .= "</tbody></table>\n";
}
else if ( $valid != null )
{
    $year = intval($valid->format("Y"));
    $year1 = (intval($valid->format("m")) < 7) ? ($year - 1) : $year;
    $year2 = (intval($valid->format("m")) < 7) ? $year : ($year + 1);
    $content .= "<div class=\"alert-info\">Here is a listing of historical road conditions for a particular
   time for all roads monitored in Iowa.  Click on the segment name to get 
   a listing of historical conditions for that segment.</div>";
  $gisurl = "https://mesonet.agron.iastate.edu/archive/data/". $valid->format('Y/m/d/') ."/GIS/iaroad_cond_". $valid->format('YmdHi') .".zip";
  $content .= "<p>You can download a <a href=\"$gisurl\">gis shapefile</a> for this reporting time.";
  $content .= "<br /><table id='table1' class=\"table table-condensed table-striped\">
  		<thead><tr><th>Date:</th><th>Report Time:</th><th>Road Segment</th>
  		<th>Condition</th></tr></thead><tbody>";
    $rs = pg_prepare(
        $dbconn, "SELECT",
        "SELECT c.label, l.valid, b.major, b.minor, ".
    	"b.segid from roads_base b, roads_log l, roads_conditions c ".
        "WHERE l.valid > $1 and l.valid < $2 and l.cond_code = c.code ".
        "and b.segid = l.segid ORDER by major ASC");
    $sts = DateTime::createFromFormat("Y-m-d H:i", $_GET["valid"]);
    $sts->sub(new DateInterval('P1D'));
    $ets = DateTime::createFromFormat("Y-m-d H:i", $_GET["valid"]);
    $ets->add(new DateInterval('P1D'));
    $rs = pg_execute(
        $dbconn, "SELECT",
        Array($sts->format("Y-m-d H:i"), $ets->format("Y-m-d H:i")));

  for ($i=0; $row = pg_fetch_assoc($rs); $i++)
  {
    	$ts = strtotime(substr($row["valid"],0,16));
    	$content .= sprintf("<tr><td>%s</td><td>%s</td>
    		<td><a href=\"history.phtml?segid=%s&month=%s\">%s -- %s</a></td>
    		<td>%s</td></tr>"
  			,strftime('%d %b %Y', $ts), strftime('%I:%M %p', $ts), $row["segid"],
  			strftime('%m', $ts), $row["major"], $row["minor"],$row["label"]);
  }
  $content .= "</tbody></table>\n";
}
else
{ 
	$content .= <<<EOF
<p>The Iowa Environmental Mesonet archives the road condition reports as 
generated by the Iowa State Patrol.  From this page, you can generate a 
listing of road conditions per road segment for a particular month or a listing
of all road conditions for a particular time.  Currently, our archive is 
basically complete back to 14 Feb 2006.

<p>You can find an archive of the raw text reports by navigating the IEM's 
archive here:
<code><a href="https://mesonet.agron.iastate.edu/archive/data/2005/01/30/text/">https://mesonet.agron.iastate.edu/archive/data/2005/01/30/text/</a></code>
<br />look for the .STOIA files.  All timestamps are in 
Greenwhich Mean Time (GMT or UTC), which is 6 hours ahead of us in the winter.
The directory structure of the site is ordered by year, month, and then day. 
The example URL is for 30 Jan 2005.

<p><br />and an archive of the GIS shapefiles per report here:
<br /><code><a href="https://mesonet.agron.iastate.edu/archive/data/2005/01/30/GIS/">https://mesonet.agron.iastate.edu/archive/data/2005/01/30/GIS/</a></code>
<br />look for the iaroads_* files.  Again, timestamps are in GMT.
EOF;
}
$t->content = $content;
$t->render('single.phtml');
?>