<?php
require_once "../../config/settings.inc.php";
define("IEM_APPID", 43);
require_once "../../include/myview.php";
require_once "../../include/database.inc.php";
require_once "../../include/forms.php";
$t = new MyView();
$t->iemselect2 = TRUE;
$dbconn = iemdb('postgis');

$month = get_int404("month", intval(date("m")));
$year = get_int404("year", intval(date("Y")));
$segid = get_int404("segid", null);
$valid = isset($_GET["valid"]) ? DateTime::createFromFormat("Y-m-d H:i", xssafe($_GET['valid'])) : null;

function segmentSelect($dbconn, $year, $month, $selected, $name = "segid")
{
    $s = "<select name=\"$name\" class=\"iemselect2\">\n";
    $stname = iem_pg_prepare(
        $dbconn, <<<EOM
    SELECT segid, major, minor from roads_base
    WHERE archive_begin <= $1 and (archive_end > $1 or archive_end is null)
    ORDER by major ASC
EOM
    );
    $rs = pg_execute($dbconn, $stname, array("{$year}-{$month}-01"));
    while ($row = pg_fetch_assoc($rs)) {
        $s .= "<option value=\"" . $row["segid"] . "\" ";
        if ($row["segid"] == $selected) $s .= "SELECTED";
        $s .= ">{$row['major']} -- {$row['minor']}</option>";
    }
    return $s;
} // End of segmentSelect

$t->title = "Historical Iowa Winter Road Conditions";
$t->jsextra = <<<EOM
<script src="/vendor/jquery-filtertable/1.5.7/jquery.filtertable.min.js"></script>
<script src="history.js"></script>
EOM;

$segselect = segmentSelect($dbconn, $year, $month, strval($segid));
$ys = yearSelect(2006, $year, "year");
$ms = monthSelect($month);

$content = <<<EOM
<ul class="breadcrumb">
<li><a href="/roads/">Roads Mainpage</a></li>
<li class="active">Historical Listing</li>
</ul>
<h3>Historical Road Conditions</h3>

<form method="GET" action="history.phtml">
<table class="table table-striped">
<tr>
 <td>Select Road Segment:</td>
 <td>Select Year</td>
 <td>Select Month</td>
 <td></td>
</tr>

<tr>
 <td>{$segselect}</td>
 <td>{$ys}</td>
 <td>{$ms}</td>
 <td><input type="submit" value="View History"></td>
</tr>
</table>
</form>
EOM;


if (isset($_GET["month"]) && isset($_GET["segid"])) {
    $content .= "<div class=\"alert-info\">Here is a listing of historical 
          road conditions for the segment you selected.  Updates during active
          weather can be as frequent as every five minutes, but the following
          display only shows when the given segment changed condition.
          Click on the time of the report to get a listing of all road 
          conditions for that time.</div>";
    $content .= <<<EOM
<br />
<table id='table1' class=\"table table-condensed table-striped\">
<thead>
<tr><th>Date:</th><th>Report Time:</th><th>Road Segment</th>
<th>Condition</th></tr></thead>
<tbody>
EOM;
    $sts = new DateTime("{$year}-{$month}-01");
    $ets = new DateTime("{$year}-{$month}-01");
    $ets->modify("+1 month");
    $stname = iem_pg_prepare($dbconn, <<<EOM
    SELECT c.label, l.valid,
    b.major, b.minor from roads_base b,
    roads_log l, roads_conditions c WHERE l.segid = $1 and
    l.valid >= $2 and l.valid < $3 and l.cond_code = c.code
    and b.segid = l.segid ORDER by valid ASC
EOM);
    $rs = pg_execute($dbconn, $stname, array($segid, $sts->format("Y-m-d"), $ets->format("Y-m-d")));

    $lastcond = "";
    while ($row = pg_fetch_assoc($rs)) {
        if ($lastcond == $row["label"]) continue;
        $lastcond = $row["label"];
        $ts = strtotime(substr($row["valid"], 0, 16));
        $content .= sprintf(
            "<tr><td>%s</td>
            <td><a href=\"history.phtml?valid=%s\">%s</a></td>
            <td>%s -- %s</td><td>%s</td></tr>",
            date('d M Y', $ts),
            date('Y-m-d H:i', $ts),
            date('h:i A', $ts),
            $row["major"],
            $row["minor"],
            $row["label"]
        );
    }
    $content .= "</tbody></table>\n";
} else if (!is_null($valid)) {
    $year = intval($valid->format("Y"));
    $content .= "<div class=\"alert-info\">Here is a listing of historical road conditions for a particular
   time for all roads monitored in Iowa.  Click on the segment name to get 
   a listing of historical conditions for that segment.</div>";
    $gisurl = "{$EXTERNAL_BASEURL}/archive/data/" . $valid->format('Y/m/d/') . "/GIS/";
    $content .= "<p>Directory of <a href=\"$gisurl\">gis shapefiles</a> for this UTC date.";
    $content .= "<br /><table id='table1' class=\"table table-condensed table-striped\">
          <thead><tr><th>Date:</th><th>Report Time:</th><th>Road Segment</th>
          <th>Condition</th></tr></thead><tbody>";
    $stname = iem_pg_prepare(
        $dbconn,
        "SELECT c.label, l.valid, b.major, b.minor, " .
            "b.segid from roads_base b, roads_log l, roads_conditions c " .
            "WHERE l.valid > $1 and l.valid < $2 and l.cond_code = c.code " .
            "and b.segid = l.segid ORDER by major ASC"
    );
    $sts = DateTime::createFromFormat("Y-m-d H:i", $_GET["valid"]);
    $sts->sub(new DateInterval('P1D'));
    $ets = DateTime::createFromFormat("Y-m-d H:i", $_GET["valid"]);
    $ets->add(new DateInterval('P1D'));
    $rs = pg_execute(
        $dbconn,
        $stname,
        array($sts->format("Y-m-d H:i"), $ets->format("Y-m-d H:i"))
    );

    while ($row = pg_fetch_assoc($rs)) {
        $ts = strtotime(substr($row["valid"], 0, 16));
        $content .= sprintf(
            "<tr><td>%s</td><td>%s</td>
            <td><a href=\"history.phtml?segid=%s&month=%s\">%s -- %s</a></td>
            <td>%s</td></tr>",
            date('d M Y', $ts),
            date('h:i A', $ts),
            $row["segid"],
            date('m', $ts),
            $row["major"],
            $row["minor"],
            $row["label"]
        );
    }
    $content .= "</tbody></table>\n";
} else {
    $content .= <<<EOM
<p>The Iowa Environmental Mesonet archives the road condition reports as 
generated by the Iowa State Patrol.  From this page, you can generate a 
listing of road conditions per road segment for a particular month or a listing
of all road conditions for a particular time.  Currently, our archive is 
basically complete back to 14 Feb 2006.

<p><br />and an archive of the GIS shapefiles per report here:
<br /><code><a href="/archive/data/2005/01/30/GIS/">{$EXTERNAL_BASEURL}/archive/data/2005/01/30/GIS/</a></code>
<br />look for the iaroads_* files.  Again, timestamps are in UTC.
EOM;
}
$t->content = $content;
$t->render('single.phtml');
