<?php 
require_once '../../config/settings.inc.php';
define("IEM_APPID", 150);
require_once '../../include/myview.php';

$t = new MyView();
$t->title = 'Winter Road Conditions';
$t->refresh = 600;
$tm = time();
  $t->content = <<<EOF

<div class="row">
          <div class="col-md-4">

<strong>Website Features:</strong>
<ul>
 <li><a href="gis.phtml">GIS Products</a>
<br />Current road conditions in GIS formats + web services.</li>
 <li><a href="rc.phtml">Sortable Text</a>
<br />Sortable textual report of current road conditions.</li>
 <li><a href="maps.phtml">Web Mapping</a>
<br />Internet mapping application with RADAR included!</li>
</ul>

<strong>Links:</strong>
<ul>
 <li><a href="http://www.511ia.org/">Iowa DOT 511 Page</a></li>
 <li><a href="https://services.arcgis.com/8lRhdTsQyJpO52F1/ArcGIS/rest/services/511_IA_Road_Conditions_View/FeatureServer">Iowa DOT REST Service</a></li>
 <li><a href="https://services.arcgis.com/8lRhdTsQyJpO52F1/ArcGIS/rest/services/Midwest_Winter_Road_Conditions_View/FeatureServer">Midwest Road Conditions REST Service</a></li>
 <li><a href="http://www.dps.state.ia.us/ISP/">Iowa State Patrol</a></li>
</ul>

</div><div class="col-md-8">

<img class="img-responsive" src="/data/iaroads.png?{$tm}">

<p>An archive of this image is in the:
<a href="/timemachine/#118.0" class="btn btn-success"><i class="fa fa-clock-o"></i> IEM Time Machine</a>.</p>

<br />Data shown is provisional and without warranty.

</div></div>
EOF;
$t->render('single.phtml');
