<?php
require_once "../../config/settings.inc.php";
define("IEM_APPID", 112);
require_once "../../include/mlib.php";
force_https();
require_once "../../include/database.inc.php";
require_once "../../include/myview.php";
$t = new MyView();

$OL = '6.2.1';
$con = iemdb("postgis");
$sql = "SELECT max(valid) as valid from roads_current";
$rs = pg_query($con, $sql);

$row = pg_fetch_array($rs, 0);
$valid = substr($row["valid"],0,16);
$ts = strtotime($valid);
$valid = strftime("%I:%M %p on %d %b %Y", $ts);

$t->headextra = <<<EOF
<link type="text/css" href="/vendor/openlayers/{$OL}/ol.css" rel="stylesheet" />
<link type="text/css" href="/vendor/openlayers/{$OL}/ol-layerswitcher.css" rel="stylesheet" />
EOF;
$t->jsextra = <<<EOF
<script src="/vendor/openlayers/{$OL}/ol.js"></script>
<script src="/vendor/openlayers/{$OL}/ol-layerswitcher.js"></script>
<script src="maps.js"></script>
EOF;
$t->title = "Interactive Road Conditions";
$t->content = <<<EOF
<ol class="breadcrumb">
  <li><a href="/roads/">Roads</a></li>
  <li class="active">Interactive Mapping</li>
</ol>
<style type="text/css">
#map {
	width: 100%;
    height: 600px;
    border: 2px solid black;
}
</style>
<h3>Interactive Data Map</h3>
<div id="map"></div>

<p>This map utilizes various <a href="/json/">GeoJSON Services</a> and
<a href="/ogc/">OGC WebMap Services</a> provided by the IEM.</p>
EOF;
$t->render('single.phtml');
?>