<?php 
        $TITLE = "IEM | ASOS 2005 Precip Report";
include("../../../config/settings.inc.php");
include("$rootpath/include/header.php"); 
?>

<h3 class="heading">2005 Iowa ASOS Precipitation Report</h3><p>

<div class="text">
<b>Download this dataset:</b> 
  <a href="asos2005.xls">Excel</a>  or 
  <a href="asos2005.dat">CDF Text</a>

<TABLE border=1 cellpadding=2 cellspacing=0 width="100%">
<TR>
<TD ></TD>
<TH  valign="bottom"  align="left" >Jan</TH>
<TH  valign="bottom"  align="left" >Feb</TH>
<TH  valign="bottom"  align="left" >Mar</TH>
<TH  valign="bottom"  align="left" >Apr</TH>
<TH  valign="bottom"  align="left" >May</TH>
<TH  valign="bottom"  align="left" >Jun </TH>
<TH  valign="bottom"  align="left" >Jul</TH>
<TH  valign="bottom"  align="left" >Aug</TH>
<TH  valign="bottom"  align="left" >Sep</TH>
<TH  valign="bottom"  align="left" >Oct</TH>
<TH  valign="bottom"  align="left" >Nov</TH>
<TH  valign="bottom"  align="left" >Dec</TH>
<TH  valign="bottom"  align="left" ><B>MJJA</B></TH>
<TH  valign="bottom"  align="left" ><B>Year</B></TH>
</TR>
<?php
 $data = Array();
 $fc = file('asos2005.csv');
 while (list ($line_num, $line) = each ($fc)) {
     if (intval($line_num) > 0){
      $tokens = split (",", $line);
      $data[ $tokens[0] ] = $tokens;
     }
 }

 while (list ($key, $val) = each ($data))  {
   echo "<tr>
    <td>". $key ."</td>
    <td>". $data[$key][1] ."</td>
    <td>". $data[$key][2] ."</td>
    <td>". $data[$key][3] ."</td>
    <td>". $data[$key][4] ."</td>
    <td>". $data[$key][5] ."</td>
    <td>". $data[$key][6] ."</td>
    <td>". $data[$key][7] ."</td>
    <td>". $data[$key][8] ."</td>
    <td>". $data[$key][9] ."</td>
    <td>". $data[$key][10] ."</td>
    <td>". $data[$key][11] ."</td>
    <td>". $data[$key][12] ."</td>
    <th>". $data[$key][13] ."</th>
    <th>". $data[$key][14] ."</th>
   </tr>\n";
 }
?>
</TABLE>

<p><b>Known Issues:</b>

<br />These are not official totals, nor are they based on the special 
reports from the ASOS stations with rainfall summaries.  These values are 
based on the hourly METARs.</div>

<?php include("$rootpath/include/footer.php"); ?>
