<?php
        $Wcities = array(
 "ADU" => array("city" => "AUDUBON", "id" => "ADU", "lat" => "41.7", "lon" => "-94.92"),
 "AIO" => array("city" => "ATLANTIC", "id" => "AIO", "lat" => "41.4", "lon" => "-95.05"),
 "AWG" => array("city" => "WASHINGTON", "id" => "AWG", "lat" => "41.28", "lon" => "-91.67"),
 "AXA" => array("city" => "ALGONA", "id" => "AXA", "lat" => "43.08", "lon" => "-94.27"),
 "BNW" => array("city" => "BOONE MUNI", "id" => "BNW", "lat" => "42.05", "lon" => "-93.85"),
 "CAV" => array("city" => "CLARION", "id" => "CAV", "lat" => "42.75", "lon" => "-93.77"),
 "CBF" => array("city" => "COUNCIL BLUFFS", "id" => "CBF", "lat" => "41.27", "lon" => "-95.77"),
 "CCY" => array("city" => "CHARLES CITY", "id" => "CCY", "lat" => "43.07", "lon" => "-92.62"),
 "CKP" => array("city" => "Cherokee", "id" => "CKP", "lat" => "42.73169", "lon" => "-95.55598"),
 "CIN" => array("city" => "CARROLL", "id" => "CIN", "lat" => "42.05", "lon" => "-94.78"),
 "CNC" => array("city" => "CHARITON", "id" => "CNC", "lat" => "41.03", "lon" => "-93.37"),
 "CSQ" => array("city" => "CRESTON", "id" => "CSQ", "lat" => "41.02", "lon" => "-94.37"),
 "CWI" => array("city" => "CLINTON", "id" => "CWI", "lat" => "41.83", "lon" => "-90.33"),
 "DEH" => array("city" => "DECORAH", "id" => "DEH", "lat" => "43.28", "lon" => "-91.73"),
 "DNS" => array("city" => "DENISON", "id" => "DNS", "lat" => "41.98", "lon" => "-95.38"),
 "EBS" => array("city" => "WEBSTER CITY", "id" => "EBS", "lat" => "42.43", "lon" => "-93.87"),
 "EOK" => array("city" => "KEOKUK MUNI", "id" => "EOK", "lat" => "40.47", "lon" => "-91.43"),
 "FFL" => array("city" => "FAIRFIELD", "id" => "FFL", "lat" => "41.05", "lon" => "-91.98"),
 "FOD" => array("city" => "FORT DODGE", "id" => "FOD", "lat" => "42.55", "lon" => "-94.18"),
 "FSW" => array("city" => "FORT MADISON", "id" => "FSW", "lat" => "40.67", "lon" => "-91.33"),
 "HNR" => array("city" => "HARLAN", "id" => "HNR", "lat" => "41.59", "lon" => "-95.34"),
 "ICL" => array("city" => "CLARINDA", "id" => "ICL", "lat" => "40.72", "lon" => "-95.03"),
 "IIB" => array("city" => "INDEPENDENCE", "id" => "IIB", "lat" => "42.45", "lon" => "-91.95"),
 "IKV" => array("city" => "ANKENY", "id" => "IKV", "lat" => "41.69", "lon" => "-93.57"),
 "LRJ" => array("city" => "LE MARS", "id" => "LRJ", "lat" => "42.78", "lon" => "-96.2"),
 "MPZ" => array("city" => "MOUNT PLEASANT", "id" => "MPZ", "lat" => "40.95", "lon" => "-91.51"),
 "MUT" => array("city" => "MUSCATINE", "id" => "MUT", "lat" => "41.37", "lon" => "-91.15"),
 "MXO" => array("city" => "MONTICELLO MUNI", "id" => "MXO", "lat" => "42.23", "lon" => "-91.17"),
 "OLZ" => array("city" => "OELWEIN", "id" => "OLZ", "lat" => "42.68", "lon" => "-91.97"),
 "OOA" => array("city" => "Oskalossa", "id" => "OOA", "lat" => "41.22615", "lon" => "-92.49388"),
 "ORC" => array("city" => "ORANGE CITY", "id" => "ORC", "lat" => "42.98", "lon" => "-96.07"),
 "OXV" => array("city" => "KNOXVILLE", "id" => "OXV", "lat" => "41.3", "lon" => "-93.12"),
 "PEA" => array("city" => "PELLA", "id" => "PEA", "lat" => "41.4", "lon" => "-92.94"),
 "RDK" => array("city" => "RED OAK", "id" => "RDK", "lat" => "41.02", "lon" => "-95.27"),
 "SDA" => array("city" => "SHENANDOAH MUNI", "id" => "SDA", "lat" => "40.75", "lon" => "-95.42"),
 "SHL" => array("city" => "SHELDON", "id" => "SHL", "lat" => "43.22", "lon" => "-95.83"),
 "SLB" => array("city" => "STORM LAKE", "id" => "SLB", "lat" => "42.6", "lon" => "-95.23"),
 "TNU" => array("city" => "NEWTON MUNI", "id" => "TNU", "lat" => "41.68", "lon" => "-93.02"),
 "VTI" => array("city" => "VINTON", "id" => "VTI", "lat" => "42.22", "lon" => "-92.02")
 );
?>
