<?php
$cameras = Array(
  "KELO-001" => Array("sts" => mktime(12,0,0,9,26,2007), "ets" => time(),
          "lat" => 44.3236, "lon" => -96.7806,
          "name" => "Brookings", "active" => true,"network" => "KELO",
          "ip" => "137.216.254.38", "county" => "Brookings"),


  "SAGI4" => Array("sts" => mktime(14,0,0,7,11,2006), "ets" => time(),
                "name" => "Algona", "active" => true,"network" => "KCCI",
                "ip" => "63.86.197.94", "county" => "Kossuth"),
  "SAMI4" => Array("sts" => mktime(16,0,0,4,14,2005), "ets" => time(),
                "name" => "Ames", "active" => true,"network" => "KCCI",
                "ip" => "129.186.185.31", "county" => "Story"),
  "SBZI4" => Array("sts" => mktime(19,0,0,5,13,2004), "ets" => time(),
		"name" => "Blank Park Zoo", "active" => true,"network" => "KCCI",
		"ip" => "63.227.72.138", "county" => "Polk"),
  "SCAI4" => Array("sts" => mktime(0,0,0,10,25,2003), "ets" => time(),
		"name" => "Carroll", "active" => false, "removed" => "true","network" => "KCCI",
		"iservice" => "Dynamic Broadband", 
		"iserviceurl" => "http://www.dybb.com/",
		"ip" => "216.203.109.40", "county" => "Carroll"),
  "SCHI4" => Array("sts" => mktime(14,0,0,6,11,2006), "ets" => time(),
        "name" => "Chariton", "active" => false, "removed" => false,"network" => "KCCI",
        "ip" => "69.66.60.199", "county" => "Lucas"),
  "SCGI4" => Array("sts" => mktime(13,0,0,6,27,2006), "ets" => time(),
        "name" => "Clarion", "active" => true, "removed" => false,"network" => "KCCI",
        "ip" => "12.202.68.5", "county" => "Wright"),
  "SCSI4" => Array("sts" => mktime(0,0,0, 9,20,2003), 
					"ets" => time(),
		"name" => "Creston", "active" => true,"network" => "KCCI",
		"iservice" => "Iowa Telecom.", 
		"iserviceurl" => "http://www.iowatelecom.com/",
		"ip" => "69.66.29.70", "county" => "Union"),
  "SGLI4" => Array("sts" => mktime(0,0,0,1,19,2006), "ets" => time(),
        "name" => "Glidden", "active" => true,"network" => "KCCI",
        "ip" => "67.54.186.247", "county" => "Carroll"),
  "SFOI4" => Array("sts" => mktime(15,0,0,7,14,2006), "ets" => time(),
        "name" => "Greenfield", "active" => true,"network" => "KCCI",
        "ip" => "71.7.70.209", "county" => "Adair"),
  "SHUI4" => Array("sts" => mktime(0,0,0,12, 4,2003), "ets" => time(),
		"name" => "Humboldt", "active" => true,"network" => "KCCI",
		"iservice" => "TRV Communications",
		"iserviceurl" => "http://www.trvnet.net/",
		"ip" => "64.71.70.33", "county" => "Humboldt"),
  "SINI4" => Array("sts" => mktime(0,0,0, 2,25,2004), "ets" => time(),
		"name" => "Indianola", "active" => true,"network" => "KCCI",
		"ip" => "198.206.243.122", "county" => "Warren"),
  "SBOI4" => Array("sts" => mktime(16,0,0,10,23,2006), "ets" => time(),
                "name" => "ISU Ag Farm", "active" => true,"network" => "KCCI",
                "ip" => "69.5.129.46", "county" => "Boone"),
  "S03I4" => Array("sts" => mktime(0,0,0, 8, 5,2003),
                   "ets" => mktime(0,0,0, 8,21,2003),"network" => "KCCI",
		"name" => "Iowa State Fair 2003", "active" => false, "removed" => true,
		"ip" => "129.186.26.63"),
  "SJEI4" => Array("sts" => mktime(0,0,0, 7,23,2003), "ets" => time(),
		"name" => "Jefferson", "active" => true,"network" => "KCCI",
		"iservice" => "Jefferson Telephone Co.", 
		"iserviceurl" => "http://showcase.netins.net/web/jtco/",
		"ip" => "216.248.72.225", "county" => "Greene"), 
  "SKNI4" => Array("sts" => mktime(17,0,0,9, 26,2005), "ets" => time(),
		"name" => "Knoxville", "active" => true,"network" => "KCCI",
		"ip" => "69.66.211.12", "county" => "Marion"),
  "SCEI4" => Array("sts" => mktime(23,0,0,6, 18,2004), "ets" => time(),
		"name" => "Lake Rathbun", "active" => true,"network" => "KCCI",
		"iservice" => "Rathbun Lake Army Corp. of Engineers",
		"iserviceurl" => "http://www.nwk.usace.army.mil/rathbun/rathbun_home.htm",
		"ip" => "65.248.192.73", "county" => "Appanoose"),
  "SLOI4" => Array("sts" => mktime(18,0,0,1, 24,2007), "ets" => time(),
        "name" => "Lamoni", "active" => true,"network" => "KCCI",
        "ip" => "216.139.122.154", "county" => "Decatur"),
  "SMDI4" => Array("sts" => mktime(0,0,0,9, 16,2005),
         "ets" => time(),"network" => "KCCI",
        "name" => "Madrid", "active" => true, "removed" => false,
        "ip" => "69.66.30.247", "county" => "Boone"),
  "SMAI4" => Array("sts" => mktime(0,0,0,10, 1,2003), 
         "ets" => mktime(14,0,0,10, 26,2004),"network" => "KCCI",
		"name" => "Marshalltown", "active" => false, "removed" => true,
		"iservice" => "Dynamic Broadband", 
		"iserviceurl" => "http://www.dybb.com/",
		"ip" => "216.203.127.250", "county" => "Marshall"),
  "SNEI4" => Array("sts" => mktime(19,0,0, 4,16,2004), "ets" => time(),
		"name" => "Newton", "active" => true,"network" => "KCCI",
		"iservice" => "Dynamic Broadband", 
		"iserviceurl" => "http://www.dybb.com/",
		"ip" => "216.203.109.40", "county" => "Jasper"),
  "SNVI4" => Array("sts" => mktime(18,10,0,7, 22,2006),
         "ets" => time(),"network" => "KCCI",
        "name" => "Nevada", "active" => true, "removed" => false,
        "ip" => "69.66.56.19", "county" => "Story"),
  "SPAI4" => Array("sts" => mktime(22,0,0,5,19,2004), "ets" => time(),
		"name" => "Panora", "active" => true,"network" => "KCCI",
		"iservice" => "Panora Coop Telephone Assoc.",
		"iserviceurl" => "http://www.panoratelco.com",
		"ip" => "66.43.253.165", "county" => "Guthrie"),
  "SPEI4" => Array("sts" => mktime(0,0,0,10,16,2003), "ets" => time(),
		"name" => "Pella", "active" => true,"network" => "KCCI",
		"iservice" => "Iowa Telecom.", 
		"iserviceurl" => "http://www.iowatelecom.com/",
		"ip" => "69.66.44.147", "county" => "Marion"),
  "SROI4" => Array("sts" => mktime(0,0,0, 2,25,2004), "ets" => time(),
		"name" => "Rockwell City", "active" => true,"network" => "KCCI",
		"iservice" => "Iowa Telecom.", 
		"iserviceurl" => "http://www.iowatelecom.com/",
		"ip" => "69.66.29.140", "county" => "Calhoun"),
  "SPKI4" => Array("sts" => mktime(11,0,0, 7,2,2005), "ets" => time(),
		"name" => "Saylorville Lake", "active" => true, "network" => "KCCI",
		"ip" => "67.41.111.192", "county" => "Polk"),
  "SJWI4" => Array("sts" => mktime(9,0,0, 6,5,2007), "ets" => time(),
		"name" => "Stratford", "active" => true, "network" => "KCCI",
		"ip" => "67.55.246.251", "county" => "Boone"),
  "STQI4" => Array("sts" => mktime(0,0,0, 5,18,2005), "ets" => time(),
		"name" => "Tama", "active" => true,"network" => "KCCI",
		"ip" => "169.203.116.12", "county" => "Tama"),
  "SWBI4" => Array("sts" => mktime(0,0,0, 8,28,2003), "ets" => time(),
		"name" => "Webster City", "active" => true,"network" => "KCCI",
		"iservice" => "WMNTEL.NET", "iserviceurl" => "http://www.wmtel.net",
		"ip" => "216.51.195.93", "county" => "Hamilton"),
  "SWII4" => Array("sts" => mktime(17,30,0, 5,14,2004), "ets" => time(),
		"name" => "Winterset", "active" => true,"network" => "KCCI",
		"ip" => "66.6.127.190", "county" => "Madison"),
 );

?>
