<?php
$cameras = Array(
"IDOT-000-02" => Array("sts" => mktime(16,0,0,12, 20,2009), "ets" => time(),
    "name" => "Adair I80 Bridge Deck", "removed" => False, "active" => True, "lat" => 41.49, "lon" => -94.72,
    "state" => "IA", "network" => "IDOT", "moviebase" => "None",
    "ip" => "None", "county" => "None", "port" => "None"),
"IDOT-000-03" => Array("sts" => mktime(16,0,0,12, 20,2009), "ets" => time(),
    "name" => "Adair I80 East", "removed" => False, "active" => True, "lat" => 41.49, "lon" => -94.72,
    "state" => "IA", "network" => "IDOT", "moviebase" => "None",
    "ip" => "None", "county" => "None", "port" => "None"),
"IDOT-000-00" => Array("sts" => mktime(16,0,0,12, 20,2009), "ets" => time(),
    "name" => "Adair I80 North", "removed" => False, "active" => True, "lat" => 41.49, "lon" => -94.72,
    "state" => "IA", "network" => "IDOT", "moviebase" => "None",
    "ip" => "None", "county" => "None", "port" => "None"),
"IDOT-000-01" => Array("sts" => mktime(16,0,0,12, 20,2009), "ets" => time(),
    "name" => "Adair I80 West", "removed" => False, "active" => True, "lat" => 41.49, "lon" => -94.72,
    "state" => "IA", "network" => "IDOT", "moviebase" => "None",
    "ip" => "None", "county" => "None", "port" => "None"),
"KCCI-024" => Array("sts" => mktime(14,0,0,7, 11,2006), "ets" => time(),
    "name" => "Algona", "removed" => False, "active" => True, "lat" => 43.06895, "lon" => -94.237418,
    "state" => "IA", "network" => "KCCI", "moviebase" => "algona",
    "ip" => "69.57.27.198", "county" => "Kossuth", "port" => "80"),
"IDOT-001-00" => Array("sts" => mktime(16,0,0,12, 20,2009), "ets" => time(),
    "name" => "Algona US18 Bridge Deck", "removed" => False, "active" => True, "lat" => 43.08, "lon" => -94.39,
    "state" => "IA", "network" => "IDOT", "moviebase" => "None",
    "ip" => "None", "county" => "None", "port" => "None"),
"IDOT-001-01" => Array("sts" => mktime(16,0,0,12, 20,2009), "ets" => time(),
    "name" => "Algona US18 EB Approach", "removed" => False, "active" => True, "lat" => 43.08, "lon" => -94.39,
    "state" => "IA", "network" => "IDOT", "moviebase" => "None",
    "ip" => "None", "county" => "None", "port" => "None"),
"IDOT-001-02" => Array("sts" => mktime(16,0,0,12, 20,2009), "ets" => time(),
    "name" => "Algona US18 WB Approach", "removed" => False, "active" => True, "lat" => 43.08, "lon" => -94.39,
    "state" => "IA", "network" => "IDOT", "moviebase" => "None",
    "ip" => "None", "county" => "None", "port" => "None"),
"IDOT-001-03" => Array("sts" => mktime(16,0,0,12, 20,2009), "ets" => time(),
    "name" => "Algona West view", "removed" => False, "active" => True, "lat" => 43.08, "lon" => -94.39,
    "state" => "IA", "network" => "IDOT", "moviebase" => "None",
    "ip" => "None", "county" => "None", "port" => "None"),
"IDOT-002-00" => Array("sts" => mktime(13,0,0,12, 20,2009), "ets" => time(),
    "name" => "Alton IA Hwy10 Bridge Deck", "removed" => False, "active" => True, "lat" => 42.99, "lon" => -96.08,
    "state" => "IA", "network" => "IDOT", "moviebase" => "None",
    "ip" => "None", "county" => "None", "port" => "None"),
"IDOT-002-01" => Array("sts" => mktime(13,0,0,12, 20,2009), "ets" => time(),
    "name" => "Alton IA Hwy10 EB", "removed" => False, "active" => True, "lat" => 42.99, "lon" => -96.08,
    "state" => "IA", "network" => "IDOT", "moviebase" => "None",
    "ip" => "None", "county" => "None", "port" => "None"),
"IDOT-002-02" => Array("sts" => mktime(13,0,0,12, 20,2009), "ets" => time(),
    "name" => "Alton IA Hwy10 FP2000", "removed" => False, "active" => True, "lat" => 42.99, "lon" => -96.08,
    "state" => "IA", "network" => "IDOT", "moviebase" => "None",
    "ip" => "None", "county" => "None", "port" => "None"),
"IDOT-002-03" => Array("sts" => mktime(13,0,0,12, 20,2009), "ets" => time(),
    "name" => "Alton IA Hwy10 WB", "removed" => False, "active" => True, "lat" => 42.99, "lon" => -96.08,
    "state" => "IA", "network" => "IDOT", "moviebase" => "None",
    "ip" => "None", "county" => "None", "port" => "None"),
"IDOT-006-01" => Array("sts" => mktime(13,0,0,12, 20,2009), "ets" => time(),
    "name" => "Avoca I-80 EB", "removed" => False, "active" => True, "lat" => 41.49, "lon" => -95.28,
    "state" => "IA", "network" => "IDOT", "moviebase" => "None",
    "ip" => "None", "county" => "None", "port" => "None"),
"IDOT-006-00" => Array("sts" => mktime(13,0,0,12, 20,2009), "ets" => time(),
    "name" => "Avoca I-80 E&W Bound Decks", "removed" => False, "active" => True, "lat" => 41.49, "lon" => -95.28,
    "state" => "IA", "network" => "IDOT", "moviebase" => "None",
    "ip" => "None", "county" => "None", "port" => "None"),
"IDOT-006-02" => Array("sts" => mktime(13,0,0,12, 20,2009), "ets" => time(),
    "name" => "Avoca I-80 FP2000", "removed" => False, "active" => True, "lat" => 41.49, "lon" => -95.28,
    "state" => "IA", "network" => "IDOT", "moviebase" => "None",
    "ip" => "None", "county" => "None", "port" => "None"),
"IDOT-006-03" => Array("sts" => mktime(13,0,0,12, 20,2009), "ets" => time(),
    "name" => "Avoca I-80 WB", "removed" => False, "active" => True, "lat" => 41.49, "lon" => -95.28,
    "state" => "IA", "network" => "IDOT", "moviebase" => "None",
    "ip" => "None", "county" => "None", "port" => "None"),
"IDOT-055-02" => Array("sts" => mktime(13,0,0,12, 20,2009), "ets" => time(),
    "name" => "Bedford", "removed" => False, "active" => True, "lat" => 40.6773, "lon" => -94.7149,
    "state" => "IA", "network" => "IDOT", "moviebase" => "None",
    "ip" => "None", "county" => "None", "port" => "None"),
"IDOT-055-01" => Array("sts" => mktime(13,0,0,12, 20,2009), "ets" => time(),
    "name" => "Bedford IA 2 Bridge Deck", "removed" => False, "active" => True, "lat" => 40.6773, "lon" => -94.7149,
    "state" => "IA", "network" => "IDOT", "moviebase" => "None",
    "ip" => "None", "county" => "None", "port" => "None"),
"IDOT-055-00" => Array("sts" => mktime(13,0,0,12, 20,2009), "ets" => time(),
    "name" => "Bedford IA 2 East View", "removed" => False, "active" => True, "lat" => 40.6773, "lon" => -94.7149,
    "state" => "IA", "network" => "IDOT", "moviebase" => "None",
    "ip" => "None", "county" => "None", "port" => "None"),
"IDOT-055-03" => Array("sts" => mktime(13,0,0,12, 20,2009), "ets" => time(),
    "name" => "Bedford IA 2 West View", "removed" => False, "active" => True, "lat" => 40.6773, "lon" => -94.7149,
    "state" => "IA", "network" => "IDOT", "moviebase" => "None",
    "ip" => "None", "county" => "None", "port" => "None"),
"KCCI-034" => Array("sts" => mktime(12,0,0,5, 21,2008), "ets" => time(),
    "name" => "Big Creek Marina", "removed" => False, "active" => True, "lat" => 41.8261, "lon" => -93.7389,
    "state" => "IA", "network" => "KCCI", "moviebase" => "bigcreek",
    "ip" => "66.185.3.40", "county" => "Polk", "port" => "80"),
"KCCI-012" => Array("sts" => mktime(19,0,0,5, 13,2004), "ets" => time(),
    "name" => "Blank Park Zoo", "removed" => False, "active" => True, "lat" => 41.53, "lon" => -93.62,
    "state" => "IA", "network" => "KCCI", "moviebase" => "zoo",
    "ip" => "63.227.72.138", "county" => "Polk", "port" => "80"),
"KELO-001" => Array("sts" => mktime(15,0,0,9, 27,2007), "ets" => time(),
    "name" => "Brookings", "removed" => False, "active" => True, "lat" => 44.3236, "lon" => -96.7806,
    "state" => "SD", "network" => "KELO", "moviebase" => "brookings",
    "ip" => "137.216.254.38", "county" => "Brookings", "port" => "80"),
"IDOT-007-01" => Array("sts" => mktime(13,0,0,12, 20,2009), "ets" => time(),
    "name" => "Burlington Position 1", "removed" => False, "active" => True, "lat" => 40.81, "lon" => -91.09,
    "state" => "IA", "network" => "IDOT", "moviebase" => "None",
    "ip" => "None", "county" => "None", "port" => "None"),
"IDOT-007-02" => Array("sts" => mktime(13,0,0,12, 20,2009), "ets" => time(),
    "name" => "Burlington Position 2", "removed" => False, "active" => True, "lat" => 40.81, "lon" => -91.09,
    "state" => "IA", "network" => "IDOT", "moviebase" => "None",
    "ip" => "None", "county" => "None", "port" => "None"),
"IDOT-007-03" => Array("sts" => mktime(13,0,0,12, 20,2009), "ets" => time(),
    "name" => "Burlington Position 3", "removed" => False, "active" => True, "lat" => 40.81, "lon" => -91.09,
    "state" => "IA", "network" => "IDOT", "moviebase" => "None",
    "ip" => "None", "county" => "None", "port" => "None"),
"IDOT-007-04" => Array("sts" => mktime(13,0,0,12, 20,2009), "ets" => time(),
    "name" => "Burlington Position 4", "removed" => False, "active" => True, "lat" => 40.81, "lon" => -91.09,
    "state" => "IA", "network" => "IDOT", "moviebase" => "None",
    "ip" => "None", "county" => "None", "port" => "None"),
"IDOT-007-00" => Array("sts" => mktime(13,0,0,12, 20,2009), "ets" => time(),
    "name" => "Burlington (US 34)", "removed" => False, "active" => True, "lat" => 40.81, "lon" => -91.09,
    "state" => "IA", "network" => "IDOT", "moviebase" => "None",
    "ip" => "None", "county" => "None", "port" => "None"),
"IDOT-059-00" => Array("sts" => mktime(13,0,0,12, 20,2009), "ets" => time(),
    "name" => "Cantril Hwy 2", "removed" => False, "active" => True, "lat" => 40.6578, "lon" => -92.062,
    "state" => "IA", "network" => "IDOT", "moviebase" => "None",
    "ip" => "None", "county" => "None", "port" => "None"),
"IDOT-059-01" => Array("sts" => mktime(13,0,0,12, 20,2009), "ets" => time(),
    "name" => "Cantril Hwy 2 EB Bridge", "removed" => False, "active" => True, "lat" => 40.6578, "lon" => -92.062,
    "state" => "IA", "network" => "IDOT", "moviebase" => "None",
    "ip" => "None", "county" => "None", "port" => "None"),
"IDOT-059-02" => Array("sts" => mktime(13,0,0,12, 20,2009), "ets" => time(),
    "name" => "Cantril Hwy 2 WB", "removed" => False, "active" => True, "lat" => 40.6578, "lon" => -92.062,
    "state" => "IA", "network" => "IDOT", "moviebase" => "None",
    "ip" => "None", "county" => "None", "port" => "None"),
"KCCI-007" => Array("sts" => mktime(0,0,0,10, 25,2003), "ets" => mktime(4,0,0,5, 11,2005),
    "name" => "Carroll", "removed" => True, "active" => False, "lat" => 42.07, "lon" => -94.87,
    "state" => "IA", "network" => "KCCI", "moviebase" => "carroll",
    "ip" => "216.203.109.40", "county" => "Carroll", "port" => "80"),
"IDOT-008-00" => Array("sts" => mktime(13,0,0,12, 20,2009), "ets" => time(),
    "name" => "Carroll Position 1", "removed" => False, "active" => True, "lat" => 42.08, "lon" => -94.89,
    "state" => "IA", "network" => "IDOT", "moviebase" => "None",
    "ip" => "None", "county" => "None", "port" => "None"),
"IDOT-008-01" => Array("sts" => mktime(13,0,0,12, 20,2009), "ets" => time(),
    "name" => "Carroll Position 2", "removed" => False, "active" => True, "lat" => 42.08, "lon" => -94.89,
    "state" => "IA", "network" => "IDOT", "moviebase" => "None",
    "ip" => "None", "county" => "None", "port" => "None"),
"IDOT-008-02" => Array("sts" => mktime(13,0,0,12, 20,2009), "ets" => time(),
    "name" => "Carroll Position 3", "removed" => False, "active" => True, "lat" => 42.08, "lon" => -94.89,
    "state" => "IA", "network" => "IDOT", "moviebase" => "None",
    "ip" => "None", "county" => "None", "port" => "None"),
"IDOT-008-03" => Array("sts" => mktime(13,0,0,12, 20,2009), "ets" => time(),
    "name" => "Carroll Position 4", "removed" => False, "active" => True, "lat" => 42.08, "lon" => -94.89,
    "state" => "IA", "network" => "IDOT", "moviebase" => "None",
    "ip" => "None", "county" => "None", "port" => "None"),
"IDOT-008-04" => Array("sts" => mktime(13,0,0,12, 20,2009), "ets" => time(),
    "name" => "Carroll Position 5", "removed" => False, "active" => True, "lat" => 42.08, "lon" => -94.89,
    "state" => "IA", "network" => "IDOT", "moviebase" => "None",
    "ip" => "None", "county" => "None", "port" => "None"),
"KCRG-001" => Array("sts" => mktime(17,0,0,4, 15,2008), "ets" => time(),
    "name" => "CDR - Mount Mercy", "removed" => False, "active" => True, "lat" => 42.0, "lon" => -91.65,
    "state" => "IA", "network" => "KCRG", "moviebase" => "cedarrapids-mm",
    "ip" => "192.251.94.203", "county" => "Linn", "port" => "80"),
"KCRG-012" => Array("sts" => mktime(12,0,0,5, 28,2009), "ets" => time(),
    "name" => "Cedar Falls/UNI", "removed" => False, "active" => True, "lat" => 42.5154, "lon" => -92.459,
    "state" => "IA", "network" => "KCRG", "moviebase" => "uni",
    "ip" => "134.161.128.74", "county" => "Blackhawk", "port" => "80"),
"IDOT-010-02" => Array("sts" => mktime(13,0,0,12, 20,2009), "ets" => time(),
    "name" => "Cedar Rapids Hwy 30 US 30 Bridge Deck", "removed" => False, "active" => True, "lat" => 41.93, "lon" => -91.68,
    "state" => "IA", "network" => "IDOT", "moviebase" => "None",
    "ip" => "None", "county" => "None", "port" => "None"),
"IDOT-010-00" => Array("sts" => mktime(13,0,0,12, 20,2009), "ets" => time(),
    "name" => "Cedar Rapids Hwy 31 US 30 East-West View", "removed" => False, "active" => True, "lat" => 41.93, "lon" => -91.68,
    "state" => "IA", "network" => "IDOT", "moviebase" => "None",
    "ip" => "None", "county" => "None", "port" => "None"),
"IDOT-010-03" => Array("sts" => mktime(13,0,0,12, 20,2009), "ets" => time(),
    "name" => "Cedar Rapids Hwy 32 US 30 EB", "removed" => False, "active" => True, "lat" => 41.93, "lon" => -91.68,
    "state" => "IA", "network" => "IDOT", "moviebase" => "None",
    "ip" => "None", "county" => "None", "port" => "None"),
"IDOT-010-01" => Array("sts" => mktime(13,0,0,12, 20,2009), "ets" => time(),
    "name" => "Cedar Rapids Hwy 33 US 30 WB", "removed" => False, "active" => True, "lat" => 41.93, "lon" => -91.68,
    "state" => "IA", "network" => "IDOT", "moviebase" => "None",
    "ip" => "None", "county" => "None", "port" => "None"),
"IDOT-009-02" => Array("sts" => mktime(13,0,0,12, 20,2009), "ets" => time(),
    "name" => "Cedar Rapids I-380 and SB I-380 Ramp", "removed" => False, "active" => True, "lat" => 41.98, "lon" => -91.67,
    "state" => "IA", "network" => "IDOT", "moviebase" => "None",
    "ip" => "None", "county" => "None", "port" => "None"),
"IDOT-009-03" => Array("sts" => mktime(13,0,0,12, 20,2009), "ets" => time(),
    "name" => "Cedar Rapids I-380 Bridge", "removed" => False, "active" => True, "lat" => 41.98, "lon" => -91.67,
    "state" => "IA", "network" => "IDOT", "moviebase" => "None",
    "ip" => "None", "county" => "None", "port" => "None"),
"IDOT-009-04" => Array("sts" => mktime(13,0,0,12, 20,2009), "ets" => time(),
    "name" => "Cedar Rapids I-380 NB Bridge", "removed" => False, "active" => True, "lat" => 41.98, "lon" => -91.67,
    "state" => "IA", "network" => "IDOT", "moviebase" => "None",
    "ip" => "None", "county" => "None", "port" => "None"),
"IDOT-009-01" => Array("sts" => mktime(13,0,0,12, 20,2009), "ets" => time(),
    "name" => "Cedar Rapids I-380 NB on Ramp", "removed" => False, "active" => True, "lat" => 41.98, "lon" => -91.67,
    "state" => "IA", "network" => "IDOT", "moviebase" => "None",
    "ip" => "None", "county" => "None", "port" => "None"),
"IDOT-009-00" => Array("sts" => mktime(13,0,0,12, 20,2009), "ets" => time(),
    "name" => "Cedar Rapids I-38 North-South Bound", "removed" => False, "active" => True, "lat" => 41.98, "lon" => -91.67,
    "state" => "IA", "network" => "IDOT", "moviebase" => "None",
    "ip" => "None", "county" => "None", "port" => "None"),
"IDOT-011-01" => Array("sts" => mktime(13,0,0,12, 20,2009), "ets" => time(),
    "name" => "Centerville Bridge Deck", "removed" => False, "active" => True, "lat" => 40.73, "lon" => -93.0,
    "state" => "IA", "network" => "IDOT", "moviebase" => "None",
    "ip" => "None", "county" => "None", "port" => "None"),
"IDOT-011-04" => Array("sts" => mktime(13,0,0,12, 20,2009), "ets" => time(),
    "name" => "Centerville East Sensor", "removed" => False, "active" => True, "lat" => 40.73, "lon" => -93.0,
    "state" => "IA", "network" => "IDOT", "moviebase" => "None",
    "ip" => "None", "county" => "None", "port" => "None"),
"IDOT-011-03" => Array("sts" => mktime(13,0,0,12, 20,2009), "ets" => time(),
    "name" => "Centerville East View", "removed" => False, "active" => True, "lat" => 40.73, "lon" => -93.0,
    "state" => "IA", "network" => "IDOT", "moviebase" => "None",
    "ip" => "None", "county" => "None", "port" => "None"),
"IDOT-011-00" => Array("sts" => mktime(13,0,0,12, 20,2009), "ets" => time(),
    "name" => "Centerville Near RPU", "removed" => False, "active" => True, "lat" => 40.73, "lon" => -93.0,
    "state" => "IA", "network" => "IDOT", "moviebase" => "None",
    "ip" => "None", "county" => "None", "port" => "None"),
"IDOT-011-05" => Array("sts" => mktime(13,0,0,12, 20,2009), "ets" => time(),
    "name" => "Centerville West Bridge Approach", "removed" => False, "active" => True, "lat" => 40.73, "lon" => -93.0,
    "state" => "IA", "network" => "IDOT", "moviebase" => "None",
    "ip" => "None", "county" => "None", "port" => "None"),
"IDOT-011-02" => Array("sts" => mktime(13,0,0,12, 20,2009), "ets" => time(),
    "name" => "Centerville West View", "removed" => False, "active" => True, "lat" => 40.73, "lon" => -93.0,
    "state" => "IA", "network" => "IDOT", "moviebase" => "None",
    "ip" => "None", "county" => "None", "port" => "None"),
"KCCI-022" => Array("sts" => mktime(14,0,0,6, 11,2006), "ets" => time(),
    "name" => "Chariton", "removed" => False, "active" => True, "lat" => 41.02, "lon" => -93.31,
    "state" => "IA", "network" => "KCCI", "moviebase" => "chariton",
    "ip" => "69.66.69.248", "county" => "Lucas", "port" => "80"),
"KCCI-023" => Array("sts" => mktime(13,0,0,6, 27,2006), "ets" => time(),
    "name" => "Clarion", "removed" => False, "active" => True, "lat" => 42.731441, "lon" => -93.734493,
    "state" => "IA", "network" => "KCCI", "moviebase" => "clarion",
    "ip" => "74.84.105.212", "county" => "Wright", "port" => "80"),
"IDOT-053-00" => Array("sts" => mktime(13,0,0,12, 20,2009), "ets" => time(),
    "name" => "Colfax I-80 EB", "removed" => False, "active" => True, "lat" => 41.6893, "lon" => -93.2648,
    "state" => "IA", "network" => "IDOT", "moviebase" => "None",
    "ip" => "None", "county" => "None", "port" => "None"),
"IDOT-053-01" => Array("sts" => mktime(13,0,0,12, 20,2009), "ets" => time(),
    "name" => "Colfax I-80 EB FP2000", "removed" => False, "active" => True, "lat" => 41.6893, "lon" => -93.2648,
    "state" => "IA", "network" => "IDOT", "moviebase" => "None",
    "ip" => "None", "county" => "None", "port" => "None"),
"IDOT-053-02" => Array("sts" => mktime(13,0,0,12, 20,2009), "ets" => time(),
    "name" => "Colfax I-80 WB", "removed" => False, "active" => True, "lat" => 41.6893, "lon" => -93.2648,
    "state" => "IA", "network" => "IDOT", "moviebase" => "None",
    "ip" => "None", "county" => "None", "port" => "None"),
"IDOT-012-00" => Array("sts" => mktime(13,0,0,12, 20,2009), "ets" => time(),
    "name" => "Council Bluffs I29 - I80", "removed" => False, "active" => True, "lat" => 41.23, "lon" => -95.86,
    "state" => "IA", "network" => "IDOT", "moviebase" => "None",
    "ip" => "None", "county" => "None", "port" => "None"),
"IDOT-012-01" => Array("sts" => mktime(13,0,0,12, 20,2009), "ets" => time(),
    "name" => "Council Bluffs I29 -I80 Bridge Deck", "removed" => False, "active" => True, "lat" => 41.23, "lon" => -95.86,
    "state" => "IA", "network" => "IDOT", "moviebase" => "None",
    "ip" => "None", "county" => "None", "port" => "None"),
"IDOT-012-02" => Array("sts" => mktime(13,0,0,12, 20,2009), "ets" => time(),
    "name" => "Council Bluffs I29 - I80 East View", "removed" => False, "active" => True, "lat" => 41.23, "lon" => -95.86,
    "state" => "IA", "network" => "IDOT", "moviebase" => "None",
    "ip" => "None", "county" => "None", "port" => "None"),
"IDOT-012-03" => Array("sts" => mktime(13,0,0,12, 20,2009), "ets" => time(),
    "name" => "Council Bluffs I29 - I80 West View", "removed" => False, "active" => True, "lat" => 41.23, "lon" => -95.86,
    "state" => "IA", "network" => "IDOT", "moviebase" => "None",
    "ip" => "None", "county" => "None", "port" => "None"),
"KCCI-004" => Array("sts" => mktime(0,0,0,9, 20,2003), "ets" => time(),
    "name" => "Creston", "removed" => False, "active" => True, "lat" => 41.07318, "lon" => -94.36958,
    "state" => "IA", "network" => "KCCI", "moviebase" => "creston",
    "ip" => "69.66.29.70", "county" => "Union", "port" => "80"),
"KCRG-013" => Array("sts" => mktime(15,0,0,5, 28,2009), "ets" => time(),
    "name" => "Decorah", "removed" => False, "active" => True, "lat" => 43.293, "lon" => -91.773,
    "state" => "IA", "network" => "KCRG", "moviebase" => "decorah",
    "ip" => "74.207.32.12", "county" => "Winneshiek", "port" => "80"),
"IDOT-015-02" => Array("sts" => mktime(13,0,0,12, 20,2009), "ets" => time(),
    "name" => "Decorah IA 9 Bridge", "removed" => False, "active" => True, "lat" => 43.24, "lon" => -91.69,
    "state" => "IA", "network" => "IDOT", "moviebase" => "None",
    "ip" => "None", "county" => "None", "port" => "None"),
"IDOT-015-01" => Array("sts" => mktime(13,0,0,12, 20,2009), "ets" => time(),
    "name" => "Decorah IA 9 EB", "removed" => False, "active" => True, "lat" => 43.24, "lon" => -91.69,
    "state" => "IA", "network" => "IDOT", "moviebase" => "None",
    "ip" => "None", "county" => "None", "port" => "None"),
"IDOT-015-00" => Array("sts" => mktime(13,0,0,12, 20,2009), "ets" => time(),
    "name" => "Decorah IA 9 Sensor", "removed" => False, "active" => True, "lat" => 43.24, "lon" => -91.69,
    "state" => "IA", "network" => "IDOT", "moviebase" => "None",
    "ip" => "None", "county" => "None", "port" => "None"),
"IDOT-015-03" => Array("sts" => mktime(13,0,0,12, 20,2009), "ets" => time(),
    "name" => "Decorah IA 9 WB", "removed" => False, "active" => True, "lat" => 43.24, "lon" => -91.69,
    "state" => "IA", "network" => "IDOT", "moviebase" => "None",
    "ip" => "None", "county" => "None", "port" => "None"),
"IDOT-060-01" => Array("sts" => mktime(13,0,0,12, 20,2009), "ets" => time(),
    "name" => "Denison Hwy 59 Bridge Deck", "removed" => False, "active" => True, "lat" => 41.9185, "lon" => -95.3439,
    "state" => "IA", "network" => "IDOT", "moviebase" => "None",
    "ip" => "None", "county" => "None", "port" => "None"),
"IDOT-060-00" => Array("sts" => mktime(13,0,0,12, 20,2009), "ets" => time(),
    "name" => "Denison Hwy 59 NB", "removed" => False, "active" => True, "lat" => 41.9185, "lon" => -95.3439,
    "state" => "IA", "network" => "IDOT", "moviebase" => "None",
    "ip" => "None", "county" => "None", "port" => "None"),
"IDOT-060-02" => Array("sts" => mktime(13,0,0,12, 20,2009), "ets" => time(),
    "name" => "Denison Hwy 59 SB", "removed" => False, "active" => True, "lat" => 41.9185, "lon" => -95.3439,
    "state" => "IA", "network" => "IDOT", "moviebase" => "None",
    "ip" => "None", "county" => "None", "port" => "None"),
"IDOT-016-00" => Array("sts" => mktime(13,0,0,12, 20,2009), "ets" => time(),
    "name" => "Des Moines Hwy 5 I-35", "removed" => False, "active" => True, "lat" => 41.53, "lon" => -93.77,
    "state" => "IA", "network" => "IDOT", "moviebase" => "None",
    "ip" => "None", "county" => "None", "port" => "None"),
"IDOT-019-03" => Array("sts" => mktime(13,0,0,12, 20,2009), "ets" => time(),
    "name" => "DeWitt ", "removed" => False, "active" => True, "lat" => 41.83, "lon" => -90.57,
    "state" => "IA", "network" => "IDOT", "moviebase" => "None",
    "ip" => "None", "county" => "None", "port" => "None"),
"IDOT-019-01" => Array("sts" => mktime(13,0,0,12, 20,2009), "ets" => time(),
    "name" => "DeWitt ", "removed" => False, "active" => True, "lat" => 41.83, "lon" => -90.57,
    "state" => "IA", "network" => "IDOT", "moviebase" => "None",
    "ip" => "None", "county" => "None", "port" => "None"),
"IDOT-019-00" => Array("sts" => mktime(13,0,0,12, 20,2009), "ets" => time(),
    "name" => "DeWitt ", "removed" => False, "active" => True, "lat" => 41.83, "lon" => -90.57,
    "state" => "IA", "network" => "IDOT", "moviebase" => "None",
    "ip" => "None", "county" => "None", "port" => "None"),
"IDOT-019-02" => Array("sts" => mktime(14,0,0,12, 20,2009), "ets" => time(),
    "name" => "DeWitt ", "removed" => False, "active" => True, "lat" => 41.83, "lon" => -90.57,
    "state" => "IA", "network" => "IDOT", "moviebase" => "None",
    "ip" => "None", "county" => "None", "port" => "None"),
"KCRG-005" => Array("sts" => mktime(15,0,0,5, 20,2008), "ets" => time(),
    "name" => "Dubuque", "removed" => False, "active" => True, "lat" => 42.4974, "lon" => -90.6568,
    "state" => "IA", "network" => "KCRG", "moviebase" => "dubuque",
    "ip" => "63.254.136.61", "county" => "Dubuque", "port" => "80"),
"IDOT-020-00" => Array("sts" => mktime(13,0,0,12, 20,2009), "ets" => time(),
    "name" => "Dubuque (US 20)", "removed" => False, "active" => True, "lat" => 42.48, "lon" => -90.73,
    "state" => "IA", "network" => "IDOT", "moviebase" => "None",
    "ip" => "None", "county" => "None", "port" => "None"),
"IDOT-020-01" => Array("sts" => mktime(13,0,0,12, 20,2009), "ets" => time(),
    "name" => "Dubuque US20 East Br Deck ", "removed" => False, "active" => True, "lat" => 42.48, "lon" => -90.73,
    "state" => "IA", "network" => "IDOT", "moviebase" => "None",
    "ip" => "None", "county" => "None", "port" => "None"),
"IDOT-020-02" => Array("sts" => mktime(13,0,0,12, 20,2009), "ets" => time(),
    "name" => "Dubuque US20 East I-Section ", "removed" => False, "active" => True, "lat" => 42.48, "lon" => -90.73,
    "state" => "IA", "network" => "IDOT", "moviebase" => "None",
    "ip" => "None", "county" => "None", "port" => "None"),
"IDOT-020-03" => Array("sts" => mktime(13,0,0,12, 20,2009), "ets" => time(),
    "name" => "Dubuque US20 NB ", "removed" => False, "active" => True, "lat" => 42.48, "lon" => -90.73,
    "state" => "IA", "network" => "IDOT", "moviebase" => "None",
    "ip" => "None", "county" => "None", "port" => "None"),
"IDOT-020-04" => Array("sts" => mktime(13,0,0,12, 20,2009), "ets" => time(),
    "name" => "Dubuque US20 West ", "removed" => False, "active" => True, "lat" => 42.48, "lon" => -90.73,
    "state" => "IA", "network" => "IDOT", "moviebase" => "None",
    "ip" => "None", "county" => "None", "port" => "None"),
"IDOT-056-02" => Array("sts" => mktime(13,0,0,12, 20,2009), "ets" => time(),
    "name" => "Eddyville Bridge Deck", "removed" => False, "active" => True, "lat" => 41.1465, "lon" => -92.6436,
    "state" => "IA", "network" => "IDOT", "moviebase" => "None",
    "ip" => "None", "county" => "None", "port" => "None"),
"IDOT-056-03" => Array("sts" => mktime(13,0,0,12, 20,2009), "ets" => time(),
    "name" => "Eddyville North View", "removed" => False, "active" => True, "lat" => 41.1465, "lon" => -92.6436,
    "state" => "IA", "network" => "IDOT", "moviebase" => "None",
    "ip" => "None", "county" => "None", "port" => "None"),
"IDOT-056-01" => Array("sts" => mktime(13,0,0,12, 20,2009), "ets" => time(),
    "name" => "Eddyville Roadway", "removed" => False, "active" => True, "lat" => 41.1465, "lon" => -92.6436,
    "state" => "IA", "network" => "IDOT", "moviebase" => "None",
    "ip" => "None", "county" => "None", "port" => "None"),
"IDOT-056-00" => Array("sts" => mktime(13,0,0,12, 20,2009), "ets" => time(),
    "name" => "Eddyville South View", "removed" => False, "active" => True, "lat" => 41.1465, "lon" => -92.6436,
    "state" => "IA", "network" => "IDOT", "moviebase" => "None",
    "ip" => "None", "county" => "None", "port" => "None"),
"KCCI-035" => Array("sts" => mktime(18,0,0,9, 11,2009), "ets" => time(),
    "name" => "Fort Dodge", "removed" => False, "active" => True, "lat" => 42.4922, "lon" => -94.192,
    "state" => "IA", "network" => "KCCI", "moviebase" => "fortdodge",
    "ip" => "74.42.84.218", "county" => "Webster", "port" => "80"),
"KCCI-021" => Array("sts" => mktime(0,0,0,1, 19,2006), "ets" => time(),
    "name" => "Glidden", "removed" => False, "active" => True, "lat" => 42.06497, "lon" => -94.733133,
    "state" => "IA", "network" => "KCCI", "moviebase" => "glidden",
    "ip" => "67.54.186.247", "county" => "Carroll", "port" => "81"),
"KCCI-025" => Array("sts" => mktime(15,0,0,7, 14,2006), "ets" => time(),
    "name" => "Greenfield", "removed" => False, "active" => True, "lat" => 41.304473, "lon" => -94.461372,
    "state" => "IA", "network" => "KCCI", "moviebase" => "greenfield",
    "ip" => "71.7.68.200", "county" => "Adair", "port" => "80"),
"KCCI-008" => Array("sts" => mktime(0,0,0,12, 4,2003), "ets" => time(),
    "name" => "Humboldt", "removed" => False, "active" => True, "lat" => 42.72, "lon" => -94.23,
    "state" => "IA", "network" => "KCCI", "moviebase" => "humboldt",
    "ip" => "208.90.15.91", "county" => "Humboldt", "port" => "80"),
"KELO-003" => Array("sts" => mktime(16,0,0,12, 10,2007), "ets" => time(),
    "name" => "Huron", "removed" => False, "active" => True, "lat" => 44.383, "lon" => -98.217,
    "state" => "SD", "network" => "KELO", "moviebase" => "huron",
    "ip" => "67.128.226.21", "county" => "Beadle", "port" => "80"),
"IDOT-051-01" => Array("sts" => mktime(13,0,0,12, 20,2009), "ets" => time(),
    "name" => "Ida Grove ", "removed" => False, "active" => True, "lat" => 42.3515, "lon" => -95.4783,
    "state" => "IA", "network" => "IDOT", "moviebase" => "None",
    "ip" => "None", "county" => "None", "port" => "None"),
"IDOT-051-03" => Array("sts" => mktime(13,0,0,12, 20,2009), "ets" => time(),
    "name" => "Ida Grove ", "removed" => False, "active" => True, "lat" => 42.3515, "lon" => -95.4783,
    "state" => "IA", "network" => "IDOT", "moviebase" => "None",
    "ip" => "None", "county" => "None", "port" => "None"),
"IDOT-051-02" => Array("sts" => mktime(13,0,0,12, 20,2009), "ets" => time(),
    "name" => "Ida Grove ", "removed" => False, "active" => True, "lat" => 42.3515, "lon" => -95.4783,
    "state" => "IA", "network" => "IDOT", "moviebase" => "None",
    "ip" => "None", "county" => "None", "port" => "None"),
"IDOT-051-00" => Array("sts" => mktime(13,0,0,12, 20,2009), "ets" => time(),
    "name" => "Ida Grove ", "removed" => False, "active" => True, "lat" => 42.3515, "lon" => -95.4783,
    "state" => "IA", "network" => "IDOT", "moviebase" => "None",
    "ip" => "None", "county" => "None", "port" => "None"),
"KCRG-007" => Array("sts" => mktime(14,0,0,8, 19,2008), "ets" => time(),
    "name" => "Independence", "removed" => False, "active" => True, "lat" => 42.45, "lon" => -91.95,
    "state" => "IA", "network" => "KCRG", "moviebase" => "independence",
    "ip" => "208.81.193.21", "county" => "Buchanan", "port" => "80"),
"KCCI-009" => Array("sts" => mktime(0,0,0,2, 25,2004), "ets" => time(),
    "name" => "Indianola", "removed" => False, "active" => True, "lat" => 41.37, "lon" => -93.55,
    "state" => "IA", "network" => "KCCI", "moviebase" => "indy",
    "ip" => "198.206.243.122", "county" => "Warren", "port" => "80"),
"KCRG-006" => Array("sts" => mktime(12,0,0,8, 6,2008), "ets" => time(),
    "name" => "Iowa City", "removed" => False, "active" => True, "lat" => 41.63, "lon" => -91.55,
    "state" => "IA", "network" => "KCRG", "moviebase" => "iowacity",
    "ip" => "216.243.209.72", "county" => "Johnson", "port" => "80"),
"KCCI-002" => Array("sts" => mktime(0,0,0,8, 5,2003), "ets" => mktime(0,0,0,8, 21,2003),
    "name" => "Iowa State Fair 03", "removed" => True, "active" => False, "lat" => 41.20539, "lon" => -92.885,
    "state" => "IA", "network" => "KCCI", "moviebase" => "iowa state fair 03",
    "ip" => "209.56.232.244", "county" => "", "port" => "80"),
"KCCI-027" => Array("sts" => mktime(16,0,0,10, 23,2006), "ets" => time(),
    "name" => "ISU Ag Farm", "removed" => False, "active" => True, "lat" => 42.02098, "lon" => -93.7736,
    "state" => "IA", "network" => "KCCI", "moviebase" => "iemwest",
    "ip" => "69.5.129.46", "county" => "Boone", "port" => "80"),
"KCCI-016" => Array("sts" => mktime(16,0,0,4, 14,2005), "ets" => time(),
    "name" => "ISU Ames", "removed" => False, "active" => True, "lat" => 42.028627, "lon" => -93.643367,
    "state" => "IA", "network" => "KCCI", "moviebase" => "ames",
    "ip" => "129.186.185.31", "county" => "Story", "port" => "80"),
"KCCI-001" => Array("sts" => mktime(0,0,0,7, 23,2003), "ets" => time(),
    "name" => "Jefferson", "removed" => False, "active" => True, "lat" => 42.015504, "lon" => -94.378223,
    "state" => "IA", "network" => "KCCI", "moviebase" => "jeff",
    "ip" => "216.248.72.225", "county" => "Greene", "port" => "80"),
"IDOT-025-02" => Array("sts" => mktime(13,0,0,12, 20,2009), "ets" => time(),
    "name" => "Jefferson IA 4 Bridge", "removed" => False, "active" => True, "lat" => 42.05, "lon" => -94.38,
    "state" => "IA", "network" => "IDOT", "moviebase" => "None",
    "ip" => "None", "county" => "None", "port" => "None"),
"IDOT-025-01" => Array("sts" => mktime(13,0,0,12, 20,2009), "ets" => time(),
    "name" => "Jefferson IA 4 NB Approach", "removed" => False, "active" => True, "lat" => 42.05, "lon" => -94.38,
    "state" => "IA", "network" => "IDOT", "moviebase" => "None",
    "ip" => "None", "county" => "None", "port" => "None"),
"IDOT-025-00" => Array("sts" => mktime(13,0,0,12, 20,2009), "ets" => time(),
    "name" => "Jefferson IA 4 SB Approach", "removed" => False, "active" => True, "lat" => 42.05, "lon" => -94.38,
    "state" => "IA", "network" => "IDOT", "moviebase" => "None",
    "ip" => "None", "county" => "None", "port" => "None"),
"IDOT-025-03" => Array("sts" => mktime(13,0,0,12, 20,2009), "ets" => time(),
    "name" => "Jefferson North View", "removed" => False, "active" => True, "lat" => 42.05, "lon" => -94.38,
    "state" => "IA", "network" => "IDOT", "moviebase" => "None",
    "ip" => "None", "county" => "None", "port" => "None"),
"IDOT-025-04" => Array("sts" => mktime(13,0,0,12, 20,2009), "ets" => time(),
    "name" => "Jefferson South View", "removed" => False, "active" => True, "lat" => 42.05, "lon" => -94.38,
    "state" => "IA", "network" => "IDOT", "moviebase" => "None",
    "ip" => "None", "county" => "None", "port" => "None"),
"KCCI-020" => Array("sts" => mktime(17,0,0,9, 26,2005), "ets" => time(),
    "name" => "Knoxville", "removed" => False, "active" => True, "lat" => 41.32, "lon" => -93.12,
    "state" => "IA", "network" => "KCCI", "moviebase" => "knoxville",
    "ip" => "71.7.55.158", "county" => "Marion", "port" => "80"),
"KCCI-015" => Array("sts" => mktime(23,0,0,6, 18,2004), "ets" => time(),
    "name" => "Lake Rathbun", "removed" => False, "active" => True, "lat" => 40.73, "lon" => -92.87,
    "state" => "IA", "network" => "KCCI", "moviebase" => "rathbun",
    "ip" => "69.66.225.18", "county" => "Appanoose", "port" => "80"),
"KCCI-028" => Array("sts" => mktime(18,0,0,1, 24,2007), "ets" => time(),
    "name" => "Lamoni", "removed" => False, "active" => True, "lat" => 40.622291, "lon" => -93.932633,
    "state" => "IA", "network" => "KCCI", "moviebase" => "lamoni",
    "ip" => "216.139.122.154", "county" => "Decatur", "port" => "80"),
"IDOT-026-01" => Array("sts" => mktime(13,0,0,12, 20,2009), "ets" => time(),
    "name" => "Leon I 35 NB", "removed" => False, "active" => True, "lat" => 40.73, "lon" => -93.84,
    "state" => "IA", "network" => "IDOT", "moviebase" => "None",
    "ip" => "None", "county" => "None", "port" => "None"),
"IDOT-026-02" => Array("sts" => mktime(13,0,0,12, 20,2009), "ets" => time(),
    "name" => "Leon I 35 SB", "removed" => False, "active" => True, "lat" => 40.73, "lon" => -93.84,
    "state" => "IA", "network" => "IDOT", "moviebase" => "None",
    "ip" => "None", "county" => "None", "port" => "None"),
"IDOT-026-03" => Array("sts" => mktime(13,0,0,12, 20,2009), "ets" => time(),
    "name" => "Leon IA 2 Bridge Deck", "removed" => False, "active" => True, "lat" => 40.73, "lon" => -93.84,
    "state" => "IA", "network" => "IDOT", "moviebase" => "None",
    "ip" => "None", "county" => "None", "port" => "None"),
"IDOT-026-00" => Array("sts" => mktime(13,0,0,12, 20,2009), "ets" => time(),
    "name" => "Leon IA 2 East View", "removed" => False, "active" => True, "lat" => 40.73, "lon" => -93.84,
    "state" => "IA", "network" => "IDOT", "moviebase" => "None",
    "ip" => "None", "county" => "None", "port" => "None"),
"IDOT-026-04" => Array("sts" => mktime(13,0,0,12, 20,2009), "ets" => time(),
    "name" => "Leon West view", "removed" => False, "active" => True, "lat" => 40.73, "lon" => -93.84,
    "state" => "IA", "network" => "IDOT", "moviebase" => "None",
    "ip" => "None", "county" => "None", "port" => "None"),
"KCCI-019" => Array("sts" => mktime(0,0,0,9, 16,2005), "ets" => time(),
    "name" => "Madrid", "removed" => False, "active" => True, "lat" => 41.87869, "lon" => -93.828918,
    "state" => "IA", "network" => "KCCI", "moviebase" => "madrid",
    "ip" => "69.66.30.247", "county" => "Boone", "port" => "80"),
"IDOT-027-00" => Array("sts" => mktime(10,0,0,12, 21,2009), "ets" => time(),
    "name" => "Manchester East View", "removed" => False, "active" => True, "lat" => 42.471, "lon" => -91.4473,
    "state" => "IA", "network" => "IDOT", "moviebase" => "None",
    "ip" => "None", "county" => "None", "port" => "None"),
"IDOT-027-01" => Array("sts" => mktime(10,0,0,12, 21,2009), "ets" => time(),
    "name" => "Manchester East View 2", "removed" => False, "active" => True, "lat" => 42.471, "lon" => -91.4473,
    "state" => "IA", "network" => "IDOT", "moviebase" => "None",
    "ip" => "None", "county" => "None", "port" => "None"),
"IDOT-027-02" => Array("sts" => mktime(10,0,0,12, 21,2009), "ets" => time(),
    "name" => "Manchester US 20", "removed" => False, "active" => True, "lat" => 42.471, "lon" => -91.4473,
    "state" => "IA", "network" => "IDOT", "moviebase" => "None",
    "ip" => "None", "county" => "None", "port" => "None"),
"IDOT-027-03" => Array("sts" => mktime(10,0,0,12, 21,2009), "ets" => time(),
    "name" => "Manchester US 20 Bridge", "removed" => False, "active" => True, "lat" => 42.471, "lon" => -91.4473,
    "state" => "IA", "network" => "IDOT", "moviebase" => "None",
    "ip" => "None", "county" => "None", "port" => "None"),
"IDOT-027-04" => Array("sts" => mktime(10,0,0,12, 21,2009), "ets" => time(),
    "name" => "Manchester West View", "removed" => False, "active" => True, "lat" => 42.471, "lon" => -91.4473,
    "state" => "IA", "network" => "IDOT", "moviebase" => "None",
    "ip" => "None", "county" => "None", "port" => "None"),
"IDOT-028-01" => Array("sts" => mktime(13,0,0,12, 20,2009), "ets" => time(),
    "name" => "Maquoketa Positon 1", "removed" => False, "active" => True, "lat" => 42.07, "lon" => -90.68,
    "state" => "IA", "network" => "IDOT", "moviebase" => "None",
    "ip" => "None", "county" => "None", "port" => "None"),
"IDOT-028-02" => Array("sts" => mktime(13,0,0,12, 20,2009), "ets" => time(),
    "name" => "Maquoketa Positon 2", "removed" => False, "active" => True, "lat" => 42.07, "lon" => -90.68,
    "state" => "IA", "network" => "IDOT", "moviebase" => "None",
    "ip" => "None", "county" => "None", "port" => "None"),
"IDOT-028-03" => Array("sts" => mktime(13,0,0,12, 20,2009), "ets" => time(),
    "name" => "Maquoketa Positon 3", "removed" => False, "active" => True, "lat" => 42.07, "lon" => -90.68,
    "state" => "IA", "network" => "IDOT", "moviebase" => "None",
    "ip" => "None", "county" => "None", "port" => "None"),
"IDOT-028-04" => Array("sts" => mktime(13,0,0,12, 20,2009), "ets" => time(),
    "name" => "Maquoketa Positon 4", "removed" => False, "active" => True, "lat" => 42.07, "lon" => -90.68,
    "state" => "IA", "network" => "IDOT", "moviebase" => "None",
    "ip" => "None", "county" => "None", "port" => "None"),
"IDOT-028-00" => Array("sts" => mktime(13,0,0,12, 20,2009), "ets" => time(),
    "name" => "Maquoketa (US 61/IA 64)", "removed" => False, "active" => True, "lat" => 42.07, "lon" => -90.68,
    "state" => "IA", "network" => "IDOT", "moviebase" => "None",
    "ip" => "None", "county" => "None", "port" => "None"),
"KCRG-014" => Array("sts" => mktime(14,0,0,6, 10,2009), "ets" => time(),
    "name" => "Marion Field Cam", "removed" => False, "active" => True, "lat" => 42.05, "lon" => -91.55,
    "state" => "IA", "network" => "KCRG", "moviebase" => "marion field cam",
    "ip" => "74.84.90.135", "county" => "Linn", "port" => "80"),
"KCCI-005" => Array("sts" => mktime(0,0,0,10, 1,2003), "ets" => mktime(14,0,0,10, 26,2004),
    "name" => "Marshalltown", "removed" => True, "active" => False, "lat" => 41.20539, "lon" => -92.885,
    "state" => "IA", "network" => "KCCI", "moviebase" => "marshalltown",
    "ip" => "209.56.232.244", "county" => "Marshall", "port" => "80"),
"IDOT-030-02" => Array("sts" => mktime(14,0,0,12, 20,2009), "ets" => time(),
    "name" => "Mason City I-35", "removed" => False, "active" => True, "lat" => 43.03, "lon" => -93.34,
    "state" => "IA", "network" => "IDOT", "moviebase" => "None",
    "ip" => "None", "county" => "None", "port" => "None"),
"IDOT-030-01" => Array("sts" => mktime(13,0,0,12, 20,2009), "ets" => time(),
    "name" => "Mason City I-35 Deck", "removed" => False, "active" => True, "lat" => 43.03, "lon" => -93.34,
    "state" => "IA", "network" => "IDOT", "moviebase" => "None",
    "ip" => "None", "county" => "None", "port" => "None"),
"IDOT-030-00" => Array("sts" => mktime(13,0,0,12, 20,2009), "ets" => time(),
    "name" => "Mason City I-35 NB", "removed" => False, "active" => True, "lat" => 43.03, "lon" => -93.34,
    "state" => "IA", "network" => "IDOT", "moviebase" => "None",
    "ip" => "None", "county" => "None", "port" => "None"),
"IDOT-030-03" => Array("sts" => mktime(13,0,0,12, 20,2009), "ets" => time(),
    "name" => "Mason City I-35 SB", "removed" => False, "active" => True, "lat" => 43.03, "lon" => -93.34,
    "state" => "IA", "network" => "IDOT", "moviebase" => "None",
    "ip" => "None", "county" => "None", "port" => "None"),
"KELO-002" => Array("sts" => mktime(11,0,0,10, 3,2007), "ets" => time(),
    "name" => "Mitchell", "removed" => False, "active" => True, "lat" => 43.6981, "lon" => -98.0317,
    "state" => "SD", "network" => "KELO", "moviebase" => "mitchell",
    "ip" => "66.115.209.25", "county" => "Davison", "port" => "80"),
"KCRG-002" => Array("sts" => mktime(14,0,0,4, 16,2008), "ets" => time(),
    "name" => "Monticello", "removed" => False, "active" => True, "lat" => 42.23, "lon" => -91.17,
    "state" => "IA", "network" => "KCRG", "moviebase" => "monticello",
    "ip" => "63.230.156.182", "county" => "Jones", "port" => "80"),
"IDOT-032-03" => Array("sts" => mktime(13,0,0,12, 20,2009), "ets" => time(),
    "name" => "Mount Pleasant US218", "removed" => False, "active" => True, "lat" => 40.89, "lon" => -91.55,
    "state" => "IA", "network" => "IDOT", "moviebase" => "None",
    "ip" => "None", "county" => "None", "port" => "None"),
"IDOT-032-00" => Array("sts" => mktime(14,0,0,12, 20,2009), "ets" => time(),
    "name" => "Mount Pleasant (US 218)", "removed" => False, "active" => True, "lat" => 40.89, "lon" => -91.55,
    "state" => "IA", "network" => "IDOT", "moviebase" => "None",
    "ip" => "None", "county" => "None", "port" => "None"),
"IDOT-032-02" => Array("sts" => mktime(13,0,0,12, 20,2009), "ets" => time(),
    "name" => "Mount Pleasant US218 Bridge", "removed" => False, "active" => True, "lat" => 40.89, "lon" => -91.55,
    "state" => "IA", "network" => "IDOT", "moviebase" => "None",
    "ip" => "None", "county" => "None", "port" => "None"),
"IDOT-032-01" => Array("sts" => mktime(13,0,0,12, 20,2009), "ets" => time(),
    "name" => "Mount Pleasant US218 NB", "removed" => False, "active" => True, "lat" => 40.89, "lon" => -91.55,
    "state" => "IA", "network" => "IDOT", "moviebase" => "None",
    "ip" => "None", "county" => "None", "port" => "None"),
"KCCI-026" => Array("sts" => mktime(18,0,0,7, 22,2006), "ets" => time(),
    "name" => "Nevada", "removed" => False, "active" => True, "lat" => 42.015185, "lon" => -93.448934,
    "state" => "IA", "network" => "KCCI", "moviebase" => "nevada",
    "ip" => "69.66.56.19", "county" => "Story", "port" => "80"),
"IDOT-033-00" => Array("sts" => mktime(13,0,0,12, 20,2009), "ets" => time(),
    "name" => "New Hampton US 18 ", "removed" => False, "active" => True, "lat" => 43.07, "lon" => -92.46,
    "state" => "IA", "network" => "IDOT", "moviebase" => "None",
    "ip" => "None", "county" => "None", "port" => "None"),
"IDOT-033-01" => Array("sts" => mktime(13,0,0,12, 20,2009), "ets" => time(),
    "name" => "New Hampton US 18 Bridge Deck", "removed" => False, "active" => True, "lat" => 43.07, "lon" => -92.46,
    "state" => "IA", "network" => "IDOT", "moviebase" => "None",
    "ip" => "None", "county" => "None", "port" => "None"),
"IDOT-033-02" => Array("sts" => mktime(13,0,0,12, 20,2009), "ets" => time(),
    "name" => "New Hampton US 18 East", "removed" => False, "active" => True, "lat" => 43.07, "lon" => -92.46,
    "state" => "IA", "network" => "IDOT", "moviebase" => "None",
    "ip" => "None", "county" => "None", "port" => "None"),
"IDOT-033-03" => Array("sts" => mktime(13,0,0,12, 20,2009), "ets" => time(),
    "name" => "New Hampton US 18 West", "removed" => False, "active" => True, "lat" => 43.07, "lon" => -92.46,
    "state" => "IA", "network" => "IDOT", "moviebase" => "None",
    "ip" => "None", "county" => "None", "port" => "None"),
"KCCI-011" => Array("sts" => mktime(19,0,0,4, 16,2004), "ets" => time(),
    "name" => "Newton", "removed" => False, "active" => True, "lat" => 41.6778, "lon" => -93.0145,
    "state" => "IA", "network" => "KCCI", "moviebase" => "newton",
    "ip" => "69.66.104.40", "county" => "Jasper", "port" => "80"),
"KCRG-015" => Array("sts" => mktime(9,0,0,10, 19,2009), "ets" => time(),
    "name" => "Olin", "removed" => False, "active" => True, "lat" => 41.998, "lon" => -91.142,
    "state" => "IA", "network" => "KCRG", "moviebase" => "olin",
    "ip" => "207.177.36.11", "county" => "Jones", "port" => "1999"),
"IDOT-034-01" => Array("sts" => mktime(13,0,0,12, 21,2009), "ets" => time(),
    "name" => "Onawa (I-29)", "removed" => False, "active" => True, "lat" => 41.86, "lon" => -96.01,
    "state" => "IA", "network" => "IDOT", "moviebase" => "None",
    "ip" => "None", "county" => "None", "port" => "None"),
"IDOT-034-00" => Array("sts" => mktime(14,0,0,12, 21,2009), "ets" => time(),
    "name" => "Onawa (I-29)", "removed" => False, "active" => True, "lat" => 41.86, "lon" => -96.01,
    "state" => "IA", "network" => "IDOT", "moviebase" => "None",
    "ip" => "None", "county" => "None", "port" => "None"),
"IDOT-034-03" => Array("sts" => mktime(14,0,0,12, 21,2009), "ets" => time(),
    "name" => "Onawa (I-29)", "removed" => False, "active" => True, "lat" => 41.86, "lon" => -96.01,
    "state" => "IA", "network" => "IDOT", "moviebase" => "None",
    "ip" => "None", "county" => "None", "port" => "None"),
"IDOT-034-02" => Array("sts" => mktime(13,0,0,12, 21,2009), "ets" => time(),
    "name" => "Onawa (I-29)", "removed" => False, "active" => True, "lat" => 41.86, "lon" => -96.01,
    "state" => "IA", "network" => "IDOT", "moviebase" => "None",
    "ip" => "None", "county" => "None", "port" => "None"),
"KCCI-031" => Array("sts" => mktime(9,0,0,11, 9,2007), "ets" => time(),
    "name" => "Osceola", "removed" => False, "active" => True, "lat" => 41.0313, "lon" => -93.7277,
    "state" => "IA", "network" => "KCCI", "moviebase" => "osceola",
    "ip" => "69.66.201.159", "county" => "Clarke", "port" => "80"),
"IDOT-036-00" => Array("sts" => mktime(13,0,0,12, 20,2009), "ets" => time(),
    "name" => "Ottumwa Bridge Deck", "removed" => False, "active" => True, "lat" => 41.02, "lon" => -92.42,
    "state" => "IA", "network" => "IDOT", "moviebase" => "None",
    "ip" => "None", "county" => "None", "port" => "None"),
"IDOT-036-01" => Array("sts" => mktime(13,0,0,12, 20,2009), "ets" => time(),
    "name" => "Ottumwa North View", "removed" => False, "active" => True, "lat" => 41.02, "lon" => -92.42,
    "state" => "IA", "network" => "IDOT", "moviebase" => "None",
    "ip" => "None", "county" => "None", "port" => "None"),
"IDOT-036-02" => Array("sts" => mktime(13,0,0,12, 20,2009), "ets" => time(),
    "name" => "Ottumwa Rt 34 Intersection", "removed" => False, "active" => True, "lat" => 41.02, "lon" => -92.42,
    "state" => "IA", "network" => "IDOT", "moviebase" => "None",
    "ip" => "None", "county" => "None", "port" => "None"),
"IDOT-036-03" => Array("sts" => mktime(13,0,0,12, 20,2009), "ets" => time(),
    "name" => "Ottumwa South View", "removed" => False, "active" => True, "lat" => 41.02, "lon" => -92.42,
    "state" => "IA", "network" => "IDOT", "moviebase" => "None",
    "ip" => "None", "county" => "None", "port" => "None"),
"KCCI-014" => Array("sts" => mktime(22,0,0,5, 19,2004), "ets" => time(),
    "name" => "Panora", "removed" => False, "active" => True, "lat" => 41.70486, "lon" => -94.3686,
    "state" => "IA", "network" => "KCCI", "moviebase" => "panora",
    "ip" => "66.43.253.165", "county" => "Guthrie", "port" => "80"),
"KCRG-011" => Array("sts" => mktime(13,0,0,5, 21,2009), "ets" => time(),
    "name" => "Parkersburg", "removed" => False, "active" => True, "lat" => 42.579266, "lon" => -92.788978,
    "state" => "IA", "network" => "KCRG", "moviebase" => "parkersburg",
    "ip" => "74.84.124.174", "county" => "Butler", "port" => "80"),
"KCCI-006" => Array("sts" => mktime(0,0,0,10, 16,2003), "ets" => time(),
    "name" => "Pella", "removed" => False, "active" => True, "lat" => 41.41, "lon" => -92.9,
    "state" => "IA", "network" => "KCCI", "moviebase" => "pella",
    "ip" => "69.66.44.147", "county" => "Marion", "port" => "80"),
"IDOT-037-02" => Array("sts" => mktime(13,0,0,12, 20,2009), "ets" => time(),
    "name" => "Pella East View", "removed" => False, "active" => True, "lat" => 41.38, "lon" => -92.87,
    "state" => "IA", "network" => "IDOT", "moviebase" => "None",
    "ip" => "None", "county" => "None", "port" => "None"),
"IDOT-037-00" => Array("sts" => mktime(13,0,0,12, 20,2009), "ets" => time(),
    "name" => "Pella IA 163 WB", "removed" => False, "active" => True, "lat" => 41.38, "lon" => -92.87,
    "state" => "IA", "network" => "IDOT", "moviebase" => "None",
    "ip" => "None", "county" => "None", "port" => "None"),
"IDOT-037-03" => Array("sts" => mktime(13,0,0,12, 20,2009), "ets" => time(),
    "name" => "Pella WB Bridge Deck", "removed" => False, "active" => True, "lat" => 41.38, "lon" => -92.87,
    "state" => "IA", "network" => "IDOT", "moviebase" => "None",
    "ip" => "None", "county" => "None", "port" => "None"),
"IDOT-058-06" => Array("sts" => mktime(13,0,0,12, 20,2009), "ets" => time(),
    "name" => "Plainfield", "removed" => False, "active" => True, "lat" => 42.8332, "lon" => -92.5371,
    "state" => "IA", "network" => "IDOT", "moviebase" => "None",
    "ip" => "None", "county" => "None", "port" => "None"),
"IDOT-058-05" => Array("sts" => mktime(13,0,0,12, 20,2009), "ets" => time(),
    "name" => "Plainfield", "removed" => False, "active" => True, "lat" => 42.8332, "lon" => -92.5371,
    "state" => "IA", "network" => "IDOT", "moviebase" => "None",
    "ip" => "None", "county" => "None", "port" => "None"),
"IDOT-058-00" => Array("sts" => mktime(13,0,0,12, 20,2009), "ets" => time(),
    "name" => "Plainfield US 218 NB", "removed" => False, "active" => True, "lat" => 42.8332, "lon" => -92.5371,
    "state" => "IA", "network" => "IDOT", "moviebase" => "None",
    "ip" => "None", "county" => "None", "port" => "None"),
"IDOT-058-02" => Array("sts" => mktime(13,0,0,12, 20,2009), "ets" => time(),
    "name" => "Plainfield US 218 NB Deck", "removed" => False, "active" => True, "lat" => 42.8332, "lon" => -92.5371,
    "state" => "IA", "network" => "IDOT", "moviebase" => "None",
    "ip" => "None", "county" => "None", "port" => "None"),
"IDOT-058-03" => Array("sts" => mktime(13,0,0,12, 20,2009), "ets" => time(),
    "name" => "Plainfield US 218 SB ", "removed" => False, "active" => True, "lat" => 42.8332, "lon" => -92.5371,
    "state" => "IA", "network" => "IDOT", "moviebase" => "None",
    "ip" => "None", "county" => "None", "port" => "None"),
"IDOT-058-01" => Array("sts" => mktime(13,0,0,12, 20,2009), "ets" => time(),
    "name" => "Plainfield US 218 SB Deck", "removed" => False, "active" => True, "lat" => 42.8332, "lon" => -92.5371,
    "state" => "IA", "network" => "IDOT", "moviebase" => "None",
    "ip" => "None", "county" => "None", "port" => "None"),
"IDOT-038-03" => Array("sts" => mktime(13,0,0,12, 20,2009), "ets" => time(),
    "name" => "Red Oak East View", "removed" => False, "active" => True, "lat" => 40.98, "lon" => -94.98,
    "state" => "IA", "network" => "IDOT", "moviebase" => "None",
    "ip" => "None", "county" => "None", "port" => "None"),
"IDOT-038-00" => Array("sts" => mktime(13,0,0,12, 20,2009), "ets" => time(),
    "name" => "Red Oak Hwy 71 Bridge", "removed" => False, "active" => True, "lat" => 40.98, "lon" => -94.98,
    "state" => "IA", "network" => "IDOT", "moviebase" => "None",
    "ip" => "None", "county" => "None", "port" => "None"),
"IDOT-038-05" => Array("sts" => mktime(13,0,0,12, 20,2009), "ets" => time(),
    "name" => "Red Oak Hwy 71 Bridge Departure", "removed" => False, "active" => True, "lat" => 40.98, "lon" => -94.98,
    "state" => "IA", "network" => "IDOT", "moviebase" => "None",
    "ip" => "None", "county" => "None", "port" => "None"),
"IDOT-038-04" => Array("sts" => mktime(13,0,0,12, 20,2009), "ets" => time(),
    "name" => "Red Oak Off-Ramp Intersection", "removed" => False, "active" => True, "lat" => 40.98, "lon" => -94.98,
    "state" => "IA", "network" => "IDOT", "moviebase" => "None",
    "ip" => "None", "county" => "None", "port" => "None"),
"IDOT-038-01" => Array("sts" => mktime(13,0,0,12, 20,2009), "ets" => time(),
    "name" => "Red Oak South Ramp", "removed" => False, "active" => True, "lat" => 40.98, "lon" => -94.98,
    "state" => "IA", "network" => "IDOT", "moviebase" => "None",
    "ip" => "None", "county" => "None", "port" => "None"),
"IDOT-038-02" => Array("sts" => mktime(13,0,0,12, 20,2009), "ets" => time(),
    "name" => "Red Oak South View", "removed" => False, "active" => True, "lat" => 40.98, "lon" => -94.98,
    "state" => "IA", "network" => "IDOT", "moviebase" => "None",
    "ip" => "None", "county" => "None", "port" => "None"),
"IDOT-038-06" => Array("sts" => mktime(13,0,0,12, 20,2009), "ets" => time(),
    "name" => "Red Oak West View", "removed" => False, "active" => True, "lat" => 40.98, "lon" => -94.98,
    "state" => "IA", "network" => "IDOT", "moviebase" => "None",
    "ip" => "None", "county" => "None", "port" => "None"),
"KCCI-010" => Array("sts" => mktime(0,0,0,2, 25,2004), "ets" => time(),
    "name" => "Rockwell City", "removed" => False, "active" => True, "lat" => 42.3922, "lon" => -94.6439,
    "state" => "IA", "network" => "KCCI", "moviebase" => "rock",
    "ip" => "69.66.29.140", "county" => "Calhoun", "port" => "80"),
"KCCI-018" => Array("sts" => mktime(11,0,0,7, 2,2005), "ets" => time(),
    "name" => "Saylorville Lake", "removed" => False, "active" => True, "lat" => 41.753578, "lon" => -93.703921,
    "state" => "IA", "network" => "KCCI", "moviebase" => "saylor",
    "ip" => "69.20.218.6", "county" => "Polk", "port" => "65312"),
"KCRG-008" => Array("sts" => mktime(15,0,0,9, 11,2008), "ets" => time(),
    "name" => "Sigourney", "removed" => False, "active" => True, "lat" => 41.3313, "lon" => -92.2052,
    "state" => "IA", "network" => "KCRG", "moviebase" => "sigourney",
    "ip" => "207.28.74.9", "county" => "Keokuk", "port" => "80"),
"IDOT-040-03" => Array("sts" => mktime(13,0,0,12, 20,2009), "ets" => time(),
    "name" => "Sigourney East View", "removed" => False, "active" => True, "lat" => 41.33, "lon" => -92.31,
    "state" => "IA", "network" => "IDOT", "moviebase" => "None",
    "ip" => "None", "county" => "None", "port" => "None"),
"IDOT-040-04" => Array("sts" => mktime(13,0,0,12, 20,2009), "ets" => time(),
    "name" => "Sigourney East View Bridge Deck", "removed" => False, "active" => True, "lat" => 41.33, "lon" => -92.31,
    "state" => "IA", "network" => "IDOT", "moviebase" => "None",
    "ip" => "None", "county" => "None", "port" => "None"),
"IDOT-040-01" => Array("sts" => mktime(13,0,0,12, 20,2009), "ets" => time(),
    "name" => "Sigourney IA 92 Roadway", "removed" => False, "active" => True, "lat" => 41.33, "lon" => -92.31,
    "state" => "IA", "network" => "IDOT", "moviebase" => "None",
    "ip" => "None", "county" => "None", "port" => "None"),
"IDOT-040-02" => Array("sts" => mktime(13,0,0,12, 20,2009), "ets" => time(),
    "name" => "Sigourney Sensor", "removed" => False, "active" => True, "lat" => 41.33, "lon" => -92.31,
    "state" => "IA", "network" => "IDOT", "moviebase" => "None",
    "ip" => "None", "county" => "None", "port" => "None"),
"IDOT-040-00" => Array("sts" => mktime(13,0,0,12, 20,2009), "ets" => time(),
    "name" => "Sigourney West view", "removed" => False, "active" => True, "lat" => 41.33, "lon" => -92.31,
    "state" => "IA", "network" => "IDOT", "moviebase" => "None",
    "ip" => "None", "county" => "None", "port" => "None"),
"IDOT-042-02" => Array("sts" => mktime(13,0,0,12, 20,2009), "ets" => time(),
    "name" => "Spencer US 18", "removed" => False, "active" => True, "lat" => 43.13, "lon" => -95.08,
    "state" => "IA", "network" => "IDOT", "moviebase" => "None",
    "ip" => "None", "county" => "None", "port" => "None"),
"IDOT-042-00" => Array("sts" => mktime(13,0,0,12, 20,2009), "ets" => time(),
    "name" => "Spencer US 18 Bridge Deck", "removed" => False, "active" => True, "lat" => 43.13, "lon" => -95.08,
    "state" => "IA", "network" => "IDOT", "moviebase" => "None",
    "ip" => "None", "county" => "None", "port" => "None"),
"IDOT-042-01" => Array("sts" => mktime(13,0,0,12, 20,2009), "ets" => time(),
    "name" => "Spencer US 18 East View", "removed" => False, "active" => True, "lat" => 43.13, "lon" => -95.08,
    "state" => "IA", "network" => "IDOT", "moviebase" => "None",
    "ip" => "None", "county" => "None", "port" => "None"),
"IDOT-042-03" => Array("sts" => mktime(13,0,0,12, 20,2009), "ets" => time(),
    "name" => "Spencer US 18 West View", "removed" => False, "active" => True, "lat" => 43.13, "lon" => -95.08,
    "state" => "IA", "network" => "IDOT", "moviebase" => "None",
    "ip" => "None", "county" => "None", "port" => "None"),
"IDOT-050-00" => Array("sts" => mktime(13,0,0,12, 20,2009), "ets" => time(),
    "name" => "Steamboat Rock US 20 Bridge Deck", "removed" => False, "active" => True, "lat" => 42.4534, "lon" => -93.0583,
    "state" => "IA", "network" => "IDOT", "moviebase" => "None",
    "ip" => "None", "county" => "None", "port" => "None"),
"IDOT-050-02" => Array("sts" => mktime(13,0,0,12, 20,2009), "ets" => time(),
    "name" => "Steamboat Rock US 20 EB", "removed" => False, "active" => True, "lat" => 42.4534, "lon" => -93.0583,
    "state" => "IA", "network" => "IDOT", "moviebase" => "None",
    "ip" => "None", "county" => "None", "port" => "None"),
"IDOT-050-01" => Array("sts" => mktime(13,0,0,12, 20,2009), "ets" => time(),
    "name" => "Steamboat Rock US 20 WB", "removed" => False, "active" => True, "lat" => 42.4534, "lon" => -93.0583,
    "state" => "IA", "network" => "IDOT", "moviebase" => "None",
    "ip" => "None", "county" => "None", "port" => "None"),
"IDOT-043-04" => Array("sts" => mktime(13,0,0,12, 20,2009), "ets" => time(),
    "name" => "Storm Lake Hwy 3 EB", "removed" => False, "active" => True, "lat" => 42.74, "lon" => -95.15,
    "state" => "IA", "network" => "IDOT", "moviebase" => "None",
    "ip" => "None", "county" => "None", "port" => "None"),
"IDOT-043-00" => Array("sts" => mktime(13,0,0,12, 20,2009), "ets" => time(),
    "name" => "Storm Lake US 71", "removed" => False, "active" => True, "lat" => 42.74, "lon" => -95.15,
    "state" => "IA", "network" => "IDOT", "moviebase" => "None",
    "ip" => "None", "county" => "None", "port" => "None"),
"IDOT-043-01" => Array("sts" => mktime(13,0,0,12, 20,2009), "ets" => time(),
    "name" => "Storm Lake (US 71/IA 3)", "removed" => False, "active" => True, "lat" => 42.74, "lon" => -95.15,
    "state" => "IA", "network" => "IDOT", "moviebase" => "None",
    "ip" => "None", "county" => "None", "port" => "None"),
"IDOT-043-02" => Array("sts" => mktime(13,0,0,12, 20,2009), "ets" => time(),
    "name" => "Storm Lake US 71 SB", "removed" => False, "active" => True, "lat" => 42.74, "lon" => -95.15,
    "state" => "IA", "network" => "IDOT", "moviebase" => "None",
    "ip" => "None", "county" => "None", "port" => "None"),
"KCCI-029" => Array("sts" => mktime(9,0,0,6, 5,2007), "ets" => time(),
    "name" => "Stratford", "removed" => False, "active" => True, "lat" => 42.271751, "lon" => -93.925123,
    "state" => "IA", "network" => "KCCI", "moviebase" => "stratford",
    "ip" => "67.55.246.251", "county" => "Hamilton", "port" => "80"),
"KCCI-033" => Array("sts" => mktime(16,0,0,7, 30,2008), "ets" => time(),
    "name" => "Stuart", "removed" => False, "active" => True, "lat" => 41.5039, "lon" => -94.3167,
    "state" => "IA", "network" => "KCCI", "moviebase" => "stuart",
    "ip" => "69.63.24.241", "county" => "Guthrie", "port" => "80"),
"KCCI-017" => Array("sts" => mktime(0,0,0,5, 18,2005), "ets" => time(),
    "name" => "Tama", "removed" => False, "active" => True, "lat" => 41.99262, "lon" => -92.6465,
    "state" => "IA", "network" => "KCCI", "moviebase" => "tama",
    "ip" => "169.203.92.94", "county" => "Tama", "port" => "80"),
"IDOT-057-04" => Array("sts" => mktime(13,0,0,12, 20,2009), "ets" => time(),
    "name" => "Tama Hwy 21", "removed" => False, "active" => True, "lat" => 41.9649, "lon" => -92.2983,
    "state" => "IA", "network" => "IDOT", "moviebase" => "None",
    "ip" => "None", "county" => "None", "port" => "None"),
"IDOT-057-02" => Array("sts" => mktime(13,0,0,12, 20,2009), "ets" => time(),
    "name" => "Tama Hwy 21 SB", "removed" => False, "active" => True, "lat" => 41.9649, "lon" => -92.2983,
    "state" => "IA", "network" => "IDOT", "moviebase" => "None",
    "ip" => "None", "county" => "None", "port" => "None"),
"IDOT-057-01" => Array("sts" => mktime(13,0,0,12, 20,2009), "ets" => time(),
    "name" => "Tama Hwy 30 and 21", "removed" => False, "active" => True, "lat" => 41.9649, "lon" => -92.2983,
    "state" => "IA", "network" => "IDOT", "moviebase" => "None",
    "ip" => "None", "county" => "None", "port" => "None"),
"IDOT-057-03" => Array("sts" => mktime(13,0,0,12, 20,2009), "ets" => time(),
    "name" => "Tama Hwy 30 EB", "removed" => False, "active" => True, "lat" => 41.9649, "lon" => -92.2983,
    "state" => "IA", "network" => "IDOT", "moviebase" => "None",
    "ip" => "None", "county" => "None", "port" => "None"),
"IDOT-057-00" => Array("sts" => mktime(13,0,0,12, 20,2009), "ets" => time(),
    "name" => "Tama Hwy 30 Sensor", "removed" => False, "active" => True, "lat" => 41.9649, "lon" => -92.2983,
    "state" => "IA", "network" => "IDOT", "moviebase" => "None",
    "ip" => "None", "county" => "None", "port" => "None"),
"IDOT-057-05" => Array("sts" => mktime(13,0,0,12, 20,2009), "ets" => time(),
    "name" => "Tama Hwy 30 WB", "removed" => False, "active" => True, "lat" => 41.9649, "lon" => -92.2983,
    "state" => "IA", "network" => "IDOT", "moviebase" => "None",
    "ip" => "None", "county" => "None", "port" => "None"),
"KCRG-010" => Array("sts" => mktime(12,0,0,10, 9,2008), "ets" => time(),
    "name" => "Tipton", "removed" => False, "active" => True, "lat" => 41.7702, "lon" => -91.1282,
    "state" => "IA", "network" => "KCRG", "moviebase" => "tipton",
    "ip" => "69.66.52.7", "county" => "Cedar", "port" => "80"),
"IDOT-044-01" => Array("sts" => mktime(13,0,0,12, 20,2009), "ets" => time(),
    "name" => "Tipton I-80 East and West Bridge Deck", "removed" => False, "active" => True, "lat" => 41.6448, "lon" => -91.1272,
    "state" => "IA", "network" => "IDOT", "moviebase" => "None",
    "ip" => "None", "county" => "None", "port" => "None"),
"IDOT-044-00" => Array("sts" => mktime(13,0,0,12, 20,2009), "ets" => time(),
    "name" => "Tipton I-80 East and West Lanes", "removed" => False, "active" => True, "lat" => 41.6448, "lon" => -91.1272,
    "state" => "IA", "network" => "IDOT", "moviebase" => "None",
    "ip" => "None", "county" => "None", "port" => "None"),
"IDOT-044-03" => Array("sts" => mktime(13,0,0,12, 20,2009), "ets" => time(),
    "name" => "Tipton I-80 East and West Lanes", "removed" => False, "active" => True, "lat" => 41.6448, "lon" => -91.1272,
    "state" => "IA", "network" => "IDOT", "moviebase" => "None",
    "ip" => "None", "county" => "None", "port" => "None"),
"IDOT-044-02" => Array("sts" => mktime(13,0,0,12, 20,2009), "ets" => time(),
    "name" => "Tipton I-80 West", "removed" => False, "active" => True, "lat" => 41.6448, "lon" => -91.1272,
    "state" => "IA", "network" => "IDOT", "moviebase" => "None",
    "ip" => "None", "county" => "None", "port" => "None"),
"KCCI-030" => Array("sts" => mktime(11,0,0,9, 28,2007), "ets" => time(),
    "name" => "Twin Cedars", "removed" => False, "active" => True, "lat" => 41.2183, "lon" => -92.9268,
    "state" => "IA", "network" => "KCCI", "moviebase" => "twincedars",
    "ip" => "209.56.232.244", "county" => "Marion", "port" => "80"),
"KCRG-004" => Array("sts" => mktime(15,0,0,5, 16,2008), "ets" => time(),
    "name" => "Vinton", "removed" => False, "active" => True, "lat" => 42.17, "lon" => -92.024,
    "state" => "IA", "network" => "KCRG", "moviebase" => "vinton",
    "ip" => "205.221.16.23", "county" => "Vinton", "port" => "80"),
"KCRG-003" => Array("sts" => mktime(14,0,0,4, 24,2008), "ets" => time(),
    "name" => "Washington", "removed" => False, "active" => True, "lat" => 41.29, "lon" => -91.68,
    "state" => "IA", "network" => "KCRG", "moviebase" => "washington",
    "ip" => "205.221.150.200", "county" => "Washington", "port" => "80"),
"IDOT-046-00" => Array("sts" => mktime(13,0,0,12, 20,2009), "ets" => time(),
    "name" => "Waterloo I-380 and US20 Bridge Deck", "removed" => False, "active" => True, "lat" => 42.45, "lon" => -92.31,
    "state" => "IA", "network" => "IDOT", "moviebase" => "None",
    "ip" => "None", "county" => "None", "port" => "None"),
"IDOT-046-01" => Array("sts" => mktime(13,0,0,12, 20,2009), "ets" => time(),
    "name" => "Waterloo I-380 US20 EB Approach", "removed" => False, "active" => True, "lat" => 42.45, "lon" => -92.31,
    "state" => "IA", "network" => "IDOT", "moviebase" => "None",
    "ip" => "None", "county" => "None", "port" => "None"),
"IDOT-046-02" => Array("sts" => mktime(13,0,0,12, 20,2009), "ets" => time(),
    "name" => "Waterloo I-380 US20 WB Approach", "removed" => False, "active" => True, "lat" => 42.45, "lon" => -92.31,
    "state" => "IA", "network" => "IDOT", "moviebase" => "None",
    "ip" => "None", "county" => "None", "port" => "None"),
"IDOT-046-03" => Array("sts" => mktime(13,0,0,12, 20,2009), "ets" => time(),
    "name" => "Waterloo I-380 US20 WB Ramp", "removed" => False, "active" => True, "lat" => 42.45, "lon" => -92.31,
    "state" => "IA", "network" => "IDOT", "moviebase" => "None",
    "ip" => "None", "county" => "None", "port" => "None"),
"IDOT-046-04" => Array("sts" => mktime(13,0,0,12, 20,2009), "ets" => time(),
    "name" => "Waterloo US 218", "removed" => False, "active" => True, "lat" => 42.45, "lon" => -92.31,
    "state" => "IA", "network" => "IDOT", "moviebase" => "None",
    "ip" => "None", "county" => "None", "port" => "None"),
"KELO-004" => Array("sts" => mktime(15,0,0,5, 19,2008), "ets" => time(),
    "name" => "Watertown", "removed" => False, "active" => True, "lat" => 44.904071, "lon" => -97.120855,
    "state" => "SD", "network" => "KELO", "moviebase" => "watertown",
    "ip" => "69.9.243.29", "county" => "Codington", "port" => "80"),
"KCCI-003" => Array("sts" => mktime(0,0,0,8, 28,2003), "ets" => time(),
    "name" => "Webster City", "removed" => False, "active" => True, "lat" => 42.47, "lon" => -93.82,
    "state" => "IA", "network" => "KCCI", "moviebase" => "web",
    "ip" => "216.51.195.93", "county" => "Hamilton", "port" => "80"),
"KCRG-009" => Array("sts" => mktime(13,0,0,9, 17,2008), "ets" => time(),
    "name" => "Williamsburg", "removed" => False, "active" => True, "lat" => 41.6689, "lon" => -92.0,
    "state" => "IA", "network" => "KCRG", "moviebase" => "williamsburg",
    "ip" => "69.66.104.157", "county" => "Iowa", "port" => "65312"),
"IDOT-048-00" => Array("sts" => mktime(13,0,0,12, 20,2009), "ets" => time(),
    "name" => "Williamsburg Position 1", "removed" => False, "active" => True, "lat" => 41.68, "lon" => -92.01,
    "state" => "IA", "network" => "IDOT", "moviebase" => "None",
    "ip" => "None", "county" => "None", "port" => "None"),
"IDOT-048-01" => Array("sts" => mktime(13,0,0,12, 20,2009), "ets" => time(),
    "name" => "Williamsburg Position 2", "removed" => False, "active" => True, "lat" => 41.68, "lon" => -92.01,
    "state" => "IA", "network" => "IDOT", "moviebase" => "None",
    "ip" => "None", "county" => "None", "port" => "None"),
"IDOT-048-02" => Array("sts" => mktime(13,0,0,12, 20,2009), "ets" => time(),
    "name" => "Williamsburg Position 3", "removed" => False, "active" => True, "lat" => 41.68, "lon" => -92.01,
    "state" => "IA", "network" => "IDOT", "moviebase" => "None",
    "ip" => "None", "county" => "None", "port" => "None"),
"IDOT-047-00" => Array("sts" => mktime(13,0,0,12, 20,2009), "ets" => time(),
    "name" => "Williams I-35 North", "removed" => False, "active" => True, "lat" => 42.5875, "lon" => -93.5315,
    "state" => "IA", "network" => "IDOT", "moviebase" => "None",
    "ip" => "None", "county" => "None", "port" => "None"),
"IDOT-047-01" => Array("sts" => mktime(13,0,0,12, 20,2009), "ets" => time(),
    "name" => "Williams I-35 South", "removed" => False, "active" => True, "lat" => 42.5875, "lon" => -93.5315,
    "state" => "IA", "network" => "IDOT", "moviebase" => "None",
    "ip" => "None", "county" => "None", "port" => "None"),
"IDOT-047-03" => Array("sts" => mktime(13,0,0,12, 20,2009), "ets" => time(),
    "name" => "Williams NB Bridge Deck", "removed" => False, "active" => True, "lat" => 42.5875, "lon" => -93.5315,
    "state" => "IA", "network" => "IDOT", "moviebase" => "None",
    "ip" => "None", "county" => "None", "port" => "None"),
"IDOT-047-02" => Array("sts" => mktime(13,0,0,12, 20,2009), "ets" => time(),
    "name" => "Williams SB Bridge Deck", "removed" => False, "active" => True, "lat" => 42.5875, "lon" => -93.5315,
    "state" => "IA", "network" => "IDOT", "moviebase" => "None",
    "ip" => "None", "county" => "None", "port" => "None"),
"KCCI-013" => Array("sts" => mktime(17,0,0,5, 14,2004), "ets" => time(),
    "name" => "Winterset", "removed" => False, "active" => True, "lat" => 41.33, "lon" => -94.01,
    "state" => "IA", "network" => "KCCI", "moviebase" => "winterset",
    "ip" => "173.19.142.63", "county" => "Madison", "port" => "80"),
"KCCI-032" => Array("sts" => mktime(14,0,0,9, 16,2008), "ets" => time(),
    "name" => "Woodward", "removed" => False, "active" => True, "lat" => 41.86, "lon" => -93.92,
    "state" => "IA", "network" => "KCCI", "moviebase" => "woodward",
    "ip" => "216.248.110.33", "county" => "Polk", "port" => "80"),
"IDOT-049-00" => Array("sts" => mktime(13,0,0,12, 20,2009), "ets" => time(),
    "name" => "Worth County I 35 NB", "removed" => False, "active" => True, "lat" => 43.39, "lon" => -93.34,
    "state" => "IA", "network" => "IDOT", "moviebase" => "None",
    "ip" => "None", "county" => "None", "port" => "None"),
"IDOT-049-03" => Array("sts" => mktime(13,0,0,12, 20,2009), "ets" => time(),
    "name" => "Worth County I 35 SB", "removed" => False, "active" => True, "lat" => 43.39, "lon" => -93.34,
    "state" => "IA", "network" => "IDOT", "moviebase" => "None",
    "ip" => "None", "county" => "None", "port" => "None"),
"IDOT-049-02" => Array("sts" => mktime(13,0,0,12, 20,2009), "ets" => time(),
    "name" => "Worth County I 35 SB Bridge", "removed" => False, "active" => True, "lat" => 43.39, "lon" => -93.34,
    "state" => "IA", "network" => "IDOT", "moviebase" => "None",
    "ip" => "None", "county" => "None", "port" => "None"),
"IDOT-049-01" => Array("sts" => mktime(13,0,0,12, 20,2009), "ets" => time(),
    "name" => "Worth County I 35 Sensor", "removed" => False, "active" => True, "lat" => 43.39, "lon" => -93.34,
    "state" => "IA", "network" => "IDOT", "moviebase" => "None",
    "ip" => "None", "county" => "None", "port" => "None"),
); ?>