<?php

$cities = Array(
"ADAI4" => array("city" => "ADAIR", "id" => "ADAI4", "lat" => "41.5", "lon" => "-94.63"),
"AGSI4" => array("city" => "AGSI4 SKUNK RIVER NR AUGUSTA", "id" => "AGSI4", "lat" => "46.75", "lon" => "-91.28"),
"GRMI4" => array("city" => "BEAVER CREEK NR GRIMES 3E", "id" => "GRMI4", "lat" => "41.69", "lon" => "-93.74"),
"WWDI4" => array("city" => "BEAVER CREEK NR WOODWARD 3SW", "id" => "WWDI4", "lat" => "41.8", "lon" => "-93.94"),
"CBSI4" => array("city" => "BEAVER SLOUGH AT 3RD ST IN CLINT", "id" => "CBSI4", "lat" => "41.83", "lon" => "-90.18"),
"LADI4" => array("city" => "BIG BEAR CREEK AT LADORA", "id" => "LADI4", "lat" => "41.75", "lon" => "-92.18"),
"PLKI4" => array("city" => "BIG CREEK PARK NR POLK CITY 2NE", "id" => "PLKI4", "lat" => "41.79", "lon" => "-93.73"),
"AKRI4" => array("city" => "BIG SIOUX RVR AT AKRON", "id" => "AKRI4", "lat" => "42.84", "lon" => "-96.56"),
"BIGI4" => array("city" => "BIGI4 BIG CREEK AT PONDING NR PO", "id" => "BIGI4", "lat" => "41.36", "lon" => "-92.97"),
"HUDI4" => array("city" => "BLACK HAWK CREEK AT HUDSON", "id" => "HUDI4", "lat" => "42.41", "lon" => "-92.46"),
"BHLI4" => array("city" => "BLACK HAWK LAKE AT LAKE VIEW", "id" => "BHLI4", "lat" => "42.3", "lon" => "-95.04"),
"MBRI4" => array("city" => "BLOODY RUN CREEK NR MARQUETTE", "id" => "MBRI4", "lat" => "43.04", "lon" => "-91.21"),
"GLDI4" => array("city" => "BOONE RIVER NR GOLDFIELD 2SW", "id" => "GLDI4", "lat" => "42.73", "lon" => "-93.97"),
"WBCI4" => array("city" => "BOONE RIVER NR WEBSTER CITY 2S", "id" => "WBCI4", "lat" => "42.43", "lon" => "-93.8"),
"LGNI4" => array("city" => "BOYER RIVER AT LOGAN #2", "id" => "LGNI4", "lat" => "41.64", "lon" => "-95.78"),
"GJTI4" => array("city" => "BUTTRICK CREEK NR GRAND JUNCTION", "id" => "GJTI4", "lat" => "42.02", "lon" => "-94.29"),
"OKMI4" => array("city" => "CEDAR CK NR OAKLAND MILLS", "id" => "OKMI4", "lat" => "40.92", "lon" => "-91.67"),
"BSSI4" => array("city" => "CEDAR CREEK NR BUSSEY 3WNW", "id" => "BSSI4", "lat" => "41.22", "lon" => "-92.91"),
"CEDI4" => array("city" => "CEDAR RIVER AT CEDAR FALLS", "id" => "CEDI4", "lat" => "42.54", "lon" => "-92.45"),
"CIDI4" => array("city" => "CEDAR RIVER AT CEDAR RAPIDS #2", "id" => "CIDI4", "lat" => "41.97", "lon" => "-91.68"),
"CCYI4" => array("city" => "CEDAR RIVER AT CHARLES CITY", "id" => "CCYI4", "lat" => "43.06", "lon" => "-92.67"),
"ALOI4" => array("city" => "CEDAR RIVER NEAR WATERLOO", "id" => "ALOI4", "lat" => "42.5", "lon" => "-92.33"),
"CNEI4" => array("city" => "CEDAR RIVER NR CONESVILLE 3NE", "id" => "CNEI4", "lat" => "41.41", "lon" => "-91.29"),
"WVLI4" => array("city" => "CEDAR RIVER NR WAVERLY", "id" => "WVLI4", "lat" => "42.74", "lon" => "-92.13"),
"CHTI4" => array("city" => "CHARITON RIVER NR CHARITON 5SE", "id" => "CHTI4", "lat" => "40.95", "lon" => "-93.26"),
"MOLI4" => array("city" => "CHARITON RIVER NR MOULTON 5W", "id" => "MOLI4", "lat" => "40.69", "lon" => "-92.77"),
"CRAI4" => array("city" => "CLEAR CREEK NR CORALVILLE", "id" => "CRAI4", "lat" => "41.68", "lon" => "-91.6"),
"CLKI4" => array("city" => "CLEAR LAKE AT CLEAR LAKE", "id" => "CLKI4", "lat" => "43.13", "lon" => "-93.38"),
"COOI4" => array("city" => "COON RAPIDS", "id" => "COOI4", "lat" => "41.87", "lon" => "-94.67"),
"CDMI4" => array("city" => "CORALVILLE DAM WEATHER STATION N", "id" => "CDMI4", "lat" => "41.72", "lon" => "-91.53"),
"CRWI4" => array("city" => "CROW CREEK NR BETTENDORF 2NE", "id" => "CRWI4", "lat" => "41.55", "lon" => "-90.45"),
"TOLI4" => array("city" => "DEER CREEK NR TOLEDO 1NW", "id" => "TOLI4", "lat" => "42.0", "lon" => "-92.59"),
"PELI4" => array("city" => "DES MOI. R AT RED ROCK D. NR PEL", "id" => "PELI4", "lat" => "41.36", "lon" => "-92.97"),
"DFMI4" => array("city" => "DES MOINES EASTON BLVD", "id" => "DFMI4", "lat" => "41.6", "lon" => "-93.53"),
"DESI4" => array("city" => "DES MOINES R AT DES MOINES (SE 6", "id" => "DESI4", "lat" => "41.58", "lon" => "-93.61"),
"DAKI4" => array("city" => "DES MOINES RIVER AT DAKOTA CITY", "id" => "DAKI4", "lat" => "42.72", "lon" => "-94.19"),
"ESVI4" => array("city" => "DES MOINES RIVER AT ESTHERVILLE", "id" => "ESVI4", "lat" => "43.4", "lon" => "-94.84"),
"FODI4" => array("city" => "DES MOINES RIVER AT FORT DODGE", "id" => "FODI4", "lat" => "42.51", "lon" => "-94.2"),
"KEQI4" => array("city" => "DES MOINES RIVER AT KEOSAUQUA", "id" => "KEQI4", "lat" => "40.73", "lon" => "-91.96"),
"RUNI4" => array("city" => "DES MOINES RIVER AT RUNNELLS", "id" => "RUNI4", "lat" => "41.49", "lon" => "-93.34"),
"OTMI4" => array("city" => "DES MOINES RIVER NR OTTUMWA", "id" => "OTMI4", "lat" => "41.01", "lon" => "-92.41"),
"STRI4" => array("city" => "DES MOINES RIVER NR STRATFORD 4W", "id" => "STRI4", "lat" => "42.25", "lon" => "-94.0"),
"TRCI4" => array("city" => "DES MOINES RIVER NR TRACEY 1NE", "id" => "TRCI4", "lat" => "41.28", "lon" => "-92.86"),
"DMOI4" => array("city" => "DES MOINES RVR AT 2ND AVE DES MO", "id" => "DMOI4", "lat" => "41.61", "lon" => "-93.65"),
"AGNI4" => array("city" => "EAST FK DES MOINES RIVER NR ALGO", "id" => "AGNI4", "lat" => "43.08", "lon" => "-94.24"),
"BDFI4" => array("city" => "EAST FORK 102 RIVER NR BEDFORD", "id" => "BDFI4", "lat" => "40.66", "lon" => "-94.72"),
"ATCI4" => array("city" => "EAST NISHNABOTNA RIVER NR ATLANT", "id" => "ATCI4", "lat" => "41.35", "lon" => "-95.08"),
"RDOI4" => array("city" => "EAST NISHNABOTNA RIVER NR RED OA", "id" => "RDOI4", "lat" => "41.01", "lon" => "-95.24"),
"EDYI4" => array("city" => "EDY14 DES MOINES RIVER NR EDDYVI", "id" => "EDYI4", "lat" => "41.16", "lon" => "-92.64"),
"KECI4" => array("city" => "ENGLISH CREEK NR KNOXVILLE 3E", "id" => "KECI4", "lat" => "41.27", "lon" => "-93.08"),
"KALI4" => array("city" => "ENGLISH RIVER NR KALONA 1SSW", "id" => "KALI4", "lat" => "41.47", "lon" => "-91.72"),
"EOKI4" => array("city" => "EOKI4 L & D 19 KEOKUK", "id" => "EOKI4", "lat" => "40.39", "lon" => "-91.37"),
"ALTI4" => array("city" => "FLOYD RIVER AT ALTON", "id" => "ALTI4", "lat" => "42.98", "lon" => "-96.0"),
"JMEI4" => array("city" => "FLOYD RIVER NR JAMES 1NE", "id" => "JMEI4", "lat" => "42.58", "lon" => "-96.31"),
"WBRI4" => array("city" => "HOOVER CRK AT WEST BRANCH", "id" => "WBRI4", "lat" => "41.67", "lon" => "-91.35"),
"IOCI4" => array("city" => "IOW14 OLD MANS CRK. AT IOWA CITY", "id" => "IOCI4", "lat" => "43.61", "lon" => "-91.62"),
"CTWI4" => array("city" => "IOWA R AT CORALVILLE LAKE (TW) C", "id" => "CTWI4", "lat" => "41.72", "lon" => "-91.53"),
"TAMI4" => array("city" => "IOWA R. AT TAMA", "id" => "TAMI4", "lat" => "41.95", "lon" => "-92.58"),
"CRVI4" => array("city" => "IOWA RIVER AT CORALVILLE LAKE (H", "id" => "CRVI4", "lat" => "41.72", "lon" => "-91.53"),
"IOWI4" => array("city" => "IOWA RIVER AT IOWA CITY -NO2", "id" => "IOWI4", "lat" => "41.66", "lon" => "-91.54"),
"MIWI4" => array("city" => "IOWA RIVER AT MARSHALLTOWN (POLL", "id" => "MIWI4", "lat" => "42.07", "lon" => "-92.91"),
"STBI4" => array("city" => "IOWA RIVER AT STEAMBOAT ROCK", "id" => "STBI4", "lat" => "42.42", "lon" => "-93.08"),
"WAPI4" => array("city" => "IOWA RIVER AT WAPELLO", "id" => "WAPI4", "lat" => "41.18", "lon" => "-91.18"),
"BPLI4" => array("city" => "IOWA RIVER NR BELLE PLAINE 3S", "id" => "BPLI4", "lat" => "41.86", "lon" => "-92.24"),
"CJTI4" => array("city" => "IOWA RIVER NR COLUMBUS JUNCTION", "id" => "CJTI4", "lat" => "41.28", "lon" => "-91.35"),
"LNTI4" => array("city" => "IOWA RIVER NR LONE TREE 5SW", "id" => "LNTI4", "lat" => "41.42", "lon" => "-91.47"),
"MROI4" => array("city" => "IOWA RIVER NR MARENGO 1N", "id" => "MROI4", "lat" => "41.81", "lon" => "-92.06"),
"ROWI4" => array("city" => "IOWA RIVER NR ROWAN 4NW", "id" => "ROWI4", "lat" => "42.76", "lon" => "-93.62"),
"CRRI4" => array("city" => "LITTLE SIOUX R NR CORRECTIONVILL", "id" => "CRRI4", "lat" => "42.47", "lon" => "-95.8"),
"LNNI4" => array("city" => "LITTLE SIOUX RIVER AT LINN GROVE", "id" => "LNNI4", "lat" => "42.89", "lon" => "-95.24"),
"TURI4" => array("city" => "LITTLE SIOUX RIVER NR TURIN 4S", "id" => "TURI4", "lat" => "41.96", "lon" => "-95.97"),
"FLZI4" => array("city" => "LIZARD CREEK NR FORT DODGE 4NW", "id" => "FLZI4", "lat" => "42.53", "lon" => "-93.71"),
"DLDI4" => array("city" => "LOCK & DAM #11 MISSISSIPPI RVR A", "id" => "DLDI4", "lat" => "42.54", "lon" => "-90.65"),
"BLVI4" => array("city" => "LOCK & DAM #12 MISSISSIPPI RVR A", "id" => "BLVI4", "lat" => "42.27", "lon" => "-90.42"),
"GTTI4" => array("city" => "LOCK & DAM 10 TAILWATER NR GUTTE", "id" => "GTTI4", "lat" => "42.78", "lon" => "-91.1"),
"MAPI4" => array("city" => "MAPLE RIVER AT MAPLETON", "id" => "MAPI4", "lat" => "42.16", "lon" => "-95.81"),
"MCHI4" => array("city" => "MAQUOKETA RIVER AT MANCHESTER", "id" => "MCHI4", "lat" => "42.47", "lon" => "-91.45"),
"MAQI4" => array("city" => "MAQUOKETA RIVER NR MAQUOKETA 2NE", "id" => "MAQI4", "lat" => "42.08", "lon" => "-90.63"),
"MXWI4" => array("city" => "MAXWELL", "id" => "MXWI4", "lat" => "41.88", "lon" => "-93.38"),
"PANI4" => array("city" => "MIDDLE RACCON RIVER AT PANORA", "id" => "PANI4", "lat" => "41.69", "lon" => "-94.37"),
"BAYI4" => array("city" => "MIDDLE RACCON RIVER NR BAYARD 6S", "id" => "BAYI4", "lat" => "41.78", "lon" => "-94.49"),
"IDNI4" => array("city" => "MIDDLE RIVER NR INDIANOLA 5NNW", "id" => "IDNI4", "lat" => "41.42", "lon" => "-93.59"),
"MGOI4" => array("city" => "MINGO 3 NW", "id" => "MGOI4", "lat" => "41.8", "lon" => "-93.32"),
"BRLI4" => array("city" => "MISSISSIPPI RIVER AT BURLINGTON", "id" => "BRLI4", "lat" => "40.82", "lon" => "-91.1"),
"CLAI4" => array("city" => "MISSISSIPPI RIVER AT CLAYTON", "id" => "CLAI4", "lat" => "42.9", "lon" => "-91.15"),
"DBQI4" => array("city" => "MISSISSIPPI RIVER AT DUBUQUE, IA", "id" => "DBQI4", "lat" => "42.5", "lon" => "-90.65"),
"FMDI4" => array("city" => "MISSISSIPPI RIVER AT FORT MADISO", "id" => "FMDI4", "lat" => "40.63", "lon" => "-91.3"),
"LNSI4" => array("city" => "MISSISSIPPI RIVER AT LANSING", "id" => "LNSI4", "lat" => "43.35", "lon" => "-91.2"),
"LECI4" => array("city" => "MISSISSIPPI RIVER AT LE CLAIRE (", "id" => "LECI4", "lat" => "41.58", "lon" => "-90.4"),
"MCGI4" => array("city" => "MISSISSIPPI RIVER AT MCGREGOR NO", "id" => "MCGI4", "lat" => "43.02", "lon" => "-91.17"),
"MUSI4" => array("city" => "MISSISSIPPI RIVER AT MUSCATINE N", "id" => "MUSI4", "lat" => "41.42", "lon" => "-91.03"),
"CMMI4" => array("city" => "MISSISSIPPI RIVER NR CAMANCHE (C", "id" => "CMMI4", "lat" => "41.78", "lon" => "-90.25"),
"FAII4" => array("city" => "MISSISSIPPI RIVER NR FAIRPORT", "id" => "FAII4", "lat" => "41.43", "lon" => "-90.88"),
"TRNI4" => array("city" => "MONA-HARRISON DITCH NR TURIN 4SS", "id" => "TRNI4", "lat" => "41.96", "lon" => "-95.99"),
"NSWI4" => array("city" => "NEAL SMITH NATIONAL WILDLIFE REF", "id" => "NSWI4", "lat" => "41.57", "lon" => "-93.26"),
"HMBI4" => array("city" => "NISHNABOTNA RIVER NR HAMBURG 2NE", "id" => "HMBI4", "lat" => "40.63", "lon" => "-95.63"),
"ICLI4" => array("city" => "NODAWAY RVR AT CLARINDA", "id" => "ICLI4", "lat" => "40.74", "lon" => "-95.01"),
"NEPI4" => array("city" => "NORTH FORK ENGLISH RIVER NR NORT", "id" => "NEPI4", "lat" => "41.56", "lon" => "-92.07"),
"EFWI4" => array("city" => "NORTH FORK RACCOON R NR JEFFERSO", "id" => "EFWI4", "lat" => "41.99", "lon" => "-94.38"),
"FLNI4" => array("city" => "NORTH MAQUOKETA R. NR FULTON 3NW", "id" => "FLNI4", "lat" => "42.16", "lon" => "-90.73"),
"SCRI4" => array("city" => "NORTH RACCON RIVER NR SAC CITY 5", "id" => "SCRI4", "lat" => "42.35", "lon" => "-94.99"),
"LKCI4" => array("city" => "NORTH RACCOON RIVER NR LAKE CITY", "id" => "LKCI4", "lat" => "42.17", "lon" => "-94.73"),
"PROI4" => array("city" => "NORTH RACCOON RIVER NR PERRY 1W", "id" => "PROI4", "lat" => "41.84", "lon" => "-94.13"),
"NRWI4" => array("city" => "NORTH RIVER NR NORWALK 2SE", "id" => "NRWI4", "lat" => "41.46", "lon" => "-93.65"),
"SPOI4" => array("city" => "OCHEYEDAN RIVER NR SPENCER 3SW", "id" => "SPOI4", "lat" => "43.13", "lon" => "-95.21"),
"OGDI4" => array("city" => "OGDEN", "id" => "OGDI4", "lat" => "42.03", "lon" => "-94.03"),
"SIOI4" => array("city" => "PERRY CREEK NR SIOUX CITY 4N", "id" => "SIOI4", "lat" => "42.54", "lon" => "-96.41"),
"RLFI4" => array("city" => "PILOT CREEK NR ROLFE 1NW", "id" => "RLFI4", "lat" => "42.81", "lon" => "-94.56"),
"BLRI4" => array("city" => "PRAIRIE CREEK NR BLAIRSTOWN 2E", "id" => "BLRI4", "lat" => "41.91", "lon" => "-92.04"),
"DMWI4" => array("city" => "RACCOON RIVER AT 63RD STREET IN", "id" => "DMWI4", "lat" => "41.56", "lon" => "-93.7"),
"DEMI4" => array("city" => "RACCOON RIVER AT FLEUR DRIVE", "id" => "DEMI4", "lat" => "41.58", "lon" => "-93.64"),
"VNMI4" => array("city" => "RACCOON RIVER AT VAN METER", "id" => "VNMI4", "lat" => "41.53", "lon" => "-93.95"),
"WDMI4" => array("city" => "RACCOON RIVER AT WEST DES MOINES", "id" => "WDMI4", "lat" => "41.53", "lon" => "-93.78"),
"RADI4" => array("city" => "RATHBUN DAM", "id" => "RADI4", "lat" => "40.83", "lon" => "-92.9"),
"RRDI4" => array("city" => "RED ROCK DAM TAILWATER NR PELLA", "id" => "RRDI4", "lat" => "41.37", "lon" => "-92.98"),
"KDMI4" => array("city" => "RED ROCK DAM WEATHER STATION", "id" => "KDMI4", "lat" => "41.36", "lon" => "-92.97"),
"HAVI4" => array("city" => "RICHLAND CREEK NEAR HAVEN 1NE", "id" => "HAVI4", "lat" => "41.9", "lon" => "-92.47"),
"RAPI4" => array("city" => "ROCK RIVER NEAR ROCK RAPIDS", "id" => "RAPI4", "lat" => "43.42", "lon" => "-96.16"),
"RKVI4" => array("city" => "ROCK RIVER NR ROCK VALLEY", "id" => "RKVI4", "lat" => "43.21", "lon" => "-96.29"),
"IRCI4" => array("city" => "ROCK RVR NR JOSLIN, IL", "id" => "IRCI4", "lat" => "41.69", "lon" => "-91.49"),
"RWCI4" => array("city" => "ROCKWELL CITY 2", "id" => "RWCI4", "lat" => "42.38", "lon" => "-94.62"),
"PRMI4" => array("city" => "S.FK. CHARITON RIVER NR PROMISE", "id" => "PRMI4", "lat" => "40.8", "lon" => "-93.19"),
"EBRI4" => array("city" => "SALT CREEK NR ELBERON", "id" => "EBRI4", "lat" => "41.96", "lon" => "-92.31"),
"SDTI4" => array("city" => "SAYLORVILLE DAM (TW) NR SAYLORVI", "id" => "SDTI4", "lat" => "41.68", "lon" => "-93.67"),
"SAYI4" => array("city" => "SAYLORVILLE DAM POOL NR SAYLORVI", "id" => "SAYI4", "lat" => "41.7", "lon" => "-93.71"),
"SDMI4" => array("city" => "SAYLORVILLE DAM WEATHER STATION", "id" => "SDMI4", "lat" => "41.7", "lon" => "-93.69"),
"OOAI4" => array("city" => "SKUNK RIVER NR OSKALOOSA 4N", "id" => "OOAI4", "lat" => "41.36", "lon" => "-92.66"),
"SIGI4" => array("city" => "SKUNK RIVER NR SIGOURNEY 2S", "id" => "SIGI4", "lat" => "41.3", "lon" => "-92.2"),
"SMCI4" => array("city" => "SNY MAGIL CREEK NR CLAYTON 3NE", "id" => "SMCI4", "lat" => "42.95", "lon" => "-91.19"),
"PSGI4" => array("city" => "SOLDIER RIVER AT PISGAH", "id" => "PSGI4", "lat" => "41.83", "lon" => "-95.93"),
"REDI4" => array("city" => "SOUTH RACCOON RIVER NR REDFIELD", "id" => "REDI4", "lat" => "41.59", "lon" => "-94.15"),
"AKWI4" => array("city" => "SOUTH RIVER NR ACKWORTH 2SW", "id" => "AKWI4", "lat" => "41.34", "lon" => "-93.49"),
"CFXI4" => array("city" => "SOUTH SKUNK RIVER AT COLFAX", "id" => "CFXI4", "lat" => "41.68", "lon" => "-93.25"),
"SLKI4" => array("city" => "SPIRIT LAKE NR ORLEANS", "id" => "SLKI4", "lat" => "43.47", "lon" => "-95.12"),
"SQCI4" => array("city" => "SQUAW CREEK NEAR COLFAX", "id" => "SQCI4", "lat" => "41.66", "lon" => "-93.27"),
"DVSI4" => array("city" => "THOMPSON RIVER AT DAVIS CITY", "id" => "DVSI4", "lat" => "40.64", "lon" => "-93.81"),
"MTWI4" => array("city" => "TIMBER CREEK NR MARSHALLTOWN 4SE", "id" => "MTWI4", "lat" => "42.01", "lon" => "-92.85"),
"EKDI4" => array("city" => "TURKEY RIVER AT ELKADER", "id" => "EKDI4", "lat" => "42.84", "lon" => "-91.4"),
"EDRI4" => array("city" => "TURKEY RIVER NR ELDORADO", "id" => "EDRI4", "lat" => "43.05", "lon" => "-91.81"),
"GRBI4" => array("city" => "TURKEY RIVER NR GARBER", "id" => "GRBI4", "lat" => "42.74", "lon" => "-91.26"),
"BLFI4" => array("city" => "UPPER IOWA RIVER AT BLUFFTON", "id" => "BLFI4", "lat" => "43.41", "lon" => "-91.9"),
"DCHI4" => array("city" => "UPPER IOWA RIVER NR DORCHESTER 4", "id" => "DCHI4", "lat" => "43.42", "lon" => "-91.51"),
"DEHI4" => array("city" => "UPPER RIVER AT DECORAH", "id" => "DEHI4", "lat" => "43.31", "lon" => "-91.8"),
"VLPI4" => array("city" => "VOLGA RIVER AT LITTELPORT", "id" => "VLPI4", "lat" => "42.75", "lon" => "-91.37"),
"HBTI4" => array("city" => "W FK DES MOINES R AT HUMBOLT WAT", "id" => "HBTI4", "lat" => "42.72", "lon" => "-94.22"),
"VNDI4" => array("city" => "WALNUT CK NR VANDALIA", "id" => "VNDI4", "lat" => "41.54", "lon" => "-93.26"),
"DOSI4" => array("city" => "WALNUT CREEK AT DES MOINES", "id" => "DOSI4", "lat" => "41.59", "lon" => "-93.7"),
"HRTI4" => array("city" => "WALNUT CREEK NR HARTWICK 4NW", "id" => "HRTI4", "lat" => "41.84", "lon" => "-92.39"),
"PRCI4" => array("city" => "WALNUT CREEK NR PRAIRIE CITY 2W", "id" => "PRCI4", "lat" => "41.6", "lon" => "-93.3"),
"IDPI4" => array("city" => "WAPSIPINICON R AT INDEPENDENCE", "id" => "IDPI4", "lat" => "42.45", "lon" => "-91.9"),
"ANSI4" => array("city" => "WAPSIPINICON RIVER NEAR ANAMOSA", "id" => "ANSI4", "lat" => "42.08", "lon" => "-91.27"),
"TPLI4" => array("city" => "WAPSIPINICON RIVER NEAR TRIPOLI", "id" => "TPLI4", "lat" => "42.84", "lon" => "-92.26"),
"DEWI4" => array("city" => "WAPSIPINICON RIVER NR DE WITT 4S", "id" => "DEWI4", "lat" => "41.77", "lon" => "-90.53"),
"EMTI4" => array("city" => "WEST FORK DES MOINES RIVER NR EM", "id" => "EMTI4", "lat" => "43.13", "lon" => "-94.71"),
"HOKI4" => array("city" => "WEST FORK DITCH AT HORNICK", "id" => "HOKI4", "lat" => "42.23", "lon" => "-96.08"),
"HNKI4" => array("city" => "WEST NISHNABOTNA RIVER AT HANCOC", "id" => "HNKI4", "lat" => "41.39", "lon" => "-95.37"),
"RDPI4" => array("city" => "WEST NISHNABOTNA RIVER NR RANDOL", "id" => "RDPI4", "lat" => "40.87", "lon" => "-95.58"),
"OBJI4" => array("city" => "WEST OKOBOJI LAKE NR MILFORD 4NW", "id" => "OBJI4", "lat" => "43.38", "lon" => "-95.18"),
"DLLI4" => array("city" => "WHITE BREAST CREEK AT DALLAS 2NW", "id" => "DLLI4", "lat" => "41.24", "lon" => "-93.27"),
"MCWI4" => array("city" => "WINNEBAGO RVR AT MASON CITY", "id" => "MCWI4", "lat" => "43.17", "lon" => "-93.19"),
"DYSI4" => array("city" => "WOLF CREEK NEAR DYSART", "id" => "DYSI4", "lat" => "42.25", "lon" => "-92.3")
);
?>
