<?php

$lsr_types = Array(
"W" => Array("name" => "WATER SPOUT"),
"C" => Array("name" => "FUNNEL CLOUD"),
"5" => Array("name" => "ICING ON ROADS"),
"P" => Array("name" => "RIP CURRENTS"),
"G" => Array("name" => "TSTM WIND GST"),
"J" => Array("name" => "DENSE FOG"),
"O" => Array("name" => "NON-TSTM WND"),
"N" => Array("name" => "NON TSTM WND GST"),
"0" => Array("name" => "HURRICANE"),
"G" => Array("name" => "TSTM WND GST"),
"H" => Array("name" => "HAIL"),
"s" => Array("name" => "HEAVY SLEET"),
"O" => Array("name" => "HIGH WINDS"),
"W" => Array("name" => "WATERSPOUT"),
"I" => Array("name" => "EXCESSIVE HEAT"),
"s" => Array("name" => "MODERATE SLEET"),
"s" => Array("name" => "SLEET"),
"N" => Array("name" => "NON-TSTM WND GST"),
"S" => Array("name" => "HEAVY SNOW"),
"Q" => Array("name" => "TROPICAL STORM"),
"M" => Array("name" => "MARINE TSTM WIND"),
"4" => Array("name" => "HIGH ASTR TIDES"),
"D" => Array("name" => "TSTM WIND DMG"),
"V" => Array("name" => "AVALANCHE"),
"K" => Array("name" => "LIGHTNING STRIKE"),
"B" => Array("name" => "DOWNBURST"),
"8" => Array("name" => "WILDFIRE"),
"A" => Array("name" => "HIGH SUST WINDS"),
"E" => Array("name" => "FLOODING"),
"G" => Array("name" => "TSTM WIND"),
"O" => Array("name" => "NON-TSTM DMG GST"),
"5" => Array("name" => "FREEZING RAIN"),
"7" => Array("name" => "EXTR WIND CHILL"),
"3" => Array("name" => "SPRINKLES - FEW"),
"Z" => Array("name" => "BLIZZARD"),
"U" => Array("name" => "FIRE"),
"6" => Array("name" => "EXTREME COLD"),
"5" => Array("name" => "ICE STORM"),
"L" => Array("name" => "LIGHTNING"),
"E" => Array("name" => "FLOOD"),
"O" => Array("name" => "NON TSTM DMG GST"),
"O" => Array("name" => "NON-TSTM WND DMG"),
"1" => Array("name" => "STORM SURGE"),
"6" => Array("name" => "FREEZE"),
"F" => Array("name" => "FLASH FLOOD"),
"D" => Array("name" => "TSTM WND DMG"),
"O" => Array("name" => "NON-TSTM DMG"),
"G" => Array("name" => "MARINE TSTM WND"),
"S" => Array("name" => "SNOW"),
"X" => Array("name" => "WALL CLOUD"),
"O" => Array("name" => "NON TSTM WND DMG"),
"T" => Array("name" => "TORNADO"),
"O" => Array("name" => "WND DAMAGE"),
"R" => Array("name" => "HEAVY RAIN"),
"2" => Array("name" => "DUST STORM"),
"P" => Array("name" => "HIGH SURF"),
"F" => Array("name" => "MAJ FLASH FLD"),
);


?>
