<?php
/* Master list of networks the IEM Processes */
$networks = Array(
 "IA_ASOS" => Array("name" => "Iowa ASOS"),
 "AWOS" => Array("name" => "Iowa AWOS"),
 "IA_RWIS"  => Array("name" => "Iowa RWIS"),
 "IACLIMATE" => Array("name" => "Iowa Climate Sites (IEM Tracked)"),
 "DCP"  => Array("name" => "DCP (GEOS Data Collection Platforms)"),
 "ISUAG"  => Array("name" => "Iowa State AgClimate"),
 "IA_COOP"  => Array("name" => "Iowa NWS COOP Observers"),
 "IACOCORAHS"  => Array("name" => "Iowa CoCoRaHS Observers"),
 "KCCI"  => Array("name" => "KCCI SchoolNET8 Stations"),
 "KELO"  => Array("name" => "KELO WeatherNet Stations"),
 "KIMT"  => Array("name" => "KIMT StormNet Stations"),
 "IL_ASOS"  => Array("name" => "Illinios ASOS/AWOS"),
 "IL_COOP"  => Array("name" => "Illinios NWS COOP Observers"),
 "IN_COOP"  => Array("name" => "Indiana NWS COOP Observers"),
 "KS_ASOS"  => Array("name" => "Kansas ASOS/AWOS"),
 "KS_COOP"  => Array("name" => "Kansas NWS COOP Observers"),
 "KS_RWIS"  => Array("name" => "Kansas RWIS"),
 "MI_COOP"  => Array("name" => "Michigan NWS COOP Observers"),
 "MN_ASOS"  => Array("name" => "Minnesota ASOS/AWOS"),
 "MN_COOP"  => Array("name" => "Minnesota NWS COOP Observers"),
 "MN_RWIS"  => Array("name" => "Minnesota RWIS"),
 "MO_ASOS"  => Array("name" => "Missouri ASOS/AWOS"),
 "MO_COOP"  => Array("name" => "Missouri NWS COOP Observers"),
 "NE_ASOS"  => Array("name" => "Nebraska ASOS"),
 "NE_AWOS"  => Array("name" => "Nebraska AWOS"),
 "NE_COOP"  => Array("name" => "Nebraska NWS COOP Observers"),
 "NE_RWIS"  => Array("name" => "Nebraska RWIS"),
 "ND_ASOS"  => Array("name" => "North Dakota ASOS/AWOS"),
 "ND_COOP"  => Array("name" => "North Dakota NWS COOP Observers"),
 "OH_COOP"  => Array("name" => "Ohio NWS COOP Observers"),
 "SD_ASOS"  => Array("name" => "South Dakota ASOS/AWOS"),
 "SD_COOP"  => Array("name" => "South Dakota NWS COOP Observers"),
 "WI_ASOS"  => Array("name" => "Wisconsin ASOS/AWOS"),
 "WI_COOP"  => Array("name" => "Wisconsin NWS COOP Observers"),
 "WI_RWIS"  => Array("name" => "Wisconsin RWIS"),
);
?>
