<?php
        $Rcities = array(
 "RDAI4" => array("city" => "Adair (I-80)"),
 "RALI4" => array("city" => "Algona (US 18)"),
 "RTNI4" => array("city" => "Alton (IA10)"),
 "RTOI4" => array("city" => "Altoona (I-80/US 65)"),
 "RAMI4" => array("city" => "Ames (I-35)"),
 "RAKI4" => array("city" => "Ankeny (I-35)"),
 "RAVI4" => array("city" => "Avoca (I-80)"),
 "RBUI4" => array("city" => "Burlington (US 34)"),
 "RCAI4" => array("city" => "Carroll (US 30)"),
 "RCDI4" => array("city" => "Cedar Rapids (I-380)"),
 "RCII4" => array("city" => "Cedar Rapids (US 30)"),
 "RCRI4" => array("city" => "Cedar Rapids (US 30)"),
 "RCNI4" => array("city" => "Centerville (IA 2)"),
 "RCBI4" => array("city" => "Council Bluffs (I-80)"),
 "RCEI4" => array("city" => "Creston (US 34)"),
 "RDVI4" => array("city" => "Davenport (I-80/I-280)"),
 "RDCI4" => array("city" => "Decorah (IA 9)"),
 "RDMI4" => array("city" => "Des Moines (I-235)"),
 "RDSI4" => array("city" => "Des Moines (I-35)"),
 "RDEI4" => array("city" => "De Soto (I-80/US 169)"),
 "RDWI4" => array("city" => "De Witt (US 30/US 61)"),
 "RDBI4" => array("city" => "Dubuque (US 20)"),
 "RFDI4" => array("city" => "Fort Dodge (US 20)"),
 "RGRI4" => array("city" => "Grinnell (I-80)"),
 "RHAI4" => array("city" => "Hanlontown (I-35)"),
 "RIGI4" => array("city" => "Ida Grove (US 59)"),
 "RIOI4" => array("city" => "Iowa City (I-80)"),
 "RIAI4" => array("city" => "Iowa City (US 218)"),
 "RJFI4" => array("city" => "Jefferson (IA 4)"),
 "RLEI4" => array("city" => "Leon (I-35)/IA 2)"),
 "RMNI4" => array("city" => "Manchester (US 20)"),
 "RMQI4" => array("city" => "Maquoketa (US 61/IA 64)"),
 "RMTI4" => array("city" => "Marshalltown (US 30)"),
 "RMCI4" => array("city" => "Mason City (I-35)"),
 "RMVI4" => array("city" => "Missouri Valley (I-29)"),
 "RMPI4" => array("city" => "Mount Pleasant (US 218)"),
 "RNHI4" => array("city" => "New Hampton (US 18)"),
 "RONI4" => array("city" => "Onawa (I-29)"),
 "ROSI4" => array("city" => "Osceola (I-35)"),
 "ROTI4" => array("city" => "Ottumwa (US 63)"),
 "RPLI4" => array("city" => "Pella (IA 163)"),
 "RROI4" => array("city" => "Red Oak (US 34/US 71)"),
 "RSDI4" => array("city" => "Sidney (I-29/IA 2)"),
 "RSGI4" => array("city" => "Sigourney (IA 92)"),
 "RSCI4" => array("city" => "Sioux City (I-29)"),
 "RSPI4" => array("city" => "Spencer (US 18)"),
 "RSBI4" => array("city" => "Steamboat Rock (US20)"),
 "RSLI4" => array("city" => "Storm Lake (US 71/IA 3)"),
 "RTPI4" => array("city" => "Tipton (I-80)"),
 "RURI4" => array("city" => "Urbana (I-380)"),
 "RWLI4" => array("city" => "Waterloo (US 20)"),
 "RWBI4" => array("city" => "Williamsburg (I-80)"),
 "RWII4" => array("city" => "Williams (I-35)"),
 );
?>
