<?php
        $Scities = array(
"SLKS2" => array("short" => "Clear Lake", "city" => "Clear Lake, SD", "id" => "SLKS2"),
"SEKS2" => array("short" => "Elkton", "city" => "Elkton, SD", "id" => "SEKS2"),
"SALS2" => array("short" => "Alcester", "city" => "Alcester, SD", "id" => "SALS2"),
"SBAS2" => array("short" => "Baltic", "city" => "Baltic, SD", "id" => "SBAS2"),
"SBRS2" => array("short" => "Brandon", "city" => "Brandon, SD", "id" => "SBRS2"),
"SGAS2" => array("short" => "Garretson", "city" => "Garretson, SD", "id" => "SGAS2"),
"SHIM5" => array("short" => "Hills", "city" => "Hills, MN", "id" => "SHIM5"),
"SHOS2" => array("short" => "Howard", "city" => "Howard, SD", "id" => "SHOS2"),
"SRMS2" => array("short" => "Ramona", "city" => "Ramona, SD", "id" => "SRMS2"),
"SUNI4" => array("short" => "Union", "city" => "Union", "id" => "SUNI4"),
"SMDI4" => array("short" => "Madrid", "city" => "Madrid", "id" => "SMDI4"),
"SEGI4" => array("short" => "Eagle Grove", "city" => "Eagle Grove", "id" => "SEGI4"),
"SATI4" => array("short" => "Anita", "city" => "Anita", "id" => "SATI4"),
"SLUI4" => array("short" => "LuVerne", "city" => "LuVerne", "id" => "SLUI4"),
"SOGI4" => array("short" => "Ogden", "city" => "Ogden", "id" => "SOGI4"),
"SJCI4" => array("short" => "Jordan Creek WDM", "city" => "Jordan Creek WDM", "id" => "SJCI4"),
"SCEI4" => array("short" => "Centerville", "city" => "Centerville", "id" => "SCEI4"),
"SOCI4" => array("short" => "Oskaloosa", "city" => "Oskaloosa", "id" => "SOCI4"),
"SPKI4" => array("short" => "Polk City", "city" => "Polk City", "id" => "SPKI4"),
"MTYS2" => array("short" => "Marty", "city" => "Marty, SD", "id" => "MTYS2"),
"FSNS2" => array("short" => "Flandreau", "city" => "Flandreau, SD", "id" => "FSNI4"),
"SBZI4" => array("short" => "Blank Park Zoo", "city" => "Blank Park Zoo, DSM", "id" => "SBZI4"),
"SFDI4" => array("short" => "Fort Dodge", "city" => "Fort Dodge", "id" => "SFDI4"),
"SAGI4" => array("short" => "Algona", "city" => "Algona, IA", "id" => "SAGI4"),
"GETS2" => array("short" => "Gettysburg", "city" => "Gettysburg, SD", "id" => "GETS2"),
"LDSS2" => array("short" => "Lead", "city" => "Lead, SD", "id" => "LDSS2"),
"SBMI4" => array("short" => "Bloomfield", "city" => "Bloomfield, IA", "id" => "SBMI4"),
"SDNI4" => array("short" => "Sheldon", "city" => "Sheldon, IA", "id" => "SDNI4"),
"EPJS2" => array("short" => "Elk Point", "city" => "Elk Point, SD", "id" => "EPJS2"),
"ESDS2" => array("short" => "Eureka", "city" => "Eureka, SD", "id" => "ESDS2"),
"KKAS2" => array("short" => "Kadoka", "city" => "Kadoka, SD", "id" => "KKAS2"),
"SMUI4" => array("short" => "Murray", "city" => "Murray", "id" => "SMUI4"),
"CCES2" => array("short" => "Ft Thompson", "city" => "Crow Creek Elem _ Ft Thompson, SD", "id" => "CCES2"),
"RDPS2" => array("short" => "Redfield", "city" => "Redfield, SD", "id" => "RDPS2"),
"MLES2" => array("short" => "Miller", "city" => "Miller, SD", "id" => "MLES2"),
"CLYI4" => array("short" => "Rock Rapids", "city" => "Rock Rapids, IA _ Central Lyon MS", "id" => "CLYI4"),
"RRCM5" => array("short" => "Lamberton", "city" => "Lamberton, MN _ Red Rock Central", "id" => "RRCM5"),
"MTMS2" => array("short" => "Mitchell", "city" => "Mitchell, SD _ Mitchell Elem", "id" => "MTMS2"),
"PESS2" => array("short" => "Parkston", "city" => "Parkston, SD _ Parkston MS", "id" => "PESS2"),
"ICSI4" => array("short" => "Inwood", "city" => "Inwood, IA _ ICS", "id" => "ICSI4"),
"BHHS2" => array("short" => "Britton", "city" => "Britton, SD _ Britton/Hecla HS", "id" => "BHHS2"),
"BKGS2" => array("short" => "Brookings", "city" => "Brookings, SD _ Mickelson MS", "id" => "BKGS2"),
 "CHAS2" => array("short" => "Chamberlain", "city" => "Chamberlain, SD _ St Joe IS", "id" => "CHAS2"),
 "LMSM5" => array("short" => "Luverne", "city" => "Luverne, MN _ Luverne MS", "id" => "LMSM5"),
 "MMSS2" => array("short" => "Madison", "city" => "Madison, SD _ Madison MS", "id" => "MMSS2"),
 "MOBS2" => array("short" => "Mobridge", "city" => "Mobridge, SD _ Mobridge MS", "id" => "MOBS2"),
 "CLTS2" => array("short" => "Colton", "city" => "Colton, SD _ Tri-Valley", "id" => "CLTS2"),
 "WHSS2" => array("short" => "Winner", "city" => "Winner, SD _ Winner HS", "id" => "WHSS2"),
 "WMSM5" => array("short" => "Worthington", "city" => "Worthington, MN _ Worthington MS", "id" => "WMSM5"),
"SADI4" => array("short" => "Adair Casey", "city" => "Adair Casey", "id" =>  "SADI4"),
"SAEI4" => array("short" => "Adel MS", "city" => "Adel _ ADM MS", "id" =>  "SAEI4"),
"SAFI4" => array("short" => "East Union Afton", "city" => "Afton _ East Union", "id" =>  "SAFI4"),
"SALI4" => array("short" => "Albia", "city" => "Albia Lincoln Center", "id" => "SALI4"),
"SAMI4" => array("short" => "Ames", "city" => "Ames _ Northwood Elem", "id" => "SAMI4"),
"SAKI4" => array("short" => "Ankeny", "city" => "Ankeny _ Christian Academy", "id" =>  "SAKI4"),
"SAUI4" => array("short" => "Audubon", "city" => "Audubon Community", "id" =>  "SAUI4"),
"SCBI4" => array("short" => "Coon Rapids", "city" => "Coon Rapids _ Bayard", "id" =>  "SCBI4"),
"SBDI4" => array("short" => "Bedford", "city" => "Bedford", "id" =>  "SBDI4"),
"SBKI4" => array("short" => "Belmond", "city" => "Belmond Klemme", "id" =>  "SBKI4"),
"SBOI4" => array("short" => "Boone", "city" => "Boone _ United Community", "id" =>  "SBOI4"),
"SBRI4" => array("short" => "Brooklyn BGM", "city" => "Brooklyn _ BGM", "id" => "SBRI4"),
"SCAI4" => array("short" => "Carroll", "city" => "Carroll _ Kuemper Catholic", "id" =>  "SCAI4"),
"SCHI4" => array("short" => "Chariton", "city" => "Chariton _ Van Allen Elem", "id" =>  "SCHI4"),
"SCGI4" => array("short" => "Clarion", "city" => "Clarion _ Clarion Goldfield", "id" =>  "SCGI4"),
"SCOI4" => array("short" => "Colo Elem", "city" => "Colo Elem", "id" =>  "SCOI4"),
"SCNI4" => array("short" => "Corning", "city" => "Corning Community", "id" => "SCNI4"),
"SCDI4" => array("short" => "Corydon", "city" => "Wayne Community _ Corydon", "id" => "SCDI4"),
"SCSI4" => array("short" => "Creston", "city" => "Creston HS", "id" =>  "SCSI4"),
"SKCI4" => array("short" => "KCCI Studios", "city" => "Des Moines _ KCCI Studios", "id" =>  "SKCI4"),
"SDRI4" => array("short" => "River Woods DSM", "city" => "Des Moines _ River Woods", "id" =>  "SDRI4"),
"SFAI4" => array("short" => "Farnhamville", "city" => "Farnhamville _ PRairie Valley", "id" =>  "SFAI4"),
"SFOI4" => array("short" => "Fontanelle", "city" => "Fontanelle _ Nodaway Valley", "id" =>  "SFOI4"),
"SGLI4" => array("short" => "Glidden", "city" => "Glidden Ralston", "id" =>  "SGLI4"),
"SGRI4" => array("short" => "Grimes", "city" => "Grimes Elementary", "id" =>  "SGRI4"),
"SHUI4" => array("short" => "Humboldt", "city" => "Humboldt _ Taft Elem", "id" =>  "SHUI4"),
"SIAI4" => array("short" => "Iowa Christian", "city" => "Iowa Christian", "id" =>  "SIAI4"),
"S03I4" => array("short" => "State Fair", "city" => "Iowa State Fair", "id" =>  "S03I4"),
"SINI4" => array("short" => "Indianola", "city" => "Indianola _ Emerson Elem", "id" =>  "SINI4"),
"SIFI4" => array("short" => "Iowa Falls", "city" => "Iowa Falls _ Rock Run Elem", "id" => "SIFI4"),
"SJEI4" => array("short" => "Jefferson", "city" => "Jefferson Scranton HS", "id" =>  "SJEI4"),
"SJWI4" => array("short" => "South Hamilton", "city" => "Jewell _ South Hamilton", "id" => "SJWI4"),
"SKNI4" => array("short" => "Knoxville", "city" => "Knoxville _ West Elem", "id" =>  "SKNI4"),
"SLOI4" => array("short" => "Lamoni", "city" => "Lamoni Community ", "id" =>  "SLOI4"),
"SLMI4" => array("short" => "Latimer", "city" => "Latimer _ CAL Community", "id" =>  "SLMI4"),
"SLEI4" => array("short" => "Leon", "city" => "Leon", "id" =>  "SLEI4"),
"SMLI4" => array("short" => "Mallard", "city" => "Mallard", "id" => "SMLI4"),
"SMAI4" => array("short" => "M'town", "city" => "Marshalltown _ Fisher Elem", "id" =>  "SMAI4"),
"SMOI4" => array("short" => "Mount Ayr", "city" => "Mount Ayr Community", "id" =>  "SMOI4"),
"SMNI4" => array("short" => "Montezuma", "city" => "Montezuma Community", "id" =>  "SMNI4"),
"SMSI4" => array("short" => "Manson NW Webster", "city" => "Manson NW Webster", "id" =>  "SMSI4"),
"SNVI4" => array("short" => "Nevada", "city" => "Nevada Community", "id" =>  "SNVI4"),
"SNEI4" => array("short" => "Newton", "city" => "Newton _ Berg MS", "id" =>  "SNEI4"),
"SOSI4" => array("short" => "Osceola", "city" => "Osceola _ Clarke Community", "id" =>  "SOSI4"),
"SPAI4" => array("short" => "Panora", "city" => "Panora _ Panorama", "id" =>  "SPAI4"),
"SPEI4" => array("short" => "Pella MS", "city" => "Pella MS", "id" =>  "SPEI4"),
"SPYI4" => array("short" => "Perry", "city" => "Perry", "id" =>  "SPYI4"),
"STQI4" => array("short" => "Tama", "city" => "Tama", "id" =>  "STQI4"),
"SROI4" => array("short" => "Rockwell City", "city" => "Rockwell City", "id" =>  "SROI4"),
"SSUI4" => array("short" => "Sully Christian", "city" => "Sully Christian", "id" =>  "SSUI4"),
"SWAI4" => array("short" => "Wall Lake", "city" => "Wall Lake-View-Auburn", "id" => "SWAI4"),
"SWBI4" => array("short" => "Webster City", "city" => "Webster City Community", "id" =>  "SWBI4"),
"SWII4" => array("short" => "Winterset", "city" => "Winterset Community", "id" =>  "SWII4"),
'SPIS2' => array("short" => "Pierre, SD", "city" => "Pierre, SD", "id" =>  "SPIS2"),
'SWAS2' => array("short" => "Wall, SD", "city" => "Wall, SD", "id" =>  "SWAS2"),  
'SRAS2' => array("short" => "Rapid City, SD", "city" => "Rapid City, SD", "id" =>  "SRAS2"),
'SABS2' => array("short" => "Aberdeen, SD", "city" => "Aberdeen, SD", "id" =>  "SABS2"),  
'SWTS2' => array("short" => "Watertown, SD", "city" => "Watertown, SD", "id" =>  "SWTS2"), 
'SMIS2' => array("short" => "Milbank, SD", "city" => "Milbank, SD", "id" =>  "SMIS2"),
'SRUM5' => array("short" => "Russell, MN", "city" => "Russell, MN", "id" =>  "SRUM5"),  
'SMAM5' => array("short" => "Madison, MN", "city" => "Madison, MN", "id" =>  "SMAM5"),  
'SSAS2' => array("short" => "Sioux Falls PH, SD", "city" => "Sioux Falls PH, SD", "id" =>  "SSAS2"),
'SSBS2' => array("short" => "Sioux Falls Pav, SD", "city" => "Sioux Falls Pav, SD", "id" =>  "SSBS2"), 
'SMSS2' => array("short" => "Mission, SD", "city" => "Mission, SD", "id" =>  "SMSS2"),  
'SHUS2' => array("short" => "Huron, SD", "city" => "Huron, SD", "id" =>  "SHUS2"),
'SYAS2' => array("short" => "Yankton, SD", "city" => "Yankton, SD", "id" =>  "SYAS2"), 
'SHII4' => array("short" => "Hull, IA", "city" => "Hull, IA", "id" =>  "SHII4"),

"SBLM5" => array("short" => "Albert Lea","city" => "Albert Lea", "id" => "SBLM5", "lat" => "43.6431", "lon" => "-93.3919", "network" => "KIMT", "county" => "Freeborn", "climate_site" => "none"),
"SASM5" => array("short" => "Austin","city" => "Austin", "id" => "SASM5", "lat" => "43.6623", "lon" => "-92.9522", "network" => "KIMT", "county" => "Mower", "climate_site" => "none"),
"SCCI4" => array("short" => "Charles City","city" => "Charles City", "id" => "SCCI4", "lat" => "43.068", "lon" => "-92.6722", "network" => "KIMT", "county" => "Floyd", "climate_site" => "ia1402"),
"SCKI4" => array("short" => "Clear Lake","city" => "Clear Lake", "id" => "SCKI4", "lat" => "43.1399", "lon" => "-93.3683", "network" => "KIMT", "county" => "Cerro Gordo", "climate_site" => "ia5235"),
"SCQI4" => array("short" => "Cresco","city" => "Cresco", "id" => "SCQI4", "lat" => "43.3761", "lon" => "-92.1031", "network" => "KIMT", "county" => "Howard", "climate_site" => "ia1954"),
"SFCI4" => array("short" => "Forest City","city" => "Forest City", "id" => "SFCI4", "lat" => "43.2657", "lon" => "-93.6491", "network" => "KIMT", "county" => "Winnebago", "climate_site" => "ia2977"),
"SKWI4" => array("short" => "Kanawha","city" => "Kanawha", "id" => "SKWI4", "lat" => "42.93682", "lon" => "-93.78675", "network" => "KIMT", "county" => "Hancock", "climate_site" => "ia4308"),
"SLEM5" => array("short" => "LeRoy","city" => "LeRoy", "id" => "SLEM5", "lat" => "43.5131", "lon" => "-92.5095", "network" => "KIMT", "county" => "Mower", "climate_site" => "none"),
"SMYI4" => array("short" => "Mason City","city" => "Mason City", "id" => "SMYI4", "lat" => "43.1506", "lon" => "-93.1691", "network" => "KIMT", "county" => "Cerro Gordo", "climate_site" => "ia5230"),
"SOAI4" => array("short" => "Osage","city" => "Osage", "id" => "SOAI4", "lat" => "43.277", "lon" => "-92.8102", "network" => "KIMT", "county" => "Mitchell", "climate_site" => "ia6305"),

);

$Sconv = array(
68 => 'SCSI4',
38 => 'SINI4',
39 => 'SGRI4',
40 => 'SFOI4',
41 => 'SOSI4',
42 => 'SWII4',
44 => 'SAFI4',
37 => 'SJEI4',
43 => 'SADI4',
56 => 'SNEI4',
55 => 'SBOI4',
54 => 'SMAI4',
58 => 'SPAI4',
52 => 'SPEI4',
57 => 'SAKI4',
62 => 'SCAI4',
61 => 'SROI4',
63 => 'SGLI4',
59 => 'SHUI4',
60 => 'SDRI4',
51 => 'SAEI4',
53 => 'SCHI4',
50 => 'SCGI4',
67 => 'SCOI4',
70 => 'SLMI4',
47 => 'SKCI4',
73 => 'SCBI4',
72 => 'SAUI4',
69 => 'SWBI4',
81 => 'SKNI4',
80 => 'SSUI4',
76 => 'SMOI4',
74 => 'SMNI4',
84 => 'SFAI4',
77 => 'SIFI4',
85 => 'SJWI4',
79 => 'SCNI4',
82 => 'SAMI4',
75 => 'SLOI4',
78 => 'SMLI4',
83 => 'SALI4',
71 => 'SWAI4',
86 => 'SBRI4',
92 => 'SBKI4',
94 => 'SLEI4',
91 => 'SPYI4',
109 => 'SMSI4',
93 => 'SIAI4',
121=> 'SNVI4',
125=> 'SCDI4',
123=> 'SBDI4',
899=> 'S03I4',
122 => 'SMUI4',
124 => 'SBMI4',
128 => 'SAGI4',
149 => 'SFDI4',
133 => 'SBZI4',
151 => 'SPKI4',
129 => 'SOCI4',
150 => 'SCEI4',
155 => 'SJCI4',
 90 => 'SOGI4',
148 => 'SATI4',
147 => 'SLUI4',
171 => 'SEGI4',
170 => 'SMDI4',
172 => 'SUNI4',
173 => 'STQI4',
 1 => 'SPIS2', 
49 => 'SWAS2',  
 9 => 'SRAS2',
 4 => 'SABS2',  
 5 => 'SWTS2', 
11 => 'SMIS2',
 7 => 'SRUM5',  
 8 => 'SMAM5',  
 0 => 'SSAS2',
15 => 'SSBS2', 
13 => 'SMSS2',  
 3 => 'SHUS2',
 6 => 'SYAS2', 
25 => 'SHII4',
903 => 'BKGS2',
900 => 'CHAS2',
906 => 'LMSM5',
911 => 'MMSS2',
920 => 'MOBS2',
904 => 'CLTS2',
921 => 'WHSS2',
907 => 'WMSM5',
916 => 'BHHS2',
918 => 'ICSI4',
910 => 'MTMS2',
917 => 'PESS2',
902 => 'RRCM5',
901 => 'CLYI4',
912 => 'MLES2',
922 => 'RDPS2',
919 => 'CCES2',
913 => 'KKAS2',
924 => 'ESDS2',
909 => 'EPJS2',
908 => 'SDNI4',
914 => 'LDSS2',
923 => 'GETS2',
905 => 'FSNS2',
915 => 'MTYS2',
500 => 'SALS2',
501 => 'SBAS2',
502 => 'SBRS2',
503 => 'SGAS2',
504 => 'SHIM5',
505 => 'SHOS2',
506 => 'SRMS2',
508 => 'SLKS2',
509 => 'SEKS2');

$SconvBack = array(
"SCSI4" => '68',
"SINI4" => '38',
"SGRI4" => '39',
"SFOI4" => '40',
"SOSI4" => '41',
"SWII4" => '42',
"SAFI4" => '44',
"SJEI4" => '37',
"SADI4" => '43',
"SNEI4" => '56',
"SBOI4" => '55',
"SMAI4" => '54',
"SPAI4" => '58',
"SPEI4" => '52',
"SAKI4" => '57',
"SCAI4" => '62',
"SROI4" => '61',
"SGLI4" => '63',
"SHUI4" => '59',
"SDRI4" => '60',
"SAEI4" => '51',
"SCHI4" => '53',
"SCGI4" => '50',
"SCOI4" => '67',
"SLMI4" => '70',
"SKCI4" => '47',
"SCBI4" => '73',
"SAUI4" => '72',
"SWBI4" => '69',
"SKNI4" => '81',
"SSUI4" => '80',
"SMOI4" => '76',
"SMNI4" => '74',
"SFAI4" => '84',
"SIFI4" => '77',
"SJWI4" => '85',
"SCNI4" => '79',
"SAMI4" => '82',
"SLOI4" => '75',
"SMLI4" => '78',
"SALI4" => '83',
"SWAI4" => '71',
"SBRI4" => '86',
"SBKI4" => '92',
"SLEI4" => '94',
'SPYI4' => '91',
'SMSI4' => '109',
'SIAI4' => '93',
'SNVI4' => '121',
'SCDI4' => '125',
'SBDI4' => '123',
'S03I4' => '899',
'SMUI4' => '122',
'SBMI4' => '124',
'SAGI4' => '128',
'SFDI4' => '149',
'SBZI4' => '133',
'SPKI4' => '151',
'SOCI4' => '129',
'SCEI4' => '150',
'SJCI4' => '155',
'SOGI4' => '90',
'SATI4' => '148',
'SLUI4' => '147',
'SEGI4' => '171',
'SMDI4' => '170',
'SUNI4' => '172',
'STQI4' => '173',
'SPIS2'=>  '1',
'SWAS2'=> '49',  
'SRAS2'=>  '9',
'SABS2'=>  '4',  
'SWTS2'=>  '5', 
'SMIS2'=> '11',
'SRUM5'=>  '7',  
'SMAM5'=>  '8',  
'SSAS2'=>  '0',
'SSBS2'=> '15', 
'SMSS2'=> '13',  
'SHUS2'=>  '3',
'SYAS2'=>  '6', 
'SHII4'=> '25',
'BKGS2'=> '903',
'CHAS2'=> '900',
'LMSM5'=> '906',
'MMSS2'=> '911',
'MOBS2'=> '920',
'CLTS2'=> '904',
'WHSS2'=> '921',
'WMSM5'=> '907',
'BHHS2'=> '916',
'ICSI4'=> '918',
'MTMS2'=> '910',
'PESS2'=> '917',
'RRCM5'=> '902',
'CLYI4'=> '901',
'MLES2'=> '912',
'RDPS2'=> '922',
'CCES2'=> '919',
'KKAS2'=> '913',
'ESDS2'=> '924',
'EPJS2'=> '909',
'SDNI4'=> '908',
'LDSS2'=> '914',
'GETS2'=> '923',
'FSNS2'=> '905',
'MTYS2'=> '915',
'SALS2'=> '500',
'SBAS2'=> '501',
'SBRS2'=> '502',
'SGAS2'=> '503',
'SHIM5'=> '504',
'SHOS2'=> '505',
'SRMS2'=> '506',
'SLKS2'=> '508',
'SEKS2'=> '509',
'SCKI4'=> 602,
'SCCI4'=> 603,
'SOAI4'=> 605,
'SFCI4'=> 606,
'SASM5'=> 607,
'SCQI4'=> 608,
'SLEM5'=> 609,
'SMYI4'=> 610,
'SKWI4'=> 604,
'SBLM5'=> 611);
?>
