<?php
$vtec_phenomea = Array(
  'BZ' => 'Blizzard',
  'WS' => 'Winter Storm',
  'WW' => 'Winter Weather',
  'SN' => 'Snow',
  'HS' => 'Heavy Snow',
  'LE' => 'Lake Effect Snow',
  'BS' => 'Blowing Snow',
  'SB' => 'Snow and Blowing Snow',
  'LB' => 'Lake Effect Snow and Blowing Snow',
  'HP' => 'Heavy Sleet',
  'ZR' => 'Freezing Rain',
  'IS' => 'Ice Storm',
  'FZ' => 'Freeze',
  'FR' => 'Frost',
  'ZF' => 'Freezing Fog',
  'WC' => 'Wind Chill',
  'EC' => 'Extreme Cold',
  'WI' => 'Wind',
  'HW' => 'High Wind',
  'LW' => 'Lake Wind',
  'FG' => 'Dense Fog',
  'SM' => 'Dense Smoke',
  'HT' => 'Heat',
  'EH' => 'Excessive Heat',
  'DU' => 'Blowing Dust',
  'DS' => 'Dust Storm',
  'FL' => 'Flood',
  'FF' => 'Flash Flood',
  'SV' => 'Severe Thunderstorm',
  'TO' => 'Tornado',
  'FW' => 'Fire Weather',
  'RH' => 'Radiological Hazard',
  'VO' => 'Volcano',
  'AF' => 'Volcanic Ashfall',
  'AS' => 'Air Stagnation',
  'AV' => 'Avalanche',
  'TS' => 'Tsunami',
  'MA' => 'Marine',
  'SC' => 'Small Craft',
  'GL' => 'Gale',
  'SR' => 'Storm',
  'HF' => 'Hurricane Force Wind',
  'SR' => 'Storm',
  'HF' => 'Hurricane Force Wind',
  'TR' => 'Tropical Storm',
  'HU' => 'Hurricane',
  'TY' => 'Typhoon',
  'TI' => 'Inland Tropical Storm Wind',
  'HI' => 'Inland Hurricane Wind',
  'LS' => 'Lakeshore Flood',
  'CF' => 'Coastal Flood',
  'UP' => 'Ice Accretion',
  'LO' => 'Low Water',
  'SU' => 'High Surf');

$vtec_significance = Array(
 'W' => 'Warning',
 'Y' => 'Advisory',
 'A' => 'Watch',
 'S' => 'Statement');

$vtec_status Array(
 'NEW'=> 'issues',
 'CON'=> 'continues',
 'EXA'=> 'extends area of',
 'EXT'=> 'extends time of',
 'EXB'=> 'extends area+time of',
 'UPG'=> 'issues upgrade to',
 'CAN'=> 'cancels',
 'EXP'=> 'expires',
 'ROU'=> 'routine',
 'COR'=> 'corrects');


?>
