<?php




$map = ms_newMapObj("iawarn_beta.map");

$counties = $map->getlayerbyname("iowa_counties");
$counties->set("status", MS_ON);

$c0 = $map->getlayerbyname("warnings0_c");
$c0->set("status", 1);
$c0->setFilter("(expire > CURRENT_TIMESTAMP and gtype = 'C')");


$st_cl = $counties->getClass(0);
$st_cl->setExpression("'".$fips."'");

$img = $map->prepareImage();
$counties->draw($img);
$c0->draw($img);


$url = $img->saveWebImage(MS_PNG, 0,0,-1);

?>
<img src="<?php echo $url; ?>">
