<html>
<head>
  <title>IEM GIS | RADAR & NWS Warnings</title>
</head>
<body bgcolor="white">
<?php

include('../../../include/mlib.php');
include('../../../include/currentOb.php');
include('../../../include/allLoc.php');

// DMX is Iowa North!
// FSD is Minnesota South! +2 W
// MPX is Minnesota South! 
// ARX is Minnesota South! 
// DVN is Illinois West!
// OAX is Iowa South! +2 W
// EAX is Iowa South
$extents = Array("DMX" => Array(1270178, 863000, 1755341, 1276783),
  "FSD" => Array(540178, -34000, 800341, 450783),
  "ARX" => Array(760178, -30000, 900341, 450783),
  "DVN" => Array(450000, 350000, 800341, 800783),
  "OAX" => Array(220000, -42000, 630000, 400000),
  "EAX" => Array(650000, 174000, 850000, 590000),
  "MPX" => Array(640178, 50000, 900341, 500783)
);

$projs = Array("DMX" => "proj=lcc,lat_1=42.0666,lat_2=43.2666,lat_0=41.5,lon_0=-93.5,x_0=1500000,y_0=1000000",
  "FSD" => "proj=lcc,lat_1=43.78,lat_2=45.21,lat_0=43,lon_0=-96,x_0=800000,y_0=100000",
  "ARX" => "proj=lcc,lat_1=43.78,lat_2=45.21,lat_0=43,lon_0=-92,x_0=800000,y_0=100000",
  "OAX" => "proj=lcc,lat_1=40.61,lat_2=41.78,lat_0=40,lon_0=-95.5,x_0=500000,y_0=0",
  "DVN" => "proj=tmerc,lat_0=36.666,lon_0=-90.16,k=0.9999,x_0=700000,y_0=0",
  "EAX" => "proj=tmerc,lat_0=36.166,lon_0=-94.5,k=0.9999,x_0=850000,y_0=0",
  "MPX" => "proj=lcc,lat_1=43.78,lat_2=45.21,lat_0=43,lon_0=-94,x_0=800000,y_0=100000"
);
?>

<table>
<tr><td>

<table>
<tr>
  <th colspan=2>Select RADAR:</th>
</tr>

<tr>
  <td><a href="iawarn.php?site=FSD">FSD - Sioux Falls</a></td>
  <td><a href="iawarn.php?site=FSD&loop=yes">(Loop)</a></td>
</tr>
<tr>
  <td><a href="iawarn.php?site=MPX">MPX - Minneapolis</a></td>
  <td><a href="iawarn.php?site=MPX&loop=yes">(Loop)</a></td>
</tr>
<tr>
  <td><a href="iawarn.php?site=ARX">ARX - LaCrosse</a></td>
  <td><a href="iawarn.php?site=ARX&loop=yes">(Loop)</a></td>
</tr>
<tr>
  <td><a href="iawarn.php?site=DVN">DVN - Davenport</a></td>
  <td><a href="iawarn.php?site=DVN&loop=yes">(Loop)</a></td>
</tr>
<tr>
  <td><a href="iawarn.php?site=EAX">EAX - Pleasant Hill</a></td>
  <td><a href="iawarn.php?site=EAX&loop=yes">(Loop)</a></td>
</tr>
<tr>
  <td><a href="iawarn.php?site=OAX">OAX - Omaha</a></td>
  <td><a href="iawarn.php?site=OAX&loop=yes">(Loop)</a></td>
</tr>
<tr>
  <td><a href="iawarn.php?site=DMX">DMX - Des Moines</a></td>
  <td><a href="iawarn.php?site=DMX&loop=yes">(Loop)</a></td>
</tr>

</table>
</td><td>
<?php

$radTimes = Array();
$fcontents = file('/mesonet/data/gis/'.$site.'.log');
while (list ($line_num, $line) = each ($fcontents)) {
  $radTimes[$line_num] = $line;
}

if (strlen($loop) > 0){

  $urls = Array();

  for ($i=0;$i<8;$i++){
   $imgi = 8 - $i;
   $radValid = $radTimes[$i];
   $radValid = substr($radValid, 0, -1);
   include("iawarn2.php");
   $urls[$i] = $url;
  }

  include ("loop.php");
  array_reverse($urls);
  printHTML($urls);
} else {
  $radValid = $radTimes[8];
  $imgi = 0;
  include("iawarn2.php");
  echo "<img src=\"". $url ."\">\n";

}

echo "</td></tr>\n</table>\n";


$fcontents = file('/mesonet/data/gis/'.$site.'.log');
while (list ($line_num, $line) = each ($fcontents)) {
  $lastT = $line;
}

echo "<br><b>RADAR is valid at:</b> ". $lastT;

echo "<hr>\n";

$connection = pg_connect("host=mesonet.agron.iastate.edu port=5432 dbname=postgis user=mesonet");

$query = "SELECT w.type, w.oid, u.name as cname, w.expire, w.issue, s.state_name as sname 
  from warnings w, uscounties u, states s
  WHERE w.expire > '".$db_ts."' and w.issue < '". $db_ts ."' 
   and w.gtype = 'C' and w.fips = u.fips 
  and u.state_fips = s.state_fips";

$result = pg_exec($connection, $query);

pg_close($connection);

echo "<table>\n";

for( $i=0; $row = @pg_fetch_array($result,$i); $i++) {

  echo "<tr> <td>". $row["type"] ."</td> 
    <td>". $row["cname"] .", ". $row["sname"] ."</td>
    <td>". $row["issue"] ."</td>
    <td>". $row["expire"] ."</td>
    </tr>\n";

}

echo "</table>\n";

?>
