<?php 
include("../../../config/settings.inc.php");
define("IEM_APPID", 73);
$TITLE = "IEM | ASOS 1 Minute Data Download";
$THISPAGE = "networks-asos";
include("$rootpath/include/header.php"); 
include("$rootpath/include/iemprop.php");
$asos_archive_end = strtotime( get_iemprop("asos.1min.end") );
$bogus = 0;
include("$rootpath/include/imagemaps.php"); 
include("$rootpath/include/forms.php");
?>

<div class="text">

<h3>Download ASOS 1 minute interval data</h3>

<p>Each month, the National Climatic Data Center provides an archive of one 
minute interval data from the ASOS sites in the United States.  Unfortunately, 
the data format of this information is brutal to work with.  Fortunately for 
you, the IEM processes this information and provides it for download here. The
archive is complete till:
<strong><?php echo date('d M Y', $asos_archive_end); ?></strong>.  There is
a different interface to download the <a href="../download.phtml">routine hourly</a>
observations from this network and for sites over the entire globe.</p>

<form method="GET" action="1min_dl.php" name="dl">

<table>
<tr><td width="50%">

<p><h3 class="subtitle">1. Select Station:</h3><br>
<i>Select One or More or All stations in the network.</i><br>
<div class="story">
  <?php echo networkMultiSelect("IA_ASOS", "", Array("FSD","MLI","OMA") ); ?>
</div>

<h3 class="subtitle">2. Timezone of Observations:</h3>
<i>The timestamps used in the downloaded files will be set in the
timezone you specify.</i>
<SELECT name="tz">
	<option value="UTC">GMT (UTC) timestamps</option>
	<option value="CST6CDT">Central Standard/Daylight Time</option>
</SELECT>

<p><h3 class="subtitle">3. Select Start/End Time:</h3><br>
<i>If you select "Central Standard/Daylight Time" in #2 above, then these
times you select for start and end time will be in CST/CDT as well. Otherwise,
the default is UTC.</i>
<table>
  <tr>
    <td></td>
    <th>Year</th><th>Month</th><th>Day</th>
    <th>Hour</th><th>Minute</th>
  </tr>

  <tr>
    <th>Start:</th>
    <td>
     <?php echo yearSelect2(2000, date("Y"), "year1"); ?>
    </td>
    <td>
     <?php echo monthSelect($bogus, "month1"); ?>
    </td>
    <td>
     <?php echo daySelect2($bogus, "day1"); ?>
    </td>
    <td>
     <?php echo gmtHourSelect($bogus, "hour1"); ?>
    </td>
    <td>
     <?php echo minuteSelect($bogus, "minute1"); ?>
    </td>
  </tr>

  <tr>
    <th>End:</th>
    <td>
     <?php echo yearSelect2(2000, date("Y"), "year2"); ?>
    </td>
    <td>
     <?php echo monthSelect($bogus, "month2"); ?>
    </td>
    <td>
     <?php echo daySelect2($bogus, "day2"); ?>
    </td>
    <td>
     <?php echo gmtHourSelect($bogus, "hour2"); ?>
    </td>
    <td>
     <?php echo minuteSelect($bogus, "minute2"); ?>
    </td>
  </tr>
</table>

<p><h3 class="subtitle">4. Select Variables:</h3><br>
<select size=5 name="vars[]" MULTIPLE>
  <option value="tmpf">Air Temperature [F]
  <option value="dwpf">Dew Point Temperature [F]
  <option value="sknt">Wind Speed [knots]
  <option value="drct">Wind Direction
  <option value="gust_drct">5 sec gust Wind Direction
  <option value="gust_sknt">5 sec gust Wind Speed [knots]
  <option value="vis1_coeff">Visibility 1 Coefficient
  <option value="vis1_nd">Visibility 1 Night/Day
  <option value="vis2_coeff">Visibility 2 Coefficient
  <option value="vis2_nd">Visibility 2 Night/Day
  <option value="ptype">Precip Type Code
  <option value="precip">1 minute precip [inches]
  <option value="pres1">Sensor 1 Station Pressure [inches]
  <option value="pres2">Sensor 2 Station Pressure [inches]
  <option value="pres3">Sensor 3 Station Pressure [inches]
</select>

</td><td valign="TOP">

<p><h3 class="subtitle">5. Data Sampling?</h3><br>
<i>Data is potentially available every minute, but you don't have to download
it at that frequency. This setting <b>does not bin</b> the values, but rather
filters based on your interval of choice.</i>
  <select name="sample">
    <option value="1min">Every Minute
    <option value="5min">Every 5 Minutes
    <option value="10min">Every 10 Minutes
    <option value="20min">Every 20 Minutes
    <option value="1hour">Every Hour
  </select>

<p><h3 class="subtitle">6. How to view?</h3><br>
<select name="what">
  <option value="download">Download to Disk
  <option value="view">View on-line
  <option value="plot">Plot in Chart
</select>

<p><h3 class="subtitle">7. Data Delimitation:</h3><br>
How shall the output values be seperated?
<br><select name="delim">
    <option value="comma">Comma
    <option value="space">Space
    <option value="tab">Tab
   </select>

<p>
<h3 class="subtitle">8. Include Station Latitude & Longitude values?</h3><img src="/images/gisready.png"><br>
<div class="story">
 <select name="gis">
   <option value="no">No
   <option value="yes">Yes
 </select>
</div>

</td></tr></table>

<p><h3 class="subtitle">Submit Form:</h3><br>
<input type="submit" value="Process Data Request">
<input type="reset">
</form>
</div>

<?php include("$rootpath/include/footer.php"); ?>
