<?php
require_once "../../../config/settings.inc.php";
define("IEM_APPID", 155);
require_once "../../../include/myview.php";
require_once "../../../include/database.inc.php";
require_once "../../../include/imagemaps.php";
require_once "../../../include/forms.php";

$mesosite = iemdb('mesosite');

$t = new MyView();
$t->iemss = True;
$t->title = "Download Hourly Precipitation Data";

$network = isset($_REQUEST["network"]) ? xssafe($_REQUEST["network"]) : "IA_ASOS";

$nselect = "<select name=\"network\">";
$rs = pg_query(
    $mesosite,
    "SELECT id, name from networks WHERE id ~* 'ASOS' and " .
        "length(id) = 7 ORDER by name ASC"
);
for ($i = 0; $row = pg_fetch_assoc($rs); $i++) {
    $sel = '';
    if ($network == $row["id"]) {
        $sel = " selected='SELECTED'";
    }
    $nselect .= sprintf(
        "<option value='%s'%s>%s</option>\n",
        $row["id"],
        $sel,
        $row["name"]
    );
}
$nselect .= "</select>";

$y1 = yearSelect2(1941, date("Y"), "year1");
$m1 = monthSelect("", "month1");
$d1 = daySelect2("", "day1");
$y2 = yearSelect2(1941, date("Y"), "year2");
$m2 = monthSelect(date("m"), "month2");
$d2 = daySelect2(date("d"), "day2");

$ar = array(
    "Etc/UTC" => "Coordinated Universal Time (UTC)",
    "America/New_York" => "America/New_York (EST/EDT)",
    "America/Chicago" => "America/Chicago (CST/CDT)",
    "America/Denver" => "America/Denver (MST/MDT)",
    "America/Los_Angeles" => "America/Los_Angeles (PST/PDT)",
    "America/Anchorage" => "America/Anchorage (AKST/AKDT)",
);

$tzselect = make_select("tz", "America/Chicago", $ar);

$t->content = <<<EOF
<ol class="breadcrumb">
    <li><a href="/ASOS/">ASOS Mainpage</a></li>
    <li class="current">IEM Computed Hourly Precipitation Totals</li>
</ol>

<p>The IEM attempts to take the METAR reports of precipitation and then 
provide just the hourly precipitation totals.  These totals are not for the
true hour (00 to 59 after), but for the hour between the standard METAR
reporting time, typically :53 or :54 after.  The timestamps displayed are 
in <strong>Central Daylight/Standard Time</strong> and for the hour the precipitation 
fell.  So a value for 5 PM would roughly represent the period between 
4:53 and 5:53 PM.

<p><div class="alert alert-warning">Data prior to 2010 only contains the
non-zero values, whereas all hours are accounted for after 2010.  This may
be fixed in upcoming work on the database.  For now, assume zeros for any 
data prior to 2010 for missing hours.</div>

<p>Select network to download from:<br />
<form name="network" action="hourlyprecip.phtml">
{$nselect}		
<input type="submit" value="Switch Network">
</form>

<form target="_blank" name="dl" action="/cgi-bin/request/hourlyprecip.py">
<input type="hidden" value="{$network}" name="network" />

<div class="row">
<div class="col-sm-8">

<h4>1) Select Station(s):</h4>
<div id="iemss" data-network="{$network}" data-name="station" data-supports-all="0"></div>

</div><div class="col-sm-4">

<h4>2) Select period:</h4>
<table class="table table-striped">
  <tr>
    <td></td>
    <th>Year</th><th>Month</th><th>Day</th>
  </tr>

  <tr>
    <th>Start:</th>
    <td>{$y1}</td><td>{$m1}</td><td>{$d1}</td>
        </tr>

  <tr>
    <th>End:</th>
    <td>{$y2}</td><td>{$m2}</td><td>{$d2}</td>
  </tr>
</table>

<h4>3) Metadata</h4>
<input type="checkbox" name="lalo" value="1" id="lalo">
<label for="lalo">Include Station Lat/Lon</label>
<br /><input type="checkbox" name="st" value="1" id="st">
<label for="st">Include State of Station</label>

<h4>4) Timezone of Observation Times:</h4>
<p><i>The following options are available for how the observation time is 
    presented.</i></p>
{$tzselect}

<input type="submit" value="Request Data">

<h4>Download Fields</h4>

<dl class="dl-horizontal">
 <dt>station</dt><dd>Common identifier for the station.</dd>
 <dt>network</dt><dd>Network identifier for the station.</dd>
 <dt>valid</dt><dd>Hour on which the precip fell.</dd>
 <dt>precip_in</dt><dd>Hourly Precipitation [inch]. A value of 0.0001 denotes
 a Trace.</dd>
 <dt>lat</dt><dd>Station Latitude (deg N), when selected.</dd>
 <dt>lon</dt><dd>Station Longitude (deg E), when selected.</dd>
 <dt>st</dt><dd>Station State Indentifier, when selected.</dd>
</dl>

</div></div>
</form>

EOF;
$t->render('single.phtml');
