<?php
include("../../../include/forms.php");
include("maplib.php");
$year = $_GET['year'];
$month = $_GET['month'];
$day = $_GET['day'];
$option = $_GET['option'];
if (strlen($year) == 0 or strlen($day) == 0) {
  $day = 4;
  $year = 2003;
}
if (strlen($month) == 0)  $month = 5;
$ts = mktime(0, 0, 0, $month, $day, $year);
$shp = strftime("%Y_%m/%Y%m%d", $ts) .".shp";
$nicedate = strftime("%d %b %Y", $ts);
$title = "Estimated Daily Rainfall during ${nicedate}";
if ($option == "monthly"){
  $shp = "monthly/". strftime("%Y%m", $ts) .".shp";
  $nicedate = strftime("%b %Y", $ts);
  $title = "Estimated Monthly Rainfall during ${nicedate}";
}
$today = time();


$previousDay = $ts - 86400;
$nextDay = $ts + 86400;
$previousURL = strftime('rainfall.phtml?year=%Y&month=%m&day=%d&var='. $var, $previousDay);
$nextURL = strftime('rainfall.phtml?year=%Y&month=%m&day=%d&var='. $var , $nextDay);



dl("php_mapscript.so");

function clrbar($map, $imgObj) {
  $layer = $map->getLayerByName("clrbar");
  $lclass = $layer->getClass(0);
  $lclass->set("size", "1");
  $point = ms_newpointobj();
  $point->setXY(30, 320);

  $point->draw($map, $layer, $imgObj, "clrbar", "");
}

function mktitle($map, $imgObj, $titlet) {
  $layer = $map->getLayerByName("credits");

  // point feature with text for location
  $point = ms_newpointobj();
  $point->setXY(50, 30);

  $point->draw($map, $layer, $imgObj, "credits",
    $titlet);
}
function mkLegendTitle($map, $imgObj, $titlet) {
  $layer = $map->getLayerByName("credits");

  // point feature with text for location
  $point = ms_newpointobj();
  $point->setXY(10, 430);

  $point->draw($map, $layer, $imgObj, "credits",
    $titlet);
}

$map = ms_newMapObj("wepp.map");


$c = Array();
$c[0] = $map->addColor(0,   160, 246); // 
$c[1] = $map->addColor(0,     0, 246); // 
$c[2] = $map->addColor(0,   255,   0); // 
$c[3] = $map->addColor(0,   200,   0); // 
$c[4] = $map->addColor(255, 255,   0); // 
$c[5] = $map->addColor(231, 192,   0); // 
$c[6] = $map->addColor(255, 144,   0); // 
$c[7] = $map->addColor(255,   0, 255); // 
$c[8] = $map->addColor(153,  85, 201); // 

$white = $map->addColor(255, 255, 255); // 

if (strlen($i1) == 0) $i1 = 0.5; 
if (strlen($i2) == 0) $i2 = 1; 
if (strlen($i3) == 0) $i3 = 2; 
if (strlen($i4) == 0) $i4 = 3; 
if (strlen($i5) == 0) $i5 = 4; 
if (strlen($i6) == 0) $i6 = 5; 
if (strlen($i7) == 0) $i7 = 6; 
if (strlen($i8) == 0) $i8 = 7; 

$bins = Array();
$bins["monthly"] = Array($i1, $i2, $i3, $i4, $i5, $i6, $i7, $i8);

$counties = $map->getlayerbyname("counties");
$counties->set("status", MS_ON);

$states = $map->getlayerbyname("states");
$states->set("status", MS_ON);

$background = $map->getlayerbyname("background");
$background->set("status", MS_ON);

$iards = $map->getlayerbyname("iards");
$iards->set("status", MS_ON);
$iards_label = $map->getlayerbyname("iards_label");
$iards_label->set("status", MS_ON);

$rainfall = $map->getlayerbyname("rainfall");
$rainfall->set("status", MS_ON);
$rainfall->set("data", "/mesonet/WEPP/raindata/${shp}");

$cz = ms_newClassObj($rainfall);
//$cz->set("color", $white);
$cz->set("size", 8);
$cz->set("symbol", 1);
$cz->setexpression("([RAINFALL] == 0)");


$c0 = ms_newClassObj($rainfall);
$c0->set("color", $c[0]);
$c0->set("size", 8);
$c0->set("symbol", 1);
$c0->setexpression("([RAINFALL] < ". $bins["monthly"][0] .")");

$c1 = ms_newClassObj($rainfall);
$c1->set("color", $c[1]);
$c1->set("size", 8);
$c1->set("symbol", 1);
$c1->setexpression("([RAINFALL] < ". $bins["monthly"][1] .")");

$c2 = ms_newClassObj($rainfall);
$c2->set("color", $c[2]);
$c2->set("size", 8);
$c2->set("symbol", 1);
$c2->setexpression("([RAINFALL] < ". $bins["monthly"][2] .")");

$c3 = ms_newClassObj($rainfall);
$c3->set("color", $c[3]);
$c3->set("size", 8);
$c3->set("symbol", 1);
$c3->setexpression("([RAINFALL] < ". $bins["monthly"][3] .")");

$c4 = ms_newClassObj($rainfall);
$c4->set("color", $c[4]);
$c4->set("size", 8);
$c4->set("symbol", 1);
$c4->setexpression("([RAINFALL] < ". $bins["monthly"][4] .")");

$c5 = ms_newClassObj($rainfall);
$c5->set("color", $c[5]);
$c5->set("size", 8);
$c5->set("symbol", 1);
$c5->setexpression("([RAINFALL] < ". $bins["monthly"][5] .")");

$c6 = ms_newClassObj($rainfall);
$c6->set("color", $c[6]);
$c6->set("size", 8);
$c6->set("symbol", 1);
$c6->setexpression("([RAINFALL] < ". $bins["monthly"][6] .")");

$c7 = ms_newClassObj($rainfall);
$c7->set("color", $c[7]);
$c7->set("size", 8);
$c7->set("symbol", 1);
$c7->setexpression("([RAINFALL] < ". $bins["monthly"][7] .")");

$c8 = ms_newClassObj($rainfall);
$c8->set("color", $c[8]);
$c8->set("size", 8);
$c8->set("symbol", 1);


$img = $map->prepareImage();

$background->draw($img);
$counties->draw($img);
$iards->draw($img);
$iards_label->draw($img);
$map->drawLabelCache($img);
$rainfall->draw($img);
$states->draw($img);
mktitle($map, $img, ${title});
mkclrbar($map, $img, $c, $bins["monthly"]);
mkLegendTitle($map, $img, "inches");

$url = $img->saveWebImage(MS_PNG, 0,0,-1);
?>
<html>
<head>
  <title>Iowa Erosion Project | Rainfall Estimates</title>
  <link rel="stylesheet" type="text/css" href="/css/mesonet.css">
</head>
<?php include("/mesonet/www/html/wepp/headerbar.phtml"); ?>

<a href="erosion.phtml?year=<?php echo $year; ?>&month=<?php echo $month; ?>&day=<?php echo $day; ?>">Switch to Erosion Totals</a><br>

<form method="GET" action="rainfall.phtml">
<input type="hidden" value="2003" name="year">
<table>
<tr>
 <th>Month:</th>
 <td><select name="month">
   <option value="01" <?php if (intval($month) == 1) echo "SELECTED"; ?>>January
   <option value="02" <?php if (intval($month) == 2) echo "SELECTED"; ?>>February
   <option value="03" <?php if (intval($month) == 3) echo "SELECTED"; ?>>March
   <option value="04" <?php if (intval($month) == 4) echo "SELECTED"; ?>>April
   <option value="05" <?php if (intval($month) == 5) echo "SELECTED"; ?>>May
   <option value="06" <?php if (intval($month) == 6) echo "SELECTED"; ?>>June
   <option value="07" <?php if (intval($month) == 7) echo "SELECTED"; ?>>July
  </select></td>

 <th>Day:</th>
 <td><?php daySelect($day); ?></td>

 <th>Plot Interval:</th>
 <td><select name="option">
   <option value="daily" <?php if ($option == "daily") echo "SELECTED"; ?>>Daily
   <option value="monthly" <?php if ($option == "monthly") echo "SELECTED"; ?>>Monthly
 </td></tr>
</table>

<table>
<tr>
  <th colspan=8>Define Plot Intervals</th>
</tr>
<tr>
  <td>1 (low):</td>
  <td>2</td>
  <td>3</td>
  <td>4</td>
  <td>5</td>
  <td>6</td>
  <td>7</td>
  <td>8</td>
</tr>
<tr>
  <td><input type="text" name="i1" value="<?php echo $i1; ?>" size=5></td>
  <td><input type="text" name="i2" value="<?php echo $i2; ?>" size=5></td>
  <td><input type="text" name="i3" value="<?php echo $i3; ?>" size=5></td>
  <td><input type="text" name="i4" value="<?php echo $i4; ?>" size=5></td>
  <td><input type="text" name="i5" value="<?php echo $i5; ?>" size=5></td>
  <td><input type="text" name="i6" value="<?php echo $i6; ?>" size=5></td>
  <td><input type="text" name="i7" value="<?php echo $i7; ?>" size=5></td>
  <td><input type="text" name="i8" value="<?php echo $i8; ?>" size=5></td>
</tr>
</table>


  <input type="submit" value="Generate Map">
</form>

<p><a href="<?php echo $previousURL; ?>">Previous Day</a>  &nbsp;
<a href="<?php echo $nextURL; ?>">Next Day</a> 

<p>
<form method="GET" action="click.php">
<input type="hidden" name="map_height" value="<?php echo $map->height; ?>">
<input type="hidden" name="map_width" value="<?php echo $map->width; ?>">
<input type="hidden" name="ul_x" value="<?php echo $map->extent->minx; ?>">
<input type="hidden" name="ul_y" value="<?php echo $map->extent->maxy ; ?>">
<input type="hidden" name="lr_x" value="<?php echo $map->extent->maxx; ?>">
<input type="hidden" name="lr_y" value="<?php echo $map->extent->miny ; ?>">
<input type="hidden" name="year" value="<?php echo $year; ?>">
<input type="hidden" name="month" value="<?php echo $month; ?>">
<input type="hidden" name="day" value="<?php echo $day; ?>">
<input type="image" name="map" src="<?php echo $url; ?>" border=1>
</form>


<p><b>Notes:</b>
<li>21 Jul 2003:  All data present and accounted for!</li>

<?php include("/mesonet/www/html/wepp/footer.phtml"); ?>
