<?php 
require_once "../../../config/settings.inc.php";
require_once "../../../include/myview.php";
require_once "../../../include/forms.php"; 

$t = new MyView();
$t->title = "B548 Agronomy Time Series";
$t->thispage = "networks-other";

$year = isset($_GET["year"]) ? intval($_GET["year"]): date("Y");
$month = isset($_GET["month"]) ? intval($_GET["month"]): date("m");
$day = isset($_GET["day"]) ? intval($_GET["day"]): date("d");
$ts = mktime(0,0,0,$month, $day, $year);

$battery = "";
if ($ts < mktime(0,0,0,7,9,2006)) { 
  $battery = <<<EOF
  <img src="battery.php?year={$year}&month={$month}&day={$day}" ALT="Time Series">
EOF;
}

$ys = yearSelect2(2003, $year, "year");
$ms = monthSelect($month, "month");
$ds = daySelect($day, "day");

$url = sprintf("1min_ot.php?year=%s&month=%s&day=%s", date("Y", $ts),
		date("m", $ts), date("d", $ts) );
$n = sprintf("ot_10min.phtml?year=%s&month=%s&day=%s", date("Y", $ts +86400),
		date("m", $ts + 86400), date("d", $ts + 86400) );
$p = sprintf("ot_10min.phtml?year=%s&month=%s&day=%s", date("Y", $ts - 86400),
		date("m", $ts - 86400), date("d", $ts - 86400) );

$t->content = <<<EOF
<ol class="breadcrumb">
<li><a href="/other/">Other Networks</a></li>
<li class="active">B548 Agronomy Server Room</li>
</ol>

<p>The IEM server resides in a room that is climate controlled by a 
dedicated heat exchanger.  This page presents daily plots of logged 
temperatures.  There are four one-wire sensors measuring ambient temperature.
The arrangement of these sensors has changed over the years. 
The current temperature observation points are:
<ul>
 <li><b>In Air Handler:</b> Located at 5 feet above the floor at the 
intake of the heat exchanger.</li>
 <li><b>Out Air Handler:</b> Located below the sub floor where the
cooled air departs the heat exchanger.</li>
 <li><b>In Rack:</b> Located on the front door of the rack at about 1 meter
 height.</li>
 <li><b>Out Rack:</b> Located at the back of the rack at about 1 meter
 height.</li>
</ul>

<br>Note that the archive begins 24 Jul 2003.</p>

  <form method="GET" action="ot_10min.phtml">
{$ys} {$ms} {$ds}



  <input type="submit" value="Make Plot"></form>
<p><a href="{$p}">View Previous Day</a> 
&nbsp; &nbsp; <a href="{$n}">View Next Day</a> 

<br>
  <img src="{$url}" alt="Time Series" class="img img-responsive">
<br>
{$battery}
<br>

<p>
<strong>Interesting Data Traces</strong>
<ul>
 <li><a href="ot_10min.phtml?year=2008&month=05&day=16">16 May 2008</a> 
  <br />Agronomy building looses chilled water supply, the heat exchanger
  later gets backed up on local 'cooler' water.</li>
 <li><a href="ot_10min.phtml?year=2010&month=06&day=14">14 Jun 2010</a> 
  <br />ISU Campus takes a power bump knocking out various utilities.</li>
 <li><a href="ot_10min.phtml?year=2010&month=08&day=11">11 Aug 2010</a> 
  <br />Flooding impacts ISU campus and the chilled water is shut off for a while.</li>
 <li><a href="ot_10min.phtml?year=2013&month=06&day=24">24 Jun 2013</a> 
  <br />Chilled water is turned off for an hour to check metering.</li>
 <li><a href="ot_10min.phtml?year=2016&month=8&day=9">9 Aug 2016</a> 
  <br />Fan bracket is repaired on heat exchanger.</li>
  <li><a href="ot_10min.phtml?year=2019&month=4&day=10">10 Apr 2019</a> 
  <br />Lightning strike knocks out chilled water and then power surge
  knocks out a few servers.</li>
  <li><a href="ot_10min.phtml?year=2020&month=4&day=11">11 Apr 2020</a> 
  <br />ISU FP&amp;M shuts down chilled water supply to do some local
  construction work.</li>
</ul>

EOF;
$t->render('single.phtml');
?>

