<?php 
include("../../../config/settings.inc.php");
$TITLE = "IEM | B548 Agronomy | Time Series";
$year = isset($_GET["year"]) ? $_GET["year"]: date("Y");
$month = isset($_GET["month"]) ? $_GET["month"]: date("m");
$day = isset($_GET["day"]) ? $_GET["day"]: date("d");
$ts = mktime(0,0,0,$month, $day, $year);
$THISPAGE = "networks-other";
include("$rootpath/include/header.php"); ?>
<?php include("$rootpath/include/forms.php"); ?>

<div class="text">

<p>The IEM server resides in a room that is climate controlled by a 
dedicated heat exchanger.  This page presents daily plots of logged 
temperatures.  The temperature observation points are:
<ul>
 <li><b>In Air Handler:</b> Located at 5 feet above the floor at the 
intake of the heat exchanger.</li>
 <li><b>Out Air Handler:</b> Located below the sub floor where the
cooled air departs the heat exchanger.</li>
 <li><b>Out Floor:</b> Located on the opposite side of the room immediately
above the vent thru the subfloor.</li>
 <li><b>Room:</b> Located at 5 feet above the floor on the opposite side
of the room to the heat exchanger.</li>
</ul>

<br>Note that the archive begins 24 Jul 2003.</p>

  <form method="GET" action="ot_10min.phtml">
  <?php 
echo yearSelect2(2003, $year, "year");
echo monthSelect($month, "month");
echo daySelect($day, "day");

$url = sprintf("1min_ot.php?year=%s&month=%s&day=%s", date("Y", $ts), 
       date("m", $ts), date("d", $ts) );
$n = sprintf("ot_10min.phtml?year=%s&month=%s&day=%s", date("Y", $ts +86400), 
       date("m", $ts + 86400), date("d", $ts + 86400) );
$p = sprintf("ot_10min.phtml?year=%s&month=%s&day=%s", date("Y", $ts - 86400), 
       date("m", $ts - 86400), date("d", $ts - 86400) );

?>
  <input type="submit" value="Make Plot"></form>
<?php
if ($ts >  mktime(0,0,0,7,24,2003)){ ?>
<p><a href="<?php echo $p; ?>">View Previous Day</a> 
<?php } if ($ts < time()) { ?>
&nbsp; &nbsp; <a href="<?php echo $n; ?>">View Next Day</a> 
<?php } ?>

<BR>
  <img src="<?php echo $url; ?>" ALT="Time Series">
<BR>
<?php if ($ts < mktime(0,0,0,7,9,2006)) { ?>
  <img src="battery.php?year=<?php echo $year; ?>&month=<?php echo $month; ?>&day=<?php echo $day; ?>" ALT="Time Series">
<?php } ?>
<BR>

<p>
<strong>Interesting Data Traces</strong>
<ul>
 <li><a href="ot_10min.phtml?year=2008&month=05&day=16">16 May 2008</a> 
  <br />Agronomy building looses chilled water supply, the heat exchanger
  later gets backed up on local 'cooler' water.</li>
 <li><a href="ot_10min.phtml?year=2010&month=06&day=14">14 Jun 2010</a> 
  <br />ISU Campus takes a power bump knocking out various utilities.</li>
</ul>

</div>

<?php include("$rootpath/include/footer.php"); ?>

