<?php 
 include("../../config/settings.inc.php");
	$THISPAGE = "climatology-main";
	$TITLE = "IEM | Climatology";
include("$rootpath/include/header.php"); 
?>

<h3 class="subtitle">Climatological Products</h3>

<div style="margin-left: 20px; width: 640px;">
<p>Climatology provides information on what you may expect for various 
variables and durations.  The IEM Climatology section is organized by
different periods of time (see second row of links in the banner).

<p><img src="../images/wizard.png" style="float:left; margin: 5px;">The 
<a href="/climodat/">Climodat</a> application provides pre-generated reports
of Iowa's climate based on the most popular requests we get from the 
general public.  You should check out that page first, it may have what 
you need.
</p></div>

<h4>Other Resources</h4>

<p>The <a href="http://www.iowaagriculture.gov/climatology.asp">Iowa State Climatologist's page</a> has a number of products from the official source of 
climate data in the state.

<p>The <a href="http://www.ncdc.noaa.gov">National Climatic Data Center</a>
is <strong>the online archive</strong> for climate information from Iowa
and the world!</p>

<p>The <a href="http://www.hprcc.unl.edu/">High Plains Climate Center</a> and
<a href="http://mrcc.isws.illinois.edu/">Midwestern Regional Cimate Center</a>
have a number of quality products for Iowa.

<?php include("$rootpath/include/footer.php"); ?>
