<?php 
 require_once "../../config/settings.inc.php";
 require_once "../../include/myview.php";
 $t = new MyView();
 $t->title = "Climatology";

 $t->content = <<<EOF
<h3 class="subtitle">Climatological Products</h3>

<div style="margin-left: 20px;">
<p>Climatology provides information on what you may expect for various 
variables and durations.  The IEM Climatology section is organized by
different periods of time (see second row of links in the banner).

<p><img src="/images/wizard.png" style="float:left; margin: 5px;">The 
<a href="/climodat/">Climodat</a> application provides pre-generated reports
of Iowa's climate based on the most popular requests we get from the 
general public.  You should check out that page first, it may have what 
you need.
</p>

<p><strong>Most Popular Products</strong>
<ul>
  <li>Download <a href="/COOP/dl/normals.phtml">Daily Climate Normals</a></li>
</ul>

<p><strong>Iowa's Earliest Snowfall on Record</strong>
<br />There is no one exact or official answer to this question.  In
the modern era, September 25th 1942 could be considered as the earliest 
date in the fall of accumulating snowfall. Up to 4 inches fell 
that day with nearly all of the state seeing something.

<br />&nbsp;<br />However, there was an earlier event back on September 16, 1881 when snow
accumulated over about the western one-half of Iowa and 4 to 6 inches was
reported between Avoca and Stuart in west central Iowa.

<br />&nbsp;<br />There were reports of a few flakes on September 6, 1929 
near Alton about 9 a.m.

</div>



<h4>Other Resources</h4>

<p>The <a href="http://www.iowaagriculture.gov/climatology.asp">Iowa State Climatologist's page</a> has a number of products from the official source of 
climate data in the state.

<p>The <a href="http://www.ncdc.noaa.gov">National Climatic Data Center</a>
is <strong>the online archive</strong> for climate information from Iowa
and the world!</p>

<p>The <a href="http://www.hprcc.unl.edu/">High Plains Climate Center</a> and
<a href="http://mrcc.isws.illinois.edu/">Midwestern Regional Cimate Center</a>
have a number of quality products for Iowa.
EOF;
$t->render('single.phtml');
 ?>
