<?php 
include("../../config/settings.inc.php");
include("../../include/myview.php");
$t = new MyView();
$t->title = "Climatology Plots for Today";

$t->content = <<<EOF
<h4>Temperature</h4>
<ul>
<li><a href="/data/summary/mon_mean_T.png">Average Temperature</a>[ASOS/AWOS]</li>
</ul>

<h4>Precipitation</h4>
<ul>
<li><a href="/data/summary/month_prec.png">Precip Accum</a>[ASOS/AWOS]</li>
<li><a href="/data/coopMonthPlot.png">Precip Accum</a>[COOP]</li>
<li><a href="/plotting/month/rainfall.phtml">Plots of Monthly Rainfall</a></li>
</ul>

<h4>Snowfall</h4>
<ul>
<li><a href="/data/coopMonthSPlot.gif">Snowfall this month</a>[COOP]</li>
</ul>

<h4>Winds</h4>
<ul>
<li><a href="/sites/windrose.phtml?station=DSM&network=IA_ASOS">Wind Roses</a></li>
</ul>

<h4>GDD</h4>
<ul>
<li><a href="/data/summary/gdd_mon.png"><?php echo date("F"); ?> Accumulated Growing Degree Days (base=50)</a></li>
</ul>

<h4>SDD</h4>
<ul>
<li><a href="/data/summary/sdd_mon.png"><?php echo date("F"); ?> Accumulated Stress Degree Days-(base=86)</a></li>
</ul>
EOF;
$t->render('single.phtml');
?>
