<?php 
include("../../config/settings.inc.php");
$TITLE = "IEM | Climatology Plots for Today";
$THISPAGE = "climatology-month";
include("$rootpath/include/header.php"); 
?>

<h4>Precipitation</h4>
<ul class="iem-list">
<li><a href="/data/summary/month_prec.png">Precip Accum</a>[ASOS/AWOS]</li>
<li><a href="/data/coopMonthPlot.gif">Precip Accum</a>[COOP]</li>
<li><a href="/data/text/IEMAZOMPR.txt">Tabular High/Low/Prec</a>[ASOS/AWOS]</li>
<li><a href="/data/text/IEMNWSMPR.txt">Tabular Precip/Snow</a>[ASOS/AWOS]</li>
<li><a href="/plotting/month/rainfall.phtml">Plots of Monthly Rainfall</a></li>
</ul>

<h4>Snowfall</h4>
<ul class="iem-list">
<li><a href="/data/coopMonthSPlot.gif">Snowfall this month</a>[COOP]</li>
</ul>

<h4>Winds</h4>
<ul class="iem-list">
<li><a href="http://mesonet.agron.iastate.edu/sites/windrose.phtml?station=DSM&network=IA_ASOS">Wind Roses</a></li>
</ul>

<h4>GDD</h4>
<ul class="iem-list">
<li><a href="/data/summary/gdd_mon.gif"><?php echo date("F"); ?> Accumulated Growing Degree Days (base=50)</a></li>
</ul>

<h4>SDD</h4>
<ul class="iem-list">
<li><a href="/data/summary/sdd_mon.gif"><?php echo date("F"); ?> Accumulated Stress Degree Days-(base=86)</a></li>
</ul>


<?php include("$rootpath/include/footer.php"); ?>
