<?php
include("../../config/settings.inc.php");
$TITLE = "IEM | Information";
include("$rootpath/include/header.php"); ?>

<h3 class="heading">Iowa Weather/Climate Hall of Fall</h3>

<table>
<tr>
 <th>Maximum High Temperature:</th>
 <td>118&deg;F</td>
 <td>Keokuk  20 July 1934</td></tr>

</table>

<h3 class="heading">Rainfall Accumulation</h3>

<table cellpadding="5">
<tr><td valign="top">

<table border="1" cellpadding="1" cellspacing="0">
<caption>For Any Month</caption>
<tr><th>Rank:</th><th>Location:</th><th>Month/Year</th><th>Amount</th></tr>
<tr><td>1.</td><td>Red Oak</td><td>Jun 1967</td><td>22.18</td></tr>
<tr><td>2.</td><td>Leon</td><td>Jul 1993</td><td>20.74</td></tr>
<tr><td>3.</td><td>Corydon</td><td>Jul 1993</td><td>20.51</td></tr>
<tr><td>4.</td><td>Larrabee</td><td>Jun 1891</td><td>19.88</td></tr>
<tr><td>5.</td><td>Audubon</td><td>Jul 1958</td><td>19.78</td></tr>
<tr><td>6.</td><td>Beaconsfield</td><td>Jul 1993</td><td>19.75</td></tr>
<tr><td>7.</td><td>Emerson</td><td>Jun 1967</td><td>19.70</td></tr>
<tr><td>8.</td><td>Malvern</td><td>Jun 1967</td><td>19.63</td></tr>
<tr><td>9.</td><td>Rathbun Dam</td><td>Aug 2007</td><td>19.43</td></tr>
<tr><td>10.</td><td>Norwich</td><td>Jul 1958</td><td>19.28</td></tr>
</table>

</td><td>

<table border="1" cellpadding="1" cellspacing="0">
<caption>For A Given Month</caption>
<tr><th>Month:</th><th>Location:</th><th>Year</th><th>Amount</th></tr>
<tr><td>January</td><td>Keokuk</td><td>1965</td><td>8.58</td></tr>
<tr><td>February</td><td>Brookside</td><td>1865</td><td>7.00</td></tr>
<tr><td>March</td><td>Muscatine</td><td>1852</td><td>8.60</td></tr>
<tr><td>April</td><td>Strawberry Point</td><td>1951</td><td>12.52</td></tr>
<tr><td>May</td><td>Grand Meadow</td><td>1902</td><td>18.04</td></tr>
<tr><td>June</td><td>Red Oak</td><td>1967</td><td>22.18</td></tr>
<tr><td>July</td><td>Leon</td><td>1993</td><td>20.74</td></tr>
<tr><td>August</td><td>Rathbun Dam</td><td>2007</td><td>19.43</td></tr>
<tr><td>September</td><td>Corydon</td><td>1926</td><td>18.57</td></tr>
<tr><td>October</td><td>Burlington Airport</td><td>1941</td><td>15.10</td></tr>
<tr><td>November</td><td>Humboldt</td><td>1909</td><td>11.48</td></tr>
<tr><td>December</td><td>Keokuk</td><td>1873</td><td>8.56</td></tr>
</table>

</td></tr>
</table>

<?php include("$rootpath/include/footer.php"); ?>
