<?php
include("../../config/settings.inc.php");
$TITLE = "IEM | Information";
include("$rootpath/include/header.php"); ?>

<h3 class="heading">Iowa Weather/Climate Records</h3>

<p>Here is a summary of Iowa weather and climate records.  The <a href="http://www.agriculture.state.ia.us/climatology.htm">Iowa State 
Climatologist</a>, Harry Hillaker, is the source of these records unless 
otherwise noted.

<h3 class="heading">Air Temperature (All values in Fahrenhit)</h3>

<table cellpadding="5">
<tr><td valign="top">

<table border="1" cellpadding="1" cellspacing="0">
<caption>For Any Day</caption>
<tr><td rowspan="2">Maximum High:</td>
 <td>Atlantic</td><td>25 July 1936</td><td rowspan="2">117</td></tr>
<tr>
 <td>Logan</td><td>25 July 1936</td></tr>
<tr><td>Latest 100F</td><td>Glenwood</td><td>28 Sep 1953</td><td>103</td></tr>
</table>

</td><td>

<table border="1" cellpadding="2" cellspacing="0">
<caption>Max High For A Given Month</caption>
<tr><th>Month:</th><th>Location:</th><th>Day/Year</th><th>High</th></tr>
<tr><td>January</td><td>Keokuk</td><td>24 Jan 1950</td><td>73</td></tr>
<tr><td>February</td><td>Sidney</td><td>29 Feb 1972</td><td>82</td></tr>
<tr><td rowspan="3">March</td><td>Clarinda</td><td>25 Mar 1907</td><td rowspan="3">92</td></tr>
<tr><td>Massena</td><td>25 Mar 1907</td></tr>
<tr><td>Glenwood</td><td>29 Mar 1986</td></tr>
<tr><td rowspan="2">April</td><td>Fort Dodge</td><td>22 Apr 1980</td><td rowspan="2">100</td></tr>
<tr><td>Waterloo</td><td>22 Apr 1980</td></tr>
<tr><td>May</td><td>Inwood</td><td>30 May 1934</td><td>111</td></tr>
<tr><td>June</td><td>Denison</td><td>10 Jun 1933</td><td>109</td></tr>
<tr><td rowspan="2">July</td><td>Atlantic</td><td>25 Jul 1936</td><td rowspan="2">117</td></tr>
<tr><td>Logan</td><td>25 Jul 1936</td></tr>
<tr><td rowspan="2">August</td><td>Ottumwa</td><td>8 Aug 1934</td><td rowspan="2">115</td></tr>
<tr><td>Keosauqua</td><td>9 Aug 1934</td></tr>
<tr><td rowspan="3">September</td><td>Bedford</td><td>5 Sep 1913</td><td rowspan="3">107</td></tr>
<tr><td>Logan</td><td>6 Sep 1939</td></tr>
<tr><td>Glenwood</td><td>7 Sep 1939</td></tr>
<tr><td rowspan="6">October</td><td>Malvern</td><td>1 Oct 1897</td><td rowspan="6">97</td></tr>
<tr><td>Ottumwa</td><td>1 Oct 1897</td></tr>
<tr><td>Onawa</td><td>3 Oct 1938</td></tr>
<tr><td>Knoxville</td><td>4 Oct 1938</td></tr>
<tr><td>Forest City</td><td>5 Oct 1963</td></tr>
<tr><td>Shenandoah</td><td>5 Oct 1963</td></tr>
<tr><td>November</td><td>Glenwood</td><td>13 Nov 1999</td><td>85</td></tr>
<tr><td>December</td><td>Thurman</td><td>6 Dec 1939</td><td>74</td></tr>
</table>

</td><td valign="top">

<table border="1" cellpadding="2" cellspacing="0">
<caption>Min Low For A Given Month</caption>
<tr><th>Month:</th><th>Location:</th><th>Day/Year</th><th>Low</th></tr>
<tr><td>January</td><td>Washta</td><td>12 Jan 1912</td><td>-47</td></tr>
<tr><td>February</td><td>Elkader</td><td>3 Feb 1996</td><td>-47</td></tr>
<tr><td rowspan="2">March</td><td>Hampton</td><td>1 Mar 1962</td><td rowspan="2">-35</td></tr>
<tr><td>Winterset</td><td>1 Mar 1962</td></tr>
<tr><td>April</td><td>Manchester</td><td>6 Apr 1982</td><td>-9</td></tr>
<tr><td>May</td><td>Washta</td><td>2 May 1908 </td><td>13</td></tr>
<tr><td>June</td><td>Decorah</td><td>3 Jun 1946</td><td>27</td></tr>
<tr><td rowspan="3">July</td><td>Logan</td><td>9 Jul 1895</td><td rowspan="3">35</td></tr>
<tr><td>Neola</td><td>9 Jul 1895</td></tr>
<tr><td>Elkader</td><td>7 Jul 1984</td></tr>
<tr><td rowspan="4">August</td><td>Elkader</td><td>30 Aug 1893</td><td rowspan="4">30</td></tr>
<tr><td>Mason City</td><td>30 Aug 1915</td></tr>
<tr><td>Britt</td><td>20 Aug 1950</td></tr>
<tr><td>Sibley</td><td>20 Aug 1950</td></tr>
<tr><td rowspan="3">September</td><td>Sheldon</td><td>29 Sep 1899</td><td rowspan="3">15</td></tr>
<tr><td>Sibley</td><td>29 Sep 1899</td></tr>
<tr><td>Mason City</td><td>30 Sep 1899</td></tr>
<tr><td>October</td><td>Inwood</td><td>29 Oct 1925</td><td>-15</td></tr>
<tr><td>November</td><td>Cresco</td><td>28 Nov 1887</td><td>-25</td></tr>
<tr><td>December</td><td>Washta</td><td>29 Dec 1917</td><td>-40</td></tr>
</table>



</td></tr></table>

<h3 class="heading">Rainfall Accumulation (All values in inches)</h3>

<table cellpadding="5">
<tr><td valign="top">

<table border="1" cellpadding="1" cellspacing="0">
<caption>For Any Month</caption>
<tr><th>Rank:</th><th>Location:</th><th>Month/Year</th><th>Amount</th></tr>
<tr><td>1.</td><td>Red Oak</td><td>Jun 1967</td><td>22.18</td></tr>
<tr><td>2.</td><td>Leon</td><td>Jul 1993</td><td>20.74</td></tr>
<tr><td>3.</td><td>Corydon</td><td>Jul 1993</td><td>20.51</td></tr>
<tr><td>4.</td><td>Larrabee</td><td>Jun 1891</td><td>19.88</td></tr>
<tr><td>5.</td><td>Audubon</td><td>Jul 1958</td><td>19.78</td></tr>
<tr><td>6.</td><td>Beaconsfield</td><td>Jul 1993</td><td>19.75</td></tr>
<tr><td>7.</td><td>Emerson</td><td>Jun 1967</td><td>19.70</td></tr>
<tr><td>8.</td><td>Malvern</td><td>Jun 1967</td><td>19.63</td></tr>
<tr><td>9.</td><td>Rathbun Dam</td><td>Aug 2007</td><td>19.43</td></tr>
<tr><td>10.</td><td>Norwich</td><td>Jul 1958</td><td>19.28</td></tr>
</table>

</td><td>

<table border="1" cellpadding="1" cellspacing="0">
<caption>For A Given Month</caption>
<tr><th>Month:</th><th>Location:</th><th>Year</th><th>Amount</th></tr>
<tr><td>January</td><td>Keokuk</td><td>1965</td><td>8.58</td></tr>
<tr><td>February</td><td>Brookside</td><td>1865</td><td>7.00</td></tr>
<tr><td>March</td><td>Muscatine</td><td>1852</td><td>8.60</td></tr>
<tr><td>April</td><td>Strawberry Point</td><td>1951</td><td>12.52</td></tr>
<tr><td>May</td><td>Grand Meadow</td><td>1902</td><td>18.04</td></tr>
<tr><td>June</td><td>Red Oak</td><td>1967</td><td>22.18</td></tr>
<tr><td>July</td><td>Leon</td><td>1993</td><td>20.74</td></tr>
<tr><td>August</td><td>Rathbun Dam</td><td>2007</td><td>19.43</td></tr>
<tr><td>September</td><td>Corydon</td><td>1926</td><td>18.57</td></tr>
<tr><td>October</td><td>Burlington Airport</td><td>1941</td><td>15.10</td></tr>
<tr><td>November</td><td>Humboldt</td><td>1909</td><td>11.48</td></tr>
<tr><td>December</td><td>Keokuk</td><td>1873</td><td>8.56</td></tr>
</table>

</td></tr>
</table>

<?php include("$rootpath/include/footer.php"); ?>
