<?php
require_once "../../config/settings.inc.php";
require_once "../../include/myview.php";
$t = new MyView();
$t->title = "Climatology Plots for Past 7 Days";

$t->content = <<<EOF
<h4>Temperature</h4>
<ul>
<li><a href="/data/summary/7day/iaavg_max_tmpf.png">Average High</a></li>
<li><a href="/data/summary/7day/iaavg_min_tmpf.png">Average Low</a></li>
</ul>

<h4>Precipitation</h4>
<ul>
<li><a href="/rainfall/obhour.phtml">Hourly Precip Accumulator</a></li>
<li><a href="/data/summary/7day/ia_precip.png">Precip Accumulation</a> [ASOS+AWOS]</li>
</ul>
EOF;
$t->render('single.phtml');
