<?php 
include("../../config/settings.inc.php");
$TITLE = "IEM | Climatology Plots for Today";
$THISPAGE = "climatology-year";
include("$rootpath/include/header.php"); 
?>

<h4>Temperature</h4>
<ul class="iem-list">
<li>Minimum temp this fall/winter<br>
     &nbsp; &nbsp; <a href="/data/summary/fallLow.gif">Plot</a> or
    <a href="/data/summary/fallLowC.gif">Contour</a></li>
<li><a href="/plotting/coop/climate_fe.php">Annual Average Temperatures</a></li>
<li><a href="/plotting/coop/vyear_fe.php">Yearly Departures from Average</a></li>
<li><a href="/data/text/IEMAZOMPR.txt">Tabular High/Low/Prec</a>[ASOS/AWOS]</li>
<li><a href="/COOP/freezing.php">Freezing Statistics</a></li>
</ul>

<h4>Past 4 Months</h4>
<ul class="iem-list">
 <li><a href="/data/summary/4mon_stage4obs.png">Estimated accumulation</a></li>
 <li><a href="/data/summary/4mon_normals.png">Climatology</a></li>
 <li><a href="/data/summary/4mon_diff.png">Departure from normal</a></li>
</ul>


<h4>GDD</h4>
<ul class="iem-list">
<li><a href="/data/summary/year/diff.png">Departure from normal</a></li>
<li><a href="/data/summary/year/stage4obs.png">Stage4 estimates</a></li>
<li><a href="/data/summary/year/normals.png">Normal accumulation</a></li>
 <li><a href="<?php echo $rooturl; ?>/plotting/yearly/rainfall.phtml">Month by Month</a></li>
</ul>

<h4>Winds</h4>
<ul class="iem-list">
<li><a href="http://mesonet.agron.iastate.edu/sites/windrose.phtml?station=DSM&network=IA_ASOS">Wind Roses</a></li>
</ul>

<h4>GDD</h4>
<ul class="iem-list">
<li>All Stations: <a href="/data/summary/gdd_qc.gif">Plot</a> or
    <a href="/data/summary/gdd_qc_contour.gif">Contour</a></li>
<li><a href="/data/summary/gdd_qc_asos.gif">ASOS / AWOS</a> |
    <a href="/data/summary/gdd_qc_rwis.gif">RWIS</a></li>
<li><a href="/data/summary/gdd_qc_snet.gif">School Net</a></li>
<li><A href="/data/summary/gdd_may1.gif">Seasonal (since May 1) Accumulated Growing Degree Days-(base=50)</a></li>
<li><a href="/data/summary/gdd_norm.gif">Normal Accumulation</a></li>
<li><a href="/data/summary/gdd_diff.gif">Departure from Normal</a></li>
<li><a href="/plotting/gs/fe.phtml">Growing Season Rainfall/GDD vs Climatology</a></li>
<li><a href="/data/summary/gdd_jan1.gif">Seasonal (before May 1) Accumulated Growing Degree Days-(base=50)</a></li>
</ul>

<h4>SDD</h4>
<ul class="iem-list">
 <li>All Stations: <a href="/data/summary/sdd_qc.gif">Plot</a> or
    <a href="/data/summary/sdd_qc_contour.gif">Contour</a></li>
<li><a href="/data/summary/sdd_qc_asos.gif">ASOS / AWOS</a> |
    <a href="/data/summary/sdd_qc_rwis.gif">RWIS</a></li>
<li><a href="/data/summary/sdd_qc_snet.gif">School Net</a></li>
<li><A href="/data/summary/sdd_may1.gif">Seasonal Accumulated Stress Degree Days-(base=86)</a></li>
</ul>


<?php include("$rootpath/include/footer.php"); ?>
