<?php 
include("../../config/settings.inc.php");
include("../../include/myview.php");
$t = new MyView();
$t->title = "Climatology Plots for Yesterday";

$u1 = sprintf("/archive/data/%scoop_avg_temp.png", 
		date("Y/m/d/" , date("U") - 86400 ));
$u2 = sprintf("/archive/data/%scoop_rec_temp.png",
		date("Y/m/d/" , date("U") - 86400 ));

$t->content = <<<EOF
<h4>Temperature</h4>
<ul>
<li><a href="/data/coopHighLow.gif">High Temps</a>[COOP]</li>
<li><a href="/data/awos_rtp.shef">12Z AWOS RTP First Guess</a></li>
<li><a href="{$u1}">Average Hi/Low Temp</a></li>
<li><a href="{$u2}">Record Hi/Low Temp</a></li>
</ul>

<h4>Precipitation</h4>
<ul>
<li><a href="/rainfall/obhour.phtml">Hourly Precip Accumulator</a></li>
<li><a href="http://www.meteor.iastate.edu/pix/radp6.gif">Radar-estimate of storm total precip through MIDNIGHT (CST)</a></li>
</ul>

<h4>Wind</h4>
<ul>
<li><a href="/data/summary/yest_gust.gif">Peak Wind Gust</a></li>
</ul>

<h4>Soil Temperatures</h4>
<ul>
<li><a href="/agclimate/daily_pics/soil-hilo-out.png">Yesterday's 4-inch</a></li>
<li><a href="/data/soilt_day1.png">County estimate 4-inch</a></li>
</ul>
EOF;
$t->render('single.phtml');
?>