<?php 
include("../../config/settings.inc.php");
include("../../include/myview.php");
$t = new MyView();

$sortcol = isset($_GET["sortcol"]) ? $_GET["sortcol"]: "station";

$t->refresh = "<meta http-equiv=\"refresh\" content=\"60; URL=current.phtml?sortcol=$sortcol\">";
$t->title = "AWOS Network Current Conditions";
$t->headextra = <<<EOF
<script language="JavaScript" type="text/javascript">
<!--//BEGIN Script
function new_window(url) {
 link = window.open(url,"_new","toolbar=0,location=0,directories=0,status=0,menubar=no,scrollbars=yes,resizable=yes,width=800,height=600");
} 
//END Script-->
</script>
EOF;
$t->current_network = "AWOS";
$t->thispage = "current-sort";
  include("../../include/mlib.php"); 
  include("../../include/iemaccess.php");
  include("../../include/iemaccessob.php");

  $iem = new IEMAccess();
  $awos = $iem->getNetwork("AWOS");

  $vals = Array("station" => "Station ID", "ts" => "Ob Time",
  		"relh" => "Relative Humidity", "sname" => "Site Name",
  		"min_tmpf" => "Today's Low Temperature",
  		"max_tmpf" => "Today's High Temperature",
  		"tmpf" => "Temperature", "dwpf" => "Dew Point", "vsby" => "Visibility",
  		"sknt" => "Speed", "peak" => "Peak Gust [knots]","alti" => "Altimeter",
  		"peak_ts" => "Gust Time", "phour" => "1 hr Rainfall", "pday" => "Today Rainfall", "feel" => "Feels Like");
  
$t->breadcrumbs = <<<EOF
<ol class="breadcrumb">
 <li><a href="/AWOS/">AWOS Homepage</a></li>
 <li class="active">Current Conditions</li>
</ol>
EOF;
$table = <<<EOF

<h3>Current AWOS Conditions</h3>

<p>** This page will automatically refresh every five minutes.

<br>Sorted by: <b>({$vals[$sortcol]})</b>  &nbsp; &nbsp; 
Click on a column to sort it.<br>

<form name="asdf" method="GET" action="/my/current.phtml">

<table class="table table-condensed table-striped table-bordered">
<thead>
<tr>
  <th rowspan=2>Add</th>
  <th rowspan=2><a href="current.phtml?sortcol=sname">Station:</a></th>
  <th rowspan=2><a href="current.phtml?sortcol=ts">Ob Time</a></th>
  <th colspan=4>&nbsp;</th>
  <th colspan=3>Wind [knots]</th>
  <th colspan=2>&nbsp;</th>
  <th colspan=2>Rainfall</th></tr>

<tr>
  <th>
   <a href="current.phtml?sortcol=tmpf">Temp</a>
   (<a href="current.phtml?sortcol=max_tmpf">Hi</a> /
   <a href="current.phtml?sortcol=min_tmpf">Lo</a>)
 </th>
  <th><a href="current.phtml?sortcol=dwpf">DewP</a></th>
  <th><a href="current.phtml?sortcol=feel">Feels</a></th>
  <th><a href="current.phtml?sortcol=relh">RH%</a></th>
  <th>Dir</th>
  <th><a href="current.phtml?sortcol=sknt">Speed</a></th>
  <th><a href="current.phtml?sortcol=peak">Peak Gust</a>
   <br>@ <a href="current.phtml?sortcol=peak_ts">Time</a></th>
  <th><a href="current.phtml?sortcol=alti">Alti</a></th>
  <th><a href="current.phtml?sortcol=vsby">Vsby</a></th>
  <th><a href="current.phtml?sortcol=phour">Hour</a></th>
  <th><a href="current.phtml?sortcol=pday">Today</a></th>
</tr>
</thead><tbody>
EOF;

function aSortBySecondIndex($multiArray, $secondIndex) {
	while (list($firstIndex, ) = each($multiArray))
		$indexMap[$firstIndex] = $multiArray[$firstIndex][$secondIndex];
	arsort($indexMap);
	while (list($firstIndex, ) = each($indexMap))
		if (is_numeric($firstIndex))
			$sortedArray[] = $multiArray[$firstIndex];
		else $sortedArray[$firstIndex] = $multiArray[$firstIndex];
	return $sortedArray;
}

  while (list($key, $iemob) = each($awos) ){
    $mydata[$key] = $iemob->db;
    $mydata[$key]["ts"] = $iemob->ts;
    $mydata[$key]["sped"] = $mydata[$key]["sknt"] * 1.15078;
    if ($mydata[$key]["tmpf"] > -99) {
      $mydata[$key]["tmpf"] = round($mydata[$key]["tmpf"], 0);
      $mydata[$key]["dwpf"] = round($mydata[$key]["dwpf"], 0);
      $mydata[$key]["relh"] = relh(f2c($mydata[$key]["tmpf"]),
       f2c($mydata[$key]["dwpf"]) );
      $mydata[$key]["feel"] = feels_like($mydata[$key]["tmpf"],
       $mydata[$key]["relh"], $mydata[$key]["sped"]);
   } else {
      $mydata[$key]["tmpf"] = "M";
      $mydata[$key]["dwpf"] = "M";
      $mydata[$key]["feel"] = "M";
      $mydata[$key]["relh"] = "M";
   } 
   $mydata[$key]["peak_ts"] = 0;
   if ($mydata[$key]["max_gust"] > $mydata[$key]["max_sknt"]){
      $mydata[$key]["peak"] = $mydata[$key]["max_gust"];
      $mydata[$key]["peak_ts"] = strtotime(substr( $mydata[$key]["max_gust_ts"],0,16) );
    } else {
      $mydata[$key]["peak"] = $mydata[$key]["max_sknt"];
      if ($mydata[$key]["max_sknt_ts"] > 0) {
        $mydata[$key]["peak_ts"] = strtotime(substr( $mydata[$key]["max_sknt_ts"],0,16) );
     }   
 }

	if ($mydata[$key]["pday"] < 0) $mydata[$key]["pday"] = 0;                                                                               
  }

 $finalA = Array();
 $finalA = aSortBySecondIndex($mydata, $sortcol);
 $now = time();
 $shade = 1;
 while (list ($key, $val) = each ($finalA))  { 
	$parts = $finalA[$key];
        $table .= "<tr ";
        if ($shade) $table .= "bgcolor=\"#EEEEEE\"";
        $shade = ! $shade;
        $table .= ">\n 
         <td><input type=\"checkbox\" name=\"st[]\" 
            value=\"".$key."\"></td>";

         $tdiff = $now - $parts["ts"];
         $table .= sprintf("<td>%s (<a href=\"/sites/site.php?station=%s&network=AWOS\">%s</a>)</td>", $parts["sname"], $key, $key );
         $table .= "<td ";
         if ($tdiff > 10000){
           $format = "%d %b %I:%M %p";
           $table .= 'bgcolor="red"> '. strftime($format, $parts["ts"]) .'</td><td colspan="12" align="center">Site is Offline</td></tr>';
           continue;
         } else if ($tdiff > 7200){
           $table .= 'bgcolor="orange"';
           $format = "%d %b %I:%M %p";
         } else if ($tdiff > 3600){
           $table .= 'bgcolor="green"';
           $format = "%d %b %I:%M %p";
         } else {
           $format = "%I:%M %p";
         }
         $table .= ">" . strftime($format, $parts["ts"]) ."</td>
 <td align='center'>". $parts["tmpf"] ."(<font color=\"#ff0000\">".
 round($parts["max_tmpf"],0) ."</font>/<font color=\"#0000ff\">".
 round($parts["min_tmpf"],0) ."</font>)</td>
          <td>". $parts["dwpf"] ."</td>
          <td>". $parts["feel"] ."</td>
          <td>". $parts["relh"] ."</td>
          <td>". $parts["drct"] ."</td>
          <td>". $parts["sknt"] ;
          if (intval($parts["gust"]) > 0){
            $table .= "G". $parts["gust"];
          } $table .= "</td>";
          $table .= "<td>". $parts["peak"] ." @ ". strftime("%I:%M %p", $parts["peak_ts"]) ."</td>
          <td>". $parts["alti"] ."</td>
          <td>". $parts["vsby"] ."</td>
          <td>". $parts["phour"] ."</td>
          <td>". $parts["pday"] ."</td></tr>\n";
}
$c = "javascript:new_window('http://mesonet.agron.iastate.edu/GIS/apps/php/currents.phtml?layers[]=radar&layers[]=labels&network=AWOS&var=";
$table .= <<<EOF
</tbody><tfoot>
<tr>
 <td colspan=3></td>
 <td><a href="{$c}tmpf');">Plot</a>
    (<a href="{$c}max_tmpf');">Plot</a> /
     <a href="{$c}min_tmpf');">Plot</a>)</td>
 <td><a href="{$c}dwpf');">Plot</a></td>
 <td><a href="{$c}feel');">Plot</a></td>
 <td><a href="{$c}relh');">Plot</a></td>
 <td colspan=2><a href="{$c}barb');">Plot</a></td>
 <td><a href="{$c}max_sknt');">Plot</a></td>
 <td><a href="{$c}alti');">Plot</a></td>
 <td><a href="{$c}vsby');">Plot</a></td>
 <td><a href="{$c}phour');">Plot</a></td>
 <td><a href="{$c}pday');">Plot</a></td>
</tr>
</tfoot>

</table>

<input type="submit" value="Add to Favorites">
<input type="reset" value="Reset">

</form>
EOF;
$t->content = $table;
$t->render("sortables.phtml");
?>
