<?php 
require_once "../../config/settings.inc.php";
require_once "../../include/myview.php";
require_once "../../include/forms.php";
require_once "../../include/mlib.php";

$t = new MyView();

$sortcol = isset($_GET["sortcol"]) ? xssafe($_GET["sortcol"]): "station";

$t->refresh = 60;
$t->title = "AWOS Network Current Conditions";
$t->current_network = "AWOS";

  $vals = Array("station" => "Station ID", "ts" => "Ob Time",
  		"relh" => "Relative Humidity", "name" => "Site Name",
  		"min_tmpf" => "Today's Low Temperature",
  		"max_tmpf" => "Today's High Temperature",
  		"tmpf" => "Temperature", "dwpf" => "Dew Point", "vsby" => "Visibility",
  		"sknt" => "Speed", "peak" => "Peak Gust [knots]","alti" => "Altimeter",
  		"peak_ts" => "Gust Time", "phour" => "1 hr Rainfall", "pday" => "Today Rainfall", "feel" => "Feels Like");

if (!array_key_exists($sortcol, $vals)) $sortcol = "name";

$t->breadcrumbs = <<<EOF
<ol class="breadcrumb">
 <li><a href="/AWOS/">AWOS Homepage</a></li>
 <li class="active">Current Conditions</li>
</ol>
EOF;
$table = <<<EOF

<h3>Current AWOS Conditions</h3>

<p>** This page will automatically refresh every five minutes.

<br>Sorted by: <b>({$vals[$sortcol]})</b>  &nbsp; &nbsp; 
Click on a column to sort it.<br>

<form name="asdf" method="GET" action="/my/current.phtml">

<table class="table table-condensed table-striped table-bordered">
<thead>
<tr>
  <th rowspan=2>Add</th>
  <th rowspan=2><a href="current.phtml?sortcol=station">ID:</a></th>
  <th rowspan=2><a href="current.phtml?sortcol=name">Name:</a></th>
  <th rowspan=2><a href="current.phtml?sortcol=ts">Ob Time</a></th>
  <th colspan=4>&nbsp;</th>
  <th colspan=3>Wind [knots]</th>
  <th colspan=2>&nbsp;</th>
  <th colspan=2>Rainfall</th></tr>

<tr>
  <th>
   <a href="current.phtml?sortcol=tmpf">Temp</a>
   (<a href="current.phtml?sortcol=max_tmpf">Hi</a> /
   <a href="current.phtml?sortcol=min_tmpf">Lo</a>)
 </th>
  <th><a href="current.phtml?sortcol=dwpf">DewP</a></th>
  <th><a href="current.phtml?sortcol=feel">Feels</a></th>
  <th><a href="current.phtml?sortcol=relh">RH%</a></th>
  <th>Dir</th>
  <th><a href="current.phtml?sortcol=sknt">Speed</a></th>
  <th><a href="current.phtml?sortcol=peak">Peak Gust</a>
   <br>@ <a href="current.phtml?sortcol=peak_ts">Time</a></th>
  <th><a href="current.phtml?sortcol=alti">Alti</a></th>
  <th><a href="current.phtml?sortcol=vsby">Vsby</a></th>
  <th><a href="current.phtml?sortcol=phour">Hour</a></th>
  <th><a href="current.phtml?sortcol=pday">Today</a></th>
</tr>
</thead><tbody>
EOF;

$jdata = file_get_contents("http://iem.local/api/1/currents.json?network=AWOS");
$jobj = json_decode($jdata, $assoc=TRUE);


foreach($jobj["data"] as $bogus => $iemob){
    $key = $iemob["station"];
    $mydata[$key] = $iemob;
    $mydata[$key]["ts"] = strtotime($iemob["local_valid"]);
    $mydata[$key]["sped"] = $mydata[$key]["sknt"] * 1.15078;
    if ($mydata[$key]["tmpf"] > -99) {
      $mydata[$key]["tmpf"] = round($mydata[$key]["tmpf"], 0);
      $mydata[$key]["dwpf"] = round($mydata[$key]["dwpf"], 0);
   } else {
      $mydata[$key]["tmpf"] = "M";
      $mydata[$key]["dwpf"] = "M";
   } 
   $mydata[$key]["peak_ts"] = 0;
   if ($mydata[$key]["max_gust"] > $mydata[$key]["max_sknt"]){
      $mydata[$key]["peak"] = $mydata[$key]["max_gust"];
      $mydata[$key]["peak_ts"] = strtotime($mydata[$key]["local_max_gust_ts"]);
    } else {
      $mydata[$key]["peak"] = $mydata[$key]["max_sknt"];
      if ($mydata[$key]["local_max_sknt_ts"]) {
        $mydata[$key]["peak_ts"] = strtotime($mydata[$key]["local_max_sknt_ts"]);
     }   
 }

	if ($mydata[$key]["pday"] < 0) $mydata[$key]["pday"] = 0;                                                                               
  }

 $finalA = Array();
 $finalA = aSortBySecondIndex($mydata, $sortcol, "desc");
 $now = time();
 foreach($finalA as $key => $parts){ 
        $table .= "<tr>\n 
         <td><input type=\"checkbox\" name=\"st[]\"  value=\"".$key."\"></td>";

         $tdiff = $now - $parts["ts"];
         $table .= sprintf("<td><a href=\"/sites/site.php?station=%s&network=AWOS\">%s</a></td>", $key, $key );
         $table .= sprintf("<td>%s</td>", $parts["name"]);
         $table .= "<td ";
         if ($tdiff > 10000){
           $format = "%d %b %I:%M %p";
           $table .= 'bgcolor="red"> '. strftime($format, $parts["ts"]) .'</td><td colspan="12" align="center">Site is Offline</td></tr>';
           continue;
         } else if ($tdiff > 7200){
           $table .= 'bgcolor="orange"';
           $format = "%d %b %I:%M %p";
         } else if ($tdiff > 3600){
           $table .= 'bgcolor="green"';
           $format = "%d %b %I:%M %p";
         } else {
           $format = "%I:%M %p";
         }
         $table .= ">" . strftime($format, $parts["ts"]) ."</td>
 <td align='center'>". $parts["tmpf"] ."(<font color=\"#ff0000\">".
 round($parts["max_tmpf"],0) ."</font>/<font color=\"#0000ff\">".
 round($parts["min_tmpf"],0) ."</font>)</td>
          <td>". $parts["dwpf"] ."</td>
          <td>". round($parts["feel"], 1) ."</td>
          <td>". round($parts["relh"], 0) ."</td>
          <td>". $parts["drct"] ."</td>
          <td>". $parts["sknt"] ;
          if (intval($parts["gust"]) > 0){
            $table .= "G". $parts["gust"];
          } $table .= "</td>";
          $table .= "<td>". $parts["peak"] ." @ ". strftime("%I:%M %p", $parts["peak_ts"]) ."</td>
          <td>". $parts["alti"] ."</td>
          <td>". $parts["vsby"] ."</td>
          <td>". $parts["phour"] ."</td>
          <td>". $parts["pday"] ."</td></tr>\n";
}
$table .= <<<EOF
</tbody>

</table>

<input type="submit" value="Add to Favorites">
<input type="reset" value="Reset">

</form>
EOF;
$t->content = $table;
$t->render("sortables.phtml");
?>
