<?php 
include("../../config/settings.inc.php");
  $TITLE = "IEM | AWOS Network";
$THISPAGE = "networks-awos";
include("$rootpath/include/header.php"); 
?>

<div class="dashboard">
<ul>
 <li><span style="font-size: 1.3em;">AWOS<br />Quick Links</span></li>
 <li><a href="current.phtml"><img src="../images/view_text.png" /><br />Currents</a></li>
 <li><a href="../request/awos/1min.php"><img src="../images/down.png" /><br />Download</a></li>
 <li><a href="../sites/locate.php?network=AWOS"><img src="../images/find.png" /><br />Locate Site</a></li>
</ul>
</div>

<h3 class="heading">AWOS Network</h3><p>

<div class="text">
<table><tr><td style="width: 650px" valign="top">
Automated Weather Observing System (AWOS) stations are often
grouped together with the ASOS stations, but they are not the same.  Like the
ASOS, the AWOS sensors primarily provide the aviation community with current
weather observations.  The data is also transmitted by phone lines or satellite
uplinks for use by other agencies. The AWOS sites are either 
federally operated by the FAA or 
some of them are locally maintained by state agencies.[1]</p> </td><td>

<div class="ninfo">
<b><u>AWOS</u></b>
<br>Reports: 3x per Hour
<br>Stations: 37
<br><a href="<?php echo $rooturl; ?>sites/locate.php?network=AWOS">Locations</a>
</div></td></tr></table>

<table width="100%">
<tr><td width="50%" valign="TOP">

<h3 class="subtitle">Docs:</h3>
<ul>
<li><b>27 Oct 2004:</b> <a href="<?php echo $rooturl; ?>/onsite/news.phtml?id=300">About AWOS 80+ Dewpoints</a></li>
<li><a href="manual/">ADAS/AWOS Manual</a></li>
<li><a href="skyc.phtml">Note about archived cloud coverages</a></li>
</ul>

<h3 class="subtitle">Current AWOS Data:</h3>
<UL>
 <li><a href="current.phtml">Sortable Current Conditions</a></li>
 <li><a href="<?php echo $rooturl; ?>/data/mesonet.gif">Combined Mesonet</a></li>
 <li><a href="<?php echo $rooturl; ?>/data/awos.gif">AWOS Mesonet</a></li>
 <li><a href="<?php echo $rooturl; ?>/data/heat.gif">Heat Index</a></li>
 <li><a href="<?php echo $rooturl; ?>/data/wcht.gif">Wind Chill Index</a></li>
 <li><a href="<?php echo $rooturl; ?>/data/relh.gif">Relative Humidity</a></li>
 <li><a href="<?php echo $rooturl; ?>/data/awos_rtp.shef">12Z RTP First Guess</a></li>
 <li><a href="<?php echo $rooturl; ?>/data/awos_rtp_00z.shef">00Z RTP First Guess</a></li>
 <li><a href="../plotting/hr/1station.php">Plot Recent Timeseries</a></li>

</UL>

<p><h3 class="subtitle">Historical Data:</h3>

Observations from the AWOS network are saved in 1 minute intervals.  The DOT
provides the IEM with a monthly update of this 1 minute dataset.  The 1 minute
data from the previous month is uploaded to the IEM server around the first 
week of the month.

<ul>
<li><a href="/plotting/awos/1station_1min.php">Daily Data Plotting</a></li>
<li><a href="/request/awos/1min.php">Download/View/Plot Archived Data</a></li>
<li><a href="/AWOS/reports/2002precip.phtml">2002 Precipitation Totals</a></li>
<li><a href="/AWOS/reports/2003precip.phtml">2003 Precipitation Totals</a></li>
<li><a href="/AWOS/reports/2004precip.phtml">2004 Precipitation Totals</a></li>
<li><a href="/AWOS/reports/2005precip.phtml">2005 Precipitation Totals</a></li>
<li><a href="/AWOS/reports/2006precip.phtml">2006 Precipitation Totals</a></li>
<li><a href="/AWOS/reports/2007precip.phtml">2007 Precipitation Totals</a></li>
<li><a href="/AWOS/reports/2008precip.phtml">2008 Precipitation Totals</a></li>
<li><a href="/AWOS/reports/2009precip.phtml">2009 Precipitation Totals</a></li>
<li><a href="reports/mon_prec.php?year=2010">2010 Precipitation Totals</a></li>
<li><a href="/cgi-bin/precip/catAZOS.py">Hourly Precipitation</a> tables</li>
</ul>

</td><td valign="top" width="50%"> 

<h3 class="subtitle">MADIS QC Mesages:</h3>
<ul>
 <li><a href="/QC/madis/network.phtml?network=AWOS">Raw QC Values</a></li>
 <li><a href="http://www.madis-fsl.org/qcms_data/qc4/qchour.txt">Hourly</a></li>
 <li><a href="http://www.madis-fsl.org/qcms_data/qc4/qcday.txt">Daily</a></li>
 <li><a href="http://www.madis-fsl.org/qcms_data/qc4/qcweek.txt">Weekly</a></li>
 <li><a href="http://www.madis-fsl.org/qcms_data/qc4/qcmonth.txt">Monthly</a></li>
</ul>

<h3 class="subtitle">Comparisons:</h3>
<ul>
 <li><a href="/plotting/compare/">Generate Interactive Comparisons</a> between two sites of your choice.</li>
  <li><a href="/wx/data/models/ruc2_iem_T.gif">Temperatures vs RUC2 Model</a></li>
  <li><a href="/data/temps.gif">Temperatures vs RWIS Network</a></li>
  <li><a href="/data/snet/Tcompare.gif">Temperatures vs SchoolNet Network</a></li>
  <li><a href="/wx/data/models/ruc2_iem_Td.gif">Dew Points vs RUC2 Model</a></li>
  <li><a href="/data/dewps.gif">Dew Points vs RWIS Network</a></li>
  <li><a href="/data/snet/Dcompare.gif">Dew Points vs SchoolNet Network</a></li>
  <li><a href="/wx/data/models/ruc2_iem_V.gif">Winds vs RUC2 Model</a></li>
  <li><a href="/data/winds.gif">Winds vs RWIS Network</a></li>
  <li><a href="/wx/data/models/ruc2_iem_Rh.gif">Relative Humidity vs RUC2 Model</a></li>
  <li><a href="/data/snet/Pcompare.gif">Pressure vs SchoolNet Network (mb)</a></li>
  <li><a href="/data/snet/P2compare.gif">Pressure vs SchoolNet Network (in)</a></li>
</ul>


<h3 class="subtitle">QC Info:</h3>
<ul>
<li>Sites <a href="/QC/offline.php">offline</a> [<a href="http://mesonet.agron.iastate.edu/GIS/apps/stations/offline.php?network=awos">Graphical View</a>]</li>
<li><a href="http://mesonet.agron.iastate.edu/QC/tickets.phtml">Open Trouble Tickets</a></li>
</ul>

<h3 class="subtitle">Hourly Mesonet + NEXRAD:</h3>
<UL>
	<li><a href="../data/DMX_radar.gif">Des Moines</a></li>
        <li><a href="../data/OAX_radar.gif">Omaha</a></li>
        <li><a href="../data/DVN_radar.gif">Davenport</a></li>
	<li><a href="../data/FSD_radar.gif">Sioux Falls</a></li>
        <li><a href="../data/ARX_radar.gif">LaCrosse</a></li>
</UL>

</td></tr></table>

<b>References:</b><br>
<b>1</b> <a href="http://www.faa.gov/asos/whatawos.htm">http://www.faa.gov/asos/whatawos.htm</a>
 , viewed: 21 Feb 2002

<br><br></div>

<?php include("$rootpath/include/footer.php"); ?>
