<?php
require_once "../../config/settings.inc.php";
define("IEM_APPID", 64);
require_once "../../include/myview.php";
$t = new MyView();
$t->title = "Iowa AWOS Network";
$t->content = <<<EOM

<h3>Iowa AWOS Network</h3>

<p>The term "AWOS" is typically applied to a subset of ASOS stations (airport
weather stations) that are not federally owned.  Over the years, the IEM has
collected some datasets and products that are limited to AWOS sites in Iowa.
This page details these Iowa-specific AWOS products.  The main page for data
from these sites resides with the <a href="/ASOS/">ASOS Mainpage</a>.</p>

<div class="row">
<div class="col-md-6">

<h3>Docs:</h3>
<ul>
<li><b>27 Oct 2004:</b> <a href="/onsite/news.phtml?id=300">About AWOS 80+ Dewpoints</a></li>
<li><a href="manual/">ADAS/AWOS Manual</a></li>
<li><a href="skyc.phtml">Note about archived cloud coverages</a></li>
</ul>

<h3>Iowa AWOS Specific Data:</h3>
<ul>
 <li><a href="/data/awos_rtp.shef">12Z RTP First Guess</a></li>
 <li><a href="/data/awos_rtp_00z.shef">00Z RTP First Guess</a></li>
</ul>

<p><h3>Archived One Minute Data:</h3>

<p>The Iowa DOT kept an one minute interval archive of their data between
1995 and <strong>1 April 2011</strong>.  Due to communication changes, 
this archival was discontinued.  You can download data from this archive at the 
links below. 

<ul>
  <li><a href="/plotting/awos/1station_1min.php">Daily Data Plotting</a></li>
  <li><a href="/request/awos/1min.php">Download/View/Plot Archived Data</a></li>
</ul>

</div>
<div class="col-md-6">

<h3>QC Info:</h3>
<ul>
<li>Sites <a href="/QC/offline.php">offline</a></li>
<li><a href="/QC/tickets.phtml">Open Trouble Tickets</a></li>
</ul>

</div>
</div>

EOM;
$t->render('single.phtml');
