<?php 
require_once "../../config/settings.inc.php";
define("IEM_APPID", 64);
require_once "../../include/myview.php";
$t = new MyView();
$t->title = "AWOS Network";
$t->thispage = "networks-awos";
$t->content = <<<EOM

<div class="row">
 <div class="col-md-3">
 <span style="font-size: 1.3em;">AWOS<br />Quick Links</span>
 </div>
 <div class="col-md-3">
 <a href="current.phtml"><img src="../images/view_text.png" /><br />Currents</a>
 </div>
 <div class="col-md-3">
 <a href="/request/download.phtml?network=AWOS"><img src="../images/down.png" /><br />Download</a>
 </div>
	<div class="col-md-3">
	<a href="/sites/locate.php?network=AWOS"><img src="../images/find.png" /><br />Locate Site</a>
	</div>
</div>

<h3">AWOS Network</h3><p>

<div class="well pull-right">
<b><u>AWOS</u></b>
<br>Reports: 12x per Hour
<br>Stations: 45
<br><a href="/sites/locate.php?network=AWOS">Locations</a>
</div>

Automated Weather Observing System (AWOS) stations are often
grouped together with the ASOS stations, but they are not the same.  Like the
ASOS, the AWOS sensors primarily provide the aviation community with current
weather observations.  The data is also transmitted by phone lines or satellite
uplinks for use by other agencies. The AWOS sites are either 
federally operated by the FAA or 
some of them are locally maintained by state agencies.[1]</td>
<td>

<div class="row">
<div class="col-md-6">

<h3>Docs:</h3>
<ul>
<li><b>27 Oct 2004:</b> <a href="/onsite/news.phtml?id=300">About AWOS 80+ Dewpoints</a></li>
<li><a href="manual/">ADAS/AWOS Manual</a></li>
<li><a href="skyc.phtml">Note about archived cloud coverages</a></li>
</ul>

<h3>Current AWOS Data:</h3>
<ul>
 <li><a href="current.phtml">Sortable Current Conditions</a></li>
 <li><a href="/data/mesonet.gif">Combined Mesonet</a></li>
 <li><a href="/data/awos.gif">AWOS Mesonet</a></li>
 <li><a href="/data/heat.gif">Heat Index</a></li>
 <li><a href="/data/wcht.gif">Wind Chill Index</a></li>
 <li><a href="/data/relh.gif">Relative Humidity</a></li>
 <li><a href="/data/awos_rtp.shef">12Z RTP First Guess</a></li>
 <li><a href="/data/awos_rtp_00z.shef">00Z RTP First Guess</a></li>
 <li><a href="/data/LOCDSMMETAR.dat">METAR formatted latest obs</a></li>
		
</ul>

<p><h3>Archived One Minute Data:</h3>

<p>The Iowa DOT kept an one minute interval archive of their data between
1995 and <strong>1 April 2011</strong>.  Due to communication changes, 
this archival was discontinued.  You can download data from this archive at the 
links below.  You can use <a href="/request/download.phtml?network=AWOS">this link</a>
for 5-10 minute interval data after 1 April 2011.

<ul>
  <li><a href="/plotting/awos/1station_1min.php">Daily Data Plotting</a></li>
  <li><a href="/request/awos/1min.php">Download/View/Plot Archived Data</a></li>
</ul>

<p><h3 class="subtitle">Historical Data:</h3>

<p>The IEM archives the routine METAR reports from this network at up to 
5 minute intervals.

<ul>
<li><a href="/request/download.phtml?network=AWOS">Download</a></li>
<li><a href="/AWOS/reports/mon_prec.php">Monthly Precipitation Totals</a></li>
<li><a href="/cgi-bin/precip/catAZOS.py">Hourly Precipitation</a> tables</li>
</ul>

</div>
<div class="col-md-6">

<h3>MADIS QC Mesages:</h3>
<ul>
 <li><a href="/QC/madis/network.phtml?network=AWOS">Raw QC Values</a></li>
 <li><a href="http://www.madis-fsl.org/qcms_data/qc4/qchour.txt">Hourly</a></li>
 <li><a href="http://www.madis-fsl.org/qcms_data/qc4/qcday.txt">Daily</a></li>
 <li><a href="http://www.madis-fsl.org/qcms_data/qc4/qcweek.txt">Weekly</a></li>
 <li><a href="http://www.madis-fsl.org/qcms_data/qc4/qcmonth.txt">Monthly</a></li>
</ul>

<h3>Comparisons:</h3>
<ul>
 <li><a href="/plotting/compare/">Generate Interactive Comparisons</a> between two sites of your choice.</li>
  <li><a href="/wx/data/models/ruc2_iem_T.gif">Temperatures vs RUC2 Model</a></li>
  <li><a href="/data/temps.gif">Temperatures vs RWIS Network</a></li>
  <li><a href="/data/snet/Tcompare.gif">Temperatures vs SchoolNet Network</a></li>
  <li><a href="/wx/data/models/ruc2_iem_Td.gif">Dew Points vs RUC2 Model</a></li>
  <li><a href="/data/dewps.gif">Dew Points vs RWIS Network</a></li>
  <li><a href="/data/snet/Dcompare.gif">Dew Points vs SchoolNet Network</a></li>
  <li><a href="/wx/data/models/ruc2_iem_V.gif">Winds vs RUC2 Model</a></li>
  <li><a href="/data/winds.gif">Winds vs RWIS Network</a></li>
  <li><a href="/wx/data/models/ruc2_iem_Rh.gif">Relative Humidity vs RUC2 Model</a></li>
  <li><a href="/data/snet/Pcompare.gif">Pressure vs SchoolNet Network (mb)</a></li>
  <li><a href="/data/snet/P2compare.gif">Pressure vs SchoolNet Network (in)</a></li>
</ul>


<h3>QC Info:</h3>
<ul>
<li>Sites <a href="/QC/offline.php">offline</a></li>
<li><a href="/QC/tickets.phtml">Open Trouble Tickets</a></li>
</ul>

<h3>Hourly Mesonet + NEXRAD:</h3>
<UL>
	<li><a href="/data/DMX_radar.gif">Des Moines</a></li>
        <li><a href="/data/OAX_radar.gif">Omaha</a></li>
        <li><a href="/data/DVN_radar.gif">Davenport</a></li>
	<li><a href="/data/FSD_radar.gif">Sioux Falls</a></li>
        <li><a href="/data/ARX_radar.gif">LaCrosse</a></li>
</UL>

</div>
</div>


<b>References:</b><br>
<b>1</b> <a href="http://www.faa.gov/asos/whatawos.htm">http://www.faa.gov/asos/whatawos.htm</a>
 , viewed: 21 Feb 2002

EOM;
$t->render('single.phtml');
?>