ALTER TABLE current ADD ice_accretion_1hr real;
ALTER TABLE current ADD ice_accretion_3hr real;
ALTER TABLE current ADD ice_accretion_6hr real;
ALTER TABLE current_log ADD ice_accretion_1hr real;
ALTER TABLE current_log ADD ice_accretion_3hr real;
ALTER TABLE current_log ADD ice_accretion_6hr real;
ALTER TABLE current_tmp ADD ice_accretion_1hr real;
ALTER TABLE current_tmp ADD ice_accretion_3hr real;
ALTER TABLE current_tmp ADD ice_accretion_6hr real;
