<?php
include("../../config/settings.inc.php");
$TITLE = "IEM | Pollen Dispersion Modelling";
include("$rootpath/include/header.php"); ?>

<h3 class="heading">Maize Pollen Dispersion</h3>

<p>East source:<br /><img src="share/rt/east.gif">
<p>West source:<br /><img src="share/rt/west.gif">
<p>North source:<br /><img src="share/rt/north.gif">
<p>Sourth source:<br /><img src="share/rt/south.gif">

<?php include("$rootpath/include/footer.php"); ?>
