#!/bin/csh -f
# Run once hourly, I believe, all of this needs to go at some point.

set ftime="`date -u +'%Y%m%d%H'`00"

csh createGrids.csh
csh SDMESONET_plot.csh
csh MW_mesonet.csh
csh TEMPS_plot.csh
csh DEWPS_plot.csh
csh WINDS_plot.csh
csh DMX_overlay.csh
csh OAX_overlay.csh
csh DVN_overlay.csh
csh FSD_overlay.csh
csh ARX_overlay.csh
csh EAX_overlay.csh
csh MPX_overlay.csh
csh HEAT_plot.csh
csh WCHT_plot.csh
csh RELH_plot.csh
csh ASOS_plot.csh

cd black
csh surfaceContours.csh
