<?php 
include_once "../../config/settings.inc.php";
require_once "../../include/myview.php";
require_once "../../include/iemprop.php";
$gmapskey = get_iemprop("google.maps.key");

$t = new MyView();
$t->title = "Confidential MEC Stuff";
$t->headextra = <<<EOF
<script src="https://maps.googleapis.com/maps/api/js?key={$gmapskey}" type="text/javascript"></script>
<script src="/assets/openlayers/2.13.1/OpenLayers.js"></script>
<script src="map.js"></script>
EOF;
$t->bodyextra = " onload=\"init();\"";
$t->content = <<<EOF

<span class="badge">NEW!</span> <a href="turbine_ts.phtml">Plot Single Turbine Timeseries</a>
<br />
<a href="map_power.phtml">Map / Power Diagnostics by Minute</a>
		<hr>

<span style="color: #0000ff;">Expansion 1</span>
<span style="color: #00ff00;">Expansion 2</span>
<span style="color: #ff0000;">Expansion 3</span>		
<span style="color: #00ffff;">Expansion 4</span>
		

<div id="map" style="width:100%; height:500px;"></div>

<img src="i/0.png" />

EOF;

$t->render('single.phtml');
?>
