<?php 
include_once "../../config/settings.inc.php";
require_once "../../include/myview.php";
require_once "../../include/forms.php";
require_once "../../include/database.inc.php";

$day = isset($_GET["day"]) ? $_GET["day"] : 30;
$month = isset($_GET["month"]) ? $_GET["month"] : 6;
$year = isset($_GET["year"]) ? $_GET["year"] : 2010;
$turbinename = isset($_GET["turbinename"]) ? $_GET["turbinename"] : "I 050-350";

$yselect = yearSelect2(2008, $year, "year");
$mselect = monthSelect($month, "month");
$dselect = daySelect2($day, "day");

$pgconn = pg_connect("dbname=mec host=iemdb-mec.local user=mesonet port=5432");
$ar = Array();
$res = pg_query($pgconn, "SELECT turbinename from turbines ORDER by turbinename ASC");
for ($i=0; $row=@pg_fetch_assoc($res,$i);$i++){
	$ar[$row['turbinename']] = $row['turbinename'];
}
$sselect = make_select("turbinename", $turbinename, $ar);

$ts = mktime(12, 0, 0, $month, $day, $year);
$img = sprintf("turbine_ts_%s_%s.png", date('Ymd', $ts), $turbinename);


$t = new MyView();
$t->title = "Confidential MEC Stuff";
$t->content = <<<EOF
<ol class="breadcrumb">
 <li><a href="/mec/">MEC Mainpage</a></li>
 <li class="active">Plot Single Turbine Power</li> 
</ol>

<form method="GET" name='a'>

<table class="table table-condensed" style="width: auto">
<thead><tr>
<th>Date:</th><th>Select Turbine:</th></tr>
</thead>
<tbody>
<tr><td>$yselect $mselect $dselect</td>
<td>{$sselect}</td>
</tr>
</tbody>
</table>

		
		<input type="submit" value="Make Plot" />
		</form>

<p><img src="$img" />

EOF;

$t->render('single.phtml');
?>
