<?php
include("../../config/settings.inc.php");
include("$rootpath/include/database.inc.php");
$THISPAGE = "severe-river";
include("$rootpath/include/header.php");
include("$rootpath/include/wfoLocs.php");
include("$rootpath/include/forms.php");
$wfo = isset($_GET["wfo"]) ? substr($_GET["wfo"],0,3): "DMX";

$postgis = iemdb("postgis");
$sevcol = Array(
 "N" =>"#0f0",
 "0" =>"#ff0",
 "1" =>"#ff9900",
 "2" =>"#f00",
 "3" =>"#f0f",
 "U" =>"#fff");

$nwsli_limiter = "";
if (isset($_GET["dvn"])){
 $nwsli_limiter = "and r.nwsli IN ('FLTI2', 'CMMI4', 'LECI4', 'RCKI2', 'ILNI2', 'MUSI4', 'NBOI2', 'KHBI2', 'DEWI4', 'CNEI4', 'CJTI4', 'WAPI4','LNTI4', 'CMOI2', 'JOSI2', 'MLII2','GENI2')";
 echo "<style>
#iem-header {
  display: none;
  visibility: hidden;
}
#iem-footer {
  display: none;
  visibility: hidden;
}
body {
  background: #fff;
  font-size: smaller;
}
</style>";
}

$sql = "select r.*, h.* from hvtec_nwsli h, riverpro r,
  (select distinct hvtec_nwsli from warnings_2009 WHERE 
   status NOT IN ('EXP','CAN') and phenomena = 'FL' and 
   significance = 'W' and wfo = '$wfo') as foo
   WHERE foo.hvtec_nwsli = r.nwsli and r.nwsli = h.nwsli $nwsli_limiter";
$rs = pg_exec($postgis, $sql);

$rivers = Array();
for($i=0;$row=@pg_fetch_array($rs,$i);$i++)
{
  $river = $row["river_name"];
  @$rivers[$river] .= sprintf("<tr><th style='background: %s;'>%s<br />%s</th><td>%s</td><td>%s</td><td>%s</td></tr>",$sevcol[$row["severity"]], $row["name"],
   $row["nwsli"], $row["stage_text"], $row["flood_text"], 
   $row["forecast_text"]);
}
?>

<h3>River Forecast Point Monitor by NWS WFO</h3>

<?php
echo "<p><form method='GET'>";
echo 'Select NWS Forecast Office:'. wfoSelect($wfo);
echo "<input type='submit'>";
echo "</form>";
?>

<table border='1' cellpadding='2' cellspacing='0' style="margin: 5px;">
<tr>
 <th>Key:</th>
 <td style="background: #ff0;">Near Flood Stage</td>
 <td style="background: #ff9900;">Minor Flooding</td>
 <td style="background: #f00;">Moderate Flooding</td>
 <td style="background: #f0f;">Major Flooding</td>
</tr></table>

<?php
echo "<p><table border='1' cellpadding='2' cellspacing='0'>";
$rvs = array_keys($rivers);
asort($rvs);

while (list($idx, $key) = each($rvs))
{
  echo "<tr><th colspan='4' style='background: #eee; text-align: left;'>$key</th></tr>";
  echo $rivers[$key];

}

echo "</table>";

include("$rootpath/include/footer.php");
?>
