<?php 
require_once "../../../config/settings.inc.php";
require_once "../../../include/imagemaps.php";
require_once "../../../include/myview.php";
define("IEM_APPID", 146);
$t = new MyView();
$t->jsextra=<<<EOF
<script src='/vendor/jquery-ui/1.11.4/jquery-ui.min.js'></script>
<script src='/vendor/jquery-ui-timepicker/1.5.3/jquery-ui-timepicker-addon.js'></script>
<script type="text/javascript">
$(function(){
	$("#startdate").datetimepicker({
		controlType: 'select',
		minDate: new Date(1947, 1, 1, 0, 0),
		showMinute: false
});
	$("#enddate").datetimepicker({
		controlType: 'select',
		minDate: new Date(1947, 1, 1, 0, 0),
		showMinute: false
});
});
</script>
EOF;
$t->headextra= <<<EOF
<link rel="stylesheet" href="/vendor/jquery-ui/1.11.4/jquery-ui.min.css">
<link rel="stylesheet" href="/vendor/jquery-ui/1.11.4/jquery-ui.theme.min.css">
<link rel="stylesheet" href="/vendor/jquery-ui-timepicker/1.5.3/jquery-ui-timepicker-addon.css">		
EOF;
$t->title = "Rawinsonde Data Archive";
$nselect = networkSelect("RAOB", "OAX");
$t->content = <<<EOF
<h3>Rawinsonde (RAOB) Data Archive</h3>

<p>The IEM proceses and archives Rawinsonde (RAOB) data made available on the
<a href="http://rucsoundings.noaa.gov">rucsoundings.noaa.gov</a> website.  This
 archive also contains data from other sources to backfill it to the 1940s.  Data
 for the United States and Canada is available. This
 data are vertical profiles of the atmosphere taken from weather balloons released
 twice daily.</p>
 
 <h4>Available Tools:</h4>
<ul>
    <li><a href="list.phtml">List Sounding Parameters per Year</a></li>
    <li><a href="/plotting/auto/?q=150">View Sounding Percentiles</a> (Autoplot 150)</li>
    <li><a href="/plotting/auto/?q=198">Sounding Monthly Min/Max values</a> (Autoplot 198)</li>
    <li><a href="/plotting/auto/?q=212">Sounding Yearly Timeseries</a> (Autoplot 212)</li>
    <li><a href="https://www.spc.noaa.gov/exper/soundingclimo/">SPC Sounding Climatology Page</a></li>
</ul>

<h4>Download Data</h4>

<p>This form provides a simple comma delimited file of RAOB data, the columns
 should be self-explainatory except the 'levelcode' column.  Those values 
 provide metadata on that level of data.  The start time is inclusive and
 end time is exclusive.  Special soundings should be in this archive as well.

<table><tr><td valign="top">
<strong>Level Codes</strong><br />
<ul>
   <li>4 = mandatory level</li>
   <li>5 = significant level</li>
   <li>6 = wind level (PPBB)</li> 
   <li>7 = tropopause level</li>
   <li>8 = maximum wind level</li>
   <li>9 = surface level</li>
</ul>
</td><td>
<strong>Output Datafile Columns</strong>
<br /><pre>
station      3 or 4 character station identifier
validUTC     RAOB Launch Cycle Time in UTC
levelcode    Level Code for this observation
pressure_mb  Pressure of data in millibar
height_m     Height above sea level m
tmpc         Air Temperature in C
dwpc         Dew Point Temperature in C
drct         Wind Direction in deg from North
speed_kts    Wind Speed in knots
bearing      Balloon bearing in degree
range_sm     Ballon range from launch in statute miles
</pre>
</td>
</table>
<form method="GET" action="/cgi-bin/request/raob.py">
<table class="table table-bordered">
<tr><th>Select Site: {$nselect}</th>
<td>Start Time: <input type="text" name="sts" id="startdate" width="20"/></td>
<td>End Time: <input type="text" name="ets" id="enddate" width="20" /></td>
<td><input type="checkbox" name="dl" />Download to disk</td>
<td><input type="submit" value="Giveme Data!" /></td>
</tr>
</table>
</form>

<h4>JSON(P) Webservice</h4>

<p>A jsonp webservice exists that currently emits one RAOB profile at a time
provided a site and valid timestamp in UTC.  Please visit the 
<a href='/json/'>IEM JSON Services</a> for more details. For the impatient,
the example URI is:

<p><a href="/json/raob.py?ts=199905031200&station=KOUN">https://mesonet.agron.iastate.edu/json/raob.py?ts=199305031200&amp;station=KOUN</a>

EOF;
$t->render('single.phtml');
?>