<?php 
require_once "../../../config/settings.inc.php";
require_once "../../../include/forms.php";
require_once "../../../include/myview.php";
define("IEM_APPID", 146);
$t = new MyView();
$t->iem_resource = "RAOB";
$t->jsextra=<<<EOM
<script type="module" src="index.module.js"></script>
EOM;
$t->title = "Rawinsonde Data Archive";
$nselect = networkSelect("RAOB", "OAX");
$t->content = <<<EOM
<h3>Rawinsonde (RAOB) Data Archive</h3>

<p>For many moons, the IEM archived the soundings provided by the now defunct
NOAA rucsoundings website.  This website was shutdown during September 2024, so
the IEM started to ingest what was provided by the
<a href="https://www.spc.noaa.gov/exper/soundings/">Storm Prediction Center</a>
website. This source was found to be missing many sounding locations that the
IEM previous archived.  So the IEM started to ingest what is provided by
<a href="https://www.ncei.noaa.gov/data/integrated-global-radiosonde-archive/">
NCEI Integrated Global Radiosonde Archive</a>, but this archive is not in real-time.
So as of March 2025, this website contains near real-time data from SPC and is
backfilled eventually with data from the NCEI archive.</p>

<p>Data for the United States and Canada is available. This
 data are vertical profiles of the atmosphere taken from weather balloons released
 twice daily.</p>

 <h4>Available Tools:</h4>
<ul>
    <li><a href="list.phtml">List Sounding Parameters per Year</a></li>
    <li><a href="/plotting/auto/?q=150">View Sounding Percentiles</a> (Autoplot 150)</li>
    <li><a href="/plotting/auto/?q=198">Sounding Monthly Min/Max values</a> (Autoplot 198)</li>
    <li><a href="/plotting/auto/?q=212">Sounding Yearly Timeseries</a> (Autoplot 212)</li>
    <li><a href="https://www.spc.noaa.gov/exper/soundingclimo/">SPC Sounding Climatology Page</a></li>
</ul>

<h4>Download Data</h4>

<p>This form provides a simple comma delimited file of RAOB data, the columns
 should be self-explainatory except the 'levelcode' column.  Those values 
 provide metadata on that level of data.  The start time is inclusive and
 end time is exclusive.  Special soundings should be in this archive as well.

<table><tr><td valign="top">
<strong>Level Codes</strong><br />
<ul>
   <li>4 = mandatory level</li>
   <li>5 = significant level</li>
   <li>6 = wind level (PPBB)</li> 
   <li>7 = tropopause level</li>
   <li>8 = maximum wind level</li>
   <li>9 = surface level</li>
</ul>
</td><td>
<strong>Output Datafile Columns</strong>
<br /><pre>
station      3 or 4 character station identifier
validUTC     RAOB Launch Cycle Time in UTC
levelcode    Level Code for this observation, not always available
pressure_mb  Pressure of data in millibar
height_m     Height above sea level m
tmpc         Air Temperature in C
dwpc         Dew Point Temperature in C
drct         Wind Direction in deg from North
speed_kts    Wind Speed in knots
bearing      Balloon bearing in degree, not always available
range_sm     Ballon range from launch in statute miles, not always available
</pre>
</td>
</table>
<form method="GET" action="/cgi-bin/request/raob.py">
<table class="table table-bordered">
<tr><th>Select Site: {$nselect}</th>
<td>Start UTC Time: <input type="text" name="sts" width="20"/></td>
<td>End UTC Time: <input type="text" name="ets" width="20" /></td>
<td><input type="checkbox" name="dl" id="dd">
<label for="dd">Download to disk</label></td>
<td><input type="submit" value="Giveme Data!"></td>
</tr>
</table>
</form>

<h4>JSON(P) Webservice</h4>

<p>A JSON webservice exists for more programatic access, more information is
<a href="/json/raob.py?help">here</a>.</p>

EOM;
$t->render('single.phtml');
