<?php
require_once "../../../config/settings.inc.php";
define("IEM_APPID", 124);
require_once "../../../include/forms.php";
require_once "../../../include/myview.php";
require_once "../../../include/imagemaps.php";
$t = new MyView();
$t->title = "List Sounding Parameters by Year";

$stationselect = networkselect("RAOB", "_OAX");
$year = date("Y");
$yearselect = yearSelect(1947, $year);
$t->headextra = <<<EOM
<link type="text/css" href="/vendor/jquery-datatables/1.10.20/datatables.min.css" rel="stylesheet" />
EOM;
$t->content = <<<EOM
<ol class="breadcrumb">
    <li><a href="/archive/raob/">Sounding Archive Mainpage</a></li>
    <li class="active">List Soundings by Year</li>
</ol>
<p>This page presents a yearly listing of sounding parameters computed by the
IEM using <a href="https://unidata.github.io/MetPy/latest/index.html">Unidata's MetPy</a>.
<strong>Please use caution</strong> when using these parameters directly as they
can struggle with GIGO. A <a href="/api/1/docs/">JSON Webservice</a> backends this page.</p>

<p>
 <form name="local">
 <div class="row">
 <div class="col-md-6">
 <strong>Select Site:</strong>
     {$stationselect}
 </div>
 <div class="col-md-6">
 <strong>Select Year:</strong>
    {$yearselect}
 </div>
</form>
</p>

<br />
<p><button id="makefancy" type="button">Make Table Interactive</button></p>
<br />

<p>
 <div id="thetable">
 <table class="table table-bordered table-striped" id="datatable">
 <thead class="sticky">
<tr>
<th>ID</th>
<th>Valid</th>
<th>SBCAPE J/kg</th>
<th>MUCAPE J/kg</th>
<th>SBCIN J/kg</th>
<th>MUCIN J/kg</th>
<th>PrecipWater mm</th>
<th>LCL m</th>
<th>LFC m</th>
<th>EL m</th>
<th>Total Totals</th>
<th>SWEAT</th>
<th>SRH 0-3 km m2/s2</th>
<th>SRH 0-1 km m2/s2</th>
<th>SHR 0-6 km mps</th>
</tr>
</thead>
 <tbody>
 </tbody>
 </table>
 </div>
 </p>

EOM;
$t->jsextra = <<<EOM
<script src='/vendor/jquery-datatables/1.10.20/datatables.min.js'></script>
<script src="list.js?v=2"></script>
EOM;

$t->render('full.phtml');
