<?php
include("../../config/settings.inc.php");
$TITLE = "IEM | MiCCA Proposal";
include("$rootpath/include/header.php"); ?>

<center>
<h2 class="heading">Midwest Consortium for Climate Assessment </h2>
<h3 class="heading">Proposal Supplementary Materials </h3>

<img src="MiCCAmap.jpg" alt="Proposed MiCCA Region" width="500" height="386"/>
</center>

<p>We provide below a number of documents that illustrate our activities with stakeholders as well as scientific and technical accomplishments.  The title of each document listed below is also a link that will open the PDF document in another window (or frame) or download it to your computer.</p>

<p>
<b>Letters of Support</b>
<br><a href="missouri.dnr.pdf" target="_blank">Missouri Department of Natural Resources</a>
<br><a href="missouri.foragesystems.pdf" target="_blank">University Missouri Forage Systems Research Center</a>
<br><a href="missouri.kc.pdf" target="_blank">Kansas City Missouri Office of Environmental Quality</a>
<br><a href="iowa.rio.pdf" target="_blank">Rebuild Iowa Office</a>
<br><a href="iowa.apa.pdf" target="_blank">American Planners Association Iowa Chapter</a>
<br><a href="iowa.arc.pdf" target="_blank">Iowa Association of Regional Councils</a>
<br><a href="iowa.ilc.pdf" target="_blank">Iowa League of Cities</a>
<br><a href="iowa.linncounty.pdf" target="_blank">Iowa Linn County Board of Supervisors</a>
<br><a href="iowa.dnr.pdf" target="_blank">Iowa Department of Natural Resources</a>
<br><a href="iowa.nrcs.pdf" target="_blank">Iowa Natural Resources Conservation Service</a>
<br><a href="iowa.watercenter.pdf" target="_blank">Iowa Water Center (National Institutes for Water Resources)</a>
<br><a href="iowa.soybean.pdf" target="_blank">Iowa Soybean Association</a>
<br><a href="iowa.farmbureau.pdf" target="_blank">Iowa Farm Bureau</a>
<br><a href="iowa.bolkcom.pdf" target="_blank">Iowa Senator Joe Bolkcom</a>
<br><a href="nebraska.republicanriver.pdf" target="_blank">Republican River Restoration Partners</a>
<br><a href="nebraska.cornboard.pdf" target="_blank">Nebraska Corn Board</a>
<br><a href="ncis.pdf" target="_blank">National Crop Insurance Services</a>
<br><a href="usda.rma.pdf" target="_blank">USDA RMA Senior Actuary</a>
<br><a href="jawf.pdf" target="_blank">Joint Agricultural Weather Facility</a>
</p>

<p>
<b>Curriculum Vitae and Biographies</b>
<br>Dr. Christopher J. Anderson <a href="AndersonCV_2009.pdf" target="_blank"> CV </a> &nbsp; <a href="http://climate.agron.iastate.edu/ResearchTeam/AndersonChristopher.html" target="_blank"> Bio </a>
<br>Dr. Michael J. Hayes <a href="Hayes-FullCV-Sept09.pdf" target="_blank"> CV </a> &nbsp; <a href="http://drought.unl.edu/contact/hayes.htm" target="_blank"> Bio </a>
<br>Dr. Cody L. Knutson <a href="CV-knutson-10012006.pdf" target="_blank"> CV </a> &nbsp; <a href="http://drought.unl.edu/contact/staff.htm#cody" target="_blank"> Bio </a>
<br>Dr. Sara C. Pryor<a href="PryorCV_2009.pdf" target="_blank"> CV </a> &nbsp; <a href="http://www.indiana.edu/~geog/people/pryor.shtml" target="_blank"> Bio </a>
<br>Dr. Eugene S. Takle <a href="Takle-CV.pdf" target="_blank"> CV </a> &nbsp; <a href="http://www.meteor.iastate.edu/faculty/takle" target="_blank"> Bio </a>
<br>Dr. Syed E. Hasan <a href="Takle-CV.pdf" target="_blank"> CV </a> &nbsp; <a href="http://www.meteor.iastate.edu/faculty/takle" target="_blank"> Bio </a>
<br>Dr. Jimmy Adegoke <a href="Takle-CV.pdf" target="_blank"> CV </a> &nbsp; <a href="http://www.meteor.iastate.edu/faculty/takle" target="_blank"> Bio </a>
<br>Dr. Patrick E. Guinan <a href="Takle-CV.pdf" target="_blank"> CV </a> &nbsp; <a href="http://www.meteor.iastate.edu/faculty/takle" target="_blank"> Bio </a>
</p>

<p>
<b>Relevant Peer-Reviewed Literature</b>
<br> <a href="rcm.hydroprocesses.anderson.2003.pdf" target="_blank"> <b> Anderson, C. J. </b> , R. W. Arritt, <b> E. S.Takle </b>, Z. Pan, W. J. Gutowski, Jr., F. O. Otieno, R. da Silva, D. Caya, J. H. Christensen, D. Lüthi, M. A. Gaertner, C. Gallardo, F. Giorgi, S.-Y. Hong, C. Jones, H.-M. H. Juang, J. J. Katzfey, W. M. Lapenta, R. Laprise, J. W. Larson, G. E. Liston, J. L. McGregor, R. A. Pielke, Sr., J. O. Roads, J. A. Taylor, 2003: Hydrological processes in regional climate model simulations of the central United States flood of June-July 1993. Journal of Hydrometeor., 4, 584-598.</a>
<br><br> <a href="SWAT_UMRB_JGR.pdf" target="_blank"> Jha, M., Z. Pan, <b>E. S. Takle</b>, R. Gu, 2004:  Impact of climate change on stream flow in the Upper Mississippi River Basin:  A regional climate model perspective. J. Geophys. Res., 109, D09105, doi:10.1029/2003JD003686 </a>
<!---
<br>Knutson, C.L., (2008) Adaptation to Water Stress in the Great Plains. Water Resources IMPACT, Vol. 10(4), pp18-21
-->
<br><br> <a href="Role.of.water.conservation.in.drt.planning_Knutson_JSWC_2008.pdf" blank="_target"> <b>Knutson, C.L.</b>, (2008) The role of water conservation in drought planning. Journal of Soil and Water Conservation, Vol. 63(5) </a> 

<br><br> <a href="Reducing.Drought.Risk.Bridging.Theory.and.Practice.pdf" target="_blank"> <b> Hayes, M. J. </b>, O. V. Welhelmi, and <b> C. L. Knutson </b>, 2004: Reducing drought risk: Bridging theory and practice. Nat. Haz. Rev., 5, 106-113. </a>
<br><br> <a href="RSER764.pdf" target="_blank"> <b> Pryor S.C. </b> and Barthelmie R.J. (2010): Climate change impacts on wind energy: A review Renewable and Sustainable Energy Reviews 14 430-437. </a>
<br><br> <a href="pryor.climate.change.variability.midwest.Chapter1.pdf" target="_blank"> <b>Pryor S. C.</b>, and <b>G. S. Takle</b>, 2009: Climate variability, predictability and change: An introduction. In: Climate variability, predictability and change in the Midwestern USA. Indiana University Press, Bloomington, p 1-18.</a>
<br><br> <a href="2008JD011416.pdf" target="_blank"> <b> Pryor S.C. </b>, Barthelmie R.J., Young D.T., <b> Takle E.S. </b>, Arritt R.W, Flory D., Gutowski Jr W.J., Nunes A., Road J. (2009): Wind speed trends over the contiguous USA. Journal of Geophysical Research - Atmospheres 114, D14105 doi:10.1029/2008JD011416.</a>
<br><br> <a href="2009IJoC29p31.pdf" target="_blank"> <b>Pryor S.C.</b>, Howe J.A. and Kunkel K.E. (2009): How spatially coherent and statistically robust are temporal changes in extreme precipitation across the contiguous USA. International Journal of Climatology 29 31-45. </a>
<br><br> <a href="2008JD010251.pdf" target="_blank"> <b>Pryor S.C.</b> and Schoof J.T. (2008): Changes in the seasonality of precipitation over the contiguous USA. Journal of Geophysical Research 113, D21108, doi:10.1029/2008JD010251.</a>
<br><br> <a href="2008JAMC_p2477.pdf" target="_blank"> Schoof J.T. and <b> Pryor S.C. </b> (2008): On the proper order of Markov chain model for daily precipitation occurrence in the contiguous United States. Journal of Applied Meteorology and Climatology 47, 2477-2486.</a>
<br><br> <a href="IJC_2007p439.pdf" target="_blank"> Schoof J.T., <b> Pryor S.C.</b> and Robeson S.M. (2007): Downscaling daily maximum and minimum temperature in the Midwestern USA: A hybrid empirical approach. International Journal of Climatology 27 439-454. </a>
<br><br> <a href="JRNIRENG_2009_R.Singh.pdf" target="_blank"> Singh, R., M. J. Helmers, A. Kaleita, <b> E. S. Takle </b>, 2009: Potential impact of climate change on subsurface drainage in Iowa's subsurface drained landscapes. J. of Irrigation and Drainage Engineering, 135, 459-466. </a>
<br><br> <a href="BAMS 83-8_2002_TheDrought Monitor.pdf" target="_blank"> Svoboda, M., D. LeComte, <b> M. J. Hayes </b>, R. Heim, K. Gleason, J. Angel, B. Rippey, R. Tinker, M. Palecki, D. Stooksbury, D. Miskus, and S. Stephens, 2002: The drought monitor.  Bull. Amer. Meteor. Soc., 104, 1181-1190. </a>
<br><br> <a href="Takle.GRL.Streamflow.pdf" target="_blank"> <b>Takle, E. S.</b>, M. Jha, and <b>C. J. Anderson</b>, 2005: Hydrological cycle in the upper Mississippi River basin: 20th century simulations using multiple GCMs. Geophys. Res. Let., 32, doi:10.1029/2005GL023630</a>
<br><br> <a href="JGR_PIRCS_paper.pdf" target="_blank"> <b>Takle, E. S.</b>, W. .J. Gutowski, Jr., R. W. Arritt, Z. Pan, <b>C. J. Anderson</b>, R. Silva, D. Caya, S.-C. Chen, J. H. Christensen, S.-Y. Hong, H.-M. H. Juang, J. J. Katzfey, W. M. Lapenta, R. Laprise, P. Lopez, J. McGregor and J. O. Roads, 1999: Project to Intercompare Regional Climate Simulations (PIRCS): Description and initial results. J. Geophys. Res., 104, 19,443-19,462.</a>
</p>

<p>
<b>Relevant Reports by Co-PIs</b>
<br> <a href="Report.floodinformationworkshop.iowa.pdf" target="_blank"> <b> Anderson, C. J. </b> and D. Kluck, 2009:  Report from Scoping Workshop on Weather and Climate Information Needs for Emergency Response and Hazard Mitigation Planning - Summary.  18-19 February 2009.  Iowa City, IA.  20pp. </a>
<br><br> <a href="Corn&ClimateReport.pdf" target="_blank"> Great Plains Institute, 2008:  The Corn and Climate Report.  64pp. </a> 
<br> <a href="Indices.pdf" target="_blank"> <b> Hayes, M. J. </b>, 2006: Drought Indices. National Drought Mitigation Center.  11pp. </a>
<br><br> <a href="How.to.reduce.drought.risk.pdf" target="_blank"> <b>Knutson, C. </b>, <b>M. J. Hayes </b>, and T. Phillips, 1998: How to Reduce Drought Risk. Western Drought Coordination Council - Preparedness and Mitigation Working Group. 43pp. </a>
<br><br><a href="Basics_10step.pdf" target="_blank"> Wilhite, D. A., <b>M. J. Hayes</b>,<b> C. Knutson</b>, and K. H. Smith: The basics of drought planning: a 10-step process. National Drought Mitigation Center. 15pp.</a>
<br><br> <a href="UNEP White Paper final draft.pdf" target="_blank"> Munang, R., M. Rivington, <b> G. Takle </b>, B. Mackey, and J. Liu, 2009:  Climate information and capacity needs for ecosystem management under Changing Climate.  White Paper prepared for World Climate Conference - 3.  Geneva Switzerland, 31 Aug - 4 Sept 2009.  42 pp. </a>

</p>

<p>
<b>Links to Relevant Co-PI Webpages</b>
<br><a href="http://drought.unl.edu/droughtscape/droughtscapecurrent.htm" target="_blank">DroughtScape </a>
<br><a href="http://droughtreporter.unl.edu" target="_blank">Drought Impact Reporter</a>
<br><a href="http://drought.unl.edu/plan/plan.htm" target="_blank">Drought Planning Resources</a>
<br><a href="http://hdrweather.com" target="_blank">HDR Weather</a>
<br><a href=" http://php.indiana.edu/~spryor/Downscaling/overview.htm" target="_blank">Indiana University Empirically Downscaled Climate Projection Archive</a>
<br><a href="http://mesonet.agron.iastate.edu" target="_blank"> Iowa Environmental Mesonet</a>
<br><a href="http://climate.agron.iastate.edu" target="_blank">Iowa State University Climate Science Initiative</a>
<br><a href="http://rcmlab.agron.iastate.edu" target="_blank">Iowa State University Regional Climate Modeling Lab</a>
<br><a href="http://drought.unl.edu/dm/monitor.html" target="_blank">U. S. Drought Monitor</a>
<br><a href="http://drought.unl.edu" target="_blank">National Drought Mitigation Center</a>
<br><a href="http://www.ncdc.noaa.gov/oa/climate/monitoring/drought/nadm" target="_blank">North American Drought Monitor</a>
</p>

<?php include("$rootpath/include/footer.php"); ?>
