<?php 
  include("../../config/settings.inc.php"); 
  include("../../include/myview.php");
  $t = new MyView();

$t->title = "Squaw Creek Flood Modeling";

$t->content = <<<EOF

<p>Welcome to the Squaw Creek Flood Prediction System homepage.  This
website is currently under active development and links may change in 
the immediate future.</p>

<p>Currently, there are two tools available.</p>

<ul>
  <li><a href="storm/index.phtml">Storm Editor</a>
  <br />Create storm events for later use in the Model Runs. Requires
  authentication.</li>
  <li><a href="scenario/index.phtml">Scenario Editor</a>
  <br />Create storm scenarios that are tied to relative time of your
   model run.</li>
  <li><a href="model/index.phtml">Run Model</a>
  <br />Actually run the flood prediction model using the data entered
	via the Storm Editor.</li>
</ul> 

<h3>TODO List:</h3>
<ul>
  <li>Documentation on the website.</li>
  <li>The original model formulation had a code block that hard coded 
the recession curve after peak flow.  I am still investigating if this is
needed for the new version, since I do accounting a bit cleaner than the
old code.</li> 
</ul>

EOF;
$t->render('single.phtml');
?>