<HTML>
<HEAD>
	<TITLE>Mesonet Adminin</TITLE>
</HEAD>
<BODY>

<h3>Admin Commands:</h3>

<!--
<li><a href="/cgi-bin/admin/imageHelp/index.py">Edit Image Help Pages</a></li>
-->
<ul>
<li><a href="iem/add_news.phtml">Add a news item</a>
<li><a href="iem/add_site.phtml">Add a mesosite station...</a>
<li><a href="iem/props.phtml">IEM Properties Editor</a>
<li><a href="webcam/scheduler.phtml">Webcam Scheduler</a>
</ul>

</BODY>
</HTML>
