<HTML>
<HEAD>
<TITLE>Mesonet Adminin</TITLE>
</HEAD>
<BODY>

<h3>Admin Commands:</h3>

<ul>
	<li><a href="iemmaps.php">Add IEM Maps Entry</a></li>
	<li><a href="iem/add_news.phtml">Add a news item</a></li>
	<li><a href="iem/add_site.phtml">Add a mesosite station...</a></li>
	<li><a href="iem/props.phtml">IEM Properties Editor</a></li>
	<li><a href="webcam/scheduler.phtml">Webcam Scheduler</a></li>
</ul>

</BODY>
</HTML>
