name: Publish iemjs to npm

on:
  push:
    tags:
      - 'iemjs-v*'  # Triggers on tags like iemjs-v1.0.0, iemjs-v1.2.3, etc.

jobs:
  publish:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          registry-url: 'https://registry.npmjs.org'
          
      - name: Extract version from tag
        id: extract_version
        run: |
          # Extract version from tag (iemjs-v1.0.0 -> 1.0.0)
          VERSION=${GITHUB_REF#refs/tags/iemjs-v}
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "Publishing version: $VERSION"
          
      - name: Validate package
        run: |
          cd src/iemjs
          npm pack --dry-run
          
      - name: Run basic syntax check
        run: |
          cd src/iemjs
          node -c src/domUtils.js
          node -c src/iemdata.js
          node -c src/index.js
          
      - name: Publish to npm
        run: |
          cd src/iemjs
          npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          
      - name: Extract changelog for this version
        id: changelog
        run: |
          cd src/iemjs
          if [ -f "CHANGELOG.md" ]; then
            # Extract changelog section for this version
            VERSION=${{ steps.extract_version.outputs.version }}
            CHANGELOG_SECTION=$(sed -n "/## \[$VERSION\]/,/## \[/p" CHANGELOG.md | head -n -1)
            if [ -z "$CHANGELOG_SECTION" ]; then
              CHANGELOG_SECTION="See CHANGELOG.md for details."
            fi
            # Save to output, escaping newlines
            echo "content<<EOF" >> $GITHUB_OUTPUT
            echo "$CHANGELOG_SECTION" >> $GITHUB_OUTPUT
            echo "EOF" >> $GITHUB_OUTPUT
          else
            echo "content=No changelog available." >> $GITHUB_OUTPUT
          fi

      - name: Create GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: iemjs v${{ steps.extract_version.outputs.version }}
          body: |
            ## iemjs v${{ steps.extract_version.outputs.version }}
            
            Published to npm: https://www.npmjs.com/package/iemjs
            
            ### Changes
            ${{ steps.changelog.outputs.content }}
            
            ### Installation
            ```bash
            npm install iemjs@${{ steps.extract_version.outputs.version }}
            ```
          draft: false
          prerelease: false
